### ISSUE TITLE
Improve error message when trying to authenticate with twitter but twitter is misconfigured.

### ISSUE THREAD

**Issue by mlolson** [parse-community/parse-server#1573]
- [x] You've met the [prerequisites](https://github.com/ParsePlatform/parse-server/wiki/Parse-Server-Guide#prerequisites).
- [x] You're running the [latest version](https://github.com/ParsePlatform/parse-server/releases) of Parse Server.
- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-server/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.
#### Steps to reproduce

Using parse server, attempt to connect twitter oauth data

   POST /users  {"auth_data": { "twitter": { ... } } }

Result: 500 error
#### Logs/Trace

[Stack trace](https://gist.github.com/mlolson/25f4d7651a57b7b1fac0e83acb08ccde)

It looks like there may be a bug in this function [here](https://github.com/ParsePlatform/parse-server/blob/master/src/authDataManager/twitter.js#L7). 

I think OAuth should be instantiated with `authData`. I made this change and it fixed the issue.  `options` is always undefined when this function is called [here](https://github.com/ParsePlatform/parse-server/blob/master/src/RestWrite.js#L244).

Thanks!

**Comment by flovilmart** [comment]
Did you configure twitter on the server?

**Comment by mlolson** [comment]
I did not, whoops! That fixed the issue. Thanks!

**Comment by drew-gross** [comment]
We could probably provide a better error message here than just crashing the server.

**Comment by flovilmart** [comment]
I Was going to suggest the same :)

**Comment by montymxb** [comment]
If configuration is missing from the server #3676 added a more appropriate exception message.
