### ISSUE TITLE
Improve caching scheme to avoid extra queries to _Session

### ISSUE THREAD

**Issue by drew-gross** [parse-community/parse-server#1869]
Currently we cache session token -> user, so that we don't have to query _User on every request. But, when a user is modified, we have to clear the cache for every session token, and to do that, we have to query the _Session table: https://github.com/ParsePlatform/parse-server/pull/1844/files#diff-3646535e0655c134862bb00401c8097cR325

We should instead cache session token -> user id and user id -> user, then we can clear the cache when a user is updated without needing to query _Session.

**Comment by montymxb** [comment]
Closing as caching was merged in #2286
