### ISSUE TITLE
Slashes in filename should save file in the correct subfolder

### ISSUE THREAD

**Issue by davodesign84** [parse-community/parse-server#1963]
When saving a file prepending a subfolder to the filename, for instance 'folder/example.jpg' the api returns "{"error":"Unexpected token �"}".

It would be useful to save them in the correct subfolder to help manage them, for example when saving files for different classes.
### Steps to reproduce
1. Create a new file with a "/" in the filename
2. Save file
3. API returns a bad request
#### Expected Results

File is saved in the correct folder structure
#### Actual Outcome

API returns "{"error":"Unexpected token �"}"
### Environment Setup
- **Server**
  - parse-server version: 2.2.10
  - Operating System:     Mac OS and Linux
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Localhost and AWS (through EB)

**Comment by montymxb** [comment]
Closing this out as there hasn't been much of a push behind this. Using slashes to create a folder structure server-side doesn't really seem to be a useful feature, or a requested one at that. If some degree of organization was needed for files a naming convention could be used instead, using _'s, -'s, etc.

If there is still an interest in this however be sure to let us know and we'll reopen this to take a look.
