### ISSUE TITLE
Order by nested objects

### ISSUE THREAD

**Issue by codebreach** [parse-community/parse-server#2113]
I am skipping on the issue template because this is not a bug.

I have an object with a Pointer to User (named `creator`). I want to be able to order by the `full_name` field on `User`

Currently, if I do `order('creator.full_name')` i get the following error:

```
{"code":105,"error":"creator.full_name is not a valid order key"}
```

Would it be possible to implement this in parse-server? Would a PR be accepted for the same?

**Comment by mtrezza** [comment]
+1 for this, I cannot count the times I stumbled upon this caveat.

**Comment by JHHMobile** [comment]
Any updates for this?

**Comment by iwantooxxoox** [comment]
Looking for the feature too

**Comment by natanrolnik** [comment]
PRs are welcome @iwantooxxoox @JHHMobile @mtrezza @codebreach

**Comment by rooswelt** [comment]
Any workaround on this?

**Comment by iwantooxxoox** [comment]
@rooswelt 
My workaround is to add a middleware before ParseServer middleware, override res.send to get response body and do any kind of sorting that you want there.

example:
```javascript
app.use(YOUR_ENDPOINT, (req, res, next) => {
  res.sendResponse = res.send;
  res.send = (body) => {
    const bodyObj = JSON.parse(body);
    bodyObj.results.sort((a, b) => a.links[cnty].order - b.links[cnty].order);
    return res.sendResponse(JSON.stringify(bodyObj));
  };
  next();
});
app.use(MOUNT_PATH, parseServer);
```

**Comment by aacassandra** [comment]
any update? order column with pointer field in rest api?

**Comment by aacassandra** [comment]
how ordering pointer field with rst api? any example?
