### ISSUE TITLE
Transaction/Commit Support

### ISSUE THREAD

**Issue by mjgerace** [parse-community/parse-server#2159]
## **Feature Request**

For a while now, parse has lacked transaction/commit support. Due to upcoming Postgres support, transactions should be very easy to implement, and provides a much-needed way to secure many api requests in a row with adequate rollback.

No workarounds presented thus far have been nearly as efficient as ACID transactions. I think that if Parse wants to consider itself a top-tier open source package, it needs to have this feature for database integrity.

**Comment by joy4eg** [comment]
+1 (#2013)

**Comment by Beingbook** [comment]
Is there no alternative?

**Comment by vitaly-t** [comment]
Transactions are already used in [PostgresStorageAdapter.js](https://github.com/ParsePlatform/parse-server/blob/master/src/Adapters/Storage/Postgres/PostgresStorageAdapter.js), not sure how sufficient though.

**Comment by pewh** [comment]
Hey, what is the current status? Is there any example how to implement transaction/commit?

**Comment by vitaly-t** [comment]
@pewh As per my earlier message:

> Transactions are already used in [PostgresStorageAdapter.js](https://github.com/ParsePlatform/parse-server/blob/master/src/Adapters/Storage/Postgres/PostgresStorageAdapter.js), not sure how sufficient though.

Method `.tx` is used in 6 places there. Not sure how sufficient it is in general, as it requires to understand how the whole thing works, which is a lot.

**Comment by trylovetom** [comment]
I think mongodb need it, too

**Comment by pewh** [comment]
`.tx` is coming from `pg-promise` (https://github.com/parse-community/parse-server/blob/master/src/Adapters/Storage/Postgres/PostgresClient.js#L17). I guess we can make Parse support transaction/commit like this:
1. Convert `Parse.query` into pg-promise instance
2. Use batch like this https://github.com/parse-community/parse-server/blob/master/src/Adapters/Storage/Postgres/PostgresStorageAdapter.js#L546-L549

P.s: I'm newbie, so i don't know if it possible or not

**Comment by trylovetom** [comment]
@pewh I think we need any query or update function support transaction/commit.

**Comment by trylovetom** [comment]
@pewh Let's do it ?

**Comment by manjukas** [comment]
Is it possible to have transactions with mongo, as mongodb doesn't really support multi document transactions? 

Optimistic locking would be nice for Object class. Just need a integer type attribute, which gets incremented each time the object is saved. And save will fail if someone else has modified since the last read. This can be consistently implemented across Mongo and Postgres.

**Comment by flovilmart** [comment]
If you need a transactional RDBMS, you should not use MongoDB in the first place, and if you really need transactions, baking it into parse-server may prove painful and inefficient (i.e., you should probably not use parse-server if you intend to have a highly transactional system, I would personally not use it for that).

**Comment by heresmyinfo** [comment]
We have an application that is currently based on Parse, but needs the reliability of transactional support. When you say "painful and inefficient", are you referring to high-performance or difficulty in implementation? We're not as concerned with performance as reliability. If it's just performance you are referring to, how much effort do you think it would take to implement transactional logic now that we have switched to Postgres (which is working great)? Do you have anyone you can refer us to?

**Comment by charleskoehl** [comment]
We also have an application based on Parse. Recently, it became necessary to use transactions to support a ledger of user loyalty rewards points. We are considering these options:
1. Switch to Firebase and use its new database, "[Firestore](https://firebase.google.com/docs/firestore/)," (in beta; has documents organized into collections and supports multi-document transactions and batch writes), and "[Cloud Functions](https://firebase.google.com/docs/functions/)" (in beta; a cross between AWS Lambda and Parse Cloud Functions), which appears to duplicate many of the features of Parse
1. Ask the ParseServer maintainers to support transactions using [Fawn](https://github.com/e-oj/Fawn) or similar.

**Comment by flovilmart** [comment]
I’m always cautious about integrating 3rd party frameworks. 

While this is a great idea, stuffing more features into the main repository is perhaps something that will be costly in the long run. 

If we support transactions for mongo, then we’ll need the same level of support for Postgres.

I’m curious of what the REST interface would look like, where it would live, wether we support cross class transactions, wether we force id based identification of the affected documents etc... 

I’m not against evaluation, as I believe there’s some value in it. 

If the implementation is just a wrapper upon Fawn, then an adapter design is perhaps more suited. 

A priori, i’m Not against it as it’s a quite requested feature, i’d Be willing to help with the design of the feature, and discuss the interfaces, and help with SDK client implementations. 

Is it something that would be only available for the masterKey at first only exposed as a REST endpoint and possible to the JS SDK?

What do you think? 

Is it something you’d willing to invest some time in?

**Comment by charleskoehl** [comment]
Thanks for your thoughts.

I think an adapter pattern would be best to maintain independence from Fawn or any other specific implementation.

I think it should support cross-class transactions. It should be available only for the masterKey at first since I think a significant portion of transactions would modify data related to multiple users.

As I'm currently the sole developer (tech co-founder) of a startup with a quickly-approaching MVP deadline, I would only be able to invest time in the feature starting in 6 months or so.

**Comment by oallouch** [comment]
Ok to close this for now, even if it would be great to have this feature.

**Comment by gtzinos** [comment]
https://docs.mongodb.com/master/core/transactions/

**Comment by mjgerace** [comment]
Not to start this up again, but I thing given the fact that mongo is implementing transactions and that postgres support is fully fleshed should further the argument for transactions. Pretty much any and all applications that want to take themselves seriously and promote data integrity will utilize such a feature. It is crippling parse that there is no current support for this.

**Comment by acinader** [comment]
I think you mean: 'To start this up again'.  ;).

Do you have some ideas on how we might implement?  What SDK do you use primarily?

**Comment by acinader** [comment]
@flovilmart lays out some good questions for a starting point:

https://github.com/parse-community/parse-server/issues/2159#issuecomment-358489154

**Comment by mjgerace** [comment]
@acinader 

To begin to answer these questions, let me give my (somewhat) uneducated thoughts.

It's no longer required to use any third-party package or integration. [MongoDB supports transactions](https://www.mongodb.com/blog/post/mongodb-multi-document-acid-transactions-general-availability) as of 4.0 (I checked, it looks like we are already version compliant for this feature set). Postgres obviously [has supported](https://www.postgresql.org/docs/8.3/tutorial-transactions.html) such transactions for a while.

As for what the rest interface would look like, I don't know yet. I think that it would be prudent to begin with support on the expressjs side of things, building out the javascript client, as that is likely where most of your users reside. Specific design details have not been well thought out by me - I made this post over 3 years ago, and have not had a look at how parse-server is architected in recent days.

I will take a look and work on understanding where this could fit in, but no longer are third-party packages necessary. Feature parity between the two DBs is doable without any additional integration.

**Comment by davimacedo** [comment]
The JS SDK has a `Parse.Object.saveAll()` method that uses the Parse Server's `batch` endpoint. Maybe including support to a transactional saveAll() process would be a good starting point. What do you guys think?

**Comment by gtzinos** [comment]
Excellent idea @davimacedo

**Comment by davimacedo** [comment]
@gtzinos @mjgerace is this something that you guys would be willed to tackle?

**Comment by yuki-takeichi** [comment]
Another good starting point is supporting an atomic update operation including `addRelation` or `RemoveRelation` operators for REST API. A relation field has an independent MongoDB collection where each relation is stored separately. REST API can specify an update for an object itself and its relation in the same call as if its updates are atomic. Because these update queries are not in a transaction, there are possible inconsistent states a query that has `addRelation` or `RemoveRelation` operators poses when the operation fails in the middle.

Supporting atomic `saveAll()` is also a good idea, but I'm not sure that `saveAll()` ensures to call `/batch` API because of possible future changes. We might have to revise the spec for `saveAll()`, and I think this leads to a discussion for client SDK transaction interfaces. (For example, bringing a concept of Session or Transaction to Parse Server and its SDKs.)
