### ISSUE TITLE
Count on sharded mongodb cluster

### ISSUE THREAD

**Issue by benishak** [parse-community/parse-server#2161]
# Env
- AWS EC2 (CentOS+NGINX)
- MongoDB 3.0.11 on sharded cluster
# Problem/Reproduce

```
q.limit(10000);
q.find().then(
    function(tokens){
        console.log("Length -> " + tokens.length);
    }
);
---> 7062
q.count().then(
    function(tokens){
        console.log("Count -> " + tokens);
    }
);
----> 8233
```

https://docs.mongodb.com/manual/reference/method/db.collection.count/

> On a sharded cluster, db.collection.count() can result in an inaccurate count if orphaned documents exist or if a chunk migration is in progress.
> 
> To avoid these situations, on a sharded cluster, use the $group stage of the db.collection.aggregate() method to $sum the documents. For example, the following operation counts the documents in a collection:
# Possible solution

change the line here
https://github.com/benishak/parse-server/blob/master/src/Adapters/Storage/Mongo/MongoCollection.js#L44

to use 

`this._mongoCollection.aggregate([{ $group: { _id: null, count: { $sum: 1 } } }]);`
# code

```
    key: 'count',
    value: function count(query) {
      var _ref3 = arguments.length <= 1 || arguments[1] === undefined ? {} : arguments[1];

      var skip = _ref3.skip;
      var limit = _ref3.limit;
      var sort = _ref3.sort;
      var pipeline = [];

      pipeline.push({ $match : query });

      if (typeof skip === "number"){
        pipeline.push({ $skip : skip });
      }

      if ((typeof limit === "number") && (limit > 1)) {
        pipeline.push({ $limit : limit });
      }

      if(sort){
        pipeline.push({ $sort : sort });
      }

      pipeline.push({ $group: { _id: null, count: { $sum: 1 } } });

      return this._mongoCollection.aggregate(pipeline).toArray();
      //return this._mongoCollection.count(query, { skip: skip, limit: limit, sort: sort });
    }
```

this worked for me but it returns

something like this

`[ { _id: null, count: 4075 } ]`

**Comment by flovilmart** [comment]
What do you think @TylerBrock?

**Comment by TylerBrock** [comment]
I'm not quite sure this is something that should be solved at the parse-server level. You can always clean up the orphaned documents.

However, if we do something like this we should only do it for sharded clusters so that all the non-sharded clients can avoid the penalty of going through the aggregation framework.

The isMaster command returns {isdbgrid: true} when its connected to a mongos:  https://docs.mongodb.com/manual/reference/command/isMaster/#sharded-instances

**Comment by benishak** [comment]
The aggregation framework work for all cases. Another approach is to use `db.collection.find().length()` but i could be slow or use more memory

**Comment by TylerBrock** [comment]
Yes it works for all cases, but you pay a performance penalty going through the aggregation framework so count will be slower for the more common case (people not running a sharded cluster). I think it's better to implement both and choose which one to send to MongoDB based on the connection but yes this solution would work for both.
