### ISSUE TITLE
Limit the number of count operations

### ISSUE THREAD

**Issue by drorsun** [parse-community/parse-server#2268]
Today we pay a heavy latency penalty on Parse count operations.  We plan to remove them completely in future releases. 
However until all users upgrade it will take some time and we still suffer.

Is there a way to limit the number of count operations?
Alternatively is there a way to timeout an abort long running queries on mongodb?

**Comment by hramos** [comment]
We don't have a mechanism in place for this at this time.

**Comment by montymxb** [comment]
You can set a timeout in the configuration for your parse-server to prevent excessively long queries from causing significant overhead.
```
databaseOptions: {
    maxTimeMS: 1000
}
```
