### ISSUE TITLE
Disable anonymous file upload

### ISSUE THREAD

**Issue by staticdreams** [parse-community/parse-server#2484]
Describe your issue in as much detail as possible.

Similar to issue [#39](https://github.com/ParsePlatform/parse-server/issues/39) I'd like to be able to disable file upload via rest to all anonymous sources.
### Steps to reproduce

Please include a detailed list of steps that reproduce the issue. Include curl commands when applicable.

As suggested, client keys are no longer needed, so I'm just using master key and AppId.

Running something similar to this:

`curl -X POST -H "X-Parse-Application-Id: appId" -H "Content-Type: text/plain" -T "hello.txt" https://localhost/myApp/parse/files/hello.txt`

would upload a file without any problems. I don't want people uploading random stuff. How would I disable file upload (to anonymous sources) ?

**Comment by flovilmart** [comment]
While we don't support that right now, we welcome pull requests.

**Comment by montymxb** [comment]
Until someone puts up a PR for restrictions I'll be closing this out. This is the intended functionality and is how it was with the original parse.com api as well. If this is still an issue let us know and we'll pop this back open.
