### ISSUE TITLE
User changed by cloud function when queried from client side returns stale data.

### ISSUE THREAD

**Issue by pushparajsamant** [parse-community/parse-server#2614]
I am having the logged in user make some changes on itself. These changes happen in the cloud function called by the client code. THe cloud code executes correctly and returns back after which I query the user table to get the updated data but it gives back old data and the updated fields are missing.  Using the latest available parse-latest.js from CDN.

I have already tried sending the users session token in the save call and also the useMasterKey but no change in behaviour. 
### Steps to reproduce
1. Call a cloud function that changes a field for the currently logged in User
2. Once cloud function has completed and returned to client side query the user table to get latest data.
3. This data is stale data and does not include the latest data. 
#### Expected Results

Should get latest data.
#### Actual Outcome

Updated data is not returned.
### Environment Setup
- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.2.18 on Nodechef
  - Operating System:    Dont know
  - Hardware:             Dont know
  - Localhost or remote server? Nodechef 
- **Database**
  - MongoDB version: Dont know
  - Storage engine:  Dont know
  - Hardware:       Dont know
  - Localhost or remote server? Nodechef
### Logs/Trace

You can turn on additional logging by configuring VERBOSE=1 in your environment.

[FILL THIS OUT]

**Comment by flovilmart** [comment]
Can you provide some code snippet of what you're doing to make sure that's not an issue on your side?

**Comment by pushparajsamant** [comment]
Sure here it is.
This is the call to the cloud function which is inside a promise
```
Parse.Cloud.run("notification_update", params))
	.then(function(obj) {
		dfd.resolve(obj);
	}, function onError(err) {
		console.error(err)
		dfd.reject(err);
}
```
The relevant code in cloud function
```
currentUser.set("team", team);
console.log("Session token ");
console.log(currentUser.getSessionToken());
promises.push(currentUser.save(null, { sessionToken: currentUser.getSessionToken() }));
```

Once the cloud function returns I call this function. I check in the parse DB the data is updated.
```
var refresh = function onRefresh(dfd) {
      console.debug("Refresh user was triggered..");
     var currentUser = Parse.User.current();
     var q = new Parse.Query(Parse.User);
     q.include("team");
     q.get(currentUser.id)
     	.then(function success(user) {
		currentUser.set({
			team: user.get("team"),           //Here the data is not updated
		});
		if (dfd && dfd.resolve) {
			dfd.resolve(currentUser);
		}
	}, function onError(error) {
		if (dfd && dfd.reject) {
			dfd.reject(error);
		}
	});
}

```

**Comment by flovilmart** [comment]
how do you acquire the currentUser? through req.user? Parse.User.current() is not available in cloud code.

**Comment by pushparajsamant** [comment]
Yup I get the user from request.user. Thanks to one of your posts earlier I realized that. The problem here is not in that part of the code since the data gets updated perfectly without any issue. The problem is the calling client function is not able to get the latest updated data once the cloud function is over.

**Comment by flovilmart** [comment]
This is probably related to the caching occurring on the user to prevent too frequent DB calls.

**Comment by pushparajsamant** [comment]
So could this be related to Nodechef server or the client code. On the client side in the debug I see the correct updated date for the user object but the field I updated is not there.

**Comment by flovilmart** [comment]
Uhm... So to summarize if I understand well:

1. you call a cloud function that update the req.user
2. you see that this user is properly updated in the DB / dashboard
3. when fetching/getting the user, you're not able to get the latest values.

If you check the network call in the Chrome/Safari/Firefox debugger that fetches the user, does the property appear in the response payload?

Can you run parse-server with VERBOSE=1 as an environment variable so we have req/response traces?

**Comment by pushparajsamant** [comment]
Perfect . I will do that.

**Comment by flovilmart** [comment]
can you post screencaps/logs please?

**Comment by pushparajsamant** [comment]
Here are the caps.
<img width="959" alt="screen shot 2016-08-31 at 8 48 09 pm" src="https://cloud.githubusercontent.com/assets/8089002/18129715/8abf1120-6fbe-11e6-9099-bddc754257a5.png">
<img width="653" alt="screen shot 2016-08-31 at 8 49 46 pm" src="https://cloud.githubusercontent.com/assets/8089002/18129716/8af3f502-6fbe-11e6-85e2-a49e7c6429b8.png">

**Comment by flovilmart** [comment]
That completely is an issue with the JS SDK, can you please open on https://github.com/parseplatform/Parse-SDK-JS/issues. and reference that one from there?

Closing.

**Comment by pushparajsamant** [comment]
Hi,
I put the issue on parse javascript sdk around 1 and half week back and there has been no update on it since then. Could you please help me expedite this as its a major blocker for our code to migrated. We have several instances where a Lead user changes fields for other users.

**Comment by flovilmart** [comment]
I'll have a look some time. It also seems that the team pointer is returned with __type Object intsead of Pointer which is related to parse-server

**Comment by pushparajsamant** [comment]
I read in this issue https://github.com/ParsePlatform/Parse-SDK-JS/issues/323   that it can also be a parse server issue that its not sending an Op Deleted when a pointer is deleted so how do I check if this is the issue.
