### ISSUE TITLE
Parse server returning 400 Bad Request

### ISSUE THREAD

**Issue by techyrajeev** [parse-community/parse-server#2622]
Running a cloned repository from parse server example.

https://github.com/ParsePlatform/parse-server-example

When running locally parse-server it responds to rest calls successfully but when deployed to heroku sending rest call request causes server to send **400** bad request with no output on server logs even though VERBOSE flag is correctly set to 1 on heroku.

Rest calls are being sent from another server to parse-server.

Strange thing is that curl requests are working successfully.

```

curl -X GET \
  -H "X-Parse-Application-Id: <App-id>" \
  -H "X-Parse-REST-API-Key: <Rest Api-key>" \
  -G \
  --data-urlencode 'limit=1' \
  https://herokuapp.com/parse/classes/Demo
```

Server setup:

```
var api = new ParseServer({
  databaseURI: databaseUri || 'mongodb://localhost:27017/dev',
  cloud: process.env.CLOUD_CODE_MAIN || __dirname + '/cloud/main.js',
  appId: process.env.APP_ID || 'myAppId',
  masterKey: process.env.MASTER_KEY || '', //Add your master key here. Keep it secret!
  serverURL: process.env.SERVER_URL',  // Don't forget to change to https if needed
  liveQuery: {
    classNames: ["Posts", "Comments"] // List of classes to support for query subscriptions
  }
});
```

I tried setting  SERVER_URL to : 
1. http://localhost:1337/parse
2. http://herokuappname.com/parse
3. https://herokuappname.com/parse

but nothing worked. In all cases curl request worked successfully.

Also local server to server communication also worked successfully ( from localhost:port1 to localhost:port2 )

I don't know whether it is https issue or Cors issue. Please help.
### Steps to reproduce:

Deploy Parse-Server to Heroku. 

Deploy another express server on heroku.

Send rest api call to Parse-server from another server.
#### Expected Results

The code should run and data should be printed in log.
#### Actual Outcome

400 Bad Request. No rest call is being done. NO output on server.

Environment Setup

Server

 express: "^4.14.0",
  parse: "^1.9.1",
  parse-server: "^2.2.18"

Operating System: Mac Os
Hardware: MacBook Pro
Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Heroku
Database

MongoDB version: 3.0.12
Storage engine: AWS us-east-1
Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): mLab

**Comment by natanrolnik** [comment]
@techyrajeev I think you are using the wrong url in your `curl` call to your heroku app - it should be `https://<nameofmyapp>.herokuapp.com/parse`... Or are you just posting here without the name intentionally?

**Comment by techyrajeev** [comment]
Yes I know that url structure. I have intentionally hidden the app name.

**Comment by natanrolnik** [comment]
@techyrajeev wait, so curl to the server deployed on heroku fails or succeeds? Can you post the code that makes the HTTP call from your other express app?

**Comment by natanrolnik** [comment]
And also, would be good to look at `heroku logs` of both.

**Comment by techyrajeev** [comment]
Curl request is passed successfully. On parse server I  response generated and I see it on terminal from where curl request was sent.

**Comment by EyesiM** [comment]
I have the same problem in my projecct.After I delete the datas in my database on the dashboard,the parse server having been returning 400 bad request.I only use the example from the parse's website,but it always return the bad request.In addition,I didn't change my code and before I deleted my datas,I can change the data by my code successfully.Could you tell me how can you solve your problem?

**Comment by montymxb** [comment]
Closing as this doesn't appear to be an issue with parse-server itself and more an issue with connecting, additionally it's been some time and this hasn't been followed up on.
