### ISSUE TITLE
Transitioning the Project to the Community Governance by January 2017.

### ISSUE THREAD

**Issue by adonoho** [parse-community/parse-server#2630]
In just under 5 months, our friends at Facebook will, most likely, be withdrawing from the Parse project. Most community driven projects put in place some kind of governance structure. Some kind of mechanism for the community to define and set a platform's direction, to address systemic issues.

There are many ways this could be set up. The obviously simplest is a BDFL and a contribution agreement. There are many other forms of project governance. I, personally, am a big fan of the BDFL form.

How does the Parse Community want to govern itself? How will the Parse Community grow? 

Have no doubt, these decisions will be made. Unless something more formal emerges, a default view of a dying platform could be easily imputed. In that case, folks will, most likely, vote with their feet. That will, unfortunately, lead to the slow minimization of the platform. I doubt any of the folks working hard on this server want that result.

With just under 5 month remaining until this project is on its own, how will we steer Parse's future?

Anon,
Andrew

P.S. Who am I? Just a Parse Server user with a couple of apps. I've also made extremely modest contributions to the Parse iOS SDK.

**Comment by flovilmart** [comment]
It ain't dying, it's striving!

Regarding the contributors agreements, I'm currently picking some brains on that, looking at working models like Jekyll, homebrew and Moya which all have striving community and passionate maintainers.

Some pull requests will be made so we can all discuss those terms together.

**Comment by adonoho** [comment]
Allow me to be very clear, I want Parse Server ecosystem to grow too. That is why I ask these hard questions. Unless the community can come together and create a governance structure, then we do have a problem.

**Comment by adonoho** [comment]
@flovilmart I understand your view. The question is when will a governance structure be established? Are you waiting until January 2017? December 2016? November 2016? October 2016? Is there a reason to wait? If so, what, pray tell, is it?

You prefer drafts over specs. OK, here's a draft: I nominate you, a non-Facebook employee, as the BDFL for the Parse Platform. Effective immediately. Organize it how you wish. For example, who is primarily responsible for the Parse Server, iOS SDK, Android SDK, or JavaScript SDK on January 28, 2017? Is there a community effort to preserve the IoT stack? What is the relationship between the open source community and the community of competing vendors hosting Parse Server services? Will there be an effort to keep the stack coherent in the face of those competitive pressures? Or is everyone free to do their own thing, thus splitting the community?

While none of these questions are actually easy to answer and getting agreement amongst folks is quite hard, they do, IMO, need to be answered. In my experience, none of these decisions is made quickly. Some of them can be quite contentious.

Hence, I don't think you have much time and encourage you to start this open process soon.

Anon,
Andrew

**Comment by lastMove** [comment]
Interesting questions. Actually, Parse is a complex project with a lot of SDK to maintains. 
It would be great to have an Open, Governance quickly established. And It would be greater to have [Facebook](https://github.com/facebook) still involved in  maintaining/supporting and maybe governing this projet with the community. 
@nlutsenko @drew-gross  @gfosco what are the plans ? 
After Jan. 2017 will Facebook still support ParsePlatform's projects ?

**Comment by adonoho** [comment]
Gentlefolk,

We are now at T-9 days and counting till the Parse servers are shut down. Have we made any progress on identifying roles and responsibilities for various SDKs? For example, the iOS SDK, one of 3 I have an interest in seeing maintained, has open pull requests since May 29, 2016 and was last released by July 21st. Has someone volunteered to lead the maintenance of the iOS-OSX and Javascript SDKs? Each of these SDKs are complex and appear to need, based upon the number of pull requests, some attention.

Anon,
Andrew

**Comment by montymxb** [comment]
Closing this as we have most definitely passed the shutdown date... Development has since progressed, sdks have their respective leads, and parse continues as expected!
