### ISSUE TITLE
Logging in using Facebook and it sends email verification

### ISSUE THREAD

**Issue by sjabba** [parse-community/parse-server#2660]
My app hosted on NodeChef allows users to log in using Facebook through Parse however it sends a verification email with a link that does not work. Firstly, it should not be sending a verification email as they have logged in using Facebook. Can you please explain why this happens?
- **Server**
  NodeChef
- **Database**
  MongoDB on NodeChef

**Comment by flovilmart** [comment]
That looks like a bug, is the email field set on your user?

**Comment by sjabba** [comment]
Hi, yes, the email field is set because I retrieve the email from Facebook and save it into that field when the user first logs on using Facebook option.

**Comment by flovilmart** [comment]
I'll have a look

**Comment by sjabba** [comment]
Hi, any luck so far with this issue? Thanks.

**Comment by flovilmart** [comment]
Nope, I didn't get the chance to look at it or fix it. You can submit a pull request with the fix if that's a pressing matter

**Comment by sjabba** [comment]
Hi, unfortunately, I don't have the expertise to fix the issue. It's not a pressing matter but rather something that should be fixed when possible. Thanks.

**Comment by tonycph** [comment]
I got this issue too

**Comment by kkgelu** [comment]
Seems it sends two emails each time when logged in with Facebook. The emailVerified filed is set to true when the link the later verification email is clicked. When logout, the emailVerified remains true. Login again, the emailVerified is set to false again, and emails are sent again.

**Comment by zirinisp** [comment]
I get something similar. I get one email every time I open the application. To be precise not every time, only if app opens are an hour apart.

**Comment by zirinisp** [comment]
Actually that was my mistake I was updating the user every time that app was restarting with new data from Facebook without checking out if the data are the same.

**Comment by eXhausted** [comment]
Same issue for 2.3.6

**Comment by flovilmart** [comment]
This was never fixed.

**Comment by ferrinho** [comment]
I have a similar issue/question. I want to avoid email confirmation when users logs in with facebook, since facebook already verified their email. Is there a way to achieve this?

**Comment by themoonlitknight** [comment]
Please can you estimate a date for the fix? I need to evaluate if I have to find a workaround. Thank you very much!

**Comment by Neilpoulin** [comment]
Does anyone know if we can set the user's "emailVerified" flag to "true" if they log in with oauth?

**Comment by madsb** [comment]
I'm authenticating with Account Kit (mobile phone), and I think this fix inadvertently makes it impossible to verify the email that the user enters manually.

I've currently hacked it by changing line 459 in RestWrite.js to:

`if (!_this8.data.authData || !Object.keys(_this8.data.authData).length || Object.keys(_this8.data.authData).length === 1 && (Object.keys(_this8.data.authData)[0] === 'anonymous' || Object.keys(_this8.data.authData)[0] === 'accountkit')) {`

... but it's not exactly beautiful.

**Comment by flovilmart** [comment]
We should probably add a method on the auth adapters as originally, someone who used the Facebook login didn’t want email verification to be sent. We probably need to check if the password is set alongside the email to trigger the verification and remove that ‘not so sexy’ logic. 

What do you think?

**Comment by flovilmart** [comment]
@madsb can you open a new issue so we can keep track of the problem as this original one has been closed! (and you actually want a different behaviour, the opposite one).
