### ISSUE TITLE
Query a nested array of objects with pointers

### ISSUE THREAD

**Issue by oallouch** [parse-community/parse-server#2709]
Hi,
I'd like to know if there's a clean way of doing this kind of query.
Example data: the Sale collection

```
{
    furniture: [
        {
            table: {
                __type: "Pointer",
                className: "Table",
                objectId: "1234"
            },
            count: 10
        },
        {
            table: {
                __type: "Pointer",
                className: "Table",
                objectId: "5678"
            },
            count: 5
        }
    ]
}
```

I'd like to find all sales with the table "1234".

Doing this doesn't work:
  query.equalTo("furniture.table", table);

But this works:
  query.equalTo("furniture.table.objectId", table.id);

Is there an official way of doing it. I'm just tricking MangoTransform.
In the non-working example, MangoTransform generates { "furniture.table": "Table$1234" } for this condition.

Thx a lot in advances.

Olivier Allouch
www.illicotravel.com

**Comment by flovilmart** [comment]
Was it working like that on parse.com? If so, that's a bug that should probably be fixed :)

**Comment by hramos** [comment]
No, this was not allowed in hosted Parse.com apps.
