### ISSUE TITLE
Querying User with parameter like email or username gives error invalid field name: _email_verify_token_expires_at

### ISSUE THREAD

**Issue by techyrajeev** [parse-community/parse-server#2767]
Every time when I sent query to fetch user created via oauth e.g google or facebook. 
I get this error while fetching user
`invalid field name: _email_verify_token_expires_at`

and corresponding error code is

errorCode: 105

**Comment by haydenbleasel** [comment]
Yep I get a similar thing on the Parse Dashboard:

```
POST https://api.parse.com/1/classes/_User 400 (Bad Request)            dashboard.bundle.js:46
```

```
{"code":105,"error":"invalid field name: _failed_login_count"}
```

"Failed login count" and "email verify token expires at" both occur.

**Comment by techyrajeev** [comment]
These fields seems to be hidden fields. Even after lots of debugging I don't have any hints about their origin.

**Comment by haydenbleasel** [comment]
@flovilmart Sorry to pull you on to this mate but this is seriously affecting things on production apps :S

**Comment by flovilmart** [comment]
@haydenbleasel in that case, you should probalbly downgrade to an earlier version while a fix is being implemented, or isolate the error and propose a fix.

**Comment by techyrajeev** [comment]
I just wanted to inform that I have fixed it on my side. It is not a valid fix but I urgently needed to fix the issue since in my case it was occuring in production. 
I had disabled email verification on self hosted server and after that it was working. 
May be it could be helpful to find out the actual problem.

**Comment by vkeepe** [comment]
In my case disable did not help. I had to delete the field in mongodb to get it to work. This is the query I used and found my records. Went into records and deleted the field _email_verify_token_expires_at.

{
    "_email_verify_token_expires_at": {
        "$exists": true
    }
}

**Comment by vkeepe** [comment]
If you have set this up "emailVerifyTokenValidityDuration". Remove it and see if this does any difference.

**Comment by flovilmart** [comment]
@vkeepe @techyrajeev @haydenbleasel did any of the things suggested here help? @cherukumilli any idea?

**Comment by haydenbleasel** [comment]
@flovilmart Commenting out Parse Server's `emailVerifyTokenValidityDuration` and `accountLockout` properties allows me to see the User table in Parse Dashboard locally, but not on Parse.com. But then again, it means disabling two features.

**Comment by flovilmart** [comment]
Yes and that makes sense, if you choose to opt-in for those features you have to stop using the dashboard, and use parse-dashboard instead. If those features are causing issues in parse-dashboard, please open on the dashboard repository.

**Comment by flovilmart** [comment]
@techyrajeev are you using dashboard.parse.com and experiencing those issues? If yes, you should use the parse-dashboard instead. 

Those features are not compatible with parse.com and will never be.

**Comment by techyrajeev** [comment]
@flovilmart No I was facing this issue in code. By the way I am using self hosted parse dashboard not dashboard.parse.com.

**Comment by flovilmart** [comment]
Can you provide the request/response logs when using running with VERBOSE=1?

**Comment by zirinisp** [comment]
Any news as I am getting the above also. Removing emailVerifyTokenValidityDuration did not help

**Comment by flovilmart** [comment]
Closing as this issue fell off the cracks, please reopen if necessary with relevant informations
