### ISSUE TITLE
I18n support for emails

### ISSUE THREAD

**Issue by Hitabis** [parse-community/parse-server#2886]
At the moment all emails to the user are hardcoded in _src/Controllers/UserController.js_.

Has anyone a fork supporting other languages?
Are there any plans to implenent I18n in emails and html-files?

**Comment by natanrolnik** [comment]
That's actually a good idea for a first PR, @Hitabis

**Comment by agent3bood** [comment]
Email adapter like mailgun have templates, cant you just add the language there?

**Comment by Hitabis** [comment]
@agent3bood the goal would be to have multiple languages. You could detect the language in the useragent for the html pages. It would be harder within the mails. But we always save the language in the installation.

**Comment by agent3bood** [comment]
@hitabis does parse currently save the user language ? 
If not that has to be added to the api first. 
I imagine a possible solution to be 
1. Add api to set the user language , so we can use during registrations or what ever. 
2. On sending email get the language and send the appropriate email text to the user.

**Comment by johnnydimas** [comment]
We were able to accomplish this with express middleware and using different email templates.

First we intercept the request:
`app.use('/verify_email_success', _VerifyEmailSuccessRouter);`

Then we get the user object and check their locale (our application saves locales), and then respond with the appropriate language template.

Hope that helps!

**Comment by mtrezza** [comment]
Email localization can now easily be accomplished with the [Parse Server API Mail Adapter](https://www.npmjs.com/package/parse-server-api-mail-adapter).

The adapter is still new, if you have any feedback for improvement or encounter any bugs, please file an issue.
