### ISSUE TITLE
Login/Signup error with 'Cannot modify readonly attribute: sessionToken' (Session afterSave issue)

### ISSUE THREAD

**Issue by apersaud** [parse-community/parse-server#2952]
### Issue Description

Describe your issue in as much detail as possible.

When registering or logging in a User, the server crashes with `Error: Cannot modify readonly attribute: sessionToken`, whenever an afterSave webhook for the '_Session' class is registered.
### Steps to reproduce

Please include a detailed list of steps that reproduce the issue. Include curl commands when applicable.
1. Setup parse-server and mongodb-runner as described in https://github.com/ParsePlatform/parse-server .

``` bash
$ npm install -g parse-server mongodb-runner
$ mongodb-runner start
$ parse-server --appId test --masterKey test --verbose true
appId: test
masterKey: ***REDACTED***
port: 1337
mountPath: /parse
maxUploadSize: 20mb
verbose: true
serverURL: http://localhost:1337/parse
[66728] parse-server running on http://localhost:1337/parse
```
1. We have setup a sample application to help reproduce the issue @ https://github.com/modernistik/parse-server-bug-report . This uses a ruby gem [Parse-Stack](https://github.com/modernistik/parse-stack) which is fully compliant with the Parse protocol spec. Clone the repository and run a rake task to register an afterSave webhook with the parse-server (from above) for the `_Session` class.

Download: [parse-server-bug-report-master.zip](https://github.com/ParsePlatform/parse-server/files/697713/parse-server-bug-report-master.zip)

``` bash
$ cd parse-server-bug-report
$ bundle install
$ rake parse:webhooks:register
Registering Parse Webhooks @ https://localhost:3000
[+] afterSave    - _Session
```
1. Make a API request to signup a new user with username 'john' and password 'test'

``` bash
 $ curl -X POST \
  -H "X-Parse-Application-Id: test" \
  -H "X-Parse-REST-API-Key: test" \
  -H "X-Parse-Revocable-Session: 1" \
  -H "Content-Type: application/json" \
  -d '{"username":"john","password":"test"}' \
  http://localhost:1337/parse/users
```
#### Expected Results

The server should properly call the afterSave webhook for Session class, and return a server  response with 201 and the payload response for the request:

```
verbose: RESPONSE from [POST] /parse/users: {
  "status": 201,
  "response": {
    "objectId": "yGfDOwCdsd",
    "createdAt": "2016-10-27T20:36:17.448Z",
    "sessionToken": "r:920eb51baea2c4acd1e357a751497a6c"
  },
  "location": "http://localhost:1337/parse/users/yGfDOwCdsd"
} status=201, objectId=yGfDOwCdsd, createdAt=2016-10-27T20:36:17.448Z, sessionToken=r:920eb51baea2c4acd1e357a751497a6c, location=http://localhost:1337/parse/users/yGfDOwCdsd
```
#### Actual Outcome

The user is signed up, but an HTTP 500 is returned due to the server crashing with the
parse-server console stating: `error: Error generating response. Error: Cannot modify readonly attribute: sessionToken`. In addition, the afterSave Session webhook is never sent. 

Note that if you are following the example above, you can unregister the `afterSave` `_Session` webhook by running:

``` bash
$ rake parse:webhooks:remove
[-] afterSave    - _Session
$ # signup the user
$ curl -X POST \
  -H "X-Parse-Application-Id: test" \
  -H "X-Parse-REST-API-Key: test" \
  -H "X-Parse-Revocable-Session: 1" \
  -H "Content-Type: application/json" \
  -d '{"username":"john2","password":"test"}' \
  http://localhost:1337/parse/users
```
### Additional Information

We figured out that the issue is related to when a user is being logged in or is signing up, a new Session record is created which also goes through the lifecycle of running after triggers in [RestWrite.js - line 903](https://github.com/ParsePlatform/parse-server/blob/86f35014f4795e0b265fb77d5d3e4896c8f61eba/src/RestWrite.js#L903). This section tries to get any changes to the newly created Session instance and applies them to the original object (`updatedObject.set(this.sanitizedData());`), which cannot be done since the `sessionToken` field is marked readonly.

Also, this does not happen using the hosted Parse service.
#### Workaround

The work around is to disable any afterSave webhooks for the _Session class, since doing so allows the codepath to short circuit to [RestWrite - line 885](https://github.com/ParsePlatform/parse-server/blob/86f35014f4795e0b265fb77d5d3e4896c8f61eba/src/RestWrite.js#L885) and return a resolved promise.
### Environment Setup
- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.2.23,
  - Operating System:     OSX El Capitan
  - Hardware:             Mac Pro
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): localhost
- **Database**
  - MongoDB version: 3.2.8 (using mongodb-runner)
  - Storage engine:  WiredTiger
  - Hardware:        MacBook Pro
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): localhost
### Logs/Trace

You can turn on additional logging by configuring VERBOSE=1 in your environment.

```
verbose: REQUEST for [POST] /parse/users: {
  "username": "john",
  "password": "********"
} method=POST, url=/parse/users, host=localhost:1337, user-agent=curl/7.49.1, accept=*/*, x-parse-application-id=test, x-parse-rest-api-key=test, x-parse-revocable-session=1, content-type=application/json, content-length=37, username=john, password=********
error: Error generating response. Error: Cannot modify readonly attribute: sessionToken
    at ParseSession.ParseObject.value (/usr/local/lib/node_modules/parse-server/node_modules/parse/lib/node/ParseObject.js:733:17)
    at RestWrite.runAfterTrigger (/usr/local/lib/node_modules/parse-server/lib/RestWrite.js:880:17)
    at /usr/local/lib/node_modules/parse-server/lib/RestWrite.js:107:18
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
error: Uncaught internal server error. Error: Cannot modify readonly attribute: sessionToken
    at ParseSession.ParseObject.value (/usr/local/lib/node_modules/parse-server/node_modules/parse/lib/node/ParseObject.js:733:17)
    at RestWrite.runAfterTrigger (/usr/local/lib/node_modules/parse-server/lib/RestWrite.js:880:17)
    at /usr/local/lib/node_modules/parse-server/lib/RestWrite.js:107:18
    at process._tickDomainCallback (internal/process/next_tick.js:129:7) Error: Cannot modify readonly attribute: sessionToken
    at ParseSession.ParseObject.value (/usr/local/lib/node_modules/parse-server/node_modules/parse/lib/node/ParseObject.js:733:17)
    at RestWrite.runAfterTrigger (/usr/local/lib/node_modules/parse-server/lib/RestWrite.js:880:17)
    at /usr/local/lib/node_modules/parse-server/lib/RestWrite.js:107:18
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
Error: Cannot modify readonly attribute: sessionToken
    at ParseSession.ParseObject.value (/usr/local/lib/node_modules/parse-server/node_modules/parse/lib/node/ParseObject.js:733:17)
    at RestWrite.runAfterTrigger (/usr/local/lib/node_modules/parse-server/lib/RestWrite.js:880:17)
    at /usr/local/lib/node_modules/parse-server/lib/RestWrite.js:107:18
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
```

Also tracking: https://github.com/modernistik/parse-stack/issues/18

**Comment by flovilmart** [comment]
I'll have a look! Thanks for the detailed report!

**Comment by apersaud** [comment]
Hello, any updates on this and do you still need to the bug-report example we provided? Thanks.

**Comment by apersaud** [comment]
Adding the example code here and above. This issue is still present and does not allow setting up an afterSave hook on the '_Session' class.
[parse-server-bug-report-master.zip](https://github.com/ParsePlatform/parse-server/files/697708/parse-server-bug-report-master.zip)

**Comment by code-bash** [comment]
Any update?

**Comment by flovilmart** [comment]
Didn't get a chance to look at it, I'd have to dig deeper or you can probably provide a PR or a failing test to start with (through a PR) so we can have a good grasp of the different options for the fix.

**Comment by flovilmart** [comment]
Triggers on _Session should not be allowed in the 1st place (https://github.com/parse-community/parse-server/blob/master/src/cloud-code/Parse.Cloud.js#L7), closing, I'll open an issue to prevent trigger registration through the web hooks API.
