### ISSUE TITLE
Thoughts on auth providers errors

### ISSUE THREAD

**Issue by natario1** [parse-community/parse-server#3017]
As far as I can see, currently auth providers in `src/authDataManager` serve as validators for input auth data. The validation occurs in RestWrite.js, that should be, when the user performs a create or update call.

- The current implementation fails if _any_ of linked providers validation fails. What’s the reason behind this design? Why should the action fail if my Facebook token expired, if I am successfully authenticated with Twitter and Instagram?

- I can see that a possible answer is to notify the client that a certain provider’s token has expired. But, correct me if I am wrong, right now it is very hard for the client to understand what’s going on. [We are returning](https://github.com/ParsePlatform/parse-server/blob/master/src/authDataManager/facebook.js#L13) a `Parse.Error.OBJECT_NOT_FOUND`, that says nothing. The only option as now is to look for `Parse.Error.OBJECT_NOT_FOUND`, and parse the message for the pattern `<provider-name> auth is invalid for this user.`. But even that is not easy, as <provider-name> is not consistent with provider names you set in the ParseServer constructor (the word is capitalised, sometimes [shortened](https://github.com/ParsePlatform/parse-server/blob/master/src/authDataManager/vkontakte.js#L17)...). And we need the exact provider name to ask the client to refresh that provider token. Right?

Possible solutions:

1. (best IMO) introduce a new `Parse.Error` constant, and pass the exact provider name in the message. It would be a breaking change, but the more we wait, the more breaking it gets.

2. (fast) leave OBJECT_NOT_FOUND, but at least make provider names consistent with the name of the js file / the name of the authData child object.

3. (nice) Create somewhere a `validate` endpoint, that wraps validators and returns an array of invalid authData providers. This way clients can call `validate` at app startup without waiting for a RestWrite call to fail.

4. (dirty) wrap myself the validators and pass their functions in the ParseServer constructor, so that I can return the error I want. 

I don’t know if you also see this as a problem, but I wanted to share. I’m not confident with the library so I might have missed something.

**Comment by flovilmart** [comment]
> The current implementation fails if any of linked providers validation fails

It should only fail if you provide authData part of your request. I believe the client SDK's are designed to only send the AuthData on particular occasions (link, login). Upon linking only the new authData should be provided. If you provide an authData object with multiple providers in and some data is outdated, then it makes sense that fails because, well the authData is invalid.

Can you provide an example of those claims??

**Comment by natario1** [comment]
> It should only fail if you provide authData part of your request. I believe the client SDK's are designed to only send the AuthData on particular occasions (link, login).

@flovilmart I didn’t know. I have not encountered these errors yet, I made up this idea by just looking at the source here at parse-server. If authData is sent only when necessary, then OK, this validation is going to happen rarely. 

But don’t you think the error messages should make it easier to understand what happened, and which provider token has expired?

By the way, if validation occurs only on these special actions, I would like even more a `validate` endpoint, to understand which of the current tokens are invalid, and refresh them before any request fails.

**Comment by dewhacker** [comment]
@natario1 we have a similar problem, Facebook access tokens expire by default in 60 days.  Once they do the user can no longer save any properties their _User object to no fault of their own. It's a terrible user experience to force the user to login/logout every 60 days. The Facebook auth adapter will call [validateAuthData](https://github.com/ParsePlatform/parse-server/blob/master/src/Adapters/Auth/facebook.js) every RestWrite.execute(), and fail on an expired FB token.  You can extend the the token via Facebook API, but there isn't a clear way to manually update the _User.authData with the long-life token. 

Have you found a clean work around?

**Comment by kelset** [comment]
Hey, @dewhacker have you found a way to refresh the access token "cleanly"?
I'm sort of facing the same issue: from time to time I need to handle expired/invalid tokens but it looks to me that there are no methods to refresh/get new ones without forcing the user to re-login.

**Comment by natario1** [comment]
@kelset what do you mean? Assuming you are talking about Facebook tokens, this is Facebook policy - when it expires, the user must login again to your app.

As for updating auth data, it can be accessed as any other key:

```
const insertAuth = (user, name, authData) => {
    let fullAuthData = user.get('authData') || {};
    fullAuthData[name] = authData;
    user.set('authData', fullAuthData);
    return user.save(null, { sessionToken: user.getSessionToken() });
};
```

**Comment by kelset** [comment]
@natario1 Oh snap I completely missed that policy, sorry about that (I also found [this](http://stackoverflow.com/questions/30128167/facebook-when-does-the-sdk-refresh-the-auth-token) longer explanation if anyone will ever need).
