### ISSUE TITLE
Cloud job response missing buffer

### ISSUE THREAD

**Issue by cyrixmorten** [parse-community/parse-server#3023]
### Issue Description

Buffer data in response of cloud job request is empty. 

I have a job that generates pdf or reads existing pdf if already generated.

The essential code for this issue boils down to this:

```
Parse.Cloud.define("reportToPDF", function (request, response) {
    Parse.Cloud.httpRequest({
            method: 'GET',
            url: urlToSomePDF,
            headers: {
                'Content-Type': 'application/pdf'
            }
    }).then(function(res) {
        response.success(res);
    });
}
```

### Steps to reproduce

Calling the cloud job above from within another cloud job e.g `Parse.Cloud.run('reportToPDF')`

#### Expected Results

```
{
     status: 200,
     headers: 
      { 
          ...
          'content-type': 'application/pdf',
          ...
     },
     buffer: <Buffer 25 50 44 46 2d 31 2e 33 0a 25 ff ff ff ff 0a 37 20 30 20 6f 62 6a 0a 3c 3c 0a 2f 54 79 70 65 20 2f 45 78 74 47 53 74 61 74 65 0a 2f 63 61 20 31 0a 3e ... >
}
```

Which is the result of the `Parse.Cloud.httpRequest` that is being sent via `response.success(res)`

#### Actual Outcome

```
{ 
     status: 200,
     headers: 
     headers: 
      { 
          ...
          'content-type': 'application/pdf',
          ...
     },
     buffer: { type: 'Buffer', data: [] },
     text: '%PDF-1.3\n%����\n7 0 obj\n<<\n/Ty ... '
}
```

### Environment Setup

- **Server**
  - parse-server version: 2.2.25-beta.1
  - Operating System:     MacOS Sierra
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Localhost and Heroku

- **Database**
  - MongoDB version: 3.2.10
  - Storage engine:  MMAPv1
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): mLab

### Workaround

Simply export the functionality of the cloud code individually and call it directly instead of through cloud job.

Though the workaround is simple, the result of calling the cloud code differs from that of parse.com and narrowing the issue down took quite some time for me. 

In case the behaviour is intentional, it may be worth noting somewhere as a breaking change w.r.t. parse.com cloud code.

**Comment by Vetnametz** [comment]
have the same issue
I am creating pdf file on server side and I want transfer it to frontend but get same behavior

**Comment by flovilmart** [comment]
The result of a cloud function is not supposed to be a buffer but text or a plain JSON object. You should unpack the buffer and send it as a text response, or use the text property that is returned.
