### ISSUE TITLE
PFFile support for 'creating' a file that already exists w/ URL to GCS or S3 bucket

### ISSUE THREAD

**Issue by MobileVet** [parse-community/parse-server#3056]
_API Enhancement:_ **PFFile**

Ran into a situation where we are generating a PDF in our GCS bucket using an external (non-node) process.  We have a callback to our Parse Cloud Code to store the resulting file reference inside one of our custom objects.  As it turns out, PFFile constructor doesn't support creating a file with a FileAdapter File nor a URL to a known file in our bucket.

Ideally **PFFile** would be expanded to allow for construction based on either
1) Reference to a File in our bucket
2) Known URL

**Comment by flovilmart** [comment]
I'm wondering, I don'T believe there's anything that prevents you to set a custom ParseFile, also it seems that it's just a client SDK limitation, not a server one.
