### ISSUE TITLE
Setting customPage's choosePassword breaks password resetting

### ISSUE THREAD

**Issue by AmrKafina** [parse-community/parse-server#3075]
### Issue Description

Setting a custom page for the choose_password file results in a "Cannot post" error. Not sure if this is a misconfiguration on my part (I'm still very new to javascript), but I've been trying to get this to work for the past couple of hours and haven't gotten anywhere. Setting choosePassword back to "undefined" works correctly.

### Steps to reproduce
1. Setting the customPages paramater in index.js:
```
customPages: {
    invalidLink: '/public/invalid_link.html',
    verifyEmailSuccess: '/public/verify_email_success.html',
    choosePassword: '/public/choose_password.html',
    passwordResetSuccess: '/public/password_reset_success.html'
  }
```

2. Attempting to reset the password by opening the reset link from the sent email correctly redirects to the choose_password file, but submitting the form results in an error:

`Cannot POST /public/choose_password.html?token=myToken&id=myAppId&username=myUsername&app=myApp`

### Environment Setup

- **Server**
  - parse-server version: 2.2.24
  - Operating System:     OSX
  - Hardware:             macbook pro 
  - Localhost or remote server?: parse-server-example  running on heroku

- **Database**
  - MongoDB version: 3.0
  - Localhost or remote server? mLab addon on heroku app

### Logs/Trace

Here's the relevant log message:

`at=info method=POST path="/public/choose_password.html?token=myToken&id=myAppId&username=myUsername&app=myApp" host=api.my-domain.com request_id=535e8e5e-8345-40b9-8713-705925bbbb58 fwd="5.245.175.133" dyno=web.1 connect=1ms service=7ms status=404 bytes=347`

**Comment by gowridev** [comment]
@flovilmart  i got error in custom_page " no object found" when new password is entered.
![screen shot 2016-12-08 at 4 27 29 pm](https://cloud.githubusercontent.com/assets/17825008/21007490/21db2822-bd63-11e6-92cb-53b26db78a2a.png)
 please guide me how to resolve it

**Comment by sureshkoduri** [comment]
@AmrKafina , I think the issue with the PARSE_SERVER_URL in choose_password.html. change it with your server url then it will work.

**Comment by acinader** [comment]
this works for me and is almost two years old.  closing.  I can see that the /parse is missing in the above, so it looks like config issue.
