### ISSUE TITLE
Arrays sometimes set to null instead of undefined

### ISSUE THREAD

**Issue by miracle7** [parse-community/parse-server#3092]
For some reason arrays occasionally get set to null instead of undefined, which prevents me from adding elements to them when I am ready to (using AddUniqueToList in the dot net sdk in a mobile app for iOS and Android).

Have updated to 2.2.24 but since it happens so rarely I don't know whether it has been fixed or not.

I have not found a reliable way to reproduce this, so not sure exactly what is happening, so wondering if someone could point me in the right direction as to what kind of things could cause this. I am using the dot net sdk with Unity if that helps at all.

Failing that, if there is some way I can validate the data on array columns to never be null that would work too.

![image](https://cloud.githubusercontent.com/assets/5317556/20505527/dd18028c-b0a1-11e6-9461-67080dabf121.png)

### Steps to reproduce

I have been unable to reliably reproduce this as of yet, seems to happen pretty randomly on my array columns.

#### Expected Results

Arrays should be undefined unless explicitly assigned as null.

#### Actual Outcome

Undefined arrays occasionally become 'null' instead, which prevents adding new values.

### Environment Setup
- **Server**
  - parse-server version: 2.2.24
  - Heroku
  - 2 Standard-2x Dynos (web)
  - 1 Standard-1x Dyno (worker)

- **Database**
  - MongoDB version: 2.1.18
  - mLab
  - Dedicated Cluster M1

### Logs/Trace

```Nov 21 06:00:33 torque-prod app/web.1:  error: Uncaught internal server error. { [MongoError: exception: Cannot apply $addToSet to a non-array field. Field named 'qualifierViewers' has a non-array type NULL in the document _id: "OItGDBjDKC"] 
Nov 21 06:00:33 torque-prod app/web.1:    message: 'exception: Cannot apply $addToSet to a non-array field. Field named \'qualifierViewers\' has a non-array type NULL in the document _id: "OItGDBjDKC"', 
Nov 21 06:00:33 torque-prod app/web.1:    errmsg: 'exception: Cannot apply $addToSet to a non-array field. Field named \'qualifierViewers\' has a non-array type NULL in the document _id: "OItGDBjDKC"', 
Nov 21 06:00:33 torque-prod app/web.1:    ok: 0 } MongoError: exception: Cannot apply $addToSet to a non-array field. Field named 'qualifierViewers' has a non-array type NULL in the document _id: "OItGDBjDKC" 
Nov 21 06:00:33 torque-prod app/web.1:      at null.messageHandler (/app/node_modules/parse-server/node_modules/mongodb-core/lib/connection/pool.js:444:5) 
Nov 21 06:00:33 torque-prod app/web.1:  MongoError: exception: Cannot apply $addToSet to a non-array field. Field named 'qualifierViewers' has a non-array type NULL in the document _id: "OItGDBjDKC" 
Nov 21 06:00:33 torque-prod app/web.1:      at null.messageHandler (/app/node_modules/parse-server/node_modules/mongodb-core/lib/connection/pool.js:444:5) 
Nov 21 06:11:46 torque-prod app/web.1:  error: Error generating response. { [MongoError: exception: Cannot apply $addToSet to a non-array field. Field named 'finalResultsFetchedBy' has a non-array type NULL in the document _id: "JPjbHe9x7A"] 
Nov 21 06:11:46 torque-prod app/web.1:    message: 'exception: Cannot apply $addToSet to a non-array field. Field named \'finalResultsFetchedBy\' has a non-array type NULL in the document _id: "JPjbHe9x7A"', 
Nov 21 06:11:46 torque-prod app/web.1:    errmsg: 'exception: Cannot apply $addToSet to a non-array field. Field named \'finalResultsFetchedBy\' has a non-array type NULL in the document _id: "JPjbHe9x7A"', 
Nov 21 06:11:46 torque-prod app/web.1:    ok: 0 } name=MongoError, message=exception: Cannot apply $addToSet to a non-array field. Field named 'finalResultsFetchedBy' has a non-array type NULL in the document _id: "JPjbHe9x7A", errmsg=exception: Cannot apply $addToSet to a non-array field. Field named 'finalResultsFetchedBy' has a non-array type NULL in the document _id: "JPjbHe9x7A", code=16837, ok=0

**Comment by Laddy101** [comment]
We've just encountered the same problem. Seems that the Javascript SDK writes (null) whereas the mobile SDKs write (undefined). This leads to the problem that the iOS SDK crashes with an NSException by accessing the values of an Parse object by Object.value, Object.object(forKey: "value"), Object.value.isDataAvailable etc.
