### ISSUE TITLE
Access HTTP request headers inside Parse triggers.

### ISSUE THREAD

**Issue by deepu-tp** [parse-community/parse-server#3097]
Hello, is there any way to access the HTTP request headers inside a Parse trigger like afterSave or beforeSave?

Request headers have been added to cloud functions (#1461).

I wanted to track activity in beforeSave and afterSave by way of logs. If a request ID is set by an upstream server (as header say X-Request-Id), then all activity for a given request (beforeSave, afterSave) can be tracked via this request ID.

I'd like your thoughts on this. Currently the headers do not get passed to the trigger handler. But this could easily be achieved.

**Comment by flovilmart** [comment]
As you mentioned that could be easily achieved. you can go ahead and implement it !

**Comment by hatpick** [comment]
@flovilmart this is exactly what they call flaming in oss development, nice!

**Comment by flovilmart** [comment]
Not sure to follow, if being sarcastic or not.

**Comment by flovilmart** [comment]
In any case feel free to implement the feature and open a pull request

**Comment by mmarshak** [comment]
And news about adding the header to the triggers?

**Comment by iOSDevil** [comment]
+1 
I need to perform GeoIP lookup prior to saving a new user registration.

**Comment by Mbompr** [comment]
I'm interested too, but I have had a quick look at it and it does not seems to be easy. 

Things seem to start in `handleCreate` / `handleUpdate` of `ClassesRouter` but I did not manage to understand where these were called.

**Comment by flovilmart** [comment]
implemented
