### ISSUE TITLE
iOs clients are logged out after parse-server migration

### ISSUE THREAD

**Issue by craffenoux** [parse-community/parse-server#3183]
Hello,

I have successfully finished my migration but it remains a last issue which is the log out my users when they switch to the new iOs client pointing to the new parse-server. 

I have the `[PFUser enableRevocableSessionInBackground]` implemented as follow 

```
[Parse enableLocalDatastore];
[Parse initializeWithConfiguration:[ParseClientConfiguration configurationWithBlock:^(id<ParseMutableClientConfiguration> configuration) {
    configuration.applicationId = @"****";
    configuration.clientKey = @"****";
    configuration.server = @"****";
}]];
[PFUser enableRevocableSessionInBackground];
```

Did I miss something ? After the user logged in again, everything is fine.

**Comment by flovilmart** [comment]
Can you run parse-server with VERBOSE=1, more particularly we wanna look at the upgradeToRevocableSession calls and their results.

**Comment by craffenoux** [comment]
I did the following steps : 

- Logged in from the old ios client pointing to parse.com
- Updated to the new ios client pointing to my parse-server
- Opened the app and `NSLog` the `[PFUser currentUser]` and i had a `(null)` result.
 
On the serve side I have set `VERBOSE=1` in my config vars and i had nothing related to the sessions which has been output. The only thing I can see is `Ran cloud function _myFunction_ for user undefined`

Are sessions linked to the clientKey ?

**Comment by flovilmart** [comment]
> Are sessions linked to the clientKey ?

No they are not, they are stored per applicationID, Do you have any logs of failing keychain access on your device/simulator?

Have you seen that thread: https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/issues/437#issuecomment-255539445

**Comment by craffenoux** [comment]
Ok I've tried something else.

```
I have deleted manually all the sessions object for a specific user.
Logged in from the old ios client pointing to parse.com
Updated to the new ios client pointing to my parse-server
Opened the app -> it works!
```

Do you think it comes from old sessions which are not revocable ?

**Comment by flovilmart** [comment]
I'm not sure. Tough to say like that.

**Comment by craffenoux** [comment]
After re-reading all the docs linked to the sessions i have figured out that my parse.com app has been on revocable sessions from day 1.
So it comes from somewhere else.. Any idea where i can look for hints ?

**Comment by craffenoux** [comment]
When I delete all the session objects for a specific user then log in from the ios client pointing to my parse-server then downgrading to the ios client pointing to parse.com i have the following error 

`[Error]: invalid session token (Code: 209, Version: 1.13.0)`

**Comment by flovilmart** [comment]
Without the device network logs or the server logs that will be tough to say

**Comment by alexblack** [comment]
Maybe try logging/catching errors from `enableRevocableSessionInBackground`
