### ISSUE TITLE
Parse.Object.saveAll Failing When PARSE_SERVER_ENABLE_EXPERIMENTAL_DIRECT_ACCESS=0

### ISSUE THREAD

**Issue by listingboat** [parse-community/parse-server#3197]
Using parse-server 2.2.5 with Node 7.2

I've completed the refactor to remove `Parse.Cloud.useMasterKey()` and use `{userMasterKey:true}` in the save and saveAll calls.

This all works fine when `PARSE_SERVER_ENABLE_EXPERIMENTAL_DIRECT_ACCESS=1`

If I turn it off, then the `saveAll(objectsToSave, {useMasterKey: true})`, I get this error:

```
error: Error handling request: ParseError {
  code: 107,
  message: 'cannot route PUT \\classes\\_User\\01dJFUbNLz' } code=107, message=cannot route PUT \classes\_User\01dJFUbNLz
URL: /parse/batch
```

**Comment by bmcminn** [comment]
Been going over this issue with @listingboat this morning and it seems the query path separator on Windows is using the native Windows filesystem path separator (`\\`) as opposed to the `/` path separator.

Is there a spec that defines how the direct parse query handler resolves query paths? because this is a behavior I'm used to seeing in Node's file system path methods.

**Comment by listingboat** [comment]
This was fixed with https://github.com/ParsePlatform/parse-server/pull/3138.  But, apparently not released yet?

It was an issue with using path on Windows.

**Comment by flovilmart** [comment]
Should be released soon.

**Comment by flovilmart** [comment]
In the meantime you can probably point yourself to `parseplatform/parse-server#latest`

**Comment by listingboat** [comment]
Thanks @flovilmart !

**Comment by flovilmart** [comment]
@listingboat is it working correctly with the latest release?

**Comment by bmcminn** [comment]
@flovilmart Everything seems to be working just fine :)

**Comment by flovilmart** [comment]
that's great, I'm thinking of putting this as the default for the next release.

**Comment by listingboat** [comment]
Yes, this issue affected windows only which our development platform, not our production platform which is Linux on Heroku.

We pushed production with this flag on and haven't seen any issues today.

**Comment by flovilmart** [comment]
that's great, any noticeable performance improvement with CloudCode?

**Comment by listingboat** [comment]
I ran a simple JMeter test against my local instance with PARSE_SERVER_ENABLE_EXPERIMENTAL_DIRECT_ACCESS set to 0 then again with it set to 1.  requests seem to be cut in half.  On larger queries, the time is cut down up to 500%.

**Comment by flovilmart** [comment]
Holy molly.... That's cool
