### ISSUE TITLE
Parse Server S3 Access Denied.

### ISSUE THREAD

**Issue by mkaya93** [parse-community/parse-server#3236]
Hello, 

I tried A few time but its not working. 

Problem is I created bucket and configured it. Also I configure de adapter. I'm getting an url https://onmesocial.s3.amazonaws.com/50fba12a2062cf42220185ea18db12d4_file.jpeg
but I'm getting this error.

```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>6B94CFF9376F1B8C</RequestId>
<HostId>
YMxWAo7TcXWQYBg1iYReib1tVmRjpLtmTBl5EEKoWwo+iMF5q9yRYnFq35AX/zEWpUffrZWblNc=
</HostId>
</Error>
```

Also parse is not writing files to the s3

this is my configuration.

```
filesAdapter: {
    "module": "parse-server-s3-adapter",
    "options": {
      "bucket": "onmesocial",
      "accessKey": "accesskey",
      "secretKey": "secretkey",
      "directAccess": true,
      "baseUrl": null, 
      "baseUrlDirect": false,
      "signatureVersion": 'v4'
    }
  },
```

**Comment by natanrolnik** [comment]
Hey @mkaya93, did you follow all the instructions here: https://github.com/ParsePlatform/parse-server/wiki/Configuring-File-Adapters#set-up-your-bucket-and-permissions, including configuring the Policy Document?

**Comment by mkaya93** [comment]
@natanrolnik yes I followed the instructions but I'm still getting access denied.

**Comment by Cliffordwh** [comment]
Either that image doest exists in the bucket or the policy in S3 has not being setup correctly!

**Comment by mkaya93** [comment]
@Cliffordwh images are not synchronized and adding to bucket either also can't access them.

**Comment by lenart** [comment]
Couple of things you can try to determine where exactly is the problem: upload a file to S3 bucket by hand and try to access is as anonymous user.

If this works then there's something wrong with your Parse config. Check the `accessKey` and `secretKey`. Compare the S3 url of your manually uploaded file with the one that parse generates - sometimes the problem can be different S3 regions. Below is my working config using custom (EU) region.

```
var S3Options = {
  accessKey: "myaccesskey",
  secretKey: "mysecret",
  bucket: "mybucket",
  region: "eu-central-1",
  signatureVersion: "v4"
}
```

**Comment by natanrolnik** [comment]
@mkaya93 are you still having this problem?

**Comment by Muesly** [comment]
I think I'm having the same issue, where files are saved:

In Parse as https://<bucket-name>.s3.amazonaws.com/<filename>

When I go to S3 the filenames are: https://s3.amazonaws.com/<bucket-name>/<filename>

The Parse filename, just times out, but the images are fine when accessed through S3.  I am using directAccess:true, and can see the file in S3 is set to be publicly viewable.
