### ISSUE TITLE
Error after updating from 2.2.13 to 2.3.1, only if you keep the same port: Error generating response. ParseError { code: 101, message: 'Object not found for update.' } code=101, message=Object not found for update.

### ISSUE THREAD

**Issue by creactivemobile** [parse-community/parse-server#3246]
Describe your issue in as much detail as possible.

I am running a Parse Server on my centOS 7 server.
I had apps running on the 2.2.13 version without any issue, but when I tried to update "npm update", I started getting this error:

Error generating response. ParseError { code: 101, message: 'Object not found for update.' } code=101, message=Object not found for update.

If I change the port where the server is running it starts working, if I revert it to the original port I get the error again.

### Steps to reproduce

Please include a detailed list of steps that reproduce the issue. Include curl commands when applicable.

I was able to reproduce this on all the apps I had on the server.

1. Parser server running 2.2.13
2. npm update to 2.3.1
3. Restart parse server

#### Expected Results

Working as it was previous

#### Actual Outcome

Error generating response. ParseError { code: 101, message: 'Object not found for update.' } code=101, message=Object not found for update.

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.3.1
  - Operating System:     centOS 7
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Localhost on dedicated server

- **Database**
  - MongoDB version: MongoDB shell version: 3.0.10-1.5
  - Storage engine:  MongoDB
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): Localhost

### Logs/Trace

You can turn on additional logging by configuring VERBOSE=1 in your environment.

Error generating response. ParseError { code: 101, message: 'Object not found for update.' } code=101, message=Object not found for update.

**Comment by srameshr** [comment]
@creactivemobile Were you able to fix this? Even I am facing the same issue. Look at this: https://github.com/ParsePlatform/parse-server/issues/3266

**Comment by creactivemobile** [comment]
@srameshr unfortunately no, the only "solution" was to downgrade back to 2.2.13 :/
