### ISSUE TITLE
GeoPoint issue on PostgreSQL

### ISSUE THREAD

**Issue by vferdiansyah** [parse-community/parse-server#3285]
### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.3.1
  - Operating System:     macOS Sierra 10.12.2
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): localhost

- **Database**
  - PostgreSQL version: 9.6.1
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): localhost

I'm using Parse Dashboard (v1.0.22) to enter my data. When I'm inputting a GeoPoint, at first everything looks good (see image below).

![screen shot 2016-12-25 at 10 17 52](https://cloud.githubusercontent.com/assets/12978330/21469569/7e2e8576-ca8b-11e6-8432-f5973f5dcf28.png)

But after I refreshed my window, it seems like the latitude and longitude was reversed automatically somehow (see image below).

![screen shot 2016-12-25 at 10 20 01](https://cloud.githubusercontent.com/assets/12978330/21469580/dc802b3e-ca8b-11e6-934c-4a3d29aaa8a7.png)

I'm using Google Maps in my app so I have to use coordinate.latitude as GMap's longitude and coordinate.longitude as GMap's latitude to make the map works.

Anyone experienced the same issue?

**Comment by hramos** [comment]
Looks like this should be opened against the parse-dashboard repo instead.

**Comment by pewh** [comment]
Please reopen this issue. I also get same issue.

This bug is ony happen when update geopoint via cloud code or parse dashboard. But this bug is not triggered when save new row with geopoint. This bug is blocking me on project

**Comment by vferdiansyah** [comment]
Same as @pewh. My first project that used MongoDB doesn't experience this issue. Only the one that is using PostgreSQL. Still persist on Parse Server 2.3.5 and Parse Dashboard 1.0.25.

**Comment by vferdiansyah** [comment]
![screen shot 2017-03-23 at 9 49 20](https://cloud.githubusercontent.com/assets/12978330/24229807/100fd276-0fae-11e7-8a18-01177b3e0306.png)

This is what I get when I tried to query using REST API. The value really is reversed.
Any updates on this?

**Comment by flovilmart** [comment]
@vferdiansyah thanks for the PR, there seems to be some failing tests
