### ISSUE TITLE
Add 'withinPolygon' to ParseQuery

### ISSUE THREAD

**Issue by tarekskr** [parse-community/parse-server#3290]
In addition to the existing 'ParseQuery.withinGeoBox', we also need a 'withinPolygon' function so that we could search inside a polygon of GeoPoints.

AFAIK, this is supported by MongoDB, but I have no idea how to implement it myself in Parse :)

Here is the MongoDB documentation: https://docs.mongodb.com/manual/reference/operator/query/polygon/#op._S_polygon

**Comment by madsb** [comment]
I am also in need of this feature. Unfortunately AFAIK, previous pull requests have been denied citing the need to be compatible with the Parse.com legacy database, which runs an older, non-geojson compatible version of MongoDB.

**Comment by natanrolnik** [comment]
I believe this is actually a good feature to have.

Recently, the [Parse Server Evolution](https://github.com/parse-server-modules/parse-evolution/blob/master/0000-template.md) repo was created to manage better feature requests. 

@tarekskr do you think you can add a PR there with the proposal? Fork the repo, add a new proposal according to [this template](https://github.com/parse-server-modules/parse-evolution/blob/master/0000-template.md) to the proposals folder, and create the PR.

**Comment by madsb** [comment]
Alright, I've created a [pull request](https://github.com/parse-server-modules/parse-evolution/pull/4) with the feature request. Please let me know if I missed something.

**Comment by otymartin** [comment]
Hey @madsb does this add support for `geoJSON`/2dsphere location queries? That would be a quantum leap for location based applications

**Comment by madsb** [comment]
@otymartin At the moment it's just a feature request, but I agree completely! Hopefully someone with the right coding chops will take a stab at it. Well, at least as soon as the pull request is merged (hint-hint, @flovilmart ;) ).

**Comment by otymartin** [comment]
@madsb 
Question & maybe is just my lack of knowledge on the subject but shouldnt it still be technically possible to associate PFObjects with a geoJSON property and use cloud code to perform 2dsphere queries. As I understand these are capabilities existing with mongoDB independent of parse server or does parse-server/parse-iOS SDK need to add some kind of support for it?

**Comment by dplewis** [comment]
Added in Parse Server 2.5.0. Closes via #3866
