### ISSUE TITLE
All logs are being printed when verbose = false

### ISSUE THREAD

**Issue by arturogutierrez** [parse-community/parse-server#3319]
### Issue Description

Hello!

I have my server running with pm2 with the following configuration:

```
clientKey: *********
cloud: /home/parse/*****/cloud/main.js
mountPath: /parse
maxUploadSize: 20mb
userSensitiveFields: email
verbose: false
logLevel: error
serverURL: http://localhost:1337/parse
parse-server running on http://localhost:1337/parse
```

But I can see all verbose logs when my app calls to any cloud function, example:

```
2017-01-04T10:47:42.731Z - RESPONSE from [POST] /parse/functions/getChallengeHistory: {
  "response": blah blah blah.......
```

Is that normal? Becuase my server's disk will be full soon then 😄 

### Steps to reproduce

1. Launch parse-server through pm2 with `"VERBOSE": false"` in the `ecosystem.json` file
2. Call to one cloud function
3. See the printed logs in the parse-server log files or through `pm2 logs`

#### Expected Results

No verbose logs

#### Actual Outcome

Everything is being printed

### Environment Setup

- **Server**
  - parse-server version:  2.3.1
  - Operating System:     Ubuntu 16.04
  - Hardware:                  Digital Ocean Droplet
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Digital Ocean

- **Database**
  - MongoDB version: 3.0.10-1.5
  - Storage engine:  Rocksdb
  - Hardware:        Digital Ocean Droplet
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): Digital Ocean

**Comment by rvitorper** [comment]
Hey there,

I managed to try it out and the thing is: you should not add '--verbose' at all if you want it to be silent. This is really an issue with Parse Server. I tried '--verbose false', '--verbose 0' and none worked. So, for now, taking '--verbose' option just works.

Kind Regards,
Ramon

**Comment by arturogutierrez** [comment]
Problem found!

Two edge things happening here:

1. As @rvitorper said, ParseServer is not being silent even with a `VERBOSE=false` environment var (furthermore, the initial parse-server log lies saying `verbose: false` 😄  ).
2. There is a bug in pm2 ( https://github.com/Unitech/pm2/issues/2576 ) which make any environment variable declared in the `ecosystem.json` file undeletable, so although I was removing the env var from the file due to the previous point I was unable to make Parse-Server non-verbose.

So, should I close the issue and open a new one about `VERBOSE=false` thing? or is this issue enough?

Thanks!
