### ISSUE TITLE
LiveQuery does not match subobjects in query specified with dot notation

### ISSUE THREAD

**Issue by dstarke** [parse-community/parse-server#3321]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Server!

- [x] You've met the prerequisites: https://github.com/ParsePlatform/parse-server/wiki/Parse-Server-Guide#prerequisites.

- [x] You're running the latest version of Parse Server: https://github.com/ParsePlatform/parse-server/releases

- [x] You've searched through existing issues: https://github.com/ParsePlatform/Parse-Server/issues?utf8=%E2%9C%93&q=is%3Aissue Chances are that your issue has been reported or resolved before.

- [x] You have filled out every section below. Issues without sufficient information are more likely to be closed.

--

### Issue Description

Parse Server allows you to specify queries on nested subobjects using dot notation. For example, the query specified using `query.equalTo("status.x", "someValue");` will match objects where there is a `status` attribute whose value is an object with the key `x` and the value `"someValue"`.

Although this works correctly for queries issued through the REST API, the LiveQuery system does not correctly match objects based on this type of constraint. As a result, queries that use this type of key specification can return objects that the LiveQuery system will not return notifications for.

### Steps to reproduce

1. Create an object with a nested subobject as its value
2. Construct a query that selects objects based on a value in the subobject using dot notation.
3. Issue the query, confirm that the object is returned by the query
4. Subscribe to the query to get LiveQuery updates
5. Update the object you created in step 1.
6. Note that no LiveQuery updates for this object are received by the client.

#### Expected Results

Client should receive LiveQuery updates

#### Actual Outcome

Client does not receive LiveQuery updates

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.3.1
  - Operating System:     macOS Sierra 10.12.2
  - Hardware:             MacBook Pro (15-inch, Late 2011)
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Localhost (also observed running on Azure)

- **Database**
  - MongoDB version: 3.2.11
  - Storage engine:  MMAPv1
  - Hardware:       unknown
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): mLab

### Logs/Trace

(no relevant logs)

**Comment by ananfang** [comment]
Hi @dstarke
Thanks for your effort that enable dot notation query of Live Query.

There is something weird that you mention that `query.equalTo("status.x", "someValue");` can work. But I tried using this kind of query in iOS, it failed.

Is it possible that query with dot notation?

**Comment by flovilmart** [comment]
It is supported in Parse-server, querying with dot notations.

As for the support for more complex queries, the main barrier is that the current implementation is synchronous and doesn't touch the DB for performance reasons. We'd have to make the query matching async first, and then add the support for such query constraints, this time, with DB access.

**Comment by ananfang** [comment]
Thanks for your reply @flovilmart.
Is there any schedule you plan to implement **querying with dot notations**?

**Comment by flovilmart** [comment]
@ananfang for now, no schedule i'm afraid, but if you feel you want to tackle the issue, i could help you get going :)

**Comment by ananfang** [comment]
@flovilmart I'am afraid that I can't handle these issue currently, I am zero experience on Node.js developement. I'll try to start studyin on Node.js, if I am ready, I'll tell you later :)

**Comment by flovilmart** [comment]
It's ok, always a good opportunity to learn.
