### ISSUE TITLE
ACL stops working randomly

### ISSUE THREAD

**Issue by abdielou** [parse-community/parse-server#3326]
### Issue Description

ACL stops working at random intervals. I have a few Roles that containing specific users. These Roles are then applied to some entries in a table. The ACL is ignored. It will start working if I restart the parse server. It stops working after a few hours or even a few minutes. There are no JOBs touching the ACL for these rows or table. This affects ALL users.

I'm sorry if I cannot provide a reproducible scenario. The issue is quite critical for my application and makes no sense that a restart fixes the issue for a while and then breaks again. I don't see anything in the parse server logs that suggests an error of this nature.

### Steps to reproduce

1. Create a Role and add a user to it
2. Set the ACL of one entry of a table with this Role
3. Restart Parse Server
4. Find all entries on the table

#### Expected Results

- All entries will be retrieved for the users with the Role
- Only entries with Public ACL will be returned for users without the Role

#### Actual Outcome

- All entries are retrieved regardless of the Role of the user.
- If the node hosting the parse-server is restarted, the ACL works fine.
- ACL stops working after a while (it could be a few minutes or a few hours).

### Environment Setup

- **Server**
  - parse-server version: 2.2.25
  - Operating System: 64bit Amazon Linux 2016.09
  - Node.js version: 6.9.1
  - Hardware: c4.large
  - Localhost or remote server?: AWS

- **Database**
  - MongoDB version: 3.2.11
  - Storage engine: MMAPv1
  - Hardware: M1
  - Localhost or remote server?: mLab

**Comment by abdielou** [comment]
I've been doing more testing and this is only happening with a Role that has hundreds of users.

**Comment by flovilmart** [comment]
Do you have more informations? We made improvements into the caching engine. If you have many objects in your roles, I suggest you use a distributed cache like Redis in order to ease the memory usage on the server.
