### ISSUE TITLE
Using Bluebird instead of Native Promise in RedisCacheAdapter 

### ISSUE THREAD

**Issue by linpf870208** [parse-community/parse-server#3359]
when query or update data, parse need to query from cacheAdapt  frequently, and as benchmarks showing native is more slower when compared to bluebird. So should we use bluebird instead of Native Promise in RedisCacheAdapter?

In my tests via benchmark, use bluebird would highly improve performance.

**Comment by Caijiacheng** [comment]
try to post the performance bench of BlueBird or PR

**Comment by flovilmart** [comment]
i ran the test suite with and without bluebird:



`npm test  77,77s user 5,53s system 69% cpu 1:59,65 total`


`BLUEBIRD=1 npm test  75,94s user 5,82s system 52% cpu 2:36,02 total`

That's not really convincing me for the High performance expected from BB...

**Comment by linpf870208** [comment]
@flovilmart 

machine parameters:
cpu cores: 2
model name: Intel(R) Xeon(R) CPU E5-2430 0 @ 2.20GHz
mem 4096MB  
1Mbps 

first i ran the benchmark for InMemoryCache, cpu ran 100%.  secondly i ran it with RedisCacheAdapte, cpu just ran 60%. i feel confuse about that. so i use bluebird to wrap redis,  
then cpu ran 100% again.

my benchmark result as follow:
ab -n 20000 -c 50 -k -H 'X-Parse-Application-Id: APPID' -H 'X-Parse-Master-Key: MASTERKEY' -T  application/json -p ab.txt

InMemoryCache
CPU 100% MEM 3.4%  TPS 168  LTC 300ms
RedisCache
CPU 60% MEM 2.9%  TPS 51  LTC 968ms
RedisCache with Bluebird 
CPU 99% MEM 3.1%  TPS 119  LTC 418ms


According to issue [http://softwareengineering.stackexchange.com/questions/278778/why-are-native-es6-promises-slower-and-more-memory-intensive-than-bluebird]
new Promise is an extremely slow way of creating a promise, first the executor function allocates a closure, secondly it is passed 2 separate closures as arguments. That's 3 closures allocated per promise but a closure is already a more expensive object than an optimized promise

i think new Promise result in slower permance,what do you think?

**Comment by acinader** [comment]
I'd like it if we could substitue bluebird in as the promise library.

both better performing and its got a richer api that I am getting used to having!

not sure what's involved...yet

**Comment by flovilmart** [comment]
Faster is not a given :/ that highly depends on the nodejs version. Using bluebird, you can swap it globally, and that doesn't require any change in parse-server.

As for the new Promise pattern, well, that implies an extensive rewrite
