### ISSUE TITLE
Parse with Heroku server hangs when making call from Unity3D

### ISSUE THREAD

**Issue by fparvan** [parse-community/parse-server#3422]
We are trying to migrate Parse to a Heroku Server, the requests work fine when using curl from a terminal, but when we try to make the requests from Unity3D, we receive neither a succes response, neither a failure response, the server just hangs and never responds. Before switching to a custom server everything worked as intented.

The Parse Version for Unity is 1.7.0 and the Unity3D version is 5.3.4f1.

### Steps to reproduce

1. This is how we initialize the Parse client in Unity: 

ParseClient.Configuration config = new ParseClient.Configuration ();
			config.Server = "Server path"; 
			config.ApplicationId = "appId";
			ParseClient.Initialize(config);

Note that we am not initializing the PraseClient with the unity script attached to the game object because it does not have the necesarry fields (server).

2. Make the actual call to parse

                        lock (mLock)
			{
				if (mPullTask != null && !mPullTask.IsCompleted) return mPullTask;

				var query = ParseObject.GetQuery(cClassName).WhereEqualTo("fbId", mFacebookId);
				Debug.Log("Parse -> Starting pull");

				// Load parse object
				mPullTask = query.FirstAsync().ContinueWith(t =>
				{
					try
					{
						Debug.Log("Parse -> Pull completed");
						mParseObject = t.Result;

						pullReceived();
					}
					catch (AggregateException ex)
					{
						if (ex.InnerExceptions.Any(
								e => e is ParseException && (e as ParseException).Code == ParseException.ErrorCode.ObjectNotFound))
						{
							tryCreateNewObject(mCloudSync.LocalEventStore);
						}
						Debug.Log("Parse -> Got exception: " + ex.Message);
					}
					catch (Exception ex)
					{
						Debug.Log("Parse -> Got exception: " + ex.Message);
					}

					if (mParseObject != null) CloudDataLoaded = true;
				});

				return mPullTask;
			}

#### Expected Results

We would expect that when the call gets a response and returns we would get either an error, or the requested Parse object. 

#### Actual Outcome

Instead, the call just hangs, no crash, no timeout, nothing. The last thing that is logged is this: 

Debug.Log("Parse -> Starting pull");

### Environment Setup

*SERVER*
- parse-server version 2.3.2  
- Hardware: Single dyno Heroku (512MB RAM, 4 x Intel Xeon X5550 @ 2.67Ghz) 
- Remote Heroku 

*DataBase*
 - mongoDB version: 3.2.11 
 - Storage engine: mongoLab 
 -  Hardware: Sandbox mLab plan (with 500MB storage)
 -  remote server mLab

**Comment by joeyslack** [comment]
Are you intending to return like that? `return mPullTask;`

You will have to use promises if you are intending to wait for your other async request to finish.

**Comment by fparvan** [comment]
No, The task is continued in another place. This part functioned before implementing the custom server logic. Here is the code for executing the task:

public void PushData()
		{
			try
			{
				// Try to load the cloud data if not loaded.
				if (!CloudDataLoaded)
					PullData().ContinueWith(t => pushAction()); // First pull cloud data then push new changes.
				else
					pushAction(); // Just push new data if already loaded cloud data.
			}
			catch (Exception ex)
			{
				Debug.Log("Parse -> Exception in push: " + ex.Message);
			}
		}

**Comment by ColossalChris** [comment]
How do you compose your reference to the heroku server?
