### ISSUE TITLE
Unsetting _User field directly through mongodb won't update Parse data. How do I clear in-memory cache?

### ISSUE THREAD

**Issue by jenshandersson** [parse-community/parse-server#3459]
### Issue Description

When unsetting a File column on the _User object directly from MongoDB it doesn't update in the Dashboard or through the API. I know there is some cache layer around User and Roles, but how does it work and how to clear it? I have restarted parse-server and waited 20 minutes.

### Steps to reproduce

Please include a detailed list of steps that reproduce the issue. Include curl commands when applicable.

1. ```db.getCollection('_User').update({_id: 'CFXE6EsHne'}, { $unset: { profilePictureSmall: '' }, $set: {_updated_at: new Date()}})```
2. ```db.getCollection('_User').find({_id: 'CFXE6EsHne'})```
3. Field `profilePictureSmall` is removed from the document in mongo

#### Expected Results
Expected the File to have been delinked from the User object. Both in dashboard and API.

#### Actual Outcome

![image](https://cloud.githubusercontent.com/assets/1150467/22469800/194df3f6-e7c5-11e6-9bbb-d90f204c6a48.png)

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.3.2
  - Operating System:     Ubuntu 14
  - Hardware:             2 CPU, 2GM RAM
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Digital ocean

- **Database**
  - MongoDB version: 3.0.8
  - Storage engine: mmapv1
  - Hardware:  Same as server above
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): localhost (same as parse server)

**Comment by acinader** [comment]
I don't have an answer for you, but may I ask why you would want to do this?  Its hard for me to imagine when this would be a good solution.  If you need to change the data in mongo, why not use the Parse SDK to do it?

**Comment by jenshandersson** [comment]
@acinader When I need to run big queries and manipulate a lot of data I prefer using mongodb directly. I'm sure there's a simple way to clear the cache, anyone?

**Comment by johanarnor** [comment]
My experience is that only the dashboard caches it, so if you do a query, the updated data will be returned. 

For me, I just force refresh (in Chrome) to clear the cache in the dashboard.
