### ISSUE TITLE
getting http error 404 from time to time

### ISSUE THREAD

**Issue by MBDeveloper** [parse-community/parse-server#3469]
Environment Setup

Server
parse-server version: 2.2.19 or 2.3.1
Operating System: windows on Azure
Localhost or remote server? remote on Azure
Database
MongoDB version: 3.0.12 (on mLab)

From time to time I am getting strange http 404 errors on the below urls (taken from the webserver log):
https://MyServerName:80/server.js
https://MyServerName:80/parse/users
https://MyServerName:80/parse/classes

- server.js is the main js file as written in the package.json file
 - /parse/ is the mountPath of parse server in express.

I have few questions:
1. Who initiate the request to the main js file (server.js)
2.How can it be https request with port 80

tried PARSE_SERVER_ENABLE_EXPERIMENTAL_DIRECT_ACCESS = 1 - didn't help.

**Comment by montymxb** [comment]
@MBDeveloper is this still an issue or did you manage to resolve it?

**Comment by natanrolnik** [comment]
Closing it since there was no reply. If it's still an issue **and a bug** in Parse Server, we'll reopen.
