### ISSUE TITLE
Save nested array or object properties

### ISSUE THREAD

**Issue by kcoop** [parse-community/parse-server#3473]
Parse server does a good job of supporting nested arrays and objects, except that there doesn't appear to be a way to submit minimal updates to them. 

I now have nested arrays that exceed 16k of JSON, and frequently need to make updates from the client that change just a single property of one nested object in an array.

The alternative is to switch to a new object type for the array values, and join them, which is awkward and less performant.

**Comment by yomybaby** [comment]
@kcoop  You can save nested object property.

```
curl -X "PUT" "http://localhost:1337/api/Classes/TestClass/lykM0LPb5c" \
     -H 'X-Parse-Session-Token: TOKEN \
     -H 'X-Parse-Application-Id: APP_ID \
     -H 'Content-Type: application/json; charset=utf-8' \
     -d $'{
  "obj.c": "yoyo"
}'
```
