### ISSUE TITLE
Getting the client ip address in cloud code beforeSave

### ISSUE THREAD

**Issue by mmarshak** [parse-community/parse-server#3515]
### Issue Description

With the latest release of Parse server cloud function have access to the header of the request (the expire header), however triggers (like beforeSave) do not have access to the header of the request.
A use case is that I want to save the client ip address in the installation object before I save it.

### Steps to reproduce

Any beforeSave trigger will not have access to the header.
The request field that is provide to the trigger is missing the header of the request that include the client ip address.

#### Expected Results

The expected behaviors is that the header of the request will be include in the request provided to the trigger (like beforeSave) in the same manner it is provided today to any other cloud function.

#### Actual Outcome

The trigger code's request does not include the header.

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.2.25
  - Operating System:     AWS Ubuntu
  - Hardware:             AWS EC2
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): AWS

- **Database**
  - MongoDB version: mLab
  - Storage engine: Do not know
  - Hardware:        mLab running on AWS
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): AWS

### Logs/Trace
if you log util.inspect(request) in the trigger function it does not include the header of the request.

**Comment by dplewis** [comment]
Closed via https://github.com/parse-community/parse-server/pull/4265
