### ISSUE TITLE
Issue with custom auth 

### ISSUE THREAD

**Issue by ranhsd** [parse-community/parse-server#3557]
Hi, 
i am trying to integrate a custom auth provider into my parse server. I am trying to use firebase login and in order to do that i created the following module: 

https://github.com/parse-server-modules/parse-server-firebase-auth-adapter

In my parse server i put the following:

 ```
   "auth" : {
        "firebase" : {
            "module" : "parse-server-firebase-auth-adapter",
            "databaseURL" : "https://bizdate-dev.firebaseio.com"
        }
    }  
```

After debug it a bit i found the my module is being executed but when i am trying to use it i get the following error from parse server:

> error: Error generating response. TypeError: Cannot read property 'adapter' of undefined
> bizdate-server |     at Object.getValidatorForProvider (/parse-server/node_modules/parse-server/lib/Adapters/Auth/index.js:112:35)
> bizdate-server |     at /parse-server/node_modules/parse-server/lib/RestWrite.js:263:58
> bizdate-server |     at Array.map (native)

After debug this one a bit i found that there is an array of providers (inside the index.js file) and there the firebase adapter not exist and when the code trying  to access the provider the result is **undefined**

Thanks  in advanced for any help

**Comment by flovilmart** [comment]
I believe your adapter is malformed  ;)

https://github.com/parse-server-modules/parse-server-firebase-auth-adapter/blob/master/src/index.js#L36

this should be:

```
module.exports = new FirebaseAuth()
```

The adapter loader expects:

```
const adapter = ...
typeof adapter.validateAppId == 'function'
typeof adapter.validateAuthData == 'function'
```

For more infos, see examples:

https://github.com/parse-community/parse-server/blob/master/src/Adapters/Auth/facebook.js
