### ISSUE TITLE
Push Sends - never receives....

### ISSUE THREAD

**Issue by mginz83** [parse-community/parse-server#3566]
This is what sticks out to me in the below:
_PushStatus vCsEiZSCwm: sent push! 0 success, 0 failures

2017-02-25T04:52:11.002303+00:00 app[web.1]: [36mverbose[39m: RESPONSE from [POST] /parse/functions/sendPushMessage: {
2017-02-25T04:52:11.004976+00:00 app[web.1]: [36mverbose[39m: _PushStatus vCsEiZSCwm: sending push to 1 installations
2017-02-25T04:52:11.002304+00:00 app[web.1]:   "response": {
2017-02-25T04:52:11.002305+00:00 app[web.1]:     "result": "Push Sent!"
2017-02-25T04:52:11.002305+00:00 app[web.1]:   }
2017-02-25T04:52:11.002306+00:00 app[web.1]: } result=Push Sent!
2017-02-25T04:52:10.994801+00:00 heroku[router]: at=info method=POST path="/parse/push" host=obscure-fortress-48710.herokuapp.com request_id=7f8edefa-6c51-4387-91ed-b03f7f75dfbd fwd="54.81.31.140" dyno=web.1 connect=0ms service=12ms status=200 bytes=533
2017-02-25T04:52:11.022075+00:00 app[web.1]: [36mverbose[39m: _PushStatus vCsEiZSCwm: sent push! 0 success, 0 failures
2017-02-25T04:52:11.000351+00:00 heroku[router]: at=info method=POST path="/parse/functions/sendPushMessage" host=obscure-fortress-48710.herokuapp.com request_id=356a768c-e9a2-48b7-b2df-732a4e72412c fwd="24.115.240.225" dyno=web.1 connect=1ms service=373ms status=200 bytes=505
2017-02-25T05:02:55.520220+00:00 heroku[router]: at=info method=GET path="/parse/" host=obscure-fortress-48710.herokuapp.com request_id=74db278d-204c-4b0e-8c0f-cdd07d9092e6 fwd="24.115.240.225" dyno=web.1 connect=1ms service=6ms status=403 bytes=466
2017-02-25T05:03:03.388683+00:00 heroku[router]: at=info method=GET path="/parse/" host=obscure-fortress-48710.herokuapp.com request_id=a3d8e441-9a8f-4f3d-9665-e14b295505b8 fwd="24.115.240.225" dyno=web.1 connect=1ms service=4ms status=403 bytes=466

Here is the _pushstatus
`{
    "_id": "vCsEiZSCwm",
    "pushTime": "2017-02-25T04:52:10.987Z",
    "query": "{\"userId\":\"UNx3w2tayd\"}",
    "payload": "{\"alert\":\"New Friend Request\",\"title\":\"Fuhnatik\"}",
    "source": "rest",
    "status": "running",
    "numSent": 0,
    "pushHash": "417f87d64b8e0792b4ec07835d416341",
    "_wperm": [],
    "_rperm": [],
    "_acl": {},
    "_created_at": {
        "$date": "2017-02-25T04:52:10.987Z"
    },
    "_updated_at": {
        "$date": "2017-02-25T04:52:11.020Z"
    },
    "count": 1
}`

Here is my cloud code:
`Parse.Cloud.define("sendPushMessage", function(request, response) {
    
    var theUserID = request.params.theUserID;
  var theUserNickname = request.params.theUserNickname;

  var query = new Parse.Query(Parse.Installation);
  query.equalTo("userId", theUserID);

  // here you can add other conditions e.g. to send a push to sepcific users or channel etc.

  Parse.Push.send({
      data: {alert: "New Friend Request",
            title: "Fuhnatik"},
      where: query
    }, {
      useMasterKey: true
    })
    .then(function() {
      response.success("Push Sent!");
    }, function(error) {
      response.error("Error while trying to send push " + error.message);
    });
});
`

Here is my android code
`            HashMap<String,String> map = new HashMap<String, String>();
            map.put("theUserID", currentUser.getObjectId());
            map.put("theUserNickname", currentUser.getUsername());\

            ParseCloud.callFunctionInBackground("sendPushMessage", map, new FunctionCallback<Object>() {

                @Override
                public void done(Object object, ParseException e) {
                    if (e == null) {
                        Log.d("Success: ", "Push sent!");
                    } else {
                        Log.d("Error: ", "Push Failed! -> " + e.getMessage());
                    }
                }
            });`

I never get the message on my device, why? How do I test this?

Oh, here is my installation:
`{
    "_id": "mB4y2a7yIX",
    "localeIdentifier": "en-US",
    "appVersion": "1.0",
    "userId": "UNx3w2tayd",
    "deviceType": "android",
    "appIdentifier": "com.fuhnatik.fuhnatik",
    "installationId": "de39ee3f-224a-45d0-80c3-1c7497a2fa55",
    "parseVersion": "1.13.1",
    "userNickname": "ginz",
    "appName": "fuhnatik",
    "timeZone": "America/New_York",
    "_created_at": {
        "$date": "2017-02-25T04:16:13.789Z"
    },
    "_updated_at": {
        "$date": "2017-02-25T05:36:39.756Z"
    }
}`

**Comment by bohemima** [comment]
There is no deviceToken, did you follow the Push Android Quickstart?

**Comment by mginz83** [comment]
@bohemima yup. I have the all keys where they need to be. I recently went with OneSignal and got everything working rather quickly. I would love to keep everything under parse though, so I think I am going to be creating a new project just to test it out again. I can't, for the life of me, figure out why the device never receives the push when the logs in heroku show sent.

**Comment by FridaySG** [comment]
@mginz83 What device are you sending it to? Android or iOS?

**Comment by mginz83** [comment]
@FridaySG android 

<meta-data android:name="com.parse.push.gcm_sender_id"
        android:value="id:xxxx" />;

**Comment by amabdelsalam** [comment]
I have the same problem, and I setup all keys in place. 

I'm trying to send a test notification to the Android emulator. 
`
curl -X POST -H "X-Parse-Application-Id: AnsuburAppId" -H "X-Parse-Master-Key: AnsuburMasterKey" -H "Content-Type: application/json" -d '{ "where": { "deviceType": { "$in": [ "ios",  "android"  ]  }  	},	"data": {"title": "Ant-man","alert": "This is awesome. It is awesome."}}' http://localhost:1337/parse/push
`

Here is the server output:
`
verbose: REQUEST for [POST] /parse/push: {
  "where": {
    "deviceType": {
      "$in": [
        "ios",
        "android"
      ]
    }
  },
  "data": {
    "title": "Ant-man",
    "alert": "This is awesome. It is awesome."
  }
} method=POST, url=/parse/push, host=localhost:1337, user-agent=curl/7.51.0, accept=*/*, x-parse-application-id=AnsuburAppId, x-parse-master-key=AnsuburMasterKey, content-type=application/json, content-length=139, $in=[ios, android], title=Ant-man, alert=This is awesome. It is awesome.
verbose: RESPONSE from [POST] /parse/push: {
  "headers": {
    "X-Parse-Push-Status-Id": "OJa3MU9cJs"
  },
  "response": {
    "result": true
  }
} X-Parse-Push-Status-Id=OJa3MU9cJs, result=true
verbose: _PushStatus OJa3MU9cJs: sending push to 1 installations
verbose: _PushStatus OJa3MU9cJs: sent push! 0 success, 0 failures
`

**Comment by mginz83** [comment]
I ended up using OneSignal. Works amazing and was super easy to get going
