### ISSUE TITLE
Feature request : default values and required for object fields

### ISSUE THREAD

**Issue by AmbroiseCollon** [parse-community/parse-server#3587]
Inspired from meteor.js technology, it could be a really valuable addition to add two properties to object fields :

- **Required boolean** : if a required field is left empty, save operation crashes
- **Default values** : if a field is not set, a default values can be selected

A field with a default value should be required. It would save a lot of dumb code in before and after save method.

Process could be like :
1. Object is created
2. Save method is called on object
3. All fields are checked. For each field : 
    a. if the object has already a value for the field => OK
    b. if the object has no value for the field :
        i. if field is not required => OK
        ii. if field is required :
            - if field has a default value => fill field with default value
            - if field has no default value => Error : field cannot be undefined

Maybe the easiest way to do this is to create meta collection aside from actual collection that owns all this required / default value data. But this is where my understanding of Parse Server behind the scenes stops.

What do you think ?

**Comment by acinader** [comment]
one way to achieve this is through a `beforeSave` hook in cloud code.  In the `beforeSave` hook you can validate a submission and set any default values.  

I could see an argument for adding the ability to set validation for a class in the dashboard obviating the need for doing it programatically.

**Comment by AmbroiseCollon** [comment]
The beforeSave hook is what I'm using now. But it much more elegant to just be able to set it directly in the dashboard.

**Comment by yomybaby** [comment]
I agree with @AmbroiseCollon . If Schema has required field option, it saves many boring codes. :)

**Comment by flovilmart** [comment]
@AmbroiseCollon , @yomybaby any one of you wanting to get started on that feature?

**Comment by franalt** [comment]
Any news on this? Just wanted to know before starting to code the beforeSave from my app.

**Comment by milesrichardson** [comment]
I have a library called `parseConstraints` I use for this in `beforeSave`. The code is old and a huge mess / needs to be refactored, so I would rather not share it. But here is what the general API looks like when used in a `beforeSave` trigger:

``` js
static beforeSave(ParseConstraints, req, res) {
        var parseConstraints = new ParseConstraints(req, res, 'Fund');

        return parseConstraints.existsKeys([
            'fundName'
        ])
        .then(() => parseConstraints.defaults({
                'fundManagers': [],
                'fundClosingDates': []
        }))
        .then(() => {
            /// .....
        })
       .then(() => {
            return res.success();
        }).catch((err) => {
            res.error(err);
        });
    }
```

Each `parseConstraints` function will reject a promise if there is an error. Other functions I've got include `keysHaveValidValues`, `objectsInArrayHaveKeys`, `capitalizeKeys`, `lowercaseKeys`, `uniqueKeys` (this is better implemented as an index so as not to require extra query), `uniqueMultipleKeys`

I might be interested in taking on this feature. My solution would be to define required fields in the schema, preferably complying with the official jsonschema docs. Then perform validation just before the beforeSave trigger, thus emulating what I do with the library. Open to any thoughts on this
