### ISSUE TITLE
Email Verification not sent

### ISSUE THREAD

**Issue by bfjfm2** [parse-community/parse-server#3592]
I have configured MailGun, Parse Server with following, but still email verification not sent.
How to Check this issue?

**Client Code in iOS:**

`
   PFUser *user = [PFUser new];

    user.username = @"testing";
    user.password = @"12345678";
    user.email = @"user2@myapp.com";
    [user signUpInBackgroundWithBlock:^(BOOL succeeded, NSError *error) {
//Received Success, but email is not sent
    }];
`

**Server Code:**
`
 verifyUsersEmails: true,

    publicServerURL: 'https://dev.myapp.com/parse',
    // Your apps name. This will appear in the subject and body of the emails that are sent.
    appName: 'Parse App',
    // The email adapter
    emailAdapter: {
        module: 'parse-server-simple-mailgun-adapter',
        options: {
            // The address that your emails come from
            fromAddress: 'user@myapp.com',
            // Your domain from mailgun.com
            domain: 'mg.myapp.com',
            // Your API key from mailgun.com
            apiKey: '********'
        }
    }
`

**Comment by funkenstrahlen** [comment]
Did you setup a custom domain on mailgun? Did you verify it? Otherwise mailgun does not allow sending mails to arbitrary mail adresses.

**Comment by partikles** [comment]
This is enough?

![screenshot-mailgun com 2017-03-04 01-47-25](https://cloud.githubusercontent.com/assets/280136/23562382/2541f10a-007d-11e7-91b0-6917e93603f4.png)

**Comment by funkenstrahlen** [comment]
Do you have email verification enabled in your parse server config?

```
  // Enable email verification
  verifyUserEmails: true,
```

Because in your post above `verifyUsersEmails: true,` contains a typo.

**Comment by bfjfm2** [comment]
It's working fine now.

**Comment by zaxonus** [comment]
Hi,

I just read this post and saw you had a few troubles when setting up email verification.
I am now facing more or less similar issues as explained in details [here](https://stackoverflow.com/questions/49206670/link-inside-verification-mail-not-working). Did you experiment the same kind of problems?

**Comment by funkenstrahlen** [comment]
@zaxonus Maybe your issue is related to this? https://github.com/parse-community/parse-server/issues/3857
