### ISSUE TITLE
Corrupt GeoPoint when created from array of Strings

### ISSUE THREAD

**Issue by psineur** [parse-community/parse-server#3597]
### Issue Description

Looks like when creating ParseGeoPoint from Array of strings and saving it in an object - save will complete successfully, however it won't be possible to find object using that GeoPoint.
Adding 0.00000000000001 to Lat & Lng manually in dashboard seems to convert strings to number and fixes the issue.

### Steps to reproduce

In cloudCode beforeSave trigger for any object:

    var gp = new Parse.GeoPoint(["37.8250918","-122.1420862"]);
    request.object.set('location',gp);
    response.success() bla bla

#### Expected Results
Object is saved and can be found using query.withinGeoBox(

#### Actual Outcome

object cannot be found using geo query

### Environment Setup

- **Server**
  - parse-server version: 2.2.22
  - Localhost or remote server?: AWS

**Comment by flovilmart** [comment]
Creating GeoPoints with array of strings, is not documented, therefore not supported, see: http://parseplatform.org/Parse-SDK-JS/api/classes/Parse.GeoPoint.html
