### ISSUE TITLE
Does the SCHEMA cache actually work?

### ISSUE THREAD

**Issue by woodardj** [parse-community/parse-server#3663]
I've just enabled the RedisCacheAdapter, and by default, it seems to be caching users and roles just fine, and according to the TTL that I've set (on parse-server 2.3.7).

However, the __SCHEMA cache defaults to 5 seconds, which I'm not sure would be of any value. There's this note in the definitions file for the defaults: https://github.com/ParsePlatform/parse-server/blob/2.3.7/src/cli/definitions/parse-server.js#L215

If I set this property as a config when initializing ParseServer via:
`        schemaCacheTTL: 60 * 1000,`

I see the keys accumulating in Redis, but every request appears to generate a new …__ALL_KEYS and …__MAIN_SCHEMA key, each of which contains identical data, rather than using the previously cached value.

Is caching the SCHEMA through the redis adapter working for anyone? What have I missed?

**Comment by flovilmart** [comment]
Thanks for reporting the issue, do you have an idea how we could write a failing test for that?

**Comment by flovilmart** [comment]
@woodardj I went back to the CLI options and yes, I believe you missed the `enableSingleSchemaCache`; without that option, the _schema is called upon every request.

**Comment by woodardj** [comment]
Ah, thanks for circling back, @flovilmart — I must have come to a similar conclusion, as I have that `enableSingleSchemaCache` param in my config. I'd be happy to add this to docs somewhere and issue a PR, but I'm not sure the best place.

**Comment by flovilmart** [comment]
enableSingleSchemaCache is true in your config?

**Comment by woodardj** [comment]
It is, I must have found it digging through source; our cache appears to be behaving as expected now. I probably found it and forgot to post back on this issue.

**Comment by flovilmart** [comment]
Awesome :) we probably need to document that. Do you want to add a PR on https://github.com/parse-community/docs/blob/gh-pages/_includes/parse-server/cache-adapters.md or another section about using SchemaCache altogether?

**Comment by woodardj** [comment]
Can do!

-Jonathan

**Comment by flovilmart** [comment]
Thanks! Very appreciated!

**Comment by flovilmart** [comment]
Closing as not an issue with parse-server
