### ISSUE TITLE
Parse.Object.saveAll() does not propagate sessionToken for all objects being saved

### ISSUE THREAD

**Issue by rdbayer** [parse-community/parse-server#3665]
When calling Parse.Object.saveAll(array, {sessionToken: request.user.getSessionToken()}), only the first object would be saved successfully, while later objects would encounter an 'Object not found' error.

If I instead do a Parse.Promise.when where I save each object individually with the sessionToken, it works fine.  Another workaround is using {useMasterKey: true} instead of the session token.

Neither of these workarounds should be necessary though.

**Comment by flovilmart** [comment]
Do you have server logs when running with VERBOSE=1 please?

**Comment by rdbayer** [comment]
Here are what I think are the relevant parts.  Let me know if you're looking for something else.

### Request

```
verbose: REQUEST for [POST] /parse/batch: {
  "requests": [
    {
      "method": "PUT",
      "body": {
        "status": 1
      },
      "path": "/parse/classes/UserTactic/GctM5PJpU0"
    },
    {
      "method": "PUT",
      "body": {
        "status": 1
      },
      "path": "/parse/classes/UserTactic/1QdvG2b2mE"
    },
    {
      "method": "PUT",
      "body": {
        "status": 1
      },
      "path": "/parse/classes/UserTactic/Pczihj8ACH"
    },
    {
      "method": "PUT",
      "body": {
        "status": 1
      },
      "path": "/parse/classes/UserTactic/cB6gmBgHpK"
    },
    {
      "method": "PUT",
      "body": {
        "status": 1
      },
      "path": "/parse/classes/UserTactic/P8PDqVdHwk"
    }
  ]
} method=POST, url=/parse/batch, user-agent=node-XMLHttpRequest, Parse/js1.9.2 (NodeJS 6.9.5), accept=*/*, content-type=text/plain, host=localhost:1337, content-length=652, connection=close, requests=[method=PUT, status=1, path=/parse/classes/UserTactic/GctM5PJpU0, method=PUT, status=1, path=/parse/classes/UserTactic/1QdvG2b2mE, method=PUT, status=1, path=/parse/classes/UserTactic/Pczihj8ACH, method=PUT, status=1, path=/parse/classes/UserTactic/cB6gmBgHpK, method=PUT, status=1, path=/parse/classes/UserTactic/P8PDqVdHwk]
```

### Response

```
verbose: RESPONSE from [POST] /parse/batch: {
  "response": [
    {
      "error": {
        "code": 101,
        "error": "Object not found."
      }
    },
    {
      "error": {
        "code": 101,
        "error": "Object not found."
      }
    },
    {
      "error": {
        "code": 101,
        "error": "Object not found."
      }
    },
    {
      "error": {
        "code": 101,
        "error": "Object not found."
      }
    },
    {
      "success": {
        "updatedAt": "2017-03-23T23:51:36.110Z"
      }
    }
  ]
} response=[code=101, error=Object not found., code=101, error=Object not found., code=101, error=Object not found., code=101, error=Object not found., updatedAt=2017-03-23T23:51:36.110Z]
```

### Extra Info

In case it helps, I should also mention that the context is that this is executing from within a cloud function (Parse.Cloud.define())

**Comment by Jeff2017** [comment]
Same here. I tried parse-server 2.3.2 and 2.3.7.  I didn't use cloud code, just created a https server with databaseURI assigned to 'mongoldb://localhost:27017/parse'

save/saveEventually works fine for each one, but saveAll will save the first one and report 'Object not found' for others.

**Comment by flovilmart** [comment]
@rdbayer @Jeff2017 I just added a repro test case, and it doesn't seem to cause any issue (https://github.com/parse-community/parse-server/pull/3820)

**Comment by rdbayer** [comment]
Thanks for looking into this, @flovilmart.  It looks like the test case you wrote doesn't cover the scenario I was talking about:
a) I was dealing with saving changes to multiple objects, not creating new objects
b) I actually noted that useMasterKey *does* work (it's the current workaround I'm using).  The issue I saw was specifically when using a session token (on objects whose ACL's would fail without that session token obviously, e.g. only a specific user has write permission)

**Comment by rdbayer** [comment]
Whoops, sorry, made my previous (deleted) comment without reading the second part of your test :)

My only additional thought is that in my specific case, the ACL I'm relying on is for a Role, so maybe the bug is Role-specific?

**Comment by flovilmart** [comment]
Ah so you have a role then, not an ACL for a particular user right?

**Comment by rdbayer** [comment]
Yeah, to be even more precise, in my specific repro, the ACL allows permissions for role X and user Y, and the session token (that doesn't seem to get propagated correctly) is for user Z who has role X.

**Comment by flovilmart** [comment]
Updated the test, with User A with Role 'admin', and objects with role read/write, and still no issue.

**Comment by rdbayer** [comment]
I think the only difference left in my case is that the ACL also has read/write permission (for a user other than user A, in addition to the Role read/write permission), so *perhaps* that could somehow be causing an issue?  But if that doesn't cause a repro, I'm out of ideas as to why I see it but you don't :-/

**Comment by flovilmart** [comment]
Do you have Class Level permissions or something else? Again, if you could post a gist with example data, that would help. I can confirm the session token is properly passed through, and _propagated_. The full auth state from the original request is actually propagated to the batch'd elements.

**Comment by flovilmart** [comment]
See: https://github.com/parse-community/parse-server/pull/3820/files#diff-6bb28738fd55b13fe1590425946ed199R427

**Comment by rdbayer** [comment]
Yes, I do indeed have class permissions (public can Create only, Admin role can full read/write, 'user' pointer column can full read/write)

**Comment by flovilmart** [comment]
OK, I'll try to replicate with CLP
