### ISSUE TITLE
Add support for fields in LiveQuery

### ISSUE THREAD

**Issue by rogerhu** [parse-community/parse-server#3671]
### Issue Description

Parse LiveQuery specifications are supposed to take a fields in the query.  Parse server does not handle these fields, nor do the iOS and Android clients.

https://github.com/ParsePlatform/parse-server/wiki/Parse-LiveQuery-Protocol-Specification

```
{
  "op": "subscribe",
  "requestId": 1,
  "query": {
      "className": "Player",
      "where": {"name": "test"},
      "fields": ["name"] // Optional
  },
  "sessionToken": "" // Optional
}

```

https://github.com/ParsePlatform/ParseLiveQuery-iOS-OSX/blob/master/Sources/ParseLiveQuery/Internal/QueryEncoder.swift

https://github.com/ParsePlatform/ParseLiveQuery-Android/pull/18

### Steps to reproduce

Create a Parse Query with fields:

```

@ParseClassName("Message")
public class Message extends ParseObject {
    public static final String USER_ID_KEY = "userId";
    public static final String BODY_KEY = "body";

    public String getUserId() {
        return getString(USER_ID_KEY);
    }

    public String getBody() {
        return getString(BODY_KEY);
    }

    public void setUserId(String userId) {
        put(USER_ID_KEY, userId);
    }

    public void setBody(String body) {
        put(BODY_KEY, body);
    }
}
```

```java
ParseLiveQueryClient<Message> parseLiveQueryClient =
                    ParseLiveQueryClient.Factory.getClient(new URI(ChatApplication.wsURI));

ParseQuery<Message> parseQuery = ParseQuery.getQuery(Message.class);
parseQuery.selectKeys(["userId"]);

            SubscriptionHandling<Message> subscriptionHandling = parseLiveQueryClient.subscribe(parseQuery);
            subscriptionHandling.handleEvents(
   new SubscriptionHandling.HandleEventsCallback<Message>() {
                        @Override
                        public void onEvents(ParseQuery<Message> query,
                                SubscriptionHandling.Event event,
                                Message object)
                        {
          }
}
```

#### Expected Results

Expect only fields to come out.

#### Actual Outcome

All fields are returned.

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.3.7
  - Operating System: MacOS    
  - Hardware:             [FILL THIS OUT]
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): localhost, Heroku

- **Database**
  - MongoDB version: 3.2.1

### Logs/Trace

Include all relevant logs. You can turn on additional logging by configuring VERBOSE=1 in your environment.

**Comment by TimNZ** [comment]
@flovilmart 

I just went looking through JS SDK for fields support on live query subscriptions.

Can we just add an additional 'options' or 'fields' arg to 'subscribe' function in LiveQueryClient.js, and upstream subscribe functions that call it?

**Comment by flovilmart** [comment]
It would require some serverside work, i’ll Be happy to review a Pull Request :) that would be easier than the CLP’s

**Comment by TimNZ** [comment]
Oh, the server isn't complete either?
I was using the Live Query protocol wiki as a guide and hadn't looked at the server code.

Ok, will add to my future dev list :)

**Comment by TimNZ** [comment]
As far as I can tell Parse Server is using subscriptionInfo.fields if specified to filter the response object, before pushing it to the client.

Do you know for a fact that the server needs dev for this?

lib/LiveQuery/Client.js
```
    key: '_pushEvent',
    value: function _pushEvent(type) {
      return function (subscriptionId, parseObjectJSON) {
        var response = {
          'op': type,
          'clientId': this.id
        };
        if (typeof subscriptionId !== 'undefined') {
          response['requestId'] = subscriptionId;
        }
        if (typeof parseObjectJSON !== 'undefined') {
          var fields = void 0;
          if (this.subscriptionInfos.has(subscriptionId)) {
            fields = this.subscriptionInfos.get(subscriptionId).fields;
          }
          response['object'] = this._toJSONWithFields(parseObjectJSON, fields);
        }
        Client.pushResponse(this.parseWebSocket, JSON.stringify(response));
      };
    }
```

**Comment by montymxb** [comment]
@TimNZ we could always use more devs ;)

**Comment by TimNZ** [comment]
Ok, still on my todo list :)

**Comment by TimNZ** [comment]
Submitted pull.
No changes to server required.

https://github.com/parse-community/Parse-SDK-JS/pull/518
