### ISSUE TITLE
Quickstart Guide? SDK? Broken Link

### ISSUE THREAD

**Issue by PunkStarStudios** [parse-community/parse-server#3672]
Ya - I have no where to post this... It's not a code related issue but rather a website issue.

So under all the various SDK sections from the main Parse website (parseplatform.org) there is a reference to a link " head over to the QuickStart guide " which links to "https://parse.com/apps/quickstart"

Well - they all end up just back at the main parseplatform.org site.

Are those pages gone now? They were pretty vital. Pretty hard to start a new Parse project with the SDKs with no quickstart guide.

**Comment by JacobJT** [comment]
All Parse.com links are redirecting to parseplatform.org.  

I've had a PR for the iOS repo open for a while fixing their guide link, and it's gone ignored for some time, despite being a one line change. 

Here's the link to the js guide: http://parseplatform.org/docs/js/guide/

Switch out `js` for `ios` or `android` for their equivalent guide. 

Here's the main wiki for setting up parse-server: https://github.com/ParsePlatform/parse-server/wiki

**Comment by flovilmart** [comment]
I have a Pr in progress for it as well, cleaning up all the dead links. I'll publish it soon

**Comment by JacobJT** [comment]
If you manage the iOS repo you should approve my PR anyway, because it's my first ever open source PR and I'll be much happier if it's approved, rather than rejected haha.

**Comment by flovilmart** [comment]
I don't manage the Parse-UI repo

**Comment by charleskoehl** [comment]
[The js guide](http://parseplatform.org/docs/js/guide/) just disappeared today (returns 404). I was viewing yesterday.

**Comment by felipemartim** [comment]
Not only the js guide, but all the docs disappeared!

**Comment by PunkStarStudios** [comment]
And the API pages

**Comment by montymxb** [comment]
@charleskoehl @felipemartim  You can still get the guides at [docs.parseplatform.org](http://docs.parseplatform.org), albeit it looks rather ugly at the moment due to some missing assets.

The source for the docs is on github [here](https://github.com/parse-community/docs). You can check those out and view them, or save them offline while things are being sorted out.

**Comment by otymartin** [comment]
Major panic attack with these guides constantly disappearing. Is parse.com no longer the main go-to for the docs?

**Comment by flovilmart** [comment]
No, docs.parseplatform.org is

**Comment by flovilmart** [comment]
All links should be valid now, we'll revisit the QuickStart guides probably in the future and update them for the open source project.
