### ISSUE TITLE
Android deviceToken

### ISSUE THREAD

**Issue by jaimeagudo** [parse-community/parse-server#3673]
Sorry for bothering with something probably is not a bug: I faced exactly this same error and I confirm `ParseInstallation.getCurrentInstallation().saveInBackground()` does **NOT** save the deviceToken in Android as per my Dashboard so I assume I cannot target notifications for specific devices/users on android without creating channels/topics. https://stackoverflow.com/questions/37799656/set-devicetoken-in-parse-for-android

I also see a lot of changes on Firebase since the last Android SDK update so I just wonder what is the official way to set the device token for Android devices right now. 

Please give me a hint and I'll update the docs properly so others will not face the same issue

Though is irrelevant, my iOS notifications are working fine and Firebase direct notifications to Android too.

Many thanks

**Comment by rogerhu** [comment]
Right now the Android SDK uses GCM v3.   It will automatically push to your installation when a device token is received.  Even if you are using Firebase you need to follow the setup guide and add the permissions.

http://guides.codepath.com/android/Push-Notifications-Setup-for-Parse

We're in the process of figuring out what to do with Firebase/GCM v3.  For now, device tokens should save by itself if you setup accordingly.

For future, please file ticket directly in the Android SDK board.  Thanks!

**Comment by drinvojka** [comment]
Any update on getting automatic device token for FCM ?
