### ISSUE TITLE
Parse server crash without detailed error in VERBOSE mode

### ISSUE THREAD

**Issue by mmarshak** [parse-community/parse-server#3675]
My Parse server is deployed in AWS for long time, and the last time I changed it was a week ago.
Today out of the blue the serve is down, I deployed a server with VERBOSE=1 and it seems that the server crash upon start and does not provide any information.

This is the production environment, any help will be greatly appreciated.

I am running this server locally connected to the same mongo DB, and it run just fine.

Please include a detailed list of steps that reproduce the issue. Include curl commands when applicable.

#### Expected Results

Server start without errors.

#### Actual Outcome

Server crash upon start.

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.2.25,
  - Operating System:     Linux
  - Hardware:             AWS
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): AWS, node version on AWS 4.4.6

- **Database**
  - MongoDB version: mongoLab
  - Storage engine:  default
  - Hardware:       AWS
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): AWS

### Logs/Trace

var/app/current/node_modules/parse-server/lib/ParseServer.js:460
            throw err;
            ^

TypeError: this is not a typed array.
    at Function.from (native)
    at Object.<anonymous> (/var/app/current/node_modules/parse-server/node_modules/ws/lib/PerMessageDeflate.js:8:24)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/var/app/current/node_modules/parse-server/node_modules/ws/lib/WebSocket.js:16:27)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/var/app/current/node_modules/parse-server/node_modules/ws/index.js:9:19)

npm ERR! Linux 4.4.14-24.50.amzn1.x86_64
npm ERR! argv "/opt/elasticbeanstalk/node-install/node-v4.4.6-linux-x64/bin/node" "/opt/elasticbeanstalk/node-install/node-v4.4.6-linux-x64/bin/npm" "start"
npm ERR! node v4.4.6
npm ERR! npm  v2.15.5
npm ERR! code ELIFECYCLE
npm ERR! parse-server-example@1.4.0 start: `VERBOSE=1 node index.js`
npm ERR! Exit status 7
npm ERR! 
npm ERR! Failed at the parse-server-example@1.4.0 start script 'VERBOSE=1 node index.js'.
npm ERR! This is most likely a problem with the parse-server-example package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     VERBOSE=1 node index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs parse-server-example
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls parse-server-example
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/app/current/npm-debug.log

> parse-server-example@1.4.0 start /var/app/current
> VERBOSE=1 node index.js

**Comment by rowntreerob** [comment]
i face very similar errors running parse-server locally after an upgrade on the server ( 2.2 -> 4.4 ) and what i found is that using "sudo" as prefix to the "start" eliminated the errors on server startup. Note that in past , i never had to sudo the command starting parse-server.

**Comment by mmarshak** [comment]
Thanks @rowntreerob.
I solved the problem by upgrading node from 4.4.6 to 5.x on AWS and the error vanish. Looks like one of the nam packages that Parse using stop working in node 4.4.6.

**Comment by flovilmart** [comment]
Closing as resolved.
