### ISSUE TITLE
A wildcard '*' cannot be used in the 'Access-Control-Allow-Origin' header when the credentials flag is true

### ISSUE THREAD

**Issue by hbkrunal** [parse-community/parse-server#3693]
### Issue Description

we are getting below error as explained on [parse server example issue](https://github.com/parse-community/parse-server-example/issues/339)

`A wildcard '*' cannot be used in the 'Access-Control-Allow-Origin' header when the credentials flag is true`

We have found that on [middlewares line](https://github.com/parse-community/parse-server/blob/master/src/middlewares.js#L213) when we replace `*` with the domain we want  then errors is resolved so want to know if there is any options from where we can change the response headers `Access-Control-Allow-Origin` value for parse response.

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : In our package,json it says `"parse-server": "*"`
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Heroku, 

- **Database**
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): mLab

**Comment by flovilmart** [comment]
Is that causing any issue with you?

**Comment by natanrolnik** [comment]
I'm closing this issue for now, as there was no reply for more than 2 weeks.

Please let us know if this is happening in the latest version (2.4.1) of parse-server. If so, provide more information - like how initialize your server, server logs, and we will reopen.
