### ISSUE TITLE
Cant post/save to parse based application

### ISSUE THREAD

**Issue by s-dm** [parse-community/parse-server#3698]
Hi, I am pretty darn stuck on this one.. 

I use a system named NearmeCMS that uses parse as a backend. I have set an app_id and master_key as described, but not all things are working as they should. 

The app is built on ionic2 and is a location based app, where you can add places and reviews. The review part work, everyone can post reviews, but adding a new place, editing profiles and uploading images are not working. 

Is it a setting in the parse server that is the problem? 

or is it my ionic app? 

here is the config file for my ionic app: https://github.com/s-dm/PubloApp/blob/master/main.js

**Comment by flovilmart** [comment]
You should probably reach out to the authors of that system. 

Also, have a look at our docs, http://docs.parseplatform.org
