### ISSUE TITLE
MongoRocks instructions?

### ISSUE THREAD

**Issue by iPaulPro** [parse-community/parse-server#3700]
Trying to find this Parse guide on using MongoRocks but it's no longer in the wiki. The docs have dead links everywhere.

**Comment by flovilmart** [comment]
What was the original link?

**Comment by flovilmart** [comment]
It's there: http://docs.parseplatform.org/parse-server/guide/#using-mongodb--rocksdb

**Comment by iPaulPro** [comment]
Great, thanks.

Blog post [here](http://blog.parse.com/learn/engineering/migrating-your-parse-app-to-mongorocks/) pointed to it being at https://github.com/ParsePlatform/parse-server/wiki/MongoRocks
