### ISSUE TITLE
fetch records corresponding to each user when queried with admin role

### ISSUE THREAD

**Issue by saikiran644** [parse-community/parse-server#3703]
Hi,
I need to fetch a particular class(say **Class A**) records corresponding to each user in my parse server, when queried with admin role  which have access to all the records in that particular class (**Class A**).

How can I do that?
Quick help would be greatly appreciated. :-)

**Comment by acinader** [comment]
@saikiran644 can you please ask on stackoverflow: http://stackoverflow.com/questions/tagged/parse-server

If you put the link here, I'll answer it for you quickly ;)
