### ISSUE TITLE
Parse takes to much time to responed to client

### ISSUE THREAD

**Issue by zack1991** [parse-community/parse-server#3704]
Hi, I am using parse server on my stand alone server(rackspace) for my game.  
Server configuaration is - 

Server Configuaration : Rackspace server, 4 GB RAM, 2 core
DB Server : Mongo Atlas, 2GB RAM

I am using cluster also.

index.js :- 

var express = require('express');
var ParseServer = require('parse-server').ParseServer;
var path = require('path');
var fs = require('fs');
var cluster = require('cluster');
if (cluster.isMaster) {
    var numWorkers = require('os').cpus().length;
    for (var i = 0; i < numWorkers; i++) {
        cluster.fork();
    }
    cluster.on('online', function (worker) {
        console.log('Worker ' + worker.process.pid + ' is online');
    });
    cluster.on('exit', function (worker, code, signal) {
        console.log('Worker ' + worker.process.pid + ' died with code: ' + code + ', and signal: ' + signal);
        console.log('Starting a new worker');
        cluster.fork();
    });
} else {

var databaseUri = process.env.DATABASE_URI || process.env.MONGODB_URI;
	if (!databaseUri) {
	  console.log('DATABASE_URI not specified, falling back to localhost.');
	}
	var api = new ParseServer({
	  //databaseURI: databaseUri || '[mongodb url]',	    
	  cloud: process.env.CLOUD_CODE_MAIN || __dirname + '/cloud/main.js',
	  appId: process.env.APP_ID || '[My app id]',
	  masterKey: process.env.MASTER_KEY || '[My master key]', //Add your master key here. Keep it secret!
	  serverURL: process.env.SERVER_URL || '[My parse url]',  // Don't forget to change to https if needed
	  liveQuery: {
	    classNames: ["GameUsers"] 
	  },
	  //node_env: "production",
	  //logLevel: 'error'
	});	

	var app = express();

	// Serve static assets from the /public folder
	app.use('/public', express.static(path.join(__dirname, '/public')));

	//Register for getting ip address in request
	app.use(function(req, res, next) {  
	  req.headers['x-real-ip'] = req.ip;
	  next();
	});

	// Serve the Parse API on the /parse URL prefix
	var mountPath = process.env.PARSE_MOUNT || '/parse';
	app.use(mountPath, api);

	// Parse Server plays nicely with the rest of your web routes
	app.get('/', function(req, res) {
	  res.status(200).send('I dream of being a website.  Please star the parse-server repo on GitHub!');
	});

	// There will be a test page available on the /test path of your server url
	// Remove this before launching your app
	app.get('/test', function(req, res) {
	  res.sendFile(path.join(__dirname, '/public/test.html'));
	});

	var port = process.env.PORT || 1337;
	var options = {
	    key:    [My key],
	    cert:   [My cert],
	    ca:     [My CA],
	    requestCert:        true,
	    rejectUnauthorized: false
	};
	var httpServer = require('https').createServer(options, app);
	httpServer.listen(port, function() {
	    console.log('parse-server-example running on port ' + port + '.');
	});

	// This will enable the Live Query real-time server
	ParseServer.createLiveQueryServer(httpServer);
}

I have parse cloud code "ping" which code is given below.

main.js

//Ping request from client
Parse.Cloud.define("ping", function (req, res) {
  try {
     if (req.user !== undefined) {
        if (!req.params.hasOwnProperty(GameConstants.USER_ID)) {
           req.params.user_id = req.user.get("username");
        }
        LoginHelper.updateUserSessionEndDateTime(req, function (error, gameUser) {
            if (error) {
               res.success({result: 0, custom_error_code: error.code, custom_error_message: error.message,    stacktrace: error.stack});
            } else {
               res.success({result: 1});
            }
       });
    } else {
       res.success({result: 0, custom_error_code: CustomErrorCode.INVALID_USER_ERROR, custom_error_message: "Inavalid user"});
    }
  } catch (e) {
     res.success({result: 0, custom_error_code: e.code, custom_error_message: e.message, stacktrace: e.stack});
 } finally {
  console.log("======ping=========");
  }
});

LoginHelper.js

updateUserSessionEndDateTime: function (req, callback) {
var query = new Parse.Query(Parse.Object.extend(GameConstants.GAME_USERS));
query.select("session_end_date_time");
query.equalTo(GameConstants.OBJECT_ID, req.params.user_id);
query.first({
success: function (gameUser) {
if (typeof gameUser !== "undefined") {
console.log("updateUserSessionEndDateTime data===========> " + JSON.stringify(gameUser));
gameUser.set(GameConstants.SESSION_END_DATE_TIME, new Date());
gameUser.save(null, {
success: function (gameUser) {
console.log("updateUserSessionEndDateTime.save.success===========> " + JSON.stringify(gameUser));
callback(null, gameUser);
},
error: function (error) {
console.log("updateUserSessionEndDateTime.save.error===========> " + error.message);
callback(error);
}
});
} else {
console.log("updateUserSessionEndDateTime.sessionData-------> undefined ");
callback(null, null);
}
},
error: function (error) {
console.log("updateUserSessionEndDateTime.error===========> " + error.message);
callback(error);
}
});
}

Now i am checking the performance of parse server with js client by sending 1000 ping request from client :-
for (var i = 0; i < 1000; i++) {
ping();
console.log("Ping-------> " + i);
}

function ping() {
//debugger;
Parse.Cloud.run("ping", {user_id: "1085075762"}, {
success: function (result) {
// Show result as an alert
console.log(result);
},
error: function (error) {
//debugger;
console.log("ping=======>Error code----------> " + error.code + ", Error message----------> " + error.message);
}
});
}

![ping response](https://cloud.githubusercontent.com/assets/26978206/24896808/31e03ee4-1eb4-11e7-9f30-b47378351c86.png)

My last ping request response comes in 55.65 sec. Why parse server is not handling the request very fast.

**Comment by flovilmart** [comment]
So, in order to run load tests, I suggest you don't use chrome, because they limit the number of open connections. I personally use `ab` (Apache Benchmark).

I've run the following tests:

1. declare a cloud function:

```
Parse.Cloud.define('test', (req, res) => {
  const obj = new Parse.Object('AnObject');
  obj.set('random', Math.random());
  obj.set('randomString', Math.random()+'');
  obj.save().then(() => {
    res.success(obj);
  });
});
```

2. Start parse-server (latest) with a local DB

```
node --inspect lib/cli/parse-server --appId hello --masterKey world --cloud ~/src/parse-load-test/main
```

3. use ngrok to do an internet round-trip
```
ngrok http 1337
```

### 1000 requests, concurrency 10:

```
/usr/local/bin/ab -n 1000 -c 10 -H 'X-Parse-Application-Id: hello' -H 'X-Parse-Master-Key: world' -T 'application/json' -p ./empty-m POST http://86e5d7f3.ngrok.io/parse/functions/test
Time taken for tests:   22.028 seconds
Requests per second:    45.40 [#/sec] (mean)
Time per request:       220.280 [ms] (mean)
Time per request:       22.028 [ms] (mean, across all concurrent requests)

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:       31   39  53.7     35    1242
Processing:    97  180  40.1    175     426
Waiting:       97  180  40.1    175     426
Total:        130  219  66.0    212    1400
```

### 1000 requests, concurrency 50:

```
/usr/local/bin/ab -n 1000 -c 50 -H 'X-Parse-Application-Id: hello' -H 'X-Parse-Master-Key: world' -T 'application/json' -p ./empty-m POST http://86e5d7f3.ngrok.io/parse/functions/test

Time taken for tests:   17.752 seconds
Requests per second:    56.33 [#/sec] (mean)
Time per request:       887.593 [ms] (mean)
Time per request:       17.752 [ms] (mean, across all concurrent requests)

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:       31   40  49.5     36    1223
Processing:   159  833 128.7    820    1319
Waiting:      158  833 128.7    820    1319
Total:        194  873 139.2    857    2099
```

This is as fast/slow as any expressjs app IMHO.

**Comment by cinder92** [comment]
hello i have same issue, but, i have a database un `mlabs` i only want to retrive 10 posts from 1 category, this takes 20 - 27 seconds per request.

can you help me please? maybe im creating a bad database request, this is my code.

Cloud Function

```
Parse.Cloud.define("getCategoryData", HomeController.getCategoryData);
```

getCategoryData

```
export function getCategoryData(req,res){
	let promises = [];
	let data = req.params;

    promises.push(Querys.getMarquee());
    promises.push(Querys.getCategories());
	promises.push(Querys.getNews(data.slug,10,data.pageNumber,'',true));
    promises.push(Querys.getBanner(470,590,"inicio")); // cabecera
    promises.push(Querys.getBanner(100,300,"inicio"));
    promises.push(Querys.getBanner(590,800,"noticias"));

    Parse.Promise.when(promises).then((results) => {
	  	let marquee = results[0];
	  	let categories = results[1];
	  	let posts = results[2][0];
	  	let pagination = results[2][1];
	  	let bannerCabecera = results[3];
	  	let bannerSidebar = results[4];
	  	let bannerBottom = results[5];

	  	res.success({
	  		posts,
	  		pagination,
	  		categories,
	  		marquee,
	  		bannerCabecera,
	  		bannerSidebar,
	  		bannerBottom
	  	});

    });
}
```

Database function

```
export function getNews(category = "",limit = 5,page = 0,postTitle = "", hasCount = false){
        //category = "black-stone";
	let promise = new Promise((resolve,reject) => {
		let key = category+"-"+limit+"-"+page+"-"+postTitle;

		cache.get(key,(err,value) => {
			if(!err){
				if(value == undefined){
					let query = new Parse.Query("Category");

					if(category != ""){
						query.equalTo('slug',category);
					}

					query.find({
					  success: (categories) => {

						  let catGuid = categories[0].get('guid');

						  const queryNews = new Parse.Query("News");
						  queryNews.descending('publishedAt');

						  if(postTitle == ""){
							  queryNews.containedIn('categories',categories);
							  queryNews.contains('title',postTitle);
						  }

						  let pagination;
						  let limitResults = limit > 0 ? limit : 10;

						  if(hasCount){
							  const countQuery = new Parse.Query('News');
							  countQuery.limit(0);
							  countQuery.count().then(totalNews => {

								 pagination =
								 Functions.getPagination(
									  totalNews,
									  5,
									  limitResults,
									  page
								 );

								 queryNews.skip((page - 1) * limitResults);
								 queryNews.limit(limitResults);

		   						  queryNews.find({
		   							  success : (news) => {

		   								  let posts = Functions.formatNews(news,catGuid);

		   								  cache.set( key , [posts,pagination] ,(err,success) => {
		   									  if( !err && success ){
		   										  resolve([posts,pagination]);
		   									  }else{
		   										  reject(err);
		   									  }

		   								  });

		   							  },error : (err) =>{
		   								  reject(err);
		   							  }
		   						  });
							  });
						  }else{
							  pagination = {};
							  queryNews.limit(limitResults);

							  queryNews.find({
								  success : (news) => {

									  let posts = Functions.formatNews(news,catGuid); // this retrive a formated object
									  cache.set( key , [posts,pagination] ,(err,success) => {
										  if( !err && success ){
											  resolve([posts,pagination]);
										  }else{
											  reject(err);
										  }

									  });

								  },error : (err) =>{
									  reject(err);
								  }
							  });
						  }
					  },
					  error : (error) => {
						  reject(err);
					  }
					});

				}else{
					//si existe el obj con ese key
					let paginationCached = value[1];
					let postsCached = value[0];

					resolve([postsCached,paginationCached]);
				}
			}else{
				reject(err);
			}
		});
	});

	return promise;

}
```

**Comment by flovilmart** [comment]
You should prob ably check your indexes in the database.
