### ISSUE TITLE
Can you please do a release soon?

### ISSUE THREAD

**Issue by funkenstrahlen** [parse-community/parse-server#3705]
I'd really like to use the push notification support for macOS in my app. It has been added in `parse-push-adapter` release 1.3 and is already part of the current master.

Please do a new official release soon, so I can use this code in my parse backend.

**Comment by flovilmart** [comment]
I was about to do it this weekend but got caught on by fixing the docs repo. Stay tuned!

**Comment by funkenstrahlen** [comment]
Thanks for the quick response! Happy to hear a release is planned soon :)

**Comment by phranck** [comment]
Yap, that's good news. Happy to hear we can use it soon... 😉

**Comment by flovilmart** [comment]
Yes sorry for the delays... Been trapped with sooo many things, there is one PR we should merge before, awaiting review then I'll go ahead.

**Comment by natanrolnik** [comment]
@funkenstrahlen 2.3.8 is available

**Comment by funkenstrahlen** [comment]
Awesome! Thanks! :)

**Comment by phranck** [comment]
@natanrolnik And push notifications for macOS are working like a charm! Thank's @funkenstrahlen!

**Comment by flovilmart** [comment]
That's great to hear! We should probably update the docs :) @funkenstrahlen, would you take care of it?

**Comment by funkenstrahlen** [comment]
@flovilmart Where can I edit the docs?

**Comment by flovilmart** [comment]
on https://github.com/parse-community/docs repo
