### ISSUE TITLE
[idea] Configure Mongo maxTimeMS on a per-query basis?

### ISSUE THREAD

**Issue by yuzeh** [parse-community/parse-server#3707]
For a parse-server talking to Mongo, we can set `maxTimeMS` for all queries, and it is applied on all queries.

I've come across a situation where I would like to set `maxTimeMS` differently depending on the query. For example, queries that end up serving data to end-users likely want a lower timeout than ETL jobs.

Is there value in adding this to the `ParseQuery` interface? If not, what would you recommend as an alternative? (For example, being able cancel a Mongo query through the Promise returned by `ParseQuery.find` also works for me.)

**Comment by flovilmart** [comment]
What do you mean by the ParseQuery interface? In the client?

**Comment by yuzeh** [comment]
In this case I my proposal would be a change in the JS SDK (perhaps this is the wrong forum) but my goal is to be able to do this from an app running on parse-server.

**Comment by flovilmart** [comment]
I'm not sure exposing timeout options in the wild is such a great practice, would you do it on your backend?

**Comment by yuzeh** [comment]
Yeah, that's a good point.

**Comment by flovilmart** [comment]
While I like the idea of specifying additional parameters for mongo queries (like read from secondary etc...) my 2 cents is that the global setting should be enough, or that we provide a hook somehow to customize every single read/writes
