### ISSUE TITLE
UWS Dependency Fails

### ISSUE THREAD

**Issue by kishanio** [parse-community/parse-server#3709]
Latest release for Parse-Server on npm package manager i.e. 2.3.7 refers `uws@^0.13.0` as dependency.Turns out UWS took down all the versions <0.14 from NPM repos.  

Now build for parse-server fails via. NPM.

So does anyone know what's the protocol to request release?

**Comment by flovilmart** [comment]
2.3.8 has just been released, with the updated dependency. https://www.npmjs.com/package/parse-server

**Comment by kishanio** [comment]
Thanks @flovilmart
