### ISSUE TITLE
Why Parse creates new Config and DatabaseController for every request?

### ISSUE THREAD

**Issue by benishak** [parse-community/parse-server#3716]
https://github.com/parse-community/parse-server/blob/master/src/middlewares.js#L110

Why not initialize it once at app startup and use it all time ? what happens after the request has been finished ? does parse destroy the DatabaseController somewhere?

**Comment by flovilmart** [comment]
It isn't, it's just getting it from the cache: https://github.com/parse-community/parse-server/blob/master/src/Config.js#L21

**Comment by benishak** [comment]
I see now AppCache is always InMemoryCache no matter the Cache Adapter was choosen!

But why load it that way instead of accessing it in different way through ParseServer class ?

**Comment by steven-supersolid** [comment]
AppCache stores application config and references to the various controllers so I think it makes sense to be in memory and not use a different cache adapter.

If you have a performance concern then please open a PR with suggested changes as I think that will be clearer and we can discuss further there once we know what you have in mind.
