### ISSUE TITLE
WildCard query in parse database

### ISSUE THREAD

**Issue by saikiran644** [parse-community/parse-server#3725]
I would like to know is there a way that I can perform a wildcard query in the parse database?

The solution in python would be greatly appreciated. Thanks in advance. :-)

**Comment by bohemima** [comment]
use $regex

http://docs.parseplatform.org/rest/guide/#query-constraints

Also see http://blog.parse.com/learn/engineering/implementing-scalable-search-on-a-nosql-backend/ if that fits your need, as regex is generally a horrible idea.

> Queries on String Values
> 
> If you're trying to implement a generic search feature, we recommend taking a look at this blog post: Implementing Scalable Search on a NoSQL Backend.
> Use the $regex operator to restrict to string values that match a regular expression. Most regular expression queries in Parse are heavily throttled due to performance considerations. Use case sensitive, anchored queries where possible. Similar to a MySQL LIKE operator, anchored queries are indexed so they are efficient for large datasets. For example:


```
# Finds barbecue sauces that start with "Big Daddy"
curl -X GET \
  -H "X-Parse-Application-Id: ${APPLICATION_ID}" \
  -H "X-Parse-REST-API-Key: ${REST_API_KEY}" \
  -G \
  --data-urlencode 'where={"name":{"$regex":"^Big Daddy"}}' \
  https://api.parse.com/1/classes/BarbecueSauce
```

**Comment by saikiran644** [comment]
Thank you so much for the response @bohemima 
I've tried this but the performance is not that good.

**Comment by bohemima** [comment]
yeah, "regex is generally a horrible idea".

Look at the blog post linked above and make sure you add a index on that field as well.
