### ISSUE TITLE
Security issue when using js sdk of parse server

### ISSUE THREAD

**Issue by zack1991** [parse-community/parse-server#3726]
Hi,
I am little bit confused about calling parse cloud functions from JS SDK. When i am using js sdk for calling cloud functions its showing application id and master key(if useMasterKey true). If anyone copy these information pass seprate request to these cloud function using ajax, then they can hit our services frequently and my server gets down.

Please help me to avoid and prevent these security breaches.

Thanks

**Comment by bohemima** [comment]
Have a look at the following blog series, they are still relevant (too some degree);

http://blog.parse.com/learn/engineering/parse-security-i-are-you-the-key-master/
http://blog.parse.com/learn/engineering/parse-security-ii-class-hysteria/
http://blog.parse.com/learn/engineering/parse-security-iii-are-you-on-the-list/
http://blog.parse.com/learn/engineering/parse-security-iv-ahead-in-the-cloud/
http://blog.parse.com/learn/engineering/parse-security-v-how-to-make-friends/

From the Javascript SDK (on client side) master key should never be used (or even be possible to use)

**Comment by natanrolnik** [comment]
Master key should never be shipped in clients/browser. Only used in the server.
