### ISSUE TITLE
Cloud Code .equalTo query not working

### ISSUE THREAD

**Issue by hackin247** [parse-community/parse-server#3727]
`
      var Activity = Parse.Object.extend("Activity");  
      var query = new Parse.Query(Activity);
      query.equalTo('photo', "xGlWQgUaN8");
      query.find({useMasterKey:true}).then(function(activities) { ... }
`

photo column is a pointer to a photo object (see AnyPic schema) and it used to work.   But now it returns zero objects.   Would appreciate any input.  Thanks

**Comment by hackin247** [comment]
comparing string with a pointer is a no go.  Weird, because I wear this used to work before. ;-)

**Comment by flovilmart** [comment]
Yeah, this should work. And we can interpolate it correctly base on the schema server side I believe

**Comment by flovilmart** [comment]
@hackin247 you don't even need to 'fetch' the photo, you can create an Object 'withoutData' and with it's objectId (that's basically what a pointer is).

We'll have a look to bring back string <-> pointer interpolation based on the schema column.
