### ISSUE TITLE
Mass Push Says FAILED in Dashboard

### ISSUE THREAD

**Issue by adambarghouthi** [parse-community/parse-server#3729]
Hi guys, I'm using Azure deployment of Parse Server. Recently push notifications stopped working and I found the fix. But sending a push to all installations is showing "FAILED" in the Parse dashboard and I can verify that no one is receiving them. 

I have a function for sending individual pushes:

```
Parse.Cloud.define("sendUserPushNotification", function(request, response) {
    var query = new Parse.Query(Parse.Installation);
    query.equalTo('userID', request.params.userID);
    
    Parse.Push.send({
        where: query,
        data: request.params.data
    }, { useMasterKey: true }).then(function() {
        console.log('PUSH SUCCESSFUL');
        response.success('PUSH SUCCESSFUL');
    }, function(error) {
        console.log('PUSH ERROR', error);
        response.error(error);
    });
});
```

And for mass push which is the one returning success, yet showing "FAILING" in dashboard: 

```
Parse.Cloud.define("sendSegmentPushNotification", function(request, response) {
    var query = new Parse.Query(Parse.Installation);
    
    Parse.Push.send({
      where: query,
      data: request.params.data
    }, { useMasterKey: true }).then(function() {
       console.log('PUSH SUCCESSFUL');
       response.success('PUSH SUCCESSFUL');
    }, function(error) {
        console.log('PUSH ERROR', error);
        response.error(error);
    });
});
```

It doesn't seem to be the code in any way, is it something with parse server? 
Thanks!

**Comment by dee-lewis** [comment]
Are your APNS / Push certificates valid?

**Comment by adambarghouthi** [comment]
@dee-lewis, yes because individual pushes are getting sent out and received as mentioned about the code with `query.equalTo('userID', request.params.userID);`.. but the mass push to all installations whether with or without deviceToken FAILS at all times..

**Comment by flovilmart** [comment]
@adambarghouthi can you:

- provide the logs when running with VERBOSE=1, this will help understanding the issue with your mass push
- perhaps update to 2.4.0

**Comment by adambarghouthi** [comment]
@flovilmart
Calling Parse.Push.send returns success all the time, but in Parse Dashboard the status for the specific mass push is FAILED. So I'm not sure, this has been going on since end of March. Any big events happened at end of March?

**Comment by flovilmart** [comment]
Can you try to use 2.4.1, we probably fixes that particular issue.

**Comment by flovilmart** [comment]
@adambarghouthi we refactored completely the push infrastructure for better handling of large pushes, if you can provide the logs when sending push with VERBOSE=1 that would be really helpful to troubleshoot!

**Comment by adambarghouthi** [comment]
@flovilmart will do, I'm just not familiar where in the code to enable verbosity. Can you guide me please?

**Comment by flovilmart** [comment]
The simplest is to set the VERBOSE environment variable to 1 (VERBOSE=1 ...)

OR

you can pass the `verbose: true` in your parse server init code:

```

server = new ParseServer({
  ... ,
  verbose: true
});

```

**Comment by adambarghouthi** [comment]
@flovilmart I got this when sending a push via dashboard:

```
ActivityId: d73490db-0000-0000-0000-000000000000, Request URI: rntbd://100.111.102.182:16700/apps/d54f0cf3-23d7-4050-9810-99d319d441a8/services/02b3305d-7c63-4fae-b1c9-fcbe005820ea/partitions/dc81dc23-d1c3-4ce8-a6bf-1a54560bfcdc/replicas/131397260764598590p
    at Function.MongoError.create (D:\home\site\wwwroot\node_modules\mongodb-core\lib\error.js:31:11)
    at D:\home\site\wwwroot\node_modules\mongodb-core\lib\connection\pool.js:462:72
    at authenticateStragglers (D:\home\site\wwwroot\node_modules\mongodb-core\lib\connection\pool.js:410:16)
    at null.messageHandler (D:\home\site\wwwroot\node_modules\mongodb-core\lib\connection\pool.js:444:5)
    at TLSSocket.<anonymous> (D:\home\site\wwwroot\node_modules\mongodb-core\lib\connection\connection.js:306:22)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at TLSSocket.Readable.push (_stream_readable.js:111:10)
    at TLSWrap.onread (net.js:536:20)
```

**Comment by flovilmart** [comment]
yep looks like it!

**Comment by adambarghouthi** [comment]
@flovilmart Thank you! Managed to scale it up to fix that :)

**Comment by flovilmart** [comment]
Good news! So there's no issue on your side?

**Comment by adambarghouthi** [comment]
@flovilmart Nope everything's smooth

**Comment by flovilmart** [comment]
So I can close that issue!
