### ISSUE TITLE
ParseLiveQueryServer options object

### ISSUE THREAD

**Issue by maximeloizeau** [parse-community/parse-server#3731]
### Issue Description

When you change default options for the live query server in the Parse config object like this:
```
new ParseServer({
  databaseURI: databaseUri || 'mongodb://localhost:27017/dev',
  liveQuery: {
    classNames: ['Bla', 'Bla', 'Bla'],
    redisURL: process.env.REDIS_URL
  },
})
```

And then start the live query server like this as mentionned in the documentation:
`ParseServer.createLiveQueryServer(httpsServer);`

It creates the following issue:
- the Publisher is created correctly with these options (see the LiveQueryController being initialised with the correct option object: [here](https://github.com/parse-community/parse-server/blob/907b160fc7317b016fc728a1b30ce3d24ead7d73/src/ParseServer.js#L207))
- the Subscriber is not created with the correct options, it uses the default ones (see the ParseLiveQueryServer getting the options from the `createLiveQueryServer` function instead of the Parse config object above: [here](https://github.com/parse-community/parse-server/blob/907b160fc7317b016fc728a1b30ce3d24ead7d73/src/ParseServer.js#L389))

So in my case, the publisher published to Redis and the subscriber listened Nodejs 'message' events (default EventSubmitter adapter)

I understand I may have misunderstood the documentation or missed anything else, but it should be fixed in the Parse code OR in the documentation to explain it a bit better I guess.

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.3.5
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): AWS and local

**Comment by flovilmart** [comment]
You probably need to pass the redisURL as well in the createLiveQueryServer call.

See the scalability section: http://docs.parseplatform.org/parse-server/guide/#live-queries

**Comment by maximeloizeau** [comment]
I missed that part of the documentation, only saw the first sections. Thanks!

**Comment by flovilmart** [comment]
No problem!
