### ISSUE TITLE
Query all parse file

### ISSUE THREAD

**Issue by tinocosta84** [parse-community/parse-server#3732]
How does one Query all parse files?

**Comment by dee-lewis** [comment]
You could look at https://github.com/parse-server-modules/parse-files-utils

It checks the schema for classes that has FILE fields and returns the url for those files.

**Comment by natanrolnik** [comment]
You can take a look here to understand better how files might be queried https://github.com/parse-community/parse-server/issues/1023
Also, @dee-lewis suggested a tool that can list the files used.
