### ISSUE TITLE
Geo-spatial queries return a maximum of 1000  results even with higher limits

### ISSUE THREAD

**Issue by dpoetzsch** [parse-community/parse-server#3733]
### Issue Description

With mongo db version 3.0.12 and 3.0.14 a geo query that also has an order specified always returns a maximum number of 1000 results.

Note: without specifying the order everything works fine.

Also, mongo db version 3.2.x fixes this issue.

Maybe this is related to https://github.com/parse-community/parse-server/issues/999#issuecomment-292253291

### Steps to reproduce

You need a table with over 1000 objects. Then:

```javascript
new Parse.Query("Item")
    .withinKilometers("location", new Parse.GeoPoint(50, 10), 4000)
    .descending("createdAt")
    .limit(5000)
    .find()
```
#### Expected Results

I'd expect a maximum number of 5000 object to be returned.

#### Actual Outcome

A maximum number of 1000 objects is returned.

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.3.8
  - Operating System:     Fedora Linux
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Reproduced on Localhost, Heroku & Scalingo

- **Database**
  - MongoDB version: 3.0x & 3.2.x
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): Localhost, mlab, scalingo

**Comment by flovilmart** [comment]
So that's an issue with mongodb right?

**Comment by dpoetzsch** [comment]
Well it might. I was not sure, I couldn't find any information on that 1000-limit in the mongodb docs. I'm not even sure if it's a really a bug (could also by by design or because of a misconfiguration or whatever?). I hoped anyone here might have more insight what could be the reason for this.

However, if it is not a bug, I thought it would be good to at least update parse's documentation.

**Comment by flovilmart** [comment]
We don't apply limits by default, if the query sent to the mongo driver actually has a limit higher than 1000 and from the driver we get 1000 results, this is an issue with either the driver or mongodb itself.

**Comment by flovilmart** [comment]
Closing as related to mongodb pre 3.2. Feel free to open a PR in the docs around the geo queries if you feel it should be described.
