### ISSUE TITLE
After upgrade to 2.3.7 . Can not find sender for push type ios 

### ISSUE THREAD

**Issue by tjlian616** [parse-community/parse-server#3736]
### Issue Description
I was on 2.3.2 and iOS push works fine. Today I upgraded to 2.3.7 and iOS push no longer works. I changed back to 2.3.2 and it worked. There is no other change.

Here is the log error
Can not find sender for push type ios

Here is my configuration
  push:{
    ios: {
      pfx: __dirname+'/files/Push.p12',
      passphrase: '', 
      cert: '', 
      key: '', 
      bundleId: 'com.xxxx.app.xxxx', 
      production: true
    }
  },

Please help me understand what changes for push between 2.3.2 and 2.3.7. And what should I do to make it work on the new version?

**Comment by flovilmart** [comment]
Can you provide the logs for both 2.3.2 and 2.3.7 when running with VERBOSE=1?

**Comment by flovilmart** [comment]
@tjlian616 any update on that?

**Comment by Valdezmj** [comment]
@tjlian616 @flovilmart Has this been addressed? I am currently running into the issue with 2.4.0 not able to send push notifications from the dashboard to an iOS device.  It connects but cannot route to the device token.

**Comment by flovilmart** [comment]
@Valdezmj without more logs, that's impossible to know what to address.

**Comment by mzgnr** [comment]
@tjlian616 did you fix the issue ? I'm having the same issue

**Comment by sureshkodur** [comment]
hi, I have the same issue
