### ISSUE TITLE
Passing a *different* object to beforeSave doesn't work

### ISSUE THREAD

**Issue by mrmarcsmith** [parse-community/parse-server#3739]
We use GitHub Issues for bugs.

### Issue Description

Sometimes when a user passes a NEW object I instead want those changes to be propagated to an EXISTING object instead. 
I have tried:
a. setting request.object.id
b. creating a new object with the correct id and coping the keys over and then passing the object like so response.success(actualJobToSave);

### Steps to reproduce
Here is an example:
```
Parse.Cloud.beforeSave("Vote", function(request, response) {
Parse.Promise.as()
  .then(function() {

        var itemQuery = new Parse.Query('Vote');

        itemQuery.equalTo('userWhoCastVote', request.user);
        itemQuery.equalTo('questionId', request.params.questionId);
        return itemQuery.find({useMasterKey: true}).then(null, function(error) {
          //there was an error querying
          return Parse.Promise.error('Sorry, An error occurred');
        });
      }
    })
  .then(function(alreadyVotedVote) {
       if(alreadyVotedVote){
          //Here is where I need to change the id of the request.object so that 
         a. users can't vote multiple times
         b. if a user changes their vote the change will be saved to the original vote
        
          //i have tried
         request.object.id = alreadyVotedVote.id;
         request.original.id = alreadyVotedVote.id;

         //i have also tried
         var jsonObject = request.object.toJSON();
         delete jsonObject.id;
         jsonObject.id = alreadyVotedVote.id;
         jsonObject.className = object.className;
         var newParseObject = Parse.Object.fromJSON(jsonObject)
         response.success(newParseObject);

        //but nothing seems to work!
        // all of the changes get saves to the "new" object
        }
  });

});

```

#### Expected Results
I expect the changes to be saved to the existing object.

#### Actual Outcome
The changes are saved to a new object creating an unwanted duplicate.

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.3.7
  - Operating System:     Ubuntu 16.04.2 LTS (GNU/Linux 4.4.0-72-generic x86_64)
  - Hardware:             Digital Ocean doesn't tell me
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Digital Ocean

- **Database**
  - MongoDB version: 3.0.14-1.9
  - Storage engine:  Rocks-DB
  - Hardware:        Ubuntu 16.04.1 LTS (GNU/Linux 4.4.0-57-generic x86_64)
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): Digital Ocean

### Logs/Trace

No logs, it just saves the new object

**Comment by mrmarcsmith** [comment]
I found the line that deletes the objectId that I'm trying to change
https://github.com/parse-community/parse-server/blob/2533a8cdb316dc9e31ff416af4e37a95f5fbf86e/src/RestWrite.js#L175
I don't intend to remove this line but instead write a case where if the objectId is change AND the new objectId exists in that class, it would allow the change because the user is trying to switch to updating an existing object. Would a PR like that be considered or should I save my keyboard time?

**Comment by flovilmart** [comment]
You can save a new object in a beforeSave, then reject the first save. Otherwise, I recommend you implement, a cloud function, where you'd return the vote object. The pattern you're trying to implement is kind of risky, and opening it would lead to probable issues.

**Comment by flovilmart** [comment]
You also could keep only the last vote, marking the previous votes as non-readable which would give you history. Drawback is that the objectId would change after each vote, but still, an interesting feature/side effect. You can also delete the previous vote etc...

**Comment by mrmarcsmith** [comment]
Understandable. I ended up just erroring out if they have voted before but that makes votes unchangeable. I have considered your suggestion of deleting previous votes or making them unreadable. The issue with this is the objectId changes which is undesirable for my situation.  Rejecting the original object and saving a new one returns an error to my client SDK which is confusing and feels hacky to my developers. Brainstorming for the future what if there was a (hidden and experimental at first) cloud function called "idForSaveObject" were you could return a different id (only of the same class). We could put it as one of the first functions in the REST chain so all of the validation functions are run thinking the request just came in that way? That allows my developers to not worry about querying first and when to edit and when to save new etc... as an added bonus I know for a fact it will be done right on all platforms because it's in the cloud.

**Comment by mrmarcsmith** [comment]
Refining this idea, in order to not break current client SDK functionality. We would only call this function on new objects where the SDKs has no expectation of what the objectId will be. "ExistingIdForNewObject" might be a better function name.

**Comment by flovilmart** [comment]
Why don't you create a cloud function to save your votes? You can have all the custom logic you want as well as all the benefits of natively types objects if you return your vote object from this cloud function.

**Comment by felipemartim** [comment]
@mrmarcsmith Here it is my Vote function that doesn't allow a user to vote twice and maintains the objectId.

```javascript
Parse.Cloud.define('vote', function(request, response) {
  const { pollId, value } = request.params
  const { user } = request

  let poll = Poll.createWithoutData(pollId)

  let voteQuery = new Parse.Query(Vote)
  voteQuery.equalTo('user', user)
  voteQuery.equalTo('poll', poll)
  Promise.resolve(voteQuery.first())
  .then((vote = new Vote()) => {
    if(vote.isNew()){
      vote.set({
        user: user,
        poll: poll,
        value: value,
      })
    } else {
      if(value === vote.get('value')){ //user didn't change vote
        return Promise.resolve(vote)
      }
      vote.set('value', value)
    }
    return Promise.resolve(vote.save())
    .then((vote) => {
      return updatePoll(vote)
      .then(() => Promise.resolve(vote))
    })
  })
  .then(response.success)
  .catch((error) => {
    sendError(response, error)
  })
})
```
