### ISSUE TITLE
Missing "objectId" from relation field

### ISSUE THREAD

**Issue by DmytroLisitsyn** [parse-community/parse-server#3742]
### Issue Description

`objectId` is missing from response object's relation field.

### Steps to reproduce

1. Sign Up
```
curl -X "POST" "http://localhost:8000/api/users" \
     -H "X-Parse-Revocable-Session: 1" \
     -H "X-Parse-REST-API-Key: MyKey" \
     -H "X-Parse-Application-Id: MyAppID" \
     -H "Content-Type: application/json" \
     -d $'{
  "username": "username",
  "password": "password"
}'
```

2. Create Session
```
curl -X "POST" "http://localhost:8000/api/classes/session" \
     -H "X-Parse-REST-API-Key: MyKey" \
     -H "X-Parse-Application-Id: MyAppID" \
     -H "Content-Type: application/json" \
     -d $'{
  "title": "Session",
  "owner": {
    "objects": [
      {
        "__type": "Pointer",
        "className": "_User",
        "objectId": "RegisteredUserID"
      }
    ],
    "__op": "AddRelation"
  }
}'
```

3. Get All Sessions
```
curl "http://localhost:8000/api/classes/session" \
     -H "X-Parse-REST-API-Key: MyKey" \
     -H "X-Parse-Application-Id: MyAppID"
 ```

#### Expected Results
`results[0].owner` contains `objectId`.
```
{
  "results": [
    {
      "objectId": "xdTAyg6NXY",
      "title": "Session",
      "createdAt": "2017-04-22T21:20:08.657Z",
      "updatedAt": "2017-04-22T21:20:08.657Z",
      "owner": {
        "__type": "Relation",
        "className": "_User"
        "objectId": "RegisteredUserID"
      }
    }
  ]
}
```

#### Actual Outcome
`results[0].owner ` does not contain `objectId`.
```
{
  "results": [
    {
      "objectId": "xdTAyg6NXY",
      "title": "Session",
      "createdAt": "2017-04-22T21:20:08.657Z",
      "updatedAt": "2017-04-22T21:20:08.657Z",
      "owner": {
        "__type": "Relation",
        "className": "_User"
      }
    }
  ]
}
```
 

Requesting Sessions by owner's id produces the same response as "Get All Sessions" above. The same response even with `include=owner` query parameter included.
Get Sessions Of User:
```
curl "http://localhost:8000/api/classes/session?include=owner&where=%7B%22owner%22:%7B%22__type%22:%22Pointer%22,%22className%22:%22_User%22,%22objectId%22:%RegisteredUserID%22%7D%7D" \
     -H "X-Parse-REST-API-Key: MyKey" \
     -H "X-Parse-Application-Id: MyAppID"
```
Also, Parse Dashboard handles tap on relation properly.

### Environment Setup

- **Server**
  - parse-server version: 2.3.8
  - Operating System:     macOS Sierra
  - Hardware:             MacBook Pro
  - Server: localhost

- **Database**
  - MongoDB version: 3.4.3
  - Storage engine:  wiredTiger
  - Hardware:        MacBook Pro
  - Server:           localhost

**Comment by flovilmart** [comment]
You're probably lookin for using pointers instead of using relations. More infos available on http://docs.parseplatform.org under the relational data sections

**Comment by DmytroLisitsyn** [comment]
@flovilmart, could you explain carefully? Because, it seems like I did as explained in docs.
<img width="868" alt="screen shot 2017-04-23 at 11 19 23 am" src="https://cloud.githubusercontent.com/assets/8964273/25312042/3c7ffe18-2817-11e7-8af5-aa1ed8ba7e0d.png">

**Comment by flovilmart** [comment]
You are using a Relation which is designed to represent Many to Many relationship. Relations are not fetched with include, and they need their own query in order to find the objects of such relation.

You should use a Pointer, it represents a Many to One or One to One relationship.

**Comment by DmytroLisitsyn** [comment]
Got it. Thank you, @flovilmart.
For me, docs were not exhaustive about it.

**Comment by flovilmart** [comment]
There seems to be missing a Relation section in the REST guide, but you can find it here http://docs.parseplatform.org/js/guide/#relations

**Comment by DmytroLisitsyn** [comment]
I can contribute to docs later.

**Comment by flovilmart** [comment]
You're more than welcome! Perhaps a link to the 'Relations' section would be helpful :)
