### ISSUE TITLE
Login Instagram

### ISSUE THREAD

**Issue by JulienLevallois** [parse-community/parse-server#3743]
Hi ! 
I would like to be able to connect Parse server with an instagram login (Like Parse does it with FacebookUtils). Do you know if it's possible now?

Otherwise how do I do?

thank you very much

**Comment by jlalvarez18** [comment]
It's available in Parse Server already.

https://github.com/parse-community/parse-server/blob/master/src/Adapters/Auth/instagram.js

I believe you add it to your server config like so:

```
{
  auth: {
   instagram: {}
  }
}
```

According to the adapter, it doesn't require any options so just pass an empty object. The client should send authData that contains `access_token` and `id` returned after authentication with Instagram.

**Comment by flovilmart** [comment]
@JulienLevallois did it help?

**Comment by JulienLevallois** [comment]
Mmm but There is no function with IOS SDK for example to connect with Insta?
Like this : 
![image](https://cloud.githubusercontent.com/assets/5727223/26561159/20a4af9c-448a-11e7-8ca4-d917c26d0afc.png)

**Comment by mzgnr** [comment]
@JulienLevallois i'm also looking for a way for instagram login. Did you find a way to accomplish that ?

**Comment by flovilmart** [comment]
No but you can create one yourself, look into the facebookUtils code

**Comment by JulienLevallois** [comment]
@mzgnr  no.... and you ?

**Comment by flovilmart** [comment]
The main example for logging with 3rd party auth is the ParseFacebookUtils repo. You need to acquire the access token from Instagram’s oauth flow and then use a similar strategy as the Facebook one!

**Comment by JulienLevallois** [comment]
I managed to recreate FacebookUtils and my login works with the token instagram but I have a question. Instagram makes it clear that its token does not have an expiration date but it can change, be revoked.

In this case, the instagram requests will return an error and the user will have to be logout. But when it is going to want to re-login, the token will have changed then how will Parse recognize this user as an old user? Will Parse create a new user? I would like to understand the logic

**Comment by flovilmart** [comment]
All tokens expire, you need to send the user ID alongside the accessToken and everything will be fine :)

**Comment by JulienLevallois** [comment]
So normally this is good? Parse Server will know the user even if the token is modified

<img width="1680" alt="capture d ecran 2017-07-18 a 17 39 44" src="https://user-images.githubusercontent.com/5727223/28326154-441bd7d4-6be0-11e7-9b08-f3fa4c2ab0fb.png">

**Comment by flovilmart** [comment]
Yes! This should work

**Comment by JulienLevallois** [comment]
@flovilmart I need to get the accesstoken instagram to use the api instagram. How can I access this token access in the authData ?

**Comment by JulienLevallois** [comment]
I can access it only from the cloud code?
