### ISSUE TITLE
Strange "Unable to connect to the Parse API" message after some running time (not directly)

### ISSUE THREAD

**Issue by ndominati-luna** [parse-community/parse-server#3746]
### Issue Description

When we start the parse server instance (with a LiveQuery server too), queries made from mobile devices, live queries and cloud function calls are working well. But about 1 or 2 days after (sometimes after about 1 hour), the cloud functions and the live query server are not responding (the queries made from the mobile devices are still working and the login / signup / logout actions too). It seems that all that is not relying on the Cloud code is still working, but not the Cloud code itself.
On the server side, we can see in the logs a lot of “[object Object]” and we are sure this logs aren’t generated by us.

We also got a lot of logs like that:

error: Failed running cloud function setConversationRead for user xxxxxxxxxx with:
  Input: {"conversationId":"yyyyyyyyyy"}
  Error: {"code":141,"message":"{\"code\":100,\"message\":\"XMLHttpRequest failed: \\\"Unable to connect to the Parse API\\\"\"}"} functionName=setConversationRead, code=141, message={"code":100,"message":"XMLHttpRequest failed: \"Unable to connect to the Parse API\""}, conversationId=yyyyyyyyyy, user=xxxxxxxxxx

error: Error generating response. ParseError {
  code: 141,
  message: '{"code":100,"message":"XMLHttpRequest failed: \\"Unable to connect to the Parse API\\""}' } code=141, message={"code":100,"message":"XMLHttpRequest failed: \"Unable to connect to the Parse API\""}
[object Object]

At this step, we can’t see any cloud function calls logs anymore.
We have other parse servers working well on the same server, the only difference is that they don’t implement any live query servers.

All our cloud code was well tested

### Steps to reproduce

We start the server, and it works well. Then, we don't know why but it stops working about between 1 hour and 2 days after, giving us the logs above.
It sounds like having the Cloud code process not responding anymore.

#### Expected Results

The Cloud code should never stop working.

#### Actual Outcome

Cloud code stops to work showing us the above logs.

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.): 2.3.1
  - Operating System:     Linux Ubuntu 16.04
  - Hardware:             online.net Dedibox® XC 2016
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): online.net

- **Database**
  - MongoDB version: 3.2.11
  - Storage engine:  ?
  - Hardware:        online.net Dedibox® XC 2016
  - Localhost or remote server? Same server as the parse server. Installed via apt-get.

### Logs/Trace

error: Failed running cloud function setConversationRead for user xxxxxxxxxx with:
  Input: {"conversationId":"yyyyyyyyyy"}
  Error: {"code":141,"message":"{\"code\":100,\"message\":\"XMLHttpRequest failed: \\\"Unable to connect to the Parse API\\\"\"}"} functionName=setConversationRead, code=141, message={"code":100,"message":"XMLHttpRequest failed: \"Unable to connect to the Parse API\""}, conversationId=yyyyyyyyyy, user=xxxxxxxxxx

error: Error generating response. ParseError {
  code: 141,
  message: '{"code":100,"message":"XMLHttpRequest failed: \\"Unable to connect to the Parse API\\""}' } code=141, message={"code":100,"message":"XMLHttpRequest failed: \"Unable to connect to the Parse API\""}
[object Object]

It's very urgent.
Many thanks in advance.

**Comment by flovilmart** [comment]
Is your node process still running or is it crashed?

**Comment by ndominati-luna** [comment]
Thanks for your prompt answer.

The NodeJS process is still running, we can still directly query the database from our devices, we can still connect / log out users and access the dashboard.
But all the Cloud code environment doesn't work.

Parse-Server logs me that it cannot connect to the Parse API.

**Comment by ndominati-luna** [comment]
I have to restart it to have it entirely working for an unknown duration.

**Comment by ndominati-luna** [comment]
Might it be because NodeJS SSL configuration is not supported or not stable?

**Comment by flovilmart** [comment]
So if I understand correctly, those are the calls within cloud code, when running queries or save with the JS SDK that fail?

**Comment by ndominati-luna** [comment]
I don't know about the beforeSave / afterSave triggers (I think this is the same).
But what I can see is that cloud code function calls made from Android or iOS doesn't work (after some time), and I got an "I/O error" on both platforms.

**Comment by flovilmart** [comment]
If you're doing the SSL termination in node, I suggest you try starting another http server that listens on port 8080. And set the serverUrl to 'http://localhost:8080/' + YOUR_PARSE_SERVER_MOUNTPATH 

this will let cloud code use the local loop instead of doing the round trip.

**Comment by ndominati-luna** [comment]
Ok, I'll give it a try and I'll let you know. (I think I've already tried it but I'll tried it again to be sure).
Thx.

**Comment by flovilmart** [comment]
You may wanna check also for number of open sockets, CPU load, memory load etc... we're running it on container based environments and it's working flawlessly.

**Comment by ndominati-luna** [comment]
Now the NodeJS server is not the SSL endpoint anymore.
I configured my Apache server as a proxy for https requests and as a websocket tunnel for the wss requests.
Now only Apache knows the SSL configuration and all is working as before.
I let it run like that hoping it will not be broken anymore and let you know in about 2 days maximum if all is ok.

Thanks a lot for your time.

**Comment by ndominati-luna** [comment]
I've also configured the serverURL using localhost as you suggested.

**Comment by ndominati-luna** [comment]
Hi,

The cloud code stopped working just now. Exactly as I described in this issue but including all the modifications we talked about.

**Comment by ndominati-luna** [comment]
Can this be due to the LiveQuery server?

I also got a lot of "[object Object]" logs which I didn't generate.

**Comment by flovilmart** [comment]
can you provide the logs when running with  VERBOSE=1

**Comment by flovilmart** [comment]
As well as perhaps other relevant infos like the code that's crashing the server. Is the node process still running? Is it still listening etc...

**Comment by ndominati-luna** [comment]
I don't know if it is the code that is crashing the server.
The only logs I got when using VERBOSE=1 are:

error: Failed running cloud function setConversationRead for user xxxxxxxxxx with:
Input: {"conversationId":"yyyyyyyyyy"}
Error: {"code":141,"message":"{"code":100,"message":"XMLHttpRequest failed: \"Unable to connect to the Parse API\""}"} functionName=setConversationRead, code=141, message={"code":100,"message":"XMLHttpRequest failed: "Unable to connect to the Parse API""}, conversationId=yyyyyyyyyy, user=xxxxxxxxxx

error: Error generating response. ParseError {
code: 141,
message: '{"code":100,"message":"XMLHttpRequest failed: \"Unable to connect to the Parse API\""}' } code=141, message={"code":100,"message":"XMLHttpRequest failed: "Unable to connect to the Parse API""}
[object Object]
[object Object]
[object Object]
[object Object]
[object Object]
[object Object]
...

Repeated each time a cloud function is called.

But the NodeJS server is still running and we can still log in / sign in / log out and make queries directly from devices.
This is only the cloud code which is not responding anymore.

**Comment by flovilmart** [comment]
Can you make a gist of the setConbersationRead code?

**Comment by ndominati-luna** [comment]
How can I give you it secretly?

**Comment by flovilmart** [comment]
send it to florent _ at _ flovilmart _ dot _ com

**Comment by ndominati-luna** [comment]
I've just sent you the email.

**Comment by ndominati-luna** [comment]
The thing that is strange is that this is not all the time this function which is logged and before the cloud code stopped to respond, the <code>setConversationRead</code> function works well.

**Comment by ndominati-luna** [comment]
I searched the whole project and I find only one serverURL use which is in the ParseServer instance configuration.
It's value is http://localhost:9003/parse.

**Comment by flovilmart** [comment]
that's very odd indeed, about those apache logs? The `{"code":100,"message":"XMLHttpRequest failed: "Unable to connect to the Parse API""}`, it's generated by the `setConversationRead` call right?

**Comment by ndominati-luna** [comment]
Not only. When this happen, all the cloud code functions are logging this.

**Comment by ndominati-luna** [comment]
And another really strange thing is the stack of "[object Object]" logs I never saw on another server (except when I logged them consciously). They are logged when the cloud code doesn't respond.
There are also logged, when the server is working, when a cloud code function returns an error or when a login action failed due to a wrong password for example.

**Comment by ndominati-luna** [comment]
I'm checking if I have some Apache logs about that.

**Comment by ndominati-luna** [comment]
Also, when the cloud code is not responding, the livequery server is also not responding.

**Comment by ndominati-luna** [comment]
In the error logs of Apache I can see when the server wasn't responding :

[Tue Apr 25 11:59:59.490519 2017] [proxy:error] [pid 26342] (111)Connection refused: AH00957: WS: attempt to connect to 127.0.0.1:9003 (*) failed
[Tue Apr 25 11:59:59.490559 2017] [proxy_wstunnel:error] [pid 26342] [client 90.88.219.174:58298] AH02452: failed to make connection to backend: localhost

Obviously, these logs appeared when the issue happened.

I'm checking the access logs.

**Comment by ndominati-luna** [comment]
Nothing special in the access logs.

I can see this many times when the livequery server is not responding anymore:

90.88.219.174 - - [25/Apr/2017:11:57:15 +0200] "GET /whoomies/ws HTTP/1.1" 503 773 "-" "-"

There is nothing else.

**Comment by flovilmart** [comment]
seems that your node process is not responding anymore: failed to make connection to backend: localhost

**Comment by ndominati-luna** [comment]
Yes but the queries still work... that's incomprehensible.

**Comment by ndominati-luna** [comment]
This issue was still reproduced.
I thought that it was due to an error in a cloud function so I called this cloud function giving it specific data to make not working.
I saw an error message which was what I expected. I did this test a lot of time to test my functions stability and I never put my server in a strange state.

**Comment by flovilmart** [comment]
That's the error itself that is improperly logged.

**Comment by ndominati-luna** [comment]
Hi,

After some investigations we found that this bug is happening when we log out a user and log in back the same user or another one from a mobile app.
Is there something special to know about the correct way to stop all previous LiveQuery subscriptions, client, queries, ...?

**Comment by ndominati-luna** [comment]
I tested this again and I can confirm you that the cloud code stops to work when a user is logged out and logged back in.
Is this an issue on the ParseLiveQuery Server?

**Comment by flovilmart** [comment]
Thanks for tracking down the issue. I'll have a look in the liveQuery server and clients. Do you pass your sessionToken with the liveQuery subscription?

**Comment by ndominati-luna** [comment]
No, I just call this: subscription = client.subscribe(query).

**Comment by ndominati-luna** [comment]
On iOS side, I initialize one Client which I use in all the application to subscribe queries.
When I log out / log in, the cloud code stops to respond, and when I restart the server, the application reconnects the websocket with no issues and all is working well.

**Comment by flovilmart** [comment]
And if you don't connect the liveQuery client it's all good?

**Comment by ndominati-luna** [comment]
Yes.

**Comment by flovilmart** [comment]
As well as if you disconnect the client/close the subscriptions after logging out?

**Comment by ndominati-luna** [comment]
Before testing without LiveQuery, I unsubscribed all queries after logging out.
I also tried to unsubscribe all queries before logging out.
All the time, it ends up with a bug in the server after logging out.

**Comment by ndominati-luna** [comment]
I never tried to disconnect.
I didn't know this function.

**Comment by ndominati-luna** [comment]
Do I have to use this function when I log a user out?

**Comment by ndominati-luna** [comment]
I tried also to use .disconnect() and .reconnect on the client and the same thing happened.

**Comment by flovilmart** [comment]
OK good to know, I'll have a look soon.

**Comment by ndominati-luna** [comment]
Thx, it will be really appreciated because our application will be released very very soon and the only option we have now is to remove the LiveQuery server. But doing this we will loose this nice real time feature...

**Comment by ndominati-luna** [comment]
Hi,

I just would like to know if you have any news about this issue.

Thanks in advance.

**Comment by flovilmart** [comment]
I haven't had a chance to look at it

**Comment by ndominati-luna** [comment]
Hi,

We testing something else to try to find a workaround to this issue.
On Android, we removed the call to logout. When we log a user out, we just store the fact that he is not logged in anymore. Then, on a new connection, we directly call the signup / login function.
This way, on Android it seems that we don't have the server crash anymore.

But on iOS, doing the same thing changed nothing.

Do you think you'll have the possibility to look at it? It becomes really critical for us.

Thanks a lot in advance.

**Comment by flovilmart** [comment]
I'll have a look before he end of he day, hopefully finding a fix, do you happen to have a server log of the error, or a clear STR so I don't spend hours reproducing ? That would really help.

**Comment by ndominati-luna** [comment]
Hi,

Sorry to answer late, I have nothing more than what I already sent you.
Did you have some news about this?

Best regards,

**Comment by ndominati-luna** [comment]
We tried again to investigate on iOS side, and we tried to delete the user files cache generated by the framework to check if there is no "not cleaned" data that can be responsible of this issue.
When we did this, the issue happened less often.
We are thinking that there is something which is not cleaned at the user session management level which is making the parse server going down.

**Comment by ndominati-luna** [comment]
Hi,

I'm investigating to try to setup the livequery server on a separate server to test if the issue can come from this.
Is this possible? I tried all the configurations I found on the Internet and the results are:
 - My app is connected to the websocket.
 - My app doesn't receive any events.

I also tried another thing (with parse server and livequery server in the same process like my initial configuration): I removed the HTTPS configuration and disabled the proxy I installed into Apache to try to connect the app directly to the NodeJS webapp without any proxy, using HTTP.
The result is the as what I described at the beginning of this ticket:
 - I log a user in. (User1)
 - The livequeries are activated and working.
 - I call a cloud function (it can be any of the functions).
 - The cloud function returns successfully.
 - I log User1 out.
 - I log User2 in.
 - The livequery are activated and working.
 - I call a cloud function (it can be any of the functions).
 - The cloud function doesn't return and I can see an [object Object] in the server logs appearing exactly at this time.

Don't hesitate if I'm not clear.

Best regards,

**Comment by ndominati-luna** [comment]
We solved this instability by running the LiveQuery server from another server, linked to the parse server through a Redis server.

**Comment by craffenoux** [comment]
Hello, did you guys have chance to look at this issue and fix it ?
Thanks!

**Comment by flovilmart** [comment]
No one has apparently, as the thread is still open. Feel free to investigate.

**Comment by craffenoux** [comment]
For the moment I can only confirm that disabling the LiveQuery _fixes_ the issue.
