### ISSUE TITLE
Call CloudCode from CloudCode & pretend to be a user.

### ISSUE THREAD

**Issue by pconihout** [parse-community/parse-server#3748]
I have a cloud function that call other cloud functions. The inside cloud functions make a check if user is loggued in or not.

How could i make this working knowing i want to call the first one as a user, and the inside from this function.

Example : 
```
Parse.Cloud.define("getAllInformations", function(request, response) {
	var user = request.user;

	if (!user)
        	return response.error("You don't have the rights to do that");

	Parse.Cloud.run('getAllQRCodes', {}).then(function (qrCodes) {
		// [...]
	});
});
```

```
Parse.Cloud.define("getAllQRCodes", function(request, response) {
	var user = request.user;

	if (!user)
    		return response.error("You must be loggued in");
	// [...]
});


```

**Comment by flovilmart** [comment]
You need to pass the session token:

```
Parse.Cloud.run('getAllQRCodes', {sessionToken: user.getSessionToken() })
```

**Comment by pconihout** [comment]
@flovilmart 
error: Failed running cloud function getAllQRCodes for user undefined with:
  Input: {"sessionToken":"XXXXXXx"}
  Error: {"code":141,"message":"You must be loggued in"} functionName=getAllQRCodes, code=141, message=You must be loggued in, sessionToken=XXXXXXX, user=undefined

**Comment by flovilmart** [comment]
Can you provide the verbose logs, the user is undefined which doesn not make sense if the sessionToken is valid.

**Comment by pconihout** [comment]
`verbose: REQUEST for [POST] /parse/functions/getAllInformations: {} method=POST, url=/parse/functions/getAllInformations, host=localhost:1337, connection=keep-alive, content-length=258, origin=http://localhost:8080, user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36, content-type=text/plain, accept=*/*, referer=http://localhost:8080/, accept-encoding=gzip, deflate, br, accept-language=fr-FR,fr;q=0.8,en-US;q=0.6,en;q=0.4, 
ParseUser { _objCount: 5, className: '_User', id: 'wEzzRrs5cF' }
verbose: REQUEST for [GET] /parse/classes/_User/wEzzRrs5cF: {} method=GET, url=/parse/classes/_User/wEzzRrs5cF, host=localhost:1337, connection=keep-alive, content-length=274, origin=http://localhost:8080, user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36, content-type=text/plain, accept=*/*, referer=http://localhost:8080/, accept-encoding=gzip, deflate, br, accept-language=fr-FR,fr;q=0.8,en-US;q=0.6,en;q=0.4, 
verbose: REQUEST for [POST] /parse/functions/getAllQRCodes: {
  "sessionToken": "r:XX"
} method=POST, url=/parse/functions/getAllQRCodes, user-agent=node-XMLHttpRequest, Parse/js1.9.2 (NodeJS 4.5.0), accept=*/*, content-type=text/plain, host=localhost:1337, content-length=257, connection=close, sessionToken=r:XX
undefined
error: Failed running cloud function getAllQRCodes for user undefined with:
  Input: {"sessionToken":"r:XX"}
  Error: {"code":141,"message":"You must be loggued in"} functionName=getAllQRCodes, code=141, message=You must be loggued in, sessionToken=r:XX, user=undefined
error: Error generating response. ParseError { code: 141, message: 'You must be loggued in' } code=141, message=You must be loggued in
error: You must be loggued in code=141, message=You must be loggued in
error: Failed running cloud function getAllInformations for user wEzzRrs5cF with:
  Input: {}
  Error: {"code":141,"message":{"code":141,"message":"You must be loggued in"}} functionName=getAllInformations, code=141, code=141, message=You must be loggued in, , user=wEzzRrs5cF
error: Error generating response. ParseError {
  code: 141,
  message: ParseError { code: 141, message: 'You must be loggued in' } } code=141, code=141, message=You must be loggued in
error: ParseError { code: 141, message: 'You must be loggued in' } code=141, code=141, message=You must be loggued in
verbose: RESPONSE from [GET] /parse/classes/_User/wEzzRrs5cF: {
  "response": {
    "objectId": "wEzzRrs5cF",
    "email": "pierre@xx.com",
    "emailVerified": true,
    "username": "p.coni",
    "createdAt": "2017-04-21T13:48:51.119Z",
    "updatedAt": "2017-04-23T16:39:24.352Z",
    "verificationLink": "",
    "firstname": "xx",
    "lastname": "de xx",
    "mobile": "xxx",
    "status": "admin",
    "ACL": {
      "*": {
        "read": true
      },
      "wEzzRrs5cF": {
        "read": true,
        "write": true
      }
    },
    "sessionToken": "r:XX"
  }
} objectId=wEzzRrs5cF, email=pierre@xx.com, emailVerified=true, username=p.coni, createdAt=2017-04-21T13:48:51.119Z, updatedAt=2017-04-23T16:39:24.352Z, verificationLink=, firstname=xx, lastname=xxx, mobile=xxx, status=admin, read=true, read=true, write=true, sessionToken=r:XX`

**Comment by pconihout** [comment]
I tried on three different parse-server instance, and I still have the same problem.. Any ideas ?

**Comment by mgreenvald** [comment]
You need to pass the session token as the third parameter, the second parameter is the function input data:

`Parse.Cloud.run('getAllQRCodes',{}, {sessionToken: user.getSessionToken() })`

**Comment by natanrolnik** [comment]
@mgreenvald is right.
@pconihout @flovilmart check the method documentation here: http://parseplatform.org/Parse-SDK-JS/api/classes/Parse.Cloud.html#methods_run

The second parameter is the data the cloud function will receive; `options` is the third parameter.
