### ISSUE TITLE
Parse server Invalid session token 

### ISSUE THREAD

**Issue by zack1991** [parse-community/parse-server#3751]
Hi,
I am getting the issue of invalid session token, while session token exist in the _Session table.
I am sharing some screenshots, please help me to find the issue.

I am requesting a url in whichs payload in below image.

![verify receipt success](https://cloud.githubusercontent.com/assets/26978206/25372376/c23ac730-29b2-11e7-81bc-db28a6626d5c.png).

Now i am getting success response which shows in below image.
![verify receipt success response]
(https://cloud.githubusercontent.com/assets/26978206/25372419/eff7e61c-29b2-11e7-9bb8-bda728ebb1c9.png)

Now i am again hitting the same service which payload in below image
![verify receipt fails request](https://cloud.githubusercontent.com/assets/26978206/25372476/31a03c40-29b3-11e7-96da-7219464a22a3.png)

Which response show invalid session token

![verify receipt fail response](https://cloud.githubusercontent.com/assets/26978206/25372492/42481130-29b3-11e7-8d63-8f29e0921fee.png)

While the session token exist in the _Session table. which shows in below image.

![session exist](https://cloud.githubusercontent.com/assets/26978206/25372569/916bfaf6-29b3-11e7-949c-880fffb7682c.png)

I am using revocable sessions. Please help me how to fix this issue.

**Comment by flovilmart** [comment]
I'll have a look, thanks for the detailed screenshots

**Comment by flovilmart** [comment]
What's the endpoint you're calling that causes issues with the sessionToken?
