### ISSUE TITLE
SIGINT doesn't kill the process : 2.3.8

### ISSUE THREAD

**Issue by jeremypiednoel** [parse-community/parse-server#3755]
### Issue Description

When I SIGINT the parse server the terminal doesn't give me the hand back

### Steps to reproduce

Start parse server and hit Ctrl + C

#### Expected Results

Terminal should kill the process and give back the hand

#### Actual Outcome

Terminal stay stuck om
```
^C[WARN] Interrupted by User
[DONE] Killing all processes with signal  SIGINT
```

### Environment Setup

- **Server**
  - parse-server version: 2.3.8
  - Operating System:    MAC OS SIERA
  - Hardware:            iMac
  - Localhost or remote server? Localhost

### Logs/Trace

Include all relevant logs. You can turn on additional logging by configuring VERBOSE=1 in your environment.

```4:30:59 PM web.1 |  Unable to listen on port 1337. The port is already in use.
[DONE] Killing all processes with signal  null```

**Comment by Fedeorlandau** [comment]
Hi!
This is happening to me too. parse-server 2.3.7 is working fine.
Thanks!

**Comment by jeremypiednoel** [comment]
Duplicate : https://github.com/parse-community/parse-server/issues/3718
