### ISSUE TITLE
Resend email verification

### ISSUE THREAD

**Issue by majidhassan** [parse-community/parse-server#3756]
Hello,

Previously I had been "hacking" the resend of the email verification through setting and unsetting the email address of the user object. I noticed, that in 2.3.7 a new endpoint for that had been added but couldn't find that in the documentation: http://parseplatform.org/Parse-SDK-JS/api/, though.

Generally, I feel some areas are poorly documented, unless I'm not looking in the correct / updated documentation. As an example, the changelog states, that jobs can be used again, but couldn't find any documentation for that.

**Comment by flovilmart** [comment]
To be clear, jobs can be defined but the scheduling is up to you. 
As for resending verification emails, I believe the REST endpoint has been available for a while.

If you feel some documentation should be improved, feel free to open an issue or a pull request on https://github.com/Parse-community/docs

Thanks!

**Comment by majidhassan** [comment]
@flovilmart Hey Florent, thanks for the reply. I don't quite get, what you mean regarding the jobs. What is the difference between defining and scheduling the jobs?

Just to clarify, does that mean, it works just like it used to in Parse.com. Meaning, I define the jobs from the cloud code and then schedule them from the dashboard?

**Comment by flovilmart** [comment]
You basically answered the question yourself, you can define a job in cloud code with Parse.Cloud.job but you can't schedule them in the dashboard because there is no scheduler

**Comment by majidhassan** [comment]
@flovilmart Any plans on when a scheduler would be added? That's the whole point of having Parse jobs.

**Comment by flovilmart** [comment]
There is no plan for the scheduler to be added. as many libraries manage it. We added back the jobs REST endpoints and status objects so you can monitor them from your dashboard.
