### ISSUE TITLE
Fetching related object of another class in python (parse) in a single query

### ISSUE THREAD

**Issue by saikiran644** [parse-community/parse-server#3760]
Is there a way to fetch the related object information (object is related with parse relations) from a record with a single query rather than using a separate query in Python parse API's (not Rest API's)

**Comment by flovilmart** [comment]
Relations are stored in a separate table, therefore they can't be included when fetching the parent object. If you only have a few objects, you should consider Pointers or arrays of Pointers

**Comment by saikiran644** [comment]
But, through python is there a way to add pointers (not through rest api's,
through python libraries).I haven't found a way till now to add pointers or
array of pointers directly from python.
Please help with this. @Florent Vilmart


On 27 Apr 2017 6:15 p.m., "Florent Vilmart" <notifications@github.com>
wrote:

Relations are stored in a separate table, therefore they can't be included
when fetching the parent object. If you only have a few objects, you should
consider Pointers or arrays of Pointers

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/parse-community/parse-server/issues/3760#issuecomment-297702819>,
or mute the thread

**Comment by flovilmart** [comment]
We don't support officially a python library, you should probably open the issue on the python lib you're using, and probably link back here
