### ISSUE TITLE
Can't run jasmine (MongoError: failed to connect to server)

### ISSUE THREAD

**Issue by felipemobile** [parse-community/parse-server#3770]
Hi guys, I can't run jasmine or npm test.  Is there any step required to setup the environment (ex: [parseServerMongoAdapterTestDatabase](https://github.com/parse-community/parse-server/blob/master/spec/testing-routes.js#L17))?

Parse-server version running on master
Operating System:    macOS Sierra
MongoDB version: 3.6.0

$ node_modules/jasmine/bin/jasmine.js spec/PushController.spec.js 
Spec started
(node:89046) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED ::1:27017]

**Comment by flovilmart** [comment]
Just running npm test work. Did you npm install with all devDependencies?

**Comment by felipemobile** [comment]
Thanks @flovilmart ! 

`npm install --dev`

Can you take a look at this [pull request](https://github.com/parse-community/parse-server/pull/3764)?
