### ISSUE TITLE
Bot Messenger and Parse Server

### ISSUE THREAD

**Issue by JulienLevallois** [parse-community/parse-server#3771]
Hi !
I wanted to know if it was possible to create a bot messenger with Parse Server, which can be connected to the database Parse, and if so, how it was possible. Thank you

**Comment by flovilmart** [comment]
This is most likely possible, Parse is a general purpose backend and supports flexible datastructures.

**Comment by srameshr** [comment]
@flovilmart 
Any thoughts on what is the best approach to use parse-server's ```User``` functionality to merge with Messenger User data.

```
app.get('/webhooks', (req, res) => {
  // sender-id is available in req.
 // https://graph.facebook.com/${sender-id} returns user data with username.
 // sign up the user if new
 // call some function defined in cloud/main.js file with req.user set to this user.
});
```

**Comment by flovilmart** [comment]
Not in particular

**Comment by srameshr** [comment]
https://github.com/fbsamples/messenger-platform-samples/tree/master/node
Look at this and let me know if you think there is a good approach to this user linking problem.

**Comment by flovilmart** [comment]
Wow..... I’m speechless...
