### ISSUE TITLE
How to Limiting LiveQuery

### ISSUE THREAD

**Issue by ulaskilic** [parse-community/parse-server#3774]
Hi everyone,
I have some problem with livequery. I have Posts Comments and Users classes. And users can like and unlike posts unlimited times. But when i subcribe my livequery server, subcribing all object of classes. So I have 1m post in posts class, when user like action first post in class, triggering all clients, but i dont want this.   
Mycode; 
```
var Posts = new Parse.Query("Posts");
 Posts.limit(10);
 Posts.include('User');
 var Sub = Posts.subscribe();

 Sub.on('open', function () {
  console.log('Posts Channel Now Online!');
 });
 Sub.on('close', function () {
  console.log('Posts Channel Now Offline!');
 });
 Sub.on('create', function (object) {
  console.log('New post created!'); // this log triggering every posts when liked. 
 });
 Sub.on('update', function () {
  console.log('Post updated');
 });
```

How can i solve this ?

**Comment by natanrolnik** [comment]
Head over to the [`Parse.Query` docs](http://docs.parseplatform.org/js/guide/#queries) - you should constraint the query to the user, the way you want it to work. Something like:

```
let user = //the user you want the 
var query = new Parse.Query("Posts");
query.limit(10);
query.include('User');
query.equalTo("usersSubscribedToLikes", user);
```

You'll need to have a list of `usersSubscribedToLikes` or something similar, so it's only "sent" the users that should receive these notifications.
