### ISSUE TITLE
Progress with Parse file uploading using JS SDK

### ISSUE THREAD

**Issue by pconihout** [parse-community/parse-server#3776]
Hi,

It seems there is a few way of implementing progress bar while uploading/downloading Parse.File with iOS & Android SDK, but I didn't found any with the JS SDK.

Did I miss something ?

Regards.

**Comment by natanrolnik** [comment]
That's correct, this is not available in the JS SDK.
You can keep keep track of the issue here: https://github.com/parse-community/Parse-SDK-JS/issues/347
