### ISSUE TITLE
How to Receive Push Notification on website using Parse JS SDK? 

### ISSUE THREAD

**Issue by emadehsan** [parse-community/parse-server#3780]
I have asked [this question on StackOverflow](http://stackoverflow.com/questions/43820278/how-to-receive-push-notification-on-website-using-parse-js-sdk) but I am in a bit hurry, so posting here. It seems to be related to Parse-JS-SDK but I believe that **Update** has some specifics to **Parse-Server**

> I have configured push notifications on Parse-Server & in Android app. But I am not able receive push notifications in a website using Parse JS SDK. They don't provide any method to subscribe for push notifications in ther [JS APIs](http://parseplatform.org/Parse-SDK-JS/api/classes/Parse.Push.html). There Documentation (JS) only talks about subscribing to mobile devices not browsers.

>> SUBSCRIBING TO CHANNELS

>> The JavaScript SDK does not currently support subscribing iOS and Android devices for pushes. Take a look at the iOS, Android or REST Push guide using the platform toggle at the top.

>So, I concluded that web browsers can't subscribe just by using Parse JS SDK? So, **how should I subscribe & receive Push notifications on a web browser from Parse Backend?**

> **Update:**
> I haven't test but If I use `ServiceWorker` to get subscription & subscribe user to some channel, can I use the default Parse Class `Installation` for saving subscription & then use that **Installation** object in Cloud Code to send Push to Website?

**Comment by flovilmart** [comment]
It's not supported at the moment.
