### ISSUE TITLE
XMLHttpRequest: Network Error 0x2ef3, in Internet explorer - Parse JS SDK

### ISSUE THREAD

**Issue by zack1991** [parse-community/parse-server#3790]
#Hi, i am using Parse javascript SDK with Cocos2dx for web application. My application running well on Google chrome, firefox, safari, opera but on Internet Explorer i am getting 
"CRIPT7002: XMLHttpRequest: Network Error 0x2ef3, Could not complete the operation due to error 00002ef3. "
or sometimes "XMLHttpRequest: Network Error 0x4c7, The operation was canceled by the user." 
issue on IE browser console when any parse cloud function gets called.

I am getting "errorCode = 100 and message = XMLHttpRequest failed: "Unable to connect to the Parse API"" error in parse cloud error block.

Apart from this when i am trying to hit parse url with mount point "https://example.com:1337/parse"
It response with {"error":"unauthorized"} in chrome, firefox, safari, opera thats fine, but in Internet Explorer this url not working it Showing "HTTP 403 Forbidden This error (HTTP 403 Forbidden) means that Internet Explorer was able to connect to the website, but it does not have permission to view the webpage."

Please help me where is the problem and how to fix it.

**Comment by flovilmart** [comment]
You should open the issue in the https://github.com/parse-community/Parse-SDK-JS/issues instead
