### ISSUE TITLE
can not receive push notification on device

### ISSUE THREAD

**Issue by kukkadapukarhtik** [parse-community/parse-server#3796]
var api = new ParseServer({
databaseURI: databaseUri || 'mongodburi',
cloud: process.env.CLOUD_CODE_MAIN || __dirname + '/cloud/main.js',
appId: process.env.APP_ID || 'appid',
masterKey: process.env.MASTER_KEY || 'masterkey, //Add your master key here. Keep it secret!,
// clientKey:process.env.CLIENT_KEY || 'cleintkey', //Add you client key here. Keep it secret!,
fileKey:process.env.FILE_KEY || 'filekey', // Add you file key here,
serverURL: process.env.SERVER_URL || 'https://appname.herokuapp.com/parse', // Don't forget to change to https if needed
push: {
ios: [
{
pfx:__dirname + '/certificates/pushfordevelopment.p12',
bundleId: 'com.appname',
production: false
}
]
},
liveQuery: {
classNames: ["Posts", "Comments"] // List of classes to support for query subscriptions
},
push: JSON.parse(process.env.PARSE_SERVER_PUSH || "{}"),
});

my cloud code

Parse.Cloud.define("iosPushforsingleuser", function(request, response) {

var query = new Parse.Query(Parse.User);
query.equalTo('username', 'emailid');

// here you can add other conditions e.g. to send a push to sepcific users or channel etc.

var payload = {
alert: "testing",
sound: "",
'content-available': 1
// you can add other stuff here...
};

Parse.Push.send({
data: payload,
where: query
}, {
useMasterKey: true
})
.then(function() {
response.success("Push Sent!");
}, function(error) {
response.error("Error while trying to send push " + error.message);
});
});

push status on mlab

{
"_id": "7khYdx0LKs",
"pushTime": "2017-05-09T06:33:37.275Z",
"query": "{"username":"xxx@xxx.com"}",
"payload": "{"alert":"YOUR_MESSAGE","sound":"","content-available":1}",
"source": "rest",
"status": "succeeded",
"numSent": 0,
"pushHash": "5a5228294bd8cd3aeb836d9834da9152",
"_wperm": [],
"_rperm": [],
"_acl": {},
"_created_at": {
"$date": "2017-05-09T06:33:37.275Z"
},
"_updated_at": {
"$date": "2017-05-09T06:33:37.304Z"
},
"numFailed": 0
}

**Comment by flovilmart** [comment]
Seems that you push options is defined twice...

**Comment by kukkadapukarhtik** [comment]
It means, please can you explain clearly

**Comment by flovilmart** [comment]
```
push: { <-- HERE
ios: [
{
pfx:__dirname + '/certificates/pushfordevelopment.p12',
bundleId: 'com.appname',
production: false
}
]
},
liveQuery: {
classNames: ["Posts", "Comments"] // List of classes to support for query subscriptions
},
push: JSON.parse(process.env.PARSE_SERVER_PUSH || "{}"), <-- AND HERE
```

**Comment by kukkadapukarhtik** [comment]
push: { <-- HERE
ios: [
{
pfx:__dirname + '/certificates/pushfordevelopment.p12',
bundleId: 'com.appname',
production: false
}
]
},
liveQuery: {
classNames: ["Posts", "Comments"] // List of classes to support for query subscriptions
},
//push: JSON.parse(process.env.PARSE_SERVER_PUSH || "{}"), <-- AND HERE


i commented above line and deployed in heroku, status was success on heroku log and mlab but not yet received on my device

**Comment by flovilmart** [comment]
please provide verbose logs, and perhaps look into the old closed issues: https://github.com/parse-server-modules/parse-server-push-adapter/issues?q=is%3Aissue+is%3Aclosed
