### ISSUE TITLE
When using multiple doesNotMatchKeyInQuery() clauses all but the last are ignored

### ISSUE THREAD

**Issue by mm11715** [parse-community/parse-server#3799]
### Issue Description

When using multiple doesNotMatchKeyInQuery() clauses on a query, only the last one constrains the query.

### Steps to reproduce

const FriendRequest = Parse.Object.extend('FriendRequest');

const fromBlockedQuery = new Parse.Query(FriendRequest);
fromBlockedQuery.equalTo('status', 'blocked');
fromBlockedQuery.equalTo('fromUser', request.user);
fromBlockedQuery.select('toUserID');

const toBlockedQuery = new Parse.Query(FriendRequest);
toBlockedQuery.equalTo('status', 'blocked');
toBlockedQuery.equalTo('toUser', request.user);
toBlockedQuery.select('fromUserID');

const contactsQuery = new Parse.Query(Parse.User);
contactsQuery.doesNotMatchKeyInQuery('objectId', 'toUserID', fromBlockedQuery);
contactsQuery.doesNotMatchKeyInQuery('objectId', 'fromUserID', toBlockedQuery);

the fromBlockedQuery constraint is ignored.

#### Expected Results

Both the fromBlockedQuery and toBlockedQuery clauses affect the contactsQuery.

#### Actual Outcome

Only the toBlockedQuery constrains the contactsQuery.

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.3.8
  - Operating System:     macOS 10.12.4
  - Hardware:             Intel Core i7
  - Localhost or remote server? Localhost

- **Database**
  - MongoDB version: 3.2.10
  - Storage engine:  mmapv1
  - Hardware:        Intel Core i7
  - Localhost or remote server? Localhost

**Comment by flovilmart** [comment]
Can you provide the logs when running with VERBOSE=1?

**Comment by davimacedo** [comment]
@mm11715 It is not possible to do this in none of the SDKs. You can't have two constraints of the same type in the same key. Take a look here https://github.com/parse-community/Parse-SDK-JS/blob/master/src/ParseQuery.js#L792 and here https://github.com/parse-community/Parse-SDK-JS/blob/master/src/ParseQuery.js#L224. My suggestion in order to achieve the same result is something like this:
```
const FriendRequest = Parse.Object.extend('FriendRequest');

const fromBlockedQuery = new Parse.Query(FriendRequest);
fromBlockedQuery.equalTo('status', 'blocked');
fromBlockedQuery.equalTo('fromUser', request.user);

const toBlockedQuery = new Parse.Query(FriendRequest);
toBlockedQuery.equalTo('status', 'blocked');
toBlockedQuery.equalTo('toUser', request.user);

const contactsQuery1 = new Parse.Query(Parse.User);
contactsQuery1.matchesKeyInQuery('objectId', 'toUserID', fromBlockedQuery);

const contactsQuery2 = new Parse.Query(Parse.User);
contactsQuery2.matchesKeyInQuery('objectId', 'fromUserID', toBlockedQuery);

const contactsQuery = new Parse.Query(Parse.User);
contactsQuery.doesNotMatchKeyInQuery('objectId', 'objectId', Parse.Query.or(contactsQuery1, contactsQuery2));
```

It works fine as you can see here: https://github.com/parse-community/parse-server/pull/3885

@flovilmart I think you can close this issue.

**Comment by flovilmart** [comment]
Alright! Thanks @davimacedo !
