### ISSUE TITLE
Snap package for Linux users

### ISSUE THREAD

**Issue by mhall119** [parse-community/parse-server#3802]
### Issue Description

Linux users would benefit from having Snap packages of parse-server available for easy installs and updates.

Snaps are self-contained application bundles that can be installed on the most popular Linux distributions, such as Ubuntu, Debian, Fedora and Arch, without having to build separate versions for each one. They give users immediate updates as soon as you publish a new release, without them having to manually download and unpack it, and will automatically create systemd services for managing daemons including restarting when updates are applied.

The Snapcraft tool makes it easy to build snaps, either from source or npm package. A good example of a project using Snapcraft and npm/nodejs is [Rocket.Chat](https://github.com/RocketChat/Rocket.Chat/blob/develop/.snapcraft/stable/snapcraft.yaml). The [Snap Store](https://dashboard.snapcraft.io/) lets you publish directly to users, without a manual review or approval process, so you can release on your own schedule.

If anybody is interested, you can find documentation and examples on [snapcraft.io](https://snapcraft.io/) and ask questions on [forum.snapcraft.io](http://forum.snapcraft.io)

#### Expected Results

The latest version of parse-server is available to install as a Snap with
`snap install parse-server`

**Comment by flovilmart** [comment]
@mhall119 thanks for the recommendation, you could probably open a PR if anything is required, but I'm not sure we have time/bandwidth at the moment for yet another distribution method. Also not sure parse-server is relevant to be distributed as an ubuntu app.
