### ISSUE TITLE
Sending a push with parse-server 2.4.0 is returning 504 GATEWAY_TIMEOUT

### ISSUE THREAD

**Issue by felipemobile** [parse-community/parse-server#3823]
Sending a push with parse-server 2.4.0 is returning 504 GATEWAY_TIMEOUT
After some retries Parse dashboard shows the message XMLHttpRequest failed: "Unable to connect to the Parse API"

  - parse-server version : 2.4.0
  - AWS EC2
  - Linux

**Comment by flovilmart** [comment]
can you provide the server logs?

**Comment by felipemobile** [comment]
```
warn: _PushStatus 4CmtJIFFui: error while sending push TypeError: Cannot read property 'toISOString' of undefined
    at Object.setInitial (/home/user/parse-clients/node_modules/parse-server/lib/StatusHandler.js:163:25)
    at /home/user/parse-clients/node_modules/parse-server/lib/Controllers/PushController.js:82:27
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
/home/user/parse-clients/node_modules/parse-server/lib/ParseServer.js:473
            throw err;
```

**Comment by flovilmart** [comment]
hehe :) no problem, that's good it's not fore everyone but only when push_time is undefined :)

```
> var a  = {push_time: undefined}
undefined
> a
{ push_time: undefined }
> a.hasOwnProperty('push_time')
true
```

**Comment by felipemobile** [comment]
Sure 👍  But push_time will be always undefined when not set on the dashboard.

**Comment by flovilmart** [comment]
so we need to check for `typeof push_time !== 'undefined'`

**Comment by felipemobile** [comment]
I hope this fixes the issue.
https://github.com/parse-community/parse-server/pull/3824
