### ISSUE TITLE
High CPU usage when using parse-server with clusters

### ISSUE THREAD

**Issue by zack1991** [parse-community/parse-server#3828]
Hi,

I am using latest version of parse-server(2.3.8) for my slots casino app and app is comunicating to server frequently just like real time game.
My server configuaration is -

DB Server - Mongo Atlas(M30 - 8GB RAM, 40GB storage), Mongodb 3.4
Parse Server - Rackspace(15GB RAM, 50GB Storage, 8 Core), Nodejs - 6.10.2

For multithread support i am using clustering using pm2(v2.4.0). I am using 6 core from 8 for clustering.
Currently there is max 10-20 Concurrent users. Initial when i startup the parse server using clustering - 
pm2 start main.js -i 6
The cpu usage us max 2% - 5%. After 1 day the cpu usage becomes 70% - 90% while the concurrent users are 10-20 or less.

I am attaching the CPU usage screenshot.

![cpu usage](https://cloud.githubusercontent.com/assets/26978206/26218645/62c32f66-3c29-11e7-8faf-d1644002d771.png)

Please help me how to minimize the cpu usage, where i am going wrong.

**Comment by flovilmart** [comment]
parse-server consumes CPU only when processing requests. Besides the custom code you can run in cloud code, there should be nothing running when not processing requests. Now, you could have a very high CPU usage if you have many requests per seconds coming onto your machine. I'm not sure what you mean by frequently, bu you should probably profile your app in a closed environment.

Do you have particularly large queries you run, with many includes etc? How does it behave on a development machine?

In any case, your question would probably find a better answer on stackoverlow than here.
