### ISSUE TITLE
Blogs about parse-server running on google container engine

### ISSUE THREAD

**Issue by ranhsd** [parse-community/parse-server#3829]
Hi, I started to write a series of blogs in medium.com on how to run deploy parse-server to google container engine. In this series i cover the following topics: 

1. Run parse-server on your local machine via docker compose
2. Deploy and run your parse-server on google container engine and run it in cluster environment.
3. Use kube-lego + lets encrypt to automatically generate certificate for your parse-server instance for FREE. 
4. Create a simple iOS mobile app which leverage parse iOS SDK and consume parse-server api's 
5. Add real time capabilities to the iOS app via parse live queries. 

The name of the series is **From Zero to Hero** because i assume that you start from scratch without having any idea about parse-server or google container engine.

Currently only part 1 and 2 are ready and part 3 will be ready soon. (i assume on next week). 

@flovilmart - What do you think about adding it to the docs/wiki? 

So if  you are running on GCP or thinking about moving to GCP and specifically running on container engine go ahead and read the following blogs: 

[From Zero to Hero — run parse-server on Google Cloud Platform Part 0 — Introduction](https://medium.com/@ran.hassid/from-zero-to-hero-run-parse-server-on-google-cloud-platform-part-0-introduction-54e7725c7ba0)

[From Zero to Hero — run parse-server on Google Cloud Platform Part 1— Run parse-server and MongoDB locally with docker-compose](https://medium.com/@ran.hassid/from-zero-to-hero-run-parse-server-on-google-cloud-platform-part-1-run-parse-server-and-mongodb-63a5f89f670d)

[From Zero to Hero — Run parse-server on google cloud platform part 2 — Deploy and run parse-server on Google Container Engine](https://medium.com/@ran.hassid/from-zero-to-hero-run-parse-server-on-google-cloud-platform-part-2-deploy-and-run-parse-server-86e5d93296a3)

Thanks, 
Ran.

**Comment by flovilmart** [comment]
Sounds like a great idea to put in the wiki!

**Comment by natanrolnik** [comment]
I've added the 3 links to the [Wiki](https://github.com/parse-community/parse-server/wiki), in the tutorials section.

Toda, @ranhsd 😉

**Comment by ranhsd** [comment]
Hi @natanrolnik.
Thanks for this but the name should be from zero to hero and not from Hero to Zero :) 

Anyway, I am about to write part 3 and 4 and I will let you know as soon as it will be ready ...

Ran.

**Comment by natanrolnik** [comment]
Oops, sorry, haha!

Fixed.

Sure, ping me here when you do so and I'll update it.

**Comment by ranhsd** [comment]
Thanks a lot. Good to see that you are from Israel as well ! ;)

**Comment by natanrolnik** [comment]
🇮🇱

**Comment by ranhsd** [comment]
Hi @scdi yes it was... here you go: 

https://medium.com/google-cloud/from-zero-to-hero-run-parse-server-on-google-cloud-platform-part-3-automatically-obtain-lets-d7db8994000a

**Comment by scdi** [comment]
Thanks. Awesome tutorial!
I got stuck temporarily because I put a different name for the disk, as is in step 3 
Filling the following details in the Create a disk form under name the article says to use 
“my-parse-db-disk” instead of “my-parse-app-db-disk.” 
I am glad that happen as that forced me to check every step carefully to grasp better what you were showing.
Thank you so much.
I am just waiting now with the message under mongo-deployment “pods are pending”
Again, thank you!

**Comment by scdi** [comment]
Hi Ran:
I am getting this error message (see attached .png file) would you know how
to fix that when I access. This happens when I access
http://localhost:8001/ui .
