### ISSUE TITLE
I can get a base64 code for a image, how i can upload this image by base64 code

### ISSUE THREAD

**Issue by rorry121** [parse-community/parse-server#3832]
addfiles(imagebase64):Observable<Response> {
    let url = "http://XXXXX:1337/parse/files/111.jpg"
    let addHeader = new Headers();
    addHeader.append("X-Parse-Application-Id","XXXXX")
   addHeader.append("X-Parse-Master-Key","XXXXX")
    addHeader.append("Content-Type","plain/text")
    return this.http.post(url, JSON.stringify({_ContentType: 'image/jpeg', base64: imagebase64}),{headers: addHeader})
  }

And ,the file upload successfully,but when I open it ,it is  string not a jpg ,how to do with it ?

**Comment by natanrolnik** [comment]
We try to use GitHub issues solely for bug reports. Please use StackOverflow for help questions, and use the correct tags ([parse-server](https://stackoverflow.com/questions/tagged/parse-server), for example).
You can post the link to the question here as well.

**Comment by doender** [comment]
I have the same issue. I believe this is a bug?

**Comment by montymxb** [comment]
@doender if you upload an encoded file to parse-server it will _not_ decode it for you. This is not a bug. Whatever is in the file you upload is what the file will retain when you download. If you want your file to to be accessible as a JPG, PNG, PDF, or any other format be sure to set:
- the appropriate content type (for proper interpretation on download)
- the file data as it would be read normally, unencoded

If you upload encoded data, like in base64, the file you will get later will be exactly that, base64 encoded data. In that case you would have to decode that data client side first before viewing.
