### ISSUE TITLE
Roles (ACL) not working properly

### ISSUE THREAD

**Issue by polo2244** [parse-community/parse-server#3833]
### Issue Description
Performing this code in the cloud gives an object not found error.
`var query = new Parse.Query('classname');
query.get('hVYmCOi7M9').then(function(object) { ...` 

---Details----
I have a User (a7MTQFYXA9) belonging to a role (admins).
and object (hVYmCOi7M9) with ACL (r/w to admins role).
I have a cloud function (templateTest) that takes an objectId (in our test case hVYmCOi7M9) from ios SDK and  retrieves this object, and returns a response of the task to be completed.

ROLE
![screen shot 2017-05-19 at 5 48 34 pm](https://cloud.githubusercontent.com/assets/4471168/26253325/ab614e82-3cbb-11e7-80ef-cba7707ace9e.png)

ROLE USERS
![screen shot 2017-05-19 at 5 48 52 pm](https://cloud.githubusercontent.com/assets/4471168/26253337/b44843e8-3cbb-11e7-960b-e465d7fc817c.png)

OBJECT
![screen shot 2017-05-19 at 5 49 32 pm](https://cloud.githubusercontent.com/assets/4471168/26253343/bbf10daa-3cbb-11e7-8f88-a2d0d82d5285.png)

OBJECT ACL
![screen shot 2017-05-19 at 5 49 27 pm](https://cloud.githubusercontent.com/assets/4471168/26253355/c01d113a-3cbb-11e7-9349-862b40c3bdce.png)

Note:
Not restricting the ACL of the object to the role and adding (public read) retrieves the object with no errors. So this may be an Role thing bug

### Steps to reproduce

Please read the explanation above.

#### Expected Results

Object to be retrieved successfully.

#### Actual Outcome

Error object not found

### Environment Setup

- **Server**
  - parse-server version 2.4.0
  - Operating System:    Mac
  - Hardware:             [FILL THIS OUT]
  - Localhost or remote server?  Localhost

- **Database**
  - MongoDB version: 3.4.3
  - Storage engine:  Default (GridStore)
  - Hardware:        [FILL THIS OUT]
  - Localhost or remote server? Localhost

### Logs/Trace
`error: Failed running cloud function templateTest for user a7MTQFYXA9 with:
Input: {"theObjectId":"hVYmCOi7M9"}
Error: {"code":141,"message":{"code":101,"message":"Object not found."}}`

**Comment by polo2244** [comment]
This works in iOS
 `   PFQuery* query = [PFQuery queryWithClassName:@"classname"];
    [query getObjectInBackgroundWithId:@"hVYmCOi7M9" block:^(PFObject* object, NSError* error{
    }];`
The problem may be just in cloud code.

**Comment by polo2244** [comment]
This works in iOS
`PFQuery* query = [PFQuery queryWithClassName:@"classname"]; [query getObjectInBackgroundWithId:@"hVYmCOi7M9" block:^(PFObject* object, NSError* error{ }];`
The problem may just be in cloud code.

**Comment by flovilmart** [comment]
you have to pass the sessionToken of the user making the request:

```
Parse.Cloud.define('func', (req, res) => {
  const sessionToken = req.user.getSessionToken()
  let query = new Parse.Query("...");
  query.get("objectId", {sessionToken: sessionToken}).then(...)
}
```
