### ISSUE TITLE
[Live Query] Subscribe to specific events?

### ISSUE THREAD

**Issue by Ghostw4lk** [parse-community/parse-server#3841]
Hey,

i have a question to subscribe only specific events [create, update...] with live query client.

For example, i only want get ParseObjects which are triggered by the CREATE-Event.
If i update an object on the server, the UPDATE-Event will be triggered.

My question is, is it possible to subscribe only for e.g. CREATE-Events?
Because all other events are not needed in my case and produce unnecessary traffic.

Thanks in adavance.

**Comment by andfk** [comment]
@Ghostw4lk did you checked [this](https://github.com/parse-community/parse-server/wiki/Parse-LiveQuery-Protocol-Specification#create-event)? maybe you get an idea

**Comment by Ghostw4lk** [comment]
@andfk I checked the protocol to work with events, but my problem is, that I only want to subscribe to a single event. 
For example: If I listen on a class called e.g. "Posts", I only want to get CREATE events, but the server sends also UPDATE, DELETE... events, if the ParseQuery matches. @flovilmart said that parse server currently does not support this feature.

**Comment by andfk** [comment]
@Ghostw4lk and `query.subscribe().on('create', (object) => {  console.log(object)  })` is not working in your case?

**Comment by flovilmart** [comment]
There is not way at the moment to subscribe to a subset of events.

**Comment by flovilmart** [comment]
But yes, filtering in the client is supported!

**Comment by Ghostw4lk** [comment]
Yes, thats the point. I only want so subscribe to e.g. CREATE-Events. 
@andfk It works for me.
Filtering can be done by subscription handling, but produces unnecessary traffic for events.
