### ISSUE TITLE
Include user objectid in push payload

### ISSUE THREAD

**Issue by SebC99** [parse-community/parse-server#3844]
### Issue Description

When we use a Query with multiple results to send a push notification to multiple installations/users it would be very useful to include the user objectId by default in the notification payload.
We can do it ourself for notifications which are sent one-by-one (user per user), but it's not possible to add this field when a notification is sent to multiple users with only one query.

Why would anyone need this? To check on the client side if the recipient user is the currently logged user (in case of multiple accounts on the same device)

**Comment by flovilmart** [comment]
The installation don't hold a user by default, many developers may implement it differently, perhaps even without a user. Or keep it a a list, or even a relation. I'm not sure how the general case would work. You can probably do it in a custom push adapter, as the full installation object is passed for sending.  

I can see easily that you can wrap parse-server-push-adapter into a custom module and override / call super on send:

https://github.com/parse-server-modules/parse-server-push-adapter/blob/master/src/ParsePushAdapter.js#L50

**Comment by SebC99** [comment]
Great idea @flovilmart! Thanks a lot for the feedback

**Comment by flovilmart** [comment]
No problem! That should be pretty easy to override and give you the full flexibility! Which is better than modifying parse-server for each particular use case! Good luck!
