### ISSUE TITLE
how to configure Separate LiveQuery Server

### ISSUE THREAD

**Issue by mr3h4n** [parse-community/parse-server#3848]
how to setup liveQuery server separate from ParseServer. so i can handle more number of users for liveQuery notifications.
currently i m using LiveQuery server in same process after configuring in index.js file of ParseServer.
I will be really thankful to you for any kind of favor. thanks

**Comment by flovilmart** [comment]
Have you (at least) visited the docs? http://docs.parseplatform.org/parse-server/guide/#live-queries
