### ISSUE TITLE
Live query for iOS is not work fine

### ISSUE THREAD

**Issue by youngerong** [parse-community/parse-server#3854]
I tried the live query demo for iOS, in the main.swift, both subscribeToUpdates(created event) and subscribeToModify(updated event),  but only the subscribeToModify is valid, so I delete subscribeToModify, then the subscribeToUpdates become valid. So I guess only the latest subscribe function is valid.
But I tried the live query for js, both create and modify event work fine.

**Comment by natanrolnik** [comment]
Please open the issue on https://github.com/parse-community/ParseLiveQuery-iOS-OSX
