### ISSUE TITLE
Making an incremental push and querying the badge number can result in incorrect installations

### ISSUE THREAD

**Issue by aontas** [parse-community/parse-server#3855]
### Issue Description

When making a push, the installation query `{ 'badge': { '$lt': 2 } }` should always return the same installations, regardless of whether the push is set to increment the badge value or not.

Using $gt seems to work fine.

### Steps to reproduce

Add the following test to spec/PushController.spec.js
It should pass, but does not.

```
it('should support lt operators when incrementing badges', (done) => {
    var pushAdapter = {
      send: function (body, installations) {
        return successfulTransmissions(body, installations);
      },
      getValidPushTypes: function () {
        return ["ios"];
      }
    }
    var config = new Config(Parse.applicationId);
    var auth = {
      isMaster: true
    }

    const where = { 'badge': { '$lt': 2 } }

    const payloadNoIncrement = {
      data: {
        alert: 'Hello World!'
      }
    }

    const payloadIncrement = {
      data: {
        alert: 'Hello World!',
        badge: 'Increment'
      }
    }
    var pushController = new PushController();
    reconfigureServer({
      push: { adapter: pushAdapter }
    }).then(() => {
      // Installations have badge counts [0,1,2,3,4]
      var installations = [];
      while (installations.length != 5) {
        const installation = new Parse.Object("_Installation");
        installation.set("installationId", "installation_" + installations.length);
        installation.set("deviceToken", "device_token_" + installations.length)
        installation.set("badge", installations.length);
        installation.set("originalBadge", installations.length);
        installation.set("deviceType", "ios");
        installations.push(installation);
      }
      return Parse.Object.saveAll(installations);
    }).then(() => {
      return pushController.sendPush(payloadNoIncrement, where, config, auth);
    }).then(() => {
     // Wait so the push is completed.
     return new Promise((resolve) => { setTimeout(() => { resolve(); }, 1000); });
    }).then(() => {
      return pushController.sendPush(payloadIncrement, where, config, auth);
    }).then(() => {
     // Wait so the push is completed.
     return new Promise((resolve) => { setTimeout(() => { resolve(); }, 1000); });
    }).then(() => {
      const query = new Parse.Query('_PushStatus');
      return query.find({ useMasterKey: true })
    }).then((results) => {
      // There should be 2 pushes.
      expect(results.length).toBe(2);

      // Each of the pushes should have pushed to 2 devices.
      expect(results[0].get('numSent')).toBe(2);
      expect(results[1].get('numSent')).toBe(2);
      done();
    }).catch((err) => {
      jfail(err);
      done();
    });
  });
```

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.4.1 (seems to exist in all versions so far)
  - Operating System:     Travis CI framework
  - Hardware:             Travis CI framework
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Both

- **Database**
  - MongoDB version: 3.4.4
  - Storage engine:  Travis CI
  - Hardware:        Travis CI
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): Both

### Logs/Trace

The (erroneous) output is:
  - Expected 1 to be 2.

**Comment by aontas** [comment]
The only way I can think of to "fix" it is to increment it after the push is sent for that device, though this still will exhibit race condition behaviour when making multiple pushes that increment the badge number.

i.e., push A sets all badge counts to 2 for badges < 2. push B sets all badge counts to 2 for badges < 2.

Currently, neither A nor B will push to every installation < 2 as the badges will be incremented before the PushWorker/PushQueue finds all the correct installations that need to be pushed to.

Updating the badge count for a device after a push has been made will mean that A or B or BOTH pushes are sent. This behaviour may or may not actually be worse, depending on what is intended..

**Comment by flovilmart** [comment]
@aontas that's a good suggestion, the increment on the installation is effectively performed before we send the push, rendering that query not suitable.

**Comment by flovilmart** [comment]
@aontas are you willing to work on a potential fix?

**Comment by aontas** [comment]
Sure, I can have a look at this. Are you OK with adding a post-increment? Assuming that you would be aware of the caveats as listed in my last comment.

I'll basically get the test as above working (consistently). Let me know if there is something else I should be looking out for as well.

**Comment by flovilmart** [comment]
Post increment may be tricky as the push may be resolved at a later time, when the push queue is actually complete which is never guaranteed, given the current architecture. 
Do you think it's acceptable to mutate the query instead?

**Comment by aontas** [comment]
As long as the outcome is as expected, mutation would be quite acceptable. It sounds like you have an idea of how to fix this. What do you have in mind?

**Comment by flovilmart** [comment]
in the push worker / push queue we could mutate the query in memory (without affecting the stored one) and apply the mutation on the badge constraint if needed (isEqual or less than) if this is an incrementing push. Also if the push sets the badge to 0, etc.. Also, I'm not sure, but do we really need to increment the badges anyway before we send the push? We could just increment in the worker. 
If we send a push with `badge: 10` we don'T write the installation right?

**Comment by aontas** [comment]
The installation written with an update whenever badge is present (update is either set to an incremental or absolute update).
https://github.com/parse-community/parse-server/blob/master/src/Controllers/PushController.js#L30

The badge does not need to be updated prior to pushing, as long as the pushed badge value is still good. Updating the badge value prior to pushing simplifies this logic, as it can just load the data without worrying what sort of updating it needs to do.

I could add something to the push worker to set the badge value (both as a write to the installation and mutation of the pushed badge value) around here: https://github.com/parse-community/parse-server/blob/master/src/Push/PushWorker.js#L92

**Comment by flovilmart** [comment]
This should handle also constraining on badge value and setting a new value (which doesn't work at all ATM). Let's go with that then, and see how it goes.

**Comment by aontas** [comment]
This will be fixed in https://github.com/parse-community/parse-server/pull/4162

**Comment by aontas** [comment]
This is really fixed in https://github.com/parse-community/parse-server/pull/4190
