### ISSUE TITLE
[PROPOSAL/DISCUSSION] AWS DynamoDB support

### ISSUE THREAD

**Issue by benishak** [parse-community/parse-server#3859]
I think DynamoDB is a good integration with Parae, for those who don't want to manage their own database.

I will start writing an Adapter for this.

But which is better, create a different module called parse-server-dynamodb-adapter or put it in this repo?

**Comment by flovilmart** [comment]
That's a great idea, the biggest issue would be testing the adapter as we don't have a specific spec for the dB adapters, but we run the full test suite against them. Ideally, we'd need a single set of specs, that fully covers the database adapters. In the meantime, I believe you can start in that repo, and we'll see how we go from there.

Once the database adapter specs are properly written, I'd move out the Postgres adapter to it's own repository.

**Comment by benishak** [comment]
Also it is even possible to migrate data from MongoDB to DynamoDB using AWS Database Migration Service.AWS claims Zero Down Time

https://aws.amazon.com/about-aws/whats-new/2017/04/aws-database-migration-service-adds-support-for-mongodb-and-amazon-dynamodb/

**Comment by benishak** [comment]
@flovilmart

I almost finished implementing this as an independent adapter, I will publish the repo as soon as I finish testing.

I was able to test it with Parse JS SDK and results are very promising.
I used the same structure as MongoAdapter to minimize or eliminate any changes at the controllers. I also used the MongoTransform from Parse Server, I had only to override some methods and manipulate the Date Type, as DynamoDB doesn't support Date at all! I'm storing dates as string and seems that Parse Server was able to parse it upon read. DyanamoDB also cannot store attributes like `__type` as I wanted to store the pointers as it is without converting it to string but I didn't work so I followed the MongoAdapter way. This is actually good if some people want to migrate from MongoDB to DynamoDB.

Do you have any suggestions how to best write tests for the adapter, is mocking/stubbing the DynamoDB API good idea to make sure it is working as expected?

**Comment by flovilmart** [comment]
> store the pointers as it is without converting it to string 

That's more efficient to convert them to strings

I need to find a way to abstract the loading of the adapter from the test suite, this way you would be able to run the full test suite against your adapter and see what's going on.

**Comment by benishak** [comment]
@flovilmart  you can have a look on the code here
https://bitbucket.org/wahb/parse-server-dynamodb-adapter

I will migrate it later to github when I'm done with testing

**Comment by benishak** [comment]
some tests are now available

**Comment by markmssd** [comment]
@benishak you're the best 👍

**Comment by nitrag** [comment]
@benishak Keep up the good work! Will test when ready, would love to see some cost savings switching to DynamoDB!

**Comment by dplewis** [comment]
Would plain old SQL be worth considering?

**Comment by benishak** [comment]
thanks everyone for the support, I will share the the github repo as soon as i'm done.

@dplewis
I'm not sure what you mean but in DynamoDB doesn't support SQL, it has a custom Expression Language which looks like this
```
#field1 = :value AND #field2 < :value2
```

Now I'm converting the Parse Query which is compatible to MongoDB Query Format ( using JSON ) to DynamoDB expression

**Comment by dplewis** [comment]
@benishak I didn't want to open up a new discussion about adding SQL as a database option

**Comment by benishak** [comment]
@flovilmart In DynamoDB you cannot use `$ne` operator on `_id`, is there any reason why parse is checking the `_id` in this case ?

```
{username: this.data.username, objectId: {'$ne': this.objectId()}}
...
{email: this.data.email, objectId: {'$ne': this.objectId()}}
```
https://github.com/parse-community/parse-server/blob/6cc99aa193f7b733a04748a543c48d2f3ee7fc85/src/RestWrite.js#L420

What is Parse trying to check here ? I replaced that queries with

```
{username: this.data.username}
...
{email: this.data.email}
```

And nothing breaks, can I do a pull request, or it is a change that can break things?

**Comment by flovilmart** [comment]
It's checking the usernames and emails are not already taken by another user.

**Comment by benishak** [comment]
@flovilmart I know that and I can see that, I'm asking what is the sense of passing `{'$ne': this.objectId()}` to the query. It just makes no sense, I think it is safe to remove it and only pass username or email to the query like this
```
{username: this.data.username}
...
{email: this.data.email}
```

**Comment by flovilmart** [comment]
no it isn't that will return the user itself.

**Comment by benishak** [comment]
so what can I do? this is not going to on DynamoDB. In DynamoDB you cannot apply not equal on primary/range key (objectId).

**Comment by benishak** [comment]
I do really see no sense in passing `{'$ne': this.objectId()}`, if `username` exists the `result.length` of the query `{username: this.data.username}`  will be `> 0` anyway!

**Comment by flovilmart** [comment]
Yeah but this is something at the core of the server, I understand your frustration, but I'M not really happy changing something like that because Dynamo doesn't support it, what will you do to support all the queries on objectId then?

**Comment by benishak** [comment]
In DynamoDB there is 2 keys
- partition key (required) : it defines your partition and it is unique, I'm setting this to the className
- sort key (optional) : is the primary key of the partition, it can be anything you want _id or username, but it needs to be able to apply it to all partitions (classes), thus I pick _id. Having a sort key helps index your data, otherwise you have to create multiple indexes, it also ensures uniqueness. 

You don't need to setup a sort key, so I can just not set a sort key but this will make inserting multiple items with the same objectId possible and make ***getting*** items by its id which is incredible fast on dynamodb impossible.

I actually think this part of code is not correct in parse and shouldn't be like that. I will do some tests and come back to you.

in DynamoDB you can use `$eq, $gt, $gte, $lt and $lte, BETWEEN, BEGINS_WITH`

I do really not see any usefulness of using `$ne` in general on the database primary key, I think many databases doesn't allow this either not just DynamoDB.

I only have this problem with SignUp user otherwise who uses DynamoDB should proceed the best practice to query their data.

So I don't think this is the only way to check the existence of a username or email

**Comment by flovilmart** [comment]
We don't have he problem with postgres either. I also read on dynamo that you can apply filters that are run a-posteriori. And this is most probably what you should use for all the constraints on the objectId

**Comment by benishak** [comment]
> var id = new ObjectId()
> id
ObjectId("593f11540db6d3c457ad0a95")
> db.getCollection('_User').insertOne({ _id: id, username: 'benishak', email : 'benishak@github.com' })
{
	"acknowledged" : true,
	"insertedId" : ObjectId("593f11540db6d3c457ad0a95")
}
> db.getCollection('_User').find()
{ "_id" : ObjectId("593f11540db6d3c457ad0a95"), "username" : "benishak", "email" : "benishak@github.com" }
> db.getCollection('_User').find({ username : 'notbenishak', _id : { $ne : id2 } })
> db.getCollection('_User').find({ username : 'notbenishak', _id : { $ne : new ObjectId() } })
> db.getCollection('_User').find({ username : 'notbenishak' })
> db.getCollection('_User').insertOne({ _id: id2, username: 'notbenishak', email : 'notbenishak@github.com' })
{
	"acknowledged" : true,
	"insertedId" : ObjectId("593f11ae0db6d3c457ad0a96")
}
> db.getCollection('_User').find({ username : 'notbenishak', _id : { $ne : new ObjectId() } })
{ "_id" : ObjectId("593f11ae0db6d3c457ad0a96"), "username" : "notbenishak", "email" : "notbenishak@github.com" }
> db.getCollection('_User').find({ username : 'notbenishak' })
Thanks!
In DynamoDB there is 2 kinds of Filters/Query Conditions

- [KeyConditionExpression / KeyConditions](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/LegacyConditionalParameters.KeyConditions.html): Query on the partition/sort key, For KeyConditions, only the following comparison operators are supported: `EQ | LE | LT | GE | GT | BEGINS_WITH | BETWEEN` and you cannot include attributes that are not partition or sort key, all queries MUST contains at least the partition key.

- [FilterExpression / QueryFilter](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/LegacyConditionalParameters.QueryFilter.html): Filter to apply on ***other*** non-key attributes and support all kind of comparisons 

A Query can contain both KeyConditions and QueryFilter

```
params = {
    TableName: "Music", 
    KeyConditionExpression: "className = '_User' AND _id = 123467",
    FilterExpression: "username = 'benishak'
}

Dynamo.query(params, callback)
```

So back to the checking the existence of a username, I did some tests, here is a way to make it works in all for DynamoDB and not break anything, that query is only useful if an existent user tried to change his username to the same username he is already have

```
// ...
let _this_objectId = this.objectId();
return this.config.database.find(
    this.className,
    {username: this.data.username},
    {limit: 1}
  ).then(results => {
    if (results.length > 0) {
      let foundUser = results[0];
      if (foundUser.objectId === this.objectId()) return;
      throw new Parse.Error(Parse.Error.USERNAME_TAKEN, 'Account already exists for this username.');
    }
    return;
  });

// do the same for email
```

I think this is a reasonable solution, isn't it?

**Comment by flovilmart** [comment]
I doubt that this will be the only thing that require a change to be compatible with the whole test suite.

**Comment by flovilmart** [comment]
How do you run the tests? 
You should probably:
1. Fork the repo
2. Add your database adapter
2. In spec/helper.js load/configure your adapter
3. Setup Travis accordingly
3. Probably apply your signup patch

And report back with the failures.

**Comment by benishak** [comment]
@flovilmart 
I'm have this temporary repo, you can check the tests
https://travis-ci.org/benishak/parse-server/jobs/242707542

After a while I start getting these errors, the connection is closed and never opened again

```
- Error: listen EADDRINUSE :::8378
      - Failed: There were open connections to the server left after the test finished 
```

**Comment by markmssd** [comment]
@benishak when you're done i will use your adapter as a reference for writing one for Neo4J graph database, keep up the good work!

**Comment by benishak** [comment]
for now most tests are passing for Parse.Query

```
Parse.Query testing
    ✓ basic query
    ✓ notEqualTo with Relation is working
    ✓ query with limit
    ✓ containedIn object array queries
    ✓ containsAll number array queries
    ✓ containsAll string array queries
    ✓ containsAll date array queries
    ✓ containsAll object array queries
    ✓ equalTo queries
    ✓ equalTo undefined
    ✓ lessThan queries
    ✓ lessThanOrEqualTo queries
    ✓ greaterThan queries
    ✓ greaterThanOrEqualTo queries
    ✓ lessThanOrEqualTo greaterThanOrEqualTo queries
    ✓ lessThan greaterThan queries
    ✓ notEqualTo queries
    ✓ containedIn queries
    ✓ notContainedIn queries
    ✗ objectId containedIn queries
      - Expected 3 to equal 2.
      - Expected 2 to equal 3.
    ✓ objectId equalTo queries
    ✓ find no elements
    ✓ find with error
    ✓ get
    ✓ get undefined
    ✓ get error
    ✓ first
    ✓ first no result
    ✓ first with two results
    ✓ first with error
    ✓ notEqualTo object
    ✗ skip
      - Expected 2 to equal 1.
      - Expected 2 to equal 0.
    ✓ skip doesn't affect count
    ✗ count
      - Expected 7 to equal 8.
    ✗ order by ascending number
      - Expected 3 to equal 1.
      - Expected 1 to equal 2.
      - Expected 2 to equal 3.
    ✗ order by descending number
      - Expected 2 to equal 3.
      - Expected 1 to equal 2.
      - Expected 3 to equal 1.
    ✗ order by ascending number then descending string
      - Expected 2 to equal 1.
      - Expected 'd' to equal 'b'.
      - Expected 3 to equal 2.
      - Expected 'a' to equal 'd'.
      - Expected 1 to equal 3.
      - Expected 'b' to equal 'c'.
      - Expected 'c' to equal 'a'.
    ✗ order by descending number then ascending string
      - Expected 2 to equal 3.
      - Expected 'd' to equal 'a'.
      - Expected 1 to equal 2.
      - Expected 'b' to equal 'd'.
      - Expected 3 to equal 1.
      - Expected 'a' to equal 'b'.
    ✗ order by descending number and string
      - Expected 2 to equal 3.
      - Expected 'd' to equal 'c'.
      - Expected 1 to equal 2.
      - Expected 'b' to equal 'd'.
      - Expected 3 to equal 1.
      - Expected 'c' to equal 'b'.
    ✗ order by descending number and string, with space
      - Expected 2 to equal 3.
      - Expected 'd' to equal 'c'.
      - Expected 1 to equal 3.
      - Expected 'b' to equal 'a'.
      - Expected 3 to equal 2.
      - Expected 'c' to equal 'd'.
      - Expected 3 to equal 1.
      - Expected 'a' to equal 'b'.
    ✗ order by descending number and string, with array arg
      - Expected 2 to equal 3.
      - Expected 'd' to equal 'c'.
      - Expected 1 to equal 3.
      - Expected 'b' to equal 'a'.
      - Expected 3 to equal 2.
      - Expected 'c' to equal 'd'.
      - Expected 3 to equal 1.
      - Expected 'a' to equal 'b'.
    ✗ order by descending number and string, with multiple args
      - Expected 'a' to equal 'c'.
      - Expected 'c' to equal 'a'.
      - Expected 1 to equal 2.
      - Expected 'b' to equal 'd'.
      - Expected 2 to equal 1.
      - Expected 'd' to equal 'b'.
    ✓ can't order by password
    ✗ order by _created_at
      - Expected 1 to equal 3.
      - Expected 3 to equal 1.
    ✗ order by createdAt
      - Expected 1 to equal 2.
      - Expected 2 to equal 1.
    ✓ order by _updated_at
    ✗ order by updatedAt
      - Expected 3 to equal 4.
      - Expected 4 to equal 2.
      - Expected 2 to equal 3.
    ✓ time equality
    ✓ time lessThan
    ✓ time createdAt
    ✗ matches string
      - Expected 0 to equal 1.
    ✗ matches regex
      - Expected 0 to equal 1.
    ✓ case insensitive regex success
    ✓ regexes with invalid options fail
    ✗ Use a regex that requires all modifiers
      - Expected 0 to equal 1.
    ✗ Regular expression constructor includes modifiers inline
      - Expected 0 to equal 1.
    ✗ contains
      - Expected 0 to equal 4.
    ✗ startsWith
      - Expected 0 to equal 2.
    ✗ endsWith
      - Expected 0 to equal 2.
    ✓ exists
    ✓ doesNotExist
    ✓ exists relation
    ✓ doesNotExist relation
    ✓ don't include by default
    ✓ include relation
    ✓ include relation array
    ✓ nested include
    ✓ include doesn't make dirty wrong
    ✓ properly includes array
    ✓ properly includes array of mixed objects
    ✓ properly nested array of mixed objects with bad ids
    ✓ properly fetches nested pointers
    ✓ result object creation uses current extension
    ✓ matches query
    ✓ select query
    ✓ $select inside $or
    ✓ dontSelect query
    ✓ dontSelect query without conditions
    ✗ equalTo on same column as $dontSelect should not break $dontSelect functionality (#3678)
      - Expected 2 to equal 0.
    ✓ multiple dontSelect query
    ✓ object with length
    ✓ include user
    ✓ or queries
    ✓ or complex queries
    ✗ async methods
      - Expected 9 to equal 1.
      - Expected 9 to equal 10.
    ✗ query.each
      - Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
    ✗ query.each async
      - Expected undefined to equal 1.
      - Expected undefined to equal 1.
      - Expected undefined to equal 1.
      - Expected undefined to equal 1.
      - Expected undefined to equal 1.
    ✓ query.each fails with order
    ✓ query.each fails with skip
    ✓ query.each fails with limit
    ✓ select keys query
    ✓ select keys with each query
    ✗ notEqual with array of pointers
      - Expected 2 to equal 1.
      - Expected '8y6dKBH7yv' to equal 'EVxsLFmqvP'.
    ✗ querying for null value
      - Expected 0 to equal 1.
      - TypeError: Cannot read property 'get' of undefined
    ✓ query within dictionary
    ✓ supports include on the wrong key type (#2262)
    ✓ query match on array with single object
    ✓ query match on array with multiple objects
    ✓ should properly interpret a query v1
    ✓ should properly interpret a query v2
    ✓ should match a key in an array (#3195)
    ✗ should find objects with array of pointers
      - Expected 0 to be 2.
    ✓ query with two OR subqueries (regression test #1259)
    ✗ objectId containedIn with multiple large array
      - Expected 0 to equal 1.
    ✓ include for specific object
    ✓ select keys for specific object
    ✓ select nested keys (issue #1567)
    ✓ select nested keys 2 level (issue #1567)
    ✓ select nested keys 2 level without include (issue #3185)
    ✓ properly handles nested ors
    ✓ should not depend on parameter order #3169
```

the falling tests are expected to fail because of these reasons
- DynamoDB doesn't support matching strings using $regex, however I made `startsWith` and `contains` work with simple strings, like `startsWith('foo'), contains('bob')`, but I try to improve this at the moment
- DynamoDB doesn't support skipping, however it does support pagination, skip should include an `ObjectId` from where DynamoDB should skip results, I try to make this possible, but pagination using `$gt / $lt` should work on any key.
- DynamoDB doesn't support sorting on keys other than `objectId`, however I may do sorting on the adapter layer
- containedIn array should not include more than 100 values!

However
- query.each and query.each async should succeed, they succeed sometimes, but sometimes they timeout, I'm looking into this at the moment
- I don't know when you insert an array of ***Pointers*** they are not transformed to strings like `['_User$1234', '_User$1230` ...]`, using the attribute name `__type` is an issue in DynamoDB, it seems to be a reserved keyword ... I can try to transform the array or the attribute `__type`, using `_type` or `type` or `___type` is just fine.

I also solved the issue of User SignUp and applying filters/query on the `objectId` by duplicating the field, this make `fetch, `include` and `get` queries fast because DynamoDB is hybrid key-value document-store database, I check if the query includes the key `_id` I use `getItem` otherwise `query` method.

**Comment by benishak** [comment]
current status
```
Executed 1241 of 1271 specs (57 FAILED) (27 PENDING) (3 SKIPPED) in 11 mins 46 secs.`
```

Most of the 57 Failing tests are compatibility issues:
- Unique Indexes : DynamoDB doesn't support this, however I'm thinking in creating a collection with the name `_UNIQUE_INDEX` and put entries in that information about unique fields, I will load the content of that collection in inMemoryCache at Adapter initialization and before inserting/updating I will check for duplication by issuing a query.

- Date : DynamoDB cannot store date objects, I transform them into 'string', Parse seems to handle this without problem. While reading data, I can see `createdAt, updatedAt` and other date attributes having the correct value but some tests are trying something like `changedAt.getTime()` which fails because `changedAt` is a string, I will solve this by loading the schema at Query then check fields with `date` types and transform them back to date Object

### Other compatibility issues:
- Skip : Can be solved if Parse.Query.skip() can pass a string, by passing an objectId, skip is doable)
- Sort : After sort is doable by local sorting however if you want to sort before you query the data, this is going to be impossible!
- Matching string with RegEx : except for contains('string') and startsWith('string') there is no solution for this

Otherwise : 
this queries are failing and **succeeding** randomly : 
- Parse.Query query.each
- Parse.Query query.each async
- Parse.Query async methods
assertion is being executed too early, but I debugged the outputs of the query and they are as expected!

what do you think @flovilmart ?

**Comment by benishak** [comment]
stable release
https://github.com/benishak/parse-server-dynamodb-adapter

also available via npm
https://www.npmjs.com/package/parse-server-dynamodb-adapter

I will include the parse-server specs in the tests soon. Till now all tests are passing except 18 tests are failing due to limitations in DynamoDB.

enjoy!

**Comment by flovilmart** [comment]
Awesome Job! If you wanna add the link to the module on the parse-community.github.io and docs, feel free to open the PR’s!

**Comment by nitrag** [comment]
>  failing due to limitations in DynamoDB.

Limitations with the test cases or permanent limitations due to DynamoDB? I'm confused - if the tests are failing, not 100% pass, shouldn't that mean that DynamoDB can't really fully utilize the Parse platform and there will be broken features?

**Comment by benishak** [comment]
@flovilmart Thanks! sure I will!

@nitrag 
Not necessarily, the specs are already skipping some tests for other databases too.

I guess permanent limitations due to DynamoDB, It could be solved in the future if AWS add these features.
I listed compatibilities in the repo, you can check them
Major limitations includes 
Skip (although this is due to Parse SDK cannot pass string, however skip in DynamoDB can be done by passing the objectId
Sort : you can sort by objectId but not by other keys
RegEx is not supported but you still can use startswith and contains with strings
You cannot have object bigger than 400KB
You cannot use $in operator with an array larger than 100 when using containedIn
GeoPoints operations like $near ... etc are not supported but you can save GeoPoints as object or array
Uniqueness cannot be guaranteed if you insert data in parallel but this is not an issue, I don't think that 2 users or more in this world will come to signup with the same username at the same moment and their finger hit the submit button at the same exact moment.

I tried my best to make some operations works with workaround like sorting which work but after the results are found, this is okay, unless you want to combine it with skip for pagination or so.

Otherwise there should be no issue using DynamoDB with Parse, a lot of apps doesn't need RegEx, GeoPoints, storing large arrays ... etc
