### ISSUE TITLE
"Unauthorized" error with push notifications / cloud code

### ISSUE THREAD

**Issue by bmueller** [parse-community/parse-server#3860]
### Issue Description

I haven't touched my Parse server in almost a year, but today I had to upload new push notification certificates to keep everything running. I added the new p12 certificates (without changing anything else), pushed the changes to Heroku, and immediately started getting an "[Error]: unauthorized (Code: 0, Version: 1.13.0)" message in my console. In my Heroku logs, I was getting code 403 for every push I tried to send using Cloud code. I could still access my dashboard and view data, etc. So it seems like my Cloud code is just broken in some way.

I noticed that my Parse Server version jumped from 2.2.16 to 2.2.25 after pushing these changes. When I reverted the changes and went back to 2.2.16, everything started working again.

Did something change between these two versions that might be causing my Cloud code to break? Is there a way to require a specific version of Parse Server so I can just keep using 2.2.16 and get these new certificates uploaded?

### Steps to reproduce

Here is the cloud code I am using. Works fine on 2.2.16, not working on 2.2.25.

Parse.Cloud.define('sendPush', function(req, res) {

  Parse.Push.send({
    channels: [req.params.channel],
    data: {
      alert: {
        title: req.params.title,
        body: req.params.body,
      },
      sound: req.params.sound,
      category: req.params.category,
      userInfo: req.params.userInfo,
    }
  },
  {
    success: function() {
      res.success('push success!');
    },
    error: function(error) {
      res.error(error);
    },
    useMasterKey: true,
  });
  
});

#### Expected Results

Push works successfully.

#### Actual Outcome

Push fails with an unauthorized message.

### Environment Setup

- **Server**
  - parse-server version : 2.2.25
  - Operating System:  macOS
  - Hardware:  iMac
  - Localhost or remote server? Heroku

- **Database**
  - MongoDB version:
  - Storage engine:  
  - Hardware:      
  - Localhost or remote server? mLab

### Logs/Trace

macOS app log: 
[Error]: unauthorized (Code: 0, Version: 1.13.0)
Error Domain=Parse Code=0 "unauthorized" UserInfo={error=unauthorized, NSLocalizedDescription=unauthorized, temporary=0}

Heroku log:
at=info method=POST path="/parse/functions/sendPush" host=XXX.herokuapp.com request_id=29e21e05-284c-4965-8a66-36e240e0537f fwd="XXX" dyno=web.1 connect=1ms service=3ms status=403 bytes=466 protocol=http

**Comment by bmueller** [comment]
Changing the 'parse-server' version in package.json to '2.2.16' from '~2.2.16' appears to have fixed the problem.

**Comment by natanrolnik** [comment]
I recommend you doing the following:

1 - Separate your `data` into an object, will make things more readable.
```
var pushData = {
  channels: [req.params.channel],
  data: {
    alert: {
      title: req.params.title,
      body: req.params.body,
    },
    sound: req.params.sound,
    category: req.params.category,
    userInfo: req.params.userInfo,
  }
}
```

2 - Then, instead of having success and error as functions, use the promise syntax:

```
Parse.Push.send(pushData, {useMasterKey: true}).then(function() {
    res.success("Success");
}, function (error) {
    res.error(error);
});
.
```

**Comment by natanrolnik** [comment]
Regarding version - the latest is 2.4.1.
