### ISSUE TITLE
Unable to retrieve and upload files (images) from parse-server hosted on amazon beanstalk

### ISSUE THREAD

**Issue by rahulfreecodecamp** [parse-community/parse-server#3880]
From last 15 hrs I am not able to retrieve and upload the files, I my database is on mlab.com  Everything else is working fine. Please help me to resolve this issue.

**Comment by flovilmart** [comment]
You may have exceeded the max size of your database if you're using the Default storage adapter.

**Comment by rahulfreecodecamp** [comment]
thanks for the reply. I'm using default storage adapter, now I have to increase my mlab.com db space right??

**Comment by natanrolnik** [comment]
Yes. Because of this (and a few other reasons), you should use an external storage, like Amazon S3 or Google Cloud Storage.
