### ISSUE TITLE
cant save file.url

### ISSUE THREAD

**Issue by shi1hh** [parse-community/parse-server#3890]
when i update
```
{"method": "PUT",
  "path": "/1/classes/Task/3OIU6Gdsv2",
  "body": {
      apk:{"__type":"File","name":"cweeqrt.txt","url":"http://qewqee.apk"}
  }
```
it allways update the filename without url.
i found parse-server not save the url....why?
so. i can create object field for save this or any idea?

**Comment by flovilmart** [comment]
parse-server is responsible for creating the URL's for your files and at the moment it's not possible to save a file only from the URL.
