### ISSUE TITLE
Load Testing Parse Server

### ISSUE THREAD

**Issue by faizsameerahmed96** [parse-community/parse-server#3893]
Since Parse Server has been out for a few months now, I am planning to run a load test on Parse Server (on AWS platform) to get an estimate for the cost/request for various AWS instances. Initially I will be using the MongoDB database on the same server but later on we can try it for a seperate configuration. I need a few suggestions on the following:
1) What is the best way load test a server? I am thinking of https://www.npmjs.com/package/loadtest
2) Any recommended way to run the Write/Read test to get a proper reading?

Let me know if there is anything else I should follow. I will start running the tests from June 20th.

**Comment by benishak** [comment]
you can try apache benchmarks (a.k.a. ab)
 https://www.cyberciti.biz/tips/howto-performance-benchmarks-a-web-server.html

**Comment by natanrolnik** [comment]
I would recommend you to do a better research about Load Testing in general, this is not a question specific to Parse Server.

I personally like using [artillery.io](https://artillery.io) for a few tests, it might or might not be enough for what you need. 

Please ask the question on StackOverflow.com or serverfault.com as it's more appropriate.
