### ISSUE TITLE
twitter not logged in with parse

### ISSUE THREAD

**Issue by kukkadapukarhtik** [parse-community/parse-server#3900]
when ever try to login with twitter in parse the below error occuring

TwitterLoginWithParseExample[2581:116523] Error: Error Domain=com.parse.networking.error Code=-1011 "Expected status code in (200-299), got 410" UserInfo={NSLocalizedDescription=Expected status code in (200-299), got 410, NSErrorFailingURLKey=https://api.parse.com/2/user_signup_or_login} (Code: 100, Version: 1.2.19)

**Comment by flovilmart** [comment]
Now sure how you try to login but the URL is wrong (https://api.parse.com/2/user_signup_or_login)
