### ISSUE TITLE
Swift 3.0 Progress block is giving extra argument call:

### ISSUE THREAD

**Issue by xhiza** [parse-community/parse-server#3907]
Hi,
Facing issue with creating progressBlock for both upload and download PFFile.

let str = "Working at Parse is great!"
let data = str.dataUsingEncoding(NSUTF8StringEncoding)
let file = PFFile(name:"resume.txt", data:data)
file.saveInBackgroundWithBlock({
  (succeeded: Bool, error: NSError?)  in
}, progressBlock: {  // =================> Extra argument call: ??????
  (percentDone: Int32)  in
})

**Comment by natanrolnik** [comment]
We use GitHub issues only for tracking bugs with Parse Server itself, not code questions, and much less for the SDKs.

Please ask a question in StackOverflow for code help.
