### ISSUE TITLE
Roadmap?

### ISSUE THREAD

**Issue by samiq** [parse-community/parse-server#3909]
Hi guys, we've been running on Parse for a good part of 3 years now and as we evaluate our ongoing infrastructure I wonder if there is any roadmap against which Parse is working on or is it in just pure maintenance mode nowadays?

**Comment by oallouch** [comment]
Yeah. It's good to communicate from time to time and say where we're heading.
A blog post would be nice.

**Comment by flovilmart** [comment]
@samiq thanks for the question. We're definitely not in maintenance mode, new features land with each release, and the client SDK's have trouble too keep up! For example, we're about to release polygonal geoqueries as well as full text search support.

We welcome ideas and contributions from users like you, and most definitely prioritize high value features that would help you be more efficient. Did you had any requirements in mind? 

I'm more than open to discuss a high level roadmap openly, and set milestones to organize the development flow!

**Comment by dplewis** [comment]
+1

**Comment by geekyfox90** [comment]
+1

**Comment by samiq** [comment]
@flovilmart in our case there are things that relate to client and others to the server, but it all boils down to not knowing what's coming and how things are/have been prioritised. also would be great to know how server vs clients keep up to date and such, also would be great to be able to discuss specifics of the roadmap. can you guys share some light into how the process is currently?

**Comment by flovilmart** [comment]
The process is totally open at the moment, on a case by case basis. For example, I mostly contribute on features I need on my day job, and also respond as fast as possible to open issues. I spend a lot of time in PR review and making sure new features get in as fast as possible. When a new release is either critical of feature complete enough we make a new release. We're welcoming new features and suggestions, I you want a specific roadmap, I'm afraid I would not be able to give 1 for you, but I welcome any suggestions and we could put those suggestions into milestones.

**Comment by oallouch** [comment]
I see a lot of new big features coming: Neo4J db adapter, Job Scheduling, Audience endpoint...

**Comment by samiq** [comment]
@oallouch @flovilmart would then at least be good to document the epics that are been worked on? or at least use milestones to track them. 

my main concern is that while I see a lot of activity in the parse-server repo, you don't see almost anything happening in the other repos, which makes me question how alive is Parse as a platform and likely would it be for someone to use to kickstart a new project using it rather than sticking with it until they can afford to move somewhere else.

**Comment by flovilmart** [comment]
I don’t have personally time to maintain ‘epics’ if it’s how you wanna call them. We move at community velocity, and unless more people contribute, this velocity is bounded by the effort offered by our contributors. 

While I understand your concerns, from my point of view it’s more alive than ever, and we’re about to ship one of our biggest release.

**Comment by oallouch** [comment]
@flovilmart is there an official parse-server Twitter account ? Is it @parseopensource so that we can, at least, "massively" retweet announcements ?

**Comment by flovilmart** [comment]
I usually post them personally, `@parseopensource` is handled and managed by Sashi.do

**Comment by oallouch** [comment]
@flovilmart so we'll retweet from your account. Though, I understand @samiq 's frustration. All those amazing new features and no one knows it...

**Comment by flovilmart** [comment]
I understand the frustration as well. It all boils down to the community, I can’t possible oversee all aspects of all repositories either. The polygonal queries are being integrated in the client Sdk’s As we speak. If you find some features are missing in the SDK’s compared to the REST API, the best is to open an issue. 

@samiq i can guarantee that the project is more open than ever, that we listen closely to the needs of each and everyone. As with every OSS project, you can adopt 2 stances, wait for the features you need to be built, or invest a bit of your time / engineering time to make those happen quickly. We usually release on a bi-weekly basis. This one is getting a bit hold up as we’ll have many new features in, and i’d Rather wait till they are all merged.

**Comment by MobileVet** [comment]
@flovilmart Can you post a bitcoin or similar address so we can send you a little alt-coin appreciation?

**Comment by flovilmart** [comment]
@MobileVet we have setup open collective for that! https://opencollective.com/parse-server

**Comment by Sadmansamee** [comment]
any paypal or anything else then bitcoin to send appreciation?

**Comment by flovilmart** [comment]
@sadmansamee we’re using open collective at the link above, we’ll be exploring additional donations in the future! Thanks for the support!
