### ISSUE TITLE
LoggerAdapter for logs DB - aggregate logs from multiple servers

### ISSUE THREAD

**Issue by peterdotjs** [parse-community/parse-server#391]
We currently use a `LoggerAdapter` which uses `FileLoggerAdapter` by default. `FileLoggerAdapter` simply logs locally to a logs folder. It would be great to have an adapter where the logs are sent to a DB to handle multiple servers.

**Comment by boardmain** [comment]
hi can you provide an example on how you use logger?
im trying to understand from documentation but it is realy bad

**Comment by peterdotjs** [comment]
@boardmain what is unclear on using the adapter? https://github.com/ParsePlatform/parse-server/wiki/FileLoggerAdapter.js

You can also look at the test if you are still unclear. https://github.com/ParsePlatform/parse-server/blob/master/spec/FileLoggerAdapter.spec.js#L30

**Comment by boardmain** [comment]
im trying to use it with the loggerAdapter option from the example parse server app.. i'm missing something (first time i use parse server)

**Comment by drew-gross** [comment]
This doesn't seem like a highly requested feature. Moving to long term.

**Comment by montymxb** [comment]
About a year old, going to close this out as there hasn't been any talk about putting this in. Seems like a good idea however. If this is still of interest let us know and we can try and put this into a more 'active' phase and get a PR going!

**Comment by trylovetom** [comment]
I am interested in this Issue.
It's might be of use to me on cluster of parse-server.
Maybe I can do it.
Does anyone agree?

**Comment by montymxb** [comment]
Not personally running a cluster so hard for me to judge outright,
@flovilmart think it's reasonable for this to be pursued?

**Comment by flovilmart** [comment]
I don't think it's reasonable to pursue it, as you'd have to integrate a centralized logger in any case, which can be done through a custom adapter.

**Comment by trylovetom** [comment]
@flovilmart 
OK, I got it. Maybe I can make a custom logger adapter replace it.
Could you please give me some advice?
This is my first time to make a adapter of parse-server.

**Comment by flovilmart** [comment]
The logger adapter is quite simple, it jhas to implement 1 method for writing (log()) and one for reading, (query)

see: https://github.com/parse-community/parse-server/blob/master/src/Adapters/Logger/LoggerAdapter.js#L11


You can also look into the default logger [here](https://github.com/parse-community/parse-server/blob/master/src/Adapters/Logger/WinstonLoggerAdapter.js#L6) as it provides a decen example of what's exepected.
