### ISSUE TITLE
How to copy a Parse.File(image)

### ISSUE THREAD

**Issue by AnChiChang** [parse-community/parse-server#3929]
I am use express + parse server, I want to design a function in server side node.js to copy the image. I can query and get the existing Parse File, but how to copy and save a new one ?

    var imageQuery = new Parse.Query("ProductImage");
    imageQuery.equalTo("products", product);
    imageQuery.find({
        success: function(productImages) {

            if (productImages.length > 0) {
                var image = productImages[0].get("imgoneS");
                for (var key in image) {
                    console.log(key + ": " + image[key]);
                }
                //console.log key only _url and _name
                //how to copy a new image and save?

            }

        },
        error: function(error) {
            console.error("product_stat_copyproduct ProductImage query error: " + error);

        }
    })

**Comment by natanrolnik** [comment]
We try to keep GitHub issues for issues and bugs specific of Parse Server.

This is more a JS question also, not specific to the Parse JS SDK.
Please use StackOverflow with the parse-server and parse-js-sdk tags, and post the link here for reference as well.

**Comment by AnChiChang** [comment]
https://stackoverflow.com/questions/44534790/how-to-copy-a-parse-fileimage
