### ISSUE TITLE
How do I set the login expiration time?

### ISSUE THREAD

**Issue by lxq20081128** [parse-community/parse-server#3930]
How do I set the login expiration time?

**Comment by MartinHerman** [comment]
Once a user logs in, a Session object is created - containing a "createdAt" and "expiresAt" parameter. The expiration time defaults to 1 year from creation and I'm not sure if you can change that somewhere.

What you could try:
- Fetching the Session object and overwriting the "expiresAt" time
- Creating a Cron job that would delete old Sessions every day

**Comment by lxq20081128** [comment]
Can I change the default expiration time?
我是否可以变更默认过期时间？






------------------
              
         公司网址：http://www.mengsens.com/
         
         
                      广东梦森信息科技有限公司 -              廖晓清
             公司地址：广州市海珠区新港西路135号中山大学国家大学科技园B座1308室
         
         手机号码：139 2609 5308
         QQ号码 ：187 2117 737
         主营业务：快递鸽 - 快递物流综合解决方案
     
     
     
     祝：生活愉快！一切顺利！
 

 
 
 
------------------ Original ------------------

**Comment by steven-supersolid** [comment]
This is controlled with the config property `sessionLength` if mounting parse as express middleware, or with the environment variable `PARSE_SERVER_SESSION_LENGTH`

**Comment by ghost** [comment]
> This is controlled with the config property `sessionLength` if mounting parse as express middleware, or with the environment variable `PARSE_SERVER_SESSION_LENGTH`

after changing this time how we will run this one ..., if you save that configuration file automatically it will get save or any command we need to run

**Comment by ghost** [comment]
after changing session time how we will run this one ..., if you save that configuration file automatically it will get save or any command we need to run
