### ISSUE TITLE
Email templates

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-server#3931]
Parse server has email templates hard coded for the following cases:

- email verification
- password reset

Is anyone already working on replacing these hard coded templates with external HTML files or has a solution to share?

Related to #2820

**Comment by mtrezza** [comment]
#2820

**Comment by pungme** [comment]
Hey @mtrezza 

This is our solution, We specified `customPages` so it'll be something like:

```
  customPages: {
    choosePassword: '/choose-password',
    ...
  },
``` 

then you can catch it in your route 

```
const router = express.Router();
router.get('/choose-password', (req, res) => res.sendFile(path.resolve(`path-to-the-file/yourownchoosepassword.html`)));
...
```

hope that helps!

**Comment by pcegarra** [comment]
Im using the mailgun adapter template (avaible by npm) to send my own html email

**Comment by pcegarra** [comment]
@pungme  I tried your code without success are you using this feature like your code?

**Comment by pungme** [comment]
@pcegarra yeah we did, but we use mandrill adapter.

**Comment by acinader** [comment]
see the section of the readme on customPages

**Comment by macarthuror** [comment]
You can try this [email adapter](https://github.com/macarthuror/parse-smtp-template) to send custom templates and multi language template support.
Is really simple to use and customise.

Hope you like it 😃🖖
