### ISSUE TITLE
Bug in all Parse releases above 2.2.23: ClientKey cannot be empty

### ISSUE THREAD

**Issue by halvini** [parse-community/parse-server#3936]
Dear Sirs,

I've updated my Parse Server and found out that the latest Parse Server versions, including 2.4.2 do not allow me to connect to it if I use **"PARSE_SERVER_CLIENT_KEY": ""**. The problem is that all our released apps use the blank key to connect to Parse Server, so we can't change it to any other value.

I see there was a "bug fix" on Feb 9, it says that Parse allows empty / null client key, but it's not true:
https://github.com/parse-community/parse-server/pull/3497

We tried downgrading the Parse Server to 2.2.23. It works. If we upgrade it to 2.2.24+, we can't connect to the server anymore with ClientKey = "". If we change the ClientKey to anything but "", it works. Nevertheless, we cannot change the client key to anything but "", because most of our clients have already downloaded the apps with ClientKey = "".

- **Server**
  - parse-server version 2.2.24 - 2.4.2
  - Operating System:     Ubuntu
  - Hardware:             8 CPU, 8 GB RAM, 150GB Disk Space
  - Localhost or remote server? Rackspace

- **Database**
  - MongoDB version: 3.2.8
  - Storage engine:  WiredTiger
  - Hardware:        250GB
  - Localhost or remote server? ObjectRocket

LOGS of the XCode, when trying to connect to Parse Server 2.4.2 with ClientKey = "" (the same key is in the parse server config ecosystem.json):
{ error : unauthorized }.

**Comment by dplewis** [comment]
Look at what I wrote here. Its not your clientKey its probably your other keys.

https://github.com/parse-community/parse-server/issues/356
