### ISSUE TITLE
Server crashing due to invalid apns connection

### ISSUE THREAD

**Issue by abhigyan2311** [parse-community/parse-server#3941]
### Issue Description

Server crashing due to 3invalid apns connection

### Steps to reproduce

`
ERR! parse-server-push-adapter APNS cannot find vaild connection for 14908ebed6e33ca16c94b0418e22e1e99f4a8cd275b03c2a65a6c78639de0f57
ERR! parse-server-push-adapter APNS cannot find vaild connection for 14908ebed6e33ca16c94b0418e22e1e99f4a8cd275b03c2a65a6c78639de0f57
ERR! parse-server-push-adapter APNS cannot find vaild connection for 14908ebed6e33ca16c94b0418e22e1e99f4a8cd275b03c2a65a6c78639de0f57
/home/ubuntu/fas-server/node_modules/parse-server/lib/ParseServer.js:473
            throw err;
            ^

Error: socket hang up
    at TLSSocket.onHangUp (_tls_wrap.js:1094:19)
    at TLSSocket.g (events.js:291:16)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
`

#### Expected Results

Server should not crash 

#### Actual Outcome

Server is always crashing after 3 invalid apns connection

### Environment Setup

- **Server**
  - parse-server version : 2.4.2
  - Operating System:     Mac OS X v10.10.25
  - Hardware:             Macbook Pro
  - Localhost or remote server : AWS

- **Database**
  - MongoDB version: v3.4
  - Storage engine:  RockDB
  - Hardware:        AWS
  - Localhost or remote server? AWS

**Comment by natanrolnik** [comment]
Closing as duplicate #3575
