### ISSUE TITLE
Minimum node.js Version Requirement?

### ISSUE THREAD

**Issue by montymxb** [parse-community/parse-server#3945]
Older versions of node.js may not be compatible with more recent versions of parse-server. Recently I discovered that with the changes made by #3916 parse-server would start on version **4.3.0** of node, but was not functional when requests were submitted.

Although most people won't be _that_ out of date, it's begs the question of at what point should the user be prompted to upgrade their version of node.js, rather than be allowed to run parse-server on it.

I can see there is a constraint in **package.json** under engines for node for `4.6`. If this is what is considered the baseline then perhaps something should be added into parse-server to check and stop the server if the version is less than that?

### Steps to reproduce

Running any version of parse-server at or after the changes added in #3916, using node version `4.3.0` specifically in my instance. 
Also may possibly extend up to node `4.5`, haven't checked how that works out though.

#### Expected Results

Happy server 👍 

#### Actual Outcome

Nonfunctional, specifically with the following log outputs on each request:
```
error: Error handling request: [TypeError: volatileClasses.includes is not a function] 
error: Uncaught internal server error. [TypeError: volatileClasses.includes is not a function] TypeError: volatileClasses.includes is not a function
    at enforceRoleSecurity (/Users/Bfriedman/Documents/parse-server-test/parse-server/lib/rest.js:152:23)
...
```
and after #3927 a similar but separate error
```
error: Error handling request: [TypeError: classesWithMasterOnlyAccess.includes is not a function] 
error: Uncaught internal server error. [TypeError: classesWithMasterOnlyAccess.includes is not a function] TypeError: classesWithMasterOnlyAccess.includes is not a function
    at enforceRoleSecurity (/Users/Bfriedman/Documents/parse-server-test/parse-server/lib/rest.js:162:35)
    ...
```

With all that in mind, it's fairly clear that older versions of npm are not supported, especially given the testing suite targeting `6` and `7` exclusively. But it would perhaps help to add a feature to verbosely express the same in the code as well.

::EDIT::
To clarify the server _will boot_ even if the version of node.js may not be able to properly run parse-server. This is the primary concern, as everything looks fine until an SDK attempts to begin making requests.

**Comment by flovilmart** [comment]
That’s the intent of the engines key. We should still be ok under 4.6, because Babel, but we upped the tests to run current LTS and 7. Not sure if we can do something with earlier version but happy if we can add a runtime check

**Comment by montymxb** [comment]
Gotcha I don't think we'll need to do anything for earlier versions in particular. But adding a runtime check would be a nice way to alert someone to an issue early on. I think I'll go ahead check versions 4.4 - 4.6, just to check out how things are down there. 

As for a runtime check I know there's an `engineStrict` for conditions where `engines` should be strongly adhered to, but it's only an install-time check.  I'll see if on server start we can validate the version of node is supported if that sounds good? I can get around to putting in a PR, and we can go from there.

**Comment by oyvindvol** [comment]
I am experiencing memory problems with parse-server on Heroku. I get memory quota exceeded errors all the time if I am heavily using the app, loading objects, performing queries.

I read that garbage collection in node V8 was not doing garbage collection before memory usage is 1,5GB, and I tried adding a procfile to start garbage collection around 460MB, but I am still getting memory warnings. I have tried changing node version to LTS 6.11.0, but are still getting errors.

So I guess my questions are; what node version are you guys using on Heroku, are you using a Procfile, and is it normal that an app (with a lot of images) are using over 1GB of memory when hosted on Heroku?

**Comment by montymxb** [comment]
@oyvindvol Personally I'm not running anything on heroku so I wouldn't be able to say. As for GC related work that can be tricky business.

If you're loading up lots of images that _may_ be your primary concern. Image data isn't cheap, and tends to weigh in heavily. Especially if multiple images are being uploaded/downloaded simultaneously. Could be a bit of pinch.

I haven't used heroku in some time but perhaps there is a way to profile what's going on while it's running? Ideally you would pin down whether node or mongo is utilizing large quantities of memory (or both) and then you would want to start isolating how. This would involve setting up a small test of sorts, seeing if you replicate the behavior. If you can get to that point (or if you can simply identify the cause to start with) you should start to be able to do research into specifically what can alleviate your issue.

**Comment by oyvindvol** [comment]
@montymxb thanks. 

We are not uploading a lot of images, but the cliens are downloading images in a collection view (iOS). However they are loading as the users scroll down the list, so it`s not loading all the images at once. The images are "thumbnails" at the size of maybe max 700kb. But when I am using AWS S3 for image storage, are the clients loading the images directly from the S3 URL, or are they going via the parse server at Heroku (or whatever hosting provider) ?

**Comment by kgoedecke** [comment]
My server just crashed as well running node 4.4.6 and and parse-server 2.2.22, how do I resolve the issue?

**Comment by flovilmart** [comment]
perhaps use node 6+ as it's LTS.

**Comment by kgoedecke** [comment]
Yeah I just upgraded, everything is back to normal. I'm wondering what happened because we didn't even touch the setup and it was running fine for ages.

**Comment by montymxb** [comment]
@kgoedecke Probably just node.js being outdated. It's possible you triggered a code path that previously wasn't run. With the recent additions to parse-server builds on `4.3.0` crash due to some syntax that is not valid on those versions, it's likely `4.4.6` may be in the same boat.

Beyond that the `engines` property in [package.json](https://github.com/parse-community/parse-server/blob/master/package.json) indicates to use at least version `4.6` or greater for node. Anything below that would not be recommended.

**Comment by montymxb** [comment]
Closing with #3962 having been merged in for minimum version requirement.
