### ISSUE TITLE
Hooks API returning empty array

### ISSUE THREAD

**Issue by jimcamut** [parse-community/parse-server#3947]
### Issue Description

The hooks REST API is not working as expected. Functions and Triggers are not recognized.

### Steps to reproduce

Send a GET request to ```/<mount>/hooks/functions``` with your app ID and master key.

#### Expected Results

Expecting a list of the defined cloud functions, per this documentation: http://docs.parseplatform.org/rest/guide/#fetch-functions

#### Actual Outcome

Status is 200, but an empty array is returned despite hooks and triggers being properly defined.

### Environment Setup

- **Server**
  - parse-server version: 2.2.25
  - Localhost or remote server? Both localhost and AWS

- **Database**
  - Localhost or remote server? Both localhost and AWS

**Comment by flovilmart** [comment]
@jimcamut did you register any hooks as web hooks (http) or cloud code?
