### ISSUE TITLE
Missing Jobs after updating to 2.5.0

### ISSUE THREAD

**Issue by Pikorua** [parse-community/parse-server#3961]
### Issue Description

I just updated to the latest version of parse-server (2.5.0) and all my jobs have disappeared. 

going to https://xxxxx.com/dashboard/apps/WhatTuDu/jobs/all would give me a full list of all the jobs that I have in my cloud code and now all I have is a cloud image with the following text "Cloud Jobs
Define Jobs on parse-server with Parse.Cloud.job()" 

Everything was working great before... 

### Steps to reproduce

run older version of parse with Jobs, update to parse-server 2.5.0 go to jobs page in the dashboard and they are all gone

#### Expected Results

Have a list of all my cloud jobs as before

#### Actual Outcome

Empty list with no jobs

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.5.0
  - Operating System:     AWS elastic beanstalk
  - Hardware:             ec2 instance
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): AWS

- **Database**
  - MongoDB version: mLab
  - Storage engine:  mLab
  - Hardware:        mLab
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): mLab

**Comment by flovilmart** [comment]
This will Be addressed with the next release of the dashboard

**Comment by Pikorua** [comment]
Hi @flovilmart! 
Any idea when you will be pushing an updated version?
We are using jobs very intensively and not having them listed an available through the dashboard is really an issue. 
I see from the logs it should be fixed right? Any reasons why a new version is not being pushed out?
Thank you so much for all the great job btw!

**Comment by flovilmart** [comment]
@natanrolnik?

**Comment by natanrolnik** [comment]
We should have a dashboard release today or tomorrow.

**Comment by Pikorua** [comment]
Ah! That's amazing! Thanks a lot @natanrolnik 👍

**Comment by natanrolnik** [comment]
@Pikorua we just released parse-dashboard v. 1.1.0!

**Comment by Pikorua** [comment]
@natanrolnik Amazing! You guys rocks!!!
Thanks :D
