### ISSUE TITLE
Parse cloud error 141 to recover data via parse cloud. [I'm using Heroku.]

### ISSUE THREAD

**Issue by JoaoArmandoo** [parse-community/parse-server#3976]
I'm having a lot of trouble with parse, always getting error 141, I posted in detail everything I've tried, and in detail what's happening in my publication in stackOverflow, but I did not get much help. The comments made there. Did not solve my problem, so I come here to the experts, ask for help, in case this has already happened to one of you.
I already checked several posts about the unauthorized 141 error, but nothing was able to solve my problem. Thank you for your patience and attention.

My post: https://stackoverflow.com/questions/44814524/parse-cloud-error-141-to-recover-data-via-parse-cloud-im-using-heroku

**Comment by natanrolnik** [comment]
Closing as you marked the StackOverflow question as solved.
