### ISSUE TITLE
[PROPOSAL/DISCUSSION] MySQL / MariaDB support

### ISSUE THREAD

**Issue by dplewis** [parse-community/parse-server#3978]
I've started working on a MySQL adapter. I leveraged the Postgres adapter and change the queries to work with MySQL

https://travis-ci.org/dplewis/parse-server-mysql-test/jobs/248923932
https://github.com/dplewis/parse-server-mysql-test/tree/master/src/Adapters/Storage/MySQL

`Executed 1302 of 1323 specs INCOMPLETE (18 PENDING) (3 SKIPPED) in 8 mins 59 secs..`

What I discovered

FullTextSearch
- Index Required
- search and sort are implemented
- language, case sensitive, diacriticSensitive can be setup with indexes

JSON / JSON Array
- Remove from json array can only remove strings and only 1

I haven't looked deep into it but MySQL 8 is coming out soon it may have more json support.
Might also need test for multiple add, remove, insert, addUnique mix and match for both JSON and Array

TODO - Make a wrapper for node-mysql2 similar to pg-promise
- Connection Pools
- Transactions
- Batch Transactions
- Multiple Query Format with Type

Special Thanks

@benishak I used your dynamodb adapter for inspiration and setting up travis
@vitaly-t I borrowed your query pattern and formatting from pg-promise to make transition from PG to MySQL easier

**Comment by flovilmart** [comment]
That's awesome! We should have a way to distribute the parse-server specs so you can run it against any database adapters.

**Comment by dplewis** [comment]
That would be awesome seeing as the specs are always updating. When we talked about building a test suite is that distributing the parse-server specs or something else?

**Comment by dplewis** [comment]
Can you do something similar to how master branch deploys latest? Deploy the test specs to a branch that way I can add it as a submodule. Or is there a better way?

**Comment by vitaly-t** [comment]
> I borrowed your query pattern and formatting from pg-promise to make transition from PG to MySQL easier

My only concern is that query formatting like one in `pg-promise` is very powerful, and highly customizable. For that reason it comes with a huge test suit against the query-formatting engine.

It will be hard to to test it properly when it is part of such an already large library. Can be quite error-prone.

**Comment by dplewis** [comment]
The node-Mysql I'm using comes with a query formatter. I just borrowed a regex expression or 2

**Comment by montymxb** [comment]
MySQL support just came across my mind and I bumped into this. @dplewis I actually implemented a system based off parse-server at my work some time ago, but built it starting on MySQL instead. If this is still going, and you need some help figuring out the queries, I can lend a hand if needed.

**Comment by dplewis** [comment]
@montymxb I built it to support all the features up to parse 2.5.0. I'll run the test against the 3.0 release. I may need a hand then.

MariaDB Update: I post issues on the repo but no reply in 3 months. They may have fixed the issues in the 10.3 release.
