### ISSUE TITLE
[PROPOSAL] Get calculated distance when making GeoSpatial queries

### ISSUE THREAD

**Issue by jcguarinpenaranda** [parse-community/parse-server#3980]
Hello, 

I would like to propose support for calculated distance when making GeoSpatial queries. 

For now, we have to calculate the distance manually in each of our UI if we are going to show it, but it would be very useful to have that distance calculated automatically by the server maybe using a library like [geolib](https://www.npmjs.com/package/geolib)

**Comment by flovilmart** [comment]
What would it look like? Where do you see it fitting?
