### ISSUE TITLE
Exception in afterSave reports the error to user

### ISSUE THREAD

**Issue by rihadavid** [parse-community/parse-server#3995]
### Issue Description

If afterSave hook throws an exception, it is reported to the user that saving the object failed, although the object **is** saved.

### Steps to reproduce

```
Parse.Cloud.afterSave("MyObject", function (request) {

	throw "Exception";
       //client gets the error reported although the MyObject instance IS saved

});
```

#### Expected Results

From [docs](http://docs.parseplatform.org/cloudcode/guide/#aftersave-triggers): "The client will receive a successful response to the save request after the handler terminates, regardless of how it terminates."

#### Actual Outcome

The client receives an error response.

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.5.3
  - Operating System:     WINDOWS
  - Localhost or remote server? LOCAL

- **Database**
  - MongoDB: MLAB.COM

### Logs/Trace

```
info: beforeSave triggered for MyObject for user wFyTH5Gb0I:
Input: { .. some data .. }
Result: { .. some data .. }
error: Error generating response. 'Exception' error=Exception
error: Uncaught internal server error. Exception
Exception
```

Could someone please test that the issue is not just in my environment? Thanks!

**Comment by flovilmart** [comment]
Nope doesn't seem to be your environment, this should definitely not interfere with the response status. We'll have a look!

**Comment by montymxb** [comment]
@rihadavid I'll take a look at this, I was just around that section of code when I was looking into the `beforeSave` hook issue. I can probably figure out what's going on here when I have some time.

**Comment by montymxb** [comment]
Just wanted to note I can confirm this is in fact a verifiable issue, working on a fix at the moment.

**Comment by montymxb** [comment]
@rihadavid #4293 is now in for this issue. Changes will be present in the next release, thanks again for bringing this to our attention!
