### ISSUE TITLE
signUp via Parse.Cloud can't bypass correct installationId to _Session

### ISSUE THREAD

**Issue by pewh** [parse-community/parse-server#3996]
### Issue Description

`installlationId` cannot be passed to session when signUp via cloud code. But it's working well on `Parse.User.logIn`.

### Steps to reproduce

```
    const newUser = await Parse.User.signUp(username, password, {
      name,
      phoneNumber: username,
      balance: 0,
    }, {
      installationId: installation.installationId,
      useMasterKey: true,
    })
```
#### Expected Results

Passing correct installationId to _Session

#### Actual Outcome

installationId is different. Not matched with `installation.installationId`

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) :2.5.0
  - Operating System:     Linux Debian
  - Hardware:             Asus X455L
  - Localhost or remote server? Localhost & VPS Linode

- **Database**
  - Storage engine:  Postgresql
  - Localhost or remote server? Localhost & VPS Linode

### Logs/Trace

```
info: Ran cloud function registerThenLoginMember for user undefined with:
  Input: {  
   "token":"XXX",
   "name":"Gg",
   "gender":"male",
   "installation":{  
      "installationId":"fd150a57-ed21-2752-be4b-b34930c153e4",
      "deviceBrand":"Xiaomi",
      "deviceModel":"HM NOTE 1W",
      "systemName":"Android",
      "systemVersion":"4.4.2",
      "deviceLocale":"en-US",
      "deviceCountry":"US",
      "isEmulator":false,
      "isTablet":false,
      "appVersion":"0.0.4.4",
      "timeZone":"Asia/Jakarta",
      "deviceToken":"fK42xhwSIGU:APA91bGCSEFkSdK5nWMX97MQ61Yh1zjrC0h4XvzgdCWIALYcN5XqudWZGOanKTLK_2Gd2a_ou_-pjl72rnjTd1hwkggGM4C_M4v67XwjAxAdZphRnjQCNx2QKP_RQ-BRFuehIbvhmKfL",
      "deviceType":"android"
   }
}
  Result: {"currentUser":{"name":"Gg","phoneNumber":"YYY","balance":0,"username":"YYY","createdAt":"2017-07-03T04:50:15.701Z","updatedAt":"2017-07-03T04:50:15.701Z","objectId":"bArtfV7eLH"},"currentRole":"Admin","sessionToken":"Qwd2BgpXFSsEUFt/VlxYFnoKBVsuVQxQFXwGU19/BglRQw=="} functionName=registerThenLoginMember, token=XXX, name=Gg, gender=male, installationId=fd150a57-ed21-2752-be4b-b34930c153e4, deviceBrand=Xiaomi, deviceModel=HM NOTE 1W, systemName=Android, systemVersion=4.4.2, deviceLocale=en-US, deviceCountry=US, isEmulator=false, isTablet=false, appVersion=0.0.4.4, timeZone=Asia/Jakarta, deviceToken=fK42xhwSIGU:APA91bGCSEFkSdK5nWMX97MQ61Yh1zjrC0h4XvzgdCWIALYcN5XqudWZGOanKTLK_2Gd2a_ou_-pjl72rnjTd1hwkggGM4C_M4v67XwjAxAdZphRnjQCNx2QKP_RQ-BRFuehIbvhmKfL, deviceType=android, user=undefined

```

**Comment by smassin** [comment]
This issue is not with the parse-server itself. Its with the JS SDK.
Parse.signUp actually does a ParseObject.save() at its core which does not send an installationId.
There are a couple options:

1) You can insert the following code just before this line https://github.com/parse-community/Parse-SDK-JS/blob/ee33c48e4a19f9264fd4301cb1dd3250dc7550a7/src/ParseObject.js#L1085

```
if (options.hasOwnProperty('installationId')) {
  saveOptions.installationId = options.installationId;
}
```

2) You can signUp and then immediately do a Parse.logIn right after with the installationId
