### ISSUE TITLE
Push notifications keep sending

### ISSUE THREAD

**Issue by rferbesa** [parse-community/parse-server#4008]
**Issue Description**

I've developed an app that sends push notifications using Cloud code. These notifications are received correctly in the devices but hours later they are automatically sent from Parse Server again (and they are received again). This happens 3 or 4 times for each push notifications.

If push notifications are sent from Parse Dashboard they are only sent one time, so it seems it's a problem of my cloud code.

**Steps to reproduce**

I'm not sure what are the steps, but this is my code:

Parse Server configuration > myparseuser/cloud/main.js

```
var api_key = 'key-myMailgunkey';
var domain = 'mg.mydomain.com';
var mailgun = require('mailgun-js')({apiKey: api_key, domain: domain});
Parse.Cloud.define("functiontosendemail", function(request, response) {
                   var name = request.params.username;
                   var email = request.params.email;
                   var body = request.params.body;
            var data = {
              from: email,
              to: 'info@mydomain.com',
              subject: "Contact Form",
              text: body
               };
        mailgun.messages().send(data, function (error, body) {
              console.log(body);
        });
});
Parse.Cloud.define("sendPushNotification", function(request, response) {
        var userId = request.params.userId;
        var message = request.params.message;
        var queryUser = new Parse.Query(Parse.User);
        queryUser.equalTo('objectId', userId);
        var query = new Parse.Query(Parse.Installation);
        query.matchesQuery('user', queryUser);

        Parse.Push.send({
          where: query,
          data: {
            alert: message,
            badge: 0,
            sound: 'default'
          }
        }, {
          success: function() {
            console.log('##### PUSH OK');
            response.success();
          },
          error: function(error) {
            console.log('##### PUSH ERROR');
            response.error('ERROR');
          },
          useMasterKey: true
        });
});

```
I had a similar issue with sending emails (see my cloud code above "functiontosendemail") and my problem was because I forgot to add response.success(); and response.error('ERROR'); methods, so I was sure to include these 2 methods in the responses of "sendPushNotification" method.

**Expected Results**

I expected that each push notification was sent only until they are received correctly. If there is a problem with a device I assume Parse will re-try automatically some time later, but once that notification is sent correctly it wouldn't be sent again.

**Actual Outcome**

Despite the notifications are received correctly in the devices they are re-sent later. I've checked that there are no bad devices between them, all of them are ok and all of them receive ok the notifications.

**Environment Setup**

    Server
        parse-server version 2.3.1
        Operating System: Ubuntu 16.041
        Hardware: 512MB RAM, 2GB Disk
        Localhost or remote server? Digital Ocean

    Database
        MongoDB version: 3.0.14
        Storage engine: Linux
        Hardware: 512MB RAM, 2GB Disk
        Localhost or remote server? Digital Ocean

**Logs/Trace**

I check the logs in Parse Dashboard and they show always this:

2017-07-09T15:38:02.427Z - Ran cloud function sendPushNotification for user undefined with:
  Input: {"message":"This is my message","userId":"myUserIdInParse"}
  Result: undefined

Maybe this Result:undefined has to do with the issue and "success: function()" and "error: function(error)" are never called?

**Comment by natanrolnik** [comment]
@rferbesa do you see `##### PUSH OK` or `##### PUSH ERRO` printed on the console?

**Comment by rferbesa** [comment]
Sincerely, I don't know where to find that logs. The server code is hosted in a Digital Ocean server and I don't usually access it. The few times I have to check for a log I loon into some fields in /var/log but I've tried this time to find the cloud code logs with no success. Where could I find the logs? Are they stored in some file in the server?

**Comment by natanrolnik** [comment]
Have you tried using `yourdomain.com/parse/scriptlog`?

If not, run it locally and you'll see the logs.

**Comment by rferbesa** [comment]
I can't find that file, but I've just seen that in my parse user I have a folder called "logs" that has inside hundreds of files called parse-server.err.<date> and parse-server.info.<date>.
Looking into them I see that parse-server.info have log about push notifications (parse-server.err doen't show anything related with notifications).

These logs are exactly the same as those showed in Parse Dashboard logs:

{"functionName":"sendPushNotification","params":{"message":"This is my message","userId":"myUserIdInParse"},"level":"info","messag
e":"Ran cloud function sendPushNotification for user undefined with:\n  Input: {\"message\":\"This is my message\",\"userId\"
:\"myUserIdInParse\"}\n  Result: undefined","timestamp":"2017-07-09T00:32:19.568Z"}

{"functionName":"sendPushNotification","params":{"message":"This is my message","userId":"myUserIdInParse"},"level":"info","messag
e":"Ran cloud function sendPushNotification for user undefined with:\n  Input: {\"message\":\"This is my message\",\"userId\"
:\"myUserIdInParse\"}\n  Result: undefined","timestamp":"2017-07-09T00:41:24.071Z"}

and so on...
There are no ##### PUSH OK or ##### PUSH ERROR logs

**Comment by natanrolnik** [comment]
Try running it locally, in your machine, and you'll be able to see if they are being called or not. If not, then probably you have the same problem as `functiontosendemail`...

**Comment by natanrolnik** [comment]
You can see that the logs show `Result: undefined`.

**Comment by rferbesa** [comment]
Yes, I commented in my question that I was afraid that this "Result:undefined" was the reason why success() and error() are not called. Is there any way to catch this result undefined so I can make some action?

**Comment by natanrolnik** [comment]
I don't think this is the right direction to solve your problem.
You should debug it locally. Do you know how to do it or do you need help running it in your machine?

**Comment by rferbesa** [comment]
The problem is that I'm an iOS and Android developer, I'm not too good with servers and I don't know how to debug this code. I would know to put more console.logs inside Cloud code but I'm not sure if this would be enough.

**Comment by natanrolnik** [comment]
I understand, but in the same way that we learned how to program for iOS and Android, we're able to learn other things as well - that is happening to me since parse-server became open source.

I would recommend you going a little bit through npm, and learning how to run the server in your machine. Take a look, for example, at #1402.

It is **always** better to develop locally, and only then deploy the server. It will save you many hours of fix-deploy-debug-fix iterations and save you from bugs.

I'm closing the issue for now; when you have more information, we'll reopen.
