### ISSUE TITLE
Integrating Socket.io and passing values to cloud code

### ISSUE THREAD

**Issue by bfjfm2** [parse-community/parse-server#4013]
I have successfully integrated socket.io at index.js and able to receive messages through the socket connection.

 How to pass the data from socket message to parse server cloud function
**cloud/main.js function messageFromSocket(message);**

index.js
```javascript
//Parse Server Initialization
var api = new ParseServer({
    databaseURI: databaseUri,
......
});

//SocketIO
var app = require('express')();
var server = require('http').createServer(app);
var io = require('socket.io')(server);
io.on('connection', function () { /* … */
});
server.listen(3000);
global._io = require('socket.io')(httpServer);
_io.on('connection', (socket) => {
    console.log('Client connected');

//Send Message to Emitter
    socket.on('message', function (data, fun) {
        console.log("Message Received");
       //Send this message to parse server cloud function  
        fun("success");
    });
}
```
cloud/main.js
```node
function receivedMessageFromSocket(message){
   //Then this will be saved to data base
}
```

**Comment by natanrolnik** [comment]
Use `Parse.Cloud.run("yourFunction")`.

See more [here](http://docs.parseplatform.org/js/guide/#use-cloud-code) and [here](http://parseplatform.org/Parse-SDK-JS/api/classes/Parse.Cloud.html#methods_run).

**Comment by bfjfm2** [comment]
@natanrolnik Thankyou

**Comment by bfjfm2** [comment]
@natanrolnik  Can you help me to call this function in reverse? Cloud function to Index.js function.
