### ISSUE TITLE
mLab upgrade of mongo version from 3.2 to 3.4 - August 18, 2017

### ISSUE THREAD

**Issue by kagayat** [parse-community/parse-server#4029]
We are running Parse server 2.2.10 against mLab instances with mongo 3.2, and they just announced an upcoming upgrade to mongo 3.4

Does Parse server 2.2.10 support mongoDB 3.4 or do we have to upgrade to a later version?

**Comment by flovilmart** [comment]
It would probably be a good idea to update to 2.5.3 the latest version.
