### ISSUE TITLE
internal server error deploying in azure

### ISSUE THREAD

**Issue by lucamorelli** [parse-community/parse-server#4037]
I'm trying to install a parse application in azure using https://aws.amazon.com/it/blogs/mobile/how-to-set-up-parse-server-on-aws-using-aws-elastic-beanstalk/.
I followed all the indications: used beanstalk to create the server and deploy it, create the db in mongoLab, copied the conn string  and added to the variables.
All seems to work, but when I try the test post according the document, I receive and internal server error message.
Where can I find more informations on how to solve this problem?

**Comment by natanrolnik** [comment]
What’s the error message? Please fill the issue template correctly and we’ll reopen.
