### ISSUE TITLE
Question about modeling data for LiveQuery

### ISSUE THREAD

**Issue by ranhsd** [parse-community/parse-server#4039]
Hi , I have a User model where i store for each users his friends. The friend is stored as **array** under the user object so it looks like the following: 

- FirstName
- LastName
- ....
- Friends (Array of users)

Now, In my app i use LiveQuery to update the user friends in realtime. So if a new friend was added then i notify the other user about this new friend in real time (via live query protocol of course).

Now, I cannot really register to event that will notify me each time a new user has been added to the friends list because live query does not allow me to model such query so what i did is to create a new **incremental** field of **friendsCount** and on the server i increase it each time a new friend is added. So my query (on iOS) looks like the following: 

```
    self.friendAddedQuery = [User query];
    [self.friendAddedQuery whereKey:@"objectId" equalTo:[User currentUser].objectId;
    [self.friendAddedQuery whereKey:@"friendsCount" greaterThan:@([User currentUser].friendsCount)];

```
The problem with this approach is that it will work as expected only for the first time and then it will be triggered each time i will update the user object so my workaround was to unsubscribe and subscribe again when i get the **PFLiveQueryEventTypeEntered** event so the server will know to subscribe again with the new friendsCount value and only when it will be updated again it will trigger the event listener. I don't like this approach because i don't like the fact that in my code i need to unsubscribe and subscribe again each time. 

I know that i can create a Friend object and attach it to the User object and solve it this way but i really care about the performance of the app and in MongoDB the best is to model it as an array. 

So i wanted to know if somebody faced the same issue before or maybe someone can provide some creative solution for this issue? 

Thanks!

**Comment by flovilmart** [comment]
I would have recommended that you implement this as a FriendshipTable with 2 user columns. Actually you'll outgrow very fast the max row size with the array, can't have pagination etc... So that's not the best way to store relational data that can grow.

**Comment by ranhsd** [comment]
Hi @flovilmart thanks for  your answer.. 
So you think that i need to create Relation (e.g. PFRelation) from User to some other object let's say Friends? 
or should i create a new Friend object of 

Friend: {
   user1ObjectId: String,
  user2ObjectId: String,
  ....
}

and then query with **or** (where  myObjectId = user1Object OR myObjectId = user2ObjectId) ?

In the first option (relation) parse will create a join table and in the second it will not... what do you think will be better approach? 

Thanks!
Ran.

**Comment by flovilmart** [comment]
The problem with relation is they are only one way, I would manage my own join table with two pointer columns

**Comment by ranhsd** [comment]
Yes but the problem with join table is that you need to query it with or and then you will always populate redundant object which is your user object because you use include and because you must include both pointers (cause you don't really know which one is your friend) then you have to populate the friend and your user object ... is there a way to avoid such situation?

**Comment by ranhsd** [comment]
Btw the only way to achieve it without or is to create 2 records for each friendship like the following:

UserObject, FriendObject
FriendObject, UserObject

I recheck my implentation again and I forgot I that I switch to use relations and what I did what to add relation for both users and the relation type is also a user object . Behind the scenes parse create a join table to manage that. The problem with this solution is that you cannot create live query event that will inform you when a new friend added so I guess the best solution is to create a join table with 2 records for each friendship (like I mentioned above) and then you can also enjoy live query capabilities ... unless you think there is a better solution...

**Comment by flovilmart** [comment]
It all depends upon your use case. Please use stackoverflow for implementation related questions.
