### ISSUE TITLE
username is required parseError code 200 during login

### ISSUE THREAD

**Issue by gate3** [parse-community/parse-server#4040]
Hi, long time and big time fan of parse server here. I have never come across this error before, but parse server is giving me a funnt error during login. I keep getting the error username is required when trying to login, i am using thesame code that works on another server and i am making use of the javascript sdk not the http request. Please i really need this, i will greatly appreciate any help. Below is the code and a snapshot of the error

`  login ({ email, password }) {
    this.isLoading = true
    const userObject = new this.parse.User()
    userObject.logIn(email, password).then(
      (s) => {
        console.log(s)
        Emitter.emitterObject.emit(Constants.eventListeners.auth.success, s)
      },
      (e) => {
        console.log(e)
        Emitter.emitterObject.emit(Constants.eventListeners.auth.error, e)
      }
    )
  }`

![image](https://user-images.githubusercontent.com/3597437/28500721-14f38e78-6fc5-11e7-8472-71018018aa22.png)

**Comment by pungme** [comment]
I don't think parse-server support the login with email yet. You either need to query for username (with the email) and then use that username to login. Or else, save username as an email (not recommend since it will make everyone's email public)

**Comment by bohemima** [comment]
Double-check that you actually have a value in `email`

**Comment by gate3** [comment]
I  went with @pungme's answer it works now. Thanks
