### ISSUE TITLE
Feature Request: Separate pointer permission for Add Field

### ISSUE THREAD

**Issue by jasonm1** [parse-community/parse-server#4045]
The CLP pointer permission groups together Create, Update, Delete, and Add Fields (at least in the Parse Dashboard). It would be useful to at least separate out Add Fields. I would prefer no clients to be able to add fields anywhere except with the Master Key, but I do need users to be able to read and write their own data. There seems to be no way to do this with Pointer Permissions.

**Comment by madsb** [comment]
Maybe I'm not understanding your issue correctly, but my dashboard looks like this (when expanding to Advanced permissions) - isn't this what you're looking for?
![parse_dashboard](https://user-images.githubusercontent.com/198395/28561009-fbc1180e-711c-11e7-839e-0a1a316478ac.png)

**Comment by jasonm1** [comment]
Sorry, I should have included a screenshot. Here, you can see the Pointer Permission CLP I am referring to.

<img width="948" alt="untitled2" src="https://user-images.githubusercontent.com/4007439/28587090-c86777d8-712a-11e7-9450-c4a030121bdf.png">

**Comment by madsb** [comment]
Ah, I see - I’ve never seen that!

**Comment by bouzoumita** [comment]
+∞ i really need that

**Comment by alexander-alzate** [comment]
+1

**Comment by shkatulo** [comment]
It would be really useful feature that can make permissions management much easier.

**Comment by flovilmart** [comment]
@shkatulo feel free to open a PR!
