### ISSUE TITLE
How to set password without session token?

### ISSUE THREAD

**Issue by lyw1991** [parse-community/parse-server#4046]
I have to reset password and how can I do it without session token?

**Comment by pungme** [comment]
Is this what you're looking for? http://docs.parseplatform.org/js/guide/#resetting-passwords

**Comment by natanrolnik** [comment]
I'm closing this issue because we try to keep GitHub issues for issues and bugs specific to Parse Server.

Please use [StackOverflow](https://stackoverflow.com) with the `parse-server` and `parse-js-sdk` tags, and post the link here for reference as well so people can help you with your question.
