### ISSUE TITLE
Parse server 2.5.3 - failure to log in

### ISSUE THREAD

**Issue by kagayat** [parse-community/parse-server#4049]
We use GitHub Issues for bugs.

### Issue Description

Upgraded Parse server from 2.2.16 to 2.5.3.

While attempting to log in, log in fails and with the following exception seen in the logs:

With sessionToken:

[31merror[39m: error getting auth for sessionToken TypeError: Cannot convert undefined or null to object
    at convertParseSchemaToMongoSchema (/var/app/current/node_modules/parse-server/lib/Adapters/Storage/Mongo/MongoStorageAdapter.js:64:16)
    at MongoStorageAdapter.find (/var/app/current/node_modules/parse-server/lib/Adapters/Storage/Mongo/MongoStorageAdapter.js:447:16)
    at /var/app/current/node_modules/parse-server/lib/Controllers/DatabaseController.js:1007:36
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
(node:3098) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): ParseError: undefined TypeError: Cannot convert undefined or null to object

Without sessionToken (clean login):

TypeError: Cannot convert undefined or null to object
    at convertParseSchemaToMongoSchema (/var/app/current/node_modules/parse-server/lib/Adapters/Storage/Mongo/MongoStorageAdapter.js:64:16)
    at MongoStorageAdapter.find (/var/app/current/node_modules/parse-server/lib/Adapters/Storage/Mongo/MongoStorageAdapter.js:447:16)
    at /var/app/current/node_modules/parse-server/lib/Controllers/DatabaseController.js:1007:36
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)

### Steps to reproduce

See above

#### Expected Results

Login to Parse server

#### Actual Outcome

Login fails

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.5.3
  - Operating System:     64bit Amazon Linux 2017.03 v4.2.0 running Node.js 6.11.1
  - Hardware:             N/A
  - Localhost or remote server? AWS

- **Database**
  - MongoDB version: 3.2.14
  - Storage engine:  N/A
  - Hardware:        N/A
  - Localhost or remote server? mLab

### Logs/Trace

See above

**Comment by flovilmart** [comment]
can you provide the logs when running with VERBOSE=1 please?

**Comment by kagayat** [comment]
Not anymore. We have abandoned our attempts to upgrade Parse server version.

**Comment by flovilmart** [comment]
What do you mean by that? Upgrading is straightforward.

**Comment by kagayat** [comment]
Not based on our experience. :) We don't have enough resources to resolve issues like the one above, so we decided to run older version for now and concentrate on other priorities.

**Comment by flovilmart** [comment]
Upgrading Parse-server is just a matter of updating the version in package.json .
