### ISSUE TITLE
Temporarily setting data on server removes all data from object when received on client.

### ISSUE THREAD

**Issue by tejpratap46** [parse-community/parse-server#4051]
I am setting some calculated temp data in object (not called `save()` just `set('data', value)`) from a cloud function, everything is OK on server, i can read data is set to object, but when i read received data in client (js), object is empty (only contains id, created and updated at), not only my temp data is missing but my actual DB data is also missing.

When i tried to send `object.toJSON()` from server and on client read with `new Parse.Object(objectJSON)` it works fine.

All i want to know why this is happening. Im i doing something wrong?

**Comment by tejpratap46** [comment]
After waiting for two days, i believe no one knows what is happening and why object is modified once received by client. So, i'm going to ask a questing instead.

**Is there any other way i can send temporary data from server(cloud function) to client?**
_* Answer should be what works on android, web and iOS(*optional)._

**Comment by flovilmart** [comment]
without any code example, that pretty tough to answer your question, also what you're describing is not an issue with parse-server but a question about implementation details. Please use stackoverflow for that, as stated in the issue template that you stripped out without reading I guess.

**Comment by tejpratap46** [comment]
@flovilmart Sorry, my bad i did not followed instructions but is saw some requests like this [here](https://github.com/parse-community/parse-server/issues/3913).

Here is same question is posted on [Stackoverflow](https://stackoverflow.com/questions/45393804/parse-server-temporarily-setting-data-on-server-removes-all-data-from-object-wh).

Check what happens after we call `response.success(parseObject)` and when js client receives object, my guess is it has something to do with `response.success(parseObject)` method in cloud code. 
please help me solve this.

**Comment by flovilmart** [comment]
Please fill the issue template completely with code etc... without it,

**Comment by tejpratap46** [comment]
### Issue Description

Cannot set additional data to response parse object sent from cloud code. 

### Steps to reproduce

Just run following code with any class in your DB

```javascript
Parse.Cloud.define('hello', function (request, response) {
	console.log('hello called');

	var AnyClass= Parse.Object.extend('AnyClass');
	var query = new Parse.Query(AnyClass);

	query.first({ useMasterKey: true }).then(function (fetchedObject) {
		fetchedObject.set('data', 'test'); // Some extra data i want in response object.
		response.success(fetchedObject);
	}, function (error) {
		response.error(error);
	});
});
```

#### Expected Results

A Parse object with `data` field attached in response object.
Here is sample:
```javascript
{
    "result": {
        "propertyOne": "data 1", // some property from db
        "propertyTwo": "data 2", // some property from db
        "propertyThree": "data 3", // some property from db
        "data": "test", // This extra field should be attached to response
        "createdAt": "2017-03-13T16:07:31.602Z",
        "updatedAt": "2017-03-13T16:07:31.602Z",
        "ACL": {
            "*": {
                "read": true
            }
        },
        "objectId": "QD7wy2s1hj",
        "__type": "Object",
        "className": "AnyClass"
    }
}

```
#### Actual Outcome

```javascript
{
    "result": {
        "__type": "Pointer",
        "className": "Video",
        "objectId": "QD7wy2s1hj"
    }
}
```

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.5.3
  - Operating System:     ubuntu 15.04
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): localhost

- **Database**
  - MongoDB version: 3.2.14
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): mLab


* Can you tell why this is happening?
* What other methods are there to attach some extra data with response parse object?

**Comment by SebC99** [comment]
Old question, but in case it helps:
Parse Cloud Function cannot return unsaved dirty objects. When the response is built in JSON, it checks if the object is dirty, and in that case, only return the object pointer instead of the object data.
I guess it's by design, to avoid having "server-data" which are not really server-data in the client side.
@flovilmart am I right?

**Comment by tejpratap46** [comment]
@SebC99 But is there a need to do this?

To solve this issue i have to convert ParseResponse to JSON and again re-construct ParseObjects from JSON when received by client (on every client that my app currently supports).

**Comment by SebC99** [comment]
@tejpratap46 not sure, but as I said, I guess it's to avoid "fake" data on client side that could mess up future save/fetch
In you case, you can reconstruct the parseObjects server side too before sending them (convert from parseObjects to JSON, modify them, convert back)
