### ISSUE TITLE
How to connect to PostgreSQL cluster?

### ISSUE THREAD

**Issue by youngerong** [parse-community/parse-server#4054]
Deploy two PostgreSQL in two machine for high available, how to make Parse connect to the cluster? For example, 'mongodb://' + "10.43.159.58:9927,10.43.159.58:9928" + '/test?replicaSet=volunteer_test&readPreference=primaryPreferred, but PostgreSQL support this style?

**Comment by flovilmart** [comment]
You should have a look at the cluster documentations:

https://www.postgresql.org/docs/8.3/static/creating-cluster.html
https://wiki.postgresql.org/wiki/Replication,_Clustering,_and_Connection_Pooling

and probably [pg-promise](https://github.com/vitaly-t/pg-promise) that we use under the hood, we [pass](https://github.com/parse-community/parse-server/blob/master/src/Adapters/Storage/Postgres/PostgresClient.js#L4) the URL as is to the pg-promise library.

**Comment by vitaly-t** [comment]
It doesn't exist in the driver, see https://github.com/brianc/node-postgres/issues/932

From the `pg-promise` point of view, one would be creating 2 separate `Database` objects, with connection details for each cluster.

**Comment by flovilmart** [comment]
Thanks @vitaly-t !

**Comment by shreeramk** [comment]
@vitaly-t how do we connect to a postgres cluster using pg-promise? Could you please explain.

**Comment by shreeramk** [comment]
@vitaly-t does pg-promise supports multiple host connection since for replica, it would be required  or is there any other alternative ?

**Comment by vitaly-t** [comment]
@shreeramk pg-promise is neutral to this, it is the driver underneath that's expected to support it, as per [this issue](https://github.com/brianc/node-postgres/issues/1470).

**Comment by shreeramk** [comment]
@vitaly-t okay. Is there any other way? Like writing a wrapper?

Consider if a wrapper is written on top of [node-postgres](https://github.com/brianc/node-postgres), to handle separate connections to primary and multiple secondary's. Then, if I have total 5 nodes(1 - primary, 4 - secondary) that means using node-postgres i hv to create 5 separate connections. Would you recommend that?

Also, if any automatic failover libraries are used at postgres level, then obviously there are chances that if primary goes down then one of the secondary will promoted to primary so how do we handle that scenario in nodejs code.

**Comment by vitaly-t** [comment]
@shreeramk There is little I can suggest about it presently. And in any case, you will do better asking about it in that issue, and not here.
