### ISSUE TITLE
Parser server, loggin in and "setting the user"

### ISSUE THREAD

**Issue by farhansyed9** [parse-community/parse-server#4057]
I understand a lot of things like setting the user is now gone from parse server. 

My question is, once I log in a user, how would I keep them signed in through all the web pages they visit?

**Comment by montymxb** [comment]
@flessard depends on which sdk, each has it's own method of persisting across pages for a given session. I'm assuming you're using either the JS or PHP sdk?

**Comment by farhansyed9** [comment]
@montymxb Yes I'm in a Node.js environment.

**Comment by montymxb** [comment]
Both persist using cookies. The php one in particular will only do this if a session is setup in advance to initializing the sdk. 

Assuming a cookie is set, and readable, the session will persist for as long as the cookie is present and as long as the session token in the cookie is valid.

**Comment by farhansyed9** [comment]
@montymxb I understand. Is there a guide on how I should go about this for node.js?

**Comment by montymxb** [comment]
It's mentioned on the [ js sdk repo](https://github.com/parse-community/Parse-SDK-JS) that running server-side is a bit different. I haven't looked into it myself but it does mention local storage, which is perhaps how they're setting it up there now (like the client side js sdk).

If you're using their npm module you should be good to go. Given that are sessions not persisting across pages for you?

**Comment by farhansyed9** [comment]
@montymxb So what your saying is, if I am using the JS SDK, I simply do the Parse.Login...etc and I'm good to go? It handles it for me?

**Comment by flovilmart** [comment]
> I understand a lot of things like setting the user is now gone from parse server.

User is not gone! The only thing that is gone is Parse.User.current() which would return non-sense in cloud triggers and functions, yet you can access req.user for getting the authenticated user. We could theoretically restore the Parse.User.current() but we'd need to guarantee process isolation for each triggers and add a layer of complexity as well as a performance hit.

**Comment by farhansyed9** [comment]
@flovilmart Thanks for clarifying. 

What your saying is say server side or in a cloud function, I can access the logged in user with req.user? Assuming I log them in via the Parse.User.login function.

**Comment by flovilmart** [comment]
yes, for more info: http://docs.parseplatform.org/parse-server/guide/#cloud-code

**Comment by flovilmart** [comment]
only in cloud code.

**Comment by farhansyed9** [comment]
@flovilmart I ran cloud code containing this: 

```
Parse.Cloud.define('login', function(req, res){

	Parse.User.logIn("farhan", "test", {
  success: function(user) {
    // Do stuff after successful login.
    res.success('logged in');
  },
  error: function(user, error) {
    // The login failed. Check error to see why.
    res.error('failed to login')
  }
});

});
```

I was a successful login. 

Then on another page i ran this cloud code function: 

```
Parse.Cloud.define('user_logger', function(req, res) {
  res.success(req.user);
});
```

Which came back with this: 

```
info: Ran cloud function user_logger for user undefined with:
  Input: {}
  Result: undefined functionName=user_logger, , user=undefined
```

**Comment by flovilmart** [comment]
yeah because you basically logged a user on your server without telling your client that you logged it in... you need to forward the user's session token to the client and then on the client call `Parse.User.become....` OR (preferred) call Parse.User.logIn on the client...

**Comment by flovilmart** [comment]
this turns more into a stackoverflow worth discussion, I encourage you to ask your questions over there and use the issues on this repository to report bugs or security issues. Thanks.

**Comment by farhansyed9** [comment]
Yeah sorry about the long thread. Is there a guide on client side login?

**Comment by farhansyed9** [comment]
@flovilmart Yeah sorry about the long discussion. When you say client side, do you mean running Parse.user.login/parse.user.become within a <script> tag in html?
