### ISSUE TITLE
[Question] is it safe to use redis without backup in parse server? (cache; livequery)

### ISSUE THREAD

**Issue by mfkenson** [parse-community/parse-server#4059]
AFAIK redis is used for cache, and pub/sub in in livequery. We are planning to deploy stuff in AWS/GCP for production use. I am working on redis deployment/configuration.

1. If the redis is dead (fail to connect), does parse server fallback to memory cache?
2. If the redis is dead (data-loss), is there any impact on user data (data to be saved in mongodb)

**Comment by flovilmart** [comment]
1. There’s no fallback to in memory cache, the cache should just miss and you’ll see more reads on the DB
2. It should not.

also, you should probably deploy in production without redis first but with singleSchemaCache enabled and other flags that may help reduce the number of reads in the DB. Using a shared cache has implications and you may actually not need those optimisations
