### ISSUE TITLE
Cannot Disable Email Verification 

### ISSUE THREAD

**Issue by davidju** [parse-community/parse-server#4062]
I followed the steps outlined in https://github.com/parse-community/parse-server to enable password reset, and Parse Server initialization looks as follows:

var api = new ParseServer({
    databaseURI: databaseUri || 'mongodb://mongoDatabse',
    cloud: process.env.CLOUD_CODE_MAIN || __dirname + '/cloud/main.js',
    appId: process.env.APP_ID || 'myAppId',
    masterKey: process.env.MASTER_KEY || 'myMasterKey', //Add your master key here. Keep it secret!
    serverURL: process.env.SERVER_URL || 'myServerUrl',  // Don't forget to change to https if needed
    liveQuery: {
        classNames: ["Posts", "Comments"] // List of classes to support for query subscriptions
    },
    verifyUserEmails: false,
    emailVerifyTokenValidityDuration: 2 * 60 * 60, // in seconds (2 hours = 7200 seconds)
    preventLoginWithUnverifiedEmail: false,
    publicServerURL: 'myServerUrl',
    appName: 'myAppName',
    emailAdapter: {
        module: 'parse-server-simple-mailgun-adapter',
        options: {
            fromAddress: 'fromEmail',
            domain: 'domain.com',
            apiKey: 'myMailgunKey'
        }
    }
});

I only want the password reset via email function, and not the email verification function, so I have set verifyUserEmails to false, but every time a user signs up, the email verification email is still being set out. Please advise if there is a mistake in my Parse Server configuration that is causing this to happen.

- **Server**
  - parse-server version: 2.2.25
  - Operating System:   Windows 10 64 bit
  - Localhost or remote server? Heroku
- **Database**
  - MongoDB version: 3.0.12
  - Localhost or remote server? mLab

**Comment by flovilmart** [comment]
@davidju I've opened a PR with a new test that is very similar to your parse-serve initialization, and the verification email doesn't seem to be sent when saving the user upon signup.
