### ISSUE TITLE
REST API POST - Invalid Field Name: __type

### ISSUE THREAD

**Issue by thomascoope** [parse-community/parse-server#4066]
### Issue Description

I am trying to send a REST HTTPS Post request to my server including a Pointer.  Note that I have no issue sending strings.  I am sending JSON as per [http://docs.parseplatform.org/rest/guide/#data-types](http://docs.parseplatform.org/rest/guide/#data-types).  I am getting an error returned.

### Steps to reproduce

I'm sending my REST API posts using Postman:

> curl -X POST \
>   https://my-api.herokuapp.com/classes/MyClass/ \
>   -H 'cache-control: no-cache' \
>   -H 'content-type: application/json' \
>   -H 'x-parse-application-id: my_api' \
>   -d '{
> 	"ReceiptBoolean":true,
> 	"__type":"Pointer",
> 	"className":"MyPointer",
> 	"objectId":"1aF78myTChr"
> }'

Note that I already have MyClass & a pointer named MyPointer set up.

#### Expected Results

`{
    "objectId": "ge0c19sTCe",
    "createdAt": "2017-07-30T23:38:31.832Z"
}`

What you expected to happen.

#### Actual Outcome

`
{
    "code": 105,
    "error": "objectId is an invalid field name."
}
`

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : Built 6 hours ago using Parse-Server-Example Repo Clone.
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Heroku

- **Database**
  - MongoDB version: 3.2  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): mlab

### Logs/Trace

> Jul 30 16:54:19 my-api app/web.1: error: Error handling request: ParseError { code: 105, message: 'objectId is an invalid field name.' } code=105, message=objectId is an invalid field name. 
> Jul 30 16:54:19 my-api heroku/router: at=info method=POST path="/classes/MyClass/" host=my-api.herokuapp.com request_id=4fc35be4-cf05-4541-a719-18fedc4b258d fwd="[IP removed]" dyno=web.1 connect=0ms service=2ms status=400 bytes=548 protocol=https 
> Jul 30 16:54:19 my-api app/web.1: error: objectId is an invalid field name. code=105, message=objectId is an invalid field name.

**Comment by flovilmart** [comment]
You have to specify the column on which you wanna save the pointer in MyClass. Ex:

```
“ReceiptBoolean”:true,
“Key”:{“__type”:”Pointer”,...}
```

**Comment by thomascoope** [comment]
Thanks.  Do you think that the user documentation should be elaborated upon to better explain this?  I'm not a particularly competent developer, partly why I'm using Parse rather than building my own API.
