### ISSUE TITLE
Intermittent Timeouts

### ISSUE THREAD

**Issue by woodardj** [parse-community/parse-server#4068]
Every few minutes, we're seeing at least one request to a parse-server-controlled endpoint stall for an indeterminate amount of time. We've set the express timeout to 25 seconds to give up on these requests, but they're still quite a nuisance.

Here's our 24h response times graph from Heroku Metrics:
<img width="1196" alt="screen shot 2017-07-31 at 12 02 46 pm" src="https://user-images.githubusercontent.com/557897/28791020-46e2c394-75e8-11e7-8a73-9cbe1c98f8b7.png">
Note 50, 95 and 99 %-iles are reporting in the sub-second (or just over) range, while many time slices include one "max" request time that's been killed by our 25s Express timeout.

I've added some logging to the Express timeout callback to dump a little request data (including a request ID) to the console to help track it down. It's almost always at a `/parse/classes/…` POST request, or a cloud code request. For one of the cloud code functions timing out, I littered the function with console logging that included the request ID so I could track back from the log timeout.

Every log message is executed, all the way up to the `request.success()` call at the end of the cloud functions before the request eventually fails 

- **Server**
  - parse-server version : 1.0.27
  - Operating System:     Heroku
  - Hardware:             2X Dynos

- **Database**
  - MongoDB version: 3.2.11 (WiredTiger)
  - Localhost or remote server? mlab

### Logs/Trace

Here's the logging I get from the cloud function, plus the entire cloud function, with some business logic snipped. Note that the output completes all the way up to calling response.success(). This cloud code function is also called successfully hundreds of times per hour, usually with response times in the ms.

Log:
```
» 24 Jul 2017 08:18:45.097 382 heroku router - - at=error code=H13 desc="Connection closed without response" method=POST path="/parse/functions/<cloud code function name>" host=<host> request_id=78aca019-76f7-449b-8af9-fe5f38690261 fwd="99.203.1.160" dyno=web.1 connect=1ms service=25007ms status=503 bytes=0 protocol=https High Response TimeCritical
» 24 Jul 2017 08:18:45.264 981 app web.1 - - {"host":"<host>","connection":"close","x-parse-client-version":"i1.14.4","accept":"*/*","x-parse-session-token":"<session token>","x-parse-application-id":"<app id>","x-parse-client-key":"<client key>","x-parse-installation-id":"<uuid>","x-parse-os-version":"10.3.2 (14F89)","accept-language":"en-us","accept-encoding":"gzip, deflate","content-type":"application/json; charset=utf-8","user-agent":"<our iOS app user agent>","x-parse-app-build-version":"4","x-parse-app-display-version":"4.0.5","x-request-id":"78aca019-76f7-449b-8af9-fe5f38690261","x-forwarded-for":"99.203.1.160","x-forwarded-proto":"https","x-forwarded-port":"443","via":"1.1 vegur","connect-time":"1","x-request-start":"1500905899957","total-route-time":"0","content-length":"40"}
» 24 Jul 2017 08:18:48.813 190 app web.1 - - 78aca019-76f7-449b-8af9-fe5f38690261 Cloud code: Fielding a '<cloud code function name>' call...
» 24 Jul 2017 08:18:48.813 170 app web.1 - - 78aca019-76f7-449b-8af9-fe5f38690261{"athId":"CorMSKLrNV","countsOnly":true}
» 24 Jul 2017 08:18:48.813 160 app web.1 - - 78aca019-76f7-449b-8af9-fe5f38690261{"limit":25,"mark_seen":false}
» 24 Jul 2017 08:18:54.820 157 app web.1 - - 78aca019-76f7-449b-8af9-fe5f38690261 Data came back from Stream
» 24 Jul 2017 08:18:54.895 148 app web.1 - - 78aca019-76f7-449b-8af9-fe5f38690261 Counts only: true
» 24 Jul 2017 08:18:54.895 145 app web.1 - - 78aca019-76f7-449b-8af9-fe5f38690261 wrapping up...
» 24 Jul 2017 08:18:54.895 173 app web.1 - - 78aca019-76f7-449b-8af9-fe5f38690261 {"unread":0,"unseen":0,"isEndOfFeed":true} 
```
(notable: if I'm reading these timestamps correctly, it appears that it takes parse-server almost 3s from request to invocation of cloud function, our third party service takes about 6s, then we run for ~1s more and then…?)

Cloud code:
```
Parse.Cloud.define("<cloud code function name>", function (request, response) {
    var req_id = request.headers['x-request-id'];
    console.log(req_id + " Cloud code: Fielding a '<cloud code function name>' call...");

    // ...snip...
    console.log(req_id + JSON.stringify(request.params));
    return Parse.Promise.as()

        .then(function () {
            // ...snip...
        })

        .then(function () {

            var params = {
                limit: 25,
                id_lt: pagingId
            };

            console.log(req_id + JSON.stringify(params));
            return [data from a call to a third party called Stream];
        })

        // response
        .then(function (t) {
            console.log(req_id + " Data came back from Stream");
            var data = {};
            console.log(req_id + " Counts only: " + countsOnly);

            // ...snip...

            console.log(req_id + " wrapping up...");
            console.log(req_id + " " + JSON.stringify(data));
            response.success(data);
        })

        .fail(function (error) {
            console.error('ERROR: getAthleteFeed ' + JSON.stringify(error));
            response.error(error.message || 'There was an error getting the feed.');
        });
});
```
Anyone else seeing these type of randomly timing-out requests with cloud code or parse queries?

**Comment by steven-supersolid** [comment]
I see H13 errors when a dyno shuts down due to autoscaling but as your log is for web.1 I don't think that is the case here.

Are you performing database operations in your cloud code? If you are then parse-server will make a HTTP request to itself (or server in serverURL). If you are not using clustering then this could saturate the dyno. Even if you are using clustering and serverURL is localhost then this could also saturate each worker on the dyno. You would experience this as a hang when performing a query or update from inside cloud code. This doesn't seem to match your log so could be something else.

The timestamps may indicate a problem, it seems the connection is closed at 08:18:45.097 after 25s unless Heroku is backdating the log to the time the connection was initiated? Then the cloud code debug displays long after this - is the request being queued, then closed without de-queuing to still be processed later?

You also have a timestamp in the request of 1500905899957 so would convert to the same timezone as may give some insight.

May be worth sharing your server setup - e.g. express mounted or CLI. Could try running with VERBOSE to see if there are any more clues when one of these slow requests occurs although it will inflate your logs.

**Comment by woodardj** [comment]
Thanks for jumping in @steven-supersolid — we've enabled `PARSE_SERVER_ENABLE_EXPERIMENTAL_DIRECT_ACCESS` so we no longer make HTTP requests to ourselves during Parse queries. We have clustering set to '1', since we seem to occasionally run at about 51% memory use per dyno, so we can't fit two threads into one, though we do run an average of 6 dynos.

We don't use Heroku's autoscaling (though we do use HireFire), and would make sense if these correlated with the restart activity (they don't, and they happen _far_ more frequently than we scale dynos). We've had timeouts of this nature five times in the last two hours, and we've scaled dynos once (and that was **up**, so no dynos were killed).

I _thought_ the router's log entry was backdated to when the request came in, however, checking out your timestamp theory…

1500905899957  == July 24, 2017 8:18:19.957 in our local TZ. 

So it does appear that all the cloud code may be executing *after* the request has already timed out.

We mount Parse (as an express middleware) almost exactly as in the example setup, if that's what you're asking:

```
    var api = new ParseServer({...});

    var mountPath = process.env.PARSE_MOUNT || "/parse";
    app.use(mountPath, api);
```

I'd like to avoid enabling VERBOSE, on account of our traffic levels, though I can try it later this week (Tuesdays are our second-busiest day) if you can't think of any other avenues to try and track this down.

**Comment by steven-supersolid** [comment]
I'm petty much out of ideas on this one. What is strange is that when your express middleware closes the connection the code continues.

I've not looked too deeply in to this but could it be an issue with the parse-server, express, node or Heroku not terminating the request properly? This may be possible to test by making a cloud code endpoint with similar logging that simply blocks for longer than the timeout period.

None of this explains why you see those timeouts in the first place although if there are long running requests that are not cleaned up then they may be blocking subsequent requests.

Just wondering - when you say you are using a clustering size of 1 does that mean you have your own cluster wrapper and set to 1 or you just don't use clustering? AFAIK parse-server only clusters when run as a CLI app, not express mounted. If you have your own cluster wrapper then would try without.

**Comment by woodardj** [comment]
I'm using Throng like so:

```
var throng = require('throng');
var WORKERS = process.env.WEB_CONCURRENCY || 1;

function serverthread() {
   //...
   var api = new ParseServer({...});
   var mountPath = process.env.PARSE_MOUNT || "/parse";
   app.use(mountPath, api);

   //... additional middlewares/express app routes for site/our own external api, etc.

    var port = process.env.PORT || 1337; 
    var httpServer = require('http').createServer(app);

    httpServer.setTimeout(25 * 1000, function(sock) {
        var r = sock.parser.incoming; 
        console.log("*=== Express timed out, logging data from socket:");
        console.log(JSON.stringify(r.headers));
        console.log("---");
        console.log(JSON.stringify(r.body));
        console.log("*=== End socket data.");
        sock.destroy();
        return;
    });

    httpServer.listen(port, function () {
        console.log('running on port ' + port + '.');
    });
}

throng({
    workers:  WORKERS,
    lifetime: Infinity,
    start:    serverthread
});
```

We currently run with WEB_CONCURRENCY set to '1', with plans to increase that to '2' at some point in the near future.

Is that not an appropriate way to mount parse-server into a clustered express app?

**Comment by steven-supersolid** [comment]
That's how I do it too minus the timeout code. It might be worth looking at what happens when the socket is destroyed - i.e. is throng responding to the event correctly?

parse-server uses code similar to throng but there was an issue reported and fixed with events not being handled correctly. I just noticed there's a comment about not shutting down correctly in the source code: https://github.com/parse-community/parse-server/blob/master/src/cli/parse-server.js

There may be some clues in the code and linked discussions. You could try temporarily not using throng to see if it has any impact or at least rule that out.

**Comment by woodardj** [comment]
Commented out throng, though I discovered that Heroku was setting WEB_CONCURRENCY (to 2), even though we weren't, so that was enlightening.

After removing it completely (and re-enabling, but explicitly setting to 1), I'm pretty sure I can rule that out. There seemed to be fewer timeouts, but they were frequently worse; I believe this was a result of there being fewer threads fielding requests.

Your inquiry around the timestamps makes me think I should be pursuing this down that avenue. I'll mark this closed and re-open if I circle back around to this. Thanks @steven-supersolid!

**Comment by woodardj** [comment]
Okay, new info on this, (and might perhaps provide some insight for #3975 ? ) Or might also belong on the iOS SDK repo.

These are being caused by a `Content-Length` mismatch with body length on some POSTs. Frequently with a body of `{}`.

I found this discussion over on body-parser: https://github.com/expressjs/body-parser/issues/207 that might be relevant as well.
