### ISSUE TITLE
Allow for Views collection (MongoDB 3.4)

### ISSUE THREAD

**Issue by SebC99** [parse-community/parse-server#4070]
Since version 3.4 MongoDB allows read-only views creation, based on aggregation pipelines.
It allows more control over returned fields, and more complex queries.

Views can be queried exactly the same way Collections are, but are not accessible in parse-server as they do not appear is the `_SCHEMA` collection, even if they appear in mongodb collections list (`db.getCollectionNames()` includes the views).

Would it be possible to allow parse-server to query views?
Thanks a lot

**Comment by flovilmart** [comment]
Feel free to open a PR to include those. Perhaps by manually creating a new entry in the _SCHEMA the view will appear to parse-server.
