### ISSUE TITLE
Can i use a middleware for CCF?

### ISSUE THREAD

**Issue by Fedeorlandau** [parse-community/parse-server#4072]
### Issue Description

I'm trying to add express-validator for cloud code functions.

#### Unexpected Results

`req.customFunction` is not defined

Does parse-server override request object? Can i add custom methods?

**Comment by flovilmart** [comment]
Cloud fonction are not express routes, therefore we don't have middleware engine. 
Also req and res are not node request/response objects but parse managed objects.
