### ISSUE TITLE
Display user password

### ISSUE THREAD

**Issue by BenBenz** [parse-community/parse-server#4074]
I want to send the password of my user via SMS and it is not possible when I try to get the password . undefined value is return

I've try user.get("password");

I think I can't do that for security reason ?

**Comment by montymxb** [comment]
Yes, passwords are stored in the database as a hash, which is computed one way only. Even if you could get one you would be unable to get the original password back for display. Additionally the password hash is kept away from the client sdks for security reasons.

I'm guessing you're trying to setup an initial password for a new user? If so you could generate one at random and send that if you wish, but email would be safer than SMS, even for a temporary password. An SMS message could be intercepted potentially whereas emails have to capacity to be transmitted over a secure connection.

**Comment by BenBenz** [comment]
@montymxb  thanks a lot for your explanation, and you quick answer

This is not a new user, this is the case when a user want to retrieve their password, in fact email must be safe but I need to do that by SMS,

I can't generate a password and set a new one and send it by sms ? 
When I change the password and try to save I have this error "Cannot modify user XXXXXX"

**Comment by montymxb** [comment]
Yeah technically you could manage resetting their password with a new one that you know and send that. But considering that you're trying to do have you tried the password reset flow instead?

**Comment by nbering** [comment]
Sending someone their plaintext password as password recovery options is so 1998. But I'm not going to leave it at that, because that would be unconstructive. You should read this. Troy Hunt is well-respected as an expert in the field of IT and Application Security.

https://www.troyhunt.com/everything-you-ever-wanted-to-know/
