### ISSUE TITLE
Q: how to define database schema? e.g. define a column as unique.

### ISSUE THREAD

**Issue by hatelove85911** [parse-community/parse-server#4076]
I'm new to parse-server.  I'm trying to find a way to define a database schema. So that when I save an object, it'll check if one field of the object is unique in the class.

**Comment by natanrolnik** [comment]
Parse Server manages the schema for you. Whenever you create an object and set a field, it will check if that object already has a type on that field. If it does, it will not allow saving a different type for that field; if it doesn't have yet, it will set that field to be of the type you set.

**Comment by hatelove85911** [comment]
@natanrolnik  what about setting a field unique?

**Comment by natanrolnik** [comment]
This is currently not supported; you would need to do it in the database level I believe. @flovilmart might have a better answer.

**Comment by GoGross** [comment]
@flovilmart  whats your take?

**Comment by flovilmart** [comment]
You can use indexes in both mongo or Postgres to enforce uniqueness for a particular column

**Comment by GoGross** [comment]
The API for schema also illustrates that, thanks, 

`const schema = new Parse.Schema('MyClass');
schema.addString('field');
schema.addIndex('index_name', {'field', 1});
schema.save();`
