### ISSUE TITLE
Cloud Job status has unexpected behaviour when calling kue's done()

### ISSUE THREAD

**Issue by harryjamesuk** [parse-community/parse-server#4079]
### Issue Description
**What happens?**

- When viewing the Job Status on parse-dashboard, when the job is run the 1st time, the job runs and will show with message **Completed** and status **SUCCEEDED**, this behaves as expected.
- However, if you run the job a 2nd time, the message shows as **Queued** and the status **RUNNING**.
- If you then run the job a 3rd time, the message shows as **Queued** and the status **RUNNING**, but also the 2nd job will then change and show the message **Completed** and status **SUCCEEDED**.
- Further running of the job has unexpected behaviour where sometimes previous jobs will change to SUCCEEDED but all the latest-run jobs show RUNNING.
- Even though in parse-dashboard, the jobs show as RUNNING, they **are actually processed by kue**, and **marked as done by kue**. That is, "Processing" will **always** be logged to the console.

**What happens if you remove the done() call?**

Everything works as expected, however the **jobs won't be marked as complete by kue**. Therefore the jobs will be kept active in kue, which isn't what you want.

---

### Steps to reproduce

Use the following code in a node.js environment:
```javascript
var queue = kue.createQueue();
queue.watchStuckJobs(1000);
queue.on('error', function(err) {
    console.error("Exception thrown in queue");
    console.error(err);
    console.error(err.stack);
});

Parse.Cloud.job('debugJob', function(request, status) {

    // Add to queue.
    var job = queue.create('debugJob', null).priority("low").removeOnComplete(true).save(function (err) {
        if (err) {
            console.error(err);
            status.error("Failed attempting to add job to queue: " + err.message);
            return Error("Error when adding job to queue");
        }
    });
    status.message("Queued"); // When using done(), the message will be "Queued".

    queue.process('debugJob', function(job, done) {
        status.message("Inner change");
        doSomeProcessing(job, done, status);
    });
});

function doSomeProcessing(job, done, status) {
    console.log("Processing...");
    status.message("Processing");

    status.success("Completed");
    done(); // CALLING THIS RESULTS IN UNEXPECTED BEHAVIOUR.
}
```

**Requirements**

- [parse JS SDK](https://github.com/parse-community/Parse-SDK-JS) - Tested with **parse/node**.
- [kue](https://github.com/Automattic/kue)
- [parse-dashboard](https://github.com/parse-community/parse-dashboard)

---

#### Expected Results

parse-dashboard should handle each job in the queue and they should all show the message **Completed** and status **SUCCEEDED** upon call of done().
 
#### Actual Outcome

This works fine the first time the program runs, but after which the job does not show as being complete according to the Parse Dashboard, although it has actually completed according to kue *(And any code in the doSomeProcessing() method will have been executed)*.

---

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.5.3
  - Operating System:     macOS Sierra
  - Hardware:             MacBook Pro 15-inch with Touch Bar 2016 model.
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): localhost

- **Database**
  - MongoDB version: 2.2.30
  - Storage engine:  -
  - Hardware:        MacBook Pro 15-inch with Touch Bar 2016 model.
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): localhost

### Logs/Trace

N/A.

---

### Additional info

**Dependencies used in test environment**
```json
    "kue": "^0.11.6",
    "kue-scheduler": "^0.7.3",
    "mongodb": "^2.2.30",
    "parse": "latest",
    "parse-dashboard": "^1.1.0",
    "parse-server": "^2.5.3",
    "redis": "^2.7.1",
```

**Comment by natanrolnik** [comment]
Hi @harryjamesuk - I'm pretty sure that `status.success()` is asynchronous.
Can you try the following:

```
status.success("Completed").then(function() {
   done();
});
```

**Comment by harryjamesuk** [comment]
Hi @natanrolnik - This code has the same affect unfortunately.

Tweaking your code slightly, I added a ``console.log("DONE")`` print before the call to done() here and I saw the **DONE** was printed all times *(As expected)*, but upon the **2nd run of the job**, the status in the dashboard shows:
**Message: Queued**
**Status: RUNNING**

**Comment by natanrolnik** [comment]
@harryjamesuk I believe that `status.message()` is also asynchronous. Can you try adding `.then()` to the calls and put the code that runs after in a callback instead?

**Comment by harryjamesuk** [comment]
Hi @natanrolnik 

Same happens when adding ``.then()`` to all of the calls, message and status are still the same *(Queued and RUNNING respectively)*.

Code as follows:
```javascript
        status.message("Queued").then(function() {
            queue.process('debugJob', function(job, done) {
                status.message("Inner change").then(function() {
                    doSomeProcessing(job, done, status);
                });
            });
        }); // When using done(), the message will be "Queued".
```

doSomeProcessing() is still called, and its output is still logged to the console.

**Comment by flovilmart** [comment]
Closing as this issue is related to the usage (mis-usage) of the kue api and not the dashboard or parse-server itself.

**Comment by harryjamesuk** [comment]
Hi @flovilmart Do you mind explaining to me how I've gone wrong when using the kue api? As far as I know I was just following the documentation and kue appears to be working fine for me - jobs are marked as successful by kue when they finish, it's just Parse dashboard is failing to update with the correct statuses.
Would appreciate any advice as this issue has been bugging me for a while!

Feel free to update me via email if you think the issue is not an appropriate place to discuss this on harryjamesuk [at] gmail [dot] com.
