### ISSUE TITLE
Cloud code AfterSave .dirty

### ISSUE THREAD

**Issue by ljs19923** [parse-community/parse-server#4082]
Hello, I would like to use the aftersave trigger of the Cloud code to know if a  key changed after saving an object. Is it possible ? I can not figure out how to do it. .dirty does not seem to work with aftersave?

Thanks you!

**Comment by natanrolnik** [comment]
Hey @JulienLevallois - in `afterSave`, all properties will be clean, not dirty. You can check the `dirty` properties in `beforeSave`.

**Comment by tealshift** [comment]
@JulienLevallois @natanrolnik  I believe you can use request.original to grab the state of the object before the save and compare!

**Comment by JulienLevallois** [comment]
@tealshift thanks ! AfterSave function dont need response ? completion, like beforeSave

**Comment by tealshift** [comment]
Correct. The afterSave function only has one parameter for 'request'. No response is possible.

**Comment by funkenstrahlen** [comment]
@JulienLevallois Did request.original work for you to solve the issue?

**Comment by oallouch** [comment]
@JulienLevallois did you use a library for your comparison ? What did you do in the case of arrays ?

merci d'avance

**Comment by JulienLevallois** [comment]
Hey ! @oallouch, dans le after save tu peux checker la version original de ton object et la nouvelle version apres le after save. Ainsi tu vas pouvoir comparer les deux et voir les différences. Si ton object contient un array, tu vas comparer les deux arrays pour voir si ils sont pareils

![image](https://user-images.githubusercontent.com/5727223/35407586-c3dd15c4-020c-11e8-85d1-e64e1f6ca5f9.png)

**Comment by vince1995** [comment]
For anybody else struggeling with this and Google brought you here: You could set in the `beforeSave` trigger the context and access this in the `afterSave` trigger:

```
Parse.Cloud.beforeSave("collectionName", req => {
    req.context.dirtyKeys = req.object.dirtyKeys();
});

Parse.Cloud.afterSave("collectionName", req => {
    console.log(req.context.dirtyKeys);
}); 
```

**Comment by JeffGuKang** [comment]
> For anybody else struggeling with this and Google brought you here: You could set in the `beforeSave` trigger the context and access this in the `afterSave` trigger:
> 
> ```
> Parse.Cloud.beforeSave("collectionName", req => {
>     req.context.dirtyKeys = req.object.dirtyKeys();
> });
> 
> Parse.Cloud.afterSave("collectionName", req => {
>     console.log(req.context.dirtyKeys);
> }); 
> ```

I applied it and it is working very well. 
```
Parse.Cloud.afterSave<Event>(
  'Event',
  async ({master, object, ...request}) => {
    const dirtyKeys = request.context.dirtyKeys as string[]
    if (dirtyKeys?.includes('name') !== undefined) return
    ....

**Comment by mtrezza** [comment]
Is there a feature or docs improvement to suggest?

To determine which fields changed in an `afterSave` trigger, you would compare the fields of `request.object`, which is the object state after saving, with `request.original` which is the object state before saving.

For example:

```js
let originalValue = request.original?.get(key); // request.original is undefined if the object was saved for the first time
let currentValue = request.object.get(key);
```
