### ISSUE TITLE
Return date as is (iso string) not as an object

### ISSUE THREAD

**Issue by zealmurapa** [parse-community/parse-server#4083]
Is there a reason why dates are returned as objects from the JS source?

`return { __type: 'Date', iso: value.toJSON() };`

why can't we just have a date string on its own to simplify bilateral data binding.

`return value.toJSON();`

**Comment by natanrolnik** [comment]
The SDKs and clients don't have any clues about the schema; when receiving an object, it cannot assume that a string is actually a date. This is why the server returns a JS object containing the `__type` of the object.

Changing it will break the clients.
