### ISSUE TITLE
Parse With Express Helmet For Security

### ISSUE THREAD

**Issue by trylovetom** [parse-community/parse-server#4084]
### Issue Description

I follow this guide below with my production parse server.
http://expressjs.com/en/advanced/best-practice-security.html
I use the module 'helmet' to hide my 'x-powered-by' header, but it's work.
It's still response with the header.

### Steps to reproduce

```
const express = require('express')
const ParseServer = require('parse-server').ParseServer
const path = require('path')
const config = require('./config')
const parseAPI = new ParseServer({
  appId: config.appId,
  databaseURI: config.databaseURI,
  cloud: path.join(__dirname, config.cloud),
  masterKey: config.masterKey,
  serverURL: config.serverURL
})
const app = express()
const helmet = require('helmet')
const httpServer = require('http').createServer(app)

app.use(helmet())
app.get('/', (req, res) => {
  res.status(200).send('I dream of being a website.  Please star the parse-server repo on GitHub!')
})
app.use('/public', express.static(path.join(__dirname, '/public')))
app.use(config.mountPath, parseAPI)
app.use('/test', (req, res) => { // Remove This Before Launching Your App
  res.sendFile(path.join(__dirname, '/public/test.html'))
})
httpServer.listen(config.port, () => {
  console.log('The Force Awaken On Port ' + config.port)
})

module.exports = httpServer
```

#### Expected Results

The response without 'x-powered-by' header

#### Actual Outcome

<img width="545" alt="2017-08-08 2 23 55" src="https://user-images.githubusercontent.com/13268073/29040211-c117ba90-7be0-11e7-88c8-245deeacd313.png">

### Environment Setup

- **Server**
  - parse-server version: ^4.15.3
  - Operating System: macOS Sierra
  - Hardware: MacBook Pro (Retina, 13-inch, Early 2015)
  - Localhost or remote server ?: localhost:3000

- **Database**
  - MongoDB version: v3.4.6
  - Storage engine: empty
  - Hardware: same as server
  - Localhost or remote server?: same as server

### Logs/Trace

```
The Force Awaken On Port 3000
info: Ran cloud function hello for user undefined with:
  Input: {}
  Result: "Hi" functionName=hello, , user=undefined
```

**Comment by woodardj** [comment]
I just started experimenting with Helmet myself, but we've had the following in our server code from day one, if you don't want to figure out what's going on with helmet:

```
app.disable('x-powered-by')
```

**Comment by trylovetom** [comment]
@woodardj  I know what's going on with helmet. https://helmetjs.github.io
"hidePoweredBy to remove the X-Powered-By header" is the default setup.

When I test the two api below, I get the different result.

If I post the '/', 'x-powered-by' is hide, but post the 'cloud  functions' isn't.

<img width="545" alt="2017-08-08 2 23 55" src="https://user-images.githubusercontent.com/13268073/29042391-563167c2-7be9-11e7-80bf-99bc7bb91aed.png">
<img width="479" alt="2017-08-08 3 26 03" src="https://user-images.githubusercontent.com/13268073/29042393-57f3c49c-7be9-11e7-9591-62ccd8779222.png">


```
const express = require('express')
const ParseServer = require('parse-server').ParseServer
const path = require('path')
const config = require('./config')
const parseAPI = new ParseServer({
  appId: config.appId,
  databaseURI: config.databaseURI,
  cloud: path.join(__dirname, config.cloud),
  masterKey: config.masterKey,
  serverURL: config.serverURL
})
const app = express()
const helmet = require('helmet')
const httpServer = require('http').createServer(app)

app.use(helmet())
app.use(config.mountPath, parseAPI)
app.post('/', (req, res) => {
  res.status(200).send('home')
})
httpServer.listen(config.port, () => {
  console.log('The Force Awaken On Port ' + config.port)
})

module.exports = httpServer

```

**Comment by flovilmart** [comment]
@trylovetom did you try `app.disable('x-powered-by')`, parse-server is an express app, so any middleware that strips headers etc.. should be OK, we don't re-enable anything internally.

**Comment by pewh** [comment]
Already add `.disable('x-powered-by')` and it still shown. Weird :/

**Comment by trylovetom** [comment]
@flovilmart Yes, I tried it. But it still shown. It's very weird. When I disable the parse-server middleware, `app.disable('x-powered-by')` it's work again.

**Comment by themoonlitknight** [comment]
It happens the same to me. Did you figure it out eventually?

**Comment by devdc** [comment]
@trylovetom a little bit of a dirty solution but the way `ParseServer`'s core is implemented, this seems to be the only way to achieve that-
```
function overrideParseServerHeaders(req, res, next) {
  const oldJson = res.json;
  res.json = function(data) {
    res.removeHeader('x-powered-by');
    // do anything you wanna do with response before Parse Server calls .json
    oldJson.apply(res, arguments);
  };
  next();
}
// mount Parse Server with our middleware
app.use(mountPath, overrideParseServerHeaders, api);
```
