### ISSUE TITLE
getACL() returns null if ACL is not explicitly set

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-server#4086]
### Issue Description

`ParseObject.getACL()` returns `null` for objects where the ACL property is not explicitly set.

### Steps to reproduce

1. Create a new Parse object without setting an ACL.
2. In Cloud Code query for the object
3. Get the object's ACL with `object.getACL();`

The object where this bug was discovered had this document in the collection:

```
{
    "_id": "kgoMaRz5j",
    "_created_at": {
        "$date": "2017-06-10T10:05:57.150Z"
    },
    "_updated_at": {
        "$date": "2017-06-10T10:05:57.150Z"
    }
}
```

#### Expected Results

Without an explicitly set ACL the object's ACL is `Public Read + Write`.
The return value of `getACL()` therefore should be accordingly.

#### Actual Outcome

The return value of `getACL()` is `null`.

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.5.3

- **Database**
  - MongoDB version: 3.2.15

**Comment by natanrolnik** [comment]
@mtrezza this is actually the expected behavior. Not having an ACL means the policy for that object is public write+read. Not all objects must have ACLs.

**Comment by mtrezza** [comment]
@natanrolnik I find this confusing in relation to Parse because I think it is not possible to completely remove an ACL via a Parse SDK or the Parse dashboard from an object once it is set. So setting an ACL  is a irreversible action (unless manual removal in the DB). 

If removing an ACL is not a functionality it should not make a difference whether an ACL is existing or not on the document level. It can be a considered a "behind the scenes mechanism".

If removing all ACL entries from an object was possible via Parse then I would agree that this is a mechanism that the developer has to consider and can potentially make use of.

**Comment by natanrolnik** [comment]
@mtrezza wait, the docs say the following:

- iOS: `@property (readwrite, strong, nonatomic, nullable) PFACL *ACL;`
- Android: `public void setACL(ParseACL acl)`
- JS: `Boolean setACL( acl, options ) `

It doesn't look like you cannot call `object.ACL = nil` on iOS and `object.setACL(null)` in the others. Have you tried?

**Comment by flovilmart** [comment]
Closing as working as expected.
