### ISSUE TITLE
Count limitations

### ISSUE THREAD

**Issue by manishsangwan** [parse-community/parse-server#4088]
Earlier parse docs had info about limitations of count such as rate limit and timeout issues for records more than 1000. I searched the current docs and could not find much info related to it.

Are there no issues with count query now. Any links for info on this will be really helpful.

**Comment by pungme** [comment]
You can do something like this in beforeFind 

```
Parse.Cloud.beforeFind('MyObject', function(req) {
  let isCount = req.count; // (available on parse-server 2.4.0 or up)
  if (req.count) {
     // reject or do something else 
  }
});
```

**Comment by addisonElliott** [comment]
I would not worry about the count limit. The warning of counting more than 1000 is a remnant of parse.com.

The docs still mention that there is a 1,000 limit and 10,000 skip limit for queries which is incorrect. I was able to retrieve about 14,000 items in a matter of a few seconds. So, counting a large amount of items will likely not be an issue.

But, to be clear, the only bottleneck for counting items is the timeout of the request.

**Comment by manishsangwan** [comment]
thanx @pungme @addisonElliott for clearing things.

**Comment by natanrolnik** [comment]
Closing this issue, let us know if there are any questions.
