### ISSUE TITLE
Server status 503 with error code 3840 when calling .signUpInBackground

### ISSUE THREAD

**Issue by KileyCaravella** [parse-community/parse-server#4093]
Description: 

I'm calling `.signUpInBackground` on a user object in swift 3 and here are the two responses I am receiving:

iOS:  `Error Domain=NSCocoaErrorDomain Code=3840 "JSON text did not start with array or object and option to allow fragments not set." UserInfo={NSDebugDescription=JSON text did not start with array or object and option to allow fragments not set.}`

Server: `at=error code=H12 desc="Request timeout" method=POST path="/parse/batch" host=xxx.herokuapp.com request_id=xxx fwd="000.000.00.000" dyno=web.1 connect=0ms service=30001ms status=503 bytes=0 protocol=https`

the object I'm sending (when printed out in xcode) looks like this: 

```
<ProjectName.User: 0x000000000a00, objectId: new, localId: (null)> {
    addresses =     (
        "<Address: 0x0000000a0000, objectId: new, localId: (null)>"
    );
    approved = 0;
    birthdayString = "1992-07-11";
    daysAvailable =     (
        Wednesday
    );
    email = "xxx@xxx.com";
    firstName = xxx;
    heardAboutBy =     (
        "App Store",
        Website
    );
    lastName = xxx;
    middleName = "";
    password = password;
    phoneNumber = "(800) 555-\U200b0000";
    transportation = "Electric Scooter";
    unformattedPhoneNumber = "+18005550000";
    username = "xxx@xxx.com";
}
```

The syntax is `newUser.signUpInBackground() { success, error in ... }`

I understand the error received on the iOS side usually coincides with bad JSON, but I'm calling a built-in function that I'm guessing serializes the object into JSON. Any ideas as to what is causing it? 

Our documentation says our parse-server is ~2.2.18 and unfortunately I'm new to working on the server so I'm not positive on the actual version.

**Comment by natanrolnik** [comment]
Are you able to run the server with `VERBOSE=1`? That might give a little more information when receiving the sign up request. 

Also, to get the exact Parse Server version, you can call: `yourapp.herokuapp.com/parse/serverInfo` with the master key.

**Comment by natanrolnik** [comment]
Are you able to run locally the server and make the call to signup? 
If so, and you are able to reproduce, it might give you more info with `VERBOSE=1`. If you can’t reproduce it locally, then probably it’s something related to the server configuration when deploying it.
Remember that you might need to allow http for localhost on the iOS side (iOS 9 blocks non https by default). 

Also, how is the serverURL property initialized?

**Comment by addisonElliott** [comment]
Since `signUpInBackground` works in some instances, I would recommend by removing fields from the user object and see when it starts to **work**. It sounds like there is a particular field that is causing this issue.

**Comment by KileyCaravella** [comment]
Thanks guys for the input!

It seems like the problem actually stems from trying to save the user's Address object (thanks @addisonElliott for recommending removing fields! I didn't do it at first because everything was working properly before this error appeared). It looks like the backend was not properly setup to handle certain addresses when associated with this specific type of user.

**Comment by addisonElliott** [comment]
I'm glad that worked. Is the issue solved then? Or is there still an error that needs to be fixed?

**Comment by natanrolnik** [comment]
@KileyCaravella if you think this might be a bug in Parse Server and you find a reproduction scenario, please write it here and we'll reopen and try to fix it.

**Comment by KileyCaravella** [comment]
The issue is solved! Sorry for not responding sooner, and sorry for wasting time but thank you so much for the help!

**Comment by natanrolnik** [comment]
No worries!
