### ISSUE TITLE
Earliest version of Parse-Server to support mongodb 3.2?

### ISSUE THREAD

**Issue by ronnno** [parse-community/parse-server#4095]
Hi,

What is the earliest version of Parse-Server that supports and was tested with mongodb 3.2 (with WiredTiger)?

We're running a pretty old ParseServer version 2.2.19 for a long time now. So far I've refrained from upgrading to a more current version as  2.2.22 requires me to upgrade our node.js engine to 4.5 and we are still running 4.3.1. So far that has led me to postpone upgrades of ParseServer fearing incompatible code.

But, we have strong reasons to move to mongodb 3.2 with WiredTiger now - and although ParseServer is documented as supporting MongoDb 3.2 - I did find that ParseServer 2.2.19 uses mongodb driver version 2.2.9 and according to [mongodb docs](https://docs.mongodb.com/ecosystem/drivers/driver-compatibility-reference/#node-js-driver-compatibility) this driver does not support 3.2.

However, it's perfectly reasonable that unsupported features were not used and since I'm using this configuration in non-production environments successfully, if you can confirm that 2.2.19 supports mongodb 3.2 that's good enough for me..

Thanks,
Ron

**Comment by flovilmart** [comment]
The best for you would be to tryout which if your current setup work also, I would recommend you bump your node-js version, 2.2.19 is very old indeed, and you're probably missing on security enhancements and bug fixes.

**Comment by ronnno** [comment]
thanks, upgraded to latest!
