### ISSUE TITLE
Query slow to execute when including thousands of pointers

### ISSUE THREAD

**Issue by bangersandflash** [parse-community/parse-server#4102]
### Issue Description

I have a Purchase class which has a column that is a pointer to an Event class. The Purchase class also has a column that is an array of Ticket pointers.

There are tens of thousands of Tickets in the database. A Purchase usually has 1k - 2k tickets.

When I query the Purchase class by Event and include tickets the query takes a long time to execute.

`var query = new Parse.Query("Purchase");

var Event = Parse.Object.extend("Event");
var event = new Event();
event.id = XXXX;

query.equalTo("event", event);
query.limit(100000);
query.include("tickets");
        
query.find({useMasterKey:true}).then(
   function(purchases){
      response.success(purchases);
    },
    function(error){
       response.error(error);
    }
);`

I have set the mLab slow query threshold to 20ms and there are only a few commands that run over the threshold. I have built all of the suggested indexes but it hasn't made any difference to the query time.

Is it simply the structure of my columns? Is there a better way to store the Tickets against the Purchase instead of an array of pointers? I don't think it's the indexing as the mLab monitoring is showing decent scanned docs vs indexes stats and as I mentioned, there aren't any mongo commands that are running over 20ms.

Another thought - could it be when it's including 2000 tickets it has to run a command so even if that command was 5ms it would still amount to 10000 milliseconds? I'm not sure what the inner workings of the include method are.

### Steps to reproduce

As with the above code, query a class that has an array column made up of thousands of pointers.

#### Expected Results

Results are returned quickly.

#### Actual Outcome

Query takes 10- 20 seconds to execute

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.5.3
  - Operating System:     OSX 10.12.4
  - Hardware:             Macbook Pro 2017
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Remote (AWS)

- **Database**
  - MongoDB version: 3.2.16
  - Storage engine:  MongoDB
  - Hardware:        Macbook Pro 2017
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): mLab

### Logs/Trace

Include all relevant logs. You can turn on additional logging by configuring VERBOSE=1 in your environment.

**Comment by sstant** [comment]
If you need to access thousands of tickets assigned to a single purchase, you should use a Relation: http://docs.parseplatform.org/js/guide/#many-to-many-relationships

This requires you to make an additional query in order to retrieve the objects, but it will scale a lot better, and you won't have to worry about maintaining an array of pointers if a ticket is deleted at some point.

```javascript
query.first({
  useMasterKey: true
}).then(purchase => { 

  var relation = purchase.relation('tickets');
  return relation.query().find();
  
}).then(tickets => {
  
  // all of the tickets for that purchase
  
});
```

If you need to pull a list of multiple purchases at once, that each contain thousands of tickets, do as @steven-supersolid  mentioned, and store a Purchase pointer on each ticket, and query for them separately:

```javascript
query.find({
  useMasterKey: true
}).then(purchases => {

  var Tickets = new Parse.Query('Ticket');
  Tickets.containedIn('purchase', purchases);

}).then(tickets => {

  // all of the tickets for all of the purchases
  
});
```

**Comment by bangersandflash** [comment]
Thanks for the help - I think the Purchase pointer will be the way to go as I do need to retrieve multiple purchases each with multiple tickets.
