### ISSUE TITLE
Parse.FacebookUtils.login does not work with masterkey

### ISSUE THREAD

**Issue by jjdp** [parse-community/parse-server#4103]
### Issue Description

The `Parse.FacebookUtils.logIn` does not work with masterkey in cloud code. It does not allow user creation if you disable the create ACL in user class.

### Steps to reproduce

`Parse.FacebookUtils.logIn(authData, {useMasterKey: true})`

#### Expected Results

User creation should be successful

#### Actual Outcome

Permission denied for action create on class _User

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.5.3
  - Operating System:     Ubuntu Server 16.04
  - Hardware:             2GB Memory, 2 vCPU, 40GB SSD
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): DigitalOcean

- **Database**
  - MongoDB version: 3.2.6
  - Storage engine:  MongoDB
  - Hardware:        2GB Memory, 2 vCPU, 40GB SSD
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): DigitalOcean

### Logs/Trace

```
2017-08-22T09:12:06.042Z - Error generating response. ParseError {
  code: 141,
  message: 
   ParseError {
     code: 119,
     message: 'Permission denied for action create on class _User.' } }
```

**Comment by natanrolnik** [comment]
I don't believe you should call any `logIn` method from Cloud Code. 
Why do you need to login in the server?

**Comment by jjdp** [comment]
I have some integrations from other services that I'd prefer to do in cloud code with signup and not in the client for security reasons.
Using `user.signup(null, {UseMasterKey: true})` works so shouldn't be the case the same with `Parse.FacebookUtils.logIn`.

**Comment by natanrolnik** [comment]
@flovilmart might have better answers, suggestions or observations

**Comment by jjdp** [comment]
as a side question though, how does `Parse.FacebookUtils.logIn` generate it's unique username? if your db is mongo then is it from `ObjectId()`?

**Comment by flovilmart** [comment]
This seems to be an issue with the JS SDK, after a quick search I found out that options are stripped (besides authData) https://github.com/parse-community/Parse-SDK-JS/blob/master/src/ParseUser.js#L79

**Comment by sunshineo** [comment]
Is the problem actually from this line not using 'useMasterKey'? https://github.com/parse-community/Parse-SDK-JS/blob/master/src/ParseUser.js#L1022
_linkWith eventually calls this linkWith

**Comment by ciekawy** [comment]
I hit the same issue when trying to integrate GraphQL via cloud code and trying to provide authentication mutation - should a new ticket be opend if its not possible? I believe this should be possible with any auth provider not only facebook

https://stackoverflow.com/questions/52701560/use-parse-server-cloud-code-to-do-facebook-authentication
