### ISSUE TITLE
Versioning cloud code

### ISSUE THREAD

**Issue by dangerdan** [parse-community/parse-server#4104]
Has anybody implemented versioning for cloud code?

Could this be a feature considered for implementation in the parse-server base code?

Starting this as a discussion for best practice, with the potential for a PR.

**Comment by oallouch** [comment]
When I deploy on Google App Engine, they version the whole server. I can rollback whenever I want.

**Comment by dangerdan** [comment]
To clarify, I'm talking about versioning between different implementations of cloud code functions, for changes that aren't backwards-compatible.

You may have users that are supported on different versions of the app using the same cloud code.

**Comment by flovilmart** [comment]
I would recommend you implement something with objects, like a version field. Then you can use it in cloud code

**Comment by flovilmart** [comment]
@dangerdan I'm closing the issue as we provided a way forward that is non obtrusive. Also in theory, nothing prevents you to use a new AppId with the same database and deploy a new version, mount on another path with the same App Id etc...
