### ISSUE TITLE
Scheduled push notifications

### ISSUE THREAD

**Issue by marvelm** [parse-community/parse-server#4105]
### Context
I would like to do the following through the dashboard.
1. Send push notifications at a specific local date and time.
2. Send recurring notifications (daily, weekly, monthly).

### Implementation

1. The `PushController` already supports the [`push_time`](https://github.com/parse-community/parse-server/blob/ad52ed64af4e32d1dc53913bb2a09e70d8a6ecf2/src/Controllers/PushController.js#L17) option and it creates a ["scheduled" `_PushStatus`](https://github.com/parse-community/parse-server/blob/51d2dd92cb8c3484d3643ee8d0a864a72554dac5/src/StatusHandler.js#L118).

   The scheduling logic should remain separate from `parse-server`, and it will be the developer's job to create/pick an implementation. This [separate program](https://github.com/AmpMe/parse-server-scheduled-pusher) will search for "scheduled" `_PushStatus` objects and send to devices in timezones for which the `pushTime` matches the current time. In order to track the delivery/failure rate of notifications, two new fields need to be added to the `_PushStatus`: `sentPerUTCOffset` and `failedPerUTCOffset`.

    These new fields are fully backwards compatible and should not affect `parse-server`. The only necessary change is adding a field to the dashboard for the user to specify the send time.
  The new schema:
    ```javascript
    _PushStatus: {
      // ...
      sentPerUTCOffset: {[key: number]: number},
      failedPerUTCOffset: {[key: number]: number}
    }
    ```

2. For this feature, I would like to introduce a new internal class in Parse called `_PushCampaign`. The pusher will create a `_PushStatus` object every interval for each `_PushCampaign`.
   Here's how the schema would look:
   ```javascript
   _PushCampaign: {
     state: "active" | "inactive",
     pushStatuses: _PushStatus[], // Pointers

     interval: "once" | "daily" | "weekly" | "monthly",
     sendTime: string, // hh:mm:ss
     dayOfWeek: ?number, // when interval = 'weekly',
     dayOfMonth: ?number, // when interval = 'monthly'
   }
   ```

    When designing this schema, I researched the available standards for representing repeated intervals and I found that [ISO 8601 supports it](https://en.wikipedia.org/wiki/ISO_8601#Repeating_intervals). However, I couldn't find a mature implementation in javascript. If the situation changes in the future, we can easily deprecate `interval`, `dayOfWeek`, and `dayOfMonth`.

I've been working on a reference implementation of the pusher at [@AmpMe/parse-server-scheduled-pusher](https://github.com/AmpMe/parse-server-scheduled-pusher).

I would appreciate any feedback on this strategy. Thank you for reading.

**Comment by flovilmart** [comment]
@acinader @felipemobile you may wanna have a look there

**Comment by acinader** [comment]
@marvelm if you're on AWS, you may want to take a look at: https://www.npmjs.com/package/parse-server-sqs-mq-adapter

Sounds like a nice, well thought out addition to me.
