### ISSUE TITLE
Parse.Object.saveAll in cloud code , should it use masterkey?

### ISSUE THREAD

**Issue by gateway** [parse-community/parse-server#4106]
Parse Version: 2.5.3

### Issue Description

Should Parse.Object.saveAll require master key in cloud code?

### Steps to reproduce

Save some data with 

```
  // Do save all
  Parse.Object.saveAll(objs, {
      success: function (result) {
          response.success(result);
          console.log('success')
      },
      error: function (err) {
          response.error(err.message);
          console.log('failed')
      }
  });
```

Please include a detailed list of steps that reproduce the issue. Include curl commands when applicable.

#### Expected Results

Most other saving of parse objects to the database fail in cloud code due to the lack of

`.save(null, {useMasterKey:true})`

**Comment by flovilmart** [comment]
It depends if your objects have write ACL set and you can’t write as a public user. Otherwise no,  saveAll don’t require masterKey
