### ISSUE TITLE
Cloud code not working if Masterkey have special characters ($%&·)

### ISSUE THREAD

**Issue by ckarmy** [parse-community/parse-server#4116]
**Parse version: 2.5.3**

Hi, I have a release app that have an appId and a master key with special characters (&%$#@)

When I try to run some Cloud Code function with ˋ({useMasterKey: true})ˋ I get ˋunauthorisedˋ. In other apps that are not release yet I remove the special character and problem solved! But I can´t change the appId and Master key for this app now because the app will crash for all users who have not updated the mobile app.

Is there some way to fix this? I try encoding the AppId and the Master key in ˋindex.jsˋ but I can´t start parse (I get ˋunauthorisedˋ)

Please help!!!!

Thanks!

**Comment by flovilmart** [comment]
You’re saying you’ve embedded the masterKey into a mobile app???? So don’t be surprised if a malicious user deletes your database. ROTATE it right away!

**Comment by ckarmy** [comment]
@flovilmart No! My masterKey is only in ˋindex.jsˋ. But when my appId and masterKey have special character my cloud function that use ˋmasterKeyˋ donˋt work.....

**Comment by flovilmart** [comment]
You can rotate the masterKey whenever you want... Otherwise, you're out of luck, you probably need to change it.

**Comment by ckarmy** [comment]
Ok then I will change my `masterKey` and see if the problem gone.

Thanks for your time!!!
