### ISSUE TITLE
Can't save ParseGeoPoint  - Parse Php SDK

### ISSUE THREAD

**Issue by soniurvashi11** [parse-community/parse-server#4117]
### Can't save ParseGeoPoint 

I am using parse php sdk and using simple save, without any relation. Here is my code -

$event = new ParseObject("Event");
$point = new ParseGeoPoint(25.20, 12.12);
$event->set("location", $point);
$event->save();

It is silently failing by just not saving my object at all!.
- **Server**
  - parse-server version :2.5.3
  - Localhost or remote server? AWS

  - Localhost or remote server?mLab

**Comment by natanrolnik** [comment]
Hi @soniurvashi11!

Do you have some server logs? Could you please fill the issue template?

**Comment by flovilmart** [comment]
@montymxb is it an issue related to the PHP SDK?

**Comment by montymxb** [comment]
Code looks fine to me. Went ahead and ran the 4 lines provided just to see if maybe there was a typo or something, but the code works 👍 . Whatever this is it's something other than an issue with the php sdk. @soniurvashi11 I would double check that saving on it's own without a geopoint doesn't not work as well...you might find there's something bigger going on there.

**Comment by flovilmart** [comment]
Closing then!
