### ISSUE TITLE
Change Facebook App for existing App.

### ISSUE THREAD

**Issue by gopal-aressindia** [parse-community/parse-server#4125]
### Issue Description

Currently, I have two Android apps published which is backed with Parse-Server. In my Apps, I have implemented Facebook login/signup with the Parse Facebook Utils. 

Both of the apps are using same Facebook App ID of a common Facebook app created initially. Now I need to separate out the Facebook app for some Internal reasons and for this I have to use separate Facebook App ID for each App.

Here the actual problem occurs, If I change app ID the authData we have received is different than the existing. I have tested this and found that the existing users of the app are treated as new users (A separate entry is created in User class). I want to avoid this disaster as I have the huge amount of live users Logged in with Facebook.

Anybody has done this before or have any solution regarding this. 
I am on a tight deadline to deal with it, any help will be appreciated
Thanks

### Steps to reproduce

not specific steps to reproduce. It is an obvious case. 

#### Expected Results

No new user should be created.

#### Actual Outcome

new user created in User class

### Environment Setup

- **Server**
  - parse-server version  : [2.2.24]

  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): [Remote Server - Heroku]

- **Database**
  - MongoDB version: [3.2.9]
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): [Remote Server - mLab]

### Logs/Trace

No specific logs.

**Comment by flovilmart** [comment]
Are your users already linked with their Facebook account when they upgrade to the new appId? The main issue you’re facing is that userId’s are not unique across multiple appId’s so Parse can’t tie them together. Your solution would be to unlink the users when they open with the new appID and link again with the new authentication data. Did you try that?

**Comment by montymxb** [comment]
@gopal-aressindia Yeah this sounds like you need to perform a migration of your existing users to the new app id. The unlink/link mentioned above would be a quick way to do this as mentioned above ^.

**Comment by gopal-aressindia** [comment]
Thanks, @flovilmart for your valuable note. I have not tried Link and Unlink yet, I have started the implementation of the same. Here I have one concern related to existing logged out users I mean users who have logged out from the app with old FB app id and now trying to log in into the updated app having updated FB app id. how should handle this case? Please suggest.

**Comment by flovilmart** [comment]
The case you're describing is quite problematic, I believe, because the user ID'S are not stable across apps, that you should get those users logged in with the old appId before you can migrate them.

**Comment by gopal-aressindia** [comment]
Thanks, Will try to handle this.
