### ISSUE TITLE
LiveQuery ignores mastery key after connection

### ISSUE THREAD

**Issue by Kenishi** [parse-community/parse-server#4127]
When connecting to the LQ Server its possible to specify client and the master key for an extra level of verification. After connection though the master key is ignored in cases where ACL rights are verified, resulting in a client that connected using the master key but no session token, not having master level permissions.

Considering the rest of Parse allows for a client to have practically universal/root level access as long as they supply the master key, should this not hold true for LiveQuery as well?

**Comment by flovilmart** [comment]
You’re right. We haven’t implemented masterKey support for LiveQuery. Is it something you’d want to implement?

**Comment by Kenishi** [comment]
I looked at the LiveQuery code and it looks like it might be a simple matter of adding a hasMasterKey flag to the Client when its created, if the master key is present and valid. Then simply checking for it in future operations. I just wanted to check if there was interest in changing it that way.

**Comment by flovilmart** [comment]
I believe this use case was not considered when designing it, always open for improvements. If you’re moving forward with the feature, don’t hesitate to open a PR with the proper tests and we’ll gladly review and merge it!

**Comment by flovilmart** [comment]
This is merged let's close!
