### ISSUE TITLE
Error with FacebookLogin

### ISSUE THREAD

**Issue by JulienLevallois** [parse-community/parse-server#4132]
Hi ! Sometimes, when a user signup with Facebook login and this method : 

PFFacebookUtils logInInBackgroundWithAccessToken:[FBSDKAccessToken currentAccessToken] block

I get this error : 

Domain=NSCocoaErrorDomain Code=3840 "JSON text did not start with array or object and option to allow fragments not set." UserInfo={NSDebugDescription=JSON text did not start with array or object and option to allow fragments not set.

I do not understand what this is all about. It does not happen all the time and it prevents the user from signing up

Thanks

**Comment by flovilmart** [comment]
Can you provide the server logs when running with VERBOSE=1 ?

**Comment by JulienLevallois** [comment]
My server is on Sashido.io so I will ask them. What is the purpose of VERBOSE = 1?

**Comment by flovilmart** [comment]
To gather all request/response logs and see what happens. Perhaps your request was malformed or the server responded in plain text, instead of a JSON object, which would explain the error you see.

**Comment by JulienLevallois** [comment]
What I do not understand is that the error does not happen every time. This can be related to speed / quality of connection or not?

**Comment by flovilmart** [comment]
without the logs nor a repro steps I can'T say much about it.

**Comment by JulienLevallois** [comment]
I just add verbose in my index.js like that ? 

<img width="424" alt="capture d ecran 2017-09-04 a 10 21 55" src="https://user-images.githubusercontent.com/5727223/30030397-027bcd66-915b-11e7-92d9-1c429e4fd614.png">

**Comment by JulienLevallois** [comment]
Okay now i have verbose=1 and i see all request/response logs. Whats the second step ? :)

<img width="1656" alt="capture d ecran 2017-09-04 a 10 31 35" src="https://user-images.githubusercontent.com/5727223/30030666-5b36714e-915c-11e7-8cff-c5fcc3f94ed2.png">

**Comment by flovilmart** [comment]
The next step, you'll need to trigger the error you've seen in the client and provide the logs. I'm closing the issue, please reopen when you gathered all the logs and reproduction steps and fill the issue template.

**Comment by JulienLevallois** [comment]
I don't understand what can i do to find this bug...
Once on 3 users get this error ...

Domain = NSCocoaErrorDomain Code = 3840 "JSON did not start with array or object and option to allow fragments not set." UserInfo = {NSDebugDescription = JSON text did not start with array or object and option to allow fragments not set.

**Comment by flovilmart** [comment]
Question is what is the logs from the parse server with verbose=1 so you can provide a trace of the problematic request/response

**Comment by JulienLevallois** [comment]
I can not find anything with these logs ..

Sometimes it works and sometimes the system creates 3 users with the same facebook identifier. This creates many problems

![image](https://user-images.githubusercontent.com/5727223/30138552-eee3cb0e-9336-11e7-84db-0776efeb9861.png)

**Comment by flovilmart** [comment]
That's another issue, that's off that multiple users are able to be created with the same Facebook ID... we have tests covering it, but I'll have a look

**Comment by JulienLevallois** [comment]
I think that's the same problem. On the client side I sometimes get this error when the user field is updated during the signup

Domain = NSCocoaErrorDomain Code = 3840 "JSON did not start with array or object and option to allow fragments not set." UserInfo = {NSDebugDescription = JSON text did not start with array or object and option to allow fragments not set.

With Verbose, I should see what kind of error?
I've been trying to figure this out for 7 days

**Comment by flovilmart** [comment]
I don't know what you should see, but probably an error, from the verbose logging.
Also, what version of parse-server are you running? if you're running on a hosting provider, I can't investigate anything as there's no guarantee they're running up to date code.

**Comment by JulienLevallois** [comment]
The parse version is 2.2.25-4
Yes I use sashido.io

**Comment by JulienLevallois** [comment]
Some users have the same error after the signup when I update a pointer to the user, so when the user field is updated

**Comment by flovilmart** [comment]
- 2.2.25-4 is not an official parse-server release.
- 2.2.25 was released about 6 months ago https://github.com/parse-community/parse-server/releases/tag/2.2.25

**Comment by JulienLevallois** [comment]
As for example for these two users. They had the error when the user field had to be updated with a pointer.

![image](https://user-images.githubusercontent.com/5727223/30139203-71932d44-933a-11e7-9885-688f3f8aae5f.png)

**Comment by flovilmart** [comment]
again, you're most likely running against a version that is 6 month old, not official, so I can't act much, I would recommend you reach out to your hosting provider in order to get more informations about your issue.

Finally, if you can reproduce the issue on your own instance, running against the latest parse-server version, and properly filling the STR, I'll be happy to help. As for now, I can't help as I don'T have any of the informations required in the originally asked issue template.

**Comment by JulienLevallois** [comment]
Alright I understand. thank you very much

**Comment by JulienLevallois** [comment]
Hi @flovilmart ! 

This is the reponse of Sashido about my problem. I will try that


" If you have "Parse.Object.extend()" method inside function each time when you call this function the CPU keep increase until it reached 100% load.

Example:
Parse.Cloud.define("SomeFunction", function(request, response) {
  var someClassName = Parse.Object.extend("someClassName");
  ...
});

This accumulates slowly but surely CPU load and at a certain moment eats the hole CPU and your Parse Server just stop working (this will restart the Parse Server). At this moment when your server is down the new user comes and ... you know what happens.

You can prevent this by move the ("Parse.Object.extend") to the global scope like this:

var someClassName = Parse.Object.extend("someClassName");

Parse.Cloud.define("SomeFunction", function(request, response) {

  ... do whatever you need with someClassName here ...
});

You should do this for all "Parse.Object.extend()" methods inside functions. "

**Comment by tai-x** [comment]
> That's another issue, that's off that multiple users are able to be created with the same Facebook ID... we have tests covering it, but I'll have a look

@flovilmart  I'm using the latest Parse Server 2.8.2 and this started to happen about 2 weeks ago in my production environment (which is like 2 years old), **multiple** users being created with the same Facebook **ID....** I have a dev environment with exactly the same code, and it doesn't have there (confirming that this is not a problem with something changing in the client - which in fact hasn't change a line of code in months now so it's odd that it is happening all of a sudden and in production only).
