### ISSUE TITLE
LiveQuery: Potential edge case bug in connection handling

### ISSUE THREAD

**Issue by Kenishi** [parse-community/parse-server#4136]
While working on a recent PR I noticed something that I think could turn into a bug in very high client throughput environments (or malicious users).

When a client connects to the LQ server it gets assigned a client ID which the server uses to link future subscriptions to that connection. This client ID is assigned from an integer/number that starts at 0 and is steadily increased as clients connect. There is no ID resuse that occurs so you could eventually break the safe bounds of integers. I'm not exactly sure what effect that would have during runtime, but I suspect it would cause weird occasional errors. Javascript doesn't really have a concept of "integer overflow," its simply a breakdown in floating point precision.

Again, this is likely to only ever occur when you have an absolutely insane number of clients connecting and you never restart the server. I'm not exactly sure what the solution to this is, but it might require a change in data structure for how clients are stored so client ids can be reused.

Just thought I would point this out.

**Comment by Thons** [comment]
I inspected code recently, and also concerned about this problem.
If we modify code simply, 

_instance property_
`clientId: string;
`

_constructor_
`this.cliendId = uuid() // uuid generator module, or random string generator`

__handleConnect_
`const client = new Client(this.clientId, parseWebsocket); // not changed`
`parseWebsocket.clientId = this.clientId; // not changed`
~~`this.clientId += 1;`~~

Pros:
Avoid "integer overflow" problem.
Cons:
Maybe increase obviously memory consumption.

it would be better?

**Comment by flovilmart** [comment]
That would be reasonable I guess

**Comment by flovilmart** [comment]
Would you want to provide a PR for it?

**Comment by Kenishi** [comment]
@Thons 's solution is simple and way easier than what I immediately thought of, a Sparse Array. The UUID allows for the current Map() setup to continue to work and I believe the UUID is actually the same kind of setup that Socket.io is using for managing clients. I'd probably do something like `uuid(clientMap)` so you can verify at generation that you aren't getting a (highly unlikely) collision.

**Comment by flovilmart** [comment]
@Kenishi do you want to take on a PR for that on?

**Comment by flovilmart** [comment]
@Kenishi this has been addressed with https://github.com/parse-community/parse-server/pull/4168
