### ISSUE TITLE
re enabling Parse.Cloud.useMasterKey() in parse server for ease of use

### ISSUE THREAD

**Issue by adplaygit** [parse-community/parse-server#4140]
re enabling Parse.Cloud.useMasterKey() in parse server for ease of use

Parse.Cloud.useMasterKey() is deprecated  and i dont want to do {useMasterkey:true} in each operation .
how can i globally enable useMasterKey in cloud code for all operations  ?
thanks.

**Comment by flovilmart** [comment]
You can’t, and it’s unlikely we’ll bring that back.
