### ISSUE TITLE
Error with withinMiles 

### ISSUE THREAD

**Issue by lavTeam** [parse-community/parse-server#4156]
I'm use: -whereKey:nearGeoPoint:withinMiles:

in real device (iphone se):
My code:
        query.whereKey("location", nearGeoPoint: (myUser?.locationUser)!, withinMiles: 10.0)
        query.findObjectsInBackground { (objects, error) in
            for object in objects! {
                //print(objects as! [PFObject])
                questionDict["question"] = object["question"]
                questionDict["textAnswer"] = object["textAnswerArray"]
                questionDict["imageAnswer"] = object["imageAnswerArray"]
            }
            self.questionArray.append(questionDict)
            if objects?.count == self.questionArray.count {
                self.listQuestionTableView.reloadData()
            }
        }

error in console:
2017-09-13 14:16:53.599436+0300 MyApp[634:152792] [Error]: {
    "$err" = "Can't canonicalize query: BadValue not handled: $maxDistance";
    code = 17287;
    message = "Can't canonicalize query: BadValue not handled: $maxDistance";
    name = MongoError;
} (Code: 1, Version: 1.15.2)

in simulator - no error (work).

BUT!!!
if I  use
...
 query.whereKey("location", nearGeoPoint: (myUser?.locationUser)!)
...
 the program works.

"location" - GeoPoint (PFGeoPoint)
(myUser?.locationUser)!) - GeoPoint (PFGeoPoint)

How to fix?

![2017-09-13 14 36 11](https://user-images.githubusercontent.com/25838110/30375385-06baf428-9891-11e7-9253-cba22b92d5a0.png)
![2017-09-13 14 36 24](https://user-images.githubusercontent.com/25838110/30375386-06d8bf76-9891-11e7-9535-b2d249304a39.png)
![2017-09-13 14 36 01](https://user-images.githubusercontent.com/25838110/30375387-06db9c6e-9891-11e7-90c1-0b565c7814ff.png)

**Comment by flovilmart** [comment]
Can you provide the server version as well as the logs when running with VERBOSE=1

**Comment by lavTeam** [comment]
Sorry, this is my mistake. 
(myUser?.locationUser)!) - value = nil

Sorry!!!!Sorry!!!!Sorry!!!!

**Comment by flovilmart** [comment]
Hah no need to be sorry! VERBOSE logs are usually here to help you pinpoint code issues :)
