### ISSUE TITLE
Allow custom objectId 

### ISSUE THREAD

**Issue by drsounds** [parse-community/parse-server#4170]
### Issue Description

I want to be able to set custom objectId when saving new parse objects.

### Steps to reproduce

```js
let obj = new Parse.Object('Country');
obj.set('objectId', 'vr');
obj.set('name', 'Virtual Reality');

#### Expected Results

A parse with the objectId vr.

**Comment by flovilmart** [comment]
It seem dangerous to allow the client overriding the objectId, you may end-up writing data in an unsuspected object.

What would be your use case?

**Comment by montymxb** [comment]
@drsounds I would be concerned as well, immediately what comes to mind is accidentally overwriting an existing object. I think, considering the purpose of the ids to be a unique identifier, setting them in a potentially non-unique fashion could be troublesome. There would be no way to sanity check a potential override.

Perhaps what you're thinking of is a tag of sorts to categorize an object by? You can always add an additional field to perform such a task, and I'm sure everyone would recommend such an approach over setting custom ids. However I don't know why you want this, so let us know if there's something specific we're missing that this could be handy for.

**Comment by montymxb** [comment]
Hey haven't heard anything so I'm going to go ahead and close this out. I would love to hear your use case though. If you want to continue discussing this feel free to let us know and we'll reopen it as needed!

**Comment by Gausoft** [comment]
**I got the same problem for this use case :**
An application in an intranet network that have to send parse objects already saved in offline to online parse-server. The online object's Id is different.

**Comment by rhuanbarreto** [comment]
Hi to all! Have a look on PR #6177 and share your thoughts! Now we can do this!

**Comment by tanzeelrana** [comment]
We should allow users to configure rules for parse objectId when they setup parse server. At the moment we have the possible chars hard coded here : https://github.com/parse-community/parse-server/blob/master/src/cryptoUtils.js#L26

`const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ' + 'abcdefghijklmnopqrstuvwxyz' + '0123456789';`

This makes things difficult when I am trying to integrate elastic search with parse server.

**Comment by tanzeelrana** [comment]
update: this feature is now available in the documentation 
https://parseplatform.org/parse-server/api/master/ParseServerOptions.html
`allowCustomObjectId`
