### ISSUE TITLE
Facebook and google signup/login

### ISSUE THREAD

**Issue by manishsangwan** [parse-community/parse-server#4178]
I want to implement google/ facebook sign up/login in my app. Coudn't find any docs on this.
The most if found was http://docs.parseplatform.org/parse-server/guide/#oauth-and-3rd-party-authentication   this was on the server side and provides the configuration for api keys. I understand that. But nothing is explained on the client side to implement it. No info on what the flow is going to be. How will the access token be handled etc. Does parse have any mechanism for this or will i need to do it manully myself?
Also the docs specifies the functions to validate access tokens and auth data. But how are the auth token going to be managed on client side? and how is parse session token generated for session token?

**Comment by manishsangwan** [comment]
Also the docs specifies the functions to validate access tokens and auth data. But how are the auth token going to be managed on client side?

**Comment by flovilmart** [comment]
You should acquire the tokens client side, for Facebook, it’s built in the JS SDK and there are utilities you can find on this org for iOS and Android. 

For google, the process is similar, once you’ll have Facebook setup, google should be trivial.

Thanks for pointing out we should probably add a note to the docs.

**Comment by ittechsathish** [comment]
Could you please explain how to acquire the token. If there is no documentation for login itself, it is very difficult job to learn and use this framework. Requesting to add a short note and very short example code...

**Comment by davimacedo** [comment]
@ittechsathish which is the SDK that you are using and learn to more about? Android, iOS, JS?
