### ISSUE TITLE
Mongo relationships

### ISSUE THREAD

**Issue by dangerdan** [parse-community/parse-server#4180]
Can somebody explain the mongo relationship/pointer format? The data format (Collection$ID) doesn't look standard to me.

Has anybody been able to make this work with mongoose?

**Comment by flovilmart** [comment]
It’s not compatible with Mongoose, nor we’re using anything specific from mongo like DB refs.
Pointer are just a string with the target collection and objectId that we lookup at runtime. For relations, we use a join table and resolve, again, at runtime.

**Comment by dangerdan** [comment]
Is there a reason a custom implementation was chosen?

**Comment by flovilmart** [comment]
On this project, to match the original implementation of parse.com and guarantee backwards compatibility. Originally, I’m not sure but it is not a bad way of representing relational data in mongodb, dbref’s can become very hairy, and don’t support relationships. 

Parse-server has nothing to do with Mongoose, not is Mongoose used internally. Actually, it wouldn’t help us at all given the dynamism of parse object models.
