### ISSUE TITLE
Parse query returning the complete content of nested Parse objects when not desired.

### ISSUE THREAD

**Issue by Dygerati** [parse-community/parse-server#4214]
### Issue Description

I have a Parse Object that includes two references to other Parse Objects in it's properties (as well as other information in other fields). My expectation via the documentation is that when I fetch this object it will **not** include the data on the referenced objects unless I use the `include([])` function to instruct it to. Instead, on a bare-bones query it seems to be returning all data on all referenced objects; I can see this just via a `console.log()` on the result of the query. 

This is resulting in more data going over the wire that I expect or want on every request. 

### Steps to reproduce

This is the code I'm using for the query:

```
import { minusHours } from '../util';
const Session = Parse.Object.extend('GameSession');

let query = new Parse.Query(Session);
query.greaterThanOrEqualTo('scheduledAt', minusHours(new Date(), 1));
query.ascending('scheduledAt');
return await query.find();
```

#### Expected Results

I expect the result to not include the complete content of the referenced objects. 

#### Actual Outcome
It includes the complete content of the referenced objects.

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.4.2
  - Operating System:     Sorry, can't find this information
  - Hardware:             Sorry, can't find this information
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Remote, NodeChef

- **Database**
  - MongoDB version: 3.0.12
  - Storage engine:  Sorry, can't find this information
  - Hardware:        Sorry, can't find this information
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): Remote, Nodechef

### Logs/Trace

Include all relevant logs. You can turn on additional logging by configuring VERBOSE=1 in your environment.

**Comment by flovilmart** [comment]
can you provide logs when running with verbose=1 ? note that you're running on node chef and they are known to run a fork of parse-server, Therefore, I'm not sure if opening an issue here is the best place. Also, version 2.4.2 if as old a may 2017, you may wanna update to the latest version.

As for your question:
>it will not include the data on the referenced objects unless I use the include([])

it should not, but all direct keys will be there (strings, dates, nested objects etc...) only pointers are not fetched (only by their objectId / ClassName)

**Comment by Dygerati** [comment]
Thanks for the quick response. This is the output on the server with **verbose=1**:
```
} 
} 
] 
} 
} 
} 
"read": true 
"*": { 
}, 
"write": true 
"read": true, 
"IZzXsmcyTK": { 
"ACL": { 
}, 
"className": "_User" 
"__type": "Relation", 
"attendees": { 
"updatedAt": "2017-09-28T03:52:01.606Z", 
"createdAt": "2017-09-28T03:52:00.764Z", 
}, 
"objectId": "IZzXsmcyTK" 
"className": "_User", 
"__type": "Pointer", 
"host": { 
"description": "", 
}, 
"objectId": "BWK9zoi6VB" 
"className": "Game", 
"__type": "Pointer", 
"game": { 
"title": "Test", 
}, 
"iso": "2017-09-28T04:51:00.000Z" 
"__type": "Date", 
"scheduledAt": { 
{ 
"results": [ 
"response": { 
RESPONSE from [GET] /parse/classes/GameSession: { 
```

It's a little weird to read; looks like it's upside down? This is just from the App Logs on node chef.

And this is the result from the query in the client app:

```
{
    "ACL": Object {
      "*": Object {
        "read": true,
      },
      "IZzXsmcyTK": Object {
        "read": true,
        "write": true,
      },
    },
    "attendees": Object {
      "__type": "Relation",
      "className": "_User",
    },
    "createdAt": "2017-09-28T03:52:00.764Z",
    "description": "",
    "game": Object {
      "__type": "Object",
      "appId": 527100,
      "className": "Game",
      "createdAt": "2017-08-07T19:35:15.206Z",
      "description": "Star Trek™: Bridge Crew will immerse you in the Star trek universe thanks to VR. In co-op, form a crew of four players to serve in the roles of Captain, Helm, Tactical or Engineer. Make strategic decisions and coordinate actions with your crew.",
      "isFree": false,
      "multiplayer": true,
      "name": "Star Trek™: Bridge Crew",
      "objectId": "BWK9zoi6VB",
      "thumbnail": "http://cdn.akamai.steamstatic.com/steam/apps/527100/capsule_sm_120.jpg?t=1496844035",
      "updatedAt": "2017-08-07T19:35:15.206Z",
      "vrOnly": true,
    },
    "host": Object {
      "ACL": Object {
        "*": Object {
          "read": true,
        },
        "IZzXsmcyTK": Object {
          "read": true,
          "write": true,
        },
      },
      "__type": "Object",
      "avatarfull": "REDACTED",
      "avatarmedium": "REDACTED",
      "className": "_User",
      "createdAt": "2017-09-04T05:25:42.897Z",
      "objectId": "IZzXsmcyTK",
      "personaname": "REDACTED",
      "profileurl": "REDACTED",
      "sessionToken": "r:REDACTED",
      "steamId": "REDACTED",
      "updatedAt": "2017-09-04T05:25:42.897Z",
      "username": "REDACTED",
    },
    "objectId": "xDZ2A4FhIE",
    "scheduledAt": Object {
      "__type": "Date",
      "iso": "2017-09-28T04:51:00.000Z",
    },
    "title": "Test",
    "updatedAt": "2017-09-28T03:52:01.606Z",
  }
```

As you can see, both the `host` and `game` properties are just pointers, and I wouldn't expect to receive any of their contents from the query. But the results include pretty much everything.

**Comment by flovilmart** [comment]
Yes I can see that, unfortunately, you’re running on 2.4.2, I can check if there’s any issue with the current version, but I highly doubt. Can you reproduce the issue with the latest version? On a local development machine?

**Comment by Dygerati** [comment]
Forgot to mention, I had actually upped it to 2.6.1, with the same behavior, before capturing those logs. I'll have to setup a local parse for anything more recent.

**Comment by flovilmart** [comment]
Can we see the query part of the logs?

**Comment by Dygerati** [comment]
Ah yes, guess I missed that part:

```
} 
} 
} 
} 
"iso": "2017-09-28T15:33:38.805Z" 
"__type": "Date", 
"$gte": { 
"scheduledAt": { 
"where": { 
"order": "scheduledAt", 
REQUEST for [GET] /parse/classes/GameSession: {
```

**Comment by Dygerati** [comment]
So, after looking at this a little further I believe it has something to do with the Parse-SDK-JS package. I've been running the query using the the react-native version of this package, and just ran the exact query with the node version and received the expected results. Things don't look very active over there but I'll give it a go. Thanks for you help.
