### ISSUE TITLE
Update Parse Server Guide for token based authentication for push notifications

### ISSUE THREAD

**Issue by hipwelljo** [parse-community/parse-server#4215]
### Issue Description

The Parse Server Guide in the Push Notifications section states "Token-based authentication instead of a certificate is not supported yet." But this is no longer true, authorization token support was added into the push adapter earlier this year (looking at this [pull request](https://github.com/parse-server-modules/parse-server-push-adapter/pull/52)). If this would be updated and the config option examples added for that approach, that would be great!

**Comment by montymxb** [comment]
@hipwelljo I took a look and it looks like you're referring to [this](http://docs.parseplatform.org/parse-server/guide/#apns-ios) section.

@flovilmart I'm not 100% on whether this is the case, I haven't been using push personally. Is this something that has in fact changed? If so we can close this out and open a relevant issue in the docs instead, following up with a PR when we have some time.

**Comment by flovilmart** [comment]
I believe the APNS node module supports token based auth, we’ll probably need to update the docs to reflect thatz

**Comment by hipwelljo** [comment]
Confirmed this format works:
```
push: {
    ios: [
      {
        token: {
          key: path.join(__dirname, 'AuthKey_XXXXXXXXXX.p8'),
          keyId: "XXXXXXXXXX",
          teamId: "YYYYYYYYYY"
        },
        topic: 'com.domain.appname',
        production: false
      }
      //add for production: true...
   ]
}
```

**Comment by montymxb** [comment]
@hipwelljo if you have a moment can you open up a PR with the relevant changes add. The corrected text would go about [here](https://github.com/parse-community/docs/blob/gh-pages/_includes/parse-server/push-notifications.md#apns-ios) in the docs repo.

**Comment by flovilmart** [comment]
Docs have been merged, closing! Thanks for the PR!

**Comment by montymxb** [comment]
Thanks again @hipwelljo !
