### ISSUE TITLE
Parse LiveQuery Scalability with Redis Failure

### ISSUE THREAD

**Issue by badraygun** [parse-community/parse-server#4217]
### Issue Description

When running separate Parse Server and Parse LiveQuery Servers with Redis for scalability, the Parse Server does not publish to Redis in order to push down new updates to the LiveQuery Servers.

Current Setup is as follows:

### Steps to reproduce

Please include a detailed list of steps that reproduce the issue. Include curl commands when applicable.

#### Expected Results

What you expected to happen.

#### Actual Outcome

What is happening instead.

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : [FILL THIS OUT]
  - Operating System:     [FILL THIS OUT]
  - Hardware:             [FILL THIS OUT]
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): [FILL THIS OUT]

- **Database**
  - MongoDB version: [FILL THIS OUT]
  - Storage engine:  [FILL THIS OUT]
  - Hardware:        [FILL THIS OUT]
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): [FILL THIS OUT]

### Logs/Trace

Include all relevant logs. You can turn on additional logging by configuring VERBOSE=1 in your environment.

**Comment by flovilmart** [comment]
@badraygun can you please provide more details and re-open the issue please?

**Comment by badraygun** [comment]
@flovilmart can you reopen this issue please, accidentally posted before finishing, it has been edited accordingly.
