### ISSUE TITLE
Impossible use mailgun adapter in cloud code

### ISSUE THREAD

**Issue by MattiaConfalonieri** [parse-community/parse-server#4219]
I have successfully installed malign adapter for my server (based on heroku) everythings work great for confirmation mail and password reset. but when I try to use mailgun into cloud code aftersave, I receive the error "mailgun-js not found" I have also tried to install mailgun standalone but nothing change, here my cloud, is a issue or I miss something... thanks for help.

```
//// Notifica mail su commento magazine////
Parse.Cloud.afterSave("CommentsMagazine", function(request) {
  console.log("INIZIO FUNZIONE");
  var mailgun = require('mailgun-js')({apiKey: 'APIKEY', domain: 'DOMAIN'});

  console.log("DOPO INIZIALIZZAZIONE");

  var mail = {
    from: 'YY@YY',
    to: 'XX@XX',
    subject: 'Hello',
    text: 'Testing some Mailgun awesomness!'
  };
  console.log("Poco prima dell'invio");
  mailgun.messages().send(mail, function (sendError, body) {
               if (error) {
                   console.log(sendError, 'mailgun sendError');
               } else {
                   console.log(body, 'Successfully send RECEIPT email to "' + toEmail + '"');
               }
           });
});
```

**Comment by MattiaConfalonieri** [comment]
In detail here the errors

 (node:17) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Cannot find module 'mailgun-js'

(node:17) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by flovilmart** [comment]
I believe you forgot to ‘save’ the package to package.json when installing.

**Comment by montymxb** [comment]
@MattiaConfalonieri did you manage to figure this out? It does seem like it's not installed from your post.

**Comment by MattiaConfalonieri** [comment]
I finally use an http request to the malign api.
