### ISSUE TITLE
Override sending email verification function

### ISSUE THREAD

**Issue by hanih** [parse-community/parse-server#4226]
I want to change the email verification sending function to differentiate between a new registration and a username reset to be able to send customized message for each.
This will require updating userRouter's handleVerificationEmailRequest  and userController's sendVerificationEmail functions to allow sending a flag to email adapter.
Is it better to add another parameter to these functions or pass the flag as a property inside the existing parameters ? @flovilmart

**Comment by flovilmart** [comment]
@hanih I would tend to recommend using a flag on the existing arguements. Would you work on a Pr so we can discuss from there?

**Comment by hanih** [comment]
@flovilmart Will do

**Comment by mulp** [comment]
Hi guys, any update on that? It would be great to have this feature.

**Comment by sd1998** [comment]
@dplewis Can I work on this?

**Comment by johnnydimas** [comment]
We were able to add custom behaviour without modifying parse by using express middleware. 

For example:
`app.use('/verify_email_success', _VerifyEmailSuccessRouter);`

With this we can intercept the request, get information on the user and do different things. Is that not sufficient for this use case?

**Comment by dblythy** [comment]
@mtrezza can this be closed with your great mail adapter?

**Comment by mtrezza** [comment]
It allows for customization, but I think we would beed more details from @hanih to know for sure whether it covers this specific scenario. After 4 years I would close this for now.

**Comment by mtrezza** [comment]
Closing this due to lack of details. We can reopen if the discussion gets picked up again.
