### ISSUE TITLE
Should we sort where clause of queries??

### ISSUE THREAD

**Issue by acinader** [parse-community/parse-server#4232]
In building and managing indexes, I am finding cases where I have to build indexes for various permutations of 'where constraints', for example:

```{"categoryId": 1, "_p_post": 1, "endOfWindow": 1}```

and 

```{"endOfWindow": 1, "categoryId": 1, "_p_post": 1}```

Being a little lazy, I haven't 100% confirmed that I have two different queries generating these different orders, but I don't think so.  And even if I did....

So my question: should I (optionally?) add a sort to `MongoTransform.transformWhere()`

I'm no expert at mongo (to say the least) and maybe there are times where the order of the where clause has important performance implications?  But even if that were the case, the current model where we use an object to hold the `restWhere` doesn't guarantee order anyway.

I can imagine if I were to just introduce the sort that it could cause problems for some folks even though there shouldn't be a guarantee of order currently.

Am I missing something here?  Hard to believe that I am the first person noticing this.

@dplewis what about postgres?

**Comment by steven-supersolid** [comment]
The order of the query arguments does not affect MongoDB performance, they are just and-ed together. I couldn't find a document that explicitly states this but the AND is mentioned here:  https://docs.mongodb.com/manual/tutorial/query-documents/#specify-and-conditions

The query planner will try and use the best index for the query and in the case of a compound index the order of the index is important, particularly when not using the entire index or when sorting. However, even with compound indexes, the order of the query will not matter.

If you only have equality queries then you should only need one permutation of the index.
If you have sorting or ranges as part of the query then there is an optimal index order to reduce index scans and avoid in-memory sorts. Here's a good writeup https://emptysqua.re/blog/optimizing-mongodb-compound-indexes/

So I don't think it's worth sorting transformWhere.

**Comment by acinader** [comment]
@steven-supersolid oh man, so I'm like actually gonna have to learn here ;)

so I created a test db:

```
> db.test_Foo.find()
{ "_id" : "bD1UrFNFoN", "bar" : "xxx", "baz" : "zzz", "_created_at" : ISODate("2017-09-28T23:52:30.150Z"), "_updated_at" : ISODate("2017-09-28T23:52:30.150Z") }
{ "_id" : "sTRrehEY4A", "bar" : "xxx", "baz" : "zzz", "_created_at" : ISODate("2017-09-28T23:53:56.692Z"), "_updated_at" : ISODate("2017-09-28T23:53:56.692Z") }
{ "_id" : "BG0KXDkgcv", "bar" : "xxx", "baz" : "zzz", "_created_at" : ISODate("2017-09-28T23:54:37.637Z"), "_updated_at" : ISODate("2017-09-28T23:54:37.637Z") }
{ "_id" : "lM9HiDm1CZ", "bar" : "xxx", "baz" : "zzz", "_created_at" : ISODate("2017-09-28T23:55:19.379Z"), "_updated_at" : ISODate("2017-09-28T23:55:19.379Z") }
{ "_id" : "uVLAsuDDzJ", "bar" : "xxx", "baz" : "zzz", "_created_at" : ISODate("2017-09-28T23:59:06.013Z"), "_updated_at" : ISODate("2017-09-28T23:59:06.013Z") }
```

and added an index on `{ bar: 1, baz: -1 }`
```
> db.test_Foo.getIndexes()
[
	{
		"v" : 2,
		"key" : {
			"_id" : 1
		},
		"name" : "_id_",
		"ns" : "parseServerMongoAdapterTestDatabase.test_Foo"
	},
	{
		"v" : 2,
		"key" : {
			"bar" : 1,
			"baz" : -1
		},
		"name" : "bar_1_baz_-1",
		"ns" : "parseServerMongoAdapterTestDatabase.test_Foo"
	}
]
```
If I try to query on baz, it doesn't use the index:
```
> db.test_Foo.find({ baz: 'zzz'}).explain()
{
	"queryPlanner" : {
		"plannerVersion" : 1,
		"namespace" : "parseServerMongoAdapterTestDatabase.test_Foo",
		"indexFilterSet" : false,
		"parsedQuery" : {
			"baz" : {
				"$eq" : "zzz"
			}
		},
		"winningPlan" : {
			"stage" : "COLLSCAN",
			"filter" : {
				"baz" : {
					"$eq" : "zzz"
				}
			},
			"direction" : "forward"
		},
		"rejectedPlans" : [ ]
	},
	"serverInfo" : {
		"host" : "arthur",
		"port" : 27017,
		"version" : "3.4.9",
		"gitVersion" : "876ebee8c7dd0e2d992f36a848ff4dc50ee6603e"
	},
	"ok" : 1
}
```

but if i query on bar it uses the index:
```
> db.test_Foo.find({ bar: 'zzz'}).explain()
{
	"queryPlanner" : {
		"plannerVersion" : 1,
		"namespace" : "parseServerMongoAdapterTestDatabase.test_Foo",
		"indexFilterSet" : false,
		"parsedQuery" : {
			"bar" : {
				"$eq" : "zzz"
			}
		},
		"winningPlan" : {
			"stage" : "FETCH",
			"inputStage" : {
				"stage" : "IXSCAN",
				"keyPattern" : {
					"bar" : 1,
					"baz" : -1
				},
				"indexName" : "bar_1_baz_-1",
				"isMultiKey" : false,
				"multiKeyPaths" : {
					"bar" : [ ],
					"baz" : [ ]
				},
				"isUnique" : false,
				"isSparse" : false,
				"isPartial" : false,
				"indexVersion" : 2,
				"direction" : "forward",
				"indexBounds" : {
					"bar" : [
						"[\"zzz\", \"zzz\"]"
					],
					"baz" : [
						"[MaxKey, MinKey]"
					]
				}
			}
		},
		"rejectedPlans" : [ ]
	},
	"serverInfo" : {
		"host" : "arthur-2501.sugarinc.com",
		"port" : 27017,
		"version" : "3.4.9",
		"gitVersion" : "876ebee8c7dd0e2d992f36a848ff4dc50ee6603e"
	},
	"ok" : 1
}
```

as I would expect.

so it's this behavior that makes me want to sort the query constraints.  my thinking is that since we store the query constraints in a javascript object, we can't ensure the order that we'll query.  and if that order changes, which appears to happen to me, then you (or I in this case) end up with permutations of query constraints that each require an index -- which seems bad to me for a number of more or less obvious reasons. 

Any thought or feedback?  thanks!!

**Comment by montymxb** [comment]
This is interesting, I can't say I'm very familiar with this behavior to begin with unfortunately. Like steven said above I don't believe the order of equality based constraints would effect the expected result, they're not codependent on each other (as far as I know). It's an all or none match, so that _should_ be ok.

Having to create individual indexes for each possible combination of parameters is not so great :/. Again I don't know much about how it handles this, but you would think it would be able to determine whether it matches by the individual elements in the query rather than their apparent order... I need to read up a bit on this to bring something more to the table here.

**Comment by acinader** [comment]
right, so if the order doesn't matter in the query itself, then sorting the constraints would be fine to ensure that we always present the constraints in the same order.  

and even if the order did matter, the current parse API doesn't guarantee the order, so sorting still seems ok -- or making the order guaranteed.  would seem like we should do one or the other, right?  I'm game to do the work, just trying to get educated on the options first ;).

**Comment by steven-supersolid** [comment]
What you've shown in your example is that the index order matters and you've used a prefix on the index in your second query: https://docs.mongodb.com/manual/core/index-compound/

If you were to use your existing index `{ bar: 1, baz: -1 }` but do the following queries then there should be no difference in explain (executionStats will give a bit more info):
`db.test_Foo.find({ bar: 'zzz', baz: 'zzz'}).explain('executionStats')`
`db.test_Foo.find({ baz: 'zzz', bar: 'zzz'}).explain('executionStats')`

So I would say that sorting the constraints won't have any positive impact, but it also won't have any negative impact on performance. It might confuse an advanced user who has written their query in a certain order and is parsing MongoDB logs for something in the same order.

I'm a bit wary about sorting as have experienced the pain of this on parse.com when there was a change to how nested object keys were sorted. I had assumed consistent ordering between reads and writes which I believe MongoDB does but that was not the case with Parse.
In mongoose they sorted keys for some micro-optimisation, then added an option to use natural ordering but now I see a mess of code to handle both options.
Of course these are a bit different to query sorting but the point is in one case developers assume even non-guaranteed things won't change and in the other the code could have been simpler.

Sorting seems like a good idea on the surface but we need to be wary of the consequences. Personally I would prefer that we did the work to guarantee the order instead. Have you considered that option?

**Comment by flovilmart** [comment]
I would agree with @steven-supersolid on that one, we should keep the order as present in the original REST query as much as possible, instead of sorting the keys. Thoughts?

**Comment by acinader** [comment]
Thanks for the thoughtful response @steven-supersolid.  learned something and i buy it.  closing.  i'll look at / think about the ordering of the constraints coming in.

**Comment by TylerBrock** [comment]
Yeah, the order of the clauses doesn't matter, what keys you match on / sort on does. Also the order direction of fields in a compound index matter.

An index on `{ bar: 1, baz: -1 }` can service queries on `{ bar: 1 }` (where ordering / matching of documents with respect to baz doesn't matter) and `{ bar: 1, baz: -1 }`
