### ISSUE TITLE
expected Object but got Bytes

### ISSUE THREAD

**Issue by adirgan** [parse-community/parse-server#4234]
### Issue Description

From the version of parse server 2.5.0 when I try to save a data type Bytes from android or ios I get an error from the corresponding client and the parse server logtrace returns me the same error.

probably this modification caused the problem in mongo [https://github.com/parse-community/parse-server/pull/3927](url)

### Steps to reproduce

**# Android code for reproduce error**

                int k1 = t[2] + myapp.KEY_DATA[0];
                int k2 = t[3] + myapp.KEY_DATA[1];
                int k3 = t[4] + myapp.KEY_DATA[2];
                int k4 = t[5] + myapp.KEY_DATA[3];
                byte[] bytes1 = ByteBuffer.allocate(4).putInt(k1).array();
                byte[] bytes2 = ByteBuffer.allocate(4).putInt(k2).array();
                byte[] bytes3 = ByteBuffer.allocate(4).putInt(k3).array();
                byte[] bytes4 = ByteBuffer.allocate(4).putInt(k4).array();
                final byte[] res = new byte[]{bytes1[3], bytes2[3], bytes3[3], bytes4[3]};
                final ParseObject user = current.getParseObject("user");
                final ParseObject code = new ParseObject("CodeAlarm");
                code.put("mac", name);
                code.put("code", res);
                user.fetchIfNeededInBackground(new GetCallback<ParseObject>() {
                    @Override
                    public void done(ParseObject object, ParseException e) {
                        if (e == null) {
                            final List<ParseObject> list = object.getList("codes");
                            if (list == null) {
                                List<ParseObject> list1 = new ArrayList<ParseObject>();
                                list1.add(list1.size(), code);
                                user.put("codes", list1);
                                user.saveEventually();
                            } else {
                                new Thread(new Runnable() {
                                    @Override
                                    public void run() {
                                        Boolean esta = false;
                                        for (int i = 0; i < list.size(); i++) {
                                            try {
                                                ParseObject object1 = list.get(i).fetch();
                                                if (object1.getString("mac").equals(name)) {
                                                    object1.put("code", res);
                                                    object1.saveEventually();
                                                    esta = true;
                                                }
                                            } catch (ParseException e1) {
                                                Crashlytics.logException(e1);
                                                e1.printStackTrace();
                                                Intent intent2 = new Intent(ERROR_SAVE_ALARM);
                                                sendBroadcast(intent2);
                                            }
                                            if (esta) {
                                                break;
                                            }
                                        }
                                        if (!esta) {
                                            list.add(list.size(), code);
                                            user.put("codes", list);
                                            user.saveEventually();
                                        }
                                    }
                                }).start();
                            }
                        } else {
                            Intent intent2 = new Intent(ERROR_SAVE_ALARM);
                            sendBroadcast(intent2);
                        }
                    }
                });

#### Expected Results

save the codes in bytes without any problem as it currently works since version 2.4.2 and smaller versions

#### Actual Outcome

`12|CarAlar | error: Error generating response. ParseError {
12|CarAlar |   code: 111,
12|CarAlar |   message: 'schema mismatch for CodeAlarm.code; expected Object but got Bytes' }           code=111, message=schema mismatch for CodeAlarm.code; expected Object but got Bytes
12|CarAlar | error: schema mismatch for CodeAlarm.code; expected Object but got Bytes code=111,    message=schema mismatch for CodeAlarm.code; expected Object but got Bytes
`

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.6.2
  - Operating System:     Ubuntu 14.04
  - Hardware:             VPS 4 Core, 8GB Ram
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Codero

- **Database**
  - MongoDB version: 3.4.1
  - Storage engine:  Memory
  - Hardware:        VPS 4 Core, 8GB Ram
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): Codero

### Logs/Trace

`12|CarAlar | error: Error generating response. ParseError {
12|CarAlar |   code: 111,
12|CarAlar |   message: 'schema mismatch for CodeAlarm.code; expected Object but got Bytes' }           code=111, message=schema mismatch for CodeAlarm.code; expected Object but got Bytes
12|CarAlar | error: schema mismatch for CodeAlarm.code; expected Object but got Bytes code=111,    message=schema mismatch for CodeAlarm.code; expected Object but got Bytes
`

**Comment by adirgan** [comment]
@flovilmart any way to fix this bug ?, it is too problematic for my service

**Comment by flovilmart** [comment]
schema mismatch for CodeAlarm.code; expected Object but got Bytes

Check your _Schema table in mongodb, seems that it's Object that's expected but you should replace it with Bytes for that key

**Comment by adirgan** [comment]
but in version 2.4.2 that I have now works perfect when I upgrade to 2.5.0 or else that problem starts @flovilmart

**Comment by flovilmart** [comment]
You asked me how to fix the issue, I propose a solution, Proper bytes support was added after the fact most probably between 2.4.2 and 2.5.0. So you can either stay on 2.4.2 or migrate / fix the issue in your DB so it will be working afterwards

**Comment by adirgan** [comment]
the _Schema table is effectively with that error, but as I change the data type, I have no knowledge of mongo to change it manually

{"_id": "CodeAlarm", "objectId": "string", "updatedAt": "date", "createdAt": "date", "mac": "string", "code": "object" name ":" string "}

the strange thing is that in 2.4.2 accepts that it is of type object, when updating no longer works in the same way, they should ensure that the old database works with new versions of parse server

**Comment by adirgan** [comment]
how to fix the problem in the database?

**Comment by flovilmart** [comment]
How I would got about it:
1- start a Parse-server (with latest) version on a dummy Db
2- compare the data stored in the new DB with the existing data on your prod DB
3- data is the same? All good just make the change on the schema (look at the mongodb docs) or through one of the many mongodb data viewer interfaces 
3- Data is different, well, now you need to migrate, post example of the differences there and we’ll see a solution.

**Comment by adirgan** [comment]
Ready and solve it, changing the data type in the table _SCHEMA of type "object" to type "bytes".

But that should not happen if you update parse server, should be contemplated to support if you come from a previous version.

In Parse Dashboard you have to update to add a column with data type Bytes

**Comment by flovilmart** [comment]
>  should be contemplated to support if you come from a previous version.

Sometimes bad things happen, this is open source, we do our best. In the meantime, if you feel there should be a proper way to upgrade the data, feel free to open a PR, and provide a migration for those in the same situation as you.

**Comment by adirgan** [comment]
@flovilmart  no matter how much they do very good work, thank you very much for your help.
