### ISSUE TITLE
MongoRock on AWS why 2 more volumes are needed

### ISSUE THREAD

**Issue by agwl-saurabh** [parse-community/parse-server#4236]
Hi,

I am creating a replica set of MongoRock (Percona Server for MongoDB 3.4). and planing to run main replica member on "t2.medium" or t2. large rest on t2.micro.

I am planing to have one primary and two secondary Replica Set Members.

I need info why MongoRock, need 3 volumes mount .  

I am referencing this document "http://docs.parseplatform.org/parse-server/guide/#using-mongodb--rocksdb" 

why we need below commends to run.

$ sudo mdadm —create /dev/md0 --level=stripe /dev/xvdb /dev/xvdc
$ sudo mkfs -t ext4 /dev/md0

My problem is my current DB size is 16 GB. so if I create replica set of i need  20GB x 3 voumes x 3 replica set = 200 to 250 GB approx space . which is to much 

mongoDB does not need 2 more node. is 3 node specific to rock Engine or parse specific.

and backup again take some GB.   can't all data can be stored on one default node.  so it will be easy replication please help.

**Comment by flovilmart** [comment]
According to the guide, the instances you're using are not the recommended ones for running MongoRocks. 

Also, you should probably head out to mongoRocks repo for help about that technology.

https://github.com/mongodb-partners/mongo-rocks
