### ISSUE TITLE
Memory usage increased ~100% after updating from Parse server 2.2.25 to 2.6.3

### ISSUE THREAD

**Issue by saulogt** [parse-community/parse-server#4238]
I updated to the newest version of parse server (2.2.25 -> 2.6.3) looking for bugfixes and possibly performance improvements. However, the memory usage increased about 100% from ~200MB to ~400MB and it seems to not decrease.

The current load is 50 requests per second. The response time and cpu load haven't changed.

![is-parse-server____metrics___heroku](https://user-images.githubusercontent.com/8147068/31254026-db3e11de-a9db-11e7-8feb-7442f7f942fe.png)

I expected to use the same amount of memory as before and even downgrade the dyno if it was more stable. Now I'm concerned about the peaks of load.

### Environment Setup

- **Server**
  - parse-server version: 2.6.3
  - NodeJS: 8.6.0
  - Hardware:             Heroku Standard 2X

- **Database**
  - MongoDB version: 3.0.12 
  - Storage engine: MMAPv1
  - Hardware:       Dedicated Cluster - mLab

**Comment by montymxb** [comment]
@saulogt What version of **node** are you using to run this?

**Comment by saulogt** [comment]
@montymxb it is nodejs 8.6.0. I just added this information to the original comment

**Comment by agwl-saurabh** [comment]
I am using below on AWS. with no issue. might be Node.js issue not 100% but as suggested by node team always use most used version not latest.
Node.js  6.11.3
 Parse Server  2.6.1
MongoRock 3.4 

Now updating to mongoDBreplica set but having issue with mongo. if you have any info about mongoDB please response to my below issue. Not sure if 3.2 mongo is better

https://github.com/parse-community/parse-server/issues/4236

**Comment by flovilmart** [comment]
That’s a good advice, we see various differences on node versions, from promise performance, to memory usage, I’m not sure where it comes from, but there’s no real need to ride on the latest version.

**Comment by flovilmart** [comment]
@saulogt did you try the revolution proposed in #4235, closing in favour of #4247

**Comment by saulogt** [comment]
@flovilmart It makes sense. I'm updating mongoDb to 2.4 first.
I'm gonna test this soon and post here the results

**Comment by flovilmart** [comment]
Try out with the enableSingleSchemaCache option, this should greatly improve your memory usage

**Comment by n-so** [comment]
@flovilmart 
I have the same issue when upgrading to parse server 3.x
Is there any other solution except from enableSingleSchemaCache:true?

**Comment by mtrezza** [comment]
@n-so can you provide more details about the environment you are running?

**Comment by n-so** [comment]
@mtrezza Thanks for your quick replay .
I posted an issue [#6061 ](https://github.com/parse-community/parse-server/issues/6061)
thanks.
