### ISSUE TITLE
Password contain # symbol not working with ParseRest API

### ISSUE THREAD

**Issue by sureshkoduri** [parse-community/parse-server#4250]
hi
When I am trying to login using Parse Rest API, If the password contains '#'symbol getting following exception.
error: Error generating response. ParseError { code: 101, message: 'Invalid username/password.' } code=101, message=Invalid username/password.

Thanks in Advance,
Suresh

**Comment by montymxb** [comment]
@sureshkoduri I'll double check this and let you know what I find.

**Comment by montymxb** [comment]
@sureshkoduri looked into this and I cannot replicate the issue mentioned. You didn't post any example code, but this is what I ran personally against a local instance.
```bash
# signup new user
curl -X POST \
  -H "X-Parse-Application-Id: app-id-here" \
  -H "X-Parse-Revocable-Session: 1" \
  -H "Content-Type: application/json" \
  -d '{"username":"standarduser","password":"#simplepassword#","phone":"415-392-0202"}' \
  http://localhost:1337/parse/users
```
and to login...
```bash
# login
curl -X GET \
  -H "X-Parse-Application-Id: app-id-here" \
  -H "X-Parse-Revocable-Session: 1" \
  -G \
  --data-urlencode 'username=standarduser' \
  --data-urlencode 'password=#simplepassword#' \
  http://localhost:1337/parse/login
```
Both appear to work just fine running against parse-server **2.6.2**. If you can follow up with a repeatable failure case we can look further into this. It seems more likely that the username/password combination you are using is incorrect. I'll close this for now, but if you follow up with details to show what's going on I'll open this back up!
