### ISSUE TITLE
Is there a work around to separate addField constraint for pointer permission

### ISSUE THREAD

**Issue by omar-bz** [parse-community/parse-server#4251]
may be you want take look at #4045.
because 4045 is inactive for a long time i opened a new one. it is critical, while a user in this case has privilege more then the admin it self, is there a work around this.

**Comment by flovilmart** [comment]
You can update the schema directly using the REST API. This is likely to be a limitation on the dashboard. Can you ping back if there’s an issue?

**Comment by bouzoumita** [comment]
i don't understand how to change the schema directly, when i get '/schemas/Test' for some test class i created i get something like this for the CLP:
```
"classLevelPermissions": {
        "find": {
            "requiresAuthentication": true,
            "*": true
        },
        "get": {
            "*": true
        },
        "create": {
            "requiresAuthentication": true
        },
        "update": {},
        "delete": {},
        "addField": {},
        "readUserFields": [
            "user"
        ],
        "writeUserFields": [
            "user"
        ]
    }
```
the user pointer has the hole write privilege specified with 'writeUserFields' and when i try 'addFieldUserFields' instead of 'writeUserFields' it gives an error.
Can you please help me with this

**Comment by flovilmart** [comment]
It should probably be in `addField` I'll have a look

**Comment by bouzoumita** [comment]
when put : 
```
{
"classLevelPermissions": {
        "find": {
            "requiresAuthentication": true,
            "*": true
        },
        "get": {
            "*": true
        },
        "create": {
            "requiresAuthentication": true
        },
        "update": {},
        "delete": {},
        "addField": {
           "user":true
        }
    }
}
```
it gives:
```
{
    "code": 107,
    "error": "'user' is not a valid key for class level permissions"
}
```

**Comment by flovilmart** [comment]
Ok thanks!

**Comment by alexander-alzate** [comment]
+1

**Comment by sunshineo** [comment]
![dashboard](https://user-images.githubusercontent.com/1072766/45788330-d140c300-bc2e-11e8-8b61-2bcb83c9fb8f.jpg)

I don't think it is a limitation for the dashboard. When I look at the database I see this
![mongo](https://user-images.githubusercontent.com/1072766/45788342-e584c000-bc2e-11e8-8501-16ea6a670058.jpg)

So the workaround would be have some cloud function code save specific user permission for each object beforeSave. I'm not sure yet, I'll be trying it.

**Comment by flovilmart** [comment]
It need to be implemented on the server as for now, pointer Permissions are blanket par missions for read or write, and don’t offer granular control over each detailed permission.
