### ISSUE TITLE
Important question regarding usage on Heroku

### ISSUE THREAD

**Issue by jcguarinpenaranda** [parse-community/parse-server#4253]
Hello, I have my Parse server running on Heroku and I have a doubt regarding multiple instances.

If I have let's say 5 instances running Parse Server, when a new Parse Object gets saved that will trigger beforeSave and afterSave on each of the 5 instances? or how does it know?

**Comment by agwl-saurabh** [comment]
you need to set up a loadbalncer on 5 server and let loadbalncer talk to your app and have condition on loadbalance lets say it x instance have 50 request/sec switch to other instance. so this is the job of loadbalncer

**Comment by jcguarinpenaranda** [comment]
Ohh ok I understand. I guess Heroku does this by default when having multiple dynos in the same project

**Comment by agwl-saurabh** [comment]
i never created anything on Heroku . but aws does this i know. and if you want you can try AWS button on parse server git to auto launch . and change the version of the server and ur done.

**Comment by rawrmaan** [comment]
Heroku does this by default.

**Comment by flovilmart** [comment]
Closing as properly answered! Thanks everyone!
