### ISSUE TITLE
Session gets destroyed on cloud code save User

### ISSUE THREAD

**Issue by jjdp** [parse-community/parse-server#4255]
I'm changing the username and password for internal purposes and then returning the data to the client. I also noticed that there is also no new session returned.

```
var user = new Parse.User();
user.id = userId;

user.set("username", username);
user.set("password", password);

return user.save(null, {useMasterKey: true});
```

Is this normal behavior?

**Comment by flovilmart** [comment]
you can pass `revokeSessionOnPasswordReset: false` to your options if you don't want the sessions to be revoked when resetting the password.

This is actually a security feature.
