### ISSUE TITLE
checkResetTokenValidity throws undefined

### ISSUE THREAD

**Issue by oallouch** [parse-community/parse-server#4267]
Hi,
The errors thrown from checkResetTokenValidity are undefined or lack codes (see UserController.js line 78).
That makes error treatment quite difficult.

Olivier

**Comment by flovilmart** [comment]
If the error is undefined, it means that no link exists, if the error is 'The password reset link has expired'. Errors could be indeed improved. Do you wanna work on a PR for that?

**Comment by dplewis** [comment]
Closing via https://github.com/parse-community/parse-server/pull/5332
