### ISSUE TITLE
Check if PFUser exists requires change of ACL?

### ISSUE THREAD

**Issue by trondkr** [parse-community/parse-server#4269]
FYI, I also asked this question on [SO](https://stackoverflow.com/questions/46850053/check-if-pfuser-exists-requires-change-of-acl). I have a Parse server setup that functions correctly. However, when I want to login a user, that originally signed up using password and username (email=username), using OAuth2 third party authentication (e.g. Google) I run into problems with ACL. First, to check if the username exists in the database I run the following Cloud function: 

    Parse.Cloud.define("usernameExists", function (request, response) {
        var query = new Parse.Query(Parse.User);
        query.equalTo("username", request.params.username);
    
        query.first
        ({
            useMasterKey: true,
            success: function(existingUser)
            {
                var acl = new Parse.ACL(existingUser);
                acl.setReadAccess(existingUser, true);
                acl.setWriteAccess(existingUser, true);
                acl.setPublicReadAccess(true);
                existingUser.setACL(acl);
    
                existingUser.save({}, {useMasterKey: true});
    
                response.success(existingUser);
            },
            error: function(error)
            {
                response.error("failed with error: " + error.message);
            }
        });
    });

The reason I run `acl.setPublicReadAccess(true);` is to enable the linking between the existing user and the OAath2 login work (called from macos app using Swift): 

     ob.linkWithAuthType(inBackground: provider, authData: authData).continue({ (task) -> Any? in
             
If I do not set the read access to **public**, the linking does not work. Afterwards I want to reset the permissions using the function
    
    Parse.Cloud.afterSave(Parse.User, function(req) {
        
        if (req.object.existed()) {
            var user = req.object;
            var acl = new Parse.ACL(user);
            acl.setWriteAccess(user, true);
            acl.setPublicReadAccess(false);
            user.setACL(acl);
            user.save(null, {useMasterKey: true}).then(function (s) {
                console.log('[afterSave succeeded]: ' + JSON.stringify(s));
            }, function (e) {
                console.log('[afterSave failed]: ' + JSON.stringify(e));
            })
        }
    
    });

Is this the correct way to do this? It seems unnecessary to change permissions like this, but I have not been able to make it function any other ways? The linking would not work otherwise.

The final PFUser object I am left with after this login provides the correct information for the user, but I am also unable to save or update the information. I receive error messages: 

> [Error]: Cannot modify user EkyHzthTOD. (Code: 206, Version: 1.15.3)

If anyone has suggestions for better login procedures for linking existing PFUsers using OAUth2 I would appreciate it (or if you see something is wrong in my current code).

**Comment by flovilmart** [comment]
@trondkr if your users is logged in from the client side, this should just work, as the sessionToken is sent out while you're asking for the linking operation.

Also, note that you can leverage Class Level Permissions, to disable the find operation on the _User table.

In any case, if your user is logged in on the client side, it's probably a bug.

Are you able to save any properties on the currentUser in the client?.

Can you provide logs when running with VERBOSE=1 running your linking?

**Comment by trondkr** [comment]
@flovilmart Your comments made me question whether I am doing it correctly. The login to Google, Github etc. is done, not on the client, but on the server. I do the OAuth2 flow (using Passport) on the server, and when successful login occurs I return the result to the client (opening up the app) and log in using the returned access_token. This works well with creating new users using OAuth2, but it fails when I try to link existing (password + username login) users to third part.

The output from doing the linking is minimal and basically says that the task completed=YES, but faulted=YES. And I get the information that I am not able to save user EkyHzthTOD... Could it be that the session token on the server side would be different from the session on the client side? Do you see way I could make this work? Thanks.
