### ISSUE TITLE
Parse Server - Image files' path returns localhost

### ISSUE THREAD

**Issue by Samigos** [parse-community/parse-server#4290]
I have deployed 2 Ubuntu servers on Azure. First, I have installed the Parse Server (2.6.3) and the second, I installed MongoDB. **(I have also put a ready db there from my previous server via `mongorestore`)**

Everything works fine! Both Parse Server and MongoDB server. They also communicate well. The thing is, when I run my iOS app, it brings all data correctly, except images. I print the URL of an image and here's what it returned: `http://localhost:1337/parse/files/filename.jpeg`

If I replace `localhost` with my server's ip, the image is being fetched nicely! 

Here's what I have on my `index.js`:

    var express = require('express');
    var ParseServer = require('parse-server').ParseServer;
    var ParseDashboard = require('parse-dashboard');
    var allowInsecureHTTP = true;
    var path = require('path');
    
    var databaseUri = process.env.DATABASE_URI || process.env.MONGODB_URI;
    
    if (!databaseUri) {
      console.log('DATABASE_URI not specified, falling back to localhost.');
    }
        
    var api = new ParseServer({
      databaseURI: databaseUri || 'mongodb://IP:27017/db',
      cloud: './cloud/main.js',
      appId: process.env.APP_ID || 'xxx',
      masterKey: process.env.MASTER_KEY || 'xxx', //Add your master key here. Keep it secret!
      fileKey: 'xxx',  
      serverURL: process.env.SERVER_URL || 'http://localhost:1337/parse',  // Don't forget to change to https if needed
    
      // Enable email verification
      verifyUserEmails: false,
    
      // The public URL of your app.
      // This will appear in the link that is used to verify email addresses and reset passwords.
      // Set the mount path as it is in serverURL
      publicServerURL: 'http://localhost:1337/parse',
    });
    
    // Client-keys like the javascript key or the .NET key are not necessary with parse-server
    // If you wish you require them, you can set them as options in the initialization above:
    // javascriptKey, restAPIKey, dotNetKey, clientKey
    
    var app = express();
    
    // Serve static assets from the /public folder
    app.use('/public', express.static(path.join(__dirname, '/public')));
    
    // Serve the Parse API on the /parse URL prefix
    var mountPath = process.env.PARSE_MOUNT || '/parse';
    app.use(mountPath, api);
    
    // Parse Server plays nicely with the rest of your web routes
    app.get('/', function(req, res) {
      res.status(200).send('Make sure to star the parse-server repo on GitHub!');
    });
    
    // There will be a test page available on the /test path of your server url
    // Remove this before launching your app
    app.get('/test', function(req, res) {
      res.sendFile(path.join(__dirname, '/public/test.html'));
    });
    
    var port = process.env.PORT || 1337;
    var httpServer = require('http').createServer(app);
    httpServer.listen(port, function() {
        console.log('parse-server-example running on port ' + port + '.');
    });
    
    // Set up parse dashboard
    var config = {
      "allowInsecureHTTP": true,
      "apps": [
        {
          "serverURL": "http://localhost:1337/parse",
          "appId": "xxx",
          "masterKey": "xxx",
          "appName": "name",
          "production": true
        }
      ],
      "users": [
        {
          "user":"username",
          "pass":"pass"
        }
      ]
    };
    
    var dashboard = new ParseDashboard(config, config.allowInsecureHTTP);
    var dashApp = express();
    
    // make the Parse Dashboard available at /dashboard
    dashApp.use('/dashboard', dashboard);  
    
    // Parse Server plays nicely with the rest of your web routes
    dashApp.get('/', function(req, res) {  
      res.status(200).send('Parse Dashboard App');
    });
    
    var httpServerDash = require('http').createServer(dashApp);  
    httpServerDash.listen(4040, function() {  
        console.log('dashboard-server running on port 4040.');
    });

One thing I noticed at Parse's documentation, is this: `When using files on Parse, you will need to use the publicServerURL option in your Parse Server config. This is the URL that files will be accessed from, so it should be a URL that resolves to your Parse Server. Make sure to include your mount point in this URL.`

The thing is that this documentation was written having in mind MongoDB, is on the same server with Parse, which in my case isn't.

Any ideas on what to do?

**Comment by flovilmart** [comment]
Which is exacly the point of the documentation. The publicServerURL is explicitely required for those cases. Parse server injects the publicServerURL for all your files at runtime, so they are not ‘stuck’ if you decide to change domain or provider.

**Comment by Samigos** [comment]
So what am I supposed to do in my case?

**Comment by flovilmart** [comment]
You’re supposed to see the publicServerURL which is the URL on which your parse-server is publicly accessible. (Https://my.domain.com/parse)

**Comment by Samigos** [comment]
And what about the URL of my images? How am I going to access them since they are on an remote MongoDB server, where there's no parse?

Remember, their path will remain `http://**localhost**:1337/parse/files/filename.jpeg `

**Comment by flovilmart** [comment]
As mentioned, the files uploaded through parse-server should always be stored with their relative path. Every file URL is replaced at runtime, with the full URL. If you set the publicServerURL this will be set in all the responses.

In you config, I see the publicServerURL is set to `http://localhost:1337/parse` try replacing it with the public URL.

**Comment by Samigos** [comment]
@flovilmart It worked! Thank you very much! You're a life saver! :)
