### ISSUE TITLE
E-Commerce Solution with Parse Server

### ISSUE THREAD

**Issue by 4vik** [parse-community/parse-server#4309]
Hello everyone,

I have been wondering, does anybody know of a third-party e-commerce marketplace solution for mobile apps, which uses Parse Server as its backend? For example for managing orders and transactions, product inventory, etc. I have only ever seen MySQL/NoSQL being used, but I was really curious if there is a Parse solution out there, as the rest of my app uses Parse for all its other backend functionality.

My app is written natively in iOS Swift and Android Studio (Java).

Thank you very much in advance for any useful advice!

**Comment by Sadmansamee** [comment]
Why not make of your own, it will be more flexible

**Comment by nbering** [comment]
Parse isn't really meant to be the backend for third-party redistributable apps like that. It's more of a rapid-prototyping framework that allows mobile app developers to get something going quickly without a lot of back-end work.

You *could* build an ecommerce solution on Parse, but much like the eCommerce platforms built on WordPress, I wouldn't necessarily think it's an ideal way to build a secure online store solution.

**Comment by flovilmart** [comment]
That being said, you can use Parse server as a base and build pretty much anything on the top of it.

**Comment by Sadmansamee** [comment]
@nbering I think it can be secured with proper ACL and CLP usage

**Comment by nbering** [comment]
Ya, I'm not saying you couldn't do it. I'm just saying if you want a boost to build something fast in the e-commerce space, look to something like Shopify. That's what it's built for. I'm sure there are other solutions out there as well.

**Comment by trylovetom** [comment]
We build e-commerce based on parse for user system core. Parse can let us build app fast. And we write another service in express for billing and paying. Parse is great, but it's not good choice for full e-commerce.

**Comment by montymxb** [comment]
Parse can work just fine as a backend and your base, but for billing/payments there are great services out there you can use from Stripe, Braintree, Square, etc. No reason why you couldn't build a platform using parse, or in anything else for that matter, and process your payments with a 3rd party.

**Comment by fmendoza** [comment]
Yeah I've build multiple e-commerce apps with Ionic/Parse Server and until now it's working just fine.

**Comment by montymxb** [comment]
Wondering if we should consider some sample/example projects on how get started doing something like this.

**Comment by Sadmansamee** [comment]
I'm building one too with parse server and for payment using Stripe.
