### ISSUE TITLE
How to make Unit Testing inside Parse Server

### ISSUE THREAD

**Issue by BenBenz** [parse-community/parse-server#4310]
How we can make unit testing with Parse, in each Cloud Code Function I have multiples query it is difficult to test actually,

How we can make unit test with Parse Query ?

**Comment by acinader** [comment]
My suggestion is to take a look at how unit testing is done on the parse-server repo itself.

https://github.com/parse-community/parse-server/blob/master/package.json#L75

is the command that runs the tests.  Which looks complicated, but basically its just invoking jasmine.

The jasmine config: https://github.com/parse-community/parse-server/blob/master/spec/support/jasmine.json

The helper.js that sets up and tears down the database and the parse-server:

https://github.com/parse-community/parse-server/blob/master/spec/helper.js

the helper has a lot of legacy code in it. 

And finally, here's an example of a test of cloud code:

https://github.com/parse-community/parse-server/blob/master/spec/CloudCode.spec.js#L79

**Comment by flovilmart** [comment]
There is also this test runner that we wrote:

https://github.com/AmpMe/parse-server-test-runner

**Comment by acinader** [comment]
look at that!  nice.

**Comment by flovilmart** [comment]
We use it extensively for everything, that's very nice to test e2e cloud functions etc...

**Comment by BenBenz** [comment]
Thank you for you answer, I'll take a look at this

**Comment by ZacharyKhan** [comment]
Just came across this, very interesting! How would I implement something like the Parse-Server-test-runner?

If I’m able to grasp it and get it working, I’d love to contribute to the README or WIKI with instructions for others to use this. I think it’s super useful!

**Comment by flovilmart** [comment]
Open an issue on the test runner if you need an example :)
