### ISSUE TITLE
2.6.5 not sending pushes, went back to 2.4.2, pushes are ok

### ISSUE THREAD

**Issue by dongalor** [parse-community/parse-server#4313]
### Issue Description

Updated to 2.6.5, pushes not working, i'm having problems with pushes:

Went back to 2.4.2:

`npm install parse-server@2.4.2 --save`

everything is working well

I've seen #4256, and I've seen this comment, which might be related to my problems:

> hey @flovilmart are you saying this will be updated in 2.6.4?
> @jeffreyjackson yes!

#### Expected Results

I'd like to have most recent version, cause I feel like lack of performance issues updates in last versions. 

### Environment Setup

- **Server**
  - parse-server version: 2.6.5
  - Operating System:    ubuntu16.04-x86_64

### Logs/Trace

```
0|parse-wr | verbose: _PushStatus n59yItvDR0: sending push to 1 installations
0|parse-wr | verbose: Sending push to 1
0|parse-wr | verbose: _PushStatus n59yItvDR0: sent push! 0 success, 1 failures
0|parse-wr | verbose: _PushStatus n59yItvDR0: needs cleanup devicesToRemove=[]
```

**Comment by flovilmart** [comment]
Can you provide your push configuration please?

**Comment by brianyyz** [comment]
Over on SO there is lots of chatter about APNS arbitrarily throttling delivery of data pushes and a new process DuetActivitySchedulerDaemon that can intercept a push notification that has been successfully delivered to your device and prevent it from being delivered to your appDelegate based on things like frequency of the silent notifications and battery state. 

I spent two days trying to figure out why my server's silent push notifications would mysteriously stop being received by my test devices until I restarted them. I haven't 100% verified that this is the cause but if you are using silent notifications to trigger activity you need to handle the use case that they could be throttled by APNS or blocked at the device which means your appDelegate may never see them.

**Comment by flovilmart** [comment]
What's bugging me is that the push adapter is not reporting/logging the error when sending the push. As you're running with VERBOSE=1, and the failure was related to APNS not being able to transmit, it should be logged. There isn't any other logs related to the parse-server-push-adapter? Can you try the same running the sever locally and targeting the push with your test device? (also, provide your push configuration please).

**Comment by dongalor** [comment]
I'm running with VERBOSE=1

My push configuration is:

push: {
        ios: {
            pfx: "/path/to/certs/file.p12",
            passphrase: "",
            bundleId: "com.company.AppName",
            production: true
        }
    },

I'll try running it locally, and report my results. Thank you in advance!

**Comment by brianyyz** [comment]
Small point not directly related bundleId is deprecated and replaced with topic.

**Comment by flovilmart** [comment]
@dongalor do you have some more logs for us?

**Comment by brianyyz** [comment]
@dongalor would you be able to share the code that is creating the push payload as well ?

**Comment by dongalor** [comment]
Here's my code, which I use to test my pushes: 
https://gist.github.com/dongalor/96d13ee1b0344d222f4a4caf899bd8ed

**Comment by flovilmart** [comment]
If you run the query on itself does it work?

**Comment by paulovitin** [comment]
I have the same problem here @dongalor.  What is the database you are using? 

My problem is because Im using Postgres. The 2.6.5 version support "expiration_interval" now. When we update the version, the column in _PushStatus is missing then, the push notification stops. I added the column manually and works now.

When schema change, we need a better option to solve problems like this.

**Comment by montymxb** [comment]
@paulovitin If that's the case using **2.6.3** would work, as the `expiration_interval` was introduced in **2.6.5** (2.6.4 has a [CLI bug](https://github.com/parse-community/parse-server/blob/master/CHANGELOG.md#265) in it but you could use that too). I would think that the schema would have been auto-updated on start though.

**Comment by paulovitin** [comment]
@montymxb we have a docker auto-redeploy, and the auto-updated for schema doesnt happened.

**Comment by montymxb** [comment]
I'll take a look and see if I can replicate this upgrade issue regarding `expiration_interval`.

**Comment by montymxb** [comment]
@paulovitin I can confirm that there is a Schema upgrade issue, but only in **postgres**. Mongodb looks to handle it properly. I'm going to open up a separate issue with further details on that specifically, including reproducability.

@dongalor if you're using postgres as your database it's possible that you're experiencing the same issue post-upgrade.

**Comment by dongalor** [comment]
@flovilmart > If you run the query on itself does it work? ie: does it return installations?
yes

@montymxb, @paulovitin
no, I'm using mongodb :( that's sad

**Comment by flovilmart** [comment]
Ok, I may have an idea, to be clear, your users hold the deviceTokens as well as the installation right?

**Comment by dongalor** [comment]
installationId? yes!

**Comment by flovilmart** [comment]
@dongalor the gist you provided don’t mention installationId at all, just matching on device token. 

Also, just a note on architecture, usually a user can have many installation, so I would recommend you set the user on the installation objects, instead of storing the installationId’s on the users.

**Comment by dongalor** [comment]
@flovilmart sorry, now I understand the question, do my users table hold installationId? No, but I have system table Installation, which is being filled automatically.

So, my users table doesn't hold installationId, but my users table hold deviceToken field.

**Comment by flovilmart** [comment]
Ok so the gist is correct, I'll have a look.

**Comment by flovilmart** [comment]
So far, I can pin point the issue in the push adapter, as everything in parse-server is going smooth. It is an issue with all your push’s, or just some?

**Comment by dongalor** [comment]
@flovilmart actually i've provided my gist (https://gist.github.com/dongalor/96d13ee1b0344d222f4a4caf899bd8ed), all other pushes use the same Push class, so none of them work (

**Comment by flovilmart** [comment]
Did you try sending a push through the dashboard?

**Comment by dongalor** [comment]
@flovilmart yeah, same result :(

**Comment by flovilmart** [comment]
Ok, the issue seem to lie in the push adapter itself, I need more time to investigate the issue.

**Comment by hopye** [comment]
if i go back to 2.4.2 , do i have to downgrade parse-dashboard as well to work well sending pushes throught it ?

npm install parse-server@2.4.2 --save

**Comment by dongalor** [comment]
@hopye actually this is the only command I used to downgrade parse without downgrading dashboard, I guess there's no need in additional actions

**Comment by promisenxu** [comment]
We are also having problems with push for 2.6.5. There are constant error messages from parse-push-adapter and push are sometime delayed rather significantly (a few hours). However, our users can still receive push notifications, both iOS and Android devices.

The errosr we get look like:

```
node-pre-gyp ERR! parse-server-push-adapter APNS VError: apn write failed: Not receiving Ping response after 150000 ms
node-pre-gyp ERR! parse-server-push-adapter APNS     at Stream.stream.on.err (/app/node_modules/parse-server/node_modules/apn/lib/client.js:105:21)
node-pre-gyp ERR! parse-server-push-adapter APNS     at emitOne (events.js:96:13)
node-pre-gyp ERR! parse-server-push-adapter APNS     at Stream.emit (events.js:188:7)
node-pre-gyp ERR! parse-server-push-adapter APNS     at _connection._streamIds.forEach (/app/node_modules/parse-server/node_modules/apn/lib/protocol/endpoint.js:155:16)
node-pre-gyp ERR! parse-server-push-adapter APNS     at Array.forEach (native)
node-pre-gyp ERR! parse-server-push-adapter APNS     at EventEmitter.close [as _close] (/app/node_modules/parse-server/node_modules/apn/lib/protocol/endpoint.js:139:33)
node-pre-gyp ERR! parse-server-push-adapter APNS     at emitOne (events.js:101:20)
node-pre-gyp ERR! parse-server-push-adapter APNS     at TLSSocket.emit (events.js:188:7)
node-pre-gyp ERR! parse-server-push-adapter APNS     at _handle.close (net.js:497:12)
node-pre-gyp ERR! parse-server-push-adapter APNS     at TCP.done [as _onclose] (_tls_wrap.js:332:7)
```

and

```
node-pre-gyp ERR! parse-server-push-adapter APNS  APNS error transmitting to device %s with error %s the_device_token { VError: apn write failed: Not receiving Ping response after 150000 ms
node-pre-gyp ERR! parse-server-push-adapter APNS     at Stream.stream.on.err (/app/node_modules/parse-server/node_modules/apn/lib/client.js:105:21)
node-pre-gyp ERR! parse-server-push-adapter APNS     at emitOne (events.js:96:13)
node-pre-gyp ERR! parse-server-push-adapter APNS     at Stream.emit (events.js:188:7)
node-pre-gyp ERR! parse-server-push-adapter APNS     at _connection._streamIds.forEach (/app/node_modules/parse-server/node_modules/apn/lib/protocol/endpoint.js:155:16)
node-pre-gyp ERR! parse-server-push-adapter APNS     at Array.forEach (native)
node-pre-gyp ERR! parse-server-push-adapter APNS     at EventEmitter.close [as _close] (/app/node_modules/parse-server/node_modules/apn/lib/protocol/endpoint.js:139:33)
node-pre-gyp ERR! parse-server-push-adapter APNS     at emitOne (events.js:101:20)
node-pre-gyp ERR! parse-server-push-adapter APNS     at TLSSocket.emit (events.js:188:7)
node-pre-gyp ERR! parse-server-push-adapter APNS     at _handle.close (net.js:497:12)
node-pre-gyp ERR! parse-server-push-adapter APNS     at TCP.done [as _onclose] (_tls_wrap.js:332:7)
```

**Comment by funkenstrahlen** [comment]
@promisenxu I also see this issue. Looks like a bug in `node-apn`. https://github.com/node-apn/node-apn/issues/583

**Comment by flovilmart** [comment]
@promisenxu so those are probably false positives, as the error occur but comes from the ping, not the delivery itself. 

I am tinkering with a workaround for that issue.

**Comment by gaodeng** [comment]
@dongalor @flovilmart 
you should check Installation.appIdentifier.
 https://github.com/parse-community/parse-server-push-adapter/blob/8cfc7fea2a405743f35c2b0b15c641f325ddda80/src/APNS.js#L237
```javascript
 _chooseProviders(appIdentifier) {
    // If the device we need to send to does not have appIdentifier, any provider could be a qualified provider
    /*if (!appIdentifier || appIdentifier === '') {
        return this.providers.map((provider) => provider.index);
    }*/

    // Otherwise we try to match the appIdentifier with topic on provider
    let qualifiedProviders = this.providers.filter((provider) => appIdentifier === provider.topic);

    if (qualifiedProviders.length > 0) {
      return qualifiedProviders;
    }

    // If qualifiedProviders empty, add all providers without topic
    return this.providers
      .filter((provider) => !provider.topic || provider.topic === '');
  }
```
I think it's related here. if Installation.appIdentifier is empty,this method will choose providers without topic.apprently,notification can't send without topic successfuly.

**Comment by dongalor** [comment]
so, parse looks like updated to 2.7.1, is it possible, that this issue is included in this update? Or this is only parse-push-adapter related?

**Comment by dongalor** [comment]
bump :) any news about pushes on new version?

**Comment by dongalor** [comment]
tried upgrading to 2.7.4 and still got no pushes :( what am i doing wrong?

**Comment by flovilmart** [comment]
how are your push configured?

**Comment by dongalor** [comment]
@flovilmart here is cut https://gist.github.com/dongalor/c1ed9443d37430dc729d6fdaab7513fa

**Comment by dongalor** [comment]
bump, sorry for bothering
i lack compound queries by objectId soooo much )

**Comment by flovilmart** [comment]
I have no idea what can be wrong. Are the queries properly returning the installations?

**Comment by brianyyz** [comment]
Could this be a prod versus dev APNS config ?

**Comment by hopye** [comment]
Hey brian,

What version are you using ? Please share config code anyways...

Lg

**Comment by brianyyz** [comment]
Here you go 

```
// Example express application adding the parse-server module to expose Parse
// compatible API routes.

var express = require('express');
var ParseServer = require('parse-server').ParseServer;
var path = require('path');

var databaseUri = process.env.DATABASE_URI || process.env.MONGODB_URI;

if (!databaseUri) {
  console.log('DATABASE_URI not specified, falling back to localhost.');
} 

var api = new ParseServer({
  databaseURI: databaseUri                        || 'mongodb://localhost:27017/dev',
  appId: process.env.APP_ID                       || 'myAppId',
  masterKey: process.env.MASTER_KEY               || '', 
  clientKey: process.env.CLIENT_KEY               || '', 
  restAPIKey: process.env.REST_API_KEY            || '', 
  cloud: process.env.CLOUD_CODE_MAIN              || __dirname + '/cloud/main.js',
  serverURL: process.env.SERVER_URL               || 'http://localhost:1337/parse',  
  publicServerURL: process.env.PUBLIC_SERVER_URL  || "http://localhost:1337/parse",
  appName: process.env.APP_NAME                   || "myAppName",
  userSensitiveFields: ["email"],
  allowClientClassCreation: process.env.ALLOW_CLIENT_CLASS_CREATION                 || false,
  verifyUserEmails: process.env.VERIFY_USER_EMAILS                                  || true,
  preventLoginWithUnverifiedEmail: process.env.PREVENT_LOGIN_WITH_UNVERIFIED_EMAIL  || false,
  verbose: process.env.VERBOSE                                                      || false,
  push: {
      ios: [
        {
          pfx: './certs/APNSProductionCertificate.p12',
          topic: 'edu.self.brianmacdonald.xxxxx',
          production: true
        },
        {
          pfx: './certs/APNSDevelopmentCertificate.p12',
          topic: 'edu.self.brianmacdonald.xxxxx',
          production: false
        }
      ]
    },
   // The email adapter
  emailAdapter: {
    module: 'parse-server-simple-mailgun-adapter',
    options: {
      // The address that your emails come from
      fromAddress: 'donotreply@xxxxxxxx.ca',
      // Your domain from mailgun.com
      domain: 'mg.xxxxxxxx.ca',
      // Your API key from mailgun.com
      apiKey: process.env.MAILGUN_PRIVATE_API_KEY     || 'myMailgunAPIKey'
    }
  }
});

var app = express();

// Serve the Parse API on the /parse URL prefix
var mountPath = process.env.PARSE_MOUNT || '/parse';
app.use(mountPath, api);

var port = process.env.PORT || 1337;
var httpServer = require('http').createServer(app);
httpServer.listen(port, function() {
    console.log('parse-server running on port ' + port + '.');
});

```

**Comment by flovilmart** [comment]
This could very well be a prod vs dev thing indeed. Do you have anything working at all? Dev certs to dev devices / prod cert to prod devices ?

**Comment by JacobJT** [comment]
I think it could also be a provisioning profile thing on iOS. If you're not signing the app with a provisioning profile that matches the certs, I don't think you get push notifications. I've found that lately Xcode makes me sign in again every 3 or so days, used to last a month+ before I switched to High Sierra.

**Comment by dongalor** [comment]
@brianyyz thanks for sharing config, the only difference with my config is empty passphrase in my config : ( 

@flovilmart thanks for reply, I don't have dev push configuration, actually I'm deploying code to production

@JacobJT thank you for your information, I've forwarded it to my IOS developers, signing might be an issue :)

maybe i can show you my config [index.js](https://gist.github.com/dongalor/1588f002e7b518a383f6586687d73195):

**Comment by dongalor** [comment]
Actually, I'm still unable to move to newer version :(

**Comment by flovilmart** [comment]
Did you try v3.0? At this point besides a bad configuration? We have no idea what’s wrong

**Comment by dongalor** [comment]
@flovilmart thank you, I'll try 3.0. 
Also, I've shown my configuration push cut:
https://gist.github.com/dongalor/c1ed9443d37430dc729d6fdaab7513fa

**Comment by brianyyz** [comment]
Maybe a long shot but looking at your config you have an absolute path specified for your certificate. On you hosted server is this a valid path? When ever I've used push on hosted servers e.g. Heroku I've used relative path like './certs/12345.p12' and I've never included passphrase.

**Comment by antonfire** [comment]
@dongalor Did you resolve this? I have the same issue

**Comment by brianyyz** [comment]
As mentioned above pushes are working for me on 3.0 both locally via ngrok and on remote Heroku server.

**Comment by funkenstrahlen** [comment]
I also see no issues with push notifications running the latest parse server release.

**Comment by dongalor** [comment]
@brianyyz yeah, i've tried using relative path, same story :( 
@antonfire still working on it, i need to solve this pretty soon though

I'm setting up 3.x.x branch, so I'll report if it's working there )

**Comment by dongalor** [comment]
Ok, I did 3.1.1 setup with bare configuration

here is index.js, which i launch my parse 3.1.1:
https://gist.github.com/dongalor/39ce1918bcf6c1eef3d5a137e4f092e9

here is my cloud function, I use to test pushes:
https://gist.github.com/dongalor/6dda14517778fecf3127f9d29fbe2a0c

here's log:

https://gist.github.com/dongalor/aa7f1d4807a575647fd7f25f88f2a856

Absolutely the same problem, so sad :(

**Comment by flovilmart** [comment]
@dongalor how are your installation objects created? Through the iOS SDK or manually?

Because all _Installation objects require a proper appIdentifier set so the push adapter can select the proper certificate / configuration to use to deliver the push. 

As mentioned here: https://github.com/parse-community/parse-server/issues/4313#issuecomment-352136108

**Comment by dongalor** [comment]
@flovimart Damn it, now I got it, we don't have appIdentifier in our Installation table, so, with parse 2.4.2 (which is sending pushes right now) we don't need apIdentifier, i guess :)

Is it possible to assign apIdentifier manually without IOS SDK?

**Comment by mman** [comment]
@dongalor Sure you can just fire up mongo cli and modify ``_Installation`` documents in your database to manually set ``appIdentifier``.

I'm deliberately not copy pasting any command to do it as this will be a massive (harmless) update, so I'd like you to understand what are you doing...

**Comment by dongalor** [comment]
@mman I have a development server, where I can do any dangerous stuff :)
So, I've made a small experiment, I've entered my appId from my parse's index.js file to every installation record and tried doing the same test push sending as [here](https://gist.github.com/dongalor/6dda14517778fecf3127f9d29fbe2a0c), what I've got in logs is:

`verbose: _PushStatus UgmAPHkeyG: sending push to installations with 1 batches
verbose: Sending push to 1
verbose: _PushStatus UgmAPHkeyG: sent push! 0 success, 1 failures
verbose: _PushStatus UgmAPHkeyG: needs cleanup devicesToRemove=[]`

**Comment by mman** [comment]
@dongalor Please try once again with ``VERBOSE_PARSE_SERVER_PUSH_ADAPTER=1`` environment variable set, you should get more detailed diagnostics in the log.

**Comment by dongalor** [comment]
@mman so, I run my parse 3.1.1 instance this way, without pm2 for test purposes:

`VERBOSE=1 VERBOSE_PARSE_SERVER_PUSH_ADAPTER=1 node index.js`

and I get this in my log:
```
verbose: RESPONSE from [POST] /parse/functions/testPush: {
  "response": {
    "result": true
  }
} result=true
verbose: REQUEST for [POST] /parse/push: {
  "where": {
    "deviceToken": {
      "$select": {
        "key": "deviceToken",
        "query": {
          "where": {
            "objectId": "3ePnw29d9C"
          },
          "className": "_User"
        }
      }
    }
  },
  "data": {
    "data": {
      "subscriberId": "xku6EHzzwD",
      "subscriberName": "Test Subscriber",
      "code": "3"
    },
    "alert": "Free hotdogs at the Parse concession stand!"
  }
} method=POST, url=/parse/push, user-agent=node-XMLHttpRequest, Parse/js2.1.0 (NodeJS 11.2.0), accept=*/*, content-type=text/plain, host=localhost:1339, content-length=404, connection=close, key=deviceToken, objectId=3ePnw29d9C, className=_User, subscriberId=xku6EHzzwD, subscriberName=Test Subscriber, code=3, alert=Free hotdogs at the Parse concession stand!
verbose: RESPONSE from [POST] /parse/push: {
  "headers": {
    "X-Parse-Push-Status-Id": "GsEETYJSAd"
  },
  "response": {
    "result": true
  }
} X-Parse-Push-Status-Id=GsEETYJSAd, result=true
verbose: _PushStatus GsEETYJSAd: sending push to installations with 1 batches
verbose: Sending push to 1
verbose: _PushStatus GsEETYJSAd: sent push! 0 success, 1 failures
verbose: _PushStatus GsEETYJSAd: needs cleanup devicesToRemove=[]
```

**Comment by antonfire** [comment]
Add a column in your installation class with the name appIdentifier and the type string. Then populate all your existing installation objects with your app id eg com.blahblah. Then try sending again

**Comment by antonfire** [comment]
Will need to ensure new installation objects are populated with this field on push registration client side

**Comment by flovilmart** [comment]
One could as well make a fix in the adapter.

**Comment by antonfire** [comment]
I would suggest removing the appIdentifier as a requirement in the installation class as this is specified in the push adaptor settings in index.js. I can have a look at a pull request for this if that would help?

**Comment by flovilmart** [comment]
That certainly would help

**Comment by antonfire** [comment]
Ok I’ll get on it

**Comment by brianyyz** [comment]
@antonfire are you thinking that this would be an either / or approach (look for appIdentifier first and if absent use push adapter settings from index.js) or just ignore the appIdentifier in Installation and rely solely on config from index.js?

**Comment by flovilmart** [comment]
That’s not that simple, if the installation does not specify an app identifier and multiple are configured, the adapter need to retry. In any case you should also fix your clients so they return a proper appIdentifiwe.

**Comment by brianyyz** [comment]
@flovilmart that is where I was headed. This starts to feel like it would be breaking away from the way that the sdks behave.

**Comment by flovilmart** [comment]
Initially, the fact that we didn’t take into account the appIdentifier was a bug.

**Comment by antonfire** [comment]
Not everyone uses the sdk to register push, a waterfall approach would be best to prevent breaking changes for users that haven’t upgraded or installed since the breaking change

**Comment by flovilmart** [comment]
@antonfire I am not sure where you’re getting at. The spec in the rest documentation has always been to pass an appIdentifier. That the server before 2.6 was permissive was a bug on the server. 

If you feel any of this is wrong, this is an opensource project, so you know what to do.

**Comment by dongalor** [comment]
@antonfire Oh My God! Now, when I'm using topic/bundleId value in my test user Installation record, I have an error! I think we are very close to beat this problem of my. Thank you so much in advance, guys!

Here's what log says:

```
verbose: _PushStatus 7GzcpE2zDK: sending push to installations with 1 batches
verbose: Sending push to 1
ERR! parse-server-push-adapter APNS APNS error transmitting to device 5083c519e51624bd6e1ff3dca9c1dac8afce4433190319d71e2015876e0bb922 with status 400 and reason BadDeviceToken
verbose: _PushStatus 7GzcpE2zDK: sent push! 0 success, 1 failures
verbose: _PushStatus 7GzcpE2zDK: needs cleanup devicesToRemove=[5083c519e51624bd6e1ff3dca9c1dac8afce4433190319d71e2015876e0bb922]
```

**Comment by flovilmart** [comment]
That’s likely because the token is invalid

**Comment by mman** [comment]
@dongalor Error 400 happens when you try to send push from parse server using a production certificate or token to a debug build of your app, IOW the push token of your app is a one that is valid for sandbox. servers.

**Comment by antonfire** [comment]
@dongalor Set up like this so works on production and development:

push: {
      ios: [
      {
        pfx: 'PushDevCert.p12',
        topic: 'com.xxxxxx.xxxxx',
        production: false
      },
      {
        pfx: 'PushDistCert.p12',
        topic: 'com.xxxxxx.xxxxx',
        production: true
      }]

}

**Comment by antonfire** [comment]
@flovilmart @brianyyz I was just thinking of a fallback to the bundle id where appIdentifier is undefined

**Comment by brianyyz** [comment]
@dongalor (going all the way back to the beginning)  In your AppDelegate are you saving the device token that returns in didRegisterForRemoteNotifications to the device Installation before sending a push to the device? The last updated time stamp on the Installation should get updated if you are.

**Comment by flovilmart** [comment]
Glad to hear. Also the issue is on the push adapter, so it won’t be fixed in this version of parse-server

**Comment by brianyyz** [comment]
Excellent news!

**Comment by dongalor** [comment]
@flovilmart got it, right :) 
@brianyyz 👍
