### ISSUE TITLE
Check out this module for Parse.Cloud

### ISSUE THREAD

**Issue by jcguarinpenaranda** [parse-community/parse-server#4317]
Hello,

First I want to thank all the community for being so active, and the people who are working so we can have new versions of `parse-server`. 

I have been working with `parse-server` some time after Parse announced they were not going to continue, and I want to share with you a module I created for being able to manage more easily the Cloud Code. It is called __ParseCloudClass__ and you can see it [here](https://github.com/owsas/parse-cloud-class)

## The module

With `parse-cloud-class` module you can easily:

* Define minimum values for keys on your classes
* Define default values
* Define required keys
* Use addons to easily extend the funcionality of your app
* Create new addons and share them with the community
* Customize the default behaviour to your own needs

The usage is very simple, like this:
```js
// cloud/main.js
// with typescript or ES6
import { ParseCloudClass } from 'parse-cloud-class';

const myConfig = new ParseCloudClass({
  // new items will not be created if they have no 'name' set
  requiredKeys: ['name']
  defaultValues: {
    // all new items will have by default active: true
    active: true,
    // by default, timesShared will be 0
    timesShared: 0,
  },
  minimumValues: {
    // timesShared cannot go below 0
    timesShared: 0,
  }
});

// Configure your class to use the configuration
ParseCloudClass.configureClass(Parse, 'MyClass', myConfig);
```

## A word on the addons

I think being able to use other community-made scripts for `parse-server` would be something very nice to have, and would continue to make our life easier as developers. 

In this way, using __ParseCloudClass__ I think we could have in the future some modules to connect the data with some Analytics service like __Mixpanel__, or with other services such as __Algolia__; or even having a replication plugin that syncs the data with __DynamoDB__ or any other database.

The only thing needed, would be that the new module implements `afterSave` or `afterDelete` (there are more functions)

## Note
I am posting this here because I think somebody else would like to easily configure the Parse Cloud classes with this basic functionality, or extend it in the future.

**Comment by flovilmart** [comment]
That’s a Neat little project you got here! I was thinking about discovery of such ‘addons’ / community packages, and that would be nice if published as: parse-server-addon-YOUR_PACKAGE_NAME

what do you think?

**Comment by jcguarinpenaranda** [comment]
Very nice!

Right now it is published as `parse-cloud-class`, but I can move it to `parse-server-addon-cloud-class`

**Comment by jcguarinpenaranda** [comment]
Now it is changed, and available in npm as `parse-server-addon-cloud-class`. I will be working on other addon for Algolia

**Comment by flovilmart** [comment]
Awesome! That will probably help discovery! I’ll check with others if we wanna move adapters to the same pattern parse-server-adapter-*.

**Comment by jcguarinpenaranda** [comment]
As promised, I did the Algolia addon I was talking about:
https://github.com/owsas/parse-server-addon-cloud-algolia

It is available in npm as `parse-server-addon-cloud-class-algolia` :) and keeps in sync the data between Algolia and the PostgreSQL or MongoDB database you use in `parse-server`

**Comment by flovilmart** [comment]
Pretty cool! I’ll make a PR on the README, so other users know about this new convention for community packages discovery.

**Comment by jcguarinpenaranda** [comment]
Can you please post these repos to parse-server-modules ?

**Comment by flovilmart** [comment]
What do you mean by that?

**Comment by jcguarinpenaranda** [comment]
I see that in that account or repository you have linked several adapters for parse-server. Community made addons can appear there?

**Comment by flovilmart** [comment]
Those are not linked. This organization was created when Parse-server was still under facebook’s management and for official adapters/reference implementations. Now, while your addons are quite useful in certain scenarios, I don’t believe they should live under this organization as it would form some kind of endorsement / official support. We have our hands pretty busy already, and i was actually thinking moving most of the official adapters back to parse-Community instead of parse-server-modules.

**Comment by jcguarinpenaranda** [comment]
Ohh I understand, I thought it was a list of repositories that would work
with parse-server, made by the community. Thank you!


2017-11-05 9:24 GMT-05:00 Florent Vilmart <notifications@github.com>:

**Comment by tejpratap46** [comment]
We can do a **Awesome Parse Server** list.
