### ISSUE TITLE
API: /parse/users/me is not working returns 404 error code.

### ISSUE THREAD

**Issue by yog27ray** [parse-community/parse-server#4347]
I was trying to login user by using ParseUser.becomeInBackground($sessionToken) from android device. On my server logs I received and error `GET /parse/users/me 404`.

Currently I am using ParseServer 2.6.5

**Comment by faladinojames** [comment]
Are you sure the sessionToken is valid?

**Comment by yog27ray** [comment]
Yes I was able to fetch data from the same sessionToken. Except for api starting with "/parse/users" rest off the apis are working.
