### ISSUE TITLE
Security Questions for Insallation and Session

### ISSUE THREAD

**Issue by jjdp** [parse-community/parse-server#4356]
1. I'm setting all count clps to {} for all my classes since we don't need it. On the _Installation Class, are there any side effects on parse-server's side? Like for example notifications.

2. Are there any side effects on parse-server if I set all clp to {} on the _Session Class

**Comment by flovilmart** [comment]
You may have side effects if you set CLP’s on sessions, while I’m not sure which, they are secured by ACL’s and additional checks.

On installations, you need clients to be able to write to installations for push to be working properly. Find operations are disabled. See the docs for more info, in the security sections.

Also, we can’t guarantee thAt your CLP’s won’t interfere with what you expect in the SDK’s, if you prevent installation / session creation, from CLP, there’s a high chance logins, signups and push’s won’t be functional.
