### ISSUE TITLE
Mailgun Adapter Not Sending Emails

### ISSUE THREAD

**Issue by fprospato** [parse-community/parse-server#4360]
Hello,
I set up my parse server for my iOS project using AWS with Bitnami. I added this to my server.js file:
```
verifyUserEmails: true,
publicServerURL: 'https://ec2../parse',
appName: 'name',
emailAdapter: {
module: 'parse-server-simple-mailgun-adapter',
options: {
fromAddress: ADDRESS',
domain: 'DOMAIN',
apiKey: 'KEY'
```
I thought that this was it, but when I sign up a user or try to reset a password, I do not get an email. The address, domain, and api key are all correct. I saw that somehow we are suppose to install the adapter through 'npm'. I have never installed something with npm before and do not know how to. I get access to my server through connecting to my instance by launching my SSH Client. How do I go from there to just add/install `npm i parse-server-mailgun` properly? 

I have been working on this mailgun integration for months and I am in desperate need for help. So if anyone can give me any help I will be forever grateful!

**Comment by montymxb** [comment]
@fprospato check out the [docs](https://docs.npmjs.com/getting-started/what-is-npm) for npm to see how to use it properly. Once you get the feel for it you may find it super handy 👍 .

**Comment by thomascoope** [comment]
@fprospato you might find this Udemy course worthwhile as it walks you through it: https://www.udemy.com/parse-server/learn/v4/overview

We built ours successfully using the instructions on here.
