### ISSUE TITLE
Possible Vulnerability in ws

### ISSUE THREAD

**Issue by pranjalsatija** [parse-community/parse-server#4374]
After running `nsp check` on my Parse Server project, I found that the `ws` module has a possible vulnerability that's been covered by the NSP. Versions of `ws` under 3.3.1 are vulnerable to DoS attacks. The full report is available [here](https://nodesecurity.io/advisories/550).

I'm not a security expert by any means, and it's totally possible that this vulnerability doesn't affect Parse Server, but is it something worth looking into? If so, I'd be happy to submit a PR.

**Comment by flovilmart** [comment]
Thanks for reporting the issue, current master is using [3.3.1](https://github.com/parse-community/parse-server/blob/master/package.json#L45), we'll craft a release soon.
We also have [NSP running on CI](https://github.com/parse-community/parse-server/blob/master/.travis.yml#L54), daily that would report any additional security errors.
