### ISSUE TITLE
Updating User With JS SDK (Notes in guide)

### ISSUE THREAD

**Issue by MakerManTom** [parse-community/parse-server#4376]
I've been Googling about & I'm unsure whether or not users can or cannot be updated using the Javascript SDK.  I've noticed that the guide is distinctly lacking the subject (along with deleting the user), but instructions are present for the REST API.

Would anyone confirm whether or not this is possible & how?  If it is, shall I write an update to the guide?

**Comment by addisonElliott** [comment]
A user is an object basically. There is a sentence in the guide that says this but it is not emphasized enough in my opinion. 

Correct me if I'm wrong, but you should be able to treat the user as an object, modify fields and then call save. Look at the section saving objects.

**Comment by montymxb** [comment]
@thomascoope You can treat a user like any other parse object in terms of saving, deleting, etc. But you'll have to respect object level ACLs. Unless you're using the **master key** changes will have to be done to a user by that same user.

**Comment by flovilmart** [comment]
Also, additional restrictions apply on the users, as described in the docs.

**Comment by thomascoope** [comment]
OK.  I'll have a tinker now treating the user as an object.  As per @addisonElliott it could probably be clearer for less than competent users like myself so I'll suggest an edit if I get it working.

**Comment by addisonElliott** [comment]
@thomascoope That's a great idea. 

A bit unrelated but maybe we should consider any examples section in the documentation to do some of these things. I think this may be easier to understand and easier to write than the typical paragraph explanations.

**Comment by thomascoope** [comment]
@addisonElliott I'll give an example with it.

**Comment by montymxb** [comment]
We used to have some awesome tutorial projects. Unfortunately we did not keep this when migrating to the community organization that exists now. It's a lot to ask for, considering all the sdks, but it would be fantastic if we started writing some new ones back in at some point.
