### ISSUE TITLE
can we use parse with react-native?

### ISSUE THREAD

**Issue by ehaanfaaz** [parse-community/parse-server#4379]
Can we use parse with parse-server with react-native?
if not then any other for react-native similar to parse-server

**Comment by flovilmart** [comment]
There’s nothing that prevents you from using any client technology with parse-server. We provide SDK’s for many clients, iOS, Android, JavaScript etc... the JS SDK is fully compatible with react-native.

**Comment by ehaanfaaz** [comment]
how can we implement it with react-native?

**Comment by flovilmart** [comment]
I’m not sure what you mean by that. Did you read the README in this repository as well as the docs on http://docs.parseplatform.org ? If your question is about integrating the JS SDK into a react native app, you can open a question on stackoverflow where experts may be able to help you. 

Parse-server is a server technology, not a client one. Clients can interact with parse-server through the rest api, or any official SDK.

**Comment by ehaanfaaz** [comment]
okay thanku @flovilmart
