### ISSUE TITLE
possible bug creating new File

### ISSUE THREAD

**Issue by lucamorelli** [parse-community/parse-server#4388]
### Issue Description

I'm trying to upload a video file from a cordova app client using this code

```
        function saveFile(filename, base64) {
            var imgFile = new Parse.File(filename, {
                base64: base64
            })
            $log.log('saving file ' + filename)
            return imgFile.save()
        }
```
this code works uploading files, but fails sending a video, where I have a base 64 string starting with `data:video/mp4;base64,AAAAGGZ0eXBtcDQyAA`.
I checked the code and I think I found the problem
this is the regexp that extract the file content
`var dataUriRegexp = /^data:([a-zA-Z]*\/[a-zA-Z+.-]*);(charset=[a-zA-Z0-9\-\/\s]*,)?base64,/;`
here tries to extract the content type from the datastring

```
          var matches = dataUriRegexp.exec(_base.slice(0, commaIndex + 1));
          // if data URI with type and charset, there will be 4 matches.
          this._source = {
            format: 'base64',
            base64: _base.slice(commaIndex + 1),
            type: matches[1]
          };
```
this control fails when the content type contains a number like **mp4**, and the **matches** array is null
changing the regexp to

`var dataUriRegexp = /^data:([a-zA-Z]*\/[a-zA-Z0-9+.-]*);(charset=[a-zA-Z0-9\-\/\s]*,)?base64,/;`
seems to work

### Steps to reproduce

try to create a un file object using the filename, and a full base64 data string containing a content type with a number like video/mp4

#### Expected Results

to be able to save file with this content type

#### Actual Outcome
error evaluting the matchs array because is null

**Comment by paulovitin** [comment]
What version of parse-server?

**Comment by lucamorelli** [comment]
latest version, the packages of the app are updated

**Comment by paulovitin** [comment]
You need to remove the "data:video/mp4;base64,".

Check the docs http://docs.parseplatform.org/js/guide/#files

**Comment by lucamorelli** [comment]
I see two constructor in the File class: one accept the filename and all the data as base64 string, and this works correctly with jpg, png files and so, and another where I can remove this part but I have to send the content type as third param. I already made this change as a workaround, but I don't understand why the first constructor works with just some content type giving this unclear error message

**Comment by paulovitin** [comment]
Maybe @flovilmart can be give to you a better response.

**Comment by montymxb** [comment]
@lucamorelli that looks about right. I _swear_ I've seen this somewhere else in one of the sdks as well, in terms of a regex parsing a content-type and not expecting a digit in the second half. Can you provide a link to where this is in the server so I can take a look?

**Comment by lucamorelli** [comment]
This is the line where the regexp is declared

https://github.com/parse-community/Parse-SDK-JS/blob/942305ab9bcc1df1707eb0a1154f1041a10c4fde/src/ParseFile.js#L28

and here where I have the problem

https://github.com/parse-community/Parse-SDK-JS/blob/942305ab9bcc1df1707eb0a1154f1041a10c4fde/src/ParseFile.js#L108

**Comment by flovilmart** [comment]
It’s in the JS SDK, please open an issue on this project instead. 

Thanks!

**Comment by montymxb** [comment]
@lucamorelli I went ahead and opened up #517 in the JS sdk regarding this so we can address it there.
