### ISSUE TITLE
question: is this session behaviour correct in 2.4.2

### ISSUE THREAD

**Issue by dongalor** [parse-community/parse-server#4391]
Trying to understand session behaviour, so correct me if I'm wrong, but it's kinda weird:

### Workflow
I have cloud function for logging in:
https://gist.github.com/dongalor/81348114f9256c567680138217b1a284 

### I run it to authorize my user
curl -X "POST" "http://example.com:1337/parse/functions/signIn" \
     -H 'X-Parse-Application-Id: APPID' \
     -H 'Content-Type: application/json' \
     -d $'{
  "email": "user@example.com",
  "password": "PASSWORD"
}'

### I have test cloud function trueCurrent

https://gist.github.com/dongalor/d87232abb451fbb03e4becc07035dc05

### I ssh to some other host (random host) then I run curl there:
curl -X "POST" "http://example.com:1337/parse/functions/trueCurrent" \
     -H 'X-Parse-Application-Id: APPID' \
     -H 'Content-Type: application/json' \
     -d $'{}'

Voila, I have my logged user from my local machine.

Is this correct? What am I doing wrong?

**Comment by flovilmart** [comment]
What version of parse-server are you using? Parse.User.current() should not be used server side. Have a look at the documentation and in particular the getting started guide on docs.parseplatform.org.

**Comment by dongalor** [comment]
@flovilmart wow, my mistake :( due to this issue #4313, I'm using 2.4.2 at this moment. So, I can't use Parse.User.current() server-side?

**Comment by addisonElliott** [comment]
@dongalor No you cannot since there is no session that is saved server-side. It is saved client-side (although this gets a bit murky in the case of PHP SDK). Regardless, Parse.User.current() is meant to get the current user for a client SDK.

Look at this code if you want an example of how to get the user who sent the request:
https://gist.github.com/addisonElliott/9baafffe970270a3fdea0acc620f6d49

**Comment by dongalor** [comment]
@addisonElliott thank you so much! 
But I'll ask one more question, if you don't mind ) 
So, what if I'm not using X-Parse-Session-Token header? I won't have request.user object, right?
So, there is Parse.User.become(sessionToken) way, is it the only option?

thank you in advance!

**Comment by addisonElliott** [comment]
No problem, happy to help. 

The X-Parse-Session-Token header is how you authenticate that you are who you are to the parse server. If you don't send that token, then you're correct that request.user will be null.

`Parse.User.become(sessionToken)` is meant for client side use. In broad terms, it saves the session token given and then it will start sending it in the X-Parse-Session-Token header.

All of the SDKs should use the header token and so I wouldn't mess with it. The parse server will handle authenticating the user for you.

**Comment by addisonElliott** [comment]
Since this has been resolved, do you mind closing this issue?

**Comment by dongalor** [comment]
@addisonElliott thank you for your time, I appreciate that so much! Actually, it won't be too difficult to change my authentication mechanism in IOS app by adding parse headers. 

And what is funny, my app without headers uses Parse.User.current() and Parse.User.become() server-wise, with unusual behaviour, but still somehow most of processes work fine, not all, but most )
