### ISSUE TITLE
Push Notifications guide requires updating

### ISSUE THREAD

**Issue by majd-kho** [parse-community/parse-server#4392]
I am implementing push notifications for android and using parse-server obviously, however Google is moving on from GCM to FCM. 

I was checking the guide http://docs.parseplatform.org/parse-server/guide/#push-notifications
and It seems to be addressing GCM only.
Also, this issue https://github.com/parse-community/parse-server-push-adapter/issues/32  does address the topic, but im wondering if anyone is going to update the guide so we can get a clear understanding of the process and what should be done.

Thanks!

**Comment by flovilmart** [comment]
GCM and FCM are one and the same, the backend / API's / credentials are the same. Everything should work as described in the documentation. If you encounter an issue configuring for Android, please open an issue in [push adapter repository](https://github.com/parse-community/parse-server-push-adapter) as it's a separate project from parse-server
