### ISSUE TITLE
code 209 invalid session token

### ISSUE THREAD

**Issue by akshaychauhan7737** [parse-community/parse-server#4395]
i am trying to authenticate session token and fetching user detaild but there is no information about how to do it at : http://docs.parseplatform.org/js/guide/#users 
I tried to google it now i got some code but don't know whether the are correct they are not working for me
```
 var Session = Parse.Object.extend("_Session");
    var sq = new Parse.Query(Session);
    sq.equalTo('sessionToken', userSessionToken)
    sq.include('user');
    console.log(sq);
    sq.find({
        success: function (sessionResult) {
            if (sessionResult.length == 0) {
                //user not found
            } else {
               //user found
            }
        },
        error: function (error) {  console.log(error); callback(false) }
    });
```

always giving me error

```
ParseError { code: 209, message: 'This session token is invalid.' }
```

**Comment by flovilmart** [comment]
If you want to login as a user from a sessionToken you can use Parse.User.become()

**Comment by natanrolnik** [comment]
Another option is to pass `userSessionToken` as the `sessionToken` parameter in the options:

```
sq.find({
    sessionToken: userSessionToken,
    success...
```
