### ISSUE TITLE
Cannot Run parse-server

### ISSUE THREAD

**Issue by nubu** [parse-community/parse-server#4397]
Hey guys,

just pulled the newest version to my local drive and after npm install, I want to start the parse-server...

Always getting this error:

/usr/local/lib/node_modules/parse-server/lib/ParseServer.js:124
    const {
          ^

SyntaxError: Unexpected token {
and so on ...

Any idea about this? Am I missing something?

Best Nico

**Comment by addisonElliott** [comment]
A few suggestions that may be the issue. First, what is your node version? You can type `node -v` to get the version. As of 2.7.0, the minimum node version is 6.11.4.

**Comment by nubu** [comment]
Hmm you are right, it only was the node version - Thanks for that. *uhh*
