### ISSUE TITLE
ignore invalid relation datatype objectId

### ISSUE THREAD

**Issue by faysal515** [parse-community/parse-server#4408]
### Issue Description

Parse doesn't throw any error when a relation data type input(objectId) is invalid.

### Steps to reproduce

Create 2 class lets say ABC and XYZ. in ABC's column, make a column `xyz` of Relation type class `XYZ`. now in the rest api, if try to put something like this in the `POST` method to insert any entry in `ABC` class like this

```
"xyz": {
      "objects": [
        {
          "objectId": "cxGAXNberx", // invalid objectId
          "className": "XYZ",
          "__type": "Pointer"
        }
      ],
      "__op": "AddRelation"
    }
```

#### Expected Results

It should throw an Error and prevent to insert the document/object claiming object not found.

#### Actual Outcome

The object gets created. The relation doesn't get created as the objectId was invalid

### Environment Setup

- **Server**
  - parse-server version : 2.6.3
  - Operating System:     macOS Sierra
  - Hardware:             core i5
  - Localhost or remote server? : localhost

- **Database**
  - MongoDB version: 3.4.9
  - Storage engine:  not sure/ default
  - Hardware:        core i5
  - Localhost or remote server? : localhost

### Logs/Trace

Include all relevant logs. You can turn on additional logging by configuring VERBOSE=1 in your environment.

**Comment by flovilmart** [comment]
While in practice this would be nice, this will impact the performance of everyone ensuring from another method that the objectId exists. I’m open for reviewing a PR that would address those needs.

**Comment by milesrichardson** [comment]
If the relation doesn't get created because the objectId is invalid, doesn't that imply that the code for adding relations is already checking if the objectId is valid?

**Comment by addisonElliott** [comment]
I agree with @flovilmart that this would impact the performance greatly. Parse does not check pointers and their object IDs for validity before saving to database. Most of the time the objectId comes from an object that was previously fetched from the database and hence can be ensured to be a valid object in most cases.

I think the better approach would be to check that the object is valid before adding it to another object. This can be done via `object.fetch()` and it will throw an error if it does not exist.
