### ISSUE TITLE
is Parse Server support desktop game?

### ISSUE THREAD

**Issue by buhuehue** [parse-community/parse-server#4416]
i wanna create a Desktop(not browser based) FPS game by using Unity3D. usually im using firebase but firebase not support desktop. So is parse server support desktop game?

**Comment by flovilmart** [comment]
Yes there's no issue with desktop games, I believe you'll be looking to use the Xamarin SDK or the MacOS SDK?

**Comment by buhuehue** [comment]
I want to create in windows desktop with unity3D. why i need xamarin or macOs SDK?
is this real time database like firebase?

(my english isn't good)

**Comment by flovilmart** [comment]
So for a Windows app, you’re probably good to go with the dotNet SDK.

**Comment by montymxb** [comment]
@buhuehue to second that you're probably talking about the .NET sdk, the [guide is over here](http://docs.parseplatform.org/dotnet/guide/). But i would lend a bit of caution, the .NET sdk has known [unity issues](https://github.com/parse-community/Parse-SDK-dotNET/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+unity), particularly on Android & iOS. I can't think of any active issues related to a desktop implementation however, so you may be ok there.
