### ISSUE TITLE
Class Level Permissions erased

### ISSUE THREAD

**Issue by Helmikku** [parse-community/parse-server#4423]
### Issue Description
For the second time, all my Class Level Permissions (CLP) were erased from the MongoDB _SCHEMA collection (no more _metadata.class_permissions key). They were not appearing either on the dashboard. Only empty collections still had their CLP.

### Steps to reproduce
I still haven't found out how to reproduce it but it could have come from some index building (that overwrite the "_metadata" key).

#### Expected Results
CLP shouldn't be erased.

### Environment Setup
- **Server**
  - parse-server version: 2.7.1
  - Operating System:     64bit Amazon Linux 2017.09 v4.4.0 running Node.js
  - Hardware:             t2.small
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): AWS EC2 

- **Database**
  - MongoDB version: 3.4.5
  - Storage engine:  WiredTiger
  - Hardware:        ?
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): mLab

### Logs/Trace
We've just made a migration in mLab so I don't have much log. The only calls to the _SCHEMA collection were the 3 following lines:

2017-12-08T17:28:04.599-0800 I REPL     [repl writer worker 3] CollectionCloner::start called, on ns:some-database._SCHEMA
2017-12-08T17:28:04.609-0800 I INDEX    [InitialSyncInserters-some-database._SCHEMA0] build index on: some-database._SCHEMA properties: { v: 1, key: { _id: 1 }, name: "_id_", ns: "some-database._SCHEMA" }
2017-12-08T17:28:04.609-0800 I INDEX    [InitialSyncInserters-some-database._SCHEMA0] 	 building index using bulk method; build may temporarily use up to 500 megabytes of RAM

Could this be related to the 2.7.0 issues with CLP?

I'm watching the logs and will add more insights if I found anything.

Thanks,

**Comment by flovilmart** [comment]
This should have been fixed with 2.7.1, you may have a server deployed with 2.7.0 that upon restated would yield the issue.

**Comment by oallouch** [comment]
I wish I could set the CLP using code, like I can set indexes in MongoDB using ensureIndex (in the Java Driver of MongoDB). Having an 'ensureCLP' would be great.

**Comment by Helmikku** [comment]
Thank you @flovilmart 

This issue has probably occured before I updated parse server from 2.7.0 to 2.7.1 indeed. I'll check that everything is fine in the next few days.

**Comment by agwl-saurabh** [comment]
is new 2.7.1 is stable. i am concern i am planing to update to 2.7.1 from 2.6.4. . some how i am able to make my apps some stable . or i still can run on 2.6.4 as i don't have any specific requirement for new version.

**Comment by montymxb** [comment]
@agwl-saurabh if you have no particular reason to upgrade you can remain at **2.6.4** where you are currently. 

**2.7.1** should be stable as well if you want the new changes, but _if_ there is no benefit to making an upgrade for you there's not really a need to make that jump then. 

Keep in mind that bug fixes, performance improvements and general enhancements are _not_ applied retroactively to existing release lines. If something new comes out that you would like to take advantage of you will eventually have to upgrade to the version that the change was introduced in.

**Comment by Helmikku** [comment]
Hello, After several weeks monitoring the CLP, it seems everything works as expected.
