### ISSUE TITLE
Parse-server logs consume too much space

### ISSUE THREAD

**Issue by majidhassan** [parse-community/parse-server#4424]
Hello,

I'm using parse-server 2.3.8, and recently ran into an issue where uploading files was failing, after some time I realized, that my server had run out of space. The parse logs alone were taking up 19G. I'm running parse-server with VERBOSE=1, which might have added to that massive size.

My question is, other than not running with verbose, is there a way to configure parse-server to automatically clean up old log files?

I'm not sure whether this should be posted as an issue here, so if it doesn't fit here feel free to close this and point me in the right direction to post this.

**Comment by bohemima** [comment]
Depending on your OS you should look at something like logrotate for *nix (https://github.com/logrotate/logrotate)

**Comment by dplewis** [comment]
Duplicate https://github.com/parse-community/parse-server/issues/3403 and https://github.com/parse-community/parse-server/issues/3934

**Comment by montymxb** [comment]
Closing in favor of #3403. @majidhassan  We definitely are open to discussion on this however, just add it to the existing issue so we can keep related discussion consolidated there 👍 .
