### ISSUE TITLE
Feature request: timeout parameter for Parse.Cloud.httpRequest

### ISSUE THREAD

**Issue by lxknvlk** [parse-community/parse-server#4426]
Parse.Cloud.httpRequest is lacking this option to set a timeout request. 	

Parse.Cloud.httpRequest({
	url: url,
        timeout: 10,
		success: function(httpResponse) {
	                response.success();
		},
		error: function(httpResponse) {
			response.error();
		}
	});

**Comment by milesrichardson** [comment]
Why don't you just use an external library, e.g. "requests"? Not much reason to rely on Parse.Cloud.httpRequest now that parse-server is self hosted.
