### ISSUE TITLE
afterFind request.user is undefined

### ISSUE THREAD

**Issue by ranhsd** [parse-community/parse-server#4428]
Hi, 
I created **afterFind** hook on Parse.User object. What i want to do is to restrict access to some **secret** attributes of the user and allow only the current user to view them. In my afterFind hook i tried to do run the following code: 

```
    _(request.objects).forEach(object => {

        if (object.id !== request.user.id) {

        }        
    });
```

but i get **undefined** error on the request.user.id condition.
There is a reason why request.user cannot be accessed? 

Another thing that i didn't find out is how to remove specific attribute from the object. I want for example to remove the "credits" attribute so only the logged in user will be able to see it in the results. I tried to do the following:

`remove object.attributes["credits"]`

But it's not really remove the credits attribute from the results. 

Thanks in advanced!

**Comment by milesrichardson** [comment]
What version are you using? I am on 2.7.0 and definitely not having this problem. Make sure you're not testing with, e.g. parse-dashboard using master key.

Regarding your other question, here is some sample code of how I solve this problem. I have a class named "Fund" and a role for each Fund object called fund_xx_invitees. If a user has the role fund_xx_invitees, the user should only see a whitelisted subset of the fields in Fund. Here is the code for the `afterFind`:

``` js

/* auth.js */
export const getUserRoles = (user, options) => {
    // eslint-disable-next-line
    return new Parse.Query('_Role').equalTo('users', user).find(options)
    .then((roles) => {
        return Promise.resolve(roles.map((r) => r.get('name')))
    })
}

/* afterFind on class Fund */
afterFind(req, res) {
    if (req.master) {
        res.success(req.objects)
        return
    }

    return auth.getUserRoles(req.user, { useMasterKey: true })
    .then((userRoles) => {
        let cleanedObjects = []

        for (let i = 0; i < req.objects.length; i++) {
            let fund = req.objects[i]

            let inviteesRoleName = fund.inviteesRoleName()

            if (userRoles.includes(inviteesRoleName)) {
                console.log('user is an invitee, strip')

                cleanedObjects.push(Parse.Object.fromJSON({
                    className: 'Fund',
                    objectId: fund.id,
                    fundName: fund.get('fundName'),
                    ownerOrganization: fund.get('ownerOrganization')
                }))
            } else {
                cleanedObjects.push(fund)
            }
        }

        res.success(cleanedObjects)
    })
    .catch((err) => res.error(err))
}
```

The basic strategy is to loop through `req.objects`, create a new list of "`cleanedObjects`" and return the `cleanedObjects` list.

**Comment by ranhsd** [comment]
Hi @milesrichardson after investing it a bit I found that the request.user is **undefined** only when the user is the current user otherwise it is not.

**Comment by flovilmart** [comment]
@milesrichardson i noticed you were still running 2.7.0. You have to upgrade to 2.7.1 as the version you’re running contains a severe issue regarding class level permissions
