### ISSUE TITLE
Proper way to get this type of object from mongo with parse-server?

### ISSUE THREAD

**Issue by mginz83** [parse-community/parse-server#4430]
Let's say I have this type of object in my mongo.

```
{
    "_id": "**********",
    "stuff": "other stuff",
    "stuff": "other stuff",
    "stuff": "other stuff",
    "stuff": "other stuff",
    "level1": {
        {"one": "1"}, 
        {"two":"2"}
    }
}
```

how can I reach "one" and "two"?

Normally, I would query it out from the local storage, but with parse-server, how would i get into the level1 object structure from within the object?

**Comment by tejpratap46** [comment]
Query it like this
`query.equalTo('level1.one', '1').find()`

If you have a ParseObject, get it like this
`object.get('level1.one')`

Another way, get as JSON and get your object.
`object.toJSON().level1.one`

**Comment by mginz83** [comment]
Cool. I'll give it a shot. It will query in background just as fast if it's pinned, right?
