### ISSUE TITLE
Files suddenly stop to work on my local machine

### ISSUE THREAD

**Issue by ranhsd** [parse-community/parse-server#4432]
### Issue Description

I am running parse-server locally with docker and docker-compose. Everything works well but suddenly today the files controller raise errors. When i am trying to access parse file from the app or from the dashboard i receive the following: 

```
{
code: 1,
message: "Internal server error."
 }
```

I tried to restart my server, change parse-server version, replace the db with a new one but the issue is still there. What is so strange is that everything works very good until today and i can't even think about a reason why its happening 

#### Actual Outcome
```
{
code: 1,
message: "Internal server error."
 }
```

What is happening instead.

### Environment Setup

- **Server**
  - parse-server version 2.7.1 & 2.6.5 
  - Operating System:    MaxOS
  - Hardware:             Macbook pro, core i7 512SSD 
  - Localhost or remote server? Docker on localhost

- **Database**
  - MongoDB version: 3.2.9
  - Hardware:        same as avoce
  - Localhost or remote server? Localhost

### Logs/Trace

```
my-server | error: Uncaught internal server error. TypeError: _mime2.default.getType is not a function
my-server |     at getHandler (/my-server/node_modules/parse-server/lib/Routers/FilesRouter.js:63:40)
my-server |     at Layer.handle [as handle_request] (/my-server/node_modules/express/lib/router/layer.js:95:5)
my-server |     at next (/my-server/node_modules/express/lib/router/route.js:137:13)
my-server |     at Route.dispatch (/my-server/node_modules/express/lib/router/route.js:112:3)
my-server |     at Layer.handle [as handle_request] (/my-server/node_modules/express/lib/router/layer.js:95:5)
my-server |     at /my-server/node_modules/express/lib/router/index.js:281:22
my-server |     at param (/my-server/node_modules/express/lib/router/index.js:354:14)
my-server |     at param (/my-server/node_modules/express/lib/router/index.js:365:14)
my-server |     at param (/my-server/node_modules/express/lib/router/index.js:365:14)
my-server |     at Function.process_params (/my-server/node_modules/express/lib/router/index.js:410:3) TypeError: _mime2.default.getType is not a function
my-server |     at getHandler (/my-server/node_modules/parse-server/lib/Routers/FilesRouter.js:63:40)
my-server |     at Layer.handle [as handle_request] (/my-server/node_modules/express/lib/router/layer.js:95:5)
my-server |     at next (/my-server/node_modules/express/lib/router/route.js:137:13)
my-server |     at Route.dispatch (/my-server/node_modules/express/lib/router/route.js:112:3)
my-server |     at Layer.handle [as handle_request] (/my-server/node_modules/express/lib/router/layer.js:95:5)
my-server |     at /my-server/node_modules/express/lib/router/index.js:281:22
my-server |     at param (/my-server/node_modules/express/lib/router/index.js:354:14)
my-server |     at param (/my-server/node_modules/express/lib/router/index.js:365:14)
my-server |     at param (/my-server/node_modules/express/lib/router/index.js:365:14)
my-server |     at Function.process_params (/my-server/node_modules/express/lib/router/index.js:410:3)
my-server | TypeError: _mime2.default.getType is not a function
my-server |     at getHandler (/my-server/node_modules/parse-server/lib/Routers/FilesRouter.js:63:40)
my-server |     at Layer.handle [as handle_request] (/my-server/node_modules/express/lib/router/layer.js:95:5)
my-server |     at next (/my-server/node_modules/express/lib/router/route.js:137:13)
my-server |     at Route.dispatch (/my-server/node_modules/express/lib/router/route.js:112:3)
my-server |     at Layer.handle [as handle_request] (/my-server/node_modules/express/lib/router/layer.js:95:5)
my-server |     at /my-server/node_modules/express/lib/router/index.js:281:22
my-server |     at param (/my-server/node_modules/express/lib/router/index.js:354:14)
my-server |     at param (/my-server/node_modules/express/lib/router/index.js:365:14)
my-server |     at param (/my-server/node_modules/express/lib/router/index.js:365:14)
my-server |     at Function.process_params (/my-server/node_modules/express/lib/router/index.js:410:3)
```

**Comment by ranhsd** [comment]
@flovilmart Maybe you have a clue on what is the issue ?

**Comment by flovilmart** [comment]
I’m not sure how it’s possible, but it seems that your server is using the wrong version of the mime package.

**Comment by ranhsd** [comment]
Hi @flovilmart this is strange because it worked very good before... do you know how to solve this issue  ?

**Comment by flovilmart** [comment]
Re run  delete your node_modules folder, run npm install,

**Comment by ranhsd** [comment]
Hi @flovilmart i am running it with docker ... so i tried to delete the image and recreate it and its still doing it... This is very strange behaviour and this is not my first project with the current setup and in all other project everything work well..

**Comment by ranhsd** [comment]
Hi @flovilmart I deleted the node_modules folder inside my project and now it works... that is strange because I am not really using it because I'm running npm install on the docker image and it creates a node_modules folder there ... buy thank you very much for helping me here... :)

**Comment by bohemima** [comment]
I actually had the exact same issue, deleting my node_modules and doing a clean install solved the issue for me as well. Didn't bother to investigate further.

**Comment by ranhsd** [comment]
Yes...

I will close it for now.
