### ISSUE TITLE
Parse Server upgrade from 2.2.23 -> 2.7.2

### ISSUE THREAD

**Issue by shkesar** [parse-community/parse-server#4435]
My codebase is using parse-server v2.2.23 and I'm in process to migrate to the latest version with one version bump at a time. I'm looking forward to know any best practices.

For the bigger perspective, the effort depends on the features that I'm using. But which are the most important releases in the past that will require considerable amount of changes?

- **Server**
  - current parse-server version 2.2.23
  - Remove server: AWS

- **Database**
  - MongoDB version: 2.2.10
  - Remote server:  Mlab

**Comment by agwl-saurabh** [comment]
Install New server with 2.7.1 version of parse. take the backup of DB and create new db with everything same as live server. test this new setup with your app if its work fine make this live. i did same 4-5 times already with previews version. nothing spacial . its all very simple.
