### ISSUE TITLE
Request failed: bad request (400)

### ISSUE THREAD

**Issue by dongalor** [parse-community/parse-server#4436]
### Issue Description

IOS developer gets this exact error, while running cloud function, which executes normally from curl and Paw.

https://gist.github.com/dongalor/ad01f0038ebd45c0be2726ace348e321

On server-side I can only see this error:

0|parse-wr | error: invalid session token code=209, message=invalid session token

But cloud functions, which runs from IOS doesn't uses sessionToken and also I can't see any request parameters in log, but I run my parse with VERBOSE=1

### Steps to reproduce

AFNetwork IOS request fails while running cloud function

**Comment by ranhsd** [comment]
Hi @dongalor are you trying to execute POST request? because cloud code functions must be executed in POST. Can you please put some code in here?

**Comment by dongalor** [comment]
@ranhsd thank you for reply, yeah, this is post request, cloud function is:

```
Parse.Cloud.define('getTags', function (req, res) {

    var json = {};

    var q = new Parse.Query("Tag");
    q.select('tag');
    //q.limit(req.params.limit || 1000);
    //q.skip(req.params.skip || 0);

    if (req.params.tag !== undefined) {
        var tagSearch = req.params.tag.toLowerCase();
        q.startsWith('tagLowerCase', tagSearch);
    }

    json['tags'] = [];

    q.find().then(function (tags) {
        tags = _.map(tags, function (tag) {
            return tag.get('tag').toLowerCase();
        });
        var resTags = _.uniq(tags);
        res.success(resTags);
    }, function (error) {
        res.error(error);
    });

});
```

I can ask IOS developer to provide code of doing request.

**Comment by ranhsd** [comment]
Did you tried to debug the cloud code and see the values in it? maybe the IOS side does not send the right values like **tag** and **skip**

**Comment by dongalor** [comment]
@ranhsd i don't understand, why I can't see the request params in parse log, while I can see all the params if I use Paw or curl to make a request :(

**Comment by ranhsd** [comment]
Hi @dongalor that is strange... there is a chance to add some IOS code as well? Calling cloud functions is simple you just need to execute a POST request to the following endpoint:  https://<host>:<port>/functions/<YourFunctionName> and send the parameters as URL parameters  (?param1=val1&param2=val2 ... )

**Comment by dongalor** [comment]
@ranhsd so, we had a X-Parse-Session token everywhere even in signIn, signOut cloud functions (we don't use Parse IOS SDK), we've removed this header from signIn and signOut and now it works, i think.. Sounds reasonable? ) 

Thank you so much for you attention!

**Comment by dongalor** [comment]
@ranhsd also, is it ok to use this kind of cloud function to sign user out, using X-Parse-Session-Token?

```
Parse.Cloud.define('signOut', function (req, res) {

    Parse.User.logOut().then(function () {
        res.success('User signed out!');
    }, function (error) {
        if (error.code === Parse.Error.INVALID_SESSION_TOKEN) {
            Parse.User.logOut();
        }
        res.error(error.message);
    });
});
```

**Comment by ranhsd** [comment]
Hi @dongalor if your client is IOS then you should logout user on the client side and not in cloud code.

**Comment by dongalor** [comment]
@rihadavid is it possible to logout user on IOS without using Parse SDK?

**Comment by dongalor** [comment]
@ranhsd can IOS client logout via rest api?

```
## signOut Duplicate
curl -X "POST" "https://example.com/parse/logout" \
     -H 'Content-Type: application/json' \
     -H 'X-Parse-Session-Token: r:xxxxxxx' \
     -H 'X-Parse-Application-Id: appid' \
     -d $'{}'
```

**Comment by ranhsd** [comment]
Hi @dongalor no.. you need just to clear the session token on the client side (from the keychain access or user defaults) i think you don't need to do anything on the server side... but maybe @flovilmart will be  able to provide more hints here ...

**Comment by dongalor** [comment]
@ranhsd cuz today after trying to use REST function of user signing out, I've had a huuuuuuuuuuuge crash.. Ran, thank you so much for your time!

I hope I can have @flovilmart comment, until then I'll remove this rest logout from my IOS app!

**Comment by ranhsd** [comment]
Hi @dongalor from what i know the logout on the server is relevant only if your app is a web app which use Parse SDK. 
I strongly recommend you and your team to use Parse IOS SDK on the client side. 
https://github.com/parse-community/Parse-SDK-iOS-OSX

This SDK will make you and your team life easier than create a custom REST client manually. The SDK provides you all the tools in order to develop your iOS app and it also include offline storage (for creating offline first apps) out of the box. 
One of the features of this SDK is the ability to logout a user.

**Comment by dongalor** [comment]
@ranhsd thank you again! Actually my IOS team decided to go other way by using their own afnetwork rest client, but now they do understand, that using parse-ios-sdk would be time- and life-saviour )

**Comment by ranhsd** [comment]
@dongalor totally. I suggest you and  your team that if you want to be generic and not count only on parse IOS SDK what you can do is to create an abstract layer that will wrap the parse IOS SDK and will map data from parse objects to your own custom models. This way you will be agnostic to any server side solution that you will want to adopt in the future and not only to parse
