### ISSUE TITLE
ACL to enable public or role read / write on specific fields of a class

### ISSUE THREAD

**Issue by srameshr** [parse-community/parse-server#4438]
### Issue Description
If a class has 3 fields namely: ```A```, ```B```, ```C```; is it possible to enable field specific individual role permission?
### Steps to reproduce
Ex:
Field ```A``` could have public read.
Field ```B``` could have role read only.
Field ```C``` could have public read and role write only.
So on and so forth...

**Comment by ranhsd** [comment]
Hi, 
What you can do is to create pointers of one to one and then create acl  for each one of the pointers. Another option (without acl's) is to perform a check in afterFind hook and remove the value there.

**Comment by srameshr** [comment]
@ranhsd I wanted to refrain from manual coding to have this behaviour and use it from the framework level.

**Comment by flovilmart** [comment]
This is not something that we support, but if you feel this is an important enough feature, feel free to work on a PR. In the meantime, you can use pointers that have different ACL’s in order to achieve the same functionality
