### ISSUE TITLE
Support for Recurring Jobs (Tasks)

### ISSUE THREAD

**Issue by montymxb** [parse-community/parse-server#4442]
Just a disclaimer this is intended for general discussion.

There are quite a few cases where things need to be run on a periodic basis in conjunction parse server. Whether this is related to logs, general cleanup, monitoring or maintenance the common solution has been to implement a cron job to handle it, or to do it by hand. Although this is perfectly fine (and usually the best option) the idea of the server being capable of setting up, running and managing it's own periodic tasks is enticing.

I should note that this would be limited to what is capable of being done from within parse server itself as is, no magic there.

The closest thing that comes to mind are cloud **jobs**, which unlike cloud **functions** can run asynchronously. It would be interesting if we could add functionality where we could schedule them and execute them at a later date, particularly in a recurring fashion. This is briefly mentioned [here](http://docs.parseplatform.org/parse-server/guide/#jobs) in regard to compatibility with the original parse.com api. 

I haven't looked into how this could be setup, and if it could even be reasonably done from within the same parse server instance. However, if it can be done, and if it is done properly, it would add the capacity for scheduled/delayed operations _anywhere_ in parse server. This means scheduled support for just about anything we would need. I believe that would be a significant enhancement to parse server, greatly increasing it's potential as an all around solution.

Again, this isn't something that would bring _brand new_ functionality that isn't already possible, as setting up a cron job to hit an endpoint could do the same thing easily. What this is intended to help with is general consolidation of parse server functionality to coming from _within_ parse server itself. The less external services that are required to support the server, the less likely an issue could arise from forgetting to maintain or update an existing external dependency; like a periodic cronjob.

I would love to hear thoughts about this. Personally I've wondered of maybe including a kind of daemon process as a part of parse server. When it starts with the server it could provide the periodic ticks we would need to run scheduled ops on. Another easier solution, but adding another dependency to the server, could be considering reliance on something like [node-schedule](https://www.npmjs.com/package/node-schedule) to be our clock.

**Comment by flovilmart** [comment]
In our scenario, that would be harmful, we have many instances running, and only want one to schedule and run the jobs. I believe this functionality is better achieved outside of the core server package.

**Comment by montymxb** [comment]
@flovilmart a solution could be devised to respect cases where multiple instances are running, and run reliably as well. I certainly wouldn't dismiss this as a possibility without further investigation into reliable options. It can't hurt to look into it.

I believe a proper integration could be designed to be safe for singular or multi-instance setups (your case). It's worth pursuing as it could help us with scheduling push as well. Pretty sure that's still outstanding. Correct me if I'm wrong there.

That being beside the point, for the many users who do not run multiple instances this would be beneficial. This initial proposal is by no means 'the solution' for all setups, but I think something could be put together and would be worth pursuing in the long term.

**Comment by flovilmart** [comment]
I’m not personally fond of those features as they are properly solved but external components and may require additional maintenance, and will always rely on 3rd party dependencies. While it would be nice to have them, they don’t belong to the server. Those 2 particular features are long running, stateful processes, and even if they leverage the server in some way, they can be totally implemented independently. This is how I draw the line to what belongs where. We already split out many adapters to simplify extensibility and maintenance. Having those inside the server would hamper this philosophy. While I’m not against providing reference implementation, even if you run on heroku, those would need to be deployed as worker dynos, not web one.

**Comment by montymxb** [comment]
I do believe it would be helpful as a built in component, but your rationale for exclusion of something like this from the core is sensible.

Considering that how about favoring instead a module or other supporting component? Having a complementary component (or adapter) to parse server that would allow scheduling could achieve the same effect. And in that direction it would be purely up to the dev and whether their implementation is right for that.

**Comment by flovilmart** [comment]
We already provide such things, the job schedules are saved in the DB, the push schedules as well. The main issue is the ‘runtime’ that leverages those :(

**Comment by montymxb** [comment]
Yeah, we just need a clock and call to trigger stuff ⌚️ . Hmmm..I'll keep this open for now so others can weigh in if they want. It could be, that for the work involved, cronjobs may just be the best solution for the time being. I'll look into setting up something standalone that could pair with parse server, allowing scheduled jobs and pushes to be triggered. Could be something like 'parse-scheduler', just connects up with parse server and 'adds' that functionality by watching and calling as needed.

**Comment by montymxb** [comment]
For reference I'm adding these two independent solutions for scheduled pushs and jobs, as options for others to be aware of.
https://github.com/AmpMe/parse-server-scheduled-pusher
https://github.com/AmpMe/parse-server-job-runner

**Comment by mman** [comment]
From where I sit (skilled unix admin) I still would vote +1 for something like this. Having a simple mechanism to trigger a cloud function repeatedly from within the parse servers itself would make it simple to keep one code base take care of everything. I have way too many times forgot to copy over the necessary cron files that essentially only invoke cloud functions via curl to perform various types of cleanup operations. so +1 from me. Whether in a core or separate module I don't care, as long as I can ``docker build`` it using ``npm install`` I'm fine 👍

**Comment by montymxb** [comment]
@mman We would probably go for a module or something independent. It would still be something that could be put in `package.json` to keep it all together. Additionally the links above ^ may be of interest to you.
