### ISSUE TITLE
Parse include * ( everything or any regex option available )

### ISSUE THREAD

**Issue by GoGross** [parse-community/parse-server#4447]
Is there an option available to include all pointers on a query without necessarily specifying each one of them?

`params: {
						'include': '*',
						'limit': 5
					}`

**Comment by montymxb** [comment]
I don't believe there is an include all feature, you would have to clarify the keys individually.

**Comment by dplewis** [comment]
Closed via https://github.com/parse-community/parse-server/pull/4838
