### ISSUE TITLE
Unable to update an User with useMasterKey

### ISSUE THREAD

**Issue by JulienRcs** [parse-community/parse-server#4450]
### Issue Description

I'm trying to update an User when another user click on my Xamarin button.
Then, I used Cloud Code to perform this but it doesnt work

### Steps to reproduce

Here is my complete JS code :

```
Parse.Cloud.beforeSave("Archive", function(request, response) {
  Parse.serverURL = 'https://pg-app-0brffxkawi8lqvf2eyc2isqrs66zsu.scalabl.cloud/1/';
  var status = request.object.get("status");
  if (status == "validated") {
    var event = request.object.get("event");
    event.fetch({
      success: function(myEvent) {
        var coinsEvent = myEvent.get("coins");
        var user = request.object.get("user");
         user.fetch({
          success: function(myUser, coinsEvent, user) {
            var email = myUser.get("email");
            var coinsUser = myUser.get("coins");
            myUser.set("coins", coinsUser + coinsEvent);
            return myUser.save(null, {useMasterKey:true});
          }
        });
      }
    });
  }
  response.success();
});
```

#### Expected Results

`return myUser.save(null, {useMasterKey:true});`

Should work 

#### Actual Outcome

I actually have that error :

> Dec 24, 2017, 12:27 GMT+1 - ERRORError generating response for [PUT] /1/classes/_User/1GPcqmn6Hd 
> "Cannot modify user 1GPcqmn6Hd."
> 
> {
>   "coins": 250
> }

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : v2.3.3
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Sashido

**Comment by coryshaw** [comment]
Your code looks good. The only thing I can think of is that you are not initializing parse with your master key.

`Parse.initialize(process.env.PARSE_APP_ID, '', process.env.PARSE_MASTER_KEY);`

Or perhaps "coins" is not a number field?

**Comment by tolgaatam** [comment]
did you really need to put your server url in the cloud code? all information is passed to the cloud functions automatically

**Comment by tolgaatam** [comment]
it seems like your problem occurs where your response.success() is called before any of your async functions calls are submitted. you can call response.success() at two spots, first in the else statement of status == "validated" and secondly in the success callback of your myUser.save rather than returning that promise.

**Comment by JulienRcs** [comment]
Yes, the problem was the "response.success()", thanks !
