### ISSUE TITLE
Create beforeUpdate and beforeSave/New cloud functions

### ISSUE THREAD

**Issue by GoGross** [parse-community/parse-server#4468]
Is there a work around, maybe it's there lying in plain sight

**Comment by flovilmart** [comment]
Check `req.object.isNew()` this will be `true` for new objects, and `false` if the object is being updated. Another trick would be to use the `createdAt` / `updatedAt` properties.


See: http://parseplatform.org/Parse-SDK-JS/api/v1.11.0/Parse.User.html#isNew
