### ISSUE TITLE
query.equalTo not working with Cloud code 

### ISSUE THREAD

**Issue by zenz** [parse-community/parse-server#4477]
### Issue Description

query.equalTo not working with Cloud code (Parse-Server 2.7.1)

### Steps to reproduce

here's the Cloud code:

```
Parse.Cloud.beforeSave("Groceries", function(request, response) {
    var Groceries = Parse.Object.extend("Groceries");
    var query = new Parse.Query(Groceries);
    var entryName = request.object;
    query.equalTo('Name', entryName.get('Name'));
    query.first({
        success: function(results) {
            console.log("Exist record");
            response.error("Exist object");
        },
        error: function(error) {
            console.log("Add record:" + request.object.get("Name") + " ...");
            response.success();
        }
    });
});
```

#### Expected Results

will not create duplicate records while with the same "Name"

#### Actual Outcome

No matter if the "Name" is duplicate or not, it creates the new record.

**Comment by bohemima** [comment]
It's unlikely that "it's not working", what error are you seeing? Perhaps you don't have access to the object, wrong parseServerUrl in config or something like that.

**Comment by zenz** [comment]
@bohemima I don't think the parseServerUrl in config was wrong, because I can get everything while using REST_API or parse dashboard.
But as I wrote in this topic, the Cloud code beforeSave, I cannot get any records from query.

in PM2's log file, I got this:
`Add record:西瓜 ...
info: beforeSave triggered for Groceries for user o6Ntk96K0E:
  Input: {"Name":"西瓜"}
  Result: {"object":{"Name":"西瓜"}} className=Groceries, triggerType=beforeSave, user=o6Ntk96K0E`

and in parse-serve's logs I got this:
{"className":"Groceries","triggerType":"beforeSave","user":"o6Ntk96K0E","level":"info","message":"beforeSave triggered for Groceries for user o6Ntk96K0E:\n  Input: {\"Name\":\"西瓜\"}\n  Result: {\"object\":{\"Name\":\"西瓜\"}}","timestamp":"2018-01-01T10:34:26.697Z"}

**Comment by dplewis** [comment]
Can you print the error here?
```
error: function(error) {
  console.log("Add record:" + request.object.get("Name") + " ...");
  response.success();
}
```

**Comment by zenz** [comment]
@dplewis

Hi,

There's no errors print out indeed.

But I had figure it out, I have to use MASTER_KEY to do the query. event ACL has not limitation for reading.

**Comment by dplewis** [comment]
👍 We can close this out?
