### ISSUE TITLE
Error when running aggregate query in version 2.7.1

### ISSUE THREAD

**Issue by xedixermawan** [parse-community/parse-server#4479]
Hi,
I appreciate if someone can figuring out what is missing in my setup. thanks.
### Issue Description

got an error when try to run aggregate request to a collection.
the collection is already filled with some data.

### Steps to reproduce

1. add some data to GameScore collection. just like the parse server example in readme
2. run:
```
curl -X GET \
  -H "X-Parse-Application-Id: myAppId" \
  -H "X-Parse-Master-Key: myKey" \
  -H "X-Parse-REST-API-Key: ${REST_API_KEY}" \
  -G \
  --data-urlencode 'group:{objectId:'null',total:{$sum:'$score'}}' \
http://localhost:1337/parse/aggregate/GameScore
```
3. error message :
```
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /parse/aggregate/GameScore</pre>
</body>
</html>
```
#### Expected Results

the result of aggregate data.

#### Actual Outcome

error above

### Environment Setup

- **Server**
  - parse-server version : 2.7.1
  - Operating System:    OSX
  - Hardware:             Macbook Pro
  - Localhost or remote server?  localhost

- **Database**
  - MongoDB version: 3.4.10
  - Storage engine: 
  - Hardware:       local Macbook Pro
  - Localhost or remote server?  localhost

### Logs/Trace

Include all relevant logs. You can turn on additional logging by configuring VERBOSE=1 in your environment.

**Comment by bohemima** [comment]
See https://github.com/parse-community/parse-server/issues/4466#issuecomment-354236387

**Comment by xedixermawan** [comment]
hi @bohemima , I saw your link before. I thought that error in the link was different and specific cloud code.
so, in version 2.7.1 , the aggregate feature don't work yet ?
anyway, I'll try the #4466 solution.

**Comment by xedixermawan** [comment]
update : same error still occurs with latest version

**Comment by xedixermawan** [comment]
it works with latest version . i found curl example aggregate queries is not correct in docs 

```

**Comment by dplewis** [comment]
@xedixermawan Please feel free to update to submit a PR https://github.com/parse-community/docs.

Please include any examples that will make it easier for new users to understand.

**Comment by jadhavmanoj** [comment]
@xedixermawan  what you did to fix your issue? I am on latest version of parse i.e. parse@1.11.0. still facing same issue. Parse server version is 2.7.1.
