### ISSUE TITLE
Can't create Role in afterSave function

### ISSUE THREAD

**Issue by ibrahimennafaa** [parse-community/parse-server#4480]
### Issue Description
I'm creating Roles related to an Account in the afterSave function of the Account object.
I'm using the `new Parse.Role("name", acl)`
But I keep receiving errors on the `role.save()` : `code=141, message=name is required`
I tested everything but it looks like the new Parse.Role() constructor doesn't set the name properly.

### Steps to reproduce
Create new role and try to save it in an afterSave function.

#### Expected Results

The save should be successful as I set all required parameters.

#### Actual Outcome

`code=141, message=name is required.`

### Environment Setup

- **Server**
  - parse-server version: 2.7.1
  - Operating System:     MacOS
  - Hardware:             Macbook pro
  - Localhost or remote server?: Localhost

- **Database**
  - MongoDB version: v3.6.0
  - Storage engine:  ?
  - Hardware:        Macbook Pro
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): Localhost

### Logs/Trace

> info: beforeSave triggered for Account for user QSPBCRek00:
>   Input: {"name":"Ennafaa","domain":"ennafaa.com"}
>   Result: {"object":{"name":"Ennafaa","domain":"ennafaa.com"}} className=Account, triggerType=beforeSave, user=QSPBCRek00
> info: afterSave triggered for Account for user QSPBCRek00:
>   Input: {"name":"Ennafaa","domain":"ennafaa.com","createdAt":"2018-01-03T19:15:23.799Z","updatedAt":"2018-01-03T19:15:23.799Z","objectId":"kAa022V1lZ"} className=Account, triggerType=afterSave, user=QSPBCRek00
> error: Error generating response. ParseError { code: 111, message: 'name is required.' } code=111, message=name is required.
> error: name is required. code=111, message=name is required.

**Comment by itolisto** [comment]
Hello @ibrahimennafaa,

Could you please post your afterSave function?

**Comment by ibrahimennafaa** [comment]
Sure!

`const createRoles = (request) => {
	var account = request.object;

	if (request.user===undefined) {
		return Parse.Promise.error("Request User is undefined");
	}

	var user = request.user;

	// 1. Create admin role for current user and for current account
	var roleACL = new Parse.ACL();
	roleACL.setPublicReadAccess(true);
	var roleAdmin = new Parse.Role("admin-"+account.get("domain"), roleACL);
	roleAdmin.set("account", account);
	roleAdmin.getUsers().add(user);
	console.log("Name:"+roleAdmin.getName());
	console.log("Account:"+roleAdmin.get("account"));

	// ?. Shall we look for superAdmin and set it as a child role for admin role?

	return roleAdmin.save(null, { useMasterKey: true })
		.then(function(roleAdmin) {
	  	// The admin role was saved successfully
	  	// 2. Create editor role for current account and set child role as admin
	  	var roleACL = new Parse.ACL();
			roleACL.setPublicReadAccess(true);
			var roleEditor = new Parse.Role("editor-"+account.get("domain"), roleACL);
			roleEditor.set("account", account);
			roleEditor.getRoles().add(roleAdmin);
			return roleEditor.save(null, { useMasterKey: true });
		})
		.then(function(roleEditor) {
	  	// the editor role was saved successfully
	  	// 3. Retrieve all users with an email matching the account domain
	  	var query = new Parse.Query(Parse.User);
	  	query.endsWith("email", account.get("domain"));
	  	return query.find().then(function(users) {
	  		// We found a list of users with same domain
	  		// 4. Create user role for current account, attach all users with same domain and set child role as editor
	  		var roleACL = new Parse.ACL();
				roleACL.setPublicReadAccess(true);
				var roleUser = new Parse.Role("user-"+account.get("domain"), roleACL);
				roleUser.set("account", account);
				roleUser.getRoles().add(roleEditor);
				roleUser.getUsers().add(users);
				return roleUser.save(null, { useMasterKey: true });
			}, function(error) {
	  		// the query failed.
	  		return Parse.Promise.error("Error looking for users with same domain: "+error.message);
			})
		})
		.then(function(roleUser) {
	  	// The user role was saved successfully
	  	// 5. done\
		}, function(error) {
	  	// Error
	  	console.error("Error creating roles for account: " + error.message);
		})
}`

**Comment by Seanw265** [comment]
I had the same issue just now. In my case the issue was using a character that was not allowed in the name of the Role (for me it was ':'). I notice in your code you use the character '-' as part of the name. The name has to match this regular expression found in the Object validate function, `/^[A-Za-z][0-9A-Za-z_]*$/`. Although it also looks like you can pass in an option for no validation (not sure what other effects that might have).

In my case, I replaced ':' with '_' and everything was fine.
