### ISSUE TITLE
aggregate with pointer relation match ?

### ISSUE THREAD

**Issue by xedixermawan** [parse-community/parse-server#4489]
Hi,
is it possible to do aggregate query using `match` with pointer relation ? 
I'm using latest branch version.
for instance request like this:
```
curl -X GET \
  -H "X-Parse-Application-Id: myAppId" \
  -H "X-Parse-Master-Key: myAppKey" \
  -H "X-Parse-REST-API-Key: ${REST_API_KEY}" \
  -G \
  --data-urlencode 'match={"user":{"$eq":{"__type":"Pointer","className":"_User","objectId":"NE962BXR9x"}}}' \
	--data-urlencode 'group={"objectId":null,"total":{"$sum":"$value"}}' \
  http://localhost:1337/parse/aggregate/Distance
```
the Distance collection have a field calls 'user' ( a pointer type which point to collection ` _User`.)

the aggregate above resulting empty data `{"results":[]}`, meanwhile it should not

**Comment by dplewis** [comment]
A quick workaround is appending `_p_` to the field name
```
const pipeline = [
    { group: { objectId: '$_p_pointerFieldName' } }
];
```

**Comment by dplewis** [comment]
Closed via https://github.com/parse-community/parse-server/pull/4493

**Comment by xedixermawan** [comment]
Hi @dplewis , thanks for quick reply & implementation.
I tried your code change and it's work by appending `_p_`.
the thing I notice, the form of aggregate query is not consistent with the form of relational query ( a query using keyword `where` ).
for my query above , here is the change I made to make it work.
```
match={"_p_user":"_User$m7WeWjAQ3P"}
group={"objectId":"$_p_user","total":{"$sum":"$value"}}
```

**Comment by dplewis** [comment]
@xedixermawan In mongo especially there are multiple stages (20+) for aggregates so adding transforms for all of them would take some time. I guess we can transform the main 3 `group`, `match`, `project`. You want to open a PR to add pointer transform to `match`?
