### ISSUE TITLE
Full text search for Parse JS SDK and or Parse Cloud code

### ISSUE THREAD

**Issue by srameshr** [parse-community/parse-server#4490]
### Issue Description
The current query options on strings, in the JS SDK and Parse Cloud code is just limited to "starting with" option.

I see that there was a PR sent to include this feature but did not get merged:
https://github.com/parse-community/Parse-SDK-JS/pull/470

### Steps to reproduce

Try to do a fuzzy query or levenshtein-distance for strings.

Parse API code has this integrated.
https://github.com/parse-community/parse-server/pull/3904l

#### Expected Results

JS SDK should support the following text search:
http://docs.parseplatform.org/rest/guide/#queries-on-string-values

#### Actual Outcome

In the meantime, any ideas on how to use the Parse API (where this feature is available) within the Parse Server Cloud code, to query on strings?

What is happening instead?: Ummm, Im stuck 😐

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.9.x
  - Operating System:     Mac OS
  - Hardware:       
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Localhost / AWS

- **Database**
  - MongoDB version: 3.4
  - Storage engine:  MIFS
  - Hardware:        
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): Localhost / AWS

### Logs/Trace

Include all relevant logs. You can turn on additional logging by configuring VERBOSE=1 in your environment.

**Comment by dplewis** [comment]
@srameshr If your stuck with you using the Rest API in Cloud Code you can use any HttpRequest package available in node like `request`. If you need examples please look at the test specs.

https://github.com/parse-community/parse-server/blob/master/spec/ParseQuery.FullTextSearch.spec.js

**Comment by srameshr** [comment]
Why are you guys not releasing the next version with this fix?

**Comment by dplewis** [comment]
@srameshr I know @flovilmart has been giving the iOS SDK some TLC to fix Bolt issues and merging the iOS related repos which which took a lot of work.

https://github.com/parse-community/Parse-SDK-iOS-OSX/pull/1237

I can't speak for the team as far as releases go but there should be one soon. I've offered plenty of way for this feature to be used in the meantime. I hope you can understand.

**Comment by christianpbrink** [comment]
Hi all, any updates on a release that adds FTS to the parse/node JS package?

**Comment by christianpbrink** [comment]
@srameshr Is that thumbs-down for it being a bad question, or are you just saying no, there aren't any updates?

**Comment by srameshr** [comment]
Latter... Latter forever..

**Comment by flovilmart** [comment]
@srameshr if you keep showing this attitude, I'd have no other choice but to act accordingly as your comments and behaviour is not one we want to tolerate.

**Comment by srameshr** [comment]
I'm unsubscribing from these threads. Ignore the whining.
