### ISSUE TITLE
Reset Parse server password

### ISSUE THREAD

**Issue by manjum-kar** [parse-community/parse-server#4491]
Hello,

I'm new to Parse.
I created a parse server on AWS and everything worked fine until I shut down the server. Now I can't login back to parse dashboard as I don't remember the original password that I got by selecting system log. Is there a way to reset the password?

**Comment by georgesjamous** [comment]
hey, the dashboard username and password are specified in the dashboard configuration. 
When you create the dashboard :
`var ParseDashboard = require('parse-dashboard');...`
So if you still have access to the code you can find them out your self.

see here:
https://github.com/parse-community/parse-dashboard
