### ISSUE TITLE
MongoError: Interrupted by the host

### ISSUE THREAD

**Issue by majidhassan** [parse-community/parse-server#4494]
Hello,

I recently got the error "MongoError: Interrupted by the host" from my self hosted parse-server. My assumption is, that this is caused by a shortage in the connection pool.

Could something else be causing this error?

Here's the exact error object:

`{"code":141,"message":{"name":"MongoError","message":"Interrupted by the host","ok":0,"errmsg":"Interrupted by the host","code":11601,"codeName":"Interrupted"}}`

**Comment by montymxb** [comment]
Just looking around seems to indicate that something is being interrupted server (host) side, don't really think a connection shortage cause this as the connection has already been established for it to be interrupted (unless there's a contest for resources, maybe...). 

Could you provide further details regarding the circumstances of this? Especially if you have a scenario that can reproduce this.

**Comment by majidhassan** [comment]
Hey @montymxb, thanks for your reply. It turned out I had a bug that caused a call to go into an infinite loop. The call made multiple calls to the database, so my guess is, that the cloud call either timed out while a db call was executing, or, that the db itself rejected a call due to too many requests. I'm betting it's the first one, though.

**Comment by montymxb** [comment]
Ahh, there you go. Glad you figured it out. Unless there's something else that's outstanding I'll go ahead and close this out. Feel free to open it back up if this is persisting.
