### ISSUE TITLE
Push error when query has no results

### ISSUE THREAD

**Issue by adammlevy** [parse-community/parse-server#4496]
### Issue Description

Anytime I send a push and the push query doesn't map to any users, Parse dashboard reports that push as an error and the logs also report an error.  This leads me to believe that many of my pushes are not being sent.  Shouldn't these pushes be reported as success even though they are not sent to a single user?  
### Steps to reproduce

Send push with a push query that includes no users. 

#### Expected Results

No pushes are sent and no push errors are reported. 

#### Actual Outcome

The following push error is reported and parse dashboard shows push status as failed
```
"errorMessage": {
2018-01-13T07:06:55.983637+00:00 app[web.1]:           "error": "PushController: no results in query"
2018-01-13T07:06:55.983638+00:00 app[web.1]:         
}
```

### Environment Setup

- **Server**
  - parse-server version : 2.7.1
  - Operating System:     N/A
  - Hardware:             N/A
  - Localhost or remote server? Heroku (2X web, 2X worker)

- **Database**
  - MongoDB version: 3.2.1
  - Storage engine:  N/A
  - Hardware:        N/A
  - Localhost or remote server? mLab

### Logs/Trace

```
"errorMessage": {
2018-01-13T07:06:55.983637+00:00 app[web.1]:           "error": "PushController: no results in query"
2018-01-13T07:06:55.983638+00:00 app[web.1]:        
 }
```

**Comment by adammlevy** [comment]
@flovilmart thanks for fixing this!  When will the release branch be cut with this fix?

**Comment by flovilmart** [comment]
This weekend or early next week

**Comment by montymxb** [comment]
Closing this out as this has been added in (pending release for usage), thanks for helping us fix this @adammlevy .
