### ISSUE TITLE
user.emailVerified is not set to false when user.email changes

### ISSUE THREAD

**Issue by Helmikku** [parse-community/parse-server#4501]
### Issue Description

When a user has verified their email, and then change it, the field emailVerified is still true.

### Steps to reproduce

One user set their email. `user.email = aaa@aaa.aa;`
They clicks on the link to verify the email. `user.emailVerified = true;`
They changes their email. `user.email = bbb@bbb.bb; user.emailVerified = true;`

#### Expected Results

I was expected emailVerified to become false again.

### Environment Setup

- **Server**
  - parse-server version 2.7.1

### How to handle it

It might not be required by everyone, so I wanted to solve that issue inside the `beforeSave` of `Parse.User`, something like:

```
if (request.object.dirty('email') && !(request.original && request.original.get('email') === request.object.get('email'))) {
    request.object.set('emailVerified', false)
}
```

Unfortunately, the `user.emailVerified` field is protected, you need the masterKey to update that field. Maybe I have to call `user.save({ emailVerified: false }, { useMasterKey: true })` inside user beforeSave but I don't like the idea (infinite loop). Maybe we could only require masterKey for setting emailVerified to true?

Thanks!

**Comment by montymxb** [comment]
Hmm, this is interesting point. @flovilmart makes sense to reset verified when the email has been changed? Trying to think if something goofy would arise from this...

**Comment by flovilmart** [comment]
Yes it makes total sense! We should do it

**Comment by paulovitin** [comment]
@montymxb Can I take care of this?

**Comment by flovilmart** [comment]
@paulovitin yes! Jump ahead!

**Comment by paulovitin** [comment]
@flovilmart just one question, the user can change the email before of confirm the old email or not?

**Comment by montymxb** [comment]
@paulovitin yep go for it! And yes, the user may change their email before confirming the existing one. A good example would be if you put the _wrong_ email (or a non-existent email with a typo) the first time around. You would want to correct that even though you cannot necessarily confirm the existing email.

Another question would be whether we would to send another verification email automatically or manually (assuming email verification is enabled). On signup the email is sent automatically, if the email is subsequently changed, and the user is not informed to re-verify by another request, it could be problematic depending on what's controlled by `emailVerified`.

**Comment by paulovitin** [comment]
@montymxb look the test in PR, the problem cant be found. I create a test with the scenario and the test pass.

@Helmikku can you have a look in the PR?

**Comment by montymxb** [comment]
@paulovitin no kidding...alright hold I'll take a look at your change.

**Comment by montymxb** [comment]
It looks like the [following test](https://github.com/parse-community/parse-server/blob/9de4b8b2a7cf4487271f3eeef84b307d53c772f4/spec/ValidationAndPasswordsReset.spec.js#L145) accounts for this behavior, but it doesn't set an email first and then set it again. However it does demonstrate that updating a user with a new email will setup the verification process again.

@paulovitin I think it would be prudent to put up a PR for a test that explicitly checks for this behavior when an email has already been set _and_ verified beforehand. If you have time you can base it off the test you put together already, there are some things I want to correct but it looks like a good start.

**Comment by montymxb** [comment]
Closing this out as #4532 has been merged. @Helmikku if your issue persists let us know. Although we didn't introduce any fix specifically the supplemental test we've added indicates that **emailVerified** is properly cleared when updating from an existing email that was also verified.

**Comment by Helmikku** [comment]
Hi @montymxb 

Thanks for your feedback. For instance, if I update an email from the dashboard, the emailVerified field is still true (I refreshed the page to be sure the data is up to date):

![screenshot-2018-2-2 parse dashboard](https://user-images.githubusercontent.com/7205882/35748332-f5b67d14-084d-11e8-8f9c-181fc1056632.png)
![screenshot-2018-2-2 parse dashboard 1](https://user-images.githubusercontent.com/7205882/35748340-fb5a3530-084d-11e8-82ed-d5731715da70.png)

Regarding my setup, I've compared with the test @paulovitin provided and since I'm using my own verification process, I don't have those field in my init json:

+      verifyUserEmails: true,
+      emailAdapter: emailAdapter,
+      emailVerifyTokenValidityDuration: 5, // 5 seconds

Isn't verifyUserEmails dedicated to send email? Or should it be enabled even if I use my own flow?
I send a link with a custom token, that I use with a cloud function to update emailVerified (with useMasterKey: true).

**Comment by montymxb** [comment]
Ahh... If you're using your own flow and _not_ using the internal method I suspect it won't set the verified field back for you. In your setup you're going to have to do this yourself unfortunately, unless you decide to utilize the built in method.

**Comment by RaschidJFR** [comment]
The `emvailVerified` field changes to `false` when modifiend the `email` field from `Parse.User.save({email})`. But shouldn't this not change until the email is verified? Otherwise, the user could get locked out (if your app's logic prevents unverified emails from logging in for example) without a chance to reset their password!
