### ISSUE TITLE
Password Policy String

### ISSUE THREAD

**Issue by dblythy** [parse-community/parse-server#4502]
Is there a better way to show password policy errors?

Instead of

Password does not meet the Password Policy requirements. (Code: 142, Version: 1.14.2)

Maybe

Password does not meet the Password Policy requirements. Passwords must have <Readable Password Policy> (Code: 142, Version: 1.14.2)

**Comment by montymxb** [comment]
If you believe there is a better way go ahead and send us a PR so we can formally look it over.

**Comment by mrmarcsmith** [comment]
I'm no the OP but I have created a PR that fixes this issue. #4582
