### ISSUE TITLE
Parse not streaming videos?

### ISSUE THREAD

**Issue by Salahq** [parse-community/parse-server#4507]
Hello, I have installed ''parse-server-example'' with latest ''parse-server'' node_modules, But i cannot stream videos on IOS when i open the video link on firefox it works. Is there any fix for that in future please? Let me know

**Comment by cubycode** [comment]
What format does your video have? .mp4? .mov?
Are you using AVPlayer to play it by its URL?
Any Xcode console message?

**Comment by webupnapoli** [comment]
Sorry any ideas for this bug. I am same problem. Can't streaming url from parse server. The file is .mp4

thanks

**Comment by AyoPrez** [comment]
Same problem here, but with Mp3 (is not video, but theoretically should be the same)
