### ISSUE TITLE
Session Token Question

### ISSUE THREAD

**Issue by stevestencil** [parse-community/parse-server#4510]
Recently I have noticed that Session tokens are being replaced when logging a user in. I would expect that it would just create a new token instead of replacing the old one? Is this expected behavior?

Example: Calling the login function twice within 2 minutes of one another will replace the first session with the second one.

Is anyone else having this issue?

**Comment by koyinusa** [comment]
I doubt that this is entire true, because I just tried testing this right now and I seems to work just fine. I have the same user logged on different platform, with different tokens
I am currently on the v2.7.2
