### ISSUE TITLE
error unauthorized on customized reset password page

### ISSUE THREAD

**Issue by Macifier** [parse-community/parse-server#4512]
i am using parse-server-amazon-ses-adapter and trying to custmize password_reset functionality i am not able to figure out how to customize password_reset email and password reset ui i am trying it for a week but not able to do it
customPages: {
   
  
   choosePassword: 'password_reset'
  }
and after clicking password_reset link i am getting {"error":"unauthorized"} on browser 
and used body option for customizing email template but still not successfull
any help

**Comment by acinader** [comment]
if you still want help with this, give info on what url path you are seeing unauthorized.

**Comment by joramirezStackit** [comment]
I got the same error, but in my case, I was using the wrong public server URL I added something like this:
{
   "customPages": {
      "invalidLink":"https://<subdomain>.b4a.app/invalid_link.html",
      "verifyEmailSuccess":"https://<subdomain>.b4a.app/verify_email_success.html",
      "choosePassword":"https://<subdomain>.b4a.app/choose_password.html", 
      "passwordResetSuccess":"https://<subdomain>.b4a.app/password_reset_success.html",
      "invalidVerificationLink":"https://<subdomain>.b4a.app/invalid_verification_link.html",
      "linkSendFail":"https://<subdomain>.b4a.app/link_send_fail.html",
      "linkSendSuccess":"https://<subdomain>.b4a.app/link_send_success.html"
   }
}
