### ISSUE TITLE
ParseServerLiveQuery crashes on client side query.

### ISSUE THREAD

**Issue by majidhassan** [parse-community/parse-server#4528]
### Issue Description

I'm using parse-server live queries and I noticed, that a certain query written and subscribed to on the client side crashed my parse-server cloud call. The cloud call was interrupted and I found liveQuery related errors in the logs.

### Steps to reproduce

1. Run liveQuery with parse-server using PM2.
2. Subscribe to a query similar to the below:

```javascript
var query = new Parse.Query("MyObject");
query.notEqualTo("MyKey", null); // 'null' is what crashed it, when changed to 'undefined' it worked fine
```
3. Run cloud call triggering the query subscribed to in 2.

#### Expected Results

Cloud call to continue normally, and only crash on the client side.

#### Actual Outcome

ParseServerLiveQuery crashed.

### Environment Setup

- **Server**
  - parse-server version: 2.3.8
  - Operating System:     Ubuntu 16.04.3 x64
  - Hardware:             DigitalOcean 1 GB (RAM) / 25 GB Disk
  - Remote Server: DigitalOcean

- **Database**
  - MongoDB version: 3.4
  - Storage engine:  MMAPv1
  - Hardware:        
  - Remote Server: mLab

### Logs/Trace

![screen shot 2018-01-29 at 7 14 57 pm](https://user-images.githubusercontent.com/18425522/35524621-c3671894-052a-11e8-99f6-e7cb94919ab0.png)

**Comment by dplewis** [comment]
@majidhassan I see you are running an older version of Parse Server. Can you update to latest version and see if the issue persists?
