### ISSUE TITLE
Calling a Function in Index.js from Cloud Function 

### ISSUE THREAD

**Issue by bfjfm2** [parse-community/parse-server#4531]
[I know how to call a function and  pass values from index.js to Cloud Code](https://github.com/parse-community/parse-server/issues/4013)

How to do this in reverse side? Calling a function in Index.js from a Cloud function.

index.js
```javascript
//Parse Server Initialization
var api = new ParseServer({
    databaseURI: databaseUri,
......
});

function call_this_function_from_cloud_code(req ,res){
}

```
cloud/main.js
```node

function cloud_function_to_call(){
   //How to call 
   //call_this_function_from_cloud_code
}
```

**Comment by tolgaatam** [comment]
in index.js , export your function and in your cloud code javascript file, you can import the function derived from the index page. There are several syntaxes for exporting and importing, use the es6 way id you are using nodejs 6xx + :

index.js:

export function call_this_function_from_cloud_code(req, res){}

cloud/main.js

import { call_this_function_from_cloud_code } from “../index”;

...

**Comment by bfjfm2** [comment]
@tolgaatam  I am not clear, any simple code snippets?

**Comment by bfjfm2** [comment]
index.js
```javascript
//Parse Server Initialization
var api = new ParseServer({
    databaseURI: databaseUri,
......
});

Parse.Cloud.define("sendToChat", function (req, res) {
console.log("It is called in the index.js");
});

```
cloud/main.js
```node

Parse.Cloud.run('sendToChat', {}).then(function (ratings) {
// ratings should be 4.5
});

```
 **Parse is globally defined you should be able to use Parse Queries and Parse.Cloud in your index.js.** Thanks @dplewis
