### ISSUE TITLE
How would I use ParseServer if I inserted this custom JSON into ParseObjects in MongoDB

### ISSUE THREAD

**Issue by mginz83** [parse-community/parse-server#4534]
Usually, when dealing with a ParseObject from MongoDB, its a simple, well, JSON object like so.

```
{
 "_id": "g5Sf4GN86S",
 "name": "kevin"
}
```

What if I kept the _id and replaced everything else with the following JSON

```
[
  {
    "name": "recipe",
    "serves": "4",
    "prep_time": "10 mins",
    "cook_time": "10 mins",
    "ingredients": [
      "item 1",
      "item 2",
      "item 3"
    ],
    "cooking_instructions": [
      "Step 1",
      "Step 2"
    ],
    "nutrition_facts": [
      {
        "fact 1",
        "fact 2"
      }
    ],
    "credit": "google.com",
    "image": "http://www.website.com/image.jpg"
  }
]
```

Can something like this be parsed with ParseServer?

**Comment by bohemima** [comment]
If you added the corresponding keys with correct type for schema, sure.

name: String
Serves: Number
ingredients: Array
etc

**Comment by montymxb** [comment]
Pretty much as bohemima said, there are numerious data types, and you can set up a type of Array and set your entire json to that if you want. In the [js sdk](http://docs.parseplatform.org/js/guide/#data-types) you can see what data types you can work with. I would recommend you look over the docs for your use case to figure out what data types you need and how you would implement them.
