### ISSUE TITLE
Clarify Parse Documentation

### ISSUE THREAD

**Issue by jferrer21** [parse-community/parse-server#4536]
Under Sessions ->  Session Security

Session objects can only be accessed by the user specified in the user field. All Session objects have an ACL that is read and write by that user only. You cannot change this ACL.  **This ACL will be created with a public read and write, however, a Class Level Permission will block the ACL.**  This means querying for sessions will only return objects that match the current logged-in user.

**Comment by dplewis** [comment]
Which doc are you looking at?

**Comment by jferrer21** [comment]
Rest Api.

**Comment by montymxb** [comment]
@jferrer21 Yep we talked about this, thanks for opening the issue.

@dplewis There is a discrepancy in the docs regarding the [REST security section](http://docs.parseplatform.org/rest/guide/#session-security). The first paragraph contains:
>All Session objects have an ACL that is read and write by that user only.

The next paragraph contains:
>When you log in a user via /parse/login, Parse will automatically create a new unrestricted Session object in the Parse Cloud.

Those statements are conflicting. There is no limiting ACL being set on session objects, but the objects may only be accessed by the owner (unless using the master key). The behavior is fine, it's just the wording is odd. Should be corrected.
