### ISSUE TITLE
modify PublicApiRouter.js for fixing error

### ISSUE THREAD

**Issue by Macifier** [parse-community/parse-server#4537]
please modify 172 line of PublicApiRouter.js to
    var params = _querystring2.default.stringify({ username: username, token: token, id: config.applicationId, error: err.message, app: config.appName });
because you are sending error object to choose_password params url so it is getting error as empty if you send err.message atleast we can display error on choose_password if it doesn't match password criteria

**Comment by dplewis** [comment]
Duplicate https://github.com/parse-community/parse-server/issues/4538

**Comment by Macifier** [comment]
please fix this i have to customize the choose_password file
