### ISSUE TITLE
Extend Parse.Cloud.define to include additional paths to cloud code function

### ISSUE THREAD

**Issue by johnnydimas** [parse-community/parse-server#4555]
### Issue Description

I would like to extend the Cloud code path to include a new subset of the path. For instance, would it be possible to do:

Parse.Cloud.define("internal/myFunction", myFunction);

So that the path to my cloud code would be /parse/functions/internal/myFunction.

This would be nice because then we could make use of AWS WAF to catch certain paths of functions. An alternative of course is to define it as "internal-myFunction" so that the final path would be /parse/functions/internal-myFunction but it's not as pretty. :)

#### Expected Results

Path to my cloud code would be /parse/functions/internal/myFunction.

#### Actual Outcome

404 Path not found.

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.7.2
  - Operating System:     mac osx
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): localhost 

Thanks!

**Comment by kaevee** [comment]
Here is an example

**Functions in a class**

`classname: create-account.ts`

`class CreateAccount {`
`    static new = (req: Parse.Cloud.FunctionRequest, res: Parse.Cloud.FunctionResponse) => {`
`      console.log(req.params);`
`      res.success(req.params);`
`    }`
`}`
``
`export default CreateAccount;`

**Cloud functions entry point** 

`main.ts`

`import CreateAccount from './create-account';`
`Parse.Cloud.define('hello', CreateAccount.new);`

**Comment by johnnydimas** [comment]
I understand how to write a cloud function, that wasn't my question, but thanks for the input!

I'm looking for a way to extend the API route endpoint with a new path subset. 

The API endpoint for your function would be /parse/functions/hello

I'm looking to do something like /parse/functions/**myNewPath**/hello
