### ISSUE TITLE
how to edit MonogoUrl in Parse server??

### ISSUE THREAD

**Issue by Xcode09** [parse-community/parse-server#4556]
how to edit the mongo url in parse server api.i want to upload a parse server to Heroku with out credit information.so tell me how to edit the monogurl .I see the index.js but do not find anything

**Comment by kaevee** [comment]
@Xcode09 You should have checked out the wiki before asking here. 

Checkout Deploying to Heroku at [http://docs.parseplatform.org/parse-server/guide/#deploying-to-heroku-and-mlab](http://docs.parseplatform.org/parse-server/guide/#deploying-to-heroku-and-mlab)
