### ISSUE TITLE
Invalid Session Token on anonymous users

### ISSUE THREAD

**Issue by pithcou** [parse-community/parse-server#4562]
I'm runing parse server latest release 2.7.2, and I'm facing this issue, sometimes when a user logout he is getting Invlid session token error, and it seems to propagate to all other users, so all the users get stuck, all public requests got this response invalid session token

**Comment by dongalor** [comment]
i might be having same issue (not so often) with the same result, but on 2.4.2

`0|parse-wr | 12-02-2018 16:39:19 +03:00: error: invalid session token code=209, message=invalid session token`

**Comment by dongalor** [comment]
@pithcou, by the way, can you tell me how exactly do you logout and what about SDK, which SDK do you use?
