### ISSUE TITLE
Support BIT operator

### ISSUE THREAD

**Issue by srameshr** [parse-community/parse-server#4563]
### Issue Description
Interface for mongoDB bit operator:
https://docs.mongodb.com/manual/reference/operator/update/bit/

Describe your issue in as much detail as possible.

Running BIT wise operations is not supported. Simple use cases like ```xor```ing data on the DB, requires indexing a column, then reading everything into memory.

Use case:
1. Calculating hamming distance
2. Levenshtien distance etc.

### Steps to reproduce
NIL

#### Expected Results
NIL

What you expected to happen.

#### Actual Outcome
NIL

What is happening instead.
NIL

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.x
  - Operating System:     Any
  - Hardware:            Any
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): All

- **Database**
  - MongoDB version: ```3.6```
  - Storage engine: Any
  - Hardware:        Any
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): All

### Logs/Trace

NIL

**Comment by dplewis** [comment]
@srameshr Would you like to get started on this?

Postgres supports bitwise operations.

https://www.postgresql.org/docs/9.4/static/functions-bitstring.html

**Comment by srameshr** [comment]
I want to, but terrible time crunch.
If nobody picks it up in a week, may be il start on it in a few weeks.

In the meantime, any thoughts about updating parse server to include fullText support?

**Comment by srameshr** [comment]
@dplewis I was thinking of picking this up if nobody is working on this commit.

**Comment by flovilmart** [comment]
Wondering if we can support it as well in PG so we have a general support for this kind of operation.

**Comment by flovilmart** [comment]
Closing as no one picked it up.
