### ISSUE TITLE
Setting up web push

### ISSUE THREAD

**Issue by jcguarinpenaranda** [parse-community/parse-server#4568]
Hello, I am setting up Push notifications and I have the following questions regarding the Installation class, and how Push notifications are sent.

Currently, I need to target Web but I would like to be able in the future to send Android and iOS notifications also. As far as I have seen in the docs, currently there's no support for web. But, I use an external provider (https://onesignal.com) which is able to send Web Notifications.

I am using the `parse-server-onesignal-push-adapter` availabe [here](https://github.com/parse-server-modules/parse-server-onesignal-push-adapter).

Now, I understand that Parse Server sends the notifications to the items in the _Installation class. Is there any way to create an Installation that targets a web browser? If so, how?

I thought one could write a Service worker as described [here](https://serviceworke.rs/push-rich_index_doc.html) and then save a new Installation object with the users's subscription key to target that browser later.

I have also thought that as a user could have multiple devices, adding a user Pointer to the Installation class would be the best way to send messages to all of them. Am I ok?

Thank you for your help, and please tell me if there's another way to solve this

**Comment by jcguarinpenaranda** [comment]
Well, now I figured out a way to solve this.

OneSignal has a possibility to add tags to the devices (or Users as they are referred to on their docs). I added an userId tag with the id of my user in the Parse Server and now whenever I want to send push notifications to that single user  I can use the OneSignal's API. With that API I can even target different channels

**Comment by jpgupta** [comment]
Hey @jcguarinpenaranda - thanks for this, really helpful! 

I'm trying to set up something similar at the moment, so am I right in thinking: You don't have to make any changes to Parse's User/Installation classes? Just add a user ID tag to OneSignal and then use their API?

**Comment by jcguarinpenaranda** [comment]
Hello James, you are right, and it is very easy indeed.

I'm concerned, though, about the security of this solution because
OneSignals API would allow anyone inside your app to open the console and
send a tag with your user id.

This would then allow them to receive your notifications



El 17/02/2018 7:39 a. m., "James Gupta" <notifications@github.com> escribió:

Hey @jcguarinpenaranda <https://github.com/jcguarinpenaranda> - thanks for
this, really helpful!

I'm trying to set up something similar at the moment, so am I right in
thinking: You don't have to make any changes to Parse's User/Installation
classes? Just add a user ID tag to OneSignal and then use their API?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/parse-community/parse-server/issues/4568#issuecomment-366438794>,
or mute the thread
