### ISSUE TITLE
Twitter auth configuration missing

### ISSUE THREAD

**Issue by JoaoArmandoo** [parse-community/parse-server#4583]
I'm getting the following exception: Twitter auth configuration missing.
Code 1.

i have this in my index.js:
oauth: { 
   twitter: { 
      consumer_key: 'MyConsumerKey', 
      consumer_secret: 'MySecrectKey'
   } 
}

I'm using this to link accounts:
  ```
if (!ParseTwitterUtils.isLinked(user)) {
            ParseTwitterUtils.link(user,
                    getActivity(), new SaveCallback() {
                @Override
                public void done(ParseException ex) {

                    if (ex == null){
                        if (ParseTwitterUtils.isLinked(ParseUser.getCurrentUser())) {
                            Log.d("MyApp", "Woohoo, user logged in with Twitter!");
                        }
                    }else {
                        Log.d("MyApp", "message: " + ex.getMessage());
                        Log.d("MyApp", "getCode: " + ex.getCode());
                    }

                }
            });
        }
```
where user is: ParseUser user = ParseUser.getCurrentUser();

I'm using android 5.1 lollipop
I'm using these libs: 
```
 compile 'com.parse:parse-android:1.15.8'
 compile 'com.parse:parsetwitterutils-android:1.10.+'
 compile 'com.parse:parsefacebookutils-v4-android:1.10.4@aar'
```
I've been trying all day to find a solution to this, but so far nothing, so I've come to the experts for help, thank you.

Forgive my English, I'm using google translator :(

**Comment by JoaoArmandoo** [comment]
I was randomly reading the parse server documentation and found this, I decided to test and it works perfectly now!
auth: {
   twitter: {
     consumer_key: "MyConsumerKey", // REQUIRED
     consumer_secret: "MyConsumerSecret" // REQUIRED
   },
   facebook: {
     appIds: "MyAppIdFb"
   }
  }

**Comment by GEverding** [comment]
I'm getting this error. I've verified my config but I don't know why its not working.
