### ISSUE TITLE
Parse.Query.and is not a function

### ISSUE THREAD

**Issue by manishsangwan** [parse-community/parse-server#4588]
the docs suggest http://docs.parseplatform.org/js/guide/#and-ed-query-constraints `and`  is allowed but i am getting `Parse.Query.and is not a function` while using it.

**Comment by bohemima** [comment]
What version of Parse? I don't think this is in a tagged release just yet, only in bleeding edge. It was added only 25 days ago (https://github.com/parse-community/Parse-SDK-JS/commit/3d7c97bd70dec051b72b0193d796b78295aadbe1)

**Comment by manishsangwan** [comment]
Thanx @bohemima for answering. I am using v 2.6.1

**Comment by dplewis** [comment]
Parse.Query.and was add in `2.7.4`. Please update to the latest version of Parse-Server.
