### ISSUE TITLE
Transactions in Parse Server

### ISSUE THREAD

**Issue by ziyadparekh** [parse-community/parse-server#4589]
I know this has been discussed before in older issues, and some have commented on the availability of transactions with the Postgres adapter. However for Mongo support, the community still hasn't reached a consensus.

With that in mind, not sure how many people have heard the announcement by MongoDB themselves about releasing full transaction support in Mongo this summer with a Beta release already out. More can be read in the link below

https://www.mongodb.com/transactions

Are there any plans to support this feature? If anyone has read the announcement, have you looked deeper into this? how big of an endeavor will this be?

Just looking to ask the community for thoughts on whether or not people think adopting this will be worth it

**Comment by trylovetom** [comment]
Cool Guy. I can't wait to see this feature!!

**Comment by oallouch** [comment]
Imagine that !

**Comment by yuki-takeichi** [comment]
MongoDB released 3.7.7 beta server, which has multi-document transaction support. Now you can try it!
https://groups.google.com/forum/#!topic/mongodb-txnbeta/ML8jxxvnRKM

Docs are also available. so we can move the discussion forward.
https://docs-beta-transactions.mongodb.com/transactions/

**Comment by flovilmart** [comment]
Are you willing on work on a design for those transactions?

**Comment by yuki-takeichi** [comment]
@flovilmart Yes. I'd like to propose some REST API updates, and can suggest strategies for implementation.

**Comment by flovilmart** [comment]
Can you open an issue with your detailed design so we can evaluate the feature?

**Comment by yuki-takeichi** [comment]
@flovilmart Sure. I will.

**Comment by flovilmart** [comment]
Thanks! very cool!

**Comment by danieldimit** [comment]
Is there any progress on the issue? Me and the organization I'm working for are interested in helping implementing this feature.

**Comment by gtzinos** [comment]
Any update?

**Comment by JeromeDeLeon** [comment]
Any update?

**Comment by flovilmart** [comment]
@JeromeDeLeon you can perhaps implement it, looks like a few people would be interested 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by JeromeDeLeon** [comment]
Sorry, I'm busy with our projects. But is there a difference if I just use Parse.Object.saveAll([object1, object2]) cuz it seems like if one of the list has an error, it will stop?

**Comment by flovilmart** [comment]
This is not a transaction, just a save in batch

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by AtomicSimon** [comment]
Is there any plan to support MongoDB Transactions in the future?

**Comment by JeromeDeLeon** [comment]
https://github.com/parse-community/Parse-SDK-JS/issues/922
