### ISSUE TITLE
afterFind breaks aggregate

### ISSUE THREAD

**Issue by dblythy** [parse-community/parse-server#4594]
### Issue Description

Using aggregate works without afterFind set on class. When afterFind is set, internal server error. Even trying to pass response.success(request.objects); straight away still breaks.

### Steps to reproduce

Perform an aggregate such as .distinct on a class with Parse.Cloud.afterFind trigger.

#### Expected Results

Aggregate to ignore after find as objects are not parse.objects; or values to be passed in request.objects.

#### Actual Outcome

Internal server error. Cannot create property 'className' on string.

### Environment Setup

- **Server**
  - parse-server version: 2.7.2
  - Localhost or remote server: localhost

- **Database**
  - MongoDB version: 3.2
  - Localhost or remote server: localhost

**Comment by dplewis** [comment]
@flovilmart What do you think? Should Aggregate ignore AfterFind or pass in values into request.objects?

**Comment by flovilmart** [comment]
Yep we should probably not run afterFind after and aggregation. Does that make sense for you @dblythy ?

**Comment by dblythy** [comment]
Sounds good @flovilmart. As it's restricted to require masterKey, any stripping/sensitive or modified fields could be written in the cloud aggregate function.

**Comment by dblythy** [comment]
Thank you @dplewis!
