### ISSUE TITLE
Nodejs PFFile save issue "Could not store file" 

### ISSUE THREAD

**Issue by vermesjar** [parse-community/parse-server#4598]
### Issue Description

I was expanding my code and ran into an issue I don't understand. I was able to grab an image from a file, create a PFFile, create an object, store said file in object and push to heroku using parse. However at one point I started receiving the error "could not store file". The interesting thing is that if I change the pointer to my prod DB the code works fine but not in my dev. At one point it was working in dev. 

Long story short the code worked at one point for dev but no longer works. 

### Steps to reproduce

function imageEncoder(cb){
	var image = require("fs");
	image.readFile('work.jpg', function(err,data){
		if (err) throw err;

		var encodedImage = new Buffer(data, 'binary').toString('base64');
		cb(encodedImage);
	});
}

function fileToParse(encodedImage, cb){

	var base64 = encodedImage;
	var file = new Parse.File("test123.png", {base64: base64});

	console.log("File created");
	file.save().then(function(){
		console.log("fileToParse Working");
		cb(file);
	}, function(error){
		//alert('Failed to create new object, with error code: ' + error.message);
		console.log("fileToParse Error");
		console.log(error.message);
	});
}

#### Expected Results

I expect the output to display "File created" and "fileToParse Working"

#### Actual Outcome

It now outputs "File create" and "could not storefile" (from error)

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : [FILL THIS OUT]
  - Operating System:    Ubuntu 14.04
  - Hardware:  Heroku
  - Localhost or remote server? remote server

- **Database**
  - MongoDB version: 3.0.8
  - Storage engine:  ObjectRocket
  - Hardware:   
  - Localhost or remote server? remote server

### Logs/Trace

Include all relevant logs. You can turn on additional logging by configuring VERBOSE=1 in your environment.

**Comment by ChengGeoff** [comment]
This is also happening to me. It may be a file storage issue in the specific environment? I'm not sure whats going on.

**Comment by hamzabinamin** [comment]
@ChengGeoff @vermesjar Were you able to find a solution for this? The image upload was working fine on my app for months but suddenly it stopped working on

**Comment by flovilmart** [comment]
Can you provide the logs when running with VERBOSE=1? What file adapter are you using?

**Comment by blipdropper** [comment]
I am using Parse from AWS marketplace in a swift app and I started getting that error in code that was previously working fine.  I deleted most files to free up space, re-ran pod install, and thought it was taking up too much file space and deleted data but still doesn't work.  Could not store file. (Code: 130, Version: 1.17.1)
