### ISSUE TITLE
Schema mismatch for Image.src; expected File but got Object

### ISSUE THREAD

**Issue by elios264** [parse-community/parse-server#4599]
### Issue Description

Parse server automatically converts objects of type `Parse.File` to a plain javascript `object` when registering a subsclass in cloud code with: 

`Parse.Object.registerSubclass('Image', Image);`

This only happens when using a `beforeSave` hook, you don't have to do anything in the hook but to call `res.success()`

### Steps to reproduce

1. Create an Image class
```
class Image extends Parse.Object {
  constructor(attributes) { super('Image', attributes); }

  setAttr(prop, value) { return isEmpty(value) ? super.unset(prop) : super.set(prop, value); }

  get src() { return this.get('src'); }
  set src(value) { this.setAttr('src', value); }
}
```
2. Register it in cloud code with:
```
const { Config, Image, User, File } = require('../src/objects');

// Parse.Object.registerSubclass('_User', User);
// Parse.Object.registerSubclass('Config', Config);
Parse.Object.registerSubclass('Image', Image);
```
3. add a beforeSave hook:
```
Parse.Cloud.beforeSave('Image', (req, res) => res.success());
```
4. try to upload a file throught the Parse dashboard.

#### Expected Results

The row to be created

#### Actual Outcome

> error: Error generating response. ParseError {
>   code: 111,
>   message: 'schema mismatch for Image.src; expected File but got Object' } code=111, message=schema mismatch for Image.src; expected File but got Object

Remove the registerSubclass, and it works.

### Environment Setup

- **Server**
  - parse-server version 2.7.2
  - Operating System:    Windows
  - Hardware:        a pc??, intel i7, 16gb ram,, ssd, ??
  - Localhost or remote server? localhost

- **Database**
  - MongoDB version:  mlab
  - Storage engine:  mlab
  - Hardware:        mlab
  - Localhost or remote server? mlab

**Comment by JakeGreer** [comment]
Did you ever find a solution for this? @elios264

**Comment by elios264** [comment]
@JakeGreer nope, as you see I was ignored :(, I just gave up on using custom classes in backend

**Comment by FransGH** [comment]
Just in case someone ends up here after getting this error: check if the field is marked as 'required' in the schema. 
At least when uploading a file via Apollo/GraphQL, the upload fails with exactly this error on parse-server 6.5.5.
Making the field optional resolved the issue.

**Comment by mtrezza** [comment]
@FransGH In case you think it would be useful to add something to the docs, we'd be happy to review your PR.

**Comment by FransGH** [comment]
> @FransGH In case you think it would be useful to add something to the docs, we'd be happy to review your PR.

This looks more like a bug but for now I’ve just set the field to not required. Unfortunately don‘t have the the time currently to dive deeper into the root cause.

**Comment by mtrezza** [comment]
Is it the same bug that this issue describes? Should it be reopened?
