### ISSUE TITLE
Full text search is not working

### ISSUE THREAD

**Issue by khalilsarabey** [parse-community/parse-server#4600]
We use GitHub Issues for bugs.

### Issue Description

I'm running the latest version of Parse, and I'm trying to use the full text search feature, but whenever I try to implement it, I get "query.fullText is not a function", I tried that in cloud code and the javascript library from npmcdn, after searching the actual js file on npmcdn, the fullText function is not defined there, I don't know if there's anything that I need to do before getting this to work, but in the documentation nothing is mentioned about any additional steps that needs to be taken.

### Steps to reproduce

- Install the latest Parse server
- Try to create this in cloud code or a Javascript in the browser:
`       
        var gameScore = new Parse.Query("Game");
        gameScore.fullText('name', 'madrid');
        gameScore.find(null, {
            useMasterKey: true,
            success:function(results) {
                console.log(results);
            }
        })`

#### Expected Results

Search results

#### Actual Outcome

Error generating response. TypeError: gameScore.fullText is not a function

### Environment Setup

- **Server**
  - parse-server version: 2.7.2
  - Operating System:     macOS
  - Localhost

- **Database**
  - MongoDB version: 3.6.0
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): [FILL THIS OUT]

### Logs/Trace

Error generating response. TypeError: gameScore.fullText is not a function
    at /Users/khalilsarabey/parse/cloud/index.js:12:21
    at /Users/khalilsarabey/parse/node_modules/parse-server/lib/Routers/FunctionsRouter.js:176:9
    at new Promise (<anonymous>)
    at handleCloudFunction (/Users/khalilsarabey/parse/node_modules/parse-server/lib/Routers/FunctionsRouter.js:144:14)
    at /Users/khalilsarabey/parse/node_modules/parse-server/lib/PromiseRouter.js:169:7
    at Layer.handle [as handle_request] (/Users/khalilsarabey/parse/node_modules/parse-server/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/khalilsarabey/parse/node_modules/parse-server/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/khalilsarabey/parse/node_modules/parse-server/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/khalilsarabey/parse/node_modules/parse-server/node_modules/express/lib/router/layer.js:95:5)
    at /Users/khalilsarabey/parse/node_modules/parse-server/node_modules/express/lib/router/index.js:281:22

**Comment by flovilmart** [comment]
The latest version of the JS SDK is not yet published with full text support, it will be available with next release.

**Comment by khalilsarabey** [comment]
@flovilmart so that's why it doesn't work in cloud code also.
I just tried on the iOS sdk and it's also not working, also not supported yet?
if I try using REST directly will it work?
Thanks!

**Comment by flovilmart** [comment]
YOU can try using REST directly, if it doesn’t work, it means you need to update parse server

**Comment by khalilsarabey** [comment]
Perfect, will do that, thanks @flovilmart ! always very helpful :) 
By the way, I think it would be great if there's a way to query or search on an inner field.
For example a Friend class that has 2 fields of 2 pointers to two users, it would be great if I can for example search for users with a name that are available in this connection pointer. Just a thought!

Thanks!
