### ISSUE TITLE
Cannot upload image to Parse Dashboard

### ISSUE THREAD

**Issue by ChengGeoff** [parse-community/parse-server#4606]
### Issue Description

I can no longer upload an image to Parse through a nodejs script or directly from Parse dashboard. In the nodejs it returns an error: something like"could not store file". When uploading a new or replacing a current image (file) in our Parse Dashboard, it hangs or just doesn't upload. It was working fine a few days ago and all of a sudden the issue appears. Additionally, If we point our NodeJS Script to our Prod environment it works fine, this issue only happens in our Dev environment (Both hosted through Heroku).

### Steps to reproduce

Go to dashboard, insert image into file type column. 

#### Expected Results

Image is uploaded and displayed

#### Actual Outcome

image hangs and is not uploaded

### Environment Setup

- **Server**
parse-server version (Be specific! Don't say 'latest'.) : [FILL THIS OUT]
Operating System: Ubuntu 14.04
Hardware: Heroku
Localhost or remote server? remote server

- **Database**
MongoDB version: 3.0.8
Storage engine: ObjectRocket
Hardware:
Localhost or remote server? remote server

### Logs/Trace

Mar 06 10:15:13 vennu-development heroku/router:  at=info method=POST path="/parse/schemas" host=vennu-development.herokuapp.com request_id=f05a76e2-c913-4e4c-bef1-590dbe6c3f83 fwd="174.199.58.240" dyno=web.1 connect=1ms service=10ms status=200 bytes=4526 protocol=https 
Mar 06 10:15:13 vennu-development heroku/router:  at=info method=POST path="/parse/schemas" host=vennu-development.herokuapp.com request_id=8668b5d9-814b-411e-a1c8-671d5fac17bc fwd="174.199.58.240" dyno=web.1 connect=1ms service=8ms status=200 bytes=4526 protocol=https 
Mar 06 10:15:13 vennu-development heroku/router:  at=info method=POST path="/parse/classes/_Installation" host=vennu-development.herokuapp.com request_id=da1863a2-ff56-4544-b2e8-8eca6a5709a8 fwd="174.199.58.240" dyno=web.1 connect=1ms service=19ms status=200 bytes=24958 protocol=https 
Mar 06 10:15:13 vennu-development heroku/router:  at=info method=POST path="/parse/classes/_Installation" host=vennu-development.herokuapp.com request_id=44661c17-0c49-42f3-9ec9-9d520b867bbf fwd="174.199.58.240" dyno=web.1 connect=2ms service=15ms status=200 bytes=564 protocol=https 
Mar 06 10:15:13 vennu-development heroku/router:  at=info method=POST path="/parse/classes/_Session" host=vennu-development.herokuapp.com request_id=c31ad842-02b1-493c-bdc6-4700e0b87fa6 fwd="174.199.58.240" dyno=web.1 connect=1ms service=16ms status=200 bytes=564 protocol=https 
Mar 06 10:15:13 vennu-development heroku/router:  at=info method=POST path="/parse/classes/Update" host=vennu-development.herokuapp.com request_id=e468c188-300b-4bf8-aaba-3d80a55e0045 fwd="174.199.58.240" dyno=web.1 connect=1ms service=18ms status=200 bytes=565 protocol=https 
Mar 06 10:15:14 vennu-development heroku/router:  at=info method=POST path="/parse/classes/Event" host=vennu-development.herokuapp.com request_id=77ba4cd6-3c3d-46e1-a16f-89df4e3086c3 fwd="174.199.58.240" dyno=web.1 connect=3ms service=19ms status=200 bytes=565 protocol=https 
Mar 06 10:15:14 vennu-development heroku/router:  at=info method=POST path="/parse/classes/_Session" host=vennu-development.herokuapp.com request_id=0951fabd-37b9-4bf5-8d6b-d34adf4268b1 fwd="174.199.58.240" dyno=web.1 connect=1ms service=29ms status=200 bytes=564 protocol=https 
Mar 06 10:15:14 vennu-development heroku/router:  at=info method=POST path="/parse/classes/Moment" host=vennu-development.herokuapp.com request_id=27b0a701-d99d-4cbd-b117-30da9cf3ca0b fwd="174.199.58.240" dyno=web.1 connect=0ms service=27ms status=200 bytes=565 protocol=https 
Mar 06 10:15:14 vennu-development heroku/router:  at=info method=POST path="/parse/classes/ProfilePhoto" host=vennu-development.herokuapp.com request_id=372b85b1-265a-4def-a279-50ea669b10ac fwd="174.199.58.240" dyno=web.1 connect=1ms service=8ms status=200 bytes=564 protocol=https 
Mar 06 10:15:14 vennu-development heroku/router:  at=info method=POST path="/parse/classes/_User" host=vennu-development.herokuapp.com request_id=5177dc44-f3f0-4bde-b38c-42ee4036477e fwd="174.199.58.240" dyno=web.1 connect=1ms service=23ms status=200 bytes=564 protocol=https 
Mar 06 10:15:14 vennu-development heroku/router:  at=info method=POST path="/parse/classes/_Installation" host=vennu-development.herokuapp.com request_id=9d28c16f-2591-48ef-b154-ac93ffcd9c8d fwd="174.199.58.240" dyno=web.1 connect=0ms service=27ms status=200 bytes=564 protocol=https 
Mar 06 10:15:14 vennu-development heroku/router:  at=info method=POST path="/parse/classes/ProfilePhoto" host=vennu-development.herokuapp.com request_id=a47a3532-d891-4671-8728-a2ff36d92bd0 fwd="174.199.58.240" dyno=web.1 connect=1ms service=27ms status=200 bytes=564 protocol=https 
Mar 06 10:15:14 vennu-development heroku/router:  at=info method=POST path="/parse/classes/Event" host=vennu-development.herokuapp.com request_id=388c5032-7651-462f-aeb3-6e259ad80385 fwd="174.199.58.240" dyno=web.1 connect=1ms service=6ms status=200 bytes=565 protocol=https 
Mar 06 10:15:14 vennu-development heroku/router:  at=info method=POST path="/parse/classes/Update" host=vennu-development.herokuapp.com request_id=ba1bc1b6-c0a2-48b2-b1d4-120be1eab0a9 fwd="174.199.58.240" dyno=web.1 connect=2ms service=19ms status=200 bytes=565 protocol=https 
Mar 06 10:15:14 vennu-development heroku/router:  at=info method=POST path="/parse/classes/Event" host=vennu-development.herokuapp.com request_id=7b615ce4-67a2-4cd7-8018-3c009d5d52cd fwd="174.199.58.240" dyno=web.1 connect=1ms service=37ms status=200 bytes=163375 protocol=https 
Mar 06 10:15:14 vennu-development heroku/router:  at=info method=POST path="/parse/classes/_User" host=vennu-development.herokuapp.com request_id=4e3bcb44-b92b-45f4-a3d1-cc9b0c1f5585 fwd="174.199.58.240" dyno=web.1 connect=1ms service=14ms status=200 bytes=564 protocol=https 
Mar 06 10:15:14 vennu-development heroku/router:  at=info method=POST path="/parse/classes/Moment" host=vennu-development.herokuapp.com request_id=b2ca6fb3-6b0e-4177-8513-a52c51f426c5 fwd="174.199.58.240" dyno=web.1 connect=1ms service=14ms status=200 bytes=565 protocol=https 
Mar 06 10:15:29 vennu-development heroku/router:  at=info method=GET path="/parse/files/vVe526aSji0aU9C65B3OHnmm36wPNCK6/9ce6a1381b2acfb18cd16eadaf6a7749_image.png" host=vennu-development.herokuapp.com request_id=1f7a847c-2447-48f6-87ec-8f2e03510d1a fwd="174.199.58.240" dyno=web.1 connect=1ms service=61ms status=200 bytes=674451 protocol=http 
Mar 06 10:15:36 vennu-development heroku/router:  at=info method=GET path="/parse/files/vVe526aSji0aU9C65B3OHnmm36wPNCK6/9ce6a1381b2acfb18cd16eadaf6a7749_image.png" host=vennu-development.herokuapp.com request_id=ddb7984f-1622-4c65-aa50-e6365f48fd9d fwd="174.199.58.240" dyno=web.1 connect=3ms service=56ms status=200 bytes=674451 protocol=http 
Mar 06 10:15:50 vennu-development heroku/router:  at=info method=OPTIONS path="/parse/files/graffiti-berlin-wall-wall-trabi.jpg" host=vennu-development.herokuapp.com request_id=f8454b84-4902-44e9-8103-69d111ade047 fwd="174.199.58.240" dyno=web.1 connect=1ms service=2ms status=200 bytes=497 protocol=https 
Mar 06 10:15:50 vennu-development heroku/router:  at=info method=POST path="/parse/files/graffiti-berlin-wall-wall-trabi.jpg" host=vennu-development.herokuapp.com request_id=834d6557-c00f-44ae-b907-396f6c408b01 fwd="174.199.58.240" dyno=web.1 connect=1ms service=414ms status=400 bytes=555 protocol=https

**Comment by ChengGeoff** [comment]
We are currently using GridFileAdapter connected to our MongoDB via Heroku.

**Comment by flovilmart** [comment]
You probably ran out of space then, can you check that?

**Comment by ChengGeoff** [comment]
We've only used 2/5 GB of storage in mongo. Our production contains much more images than our dev, however it is dev that isn't working. Is there some information I'm missing about the capacity of GridFileAdapter?

**Comment by MBDeveloper** [comment]
If the file is a json file I found that after version 1.0.24 of the dashboard the file upload hangs.

**Comment by ChengGeoff** [comment]
In the nodejs script the PFFile for the image encoded in base 64. In the dashboard itself it's a png/jpeg image.
