### ISSUE TITLE
Suggestion: Make A Blueprint of Architecture of Parse-Server 

### ISSUE THREAD

**Issue by trylovetom** [parse-community/parse-server#4615]
parse-server is a very large project now. It might help to have a blueprint of architecture of parse-server in CONTRIBUTE.md for the new contributor.

Suggestion Context
1. Concept of Architecture
2. Detail of Architecture. something like Adapter interface or module description.
3. Roadmap

**Comment by dplewis** [comment]
There's the [Development Guide](http://docs.parseplatform.org/parse-server/guide/#development-guide) in the Wiki. It could be overwhelming to new contributors.

We could have some kind of visual graph like in the [PHP Class Diagram](http://parseplatform.org/parse-php-sdk/graph_class.html) or [Developer Roadmap](https://github.com/kamranahmedse/developer-roadmap)

I usually follow this generic flow especially for queries. We can definitely expand on this for the detail of the architecture. We could leverage the test specs as they separated.
```
middleware -> router -> rest -> controller -> storageAdapter
```

As far as a Roadmap, sadly there isn't one. A previous discussion was opened [Roadmap](https://github.com/parse-community/parse-server/issues/3909)

I do have my own personal roadmap.

* Unique Indexes
* GeoPoint 2dsphere Indexes
* Add indexes to Parse Dashboard
* Ram Usage / MongoStats to Parse Dashboard
* LeftJoin on Pointer and Relation
* Sample (Random Object) Query
* MySql Adapter update
* Neo4J Adapter
* Adapter Test Spec
* New Adapter Guide
* Let's Encrypt
* Field Validation / Private Fields via Schema
* .NET Live Queries

**Comment by flovilmart** [comment]
@dplewis, what a wonderful roadmap! Why don't you open the issues now around those feature? Maybe some +1's will let other people wanna help you or move things faster if we see a common urge.

**Comment by dplewis** [comment]
@flovilmart Most them already have issues opened. 😔

private fields via schema api https://github.com/parse-community/parse-server/issues/1547#issue-149363991
field validation via schema api https://github.com/parse-community/parse-server/issues/1547#issue-149363991
More database adapters https://github.com/parse-community/parse-server/issues/20
Live Query Subscribe to specific events https://github.com/parse-community/parse-server/issues/3841
LetsEncrypt https://github.com/parse-community/parse-server/issues/33
Randomly get objects from mongo https://github.com/parse-community/parse-server/issues/818
[.NET Live Queries](https://github.com/parse-community/Parse-SDK-dotNET/issues/199)

**Comment by dplewis** [comment]
@flovilmart If your interested I went through the opened and closed issues for all the repositories at one point in time and made a list of potential features. A lot of features were closed during the migration from parse.com because there wasn't time.
