### ISSUE TITLE
2.7.2 has a huge impact on latency

### ISSUE THREAD

**Issue by SebC99** [parse-community/parse-server#4616]
### Issue Description

When updating parse-server from 2.7.1 to 2.7.2 there's a huge impact on server latency (observed on AWS ELB)

The chart below presents the increase (at the exact minute of the update) and the decrease one week later when coming back to 2.7.1 (no other changes)

![capture d ecran 2018-03-09 a 11 50 40](https://user-images.githubusercontent.com/3028067/37204224-6544082e-2390-11e8-8a06-726cc2b9954e.png)

### Environment Setup

- **Server**
  - parse-server version: Upgrading 2.7.1 to 2.7.2
  - Operating System: Nodejs with AWS ElasticBeanstalk on t2.large

- **Database**
  - MongoDB version: 3.6
  - Storage engine: WiredTiger
  - Localhost or remote server? Mongo Atlas

**Comment by steven-supersolid** [comment]
There's a bug in mongodb-core 3.0.x that was fixed in 3.0.4 https://github.com/mongodb-js/mongodb-core/blob/v3.0.4/HISTORY.md which is fixed in the corresponding 3.0.4 node.js driver https://github.com/mongodb/node-mongodb-native/blob/v3.0.4/HISTORY.md

The bug is increased latency (about double) on mongodb SSL connections.

parse-server 2.7.1 upgraded the driver from 2.1.17 to 3.0.1 so likely had the bug introduced there

#4603 updates the driver to 3.0.4 so will fix this in the next release

**Comment by JacobJT** [comment]
Could this affect CPU usage on EC2 as well? I.e. longer requests results in more requests staying active and waiting for their results?

**Comment by flovilmart** [comment]
@JacobJT it’s unlikely that waiting for something spiked CPU usage. The SSL bug may have caused the CPU spike

**Comment by JacobJT** [comment]
Still this same issue with Mongo, or are you referring to a different issue with SSL? 

I suppose a more to the point question: Does 2.7.2 also affect CPU spikes, and reverting to 2.7.1 would reduce / eliminate them until 2.7.3 is released?

**Comment by SebC99** [comment]
@JacobJT in my case, there could be a 10% CPU increase linked to 2.7.2 but that's not that clear.

**Comment by JacobJT** [comment]
@SebC99 Thanks for the info. We had a CPU spike + massive latency, but it doesn't look like it matched up with our deployment of 2.7.2, I think it was related to some marketing e-mails causing a user spike and EB not spinning up a new server instance fast enough to handle it.

**Comment by flovilmart** [comment]
2.7.3 has been released, please update and reopen the issue if it persists.

**Comment by SebC99** [comment]
I confirm 2.7.4 fixes the issues, no more latency increase, just perfect :)
