### ISSUE TITLE
Deploying parse-server 2.7.3 fails

### ISSUE THREAD

**Issue by markuswinkler** [parse-community/parse-server#4625]
### Issue Description

Deploying parse-server 2.7.3 fails

### Steps to reproduce

`rm -rf node_modules/ && npm cache verify && npm prune && npm i`

#### Actual Outcome

fails with:
```
In file included from ../src/connection.cc:1:
../src/addon.h:5:10: fatal error: 'libpq-fe.h' file not found
#include <libpq-fe.h>
         ^~~~~~~~~~~~
```

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.7.3
  - Operating System:     MacOS 10.12.6
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc):  localhost & AWS

**Comment by flovilmart** [comment]
This is odd indeed, we’ll have a look

**Comment by flovilmart** [comment]
Is parse server a dependency on your project?

**Comment by markuswinkler** [comment]
yes.
this is my package.json. Setting parse-server to 2.7.3 fails.
```
{
  "name": "xxxxxxx",
  "version": "2.7.2",
  "main": "index.js",
  "private": true,
  "repository": {
    "type": "git",
    "url": "xxxxx"
  },
  "dependencies": {
    "aws-sdk": "<= 2.207.0",
    "bluebird": "<= 3.5.1",
    "currency-converter": "0.1.12",
    "express": "<= 4.16.2",
    "firebase-admin": "<= 5.10.0",
    "iap_verifier": "0.0.12",
    "jsonpointer": "<= 4.0.1",
    "kerberos": "~0.0.x",
    "memwatch-next": "<= 0.3.0",
    "mixpanel": "<= 0.9.0",
    "moment": "<= 2.21.0",
    "nodemailer": "<= 4.6.2",
    "parse": "<= 1.11.1",
    "parse-server": "<= 2.7.2",
    "parse-server-onesignal-push-adapter": "<= 1.0.0",
    "pm2": "<= 2.10.1",
    "raven": "<= 2.4.2",
    "request": "<= 2.83.0",
    "request-promise-native": "<= 1.0.5",
    "underscore": "<= 1.8.3"
  },
  "scripts": {
    "start": "node ./node_modules/.bin/pm2 start index.js --name xxxxx",
    "poststart": "node ./node_modules/.bin/pm2 logs"
  },
  "engines": {
    "node": "6.11.5"
  },
  "devDependencies": {
    "babel-cli": "<= 6.26.0",
    "eslint": "<= 4.18.2"
  }
}

```

**Comment by flovilmart** [comment]
Seems related to the latest version of the postgres storage adapter.

**Comment by markuswinkler** [comment]
I am not using postgres. Dependency inside parse-server maybe?

**Comment by flovilmart** [comment]
yes, pg-promise is using pg-native since verison `8.2.0`. Our travis CI didn't catch it as it has the required dependencies.

Can you check if it's possible to install the dependencies required for pg-native in the meantime? https://www.npmjs.com/package/pg-native

I'll try to get the maintainer of pg-promise to make pg-native a peer dependency.

**Comment by dplewis** [comment]
https://github.com/vitaly-t/pg-promise/issues/488

pg-native will be removed in pg-promise `8.2.1`

**Comment by flovilmart** [comment]
I guess we're in for a new release :)

**Comment by vitaly-t** [comment]
> pg-native will be removed in pg-promise 8.2.1

@dplewis It was removed 3 hours before you wrote this :wink:

Guys, really sorry about that mess with #488

**Comment by flovilmart** [comment]
Haha! All good @vitaly-t our CI didn’t catch it either. Which kinda sucks too

**Comment by flovilmart** [comment]
@markuswinkler 2.7.4 is released, is it all good on your side with this version%

**Comment by markuswinkler** [comment]
Works!  👍

**Comment by flovilmart** [comment]
awesome! Let us know if there'S anything!
