### ISSUE TITLE
Can we connect Parse server to MySql?

### ISSUE THREAD

**Issue by GursheeshSingh** [parse-community/parse-server#4631]
How can we connect Parse to a MySQL database?

**Comment by flovilmart** [comment]
At the moment, Parse supports mongodb and Postgres as storage engines and we don’t plan supporting MySQL. If that’s something you’d like to contribute, feel free to ask questions about a potential implementation.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dplewis** [comment]
@GursheeshSingh I wrote an adapter a while ago, but its not up-to-date.

https://github.com/dplewis/parse-server-mysql-adapter

**Comment by GursheeshSingh** [comment]
@dplewis isn’t there any oter way to use MySQL with parse?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dplewis** [comment]
@GursheeshSingh Thats the only way unless you want to contribute a potential implementation.

**Comment by GoGross** [comment]
@dplewis How far with updating the adapter as it is now breaking with latest versions of parse?

**Comment by dplewis** [comment]
@GoGross I haven’t updated it since 2.5.0 (it is now 3.9.0). It takes some work to run against the tests, since we don’t have a test spec to run against any database adapter.

I’ll look into it sometime this week.

**Comment by GoGross** [comment]
I look forward to it

**Comment by badboy-tian** [comment]
@dplewis any update for parse-server-mysql-adapter ?

**Comment by dplewis** [comment]
@badboy-tian I’ve been thinking about updating it to at least have the same capabilities as Postgres. Let’s move this conversation over to the Adapter repo.

**Comment by badboy-tian** [comment]
@dplewis ok, thank you
