### ISSUE TITLE
`matchesQuery` returns zero (0) results when used inside cloud function

### ISSUE THREAD

**Issue by awgeorge** [parse-community/parse-server#4641]
### Issue Description

I have a query that uses `matchesQuery` when fetching data. The data has public read. The function works correctly when running standalone using parse and node.

When I move the function into a cloud function and attempt to trigger it via a rest call. The same function returns 0 results. Upon removing the `matchesQuery` check - I start getting results.

In my case, the inner query is returning many objects. 

### Steps to reproduce

1) Create a cloud function 
2) Query data using `matchesQuery` 

#### Expected Results

Results should return

#### Actual Outcome

An empty array is returned 

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.7.4
  - Operating System:     macOS 10.13.3
  - Hardware:             OSX
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Localhost

- **Database**
  - MongoDB version:  3.4.7 
  - Storage engine:  (MMAPv1)
  - Hardware:  linux
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): mLab

### Similar issues

#1109
#1014

**Comment by flovilmart** [comment]
Are you able to open a pull request with a failing test or share a code example?

**Comment by awgeorge** [comment]
Failing test added: #4648

**Comment by awgeorge** [comment]
@flovilmart Do you know if cloud code does anything differently?

**Comment by awgeorge** [comment]
@flovilmart thanks for your patience with me. When using a cloud function, you have the ability to parse parameters. `var year = request.params.year || 2018;`. Clearly, 🤦‍♂️, when you submit these values via `x-www-form-urlencoded` they're transmitted as strings.

    yearQuery.equalTo("year", year); // (number)year === (string)year

Obviously (now) fails. A simple `parseInt` did the trick.

Sorry 😞

**Comment by flovilmart** [comment]
No problem! Glad you found. The solution!
