### ISSUE TITLE
buildConfigDefinition.js -  adapter config sample for S3FileAdapter

### ISSUE THREAD

**Issue by rowntreerob** [parse-community/parse-server#4642]
i would like to use [S3Adapter](https://github.com/parse-community/parse-server-s3-adapter/blob/master/README.md) which covers its own config in docs in the link. Its a clear sample but , regarding **buildConfigDefinition.js** in  parse server i have only : 

```
  /* Adapter module for the files sub-system */
  filesAdapter: ?Adapter; 
```

and the source for buildConfig.. js   which is a bit over my head regarding the interfaces used for Adapters.

So, is there an example for repurposing the sample config from the S3Adapter module for the idiom and syntax of buildConfigDefinition.js ? 

how to get bcd.js to handle the config for S3 shown below:

```
{
  "appId": 'my_app_id',
  "masterKey": 'my_master_key',
  // other options
  "filesAdapter": {
    "module": "@parse/s3-files-adapter",
    "options": {
      "bucket": "my_bucket",
      // optional:
      "region": 'us-east-1', // default value
      "bucketPrefix": '', // default value
      "directAccess": false, // default value
      "baseUrl": null, // default value
      "baseUrlDirect": false, // default value
      "signatureVersion": 'v4', // default value
      "globalCacheControl": null, // default value. Or 'public, max-age=86400' for 24 hrs Cache-Control
      "ServerSideEncryption": 'AES256|aws:kms' //AES256 or aws:kms, or if you do not pass this, encryption won't be done
    }
  }
}
```

**Comment by flovilmart** [comment]
I’m not sure I fully understand the question. The buildConfigDefinitionas is an internal file that help us define all options we can pass to parse server. The S3 options are specific to the S3 adapter, so we can’t really document them here.

**Comment by rowntreerob** [comment]
node resources/buildConfigDefinitions   

with  (index.js ) input of

  filesAdapter: ?Adapter; /* =
  {
    "module": "@parse/s3-files-adapter",
    "options": {
      "bucket": "my_bucket"}}

  */
Error: ./src/Options/index.js: Unable to parse value for filesAdapter 
    at list.map (/home/rob/src/tmp/parse-server/resources/buildConfigDefinitions.js:186:15)
    at Array.map (<anonymous>)
    at inject (/home/rob/src/tmp/parse-server/resources/buildConfigDefinitions.js:165:15)
    at PluginPass.ExportDeclaration (/home/rob/src/tmp/parse-server/resources/buildConfigDefinitions.js:213:21)
    at newFn (/home/rob/src/tmp/parse-server/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/home/rob/src/tmp/parse-server/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/home/rob/src/tmp/parse-server/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/home/rob/src/tmp/parse-server/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/home/rob/src/tmp/parse-server/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitMultiple (/home/rob/src/tmp/parse-server/node_modules/babel-traverse/lib/context.js:103:17)

The parser looks as tho i should be able to transfer the options for extern -s3Adapter- into the process that builds  definitions file (src/Options/Definitions.js)

OR i guess i can just apply another options file on the CLI

**Comment by flovilmart** [comment]
I’m still not really sure what you’re trying to achieve here. Are you trying to update the definitions so the generated documentation is more specific to S3 adapters?

**Comment by rowntreerob** [comment]
No.  im only trying to run the server with some additional adapters that are ES6  so i had to stop using the 'parse-server-example' project as it has no build step to accomodate ES 6 modules.

**Comment by flovilmart** [comment]
so you're definitely looking at the wrong place.

Did you get a look at:

http://docs.parseplatform.org/parse-server/guide/#usage

or 

https://github.com/parse-community/parse-server/#parse-server--express

Then the options to configure the S3 Adapter are also documented there

http://docs.parseplatform.org/parse-server/guide/#configuring-s3adapter
