### ISSUE TITLE
Feature Request: IncludeAll

### ISSUE THREAD

**Issue by dplewis** [parse-community/parse-server#4644]
Wanted to have a discussion the best way to implement including all pointers.

`query.include('*')` or `query.includeAll()`

We can query the schema to find all the pointers and leverage existing `handleInclude()` in `RestQuery.js`

My ultimate goal is to add this somehow to `Parse.User.login`

Similar Issue: https://github.com/parse-community/parse-server/issues/288

**Comment by tolgaatam** [comment]
+1, client side not having the includes for the user object is a big problem indeed

**Comment by milesrichardson** [comment]
Should it be optionally recursive?

**Comment by omairvaiyani** [comment]
Happy to undertake this, can anyone point me to where we can access the schema for a given class?

**Comment by dplewis** [comment]
You can have a look at the [SchemaController](https://github.com/parse-community/parse-server/blob/master/src/Controllers/SchemaController.js).

**Comment by JacobJT** [comment]
@milesrichardson That sounds like it's asking for lots of circular recursion cases, i.e. classA -> classB -> classC -> classA. Although it's my understanding that used to create save loops and no longer does, so maybe whatever solution was used to block those can be used to block an infinite include loop.
