### ISSUE TITLE
Could not connect to parse-server mit javascript sdk

### ISSUE THREAD

**Issue by aBuder** [parse-community/parse-server#4645]
Hi,

I cant connect with Javascript sdk to my parse-server on heroku. I get the error.
`{"error":"unauthorized"}`

Javascript Client Configuration

![bildschirmfoto 2018-03-15 um 07 59 53](https://user-images.githubusercontent.com/1265139/37448487-dfa8a454-2826-11e8-8f55-a8e9c4fe6c80.png)

Parse Server Configuration
![bildschirmfoto 2018-03-15 um 07 49 20](https://user-images.githubusercontent.com/1265139/37448468-c933bc86-2826-11e8-9005-618fcbc09f9c.png)

![bildschirmfoto 2018-03-15 um 07 51 47](https://user-images.githubusercontent.com/1265139/37448457-bf875792-2826-11e8-9033-2c0cb7a718a0.png)

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.7.4
  - Operating System:     unknown
  - Hardware:             unknown
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Heroku

- **Database**
  - MongoDB version: 3.4.14
  - Storage engine:  unknown
  - Hardware:        unknown
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): mLab

**Comment by dplewis** [comment]
When you deploy to Heroku, are your environment variables setup and match your config?

**Comment by aBuder** [comment]
@dplewis Thanks for answer, I attach an screenshot form heroku dashboard.

![heroku](https://user-images.githubusercontent.com/1265139/37508242-8ba11784-28f2-11e8-9577-0f5eafcb6d31.png)

**Comment by aBuder** [comment]
I found an solution for my problem. I create an fork from https://github.com/parse-community/parse-server-example and deployed to heroku. Now all work fine.
