### ISSUE TITLE
ParseError {code: 206, message: "Cannot modify user FQrZUWcoW9."}

### ISSUE THREAD

**Issue by mrmengjun** [parse-community/parse-server#4647]
ParseError {code: 206, message: "Cannot modify user FQrZUWcoW9."}.

### Issue Description

ParseError {code: 206, message: "Cannot modify user FQrZUWcoW9."} when setting another user
even though set this ACL

### Steps to reproduce
In source code, I found these
```js
//RestWrite.js 975-979
if (this.className === '_User' &&
      this.query &&
      !this.auth.couldUpdateUserId(this.query.objectId)) {
    throw new Parse.Error(Parse.Error.SESSION_MISSING, `Cannot modify user ${this.query.objectId}.`);
  }
```
```js
//Auth.js 21-31

// Whether this auth could possibly modify the given user id.
// It still could be forbidden via ACLs even if this returns true.
Auth.prototype.couldUpdateUserId = function(userId) {
  if (this.isMaster) {
    return true;
  }
  if (this.user && this.user.id === userId) {
    return true;
  }
  return false;
};
```

#### Expected Results

What you expected to happen.

#### Actual Outcome

What is happening instead.

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) :2.7.2

**Comment by flovilmart** [comment]
This is the expected behaviour, one authenticated user cannot write on another user's object, nor read on it. THis is a security measure. Users hold private information and therefore are protected in a more restrictive way.

**Comment by aBuder** [comment]
@flovilmart Is there no solution to update the user attributes? For example an user with admin role should edit and change user attributes. Is there an solution to solve the problem on basic parse way without writing some custom cloud code.

**Comment by flovilmart** [comment]
In the latest release, updating users with the masterKey should let any ACL be set. We still want to ensure a user can’t accidentally lock himself out, there has been some discussion around it. I’d gladly review a PR, that softens the possible updates on ACL’s while preserving enough safety.

**Comment by mullwaden** [comment]
@flovilmart yes the ACL is possible to set but does not reflect what can actually be done since ``Auth.prototype.couldUpdateUserId`` would still block any changes by another user. 

Made a simple PR #4792

**Comment by aBuder** [comment]
@mullwaden This PR would make me happy and solve the problem 👍🏻
