### ISSUE TITLE
How to query object contain in field type array of pointer?

### ISSUE THREAD

**Issue by sonysm** [parse-community/parse-server#4659]
Hello,

I have one question about query object
Example my data has field "students" type as array pointer of "student" class

students [
    {"__type":  "pointer", className: "student",  "objectId": "123"},
    {"__type":  "pointer", className: "student",  "objectId": "1234"},
]

I want get all field has student object (objectId: 123)

Anyone can help please?
sorry for my poor English

**Comment by dplewis** [comment]
@sonysm Why not use [Parse Relations](http://docs.parseplatform.org/js/guide/#many-to-many-relationships)? You can then query for whatever object you want.

Its easier to maintain than an Array of Pointers

**Comment by acinader** [comment]
From the JS guide:

"Arrays are ideal when we know that the number of objects involved in our one-to-many relationship are going to be small. Arrays will also provide some productivity benefit via the includeKey parameter."

@sonysm https://docs.parseplatform.org/js/guide/#using-arrays

```
const needle = {"__type": "pointer", className: "student", "objectId": "123"};
new Parse.Query('XXX').equalTo('student', needle).find();
```

that should do it.

**Comment by Guinto** [comment]
> From the JS guide:
> 
> "Arrays are ideal when we know that the number of objects involved in our one-to-many relationship are going to be small. Arrays will also provide some productivity benefit via the includeKey parameter."
> 
> @sonysm https://docs.parseplatform.org/js/guide/#using-arrays
> 
> ```
> const needle = {"__type": "pointer", className: "student", "objectId": "123"};
> new Parse.Query('XXX').equalTo('student', needle).find();
> ```
> that should do it.

Make sure to capitalize ```Pointer```

**Comment by kimi21** [comment]
instead of hardcoding 123 in objectId, how could we keep it variable, what would be the correct syntax then?

**Comment by RaschidGithub** [comment]
> instead of hardcoding 123 in objectId, how could we keep it variable, what would be the correct syntax then?

I guess this way:

```
const id = "123";
const needle = {"__type": "pointer", className: "student", "objectId": id};
new Parse.Query('XXX').equalTo('student', needle).find();
```
