### ISSUE TITLE
Running Schema.purge on empty table fails

### ISSUE THREAD

**Issue by mullwaden** [parse-community/parse-server#4664]
### Issue Description

Running purge on a schema with no data rows fails

### Steps to reproduce

Run the following code for some schema. If there are no rows in the database it will fail

```
const schema = new Parse.Schema('Machine');
schema.purge();
```

#### Expected Results

If the table has no rows then nothing should happen

#### Actual Outcome

Where my script that runs the code above gives an unhandledPromiseRejectionWarning.

My server gives the following error:

```
[1] error: Error generating response. ParseError { code: 101, message: 'Object not found.' } code=101, message=Object not found.
[1] error: Object not found. code=101, message=Object not found.
```

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 1.11.1
  - Operating System:     Windows 10
  - Localhost

- **Database**
  - postgreSQL 9.6.5

### Logs/Trace

See above

**Comment by dplewis** [comment]
Thanks for reporting. I wasn't able to replicate your error exactly but I did find an error. I'll submit a fix soon.

**Comment by mullwaden** [comment]
Looks like that is the issue, nice solve, thanks

**Comment by dplewis** [comment]
No Problem!
