### ISSUE TITLE
simple-mailgun-adapter

### ISSUE THREAD

**Issue by jferrer21** [parse-community/parse-server#4666]
Parse Server 2.7.4

Could the repository be updated to avoid the below warming during installation?

warning parse-server > @parse/simple-mailgun-adapter > mailgun-js > proxy-agent > socks-proxy-agent > socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0

**Comment by flovilmart** [comment]
Feel free to open a pull request.
