### ISSUE TITLE
publicServerURL has no effect on link sent in verification email

### ISSUE THREAD

**Issue by anandundavia** [parse-community/parse-server#4671]
### Issue Description

The `publicServerURL` has no effect on the verification link sent in the email.
I have enabled email verification in my project.
I have set publicServerURL to 'http://abc.com' ( for e.g. )

When I run the application locally, and try to sign up, the verification URL in the email starts with 
my local address ( 127.0.0.1 ) but not the value I set in the publicServerURL  

I know that ideally, because I am running the application locally, it should point me to my localhost.
But because I am explicitly setting the `publicServerURL`, should not it point me to that URL?

### Steps to reproduce

Set up parse server
While setting up, set 

```
verifyUserEmails: true, 
publicServerURL: 'http://abc.com'
```

Now try to sign up.
Check the your email.

The verification url starts with `http://127.0.0.1:4000` rather than  `http://abc.com`

#### Expected Results

Verification Link should start with `publicServerURL` ( http://abc.com for example ) 

#### Actual Outcome

Verification Link starts with `http://127.0.0.1:4000` ( the address on which my parse-server is running)

### Environment Setup

- **Server**
  - parse-server version : [2.7.4]
  - Operating System:     [Windows 7, MacOS 10.12]
  - Hardware:             [FILL THIS OUT]
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): [localhost]

- **Database**
  - MongoDB version: [FILL THIS OUT]
  - Storage engine:  [FILL THIS OUT]
  - Hardware:        [FILL THIS OUT]
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): [Azure Cloud]

**Comment by faladinojames** [comment]
Can you show your full Parse Server configuration?
