### ISSUE TITLE
Custom oAuth2 stopped working

### ISSUE THREAD

**Issue by markuswinkler** [parse-community/parse-server#4677]
### Issue Description

I have a custom oAuth2 configuration for linkedIn that worked fine until recently.
The oAuth2 redirect url doesn't get handled anymore.
Anyone else ran into that problem?

#### Expected Results
redirect to the custom oAuth2 handler

#### Actual Outcome
displays "Cannot get /oauth/linkedin"

### Environment Setup

config file:
```
const api = new ParseServer({
	databaseURI: databaseUri,
	databaseOptions: {
		poolSize: 10,
		reconnectTries: 15,
		socketOptions: {keepAlive: 1, connectTimeoutMS: 30000},
		auto_reconnect: true
	},
	cloud: process.env.CLOUD_CODE_MAIN || __dirname + "/cloud/main.js",
	appId: process.env.APP_ID,
	masterKey: process.env.MASTER_KEY,
	serverURL: process.env.SERVER_URL,
	enableAnonymousUsers: false,
	allowClientClassCreation: false,
	facebookAppIds: process.env.PARSE_SERVER_FACEBOOK_APP_IDS,
	auth: {
		facebook: {
			appIds: [process.env.PARSE_SERVER_FACEBOOK_APP_IDS ]
		},
		linkedin_crypt: {
			module: "../../../../cloud/linkedin_encrypt.js"
		}
	},
	push: {
		adapter: oneSignalPushAdapter
	}
});
```

- **Server**
  - parse-server version : 2.7.4
  - Operating System:     AWS Linux

**Comment by flovilmart** [comment]
Parse server doesn’t handle oauth redirection for you, so have a look into the LinkedIn documentation, they may have changed something there.

**Comment by markuswinkler** [comment]
Found what caused it. iOS >= 11.2 breaks Universal Links. 😡
Work around was to use a UIWebView with a local url scheme instead of SFSafariViewController.
Thought I post this here in case anybody else runs into this issue.
