### ISSUE TITLE
Aggregation match doesn't seem to work with date value

### ISSUE THREAD

**Issue by SebC99** [parse-community/parse-server#4678]
### Issue Description

When using the new aggregate options with a match pipeline on a Date value, it silently fails with empty result.
By the way, to match a `createdAt` or a `updatedAt` field, we have to use the db form `_created_at` / `_updated_at`, and I'm not sure it's on purpose. Either way, we can't query them with the standard `$lt` or `$gt` operator.

### Steps to reproduce

`query.aggregate([{match: {_created_at:{$lt:new Date()}}}])` always returns `[]`
whereas
`query.aggregate([{match: {_created_at:{$exists:true}}}])` works perfectly.

#### Expected Results

Both results should be the same

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.7.4
  - Localhost or remote server? Localhost

- **Database**
  - MongoDB version: 3.4
  - Storage engine: WiredTiger
  - Localhost or remote server? Mongo Atlas

**Comment by dplewis** [comment]
Thanks for reporting. I'll have a look.

**Comment by sauravazad** [comment]
I have been facing the same issue and it is related to only Date fields , number  works fine.

**Comment by eleynes** [comment]
Any updates on this? TIA

**Comment by fmendoza** [comment]
Same here

**Comment by dplewis** [comment]
Sorry guys been off the grid.

I'll submit a PR sometime this week.

**Comment by cjbland** [comment]
FWIW, in my debugging last night (if I remember correctly) `MongoStorageAdapter.js` was converting a `Date` object into a string, and the mongodb adapter did not seem to like that. Tonight I'll modify the code to keep it a `Date` object and see if that makes a difference.

**Comment by cjbland** [comment]
Yes, this was definitely it. When I converted the strings to `new Date()` and passed that on. Then I started getting results back. Within `MongoStorageAdapter.js` within the `aggregate` method I added check on `schema.fields[field]` to see if it was a date. If so, I convert the string into a `Date` object. That seems to do the trick. I can make a PR if you'd like to review the code.

**Comment by flovilmart** [comment]
Go ahead with the PR! That sound like a good fiz

**Comment by dreadful44** [comment]
Same bug for me.

**Comment by dplewis** [comment]
Closed via https://github.com/parse-community/parse-server/pull/4743

**Comment by pixel2** [comment]
I have the same problem as @anhnhv2812. Could you please create a new bug so we can track and try and get this fixed, or do you want me to do it?

**Comment by SebC99** [comment]
I have the same issue, and with custom fields that are created by the aggregation pipeline, and not in the base Schema, the dates are not detected.
Modifying the `_parseAggregateArgs` method in the MongoStorageAdapter file to add a 
```
} else if (pipeline instanceof Date) {
      return pipeline;
}```
condition before the `if (typeof pipeline === 'object')` seems to work, but I'm not sure of the repercussion of this.

Anyway, testing the schema in all the pipeline is weird as all the fields can be changed/removed/added at every stage, so the schema is not coherent anymore.
As for the `isPointerField` condition which is set during any `$group` stage and used to change the final `$_id` of the last stage of the pipeline... I just don't understand why, but it results in weird `_id` deletion (but I'm far from understanding all that code) 😅

**Comment by adrianaxente** [comment]
There is another work-around :
```
{
            'match': {
                "$expr": {
                    "$lte": [
                        "$lastState.date", 
                        {
                            "$toDate": "2020-09-09T00:00:00.000Z" 
                        }
                    ]
                }
            }
        },
```
Where "2020-09-09T00:00:00.000Z"  can be used as string.
Hope it helps someone till the fix will be available in the following releases.

**Comment by ilovett** [comment]
Thanks for the workaround @adrianaxente

**Comment by andreisucman** [comment]
Here is the new syntax for Parse v6 +
It aggregates rows by date and counts the number of occurences within a date.

  ```
const pipeline = [
    {
      $group: {
        _id: { $dateToString: { format: "%Y-%m-%d", date: "$createdAt" } },
        count: {
          $sum: 1,
        },
      },
    },
  ];

```
```
    const query = new Parse.Query("Table");
    const qResult = await query.aggregate(pipeline);
```

Not that unlike in previous versions you use _id instead of objectId, and you must prefix the stages with $ just like directtly in MongoDB
