### ISSUE TITLE
Email Unverified error returns even with Incorrect Password

### ISSUE THREAD

**Issue by dblythy** [parse-community/parse-server#4693]
### Issue Description

Logging in with an incorrect password returns email unverified instead of incorrect username or password. I am giving users the option to use  /verificationEmailRequest on error code 205, however error code 205 returned on incorrect password.

### Steps to reproduce

Create an account with preventLoginWithUnverifiedEmail set to true. Login immediately with incorrect password and error will be "email not verified".

#### Expected Results

Incorrect password error.

#### Actual Outcome

Email not verified error.

### Environment Setup

- **Server**
  - parse-server version: 2.7.4
  - Localhost

**Comment by paulovitin** [comment]
Im not understand the wrong behavior. 

The docs says: `set preventLoginWithUnverifiedEmail to true to prevent user from login if their email is not verified`

So, if you set true, the error returned its correct. I missing something?

**Comment by dblythy** [comment]
I want to prompt unverified users after login (correct password) with "resend verification email". Point being, they can find out a users email address before they verify their email.

Just as an incorrect password returns "invalid email/password", not "invalid password" to hide a database users email, incorrect password before verification returns "unverified email" - revealing an unverified user's email.

**Comment by paulovitin** [comment]
@montymxb can you help here?

**Comment by dblythy** [comment]
Potentially, if a malicious user brute forced emails, all they would need is to attempt login and search for error 205 to get a users email. Then wait until they verify and brute force password.

**Comment by flovilmart** [comment]
Can one of you open a PR to reverse the order of the errors?

**Comment by dblythy** [comment]
Yep! Will do.
