### ISSUE TITLE
addAllUnique() on Parse.User is not a function 

### ISSUE THREAD

**Issue by venkataramanab** [parse-community/parse-server#4704]
### Issue Description

Parse.User.addAllUnique() is not a function

### Steps to reproduce

Used on Parse Cloud Code on beforeSave(Parse.User,{})

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.7.4
  - Operating System:     Mac 10.10.5
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): localhost

- **Database**
  - MongoDB version: mongodb-core: 2.1.15
  - Storage engine:  WiredTiger
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): localhost

### Logs/Trace

Include all relevant logs. You can turn on additional logging by configuring VERBOSE=1 in your environment.

```
user ParseUser { _objCount: 0, className: '_User' }
error: Error generating response. ParseError {
  code: 141,
  message: TypeError: user.addAllUnique is not a function
    at /Users/venkataramana/Documents/parse-server/cloud2.js:180:18
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7) } code=141, 
```

**Comment by flovilmart** [comment]
Can you double check your parse server and JS SDK version? Are those methods available on any other object?

**Comment by venkataramanab** [comment]
After updating to parse@1.11.1 resolved my Issue.

**Comment by venkataramanab** [comment]
before updating to parse@1.11.1, I didn't see this in ParseObject.js
```
{
    key: 'addAllUnique',
    value: function (attr, items) {
      return this.set(attr, new _ParseOp.AddUniqueOp(items));
    }
```

**Comment by flovilmart** [comment]
Awesome!
