### ISSUE TITLE
One user one session only?

### ISSUE THREAD

**Issue by mchun** [parse-community/parse-server#4705]
I have just updated parse-server to the latest (2.7.4) from 2.3.x and noticed a different behaviour about session. When a user login in multiple devices, instead of creating multiple session objects, session object is being overwritten, and so the user is kicked out in other devices. When is this change introduced and can I revert back to the previous one, where multiple session for the same user is allowed?

**Comment by mchun** [comment]
The old session is not overwritten but deleted instead, as I find the new session objectId is different.

**Comment by flovilmart** [comment]
Sessions should not be deleted as long as a different installation ID is provided. Can you provide the logs on the server please when running with VERBOSE=1

**Comment by flovilmart** [comment]
Also, 2.3.x is a year old, you should probably stick to more frequent updates.

**Comment by mchun** [comment]
I do not touch any session object by myself and am doubt if the new parse-server does that somewhere. I have just downgraded back to 2.3.8 and the problem is gone now.

**Comment by flovilmart** [comment]
Can you provide the logs when running with VERBOSE=1 please?

**Comment by flovilmart** [comment]
You’re logging in inside a cloud function, you need to pass the installationId that made the request (req.installationId) into your login call in the cloud function.

**Comment by mchun** [comment]
Thanks!

after changing :
Parse.User.logIn(phoneNumber , password)
to:
Parse.User.logIn(phoneNumber , password, { installationId : req.params.installationId })

The problem has been solved.

**Comment by refre5h** [comment]
@flovilmart Thanks for the tips! But one question, does the installationId passed to the login call have anything to do with the installationId in the `Installation` class? I searched around and couldn't find any docs about it.

**Comment by refre5h** [comment]
I have iOS, Android and Web relying on the same cloud call to return the session token. iOS and Android have the installationId, but there isn't one for the web.

I tried hardcoding a random installationId for the web, and it seems working, but I'm not sure if this is the right way to do it. Can you advice?
