### ISSUE TITLE
Cannot create index with default field

### ISSUE THREAD

**Issue by ClaireNeveu** [parse-community/parse-server#4714]
### Issue Description
I am attempting to create an index that involves teh `updatedAt` field. Parse rejects such a request claiming that the field does not exist. It looks like the issue is that [`updateClass`](https://github.com/parse-community/parse-server/blob/master/src/Controllers/SchemaController.js#L516) gets the list of current fields from [`buildMergedSchemaObject`](https://github.com/parse-community/parse-server/blob/master/src/Controllers/SchemaController.js#L957) which explicitly filters out the default fields. Further, the default fields are named differently in Parse and Mongo so it seems there would need to be some translation occuring (`updatedAt` to `_updated_at`)

### Steps to reproduce
1. Create a collection of the name Foo.
2. `curl -X PUT http://localhost:7345/1/schemas/Foo -H 'content-type: application/json' -H "X-Parse-Application-Id: the_application_id" -H "X-Parse-Master-Key: the_master_key" -d '{"className":"Foo","indexes":{"testestest":{"_updated_at":1}}}'`

#### Expected Results

An index named `testestest` is created.

#### Actual Outcome

Parse returns an error: `Field _updated_at does not exist, cannot add index.`

### Environment Setup

- **Server**
  - parse-server version: 2.7.4
  - Operating System:     Arch Linux
  - Hardware:             EC2 or Thinkpad
  - Localhost or remote server? (AWS): Either

- **Database**
  - MongoDB version: 3.2
  - Storage engine:
```
rs0:PRIMARY> db.serverStatus().storageEngine
{
	"name" : "wiredTiger",
	"supportsCommittedReads" : true,
	"readOnly" : false,
	"persistent" : true
}
```
  - Hardware:        Same as above
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): Same as above

**Comment by flovilmart** [comment]
Thanks for reporting the issue. If you specify `updatedAt` as the field to index, does it work?

**Comment by ClaireNeveu** [comment]
Ah yes, I should have specified that neither `updated_at` nor `updatedAt` work.

**Comment by flovilmart** [comment]
thanks! That helps
