### ISSUE TITLE
How to implement Parse query properly to get ordered data?

### ISSUE THREAD

**Issue by ashish-naik** [parse-community/parse-server#4717]
### Issue Description

I have below code to build a query out of two queries.

Issue is result is not sorted by updatedAt.

What could be the issue?

```
let ownerQuery = PFQuery(className: "requests")
ownerQuery.whereKey("owner", equalTo: forUser)
ownerQuery.whereKey("stage", containedIn: ["initiated"])

let requestQuery = PFQuery(className: "requests")
requestQuery.whereKey("requested_by", equalTo: requestedBy)
requestQuery.whereKey("stage", containedIn: ["accepted"])

// fetch all request of current user as requestor or lender/seller
let query = PFQuery.orQuery(withSubqueries: [ownerQuery, requestQuery])

query.includeKey("requested_by")
query.includeKey("owner")
query.order(byDescending: "updatedAt")
```

### Steps to reproduce

Build query as above.

#### Expected Results

Rows fetched ordered by updatedAt date

#### Actual Outcome

Parse gives unordered roes.

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.5.3
  - Operating System:     dont know
  - Hardware:             dont know
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Heroku

- **Database**
  - MongoDB version: 3.4.7 (MMAPv1)
  - Storage engine:  dont know
  - Hardware:        dont know
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): mLab

### Logs/Trace

dont have

**Comment by flovilmart** [comment]
Can you provide the logs when running with VERBOSE=1 please?

**Comment by ashish-naik** [comment]
Pls see the log

 [36mverbose[39m: RESPONSE from [GET] /parse/classes/requests: {
   "response": {
     "results": [],
     "count": 7
   }
 } results=[], count=7
 [36mverbose[39m: REQUEST for [GET] /parse/classes/requests: {
   "limit": "20",
   "include": "owner,requested_by",
   "order": "-updatedAt",
   "where": {
     "$or": [
       {
         "owner": {
           "__type": "Pointer",
           "className": "_User",
           "objectId": "DyxDFCN9W0"
         },
         "stage": {
           "$in": [
             "initiated"
           ]
         }
       },
       {
         "stage": {
           "$in": [
             "accepted"
           ]
         },
         "requested_by": {
           "__type": "Pointer",
           "className": "_User",
           "objectId": "DyxDFCN9W0"
         }
       }
     ]
   }

**Comment by flovilmart** [comment]
I don't see the ordering issue in your logs as there's no results :)

**Comment by flovilmart** [comment]
It’s up to you to see how to resolve this issue, there are plenty of possible avenues.

**Comment by ashish-naik** [comment]
Yes I understand. Thanks for suggesting verbose mode.
