### ISSUE TITLE
Broken Mail Verification: Invalid Verification Link

### ISSUE THREAD

**Issue by funkenstrahlen** [parse-community/parse-server#4718]
### Issue Description

I can not verify user mails. I always get `invalid verification link`.

![screen shot 2018-04-12 at 16 46 36](https://user-images.githubusercontent.com/144173/38684995-3cffebe8-3e71-11e8-9324-779b75901adc.png)

My mail configuration:

```json
  verifyUserEmails: true,
  emailVerifyTokenValidityDuration: 48 * 60 * 60, // in seconds (2 hours = 7200 seconds)
  preventLoginWithUnverifiedEmail: false, 
```

I checked for the verification token in the database:

![screen shot 2018-04-12 at 16 48 08](https://user-images.githubusercontent.com/144173/38685049-53a42620-3e71-11e8-89eb-5494cb889ac9.png)

It does set both values correctly after changing the mail address of a user.

This is the verification link it generates:

`https://myserver.com/parse/apps/skgjhsfgkjhkjhsfdgkjh/verify_email?token=XmLufY59n3gMxDWQi5mOI6q5Z&username=funkenstrahlen`

This does look very promising.

### Steps to reproduce

* Change user mail address
* Click generated verification link

#### Expected Results

Mail is verified

#### Actual Outcome

Invalid verification link error

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.7.4
  - Operating System:     [FILL THIS OUT]
  - Hardware:             Heroku Hobby
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Heroku

- **Database**
  - MongoDB version: [FILL THIS OUT]
  - Storage engine:  [FILL THIS OUT]
  - Hardware:        [FILL THIS OUT]
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): mLab

**Comment by flovilmart** [comment]
Thanks for reporting the issue! Any chance you want to attempt to fix it?

**Comment by funkenstrahlen** [comment]
@flovilmart I already had a look at the code but could not find the source of the issue. Unfortunately I can not provide a PR with a fix in this case.

**Comment by flovilmart** [comment]
We’ll have a look then!

**Comment by funkenstrahlen** [comment]
I initially thought that this issue might be related: https://github.com/parse-community/parse-server/issues/4369 

However as you can see in my bug report I confirmed the expiration times are correct.

**Comment by funkenstrahlen** [comment]
This is the relevant area in the code: https://github.com/parse-community/parse-server/blob/db8594dd33566af7bd51da93658f85bf735fdcb1/src/Controllers/UserController.js#L44-L70

**Comment by funkenstrahlen** [comment]
I discovered the problem! I do have some before save cloud code trigger on the user object. I expected `request.original` to always be set in my cloud code. However when the before save is triggered by the request to update the mail verification `request.original` is undefined.

In this case my before save trigger failed and therefore the database update request failed.
