### ISSUE TITLE
Parse creates incorrect index for pointer columns

### ISSUE THREAD

**Issue by ClaireNeveu** [parse-community/parse-server#4719]
### Issue Description

Describe your issue in as much detail as possible.

### Steps to reproduce

1. Create a collection of the name `Foo` with a column `testCol` which is a Pointer to `Foo` (or any class)
2. `curl -X PUT http://localhost:7345/1/schemas/Foo -H 'content-type: application/json' -H "X-Parse-Application-Id: the_application_id" -H "X-Parse-Master-Key: the_master_key" -d '{"className":"Foo","indexes":{"testestest":{"testCol":1}}}'`

#### Expected Results

Parse creates a mongo index on `_p_testCol` (the backing field of `testCol`).

#### Actual Outcome

Parse creates a mongo index on `testCol` (which doesn't exist in the mongo documents)
```console
> db.getCollection('Foo').getIndexes()
[
	{
		"v" : 1,
		"key" : {
			"_id" : 1
		},
		"name" : "_id_",
		"ns" : "parse.Foo"
	},
	{
		"v" : 1,
		"key" : {
			"testCol" : 1
		},
		"name" : "testestest",
		"ns" : "parse.Foo"
	}
]
```
### Environment Setup

- **Server**
  - parse-server version: 2.7.4
  - Operating System:     Arch Linux
  - Hardware:             Thinkpad
  - Localhost or remote server? (AWS): localhost

- **Database**
  - MongoDB version: 3.2
  - Storage engine:
```
rs0:PRIMARY> db.serverStatus().storageEngine
{
	"name" : "wiredTiger",
	"supportsCommittedReads" : true,
	"readOnly" : false,
	"persistent" : true
}
```
  - Hardware:        Same as above
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): Same as above

**Comment by ClaireNeveu** [comment]
Updating this now that https://github.com/parse-community/parse-server/pull/4738 is merged to note that the indices created for `objectId`, `createdAt`, and other default fields is likewise incorrect. We'll need to implement a mapping layer in the mongo adapter which should handle all these cases.

**Comment by dplewis** [comment]
@ClaireNeveu I've added a fix to this in https://github.com/parse-community/parse-server/pull/4629

**Comment by ClaireNeveu** [comment]
@dplewis In your PR shouldn't the `_id_` index be `{ objectId: 1 }` instead of `{ _id: 1 }`?
