### ISSUE TITLE
Role is not working correctly. Permission denied for action find on class. (Code: 119)

### ISSUE THREAD

**Issue by rogerfanfan** [parse-community/parse-server#4720]
### Issue Description
I have a role named "vipUser" and set relation to every user. 
And I set CLP and ACL in some class that only vipUser can read and write. 
But when user query these class, user get "Permission denied for action find on class. (Code: 119)".

#### Expected Results
Query will have results. [PFObject]

#### Actual Outcome
Permission denied for action find on class. (Code: 119)

### Environment Setup
- **Server**
  - parse-server version : 2.3.8
  - Operating System:
  - Hardware:
  - Localhost or remote server? : Parse server on Azure

- **Database**
  - MongoDB version: 
  - Storage engine:
  - Hardware:
  - Localhost or remote server? : Azure Cosmos DB

**Comment by flovilmart** [comment]
Can you provide your schema as well as the logs when running with VERBOSE=1 and reopen the issue?
