### ISSUE TITLE
Postgres doesn't support this query type yet {"$nin":[]}

### ISSUE THREAD

**Issue by repertory** [parse-community/parse-server#4727]
### Issue Description

request:

> users:  RELATION <_USER> and this relation has no rows

```
where: {users: {$exists: false, $ne: {__type: "Pointer", className: "_User", objectId: "hXqhAUjRz2"}}}
```
response:

```
{"code":119,"error":"Postgres doesn't support this query type yet {\"$nin\":[]}"}
```

**Comment by dplewis** [comment]
Can you get the logs when running with VERBOSE=1?

Or provide a query?

**Comment by repertory** [comment]
I have switched to mongo

**Comment by dplewis** [comment]
@repertory Sorry we took so long. Thank you for using parse. If you want to help with the issue you opened that would be great, in case anybody else would run into the issue.

**Comment by CoderickLamar** [comment]
Hoping we can get this re-opened. If someone can direct me in the right direction on this, I can try and take a look

**Comment by dplewis** [comment]
@CoderickLamar There isn't enough info in the original post and no logs posted. Hard to reproduce.

**Comment by CoderickLamar** [comment]
We're experiencing the same issue on our end. Let me see if I can grab more details and update this post with our info

**Comment by jwenBai** [comment]
I also have this issue. It works fine when the array is not empty, but when the array is empty it causes the issue.

the query that I used:
```
const testQuery = new Parse.Query('testTable');
  testQuery.notContainedIn('value', []);
  testQuery.find().then((testObj) => {
    console.log(testObj);
  });
```

and the error message :
```
debug: PG: find testTable { value: { '$nin': [] }, _rperm: { '$in': [ null, '*' ] } } skip=undefined, limit=100, , keys=undefined
error: Error generating response. ParseError {
  code: 119,
  message: 'Postgres doesn\'t support this query type yet {"$nin":[]}' } code=119, message=Postgres doesn't support this query type yet {"$nin":[]}
error: Postgres doesn't support this query type yet {"$nin":[]} code=119, message=Postgres doesn't support this query type yet {"$nin":[]}
```

**Comment by vijay259** [comment]
Make sure that  { '$nin': [] } should not empty
