### ISSUE TITLE
include() in aggregate queries

### ISSUE THREAD

**Issue by fmendoza** [parse-community/parse-server#4728]
I'm trying to show the pointer data but it seems is not supported?

```javascript
let query = new Parse.Query('MyObject')
query.include(['myPointer'])

let pipeline = {
    match: { sectionType: 'Used', status: 'Active', deletedAt: { '$exists': false } },
    sample: { size: 10 }
}

let result = await query.aggregate(pipeline)
```

#### Expected Results

myPointer field should return all database fields

#### Actual Outcome

myPointer only return className, objectId and __type fields.

### Environment Setup

- **Server**
  - parse-server version: 2.7.4
  - Operating System: Mac
  - Hardware:  Macbook Pro
  - Localhost or remote server?: Localhost

- **Database**
  - MongoDB version: 3
  - Storage engine:  n/a
  - Hardware: Macbook
  - Localhost or remote server? : Localhost

### Logs/Trace

n/a

**Comment by dplewis** [comment]
Its currently not supported. Since you are using aggregate you can use $lookup (left join) https://github.com/parse-community/parse-server/issues/1908#issuecomment-371589760

Feel free to open a PR. I'm a bit surprised that `mypointer` returned data without using `project` stage.
