### ISSUE TITLE
when  afterUpdate:'afterUpdate'

### ISSUE THREAD

**Issue by bughp** [parse-community/parse-server#4729]
const Types = exports.Types = {
  beforeSave: 'beforeSave',
  afterSave: 'afterSave',
  beforeDelete: 'beforeDelete',
  afterDelete: 'afterDelete',
  beforeFind: 'beforeFind',
  afterFind: 'afterFind',
  beforeUpdate:'beforeUpdate',
  afterUpdate:'afterUpdate'
};
  beforeUpdate:'beforeUpdate',
  afterUpdate:'afterUpdate'

**Comment by flovilmart** [comment]
You can use beforeSave
