### ISSUE TITLE
ACL REST query failure, no results

### ISSUE THREAD

**Issue by GoGross** [parse-community/parse-server#4739]
Everything up to date with MongoDB 3.4

**This works just fine:**

`let Q = Parse.Object.extend ( 'settings' );`
	    `let q   = new Parse.Query ( Q );`
	    `q.find ().then ( function ( results ) {`
		        `console.log( results )`
	`} );`

**Yet the same doesn't when I use REST**

`curl -X GET \
  -H "X-Parse-Application-Id: ${APPLICATION_ID}" \
  -H "X-Parse-REST-API-Key: ${REST_API_KEY}" \
  -G \
  base + /classes/settings`

What am I missing? Do I have to query the ACL somehow?

**Comment by GoGross** [comment]
@flovilmart Please help

**Comment by flovilmart** [comment]
Can you get the logs when running with VERBOSE=1 for both of your requests?

**Comment by GoGross** [comment]
Sorry mate for wasting your time, it turns out I need to include the session token in the header: `'X-Parse-Session-Token' ` not sure if it's the ideal method

**Comment by flovilmart** [comment]
This is mainly why we ask for the VERBOSE logs when opening the issues

**Comment by GoGross** [comment]
I will take note of that next time
