### ISSUE TITLE
Isolating background jobs execution

### ISSUE THREAD

**Issue by fcoufour** [parse-community/parse-server#4741]
My background jobs are very CPU consuming and I do not want them to affect the quality of service during execution.

My Parse Server is configured with PARSE_SERVER_ENABLE_EXPERIMENTAL_DIRECT_ACCESS to 1 so the local requests do not use the HTTP layer. If I disable it, I could eventually use Nginx rate limiting to slow down only the requests made by the background jobs.

A better option would be to configure Parse Server so that the executed background jobs are run in a specific process (on a dedicated CPU core) but I wonder if it is possible.

_If anyone has already faced this problem or see a good way to solve it, I listen carefully :)._

**Comment by flovilmart** [comment]
You can run the instance of parse-server on a separate instance / docker container so your regular traffic don’t hit it.

**Comment by fcoufour** [comment]
Guys, thanks for your feedback.

I decided to run 2 Parse Server apps on the same machine and with the same config file thanks to PM2. Only the port differs.

The default Parse Server (used for my regular traffic) is started in cluster mode (as many processes as possible). The inner Parse Server (only used to run the background jobs) is started in fork mode (1 process).

I'm pretty satisfied and I'm now looking for a way to set the core affinity so that both do not interfere with each other. Any idea?

**Comment by fcoufour** [comment]
Autoresponse :): there is no such a feature on PM2 at the moment according to the support team.

We can set the core affinity using taskset once the processes are started.
