### ISSUE TITLE
QueryRelation.setLimit(); doesn't work

### ISSUE THREAD

**Issue by JoaoArmandoo** [parse-community/parse-server#4748]
Hello everyone, I think there is a problem with .setLimit (); in relationships, it just does not work, and returns 0 objects, when I put .setLimit (100); or when it is without .setLimit (); everything works fine, but this causes a poor user experience, taking into consideration the response time to recover many objects is much higher.

_My code:_
```
 final ParseRelation<ParseObject> relation = obj.getRelation("user_feeds");
                            final ParseQuery queryRelation = relation.getQuery();
                            queryRelation.setLimit(3);
                            queryRelation.orderByAscending("createdAt");
                            queryRelation.include("createdByUserInfo");
                            queryRelation.findInBackground...
```
I'm using:  _**compile 'com.parse:parse-android:1.15.8'**_

**Comment by flovilmart** [comment]
Please reopen the issue providing all requested informations in the issue template, including version and logs.
