### ISSUE TITLE
Adding multiple users to a role behaves unexpectedly

### ISSUE THREAD

**Issue by mullwaden** [parse-community/parse-server#4755]
### Issue Description

When adding multiple users to a Role i get a strange behavior, only the first added user is actually added to the Roles users Relationship list. (in the code below users is an array of 2 users). The log in the bottom shows for Case3 - looks like nothing is being sent in the request to add the second user.

Case1: __works__ - both users are in the relationship
```
userRole.getUsers().add(users);
userRole.save(null, { useMasterKey: true });
```

Case2: Does __not__ work - only first user is in the relationship
```
users.forEach((user) => {
  userRole.getUsers().add(user);
});

userRole.save(null, { useMasterKey: true });
```

Case3: Also does not work (!!) - only first user is in the relationship
```
Promise.resolve().then(() => {
  userRole.getUsers().add(users[0]);
  return userRole.save(null, { useMasterKey: true });
})
.then((updatedRole) => {
  updatedRole.getUsers().add(users[1]);
  return updatedRole.save(null, { useMasterKey: true });
});
```

### Steps to reproduce

- I run the code above in a cloud function
- The users are created in the back-end beforehand, so is the role

#### Expected Results

All three versions of the code above should give the same results

#### Actual Outcome

Only in case1 are both users added

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.):
      "parse": "1.11.1",
      "parse-dashboard": "1.2.0",
      "parse-server": "2.7.4",
  - Operating System:     windows 10 as well as heroku
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): both

- **Database**
  - Using postgres

### Logs/Trace

```
verbose: REQUEST for [PUT] /parse/classes/_Role/iA3kp6gLdY: {
  "users": {
    "__op": "AddRelation",
    "objects": [
      {
        "__type": "Pointer",
        "className": "_User",
        "objectId": "rfpZtgufYD"
      }
    ]
  }
} method=PUT, url=/parse/classes/_Role/iA3kp6gLdY, user-agent=node-XMLHttpRequest, Parse/js1.11.1 (NodeJS 8.9.4), accept=*/*, content-type=text/plain, host=127.0.0.1:1337, content-length=266, connection=close, __op=AddRelation, objects=[__type=Pointer, className=_User, objectId=rfpZtgufYD]

verbose: RESPONSE from [PUT] /parse/classes/_Role/iA3kp6gLdY: {
  "response": {
    "updatedAt": "2018-05-09T12:30:02.902Z"
  }
} updatedAt=2018-05-09T12:30:02.902Z

verbose: REQUEST for [PUT] /parse/classes/_Role/iA3kp6gLdY: {
  // THERE IS NOTHING HERE!!!
} method=PUT, url=/parse/classes/_Role/iA3kp6gLdY, user-agent=node-XMLHttpRequest, Parse/js1.11.1 (NodeJS 8.9.4), accept=*/*, content-type=text/plain, host=127.0.0.1:1337, content-length=158, connection=close,
verbose: RESPONSE from [PUT] /parse/classes/_Role/iA3kp6gLdY: {
  "response": {
    "updatedAt": "2018-05-09T12:30:02.918Z"
  }
} updatedAt=2018-05-09T12:30:02.918Z
```

**Comment by georgesjamous** [comment]
Thats weird, I usually do what you do in Case1, never tried any of the other cases.

Regardless,
Case3 should work, can you make sure that users[1] is in fact a _User object with an .id ?
I can see no reason why it shouldn't work
