### ISSUE TITLE
Multi Database support

### ISSUE THREAD

**Issue by aBuder** [parse-community/parse-server#4756]
Hi, 

This is an question or an feature that would be really great. I don't no if it is implemented yet. So is there an solution that  I can connect multi databases, so that Parse supports multitenancy. 
![zrzut-ekranu-z-2014-01-12-211329](https://user-images.githubusercontent.com/1265139/39820685-ad9979a6-53a6-11e8-9143-59ae09c20ae7.png)

**Comment by flovilmart** [comment]
the issue is not with the database but with the cloudcode runtime. Multi tenancy has been heavily discussed in the past, but we will not support it nor actively work on it. 

See: https://github.com/parse-community/parse-server/pull/263
