### ISSUE TITLE
2.8.1 Request time out for one db collection ...?

### ISSUE THREAD

**Issue by gateway** [parse-community/parse-server#4773]
### Issue Description

Upgrading to the latest build 2.8.1 and testing our iPhone app, we are getting a request time out on one of our db inserts.

2018-05-18T20:08:53.099693+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=POST path="/parse/classes/PrivateUserData" host=xxxx.herokuapp.com request_id=5d3b3f7b-xxx fwd="12.24.57.194" dyno=web.1 connect=1ms service=30000ms status=503 bytes=0 protocol=https

We have verbose enabled but nothing sticks outside of that .. kinda hard to debug from here :/ I'm going to try to rollback to test some more .. also if their is anymore verbose data we can provide or options let us know.. we are sorta stuck.. this has been working all until now.
### Steps to reproduce

Please include a detailed list of steps that reproduce the issue. Include curl commands when applicable.

#### Expected Results

What you expected to happen.

#### Actual Outcome

What is happening instead.

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.8.1
  - Operating System:     heroku
  - Hardware:             heroku dyno
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): heroku

- **Database**
  - MongoDB version: 3.4.7
  - Storage engine:  MMAPv1
  - Hardware:        xxx
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): Mlab

Also what version of Node should be running.. it defaults to 10.

`remote: -----> Installing binaries
remote:        engines.node (package.json):  >=4.3
remote:        engines.npm (package.json):   unspecified (use default)
remote:        
remote:        Resolving node version >=4.3...
remote:        Downloading and installing node 10.1.0...
remote:        Using default npm version: 5.6.0
`

**Comment by flovilmart** [comment]
> We have verbose enabled but nothing sticks outside of that 

It should still be intereting to see what is going on with the verbose logs. The request timeout can be caused by many things.

**Comment by gateway** [comment]
I agree, digging though the logs everything looks good. no errors crop up, the only error is the one I see, for some reason it wants to time out.. still digging  :/

what engine version should we be using.. 8.x?

**Comment by flovilmart** [comment]
All the same calls are timing out? Do you have cloud code before / afterSave hooks on this class ?

**Comment by gateway** [comment]
We have no cloud code for that function, basically only cloud code is to insert a user into a specific role, then remove any old _installation id's since when a user deletes the app and or reinstalls it thus allowing push it keeps old id's around.  Thats pretty much it during sign up.

I can confirm that the user is added to the role, and installation is added and if any old ones removed.. the same class keeps timing out..

**Comment by flovilmart** [comment]
For all calls ? Nothing particular otherwise in the payload? Is is reproducible all the times?

**Comment by gateway** [comment]
its 100% repo.. im going though the installation cloud code now.. just to make sure it returns a success.. its the oldest of the files listed..

**Comment by gateway** [comment]
Ok, fixed.. found some code another teammate did, that was doing a post request to another end point for some data.. that data requires auth and the token was expired.. sigh.. need a good way to deal with post data and gracefully failing.. that was the hold up.. this is not my code but an example of what was going on.. I remove the auth code for security.. please just nuke this post ..

sorry for wasting your time :/ its deff a friday for me :(

```
Parse.Cloud.beforeSave("PrivateUserData", function(request, response) {
  if(request.object.id != null) {
    //console.log('already exists');
    response.success(); 
  } else {
    var email = request.object.get("email")
    var fname = request.object.get("firstName")
    var lname = request.object.get("lastName")
    var zip = request.object.get("zipCode")
    /* debug
    console.log(email)
    console.log(fname)
    console.log(lname)
    console.log(zip)
    */
    
    // with facebook user we do not get zip.
    if (zip !== null || zip !== undefined || zip !== '') {
      var zipCode = request.object.get("zipCode")
    } else {
      var zipCode = '00000'
    }
        
    // make sure to change to use the right server end point.
    var link = 'https:// <api endpoint>

    //console.log(link);

    Parse.Cloud.httpRequest({
      //method: 'POST',
      url: link,
    }).then(function(httpResponse) {
      //console.log('in success for email')
      response.success();
      console.log(httpResponse.text);
      console.error('Request succeded with response code ' + httpResponse.status);
    }, function(httpResponse) {
      console.error('Request failed with response code ' + httpResponse.status);
    });
  }
});
```

**Comment by flovilmart** [comment]
But is it a regression with 2.8.1 or also breaking in the previous versions?

**Comment by gateway** [comment]
I thought it was since I updated today and saw it happen for the first time on our staging server.. so nothing with a parse server version, it was just a coincidence

**Comment by flovilmart** [comment]
Ok awesome!
