### ISSUE TITLE
Invalid key name: $relatedTo with Parse.Query.and

### ISSUE THREAD

**Issue by elios264** [parse-community/parse-server#4785]
### Issue Description

Parse server is rejecting `Parse.Query.and ` queries in conjution with relations, `Parse.Query.or` is working correctly.

my usecase is sending a push notification with complex query. therefore I need the `Parse.Query.and`

![usecase](https://user-images.githubusercontent.com/15863852/40507219-26573e66-5f5d-11e8-8183-6f2ac81cc459.PNG)

### Steps to reproduce
Not working:
![relations not working with and query](https://user-images.githubusercontent.com/15863852/40506814-f4550f4c-5f5c-11e8-840b-d1072d19d5c5.PNG)

Working:

![or is working](https://user-images.githubusercontent.com/15863852/40506958-051d3c14-5f5d-11e8-97e0-4613c2421bee.PNG)

#### Expected Results

`$relatedTo` to be supported.

#### Actual Outcome

an exception.

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.7.4
  - Operating System:     windows
  - Hardware:             my pc
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): local

- **Database**
  - MongoDB version: n/a
  - Storage engine:  n/a
  - Hardware:        n/a
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): mLab

**Comment by flovilmart** [comment]
Can you try with:

```
const installationsQuery = Parse.Query.or(....)
installationsQuery.equalTo('enabled', true);
installationsQuery.exists('user');
```

Also please provide the server logs when running with VERBOSE=1

**Comment by elios264** [comment]
Hey @flovilmart,

These are the verbose logs, before trying your approach:

![verbose log](https://user-images.githubusercontent.com/15863852/40513538-b3f62d28-5f6b-11e8-841a-12200e4da750.PNG)

Your workaround worked nice so far, I'll keep testing and if I encounter another case parse fails, I'll post it here.

**Comment by flovilmart** [comment]
Actually the workaround is the original way of doing it. The and operator has been added lately and as you noticed, may be problematic. I’ll fix the issue in a shot future.

**Comment by LMBernardo** [comment]
Can we re-open this issue? It seems to still exist in the current version of parse-server. I'm not sure how to apply the workaround above to my situation - I definitely need AND, not OR.
