### ISSUE TITLE
PFQuery whereKey..contains causes [__NSArrayM length] unrecognized selector error

### ISSUE THREAD

**Issue by AlessandroRiet** [parse-community/parse-server#4787]
let query = PFQuery(className: "class")
query.fromPin(withName: "pin")
query.whereKey("user_id", equalTo: "ab")
query.whereKey("detail", contains: "coffee")

where _detail_ is an array that looks like this:
["coffee and cheese", "wine"]

Some error reported from ParseErrorHandlingControllerError: Error Domain=Parse Code=102 "-[__NSArrayM length]: unrecognized selector sent to instance 0x1d425e7e0" UserInfo={error=-[__NSArrayM length]: unrecognized selector sent to instance 0x1d425e7e0, NSLocalizedDescription=-[__NSArrayM length]: unrecognized selector sent to instance 0x1d425e7e0, code=102}

------------------

Swift: 4.0
parse-server: 2.6.5
Xcode: 9.2

**Comment by flovilmart** [comment]
Can you provide the full stacktrace please?

**Comment by flovilmart** [comment]
@AlessandroRiet I believe this is the expected. When you run this query against the server, does it work like expected ie: returns the proper response?
