### ISSUE TITLE
parse-server 2.8.1: Cannot login after changing user password

### ISSUE THREAD

**Issue by nebitrams** [parse-community/parse-server#4790]
### Issue Description

These is error deployment error (see log showing Kerberos compilation error) when I deploy to Heroku.  The application works fine in all expects except that I cannot login after changing user password.  

### Steps to reproduce

1. Change user password using iOS ParseUI and also parse dashboard. 
2. Login using App ParseUI Login screen.
3. Failed to login and this is the server error log.

error: Error generating response. ParseError { code: 101, message: 'Invalid username/password.' } code=101, message=Invalid username/password.
error: Invalid username/password. code=101, message=Invalid username/password.

It works after I rollback to previous version in heroku with parse-server 2.7.4

#### Expected Results

I should be able to login after changing password.  

#### Actual Outcome

I cannot login.

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.8.1
  - Operating System:     Heroku stack Cedar-14
  - Hardware:             Heroku
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Heroku

- **Database**
  - MongoDB version: current is 3.2.10 (MMAPv1).  Should I switch to mLab latest 3.4.15 (MMAPv1)?
  - Storage engine:  mLab
  - Hardware:        mLab
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): mLab

### Logs/Trace

This is the heroku deployment error.

-----> Node.js app detected
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NODE_VERBOSE=false
       NODE_ENV=production
       NODE_MODULES_CACHE=true
-----> Installing binaries
       engines.node (package.json):  >=4.3
       engines.npm (package.json):   unspecified (use default)
       
       Resolving node version >=4.3...
       Downloading and installing node 10.2.0...
       Using default npm version: 5.6.0
-----> Restoring cache
       Skipping cache restore (new-signature)
-----> Building dependencies
       Installing node modules (package.json)
       
       > parse-image@0.2.0 preinstall /tmp/build_786e8213e834a7d1022250f222c7b1bb/node_modules/parse-image
       > ./install.sh
       
       Cannot install using brew or sudo apt-get
       Please install manually
       
       > bcrypt@2.0.1 install /tmp/build_786e8213e834a7d1022250f222c7b1bb/node_modules/bcrypt
       > node-pre-gyp install --fallback-to-build
       
       [bcrypt] Success: "/tmp/build_786e8213e834a7d1022250f222c7b1bb/node_modules/bcrypt/lib/binding/bcrypt_lib.node" is installed via remote
       
       > uws@10.148.0 install /tmp/build_786e8213e834a7d1022250f222c7b1bb/node_modules/uws
       > node-gyp rebuild > build_log.txt 2>&1 || exit 0
       
       
       > kerberos@0.0.23 install /tmp/build_786e8213e834a7d1022250f222c7b1bb/node_modules/kerberos
       > (node-gyp rebuild) || (exit 0)
       
       make: Entering directory `/tmp/build_786e8213e834a7d1022250f222c7b1bb/node_modules/kerberos/build'
       CXX(target) Release/obj.target/kerberos/lib/kerberos.o
       In file included from ../lib/kerberos.h:4:0,
       from ../lib/kerberos.cc:1:
       /app/.node-gyp/10.2.0/include/node/node.h:53:50: fatal error: core.h: No such file or directory
       #include "core.h"  // NOLINT(build/include_order)
       ^
       compilation terminated.
       make: *** [Release/obj.target/kerberos/lib/kerberos.o] Error 1
       make: Leaving directory `/tmp/build_786e8213e834a7d1022250f222c7b1bb/node_modules/kerberos/build'
       gyp ERR! build error
       gyp ERR! stack Error: `make` failed with exit code: 2
       gyp ERR! stack     at ChildProcess.onExit (/tmp/build_786e8213e834a7d1022250f222c7b1bb/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
       gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
       gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
       gyp ERR! System Linux 4.4.0-1019-aws
       gyp ERR! command "/tmp/build_786e8213e834a7d1022250f222c7b1bb/.heroku/node/bin/node" "/tmp/build_786e8213e834a7d1022250f222c7b1bb/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
       gyp ERR! cwd /tmp/build_786e8213e834a7d1022250f222c7b1bb/node_modules/kerberos
       gyp ERR! node -v v10.2.0
       gyp ERR! node-gyp -v v3.6.2
       gyp ERR! not ok
       
       > parse-server@2.8.1 postinstall /tmp/build_786e8213e834a7d1022250f222c7b1bb/node_modules/parse-server

**Comment by flovilmart** [comment]
Please provide the logs when running with VERBOSE=1 of the whole process of singing up, logging in, changing password etc...

**Comment by nebitrams** [comment]
I have switch on the VERBOSE=1, restarted dyno.  After that, I did the followings:

1. Login from App.
2. Trigger Password Reset from App.
3. Click on link in email to set new password.
4. Login from App.

This is the full log.  I have replaced all sensitive information such as username/password/emails.

[heroku-app-logs-1527347145223.txt](https://github.com/parse-community/parse-server/files/2041705/heroku-app-logs-1527347145223.txt)

**Comment by flovilmart** [comment]
Is the old password still valid?

**Comment by nebitrams** [comment]
I can't try because I could not remember the old password.  I test against several other accounts.  It seems that this problem affect accounts that are created long ago such as April 2015 (they were migrated from parse.com to ParseServer).  The recent accounts is working fine after password reset.

**Comment by nebitrams** [comment]
This is the verbose log when I change password using parsedashboard.

2018-05-26T16:05:17.530967+00:00 app[web.1]: [36mverbose[39m: REQUEST for [PUT] /parse/classes/_User/pG1Joxxxxx: {
2018-05-26T16:05:17.530981+00:00 app[web.1]:   "password": "********"
2018-05-26T16:05:17.530985+00:00 app[web.1]: } method=PUT, url=/parse/classes/_User/pG1Joxxxxx, host=myApp.herokuapp.com, connection=close, content-type=text/plain, origin=https://myApp.herokuapp.com, accept-encoding=gzip, deflate, accept=*/*, user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/604.4.7 (KHTML, like Gecko) Version/11.0.2 Safari/604.4.7, referer=https://parsedashboard.herokuapp.com/apps/myApp/browser/_User, accept-language=en-sg, x-request-id=d6de23b9-6527-43f2-bd69-f91e8d10a51b, x-forwarded-for=58.96.228.254, x-forwarded-proto=https, x-forwarded-port=443, via=1.1 vegur, connect-time=0, x-request-start=1527350717527, total-route-time=0, content-length=239, password=********

**Comment by nebitrams** [comment]
I used mLab to query the _Session table.  I could not find session for the failed to logon users.

This is the _user record for the account that I could not login.  Does it contain any clue on the sessionToken type?
{
    "_id": "xxx",
    "_created_at": {
        "$date": "2015-01-26T00:34:23.529Z"
    },
    "_hashed_password": "hashedXXX",
    "_session_token": "xxx",
    "_updated_at": {
        "$date": "2018-05-26T15:51:12.611Z"
    },
    "email": "xxx@a.b",
    "username": "Nebi",
    "emailVerified": true,
    "_email_verify_token": "yyy"
}

**Comment by flovilmart** [comment]
Legacy session tokens have the token on he user object; this is what you see there.

**Comment by flovilmart** [comment]
parse-server never supported old session tokens, further investigation need to be done to reproduce the issue and perhaps find a workaround. I have trouble also understanding why login information would not work after resetting the password.

**Comment by nebitrams** [comment]
Thanks.  

Apparently, for those old user account, session token is never generated for user login.  I can help to test/reproduce if you need, just let me know.

May I trouble you to delete the log file that I submitted earlier?  I deleted the link in this thread but could not delete the file.  I can email you the actual link if you need to link to delete it.

**Comment by flovilmart** [comment]
I don’t believe I have access to the log file myself. I can see the comment isn’t there anymore.

As for the reproduction, that would be very nice to have an edge to edge test that simulates this password exchange / replacement flow. This may help us understand the issue a bit more in depth.

There are many tests for the ‘reset password’ emails as well  as for legacy session tokens. Perhaps there’s something there that’s problematic

**Comment by lxknvlk** [comment]
I have the same problem, just after updating parse server logging in with my old password returned invalid username/password error. Then i have changed password, logged in. After some time logged out and again i cant login. In all cases the password was the same old password.

**Comment by nebitrams** [comment]
I work around this problem by manually deleting the old "_User" record and use app GUI to "signup" for new user account.

The new user account is having different data structure and don't have the password reset problem.
{
    "_id": "xxx",
    "email": "xxx@a.b",
    "username": "Nebi",
    "_hashed_password": "...",
    "emailVerified": true,
    "_wperm": [
        "xxx"
    ],
    "_rperm": [
        "*",
        "xxx"
    ],
    "_acl": {
        "xxx": {
            "w": true,
            "r": true
        },
        "*": {
            "r": true
        }
    },
    "_created_at": {
        "$date": "20xx-xx-xxTyy:yy:yy.yyyZ"
    },
    "_updated_at": {
        "$date": "20xx-xx-xxTyy:yy:yy.yyyZ"
    }
}

**Comment by flovilmart** [comment]
Interesting! I’ll be able to investigate from there with the old user data then!

**Comment by flovilmart** [comment]
The full old user object is the one that was previously posted?

**Comment by nebitrams** [comment]
Yes, the old user object the one posted with "_created_at" time stamp as 2015-01-26, having sessionToken inside the _user object.

I basically deleted account for username "Nebi" and use the iOS App to sign up a new account for username "Nebi" again.  I noticed that the new structure embeds the ACL.  Would this make a difference?

**Comment by flovilmart** [comment]
This is very likely that this is the issues

**Comment by alexblack** [comment]
Same issue here. We rolled back to fix it.

**Comment by flovilmart** [comment]
@nebitrams I'll try to work on a fix today, if I have time.

**Comment by flovilmart** [comment]
@nebitrams @alexblack 

The issues originate in the fact that now, we let the masterKey lock the users out. A locked out user is a user where the ACL is either not set or completely empty. Those old users, have the ACL completely empty as seen in the object that @nebitrams shared above.
It seems that for legacy reasons, the original users from the parse API didn't have an ACL, and the API would let them pass anyway.

How many of your users are affected by this issue? You can find out by checking the number of users with neither _rperm nor _wperm nor _acl set on them.

**Comment by saulogt** [comment]
We have a total of 727995 (legacy) users with no _acl nor _rperm nor _wperm.
About 33k of them have logged in during this month.

**Comment by flovilmart** [comment]
Ok, good to know, i’ll Push a workaround then so they are not locked out upon re-login. If needed

**Comment by nebitrams** [comment]
Thanks Florent.  I don't have that many legacy users.  I do not rollback and can wait for the patch.

**Comment by flovilmart** [comment]
@nebitrams @alexblack @saulogt the latest branch should be up to date, can you let me know if it fixes the issue for you?

**Comment by nebitrams** [comment]
Is this available via npm?
How do I test it in my local parse-server?  I can see the change in in src/Routers/UsersRouter.js but not sure how to apply it to my local installation.

**Comment by flovilmart** [comment]
As mentioned above, in your package.json, replace the version with the link pointing to this repository’s latest branch: https://github.com/Parse-community/Parse-server#latest

**Comment by dulmanr** [comment]
Having the same issues here. Not sure if it is related to users who changed their password, but possible. Rolling back to parse-server 2.7.4 fixed the problem for us.
**problematic version - 2.8.1**

**Comment by flovilmart** [comment]
@dulmanr can you try the version on the latest branch and let us know if everything is fine on this one?

**Comment by nebitrams** [comment]
I pointed my package.json to https://github.com/Parse-community/Parse-server#latest and ran npm install.  

I tested and the same problem remains.  I am switching VERBOSE to see more details now.

**Comment by flovilmart** [comment]
@nebitrams thanks.

**Comment by flovilmart** [comment]
Are you sure the password is not really invalid? Can you check with the DB stored password that it's all good?

**Comment by nebitrams** [comment]
Password is correctly entered because I tried 2-3 times.  I don't have a tool to view "local" mongo database.

This is the log for password reset.

verbose: REQUEST for [POST] /parse/apps/appIDxxx/request_password_reset: {
  "new_password": "secret",
  "confirm_new_password": "secret",
  "utf-8": "✓",
  "username": "Nebi",
  "token": "sessiontokenxxx"
} method=POST, url=/parse/apps/appIDxxx/request_password_reset, host=localhost:1337, content-type=application/x-www-form-urlencoded, origin=http://localhost:1337, accept-encoding=gzip, deflate, connection=keep-alive, upgrade-insecure-requests=1, accept=text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8, user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/604.4.7 (KHTML, like Gecko) Version/11.0.2 Safari/604.4.7, referer=http://localhost:1337/parse/apps/choose_password?token=sessiontokenxxx&id=appIDxxx&username=Nebi&app=xxx%20xxxx, content-length=109, accept-language=en-sg, new_password=secret, confirm_new_password=secret, utf-8=✓, username=Nebi, token=sessiontokenxxx

**Comment by nebitrams** [comment]
Is there anyway to check whether I got the latest update via NPM?

**Comment by flovilmart** [comment]
And the hashed password is corresponding to your "secret"?

Check the generated code in `node_modules/parse-server/lib/Routers/UsersRouter.js` line 139 should be:

```
if (!req.auth.isMaster && user.ACL && Object.keys(user.ACL).length == 0) {
```

**Comment by nebitrams** [comment]
I believe I still have the old code.  Sorry about this but need to go now.  Resume tomorrow.

line 132 onwards.
      if (!isValidPassword) {
        throw new _node2.default.Error(_node2.default.Error.OBJECT_NOT_FOUND, 'Invalid username/password.');
      }
      // Ensure the user isn't locked out
      // A locked out user won't be able to login
      // To lock a user out, just set the ACL to `masterKey` only  ({}).
      if (!req.auth.isMaster && (!user.ACL || Object.keys(user.ACL).length == 0)) {
        throw new _node2.default.Error(_node2.default.Error.OBJECT_NOT_FOUND, 'Invalid username/password.');
      }

**Comment by flovilmart** [comment]
Yes this is still the old code.

Did you run `npm install --save https://github.com/parse-community/parse-server#latest`

Also you can delete perhaps the node_modules folder and re-reun npm install.

**Comment by dulmanr** [comment]
@flovilmart 
I get this error when trying to install latest version:
npm ERR! parse-server@2.8.1 postinstall: `node -p 'require("./postinstall.js")()'`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the parse-server@2.8.1 postinstall script 'node -p 'require("./postinstall.js")()''.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the parse-server package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node -p 'require("./postinstall.js")()'
...

**Comment by dulmanr** [comment]
The command you put in the last comment:
npm install --save https://github.com/parse-community/parse-server#latest

**Comment by flovilmart** [comment]
do you have a package-lock.json? In package.json, is the line specifying the parse-server dependency pointing to the one I provided your, if not can you ensure it is? Lastly, you can remove the package-lock.json as well as the node_modules folder and re-run `npm install`

**Comment by nebitrams** [comment]
I ran the npm install --save and see many errors too.  I also checked that the UserRouter.js file not updated.  Can I manually add the new line into UserRouter.js?

XXX-MacBook-Air:elochallenge Seet$ npm install --save https://github.com/parse-community/parse-server#latest
npm ERR! prepareGitDep 1> 
npm ERR! prepareGitDep > fsevents@1.2.4 install /Users/XXX/.npm/_cacache/tmp/git-clone-35c9c4c1/node_modules/fsevents
npm ERR! prepareGitDep > node install
npm ERR! prepareGitDep 
npm ERR! prepareGitDep [fsevents] Success: "/Users/XXX/.npm/_cacache/tmp/git-clone-35c9c4c1/node_modules/fsevents/lib/binding/Release/node-v59-darwin-x64/fse.node" is installed via remote
npm ERR! prepareGitDep

**Comment by flovilmart** [comment]
> Can I manually add the new line into UserRouter.js?

You can but I discourage it as besides locally you won't be able to run.

> and see many errors too

What version of node are you running? Also you see errors, but the logs you're showing me are not errors at all.

**Comment by nebitrams** [comment]
npm 5.5.1
nvm v9.3.0

**Comment by flovilmart** [comment]
node 9 is unsupported, can you use node 8.10+. while this should work properly with node 9, one is never too sure.

Also, if you believe npm install fails, can you post the whole logs in a gist please?

**Comment by nebitrams** [comment]
I removed package-lock.json and node_modules folder and re-run "npm install".  The npm is successful but the UserRouter.js is still the old file.

Is my package.json correct?

{
  "name": "parse-server-example",
  "version": "1.4.0",
  "description": "An example Parse API server using the parse-server module",
  "main": "index.js",
  "repository": {
    "type": "git",
    "url": "https://github.com/parse-community/parse-server#latest"
  },
  "license": "MIT",
  "dependencies": {
    "express": "^4.16.3",
    "kerberos": "~0.0.x",
    "moment": "^2.22.1",
    "parse": "^1.11.1",
    "parse-image": "~0.2.x",
    "parse-server": "^2.8.1",
    "pug": "^2.0.3",
    "pug-bootstrap": "*",
    "request": "^2.87.0",
    "underscore": "^1.9.0"
  },
  "scripts": {
    "start": "node index.js"
  },
  "engines": {
    "node": ">=4.3"
  }
}

**Comment by flovilmart** [comment]
No it isn’t, uou’re pointing parse-server to ^2.8.1, and not the proper URL.

**Comment by nebitrams** [comment]
I edited UserRouter.js manually and the revised logic works for user records created in 2015.

verbose: REQUEST for [GET] /parse/login: {
  "username": "Nebi",
  "password": "*""
} method=GET, url=/parse/login, host=....

verbose: RESPONSE from [GET] /parse/login: {
  "response": {
    "objectId": "id",
    "createdAt": "2015-01-26T00:34:23.529Z",
    "updatedAt": "2018-06-01T12:23:45.463Z",
    "email": "xxx@a.b",
    "username": "Nebi",
    "emailVerified": false,
    "sessionToken": "r:xxxaaabbb"
  }
}

**Comment by flovilmart** [comment]
@nebitrams ok good to know. But you should not have done that as when you'll deploy to heroku or somewhere else, this won't work anymore.

**Comment by nebitrams** [comment]
Thanks Florent for fixing this issue.
Will there be a 2.8.2 release that contain this fix?  For production, I will not patch it using the parse-server#latest.

**Comment by lxknvlk** [comment]
This issue still persists in 2.8.2

**Comment by flovilmart** [comment]
@lxknvlk can you open a new issue please, with providing verbose logs, as well as any relevant information that would help isolating the issue?

**Comment by lxknvlk** [comment]
@flovilmart ok

**Comment by dulmanr** [comment]
@flovilmart Why open a new issue if the issue wasn't resolved?
Personally I'm still having issues in installing the new parse-server 2.8.2.

**Comment by flovilmart** [comment]
It’s been resolved according to the person who opened it. So, I’m not sure what to say, open a new issue please, with filling all required informations.

**Comment by artua** [comment]
The same problem here. 
Parse 2.8.1 on node 6.11.5 authorization failed.

**Comment by flovilmart** [comment]
Can you try with 2.8.2 on node 8+ please?

**Comment by artua** [comment]
I will ask my hosting provider (nodechef.com) to get it up and running, because now it crashes then I try to run it on node 8.

**Comment by flovilmart** [comment]
@artua so please reach out to nodechef support.

**Comment by nebitrams** [comment]
@flovilmart I tested 2.8.2 in heroku and it works well.  I am using these node and npm version.

remote:        Downloading and installing node 10.4.0...
remote:        Using default npm version: 6.1.0

**Comment by flovilmart** [comment]
Awesome! Good to hear!
