### ISSUE TITLE
Parse latest doesn't support Eclipse anymore?

### ISSUE THREAD

**Issue by huudaik** [parse-community/parse-server#4796]
Hi, 
This is not an issues, I just want to ask, where i can download Parse-1.17.3.jar because i need the library to update my Eclipse project from 1.8.0 to latest,
what changed? and how i can update it?
thank you verymuch!

**Comment by flovilmart** [comment]
parse-server is not distributed in the form of a Jar. Please look onto the Android repository for installation instructions https://github.com/parse-community/Parse-SDK-Android#installation and further assistance (if needed)

**Comment by huudaik** [comment]
OH, i'm sorry, i have mistake, my mean is Parse SDK Android, how to insall it on Eclipse?
