### ISSUE TITLE
[Feature Request] Crash Reporting

### ISSUE THREAD

**Issue by JTAguinaga** [parse-community/parse-server#4803]
Would it be possible to re-implement crash reporting into the Parse SDK? I have seen threads about it by googling. However, they are from a couple of years ago or more. No one has talked about them recently. I asked the Parse provider that I use if it was possible to do it anymore and they said no. And, that the best thing to do would be to send a Feature Request here. 

If it is not possible, that is fine. What would my other options be? The app with which I would like to use it on is an Apple Enterprise app. It is completely in-house and not on any of the stores.

**Comment by flovilmart** [comment]
That would be interesting!

**Comment by mtrezza** [comment]
It sounds interesting indeed to have basic crash reporting statistics out of the box.

@JTAguinaga, your current options are 3rd party SDKs like [Crashlytics](http://crashlytics.com) or the more lightweight [hockeyApp](http://www.hockeyapp.net).

**Comment by flovilmart** [comment]
@JTAguinaga there are plenty of opensource solutions and at the time of making parse opensource, this feature was already removed. Crash reporting and processing is quite a chore, symbolications isn'T trivial etc... Unfortunately we don't have the original SDK's either. So at this time, I'll close this issue as it won't be maintainable by us.

IF you still wanna work on this feature, let us know.
