### ISSUE TITLE
Is there a Parse Community Slack, Discord, Forum, etc?

### ISSUE THREAD

**Issue by zackshapiro** [parse-community/parse-server#4809]
I was wondering if a community exists somewhere of people who use Parse asking each other questions, talking about Parse, etc. 

Thus far, I haven't been able to find anything online to this effect. Thanks!

**Comment by flovilmart** [comment]
There is the gitter: https://gitter.im/ParsePlatform/Chat, also the slack `parseopensource.slack.com`

**Comment by zackshapiro** [comment]
Awesome. Thank you!

**Comment by zackshapiro** [comment]
@flovilmart Is there a different link to join the slack? That's just the link sign in and I don't have an account. Thanks

**Comment by flovilmart** [comment]
Slack is maintained by other people than this repository maintainer. So i’m not sure.

**Comment by zackshapiro** [comment]
Okay thanks.

**Comment by JacobJT** [comment]
@zackshapiro drop your e-mail and I'll invite via e-mail to Slack. I found the link on one of the many web pages and can't find which, but there's a send invite feature built in to Slack.

**Comment by JacobJT** [comment]
@zackshapiro  Nevermind, found it: https://parse-opensource.sapp.io/

**Comment by zackshapiro** [comment]
@JacobJT zack@zackshapiro.com

**Comment by zackshapiro** [comment]
thanks!

**Comment by yozef** [comment]
[](https://parse-opensource.sapp.io/) is not loading. Expect a flood of new Users, now that Axway has dropped their MBaaS.
