### ISSUE TITLE
parse server limitations

### ISSUE THREAD

**Issue by noyessie** [parse-community/parse-server#4811]
I wont to build a very huge and complexe plateforme. I think to use firebase, but i want to have a full control of the solution. I found open source parse and i think he can help me. but i found this article and it left me in doubt. The article present the limit of parse server. see [here](http://profi.co/all-the-limits-of-parse/). But it dates from 2014. I found another post on [quora](https://www.quora.com/What-are-the-limitations-of-parse).

Now i want to know after 3 years if all of this parse limitations is solved or not and what is the new parse limitations.

**Comment by flovilmart** [comment]
What are the limitations listed above you think go against what you plan to do? None really apply to the open source project. You’ll likely be I/O bound or CPU bound or Memory bound, depending your workloads.

**Comment by noyessie** [comment]
her is a list:

- 

- limited number of COUNT operations (differs every time, but surely under 160)
- if you are counting objects with the count higher that just a 1000, the system switches to “approximate count”
- maximum of 2 concurrent jobs (threads)
- log system remembers only 100 last logs
- push notifications have delay
- LIMIT SKIP operation can skip a maximum of 10 000 objects
- no debugger when writing cloudcode – you have to rely on logs only, and they have their own issues mentioned above
-  There is a lack of in case sensitive string queries

This is limitations i found that can be bad for my projet.

And please were can i find projet made with parse ?

**Comment by flovilmart** [comment]
None of those limitations apply on self hosted parse. 

Many projects are made with the open source parse server, but I’m not aware of demo projects.
