### ISSUE TITLE
Self hosted open source parse server limitations

### ISSUE THREAD

**Issue by noyessie** [parse-community/parse-server#4812]
Hello

I want to build a very huge and complex application and i want to  know if open source parse-server can support it. The solutions will manage:

- **images ( and her exif informations ), movie and sound**.
- **restricted authentification**; user came and submit and authentification request. Administrateur should validate or reject it. During the process both of then should be notified by mail
-  **data modification tracking** For some objects, we need to know who modify some data, when and store the data before modification
- **Multiple role**: the system will have more than 5 roles and complex relations between them
- **Web Portal**: Web portal will be available
- **Super Admin**: only super admin have the role to add other user.
- **lots of data**: Database should have a billions of rows and we don't want a latency when this appears. Thes constraints of the projet is to use **PostgreSQL or MySQL**, but i seen parse does not support MySQL.
- **archive**: we will need to archive some data ( this data have an files associated with him ).
- **File**: Have a full control of where file is saved. This is for security reason.
- **Dynamic models**

Someone can help me and tell me about know self hosted parse limitations ?

**Comment by oallouch** [comment]
Same here, many apps using parse-server. If you host on something like Google Cloud, you don't even manage stuff like load balancing or scalability (new instances are started automatically)

**Comment by noyessie** [comment]
No, we can't use Google Cloud. We will use our server.

**Comment by flovilmart** [comment]
@noyessie you can certainly build any kind of application on parse-server. It’s a nodejs web app that help abstracting the database layer, authentication as well as push notifications. In terms of scalability, this completely depends on your deployment, knowledge and skills. It is a nodejs app with a database so all the same rules apply.
