### ISSUE TITLE
2.8.2.: invalid username/password

### ISSUE THREAD

**Issue by lxknvlk** [parse-community/parse-server#4814]
### Issue Description

When i update my parse server from 2.7.4 to 2.8.2 users cant log in anymore, they get error "invalid username/password". Same was when i tried to update from 2.7.4. to 2.8.1.

When i updated to 2.8.2 this time, first time everything looked ok, but then after few hours i started getting complaints from users that they cant log in, even after resetting password they got the invalid username/password error.

### Steps to reproduce

1) Login a user and do something to parse-server 2.7.4
2) update server version to 2.8.2, restart server
3) users can't login anymore immediately, or after some time.

#### Expected Results

No error, user can login and use new server version.

#### Actual Outcome

Users cant login. 

### Environment Setup

- **Server**
  - parse-server version : 2.8.2
  - Operating System:     Ubuntu 14.04.5 LTS (GNU/Linux 3.13.0-125-generic x86_64)
  - Hardware:             AWS c4.large instance
  - Localhost or remote server?: AWS

- **Database**
Not sure about mongodb version, it is hosted at objectrocket.com

### Logs/Trace

No logs for this.

**Comment by flovilmart** [comment]
Can you provide the user data object from the DB for the ones that can’t log in? Also please provide the logs when running with VERBOSE=1.

**Comment by flovilmart** [comment]
I’ll reopen the issue when the info will be provided
