### ISSUE TITLE
When a cloud function has no result the response is malformed

### ISSUE THREAD

**Issue by SebC99** [parse-community/parse-server#4818]
### Issue Description

Cloud functions return a json response formatted as `{result: ... }` which is then interpreted by the client SDKs
But when it should return a `undefined` result, instead of returning `{result: undefined}`, it returns `{}` which is really not a valid json object, and which causes an error in the JS SDK for example.

To ensure the JSON response can be stringify we could use a replacer method to replace all the undefined by null values...?
Or we need to ensure all SDKs can cope with this kind of invalid json result...

**Comment by joshkopecek** [comment]
Under what circumstances should it return undefined?
Can you give an example of a successful query which returns `undefined`?

**Comment by flovilmart** [comment]
undefined is not serializable, this is why when your result is ‘undefined’ the response payload is empty.

If you attempt to return an empty result, use false, null, true etc...

**Comment by SebC99** [comment]
@joshkopecek it's not a query, it's a cloud function. So you could have a cloud function to retrieve a value if exists and nothing if not (i.e. undefined)
So as @flovilmart said, the best way to do it is to force a null return value

**Comment by JacobJT** [comment]
@SebC99 I appreciate the issue as this was not functionality I was aware of! We just happen to not have any cloud functions that have no response run from the JS SDK. 

@flovilmart Would a PR adding a warning when a cloud code function returns no value be approved? I suddenly feel my cloud code is a bit more full of holes than I had realized, and personally I would have heeded such a warning from the start if it had been there.

**Comment by flovilmart** [comment]
Perhaps we should return an empty object when response.success() is called without a parameters or `true`. Whatever would be less breaking

**Comment by SebC99** [comment]
One way to do it would be to include a `status` field in the response object, which would be `ok` when no error, even without a result in case of no result. 
It would then allow to pass some cloud functions errors in the status and not in the http headers (for example when you detect a parameter is missing)

**Comment by flovilmart** [comment]
The problem at hand is that the response body is entirely an empty object. Status is not a regular field, and should not be added at that time, as it is inconsistent with the rest of the platform.

**Comment by SebC99** [comment]
true
And when we stringify an empty result it removes the key, so we end up with an empty (i.e. invalid) json being sent to the client.
We could replace undefined values by null values before stringify it to avoid that, or add a warning to avoid undefined values, or add another field indicating a NO_VALUE / EMPTY result as in usual rest api like json-api

**Comment by flovilmart** [comment]
Again, I’m usually against adding new magic constants like ‘NO_VALUE’ which bears as much consistency as 42 or null. 

I’ll look into the original docs and iOS / JS Sdk’s , but I believe the original parse.com implementation used `true` to indicate a successful Cloud code call that was completed without a return value.

**Comment by JacobJT** [comment]
@flovilmart I believe forcing node 8+ is coming in a 3.0.0 release, right? 

The only non-breaking change I can think of is that warning. Even passing an empty object as the result I believe could potentially break some people's code, even if it wasn't intended behavior.

But, if a 3.0.0 is on the horizon, I can't think of a better time to update the result to at least force an empty object being returned. I think it's the least damaging in terms of breaking changes, and thus probably the most appropriate.

I would be wary of straight up returning true for missing values, as it's very likely many people look for a truthy / falsey value, so this would cause more widespread breakages.

**Comment by flovilmart** [comment]
Node 8+ has been the target for the latests releases already as 6 is not supported anymore.

So no breaking changes here just pure evolution

Also, i’m Curious of the cases where JSON decoding fails or other issues. @SebC99 do you have an example of failing code?

**Comment by SebC99** [comment]
Well, every cloud function where you respond a `response.success()` without any result fails in the web JS SDK

**Comment by flovilmart** [comment]
Uhm... ok!

**Comment by JacobJT** [comment]
@flovilmart Calling `callEmptyResponse` returned `ParseError {code: 107, message: "The server returned an invalid response."}` 

```
Parse.Cloud.define('emptyResponse', (req, res) => {
    return res.success();
});

Parse.Cloud.define('callEmptyResponse', (req, res) => {
    Parse.Cloud.run('emptyResponse', null, null).then(
        success => {
            res.success();
        },
        error => {
            res.erorr(error);
        }
    );
});
```

**Comment by flovilmart** [comment]
so during development you should catch it if I understand correctly.

**Comment by SebC99** [comment]
We can. But it means we have to catch a 107 error as a success with no result, which is weird as it's not a real error...
All other response are embedded in a `{result: ...}` response, so there's a specific behavior for "no result" response.
That's why I suggested to have all response embedded in a `{status: OK, result: ...}` response to avoid empty json results.

**Comment by flovilmart** [comment]
Adding the status key would force all SDK’s to implement it, and infer an empty response with status: “ok”, hard code this string etc...

I’ll provide a fix that will simply set true if no arguments are passed to the success method

**Comment by JacobJT** [comment]
That would break mobile SDKs.

I.e. on iOS, one can currently do `if(!result) {...}` in the callback. Setting either true or false here is going to make `result` an `NSNumber*` instead of `nil`, which, regardless of whether the value inside is true or false, is going to be truthy itself. 

I'm not saying don't do it, I think *some* change ought to be made here. There's just not a non-breaking solution that I can see, so I would make sure it goes in a major version change.

Whatever the decided upon solution, I'd be happy to work on it next week. I've contributed some test cases and bug reports but have yet to contribute some functional code, would like to change that. Though I'm going out of town this weekend.

**Comment by SebC99** [comment]
Won't client SDK simply ignore an added field?
The other solution would to change `undefined` value to `null` before stringify it so that the response would be `{result: null}` instead of `{}` which shouldn't break any `if(!result) {...}` client code.

**Comment by flovilmart** [comment]
Ok so no changes, this is the expected behavior and should be addressed at development time. I can make the server fully explode if you’d call response.success() withtout any argument so you know it is not recommended and unsupported

**Comment by flovilmart** [comment]
@JacobJT checking `if(!result)` for a positive successful call is really backwards.

**Comment by SebC99** [comment]
@flovilmart it could be ok with just a warning yes, but what about my previous suggestion? Won't it work?

**Comment by flovilmart** [comment]
Adding a new status field is really cumbersome as it requires update on all SDK's and it is not used anywhere else in the server. I don't want to add an additional field that pollutes all calls, just to counter bad SDK usage on the server that should be caught at development time. Again, this is not a new behaviour or a regression. My guts would be to put `true` as the response as @JacobJT mentions checking 

```
if !result { 
/* something went wrong */ 
} else { 
/* yay */ 
}
```

is a very common pattern.

**Comment by SebC99** [comment]
@flovilmart i really don't see why it would need an update on all SDKs as it wont change the existing `result` response field, but ok I trust you. A warning will be fine

**Comment by flovilmart** [comment]
> i really don't see why it would need an update on all SDKs

Because we'll probably want to check on this status field no? check if it's 'OK'

**Comment by SebC99** [comment]
We could in the future, but it's not mandatory at all!
In the meantime it can be ignored and just avoid empty malformed response.

**Comment by JacobJT** [comment]
@flovilmart I check the existence of error to determine if a call was successful or not, but I have some cloud functions that say, end up returning the results of a `query.first()` call, which may or may not return an object. So my callback might look like this:

```
if( !error ) {
    if( result ) { // Do the thing with the result }
} else { <Parse Error Handler> } 
```

With neither the server nor iOS SDK disagreeing with the implementation I didn't realize I was doing anything improper.

A warning will suffice and could be put in a patch without causing breaking changes. I think a breaking change to enforce correct usage would also be appropriate in the next major version change as well, whether that's returning true or null as a default, or throwing an exception on the server if you try to call `success()` with an undefined value.
