### ISSUE TITLE
Update multiple rows using single query

### ISSUE THREAD

**Issue by newdev7** [parse-community/parse-server#4820]
How to update multiple rows using single query?

In MongoDb, they are using `updateMany()` function to update multiple rows.

In parse-server also I'm seeing `updateMany()` function which is calling that MongoDb function.
[https://github.com/parse-community/parse-server/blob/7223add446ffd1af0e023f50f3a2cd8dc06c3c16/src/Adapters/Storage/Mongo/MongoCollection.js](https://github.com/parse-community/parse-server/blob/7223add446ffd1af0e023f50f3a2cd8dc06c3c16/src/Adapters/Storage/Mongo/MongoCollection.js)

I'm using REST api to retrieve/update the rows. How to use this `updateMany()` in REST api to update multiple rows?

Thanks.

**Comment by flovilmart** [comment]
It is not supported by REST at the moment. A pull request is open for the but needs changes and improvements before it can be made public.
