### ISSUE TITLE
 Maximum call stack size exceeded, related to Parse.Role

### ISSUE THREAD

**Issue by omairvaiyani** [parse-community/parse-server#4832]
parse-server 2.7.4

I have ran into this issue, which appears to fail a number of requests to our server:

```
RangeError: Maximum call stack size exceeded:

parse-server/lib/Auth.js in _getAllRolesNamesForRoleIds.then.roleNames at line 161:45
```

Snippet of parse-server code that's failing:
```
      return this._getAllRolesNamesForRoleIds(rolesMap.ids, rolesMap.names).then(roleNames => {
        this.userRoles = roleNames.map(r => {
          return 'role:' + r;
        });
        this.fetchedRoles = true;
        this.rolePromise = null;
        cacheAdapter.role.put(this.user.id, Array(...this.userRoles)); <-- THIS LINE
        return Promise.resolve(this.userRoles);
      });
    });
  });
```

We have a deep role hierarchy. Is this the cause? Are there any steps I can take to fix this.

-

**Comment by flovilmart** [comment]
How deep? Do you have any circular role dependency? Can you provide and example of the roles involved in an test?

**Comment by flovilmart** [comment]
If you can provide the list of roles and their hierarchy, that would help understanding which depth of call stack we're talking asbout. Also, you could debug / log the roles list. 

Another note, the line that'S breaking is the one that adds another function call to the stack, so thta's not the line that ultimately fails.é

**Comment by omairvaiyani** [comment]
@flovilmart 

I'll have to explain how we handle roles in order to explain the hierarchy. We create two roles per object, respectively named "[className]-read-[objectId]" and "[className]-write-[objectId]".

Rather than increasing the size of the object by endlessly adding users to the object's ACL, we simply add users to the object's read/write roles.

E.g.
```javascript
// saved object
const object1 = await CustomObject.createWithoutData("OBJ3CT1D").fetch();

// create roles
// Parse.Role { name : "customobject-read-OBJ3CT1D" }
const readRole = await object1.getReadRole(); 
 // Parse.Role { name : "CustomObject-write-OBJ3CT1D" }
const writeRole = await object1.getWriteRole();

const ACL = new Parse.ACL();
ACL.setRoleReadAccess(readRole, true);
ACL.setRoleWriteAccess(writeRole, true);
await object.save({ACL}, options);

// let user see object
const user = await Parse.User.createWithoutData("US3R1D").fetch();
readRole.getUsers().add(user);
await readRole.save();

// let members of a particular group see object
// Parse.Object subclass { title: "Some Group", "members": Parse.Relation<Parse.User> }
const group = await UserGroup.createWithoutData("GR0UP1D").fetch();
// Parse.Role { name: "usergroup-member-GR0UP1D" }
const groupMemberRole = await group.getMemberRole(); 
readRole.getRoles().add(groupMemberRole);
await readRole.save();
```

Can you inherently see any troubles with this methodology? We can essentially have unlimited user groups, some with parent groups that extend the privileges of the child group.

I have left out some complexities, such as the ```ACL```s on the role's themselves. We have group moderators that have ```read``` and ```write``` access to the respective read/write roles.

**Comment by flovilmart** [comment]
So uou create 1 role per object? How many roles do you have? This is quite insande I believe.

**Comment by omairvaiyani** [comment]
I wouldn't say 1 per all objects. It's only for those that need to be accessed by various groups of people at various times. We've ended up with 50k plus roles, so yes it's a role explosion and one Id like to get on top of now. 

We're fortunately in a position to change our approach without irreparable damage, but I'm unsure which approach is the most efficient and still give us the current flexibility. 

Have you come across any detailed guides for handling access control and scale, using parse?

**Comment by flovilmart** [comment]
In average how many users share access to a particular object? Because at that time, you are scaling for role explosion. let's say your average is 100 users per object, this will just take 100 strings in the DB, which is indexed if you wish per row. An objectId is just 10 characters so we're talking of 1000 chars which is very small.

On the opposite you have 50k roles, and potentially a user can belong to as many roles as he's got access to. So the more unique objects users have access to, the slower your whole system becomes.

**Comment by omairvaiyani** [comment]
Thanks @flovilmart that makes things a little clearer.

Feel free to close this issue as I think the problems lays with my handling of this, rather than the core parse system.

Would I be able to pick you brain a little more by explaining our specific context, perhaps by email?

**Comment by flovilmart** [comment]
I don’t offer consulting at this time.
