### ISSUE TITLE
iOS SDK - The class PFUser must be registered with registerSubclass before using Parse

### ISSUE THREAD

**Issue by xscoder1** [parse-community/parse-server#4837]
Hello, I'm using Parse Server hosted on back4app, and it's been half an hour that I'm getting this error in my iOS app:

```
2018-06-14 12:18:04.955801+0200 Pikky[6867:3655616] [DYMTLInitPlatform] platform initialization successful
2018-06-14 12:18:05.097792+0200 Pikky[6867:3655503] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'The class PFUser must be registered with registerSubclass before using Parse.'
*** First throw call stack:
(0x18406ad8c 0x1832245ec 0x18406ac6c 0x102c4bad4 0x102c4a480 0x102a03774 0x102a00f68 0x102a0c1dc 0x102a0c368 0x18e2e9fec 0x18e44b738 0x18e44b8b0 0x18e44b470 0x18e119294 0x18e12d994 0x18e44b738 0x18e44b8b0 0x18e44b470 0x18e119294 0x18e14749c 0x18e44b738 0x18e44b470 0x18e2e9c94 0x18e44b738 0x18e44b8b0 0x18e44b470 0x18e2e8fe4 0x18e5f5e98 0x18e057fa4 0x18dc751d8 0x18dc434d4 0x18e273b1c 0x18dc42dd0 0x18dc42c6c 0x18dc41afc 0x18e8d784c 0x18dc411ec 0x18e6bcac8 0x18e80abf8 0x18dc40c0c 0x18dc405a8 0x18dc3d5e0 0x18dc3d330 0x18686b470 0x186873d6c 0x10404919c 0x1040557cc 0x18689f878 0x18689f51c 0x18689fab8 0x184013404 0x184012c2c 0x18401079c 0x183f30da8 0x185f15020 0x18df4d758 0x1029fca6c 0x1839c1fc0)
libc++abi.dylib: terminating with uncaught exception of type NSException
```
I haven't changed the code nor updated the Parse.framework, what can cause this issue? It was working fine until a while ago...

**Comment by nebitrams** [comment]
What's the Parse.framework version that you are using? 

In very old version such as Parse-SDK-iOS-OSX 1.14.3, you need to registerSubclass.  This is no longer required now.

**Comment by xscoder1** [comment]
i’ve fixed the issue by instantiating:
var user = PFUser(className: “_User”)

**Comment by JacobJT** [comment]
@xscoder1 I've never run into this issue. You shouldn't have to register a subclass like that. You should probably double check your version and use the latest without calling registerSubclass that way.

**Comment by flovilmart** [comment]
@kangaroo5383 did you call registerSubclass ? I’ll close as we’ll likely not fix auto registration for Swift subclasses

**Comment by DolenzSong** [comment]
Having same issue

**Comment by xscoder1** [comment]
@DolenzSong have you tried using:
‘var user = PFUser(className: “_User”)’?
