### ISSUE TITLE
Error install command (node postinstall.js )

### ISSUE THREAD

**Issue by CaptainClaquette** [parse-community/parse-server#4843]
### Issue Description

I got a error after using the install command : "npm install -g parse-server mongodb-runner"

### Steps to reproduce

execute : npm install -g parse-server mongodb-runner

#### Expected Results

Installation ok

#### Actual Outcome

npm WARN @semantic-release/git@4.0.3 requires a peer of semantic-release@>=15.0.0 <16.0.0 but none was installed.
npm ERR! Linux 4.15.0-23-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "parse-server" "mongodb-runner"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! parse-server@2.8.2 postinstall: `node -p 'require("./postinstall.js")()'`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the parse-server@2.8.2 postinstall script 'node -p 'require("./postinstall.js")()''.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the parse-server package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node -p 'require("./postinstall.js")()'
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs parse-server
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls parse-server
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.8.2
  - Operating System:     ubuntu 18.04
  - Hardware:              
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): localhost

- **Database**
  - MongoDB version: mongodb-runner@3.6.1
  - Storage engine:  ?
  - Hardware:       ?
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): localhost

### Logs/Trace

[npm-debug.log](https://github.com/parse-community/parse-server/files/2110385/npm-debug.log)

**Comment by JacobJT** [comment]
`npm ERR! npm v3.5.2`
...
`npm ERR! Make sure you have the latest version of node.js and npm installed.`

**Comment by iop280** [comment]
On AWS, the latest version is 6.14 - which doesn't allow us to roll out the latest version. How do we go about this?

**Comment by CaptainClaquette** [comment]
i solved my problem. In my case the "umask" of my provider was too restrictive (077). When npm create some directory it can't go inside because of the the insufisent file permission.

Beware of the "Umask" 😝

**Comment by flovilmart** [comment]
@iop280 by default AWS Elastic Beanstalk is effectively running on 6.14, but you can change it: https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/concepts.platforms.html#concepts.platforms.nodejs

and you can configure elastic beanstalk nodejs version with those options: https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/concepts.platforms.html#concepts.platforms.nodejs

Check this stackoverflow question: https://stackoverflow.com/questions/38976640/updating-nodejs-version-in-elastic-beanstalk
