### ISSUE TITLE
[Enhancement] Response whole object when creating object through REST API 

### ISSUE THREAD

**Issue by thobhanifreddy** [parse-community/parse-server#4846]
Whenever we create a new object using `query.save()` we will always get the whole object as a response.  But when we use REST API to create a new object we only get "createdAt" and "objectId"

So won't it be consistent to return the whole object as a response in both the methods?

P.S. I need it because I am making a new object in other parse server using cloud cloud and the whole object as a response will be helpful.

**Comment by flovilmart** [comment]
This would likely break all SDK’s and existing setups, even if I understand it saves you a bit of time in your implementation this is not something we want to implement.
