### ISSUE TITLE
With the REST API can I set relational pointers?

### ISSUE THREAD

**Issue by farhansyed9** [parse-community/parse-server#4851]
I know with the Parse iOS SDK you can set relational pointers to other classes, recently I've started the switch to encoding and decoding my own objects. Anyway is it possible to create a pointer via the REST API?

**Comment by flovilmart** [comment]
Yes you can, check the docs, http://docs.parseplatform.org/rest/guide/#objects under relations, there is an example of the JSON form of a pointer
