### ISSUE TITLE
Error: Cannot find module 'parse-server'

### ISSUE THREAD

**Issue by greggmojica** [parse-community/parse-server#4852]
Getting this error, any thoughts??

Error: Cannot find module 'parse-server'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)

**Comment by flovilmart** [comment]
Please fill the issue template completely.
This indicates the parse-server module is not installed. So it depends on your setup, package.json file etc..

**Comment by greggmojica** [comment]
@flovilmart running parse server 2.8.2 and getting this problem. Can you shed some light as to why this might happen?

**Comment by flovilmart** [comment]
Do you have a longer stacktrace? Whst’s In package.json?

**Comment by greggmojica** [comment]
I have a series of npm modules, but here's the log output I'm getting, is this of any help?
```

19749 verbose Darwin 16.7.0
19750 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "parse-server" "--save"
19751 verbose node v8.11.3
19752 verbose npm  v5.6.0
19753 error Cannot read property '0' of undefined
19754 verbose exit [ 1, true ]
```

**Comment by flovilmart** [comment]
So yeah, looks like it’s not installing correctly. What is the command you are running?

**Comment by greggmojica** [comment]
Hmm, I'm just running npm install and have never had this problem before? Thoughts?

**Comment by flovilmart** [comment]
It’s tough to say without knowing which exact commands you’re running. 

Can you provide all the elements I asked over before:

- the full stacktrace of the error you have (mentioned in the issue itself)
- the contents of package.json
- the exact command you run that fails
- any additional logs that may be relevant.

**Comment by flovilmart** [comment]
@greggmojica any chance you got it solved†

**Comment by JacobJT** [comment]
npm itself had a lot of issues the past week. They had some downtime due to Twitter's Smyte acquisition + shutdown, and then some other internal issues were going on last week that caused some installs and what not to fail.

I left the office Friday unable to run `npm install` and it worked fine today. The suggestion that worked for some people prior to that was `npm cache clear --force`, but I didn't need to do that.

**Comment by acinader** [comment]
not enough info.  re-open to pursue.

**Comment by SanzenDev** [comment]
have anyone solved this issue? I faced the same problem. maybe it's about the version of parse-server

**Comment by dplewis** [comment]
@SanzenDev can you open an new issue and fill out the template?

**Comment by hajjarjoseph** [comment]
Try adding `"parse-server": "3.6.0"` in your dependencies in `package.json`

**Comment by Mxdi** [comment]
This is still an issue.

**Comment by Samigos** [comment]
For some reason this worked for me https://stackoverflow.com/a/51688273/4388495
