### ISSUE TITLE
Invalid parameter for query: distinct

### ISSUE THREAD

**Issue by liangmark** [parse-community/parse-server#4857]
i have installed parse-server@2.7.4 on node@6.8.0, when i use 'distinct' to query, it does not work.

![snip20180628_7](https://user-images.githubusercontent.com/12019458/42009853-b06a7b6e-7abe-11e8-8211-2eba4aab19cb.png)

**Comment by acinader** [comment]
my guess is that you need to change it to `--data-urlencode '{distinct: "outId"}'`

I will test it out in an hour or so to confirm.  If I am correct, then I'll update the docs here:
http://docs.parseplatform.org/rest/guide/

**Comment by acinader** [comment]
@liangmark i can reproduce your issue.  looking into.

**Comment by acinader** [comment]
@liangmark the documentation is just wrong and I'll fix it.

The path in your request: `/parse/classes/TestTable`

Needs to be: `/parse/aggregate/TestTable`

sorry 'bout that.

`

**Comment by acinader** [comment]
actually the docs are correct.  you just had it wrong and I copied transcribed what you had.  thanks, now i understand the rest api much better ;)

**Comment by liangmark** [comment]
I got what I want，Thank you!
