### ISSUE TITLE
Parse Server Hosting

### ISSUE THREAD

**Issue by dpatel20** [parse-community/parse-server#4870]
Firstly, I appreciate this is probably the best place to ask this but I am not too sure where to ask.

I have created a Web App with Parse as the backend. It is used for a children's football (soccer) tournament. It is not a paid app/no ads. The app is used to manage the scoring, etc and give updates to those participating/watching.

Now, the web app is only used TWICE in the year (two separate days, usually within 1mth of each other). I use a paid hosting service and am normally on their free service but for the tournament period I upgrade to a higher package to get the required requests/month and then have to ask the provider to kindly drop the package back to the free tier for the next 11mths (used only for devel purposes)!

I am thinking that may be hosting on a different provider might work out cheaper (it's not a lot of money to be fair; so that's not my mine incentive) and it might mean I do not have to annoy the provider to change my tier. Also, my provider currently does not support push notifications to the web which is something I'd like.

I am very confused by the pricing options on services like AWS, etc so was hoping someone can help with what might be the best option. 

My requirements/usage:
- Each tournament day the app uses ~50K requests.
- It never gets close to 10req/s - maybe 2-3 req/s.
- I use live queries so this is a must.
- In the future, I'd like to send push notifications to the web so need to be able to configure a service that supports that (OneSignal??).
- Database is ~1.5MB (compressed, I assume).
- Maybe in future be able to upload photos for a live feed. But relatively small amounts - say 500MB.
- https

My research:
- buddy.com seems almost ideal except it does not support live queries (and has been on their roadmap for some months). And again not sure I can do Web push notifications.
- heroku - I think the free option here would work with mlab free option.  Do I need to pay to get https? I'm not clear if parse on heroku will support live queries, push to web, etc (I assume I just need to configure these myself?).
- AWS - this just is mind boggling complicated for me to figure out! :( Any insight would be appreciated.
- Any others???

**Comment by flovilmart** [comment]
You should probably ask over stackoverflow or serverfault for those kind of questions. We don’t affiliate with any provider.
