### ISSUE TITLE
error object lost in SchemasRouter

### ISSUE THREAD

**Issue by oallouch** [parse-community/parse-server#4871]
Hi,
I got a "Database adapter error" from SchemasRouter, but the original error gets eaten by:

` .catch(error => {
      if (error === undefined) {
        throw new Parse.Error(Parse.Error.INVALID_CLASS_NAME, `Class ${className} does not exist.`);
      } else {
        throw new Parse.Error(Parse.Error.INTERNAL_SERVER_ERROR, 'Database adapter error.');
      }
    });`

Should the original message be appended ?
Should Parse.Error have another constructor argument (sourceError) ?
Should the original error be rethrown ?

Thx a lot (as always),

Olivier

**Comment by flovilmart** [comment]
Is it a recurring error / are you able to reproduce it?

**Comment by oallouch** [comment]
Yes.
Actually, it was thrown in MongoStorageAdapter.deleteObjectsByQuery(). Debugging handleError(error) gave me the error message : "Cannot use (or request) retryable writes with limit=0"
I recently moved to MongoDB Atlas and I apparently need to remove retryWrites=true from my connection URI.
see https://stackoverflow.com/questions/50283081/mongodb-error-cannot-use-retryable-writes-with-limit-0
They say it's better to change some queries.

Anyway, having the original message appended in the Parse.Error would be nice, I think.

**Comment by flovilmart** [comment]
Feel free to open a PR, I'd rather have the error logged as is with the logger, the error is forwarded to the client and it's leaky to forward database level errros in public :)

**Comment by oallouch** [comment]
Can it be something like:

`
  handleError<T>(error: ?(Error | Parse.Error)): Promise<T> {
    if (error && error.code === 13) { // Unauthorized error
      delete this.client;
      delete this.database;
      delete this.connectionPromise;
      logger.error('Received unauthorized error', { error: error });
    } else {
     logger.error('Unknown MongoDB error', { error: error });
    }
    throw error;
  }
`

**Comment by oallouch** [comment]
the debug session tells me it's ok
