### ISSUE TITLE
 About the uniqueness of the "_id" field. Please tell me, thank you.

### ISSUE THREAD

**Issue by Likeyong** [parse-community/parse-server#4873]
Excuse me, the "_id field" in each database table is guaranteed to be unique in a separate table, or to guarantee the uniqueness of all the tables on the parse server.

**Comment by georgesjamous** [comment]
To my knowledge, each id "objectId" is unique per table]
But it is highly unlikely to have duplicate ids between tables

**Comment by flovilmart** [comment]
There is no guarantee but the objectId génération should be random enough that you can calculate the probability for it to happen
