### ISSUE TITLE
Support MongoDB collation

### ISSUE THREAD

**Issue by oallouch** [parse-community/parse-server#4883]
Hi,
Being able to use collation with Parse.Query (as a param of find or aggregate for instance) would be great for case insensitive searches.

What do you think about it ?

For now, I'll use the rawCollection using the 'not so internal' Config :)

Thx,
Olivier

**Comment by flovilmart** [comment]
@oallouch we already added additional options for the queries like the read preference. Collation would be in the same style. Do you have any documentation from mongodb?

**Comment by oallouch** [comment]
Of course
For standard queries:
https://docs.mongodb.com/manual/reference/method/cursor.collation/
For the aggregation framework (search 'collation' on this page)
https://docs.mongodb.com/manual/reference/method/db.collection.aggregate/

**Comment by oallouch** [comment]
Any news on this one ?

**Comment by acinader** [comment]
hi @oallouch I got started on a related solution this past summer: https://github.com/parse-community/parse-server/pull/5634/files#diff-b0af2ee2c26859a8aa6d8d0a0cf3a64aR1721

to solve what I think is a bad and annoying shortcoming of parse: usernames and emails are case-sensitive in a way that they shouldn't be (see: #3990).

I haven't gotten the solution over the finish line, and your use-case may require us to rethink how I planned going about it.  I'd love some help with finishing it (@dplewis :).  But I haven't gotten any takers yet.

**Comment by oallouch** [comment]
Maybe all I need is an option parameter so that I can pass any mongo option to the native driver.
It's what I do now when I directly use the driver's collection.

**Comment by dplewis** [comment]
@acinader Sorry dropped the ball on that one. I was waiting for you to right a test.

@oallouch You are right. Feel free to open a PR. There are a lot of options like ReadPreference that get passed into mongo with the same style.

We are here to help. I’ll assign this to myself but I wont be able to get to it for a while.

**Comment by oallouch** [comment]
@dplewis ok, I'll try when I have more time.

**Comment by dplewis** [comment]
I’ll race you lol.

**Comment by oallouch** [comment]
I just saw your response, which means you'll win :)

**Comment by oallouch** [comment]
I try to do it, based on the ReadPreference implementation.
The thing is I try to do it on Windows, so everytime I see something odd I think "oh that's because of Windows, it can't be done on Windows".
For instance, when run the ReadPreference tests I see one failure with the log "Temporarily disabled with xit".

![image](https://user-images.githubusercontent.com/2777369/78450624-40023780-7680-11ea-82cd-7d8d30cb081b.png)

Is it normal ?
