### ISSUE TITLE
PR => extending Parse.Object

### ISSUE THREAD

**Issue by Aetherall** [parse-community/parse-server#4884]
I am adding a field level permission layer using beforeSave triggers

For this to work, I use a class extending Parse.Object to extend my Data Classes.

This works like a charm on the client, on the server, I am experiencing issues when the data get decoded before "beforeTrigger"s:

The Operations like AddOp get interpreted as "part of the data" and it messes up the "to be saved" data

I am looking for someone who could lead me in the right direction about where to look to fix the issue, and why not do a PR afterward

Thanks !

**Comment by flovilmart** [comment]
Can you share the code and open the PR? Depending where uou’re Injecting this logic, you may be mistaken. This layer of validation should probably be in RestWrite, using the Schema table as a reference.

**Comment by Aetherall** [comment]
I found out that the AddOp created by
`parse-server > RestWrite > sanitizedData > Parse._decode`
is not an instance of the ParseOp.Op from 
`parse-sdk > ParseObject > set`

It may be a problem relative to my setup ( webpack on both client and server with both HMR )

I tried to bundle the parse-server within my server bundle but I got errors due to  relative SQL files
I tried with the SDK too but it doesn't seem to change anything

**Comment by Aetherall** [comment]
I found it, the class used 'parse/browser' from client because the server imported the client app for SSR

To fix it, I created global.Parse on the client too and stopped importing 'parse'
