### ISSUE TITLE
Support file adapter for Digital Ocean Spaces

### ISSUE THREAD

**Issue by srameshr** [parse-community/parse-server#4886]
**Is your feature request related to a problem? Please describe.**
Include support for [Digital Ocean Spaces](https://www.digitalocean.com/products/spaces/) as one of the file adapters.

**Describe the solution you'd like**
Just as simple as any other existing adapters.
```
const spacesAdapter = require('parse-server').spacesAdapter;
new ParseServer({
  filesAdapter: new spacesAdapter({ ...config }),
});
```

**Describe alternatives you've considered**
None exists yet, to consider.

**Comment by flovilmart** [comment]
Did you have a look at the file system storage adapter? This seems to be the one you need. D.O. Storage is similar to AWS block storage and are just attached volumes on your instance. I’m not sure how multiple instances referencing the same volume in read/write would work, but from what I can see, the FS adapter, pointing to the right folder on the volume should do the job.

**Comment by srameshr** [comment]
I think I need to edit my question. The S3 equivalent seems to be **Digital Ocean Spaces**.

**Comment by flovilmart** [comment]
Excellent, it’s compatible with S3, so probably, we would either use the S3Adapter with a new customization point for the remote URL to send the data to DO instead of AWS.

**Comment by Tybi** [comment]
Hi, I did something like that to specify the remote URL of DO : 

```
var express = require("express");
var ParseServer = require("parse-server").ParseServer;
var path = require("path");
var S3Adapter = require("@parse/s3-files-adapter");
var AWS = require("aws-sdk");

//Configure Digital Ocean Spaces EndPoint
const spacesEndpoint = new AWS.Endpoint(process.env.SPACES_ENDPOINT);
var s3Options = {
  bucket: process.env.SPACES_BUCKET_NAME,
  baseUrl: process.env.SPACES_BASE_URL, 
  region: process.env.SPACES_REGION,
  directAccess: true,
  globalCacheControl: "public, max-age=31536000", 
  bucketPrefix: process.env.SPACES_BUCKET_PREFIX,
  s3overrides: {
    accessKeyId: process.env.SPACES_ACCESS_KEY,
    secretAccessKey: process.env.SPACES_SECRET_KEY,
    endpoint: spacesEndpoint
  }
};

var s3Adapter = new S3Adapter(s3Options);

var api = new ParseServer({
  databaseURI: process.env.DATABASE_URI || "mongodb://localhost:27017/dev",
  cloud: process.env.CLOUD_CODE_MAIN || __dirname + "/cloud/main.js",
  appId: process.env.APP_ID || "myAppId",
  masterKey: process.env.MASTER_KEY || "", 
  serverURL: process.env.SERVER_URL || "http://localhost:1337/parse", 
  logLevel: process.env.LOG_LEVEL || "info",
  allowClientClassCreation: false,
  filesAdapter: s3Adapter,
  }
});
```

If it can help !

**Comment by srameshr** [comment]
I will give it a try and let you know. Thanks for this @Tybi

**Comment by flovilmart** [comment]
@Tybi if you can, adding this to a PR on the S3 adapter repo would be nice

**Comment by Tybi** [comment]
@flovilmart Ok ! I will do this this week !

**Comment by flovilmart** [comment]
Thanks @Tybi ! I believe this can go into the docs repo as well, where the guide for setting up is

**Comment by carlosrbta** [comment]
Hi, @Tybi thanks, i can run using passing as an instance, but how i can use using config file (pm2 json)?

**Comment by srameshr** [comment]
@Tybi The files I upload via cloud code does not have the unique prefix in its path that digital ocean spaces require.
I get something like ```sfo2.digitaloceanspaces.com/my-file-name-prefix-hash-media.jpeg``` in ```url()``` but I want it to be prefixed with bucket name in order for the link to be valid.
```my-bucket-name.sfo2.digitaloceanspaces.com/my-file-name-prefix-hash-media.jpeg```

**Comment by majidhassan** [comment]
Starting which Parse-Server version are DO Spaces supported?

**Comment by teonivalois** [comment]
Another option is to add the following additional file as an adapter:

```js
var AWS = require("aws-sdk");
var S3Adapter = require('@parse/s3-files-adapter');

class DOSpacesFileAdapter extends S3Adapter {
  constructor(...args) {
    //Set Digital Ocean Spaces EndPoint
    const spacesEndpoint = new AWS.Endpoint(process.env.SPACES_ENDPOINT);
    
    //Define S3 options
    var s3Options = {
      bucket: process.env.SPACES_BUCKET_NAME,
      baseUrl: process.env.SPACES_BASE_URL,
      region: process.env.SPACES_REGION,
      bucketPrefix: process.env.SPACES_BUCKET_PREFIX,
      s3overrides: {
        accessKeyId: process.env.SPACES_ACCESS_KEY,
        secretAccessKey: process.env.SPACES_SECRET_KEY,
        endpoint: spacesEndpoint
      }
    };
    super(s3Options);
  }
}

module.exports = DOSpacesFileAdapter;
module.exports.default = DOSpacesFileAdapter;
```

If you are using parse-server in a docker container, you can even mount the file as part of the container under _/parse-server/lib/Adapters/Custom/_ and reference it via **PARSE_SERVER_FILES_ADAPTER**=_./Custom/DOSpacesFileAdapter.js_

**Comment by tran-huy-phuc** [comment]
I'm getting this error when I try to upload the file from my Parse Dashboard: `expected connection string to start with "mongodb://" or "mongodb+srv://"`

The strange thing is My parse server is connected to Postgres, not mongo. And it works with other data type (string, boolean...)
