### ISSUE TITLE
Increment not working with parallel calls.

### ISSUE THREAD

**Issue by elios264** [parse-community/parse-server#4892]
### Issue Description

Increment op not working with concurrent calls

### Steps to reproduce

Do this: 

![222](https://user-images.githubusercontent.com/15863852/42644215-a30425ee-85c0-11e8-93e7-627cc32f0342.PNG)

 
### Expected Results

a value of 4000 in the cost attribute

### Actual Outcome
3562

![11](https://user-images.githubusercontent.com/15863852/42644233-b1247cf0-85c0-11e8-8f06-8a01c51c3594.PNG)

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.8.2
  - Operating System:     ubuntu
  - Hardware:          ram 1gb, 
  - Localhost or remote server? : DigitalOcean

- **Database**
  - MongoDB version: 3.4
  - Storage engine:  no idea
  - Hardware:        n/a
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): everywhere, in my local computer too.

### Logs/Trace

No error logs no nothing,

**Comment by flovilmart** [comment]
Are you sure all 4000 calls passed and none failed?

**Comment by elios264** [comment]
I just tried again while watching the log,

291 instead of 300

![capture](https://user-images.githubusercontent.com/15863852/42646644-1601ab42-85c7-11e8-8df5-ecd61ddc68fb.PNG)

**Comment by flovilmart** [comment]
Again, there is no guarantee that all your calls are passing, and returning 2xx. Then if you say 2 concurrent increments cause an issue, that’s skmething else. But I’m not convinced that all your calls really are processed by the server and not dropped, throttled or else. 

In the case you’re describing, that would mean 2 different calls return with the same value. Which isn’t proved yet

**Comment by elios264** [comment]
Upon trying to get a case where 2 different calls returning the same value, I discovered than other beforeSave hook was causing this bug, 
Sorry for the inconvenience!
