### ISSUE TITLE
Disable record creation from client code.

### ISSUE THREAD

**Issue by srameshr** [parse-community/parse-server#4894]
### Issue Description

Is it possible to disable ```record``` creation on any ```Class``` via client code by a simple configuration on the server?
Basically, I want ```save``` or ```saveAll``` operations to be triggered by cloud code **only**, without using any ```beforeSave``` trigger on any ```Class```.

### Steps to reproduce

N/A

#### Expected Results
Do this via, chrome JS console.
```
const customClass = Parse.Object.extend('CustomClass');
const customInstance = new customClass();
customInstance.set('foo', 'bar');
customInstance.save();
```
#### Actual Outcome

N/A
### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 3.x
  - Operating System:     Any
  - Hardware:             Any
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): All

- **Database**
  - MongoDB version: 3.x
  - Storage engine:  Any
  - Hardware:        Any
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): All
### Logs/Trace

Include all relevant logs. You can turn on additional logging by configuring VERBOSE=1 in your environment.

**Comment by srameshr** [comment]
Destroys the point of CLP, if I just set every ```public write``` to false.
Right now this is what I am doing. For every ```save``` or ```saveAll``` call from the cloud code, I am setting a key called ```serverAuthKey```. 
The value of that key is set from ```.env``` file and I check for this key to match the right value in ```beforeSave```.

Demo code:
```
Parse.Cloud.beforeSave('MyCustomClass', (req, res) => {
   if (req.object.get('serverAuthKey') === process.env.SECRET_SERVER_KEY) {
     req.object.unset('serverAuthKey'); // So this wont get saved to the db.
     res.success();  
   } else {
     req.object.unset('serverAuthKey'); // Regardless remove that key
     res.error('Authorization failure... bad bad boy'); 
   }
});
```

And during the call, from cloud code:
```
myCustomClassInstance.save({
  ...body,
  serverAuthKey: process.env.SECRET_SERVER_KEY
})
```

**Comment by georgesjamous** [comment]
Yes, I just noticed that using masterKey with CLP will also affect individual object ACL since its using masterKey, I apologize for my mistake.
And yes, just remembered that in one of my projects, I did the exact same thing you did to make sure the request came from CloudCode

**Comment by flovilmart** [comment]
Why can’t you use CLP on this case? Your secret key is basically a master key. If you don’t want to share that masterKey, then that’s another issue.

As for your snippet, this works with cloud code, and I don’t see any issue with it

**Comment by srameshr** [comment]
Can you show a snippet of how you try to achieve this with CLP.

**Comment by georgesjamous** [comment]
@flovilmart 
wouldn't using CLP with master key when updating objects bypass the ACL of the object ?

**Comment by flovilmart** [comment]
CLP are processed before the ACL’s. If you restrict object creation or object to master key only, you’ll need to use the masterKey to update the object. THhen obviously the ACL Will not matter as the masterKey will be used.

**Comment by georgesjamous** [comment]
Yes, that is what I meant.
So, for now, the only solution would be yours  @srameshr

**Comment by flovilmart** [comment]
The server auth key is basically a master key in the sense it’s being used. Not sure there anything to do in parse server. You could also use a custom header, as they are forwarded to all cloud code functions

**Comment by srameshr** [comment]
I don't understand why things get closed without everyone coming to a conclusion.

**Comment by srameshr** [comment]
Oh, ok I found it here in the docs:
```
Add fields: Parse classes have schemas that are inferred when objects are created. While you’re developing your app, this is great, because you can add a new field to your object without having to make any changes on the backend. But once you ship your app, it’s very rare to need to add new fields to your classes automatically. You should pretty much always turn off this permission for all of your classes when you submit your app to the public.
```

**Comment by georgesjamous** [comment]
If you decide to go ahead with what you proposed and already doing, I suggest you create a helper module that secures any function you want with an internally generated key.
You could then register your cloud function like this.

```
Parse.Cloud.beforeSave('MyCustomClass', (req, res) => secure(req, resp, function))
```

Where secure could do everything you do here:

>  if (req.object.get('serverAuthKey') === process.env.SECRET_SERVER_KEY) {
     req.object.unset('serverAuthKey'); // So this wont get saved to the db.
     res.success();  
   } else {
     req.object.unset('serverAuthKey'); // Regardless remove that key
     res.error('Authorization failure... bad bad boy'); 
   }

Hope this helps

**Comment by flovilmart** [comment]
@srameshr I closed the issue because this is not a bug with parse server but an implementation detail to which you already have a proper solution.
We provided multiple possible options, using CLP and I don’t see why this issue should stay open. If you need help for your implementation, you can reach out on stackoverflow or hitter and discuss your solution with other devs.

**Comment by srameshr** [comment]
@flovilmart If you read my question again, you will see that I was asking for a **configuration**, possibly while instantiating ```new ParseServer({})```. So, this ideally stands as a feature request. The discussion was on workarounds for the feature and not the implementation of the feature itself.

**Comment by oallouch** [comment]
Maybe this request is liked to this one : https://github.com/parse-community/Parse-SDK-JS/issues/583

**Comment by flovilmart** [comment]
I’m not sure we’ll implement a system where only the masterKey would work, as you can implement it through CLP. As always, if it’s a feature that you need, we’re open for pull requests. As it stands, i believe this is an unnecessary burden. In your case you’re Using another ‘secret’ (that should be passed as a header instead of an object).
