### ISSUE TITLE
How much optimized is "include"?

### ISSUE THREAD

**Issue by Samigos** [parse-community/parse-server#4896]
This is not much of an issue, but a question... I'm using the `include` constraint pretty often in my app and I would like to know how much optimized it is!

For example, let's say I have a `Post` collection, which has a `user` pointer, which has to be `include`d in a query that returns, say 50 objects. In a hypothetical scenario, let's say 10 out of 50 objects, are created by user "a". Is that user going to be `include`d 10 times, or 1?

If it's `include`d at all times, should I create an additional query to fetch the users, just to make sure I don't have any unnecessary reads?

Thanks in advance!

**Comment by dplewis** [comment]
You can start by looking here 

https://github.com/parse-community/parse-server/blob/master/src/RestQuery.js#L602

All 10 objects will have user a included.

**Comment by Samigos** [comment]
Hmm, I see! So in cases where we fetch 100 objects and 100 `includes have to occur, the performance could really get affected, right?

**Comment by dplewis** [comment]
Maybe I’m wrong here @flovilmart maybe you can help me out

So the way it works if you use 1 query.include(“user”)

There are only two queries that are run

1 query to get all the objects left say 50 are returned

1 query to get all the include pointers in your case you are getting one object.

So if you get 1000 objects with the same user, it’s still 2 queries. One to get the 1000 objects, one to get the one user.

**Comment by flovilmart** [comment]
@dplewis you,re right, we get all the objects to fetch in the include based on the results of the 1st query and building a large `$or`  query with all the values we need to fetch from the DB.

**Comment by Samigos** [comment]
@flovilmart So in the case I mentioned above, where a user exists many times, would it be wise to create a separate query just to fetch distinctly the users?

**Comment by flovilmart** [comment]
It depends if you have the local datastore enabled, and the object is available, you won’t need to fetch it. Server side, the number of DB calls is at the minimum for the includes.
