### ISSUE TITLE
I want to create an object in parse using rest api

### ISSUE THREAD

**Issue by alymohamedhassan** [parse-community/parse-server#4900]
I get this error while creating a parse object that has a pointer field in it using the REST API in python.
{"code":111,"error":"schema mismatch for messages.senderId; expected Pointer<_User> but got String"}

**Comment by georgesjamous** [comment]
Can you please provide the data you are sending?

**Comment by alymohamedhassan** [comment]
{
  "message": "Hello World!!",
  "Users": [
    [
      "12345"
    ],
    [
      "6785"
    ]
  ],
  "senderId": "abpDBYNDL8",
  "chatRoomId": "A56J686ELJ"
}

**Comment by georgesjamous** [comment]
Check this: https://docs.parseplatform.org/rest/guide/#relations
The senderId should be a pointer, like this:
"senderId" :   {"__type":"Pointer", "className":"_User","objectId":"abpDBYNDL8"}

**Comment by alymohamedhassan** [comment]
Thanks georgesjamous, One last, do you know how to query this pointer as in "WHERE sender Id = x"

**Comment by georgesjamous** [comment]
You are welcome, please close this if it is solved.

The documentation is where you should be looking, everything is explained there, I suggest you study them thoroughly as it will help you architect a better project.
https://docs.parseplatform.org/rest/guide/#query-constraints

This is how you do it, following the example from my link.
`where={"playerName":"Sean Plott","cheatMode":false}`
`where={"senderId": {"__type":"Pointer", "className":"_User","objectId":"abpDBYNDL8"}}`
