### ISSUE TITLE
Cloud Code Functions API Versioning

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-server#4902]
**Is your feature request related to a problem? Please describe.**
When a cloud code function updates with breaking response changes, the function has to be given a new name to expose both versions, the old version for older clients, the new for new clients. E.g. a function `sendChatMessage` has to exists beside `sendChatMessage_v2`.

**Describe the solution you'd like**
An API version concept for cloud code functions. The client should pass an API version parameter, or default to the newest version if none is set. That parameter should be used to route to a specific `main.js` file. The versions can be described in folders, e.g. `/cloud/1.2/` containing all the files for API v1.2 including `main.js`.

**Describe alternatives you've considered**
Adding the version name to new functions is an easy workaround but does not make a clear cut between endpoint versions.

**Comment by flovilmart** [comment]
How would you consider passing the version from the client? As the client should know what version of the function to call. Also do you want all functions to move to a version 2 or just a single one?


There is another trick, you can pass the `version` as a parameter, and behind you single function, call the different versions:

```
Parse.Cloud.define('myFunction', (req, res) => {
    const { version } = req.params;
    if (!version) { 
        doOriginalVersion(req, res);
    } else if (version === 2) {
        doVersion2(req, res);
    }
});
```

What do you think?

**Comment by mtrezza** [comment]
Your trick is a clever solution. I am thinking more of the Facebook API model, where API versions are clearly defined with a given "versions" of functions. It separates the API versions and their functions more clearly from each other which makes it also easier to document and manage, e.g. deprecating API versions for clients.

I updated my problem statement above with a suggestion of using a folder structure to contain all files for an API versions.

**Comment by flovilmart** [comment]
@mtrezza do you realize that the parse API is still at version 1? so there has no breaking changes that were introduced since it's lifetime. 

To me, the engineering cost is too high compared to the 'trick' I propose, and I don't see it at something easy to maintain for users.

If you wish to implement it, we may consider merging your pull request but from the get go, I see it as an over engineered solution for a use case that can be solved with the current implementation.

> The client should pass an API version parameter, or default to the newest version if none is set.

This is exactly what I recommend part of the parameters.

I believe you can write a 'loader' for Cloud Code that would handle automatically this use case without changing anything on parse server and using the param trick. I did that in the past, it's bullet proof and simple to use. for example:

```
// This function will run the functions based on the version param
// If the version param is set, will lookup the function and run it
// otherwise will run the default
function versioned(implementations) {
	return function(req, res) {
		const { version } = req.params;
		const impl = implementations[version] || implementations.default;
		return impl(req, res);
	}
}

Parse.Cloud.define('myFunction', versioned({
	'1.1': (req, res) => {},
	default: (req, res) => {}  
}));
```

Then you can imagine something that loads from your cloud folders or something like that or:

```
// myFunction.js

module.exports = {
   default: (req, res) => {}
   '1.1': (req, res) => {}
}
```

Or any other organization.

**Comment by mtrezza** [comment]
Thanks, looks like a good solution to me, also for sake of simplicity.  I'll close this issue for now.

**Comment by mtrezza** [comment]
@flovilmart I stumbled across [this SO answer](https://stackoverflow.com/a/45715823/1870795), proposing to use the mount path to versionize the cloud code. What are you thoughts on this? Could it be a problem if multiple instances of Parse Server run on the same DB?

**Comment by flovilmart** [comment]
It could very well collide and is not recommended

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mtrezza** [comment]
@flovilmart Just to understand, running multiple parse servers with the same cloud code and configuration (storage, push, etc) and a common DB should work fine? For example when migrating to a different PaaS provider and parse server runs concurrently in both environments.

**Comment by flovilmart** [comment]
I don’t believe so. Your objects could end up in a different Sara as 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mtrezza** [comment]
@flovilmart With a common DB I mean, hosted externally, on mLab for example.

**Comment by flovilmart** [comment]
Same thing. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mtrezza** [comment]
@flovilmart Why? Didn't parse.com have the same migration strategy?

![screen shot 2019-02-16 at 00 50 45](https://user-images.githubusercontent.com/5673677/52890433-fc4f2480-3184-11e9-8002-e1ec2c4f3625.png)

**Comment by flovilmart** [comment]
I have no idea what you are referring to, but there is a fact. This fact is that the JS SDK only supports a single instance for a given process, as this JS SDK is used in cloud code. From there, you should never initialize 2 parse server instances, in the same node process. I you don’t believe me, feel free to do what you want 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mtrezza** [comment]
@flovilmart I was referring to something else: One parse server instance running on Heroku, another one on AWS EC2. They run in separate environments but connect to the same database on mLab. Do you see any issues with that? My bad, I should have been more clear.

**Comment by flovilmart** [comment]
No I don’t 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
