### ISSUE TITLE
Parse on aws lambda

### ISSUE THREAD

**Issue by devdeepaknagar** [parse-community/parse-server#4911]
Hi, 
We have setup parse server on lambda, I am facing some issues, when I am trying to access following API url:
https://wybqjcb5gg.execute-api.us-west-2.amazonaws.com/latest/parse/classes/userTemp/PwoarwB36U
Header : 
Content-Type:application/json
X-Parse-Application-Id:***********
X-Parse-REST-API-Key:******************

Method : GET
Sometime I am getting Error1 or Error2 randomly 
Error 1:
{
    "code": 101,
    "error": "Object not found."
}
Error 2:
{
    "message": "Internal server error"
}
I have checked through postman, can you please address the issue.

**Comment by georgesjamous** [comment]
I don't think there is an official guide to setup parse-server on lambda yet.
There is a discussion ticket open here #483 maybe it could help you.
