### ISSUE TITLE
Cannot change password when maxPasswordHistory is 1

### ISSUE THREAD

**Issue by akiowata** [parse-community/parse-server#4918]
### Issue Description

When I set passwordPolicy of maxPasswordHistory: 1,
reset password doesn't work at last step (after inputting a new password).

I found the process below has infinite loop.
https://github.com/parse-community/parse-server/blob/a61ef7ee2f0c21bd48976e43a33f0995d62774ec/src/RestWrite.js#L1018

### Steps to reproduce
1. Set passwordPolicy of maxPasswordHistory as 1.
2. Try resetting password.
 
### Expected Results

That it works.

### Actual Outcome

No responce.

**Comment by flovilmart** [comment]
@akiowata can you provide a workaround? and a PR? That should be an accessible one for a new contributor.

**Comment by paulovitin** [comment]
Exists a test for this scenario:

https://github.com/parse-community/parse-server/blob/master/spec/PasswordPolicy.spec.js#L1405-L1407

**Comment by dplewis** [comment]
Closing via https://github.com/parse-community/parse-server/pull/5191
