### ISSUE TITLE
Parse masterkey security

### ISSUE THREAD

**Issue by Hypothesis-github** [parse-community/parse-server#4919]
The only way I can initialize my app is by using masterkey in `Parse.initialize("myapp1", "thisismymasterkey") ` and I want to know if there is a way to not use the masterkey so that the client side doesnt have access to my database.

```
var api = new ParseServer({  databaseURI: databaseUri || 'mongodb://1.1.1.1:27017/dev',  cloud: process.env.CLOUD_CODE_MAIN || __dirname + '/cloud/main.js',
  appId: process.env.APP_ID || 'myapp1',  masterKey: process.env.MASTER_KEY || 'thisismymasterkey', //Add your master key here. Keep it secret!  serverURL: process.env.SERVER_URL || '1.1.1.1:3333/myapp1',  // Don't forget to change to https if needed  liveQuery: {    classNames: ["Posts", "Comments"] // List of classes to support for query subscriptions  }
});
// Client-keys like the javascript key or the .NET key are not necessary with parse-server
// If you wish you require them, you can set them as options in the initialization above:
// javascriptKey, restAPIKey, dotNetKey, clientKey
var trustProxy = true;
var config = {  "allowInsecureHTTP": true,   "trustProxy": 1,  "apps": [
    {      "serverURL": "http://1.1.1.1:3333/myapp1",      "appId": "myapp1",      "masterKey": "thisismymasterkey",      "appName": "thisistheapp"    },  ],"users": [    {      "user":"admin",      "pass":"12345"    }  ]
```

when I change the `masterkey `in `config `and make it different from `api ``masterkey `I cannot click on my app in the panel anymore as it says authorization failed.

I expect to have a key set in my index.js which has limited operation level for the client

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : latest
  - Operating System:    Ubuntu
  - Hardware:             2gb ram
  - Localhost or remote server? Remote- vps

- **Database**
  - MongoDB version: latest
  - Hardware:        2gb ram
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): vps

**Comment by flovilmart** [comment]
Closing as not an issue and duplicate of a stackoverflow question.

https://stackoverflow.com/questions/51583711/parse-server-questionable-security-of-masterkey
