### ISSUE TITLE
Parse.Installation query with nested matchesQuery returning 0 objects

### ISSUE THREAD

**Issue by moesalih** [parse-community/parse-server#4920]
### Issue Description

I'm trying to get installations with a user with some criteria using the following

```
	var aQ = new Parse.Query('Applicant');
	aQ.withinKilometers('location', job.get('location'), distance);

	var uQ = new Parse.Query(Parse.User);
	uQ.matchesQuery('applicant', aQ);
	uQ.include('applicant');

	var iQ = new Parse.Query(Parse.Installation);
	iQ.matchesQuery('user', uQ);
	iQ.include('user');


	iQ.find({ useMasterKey: true }).then(function(objects) {

		console.log('***** objects', objects.length);
		objects.forEach(function(o) {
			console.log(o.get('user').get('email'));
		});

	}, function(error) {
		console.log(error);

	});
```

Running the user query on its own behaves correctly and I get a list of users, but when I run the installation query to match those users I get nothing.

Am I doing something wrong or is there some sort of limitation on nested Parse.Installation queries? 

 
### Expected Results

Some results

### Actual Outcome

No results

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.8.2
  - Operating System:     mac
  - Hardware:             [FILL THIS OUT]
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): localhost

- **Database**
  - MongoDB version: [FILL THIS OUT]
  - Storage engine:  [FILL THIS OUT]
  - Hardware:        [FILL THIS OUT]
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): mLab

### Logs/Trace

```
verbose: REQUEST for [GET] /parse/classes/_Installation: {
  "where": {
    "user": {
      "$inQuery": {
        "where": {
          "applicant": {
            "$inQuery": {
              "where": {
                "location": {
                  "$nearSphere": {
                    "__type": "GeoPoint",
                    "latitude": 40.9849233,
                    "longitude": -80.2452768
                  },
                  "$maxDistance": 0.0015696123057604772
                }
              },
              "className": "Applicant"
            }
          }
        },
        "include": "applicant",
        "className": "_User"
      }
    }
  },
  "include": "user"
} method=GET, url=/parse/classes/_Installation, user-agent=node-XMLHttpRequest, Parse/js1.11.1 (NodeJS 10.0.0), accept=*/*, content-type=text/plain, host=l
ocalhost:1337, content-length=448, connection=close, __type=GeoPoint, latitude=40.9849233, longitude=-80.2452768, $maxDistance=0.0015696123057604772, class
Name=Applicant, include=applicant, className=_User, include=user
```

**Comment by flovilmart** [comment]
The best way to debug this is to first try to resolve the query for your users (ensuring there are some results) and replace your installation query on the user property with the list of found users. 

Given  your query also, it's possible that it doesn't yeild any result because the users are not referenced in the Installation table?

**Comment by moesalih** [comment]
@flovilmart I did already test doing the user query on its own, and then matching those users:

```
	var aQ = new Parse.Query('Applicant');
	aQ.withinKilometers('location', job.get('location'), distance);

	var uQ = new Parse.Query(Parse.User);
	uQ.matchesQuery('applicant', aQ);
	uQ.include('applicant');



	uQ.find({ useMasterKey: true }).then(function(objects) {

		console.log('***** users', objects.length);
		objects.forEach(function(o) {
			console.log(o.get('email'));
			// console.log(o.id);
		});


		var iQ = new Parse.Query(Parse.Installation);
		// iQ.matchesQuery('user', uQ);
		iQ.include('user');
		iQ.containedIn('user', objects);

		return iQ.find({ useMasterKey: true });

	}).then(function(objects) {

		console.log('***** inst', objects.length);
		objects.forEach(function(o) {
			// console.log(o.get('email'));
			console.log(o.id);
		});

	}, function(error) {
		console.log(error);
	});

```
The first query returns some user objects, but the installation query returns nothing, even though the user property is indeed populated on the installation object

**Comment by flovilmart** [comment]
Can you provide the logs when running with VERBOSE=1?

> even though the user property is indeed populated on the installation object

Can you try with equalTo and a single user? (on which you are sure it exists in the DB?) As well as the screenshot from the dashboard that shows the object properly populated?

**Comment by moesalih** [comment]
I tried equalTo and a single user like you said, and that made me realize I was looking at two different sets of objects for development. I'm such an idiot 🤣 

Thanks for the help.

**Comment by flovilmart** [comment]
Don’t blame yourself, shit happen.

**Comment by dekple** [comment]
I'm still confused. equalTo with a specified user works, but I need the query to fetch the usernames, how could I make that work?
