### ISSUE TITLE
Prod/Dev iOS Token based push settings

### ISSUE THREAD

**Issue by Vortec4800** [parse-community/parse-server#4945]
With the old certificate setup, we needed separate configs for production and dev environments. But now with token push, it's the same either way.

Do we still need to provide two configurations for this to work?

                {
                    token: {
                        key: 'keys/aps_key.p8',
                        keyId: 'XYZ',
                        teamId: 'XYZ'
                    },
                    topic: 'com.myapp',
                    production: true // Prod
                },
                {
                    token: {
                        key: 'keys/aps_key.p8',
                        keyId: 'XYZ',
                        teamId: 'XYZ'
                    },
                    topic: 'com.myapp',
                    production: false // Dev
                }

**Comment by flovilmart** [comment]
I am not sure, did you try with a single configuration?

**Comment by Vortec4800** [comment]
Well if the production key is missing it doesn't seem to work. It does work with production set to dev, but I can't test production quite yet, just was looking to see what to expect.

**Comment by flovilmart** [comment]
The options are passed directly to node-apn, which is documented here: https://github.com/node-apn/node-apn/blob/master/doc/provider.markdown

Which you can read: https://github.com/node-apn/node-apn/blob/master/doc/provider.markdown#provider-certificates-vs-authentication-tokens

So it seems that it doesn't matter at all, you should be good setting ` production: true` for both development and production environments.

**Comment by Vortec4800** [comment]
Ah very good, I didn't realize it was using node-apn under the hood.

It seems like the only difference is which server it connects to, sandbox or production, but both tokens are the same.

I'm still not sure based on their documentation if we need to provide both and it will just send pushes to both environments then, or if we need to have a single config with production set according to what we want to test in order to keep from spamming the other environment with invalid pushes.

**Comment by flovilmart** [comment]
I am not sure either, and we don't have an option at the moment to indicate the app should be used with sandbox or production environment. The alternative is probably to use two parse-server, one for production users, the other for sandbox users, pointing to the same DB, but with the push configuration slightly different.

**Comment by Vortec4800** [comment]
Okay well thanks for the info, this will simplify configuration either way as only the production bool needs to change now, so it's still a win.
