### ISSUE TITLE
[Feature Request] Deselect Keys

### ISSUE THREAD

**Issue by dplewis** [parse-community/parse-server#4948]
**Is your feature request related to a problem? Please describe.**

I often find myself wanting to select all keys except one or a few. This requires me to specify a lot of keys which is a lot of work.

**Describe the solution you'd like**

query.deselect('somefield'); or unselect or exclude or selectAllExcluding()?

If used with select  just remove from select
If used without select all keys added excluding

**Describe alternatives you've considered**

Aggregate project { key: -1 } will exclude that key. (Only for Mongo 3.4+)

Alternatively you can get the schema and find all the keys from that then remove what you don't need

**Additional context**

From a quick glance adding this to Mongo should be pretty easy
Postgres uses * or column names. You don’t know the column names if you only uses exclude. So you’ll have to get all fields first then use exclude

**Comment by ozeas** [comment]
Hello, I would like to help with this, can I?

**Comment by dplewis** [comment]
@ozeas Its all yours feel free to open a PR and let us know if you need direction

**Comment by srameshr** [comment]
@dplewis @ozeas You guys working on this?

**Comment by dplewis** [comment]
It’s up for grabs. Feel free to do a PR.

**Comment by ozeas** [comment]
Hi everyone, I had some personal problems, I could not continue. Sorry about that.

**Comment by flovilmart** [comment]
Take care @ozeas

**Comment by RaschidJFR** [comment]
🙋‍♂️ I want in!
So I just start working on this, right? I guess there's no specific deadline, but anyway I'll try not to delay it that much while getting familiar with the repo.

Just point me in the right direction: It seems to me this is to be done in the [JS-SDK](https://github.com/RaschidJFR/Parse-SDK-JS), not on the server... or why is this posted in the server repo? I'm I supposing wrong?

**Comment by dplewis** [comment]
You have to add it to the server first. Here is a sample PR. https://github.com/parse-community/parse-server/pull/4195

The SDK sends the request to the server

**Comment by RaschidJFR** [comment]
So how do you think guys this restOption should be called? Currently the selecting option is `keys`, so let's call this new option `excludeKeys`, ok?

**Comment by dplewis** [comment]
`excludeKeys` or `exclude` whichever one you want

**Comment by srameshr** [comment]
```exclude```

**Comment by RaschidJFR** [comment]
I have [added and tested](https://github.com/parse-community/parse-server/compare/master...RaschidJFR:unselect-keys) a new restOption as `excludeKeys`. Can you have a look @dplewis ? If that's ok then all proceed to update the docs and add the function to the SDK repo i guess.
