### ISSUE TITLE
CloudFunctions Errors are logged twice

### ISSUE THREAD

**Issue by SebC99** [parse-community/parse-server#4950]
### Issue Description

When we return an error as a response of a Parse Cloud Functions, the error is logged at least twice (sometimes 3 times) with this kind of format:
* [ERROR] Failed running cloud function _FunctionName_ for user _xxxx_ with
* [ERROR] Error generating response. ParseError { code: _XXX_, message: _Error Message_ }
* [ERROR] _Error Message_ { "code": _XXX_, "message": _Error Message_ }

I use the default logger adapter (Winston), with an additional transport on AWS Cloudwatch, but we have the exact same behavior on the instance logs directly.

BTW, errors automatically generated by ACLs (`[ERROR] Object not found. { "code": 101, "message": "Object not found." }`) are only displayed twice, without any info on the Cloud Function or Query or Object that led to the error, which is harder to debug ;)

### Environment Setup

- **Server**
  - parse-server version: 2.8.2
  - Operating System: aws unix
  - Hardware: aws
  - Localhost or remote server? AWS ELB

- **Database**
  - MongoDB version: 3.6
  - Storage engine:  WiredTiger
  - Localhost or remote server? Mongo Atlas

**Comment by flovilmart** [comment]
We need to remove the `ERror generaing respone` part.

**Comment by flovilmart** [comment]
Closing as the PR is merged
