### ISSUE TITLE
Push notification with closed app.

### ISSUE THREAD

**Issue by JoaoArmandoo** [parse-community/parse-server#4953]
Hello, I'm having trouble sending notifications when my app is closed, I read somewhere about services, but I'm a beginner on android and I do not quite understand. I've been able to make notifications work when the application is open, so here I am asking you for an orientation on how to get notifications with an app closed, any help will be appreciated if you have a code related to it and want to share it, help a lot! Thank you.

**Comment by flovilmart** [comment]
Please open an issue on the android SDK or ask the question on stackoverflow. You may have a quicker response there
