### ISSUE TITLE
Correct Config for mailgun

### ISSUE THREAD

**Issue by haroot** [parse-community/parse-server#4964]
I upgraded from an old parse server to latest:

does this look outdated? 

    // Email (used for password reset)
    verifyUserEmails: false,
    emailVerifyTokenValidityDuration: 2 * 60 * 60, // in seconds (2 hours = 7200 seconds)
    preventLoginWithUnverifiedEmail: false,
    publicServerURL: cfg.serverURL,
    // This will appear in the subject and body of the emails sent
    appName: 'Ēvolve',
    emailAdapter: {
      module: '@parse/simple-mailgun-adapter',
      options: {
        fromAddress: 'support@xxxxxxxx.io',
        domain: 'email.xxxxxx.io',
        apiKey: 'key-XXXXXXXXXXXXXXXXX'
      }
    }

maybe @parse/simple-mailgun-adapter should be something else?

Only GMAIL users have no issues, seems like Yahoo, Hotmail users can't reset, and some users don't get the reset email at all.. 

~/parse/node_modules/@parse$ ls
fs-files-adapter  node-gcm  push-adapter  s3-files-adapter  simple-mailgun-adapter

shows is there...

**Comment by flovilmart** [comment]
> Only GMAIL users have no issues, seems like Yahoo, Hotmail users can't reset, and some users don't get the reset email at all..

This means the adapter works correctly, double check your mailgun account. 

From mailgun check that the API calls properly received.

This is not and issue with the server, but from your configuration / usage of mailgun.

Consider asking on stackoverflow / server fault.

**Comment by flovilmart** [comment]
The goal of the adapter design is to let you write your own adapter and best way to send messages to your users.

The mail adapter is a single function, and you should be able to write one or use another one built by the community so indeed, it is designed to switch email plugins with a single configuration.

**Comment by georgesjamous** [comment]
If I may jump in for a second.

@haroot for a production environment or even staging, you shouldn't, or maybe would not need to, have multiple email providers. Having multiple email accounts renders your project less maintainable and kinda messy, where you would want to keep track of all these very different accounts.

Instead, you could purchase a private/dedicated IP address from Mailgun (i think they come in packages now), or ask support to switch your account to a less aggressive (more trusted) IP address.
You can use the same account for different projects.
 
I think this approach is far better than having multiple email endpoints.
Again, just a thought :)

**Comment by flovilmart** [comment]
I’m not even sure what to suggest. This is an opensource project, mailgun if properly configured alongside with your domain verification and best practices works like a charm. I believe you’re placing the blame at the wrong place. And if you feel the mailgun adapter should be deprecated or replaced you can contribute back instead in the form of a pull request.

**Comment by haroot** [comment]
sounds like i'm going to have to make a push, because its not a config issue, read my posts. its a Mailgun Ip getting brownlisted by yahoo issue...

**Comment by flovilmart** [comment]
And how is it relevant to this project? Mailgun’s best practices documentation actually explain you how to work around those. But again; you’re not listening to what we’re saying here. Which is: use any adapter / provider you want; mailgun is the easiest to get started. 

The same way te default files adapter is GridStore, at it’s the easiest to get started.

**Comment by haroot** [comment]
"Will retry in 7200 seconds: postmaster@email.evolvehealth.io → XXX.XXX@yahoo.com 'Password Reset for Ēvolve' Server response: 421 4.7.0 [TSS04] Messages from 104.130.122.15 temporarily deferred due to user complaints - 4.16.55.1; see" , 104.130.122.15 is a mailgun dns ip in my link above: http://tools.tracemyip.org/lookup/104.130.122.15

**Comment by haroot** [comment]
I already read that, its on a shared mailgun ip, otherwise they want $59 a month for a dedicated ip which is a ripoff, when they don't allow me to use my own dedicated smtp server, nor does your code make it easy.. to do so. We are on an app in the appstore, I don't have time to teach you guys how to send low latency data securely across the web, nor do I have time to teach you how to code NodeJs properly and write proper documentation. For example, storing a user with signup() works fine, but when I pass the credentials it does not work fine... EXACTLY AS IN YOUR DOCUMENTATION. So maybe you guys should write documentation properly?  https://docs.parseplatform.org/js/guide/#users

**Comment by haroot** [comment]
You have a tendency to close tickets, but when it comes time to fix your bugs and design flaws, you fail to admit, that REST APi is insecure and OUTDATED!  It was created by a SCIENTIST like myself. the Web was created by a Physicist like myself at CERN. I worked for the LHC @ Cern, put two and two together. Your implementation of websockets is also questionable.

**Comment by flovilmart** [comment]
And your account has been reported for violating our community guidelines.

**Comment by flovilmart** [comment]
Look the issue is closed because it is not related to parse-server but *your* integration with mailgun.
It exists a *MANY* other adapter, using sendgrid, mailjet, or pure SMTP, maintained by the community: https://www.npmjs.com/search?q=parse-server%20mail%20adapter

For the rest, I'm not sure where to start. If there are flaws in the documentation, you're free to open an issue on the docs repository. We do our best to provide a timely support to security issues and to keep the project evolving and moving forward.

It's too bad that you can't read the LICENCE in this repository and this line in particular:

[THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"](https://github.com/parse-community/parse-server/blob/master/LICENSE#L21)

I sincerely wish I could be more of help. 

As a scientist like you, you should perhaps realize you're banging on the wrong door.
