### ISSUE TITLE
PFFile objects in an array have the incorrect server URL

### ISSUE THREAD

**Issue by Vortec4800** [parse-community/parse-server#4971]
### Issue Description

We moved our server to a new domain name, updating the SSL certificates and changed the publicServerURL in the server config to match.

PFFile objects have been updated to the new URL correctly as expected, however we have an array of PFFile objects and those are not getting the new domain.

### Steps to reproduce

Create a new column that is an array and store PFFiles in it. Here is an example from the dashboard:

```
[
  {
    "__type": "File",
    "name": "5be8019fa600f7da7f800ecac4574f15_FDEC2A0E-826C-484E-B044-3D2AAB473A4D.jpg",
    "url": "https://app.olddomain.com:1337/parse/files/app/5be8019fa600f7da7f800ecac4574f15_FDEC2A0E-826C-484E-B044-3D2AAB473A4D.jpg"
  },
  {
    "__type": "File",
    "name": "1ac96668a915e15f597cf7631ad0b631_84C17B55-E8D2-4595-A785-2C30CD5AC2F5.jpg",
    "url": "https://app.olddomain.com:1337/parse/files/app/1ac96668a915e15f597cf7631ad0b631_84C17B55-E8D2-4595-A785-2C30CD5AC2F5.jpg"
  }
]
```
 
### Expected Results

If you try to access a PFFile from a file column, it loads as expected with the new domain. PFFiles contained in the array do not get the new domain.

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.7.2
  - Operating System:     Ubuntu LTS
  - Hardware:             Digital Ocean
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): DO

- **Database**
  - MongoDB version: 3.2
  - Storage engine:  Default
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): Same box

### Logs/Trace

Let me know if you need any logs and I will include.

**Comment by Vortec4800** [comment]
Let me know if you need any additional information, or what the best course of action is to fix this, if the server needs a bug fix or if I need to run through these files and change them somehow, etc.

**Comment by flovilmart** [comment]
You should loop through all your files and update the references. Parse server doesn’t handle file arrays as a type, thar’s why When you serialized them and saved them, they became with the original URL. 

Parse Files columns are stored only with a relative reference to the file URL.

I’m not sure a blanket fix that would rewrite at runtime all the files that are stored in arrays is something we’d want. 

The easiest path is probably migration. A note:

The files in your arrays are pure JSON / JavaScript objects, even if the SDK Interpolates them as Parse.Files so you can store back pure JSON objects in there as you cannot init a Parse.File with a URL from the public api’s

**Comment by Vortec4800** [comment]
Okay thank you for the info and the tip. I understand the technical reasoning, but I'm not crazy about the inconsistency depending on how the files are stored.

Regardless, I was able to get it all fixed. Here is the code I ran on the server, which may be useful for someone else looking for assistance with this:

    var url = require('url');
    
    var fileQuery = new Parse.Query('Product');
    fileQuery.limit(1000);
    fileQuery.find().then(function(products){
        var saves = [];
        _.forEach(products, function(product){
            var images = product.get('productImageFiles');
            var updatedImages = [];
            _.forEach(images, function(file){
                var oldURL = file._url;
                var u = url.parse(oldURL);
                u.host = null;
                u.hostname = 'app.newdomain.com';
                var newURL = url.format(u);
                file._url = newURL;
                updatedImages.push(file);
            });
            product.set('productImageFiles', updatedImages);
            saves.push(product.save(null, { useMasterKey: true }));
        });
        return Parse.Promise.when(saves);
    }).then(function(){
        console.log('done');
    }, function(error){
        console.error('error');
    });

**Comment by flovilmart** [comment]
> but I'm not crazy about the inconsistency depending on how the files are stored.

This is an opensource project, if you feel the current behaviour is not the one that we should have, you can open a pull request with your proposed changes.

**Comment by Vortec4800** [comment]
Well I feel like as a core contributor you would have a better understanding of the entire system than I, and a desire to keep complexity at a minimum, which is reasonable. I also think you're probably right that a runtime check that rewrites files in certain instances on the fly is probably not ideal. I do wish there was a better way of handling this scenario, but I'm not sure what it is, and I'm also not sure how often servers change their public URLs that would necessitate coming up with a solution for it.
