### ISSUE TITLE
Return new Error from cloud function should respond with error

### ISSUE THREAD

**Issue by stage88** [parse-community/parse-server#4991]
# Before opening the issue please ensure that you have:

- [x] [Read the migration guide](https://github.com/parse-community/parse-server/blob/master/3.0.0.md) to parse-server 3.0.0
- [x] [Read the migration guide](https://github.com/parse-community/Parse-SDK-JS/blob/master/2.0.0.md) to Parse SDK JS 2.0.0

### Issue Description

Am I doing something wrong. I have:

```js
Parse.Cloud.define('my-function', async request => {
  logger.trace('my-function', request);
  const { user } = request;
  if (!user) {
    return new Error('Need user');
  }

  try {
    const isValid = await validate(request.user);
    if (!isValid) {
      return new Error('Invalid user');
    }

    return {
      hello: 'world'
    };
  } catch (err) {
    logger.error('Error in my-function', err);
    return new Error('Unexpected server error');
  }
});
```

Should Parse Server respond with an error when I ```return new Error('Need user');```?

### Steps to reproduce

See above
 
### Expected Results

Expected an error response from Parse.

### Actual Outcome

Parse responds with HTTP 200 and 
```js
{
    "result": {}
}
```

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 3.0
  - Operating System:     Mac OS
  - Hardware:             Macbook
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Local

- **Database**
  - MongoDB version: 4.0.1
  - Storage engine:  default
  - Hardware:        Mac OS
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): Local

**Comment by stage88** [comment]
With a small mod to one of the functions in FunctionsRouter.js, it does work as expected:

```js
static createResponseObject(resolve, reject, message) {
  return {
    success: function (result) {
      // *** start mod
      // parse error, process away
      if (result instanceof Parse.Error) {
        return reject(result);
      }

      // If it's an error, mark it as a script failed
      if (result instanceof Error) {
        return reject(new Parse.Error(Parse.Error.SCRIPT_FAILED, result.message));
      }
      // *** end mod

      resolve({
        response: {
          result: Parse._encode(result)
        }
      });
    },
    ...
  };
}
```

Then the response is as expected with HTTP 400:
```js
{
    "code": 141,
    "error": "Need user"
}
```

**Comment by flovilmart** [comment]
Use throw error as stated in the migration guide

**Comment by stage88** [comment]
Hi Florent,

Thanks for your reply, however I disagree with your thinking. While ideologically you are correct, pragmatically this doesn't really make sense. There are a lot of people that use Parse in complicated scenarios of which you haven't thought of yet. You have removed a core functional feature in Parse which is to respond with an error without throwing an exception and breaking the execution of your code.

For us, in production it does not always make sense to throw errors, we have too many scenarios above in which the throw inside the try/catch would not work as you described since the catch would hide the original error.

I small change like the one I described above would work just fine, for now we are happy to maintain our own fork.

**Comment by flovilmart** [comment]
This ain’t **my** thinking. Just sticking with node semantics to make sure it’s easier and consistent with the platform used by millions.

If you wish to maintain a fork, that’s on you. 

Also, you don’t have to throw an error, but you can use `return Promise.Reject(new Error())`.

**Comment by flovilmart** [comment]
Just to make sure I am properly understood, there are two ways to notify a caller from an async function of an error:

- `throw new Error()`
- `return Promise.reject()`

`return new Error()` ain’t one of those.

**Comment by stage88** [comment]
Ah ok, Promise.reject. Maybe that should be an example in your migration guide :)

**Comment by flovilmart** [comment]
You can very well open a pull request and suggest a change if it should be in the migration guide.

**Comment by nebitrams** [comment]
In Parse-Server 3.1.3 onwards, is it normal to see error log with stack trace whenever I throw an error in cloud function?  In parse-server 2.x, returning error using response.error did not cause he server to show stack trace.

Sample cloud function:
`Parse.Cloud.define("createUserByAdmin", (request) => {
    throw new Error("This is my error.");
});`

I see this log with stack trace in the server.

`error: This is my error. message=This is my error., stack=Error: This is my error.
    at error (/Users/xxxx/Documents/heroku/appname/branch-parse-server-3/node_modules/parse-server/lib/Routers/FunctionsRouter.js:121:16)
    at processTicksAndRejections (internal/process/next_tick.js:81:5), code=141`

**Comment by flovilmart** [comment]
This is not related to parse-server 3.1.3 but because you are throwing and Error instance, which has a stacktrace part of it’s construction.

If you wish to avoid it, use `return Promise.reject(‘This is my Error’)`

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nebitrams** [comment]
I changed it to `return Promise.reject('This is my Error.')` but I still see the same stack trace.

**Comment by flovilmart** [comment]
My bad, Feel free to open a PR if this behavior is problematic 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nebitrams** [comment]
I am alright with seeing stack trace from throw new Error("This is my error.").

When I refactor my code further, I notice another problem which is a bit more serious.  In the parse-server 2.8.3 (with jssdk 1.11.1), I see the line number of the original code upon an unexpected runtime error.  This is very useful for troubleshooting.  In the example below, Parse SDK 2 does not show the line number of original code.  This makes it very difficult to trace the root of the error.

**Parse SDK 2**
error: Failed running cloud function testAppTeam for user xxxxxxx with:
  Input: {"flag":true,"dummy":"dondon","param1":"Haha","param2":"Cheess","param3":false,"param4":false}
  Error: {"message":"Cannot read property 'length' of undefined","code":141} functionName= testAppTeam, message=Cannot read property 'length' of undefined, code=141, flag =true, dummy =dondon, param1=Haha, param2=Cheess, param3=false, param4=false, user=xxxxxxx
error: Cannot read property 'length' of undefined message=Cannot read property 'length' of undefined, stack=Error: Cannot read property 'length' of undefined
    at error (/Users/xxx//app/branch-parse-server-3/node_modules/parse-server/lib/Routers/FunctionsRouter.js:121:16)
    at processTicksAndRejections (internal/process/next_tick.js:81:5), code=141

**Parse SDK 1.11.1**
error: TypeError: Cannot read property 'length' of undefined
    at ParsePromise.<anonymous> (**/Users/xxx/app/main/cloud/MyAppTeamClass.js:252:26**)
    at ParsePromise.wrappedResolvedCallback (/Users/app/main/node_modules/parse/lib/node/ParsePromise.js:152:43)
    at ParsePromise.value (/Users/xxx/app/main/node_modules/parse/lib/node/ParsePromise.js:90:36)
    at ParsePromise.<anonymous> (/Users/xxx/app/main/node_modules/parse/lib/node/ParsePromise.js:162:29)
    at ParsePromise.wrappedResolvedCallback (/Users/xxx/app/main/node_modules/parse/lib/node/ParsePromise.js:152:43)
    at /Users/xxx/app/main/node_modules/parse/lib/node/ParsePromise.js:218:35
    at processTicksAndRejections (internal/process/next_tick.js:74:9) code=141,

**Comment by mikebolivar** [comment]
to return error from a cloud function I used this and works for me:


`  throw new Error('Unexpected server error, my error')
`

**Comment by capacitivellc** [comment]
`throw new Error('Unexpected server error, my error')`

results in html being sent to the client, not {
    "code": 141,
    "error": "..."
}

Received an error with invalid JSON from Parse: <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Error: foo<br> &nbsp; ...</pre>
</body>
</html>

**Comment by mtrezza** [comment]
@capacitivellc Can you please open a new issue, fill out the issue template and reference this issue if it is relevant?
