### ISSUE TITLE
LiveQuery returns originalObject instead of Update

### ISSUE THREAD

**Issue by dplewis** [parse-community/parse-server#4998]
### Issue Description

using `subscription.on('update', (object))` works but returns original object when a pointer is unset
It does work when the pointer it changed to a different pointer but not on unset

### Steps to reproduce

1. Set a pointer field in dashboard
2. call subscription to on update
3. Unset / delete value in pointer field in dashboard
 
### Expected Results

Updated object to have pointer field unset / not returned

### Actual Outcome

Updated object has old pointer field value

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 3.0
  - Operating System:     Mac OSX
  - Hardware:             [FILL THIS OUT]
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc):  Localhost

- **Database**
  - MongoDB version: 3.4
  - Storage engine:  mmapv1
  - Hardware:        [FILL THIS OUT]
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): mLab

**Comment by dplewis** [comment]
I don’t know much about how live query works internally. I’ll give it a look.

**Comment by alvinthen** [comment]
May be relevant, consider a class with a field of Array<Pointer>, initially with empty array, when adding a Pointer to the field using `.add()`, the same field in the object sent back to the `update` callback has two identical Pointer.

console.log shows the length of the array is indeed 2, but in actual, there's only one Pointer seen in the dashboard, or after calling `fetch()`, or when inspecting in debug console.

The query is just simply `q.include(User)`

**Comment by joshuadiezmo** [comment]
I think this is not live query problem. I check the variables that live query pass to my javascript sdk. and when I unset the pointer, it gives me object without the pointer. but when I console.log the object, the pointer are still on my object. the problem was on the javascript SDK.

**Comment by joshuadiezmo** [comment]
[![IParse server livequery Pointer problem](https://img.youtube.com/vi/rYiA_a_b7b4/0.jpg)](https://www.youtube.com/watch?v=rYiA_a_b7b4)

**Comment by dplewis** [comment]
Closing via https://github.com/parse-community/Parse-SDK-JS/pull/714
