### ISSUE TITLE
Any Way to LiveQuery _User ???

### ISSUE THREAD

**Issue by haroot** [parse-community/parse-server#5002]
Would like to be able to for live stats collection, if not I can use socket.io

let api = new ParseServer({
  ...,
  liveQuery: {
    classNames: ['User']
  }
});

there is also an issue where you can creater a Class named "User" hence having two Users in Dashboard _User -> User and User -> User

**Comment by flovilmart** [comment]
Just use _User as the class name in the list instead of User.

**Comment by haroot** [comment]
I tried that wasn't able to get any output when I subscribed to both User and _User in case

**Comment by haroot** [comment]
Could CLP and ACLs prevent LiveQuery from working possibly ? I

**Comment by haroot** [comment]
Yah ACLs can prevent it from working thanks a bunch

**Comment by haroot** [comment]
any way I can keep more secure ACLs and pass useMasterKey somewhere here?

let query = new Parse.Query('People');
query.equalTo('name', 'Mengyan');
let subscription = query.subscribe();

**Comment by flovilmart** [comment]
Well you should be able to subscribe to the _User object as long as you can read it.
I don’t see why it would not work. 

If it’s the case, then open an issue with properly filling all required informations, VERBOSE logs and code samples.

**Comment by haroot** [comment]
yah I added Public Read it worked, but I had previously only READ/WRITE set to user objectId

**Comment by mstephano** [comment]
Hi, I have created a branch from my repo specially for you as an exmaple to Live Query on User object. Check it out: https://github.com/mstephano/parse-server-live-query-with-angular/tree/feature/LiveQueryUser

**Comment by flovilmart** [comment]
@mstephano I’m not sure how it is relevant to the current question, nor where it’s implemented. The issue is also closed. If there are some documentations improvements that can be done, feel free to open a Pr.

I’m not sure what your project does, but it looks unrelated to the current issue.
