### ISSUE TITLE
query.get is using find which creates issues with BeforeFind

### ISSUE THREAD

**Issue by mullwaden** [parse-community/parse-server#5006]
### Issue Description
I am having issues with the isGet parameter in the beforeFind trigger. While my query is definitely a .get isGet does not seem to be set correctly.

* When I run the following command in the front-end ``(new Parse.Query('BusinessUnit')).get('HlNbtoSUiR')`` the parse-js-sdk creates a POST request to ``http://localhost:1337/parse/classes/BusinessUnit``.
* This triggers ``handleFind`` (not ``handleGet``) in ``ClassesRouter.js`` in the back-end. This is likely because handleGet expects a route with the following format ``/classes/:className/:objectId`` but as the get in the frontend uses .first it ends up calling ``/classes/:className``
* ``ClassesRouter.js`` then triggers find() in ``rest.js`` which in turn calls the ``beforeFind`` trigger with ``isGet`` set to false

Relevant files:
https://github.com/parse-community/Parse-SDK-JS/blob/master/src/ParseQuery.js
https://github.com/parse-community/parse-server/blob/master/src/Routers/ClassesRouter.js
https://github.com/parse-community/parse-server/blob/master/src/rest.js

### Steps to reproduce
Run any query.get command and look at the network tab
 
### Expected Results
A .get query in the frontend GETs on ``/classes/:className/:objectId``

### Actual Outcome
A .get query in the frontend POSTs on ``/classes/:className``
(the POST vs GET bit is probably fine, but the route seems off)

**Comment by flovilmart** [comment]
Can you provide the logs when running with VERBOSELY=1 p’ease?

**Comment by mullwaden** [comment]
Sure thing, so when i run the following command ``(new Parse.Query('BusinessUnit')).get('HlNbtoSUiR')``

It prints:
```
[1] verbose: REQUEST for [GET] /parse/classes/BusinessUnit: {
[1]   "where": {
[1]     "objectId": "HlNbtoSUiR"
[1]   },
[1]   "limit": 1
[1] } method=GET, url=/parse/classes/BusinessUnit, host=localhost:1337, connection=keep-alive, content-length=228, pragma=no-cache, cache-control=no-cache, origin=http://localhost:3003, user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36, content-type=text/plain, accept=*/*, referer=http://localhost:3003/active-search-list, accept-encoding=gzip, deflate, br, accept-language=en-US,en;q=0.9, objectId=HlNbtoSUiR, limit=1
```

in beforeFind for BusinessUnit I get the following parameters:

```
{
  "triggerName": "beforeFind",
  "query": {
    "where": {
      "objectId": "HlNbtoSUiR"
    },
    "limit": 1
  },
  "master": false,
  "count": false,
  "log": { ... },
  "isGet": false,
  "headers": {
    "host": "localhost:1337",
    "connection": "keep-alive",
    "content-length": "228",
    "pragma": "no-cache",
    "cache-control": "no-cache",
    "origin": "http://localhost:3003",
    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36",
    "content-type": "text/plain",
    "accept": "*/*",
    "referer": "http://localhost:3003/active-search-list",
    "accept-encoding": "gzip, deflate, br",
    "accept-language": "en-US,en;q=0.9"
  },
  "ip": "::1",
  "user": { ... },
  "installationId": "ffbaf088-79e9-89f6-5afa-19f0ba39639c"
}
```

**Comment by mullwaden** [comment]
Made a little workaround in my beforeFind which works but doesnt feel quite right:

```
  let isGetFixed = isGet;

  if (!isGet) {
    isGetFixed = query._where && isParseId(query._where.objectId) && query._limit === 1;
  }
```

**Comment by flovilmart** [comment]
Closing as behaving as expected. The isGet denotes if using the endpoint with objectId, not a query on the objectId.  Please update your code accordingly

**Comment by mullwaden** [comment]
Hmm ok, how would I write it correctly in the front-end? Seems strange to me that .get is not isGet

**Comment by flovilmart** [comment]
Use Parse.Object() ‘s [fetch]
(http://parseplatform.org/Parse-SDK-JS/api/v2.0.2/Parse.Object.html#fetch) instead of a query. Perhaps isGet is not the right term, or is confusing, but I won’t do what you expect it to do.

**Comment by mullwaden** [comment]
I see, maybe isFetch would be a better name - anyhow easy to work around, just confusing

**Comment by flovilmart** [comment]
yeah maybe. But we won't consider this change at the moment.
