### ISSUE TITLE
Aggregations with pointers does not work

### ISSUE THREAD

**Issue by srameshr** [parse-community/parse-server#5007]
### Issue Description

Aggregate query documentation does not mention that the pointer field names should be appended with ```_p_``` while querying.

### Steps to reproduce

If you have a pointer field by name ```createdBy```, then:
**THIS DOES NOT WORK**
```
{
  project: { 'createdBy': 0 }
} 
```

** THIS WORKS**
```
{
  project: { '_p_createdBy': 0 }
} 
```
### Expected Results

Update the docs to reflect this nuance.

### Actual Outcome

N/A

### Environment Setup

N/A

**Comment by flovilmart** [comment]
Actually it should probably not be the case, I'M not sure why this is like that @dplewis any idea why the keys are not properly transformed?

**Comment by dplewis** [comment]
Which version of Parse Server you are running?

There is a test case for this already.

https://github.com/parse-community/parse-server/blob/master/spec/ParseQuery.Aggregate.spec.js#L762

```
it('project pointer query', (done) => {
    const pointer = new PointerObject();
    const obj = new TestObject({ pointer, name: 'hello' });

    obj.save().then(() => {
      const pipeline = [
        { match: { objectId: obj.id } },
        { project: { pointer: 1, name: 1, createdAt: 1 } }
      ];
      const query = new Parse.Query(TestObject);
      return query.aggregate(pipeline);
    }).then((results) => {
      expect(results.length).toEqual(1);
      expect(results[0].name).toEqual('hello');
      expect(results[0].createdAt).not.toBe(undefined);
      expect(results[0].pointer.objectId).toEqual(pointer.id);
      done();
    });
  });
```

**Comment by flovilmart** [comment]
I'Ll be closing this one as we explicitely have a test for it. If you consider reopening an issue, please attach logs as well as server version and also a full code snippet.

**Comment by srameshr** [comment]
@dplewis @flovilmart I was on ```2.8.x```, after upgrading to ```3.0``` it works without ```_p_```

**Comment by dplewis** [comment]
@srameshr that’s great! Let us know how the migration goes too

**Comment by srameshr** [comment]
@dplewis It is breaking, have to replace some of the ```res.success``` calls. Thankfully, ```res.error``` was on one global utility file.

**Comment by flovilmart** [comment]
The breaking changes were to be expected.

**Comment by srameshr** [comment]
One question, out of context to this thread, how do you construct ```_url``` for a file field. With aggregation, it just returns the file name, something like```6a5b69cbe836f5b0c1447ba3e0ea5ece_appname-media.jpeg```

**Comment by dplewis** [comment]
@srameshr I honestly have no idea. A PR was just approved on the hash name so I haven't been up-to-date on it

**Comment by srameshr** [comment]
The actual URL is,
```http://localhost:1337/parse/files/my_app_id/6a5b69cbe836f5b0c1447ba3e0ea5ece_filename-media.jpeg```
I can make some changes to the aggregation query to prepend something like ```${SERVER_URL}/parse/files/${MY_APP_ID}/``` to the filename, but does this format change if I use ```Parse File Adapter```?
