### ISSUE TITLE
clarification on passing aggregates breaking change for 3.0

### ISSUE THREAD

**Issue by raytrask** [parse-community/parse-server#5011]
In the list of breaking changes the last line says:
**The aggregate now require aggregates to be passed in the form: {"pipeline": [...]}**

Can you better explain what that means...perhaps with before and after code snippets?

**Comment by flovilmart** [comment]
@raytrask did you investigate on your own? Checked the updated test suite or other things?

**Comment by acinader** [comment]
I took a look into it.  If you look at the docs: https://docs.parseplatform.org/js/guide/#aggregate you'll see this: 

"You can create a pipeline using an Array or an Object."

with this example 

```
var pipelineObject = {
  group: { objectId: '$name' }
 };

var pipelineArray = [
  { group: { objectId: '$name' } }
];
```

You can see that there is test coverage for both cases:

https://github.com/parse-community/parse-server/blob/master/spec/AggregateRouter.spec.js#L5

So I'm not sure why that is in the upgrade docs (@dplewis any light to shed?) :(.

**Comment by dplewis** [comment]
That’s for the RestApi only

**Comment by dplewis** [comment]
@acinader I can update the change log to specify Rest only. I can update the docs as well. It’s not really a breaking change as it is backwards compatible but we try to push it to allow for multiple stages

**Comment by acinader** [comment]
I think @raytrask point is valid that the changelog is not clear, leaving someone who is upgrading uncertain if they need to address an issue or not.  Would be good to close this out one way or another.  Either by adding more detail (or linking to more detail) or moving it out of breaking change or deleting if not relevant.
