### ISSUE TITLE
Don't make Everyone the default audience on Push.

### ISSUE THREAD

**Issue by DevBakura** [parse-community/parse-server#5016]
**Is your feature request related to a problem? Please describe.**
Unfortunately today I made this mistake of sending a push to over 20k users.
To make is worse the push contained json as text.
This was clearly my fault. But I believe this can be prevented. 

**Describe the solution you'd like**
Don't have the audience selected to "Everyone" by default.

**Describe alternatives you've considered**
Require a confirmation window when sending a push to "Everyone" or over a X limit users.

Also, and I think this is a bit more complex is to detect when the message contains json and is set to text. Maybe show a warning to the user.

**Comment by flovilmart** [comment]
This is not an issue with parse-server, but the dashboard, open the issue on the appropriate repository please.
