### ISSUE TITLE
[Feature Request] Non Distinct Query / Distinct Options

### ISSUE THREAD

**Issue by dplewis** [parse-community/parse-server#5019]
**Is your feature request related to a problem? Please describe.**

Finding non unique values

**Describe the solution you'd like**

Looking for fields with duplicates.
Maybe add a parameter for number of duplicates like 1, 2, or 3, $gt / $eq

**Describe alternatives you've considered**

Currently using the following. 

It groups all field values to be unique but keeps count of how many objects had that value. 
If more than one object had that value its not unique.

```
db.collection.aggregate([
    { "$group": {
        "_id": "$field",
        "count": { "$sum": 1 }
    }},
    { "$match": {
        "count": { "$gt": 1 }
    }}
])
```
**Additional context**

**Comment by flovilmart** [comment]
Closing as a reasonable workaround is available. Adding a new API just for that seems overkill.
