### ISSUE TITLE
Obtaining X-Parse-Push-Status-Id after migrating

### ISSUE THREAD

**Issue by elios264** [parse-community/parse-server#5027]
### Issue Description

How can I get the `X-Parse-Push-Status-Id` ?

I was able get it before using the following code:

  ```
const [,, { headers, response } = {}] = await new Promise((res, rej) => Parse.Push.send(notification, {
    error: rej,
    success: (...args) => res(args),
    useMasterKey: true
  }));

  return response.result && headers['X-Parse-Push-Status-Id'];

```

In this [line](https://github.com/parse-community/parse-server/blob/master/src/ParseServerRESTController.js#L94) you are resolving with multiple arguments but that's not spec compliant with native promises and it does not work. 

I'm not sure how to fix this but to include the push id inside the response object in [here](https://github.com/parse-community/parse-server/blob/d83a0b680854f52ce30205d3558c0133d7f8cf19/src/Routers/PushRouter.js#L43)

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 3.0.0
  - Operating System:     n/a
  - Hardware:             n/a
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): n/a

- **Database**
  - MongoDB version: n/a
  - Storage engine:  n/a
  - Hardware:        n/a
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): n/a

**Comment by flovilmart** [comment]
The JS SDK Shoild probably return it part of the response no? What do you think?

**Comment by elios264** [comment]
That'd be probably a good solution if this was not a function that's only called in cloud code.

![capture2](https://user-images.githubusercontent.com/15863852/45037542-ddb8ff00-b024-11e8-9afb-08afdc6c0904.PNG)

because of that `ParseServerRESTController.js` (inside the parse-server lib) is being invoked directly and just returning its promise, which of course if has only the result, no headers, so the only other solution I can think of is to directly call the `/push` endpoint when you need the push id, and if you don't just use the JS SDK push function.

**Comment by flovilmart** [comment]
Well, that doesn’t change that it’s possible to change what the RESTcontroller returns if it’s seeing a X-Parse-Push-Status-Id in the response headers as it’s doing with the Job id

**Comment by moesalih** [comment]
@elios264 Did you find a solution to this?

**Comment by moesalih** [comment]
@flovilmart I think this is a regression with Parse Server 3.0. We used to be able to get Parse-Push-Status-Id before but not anymore. Do you think this should be reopened and fixed?

**Comment by elios264** [comment]
Hi @moesalih my solution was to patch the lib in PushRouter.js sending the headers as part of the response, I cannot attach anything though because Im in my mobile browser

**Comment by flovilmart** [comment]
This is related to the JS SDK not the server implementation. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
