### ISSUE TITLE
TypeError: res.success is not a function

### ISSUE THREAD

**Issue by greggmojica** [parse-community/parse-server#5032]
Hello,
Using parse-server 2.8.2 and getting the following error, not sure why, any help would be appreciated!

(node:15) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: res.success is not a function
(node:15) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by flovilmart** [comment]
You’re not using 2.8.2 but 3.0.0. I am pretty sure

**Comment by greggmojica** [comment]
@flovilmart how do I resolve this?

**Comment by flovilmart** [comment]
Well you either install 2.8.2 or update the code following the migration guide.

I can guarantee you that your server is not on 2.8.2 OR that you’re calling res.success where you should not. If it broke and it was ‘working before’ but you did ‘nothing’ well, I guess you still did ‘something’

**Comment by nebitrams** [comment]
@greggmojica I hope you have completed your migration.  I have migrated my code with the least code change and share some details in my blog [https://nebitrams.blogspot.com/2019/02/migrating-to-parseserver-3.html](url)
