### ISSUE TITLE
query.withinKilometers() not working at all

### ISSUE THREAD

**Issue by Zerokk** [parse-community/parse-server#5033]
### Issue Description

If I perform a geoquery to my server, it does not return anything. If I remove it, and perform a regular query, it works as expected. This leads me to think that something's missing either at the Parse docs, or something is failing at the server/SDK.

### Steps to reproduce

I've got a collection for my app in which I have a table "Places", for which there is a column called "location", which type is GeoPoint. Got a few mockup places that are just at a few hundred meters from my place, which will be the initial geopoint to look for.

 
### Expected Results

It should retrieve all of these mockup places.

### Actual Outcome

The query returns nothing.

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 3.00
  - Operating System:     Debian Linux (back), Windows 10 (front)
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): VPS

- **Database**
  - MongoDB version: 3.2.11
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): VPS

### Logs/Trace

Parse server logs have nothing in them.

- - - - - 

Here you have my code:
```

            let query = new Parse.Query("Place");
            const geo = new Parse.GeoPoint(geopoint.lat, geopoint.lng)
            const res = await query.withinKilometers("location", geo, 200)        // TODO FIX
                            .include("placeType")
                            .find();

```

If I comment the .withinKilometers part, the query works and retrieves the data I want, but if I let it there, it will fail. I already checked if the "geopoint" data I receive at the method is okay, and it is. The problem must be either in the Parse Server, or Parse SDK.

**Comment by flovilmart** [comment]
We have many tests with the GeoPoints that cover this specific case with mock data.

At this time, you should probably double / triple / quadruple check your code and database contents. 

Consider writing a test case that shows your issue including the creation of objects and the query to find them.
