### ISSUE TITLE
Login with Code sent to Phone Number/Email

### ISSUE THREAD

**Issue by promisenxu** [parse-community/parse-server#5034]
**Is your feature request related to a problem? Please describe.**
In our app, we allow users to sign up with their phone number. As of now, to login with phone number, one needs to provide their password. We want to allow users to login with a verification code sent to their phone.

**Describe the solution you'd like**
It seems to me the best approach is to implement an auth provider that handles the verification process. We would also need to update the authData field for all existing users with a phone number so that they can login.

**Describe alternatives you've considered**
Is there a way to implement this feature without any new code/auth provider? I read through the documentation for Session and User and it doesn't seem possible to me.

**Comment by georgesjamous** [comment]
@promisenxu 
Actually you can.
If the process you are looking for is:
1- user enters phone/email
2- user waits for sms/email
3- user enters passcode got from sms/email
You can create a cloud code function to do this process and edit the password to match the code sent via sms/email

**Comment by promisenxu** [comment]
@georgesjamous Thanks for the reply! Your proposed solution would definitely work for many situations. However, in our situation, users can also choose to login with username and password directly. This would prevent us from changing the password on the fly.

**Comment by flovilmart** [comment]
So a custom Auth adapter is a valid solution in this case. Coupled with a cloud functions. As there is no need to make any change inside the server and the details are specific to your implementation, I’ll be closing this issue

**Comment by Eolykab** [comment]
This is what I also require. Any example of the custom Auth adapter @flovilmart ?  @promisenxu How did you solve this?
