### ISSUE TITLE
How to implement Elasticsearch / fuzzy text search?

### ISSUE THREAD

**Issue by NicksonYap** [parse-community/parse-server#5046]
**Describe the solution you'd like**

I'd like to be able to perform fuzzy text search on Parse Server (preferrably using Elasticsearch)

**Describe alternatives you've considered**

I've considered `query.fullText()` and `query.contains()`, though they can't do fuzzy search

**Additional context**

**Comment by flovilmart** [comment]
It’s unlikely we’ll work on adding elastic search support. You can probably look into using elastic search with mongodb directly.
