### ISSUE TITLE
_User class does not appear completely. 

### ISSUE THREAD

**Issue by charvoa** [parse-community/parse-server#5048]
### Issue Description

I have set up two environment on Heroku : 1) Staging 2) Production
The database on production appears completly on the dashboard, I imported the Staging database from the Production database (with the use of mongorestore and mongodump) 

On Prod, for example I can see the stripeAccountId, or the accountType, which are custom rows added directly from Parse. 
On Staging, I cannot see those rows on dashboard, but they appear on my mongodb data from the shell.

### Steps to reproduce

Import database locally using mondodump from prod env
Export database to staging env using mongostore. 
Launch staging dashboard . 
 
### Expected Results

I want to see the same things between Prod and Staging, as I used the exact same DB. 

### Actual Outcome

Custom rows are not shown . 

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 3.0.0
  - Operating System:     HEROKU (UNIX)
  - Hardware:            HEROKU FREE VERSION
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): HEROKU

- **Database**
  - MongoDB version: 3.6.6
  - Storage engine:  mLab Sandbox
  - Hardware:        mLab Sandbox 
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): mLab

**Comment by flovilmart** [comment]
I believe you didn’t import the _SCHEMA collection or at least the _User Schema found in this table.

**Comment by charvoa** [comment]
@flovilmart  Could you provide me a way of importing the schema ? Or maybe a link ? Thanks !

**Comment by flovilmart** [comment]
There is a _SCHEMA collection in your database that holds all valid keys for all classes, you have to move it as well. Not sure what else I can add

**Comment by charvoa** [comment]
Ok thank you very much !
