### ISSUE TITLE
Returning undefined in cloud code throws error

### ISSUE THREAD

**Issue by dplewis** [parse-community/parse-server#5053]
### Issue Description

Similar to https://github.com/parse-community/Parse-SDK-JS/issues/417 

### Steps to reproduce

```
Parse.Cloud.define('returnUndefined', () => {
  return undefined;
});
```
 
### Expected Results

return undefined / null 
not throw error 

### Actual Outcome

Unhandled Promise Rejection: Error: The server returned an invalid response.

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 3.0.0
  - Operating System:     Mac OSX        
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): localhost

- **Database**
  - MongoDB version: Mongo
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): localhost

### Logs/Trace

```
info: Ran cloud function returnUndefined for user undefined with:
  Input: {}
  Result: undefined functionName= returnUndefined, , user=undefined
verbose: RESPONSE from [POST] /parse/functions/returnVoid: {
  "response": {}
} result=undefined
```

**Comment by dplewis** [comment]
@SebC99 PR? @flovilmart is forcing return null ok?

**Comment by SebC99** [comment]
@dplewis there was no real consensus on the solution and on the impact on SDKs:
- solution 1: return null instead of undefined before stringifying the json. Should have no impact on SDK as null would be understand well in JS and iOS (I don't know for Android)
- solution 2: just display a warning on server side to avoid undefined results, but we will still have the issue
- solution 3: add a status field next to the result field in the json to avoid empty json, which could be ignore by SDKs at first to have no impact.

**Comment by dplewis** [comment]
The rest api returns `{}`, iOS returns `null`, JS returns unhandled promise rejection.

We can at least get rid of the unhandled rejection with a catch

https://github.com/parse-community/Parse-SDK-JS/blob/master/src/Cloud.js#L129

**Comment by flovilmart** [comment]
Uhm ok. On iOS can you show me the equivalent code?

**Comment by dplewis** [comment]
https://github.com/parse-community/Parse-SDK-iOS-OSX/blob/master/Parse/Parse/Internal/CloudCode/PFCloudCodeController.m#L62

Getting the result from the cloud code function works its just how the SDK's handle the response

**Comment by flovilmart** [comment]
alright, that kinda sucks, as in iOS it ends up being `decode:nil`.

let's support it on the JS SDK.

**Comment by dplewis** [comment]
Closed via https://github.com/parse-community/Parse-SDK-JS/pull/682
