### ISSUE TITLE
Making email field mandatory

### ISSUE THREAD

**Issue by imandyie** [parse-community/parse-server#5057]
**Is your feature request related to a problem? Please describe.**
There doesn't seem to be a setting to make email field or other fields mandatory when user signs up.

**Describe the solution you'd like**
Would be nice to pass an array of mandatory fields when initialising the server

**Comment by flovilmart** [comment]
You can validate the user is properly configured with 
```
Parse.Cloud.beforeSave(Parse.User, (req) => {
   const user = req.object;
   if (!user.get('email')) { 
       throw new Error('Email is required');
    }
});
```

I believe this is a great way to validate the users before signup.
