### ISSUE TITLE
Parse server should can easily protect specific fields in class and validate schema

### ISSUE THREAD

**Issue by MatisiekPL** [parse-community/parse-server#5058]
**Is your feature request related to a problem? Please describe.**
I'm very frustrated, because the parse server is not providing any security features to protect specific fields in class and schema. For example I have the the User class. User class should keep basic informations about User. But what happen if I will add to my android game the "admin mode" feat.? The User class should have the adminMode field, but... it can be read and modified by anyone. Another problem is, that we can't protect User class against many unnecessary fields. Any rest client can do that, because parse server is automatically changing the schema of database when new request is handled

**Describe the solution you'd like**
In my opinion, Parse server should have a mode, that will disable automatic schema modification. To protect the specific fields Parse Server should have a special param in schema declaration - "read". In "read" property admin can declare the JS code that will be executed when the read request is incoming. The solution is very similar to Google's Firebase sec. rules. Of course all rest actions will be supported. Also the good idea is to support all those properties not for specific fields but for whole class. That will not cause the repeating code.

**Describe alternatives you've considered**
I was trying to protect fields by Cloud Code, but it was not working on LiveQuery

**Additional context**
I think, that security is very important feature. Without security you can erase all fields in object by one request - it can cause bugs in your app - for example - in raking 

I can make some changes in code and sent PR, but I want to get some review of my idea. Is it a good solution or there are better ideas...

Thanks,
Mateusz Woźniak

**Comment by flovilmart** [comment]
> because the parse server is not providing any security features to protect specific fields in class and schema

This is quite exaggerated, there are ACLs,
CLP and Cloudcode validation to protect your objects, did you try any of those?

> Also the good idea is to support all those properties not for specific fields but for whole class.

You are describing ACL and CLP here.

> The User class should have the adminMode field, but... it can be read and modified by anyone

This is false, the User class by default can only be read/write by himself. 

If you want to have admin users, then you can also design an admin ‘role’ only writable by masterKey. Using roles, ACL’s and CLP, You can achieve what you are describing.

Overall, I believe there is a lot of confusion. You are describing 3 levels of security of which 2 are already implemented (object
And classes) leaving field level security.

Field level security can be achieved with not much effort in cloud code, did you try it?

I am not against a feature described as Field Level Permissions with the same level of granularity as CLP. It can reduce the amount of cloud code boiler plate. 

BUT before you start this endeavour, I want to make sure you exhausted all your options

**Comment by MatisiekPL** [comment]
@flovilmart Thanks for your reply ✨ .

Can your provide an example of Cloue Code ☁️ , that will protect an adminMode field in User? I cannot imagine the real working example :blush:. 

Thanks,
Mateusz Woźniak

**Comment by flovilmart** [comment]
```
Parse.Cloud.beforeSave(Parse.User, (req) => {
  if (!req.master && req.object.op(‘adminMode’)) throw ‘Error!’
});
```

**Comment by MatisiekPL** [comment]
@flovilmart 
Wow, I don't know that it is so easy. Thank you very much.

Thanks,
Mateusz Woźniak
