### ISSUE TITLE
Query regarding node.js platform on which parse is built.

### ISSUE THREAD

**Issue by Ashlin-Siby** [parse-community/parse-server#5059]
I have read everywhere that parse server is open source (built on node js) but couldn't understand much of the code, As I have a requirement of customising the server according to my need. So can someone help me with understanding various services (packages) in node that would help me in understanding and customising the server.

**Comment by flovilmart** [comment]
Your question would be better suited on stackoverflow.

**Comment by Ashlin-Siby** [comment]
Ok @flovilmart
Thanks!
