### ISSUE TITLE
Got "Unable to connect to the Parse API" when calling cloud code

### ISSUE THREAD

**Issue by reallyimeric** [parse-community/parse-server#5062]
### Issue Description

I'm trying cloud code consulting [docs on parseplatform.org](https://docs.parseplatform.org/cloudcode/guide/#cloud-functions) and [migration guide on github](https://github.com/parse-community/parse-server/blob/master/3.0.0.md).

I got "Unable to connect to the Parse API" error when calling cloud code, but how couldn't Parse server connect to itself? Do I need to call `Parse.initialize` and set the api address as I do for parse javascript client? I didn't seen example code doing that.

### Steps to reproduce

```js
Parse.Cloud.define('test', async (req) => {
    const { doll } = req.params;
    const query = new Parse.Query(Parse.Object.extend('Doll'));
    const masterObject = await query.get(doll);
});
```

then call this method using curl
 
### Expected Results

no error reported.

### Actual Outcome

```
{"code":100,"error":"XMLHttpRequest failed: \"Unable to connect to the Parse API\""}
```

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 3.0.0
  - Operating System:     linux
  - Hardware:             x86_64
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): localhost

- **Database**
  - MongoDB version: mongodb 3.6.5 WiredTiger: 3.0.1: (January 8, 2018)
  - Storage engine:   WiredTiger
  - Hardware:         the same with server
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc):  the same with server

### Logs/Trace

```
error: Failed running cloud function test for user undefined with:
  Input: {"doll":"yaya"}
  Error: {"code":100,"message":"XMLHttpRequest failed: \"Unable to connect to the Parse API\""} functionName=test, code=100, message=XMLHttpRequest failed: "Unable to connect to the Parse API", doll=yaya, user=undefined
error: XMLHttpRequest failed: "Unable to connect to the Parse API" code=100, message=XMLHttpRequest failed: "Unable to connect to the Parse API"
```

**Comment by georgesjamous** [comment]
Can you share your server's initialization code?

**Comment by reallyimeric** [comment]
@georgesjamous Thanks for your mention and I found I have missed the `serverURL` field.

The cloud function works after I supply this field.

By the way why it is necessary to provide this field to parse server? Is there actually a real parse javascript client, which is initialized by parse server, in the parse cloud code?

**Comment by georgesjamous** [comment]
Yes, the server uses a regular JS-SDk instance internally for cloud code.
Your will find you answer here [ParseServer.js#L86](https://github.com/parse-community/parse-server/blob/5177d5d0afea357ebfc4af9dac437ea09061d357/src/ParseServer.js#L86)
