### ISSUE TITLE
npm install parse-server not working! 

### ISSUE THREAD

**Issue by thobhanifreddy** [parse-community/parse-server#5067]
### Issue Description
I am trying to install parser sever in my express app, but it's failing with error. 

When I run `npm install parse-server --save`, after few minutes it gives me following error,

```
npm ERR! code E500

npm ERR! 500 Internal Server Error: @parse/s3-files-adapter@1.2.1
```

I even tried, `npm install parse-community/parse-server.git#master` but it's also failing and giving following error:
```
npm ERR! prepareGitDep npm ERR! code E500
npm ERR! prepareGitDep npm ERR! 500 Internal Server Error: @parse/minami@1.0.0
npm ERR! prepareGitDep 
npm ERR! prepareGitDep npm ERR! A complete log of this run can be found in:
npm ERR! prepareGitDep npm ERR!     /Users/freddythobhani/.npm/_logs/2018-09-19T23_47_01_321Z-debug.log
npm ERR! prepareGitDep 
npm ERR! code ENOPACKAGEJSON
npm ERR! package.json Non-registry package missing package.json: github:parse-community/parse-server#master.
npm ERR! package.json npm can't find a package.json file in your current directory.
```

### Steps to reproduce
`npm install parse-server --save`
and 
`npm install parse-community/parse-server.git#master`

 
### Expected Results

Parse server should install successfully.

### Actual Outcome

Errors

### Environment Setup

- **Server**
  
  - Operating System:  macOS High Sierra 10.13.6     
  - node version: 8.9.0
  - npm version: 6.4.1

**Comment by flovilmart** [comment]
See npm current outage: https://status.npmjs.org
