### ISSUE TITLE
Unable to install the simple mailgun adapter.

### ISSUE THREAD

**Issue by plug-developers** [parse-community/parse-server#5068]
Here is a log of my steps to get Email Verification working for my aws bitnami parse server. I believe, I have everything set up correctly, but I will keep getting the 503 error until I can get the simple mailgun adapter installed into my root directory. 

Please help me if you can!

<img width="971" alt="screen shot 2018-09-19 at 11 12 48 pm" src="https://user-images.githubusercontent.com/37726267/45795505-a1f77980-bc61-11e8-988a-958458de8c18.png">

Also -- My package.json file is completely empty. I have never modified this file and the only time I opened it was when I started receiving errors from the installation of the mailgun adapter. The only file that I have been modifying is the Server.js file to implement email verification.

**Comment by georgesjamous** [comment]
The error indicates that the package **package.json** following the path in the logs you sent (.../htcdocs/package.json) is the problem. Not the mailgun package.

Your package.json should not be completely empty. (it wouldn't be a .json file if it were)
If it is, initialize your server using `npm init`, then attempt to install the package.
