### ISSUE TITLE
Can't connect to MongoDB server

### ISSUE THREAD

**Issue by Samigos** [parse-community/parse-server#5071]
I just installed Parse Server 3.0.0 at a NodeJS 8.10 Ubuntu (18.04) server.
That worked perfectly! The thing is, when I'm trying to access my dashboard, it shows me no data!

My MongoDB (4.0.2) is on another Ubuntu (18.04) server...

Here's what I have on `index.js`:
`databaseURI: databaseUri || 'mongodb://ip:27017/db',`

I've made sure the 27017 port is open!
This is my Parse Server log:
`
MongoNetworkError: failed to connect to server [ip:27017] on first connect [MongoNetworkError: connect ECONNREFUSED ip:27017]
0|index    |     at Pool.<anonymous> (/root/parse-server-example/node_modules/mongodb-core/lib/topologies/server.js:564:11)
0|index    |     at emitOne (events.js:116:13)
0|index    |     at Pool.emit (events.js:211:7)
0|index    |     at Connection.<anonymous> (/root/parse-server-example/node_modules/mongodb-core/lib/connection/pool.js:316:12)
0|index    |     at Object.onceWrapper (events.js:317:30)
0|index    |     at emitTwo (events.js:126:13)
0|index    |     at Connection.emit (events.js:214:7)
0|index    |     at Socket.<anonymous> (/root/parse-server-example/node_modules/mongodb-core/lib/connection/connection.js:245:50)
0|index    |     at Object.onceWrapper (events.js:315:30)
0|index    |     at emitOne (events.js:116:13)
`

Any ideas?

**Comment by georgesjamous** [comment]
I am sure that this not a parse-server issue.
Replace "ip" with "127.0.0.1" or "localhost" if your mongo is running locally.
Or with the full mongo uri if its running somewhere else.
Example from the docs:
```
var api = new ParseServer({
  databaseURI: 'mongodb://localhost:27017/dev', // Connection string for your MongoDB database
});
```

**Comment by Samigos** [comment]
> Or with the full mongo uri if its running somewhere else.

Which can be found where?

**Comment by Samigos** [comment]
The problem was indeed a MongoDB issue! For some reason, it didn't allow remote access.
<img width="1367" alt="screenshot at sep 22 15-17-54" src="https://user-images.githubusercontent.com/9467442/45917404-0e9b8f80-be7f-11e8-8ed4-7cd059022df9.png">

Thank you @georgesjamous
