### ISSUE TITLE
Cannot use Facebook Account Kit - Cannot read property "authenticate" of undefined

### ISSUE THREAD

**Issue by krishnakeshan** [parse-community/parse-server#5072]
### Issue Description
I am using Parse Server 3.0.0 and trying to get it to work with Facebook's Account Kit. I have followed the instructions in the docs and done the following:

1. Configured  **facebookaccountkit** inside **auth** passed to **ParseServer()**
```
var polaris = new ParseServer({
  databaseURI: 'mongodb://localhost:27017/polaris',
  cloud: __dirname + '/cloud/main.js',
  appId: 'polarisAppId',
  masterKey: 'polarisMasterKey',
  serverURL: 'http://' + ipAddress + ':1337/polaris',
  auth: {
    facebookaccountkit: {
      appIds: ["app_id_here"],
      appSecret: "app_secret_here"
    },
  },
});
```
2. Getting Access Token inside my Android by going through phone verification.
3. Calling **_linkWith()** in cloud code as:

```
    let accountKitAuthData = {
        "id": accountKitId,
        "access_token": accessToken,
        "last_refresh": lastRefresh
    }

    let user = new Parse.User()
    user._linkWith('facebookaccountkit', accountKitAuthData).then(function (user) {
        console.log("linkWith method finished ")
        console.log("user object type " + (typeof user))
    });
```

However, after all this, I am getting the following error:

`(node:21807) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'authenticate' of undefined`

My best guess is that the **facebookaccountkit** provider is not getting registered due to some reason but I may be wrong. Please help!

### Expected Results
Linking of user with facebookaccountkit credentials

### Actual Outcome
Error:
`(node:21807) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'authenticate' of undefined`
### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 3.0.0
  - Operating System:     Ubuntu
  - Hardware:             -
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Google Cloud Platform

**Comment by flovilmart** [comment]
Can you provide the full stack trace please?

**Comment by krishnakeshan** [comment]
Here's the stack trace:
```

info: Ran cloud function authenticateUser for user vW67ERG1Fx with:
  Input: {"accessToken":"access_token_replaced","lastRefresh":"Sun Sep 23 07:16:53 GMT+05:30 2018","accountKitId":
"account_kit_id_replaced"}  
Result: undefined functionName=authenticateUser, accessToken=access_token_replaced, lastRefresh=Sun Sep 23 07:16
:53 GMT+05:30 2018, accountKitId=account_kit_id_replaced user=vW67ERG1Fx(node:16681)
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'authenticate' of undefined
    at /home/qriltme/parse-server-bracket/node_modules/parse-server/node_modules/parse/lib/node/ParseUser.js:171:20
    at new Promise (<anonymous>)    at new F (/home/qriltme/parse-server-bracket/node_modules/parse-server/node_modules/core-js/library/modules/_export.js:36:28)
    at ParseUser.value (/home/qriltme/parse-server-bracket/node_modules/parse-server/node_modules/parse/lib/node/ParseUser.js:170:16)
    at /home/qriltme/parse-server-bracket/cloud/paytm.js:86:10
    at Promise.resolve.then (/home/qriltme/parse-server-bracket/node_modules/parse-server/lib/Routers/FunctionsRouter.js:187:16)    at <anonymous>    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
(node:16681) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)(node:16681) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by flovilmart** [comment]
You're not using the JS SDK corectly, as described in the documentation, you have to wrap the auth data in to an authData key:


https://github.com/parse-community/Parse-SDK-JS/blob/master/src/ParseUser.js#L79

user._linkWith('facebookaccountkit', { authData: accountKitAuthData }).then(function (user) {
        console.log("linkWith method finished ")
        console.log("user object type " + (typeof user))
    });

**Comment by krishnakeshan** [comment]
that solved it! thank you so much!

**Comment by flovilmart** [comment]
Having looked at the stack trace, you could have figured it out on your own I believe...
