### ISSUE TITLE
Option to query mongo directly from cloud code (instead of additional API request)

### ISSUE THREAD

**Issue by EricNetsch** [parse-community/parse-server#5073]
One of the issues we are seeing is latency when using `get`, `find`, `save` etc from inside of our cloud functions. This is due to firing another API call to parse-server to complete the operations (ex: /:classname/:id)

It would be a great feature to add an option to query the mongo database directly from within the cloud function using parse-server query syntax. this has also caused issues while breaking up our parse-server into microservices since the the API call for the cloud function (ex: `/functions/:functionName`) is actually calling additional endpoints to (ex: `/:classname/:id`) which is hosted on a different microservice entirely. The multiple API roundtrips is causing additional latency for our cloud functions when we could just query mongo directly on the same backend without additional HTTP requests happening (ex: `/:classname/:id`). 

I know this is the nature of parse-server and might require some major feature additions. This also might have implications that effect afterSave and beforeSave functionality. 

An option for the query syntax could look something like this using an additional option `direct:true`
`Parse.Cloud.define("functionName", async (request) => {
    \let query = new Parse.Query("className");
    \return await query.get(request.params.appId,{useMasterKey: true, direct: true});
});`

Any ideas would help. Thanks,

**Comment by flovilmart** [comment]
PARSE_SERVER_ENABLE_EXPERIMENTAL_DIRECT_ACCESS=1 is exactly meant to address this.

**Comment by EricNetsch** [comment]
@flovilmart  Always crushing it on the issues. Amazing thanks so much! 
I didn't see this documented anywhere.

I will try this out asap and report back.

**Comment by flovilmart** [comment]
It’s not documented because it’s experimental and may cause other issues. Be sure to thouroughly look the code and understand what it does and how it work before blindly using it.

Also, it was discoverable by reading the source as it sits in the main initializer.

In any case be careful with this flag as you may encounter things you would not expect. After all, it’s experimental.

**Comment by flovilmart** [comment]
Env variable only.

**Comment by EricNetsch** [comment]
Implemented and confirmed working. The microservice only does `get` queries with masterkey. Is there any potential issues I should be looking out for in this instance?

**Comment by flovilmart** [comment]
The main issue that can arise is perhaps if you have bad code related to users (like login) etc...

I don’t know for sur of all the potential issues, but what I lnow is that many tests don’t pass with the flag on.

You can always clone the repo and find out for yourself :)
