### ISSUE TITLE
response.success() is not a function - Parse Server 3.0.0 Cloud Code

### ISSUE THREAD

**Issue by krishnakeshan** [parse-community/parse-server#5074]
# Before opening the issue please ensure that you have:

- [x] [Read the migration guide](https://github.com/parse-community/parse-server/blob/master/3.0.0.md) to parse-server 3.0.0
- [x] [Read the migration guide](https://github.com/parse-community/Parse-SDK-JS/blob/master/2.0.0.md) to Parse SDK JS 2.0.0

### Issue Description

I am trying to use a cloud function that returns a string with the response.success() method. This worked before 3.0.0 but now it says *response.success()* is not a function. I understand this comes with the update but my cloud functions heavily rely on the response object's success function. What's the best way now to return values from cloud functions to clients?
 
### Expected Results
Cloud function returns value to Android client

### Actual Outcome
Error saying response.success() is not a function

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) 3.0.0
  - Operating System:     Ubuntu 16.04
  - Hardware:             -
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Google Cloud Platform

**Comment by flovilmart** [comment]
Did you really read the migration guide and try to 'just' return the value you want to the client?

**Comment by krishnakeshan** [comment]
Hi, yes I did read the migration guides, both for Parse Server 3.0.0 and Parse JS SDK 2.0.0. However, I'm not experience with JS and cannot figure out how to return values to client.

I did try returning the value to client like so:

```
    let user = new Parse.User()
    user._linkWith('facebookaccountkit', {
        authData: accountKitAuthData
    }).then(function (user) {
        console.log("linkWith method finished ")

        //for now return parse session token
        var parseSessionToken = user.get("sessionToken")
        return parseSessionToken //return session token here
    });
```

**Comment by flovilmart** [comment]
well because you don't return anything to the client. 


```
let user = new Parse.User()
return user._linkWith('facebookaccountkit', {
    authData: accountKitAuthData
}).then(function (user) {
    console.log("linkWith method finished ")

    //for now return parse session token
    var parseSessionToken = user.get("sessionToken")
    return parseSessionToken //return session token here
 });
```

Which is exactly what is described in the guide in the function migration guide.

Also note that we usually recommend using stackoverflow for implementation details as those *issues*  are trivial to solve, unrelated to parse-server.

**Comment by krishnakeshan** [comment]
Right, I was missing the return statement earlier. It works.

Will keep in mind to post to SO next time.

Thanks!!
