### ISSUE TITLE
"Cannot modify user 8BNz8oMty7" error when run _linkWith method

### ISSUE THREAD

**Issue by ns16** [parse-community/parse-server#5075]
### Issue Description

I'm trying to authorize a user through facebook. For this I use the cloud function `facebook`, which takes an object of the form:

```
{
	"data": {
		"email": <email>,
		"authData": {
			"id": <user_id>,
			"access_token": <user_access_token>
		}
	}
}
```

My code:

cloud/main.js
```
const AuthModule = require('./modules/AuthModule');

Parse.Cloud.define('facebook', async function (req, res) {
    const user = await AuthModule.facebook(req.params.data);
    return user.toJSON();
});
```

cloud/modules/AuthModule
```
const randomstring = require('randomstring');

module.exports = AuthModule = {
    facebook: function (data) {
        return new Promise((resolve, reject) => {
            const query = new Parse.Query(Parse.User);
            query.equalTo('email', data.email);
            query.first({ useMasterKey: true })
                .then(async user => {
                    if (!user) {
                        user = new Parse.User();
                        user.set('password', randomstring.generate());
                        user.set('username', data.email);
                        user.set('email', data.email);
                        user = await user.signUp(null);
                    }
                    user._linkWith('facebook', { authData: data.authData })
                        .then(user => resolve(user))
                        .catch(error => reject(error));
                })
                .catch(error => reject(error));
        });
    },
}
```

### Steps to reproduce

Run the command:

```
curl -X POST \
-H "X-Parse-Application-Id: APPLICATION_ID" \
-H "X-Parse-REST-API-Key: REST_API_KEY" \
-H "Content-Type: application/json" \
-d '{ "data": { "email": <email>, "authData": { "id": <user_id>, "access_token": <user_access_token> } } }' \
http://localhost:1337/parse/functions/facebook
```
 
### Expected Results

The _linkWith method succeeds.

### Actual Outcome

The _linkWith method fails.
This is because the _linkWith method calls the Parse.User#save method without the option object with the useMasterKey: true.
[Link to code](https://github.com/parse-community/Parse-SDK-JS/blob/master/src/ParseUser.js#L1022)

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 3.0.0
  - Operating System:     Ubuntu 16.04.5 LTS
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): localhost

- **Database**
  - MongoDB version: 3.6.6
  - Storage engine:  MMAPv1
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): mLab

**Comment by flovilmart** [comment]
Closing as unrelated to parse server.

- _linkWith is a private method
- it should not be used serverside and in the future, all user login/signup related methods may be removed
- this is the expected behavior as those methods are not supposed to be used serverside. As you see in the JS SDK Code, non allow masterKey access.

You have to use another way of achieving whatever you are doing, and probably ask on stackoverflow as we don’t provide implementation related answers here. Github issues are for reporting bugs,

**Comment by mikecann** [comment]
@ns16 hi mate, im running into the same issue as you. Im trying to user _linkWith on the client side to link a google auth to an existing user. I do the same as you (query for user by email first, then attempt _linkWith) but do it all on the client side.

Im really not sure how you are supposed to link to an existing user, the docs tell me this is the correct way to do it: https://docs.parseplatform.org/js/guide/#linking-users but I cant seem to get it to work.

Have you had any luck?

**Comment by JeromeDeLeon** [comment]
I also followed the docs but got no luck. I think they should have explained how to use it properly.

**Comment by dplewis** [comment]
https://github.com/parse-community/Parse-SDK-JS/pull/750

I submitted a PR with a fix. Should be released soon

**Comment by JeromeDeLeon** [comment]
I just updated to version v2.3.1 and I still couldn't figured out how user can logIn with google and link that to their other existing account.

**Comment by dplewis** [comment]
@JeromeDeLeon Have you checked the guide http://docs.parseplatform.org/parse-server/guide/#oauth-and-3rd-party-authentication

**Comment by JeromeDeLeon** [comment]
Yes, I already implemented or tried to use `validateAuthData(authData, options) {}` and `validateAppId(appIds, authData, options) {}`.

What I wanted to do is if I have existing account say, facebook account, and then decided to login using google then I want to link my existing account to google then get a session and use `become()`

like [How to link Google + signed in users on Parse backend on Android?](https://stackoverflow.com/questions/28114422/how-to-link-google-signed-in-users-on-parse-backend-on-android)
