### ISSUE TITLE
Downgrade Parse Server

### ISSUE THREAD

**Issue by Samigos** [parse-community/parse-server#5081]
I've been trying for a day now, to downgrade Parse Server from `3.0.0` to `2.8.4` and I fail every time!

I changed it from `package.json`, `npm install`, go to dashboard, still: `server version 3.0.0`!

Here are the logs of the installation:

    npm install
    npm WARN deprecated uws@10.148.1: stop using this version
    parse-server-example@1.4.0 /root/parse-server-example
    ├─┬ parse-dashboard@1.2.0
    │ └─┬ express@4.16.3
    │   ├── array-flatten@1.1.1 
    │   ├── encodeurl@1.0.2 
    │   ├─┬ finalhandler@1.1.1
    │   │ └── encodeurl@1.0.2 
    │   ├─┬ send@0.16.2
    │   │ └── encodeurl@1.0.2 
    │   └─┬ serve-static@1.13.2
    │     └── encodeurl@1.0.2 
    └─┬ parse-server@2.8.4 
      ├─┬ @parse/push-adapter@3.0.0-alpha2
      │ └─┬ parse@1.11.1 
      │   └─┬ ws@3.3.3 
      │     └── ultron@1.1.1 
      ├── @parse/simple-mailgun-adapter@1.0.2 
      ├── commander@2.16.0 
      ├─┬ express@4.16.2
      │ ├── array-flatten@1.1.1 
      │ └── encodeurl@1.0.2 
      ├── lru-cache@4.1.2 
      ├─┬ mongodb@3.1.1 
      │ └─┬ mongodb-core@3.1.0 
      │   └── bson@1.0.9 
      ├─┬ parse@1.11.1 
      │ └─┬ ws@3.3.3 
      │   └── ultron@1.1.1 
      └── request@2.85.0 
    
    npm ERR! Linux 4.15.0-34-generic
    npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
    npm ERR! node v8.10.0
    npm ERR! npm  v3.5.2
    npm ERR! path /root/parse-server-example/node_modules/.staging/node-pre-gyp-49f396d5
    npm ERR! code ENOENT
    npm ERR! errno -2
    npm ERR! syscall rename
    
    npm ERR! enoent ENOENT: no such file or directory, rename '/root/parse-server-example/node_modules/.staging/node-pre-gyp-49f396d5' -> '/root/parse-server-example/node_modules/bcrypt/node_modules/node-pre-gyp'
    npm ERR! enoent ENOENT: no such file or directory, rename '/root/parse-server-example/node_modules/.staging/node-pre-gyp-49f396d5' -> '/root/parse-server-example/node_modules/bcrypt/node_modules/node-pre-gyp'
    npm ERR! enoent This is most likely not a problem with npm itself
    npm ERR! enoent and is related to npm not being able to find a file.
    npm ERR! enoent 
    
    npm ERR! Please include the following file with any support request:
    npm ERR!     /root/parse-server-example/npm-debug.log

What can I do?

**Comment by flovilmart** [comment]
Did you properly re deploy it to wherever it is supposed to be deployed?

**Comment by flovilmart** [comment]
You should perhaps also use a proper version of npm. 3.5.2 is really not what comes with node 8.10.

**Comment by Samigos** [comment]
So I should downgrade node as well?

**Comment by flovilmart** [comment]
Also closing as unrelated to parse-\server itself, and you should not downgrade. Stackoverflow is a great resource for such questions.

**Comment by Samigos** [comment]
> You should perhaps also use a proper version of npm. 3.5.2 is really not what comes with node 8.10.

I see that `3.5.2` is the latest... what should I do?
