### ISSUE TITLE
Indexes are not automatically created when using fullText on User field

### ISSUE THREAD

**Issue by srameshr** [parse-community/parse-server#5084]
### Issue Description

```fullText``` query fails on ```_User``` collection.

### Steps to reproduce

```
const userQuery = Parse.Query('User');
userQuery.fullText('username', 'foobar')
userQuery.find();
 ```

### Expected Results

Should return some documents from ```User``` collection.

### Actual Outcome

```
error: { MongoError: text index required for $text query
    at queryCallback (node_modules/mongodb-core/lib/cursor.js:248:25)
    at node_modules/mongodb-core/lib/connection/pool.js:531:18
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
  ok: 0,
  errmsg: 'text index required for $text query',
  code: 27,
  codeName: 'IndexNotFound',
  name: 'MongoError',
  [Symbol(mongoErrorContextSymbol)]: {} } code=1, ok=0, errmsg=text index required for $text query, code=27, codeName=IndexNotFound, name=MongoError
```

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.): 3.0.0
  - Operating System:     Mac OSX Sierra
  - Hardware:      Mac OSX Sierra       
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): local

- **Database**
  - MongoDB version: 3.7
  - Storage engine:  Mongo FS
  - Hardware:        
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): localhost

**Comment by flovilmart** [comment]
The error is clear, your table lacks an index. At this time we don’t provide index creation on the fly for those. Please refer to mongo Db driver documentations to create such indexes.

If you feel this is a feature that should be implemented, feel free to open a PR.

**Comment by srameshr** [comment]
```You can use fullText for efficient search capabilities. Text indexes are automatically created for you. Your strings are turned into tokens for fast searching.``` This is from the docs. I specifically raised this cos I assumed parse creates indexes on the fly.

**Comment by flovilmart** [comment]
Can you provide a unit test that reproduces the issue because I assume the tests are covering this.

**Comment by srameshr** [comment]
But for now, can you try to just create a user via the dashboard and then try this scenario out?
```
const userQuery = Parse.Query('User');
userQuery.fullText('username', 'foobar')
userQuery.find();
```

**Comment by srameshr** [comment]
Ok, in the meantime how would one create an index on predefined classes like ```_User``` or ```_Session```.
```db._User.find()``` or ```db._User.createIndex({ username: true })``` throws  ```collection not found```

**Comment by flovilmart** [comment]
I am not sure, perhaps look into getCollection, or better as mentioned above, the mongodb documentation

**Comment by ramiro-ciocca** [comment]
@srameshr, did you find a solution?
I managed to create indexes on _User class with:

db.getCollection("_User").createIndex({"myField": 1})

and I see the index with:

db.getCollection("_User").getIndexes()

but still getting the exception from fullText ("index required for ...")

**Comment by ramiro-ciocca** [comment]
I figured it out how to properly create the index.  I is a text index:

db.getCollection("_User").createIndex({myField: "text"})

**Comment by TheTyrius** [comment]
> `You can use fullText for efficient search capabilities. Text indexes are automatically created for you. Your strings are turned into tokens for fast searching.` This is from the docs. I specifically raised this cos I assumed parse creates indexes on the fly.

It is the same docs that brought me here. Will this issue be reopened? It would be great to have indexes automatically generated for the User class, otherwise the exception of this class could be mentioned in the docs. What do you think?
