### ISSUE TITLE
Why not config cross-domain?

### ISSUE THREAD

**Issue by xugy0926** [parse-community/parse-server#5091]
Sometimes,  Services based on parse-server are part of the microservices.

Requests are forwarded through nginx, which handle cross-domains.

If parse-server also does cross-domain processing, this results in a double cross-domain.

Why not configure cross-domain processing of parse-server to switch?

**Comment by flovilmart** [comment]
Feel free to open a PR if you need a flag tha disables adding certain middlewares.
