### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by Samigos** [parse-community/parse-server#5092]
Parse server version: 2.8.4
Parse dashboard version: 1.2.0
MongoDB version: 4.0.2

Hosting service: DigitalOcean

=================================

I'm transferring my app to a new Parse server and a new MongoDB server.
Everything works fine except the fact that I can't load any images! The content is being fetched properly, but the images don't load. Neither from the app, nor from the dashboard. (I get the `File not found.` there)

Here's how I transferred my db:
`mongodump --host sourceIP -d dbName --port 27017`

and then to load it:
`mongorestore --db dbName dbDir --username “username” —password "password" --authenticationDatabase "admin"`

I did a `db.fs.files.find()` and the images seem to be there just fine!

I also tried uploading a new image file and got the error:
`error 130. Could not store file.`

I believe that this is a db-side issue, because I tested the parse server with another MongoDB I have and it was working!

I also tried creating a new droplet and redo everything, but it didn't fix it!
Any suggestions?

**Comment by flovilmart** [comment]
Did you try with mongodb version 3.x?

**Comment by Samigos** [comment]
No... I don't think version is the issue, since the other MongoDB I mentioned, the one that I tested the parse server with, is also 4.0.2!

**Comment by flovilmart** [comment]
Your best chance would then be to debug the files adapter itself, inserting logs etc...

**Comment by Samigos** [comment]
How can I do that?
(Sorry, I'm not really familiar with the inner parts of a parse server)

**Comment by flovilmart** [comment]
Perhaps start with searching where those errors are thrown from and work backwards from there

**Comment by Samigos** [comment]
I spent 2.5 days of my life, full of stress, just because I had the symbol `&` in my auth password, inside my `databaseURI`! For some reason, it doesn't affect fetching the data but it does affect fetching images!
