### ISSUE TITLE
Parse User being deleted...

### ISSUE THREAD

**Issue by SebC99** [parse-community/parse-server#5100]
Some users (very few) are randomly deleted from database without any reason.
We've checked all our code, and there's not a single "destroy" or "delete" command on any Parse Object (we just mark some objects as deleted with a specific property when we need to) but some rare users are still deleted from MongoDB database
(the _Session and _Installation objects are not).
We've tried to investigate by adding logs or searching in parse-server code but we can't find anything.

Any idea why it could happen?
Thanks!

**Comment by georgesjamous** [comment]
Did you try to query the users specifically by _Id/username/email/any key_ and did not get any result back ?

**Comment by SebC99** [comment]
Yes we've checked on Mongo: the document has been deleted... So there is no more user with those id

**Comment by flovilmart** [comment]
Are you sure no one on your team accidentally deleted the rows? Are you sure you have proper ACL’s so that this cannot occur? More importantly, do you have the logs from your parse-server API for the deletion?

**Comment by flovilmart** [comment]
There are many logs, from the load balancer in front to the server verbose logs, if you don’t have any of those in production, then I suggest you turn all of them on.

**Comment by SebC99** [comment]
I should have been more precise. No one has access to the DB so it's not a human mistake.
Nginx and parse (nodejs) doesn't show any deletion request but just the standard application requests. And suddenly those requests fail as there is no user anymore. 
ACLs on users are the default ones (write access only for the user himself)
We're not logging in verbose mode in production of course as it would result in something huge... 
Are beforeDelete hooks new? I haven't seen those in the documentation before... We could use that to improve logs!!

**Comment by flovilmart** [comment]
@SebC99 when you say no one has access to the DB, are you sure your masterKey didn’t leak? Don’t you have a dashboard up? With parse everybody has access to the DB.

Adding the hook won’t do anything as all requests to your server go through the http interface unless you’re explitely using experimental / undocumented features.

So all the logs should be there already.

**Comment by georgesjamous** [comment]
> Nevertheless, I suggest you set a beforeDelete hook on _User and watch the logs for a while

What I meant was beforeDelete in CloudCode.

**Comment by SebC99** [comment]
The dashboard uses the read only key...
Even internal calls are logged in nginx? Because they are not in nodejs parse logs, that's why I was thinking of the before hook to log the stack trace

**Comment by flovilmart** [comment]
There is no internal direct call that would inconsistently delete a user. 

You can probably understand that analyzing this issue from my standpoint, there is nothing that points directly to an issue with this project, unless you can pinpoint a specific place in. The code that would randomly delete users, I priviledge other théories than ones that imply a failure in this project.

Also, did you have backups that would let your restore orphan objects, by dichotomy, you can perhaps find when the users started to not exist. Also you haven’t provided any logs of users that are successfully saved/referenced/accessed as well as logs that shows a 404 error. Can you provide those please?

**Comment by acinader** [comment]
@SebC99 I'm going to close this for now, pending additional information that could help us determine where the issue may lie.

As an aside, I think that @georgesjamous suggestion to see if you can find the object using another key than objectId is a good idea to see if maybe they are 'hiding' in your mongo collection.

**Comment by JacobJT** [comment]
We had this problem, too. No user delete / destroy calls anywhere in our code that we could find. Users were mysteriously disappearing. I think we were still on Parse.com back then. We got around it by doing, never found a source nor uncovered other issues from blocking this delete.

```
Parse.Cloud.beforeDelete(Parse.User, (req, res) => {
    return res.error(`Deleting users is not allowed`);
});
```

**Comment by SebC99** [comment]
I surely understand!! 
As we've looked in every line of code we had, and every logs we had, without finding any clue, I was really wondering if there was a place in place-server were an object could be destroyed for any reason. 
I really love Parse and all the work that is done to maintain this project, so I really trust you guys, and we've really tried to found the error on our side :)

And yes we have backups so we are able to restore those documents, but we can't know for sure the time of the deletion: we detect those deletions many days (or weeks) after it happened, so those (old) backups are not very granular in term of time.

**Comment by SebC99** [comment]
> Edit:
> 
> I just dug up some old info, we started logging "Delete Attempts". `request.master` was `true`, `request.user` was `undefined`, but there was always a `request.installationId`. I have no record of an Installation or Session with any of the installationIds though, and it hasn't happened in over a year.

@JacobJT yes I was wondering if the deletion of installations (based on push attempts that have failed for example) could lead to a deletion of users in rare cases

**Comment by SebC99** [comment]
@flovilmart just got one this morning, with this nginx log (filtered based on the user objectId):
<img width="1613" alt="capture d ecran 2018-10-06 a 17 11 49" src="https://user-images.githubusercontent.com/3028067/46572736-1aad4400-c98b-11e8-8665-bfd348f4ea71.png">

**Comment by flovilmart** [comment]
I don’t see a call to delete

**Comment by acinader** [comment]
are there any other fields you could try and find that record with?  a name, an email?  i'm wondering if the object id is getting edited.

**Comment by flovilmart** [comment]
Well, what Can I do about it? Did you enable verbose logging so you can trace what the last call were and what code path could have been taken? 

Lastly, did you identify any part in the code that would lead to a deletion of an object after a particular operation? Obviously the logs are giving no value, so now, your best chance is to reproduce the issue.

**Comment by stage88** [comment]
Do you maybe have a TTL on a mongo db collection?

**Comment by SebC99** [comment]
@stage88 thanks but we don't. And it happens for random users, some of them being 2 years old, some of them being 3 days old ... And approximately to 0.01% of our users so hard to reproduce!
