### ISSUE TITLE
Roles not working; no object found unless ACL set to Public Read [PS 2.8.4]

### ISSUE THREAD

**Issue by kross50** [parse-community/parse-server#5109]
### Issue Description

When restricting PFObject to a specific Role, Users cannot see it unless it is set to Public Read.

### Steps to reproduce

1) Create new User
2) Create new Role
3) Modify newly created Role by adding User(s) to Role.users
4) Create new Photo (or whatever new class record) and set ACL to Role (from step 2)
5) Have any User that is a member of Role attempt to read record (from step 4).
 
### Expected Results

Users in Role should be able to read objects that have Role Read perms in ACL.

### Actual Outcome

No objects found with PFQuery in iOS 12 app using Parse-SDK-iOS-OSX 1.17.1 (latest).  Users can only read objects if target object is set to Public Read in its ACL.

### Environment Setup

- **Server**
  - parse-server version: 2.8.4
  - Remote server? Back4App (hosted)

- **Database**
- Remote server? Back4App (hosted)

**Comment by kross50** [comment]
Below example in App Id: 7nuz73slygP42pQBHFF3mx4OuXdbaBVGZiNP9air
 
Role: WemGfQJiWi
      Role.user: yQnK6tzqlJ
            Photo: hBeaCelHzj [ACL: WemGfQJiWi (Role): Read]
                  Cloud Function: testPhotoFind
                        Results: can’t find record unless Photo ACL is set to Public Read.
 
Parse.Cloud.define("testPhotoFind", function(request, response) {
            var token = (request.user ? request.user.getSessionToken() : null);
 
            if (request.master) {
                        var queryPhoto = new Parse.Query("Photo");
                              queryPhoto.equalTo("objectId", "hBeaCelHzj");
                              queryPhoto.first({ useMasterKey: true }).then(function(photo) {
                                          if (photo) {
                                                      response.success(photo);
                                          }
                                          else {
                                                      response.success('Not Found');
                                          }
                              }).catch(function(error) {
                                          response.success(error);
                              });
            }
            else {
                        var queryPhoto = new Parse.Query("Photo");
                              queryPhoto.equalTo("objectId", "hBeaCelHzj");
                              queryPhoto.first({ sessionToken: token }).then(function(photo) {
                                          if (photo) {
                                                      response.success(photo);
                                          }
                                          else {
                                                      response.success('Not Found');
                                          }
                              }).catch(function(error) {
                                          response.success(error);
                              });
            }
});

![rolescenario](https://user-images.githubusercontent.com/5742269/46706336-b687bb80-cbe8-11e8-9f8c-732dec3752b5.jpg)

**Comment by flovilmart** [comment]
Can you write a test that runs against this project and open a pull request? Because as it stands, our test suite covers this particular use case.

**Comment by flovilmart** [comment]
Actually your role name is wrong. I'm not sure how it went through but your role sjhould  be identified by `name`, not by id.

**Comment by kross50** [comment]
I wanted the Role.Name to match the corresponding Subscription.ObjectId that it is associated to.  This is merely my naming convention that shouldn't create any issues correct?

**Comment by georgesjamous** [comment]
@kross50 the role name can be anything you want. This is not the problem here.
The problem is that the RoleName in the Objetc's ACL (the object you want to secure, "Photo")
does not match the RoleName that the user is assigned to.

In photos the RoleName in the ACL is "WemG...." while the actual name of the role is "NR5d..."
