### ISSUE TITLE
When save a Parse.File should not save full url

### ISSUE THREAD

**Issue by meepeek** [parse-community/parse-server#5114]
### Issue Description
When save a Parse.File save full _url path which cause a problem when change server ip/domain.

```
ParseFile {
_name: "b1bd5ca2c3b95f9970aa5da87bbbf715_389034_3546334298436_243493388_n-colored.jpg",
_url: "http://localhost:4001/parse/files/zyl31sZDsmvd1…f715_389034_3546334298436_243493388_n-colored.jpg",
 _source: undefined, _previousSave: undefined}
```
It should not keep the data with http://localhost:4001, it should, instead, generate from the current server config  because the link will break if server ip or domain has been changed.

### Steps to reproduce

1. Save a file object, Parse.File, into any class
2. Query the object, there would be _url in attributes

### Expected Results

```
ParseFile {
_name: "b1bd5ca2c3b95f9970aa5da87bbbf715_389034_3546334298436_243493388_n-colored.jpg",
_url: "parse/files/zyl31sZDsmvd1…f715_389034_3546334298436_243493388_n-colored.jpg",
 _source: undefined, _previousSave: undefined}
```

### Actual Outcome

```
ParseFile {
_name: "b1bd5ca2c3b95f9970aa5da87bbbf715_389034_3546334298436_243493388_n-colored.jpg",
_url: "http://localhost:4001/parse/files/zyl31sZDsmvd1…f715_389034_3546334298436_243493388_n-colored.jpg",
 _source: undefined, _previousSave: undefined}
```

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 3.0
  - Operating System:     OSX
  - Hardware:             Macbook Air 2012
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): localhost

- **Database**
  - MongoDB version: [FILL THIS OUT]
  - Storage engine:  [FILL THIS OUT]
  - Hardware:        [FILL THIS OUT]
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): localhost

**Comment by flovilmart** [comment]
Can you provide a code sample please? When files are saved at the ‘top-level’ of a Parse.Object this behavior should not be exhibited. Only when saved in arrays and when nested on objects.

**Comment by flovilmart** [comment]
Feel free to open a PR to resolve the isdue

**Comment by flovilmart** [comment]
We generate it at runtime in the case we can be sure it’s a Parse.file, in the case of array elements or object properties we can’t be sure and the cost of doing so is high as we’d need to introspect recursively each object and key

**Comment by meepeek** [comment]
Thanks for sharing the information.
