### ISSUE TITLE
List all files or get size of all files in db

### ISSUE THREAD

**Issue by aBuder** [parse-community/parse-server#5120]
Hi,

is there an solution to ge all files in parse-server 3.0.0? Otherwise is there an solution to get size of files Collection?

**Comment by flovilmart** [comment]
There are various projects that scrape the database for files objectslike this one: https://github.com/parse-server-modules/parse-files-utils

**Comment by aBuder** [comment]
@flovilmart Thanks for answer. Is the no other solution? With parse server you can also upload files without referencing these files to an class. 
I  would like to the all files form db and will calculate the size ob all files.

**Comment by aBuder** [comment]
@flovilmart Is there otherweise an solution, that I can fire custom mongo db query?

**Comment by flovilmart** [comment]
I’m not sure what you’re talking about. Files are saved by adapters. So you should perhaps look into the gridstore mongo component instead of here. If you used the S3 adapter, you can probably list all the elements in the bucket etc...

**Comment by georgesjamous** [comment]
@aBuder may I ask, why do you need to list all files directly from their storage location?

If you need to keep a list of your files, why not reference them in a class, it's far less operational cheap than what you are doing if you need to access this information frequently.

Also, your last comment predicates that files are stored in the database using the default storage adapter.

**Comment by aBuder** [comment]
@georgesjamous We build an SAAS product and there the customer has limitation on "cloud size" We just have to check how many megabyte the user use.

**Comment by flovilmart** [comment]
Storing files in mongo is a bad idea, but you should already know that

**Comment by aBuder** [comment]
@flovilmart Where store parse-server the files on default ? I think they would save the files in gridfs

**Comment by flovilmart** [comment]
It’s not because the default stores on mongodb that’s it’s a good idea to use that in production. S3 is a better suited storage technology

**Comment by aBuder** [comment]
@flovilmart Why it is an bad idea to store files in mongodb?

**Comment by flovilmart** [comment]
You tell me, what can be wrong sorting and  fetching images from the DB where the database server usually is RAM and disk bound? 

GridFS is a way to split files in document chunks of 256kb, and is all handled by the driver. You’ll do disk I/o on all your file reads, slowing down you whole DB. Besides that it’s all good
