### ISSUE TITLE
Allowing GET for Cloud Functions

### ISSUE THREAD

**Issue by bohemima** [parse-community/parse-server#5125]
**Is your feature request related to a problem? Please describe.**
POST should not be cached according to the HTTP RFC, GET however is. Allowing parse-server to trigger a function using GET instead of POST would allow the underlying HTTP request to be cached (at least on Android using OkHttp)

**Describe the solution you'd like**
Allow both POST and GET for Cloud Functions in parse-server, which also means that params need to be able to come from the query string. Allowing in the Client SDK to choose if you would like the call to be GET or POST (If the change is done in parse-server you could manually intercept the request and change to GET for the functions-endpoint until changes are made in the Client SDKs)

**Describe alternatives you've considered**
Intercepting the response and storing manually on disk and also intercepting the request and check disk first, allowing for callback to be called twice just like for queries to classes.

**Comment by flovilmart** [comment]
Have you considered using a plain http express server as an alternative instead of cloud functions? Cloud functions were initially developed when no access on the server was provided as a stand-alone alternative to writing an external server. Now that all runs as an express server, I fail to realize the complete necessity to implement such feature, besides adding confusion

**Comment by bohemima** [comment]
Yes, I did consider that as well, haven't given it a try yet. The reason we use Cloud Functions for this specific project is to move some of the complex queries to the server side while keeping it simple to use those queries from the Client SDKs (functions returns arrays of Parse.Object most/all of the time) - what we gained was having the complex queries on the server (yay) but we lost the caching on the clients (mix of iOS/Android/Web)

Would it be possible to use the Parse Client SDK to convert the JSON returned from a custom express route to valid objects on the clients? As I said I haven't given it a go yet but my thought was that since Cloud Functions already handle this, "simply" allowing them to use GET would solve the issue with as little impact as possible.

**Comment by flovilmart** [comment]
If the only thing you actually need is the parser to restore the objects from any JSON array that lives into the SDK, then you could extract that instead. 

In any case, this is not something that fits into the current vision for the server, nor something we have time to develop and maintain. Would you want to implement it?

**Comment by bohemima** [comment]
Well, only and only.. :) Making the requests, retries and potentially more as it goes on. I'll explore our options and see what makes most sense for us right now. Thanks for the input!
