### ISSUE TITLE
Missing Last-Modified Header

### ISSUE THREAD

**Issue by nkranes** [parse-community/parse-server#514]
I am trying to get 304 Not Modified behavior working through Akamai in front of Parse, but they require both ETags and the Last-Modified header.  Is there any reason the Last-Modified header is not coming through.  Thanks!

**Comment by flovilmart** [comment]
You're welcome to provide a Pull Request for that.

**Comment by ArKam** [comment]
Hey community! I'm currently working on the infrastructures abstraction framework like parse and so would like to start contributing to this project.

As a first light task I could take this one, it's old, doesn't seems to be that difficult, but it have a lack of informations as:

Does you need parse to give you the last-modified headers on each requests globally or do you only need it on some specific endpoint like file object ?

I know that there is a limited set of contributors available and hope to give a hand.
With all the hype about FaaS (or rather named serverless trend) incoming, I think that the parse community can gain interest back at its platform.

**Comment by flovilmart** [comment]
@ArKam thanks for wanting to contribute. I'm not sure what @nkranes had in mind, but logically, on queries with multiple objects, the last modified would be the most recent updatedAt, and for a single object, just the updatedAt value of such object.

**Comment by ArKam** [comment]
Hi @flovilmart, nice to read a response on this topic.
Indeed, my question was improperly asked.

I would rather look at the following points:
Does @nkranes is using a mongoDB as the backend for both Files and Objects storage?
Does @nkranes requesting the File API or the Database API?

I am asking that to be able to know what is the scope of the fix and what endpoint should I inspect and fix if needed.

About your own answer, from my experience with object storage backend like S3 or Swift (Openstack) they do send a 304 Not Modified HTTP Response when an object didn't was updated. As it is a defacto way to do things and that most of the biggest CDN like Akamai and CloudFlare are somehow expecting it, I think that I'll try to add this feature.

**Comment by montymxb** [comment]
Haven't seen any push towards handling 304s lately. @ArKam are you still working on this? I'm closing this out pre-emptively as it seems to have hanged, but if you are let me know and we'll reopen this.

**Comment by ArKam** [comment]
Hi @montymxb I'm really sorry, I didn't had time to work on it, I'll try to have something during my next holidays, for now consider it as close, I'll do a push with this issue ID as soon as I'll get time.

**Comment by montymxb** [comment]
@ArKam all good, whenever you have time.
