### ISSUE TITLE
Cannot modify user error when using _linkWith google auth on an existing user..

### ISSUE THREAD

**Issue by mikecann** [parse-community/parse-server#5148]
### Issue Description

I am following this part of the JS SDK docs: 

https://docs.parseplatform.org/js/guide/#linking-1

When you attempt to do that with google auth and an existing user however you end up with the following error:

`error: Cannot modify user JzDZZ4XjW5. ParseError: 206 Cannot modify user JzDZZ4XjW5.`

I suspect this happens with facebook auth too.

### Steps to reproduce

1. create a new user manually with username and password.
1. logout
1. attempt to social-auth login with using google following the guide here: https://docs.parseplatform.org/js/guide/#linking-1
 
### Expected Results

_linkWith should be able to modify the existing user and add the new google auth data. 

### Actual Outcome

`error: Cannot modify user JzDZZ4XjW5.`

### Environment Setup

- **Server**
  - parse-server version: 3.1.0
  - Operating System:   Windows 10 64
  - Hardware:    
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Local

**Comment by ashish-naik** [comment]
@mikecann  Were you able to resolve this issue?

**Comment by mikecann** [comment]
> @mikecann Were you able to resolve this issue?

No idea mate. Cant remember. Ditched parse a while back.

**Comment by 2shrestha22** [comment]
@mikecann I am searching for same issue. I want to automatically link user when signing with OAuth providers but didn't find any solution yet.

**Comment by mtrezza** [comment]
@ashish-naik @2shrestha22 If you are experiencing an issue, please open a new issue (because there is a new issue template) and paste your code and the describe the issue. Ideally, you could in addition submit a failing test case to demonstrate the issue.

**Comment by 2shrestha22** [comment]
@mtrezza, Thank you! It is not issue with Parse but actually with me (or others) unable to find how to make things work. In parse documentation I found cloud code should be used to link unauthenticated user, but being a noob and not knowing JS, things are terribly complicated. It will be nice if I get some help on creating cloud code to automatically link existing user when login with 3rd party auth like google, facebook.

**Comment by mtrezza** [comment]
@2shrestha22 Thanks for clarifying. If you need code level support, I suggest you open a topic in the [community forum](https://community.parseplatform.org). Then, once you found out how to do it, please feel free to suggest an improvement to the docs by opening an [issue](https://github.com/parse-community/docs/issues) there.
