### ISSUE TITLE
Request: Great to know a minimum required version to use each feature

### ISSUE THREAD

**Issue by gtzinos** [parse-community/parse-server#5153]
Hello,

I would like to use a lot of your great features but as we use an older version of parse server, it would be great to have a suggestion of what version of parse server, we should have to use it smoothly.

Thank you very much!

**Comment by dplewis** [comment]
We try to update the docs with requirements. There is also the Changelog. Do you have a feature that you are trying to use that is undocumented?

**Comment by gtzinos** [comment]
Hello @dplewis, thank you very much for your response. I checked the Changelog about the feature of FCM (Firebase Cloud Messaging), but I didn't find when was released. We use the old GSM way and we would like to migrate it to FCM.

Thank you!

**Comment by flovilmart** [comment]
You should always use the latest features of this project as we do not maintain previous versions.

**Comment by flovilmart** [comment]
The latest versions of parse-server always contain improvements that may affect push notifications performance, security etc...

Upgrading to the latest version is the only way to ensure you benefit from all those improvements. 

Then, if you can’t upgrade to the latest version, i am very curious why.

As @dplewis mentioned, the changelog is true place to look for improvements, and notable changes. Then there is the commit history.
