### ISSUE TITLE
Could Parse Platform support unicode field name

### ISSUE THREAD

**Issue by boringwork** [parse-community/parse-server#5156]
I found the Parse Platform not supported unicode field name, but javascript and mongodb supported, I review the code and found regex of the key is only supported english alphabet.
```javascript
    for (var key in attrs) {
      if (!/^[A-Za-z][0-9A-Za-z_]*$/.test(key)) {
        return new _ParseError.default(_ParseError.default.INVALID_KEY_NAME);
      }
    }
```
The fact that most modern programming languages support Unicode naming illustrates the real existence of this requirement and the forward-looking nature of programming language developers.

The following is a programming language that supports Chinese naming in English. The link is a sample code for the demo:

[C](https://github.com/program-in-chinese/overview/blob/master/%E7%A4%BA%E4%BE%8B%E4%BB%A3%E7%A0%81/%E4%BD%A0%E5%A5%BD.c), [C++](https://github.com/program-in-chinese/overview/blob/master/%E7%A4%BA%E4%BE%8B%E4%BB%A3%E7%A0%81/%E9%97%AE%E5%A5%BD.cpp), [C#](https://github.com/program-in-chinese/overview/blob/master/%E7%A4%BA%E4%BE%8B%E4%BB%A3%E7%A0%81/%E5%A4%A7%E5%AE%B6%E5%A5%BD.cs), [CoffeeScript](https://github.com/program-in-chinese/overview/blob/master/%E7%A4%BA%E4%BE%8B%E4%BB%A3%E7%A0%81/%E6%96%90%E6%B3%A2%E9%82%A3%E5%A5%91.coffee), [Common Lisp](https://github.com/program-in-chinese/overview/blob/master/%E7%A4%BA%E4%BE%8B%E4%BB%A3%E7%A0%81/%E6%96%90%E6%B3%A2%E9%82%A3%E5%A5%91.lisp), [FASM](https://github.com/program-in-chinese/overview/blob/master/%E7%A4%BA%E4%BE%8B%E4%BB%A3%E7%A0%81/%E4%BD%A0%E5%A5%BD.asm), [Go](https://github.com/program-in-chinese/overview/blob/master/%E7%A4%BA%E4%BE%8B%E4%BB%A3%E7%A0%81/%E6%96%90%E6%B3%A2%E9%82%A3%E5%A5%91.go), [Haskell](https://github.com/program-in-chinese/overview/blob/master/%E7%A4%BA%E4%BE%8B%E4%BB%A3%E7%A0%81/Haskell%E7%A4%BA%E4%BE%8B.hs), [Java](https://github.com/program-in-chinese/overview/blob/master/%E7%A4%BA%E4%BE%8B%E4%BB%A3%E7%A0%81/%E5%A4%A7%E5%AE%B6%E5%A5%BD.java), [JavaScript](https://github.com/program-in-chinese/overview/blob/master/%E7%A4%BA%E4%BE%8B%E4%BB%A3%E7%A0%81/%E6%96%90%E6%B3%A2%E9%82%A3%E5%A5%91.js), [Kotlin](https://github.com/program-in-chinese/overview/blob/master/%E7%A4%BA%E4%BE%8B%E4%BB%A3%E7%A0%81/%E4%BD%A0%E5%A5%BD.kt), [MySQL](https://github.com/program-in-chinese/jinxiaocun/blob/master/MySQL%E6%95%B0%E6%8D%AE%E5%BA%93schema.sql),[Objective-C](https://github.com/program-in-chinese/overview/blob/master/%E7%A4%BA%E4%BE%8B%E4%BB%A3%E7%A0%81/%E4%BD%A0%E5%A5%BD.m), [Perl](https://github.com/program-in-chinese/overview/blob/master/%E7%A4%BA%E4%BE%8B%E4%BB%A3%E7%A0%81/%E6%96%90%E6%B3%A2%E9%82%A3%E5%A5%91.pl), [PHP](https://github.com/program-in-chinese/overview/blob/master/%E7%A4%BA%E4%BE%8B%E4%BB%A3%E7%A0%81/%E6%96%90%E6%B3%A2%E9%82%A3%E5%A5%91.php), [Python 3](https://github.com/program-in-chinese/overview/blob/master/%E7%A4%BA%E4%BE%8B%E4%BB%A3%E7%A0%81/%E6%96%90%E6%B3%A2%E9%82%A3%E5%A5%91.py), [R](https://github.com/dushoff/Generation_distributions/blob/master/chinese.R), [Ruby](https://github.com/program-in-chinese/overview/blob/master/%E7%A4%BA%E4%BE%8B%E4%BB%A3%E7%A0%81/%E6%96%90%E6%B3%A2%E9%82%A3%E5%A5%91.rb), [Scala](https://github.com/program-in-chinese/overview/blob/master/%E7%A4%BA%E4%BE%8B%E4%BB%A3%E7%A0%81/%E6%96%90%E6%B3%A2%E9%82%A3%E5%A5%91.scala), [Sqlite3](https://github.com/program-in-chinese/overview/blob/master/%E7%A4%BA%E4%BE%8B%E4%BB%A3%E7%A0%81/sqlite%E8%84%9A%E6%9C%AC), [Swfit](https://github.com/program-in-chinese/overview/blob/master/%E7%A4%BA%E4%BE%8B%E4%BB%A3%E7%A0%81/%E5%8F%98%E9%87%8F.swift),

The above is only a test language version that has been verified by the test. Earlier versions and other languages are probably already supported. Unicode strings - Rosetta Code lists more programming languages' support for Unicode, which can be tested one by one.

**Comment by flovilmart** [comment]
Keys are intended to be consumed in other languagesc that may not support this feature. Because the server exposes it all through a REST API, it is impossible to know ahead of time if the client supports this encoding ahead of time.

**Comment by boringwork** [comment]
> Keys are intended to be consumed in other languagesc that may not support this feature. Because the server exposes it all through a REST API, it is impossible to know ahead of time if the client supports this encoding ahead of time.

How about unified use UTF-8 encoding?

**Comment by flovilmart** [comment]
I don’t see the benefit of it directly as it should always be possible for the developer to use keys that match the current valuation pattern.
If you wish to implement a Pr that adds the support for another validation strategy, feel free to do so, but by default I wish to maintain the current behavior.
