### ISSUE TITLE
Create custom data type | ParseConfig | Parse.Object

### ISSUE THREAD

**Issue by GoGross** [parse-community/parse-server#5157]
Is it possible to create a custom data type such as:

"currency": {
                "type": "Currency"
            },
            "number": {
                "type": "Number"
            },
            "phone": {
               "type": "Phone"
            }`
`

**Comment by flovilmart** [comment]
It is not. If you with to validate your data, use beforeSave / afterSave hooks. That’s what they are designed for.

**Comment by GoGross** [comment]
Kindly explain this extract from the docs page:

## Parameters

ParseConfig supports most of the data types supported by Parse.Object:

- string
- number
- Date
- Parse.File
- Parse.GeoPoint
- JS Array
- JS Object

We currently allow up to 100 parameters in your config and a total size of 128KB across all parameters.

**Comment by flovilmart** [comment]
What’s to explain and how it is related to the issue you’ve opened?

The limitations part may not be true, but true config being stored in a single mongodb document, it will be subject to the max document size of your mongo database which varies across versions
