### ISSUE TITLE
i/o failure

### ISSUE THREAD

**Issue by HudiDev** [parse-community/parse-server#5158]
I am using parse server as a BAAS for my android app. 
Everything Is working like a charm, except, when I use the app intensely I.E. if I send several requests in a very small span of time (refreshing the data many times quickly) from my android client to the parse server, the server freezes. and I get a message back from my cloud function saying: "i/o failure".

I am not getting any  info in my parse.logs file related to the issue besides the "i/o failure" message on client-side
I would be more then happy to understand the cause for this issue. and I how to resolve it. 

### Environment Setup

- **Server**
  - parse-server version: 1.17.3
  - Operating System: Ubuntu (Bitnami image)
  - Localhost or remote server? AWS

- **Database**
  - MongoDB version: v3.0.9
  - Localhost or remote server? Localhost

**Comment by flovilmart** [comment]
This means you are saturating your server, you should scale it up, increase it’s capacity or number of instances.

Overall it’s not relate particularly to this project, but any nodejs based program can face this issue. Server fault would be the best place for you to get accurate help.

**Comment by HudiDev** [comment]
The weird part is that It happens even with a single user traffic, meaning even if at this moment currently there is only a single user sending requests intensely, it will still crash, does that make any sense?

**Comment by JacobJT** [comment]
Link me to your server fault post and I'll answer there, but they like to keep these issues about problems with the repo / source code, not problems with your implementation.

**Comment by HudiDev** [comment]
got it 👍

**Comment by HudiDev** [comment]
@JacobJT https://serverfault.com/questions/938061/receiving-i-o-failure-on-parse-server
