### ISSUE TITLE
Cloud Code doesn't save object

### ISSUE THREAD

**Issue by memishood** [parse-community/parse-server#5159]
I tried save an object to parse server using to cloud code but it returns result: undefined,

**Server side:** 

`Parse.Cloud.define("test_function",(req)=>
{
  var params = req.params;
  var query = new Parse.Query(Parse.User);

  query.equalTo('count',params.userObjectId);

  query.find().then({useMasterKey:true,
	success: (obj)=>
	{
		obj.save(null,{useMasterKey: true,
		success: (saveObj)=>
			{
				saveObj.increment('count',1);
				saveObj.save();
                                /* Failed..
                                       return saveObj
                                      .increment('count',1)
                                      .save();   */ 
			},
		  error: (errr)=>
		{
		    console.log('got error');
		}
	   });
	},
	error: (err)=>
	{
		console.log('Got error');
	}
   });
});`

**Client side(Android Studio);**

`private fun updateCount()
    {
        val params:HashMap<String,Any> = HashMap()
        params.put("userObjectId",ParseUser.getCurrentUser().objectId)
        ParseCloud.callFunctionInBackground("test_function",params,object: FunctionCallback<Any>{
            override fun done(`object`: Any?, e: ParseException?) {
                if (e != null){
                    Log.d(tag,e.localizedMessage)
                }
            }
        })
    }`

**Comment by dplewis** [comment]
I’d recommend updating to Parse Server 3.0.

Here you are missing response.success().

**Comment by memishood** [comment]
Hello i use latest version and when add response param, it returns response.success() is not a function

**Comment by flovilmart** [comment]
Yes, because the latest SDK version and server version do not use backbone style callbacks anymore see:

https://github.com/parse-community/parse-server/blob/master/3.0.0.md

https://github.com/parse-community/Parse-SDK-JS/blob/master/2.0.0.md

**Comment by memishood** [comment]
Hello @flovilmart , could you edit my code (server side) as correctly ?, i didn't find my problem on the page you sent. Thx

**Comment by flovilmart** [comment]
What are the topic of both the links I shared and what are the major changes ? Can you please show an example?

**Comment by memishood** [comment]
i downgrade 2.8.4 and now no problem, thx @flovilmart

**Comment by flovilmart** [comment]
Well, you should not do that and upgrade your code to work with the latest version...
