### ISSUE TITLE
request.original in afterSave handler gone

### ISSUE THREAD

**Issue by markuswinkler** [parse-community/parse-server#5167]
### Issue Description

I have an afterSave handler that uses request.original data to check if a field truly has changed.

### Steps to reproduce

try to access request.original
 
### Expected Results

access to request.original

### Actual Outcome

request.original is undefined

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 3.0.0
  - Operating System:     macOS
  - Hardware:             mac
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): localhost

- **Database**
  - MongoDB version: 3.4.13
  - Storage engine:  wired tiger
  - Hardware:        -
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): localhost

### Logs/Trace

**Comment by flovilmart** [comment]
Can you point out a commit that would have removed this feature?

**Comment by markuswinkler** [comment]
It disappeared when I switched from 2.8.4 to 3.0.0

**Comment by flovilmart** [comment]
I just tried to reproduce it with this https://github.com/parse-community/parse-server/pull/5170 and it behaves as expected. The original object is only present on updates (as written in RestWrite.js).

**Comment by markuswinkler** [comment]
ah! my bad. I didn't know that the original is only there in that case.
Funny enough though I never had the problem before that.
Is afterSave not in general called after every save?
Can I safely assume that original is there every time the content has changed?

**Comment by flovilmart** [comment]
It should be there whenever there was an original object in the DB ‘before’ the save call enters I.e. when the object is updated, not when it is created.

**Comment by markuswinkler** [comment]
Thank you for the clarification.
