### ISSUE TITLE
beforeSave questions

### ISSUE THREAD

**Issue by stevestencil** [parse-community/parse-server#5171]
I have a couple of questions on the beforeSave hook.

1) Is there a way to hook a beforeSave on a Parse.Object.saveAll()? Something like a 'beforeSaveAll'. This would allow the ability to loop through all objects and perform actions (like removing some from the array) before saving them.

2) Does parse-server support adding more than one beforeSave hook to a class? For example: can I use Parse.Cloud.beforeSave(Parse.User, () => {}) to do a specific action and then later on add another Parse.Cloud.beforeSave(Parse.User, () => {}) to do a different action in a different part of my project? will both beforeSave hooks get called?

3) Is there any way to add a beforeSave hook to every class? Let's say I want every all of my classes to have an "edits" column that keeps track of the last person who edited each object. With a beforeSave that works with all classes I could add this logic in 1 place instead of declaring a beforeSave for every class.

Thanks for your help!

**Comment by flovilmart** [comment]
1. No
2. No
3. No

Hope this helps
