### ISSUE TITLE
Switching from parse-server-fs-adapter to GridStoreAdapter

### ISSUE THREAD

**Issue by andresteves** [parse-community/parse-server#5172]
### Issue Description

Sorry for dropping this here but I tried elsewhere without any response.
I have an instance of Parse Server running with parse-server-fs-adapter as the file adapter and unfortunately I cannot stream videos to iOS because of that.

I would like to know how and if changing from parse-server-fs-adapter to GridStoreAdapter will continue to serve my files as https://server.com/parse/files/whateverfile.mp4 and if it will delete existing files?

#### Expected Results

That the files continue to be served like before and no deletion happens

#### Actual Outcome

Unsure due to possible deletion of existing files

### Environment Setup

- **Server**
  - parse-server version  : 3.1.1
  - Operating System:     Ubuntu 16.04
  - Localhost or remote server?  Dedicated server

- **Database**
  - MongoDB version: 3.4
  - Storage engine:  RocksDB
  - Localhost or remote server? Dedicated server

**Comment by flovilmart** [comment]
You need to move the files from one storage to the other which is not supported and likely won’t be. 

You will need to find a way to list all the files from the fs adapter, and the save it into the grid store one. Fortunately, those adapters provide read and write capabilities
