### ISSUE TITLE
Bug for parse-server while use PostgreSQL

### ISSUE THREAD

**Issue by dovewi** [parse-community/parse-server#5174]
ParseServer 3.0+ version

PostgreSQL 10

When I created a new configuration item today, the old one configuration item was deleted.

like this:

before create new one config item:
![before_add_secend_config](https://user-images.githubusercontent.com/5876087/48532860-11de5500-e8dd-11e8-83bb-f7b2836f7041.png)

then i create new one:
![add_new_config](https://user-images.githubusercontent.com/5876087/48532869-1dca1700-e8dd-11e8-8f2a-27654e38c2c0.png)

after that:
![after_add_new_config_but_not_refresh](https://user-images.githubusercontent.com/5876087/48532877-26bae880-e8dd-11e8-9a60-c746868b21a0.png)

then refresh,the old one configuration item was deleted:
![after_refresh](https://user-images.githubusercontent.com/5876087/48532915-4e11b580-e8dd-11e8-8546-f5f2ec9748b7.png)

I checked the database record.Found that objectId is integer 1.
![db_record](https://user-images.githubusercontent.com/5876087/48532940-6c77b100-e8dd-11e8-9071-8b66464c2e1a.png)

How to fix this problem?

**Comment by flovilmart** [comment]
Please reopen the issue filling completely the template, including the logs when running with the VERBOSE environment variable.
