### ISSUE TITLE
User Login Error (3.1.1)

### ISSUE THREAD

**Issue by mat2cc** [parse-community/parse-server#5175]
### Issue Description

Login functions are causing breaking failure on server. Any attempted login cause an ELIFECYCLE error. This was tried both using cloud code and the Parse.Unity API and the problem persists on both. This was working fine in Parse 3.0.0, this issue exists now after the update to 3.1.1 (We updated directly to 3.1.1 from 3.0.0).

### Steps to reproduce

Unity: ParseUser.LogInAsync()
Cloud Code: Parse.User.logIn()

#### Expected Results

User to be logged in. 

#### Actual Outcome

Server Error:
npm ERR! code ELIFECYCLE
npm ERR! errno 3228369023
npm ERR! parse-server-example@1.4.0 start: `node index.js`
npm ERR! Exit status 3228369023
npm ERR!
npm ERR! Failed at the parse-server-example@1.4.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2018-11-15T07_32_49_357Z-debug.log

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 3.1.1
  - Operating System: Windows Server 2012
  - Hardware: Intel(R) Xeon(R CPU E5-2673 v4 @ 2.30 GHz  2.29GHz, 64 bit
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Virtual Machine on Azure

- **Database**
  - MongoDB version: 3.6
  - Storage engine:  mmapv1
  - Hardware:        Intel(R) Xeon(R CPU E5-2673 v4 @ 2.30 GHz  2.29GHz, 64 bit
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): Virtual Machine on Azure

### Logs/Trace

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@6.4.1
3 info using node@v8.9.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle parse-server-example@1.4.0~prestart: parse-server-example@1.4.0
6 info lifecycle parse-server-example@1.4.0~start: parse-server-example@1.4.0
7 verbose lifecycle parse-server-example@1.4.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle parse-server-example@1.4.0~start: PATH: C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\Administrator\Documents\Parse\parse-server\node_modules\.bin;C:\Oracle11G\product\11.2.0\dbhome_1\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\OBI11\Oracle_BI1\bin;C:\OBI11\Oracle_BI1\opmn\bin;C:\OBI11\Oracle_BI1\opmn\lib;C:\OBI11\Oracle_BI1\perl\bin;C:\Program Files\nodejs\;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\Git\cmd;C:\Users\Administrator\AppData\Roaming\npm
9 verbose lifecycle parse-server-example@1.4.0~start: CWD: C:\Users\Administrator\Documents\Parse\parse-server
10 silly lifecycle parse-server-example@1.4.0~start: Args: [ '/d /s /c', 'node index.js' ]
11 silly lifecycle parse-server-example@1.4.0~start: Returned: code: 3228369023  signal: null
12 info lifecycle parse-server-example@1.4.0~start: Failed to exec start script
13 verbose stack Error: parse-server-example@1.4.0 start: `node index.js`
13 verbose stack Exit status 3228369023
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid parse-server-example@1.4.0
15 verbose cwd C:\Users\Administrator\Documents\Parse\parse-server
16 verbose Windows_NT 6.2.9200
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v8.9.3
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 3228369023
22 error parse-server-example@1.4.0 start: `node index.js`
22 error Exit status 3228369023
23 error Failed at the parse-server-example@1.4.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 3228369023, true ]

**Comment by flovilmart** [comment]
Thanks for teleporting the issue, can you provide the logs when running with tje VERBOSE=1 environment variable set?

**Comment by mat2cc** [comment]
<pre>
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start',
1 verbose cli   'VERBOSE=\'1\'',
1 verbose cli   'parse-server',
1 verbose cli   '--appId',
1 verbose cli   '**',
1 verbose cli   '--masterKey',
1 verbose cli   '**' ]
2 info using npm@6.4.1
3 info using node@v8.9.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle parse-server-example@1.4.0~prestart: parse-server-example@1.4.0
6 info lifecycle parse-server-example@1.4.0~start: parse-server-example@1.4.0
7 verbose lifecycle parse-server-example@1.4.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle parse-server-example@1.4.0~start: PATH: C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\Administrator\Documents\Parse\parse-server\node_modules\.bin;C:\Oracle11G\product\11.2.0\dbhome_1\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\OBI11\Oracle_BI1\bin;C:\OBI11\Oracle_BI1\opmn\bin;C:\OBI11\Oracle_BI1\opmn\lib;C:\OBI11\Oracle_BI1\perl\bin;C:\Program Files\nodejs\;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\Git\cmd;C:\Users\Administrator\AppData\Roaming\npm
9 verbose lifecycle parse-server-example@1.4.0~start: CWD: C:\Users\Administrator\Documents\Parse\parse-server
10 silly lifecycle parse-server-example@1.4.0~start: Args: [ '/d /s /c',
10 silly lifecycle   'node index.js "VERBOSE=\'1\'" "parse-server" "**" "**"' ]
11 silly lifecycle parse-server-example@1.4.0~start: Returned: code: 3228369023  signal: null
12 info lifecycle parse-server-example@1.4.0~start: Failed to exec start script
13 verbose stack Error: parse-server-example@1.4.0 start: `node index.js "VERBOSE='1'" "parse-server" "**" "**"`
13 verbose stack Exit status 3228369023
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid parse-server-example@1.4.0
15 verbose cwd C:\Users\Administrator\Documents\Parse\parse-server
16 verbose Windows_NT 6.2.9200
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start" "VERBOSE='1'" "parse-server" "--appId" "**" "--masterKey" "**"
18 verbose node v8.9.3
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 3228369023
22 error parse-server-example@1.4.0 start: `node index.js "VERBOSE='1'" "parse-server" "**" "**"`
22 error Exit status 3228369023
23 error Failed at the parse-server-example@1.4.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 3228369023, true ]
</pre>

**Comment by flovilmart** [comment]
It says ‘Failed to exec start script’ so actually the server didn’t start at all.

Also, this is not how you set environment variables on Windows.

You can also set `verbose: true` part of the ParseServer constructor options, alongside the appId and masterKey

**Comment by mat2cc** [comment]
The server is starting because I can log in with Google and Facebook. Also other parse calls are working fine, once logged in via Facebook/Google So the issue is not to do with that. I'm not sure why it says ‘Failed to exec start script’.

**Comment by flovilmart** [comment]
According to the logs you sent:

1. Verbose is not set correctly
2. No trace of logging in is shown

So please provide those logs

**Comment by mat2cc** [comment]
Log In with Username and Password:
<pre>
verbose: REQUEST for [POST] /parse/functions/LogInASP: {
  "p_Username": "**",
  "p_Password": "**"
} method=POST, url=/parse/functions/LogInASP, x-parse-application-id=**, x-parse-client-version=net-netfx1.7.0.0, x-parse-installation-id=**, x-parse-os-version=Microsoft Windows NT 10.0.17134.0, x-parse-windows-key=, content-type=application/json, cache-control=no-cache, host=**:1337, x-ms-request-root-id=RESK6EMF5JY=, x-ms-request-id=|RESK6EMF5JY=.23bcb389_3., requestid=|RESK6EMF5JY=.23bcb389_3., content-length=43, expect=100-continue, p_Username=**, p_Password=**

verbose: REQUEST for [GET] /parse/login: {
  "username": "**",
  "password": "********"
} method=GET, url=/parse/login, user-agent=node-XMLHttpRequest, Parse/js2.1.0 (NodeJS 8.9.3), accept=*/*, content-type=text/plain, host=**:1337, content-length=206, connection=close, username=**, password=********
npm ERR! code ELIFECYCLE
npm ERR! errno 3228369023
npm ERR! parse-server-example@1.4.0 start: `node index.js`
npm ERR! Exit status 3228369023
npm ERR!
npm ERR! Failed at the parse-server-example@1.4.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2018-11-15T1
3_37_26_882Z-debug.log
</pre>
the log referenced (C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2018-11-15T1
3_37_26_882Z-debug.log )at the bottom is the one mentioned above in my previous post.

Login with google:
<pre>
verbose: RESPONSE from [POST] /parse/users: {
  "response": {
    "objectId": "UEpydsRSfy",
    "username": "MattGoogle",
    "authData": {
      "google": {
        "id": "**",
        "id_token": "**",
        "access_token": "**"
      }
    },
    "createdAt": "2018-06-27T11:17:23.428Z",
    "updatedAt": "2018-11-13T00:55:18.291Z",
    "email": "**@gmail.com",
    "displayPicture": {
      "__type": "File",
      "name": "e9ff05ad63fdaf127341be9ba91b82b8_koi.jpg",
      "url": "**"
    },
    "ACL": {
      "*": {
        "read": true
      },
      "UEpydsRSfy": {
        "read": true,
        "write": true
      }
    },
    "sessionToken": "r:7acdb872e1cc79c48a12198f6924b1da"
  },
  "location": "http://**:1337/parse/users/UEpydsRSfy"
} objectId=UEpydsRSfy, username=MattGoogle, id=**, id_token=, access_token=, createdAt=2018-06-27T11:17:23.428Z, updatedAt=2018-11-13T00:55:18.291Z, email=**@gmail.com, __type=File, name=e9ff05ad63fdaf127341be9ba91b82b8_koi.jpg, url=**, read=true, read=true, write=true, sessionToken=r:7acdb872e1cc79c48a12198f6924b1da, location=**:1337/parse/users/UEpydsRSfy
</pre>

**Comment by flovilmart** [comment]
Are you putting a body in your GET query for login?

**Comment by mat2cc** [comment]
I'm just calling this from cloud code. The same occurs when logging in on Unity through `ParseUser.LogInAsync()`
<pre>

Parse.Cloud.define('LogInASP', async (request) => {
	const {
		p_Username, p_Password
	} = request.params;

	try
	{
		const user = await Parse.User.logIn(p_Username, p_Password);
		return user.getSessionToken();
	}
	catch(e)
	{
		throw 'Cloud Code Error. Error logging in with username: ' + p_Username + '\n' + e;
	}


});
</pre>

Have in mind these both work perfectly fine in version 3.0.0, I downgraded again just to make sure.  It is only happening in this version.

**Comment by flovilmart** [comment]
Can you attempt to create a test that reproduces the issue on this codebase?

**Comment by mat2cc** [comment]
To eliminate any issues that may be caused by data or any cloud code, I created a fresh instance of parse server on a brand new database. I cannot even create a user using the parse-dashboard or any other means. I tried this with version 3.1.0 and the same issues occurred as on 3.1.1.

I have also done a fresh installation with version 3.0.0 and it is working fine.

The environment setup is the same as described above in the original post. There seems to be an issue affecting the Windows. The steps followed to reproduce are:

1. cloned the parse-server-example repository into a new directory
2. npm install in that new directory.
3. Created new mongo database.
4. Setup server in index.js to point to clean instance of database
5. Go to dashboard url
6. Create User
7. Error described above appears

Am I doing something incorrectly? Have in mind I followed the same steps for older versions of parse and it worked perfectly.
Please let me know if there is anymore information I can provide to further assist in any troubleshooting

**Comment by mman** [comment]
I think the key to decipher this crash is to understand ``error errno 3228369023``. Converting this into hex  shows ``0xC06D007F``.

Anybody understands what ``node`` puts into ``errno``?

This looks like a custom error code.

**Comment by flovilmart** [comment]
It looks like it's related to your windows machine: https://github.com/Automattic/node-canvas/issues/1285#issuecomment-431897492

The error code (0xC06D007F) that you see is matching what is described above.
