### ISSUE TITLE
Using PostgreSQL10 to install Parse Server, add configuration items, there is an error.

### ISSUE THREAD

**Issue by dovewi** [parse-community/parse-server#5176]
### Issue Description

When installing Parse Server with PostgreSQL 10, adding Config entries to ParseDashboard will result in deletion of the old Config entries, i.e. Config can only put one entry. After checking the database, it is found that each new Config entry objectId is 1.

### Steps to reproduce

Before adding new entries:
![before_add_secend_config](https://user-images.githubusercontent.com/5876087/48597516-2e3fc780-e999-11e8-998c-13c8e7ed7beb.png)

then add new one:
![add_new_config](https://user-images.githubusercontent.com/5876087/48597528-3ac42000-e999-11e8-988e-db4ece1a97d1.png)

add success and refresh page:
![after_refresh](https://user-images.githubusercontent.com/5876087/48597540-47487880-e999-11e8-86f6-9c9c9c6e3aee.png)

the db record:
![db_record](https://user-images.githubusercontent.com/5876087/48597549-50394a00-e999-11e8-81f9-0dc0a1ea85df.png)
 
### Expected Results

There was originally a configuration item,after adding an entry, there should be two configuration items.

### Actual Outcome

In fact, only new configuration items are added after the old ones are replaced.

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 3.0.0
  - Operating System:     unknown , like heroku PaaS platform,sina cloud SAE service
  - Hardware:             unknown
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): remote, sina SAE

- **Database**
  - PostgreSQL version: 10.0
  - Storage engine:  S3
  - Hardware:       unknown
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc):remote ,Aliyun RDS

**Comment by dplewis** [comment]
Do you want to try a pull request to address this?

I should have free time this weekend. I’m still using PG 9.5.

It might be an issue with how JSON objects are handled in 10

**Comment by dovewi** [comment]
> Do you want to try a pull request to address this?
> 
> I should have free time this weekend. I’m still using PG 9.5.
> 
> It might be an issue with how JSON objects are handled in 10

All right, I'll try it then.

**Comment by dplewis** [comment]
@dovewi I tried this on both PG 9.6 and PG 10. This is an issue.

This test fails

```
fit('can add new config to existing config', async () => {
    await request({
      method: 'PUT',
      url: 'http://localhost:8378/1/config',
      json: true,
      body: {
        params: { SWIPER: [{ __type: 'File', name: 'name', url: 'http://url' }] },
      },
      headers,
    });

    await request({
      method: 'PUT',
      url: 'http://localhost:8378/1/config',
      json: true,
      body: {
        params: { newConfig: 'good' },
      },
      headers,
    });

    const result = await Parse.Config.get();
    console.log(result.get('file')); // returns undefined should be [{ __type: "File" ...}]
    console.log(result.get('newConfig')); // returns 'good'
  });
```

```
 "params": {
        "newConfig": "good",
        "file": [
            {
                "__type": "File"
            }
        ]
    }
```

PG isn't setup to update an object but rather replaces it. I have limited time to work on it right now.

This is similar to the feature request https://github.com/parse-community/Parse-SDK-JS/issues/680 see discussion.
