### ISSUE TITLE
parse_image 0.2.0 is still using Parse.promise.as() and Parse.promise() which results in an exception

### ISSUE THREAD

**Issue by gorillatapstudio** [parse-community/parse-server#5190]
# Before opening the issue please ensure that you have:

- [ ] [Read the migration guide](https://github.com/parse-community/parse-server/blob/master/3.0.0.md) to parse-server 3.0.0
- [ ] [Read the migration guide](https://github.com/parse-community/Parse-SDK-JS/blob/master/2.0.0.md) to Parse SDK JS 2.0.0

### Issue Description

parse_image 0.2.0 is still using Parse.promise.as() and Parse.promise() which results in an exception
### Steps to reproduce

return Parse.Cloud.httpRequest({ url: url }).then(function(response) {
		var image = new Image();
	  	return image.setData(response.buffer);
 
### Expected Results

promise resolved

### Actual Outcome

exception: Parse.promise is the wrong type 

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 3.1.1beta
  - Operating System:     [FILL THIS OUT]
  - Hardware:             [FILL THIS OUT]
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): back4app.com

- **Database**
  - MongoDB version: [FILL THIS OUT]
  - Storage engine:  [FILL THIS OUT]
  - Hardware:        [FILL THIS OUT]
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): [FILL THIS OUT]

**Comment by flovilmart** [comment]
Unrelated to this project. Please open the issue on the appropriate repositoryz
