### ISSUE TITLE
Parse-Server shuts down once a User signup request is received

### ISSUE THREAD

**Issue by tobunka-git** [parse-community/parse-server#5192]
### Issue Description

I was trying to sign up a user to the parse server, and the server shuts down, claiming JSON syntax error. I remove the parse-server@3.1.1 and install an earlier version, 3.0.0. Then used the same piece of data for user creation. You know what, the signup succeeds.

### Steps to reproduce

After installing parse-server@3.1.1/3.1.0, and fire a curl command from the rest api doc. The parse server always shuts down.

After installing parse-server@3.0.0, and fire the same command, the parse server accepts the user creation request like always.
 
### Expected Results

User signup succeeds when using 3.1.0 and above versions

### Actual Outcome

User signup succeeds when 3.0.0 is in use, but fails 3.1.0 and above versions are in use.

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 3.0.0/3.1.0/3.1.1
  - Operating System:     Windows 7 64bit
  - Hardware:             4 Core/8 GB
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): localhost

- **Database**
  - MongoDB version: 4.0
  - Storage engine:  wildtiger
  - Hardware:        Same machine as the server
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): localhost

### Logs/Trace

"ParseError: 100 XMLHttpRequest failed: \"SyntaxError: Unexpected end of JSON input\""

**Comment by flovilmart** [comment]
Can you provide the server logs when running with VERBOSE=1 set?

**Comment by tobunka-git** [comment]
nothing output, just shutdown

**Comment by flovilmart** [comment]
Are your running with the verbose logs? What is your configuration?

**Comment by tobunka-git** [comment]
`[13728] parse-server running on http://localhost:1337/parse
verbose: REQUEST for [POST] /parse/users: {
  "username": "cooldude6",
  "password": "********",
  "phone": "415-392-0202"
} method=POST, url=/parse/users, host=localhost:1337, connection=keep-alive, con
tent-length=69, origin=chrome-extension://aejoelaoggembcahagimdiliamlcdmfm, x-pa
rse-application-id=7da3ed62-4ec3-4444-a112-e9cea813f910, x-parse-master-key=tlRz
TlrTwhEzMeGRCYuVdrsJc25WX1cS, content-type=application/json, user-agent=Mozilla/
5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/7
0.0.3538.102 Safari/537.36, x-parse-revocable-session=1, accept=*/*, accept-enco
ding=gzip, deflate, br, accept-language=zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7, use
rname=cooldude6, password=********, phone=415-392-0202

E:\Projects\devdocBack>`

**Comment by tobunka-git** [comment]
in verbose mode, just output the request with data and headers, and then the server quits

**Comment by flovilmart** [comment]
What is the exit code of the process? What version of node are you running?

**Comment by tobunka-git** [comment]
I just installed the parse-server@3.1.1 using npm instead of yarn. It succeeds with user creation.

**Comment by flovilmart** [comment]
this should make no difference, unless you had different versions of node.

**Comment by tobunka-git** [comment]
i don't know why. Since parse-server required node-gyp to compile, and i think there might be differences between npm and yarn in the way they do the compilation.

**Comment by flovilmart** [comment]
We do not test with yarn nor support it actively.
