### ISSUE TITLE
Why not use object to store schema type

### ISSUE THREAD

**Issue by xVanTuring** [parse-community/parse-server#5195]
**Describe the solution you'd like**
Currently parse server uses a string to set the schema type in mongo _SCHEMA, making it difficult to make additional settings such as required
If we use an Object, it will be easy to add an `isRequired` option.
And I tried this and modified a few functions, the parse server can create objects, and schema,The rest is still unclear.

Bottom it's the schema of the GameObject
![tim 20181127143526](https://user-images.githubusercontent.com/11146248/49063238-b5baef80-f251-11e8-94ef-15b18ea3ad72.png)

### Function I edited
``` js
// MongoSchemaCollection.js
function mongoFieldToParseSchemaField(type) {
   return type;
}
function parseFieldTypeToMongoFieldType(fieldType) {
 return fieldType;
}
```
``` js
// MongoStorageAdapter.js
const mongoSchemaFromFieldsAndClassNameAndCLP=(/**/)=>{
  const mongoObject = {
    _id: className,
    objectId: {type:'String'}, //objectId: 'string',
    updatedAt: {type:'String'},
    createdAt: {type:'String'},
    _metadata: undefined,
  };
}
```
Hope this is useful

**Comment by xVanTuring** [comment]
Well,that will definitely work, I just think parse server complicates some issues.

**Comment by flovilmart** [comment]
This is exactly the point of the beforeSave function, to let your define validation and custom logic. If this make is too complicated, you can always fork the project, and submit a PR when you have your feature ready!
