### ISSUE TITLE
aggregate query with 2 lookups not working

### ISSUE THREAD

**Issue by ranhsd** [parse-community/parse-server#5201]
Hi, 
The following aggregation is not working: 

```
        let aggregation = [
            {
                match: {
                    lastSeenDate: { $lte: date }
                }
            },
            {
                lookup:{
                    from: "_User",
                    localField: "userId",
                    foreignField: "_id",
                    as: "user"
                }
            },
            {
                unwind: {
                    path: "$user"
                }
            },
            {
                lookup: {
                    from: "Closet",
                    localField: "ownerId",
                    foreignField: "user._id",
                    as: "closet"                    
                }
            },
            {
                unwind: {
                    path: "$closet"
                }
            },            
            {
                limit: 10
            }
        ];
```

If I remove one of the lookups from the aggregation it works as expected but it doesn't work if I add another lookup to the query. 

I tried to use the same aggregation in a MongoDB GUI client (3T Studio) and there it works well. 

I wanted to know if there is a limitation to one lookup only? 

Thanks!

**Comment by dplewis** [comment]
What version of parse server and JS SDK are you running?

**Comment by ranhsd** [comment]
Hi @dplewis I'm still on parse-server 2.8.4 which use JS SDK 1.11.1

I cannot upgrade now to Parse 3 because I have a lot of cloud code functions which needs to migrated.

**Comment by dplewis** [comment]
This has already been addressed https://github.com/parse-community/parse-server/pull/4835

Released on Parse 3
