### ISSUE TITLE
Schema error number; expected String but got Number

### ISSUE THREAD

**Issue by aBuder** [parse-community/parse-server#5219]
I got the following error 

`{"code":111,"error":"schema mismatch for Machine.number; expected String but got Number"}`

I created an class with an column `number` of type `String`. The column would be created, but if I type in some data I get these error.

![bildschirmfoto 2018-12-01 um 15 50 27](https://user-images.githubusercontent.com/1265139/49329549-e4520680-f580-11e8-9f56-ca69d367edc6.png)

### Environment Setup

- **Server**
  - parse-server version  3.0.0
  - Operating System:    Linux

**Comment by flovilmart** [comment]
As always, can you provide server logs?

**Comment by aBuder** [comment]
After Updating the server to parse version 3.1.2 everything works fine.
