### ISSUE TITLE
Getting started docs ocs recommend piping bootstrap script into sh instead of bash

### ISSUE THREAD

**Issue by monstrobishi** [parse-community/parse-server#5220]
### Issue Description

Getting started docs inlcude this line:
```
sh <(curl -fsSL https://raw.githubusercontent.com/parse-community/parse-server/master/bootstrap.sh)
```

However, the boostrap script is not compatible with a basic sh shell, and needs bash to function correctly. The recommended command should be altered to:

```
bash <(curl -fsSL https://raw.githubusercontent.com/parse-community/parse-server/master/bootstrap.sh)
```

More specifically, sh doesn't support the `[[ ]]` syntax used in the script, so many of the commands in the script error out (For example, generating default values).

### Steps to reproduce

Read getting started docs, follow commands to get started
 
### Expected Results

Default config values are generated.

### Actual Outcome

Default config values are not generated, amongst other issues.

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : Bootstrap script as of 3/12/2018
  - Operating System:     Ubuntu 18.04
  - Hardware:             Aws
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Aws

### Logs/Trace

```
             `.-://////:-..`
         `:/oooooooooooooooo+:.`
      `:+oooooooooooooooooooooo+/`
     :+ooooooooooooooooooooooooooo/.
   .+oooooooooooooo/:.....-:+ooooooo-
  .+ooooooooooooo/` .:///:-` -+oooooo:
 `+ooooooooooooo: `/ooooooo+- `ooooooo-
 :oooooooooooooo  :ooooooooo+` /oooooo+
 +ooooooooooooo/  +ooooooooo+  /ooooooo.
 oooooooooooooo+  ooooooooo`  .oooooooo.
 +ooooooooooo+/: `ooooooo`  .:ooooooooo.
 :ooooooo+.`````````````  /+oooooooooo+
 `+oooooo- `ooo+ /oooooooooooooooooooo-
  .+ooooo/  :/:` -ooooooooooooooooooo:
   .+ooooo+:-..-/ooooooooooooooooooo-
     :+ooooooooooooooooooooooooooo/.
      `:+oooooooooooooooooooooo+/`
         `:/oooooooooooooooo+:.`
             `.-://////:-..`

              parse-server


Enter an installation directory
(/home/ubuntu/temp): /home/ubuntu/parse

This will setup parse-server in /home/ubuntu/parse
Do you want to continue? (Y/n): Y
\xE2\x9C\x93 node: v8.10.0
\xE2\x9C\x93 npm: 3.5.2
Setting up parse-server in /home/ubuntu/parse
\xE2\x9C\x93 Created /home/ubuntu/parse
test: 124: test: [[: not found
```

**Comment by flovilmart** [comment]
Thanks for reporting the issue! Are you able to provide a Pr with a fix?

**Comment by monstrobishi** [comment]
I'm not sure if a PR can fix this as it's an issue with the website:

https://docs.parseplatform.org/parse-server/guide/

If the code for the website is hosted somewhere on github I can provide a PR.

**Comment by flovilmart** [comment]
It’s on the docs repository of this GitHub organisation
