### ISSUE TITLE
Docs on how to add adapter settings in environment variables

### ISSUE THREAD

**Issue by dave08** [parse-community/parse-server#5223]
I couldn't find any mention in the docs how to add options for file or mail adapters (like the s3adapter endpoint for digital ocean), or maybe this is not possible? If not, is there a file I could add for these kinds of options? Where do I put it? We're running on Kubernetes, so this has to work in a Docker image...

It would be nice if this aspect would have better docs, more and more companies are moving to orchestrators like k8s nowadays.

**Comment by flovilmart** [comment]
did you read the README? Did you see links? Did you click? Did you notice the S3 adapter is not hosted here? Did you try google ‘S3 adapter parse server’?

**Comment by dave08** [comment]
@flovilmart I saw the readme, went through the links, the s3 adapter is under parse-community github user. But all that is besides the point, you guys are doing a great job, I'm not complaining, just pointing out that for an end user, it's very hard to understand how to configure adapters in general when you're not tweaking the code.

In general, docker image best practices allow all main configs through emviroment vars to make it easy and clear to configure them in orchestrators without touching code.

In the end, after ploughing through code for days, I found that I could use a combination of env. vars. and a config file (if I understood correctly) and provide a docker CMD with the path to those configs. That way, I just need a k8s ConfigMap in Helm template to provide the configs, and use secrets as env. vars. to not include sensitive info in the values.yaml.

I'm just wondering now if there was an easier way?

**Comment by flovilmart** [comment]
Closing as completely off topic. All adapters can be configured through environment variables, in the form of a serialized JSON object. Not sure why you mention Digital ocean, as it’s properly documented in the S3 adapter repository. 

You don’t share any core, so I don’t know what to say. 

This is for reporting bugs, not general questions, as stated in the issue templates.

**Comment by dave08** [comment]
I'm really sorry for the trouble, I mean it's documented using code examples. I don't see any example of using a serialized JSON object in an environment variable (I've been looking for a few days...). I'm not a js programmer, so it's a bit hard to figure this out. If you would just give me an example of how to pass such a serialized JSON object to the environment variables, I could possibly offer a PR to the README if you want...

**Comment by flovilmart** [comment]
> I'm not a js programmer, so it's a bit hard to figure this out. 

This has nothing to do with JS. 

The documentation website is quite clear I am gonna paste the link because I assume you didn't get that far looking for a few days: https://docs.parseplatform.org/parse-server/guide/#configuration-options

I will also assume you didn't reach that page either: https://github.com/parse-community/parse-server-s3-adapter#usage-with-digital-ocean-spaces because it doesn't look like you did.

> I don't see any example of using a serialized JSON object in an environment variable

because it should not be necessary!

- Using as an express mounted app: https://docs.parseplatform.org/parse-server/guide/#usage
- Using as a CLI https://github.com/parse-community/parse-server#configuration where is it written:

```
Parse Server can be configured using the following options. You may pass these as parameters when running a standalone parse-server, or by loading a configuration file in JSON format using parse-server path/to/configuration.json. If you're using Parse Server on Express, you may also pass these to the ParseServer object as options.
```

> I couldn't find any mention in the docs how to add options for file or mail adapters 
> If not, is there a file I could add for these kinds of options?

Did you read them?

**Comment by dave08** [comment]
I saw all that. All those configs are using JS code, not uniquely environment variables. So to make a Docker image, I'd have to include a JS file declaring all that, build the image every time one of those settings change. This means adding one more unecessary CI/CD pipeline to Jenkins, an extra git repo, all just for a few settings.

Thank you for taking time to answer this issue, I wouldn't bother anyone if I didn't think that others could benefit from this. I don't expect everyone to be using Kubernetes and Docker, so it might be unclear to you what the issue is in the first place.

If I specify `PARSE_SERVER_FILES_ADAPTER="./Files/S3Adapter.js"`, How will I configure the digital ocean endpoint? Where do I pass the S3Adapter's options uniquely through environment vars?

Maybe `PARSE_SERVER_FILES_ADAPTER="{"module":"@parse/fs-files-adapter", "options":{...}}"`? That isn't stated in any document...

**Comment by flovilmart** [comment]
To conclude this, passing the environment variable with the (`PARSE_SERVER_FILES_ADAPTER="{"module":"@parse/fs-files-adapter", "options":{...}}"? `) is definitely a bad idea.

If your goal is to work with docker and kuberenetes, you should leverage volumes and arguments:

- use a volume to mount your configuration file, `.js`configuration.
- use arguments: https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/ in your container

This way, you do not have to rebuild your docker image which only contains the server, and you can update your config on the fly.

The `.js`/`.json` configuration is passed to the parse server constructor + let you start live query server

**Comment by dave08** [comment]
@flovilmart 
Merci pour votre patience :smile:! Hopefully this is the last question, if you don't mind:

I have this in my config map:
```javascript
        var express = require('express');
        var ParseServer = require('parse-server').ParseServer;
        var app = express();

        var S3Adapter = require("@parse/s3-files-adapter");
        var AWS = require("aws-sdk");

        //Configure Digital Ocean Spaces EndPoint
        const spacesEndpoint = new AWS.Endpoint(process.env.S3_ENDPOINT);
        var s3Options = {
            bucket: process.env.S3_BUCKET,
            directAccess: {{ .Values.api.s3.direct }},
            bucketPrefix: process.env.S3_BUCKET,
            s3overrides: {
                accessKeyId: process.env.S3_ACCESS_KEY,
                secretAccessKey: process.env.S3_SECRET_KEY,
                endpoint: spacesEndpoint
            }
        };

        var s3Adapter = new S3Adapter(s3Options);

        var api = new ParseServer({
            databaseURI: process.env.DATABASE_URI, // Connection string for your MongoDB database
            appId: process.env.APP_ID,
            appName: process.env.APP_NAME,
            masterKey: process.env.MASTER_KEY,
            fileKey: process.env.FILE_KEY,
            serverURL: process.env.SERVER_URL,
            emailAdapter: {
                module: '@parse/simple-mailgun-adapter',
                options: {
                             // The address that your emails come from
                    fromAddress: process.env.EMAIL_FROM,
                             // Your domain from mailgun.com
                    domain: process.env.EMAIL_DOMAIN,
                             // Your API key from mailgun.com
                    apiKey: process.env.EMAIL_API_KEY
                }
            }
        });

        // Serve the Parse API on the /parse URL prefix
        app.use('/parse', api);

        app.listen(process.env.PORT, function() {
            console.log('parse-server-example running on port ' + process.env.PORT + '.');
        });
```
I mount it to `/parse-server/index.js` in the docker image and use `node index.js` in the `command`, but I'm getting this in the Pod logs: 
```
module.js:550
    throw err;
    ^

Error: Cannot find module 'parse-server'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/parse-server/index.js:2:19)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
```

**Comment by flovilmart** [comment]
What does your docker image look like? Is it the one in this repo? Odd thing is that express is found. That makes me wonder if the parse-server dependency is set in your package.json. If you are using the docker image from this project, then you should require parse-server differently (lib/index) I believe or something similar

**Comment by flovilmart** [comment]
Well, you should try it out. Perhaps starting with checking what’s in the docker image the files etc...
