### ISSUE TITLE
My Parse cloud code is returning 400 errors

### ISSUE THREAD

**Issue by trappat** [parse-community/parse-server#5224]
I had a foreign developer write my app but he didnt write the cloud code correctly, now my servers CPU is overloading and I am getting so many slow requests. Can someone look in my cloud code to see what needs to be refactored?

I have back4app as a host but they are no help and I am running Parse 2.8.4

Slow request screenshot 
https://www.dropbox.com/s/gt253n71hwdzgym/Screen%20Shot%202018-12-05%20at%2011.52.14%20AM.png?dl=0

Cloud code
https://www.dropbox.com/s/l57tl91yef6pvs4/cloud.zip?dl=0

Errors from server
- - - [27/Nov/2018:01:17:57 +0000] "POST /functions/getActivitiesForPhoto HTTP/1.1" 400 82 "-" "Blitter/1 CFNetwork/975.0.3 Darwin/18.2.0" appID:g7m0b6pKUILW5uZnCCdTs0u14QlflZQcSrLU50Xx RT:8.118 URT:8.118 .
- - - [27/Nov/2018:01:17:57 +0000] "POST /functions/getActivitiesForPhoto HTTP/1.1" 400 33 "-" "Blitter/1 CFNetwork/975.0.3 Darwin/18.2.0" appID:g7m0b6pKUILW5uZnCCdTs0u14QlflZQcSrLU50Xx RT:1.221 URT:1.221 .
- - - [27/Nov/2018:01:17:58 +0000] "POST /functions/getActivitiesForPhoto HTTP/1.1" 400 33 "-" "Blitter/1 CFNetwork/975.0.3 Darwin/18.2.0" appID:g7m0b6pKUILW5uZnCCdTs0u14QlflZQcSrLU50Xx RT:0.514 URT:0.514 .
69.40.104.144, 216.137.42.75, 10.0.3.250 - - [27/Nov/2018:01:18:00 +0000] "POST /functions/getActivitiesForPhoto HTTP/1.1" 400 33 "-" "Blitter/1 CFNetwork/975.0.3 Darwin/18.2.0" appID:g7m0b6pKUILW5uZnCCdTs0u14QlflZQcSrLU50Xx RT:8.869 URT:8.848 .
- - - [27/Nov/2018:01:18:01 +0000] "POST /functions/getActivitiesForPhoto HTTP/1.1" 400 33 "-" "Blitter/1 CFNetwork/974.2.1 Darwin/18.0.0" appID:g7m0b6pKUILW5uZnCCdTs0u14QlflZQcSrLU50Xx RT:9.485 URT:9.485 .
- - - [27/Nov/2018:01:18:02 +0000] "POST /functions/getActivitiesForPhoto HTTP/1.1" 400 33 "-" "Blitter/1 CFNetwork/975.0.3 Darwin/18.2.0" appID:g7m0b6pKUILW5uZnCCdTs0u14QlflZQcSrLU50Xx RT:6.223 URT:6.223 .
69.40.104.144, 216.137.42.5, 10.0.3.163 - - [27/Nov/2018:01:18:02 +0000] "POST /functions/getActivitiesForPhoto HTTP/1.1" 400 33 "-" "Blitter/1 CFNetwork/975.0.3 Darwin/18.2.0" appID:g7m0b6pKUILW5uZnCCdTs0u14QlflZQcSrLU50Xx RT:7.161 URT:7.102 .
- - - [27/Nov/2018:01:18:03 +0000] "POST /functions/getActivitiesForPhoto HTTP/1.1" 400 33 "-" "Blitter/1 CFNetwork/975.0.3 Darwin/18.2.0" appID:g7m0b6pKUILW5uZnCCdTs0u14QlflZQcSrLU50Xx RT:2.707 URT:2.707 .
- - - [27/Nov/2018:01:18:04 +0000] "POST /functions/getActivitiesForPhoto HTTP/1.1" 400 33 "-" "Blitter/1 CFNetwork/975.0.3 Darwin/18.2.0" appID:g7m0b6pKUILW5uZnCCdTs0u14QlflZQcSrLU50Xx RT:8.293 URT:8.292 .
- - - [27/Nov/2018:01:18:06 +0000] "POST /functions/getActivitiesForPhoto HTTP/1.1" 400 33 "-" "Blitter/1 CFNetwork/976 Darwin/18.2.0" appID:g7m0b6pKUILW5uZnCCdTs0u14QlflZQcSrLU50Xx RT:5.769 URT:5.769 .
- - - [27/Nov/2018:01:18:06 +0000] "POST /functions/getActivitiesForPhoto HTTP/1.1" 400 33 "-" "Blitter/1 CFNetwork/975.0.3 Darwin/18.2.0" appID:g7m0b6pKUILW5uZnCCdTs0u14QlflZQcSrLU50Xx RT:1.061 URT:1.061 .
- - - [27/Nov/2018:01:18:07 +0000] "POST /functions/getActivitiesForPhoto HTTP/1.1" 400 33 "-" "Blitter/1 CFNetwork/974.2.1 Darwin/18.0.0" appID:g7m0b6pKUILW5uZnCCdTs0u14QlflZQcSrLU50Xx RT:5.606 URT:5.606 .
69.40.104.144, 216.137.42.5, 10.0.3.163 - - [27/Nov/2018:01:18:07 +0000] "POST /functions/getActivitiesForPhoto HTTP/1.1" 400 33 "-" "Blitter/1 CFNetwork/975.0.3 Darwin/18.2.0" appID:g7m0b6pKUILW5uZnCCdTs0u14QlflZQcSrLU50Xx RT:1.073 URT:1.055 .
- - - [27/Nov/2018:01:18:08 +0000] "POST /functions/getCommentsForBleet HTTP/1.1" 400 33 "-" "Blitter/1 CFNetwork/975.0.3 Darwin/18.2.0" appID:g7m0b6pKUILW5uZnCCdTs0u14QlflZQcSrLU50Xx RT:1.220 URT:1.220 .
- - - [27/Nov/2018:01:18:10 +0000] "POST /functions/getActivitiesForPhoto HTTP/1.1" 400 82 "-" "Blitter/1 CFNetwork/975.0.3 Darwin/18.2.0" appID:g7m0b6pKUILW5uZnCCdTs0u14QlflZQcSrLU50Xx RT:6.384 URT:6.384 .
69.40.104.144, 216.137.42.5, 10.0.3.163 - - [27/Nov/2018:01:18:10 +0000] "POST /functions/getActivitiesForPhoto HTTP/1.1" 400 33 "-" "Blitter/1 CFNetwork/975.0.3 Darwin/18.2.0" appID:g7m0b6pKUILW5uZnCCdTs0u14QlflZQcSrLU50Xx RT:5.184 URT:5.144 .
69.40.104.144, 216.137.42.75, 10.0.3.250 - - [27/Nov/2018:01:18:10 +0000] "POST /functions/getActivitiesForPhoto HTTP/1.1" 400 33 "-" "Blitter/1 CFNetwork/975.0.3 Darwin/18.2.0" appID:g7m0b6pKUILW5uZnCCdTs0u14QlflZQcSrLU50Xx RT:1.191 URT:1.190 .

**Comment by flovilmart** [comment]
This is not a bug with the server, reach out to your developer or back4app for help

**Comment by trappat** [comment]
> This is not a bug with the server, reach out to your developer or back4app for help

Back4app people dont know how to help and my developer doesnt either

**Comment by trappat** [comment]
> This is not a bug with the server, reach out to your developer or back4app for help

Could you help with this?

**Comment by addisonElliott** [comment]
Please post on StackOverflow with the appropriate tag or using the chatroom.

GitHub issues are **only** to be used for bugs related to the software.

If you're wanting to debug this yourself, the approach I use with cloud code is to comment things out until it gets better and then add console.log commands to gain further information.
