### ISSUE TITLE
_user object structure is different from pre-migration

### ISSUE THREAD

**Issue by digitalfractal** [parse-community/parse-server#5229]
### Issue Description

i notice when old user objects before migration happened, had different data structures than the new ones which is causing some issue on our end, why would this be so and how to fix ths? app is hosted on heruku

### Steps to reproduce

adding a _user record
 
### Expected Results

{
    "_id": "lxrTjox1D7",
    "username": "abc@gmail.com",
    "_hashed_password": "$2a$10$mG4q1RE5QT9b4cx.Acbwc.UB6Mv1GTMhT8PWR9JrqvV7a3/Tplh6C",
    "_perishable_token": "l0LvGETHgaaJhqZ5W2vT2cqR1",
    "name": "White Horse",
    "device_number": 0,
    "job_number": 0,
    "_session_token": "7LoG7P1D3LtU4ED4gdSnIYKCm",
    "_created_at": {
        "$date": "2018-12-04T22:02:38.857Z"
    },
    "email": null,
    "userType": "company",
    "projectId": "7015347",
    "_updated_at": {
        "$date": "2018-12-04T22:02:38.857Z"
    },
    "serialNumber": "lxrTjox1D7",
    "user_email": "abc@gmail.com"
}

### Actual Outcome

{
    "_id": "lxrTjox1D7",
    "username": "1543960958846",
    "user_email": "abc@gmail.com",
    "serialNumber": "lxrTjox1D7",
    "name": "White Horse",
    "projectId": "7015347",
    "userType": "company",
    "device_number": 0,
    "job_number": 0,
    "_hashed_password": "$2a$10$mG4q1RE5QT9b4cx.Acbwc.UB6Mv1GTMhT8PWR9JrqvV7a3/Tplh6C",
    "_wperm": [
        "lxrTjox1D7"
    ],
    "_rperm": [
        "*",
        "lxrTjox1D7"
    ],
    "_acl": {
        "lxrTjox1D7": {
            "w": true,
            "r": true
        },
        "*": {
            "r": true
        }
    },
    "_created_at": {
        "$date": "2018-12-04T22:02:38.857Z"
    },
    "_updated_at": {
        "$date": "2018-12-04T22:02:38.857Z"
    }
}

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : it was 2.2.2 but now it says * in setting
  - Operating System:     linux
  - Hardware:             free version of heruku
  - Localhost or remote server? Heruku
- Node: "node": ">=6.11.x"

- **Database**
  - MongoDB version: mlabs 
 mongod version: 3.6.6 (MMAPv1)
  - remote server? mLab

### Logs/Trace

none

**Comment by dplewis** [comment]
What issues where you having exactly? Can you post logs VERBOSE=1

Also you should update your node version > 8

You shouldn't use * pin your packages.

**Comment by digitalfractal** [comment]
@dplewis some of the fields that we normally add to user object and other records are happening on cloud code. apparently the cloud code doesnt function anymore and doesnt make updates, inserts etc. the error we are getting are things like Cannot read property 'error' of undefined (Code: 141, Version: 1.12.0)
 
what could be causing this do you think?

instead of * what should we set for the parse server ode?

**Comment by dplewis** [comment]
Set it to the latest version 3.1.2

You should make it a habit of keep track of releases for your dependencies.

Check out the [Migration to 3.0.0](https://github.com/parse-community/parse-server/blob/master/3.0.0.md) guide

Reopen if you are still having issues after migration

**Comment by digitalfractal** [comment]
@dplewis we are still getting the same issues. Any other ideas.

**Comment by dplewis** [comment]
Did you write all of your cloud code functions?

**Comment by dplewis** [comment]
Quick glance Parse.Cloud.useMasterKey() does nothing

response.success and response.error doesn’t exist please read the migration guide I posted

**Comment by digitalfractal** [comment]
Hi Diamond

Will you be able rewrite these cloud codes for a fee if we provided them to
you. there are a few more functions as well.

The person who developed this is no longer with us and its taking a while
to get our new developer get up to speed with parse?

tnx

Souhail Alavi | Business Development Director | Digital Fractal
Technologies Inc
Phone: (780) 669-0944 x23
Cell: (780)-886-7846
Fax: (780) 669-0944
Web: http://www.digitalfractal.com

**Comment by dplewis** [comment]
Sorry no can do. 

It’s an easy fix just replace

response.success(whatever) with `return whatever`

response.error(whatever) with `throw whatever`

**Comment by flovilmart** [comment]
@digitalfractal this is not a job board, and we already gave you all the pointers to solve your issue. If you are looking to hire a consultant, I would suggest you use a more appropriate channel.

**Comment by digitalfractal** [comment]
i do appreciate your help on this, thank you.

**Comment by dplewis** [comment]
No problem!
