### ISSUE TITLE
LiveQuery updates doesnt return the original object

### ISSUE THREAD

**Issue by smiziara** [parse-community/parse-server#5233]
To make a decision when receiving a LiveQuery update, we need to have the previous values (original values).

I can see that theres already a variable with the original object ready to be sent, but its not, only the current object is sent.

Would you please consider returning the original object as an extra parameter to the Update subscription?

**Comment by dplewis** [comment]
That’s a great idea. Do you want to do a PR?

**Comment by smiziara** [comment]
@dplewis Yes i can do it. But i believe it will be necessary to change the ParseServer and the JS SDK, right? Otherwise it may break the compatibility.

**Comment by dplewis** [comment]
Sounds about right
