### ISSUE TITLE
Migrating Cloud Code hangs on await query.find

### ISSUE THREAD

**Issue by haroot** [parse-community/parse-server#5238]
THe below code   hangs on the const user = await query1.get / find etc segment. if i put console.log after it won't log because the async function is not resolved... worked fine on parse 2.8.3

Parse.Cloud.define('exportData', async (req, res) => {
  console.log("req params:", req.params, req.params.parseUserId);
  if (!_.has(req.params, 'parseUserId')) {
    return;
  }
  try {
    console.log("At exportData");
    //Export data from User and JournalEntry Collection
    var id = req.params.parseUserId;
    var query1 = new Parse.Query(Parse.User);
    var query2 = new Parse.Query("JournalEntry");
    var query3 = new Parse.Query("Timeline");
    query2.equalTo("user", { "__type": "Pointer", "className": "_User", "objectId": id });
    query3.equalTo("user", { "__type": "Pointer", "className": "_User", "objectId": id });
          console.log("queries, ", query1, query2, query3, id, user); // does not work after consts
    const user = await query1.get(id, { useMasterKey: true });
    const journal = await query2.find({ useMasterKey: true });
    const timeline = await query3.find({ useMasterKey: true });
    console.log("Exporting user", id, user, journal, timeline);
    //res.success("Exported User Data Successfully for " +user.get('email'));
    console.log("Exporting PRO Status:", user.get("isPro"));
    if ( user.get("isPro") == true ) {
      await makeProPdf(user, journal, timeline);
    }
    else {
      await makeFreePdf(user, journal, timeline);
    }
  } catch (err) {
    //$res.error("Error:", err);
    return err;
  }
  //return user.get('email');
});

**Comment by flovilmart** [comment]
Please use stackoverflow for implementation related question, or open a PR with a failing test.

**Comment by haroot** [comment]
solution is:
const user = await query1.get(id, { useMasterKey: true });  =>
 const user = await query1.get(id);

**Comment by andreasanta** [comment]
This is happening to me as well. Do you have a Stackoverflow thread or a PR open for it? I have a query that never returns on "find" on Node.

It is a very simple code:

```
    const fastestUsersQuery = new Parse.Query('Answer');
    fastestUsersQuery.select('user', 'elapsedTime');
    let allTheFastestUsers = await fastestUsers.find({ useMasterKey: true });
```

Thanks!
