### ISSUE TITLE
Can't includeAll() include: '*' in REST API

### ISSUE THREAD

**Issue by zealmurapa** [parse-community/parse-server#5240]
Is it possible to run the query:

`query.include( '* '); or query.includeAll( );`

in REST API?

Maybe I am missing something, it `include: '*'` won't work

**Comment by flovilmart** [comment]
Can you provide the logs when running with verbose = 1 as well as the logs when doing the same from the JS SDK?

**Comment by zealmurapa** [comment]
includeAll: '*' worked
