### ISSUE TITLE
Invalid WebSocket frame: RSV2 and RSV3 must be clear

### ISSUE THREAD

**Issue by bughp** [parse-community/parse-server#5245]
hmy-app_1  | /app/node_modules/parse-server/lib/ParseServer.js:218
hmy-app_1  |           throw err;
hmy-app_1  |           ^
hmy-app_1  | 
hmy-app_1  | RangeError: Invalid WebSocket frame: RSV2 and RSV3 must be clear
hmy-app_1  |     at Receiver.getInfo (/app/node_modules/parse-server/node_modules/ws/lib/receiver.js:160:14)
hmy-app_1  |     at Receiver.startLoop (/app/node_modules/parse-server/node_modules/ws/lib/receiver.js:121:22)
hmy-app_1  |     at Receiver._write (/app/node_modules/parse-server/node_modules/ws/lib/receiver.js:69:10)
hmy-app_1  |     at doWrite (_stream_writable.js:410:12)
hmy-app_1  |     at writeOrBuffer (_stream_writable.js:394:5)
hmy-app_1  |     at Receiver.Writable.write (_stream_writable.js:294:11)
hmy-app_1  |     at Socket.socketOnData (/app/node_modules/parse-server/node_modules/ws/lib/websocket.js:788:35)
hmy-app_1  |     at Socket.emit (events.js:182:13)
hmy-app_1  |     at Socket.EventEmitter.emit (domain.js:441:20)
hmy-app_1  |     at addChunk (_stream_readable.js:283:12)

**Comment by flovilmart** [comment]
Closing as this is not an issue with the server but with your client and/or the was module. 

Feel free to reopen an issue with the template correctly and completely filled, with samples and reproduction steps.
