### ISSUE TITLE
performance issue

### ISSUE THREAD

**Issue by Amit-synergytop** [parse-community/parse-server#5262]
### Issue Description
We are using AWS lambda functions and MongoDB Atlas with parse server.
We are facing slow API response issue and we are trying to determine where is the issue. As I did some RND on it and get conclusion that parse server responding slow.
So can you please help me in determining the actual problem or suggest me any tool through which I can determine it by my self.

#### Expected Results
Getting 10 Records in response Time : 50ms

#### Actual Outcome
Getting 10 Records in response Time : 1500ms

### Environment Setup
Server-less Architecture 

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 1.8.0
  - Operating System:     AWS Lambda Server

- **Database**
  - MongoDB Atlas

**Comment by flovilmart** [comment]
Hi, 

> get conclusion that parse server responding slow.

What makes you reach this conclusion?

**Comment by Amit-synergytop** [comment]
We removed the parse server and directly called the lambda server and observe that the speed is getting quite fast.

**Comment by flovilmart** [comment]
Can you provide benchmarks from your load tests?

Also you are using version 1.8.0 which does not exist. Where did you get this version from?

**Comment by Amit-synergytop** [comment]
Sorry this is correct version 3.1.2. And i will provide benchmarks.

**Comment by flovilmart** [comment]
Another thing you can check is the same benchmark with the server running locally. Can you provide those numbers?

**Comment by flovilmart** [comment]
You can use the `ab` tool 
https://httpd.apache.org/docs/2.4/programs/ab.html

To perform a benchmark against your server. The interface is similar to curl

**Comment by Amit-synergytop** [comment]
This is ApacheBench, Version 2.3 <$Revision: 1807734 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking cpp-bucket.s3-website-us-west-2.amazonaws.com (be patient)
Completed 100 requests
Completed 200 requests
Completed 300 requests
Completed 400 requests
Completed 500 requests
Completed 600 requests
Completed 700 requests
Completed 800 requests
Completed 900 requests
Completed 1000 requests
Finished 1000 requests


Server Software:        AmazonS3
Server Hostname:        cpp-bucket.s3-website-us-west-2.amazonaws.com
Server Port:            80

Document Path:          /
Document Length:        1320 bytes

Concurrency Level:      10
Time taken for tests:   30.018 seconds
Complete requests:      1000
Failed requests:        0
Keep-Alive requests:    992
Total transferred:      1678960 bytes
HTML transferred:       1320000 bytes
Requests per second:    33.31 [#/sec] (mean)
Time per request:       300.182 [ms] (mean)
Time per request:       30.018 [ms] (mean, across all concurrent requests)
Transfer rate:          54.62 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    4  32.9      0     287
Processing:   281  295  36.9    291    1395
Waiting:      281  295  36.9    291    1395
Total:        281  299  51.3    291    1395

Percentage of the requests served within a certain time (ms)
  50%    291
  66%    293
  75%    295
  80%    296
  90%    303
  95%    325
  98%    367
  99%    601
 100%   1395 (longest request)

**Comment by flovilmart** [comment]
So what is wrong with those benchmark values?

**Comment by flovilmart** [comment]
Also what was the command that you ran?

**Comment by Amit-synergytop** [comment]
ab -n 1000 -c 10 -k -H "Accept-Encoding: gzip, deflate" http://cpp-bucket.s3-website-us-west-2.amazonaws.com/

**Comment by flovilmart** [comment]
This does not make a query to your server though. Did you check the REST documentation in order to properly make a query?

**Comment by Amit-synergytop** [comment]
Can you provide any example for ab tool? So I will used that.

**Comment by flovilmart** [comment]
Well I don't know your server URLs, API keys etc...

`ab -n 1000 -c 10 -k  -H "X-Parse-Application-Id: APP_ID" -H "X-Parse-REST-API-Key: REST_KEY" http://URL_TO_QUERY_THE_CLASS`

You can actually check everything is running smoothly with using `curl`  and this documentation:

https://docs.parseplatform.org/rest/guide/#queries

**Comment by Amit-synergytop** [comment]
ab -A "authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibm9ybWFuQHlvcG1haWwuY29tIiwiZW1haWwiOiJub3JtYW5AeW9wbWFpbC5jb20iLCJfaWQiOiJPbkJGZmlMUmlFIiwiaWF0IjoxNTQ1OTE4OTQwfQ.vL0MCqwKNijtqabo5nlsDI1S1IG8IAFKJRH2JutwCXY" -n 1000 -c 10 -k  -H "X-Parse-Application-Id: myAppId" -H "X-Parse-REST-API-Key: myMasterKey" -H "X-Parse-REST-API-Key: myMasterKey" -H "Accept: application/json, text/plain, */*" http://35.175.12.99:3001/parse/functions/viewProject
This is ApacheBench, Version 2.3 <$Revision: 1807734 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 35.175.12.99 (be patient)
Completed 100 requests
Completed 200 requests
Completed 300 requests
Completed 400 requests
Completed 500 requests
Completed 600 requests
Completed 700 requests
Completed 800 requests
Completed 900 requests
Completed 1000 requests
Finished 1000 requests


Server Software:        
Server Hostname:        35.175.12.99
Server Port:            3001

Document Path:          /parse/functions/viewProject
Document Length:        70 bytes

Concurrency Level:      10
Time taken for tests:   21.126 seconds
Complete requests:      1000
Failed requests:        0
Keep-Alive requests:    1000
Total transferred:      446000 bytes
HTML transferred:       70000 bytes
Requests per second:    47.33 [#/sec] (mean)
Time per request:       211.262 [ms] (mean)
Time per request:       21.126 [ms] (mean, across all concurrent requests)
Transfer rate:          20.62 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    2  20.5      0     214
Processing:   201  208  17.6    203     372
Waiting:      201  208  17.6    203     372
Total:        201  210  26.9    203     427

Percentage of the requests served within a certain time (ms)
  50%    203
  66%    207
  75%    210
  80%    211
  90%    213
  95%    214
  98%    328
  99%    403
 100%    427 (longest request)

**Comment by flovilmart** [comment]
> Time per request: 21.126 [ms] (mean, across all concurrent requests)

and as you can see the performance is just fine

**Comment by Amit-synergytop** [comment]
Yes i am using custom functions. this is testing report using with lambda server.

ab -A "authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibm9ybWFuQHlvcG1haWwuY29tIiwiZW1haWwiOiJub3JtYW5AeW9wbWFpbC5jb20iLCJfaWQiOiJPbkJGZmlMUmlFIiwiaWF0IjoxNTQ1OTE4OTQwfQ.vL0MCqwKNijtqabo5nlsDI1S1IG8IAFKJRH2JutwCXY" -n 1000 -c 10 -k  -H "X-Parse-Application-Id: myAppId" -H "X-Parse-REST-API-Key: myMasterKey" -H "X-Parse-REST-API-Key: myMasterKey" -H "Accept: application/json, text/plain, */*" https://724bsy9xt2.execute-api.us-west-2.amazonaws.com/latest/parse/viewProject
This is ApacheBench, Version 2.3 <$Revision: 1807734 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 724bsy9xt2.execute-api.us-west-2.amazonaws.com (be patient)
Completed 100 requests
Completed 200 requests
Completed 300 requests
Completed 400 requests
Completed 500 requests
Completed 600 requests
Completed 700 requests
Completed 800 requests
Completed 900 requests
Completed 1000 requests
Finished 1000 requests


Server Software:        
Server Hostname:        724bsy9xt2.execute-api.us-west-2.amazonaws.com
Server Port:            443
SSL/TLS Protocol:       TLSv1.2,ECDHE-RSA-AES128-GCM-SHA256,2048,128
TLS Server Name:        724bsy9xt2.execute-api.us-west-2.amazonaws.com

Document Path:          /latest/parse/viewProject
Document Length:        70 bytes

Concurrency Level:      10
Time taken for tests:   59.178 seconds
Complete requests:      1000
Failed requests:        0
Keep-Alive requests:    1000
Total transferred:      902000 bytes
HTML transferred:       70000 bytes
Requests per second:    16.90 [#/sec] (mean)
Time per request:       591.779 [ms] (mean)
Time per request:       59.178 [ms] (mean, across all concurrent requests)
Transfer rate:          14.88 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    1   9.8      0     103
Processing:   240  590 2563.1    249   29112
Waiting:      240  590 2563.1    249   29112
Total:        240  591 2572.1    249   29213

Percentage of the requests served within a certain time (ms)
  50%    249
  66%    257
  75%    274
  80%    671
  90%    701
  95%    893
  98%    901
  99%   4147
 100%  29213 (longest request)

**Comment by Amit-synergytop** [comment]
Actually i have putting data limit (10) that way i am getting fast response. otherwise i will putting data limit (100) after that response time increased .

**Comment by flovilmart** [comment]
> putting data limit (100) after that response time increased .

By how much? Can you provide the benchmark results?

Initially you stated that in order to get 10 objects you were seeing response times of 1500ms. Is it *still* the case?

**Comment by Amit-synergytop** [comment]
let you know after creating benchmark report

**Comment by Amit-synergytop** [comment]
if Any other option for get benchmark report. Please let me know.

**Comment by flovilmart** [comment]
I will be closing this issue now, as the performance is not what is described in the original issue description. If you have performance issues, consider running another benchmark through AB and open the issue with the performance report.
