### ISSUE TITLE
What are these files in mlab? [fs.chunks, _JobStatus, _Push Status]

### ISSUE THREAD

**Issue by JoaoArmandoo** [parse-community/parse-server#5266]
Hello everyone, I just go to the mlab see how my storage is, and I realize that some files are taking up too much space, I do not know what they are ... Can I delete these files without problems?

The first file that catches my attention is: **fs.chunks**
[You can see a image here](https://drive.google.com/file/d/10RUIJfgSRVqNPliArXxNkDyGYfUM7A9m/view?usp=sharing)
What is this for? Can I delete it safely without causing problems?

The second file is: **_JobStatus**
[You can see a image here](https://drive.google.com/file/d/1oXzdyVmTrwK5MCqSFeeAX7pW84SX57Ec/view?usp=sharing)

The third and last file is: **_Push Status**
[You can see a image here](https://drive.google.com/file/d/1XeqHAh6cRlqjIkIO5XrkBquXCMGA_v6u/view?usp=sharing)

Could you explain to me what these files are for, and tell me if I can safely delete them? Thank you very much!!

**Comment by flovilmart** [comment]
> The first file that catches my attention is: fs.chunks

these are all the uploaded files by your users, you should not delete them. Also you should consider storing the files in S3 or another storage.

>  The second file is: _JobStatus

The _JobStatus collection keeps track of the execution of past jobs, you should be able to safely delete them

> The third and last file is: _PushStatus

The _PushStatus collection keeps track of all the sent push notification, you should be able to safely delete them if you do not mind loosing the history.

For both _PushStatus and _JobStatus, you can probably [create a TTL index](https://docs.mongodb.com/manual/core/index-ttl/). A TTL index allows a collection to automatically purge 'old' objects, as configured by `expireAfterSeconds`. Mlab provides an inteface to configure those. You could set the expireAfterSeconds to `2592000` (a month)
