### ISSUE TITLE
Parse Server 3.1.3 release not available in npm directory

### ISSUE THREAD

**Issue by funkenstrahlen** [parse-community/parse-server#5268]
Currently it only lists `3.1.2` release but not the current `3.1.3` release. https://www.npmjs.com/package/parse-server

**Comment by flovilmart** [comment]
Thanks @funkenstrahlen for pointing this out! I've fixed the travis setup so it build and should be all good now.

**Comment by funkenstrahlen** [comment]
Thank you! 😊
