### ISSUE TITLE
Google and Twitter Auth

### ISSUE THREAD

**Issue by GoGross** [parse-community/parse-server#5273]
Where can I get full documentation on implementing google and twitter auth, seems the documentation doesn't have it all? I have successfully done so with Facebook with no problems. An example gist? @flovilmart

**Comment by flovilmart** [comment]
What did you try? Or miss? Everything is documented in docs.parseplatform.org.

**Comment by GoGross** [comment]
Kindly reference the Google implementation for me, its nowhere to be found.

**Comment by flovilmart** [comment]
I don’t have any reference implementation at hand, sorry about that. But all is documented. Closing as it’s not a bug with the server.
