### ISSUE TITLE
I can't upload PFFile (image) from Dashboard and I get 404 when I try to access it on browser when my parse server uses https

### ISSUE THREAD

**Issue by JEKos** [parse-community/parse-server#5279]
### Issue Description
Hi,
I have a parse server on Digital Ocean with https using nginx proxy method. My parse server url is like https://my-domain.com/myappname. I have added this link to publicServerURL of my parse server in index.js file to use for mailgun and files.

I also have added this link as **serverURL** in `config.json` file of Parse Dashboard.
I tried to upload a pffile (image) through Parse Dashboard but it says **Unable to connect to Parse API** . 
When I change the **serverURL** in `config.json` file, from https://my-domain.com/myappname to http://server-ip:port/parse, it's working without a problem, but I get an error when I try to delete a row from the database (With https this thing works without problem)

my file in `/etc/nginx/sites-enabled/my-domain.com` is the follow (I also hosting my website in the same server with my parse server):

```
server {

        root /var/www/my-domain.com/html;
        index index.php index.html index.htm index.nginx-debian.html;
        client_max_body_size 100m;
        server_name my-domain.com www.my-domain.com;


        location / {
               if ($request_uri ~ ^/(.*)\.html$) {
                    return 302 /$1;
                }
               #try_files $uri $uri/ =404;
               try_files $uri $uri.html $uri/ /index.php$is_args$args;
        }

        location ~ \.php$ {
                include snippets/fastcgi-php.conf;
                fastcgi_pass unix:/var/run/php/php7.2-fpm.sock;
        }

        location ~ /\.ht {
                deny all;
        }

        location /myparseapp {
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-NginX-Proxy true;
                proxy_pass http://localhost:1337/parse;
                proxy_ssl_session_reuse off;
                proxy_set_header Host $http_host;
                proxy_redirect off;
        }


    location = /favicon.ico { log_not_found off; access_log off; }
    location = /robots.txt { log_not_found off; access_log off; allow all; }
    location ~* \.(css|gif|ico|jpeg|jpg|js|png)$ {
        expires max;
        log_not_found off;
    }

    listen [::]:443 ssl ipv6only=on; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/my-domain.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/my-domain.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot


}
server {
    if ($host = www.my-domain.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    if ($host = my-domain.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


        listen 80;
        listen [::]:80;

        server_name my-domain.com www.my-domain.com;
    return 404; # managed by Certbot

}
```

Also I can't access the uploaded PFFile(image) through web browser. The url `https://my-domain.com/myappname/files/11d51c92517ace2d17bc376f2da99a50_default.png` says  **404 Not Found nginx/1.14.0 (Ubuntu)**

#### Expected Results

I want to upload pffile(image) through Parse Dashboard using https without getting that error.
Also I want to access that pffile(image) through web browser without getting the 404 Not Found page from nginx.

#### Actual Outcome

• When I use `https` as serverURL in Parse Dashboard I can't upload PFFile(image) and I get **Unable to connect to Parse API**
• When I use `http` as serverURL in Parse Dashboard I can upload PFFile(image) but I can't delete rows.
• With both (above) methods I can't access the PFFile(image) through web browser. It says **404 Not Found nginx/1.14.0 (Ubuntu)**
### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 3.1.3
  - Operating System:     Ubuntu 18.04 x64bit
  - Hardware:             Digital Ocean the 5$ droplet
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Digital Ocean

- **Database**
  - MongoDB version:  I'm not using MongoDB but PostgreSQL
  - Storage engine:  [FILL THIS OUT]
  - Hardware:        [FILL THIS OUT]
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): Digital Ocean

**Comment by JEKos** [comment]
I also found that when i have http://my-ip:my-port/parse in my config.json for the Dashboard and have the same as a publicServerURL I can add and delete rows without a problem and also I can upload files and see the images on the browser. 

When I change only the publicServerURL to https://my-domain.com/myapp. I can't see the images on the browser ,I can't upload files and I can't delete rows.

When I change my config.json and my publicServerURL to https://my-domain.com/myapp. I can't upload files and see images on the browser.

So
1st: All working (Without https and without domain)
2nd :  I can't upload files, I can't see images in browser, I cant delete rows (https only in publicServerURL)
3nd: I can't upload files, I can't see images in browser (https in publicServerURL and https in config.json of the Dashboard)

@flovilmart is anything to do with parse-server not allowing https as publicServerURL ?

**Comment by flovilmart** [comment]
> is anything to do with parse-server not allowing https as publicServerURL ?

did you configure HTTPS properly? is your certificate valid?

**Comment by JEKos** [comment]
@flovilmart Yeah, my apps (iOS and Android) use `https://my-domain.com/myapp`  as a server url in Parse initialization without any problem. I have SSL from Let's Encrypt that renew the certifications automatically.

The problem is nginx doesn't recognize files after the `htttps://my-domain.com/myapp` path

For example:
If I want to see the image in  `https://my-domain.com/myapp/files/myappid/114b216c479501c629934e915a9a7d33_avatar.png`
it say's **404 Not found**

but when I want to go to `https://my-domain.com/myapp/files/myappid/` , returns the same thing that https://my-domain.com/myapp returns, which is `{"error":"unauthorized"}`  (I know this means it's working without problem)

**Comment by JEKos** [comment]
Yeah, sure. I have an Ubuntu 18.04 x64bit without any add-on from digital ocean's list. 
I have installed postgres (This is what I'm using as db), parse-server, nginx, node.js and mailgun plugin.

Here is the my whole index.js file :

```
// Example express application adding the parse-server module to expose Parse
// compatible API routes.
var express = require('express');
var ParseServer = require('parse-server').ParseServer;
var path = require('path');

var api = new ParseServer({
    databaseURI: 'postgres://mydbname:mydbpassword@localhost:port/myappdb',
    cloud: __dirname + '/cloud/main.js',
    appId: 'myappId',
    masterKey: 'myMasterKey', //Add your master key here. Keep it secret!
    serverURL: 'http://localhost:1337/parse', // Don't forget to change to https if needed
    publicServerURL: 'https://my-domain.com/myapp',
    filesAdapter: {
        module: '@parse/fs-files-adapter'
    },
    appName: 'MY-APP-NAME',
    verifyUserEmails: true,
    emailAdapter: {
        module: 'parse-server-mailgun',
        options: {
            fromAddress: 'MY-APP-NAME App <no-reply@my-domain.com>',
            domain: 'mg.my-domain.com',
            host: 'api.mailgun.net',
            apiKey: 'my-mailgun-api-key',
            templates: {
                passwordResetEmail: {
                    subject: 'Reset your password',
                    pathPlainText: path.join(__dirname, '../mypath/email-templates/password_reset_email.txt'),
                    pathHtml: path.join(__dirname, '../mypath/email-templates/password_reset_email.html'),
                },
                verificationEmail: {
                    subject: 'Confirm your account',
                    pathPlainText: path.join(__dirname, '../mypath/email-templates/verification_email.txt'),
                    pathHtml: path.join(__dirname, '../mypath/email-templates/verification_email.html'),
                    callback: () => {},
                }
            }
        }
    },
    customPages: {
        invalidLink: 'https://my-domain.com/invalid-link.html',
        verifyEmailSuccess: 'https://my-domain.com/verify-email-success.html',
        choosePassword: 'https://my-domain.com/choose-password.html',
        passwordResetSuccess: 'https://my-domain.com/password-reset-success.html',
    },
    auth: {
        twitter: {
            consumer_key: "my-twitter-consumer-key", // REQUIRED
            consumer_secret: "my-twitter-consumer-secrect" // REQUIRED
        },
        facebook: {
            appIds: "my-facebook-appId"
        },
        instagram: {

        },
        google: {

        }
    },
    liveQuery: {
        classNames: ["TestLiveQuery"] // List of classes to support for query subscriptions
    }
});
// Client-keys like the javascript key or the .NET key are not necessary with parse-server
// If you wish you require them, you can set them as options in the initialization above:
// javascriptKey, restAPIKey, dotNetKey, clientKey

var app = express();

// Serve static assets from the /public folder
app.use('/public', express.static(path.join(__dirname, '/public')));

// Serve the Parse API on the /parse URL prefix
var mountPath = '/parse';
app.use(mountPath, api);

// Parse Server plays nicely with the rest of your web routes
app.get('/', function (req, res) {
    res.status(200).send('I dream of being a website.  Please star the parse-server repo on GitHub!');
});

// There will be a test page available on the /test path of your server url
// Remove this before launching your app
app.get('/test', function (req, res) {
    res.sendFile(path.join(__dirname, '/public/test.html'));
});

var port = 1337;
var httpServer = require('http').createServer(app);
httpServer.listen(port, function () {
    console.log('parse-server running on port ' + port + '.');
});

// This will enable the Live Query real-time server
var parseLiveQueryServer = ParseServer.createLiveQueryServer(httpServer);
```

**Comment by flovilmart** [comment]
This is likely caused because the mount path is different between your publicServerURL and serverURL. Try using the https://my-domain.com URL as the serverURL OR use /myapp as your mount in the serverURL (instead of /parse)

**Comment by JEKos** [comment]
@flovilmart I changed to  /myapp like that:

```
// Serve the Parse API on the /parse URL prefix
var mountPath = '/myapp';
app.use(mountPath, api);
```

But when I start the parse-server it says 

```
root@DigitalOceanServer:~/pmore-server# npm start

> parse-server-example@1.4.0 start /root/pmore-server
> node index.js

parse-server running on port 1337.

WARNING, Unable to connect to 'http://localhost:1337/parse'. Cloud code and push notifications may be unavailable!
```
and my server doesn't work.

Also my https://my-domain.com goes to a website. I'm hosting a website in the same Digital Ocean Server

The `https://my-domain.com/myapp` is a reverse proxy for `http://localhost:1337/parse` (as you can see from the first post in nginx config file). So it's the same `/parse` path right? For serverURL and publicServerURL.

**Comment by flovilmart** [comment]
> I changed to /myapp like that:

You need to change all the references from /parse to /myapp if you are going that route OR you can replace /myapp by /parse in your nginx config and other relevant place.

**Comment by JEKos** [comment]
@flovilmart You mean I have to change from 

location /myapp {
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-NginX-Proxy true;
                proxy_pass http://localhost:1337/parse;
                proxy_ssl_session_reuse off;
                proxy_set_header Host $http_host;
                proxy_redirect off;
        }

to 

location /parse {
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-NginX-Proxy true;
                proxy_pass http://localhost:1337/parse;
                proxy_ssl_session_reuse off;
                proxy_set_header Host $http_host;
                proxy_redirect off;
        }

It doesn't do anything. It just change the name of the url from `https://my-domain.com/myapp/files/myappid/114b216c479501c629934e915a9a7d33_avatar.png` to `https://my-domain.com/parse/files/myappid/114b216c479501c629934e915a9a7d33_avatar.png`

**Comment by flovilmart** [comment]
Sorry then, that’s perhaps something else. Are you sure the file is in the drive as you are using the fs file adapter?

**Comment by JEKos** [comment]
@flovilmart Ok, but my parse-server reverse proxies are working without a problem in my apps. (I have 2 parse servers, 1337 and 1310 port)

Do you recommend any good tutorial on how you can setup ngnix properly for the parse server?

**Comment by flovilmart** [comment]
> but my parse-server reverse proxies are working without a problem in my apps

I am not sure what you mean by that, becuuse there are clearly some problems in the configuration that you describe.

This does not look like a parse-server bug, as you are mentioning, it works locally.

> Do you recommend any good tutorial on how you can setup ngnix properly for the parse server?

I do not know any specific for parse-server, but any tutorial for usign nginx in front of a nodejs app should work.

**Comment by JEKos** [comment]
> > but my parse-server reverse proxies are working without a problem in my apps
> 
> I am not sure what you mean by that, becuuse there are clearly some problems in the configuration that you describe.

@flovilmart I mean that reverse proxy that go from http://my-domain.com/myapp to http://my-ip:1337/parse it's working but I can't retrieve the PFFile images through code in my iOS app and also I can't upload PFile and see the images through Parse Dashboard.

Maybe I'll try to re-setup again the DigitalOcean server to see if nginx works correctly in the new setup.

Thanks for your help! 👍

**Comment by JEKos** [comment]
Finally I found solution!!!🎉🎉  After 10+ hours searching and testing this weekend I found it!

My solution about having dashboard with https is [here](https://github.com/parse-community/parse-dashboard/issues/598#issuecomment-455895329)

And for parse-server, I used `subdomain.my-domain.com` instead of `my-domain.com/myapp` and in nginx config I removed `try_files $uri $uri/ =404;` and typed the follow

```
location / {
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-NginX-Proxy true;
                proxy_pass http://localhost:1337/parse/;
                proxy_ssl_session_reuse off;
                proxy_set_header Host $http_host;
                proxy_redirect off;
        }
```

You need to have `/` at the of `proxy_pass` for the images to work on your browser.

Thank you @flovilmart for your help!
