### ISSUE TITLE
 No retries are made after "failed to connect on first connect" 

### ISSUE THREAD

**Issue by barakbd** [parse-community/parse-server#5280]
Please see issue here: https://github.com/Automattic/mongoose/issues/5169

Same issue occurs in parse-server.

Suggestions?

**Comment by flovilmart** [comment]
From what I can read, this behavior is expected from the driver perspective.

Also, parse server has some initialization to perform before it can startup. So it will always expect the DB to be up before it starts. 

Even in the docker compose docs, they recommend to add a ‘wait-for-it’ script
https://docs.docker.com/compose/startup-order/ for such behavior. I am not sure we should fix in parse-server
