### ISSUE TITLE
Users can't Login via REST API

### ISSUE THREAD

**Issue by nuborian** [parse-community/parse-server#5283]
Hey,

since update i can't get login a user to work - and i have really no idea why ... :(

`Running on http://localhost:1337
dyld: lazy symbol binding failed: Symbol not found: __ZN4node19GetCurrentEventLoopEPN2v87IsolateE
  Referenced from: /Users/*****/Documents/*****/_Development/*****/node_modules/bcrypt/lib/binding/bcrypt_lib.node
  Expected in: flat namespace

dyld: Symbol not found: __ZN4node19GetCurrentEventLoopEPN2v87IsolateE
  Referenced from: /Users/*****/Documents/*****/_Development/*****/node_modules/bcrypt/lib/binding/bcrypt_lib.node
  Expected in: flat namespace

Program node index.js exited with code null
`

That's my output in console.. 

All I am trying to do is login a user with his username/password via REST-API on my local Parse-Server. Any idea what could be wrong?

**Comment by flovilmart** [comment]
Try deleing the `node_modules` folder and running `npm install` again

**Comment by nuborian** [comment]
hmm tried that - same result. Did I use any wrong/old version of some module or what was your idea?

**Comment by flovilmart** [comment]
Perhaps, I have no way to know from here. What version of node do you use? I believe this was requested in the bug template.

**Comment by nuborian** [comment]
Node Version is v9.2.0

**Comment by flovilmart** [comment]
Can you use latest node LTS (10.14.x)

**Comment by nuborian** [comment]
Updated node to 11.6.x and it works =)
