### ISSUE TITLE
Parse.Cloud.job, syntax problem

### ISSUE THREAD

**Issue by markuswinkler** [parse-community/parse-server#5297]
### Issue Description

I am not sure what I am doing wrong here. Must be something very simple.
It always fails in the logs. I tried to follow the migration guide for 3.x.

```
Parse.Cloud.job("delete sign up stage 0 users", async function(request) {
	// Update the Job status message
	let query = new Parse.Query(Parse.User);
	query.limit = 200;
	query.equal("signUpStage",0);
	const results = await query.find({useMasterKey: true});
	await Parse.Object.destroyAll(results, {useMasterKey: true});
	request.message("done");
});

```

#### Expected Results

job result success

#### Actual Outcome

job result failed

### Environment Setup

  - parse-server version (Be specific! Don't say 'latest'.) : 3.1.3

**Comment by flovilmart** [comment]
What do you mean fails? Can you get the job status object from the DB?

**Comment by markuswinkler** [comment]
Ahh, ok, got it. Once I wrapped inside a try/catch I could read the error.
I used .equal instead of .equalTo.
Will wrap up all future jobs in a try/catch.
Sorry to bother you with something so simple and thanks for the help!

**Comment by flovilmart** [comment]
The job should properly inform you about this error though. Can you provide the _JobStatus object and a screenshot of the dashboard?

**Comment by markuswinkler** [comment]
![screen shot 2019-01-14 at 9 36 45 pm](https://user-images.githubusercontent.com/762485/51155157-92b9be80-1844-11e9-82a2-090b21fe4b26.png)

failed status:
```
        {
            "objectId": "u4Msd99OoA",
            "jobName": "delete sign up stage 0 users",
            "params": {
                "description": "Executing from job schedule web console.",
                "input": {},
                "jobName": "delete sign up stage 0 users",
                "when": 0
            },
            "status": "failed",
            "source": "api",
            "createdAt": "2019-01-15T02:11:34.467Z",
            "updatedAt": "1970-01-01T00:00:00.000Z",
            "finishedAt": {
                "__type": "Date",
                "iso": "2019-01-15T02:11:34.475Z"
            },
            "ACL": {}
        },
```

**Comment by flovilmart** [comment]
Ok we should probably record the error message if there was an exception.
