### ISSUE TITLE
MongoDB@3.2.0 doesn't exist

### ISSUE THREAD

**Issue by Erik-Stevens** [parse-community/parse-server#5320]
### Issue Description

Project won't build because the parse-server package.json file contains dependency: mongodb@3.2.0, which does not exist. I believe the latest npm package for mongodb is 3.1.13.

npm ERR! notarget No matching version found for mongodb@3.2.0
       npm ERR! notarget In most cases you or one of your dependencies are requesting
       npm ERR! notarget a package version that doesn't exist.
       npm ERR! notarget 
       npm ERR! notarget It was specified as a dependency of 'parse-server'

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 3.1.3
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Heroku

**Logs**
>npm view mongodb versions  --json
[
...
  "2.2.36",
  "3.0.0-rc0",
  "3.0.0",
  "3.0.1",
  "3.0.2",
  "3.0.3",
  "3.0.4",
  "3.0.5",
  "3.0.6",
  "3.0.7",
  "3.0.8",
  "3.0.9",
  "3.0.10",
  "3.0.11",
  "3.1.0-beta1",
  "3.1.0-beta2",
  "3.1.0-beta3",
  "3.1.0-beta4",
  "3.1.0",
  "3.1.1",
  "3.1.2",
  "3.1.3",
  "3.1.4",
  "3.1.5",
  "3.1.6",
  "3.1.7",
  "3.1.8",
  "3.1.9",
  "3.1.10",
  "3.1.11",
  "3.1.12",
  "3.1.13"
]

**Comment by flovilmart** [comment]
It seems that npm unpublished 3.2.0 as the build was successful https://github.com/parse-community/parse-server/pull/5300

**Comment by dplewis** [comment]
@flovilmart 3.2.0 was reverted https://github.com/mongodb/node-mongodb-native/commit/508d685747e83276016718c2046ec3c30de8c4db

**Comment by flovilmart** [comment]
The fix has been merged @Erik-Stevens .  I don’t believe this was released in the wild, so next release will be OK

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
