### ISSUE TITLE
increment inset filelds error

### ISSUE THREAD

**Issue by puny-d** [parse-community/parse-server#5327]
My scheme design: Product
`{
 objectId: xxxxxxxxx,
  sku:{
"1548573702": {
    "count": 12,
......
  }
}
}`

so if I want to increment the count, I would
`some.incement("sku.1548573702.count",1)`

And count expect to be 13, but the result is

`{
 objectId: xxxxxxxxx,
  sku:{
"1548573702": {
    "count": ":{"__op":"Increment","amount":1}",
......
  }
}
}`

**Parse-server: 3.1.3
Postgresql: 9.5.4**

**Comment by dplewis** [comment]
@flovilmart I remember you were against updating / setting nested documents. Are you still against this feature?

**Comment by flovilmart** [comment]
Well, that’s messy and prone to error. Just wondering how good it can be, given that PG isn’t great at that

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dplewis** [comment]
Setting fields in a nested document is already optional. We can make the rest optional as well

**Comment by flovilmart** [comment]
alright let's go then.
