### ISSUE TITLE
Allow slash in Parse.File names

### ISSUE THREAD

**Issue by GabrielLomba** [parse-community/parse-server#5328]
**Is your feature request related to a problem? Please describe.**
I am trying to better organize files uploaded to the server and I can't because of the restriction on [this line](https://github.com/parse-community/parse-server/blob/22c39ed6c86263e69c836b2d03898b6076ebef89/src/Routers/FilesRouter.js#L91).

**Describe the solution you'd like**
I would like to be able to save them with slashes as that would allow a clear folder separation between the files, something that another character does not do as clearly (I am using S3 and it supports this separation).

**Describe alternatives you've considered**
I am currently having to fork the S3 Files Adapter in order to implement this. Even though a slash may not be supported by all adapters, since it is supported by some, I believe the server should allow the adapter to decide wheter or not that is a valid name.

**Comment by milesrichardson** [comment]
Related discussion: https://github.com/parse-community/parse-server-s3-adapter/issues/16
