### ISSUE TITLE
wss Fails over SSL, works well on https

### ISSUE THREAD

**Issue by GoGross** [parse-community/parse-server#5347]
### Issue Description

I am trying to run ParseLiveQueries, and everything seems to work well over nodejs HTTP, but fails over HTTPS

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 3.0
  - Operating System:    3.1.1
  - Hardware:            Linux
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): [FILL THIS OUT]

- **Database**
  - MongoDB version: 3.4
  - Storage engine:  wiredTiger
  - Hardware:        Linux
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): AWS, Localhost

### Logs/Trace

info: Client disconnect: undefined
error: Can not find client undefined on disconnect

parse.js:1353 WebSocket connection to 'wss://localhost:8080/api/' failed: Error during WebSocket handshake: net::ERR_SSL_PROTOCOL_ERROR

**Comment by flovilmart** [comment]
I will assume you are using nginx. Did you configure it correctly for web sockets?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by GoGross** [comment]
OPINION: Its a "uws" module error on line `ParseWebSocketServer.js line 14`, and has since been fixed in "ws". "uws" module has been deprecated, 

```javascript
const getWS = function () {
  try {
    return require('uws'); 
  } catch (e) {
    return require('ws');
  }
};
```

my temporary solution:

```javascript
const getWS = function () {
  return require('ws');
};
```

**Comment by GoGross** [comment]
I dont know either, but two things are certain, "uws" don't exist no more, my issue is temporarily solved by its omission.

**Comment by flovilmart** [comment]
And http va https has nothing to do with ws versus uws as packages. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by GoGross** [comment]
Well according to you, thanks for nothing buddy.

**Comment by flovilmart** [comment]
not sure what this is then:

```
$ ls node_modules/uws
LICENSE                 uws_darwin_57.node*     uws_linux_59.node*      uws_win32_64.node*
README.md               uws_darwin_59.node*     uws_linux_64.node*
package.json            uws_darwin_64.node*     uws_win32_57.node*
uws.js                  uws_linux_57.node*      uws_win32_59.node*
~/src/Parse/parse-server (master ±)
```

And this:

```
npm ls uws
parse-server@3.1.3 /Users/florent/src/Parse/parse-server
└── uws@10.148.1
```

How is it not installed for you?

**Comment by GoGross** [comment]
It installs but fails over wss:// works well with ws://

**Comment by dplewis** [comment]
@GoGross out of curiosity. What version of Node are you running. uws only had binding to node 8 and 9. I believe.

**Comment by GoGross** [comment]
I am running version 10

**Comment by thunderwin** [comment]
I have the same issue... how to solve it..

**Comment by GoGross** [comment]
I don't know why they won't accept my PR but it's because `npm uws` is deprecated and instead of calling `ws` `ParseWebSocketServer.js line 14` still tries it, try remove it completely or edit the module file :

```
const getWS = function () {
  try {
    return require('uws');
  } catch (e) {
    return require('ws');
  }
};

// my temporary solution:

const getWS =  require('ws');
```
