### ISSUE TITLE
Unable to Add Response Headers

### ISSUE THREAD

**Issue by rsmets** [parse-community/parse-server#5348]
To whom this concerns,

I feel like this should a trivial task to add a custom header to the response object however no luck. The [docs](https://docs.parseplatform.org/cloudcode/guide/#the-response-object) state simply doing a `response.headers{"header": "value"}` is the correct way to set however not working. Running parse-server 2.7.3. Curious if anyone else has luck adding custom response headers and if so how? Decided to file this under "need help" because I feel like if it was a bug I would've found a history of this issue. 

NOTE: upon trying to set a cookie having the same issue... not making it out in the final response headers. 

Thanks for your input, much appreciated!

**Comment by flovilmart** [comment]
I believe you are mistaken. The docs part you are referring is stating that you can read headers from the response using Parse.Cloud.httpRequest. It does not mentions anything regarding setting response headers. Where do you attempt this? Note that also, 2.7.3 is no longer maintained and you are heavily encouraged to upgrade to 3.1

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rsmets** [comment]
Hi @flovilmart thanks for your reply. Below is what that doc link takes you to. I believe I'm not mistaken. 

> THE RESPONSE OBJECT
> The response object passed into the success and error will contain:
> 
> status - The HTTP Response status.
> headers - The response headers
> buffer - The raw byte representation of the response body.
> text - The raw response body.
> data - The parsed response, if Cloud Code knows how to parse the content-type that was sent.
> cookies - The cookies sent by the server. They are Parse.Cloud.Cookie objects.

Furthermore here is some example code in which I have tried what is stated above. 

```
Parse.Cloud.define('doSomething', (request, response) => {
  
  validateRequest(request, response).then( () => {
    return AdminFunctions.doSomething(
      request.user,
      request.params,
    )
    }).then(
    result => {
      response.headers = {'Custom-Header': "I Love Parse"}
      response.cookies = {'Custom-Cookie': "I Love Cookies"}
      response.success(result)
    },
    error => {response.error( Errors.errorMessage(error.code,error.message) )}
  )
})
```
I would very much appreciate an example of how one would add a custom header with a Parse.Cloud.define function. Thanks again!

**Comment by flovilmart** [comment]
So yes, you are mistaken. You are reading the docs for `Parse.Cloud.httpRequest` and not `Parse.Cloud.define`.

At this time, there is no way to set http response headers on cloud functions’s responses. Feel free to open a pull request if this is a feature you wish to implement.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rsmets** [comment]
Hmm I see. Maybe I'll start with a pr on the docs. :) 
Jokes aside the pr to allow custom response headers actually seems like something worth doing... I think I might just head that up! 

Thank you again @flovilmart for the the definitive answer and for all your efforts maintaining the project. Very much appreciated!
