### ISSUE TITLE
Updating from v2.3.6 to v3.1.3 MongoDB access issue

### ISSUE THREAD

**Issue by acegreen** [parse-community/parse-server#5372]
Hi, I haven't touched Parse server in a while so maybe I'm missing something obvious here but I can't seem to get the new Parse server instance to recognize my database. The v2.3.6 instance seems to recognize it just fine. 

I also checked the migration documentation but haven't been able to pinpoint the issue. Only warnings on Verbose=1 show that push related issues since I'm running to instances on the same server. First attempt was just running one instance v3.1.3 so these warnings are unrelated.

<img width="1856" alt="screen shot 2019-02-17 at 8 49 02 am" src="https://user-images.githubusercontent.com/10794609/52914660-2265e900-3299-11e9-8dee-f39cc3a6e79e.png">

<img width="927" alt="screen shot 2019-02-19 at 5 18 32 am" src="https://user-images.githubusercontent.com/10794609/53007829-0af83e80-3406-11e9-9228-840d33ff5430.png">

**Comment by nebitrams** [comment]
hi,

  I believe I had faced the same issues as what you see now.  "Unable to ensure uniqueness" for usernames, email addresses and role names.

  Refer to my resolution here https://github.com/parse-community/parse-server/issues/5161#issuecomment-441409616

  If you have a test environment, I recommend that you try to drop the 3 indices in test environment and see whether that resolve the warning.

**Comment by acegreen** [comment]
@nebitrams thanks for the response. The warnings are indeed because I have test environments but that isn't the issue. I had setup v3.1.3 as a standalone and the database still didn't load, that's why I setup another instance and now encounter these warnings. 

Also Im on v3.1.3 and my cloud code is commented out.

**Comment by nebitrams** [comment]
The first 3 warnings starting with "Unable to ensure uniqueness" is not related to your test environment.  They are there because parse-server 3 failed to create new indices.  However, since these are warnings and you application should still work as per normal.

The first line of log says "DATABASE_URI not specified".  Where do you run your mongo database?

**Comment by acegreen** [comment]
@nebitrams database runs locally, and I used the same index.js so I would assume it should work.

<img width="898" alt="screen shot 2019-02-18 at 10 42 34 am" src="https://user-images.githubusercontent.com/10794609/52961975-1f86f900-336a-11e9-9a37-06091b90e62c.png">

**Comment by nebitrams** [comment]
The npm start log in the original post screen shot is truncated. It shows only warning. Is there any error at the end of the log?

Does “npm start” successfully start up the parse server locally?

**Comment by acegreen** [comment]
I updated the screenshot, it is not truncated, the rest was just attempts to query the database. The server is running fine with no errors, its shown in the first few lines of that screenshot.

**Comment by acegreen** [comment]
Got database access on version v3.1.3 by deleting the _PushStatus class though Parse Dashboard, now onto resolving the errors. @nebitrams can you just delete the indexes through Parse dashboard or does it have to be done through MongoDB?

**Comment by nebitrams** [comment]
The database index can only be deleted in mongo database. 

Cannot delete from parse dashboard. 
Do not delete the table column. This is dangerous because those coulmns are useful.
