### ISSUE TITLE
Limit question about Parse?

### ISSUE THREAD

**Issue by LilMoke** [parse-community/parse-server#5383]
I was wondering if anyone can tell me all the citations with Parse.  I know of the 100 record limit and how to get around it, but I am trying to find out what other limitations Parse has.  I have seen some people say that if you get over 10,000 records in the Collections Parse stop working.

So, can anyone tell me what all the limits are with parse?

Thank you

**Comment by mtrezza** [comment]
- The 100 record limit has been a feature of parse.com and has been removed from the open source parse-server.
- I am not aware of any limitations regarding collection size. I have seen collections with millions of documents where parse server works fine. Before parse server becomes a conceptual limitation regarding most (hobby) developers will run into database limitations (e.g. [monogdb limitations](https://docs.mongodb.com/manual/reference/limits)) or infrastructure limitations.

**Comment by acegreen** [comment]
is it 100 or 1000?

**Comment by mtrezza** [comment]
In any case there is a default limit of results returned when _not setting a limit_, but you can set any limit for a query.

```
const query = new Parse.Query("MyClass");
const results = query.find(); // Returns 100 results

query.limit(5000);
const results = query.find(); // Returns 5k results
```

**Comment by acegreen** [comment]
Can you set an unlimited query?

**Comment by mtrezza** [comment]
Did you take a look at the DB docs?

For [mongodb](https://docs.mongodb.com/manual/reference/method/cursor.limit):

> A limit() value of 0 (i.e. .limit(0)) is equivalent to setting no limit.

**Comment by acegreen** [comment]
I never noticed that. Thanks

**Comment by acinader** [comment]
Nothing to do here, right?

**Comment by omkar-tenkale** [comment]
query.limit(0); **doesn't** fetch all rows, the response simply has 0  rows
