### ISSUE TITLE
S3 file adapter docs missing parameters

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-server#5386]
The [S3 file adapter](https://docs.parseplatform.org/parse-server/guide/#configuring-s3adapter) is missing some parameters that have been added over time.

**Suggestions for parameters to add to doc:**

baseUrl
- Description: The base URL the file adapter uses to determine the file location for direct access.
- Note: Optional. Default: `null`. To be used when `directAccess=true`. When set the file adapter returns a file URL in format `baseUrl/bucketPrefix` + `filename`. Example for `baseUrl='http://domain.com/folder'` and `bucketPrefix='prefix_'` the returned file location is  `http://domain.com/folder/prefix_file.txt`.

baseUrlDirect
- Description: Is true if the file adapter should ignore the bucket prefix when determining the file location for direct access.
- Note: Optional. Default: `false`. To be used when `directAccess=true` and `baseUrl` is set. When set to `true`, the file adapter returns a file URL in format `baseUrl/filename`. Example for `baseUrl='http://domain.com/folder'` and `baseUrlDirect=true` the returned file location is  `http://domain.com/folder/file.txt`.

globalCacheControl
- Description: The `Cache-Control` http header to set in the file request.
- Note: Optional. Default: `null`. Example: `public, max-age=86400` for 24 hrs caching. More info [here](http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.9.1).

It seems worth to include the interplay of these parameters with the `directAccess`.

Found some references here:
https://github.com/parse-community/parse-server-s3-adapter
https://github.com/parse-community/parse-server/issues/1857
https://github.com/parse-community/parse-server-s3-adapter/pull/13

Are the above parameter details understandable and correct?

**Comment by acinader** [comment]
would you be willing to open a pull request for this change?

**Comment by mtrezza** [comment]
PR merged
