### ISSUE TITLE
[Feature Request] Redis retry_strategy

### ISSUE THREAD

**Issue by dplewis** [parse-community/parse-server#5387]
**Is your feature request related to a problem? Please describe.**

If a redis server goes down the server will go down.

**Describe the solution you'd like**

Should auto connect based on number of attempts or timeout

**Additional context**

The redis node package already has this feature, here is an example taken from their docs.

```
var client = redis.createClient({
    retry_strategy: function (options) {
        if (options.error && options.error.code === 'ECONNREFUSED') {
            // End reconnecting on a specific error and flush all commands with
            // a individual error
            return new Error('The server refused the connection');
        }
        if (options.total_retry_time > 1000 * 60 * 60) {
            // End reconnecting after a specific timeout and flush all commands
            // with a individual error
            return new Error('Retry time exhausted');
        }
        if (options.attempt > 10) {
            // End reconnecting with built in error
            return undefined;
        }
        // reconnect after
        return Math.min(options.attempt * 100, 3000);
    }
});
```

**Comment by oleg-koval** [comment]
are you looking for smth like redis exponential backoff?

**Comment by georgesjamous** [comment]
@dplewis 
doesn't configuring Redis with retry_strategy achieve the expected result?

**Comment by dplewis** [comment]
@georgesjamous RedisAdapter yes, but not for LiveQuery. I submitted a PR to make this configurable. Also check your email.
