### ISSUE TITLE
Cost optimization for Parse Server on AWS

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-server#5388]
After moving from Heroku to AWS, the costs of running Parse Server have significantly increased (more than 3 fold).

**Heroku:** On average 4 dynos `STANDARD 2X`
**AWS:** On average 5 instances `t2.small` on Elastic Beanstalk with Application Load Balancer

In both cases
- ca. 150 requests / second handled
- files are stored on S3 with `directAccess=false`

AWS Cost Explorer shows that >50% of the costs come from `DataTransfer-Out-Bytes`.

![screen shot 2019-02-23 at 04 57 20](https://user-images.githubusercontent.com/5673677/53281543-8ae61780-372a-11e9-999f-8a226132d4bd.png)

The files on S3 are routed through parse server, i.e. the ELB and EC2 instances when requested by a client. Could it be possible that when a client request a file from parse server, the data somehow goes from S3 to the internet gateway and back to the EC3 instance (0.09$/GB) instead of directly to the EC2 instance (0$)?

On the other hand the Cost Explorer shows that the S3 bucket has only a minimal cost effect, >50% come from the ELB.

![rscreen shot 2019-02-23 at 04 57 01](https://user-images.githubusercontent.com/5673677/53281548-989b9d00-372a-11e9-9e87-f2163ac314e9.png)

I have no clue as to what is causing this cost difference - could it be a misconfiguration of Parse Sever on AWS?

**Comment by agwl-saurabh** [comment]
I am also facing same issue on AWS i used AWS for almost 1 yrs but i am moving to digitalocean . the problem with aws is they charge for bandwidth even for everything like hard disk etc also but digitalocean has fixed and now i am able to reduce my cost to 60% in comparison to AWS.

**Comment by mtrezza** [comment]
@agwl-saurabh What I don't understand is why the costs are significantly less on Heroku. How can PaaS be more expensive than IaaS when Heroku even runs on AWS. If they have some bandwidth discount they got a pretty good deal with AWS saving ~70% of costs.

**Comment by agwl-saurabh** [comment]
very simple answer to this when you use AWS. u actually start using lot of unwanted services which really add up the cost for e.g I was using parse on AWS elastic bean(by one click button on parse example) and when i was on free tire i was not paying for loadbalancer data transfer and lot more was on free and suddenly after my free tire my bill becomes almost 2.5 what i was paying on free tire. FYI i was using two large ec2 and one medium ec2 . even in one yrs my load on server decreased but cost increased :). 
so after lot of research and two months running on digitalocean i found it cheapest option. 
I already tried Google could also.  
without seeing your console i will not able to tell you exact issue. I will suggest take paid support from AWS and get there engineer on call and understand this it will not cost you more then 100$ for one time.. 

but on Heroku you use very limited services.

**Comment by mtrezza** [comment]
The higher costs for me come specifically from bandwidth:
- regional data transfer - in/out/between EC2 AZs or using elastic IPs or ELB
- first 10 TB / month data transfer out beyond the global free tier

Possible causes:
- Connection to mLab hosted mongodb runs through public IP
  - mLab offers to place a DB deployment in an AWS-VPC, so if the Elastic Beanstalk environment runs also in a VPC and both are peered, parse server should call the DB by its private IP.
- Cloud code calling parse server through public IP
  - Is it OK to use `https://localhost/parse` as `serverUrl` instead of a domain or IP?
- File requests from parse server to S3 (`directAccess=false`) are routed through the public IP
  - file adapter [composes the URL](https://github.com/parse-community/parse-server-s3-adapter/blob/874248d1ecfadc5ed9114f16bbffecbabbd23ad8/index.js#L141) with `https://bucketname.s3.amazonaws.com...`. When I `ssh` into an EC2 instance and do a `nslookup` it resolves this to a public IP.

**Comment by georgesjamous** [comment]
Using `directAccess=false` forces the server to load the file into memory on each request, thus increasing the instance's memory, CPU requirements, and bandwidth usage.

I highly recommend that you keep`directAccess=true`, you will need fewer instances and will offload a considerable amount of work to s3. Since S3 is designed to scale massively.

**Comment by mtrezza** [comment]
@georgesjamous Good point, I have now setup a CDN instead of allowing direct access to the S3 bucket, to keep the bucket private and reduce the bandwidth costs.

**Comment by mtrezza** [comment]
Costs are down considerable after:
- adding a CDN for static content
- make cloud code calls to the server call itself (localhost) instead of the load balancer
