### ISSUE TITLE
Parse server installation issue on digital digitalocean.

### ISSUE THREAD

**Issue by agwl-saurabh** [parse-community/parse-server#5389]
### Issue Description

I am facing two instalation issues. 
> npm WARN deprecated uws@10.148.1: New code is available at github.com/uNetworking/uWebSockets.js

and 

> make: Entering directory '/root/parse-server-example/node_modules/kerberos/build'
CXX(target) Release/obj.target/kerberos/lib/kerberos.o
In file included from ../lib/kerberos.cc:1:0:
../lib/kerberos.h:5:10: fatal error: gssapi/gssapi.h: No such file or directory
#include <gssapi/gssapi.h>

I have already checked the closed issue but did not able to find the solution. 

### Steps to reproduce

I am using "parse-server-example" from GitHub for this installation and trying to install parse server 3.1.3 

`npm install`

I have installed Parse Server based on below this [tutorial](https://www.digitalocean.com/community/tutorials/how-to-run-parse-server-on-ubuntu-14-04)

### Expected Results
Possibly remove uws as a dependancy since parse server falls back to ws anyway

### Actual Outcome
Got two warnings when running `npm install`.

### Environment Setup
* **Server**
  
  * parse-server version (Be specific! Don't say 'latest'.) : 3.1.3
  * Operating System:     Ubuntu NodeJS 8.10.0 on 18.04
  * Hardware:             2GB Memory/1vCPU/50GB hardDrive
  * Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Digital Ocean
* **Database**
  
  * MongoDB version: 4.0.2
  * Storage engine:  default
  * Hardware:        4GB Memory/2vCPU/50GB hardDrive
  * Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): Digital Ocean

### Logs/Trace
I am not able to fix this issue I am using "parse-server-example" from GitHub and I have seen the `package.json` and not able to understand what needs to change in dependencies for version update below is my `package.json` file i have updated the parse-server variable to latest.
```json
"dependencies": {
    "express": "~4.11.x",
    "kerberos": "~0.0.x",
    "parse": "~1.8.0",
    "parse-server": "3.1.3"
}
```

**Comment by AlexEKoren** [comment]
Running into the same issue on Heroku currently.

` [4/4] Building fresh packages...
       error /tmp/build_2f6d0c147aedbc8a82a0c46b150b2df5/node_modules/kerberos: Command failed.
       Exit code: 1
       Command: prebuild-install || node-gyp rebuild
       Arguments: 
       Directory: /tmp/build_2f6d0c147aedbc8a82a0c46b150b2df5/node_modules/kerberos
       Output:
       make: Entering directory '/tmp/build_2f6d0c147aedbc8a82a0c46b150b2df5/node_modules/kerberos/build'
         CXX(target) Release/obj.target/kerberos/src/kerberos.o
       In file included from ../src/kerberos.h:5:0,
                        from ../src/kerberos.cc:1:
       ../src/kerberos_common.h: In function ‘std::__cxx11::string StringOptionValue(v8::Local<v8::Object>, const char*)’:
       ../src/kerberos_common.h:29:50: error: no matching function for call to ‘v8::Object::Has(v8::Local<v8::String>&)’
            return !options.IsEmpty() && options->Has(key) && options->Get(key)->IsString()
                                                         ^
       In file included from /app/.node-gyp/12.2.0/include/node/node.h:63:0,
                        from ../../nan/nan.h:53,
                        from ../src/kerberos.h:4,
                        from ../src/kerberos.cc:1:
       /app/.node-gyp/12.2.0/include/node/v8.h:3449:37: note: candidate: v8::Maybe<bool> v8::Object::Has(v8::Local<v8::Context>, v8::Local<v8::Value>)
          V8_WARN_UNUSED_RESULT Maybe<bool> Has(Local<Context> context,
                                            ^~~
       /app/.node-gyp/12.2.0/include/node/v8.h:3449:37: note:   candidate expects 2 arguments, 1 provided
       /app/.node-gyp/12.2.0/include/node/v8.h:3455:37: note: candidate: v8::Maybe<bool> v8::Object::Has(v8::Local<v8::Context>, uint32_t)
          V8_WARN_UNUSED_RESULT Maybe<bool> Has(Local<Context> context, uint32_t index);
                                            ^~~
       /app/.node-gyp/12.2.0/include/node/v8.h:3455:37: note:   candidate expects 2 arguments, 1 provided
       In file included from ../src/kerberos.h:5:0,
                        from ../src/kerberos.cc:1:
       ../src/kerberos_common.h:29:71: warning: ‘v8::Local<v8::Value> v8::Object::Get(v8::Local<v8::Value>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
            return !options.IsEmpty() && options->Has(key) && options->Get(key)->IsString()
                                                                              ^
       In file included from /app/.node-gyp/12.2.0/include/node/v8-internal.h:14:0,
                        from /app/.node-gyp/12.2.0/include/node/v8.h:25,
                        from /app/.node-gyp/12.2.0/include/node/node.h:63,
                        from ../../nan/nan.h:53,
                        from ../src/kerberos.h:4,
                        from ../src/kerberos.cc:1:
       /app/.node-gyp/12.2.0/include/node/v8.h:3412:55: note: declared here
          V8_DEPRECATE_SOON("Use maybe version", Local<Value> Get(Local<Value> key));
                                                              ^
       /app/.node-gyp/12.2.0/include/node/v8config.h:322:3: note: in definition of macro ‘V8_DEPRECATE_SOON’
          declarator __attribute__((deprecated(message)))
          ^~~~~~~~~~
       In file included from ../src/kerberos.h:5:0,
                        from ../src/kerberos.cc:1:
       ../src/kerberos_common.h:30:64: warning: ‘v8::Local<v8::Value> v8::Object::Get(v8::Local<v8::Value>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
                       ? std::string(*(Nan::Utf8String(options->Get(key))))
                                                                       ^
       In file included from /app/.node-gyp/12.2.0/include/node/v8-internal.h:14:0,
                        from /app/.node-gyp/12.2.0/include/node/v8.h:25,
                        from /app/.node-gyp/12.2.0/include/node/node.h:63,
                        from ../../nan/nan.h:53,
                        from ../src/kerberos.h:4,
                        from ../src/kerberos.cc:1:
       /app/.node-gyp/12.2.0/include/node/v8.h:3412:55: note: declared here
          V8_DEPRECATE_SOON("Use maybe version", Local<Value> Get(Local<Value> key));
                                                              ^
       /app/.node-gyp/12.2.0/include/node/v8config.h:322:3: note: in definition of macro ‘V8_DEPRECATE_SOON’
          declarator __attribute__((deprecated(message)))
          ^~~~~~~~~~
       In file included from ../src/kerberos.h:5:0,
                        from ../src/kerberos.cc:1:
       ../src/kerberos_common.h: In function ‘uint32_t UInt32OptionValue(v8::Local<v8::Object>, const char*, uint32_t)’:
       ../src/kerberos_common.h:39:50: error: no matching function for call to ‘v8::Object::Has(v8::Local<v8::String>&)’
            return !options.IsEmpty() && options->Has(key) && options->Get(key)->IsNumber()
                                                         ^
       In file included from /app/.node-gyp/12.2.0/include/node/node.h:63:0,
                        from ../../nan/nan.h:53,
                        from ../src/kerberos.h:4,
                        from ../src/kerberos.cc:1:
       /app/.node-gyp/12.2.0/include/node/v8.h:3449:37: note: candidate: v8::Maybe<bool> v8::Object::Has(v8::Local<v8::Context>, v8::Local<v8::Value>)
          V8_WARN_UNUSED_RESULT Maybe<bool> Has(Local<Context> context,
                                            ^~~
       /app/.node-gyp/12.2.0/include/node/v8.h:3449:37: note:   candidate expects 2 arguments, 1 provided
       /app/.node-gyp/12.2.0/include/node/v8.h:3455:37: note: candidate: v8::Maybe<bool> v8::Object::Has(v8::Local<v8::Context>, uint32_t)
          V8_WARN_UNUSED_RESULT Maybe<bool> Has(Local<Context> context, uint32_t index);
                                            ^~~
       /app/.node-gyp/12.2.0/include/node/v8.h:3455:37: note:   candidate expects 2 arguments, 1 provided
       In file included from ../src/kerberos.h:5:0,
                        from ../src/kerberos.cc:1:
       ../src/kerberos_common.h:39:71: warning: ‘v8::Local<v8::Value> v8::Object::Get(v8::Local<v8::Value>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
            return !options.IsEmpty() && options->Has(key) && options->Get(key)->IsNumber()
                                                                              ^
       In file included from /app/.node-gyp/12.2.0/include/node/v8-internal.h:14:0,
                        from /app/.node-gyp/12.2.0/include/node/v8.h:25,
                        from /app/.node-gyp/12.2.0/include/node/node.h:63,
                        from ../../nan/nan.h:53,
                        from ../src/kerberos.h:4,
                        from ../src/kerberos.cc:1:
       /app/.node-gyp/12.2.0/include/node/v8.h:3412:55: note: declared here
          V8_DEPRECATE_SOON("Use maybe version", Local<Value> Get(Local<Value> key));
                                                              ^
       /app/.node-gyp/12.2.0/include/node/v8config.h:322:3: note: in definition of macro ‘V8_DEPRECATE_SOON’
          declarator __attribute__((deprecated(message)))
          ^~~~~~~~~~
       In file included from ../src/kerberos.h:5:0,
                        from ../src/kerberos.cc:1:
       ../src/kerberos_common.h:40:34: warning: ‘v8::Local<v8::Value> v8::Object::Get(v8::Local<v8::Value>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
                       ? options->Get(key)->Uint32Value()
                                         ^
       In file included from /app/.node-gyp/12.2.0/include/node/v8-internal.h:14:0,
                        from /app/.node-gyp/12.2.0/include/node/v8.h:25,
                        from /app/.node-gyp/12.2.0/include/node/node.h:63,
                        from ../../nan/nan.h:53,
                        from ../src/kerberos.h:4,
                        from ../src/kerberos.cc:1:
       /app/.node-gyp/12.2.0/include/node/v8.h:3412:55: note: declared here
          V8_DEPRECATE_SOON("Use maybe version", Local<Value> Get(Local<Value> key));
                                                              ^
       /app/.node-gyp/12.2.0/include/node/v8config.h:322:3: note: in definition of macro ‘V8_DEPRECATE_SOON’
          declarator __attribute__((deprecated(message)))
          ^~~~~~~~~~
       In file included from ../src/kerberos.h:5:0,
                        from ../src/kerberos.cc:1:
       ../src/kerberos_common.h:40:49: error: no matching function for call to ‘v8::Value::Uint32Value()’
                       ? options->Get(key)->Uint32Value()
                                                        ^
       In file included from /app/.node-gyp/12.2.0/include/node/node.h:63:0,
                        from ../../nan/nan.h:53,
                        from ../src/kerberos.h:4,
                        from ../src/kerberos.cc:1:
       /app/.node-gyp/12.2.0/include/node/v8.h:2567:41: note: candidate: v8::Maybe<unsigned int> v8::Value::Uint32Value(v8::Local<v8::Context>) const
          V8_WARN_UNUSED_RESULT Maybe<uint32_t> Uint32Value(
                                                ^~~~~~~~~~~
       /app/.node-gyp/12.2.0/include/node/v8.h:2567:41: note:   candidate expects 1 argument, 0 provided
       kerberos.target.mk:110: recipe for target 'Release/obj.target/kerberos/src/kerberos.o' failed
       make: Leaving directory '/tmp/build_2f6d0c147aedbc8a82a0c46b150b2df5/node_modules/kerberos/build'
       make: *** [Release/obj.target/kerberos/src/kerberos.o] Error 1
       gyp ERR! build error 
       gyp ERR! stack Error: `make` failed with exit code: 2
       gyp ERR! stack     at ChildProcess.onExit (/tmp/build_2f6d0c147aedbc8a82a0c46b150b2df5/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
       gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
       gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:257:12)
       gyp ERR! System Linux 4.4.0-1042-aws
       gyp ERR! command "/tmp/build_2f6d0c147aedbc8a82a0c46b150b2df5/.heroku/node/bin/node" "/tmp/build_2f6d0c147aedbc8a82a0c46b150b2df5/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
       gyp ERR! cwd /tmp/build_2f6d0c147aedbc8a82a0c46b150b2df5/node_modules/kerberos
       gyp ERR! node -v v12.2.0
       gyp ERR! node-gyp -v v3.8.0
       gyp ERR! not ok
       info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       Some possible problems:
       
       - Dangerous semver range (>) in engines.node
         https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version
       
       Love,
       Heroku
       
 !     Push rejected, failed to compile Node.js app.
 !     Push failed`
