### ISSUE TITLE
Maintenance Mode?

### ISSUE THREAD

**Issue by mikecann** [parse-community/parse-server#5392]
Hi Guys,

I am wondering if there is a way to put ParseServer into "maintainance mode"? To prevent the outside world from accessing the server but allow "masterKey" to access and perform queries and changes. 

This would make my "migrations" much safer when the server starts up.

Cheers,

**Comment by suathh** [comment]
I am using parse-server with Heroku there is feature in Heroku for that.

> If you need to temporarily disable access to your Heroku app (for example, to perform a large migration), you can enable Heroku’s built-in maintenance mode. While in maintenance mode, your app serves a static maintenance page to all visitors.

https://devcenter.heroku.com/articles/maintenance-mode

If you are not using Heroku, since parse-server working with express.js you can put your express.js to maintenance mode.

But in both way you can not access your server via HTTP either.

**Comment by mikecann** [comment]
@suathh Cool! I didnt know about about Maintenance Mode on heroku server. My backend is indeed running on Heroku. 

I just tested it and unfortunately although it does block access to outside users it also blocks access to my migration code that needs to perform finds, updates, deletes etc.

I think what I need is something in Parse Server which says, "block all traffic that doesnt have the master key, or doesnt come from this role", the role part is optional and not strictly necessary but might be one way of thinking about it.

**Comment by acinader** [comment]
Offhand, I think this would be more easily and better done at the network level.  So in your case, I'd think you'd want to ask Heroku.

There's nothing in parse-server that I am aware of that would help with this and it would need to be built.

**Comment by mikecann** [comment]
@acinader if in my maintenance code (that runs on the server) I use Parse.Query or Parse.Object functions, wont that go out to the network and back in again?

**Comment by acinader** [comment]
If I needed to do what you're trying to do, I'd see if I could do it with networking rules that block all but a whitelist while in maintenance mode.  and then allow all traffic when not in maint mode

the master key approach is reasonable too if you want to give it a shot

**Comment by georgesjamous** [comment]
In my opinion, a network level approach should be preferred over using `masterKey`.
That way, you can perform operations using an assumed role (sessionToken) rather than always using the `masterKey`.

**Comment by mikecann** [comment]
@acinader @georgesjamous okay thanks guys. I guess because im hosting parse server inside of express I can do some IP based filtering in the /parse handler as suggested. 

Thanks for your tips!
