### ISSUE TITLE
LiveQueries and Roles in v3.1.x

### ISSUE THREAD

**Issue by pivanov** [parse-community/parse-server#5393]
### Issue Description

If we use ACL Roles with Live Queries there is an issue where the records with ACL (latest created Role) doesn't work and after logout or restart of the server everything looks OK till next created Role then the issue popups again.

I found that in v3.0.0 everything works fine till commit [Adds support for CLP in Live query (no support for roles yet)](https://github.com/parse-community/parse-server/pull/4387/commits/0f7b52367c4212bb5a5b61b1677b1a6290639d6d)

### Steps to reproduce
Here is a [simple HTML test page](https://gist.github.com/pivanov/c2237d3d881a2175ff20dfd8b1cf4def) where you can reproduce the issue with few clicks.
 
Here is the [screen capture](https://my.pcloud.com/publink/show?code=XZo8bd7ZkhGpkIbJYEVzzG9FAXBWAfIvMpTV) with the issue in action.

**Comment by ridem** [comment]
I've noticed the issue as well, which comes from the addition of `authCache` in `ParseLiveQueryServer`: https://github.com/parse-community/parse-server/blob/3.1.3/src/LiveQuery/ParseLiveQueryServer.js#L56

The `authCache` will remember the user ID and its roles based on a session token. So the only two ways to get fresh data (apart from restarting your server) are:
- Getting a new session token (which is why it works when you log out / log in)
- Waiting 1h

This provides a much better performance, but we might want to provide a way to configure this cache. `lru-cache` is imported directly and its configuration is hardcoded.

**Comment by ridem** [comment]
@flovilmart I can make a PR if you point me to the approach you find most sensible.
Here are some things that could be done from what I understand:
- Don't use lru-cache directly in ParseLiveQueryServer but use the abstraction, allow for customizing max and maxAge. (This effectively lets people disable it in case that's what's wanted)
- [Maybe not a good idea] Support for role changes in ParseLiveQueryServer. I guess there you be some "master subscriber" listening for role changes of active client users. That process would delete outdated cache entries when role changes

**Comment by flovilmart** [comment]
@ridem  I don’t participate in this project anymore. Check with @dplewis or @acinader 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ridem** [comment]
@dplewis @acinader are you interested in a PR covering this issue?

**Comment by dplewis** [comment]
I’m not really an expert in this area. If you can open a PR with failing cases that would be great.

There is a separate issue opened.

https://github.com/parse-community/parse-server/issues/5839

**Comment by mullwaden** [comment]
We are having an issue with this and @ridem has made a perfect analysis of what is wrong. Would be fun to make a PR on how to fix it but I am not sure how, I believe it could be quite tricky.

Why it is important to fix:
- When adding a user to a role it might take up to an hour before the cache is reset and live queries work again
- when removing a user from a role she might have access to data which she should not have access to which is a bit of a security issue

I made a small workaround it is not optimal but as long as we have the liveQueryServer and the parseServer on the same server it will work:
- create the server as usual ``const liveQueryServer = ParseServer.createLiveQueryServer(httpServer)``
- In _Role add the following to beforeSave ``liveQueryServer.authCache.reset()``

This clears the cache as soon as a role is changed. It could easily be made smarter by fetching the users that belong to that role and only removing or editing those rows in the authCache

**Comment by dblythy** [comment]
Closing via #8026
