### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by i--storm** [parse-community/parse-server#5403]
### Issue Description

Parse installation fails with errors

### Steps to reproduce

run under debian
```
sh <(curl -fsSL https://raw.githubusercontent.com/parse-community/parse-server/master/bootstrap.sh)
```
 
### Expected Results

Installation of Parse Server

### Actual Outcome

Error messages in dialogs
```
Setting up parse-server in parse-projectname
\xE2\x9C\x93 Created ****
/dev/fd/63: 124: /dev/fd/63: [[: not found
Enter your Application Name: ****
Enter your Application Id (leave empty to generate):
/dev/fd/63: 133: /dev/fd/63: [[: not found
Enter your Master Key (leave empty to generate):
/dev/fd/63: 138: /dev/fd/63: [[: not found
Enter your mongodbURI (mongodb://127.0.0.1:27017/parse):
/dev/fd/63: 143: /dev/fd/63: [[: not found
```
installation failure
```
/dev/fd/63: 210: /dev/fd/63: Syntax error: end of file unexpected (expecting ")")
```

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : N/A
  - Operating System:     Debian Sid
  - Hardware:             
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): localhost

### Possible issue solving

replace **#!/bin/sh** to **#!/bin/bash** at first line of **bootstrap.sh** file
because **sh** has no commands used in file

**Comment by sarunyu** [comment]
yes, it's work for me.

**Comment by theRippedPug** [comment]
Had same problem.
Just write a random app-id and key in config.json manually and you're good to go

**Comment by StianOvrevage** [comment]
Just got the same problem.

Worked better when using `bash` as shell instead of `sh`:

```
bash <(curl -fsSL https://raw.githubusercontent.com/parse-community/parse-server/master/bootstrap.sh)
```

**Comment by bing-deng** [comment]
> ```
> bash <(curl -fsSL https://raw.githubusercontent.com/parse-community/parse-server/master/bootstrap.sh)
> ```

nice ,it works
