### ISSUE TITLE
Geo queries cause internal server errors

### ISSUE THREAD

**Issue by Erik-Stevens** [parse-community/parse-server#5409]
### Issue Description
Geo queries cause internal server error: type "geometry" does not exist. See log for more details. Note that I'm using a Psql database, not MongoDB. I get the same error if I try query.withinMiles(), query.withinKilometers(), or query.near().

### Steps to reproduce

Class Location contains key "latlon" that is of type GeoPoint.
![image](https://user-images.githubusercontent.com/27454024/53689255-46e0ad00-3cfe-11e9-9c3c-b589f120cd7e.png)

client-side JS code:
	var coords = {
		latitude: 59.045,
		longitude: -135.554
	};
	loc = new Parse.GeoPoint(coords);
	const LO = Parse.Object.extend("Location");
	const query = new Parse.Query(LO);
	query.withinMiles("latlon", loc, 5);
	const results = await query.find();
 
### Expected Results

Should return 5 Location objects (all are within 5 miles of coords.)

### Actual Outcome

5 internal server errors! One for each location that should be returned. 

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 3.1.1
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Heroku

- **Database**
Heroku PostgresSQL

### Logs/Trace

![image](https://user-images.githubusercontent.com/27454024/53689237-b904c200-3cfd-11e9-86f3-0ae48726aade.png)

**Comment by mosid** [comment]
Is Postgis extension enabled on your database?

**Comment by stck** [comment]
Hi, it's may be not related to question itself, but why don't you use geohash instead of geopoint? It's simple to make queries like yours (`query.withinMiles("latlon", loc, 5);`)

**Comment by Erik-Stevens** [comment]
> Is Postgis extension enabled on your database?

Will check on this. Sorry for the delay I've had to move to another project for a few weeks but will be getting back to this this week.

I will also look into using geohash. Wasn't aware of that option. Either way geo queries with Geopoints should work.

**Comment by dplewis** [comment]
Ensure you have all postgres extensions installed. 

https://github.com/parse-community/parse-server/blob/master/.travis.yml#L46

**Comment by Erik-Stevens** [comment]
Thanks for your help. The Postgis extension was not installed and that was the problem.
