### ISSUE TITLE
Add possibility to use async requests on choose password

### ISSUE THREAD

**Issue by vince1995** [parse-community/parse-server#5418]
**Is your feature request related to a problem? Please describe.**
Because JavaScript must be available in `choose_password` the form which redirects to another page seems needless.

**Describe the solution you'd like**
To uphold backwards compatibility add a simple flag `shouldNotRedirect` to the body of the POST request and just respond with the status code 200 instead of 302.

**Describe alternatives you've considered**
I'm using a custom page and proxying the request to keep a SPA instead of getting an unneeded redirect (which causes a full refresh of my website).

**Comment by dplewis** [comment]
@vince1995 A PR https://github.com/parse-community/parse-server/pull/5332 was submitted. Would that solve your issue?

**Comment by vince1995** [comment]
Oh wow, yeah, that's exactly what I imagined. Sorry, searched in issues for that feature but not in PRs. You can close.
