### ISSUE TITLE
Can't upload/download files (URL string parser is deprecated)

### ISSUE THREAD

**Issue by 1987cr** [parse-community/parse-server#5425]
# Before opening the issue please ensure that you have:

- [X] [Read the migration guide](https://github.com/parse-community/parse-server/blob/master/3.0.0.md) to parse-server 3.0.0
- [X] [Read the migration guide](https://github.com/parse-community/Parse-SDK-JS/blob/master/2.0.0.md) to Parse SDK JS 2.0.0

### Issue Description

After doing the migration can't upload/download files.

### Steps to reproduce

- Create a new Class with a File column (using parse-dashboard to simplify things)
- Add a new row and upload a file, nothing will happen.

### Expected Results

Upload and Download files without errors.

### Actual Outcome

When trying to retrieve a file stored in gridFS, accessing the URL gives a "File not found." and the console shows the following warning:

```
(node:1972) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
```

Same message is displayed when trying to upload files.

Seems like the `{ useNewUrlParser: true }` option is missing on the `GridFSBucketAdapter.js`  file (probably is needed on the `GridStoreAdapter.js` file too).

I stopped getting the error after (locally) changing this:

```
constructor(mongoDatabaseURI = _defaults.default.DefaultMongoURI) {
    super();
    this._databaseURI = mongoDatabaseURI;
  }

  _connect() {
    if (!this._connectionPromise) {
      this._connectionPromise = _mongodb.MongoClient.connect(this._databaseURI).then(client => client.db(client.s.options.dbName));
    }

    return this._connectionPromise;
  }
```

to this:
```
constructor(mongoDatabaseURI = defaults.DefaultMongoURI, mongoOptions = {}) {
    super();
    this._databaseURI = mongoDatabaseURI;
    this._mongoOptions = mongoOptions;
    this._mongoOptions.useNewUrlParser = true; 
  }

  _connect() {
    if (!this._connectionPromise) {
      this._connectionPromise = MongoClient.connect(
        this._databaseURI,
        this._mongoOptions
      ).then(client => client.db(client.s.options.dbName));
    }
    return this._connectionPromise;
  }
```

Can submit a PR with that change if needed.

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 3.1.3
  - Operating System:
  - Hardware:
  - Localhost or remote server: Azure

- **Database**
  - MongoDB version: 3.2.0
  - Storage engine: 
  - Hardware: 
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): Azure Cosmos DB

**Comment by dplewis** [comment]
Closing via https://github.com/parse-community/parse-server/pull/5025

Please update to the latest version of Parse Server.

**Comment by danielmartinprieto** [comment]
Hi @dplewis, we're still experiencing the issue. Given the date of the PR you mentioned, it seems that the warnings are not the same. In case we are wrong, could you help us finding the problem? We're creating a new issue with more info as we can't reopen this one, but let us know if you want to reopen this one and we close the new one and bring that info here.
