### ISSUE TITLE
Request: In-Memory Storage adapter for mocking unit tests

### ISSUE THREAD

**Issue by mrmarcsmith** [parse-community/parse-server#5437]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

I'm bummed there isn't a "baked in" method for efficient unit testing without mongo.

**Describe the solution you'd like**

I'm imagining an "In-Memory" storage adapter that contains ALL of the functionality of parse without any of the unit-testing "baggage" of mongo. For example, I could "save" an object, then query for the object but the "object" is stored in RAM instead of Mongo. 

**Describe alternatives you've considered**

Our current options for testing are:
1. test the javascript function manually -> doesn't mock Parse objects or any other "more complex" parse server functionality
example from @flovilmart 
```
// lib/jobs.js

module.exports = {
   job_1: function() {},
   job_2: function() {} 
}
...

// main.js

var jobs = require('lib/jobs');
Object.keys(jobs).forEach(function(jobName) {
   Parse.Cloud.job(jobName, jobs[jobName]);
});
```

2. spin up parse server with mongo-runner -> requires additional resources and slows tests down.

3. I'm open to additional suggestions if anyone has any!

**Additional context**

**Comment by acinader** [comment]
I've used and contributed to some 'fake mongos' for unit testing, but I've since switched over to using mongodb-runner instead as it is fast and easy.
