### ISSUE TITLE
[Feature Request] Update array at index

### ISSUE THREAD

**Issue by dplewis** [parse-community/parse-server#5440]
**Is your feature request related to a problem? Please describe.**

```
const list = object.get('list');
list[0] = "insert me";
object.set('list', list);
await object.save();

This will send the whole array to the server, not just the index that you changed
```

**Describe the solution you'd like**

object.add('list', value, index);

**Additional context**

Mongo and Postgres supports this
Mongo has [$ positional operator](https://docs.mongodb.com/manual/reference/operator/update/positional/?_ga=1.12567092.1864968360.1429722620#up._S_)
Postgres has [element[index]](https://www.postgresql.org/docs/9.5/arrays.html)

**Comment by acinader** [comment]
I think the arguments would be: `object.add('list', value, index);`

**Comment by omairvaiyani** [comment]
I imagine this will need co-ordination between the server and client-side libraries. Has anyone taken up the server-side work for this? If not I'm happy to get that side done.

**Comment by dplewis** [comment]
@omairvaiyani Feel free to open a PR. The server-side work hasn't been done yet.

Thanks for getting started on this!

**Comment by omairvaiyani** [comment]
Sounds good! FYI this [mongodb article](https://docs.mongodb.com/manual/reference/operator/update/push/) is more closer to the `add` operator since it will only append items to the add, rather than replacing existing items.

I'm not at all familiar with postgres so my PR might be a little lacking

**Comment by dplewis** [comment]
If there is enough support for this feature we will reopen.
