### ISSUE TITLE
Error 141: TypeError: res.success is not a function

### ISSUE THREAD

**Issue by BillyJohn3** [parse-community/parse-server#5447]
Have cloud code that has worked fine before but is now throwing issues. 
Some of my cloud functions return res.error or res.success so that I can let the caller know everything was fine part way through the function and then continue working on the data in the cloud function.

However the only accepted code is now "return" or "throw" both of which exit the function. 

the function is: 
Parse.Cloud.define('hello', function(req, res) {
  res.success('Hi');
});

the error log is: 

 lym > error: Failed running cloud function hello for user undefined with:                                                                │
│                                                          ││ lym >   Input: {}                                                                                                                        │
│                                                          ││ lym >   Error: {"message":"res.error is not a function","code":141} functionName=hello, message=res.error is not a function,   │
│                                                          ││ code=141, , user=undefined                                                                                                               │
│                                                          ││ lym > error: res.error is not a function message=response.error is not a function, stack=Error: res.error is not a function    │
│                                                          ││ lym >     at error (/root/parse-server-example/node_modules/parse-server/lib/Routers/FunctionsRouter.js:121:16)                          │
│                                                          ││ lym >     at processTicksAndRejections (internal/process/next_tick.js:81:5), code=141 

Any ideas how I can deal with this?

**Comment by acinader** [comment]
Hi @BillyJohn3,

If you try and fill out the issue template, you may figure out what your problem is ;)

Likely, you have inadvertently upgraded to JS SDK 2.0 and/or Parse Server 3

You can read about it here:

https://github.com/parse-community/parse-server/blob/master/3.0.0.md
