### ISSUE TITLE
Setting up appsecret_proof for Facebook calls

### ISSUE THREAD

**Issue by ssgsgugel** [parse-community/parse-server#5448]
According to Facebook, stepping up our API from 2.8 to the latest will require the use of the appsecret_proof in all user related calls. I've seen how to do this for Javascript in general, but how is it handled for the Parse server configuration?

**Comment by dplewis** [comment]
This isn't currently implemented. If you would like to submit a PR, you can look into the following files:

[Facebook Auth](https://github.com/parse-community/parse-server/blob/master/src/Adapters/Auth/facebook.js)
[3rd Party Guide](http://docs.parseplatform.org/parse-server/guide/#oauth-and-3rd-party-authentication)

**Comment by dplewis** [comment]
I open a PR for this feature.

I don't think all calls are required to have appsecret. You can set it required in your advance settings.

https://developers.facebook.com/docs/graph-api/securing-requests/
