### ISSUE TITLE
How to run with configure file?

### ISSUE THREAD

**Issue by zhanswift** [parse-community/parse-server#5455]
Before I used [parse-server-example](https://github.com/parse-community/parse-server-example)
Now I installed just parse-server.

And in parse-server-example we have **index.js** file to write configure parse server and then run it.

How to do same file in just parse-server?

in **parse-server-example** I can do like this:

```
var api = new ParseServer({
  databaseURI: 'mongodb://....',
  cloud: process.env.CLOUD_CODE_MAIN || __dirname + '/cloud/main.js',
  appId: process.env.APP_ID || '***',
  masterKey: process.env.MASTER_KEY || '***',
  serverURL: process.env.SERVER_URL || 'http://localhost:1337/parse'
});
```

**Comment by Tom-Fox1** [comment]
We reserve GitHub issues to bug reports and feature requests. See our announcement about channels of communication [here](https://community.parseplatform.org/t/where-should-you-ask-questions/167).

It also seems you have already posted this on the community forum [here](https://community.parseplatform.org/t/how-to-run-parse-server-with-own-configure/187/2).

I appreciate that sometimes it can be frustrating to be waiting for a solution for a problem that is holding you back, we’ve all been there. However, we are all volunteers here so we do ask that you follow our guidelines as much as possible to prevent duplicates and make best use of maintainer time.
