### ISSUE TITLE
Inaccurate Documentation for Object save method's params

### ISSUE THREAD

**Issue by pocketcolin** [parse-community/parse-server#5456]
**The issue**
The documentation for the params required for [Object's save method](http://parseplatform.org/Parse-SDK-JS/api/2.2.1/Parse.Object.html#save) describes 1 param (`options`), but you cannot actually pass just options as an object to the save method. The correct use of the save method is described with examples in the documentation, but the additional 2 params are not documented.

**Solution**
As the save method does accept 3 arguments (in the code as `value: function (arg1, arg2, arg3) {`), these params need to be added to the documentation and not just mentioned in the examples.

**Comment by acinader** [comment]
right you are!  in fact, if you pass `{ useMasterKey: true }` as the first argument, you'll a) not use the master key and b) end up with a column called `useMasterKey` in your class (I man someone told me that, I'm not dumb enough to have tried it myself ;))

Those docs are generated from the JS-SDK source code.  You can find the offending bit right here: https://github.com/parse-community/Parse-SDK-JS/blob/781026c72b3ee597c77f274b941127797aa36d22/src/ParseObject.js#L1078-L1109.

Would you be willing to take a stab at fixing and opening a Pull Request?

**Comment by pocketcolin** [comment]
[Done](https://github.com/parse-community/Parse-SDK-JS/pull/777)!

**Comment by acinader** [comment]
fixed by https://github.com/parse-community/Parse-SDK-JS/pull/777
