### ISSUE TITLE
about verify a signature from client

### ISSUE THREAD

**Issue by luojieerr** [parse-community/parse-server#5459]
Hi,I want to verify the signature through Parse Server, send an encrypted signature from the client, verify it on the server, and return error to all requests if the signature is invalid. Is there a more efficient way to do this than using Triggers?

thank you!

**Comment by Tom-Fox1** [comment]
Hi 👋. Could you please post this over on our [community forum](https://community.parseplatform.org/).

We are trying to keep GitHub issues reserved for bug reports & feature requests - see announcement about our channels of communication [here](https://community.parseplatform.org/t/where-should-you-ask-questions/167) or see the section on help and communication on our website [here](https://parseplatform.org/).

**Comment by yxw21** [comment]
Hi @rs5173 
Have you solved the problem yet?
