### ISSUE TITLE
Master tests failing.  Need better notification

### ISSUE THREAD

**Issue by acinader** [parse-community/parse-server#5500]
tests failing since https://travis-ci.org/parse-community/parse-server/builds/515639414

1.  Investigate and fix.
2. Check to understand how to get 'higher priority' notification when repos in parse-community are failing beyond some certain threshold.

**Comment by Tom-Fox1** [comment]
Perhaps [Travis Buddy](https://www.travisbuddy.com) could help with 2.

It comments on PRs if the tests are failing and shows the relevant part of the log - but I'm not sure whether you can set it so it only comments if over a certain number of tests fail.

**Comment by dplewis** [comment]
@vitaly-t I remember you posted something about mongo url strings https://github.com/parse-community/parse-server/pull/986#issuecomment-475936749

You want to submit a PR?

**Comment by vitaly-t** [comment]
@dplewis I have no practical knowledge about parse-server, i.e. I only helped with the database layer for PostgreSQL, but I never used the library myself.

Given just how completely generic `connection-string` is, perhaps it is better that someone well familiar with parser-server does it?

**Comment by acinader** [comment]
@stage88 and I are on the tests. It has nothing to do with the mongo adapter, it’s how jasmine handles spies has changed subtly in a way that broke some tests.  

This case will be solved shortly.  I’m more concerned about notifications that prevent this from going unnoticed.  I’ll have better internet soon.

**Comment by dplewis** [comment]
@acinader The issue is how unhandled promises are no longer warnings.

**Comment by dplewis** [comment]
I edited my last comment. We shouldn't run into this issue anymore. As unhandled promises will make tests fail

**Comment by acinader** [comment]
@dplewis I think that's a legitimate add to the mongo adapter connect method, but it does not solve the failing test.  I'm still trying to work out what's going on.

**Comment by acinader** [comment]
actually @dplewis I don't see where your change could be introduced.

still trying to work it out :(

**Comment by acinader** [comment]
for those of you playing along at home, I can confirm that the unhandled rejection is occurring during the initialization of ParseServer and not during the rest post to create a new object.

**Comment by davimacedo** [comment]
@acinader I think we can close this one, right?

**Comment by davimacedo** [comment]
Or do we still need to lead with number 2?

**Comment by acinader** [comment]
yes, I think we can close.  the issue with #2 is just for me to figure out i stopped getting notifications on failure.
