### ISSUE TITLE
Parse Server w/Mongo Atlas XMLHttpRequest failed error

### ISSUE THREAD

**Issue by gigswift** [parse-community/parse-server#5501]
I'm using Parse Server 3.2.3, Parse Javascript SDK 2.3.2. with a connection to Mongo Atlas Node.js driver 3.0

When I try to run a basic server side query I get the following error message:
> XMLHttpRequest failed: {"UNSENT":0,"OPENED":1,"HEADERS_RECEIVED":2,"LOADING":3,"DONE":4,"readyState":4,"responseText":"","responseXML":"","status":410,"statusText":null,"withCredentials":false}

My app.js:

```javascript
'use strict';
require('dotenv').config();
var express = require('express');
var path = require('path');
var cookieParser = require('cookie-parser');
var logger = require('morgan');
var helmet = require('helmet');
var ParseServer = require('parse-server').ParseServer;
var S3Adapter = require('parse-server-s3-adapter');
var cluster = require('cluster');
var os = require('os');
var debug = require('debug')('name-of-module:server');
var http = require('http');

if(cluster.isMaster) {
  var numWorkers = os.cpus().length;
  console.log('Master cluster setting up ' + numWorkers + ' workers...');

  for(var i = 0; i < numWorkers; i++) {
      cluster.fork();
  }

  cluster.on('online', function(worker) {
      console.log('Worker ' + worker.process.pid + ' is online');
  });

  cluster.on('exit', function(worker, code, signal) {
      console.log('Worker ' + worker.process.pid + ' died with code: ' + code + ', and signal: ' + signal);
      console.log('Starting a new worker');
      cluster.fork();
  });
} else {
  var app = express();
  var api = new ParseServer({
    databaseURI: 'mongodb+srv://name:'+process.env.MONGO_PASS+'@abc-pgid7.mongodb.net/test?retryWrites=true',
    appId: process.env.PARSE_SERVER_APPLICATION_ID,
    masterKey: process.env.PARSE_SERVER_MASTER_KEY,
    port: 3000,
    serverURL: 'http://localhost:3000/parse/',
    appName: "somethingNew",
    emailAdapter: {
      module: '@parse/simple-mailgun-adapter',
      options: {
        // The address that your emails come from
        fromAddress: 'info@com.me',
        // Your domain from mailgun.com
        domain: 'mg.sunflower.com',
        // Your API key from mailgun.com
        apiKey: 'some-key'
      }
    },
    allowClientClassCreation: false,
    revokeSessionOnPasswordReset: true,
    enableAnonymousUsers: false,
  });

  app.use(helmet());
  app.all('*', function(req, res, next) {
    res.set({ // since there is no res.header class in Parse, we use the equivalent to set the response headers
        'Access-Control-Allow-Origin': '*/*',
        'Access-Control-Allow-Credentials': true,
        'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS',
        'Access-Control-Allow-Headers': 'Origin, X-Requested-With, Content-Type, Accept, X-Parse-Session-Token'
    });
    res.header('Access-Control-Allow-Origin', '*');
    res.header('Access-Control-Allow-Origin', 'http://localhost:3000/parse');//change on 8/22/17 - probably because of node update?
    res.header('Access-Control-Allow-Methods', 'PUT, GET, POST, DELETE, OPTIONS');
    res.header('Access-Control-Allow-Headers', 'accept, content-type, x-parse-application-id, x-parse-rest-api-key, x-parse-session-token');
     // intercept OPTIONS method
    if ('OPTIONS' == req.method) {
      res.send(200);
    }
    else {
      next();
    }
  });
  app.use(logger('dev'));
  app.use(express.json());
  app.use(express.urlencoded({ extended: false }));
  app.use(cookieParser());
  app.use(express.static(path.join(__dirname, 'public')));
  app.use('/parse/',api);

  var port = normalizePort(process.env.PORT || '3000');
  app.set('port', port);

  /**
   * Create HTTP server.
   */

  var server = http.createServer(app);

  /**
   * Listen on provided port, on all network interfaces.
   */

  server.listen(port);
  server.on('error', onError);
  server.on('listening', onListening);

  /**
   * Normalize a port into a number, string, or false.
   */

  function normalizePort(val) {
    var port = parseInt(val, 10);

    if (isNaN(port)) {
      // named pipe
      return val;
    }

    if (port >= 0) {
      // port number
      return port;
    }

    return false;
  }

  /**
   * Event listener for HTTP server "error" event.
   */

  function onError(error) {
    if (error.syscall !== 'listen') {
      throw error;
    }

    var bind = typeof port === 'string'
      ? 'Pipe ' + port
      : 'Port ' + port;

    // handle specific listen errors with friendly messages
    switch (error.code) {
      case 'EACCES':
        console.error(bind + ' requires elevated privileges');
        process.exit(1);
        break;
      case 'EADDRINUSE':
        console.error(bind + ' is already in use');
        process.exit(1);
        break;
      default:
        throw error;
    }
  }

  /**
   * Event listener for HTTP server "listening" event.
   */

  function onListening() {
    var addr = server.address();
    var bind = typeof addr === 'string'
      ? 'pipe ' + addr
      : 'port ' + addr.port;
    debug('Listening on ' + bind);
  }

}

module.exports = app;
```

I'm testing Parse by running this file from the command line; in a separate terminal app.js is running and parsePlay.js is a file running from app.js.

I've since tried the parsePlay.js query from the client and it works just fine given the documentation shown for initializing Parse. For some reason there's trouble when I try running this code from within my express server side code.

parsePlay.js:

```javascript
'use strict'
const Parse = require('parse/node');
Parse.initialize("AppId", "MasterKey");

const queryStep = Parse.Object.extend("someCollection");
  const query = new Parse.Query(queryStep);
  query.find().then((data) => {
      console.log("data", data);
    }, (error) => {
      console.log("error", error.message);
    });

return;
```

Any help on this matter would be greatly appreciated!

**Comment by dplewis** [comment]
Please run parse-server with VERBOSE=1 and provide the logs for this operation in order to help debugging.

Also do you have any cloud code hooks?

**Comment by dplewis** [comment]
Your client side is initialized wrong.
https://github.com/parse-community/Parse-SDK-JS/blob/master/src/Parse.js#L33

**Comment by gigswift** [comment]
> Please run parse-server with VERBOSE=1 and provide the logs for this operation in order to help debugging.
> 
> Also do you have any cloud code hooks?
Thanks for responding dplewis. I posted this just as I was wrapping up my Saturday session. 

I'm unclear as to how you enable VERBOSE = 1. As I understand .env, I need to apply that environmental variable somewhere in my code, but where?
This is mentioned in the documentation: https://github.com/parse-community/parse-server but I'm not sure what's meant, could you provide some clearer guidance?

I don't have any cloud code hooks.

**Comment by gigswift** [comment]
Hey there Diamond, thanks for the follow up.

This app has no client right now.

parsePlay.js is a node file.

R

**Comment by dplewis** [comment]
```
var api = new ParseServer({
  ...
 verbose: true
  ...
});
```

I don’t know what your environment is but is should be something like 
`npm run (how you start your server) VERBOSE=1`

**Comment by gigswift** [comment]
Thanks man! I did get that part in there earlier today but it seems to be bringing up only logs from other errors I had before running into this. 

Should I look in the logs folder for something like parse-server.info.2019-04-14? That file specifically has nothing that appears related to this error. 

The Parse Dashboard, on the other hand actually no longer shows logs since I implemented verbose.

More guidance please.

**Comment by dplewis** [comment]
Can you connect to your server? Looks like it’s Parse.initialize is wrong

**Comment by gigswift** [comment]
I can from the front end but not from the backend. 

In past apps I was able to initialize Parse for queries in my Express code with 

```
const Parse = require('parse/node');
console.log("This is Parse", Parse);
Parse.initialize("AppId", "MasterKey");

```


What's changed or what am I missing? I'm not using a JS key right now.

I also know that the Parse object is getting picked up in the Express code as I just console.log it.

There seems to be a problem with the Parse Object communicated with Parse-Server.

**Comment by gigswift** [comment]
I figured it out - for some reason I need to include Parse.serverURL in my Node code in order for the Parse JS SDK to communicate with the Parse-Server API. I'm not sure why this is given the documentation as I don't see this expressed anywhere. 

Am I doing something wrong?

**Comment by dplewis** [comment]
It is documented in the [Javascript Guide](http://docs.parseplatform.org/js/guide/)

**Comment by gigswift** [comment]
You're right, I missed. Thanks for the help.

R
