### ISSUE TITLE
missing docs for setting the readPreference option in a query

### ISSUE THREAD

**Issue by oallouch** [parse-community/parse-server#5515]
Hi,
Like in my previous [issue](https://github.com/parse-community/parse-server/issues/5508) (where I said I can't find user.getSessionToken() in the docs), I face another documentation problem : this time I'd like to make some queries read from the secondary mongodb server, but I can't find the readPreference in the reference js documentation.

Thx a lot in advance,
Olivier

**Comment by davimacedo** [comment]
The only way to change the readPreference so far is by using a beforeFind trigger, like in the example below:
```
Parse.Cloud.beforeFind('MyClass', req => {
  req.readPreference = 'SECONDARY';
});
```

Note that in this example all queries in MyClass will be changed to the SECONDARY, but you can also do some verifications in the req object in order to check for a specific set of queries and only change for them.

I will open a PR soon in the docs repo explaining this.

**Comment by oallouch** [comment]
That's odd. Reading the sources, I would think I can do it directly in a Query
https://github.com/parse-community/parse-server/blob/3608b19b3a485d76dec53837c20fc710c76aa8f2/src/RestQuery.js#L112
and MongoStorageAdapter seems to retrieve it from the Query, next to limit, skip, ...
https://github.com/parse-community/parse-server/blob/3e003ee9f4c1955a09e8bc06ec1835698962e350/src/Adapters/Storage/Mongo/MongoStorageAdapter.js#L595

What do you think ?

**Comment by dplewis** [comment]
@oallouch Good catch surprised `query.setReadPerference()` was never added. Would you like to do a PR?

**Comment by oallouch** [comment]
I can try, but it'll be my first. I might need some help.
For instance, when I try npm install , I get many errors like:

npm WARN tar ENOENT: no such file or directory, open 'C:\Users\xxx\Documents\GitHub\Parse-SDK-JS\node_modules\.staging\insert-module-globals-cbc4cf8a\test\global\filename.js'

**Comment by dplewis** [comment]
Which node version are you running and do you have permissions?

**Comment by davimacedo** [comment]
@dplewis @oallouch when I wrote the readPreference option, my original idea was to include it as an option in the API and also in the JavaScript SDK, but, in that point in time, there were a discussion between some of the maintainers and they thought it was not a good idea to allow the client to choose where the query should run (it is a backend responsibility). I agree with the argument but I still think it would be much easier to have this option in the API. We can also protected it with master key so it could be set only in cloud code and server environments. So I see we have three options:
- keep like it is, only setting it using triggers
- include the readPreference option in the API and SDKs without requiring a master key
- include the readPreference option in the API and SDKs requiring master key

What do you think? @acinader can you please also share your thoughts on this?

**Comment by davimacedo** [comment]
I've just remembered we actually wrote the PR with the API option for readPreference but it was never approved:
https://github.com/parse-community/parse-server/pull/3963

I think it is a good start point for a new PR on this.

**Comment by oallouch** [comment]
The second one is very fine with me.

**Comment by oallouch** [comment]
@davimacedo I think you should write the server and client PRs. All the options (readPreference, includedReadPreference and subqueryReadPreference ) aren't as clear for me as it must be for you.

Btw, when a readPreference is set for a query, shouldn't it also change the default values of includedReadPreference and subqueryReadPreference ?

@dplewis my problem was just a config issue

**Comment by oallouch** [comment]
@dplewis I'm trying to write a Query.setReadPreference() test in the JS SDK, but I can't find an example of test that uses the output REST call generated from a Query.
I looked in integration/test/ParseQueryTest.js

**Comment by oallouch** [comment]
Ok, I'll just look at the output of ParseQuery.toJSON() .

**Comment by dplewis** [comment]
It would be easier to wait for something like https://github.com/parse-community/parse-server/pull/3963 to be implemented.

**Comment by oallouch** [comment]
Yes, that would be good.
#3963 is great, but 'includeReadPreference' and 'subqueryReadPreference' aren't completely treated in MongoStorageAdapter

I tried to modify the server myself.
I added the symlinks (using npm link) so that my project uses the local parse-server repo (with express), but I get "Cannot find module 'parse/node'".
Any ideas ?

**Comment by oallouch** [comment]
Never mind, I did 
const Parse = require('parse/node').Parse;
in a file.
It worked with the normal release, but not with this local symlink.

**Comment by davimacedo** [comment]
@dplewis @oallouch  I will rebase the PR this Monday and let you guys know.

**Comment by davimacedo** [comment]
The API changes were merged. I will now work on JS SDK.

**Comment by TomWFox** [comment]
For the sake of clarity the API changes were made in #3963, @davimacedo I believe changes to the JS SDK are still to be done? - maybe a separate issue should be opened there and this one be closed?

**Comment by davimacedo** [comment]
@TomWFox we still need to add the read preference option in the JS SDK and updated the docs. I will work this Tuesday to close the issue.
