### ISSUE TITLE
Unable to import array objects via mongoimport

### ISSUE THREAD

**Issue by luojieerr** [parse-community/parse-server#5518]
I have a csv file with a field formatted as an array object, but when I import data using mongoimport, there is no data loaded in the Parse Dashboard. If I change them to a string object, this will load normally.

csv example : https://drive.google.com/open?id=1GOd4SDtW0deeIarEbCg9sTrB7GWLF4U0
mongodb : v4.0.4
parse server : v3.2.1
node.js : v10.14.2

**Comment by TomWFox** [comment]
Closing this as you have cross posted this on the community forum.
