### ISSUE TITLE
well, yeah, strange behaviour 2.8.4 with apple receipt api

### ISSUE THREAD

**Issue by dongalor** [parse-community/parse-server#5519]
As I was trying to write in #5482, I was going to write apple receipt verification inside of cloud function, but when I add apple api call, like this: (this code works like a charm without parse cloud function)

```JavaScript
const rp = require('request-promise');

var verifyURL = 'https://sandbox.itunes.apple.com/verifyReceipt';
// use 'https://buy.itunes.apple.com/verifyReceipt' for production

var options = {
    uri: verifyURL,
    method: 'POST',
    headers: {
        'User-Agent': 'Request-Promise',
        'Content-Type': 'application/x-www-form-urlencoded',
    },
    json: true
};

options.form = JSON.stringify({
    'receipt-data': receiptData,
    'password': password
});

rp(options).then(function (resData) {
    devLog.log(resData); // 0
}).catch(function (err) {
    devLog.log(err);
});
```

I'm getting 3 of 5 calls to this function with socket disconnect on client side.

My parse api got some other than apple api calls, but they work fine. Is it possible, that there's some issue with compatibility?

Thank you.

**Comment by dongalor** [comment]
I also tried using Parse.Cloud.httpRequest:

(this is my Utils class)

```
getReceiptData: function(appleReceipt) {
      var promise = new Parse.Promise();

      var verifyURL = 'https://sandbox.itunes.apple.com/verifyReceipt';
      // use 'https://buy.itunes.apple.com/verifyReceipt' for production

      const secret = 'somethingsomethingsomething';

      Parse.Cloud.httpRequest({
        method: 'POST',
        url: verifyURL,
        headers: {
          'Content-Type': 'application/x-www-form-urlencoded',
        },
        body: {
          'receipt-data': appleReceipt,
          'password': secret
        }
      }).then(function(result) {
        promise.resolve(result);
      }, function(error) {
        promise.reject(error);
      });
      return promise;
    }
```

And here is code with request-promise:

```
getReceiptData: function (appleReceipt) {
      var promise = new Parse.Promise();

      var verifyURL = 'https://sandbox.itunes.apple.com/verifyReceipt';
      // use 'https://buy.itunes.apple.com/verifyReceipt' for production

      var options = {
        uri: verifyURL,
        method: 'POST',
        headers: {
          'User-Agent': 'Request-Promise',
          'Content-Type': 'application/x-www-form-urlencoded',
        },
        json: true
      };
      const secret = 'somethingsomethingsomething';
      options.form = JSON.stringify({
        'receipt-data': appleReceipt,
        'password': secret
      });

      rp(options).then(function (resData) {
        promise.resolve(resData);
        console.log(resData); // 0
      }).catch(function (err) {
        promise.reject(err);
      });

      return promise;
    }
```

So, I'm using it inside cloud function like this:

```
Parse.Cloud.define('verifyReceipt', function (req, res) {
  Utils.getReceiptData(req.params.receipt).then(data => {
    res.success(data);
  }, error => {
    res.error(error);
  })
});
```

**Comment by dongalor** [comment]
No, I clicked CLOSE for mistake, please reopen this, if you can )

**Comment by dongalor** [comment]
Actually, question is WHY using this exact code via nodejs CLI, I'm not having any interrupts, but when I use it inside cloud function, I do?

**Comment by dongalor** [comment]
No one will ever see this messages, cuz I closed this issue :(

**Comment by dongalor** [comment]
Here's httpie request log to cloud function url with this apple purchase request:

`http: error: ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')) while doing POST request to URL: http://localhost:1337/parse/functions/verifyReceipt`

**Comment by acinader** [comment]
try re-arranging your code like this:



```
Parse.Cloud.define('verifyReceipt', function (req, res) {
  return Utils.getReceiptData(req.params.receipt)
        .then(res.success)
        .catch(res.error);
  })
});
```

i'm guessing that whatever data is returned is causing an error in res.success and you're not catching the error....maybe?

**Comment by dongalor** [comment]
@acinader I see [this](https://gist.github.com/dongalor/f365336e55db8efa7e7955f0232f166a) in my logs and no error :(

**Comment by acinader** [comment]
your problem may be the size of the response.

it's odd that the second entry isn't truncated too.

can you simulate a smaller response (maybe truncate the value before handing it to success) and see if that solves it?

**Comment by dongalor** [comment]
@acinader i even removed this large response data (which indeed is very large, due to it includes this exact receipt too), same story...

```
Parse.Cloud.define('verifyReceipt', function (req, res) {
  Utils.getReceiptData(req.params.receipt).then(function () {
    res.success("GOOD");
  }, error => {
    res.error(error);
  })
});
```

**Comment by acinader** [comment]
something odd for sure.

You should really switch from using then(success, error) to then(success).catch(error).

if there is an error in your success function, you won't catch it.

Below I have re-written your getReceiptData function to not have the unnecessary promise wrapper around the request promise wrapper.

```
getReceiptData: function (appleReceipt) {
      var verifyURL = 'https://sandbox.itunes.apple.com/verifyReceipt';
      // use 'https://buy.itunes.apple.com/verifyReceipt' for production

      var options = {
        uri: verifyURL,
        method: 'POST',
        headers: {
          'User-Agent': 'Request-Promise',
          'Content-Type': 'application/x-www-form-urlencoded',
        },
        json: true
      };
      const secret = 'somethingsomethingsomething';
      options.form = JSON.stringify({
        'receipt-data': appleReceipt,
        'password': secret
      });

      return rp(options);
    }
```

I still don't see what is going wrong.

you may want to time the apple response.  maybe your cloud call is timing out.

the funny thing is that I am going to have to write the same thing in a few weeks.

**Comment by dongalor** [comment]
@acinader I've tried eliminating parse promise and still no effect, 
Actually this request is indeed time consumable (cli way), I'll post results tomorrow. 

p.s. thank you for support, for sure it's possible, we will solve this issue before you will start implementing this on your project =)

**Comment by dongalor** [comment]
So, time command on this node cli script:

`node check.js  0.45s user 0.09s system 13% cpu 3.816 total`

**Comment by acinader** [comment]
The 3.8s time is your issue.

If the time is not under your control, you can change this from a cloud function to a [cloud job](https://docs.parseplatform.org/cloudcode/guide/#cloud-jobs).

I'm going to close this issue as I do not believe that this is a problem with parse-server.

**Comment by dongalor** [comment]
@acinader Thank you, now I got it. I'm switching to cron job, which will run nodejs script with apple purchase inside, then it will pass data to Parse javascript sdk.
