### ISSUE TITLE
Postgres Geopoint Error

### ISSUE THREAD

**Issue by CoderickLamar** [parse-community/parse-server#5522]
### Issue Description

Excluding geopoints that are zero results in a server error and is breaking. (Postgres)
Error also occurs when excluding non-zero geopoints (ie. 1.0, 1.1, etc.)

### Steps to reproduce

Look for geopoints that are non zero with a Postgres DB
Error also occurs when excluding non-zero geopoints (ie. 1.0, 1.1, etc.)

```
finalFilter.push({
     name: 'location',
     queryType: 'notEqualTo',
     value: new Parse.GeoPoint({ latitude: 0, longitude: 0 }),
 });
 
```
### Expected Results

Query runs normally like it does on Mongo.

### Actual Outcome
Server Error. See logs below

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : Latest on master (Tried on older versions as well)
  - Operating System: Node.js running on 64bit Amazon Linux/4.5.1
  - Localhost or remote server? AWS

- **Database**
  - Postgres version: 10.4 with PostGIS
  - Localhost or remote server? AWS

### Logs/Trace

```
Server Error:
 name: 'error',
  length: 153,
  severity: 'ERROR',
  code: '22P02',
  detail: undefined,
  hint: undefined,
  position: '259',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'float.c',
  line: '545',
  routine: 'float8in_internal' } name=error, length=153, severity=ERROR, code=22P02, detail=undefined, hint=undefined, position=259, internalPosition=undefined, internalQuery=undefined, where=undefined, schema=undefined, table=undefined, column=undefined, dataType=undefined, constraint=undefined, file=float.c, line=545, routine=float8in_internal, stack=Error: error: invalid input syntax for type point: "{"__type":"GeoPoint","latitude":0,"longitude":0}"
    at adapter.find.then.catch.error (/var/app/current/node_modules/parse-server/lib/Controllers/DatabaseController.js:1075:21)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
    at process.wrappedProcess (/var/app/current/node_modules/newrelic/lib/instrumentation/core/timers.js:15:21), code=1

```

**Comment by acinader** [comment]
can you write a failing test for this?

**Comment by CoderickLamar** [comment]
```
it('fails to fetch geopoints that are specifically not at (0,0)', function (done) {

  const tmp = new TestObject({ location: new Parse.GeoPoint({ latitude: 0, longitude: 0 }) });

  const tmp2 = new TestObject({ location: new Parse.GeoPoint({ latitude: 49.2577142, longitude: -123.1941149 }) });

  Parse.Object.saveAll([tmp, tmp2]).then(function () {

    const query = new Parse.Query(TestObject);

    query.notEqualTo('location', new Parse.GeoPoint({ latitude: 0, longitude: 0 }));

    query.find().then(function (results) {

      expect(results.length).toEqual(1);

      done();

     });

 });

 });
```

Do you want me to submit this as a pull request?

**Comment by CoderickLamar** [comment]
@dplewis I believe you're using postgres as well. Is this something you've seen as well?

**Comment by dplewis** [comment]
@CoderickLamar I don't use postgres, just here for support. I can look into it for you.

**Comment by dplewis** [comment]
@CoderickLamar I submitted a PR. 

Using any NOT queries is not recommended as they don't use indexes and can will be exponentially slower as your DB grows.
