### ISSUE TITLE
Access to data without any session

### ISSUE THREAD

**Issue by topdeveloper0017** [parse-community/parse-server#5523]
I like to access data without any authentication.
Now I am getting "Session token is expired" when I try to access any data on parse DB.
But I don't need to login to get any data on db.

How can I access data without any user session token ?
Regards

**Comment by acinader** [comment]
@topdeveloper0017 

You do not need a session token to create a parse query.  

Please see https://community.parseplatform.org/ for how to find help with parse-server.

If you are trying to open an issue, please open a new issue here and use the issue template.
