### ISSUE TITLE
Common classes ("Users" for example) shared by all the apps in Parse dashboard?

### ISSUE THREAD

**Issue by lincyim** [parse-community/parse-server#5524]
**Is your feature request related to a problem? Please describe.**
I have several apps and I want all of them share the same users data. I mean one account that can login several apps. If I cloud set what classes to share within what apps, it would be fantastic. Thanks for your hard work!

**Comment by davimacedo** [comment]
I am not sure if this feature could be included in Parse Server. Your best chance now is probably using after save triggers to keep the data synchronized among the different apps.

**Comment by acinader** [comment]
@lincyim unless you want to give this a try, I think it's safe to say that this will not be on the roadmap.

I'm going to close this, but if you think we should reconsider and want to make an argument, feel free to reopen.
