### ISSUE TITLE
Can't upload/download files (URL string parser is deprecated)

### ISSUE THREAD

**Issue by 1987cr** [parse-community/parse-server#5525]
### Issue Description

I'm reopening [this issue](https://github.com/parse-community/parse-server/issues/5425) since it got closed after referencing an older commit that does not solves the problem.

Still not working on `parse-server v3.2.3`

### Steps to reproduce

- Create a new Class with a File column (using parse-dashboard to simplify things)
- Add a new row and upload a file, nothing will happen.

### Expected Results

Upload and Download files without errors.

### Actual Outcome

When trying to retrieve a file stored in gridFS, accessing the URL gives a "File not found." and the console shows the following warning:

```
(node:1972) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
```

Same message is displayed when trying to upload files.

Seems like the `{ useNewUrlParser: true }` option is missing on the `GridFSBucketAdapter.js`  file (probably is needed on the `GridStoreAdapter.js` file too).

I stopped getting the error after (locally) changing this:

```
constructor(mongoDatabaseURI = _defaults.default.DefaultMongoURI) {
    super();
    this._databaseURI = mongoDatabaseURI;
  }

  _connect() {
    if (!this._connectionPromise) {
      this._connectionPromise = _mongodb.MongoClient.connect(this._databaseURI).then(client => client.db(client.s.options.dbName));
    }

    return this._connectionPromise;
  }
```

to this:
```
constructor(mongoDatabaseURI = defaults.DefaultMongoURI, mongoOptions = {}) {
    super();
    this._databaseURI = mongoDatabaseURI;
    this._mongoOptions = mongoOptions;
    this._mongoOptions.useNewUrlParser = true; 
  }

  _connect() {
    if (!this._connectionPromise) {
      this._connectionPromise = MongoClient.connect(
        this._databaseURI,
        this._mongoOptions
      ).then(client => client.db(client.s.options.dbName));
    }
    return this._connectionPromise;
  }
```

Can submit a PR with that change if needed.

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 3.2.3
  - Operating System:
  - Hardware:
  - Localhost or remote server: Azure

- **Database**
  - MongoDB version: 3.2.0
  - Storage engine: 
  - Hardware: 
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): Azure Cosmos DB

**Comment by dplewis** [comment]
Didn't notice the `GridStoreAdapter.js` file would you like to submit a PR?

Also It is highly recommended to use [S3 Adapter](https://github.com/parse-community/parse-server-s3-adapter)

**Comment by danielmartinprieto** [comment]
But S3 adapter is only for Amazon, right? Can/Should we use it with Azure?

**Comment by davimacedo** [comment]
S3 Adapter is only for AWS S3. You can try this one here for Azure: https://github.com/felixrieseberg/parse-server-azure-storage

**Comment by danielmartinprieto** [comment]
Thanks, @davimacedo! We currently use Parse directly for images, as we're not doing a heavy use, but we'll consider migrating to `parse-server-azure-storage` soon.

**Comment by 1987cr** [comment]
Alright @dplewis, I'll submit the PR as soon as I have the chance.
