### ISSUE TITLE
Full Text Search Error code: 107, Bad constraint: $text

### ISSUE THREAD

**Issue by fsoegiono** [parse-community/parse-server#5533]
I'm running my code on cloud parse-server version `2.8.4` full text search and it seems it does not work for me. I got the following message... 

<img width="428" alt="Screen Shot 2019-04-26 at 2 08 33 PM" src="https://user-images.githubusercontent.com/8943566/56836647-cab1a400-682c-11e9-98c3-5dd09c7ceb6b.png">

Here's my code:

![Screen Shot 2019-04-26 at 2 09 10 PM](https://user-images.githubusercontent.com/8943566/56836681-e2892800-682c-11e9-8ea9-d7c198e33f29.png)

I'm using mlab/mongodb for storing parse data

Any help is much appreciated.

**Comment by dplewis** [comment]
Please update to the latest version of Parse Server and reopen if issue persists.

**Comment by fsoegiono** [comment]
Tried parser server latest version 3.3.0 but still gives the same result

<img width="428" alt="Screen Shot 2019-04-26 at 2 08 33 PM" src="https://user-images.githubusercontent.com/8943566/56839973-04d57280-683a-11e9-82f3-90b30b225289.png">

**Comment by dplewis** [comment]
Can you post logs?

Here is where $text is https://github.com/parse-community/parse-server/blob/7122ca05c4e29ccf9d1c86ab3864b08508a09915/src/Adapters/Storage/Mongo/MongoTransform.js#L956
