### ISSUE TITLE
All Files Missing

### ISSUE THREAD

**Issue by tgreco** [parse-community/parse-server#5535]
### Issue Description

I am running Parse-Server on a Heroku cloud instance.
It has been humming along just fine for months without issue.
I logged in to the website today and all the images were not displaying.

By Images I mean files saved to the backend.
I have my Users table have a column for profile picture.

This image was still there and when I tried to access it via the parse-dashboard to view it it did not work. 
I received a 404 error.

After restarting the server the images displayed just fine. 

I am wondering why it stopped working in the first place since nothing changed.

### Software packages: 
    "npm": "^6.4.1",
    "parse": "^2.1.0",
    "parse-dashboard": "^1.2.0",
    "parse-server": "^2.8.4"

**Comment by davimacedo** [comment]
What's the file adapter that you are using and where are your files hosted? Can you please send an url that is failing?
