### ISSUE TITLE
Parse Server Cloud Code remove an object from array in database

### ISSUE THREAD

**Issue by memishood** [parse-community/parse-server#5587]
i try many times remove an object from user array on parse server but it doesn't work, 
Server side:
Parse server 2.8.4

my code: 
`Parse.Cloud.define("deleteFriend",(req,res)=>{
	var params = req.params;
	var query = new Parse.Query(Parse.User);
	query.equalTo('objectId',params.remoteObjectId);

	query.first({
		useMasterKey: true,
		success: (user)=>{
			user.remove('friends', params.localObjectId);
                        // also i tried user.removeAll('friends',params.localObjectId);
                       // also i tired user.removeAll('friends', [params.localObjectId]);
			user.save(null,{
				success: ()=>{
					res.success('User removed from your list');
				},
				error: ()=>{
					res.error('error');
				}
			});
		},
		error: (err)=>{
			res.error('got error' + err);
		}
	});
});`

it returns error because of res.error('error');

**Comment by zealmurapa** [comment]
are you sure the field is an array, and are you sure you have permissions?

**Comment by memishood** [comment]
yes i'm sure and i have

**Comment by memishood** [comment]
anybody know how to remove an object from user's array from parse server on cloud code ?

**Comment by dplewis** [comment]
What error was returned? Can you post logs VERBOSE=1

**Comment by memishood** [comment]
okey guys i fixed using to the useMasterKey: true in save function. thanks for everything.
