### ISSUE TITLE
Allow disabling object merge behavior

### ISSUE THREAD

**Issue by mrclay** [parse-community/parse-server#5597]
Our team has been bitten many times by the quirky merge behavior:

```js
obj.set('foo', {one: 1, two: { a: 'a', b: 'b' }});
await obj.save(null);

obj.set('foo', {two: { b: 'b' }});
await obj.save(null);

console.log(obj.get('foo')); // { one: 1, two: { b: 'b' }}
```

First-level keys in attribute objects cannot be removed, only set to `null`. We have to completely unset('foo'), save, and re-set it to be assured it has the exected value.

This behavior isn't documented in [Object.set](http://parseplatform.org/Parse-SDK-JS/api/2.4.0/Parse.Object.html#set).

**Comment by dplewis** [comment]
Is this for Postgres? What version of Parse-Server are you using? I believe this has been fixed. 

https://github.com/parse-community/parse-server/pull/5242

**Comment by mrclay** [comment]
parse-server 2.8.1 on postgres, so looks like we'll have to get to 3.x. Thanks.

**Comment by dplewis** [comment]
No problem! A lot of PG improvements made. 

Can you comment on https://github.com/parse-community/parse-server/pull/5336?
