### ISSUE TITLE
Can i send push to android without using fcm? 

### ISSUE THREAD

**Issue by javadghane** [parse-community/parse-server#5603]
### Issue Description

Hi, i'm using parse server v2.3.3 and parse dashboard 1.10.18 on my own server. 
after configure the config i can send object and receive them by curl commands. 
but for sending push notification to android devices i confused how to configure server. 
is need to use FCM for sending pushes? or This is an optional option? 
is there any way to using parse server without FCM? in my server i cant have internet some times. 
currently i'm getting installation record but push notification doesn't receive to android devices!

### Push Configuration

Server is running with [this docker image](https://hub.docker.com/r/yongjhih/parse-server)

Android config:
(the google-services.json is added to app directory)

build.gradle 
```
    implementation "com.github.parse-community.Parse-SDK-Android:fcm:1.20.0"
    implementation "com.github.parse-community.Parse-SDK-Android:parse:1.20.0"
    implementation 'com.google.firebase:firebase-core:16.0.9'
    implementation 'com.google.firebase:firebase-messaging:18.0.0'
```

```
 Parse.initialize(new Parse.Configuration.Builder(this)
                .applicationId("YOUR_APP_ID")
                .server("http://MyServerIp:1337/parse/")
                .build()
        );
        Parse.setLogLevel(Parse.LOG_LEVEL_DEBUG);
        ParsePush.subscribeInBackground("myChannel", new SaveCallback() {
            @Override
            public void done(ParseException e) {
                Log.e(LOG_TAG, "Successfully subscribed to Parse!");
            }
        });

        ParseInstallation.getCurrentInstallation().saveInBackground();
```

Manifest.xml
```
 <service
            android:name="com.parse.fcm.ParseFirebaseInstanceIdService"
            android:exported="true">
            <intent-filter>
                <action android:name="com.google.firebase.INSTANCE_ID_EVENT" />
            </intent-filter>
        </service>

        <service android:name="com.parse.fcm.ParseFirebaseMessagingService">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>

        <receiver
            android:name="com.parse.ParsePushBroadcastReceiver"
            android:exported="false">
            <intent-filter>
                <action android:name="com.parse.push.intent.RECEIVE" />
                <action android:name="com.parse.push.intent.DELETE" />
                <action android:name="com.parse.push.intent.OPEN" />
            </intent-filter>
        </receiver>

        <receiver
            android:name="com.parse.ParsePushBroadcastReceiver"
            android:exported="false">
            <intent-filter>
                <action android:name="com.parse.push.intent.RECEIVE" />
                <action android:name="com.parse.push.intent.DELETE" />
                <action android:name="com.parse.push.intent.OPEN" />
            </intent-filter>
        </receiver>
```

### Environment Setup

- **Server**
  - parse-server version 2.3.3 
  - Operating System:     ubunut 18.04
  - Localhost or remote server? localhost

- **Database**
  - MongoDB version: https://hub.docker.com/r/yongjhih/parse-server/ 
  - Storage engine:  default storage of parse 
  - Hardware:        disk
  - Localhost or remote server? localhost

### Logs/Trace

sending push with curl:
```

curl -X POST \
  http://myServerIp:1337/parse/push \
  -H 'Postman-Token: 6acde416-955f-442a-a697-bd3ec984980f' \
  -H 'X-Parse-Application-Id: YOUR_APP_ID' \
  -H 'X-Parse-Master-Key: YOUR_MASTER_KEY' \
  -H 'X-Parse-REST-API-Key: YOUR_MASTER_KEY' \
  -H 'cache-control: no-cache' \
  -d '{
        "channels": [
          "myChannel"
        ],
        "data": {
        "masterKey": "YOUR_MASTER_KEY",
          "alert": "The Mets scored! The game is now tied 1-1.",
          "badge": "Increment",
          "sound": "cheering.caf",
          "title": "Mets Score!"
        }
      }'

```

**Comment by davimacedo** [comment]
Yes. Parse Server requires FCM in order to send push notifications to Android devices. Please refer to this guide here on how to setup: https://docs.parseplatform.org/android/guide/#setting-up-push

**Comment by mtrezza** [comment]
That is actually a very interesting question.

It is interesting because [FCM](https://firebase.google.com/docs/cloud-messaging/android/client) requires Google Play Services to be installed on the client.

What if you want to target users in China who mostly do not / cannot use Google services or users who refuse to install Google services out of privacy concerns?

All I can think of is a 3rd party push service like [Pusher](https://pusher.com) or [OneSignal](https://onesignal.com), which are not free.

**Comment by badboy-tian** [comment]
+1
