### ISSUE TITLE
MongoDB create index error after update from 3.2.3 to 3.3.0/3.4.0

### ISSUE THREAD

**Issue by BH4EHN** [parse-community/parse-server#5614]
### Before opening the issue please ensure that you have:

- [✔] [Read the migration guide](https://github.com/parse-community/parse-server/blob/master/3.0.0.md) to parse-server 3.0.0
- [✔] [Read the migration guide](https://github.com/parse-community/Parse-SDK-JS/blob/master/2.0.0.md) to Parse SDK JS 2.0.0

### Issue Description

Previously I'm using ParseServer 3.2.3 (and long ago use 2.x), and try to upgrade to 3.3.0/3.4.0 some days ago.

In 3.2.3, on booting ParseServer, some MongoDB index creation warning like 
 - `Unable to ensure uniqueness for usernames: MongoError: Index with name: username_1 already exists with different options` 
 - `Unable to ensure uniqueness for user email addresses: MongoError: Index with name: email_1 already exists with different options`

are treat like warning and application keeps running.

After 3.3.0, same code, same dependency, just different version Parse Server, these errors above are treat as error and make the process exit.

### Steps to reproduce

- a Parse MongoDB database with `_User` collection have index `username_1` or `email_1` but not unique.
- run Parse Server 3.3.0/3.4.0
 
### Expected Results

Application keeps running, just have some MongoDB error message.

### Actual Outcome

Application process exits with MongoDB error.

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 3.3.0 and 3.4.0
  - Operating System:     Amazon Linux 2
  - Hardware:             AWS EC2 c5.xlarge
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): AWS

- **Database**
  - MongoDB version: 3.2.22
  - Storage engine:  MMAPv1
  - Hardware:        <unknown>
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): AWS

**Comment by dplewis** [comment]
Check out the [2.3 Upgrade Guide](https://github.com/parse-community/parse-server/blob/master/2.3.0.md)

**Comment by BH4EHN** [comment]
@dplewis really thanks
