### ISSUE TITLE
Problems saving date inside an object

### ISSUE THREAD

**Issue by FredericoSFerreira** [parse-community/parse-server#5623]
- [X] [Read the migration guide](https://github.com/parse-community/parse-server/blob/master/3.0.0.md) to parse-server 3.0.0
- [X] [Read the migration guide](https://github.com/parse-community/Parse-SDK-JS/blob/master/2.0.0.md) to Parse SDK JS 2.0.0

### Issue Description
How do I save a date-type record inside an array of objects in the mongo through the parse it saves in the following format in the database.

    {  "_id" : "GZ8BTtpdSB",
       "historicoStatus" : [{
            "status" : "Recebida",
            "color" : "red",
            "dateHourInside" : {
                "__type" : "Date",
                "iso" : "2019-05-30T09:25:49.025Z"
         }],
        "dateHourOut" : ISODate("2019-05-30T09:25:49.008Z")
     }

Note that `dateHourInside` does not write with the type date in the database, which hinders the search by date, but when saved the date in the root of the` dateHourOut` object it saves in the correct way in the database in the ISOdate standard.

Also see that the value obtained by `moment` equals

`dateHourOut = moment().utc(moment.now(), 'YYYY-MM-DD HH:mm:ss').toDate();`

`dateHourInside = moment().utc(moment.now(), 'YYYY-MM-DD HH:mm:ss').toDate();`

 
### Expected Results

    { "_id" : "GZ8BTtpdSB",
       "historicoStatus" : [{
           "status" : "Recebida",
           "color" : "red",
           "dateHourInside" :ISODate("2019-05-30T09:25:49.008Z")
        }],
      "dateHourOut" : ISODate("2019-05-30T09:25:49.008Z")}

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 3.4.0
  - Operating System:    Linux Ubuntu
  - Hardware: -
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Localhost and Digital Ocean
- **Database**
  - MongoDB version: 3.6 and 4.1
  - Storage engine: WiredTiger
  - Hardware:       -
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): : Localhost and Digital Ocean

**Comment by dplewis** [comment]
Thanks for reporting. Would you like to write a failing test?

**Comment by igorarduini** [comment]
@dplewis I have the same problem. Do you have some prediction?

**Comment by dplewis** [comment]
@igorarduini Can you post server logs?

**Comment by igorarduini** [comment]
@dplewis I have uploaded 2 images, this one with logs ![Image of logs](https://imgur.com/kWZ1svg.jpg) and with DB object ![Image of db](https://imgur.com/ut6xdNu.jpg)

**Comment by dplewis** [comment]
Are you able two query both dates successfully? __type Date should parse correctly.

**Comment by igorarduini** [comment]
> Are you able two query both dates successfully? __type Date should parse correctly.

@dplewis here is the queries:
Success
![Image of success](https://i.imgur.com/FDGOELp.jpg)

Failure
![Image of fail](https://i.imgur.com/zDfpQ43.jpg)

I have tried to access Date iso object with `objectExample.iso: { $gte: new ISODate() }` but without success.

**Comment by dplewis** [comment]
Does querying work from the client JS SDK?

If you are trying to interact with mongodb directly you should change your query.

**Comment by igorarduini** [comment]
@dplewis how should the query be? This is the first time i have seen `objectDate.iso` format

**Comment by dplewis** [comment]
Closing as this isn't an issue with Parse.

In your case:

`db.getCollection('ocorrencia').find({ "historicoStatus.dataHoraMongo.iso" : ...});`

**Comment by igorarduini** [comment]
@dplewis how I mentioned before, I have tried `objectParse.iso and it doesn't works

**Comment by igorarduini** [comment]
Just to consider, if I add a date with parseJS, an object.iso is created, and if I add a date without parse, an attribute type `Date` is created. This is the problem
