### ISSUE TITLE
Unable to get fields in client after request.user.save in cloud

### ISSUE THREAD

**Issue by grantespo** [parse-community/parse-server#5629]
`request.user.save` successfully saves the value into the appropriate field.

However, the current user's field still shows null when I use .get() in client. It shows that the value is updated in my dashboard though.

The only way for me to see the newly saved value on the client is if I log out and log back in on the client.

I've tried passing request.user.sessionToken and masterKey: true as parameters for my cloud's save function but still the same result.

**Comment by dplewis** [comment]
This is expected behavior. You can use `.fetch()` on the client to get the updated values.
