### ISSUE TITLE
write: false, read: true for a user field

### ISSUE THREAD

**Issue by grantespo** [parse-community/parse-server#5630]
By default, the `_User's` CLP is set to `read: true, write: false` for the public. And `read: true, write: true` for himself.

I was able to successfully use `protectedFields` to  set a field to `read: false` for the public like this:

`protectedFields: {
    _User: { "*": ["email", "phoneNum"]}
  },`

Is it also possible to set a user field to  `read: true, write: false` for public but `read: true, write: false` for himself?

**Comment by dplewis** [comment]
Have you tried setting ACL on signup?

**Comment by grantespo** [comment]
Doesn't ACL make force these settings for all field for the class? I only need these settings for one field.

**Comment by grantespo** [comment]
just use beforeSave for Current user
