### ISSUE TITLE
Sign in with Apple Authentication

### ISSUE THREAD

**Issue by otymartin** [parse-community/parse-server#5632]
It appears that for iOS app's that offer social Sign In options like Facebook, Google, Twitter etc, **"[Sign in with Apple](https://developer.apple.com/sign-in-with-apple/)"** will be a mandatory option we must include.

Any plan's to add support for this? Major key will be avoiding conflict with accounts created with FB/Twitter/Google that later on choose to sign in with Apple or those created with Apple and Sign In on android devices with other social Sign In options.

Nightmare

**Comment by TomWFox** [comment]
I haven't seen anything about it being mandatory but definitely recommended.

I would like to see this implemented as well, I'm going to look into the details of how it should be done but would appreciate any help from people who would also like this added to Parse Server & client SDKs.

**Comment by otymartin** [comment]
@TomWFox It's definitely mandatory: [SOURCE](https://www.macrumors.com/2019/06/03/sign-in-with-apple-required-as-sign-in-option/)

**Comment by TomWFox** [comment]
I stand corrected, thanks for that information

**Comment by dplewis** [comment]
Apple back at it again. Would this be something you would like to implement?

**Comment by acegreen** [comment]
+1

**Comment by SebC99** [comment]
Isn't it just another auth adapter with a user identifier and a JWT token?
I don't see why it could lead to any conflicts...

**Comment by rizzla22** [comment]
@SebC99 I need exactly that!! but for wordpress authentication. Do you know of any examples which show how to do this ? I just opened an issue on the matter here https://github.com/parse-community/parse-server/issues/5649

**Comment by fishandphil** [comment]
has anyone succeeded with Apple SignIn & Parse Server?

**Comment by dplewis** [comment]
I opened a Pull Request with this feature. https://github.com/parse-community/parse-server/pull/5694

**Comment by funkenstrahlen** [comment]
Thank you @dplewis !

**Comment by TomWFox** [comment]
So was the takeaway from this that the client ID is not actually optional? - if so I'll update the docs

**Comment by ashish-naik** [comment]
Value is needed according to me.  Service id didn’t work for me.  Bundle is id.

**Comment by omarojo** [comment]
> Value is needed according to me. Service id didn’t work for me. Bundle id did.

Where do you get the **Service ID** anyways ?

**Comment by ashish-naik** [comment]
https://developer.apple.com/account/resources/identifiers/list/serviceId
