### ISSUE TITLE
response.success() is not a function

### ISSUE THREAD

**Issue by misaghDroid** [parse-community/parse-server#5635]
Hi, 
I have installed parse-server-example and I have uploaded my cloud code. I have a function there but I got error response.success is no function.

` 

    Parse.Cloud.define("submitWeeklyScore", function (request, response) {
    const gameScore = new Parse.Object("WeeklyGameScore");

    gameScore.set("rubikaId", request.params.rubikaId);
    gameScore.set("score", request.params.score);
    gameScore.set("name", request.params.name);
    gameScore.set("family", request.params.family);
    gameScore.set("username", request.params.username);
    
    gameScore.save(null, {useMasterKey: true}).then((saveResult) => {
        var playerScore = saveResult.get("score");
        var playerCreatedAt = saveResult.createdAt;
        var objectId = saveResult.id;
        var mainQuery = new Parse.Query("WeeklyGameScore");
        mainQuery.greaterThanOrEqualTo("score", playerScore);
        mainQuery.lessThan("createdAt", playerCreatedAt);

        mainQuery.count({useMasterKey: true}).then((count) => {
            var obj = {rank: count + 1, objId: objectId};
            response.success(obj);
        }, (error) => {
            response.error(error);
        });

    }, (error) => {
        response.error(error);
    });
    }); `

Can anyone help me? I am new in parse server

**Comment by misaghDroid** [comment]
if I replace response.success(obj); with return obj; I get this :

    ```
info: Ran cloud function submitWeeklyScore for user undefined with:
      Input: {"score":1337,"rubikaId":11111,"name":"","family":"","username":""}
      Result: undefined {"functionName":"submitWeeklyScore","params": {"score":1337,"rubikaId":11111,"name":"","family":"","username":""}}
```

**Comment by TomWFox** [comment]
Parse Server example installs the latest version of parse server. Version 3.0.0 of Parse Server removed `response.success()`. Please see the migration guide for details on updating your cloud code.

**Comment by misaghDroid** [comment]
Thank you, it works.

**Comment by misaghDroid** [comment]
> 
> 
> Parse Server example installs the latest version of parse server. Version 3.0.0 of Parse Server removed `response.success()`. Please see the [migration guide](https://github.com/parse-community/parse-server/blob/master/3.0.0.md) for details on updating your cloud code.

Thank you, it worked.
