### ISSUE TITLE
Anonymous login not working

### ISSUE THREAD

**Issue by fmendoza** [parse-community/parse-server#5647]
### Steps to reproduce

Call the logIn method of the AnonymousUtils
```javascript
Parse.AnonymousUtils.logIn();
```

Curl:
```bash
curl -X POST -H "X-Parse-Application-Id: myAppId" -H "X-Parse-REST-API-Key: undefined" -H "Content-Type: application/json" -d '{"authData": { "anonymous": { "id": "12345678" }}}' https://someserver.here/parse/users
``` 
### Expected Results

Anonymous user should be created

### Actual Outcome

Parse Server returns:
```javascript
{"code":141,"error":"Cannot read property 'access_token' of undefined"}
```
### Environment Setup

- **Server**
  - parse-server version : 3.4.0
  - Operating System: Ubuntu
  - Hardware: 50GB, 2GB, 1 CPU
  - Localhost or remote server? : DigitalOcean

- **Database**
  - MongoDB version: 3.4
  - Storage engine:  Mongo
  - Hardware:  Same as server
  - Localhost or remote server?: DigitalOcean

**Comment by dplewis** [comment]
Can you post logs? VERBOSE=1

That call to AnonymousUtils shouldn’t affect curl

**Comment by fmendoza** [comment]
The issue was a custom code in my beforeSave. Sorry for that. Closing issue now.

**Comment by tiavina-mika** [comment]
I try to signup anonymous user with REST but I got this error: `This authentication method is unsupported`

I'm using:
-  Parse Server 4.5.0
-  Node 14.15.4


## Steps to reproduce: 
1. My Endpoint: http://localhost:1337/parse/users
2. The request body:
```
{
    "authData": {
        "anonymous": {
            "id": "abcdef1234"
        }
    }
}
```

## Excepted result
```
{
  "createdAt": "2012-02-28T23:49:36.353Z",
  "objectId": "uMz0YZeAqc",
  "sessionToken": "r:samplei3l83eerhnln0ecxgy5"
}

```
## Actual Result:
```
{
    "code": 252,
    "error": "This authentication method is unsupported."
}
```
Where I'm wrong?

**Comment by tiavina-mika** [comment]
SOLVED: 		
set ``enableAnonymousUsers`` to true

```
	const parseServer = new ParseServer({
			databaseURI: dbUrl,
			cloud: __dirname + '/cloud/main.js',
			appId: APP_ID,
			masterKey: MASTER_KEY,
			enableAnonymousUsers: true,
			// enableAnonymousUsers: false,
			verbose: false, //!isProduction,
			serverURL,
			appName: 'myApp',
			publicServerURL: serverURL,
			auth: {
				myAuth: {
					module: myAuthAdapter,
				}
			}
	});
```
