### ISSUE TITLE
Authentication with Wordpress 

### ISSUE THREAD

**Issue by rizzla22** [parse-community/parse-server#5649]
I have defined cloud functions which will do a http request to an instance of wordpress and will receive a valid JWT, this is done for both login and registration. 

I only want wordpress for Authentication, everything else will be done via Parse such as profiles etc.

The documentation doesnt really show how to authenticate using this method and at the moment during registration im registering the user on wordpress and parse and for login im logging in on wordpress and if that is successful i login on parse too - but there should be a simple solution whereby if the user is authenticated on WP then all their profile on Parse is unlocked too

            Parse.Cloud.define("loginUser", async (request: FunctionRequest): Promise<any> => {
                try {
                const profileRequestOptions: Parse.Cloud.HTTPOptions = { 
                    followRedirects: true,
                    url: 'http://wordpress-website.com/wp-json/v1/login',
                    headers: {
                        'Content-Type': 'application/json'
                    },
                    method: "POST",
                    params: {
                        "username": request.params.email,
                        "password": request.params.password
                    }
                }
                let getLoginResponse = await Parse.Cloud.httpRequest(profileRequestOptions)
                if( getLoginResponse.status != 200 ) {
                    throw new Error(getLoginResponse.data.code)
                }
                let profileData: IWPUserData = getLoginResponse.data;
                
                Parse.User.enableUnsafeCurrentUser();
                const provider = {
                authenticate: () => Promise.resolve(),
                restoreAuthentication() {
                    return true;
                },
                getAuthType() {
                    return 'myAuth';
                },
                getAuthData() {
                    return {
                    authData: {
                        id: 1234,
                    },
                    };
                },
                };
                Parse.User._registerAuthenticationProvider(provider);
                await Parse.User.logIn(request.params.email, request.params.password)      
                return profileData       
                } catch (error) {
                    throw new Error(error.data.code ) // usually incorrect_password
                }
            })

**Comment by dplewis** [comment]
Have you looked at https://docs.parseplatform.org/js/guide/#custom-authentication-module?

You should register your module and call `_linkWith`

**Comment by rizzla22** [comment]
Hi, yes Ive followed that so far - user gets created etc but for some reason a session isnt generated on my app when trying to retrive the parse current user during registration..


            Parse.User.enableUnsafeCurrentUser(); // this could be insecure
            const provider = {
            authenticate: () => Promise.resolve(),
            restoreAuthentication() {
                return true;
            },
            getAuthType() {
                return 'myAuth';
            },
            getAuthData() {
                return {
                authData: {
                    id: profileData.user_nicename,
                },
                };
            },
            };
            
            Parse.User._registerAuthenticationProvider(provider);
            const user = new Parse.User();
                user.setUsername(profileData.user_nicename);
            await user._linkWith(provider.getAuthType(), provider.getAuthData());
                user._isLinked(provider);
            await user._unlinkFrom(provider);

**Comment by rizzla22** [comment]
Yes I have followed that fully.. my code is below, grateful for any pointeres on what is wrong here

// my main function to handle the wp authentication
        Parse.Cloud.define("wordpressRegister", async (request: FunctionRequest): Promise<Parse.User> => {
            
            try {
            const profileRequestOptions: Parse.Cloud.HTTPOptions = { 
                followRedirects: true,
                url: 'http://wordpress-auth.io/wp-api-auth/v1/users/register',
                headers: {
                    'Content-Type': 'application/json'
                },
                method: "POST",
                params: {
                    "email": request.params.email,            
                    "password": request.params.password
                }
            }
            
            let getLoginResponse = await Parse.Cloud.httpRequest(profileRequestOptions)
            if( getLoginResponse.status != 200 ) {
                throw new Error(getLoginResponse.data.code)
            }

            let profileData: any = getLoginResponse.data;
            
            Parse.User.enableUnsafeCurrentUser();
            
            const provider = {
            authenticate: () => Promise.resolve(),
            restoreAuthentication() {
                return true;
            },
            getAuthType() {
                return 'myAuth';
            },
            getAuthData() {
                return {
                authData: {
                    id: profileData.user_nicename,
                },
                };
            },
            };
            // https://github.com/parse-community/Parse-SDK-JS/issues/379
            Parse.User._registerAuthenticationProvider(provider);
            const user = new Parse.User();
            await user._linkWith(provider.getAuthType(), provider.getAuthData());
                user._isLinked(provider);
            await user._unlinkFrom(provider);    

                let parseSessionToken = await  user.getSessionToken();
                console.log("##### SESSION TOKEN #####"+ parseSessionToken)
            
                await Parse.Cloud.run("LinkProfileToUser", {'user': user.toJSON()}, masterKey)
                await user.fetch(masterKey)
                
                const userProfile = await user.get('profile').fetch(masterKey)

                userProfile.set('discovery', false)    
            await userProfile.save(null, masterKey)

            return user
            } catch (error) {
                throw new Error( JSON.stringify(error) ) // issue happened
            }    

        })



        // function in my app to register the user and assign it to the IUser type - this works, I get back the users details
        async wordpressRegister(email: string, password: string): Promise < IUser > {
            const user: IUser = <IUser><any> await this.promise(this.runCloud('wordpressRegister', {email: email, password: password}))
            this.registerPush()
            return user        
            }    
            
        // calling another function to get the users ID does not work 

        currentUser(): IUser {
                return <IUser><ParseUser>Parse.User.current()
            }

**Comment by rizzla22** [comment]
Also my custom auth is defined in the config as so

```
const CustomAuth = require('./CustomAuth');

auth = {
    myAuth: {
        module: CustomAuth,
        option1: 'hello',
            option2: 'world',
    }
}
```

and contained in custom auth is 
```
function validateAuthData(authData, options) {
    return Promise.resolve({})
}

function validateAppId(appIds, authData, options) {
    return Promise.resolve({});
}

module.exports = {
    validateAppId,
    validateAuthData,
};```
