### ISSUE TITLE
Linkedin login doesn't work anymore since v1 is deprecated

### ISSUE THREAD

**Issue by faysal515** [parse-community/parse-server#5655]
### Issue Description

Linkedin stopped supporting their v1 api. Now parse server always fails to auth. getting `Linkedin auth is invalid for this user` error.

### Steps to reproduce

this is what we get if we do a manual request on v1 api `https://api.linkedin.com/v1/people/~?format=json`

```{
    "errorCode": 0,
    "message": "This resource is no longer available under v1 APIs",
    "requestId": "DO3MD6H878",
    "status": 410,
    "timestamp": 1560139440191
}
```

 
### Expected Results

A sessionToken after authentication.

### Actual Outcome

`Linkedin auth is invalid for this user`

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.8.2
  - Operating System:     MacOS Mojave
  - Hardware:             macbook pro 13'
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): localhost

- **Database**
  - MongoDB version: 3.4
  - Storage engine:  WeiredTiger
  - Hardware:        
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): localhost

**Comment by dplewis** [comment]
Would you like to open a PR?

You can change [LinkedIn Auth Adapter](https://github.com/parse-community/parse-server/blob/master/src/Adapters/Auth/linkedin.js)

**Comment by faysal515** [comment]
pull request added for master branch https://github.com/parse-community/parse-server/pull/5660

pull request for 2.8.x branch https://github.com/parse-community/parse-server/pull/5661
