### ISSUE TITLE
Can't send email regarding potential security issue to security@parseplatform.org

### ISSUE THREAD

**Issue by BenniPlejd** [parse-community/parse-server#5671]
### Issue Description

I've discovered a potential security issue that I don't want to disclose through a GitHub issue. However, when I try to send an email to security@parseplatform.org [as specified here](https://github.com/parse-community/parse-server/security/policy) I get a **Mail Discovery Notification (Failure)** email back.

I've also tried sending the email to the contact email community@parseplatform [as specified here](https://community.parseplatform.org/tos#heading--contact), but I still get the same failure email back.

We use G Suite (i.e. Google Mail) for sending our emails.

### Steps to reproduce

1. Send email to security@parseplatform.org.
 
### Expected Results

1. Email sent and received successfully.

### Actual Outcome

1. I get a **Mail Discovery Notification (Failure)** mail back, with the following information: "Your message wasn't delivered to security@parseplatform.org   because the address couldn't be found, or is unable to receive mail."

### Environment Setup

N/A

### Logs/Trace

N/A

**Comment by acinader** [comment]
thanks.  looking into.

**Comment by TomWFox** [comment]
As an alternative, as a non-member can you create a Security Advisory through GitHub?
<img width="1063" alt="Screenshot 2019-06-12 at 17 40 06" src="https://user-images.githubusercontent.com/13188249/59369820-22529300-8d39-11e9-9e65-c1b697b142e2.png">

**Comment by acinader** [comment]
@TomWFox YES!!! that is so much better.  If you're up for it, will you update the docs to direct security issues there?

@BenniPlejd I've created the email addresses for those aliases.  I can imagine how it all happened and I appreciate you're opening this issue.  Would you open a [security issue](https://github.com/parse-community/parse-server/network/alerts)

**Comment by BenniPlejd** [comment]
@acinader Unfortunately I get 404 on that link, and I can't create any advisories if I click on the Security tab in the project's GitHub.

I'll test emailing you guys again!

**Comment by TomWFox** [comment]
@BenniPlejd can you try this link to the advisories section -> https://github.com/parse-community/parse-server/security/advisories

**Comment by acinader** [comment]
@BenniPlejd I got it.  thanks.  I'm going to look into how we use github to discuss and keep you up to date on resolving...

@TomWFox i'll leave this open to see if you want to revise the published procedure?

**Comment by TomWFox** [comment]
Seems odd that non-members can't create advisories but it should still be useful as we can then publish as a know vulnerability when solved.

**Comment by acinader** [comment]
nice.  i'll close this now then.

**Comment by acinader** [comment]
@BenniPlejd are you able to see any of the conversations we're having about the advisory?  this is my first time using these features of GitHub.  we invited you to participate, but it is not clear to me if we did that right, or if it is even supported...

**Comment by BenniPlejd** [comment]
@acinader Yes, I can see it!
