### ISSUE TITLE
Prevent change of user pointer and date 

### ISSUE THREAD

**Issue by farhad2161** [parse-community/parse-server#5688]
I have an "owner" field which its type is _User pointer and also a "publishedAt" field which its type is Date. When a user adds something, both field filled correctly, but later when I use masterkey to update some other columns of that row, the "owner" field automatically changes to undefined and "publishedAt" changes to current date time!

How can i prevent changing of those fields?

**Comment by dplewis** [comment]
Can you post server logs or write a failing test case?

**Comment by farhad2161** [comment]
I checked the log and found my bug.
Thanks
