### ISSUE TITLE
Client Class Creation not working again at all on Android Parse Client

### ISSUE THREAD

**Issue by hashweather** [parse-community/parse-server#5714]
Hello all,

Before now Client Class creation was configurable on demand. But right now, I discovered that even after allowing client class creation on my Server Dashboard, I still can't allow Clients to create classes on the fly. Can this behaviour be restored?

I should be able to allow Clients Create Classes once configured as before.

I am using the latest version of the Parse Android Client

` implementation "com.github.parse-community.Parse-SDK-Android:parse:1.20.0"
`

**Comment by davimacedo** [comment]
Nothing has changed regarding this and you should be able to create class from client if allowClientClassCreation option is set to true in parse-server. Can you make sure this option is realy set in your parse-server (not dashboard) and share the error message that you are receiving?
