### ISSUE TITLE
Custom Auth Adapter: Uncaught internal Server Error in rest.js

### ISSUE THREAD

**Issue by fastrde** [parse-community/parse-server#5724]
### Issue Description

I used my custom LDAP-Auth Adapter that works fine in Parse-Server 2.4.2 and 2.8.2. In Version 3.4.4 I get a "Uncaught internal server error. Cannot read property 'code' of undefined"-Error when I use a wrong username/password combination (with correct credentials the login works fine).
Problem: In the catch-clause in rest.js line 165 is no valid error object.

#### Stacktrace:
    TypeError: Cannot read property 'code' of undefined
    at handleSessionMissingError (/opt/myude-server/node_modules/parse-server/lib/rest.js:171:38)
    at Promise.resolve.then.then.catch.error (/opt/myude-server/node_modules/parse-server/lib/rest.js:165:5)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)

#### validateAuthData:
    class LDAPAuth {
      constructor() {}   
      
      validateAuthData(authData, options) {
          let authenticator = new Authenticator();
          return authenticator.ldapAuthenticate(authData).then((valid) => {
            if (valid) {
              return;
            }   
            throw new Parse.Error(Parse.Error.OBJECT_NOT_FOUND, 'LDAP auth not found for this user.'); //This Error is not passed to the restController 
        }); 
      }   

      validateAppId() {
        return Promise.resolve();
      }   
    }

In the version that works in 2.4.2 and 2.8.2 I didn't require Parse. In the included Auth-Adapters I saw the line `var Parse = require("parse/node").Parse`. I tried to include that line but nothing changed. I also tried to `throw {code: 123, message: 'something'}` but the error is still the same. When I explicitly generate a new Parse.Error in rest.js line:165 I got a valid Error-Message on the client "Insufficent Auth."

_Edit: In the git version auf rest.js the problem is located at line 249-251_

### Expected Results

The Error should be handled and send to the client.

### Actual Outcome

Internal Server Error

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 3.4.4
  - Operating System:  Ubuntu
  - Hardware: vmware
  - Localhost or remote server?: selfhosted

**Comment by fastrde** [comment]
Something went wrong in my code... could be 'reject()' without a value or some other minor changes i tried. Custom Adapter is now working again.

**Comment by Dealerpriest** [comment]
I have the same issue. What made it work for you @fastrde?
