### ISSUE TITLE
Push device token sometimes not saved

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-server#5748]
### Issue Description

I see that ~2% of device tokens are not saved in the database. This includes iOS and Android devices.

Online research indicates that other people experience similar issues, e.g.
- https://stackoverflow.com/questions/30395044/parse-push-notification-android-device-token-not-saved-in-some-cases (2015)

For Android the setup is:

`ParseInstallation.getCurrentInstallation().saveInBackground(new SaveCallback() { ... } );`

For iOS the setup is:

```
extension AppDelegate {
    
    func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {

        DispatchQueue.global(qos: DispatchQoS.QoSClass.userInitiated).async {

            guard let installation = PFInstallation.current() else {
                return
            }
            
            installation.setDeviceTokenFrom(deviceToken)
            installation.saveInBackground { ... }
        }
    }
}
```

In both cases the methods are called every time on app launch / resume.

Note:
`PARSE_SERVER_CLEANUP_INVALID_INSTALLATIONS` is not enabled.

### Steps to reproduce

Was not able to reproduce it, has only been observed in live app.

_For Android:_
Could it be that [onNewToken](https://github.com/parse-community/Parse-SDK-Android/blob/966a740a13bcd198d51691fe8b4141aeb4644de9/fcm/src/main/java/com/parse/fcm/ParseFirebaseMessagingService.java#L14) is not called in some cases? It should be called at least for new app installations when a new token is generated.

Some users suggest to manually set the token with:

```
FirebaseInstanceId.getInstance().getInstanceId().addOnSuccessListener(new OnSuccessListener<InstanceIdResult>() {
        @Override
        public void onSuccess(InstanceIdResult instanceIdResult) {
            String token = instanceIdResult.getToken();
            // send it to server
        }
    });
```
 
Is that a necessary workaround for the issue, or is there a bug to fix in the client SDK or server side?

_For iOS:_
The token is requested on app launch / resume and has to be manually set for the installation. So even more surprising that this fails sometimes. Hints to a server side issue since both SDKs are affected.

### Expected Results

- For Android in every case the app was installed trough the Google Play Store, so we can assume Google Play Service are installed and the device token should be retrieved and stored in the DB.
- For iOS the device token must be retrieved and stored in the DB in every case, regardless of the user's push notification permissions alert choice.

### Actual Outcome

Device token not saved in some cases.

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 3.4.4

- **Client**
  - Parse-SDK-Android:parse:1.18.5
  - Parse-SDK-Android:fcm:1.18.5

- **Database**
  - MongoDB

**Comment by mtrezza** [comment]
The code has since been changed in Android and we have the tokens now set for 100% of installations. 

We are now manually requesting and setting the token:
```
FirebaseInstanceId.getInstance().getInstanceId().addOnSuccessListener(new OnSuccessListener<InstanceIdResult>() {
        @Override
        public void onSuccess(InstanceIdResult instanceIdResult) {
            String token = instanceIdResult.getToken();
            ParseInstallation.getCurrentInstallation().setDeviceToken(token);
            ParseInstallation.getCurrentInstallation().saveInBackground(...);
        }
    });
```

We also upgraded to
- `com.google.gms:google-services:4.3.0` and
- `implementation 'com.github.parse-community.Parse-SDK-Android:parse:1.20.0'`
- `implementation 'com.github.parse-community.Parse-SDK-Android:fcm:1.20.0'`

Since we did both changes at the same time it's hard to tell which of the two helped. Can anyone observing the same issue weigh in?

**Comment by mtrezza** [comment]
Update: Since the code change there are 0,18% of Android devices without token, compared to 8,5% where the token was supposed to be set automatically.

**Comment by funkenstrahlen** [comment]
As changing your client side code helped this is more likely an issue in the Android SDK of parse instead of the server?

https://github.com/parse-community/Parse-SDK-Android

**Comment by mtrezza** [comment]
I agree.

**Comment by funkenstrahlen** [comment]
Thank you for documenting this issue so clearly and investigating!

**Comment by GPack1** [comment]
> The code has since been changed in Android and we have the tokens now set for 100% of installations.
> 
> We are now manually requesting and setting the token:
> 
> ```
> FirebaseInstanceId.getInstance().getInstanceId().addOnSuccessListener(new OnSuccessListener<InstanceIdResult>() {
>         @Override
>         public void onSuccess(InstanceIdResult instanceIdResult) {
>             String token = instanceIdResult.getToken();
>             ParseInstallation.getCurrentInstallation().setDeviceToken(token);
>             ParseInstallation.getCurrentInstallation().saveInBackground(...);
>         }
>     });
> ```
> 
> We also upgraded to
> 
> * `com.google.gms:google-services:4.3.0` and
> * `implementation 'com.github.parse-community.Parse-SDK-Android:parse:1.20.0'`
> * `implementation 'com.github.parse-community.Parse-SDK-Android:fcm:1.20.0'`
> 
> Since we did both changes at the same time it's hard to tell which of the two helped.
> My guess is that the solution was setting the token manually.
> 
> If setting the token manually is a safer solution and setting it automatically we should update the docs with a note.
> 
> Can anyone observing the same issue weigh in?

Same issue here with Parse-SDK-Android 1.21.0, sometimes deviceToken results in (undefined)

**Comment by mtrezza** [comment]
@GPack1 We had that with new FCM tokens and were actually able to reproduce this.

However, this is not parse server related, hence issue closed, continues in #966.

**Comment by ramiro-ciocca** [comment]
@mtrezza hello, where in the app did you put that code to manually request and set the token?
Im having simmilar issue where the token is not refreshing in parse when outdated in fcm.
Thanks!

**Comment by mtrezza** [comment]
@ramiro-ciocca you can put this where ever it makes sense according to your app logic.

The [docs](https://firebase.google.com/docs/cloud-messaging/android/client#sample-register) say:

> On initial startup of your app, the FCM SDK generates a registration token for the client app instance. If you want to target single devices or create device groups, you'll need to access this token by extending FirebaseMessagingService and overriding onNewToken.
> 
> This section describes how to retrieve the token and how to monitor changes to the token. Because the token could be rotated after initial startup, you are strongly recommended to retrieve the latest updated registration token.
> 
> The registration token may change when:
> 
> The app deletes Instance ID
> The app is restored on a new device
> The user uninstalls/reinstall the app
> The user clears app data.

So one way to interpret this is that the token should be updated at least with every app start.
