### ISSUE TITLE
How to catch Error from logging in java script (React native)

### ISSUE THREAD

**Issue by Azerilla** [parse-community/parse-server#5752]
How can I find out my user login successfully in react native .according to document log in has no error callback

**Comment by davimacedo** [comment]
@Azerilla please use https://stackoverflow.com/questions/tagged/parse-platform for code related questions. Anyway, please try something like this:

```
try {
  const user = await Parse.User.logIn("myname", "mypass");
} catch (e) {
  console.log('Here is your error:', e);
}
```
