### ISSUE TITLE
error when use livequery with query.fields( updated, may someone help make a PR?)

### ISSUE THREAD

**Issue by akg1234** [parse-community/parse-server#5764]
### Issue Description
get error when using live query with query.fields
but this work on 2.8.4

### Steps to reproduce

this is OK

```
{
  "op": "subscribe",
  "requestId": 1,
  "query": {
      "className": "Player",
      "where": {"name": "test"}
  },
  "sessionToken": "" // Optional
}
```
this get error

```
{
  "op": "subscribe",
  "requestId": 1,
  "query": {
      "className": "Player",
      "where": {"name": "test"},
      "fields": ["name"] // Optional
  },
  "sessionToken": "" // Optional
}
```

### Expected Results
{"op":"create","clientId":"xxx","requestId":10,"object":xxxxxxx,"original":null}

### Actual Outcome

```
(node:1468) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'className' of null

    at Client._toJSONWithFields (/rbd/pnpm-volume/3de49c66-6120-4e8e-822d-0dc5af59b3dd/node_modules/.registry.npmjs.org/parse-server/3.5.0/node_modules/parse-server/lib/LiveQuery/Client.js:95:50)

    at Client.pushCreate (/rbd/pnpm-volume/3de49c66-6120-4e8e-822d-0dc5af59b3dd/node_modules/.registry.npmjs.org/parse-server/3.5.0/node_modules/parse-server/lib/LiveQuery/Client.js:79:39)

    at _matchesCLP.then.then (/rbd/pnpm-volume/3de49c66-6120-4e8e-822d-0dc5af59b3dd/node_modules/.registry.npmjs.org/parse-server/3.5.0/node_modules/parse-server/lib/LiveQuery/ParseLiveQueryServer.js:293:33)

    at process._tickCallback (internal/process/next_tick.js:68:7)

(node:1468) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
```

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 3.0.0-3.5.0
  - Operating System:     [FILL THIS OUT]
  - Hardware:             [FILL THIS OUT]
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): [FILL THIS OUT]

- **Database**
  - MongoDB version: [FILL THIS OUT]
  - Storage engine:  [FILL THIS OUT]
  - Hardware:        [FILL THIS OUT]
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): [FILL THIS OUT]

**Comment by davimacedo** [comment]
@akg1234 thanks for reporting. Would you be willed to open a PR with a failing test for this case?

**Comment by akg1234** [comment]
How to make a pull request?

> @akg1234 thanks for reporting. Would you be willed to open a PR with a failing test for this case?

**Comment by TomWFox** [comment]
@akg1234 Check out the [contributing guide](https://github.com/parse-community/parse-server/blob/master/CONTRIBUTING.md) - first steps are to fork the parse server repo and clone it to your local machine.

**Comment by akg1234** [comment]
> @akg1234 Check out the [contributing guide](https://github.com/parse-community/parse-server/blob/master/CONTRIBUTING.md) - first steps are to fork the parse server repo and clone it to your local machine.

oh
this maybe too difficult for me.
i only know the problem but i don't know how to fix it.

**Comment by davimacedo** [comment]
@akg1234 you don't need to fix it. If possible we only wanted you to write a failing test case that shows the problem and open a PR with it so other developers can tackle the problem. You can find the other Live Query test cases in this [file](https://github.com/parse-community/parse-server/blob/master/spec/ParseLiveQueryServer.spec.js) and you can use them as reference to write a new one.

**Comment by akg1234** [comment]
> @akg1234 you don't need to fix it. If possible we only wanted you to write a failing test case that shows the problem and open a PR with it so other developers can tackle the problem. You can find the other Live Query test cases in this [file](https://github.com/parse-community/parse-server/blob/master/spec/ParseLiveQueryServer.spec.js) and you can use them as reference to write a new one.

it is still too difficult to me
i update the description of the bug
hope someone can help me
