### ISSUE TITLE
Can't find Python executable "python", you can set the PYTHON env variable.

### ISSUE THREAD

**Issue by ozbillwang** [parse-community/parse-server#5778]
### Issue Description

when run `docker build`, I got below error

```
$ docker build -t parse-server . 
...
> bcrypt@3.0.6 install /tmp/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.12.0
node-pre-gyp info using node@10.16.0 | linux | x64
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp info check checked for "/tmp/node_modules/bcrypt/lib/binding/bcrypt_lib.node" (not found)
node-pre-gyp http GET https://github.com/kelektiv/node.bcrypt.js/releases/download/v3.0.6/bcrypt_lib-v3.0.6-node-v64-linux-x64-musl.tar.gz
node-pre-gyp http 404 https://github.com/kelektiv/node.bcrypt.js/releases/download/v3.0.6/bcrypt_lib-v3.0.6-node-v64-linux-x64-musl.tar.gz
node-pre-gyp WARN Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v3.0.6/bcrypt_lib-v3.0.6-node-v64-linux-x64-musl.tar.gz
node-pre-gyp WARN Pre-built binaries not found for bcrypt@3.0.6 and node@10.16.0 (node-v64 ABI, musl) (falling back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://github.com/kelektiv/node.bcrypt.js/releases/download/v3.0.6/bcrypt_lib-v3.0.6-node-v64-linux-x64-musl.tar.gz
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.16.0 | linux | x64
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.16.0 | linux | x64
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
```
### Steps to reproduce

 
```
docker build -t parse-server . 
```

I tested in release 3.4.4 and 3.5.0, same issue

### Expected Results

I should get the docker image to be built. I am interesting, how the image to be built and push to hub.docker.io here?

### Actual Outcome

```
Can't find Python executable "python", you can set the PYTHON env variable.
```

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : [3.5.0 and 3.4.4]
  - Operating System:     [MacOS]
  - Hardware:             [MacOs]
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): [not test at this stage]

- **Database**
  - MongoDB version: [not test at this stage]
  - Storage engine:  [not test at this stage]
  - Hardware:        [not test at this stage]
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): [not test at this stage]

### Logs/Trace

If I add `python` in `Dockerfile`, I will get another errors, such as no `make`, no `gcc`, etc.

**Comment by ozbillwang** [comment]
After switch the base image to `node:10.16.0`, I can `docker build` now.

```diff
diff --git a/Dockerfile b/Dockerfile
index 581b3f6..cb6c259 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -1,8 +1,6 @@
 # Build stage
-FROM node:lts-alpine as build
+FROM node:10.16.0 as build
 
-RUN apk update; \
-  apk add git;
 WORKDIR /tmp
 COPY package*.json ./
 RUN npm ci
@@ -10,7 +8,7 @@ COPY . .
 RUN npm run build
 
 # Release stage
-FROM node:lts-alpine as release
+FROM node:10.16.0 as release
 #VOLUME /parse-server/cloud /parse-server/config
 
 WORKDIR /parse-server
```

The package `bcrypt` clearly mentioned, it doesn't support alpine nicely. 

https://github.com/kelektiv/node.bcrypt.js/wiki/Installation-Instructions#alpine-linux-based-images

Let me know which base image should I go with.

**Comment by ozbillwang** [comment]
Seems this PR #5248 made the trouble.

**Comment by davimacedo** [comment]
@ozbillwang have you tried the workaround specified in the [link](https://github.com/kelektiv/node.bcrypt.js/wiki/Installation-Instructions#alpine-linux-based-images) you sent?

**Comment by ozbillwang** [comment]
@davimacedo 

I did. But can't successfully build the image.

**Comment by davimacedo** [comment]
I tested here now and, besides the error messages about bcrypt package installation, the image was successfully created and I successfully started/used a container. Wasn't it your case?

As you can see [here](https://github.com/parse-community/parse-server/blob/d83a0b680854f52ce30205d3558c0133d7f8cf19/src/password.js#L6) Parse Server try to use bcrypt, but, if it does not work, it uses bcryptjs. So it should be working for you besides the errors in the log.

**Comment by ozbillwang** [comment]
Do you mean I can ignore the error about bcrypt?

Sure, if this is the case.

**Comment by davimacedo** [comment]
Yes. I think you can ignore. I saw in the commit history that both options are tried because bcrypt is supposed to have a better performance than bcryptjs. If the performance for creating/validating passwords is a concern for you, you should go with your solution and change the node version you are running on your container. Otherwise you can just ignore.
