### ISSUE TITLE
Reduce Test Output

### ISSUE THREAD

**Issue by acinader** [parse-community/parse-server#5793]
The current test output report on each test, pass or fail.  In Travis, this much output provides little value, but makes it difficult to isolate filing tests as scrolling through all of the output is cumbersome

I suggest that we revert to the standard jasmine output from the current to reduce the output.

Probably worth noting here that I made it this verbose...

**Comment by dplewis** [comment]
I agree, we should take a page from the JavaScript SDK. Also I think this will increase the speed of the test as logging is notoriously slow.

**Comment by acinader** [comment]
on it.
