### ISSUE TITLE
Option to prevent cascade saving

### ISSUE THREAD

**Issue by RaschidJFR** [parse-community/parse-server#5811]
**Is your feature request related to a problem? Please describe.**
When saving an object in which properties there's a pointer to another object, the SDK launches a batch operation to save all modifications made to all nested objects, which is great but... when you don't have write access to any of those (for example when you're saving a Message object pointing to another user's profile) you need to make sure nested objects are not `dirty` or call `rever()` in order not to get the `Object not found` error.

**Describe the solution you'd like**
A parameter in the saving options, something like `ParseObject.save(null, {cascadeSave: false})` would address this issue.

**Describe alternatives you've considered**
A workaround for now is to call `Parse.Object.revert()` on all objects to which you know this user does not have write permissions.

**Comment by davimacedo** [comment]
I think this is an issue for the JS SDK, right? Can you please open it [here](https://github.com/parse-community/Parse-SDK-JS/issues/new/choose)?

**Comment by oallouch** [comment]
Oh, the time I lost with this one...

**Comment by acinader** [comment]
does that mean you'll help solve it :) ??? :).
