### ISSUE TITLE
hope GridFSBucketAdapter support getFileStream interface for client request range content

### ISSUE THREAD

**Issue by postgetme** [parse-community/parse-server#5834]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by davimacedo** [comment]
Can you please add more details about what you need? The use-case is actually not so clear to me.

**Comment by postgetme** [comment]
thanks for your reply, my use-case is [like this](https://github.com/parse-community/parse-server/pull/2437)

**Comment by davimacedo** [comment]
I read the whole thread of the PR you mentioned but it is still not so clear for me what you need. Would you be able to give more details and/or send a PR with your suggested changed?

**Comment by dplewis** [comment]
@postgetme I opened a PR https://github.com/parse-community/parse-server/pull/6028. Can you test and see if it works for you?
