### ISSUE TITLE
in the node can not use  **Parse.Cloud.beforeLogin** ?

### ISSUE THREAD

**Issue by lybaiyy123** [parse-community/parse-server#5851]
### Issue Description
in the node
`var express = require('express');`
`var parse_node=require('parse/node')`
`var ParseServer = require('parse-server').ParseServer;`

but i can not use “Parse.Cloud.beforeLogin”

in  the @types/parse/index.d.ts no  **beforeLogin** but have two **beforeFind**

        function afterDelete(arg1: any, func?: (request: AfterDeleteRequest) => Promise<void> | void): void;
        function afterSave(arg1: any, func?: (request: AfterSaveRequest) => Promise<void> | void): void;
        function beforeDelete(arg1: any, func?: (request: BeforeDeleteRequest) => Promise<void> | void): void;
        function beforeSave(arg1: any, func?: (request: BeforeSaveRequest) => Promise<void> | void): void;
        **function beforeFind(arg1: any, func?: (request: BeforeFindRequest) => Promise<void> | void): void;
        function beforeFind(arg1: any, func?: (request: BeforeFindRequest) => Promise<Query> | Query): void;**
        function afterFind(arg1: any, func?: (request: AfterFindRequest) => Promise<any> | any): void;
        function define(name: string, func?: (request: FunctionRequest) => Promise<any> | any): void;
        function httpRequest(options: HTTPOptions): Promise<HttpResponse>;
        function job(name: string, func?: (request: JobRequest) => Promise<void> | void): HttpResponse;
        function run(name: string, data?: any, options?: RunOptions): Promise<any>;
        function useMasterKey(): void;

### Actual Outcome

can you tell me how to get the  **Parse.Cloud.beforeLogin** ?
thak you very much
### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : [FILL THIS OUT] 3.6
  - Operating System:     [FILL THIS OUT] centos 7.2
  - Hardware:             [FILL THIS OUT]
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): [FILL THIS OUT] Localhost 

- **Database**
  - MongoDB version: [FILL THIS OUT] 4.0
  - Storage engine:  [FILL THIS OUT]
  - Hardware:        [FILL THIS OUT]
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): [FILL THIS OUT]

**Comment by dplewis** [comment]
Great catch! Would you like to submit a fix on the DefinitelyTyped Repo?

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/parse/index.d.ts#L829

**Comment by lybaiyy123** [comment]
I don't think I can.
Because I can't TS
Only use
iam so sorry...

**Comment by lybaiyy123** [comment]
another bug is
console.log("Parse.ErrorCode.ACCOUNT_ALREADY_LINKED:"+Parse.ErrorCode.ACCOUNT_ALREADY_LINKED)
console.log("Parse.Error.ACCOUNT_ALREADY_LINKED:"+Parse.Error.ACCOUNT_ALREADY_LINKED)
Parse.ErrorCode is worry！
Cannot read property 'ACCOUNT_ALREADY_LINKED' of undefined

**Comment by dplewis** [comment]
Closing via https://github.com/DefinitelyTyped/DefinitelyTyped/pull/39072
