### ISSUE TITLE
unknown option `--mountGraphQL'

### ISSUE THREAD

**Issue by Moumouls** [parse-community/parse-server#5859]
### Issue Description

When we install a fresh instance of `Parse Server 3.6` it seems that there are a gap between documentation and package capabilities. (I'm on MacOS)
`unknown option --mountGraphQL` 

### Steps to reproduce

* Install a fresh instance: `npm -g install parse-server`
* Try ton run: `parse-server --appId APPLICATION_ID --masterKey MASTER_KEY --databaseURI mongodb://localhost/test --mountGraphQL --mountPlayground`

### Expected Results

To have option `--mountGraphQL` working

### Actual Outcome

Option not found `--mountGraphQL`

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 3.6
  - Operating System:    MacOS
  - Hardware:             Macbook Pro
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): localhost

- **Database**
  - MongoDB version: `mongo-runner`
  - Storage engine:  [FILL THIS OUT]
  - Hardware:        [FILL THIS OUT]
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): localhost

### Logs/Trace
```
❯ npm list -g --depth 0
/Users/antoinecormouls/.npm-packages/lib
├── mongodb-runner@4.7.1
├── parse-server@3.6.0
└── pure-prompt@1.9.0
```
```
❯ parse-server --appId APPLICATION_ID --masterKey MASTER_KEY --databaseURI mongo
db://localhost/test --mountGraphQL --mountPlayground
error: unknown option `--mountGraphQL'
```

**Comment by davimacedo** [comment]
The --mountGraphQL option is actually supported in the version 3.6.0. I've just installed it again from scratch and it worked for me. It is really strange what is happening for you case. It seems that parse-server is not pointing out the latest package you installed, but to an old one. Could you try to  run the bin directly from the parse-server installation folder? It would be something like this:

```
/Users/antoinecormouls/.npm-packages/lib/node_modules/parse-server/bin/parse-server --appId APPLICATION_ID --masterKey MASTER_KEY --databaseURI mongodb://localhost/test --mountGraphQL --mountPlayground
```

Could you please also confirm the npm and nodejs versions that you are using?

**Comment by Moumouls** [comment]
Yes it works with `~/.npm-packages/bin/parse-server` and yes it seems that `parser-server` don't execute the correct `/bin`
So it's a problem with my setup.
We can close this issue !

node: `v10.15.1`
npm: `6.4.1`

**Comment by davimacedo** [comment]
Nice. I hope you enjoy the GraphQL API. If you have any feedback let me know :)
