### ISSUE TITLE
Parse 3.7.0 missing APN module

### ISSUE THREAD

**Issue by johnnydimas** [parse-community/parse-server#5867]
### Issue Description

After updating to ParseServer 3.7.0 (latest release), I can no longer start my server. It appears one of the modules (apn) for the @parse/push-adapter is missing. If I manually install the apn module, and start the parse-server, it works as usual. I do not use push-notifications in my setup, so I did not have the module installed previously.

### Steps to reproduce

Update to ParseServer 3.7.0 and start the server. 

 
### Expected Results

Server should start as usual. 

### Actual Outcome

I receive the following error.

`unhandledRejection error:  { Error: Cannot find module 'apn'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/***/node_modules/@parse/push-adapter/lib/APNS.js:12:12)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3) code: 'MODULE_NOT_FOUND' }`

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 3.7.0
  - Operating System:     macOS Mojave 10.14.5
  - Hardware:             MacBook Pro 2018
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): localhost

- **Database**
  - MongoDB version: 3.6.12
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): localhost

**Comment by davimacedo** [comment]
I think we didn't release this package correctly. I will try to publish a new release and fix it.

**Comment by douglasmuraoka** [comment]
@johnnydimas as a temporary fix, you can do the following:

Clone `parse-server-push-adapter` repo, and run `git checkout updateAPN && npm install && npm link`.
And at the `parse-server` directory, `npm install && npm link @parse/push-adapter`.

It works for me :)

**Comment by dplewis** [comment]
I did a clean npm install (removed node_modules and package-lock)

You can see it working https://github.com/parse-community/Parse-SDK-JS/pull/876

**Comment by johnnydimas** [comment]
@dplewis I actually tried that as well before I posted the issue. It didn't seem to do the trick to me.

**Comment by davimacedo** [comment]
@johnnydimas could you please install parse-server from the master branch and check if the problem was solved for you? In a positive case, we will release a new version.

**Comment by johnnydimas** [comment]
@davimacedo That did it for me, thanks for the assistance!

**Comment by davimacedo** [comment]
Nice. We will launch release 3.7.2 with the fix soon.

**Comment by Vortec4800** [comment]
I just tried to do a fresh install of server 3.7.2 and am getting this error during npm install:

No matching version found for apn@^v3.0.2-parse

Tried deleting the package lock and modules dir and do a clean install, but no difference. Seems to be related to this issue, if you want I can create a new one though.

**Comment by davimacedo** [comment]
@Vortec4800 can you please share the steps that you are using to install parse-server 3.7.2 and also the versions of node.js and npm that you are using?

**Comment by Vortec4800** [comment]
Sure. I've got these (along with other) frameworks in my package file:

    "parse": "^2.6.0",
    "parse-server": "^3.7.2",
    "parse-server-mailgun-adapter-template": "^1.1.7",

Running Node 9.11.2 and npm 5.6.0

**Comment by davimacedo** [comment]
I could reproduce here. The problem is happening for node.js <= 9. Could you upgrade Node >= 10?

**Comment by Vortec4800** [comment]
We ran into some compatibility issues with Node 10, so we decided to stick with 9. Is Parse server no longer supported in Node 9?

**Comment by davimacedo** [comment]
It seems that the problem is not the node version itself but the npm version, which is failing to install the package from the github tag. I tested here Node 9 with latest version of npm and it worked for me. Can you please try to upgrade npm and check again?
```
npm install -g npm@latest
```

**Comment by Vortec4800** [comment]
I updated npm to 5.10 and that did the trick. Thank you!

**Comment by laticq** [comment]
I have the same problem with `npm install parse-server`, version latest: 3.7.2

NPM LOG
```
...
1 verbose cli   'install',
1 verbose cli   'parse-server' ]
2 info using npm@6.10.3
3 info using node@v10.16.3
4 verbose npm-session f8bccb23010efb78
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 https://registry.npmjs.org/parse-server 370ms
8 silly pacote tag manifest for parse-server@latest fetched in 400ms
...
101 silly fetchPackageMetaData error for apn@github:parse-community/node-apn#semver:^v3.0.2-parse Error while executing:
101 silly fetchPackageMetaData undefined ls-remote -h -t ssh://git@github.com/parse-community/node-apn.git
101 silly fetchPackageMetaData
101 silly fetchPackageMetaData
101 silly fetchPackageMetaData spawn git ENOENT
...
116 verbose Windows_NT 6.1.7601
117 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\laticq\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "parse-server"
118 verbose node v10.16.3
119 verbose npm  v6.10.3
120 error code ENOENT
121 error syscall spawn git
122 error path git
123 error errno ENOENT
124 error enoent Error while executing:
124 error enoent undefined ls-remote -h -t ssh://git@github.com/parse-community/node-apn.git
124 error enoent
124 error enoent
124 error enoent spawn git ENOENT
125 error enoent This is related to npm not being able to find a file.
126 verbose exit [ 1, true ]
```

**Comment by laticq** [comment]
I do not use the following features in my projects:
- graphql
- push
- s3-files
- redis

Are they required to install? Can I make the installation version without them or optionally?

**Comment by paivaric** [comment]
Hi @laticq 
This `undefined ls-remote -h -t ssh://git@github.com/parse-community/node-apn.git` means you don't have git installed. Check it using `git --version` and install it from here https://git-scm.com/download/win

**Comment by laticq** [comment]
> 
> 
> Hi @laticq
> This `undefined ls-remote -h -t ssh://git@github.com/parse-community/node-apn.git` means you don't have git installed. Check it using `git --version` and install it from here https://git-scm.com/download/win

Thank you, it worked. But earlier versions of parse-server could be installed without git, I would like to do without it... 
Why did this start to happen?

**Comment by TomWFox** [comment]
@laticq It is because @funkenstrahlen made a fix to the node-apn repo but they have not made a new release so he and @davimacedo made the decision to point to our own fork of node-apn instead. This means it is no longer being installed from npm but directly from GitHub instead.

**Comment by omairvaiyani** [comment]
+1 I'm getting the same issue on Node `lts-alpine` on docker. I'll see if I can dig a little deeper.

**Comment by funkenstrahlen** [comment]
Do you guys thing we should add the parse owned  node-apn repository to npm to make deploys work without git installed?

**Comment by funkenstrahlen** [comment]
We decided to create our own fork of node-apn because the existing repository is no longer actively maintained. With the fork we can fix required changes.

**Comment by davimacedo** [comment]
@omairvaiyani double check if your docker container has git installed. It is probably the issue.

@funkenstrahlen I agree with you. I think we can avoid all these issues by publishing our fork to npm. @acinader can you help us here?

**Comment by funkenstrahlen** [comment]
@acinader 
https://github.com/parse-community/node-apn

**Comment by funkenstrahlen** [comment]
Awesome! Thank you @acinader 😊👍
