### ISSUE TITLE
Implement global triggers

### ISSUE THREAD

**Issue by santiagosemhan** [parse-community/parse-server#5874]
There are situations where it's necessary to be able to execute functions globally.
For example beforeSave, afterSave, etc.

So what I propose is that things such as "*" can be implemented in the class name.

```javascript
Parse.Cloud.beforeSave("*", (request) => {
    // Do some cool stuffs
}
```

**Comment by mtrezza** [comment]
I don't see any immediate use case for this, beyond maybe logging. Can you provide some details for your use case?

**Comment by santiagosemhan** [comment]
I'm currently tracking createdBy and updatedBy fields in beforeSave triggers. I have to implement it for each class declared in cloud code. 
Another's API frameworks implement this kind of "hooks". For this reason, could be a great idea. It's just a simple proposal.

**Comment by acinader** [comment]
you could do this with inheritance today. You could make a base class that extends ParseObject and then all of your classes can extend your base class. Your base class can implement a before save and after save that does your common stuff.  If you want something specific for a class, implement its beforeSave method and be sure to call super.beforeSave(request).

**Comment by santiagosemhan** [comment]
Perfect! Could you provide me an example? 
I'll be implementing your solution!

**Comment by santiagosemhan** [comment]
Another's users with the same issue. (2 years ago )
https://stackoverflow.com/questions/43916050/parse-server-cloud-code-beforesave-on-parse-object

**Comment by acinader** [comment]
@santiagosemhan I don't have an example to point you to.  My response was just from thinking about it and how I would approach it.  But I'd be glad to help you with it if you'd like.  I would start by figuring out how to get it working with two different classes, so something like this:

1. create a base class the extends Parse.Object
2. put a 'beforeSave' function in it.
3. create two classes that extend your base class: SubClassA and SubClassB
4. register those two classes to map to a table in parse.  See how to extend Parse.Object in the docs
5. in one of the two subclasses, implement a beforeSave function and make sure to call super.beforeSave() in that function.  In the other subclass, don't bother with a beforeSave to prove that this works
6. register the before saves like Parse.Cloud.beforeSave('SubClassA', SubClassA.beforeSave) and then the same thing for SubClassB

That should do it.  When you save an instance of SubClassA, it'll call it's beforeSave, which will then do any class-specific stuff but also will call super.beforeSave.  In SubClassB where you have no class-specific beforeSave code, the super.beforeSave will just called as a result of inheritance.




That should do it for you.

**Comment by acinader** [comment]
and for the record, I don't think that it would be a bad thing to change the hook implementation to allow more than one hook to run using something like a regex and/or a list to match witch classes to apply a hook too, as well as allowing more than one 'beforeSave' observer, but I am not going to do that work any time soon myself, so either you give it a try (which I'd help you with and others might too) or in the meantime, you can try my method which does require some work, but will work today.

**Comment by santiagosemhan** [comment]
@acinader I did it as you proposed and works as expected. So, if I have time I will post the solution in stackoverflow. But, in other hands, I think that would be good to document this stuffs into the cloud code section.

**Comment by acinader** [comment]
great.  we'd also welcome a pull request on the documentation front if you think you could improve for this case.
