### ISSUE TITLE
I want to set up that users can only login on one client at the same time.

### ISSUE THREAD

**Issue by lybaiyy123** [parse-community/parse-server#5880]
Every user can login on different clients, but that's not what I want.

I want to set up that users can only login on one client at the same time.

What can I do?

**Comment by lybaiyy123** [comment]
Delete data session class different from this user session after login?

**Comment by davimacedo** [comment]
Let's say you have a user that is logged in a certain device. Then this same user tries to log in in another device. What do you want to happen? Not allow him to log in the other device? Or allow him to log in the other device and automatically log out him from the first device?

Both scenarios can be achieved with a cloud code function.

**Comment by lybaiyy123** [comment]
> Let's say you have a user that is logged in a certain device. Then this same user tries to log in in another device. What do you want to happen? Not allow him to log in the other device? Or allow him to log in the other device and automatically log out him from the first device?
> 
> Both scenarios can be achieved with a cloud code function.

allow him to log in the other device and automatically log out him from the first device?
how to do it ？ delete him old session ？

**Comment by davimacedo** [comment]
Yes. I'd write a cloud function like the one below. In your app you can call this cloud function instead of the regular logIn operation.

```
Parse.Cloud.define('logIn', async req => {
  const username = req.params.username;
  const password = req.params.password;
  const user = await Parse.User.logIn(username, password);
  const sessionToken = user.getSessionToken();
  const oldSessionsQuery = new Parse.Query(Parse.Session);
  oldSessionsQuery.equalTo('user', user);
  oldSessionsQuery.notEqualTo('sessionToken', sessionToken);
  const oldSessions = await oldSessionsQuery.find({ useMasterKey: true });
  await Parse.Object.destroyAll(oldSessions, { useMasterKey: true });
  return user;
});
```

**Comment by lybaiyy123** [comment]
oh ,thanks

Why don't you judge the length of oldSessions?

**Comment by davimacedo** [comment]
It is just an example. Feel free to optimize it :)
