### ISSUE TITLE
 Parse.Object.unPinAllObjects()  No effect at all.

### ISSUE THREAD

**Issue by lybaiyy123** [parse-community/parse-server#5885]
i use             object.pin() save data in localstorage.
but when i use  Parse.Object.unPinAllObjects() to delect all localstorage data, itis No effect at all,
Using localstorage to view data in Firefox and Google Browser, the data still exists

**Comment by davimacedo** [comment]
@lybaiyy123 can you please open the issue in the SDK repository including as more details as possible? Thanks.
