### ISSUE TITLE
Is there any way to edit Class Level Permissions Programatically?

### ISSUE THREAD

**Issue by stevestencil** [parse-community/parse-server#5888]
With the latest version of parse we can now have a class level permission set for the "count" operation. This makes it so that all class level permissions have to be updated to support this operation, otherwise you'll get permission errors when calling "count". I know we can do this via the dashboard but if other devs are working in the same project they'll have to update the same permissions on their local instance, dev instances, staging instances, etc. Ideally I could update the class level permissions programmatically once parse starts so that any other devs working on the project won't have to worry.

Is there any way to edit the class level permissions through the API?

**Comment by Moumouls** [comment]
I think you can do this with the `REST API`:
[Rest Guide CLP](https://docs.parseplatform.org/rest/guide/#restricting-class-creation)
```
// POST http://my-parse-server.com/schemas/Announcement
// Set the X-Parse-Application-Id and X-Parse-Master-Key header
// body:
{
  classLevelPermissions:
  {
    "find": {
      "requiresAuthentication": true,
      "role:admin": true
    },
    "get": {
      "requiresAuthentication": true,
      "role:admin": true
    },
    "create": { "role:admin": true },
    "update": { "role:admin": true },
    "delete": { "role:admin": true }
  }
}
```

**Comment by stevestencil** [comment]
this is exactly what I need... Thank you!

**Comment by dplewis** [comment]
@stevestencil This has been discussed adding to the JS SDK [CLP needs an API](https://github.com/parse-community/Parse-SDK-JS/issues/583). Would like to get started on this?

**Comment by stevestencil** [comment]
I would be happy to add this... this would be my first time so I will need some guidance... I'd imagine i'll be adding it to the ParseSchema.js file?

**Comment by davimacedo** [comment]
Yes. It should be added in the [ParseSchema.js](https://github.com/parse-community/Parse-SDK-JS/blob/master/src/ParseSchema.js) file of the JS SDK.

**Comment by unmec** [comment]
Just a few notes:

- ```classLevelPermissions``` in req body should be double quoted otherwise Parse will complain about JSON format

- If I run this command on an existing Class, Parse will return 400 saying that Class exist already and unable to change CLP. However creating a new Class is fine

**Comment by davimacedo** [comment]
You can actually add and remove fields of an existing class. But you can't change an existing field of an existing class.

**Comment by unmec** [comment]
@davimacedo Very helpful as this is not explicitly stated in doc, thanks!
```
Modifying the schema
You can add or delete columns to a schema
```

**Comment by unmec** [comment]
Um, just want to add that the docs are clear actually with an example of PUT command that I didn't catch earlier. ;-)

**Comment by dplewis** [comment]
Closing via https://github.com/parse-community/Parse-SDK-JS/pull/960
