### ISSUE TITLE
Rest API with angular

### ISSUE THREAD

**Issue by Eolykab** [parse-community/parse-server#5892]
Getting this error on the client app (Angular) POST http://localhost:1337/parse/users 403 (Forbidden)

This is how I initialize it     
Parse.initialize(environment.appId); 
(Parse as any).serverURL = environment.serverUrl;
export const environment = {
  production: false,
  serverUrl: 'http://localhost:1337/parse',
  appId: 'xzFvFNe3hovXg1zHxXhI',
  myMasterKey: 'H137HRAwIZcC1TF2MiAu'
};
This below is the server config : 
const api = new ParseServer({
    databaseURI: databaseUri || 'mongodb://localhost:27017/dev',
    cloud: process.env.CLOUD_CODE_MAIN || __dirname + '/cloud/main.js',
    appId: process.env.APP_ID || 'myAppId',
    masterKey: process.env.MASTER_KEY || 'myMasterKey', //Add your master key here. Keep it secret!
    serverURL: process.env.SERVER_URL || 'http://localhost:1337/parse',  // Don't forget to change to https if needed
    liveQuery: {
        classNames: ["Posts", "Comments"] // List of classes to support for query subscriptions
    }
});
env server : 

PUBLIC_SERVER_URL='http://localhost:1337'
PARSE_SERVER_MOUNT='/parse'
MONGODB_URI='mongodb://localhost:27017/dop-api'
PORT=1337
APP_NAME='DOP API'
APP_ID='xzFvFNe3hovXg1zHxXhI'
MASTER_KEY='H137HRAwIZcC1TF2MiAu'

Can you help?

**Comment by davimacedo** [comment]
Can you also share the code that you are using to send the POST request?

**Comment by Eolykab** [comment]
This is what I am trying to implement. https://akveo.github.io/nebular/docs/auth/configuring-a-strategy#setup-api-configuration

These are my settings : 

import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { NbThemeModule, NbLayoutModule } from '@nebular/theme';
import { NbEvaIconsModule } from '@nebular/eva-icons';
import {HttpClientModule} from '@angular/common/http';
import {NbAuthModule, NbPasswordAuthStrategy} from '@nebular/auth';
import {environment} from '../environments/environment';
import {AuthGuardService} from './services/auth-guard.service';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    BrowserAnimationsModule,
    NbThemeModule.forRoot({ name: 'corporate' }),
    NbLayoutModule,
    NbEvaIconsModule,
    HttpClientModule,
    NbAuthModule.forRoot({
      strategies: [
        NbPasswordAuthStrategy.setup({
          name: 'email',
          baseEndpoint: environment.serverUrl,
          login: {
            endpoint: '/login',
            method: 'get'
          },
          register: {
            endpoint: '/users',
            method: 'post'
          },
          logout: {
            endpoint: '/logout',
            method: 'post',
          },
          requestPass: {
            endpoint: '/requestPasswordReset',
            method: 'post',
          },
          resetPass: {
            endpoint: '/users',
            method: 'post',
          },
        }),
      ],
      forms: {},
    }),
  ],
  providers: [
    AuthGuardService
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }

**Comment by davimacedo** [comment]
I don't see where you are setting the headers and it seems to be missing. You have to make sure that `NbPasswordAuthStrategy.setup` is configured to send `X-Parse-Application-Id` header.
