### ISSUE TITLE
GraphQL: How to query data from array of pointers

### ISSUE THREAD

**Issue by murshudov** [parse-community/parse-server#5894]
#### This is my query
``` graphql
query JobQuery {
  objects {
    getJob(objectId: "sqvJTrN9no") {
      title
      company {
        name
      }
      countries
    }
  }
}

```
#### and it returns
``` json
{
  "data": {
    "objects": {
      "getJob": {
        "title": "Sales Assistant",
        "company": {
          "name": "Gulfstream Distribution"
        },
        "countries": [
          {
            "__type": "Pointer",
            "className": "Country",
            "objectId": "lZ15JnGq7h"
          }
        ]
      }
    }
  }
}
```

#### I thought maybe something like this exists:
``` graphql
query JobQuery {
  objects {
    getJob(objectId: "sqvJTrN9no") {
      title
      company {
        name
      }
      countries
    }
    
    findCountry(where: { objectId: { _in: ["lZ15JnGq7h"]} }) {
      results {
        name
      }
    }
  }
}
```

#### Result: 
``` json
{
  "data": {
    "objects": {
      "getJob": {
        "title": "Sales Assistant",
        "company": {
          "name": "Gulfstream Distribution"
        },
        "countries": [
          {
            "__type": "Pointer",
            "className": "Country",
            "objectId": "lZ15JnGq7h"
          }
        ]
      },
      "findCountry": {
        "results": [
          {
            "name": "Azerbaijan"
          }
        ]
      }
    }
  }
}
```

#### I don't know how to include results from getJob query into findCountry query. Any help would be appreciated 😊

**Comment by davimacedo** [comment]
It works pretty much like you expect if you have a field that is a `Pointer` or a `Relation`. Since it is an `Array`, and an `Array` can have any kind of item, the Parse GraphQL Server does not know beforehand what kind of object you have there and can't make its fields automatically available. We can think about some solutions for this. Maybe allow the developer to specify the type of the array? @Moumouls @omairvaiyani @douglasmuraoka

**Comment by omairvaiyani** [comment]
One option is to introduce this into the Parse GraphQL [Config](https://docs.parseplatform.org/graphql/guide/#customisation):

```javascript
{
 ...
 classConfigs: [
 {
  className: "Country",
  type: {
      pointerArrays: [ {  field: "cities",  className: "City"  }, {  field: "states",  className: "State"  }  ]
  }
 }
] 
 ...
}
```

Longer-term would be to introduce this knowledge directly into the database schema, although I've not assessed the drawbacks yet.

**Comment by davimacedo** [comment]
@omairvaiyani I like this idea. I am only wondering if this information could be also useful for Parse Server overall. So maybe having this information in the parse server schema would be better?

**Comment by omairvaiyani** [comment]
@davimacedo it certainly would be. I understand that the Parse Server ```_Schema``` class stores the field type as `"array"`, regardless of whether the array stores regular POJOS, or Parse pointers. The source code also freely allows pointers to be changed from one class to another. If we did introduce a specific type, it would result in stricter behaviour, possibly classified as a breaking change.

A way around this would be to allow the current type `"array"` to continue behaving exactly as it does today, whilst allowing those who wish to upgrade to store the type as e.g. `"array$_User"`, where the `$` would signal a bifurcation in the `SchemaController`.

This migration could be sped up using a simple code snippet that runs through an active database (at runtime), and updates the `_Schema` class with extracted array pointer classes where available.

**Comment by davimacedo** [comment]
We could also leave the `Array` data type as it is now (to avoid the breaking change or any migration) and just add a metadata specifying it is a pointer Array (like we did in the required fields). What do you think? Is this something that you would be willed to tackle?

**Comment by Moumouls** [comment]
We could also have a huge problem with multi pointers in an Array (ex: `[User, Role, Product]`).

I think the solution is to implement an `InlineFragment` strategy: [GraphQL InlineFragment](https://graphql.org/learn/queries/#inline-fragments)

Tasks:

* Create an empty interface `ArrayResult` (if it's allowed by GQL, i don't know currently)
* Add doc on the field about the `InlineFragment` strategy
* Implement the `InlineFragment` on Array Resolvers

Example:
```graphql
query JobQuery {
  objects {
    getJob(objectId: "sqvJTrN9no") {
      title
      company {
        name
      }
      countries {
        ... on Country {
          name
        }
      }
    }
}
```

**Comment by davimacedo** [comment]
@Moumouls thanks for the suggestion. I think it is really the best way to solve this issue! I will take a look in your PR and revert my feedback.

**Comment by Moumouls** [comment]
@murshudov on the `master` branch you can test the new powerful `InlineFragment` feature, example here:

```graphql
{
  objects {
    getCountry(objectId: "8dDDVCHN2q") {
      objectId
      name
      companies {
        ... on CompanyClass {
          objectId
          name
          employees {
            ... on EmployeeClass {
              objectId
              name
            }
          }
          teams {
            ... on TeamClass {
              objectId
              name
              employees {
                ... on EmployeeClass {
                  objectId
                  name
                  country {
                    objectId
                    name
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
```

**Comment by murshudov** [comment]
@Moumouls and others, thank you very much for the great effort and awesome work 👍
