### ISSUE TITLE
Twitter Authentication not working Twitter auth is invalid for this user.

### ISSUE THREAD

**Issue by ittechsathish** [parse-community/parse-server#5897]
Problem : Twitter Authentication not working Twitter 
Error: auth is invalid for this user.

Problem Found:

twitter.js

// Returns a promise that fulfills iff this user id is valid.
function validateAuthData(authData, options) {
  if (!options) {
    throw new Parse.Error(
      Parse.Error.INTERNAL_SERVER_ERROR,
      'Twitter auth configuration missing'
    );
  }
  options = handleMultipleConfigurations(authData, options);
  var client = new OAuth(options);
  client.host = 'api.twitter.com';
// HERE IS THE ERROR, SO I CHANGED TO OPTIONS VARIABLE
  client.auth_token = options.auth_token;
  client.auth_token_secret = options.auth_token_secret;
}

PLEASE FIX THIS

ALSO I CHANGED CONFIG WITH AUTH TOKEN AND AUTH TOKEN SECRET

**Comment by davimacedo** [comment]
@ittechsathish thanks for reporting. Could you please send a PR with a failing test and your proposed solution?

**Comment by ittechsathish** [comment]
I was wrong, the auth_token and oauth_token_secret are there in twitter auth response.

window.hello.getAuthResponse("twitter") -> gives the data in the client side, we should add them in the use login request object

Please close this issue.
