### ISSUE TITLE
postgres high CPU usage!

### ISSUE THREAD

**Issue by davisbra** [parse-community/parse-server#5906]
hi, 
I use parse server with Postgres in my Node.js application. run parse (index.js) permanently in the background with pm2 My connection string in the app looks like this: 
```
var api = new ParseServer({
  databaseURI: databaseUri || 'postgres://postgres:Pass@IPaddress:5432/DatabaseName' ,
 ...});
```
at first hours everything is ok and CPU usage is under 5% but after 10-12 hours it increases to 100% even when I didn’t make any requests and even queries to the database. when I restart the Postgres everything goes back to normal. do you know what may cause the problem?

- **Server**
  - Operating System:     ubuntu 16.04
  - Hardware:            8G RAM, CPU(s):3, CPU Model name:Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
  - Localhost or remote server? remote server

- **Database**
  - Postgresql version: 11.4
  - Localhost or remote server? remote server

**Comment by dplewis** [comment]
Can you check this thread https://github.com/parse-community/parse-server/issues/5029

**Comment by davisbra** [comment]
thanks for your response, but I couldn't solve the problem!

**Comment by dplewis** [comment]
What have you tried? Did you remove pm2 in favor of cluster mode? Where are you hosted, something could be pinging your server if you aren’t. 

What version of Parse Server and Node are you running?
