### ISSUE TITLE
GraphQL: Using generic Mutation can lead to unwanted result

### ISSUE THREAD

**Issue by Moumouls** [parse-community/parse-server#5925]
### Issue Description

Using a generic Mutation can lead to unwanted result, more specifically on data types like: Array/Relation.

### Steps to reproduce

Create a new Object (with new field) and an array of `Pointers`
```graphql
mutation {
  objects {
    create(
      className: "SomeClass"
      fields: {
        relation: [
          { __type: "Pointer", className: "Country", objectId: "GFFCf5dxKW" }
        ]
      }
    ) {
      objectId
    }
  }
}
```
 
### Expected Results

`relation` field must be a `Relation`

### Actual Outcome

<img width="779" alt="Capture d’écran 2019-08-15 à 23 32 45" src="https://user-images.githubusercontent.com/27959372/63128354-05df0b00-bfb5-11e9-9667-f3d0d79d2b87.png">

The data type is interpreted as an Array

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : master
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): localhost

- **Database**
  - MongoDB

## Suggestion

I think that generic Mutations isn't suitable in real GraphQL app but it's useful for testing the current GraphQL feature. The generic `Mutation` currently seems to be a black box and can be confusing for new developers who are not familiar with SDKs (Polygon, ACL, Pointer, etc...)

In fact, I think that in most applications that will use the `Parse GraphQL` as `API`, the SDKs will be used little or not at all to interact with the `GraphQL` because it is not comfortable and really logical to combine a `SDK` and a `API GraphQL` in terms of developer experience.

We should teach developers to create first a schema with a well designed `createClass`/`createSchema` `Mutation` and then use a specific `Mutation`

What do you think about this @davimacedo @omairvaiyani @douglasmuraoka  ?

**Comment by davimacedo** [comment]
The sintax for creating a relationField through the generic method is the same of the REST API. So it whould be:

```graphql
mutation {
  objects {
    create(
      className: "SomeClass"
      fields: {
        relation: {
          __op: "Batch",
          ops: [{ __op: "AddRelation", objects: [{ __type: "Pointer", className: "Country", objectId: "GFFCf5dxKW" }]}]
      }
    ) {
      objectId
    }
  }
}
```

See test case here: https://github.com/parse-community/parse-server/blob/master/spec/ParseGraphQLServer.spec.js#L5119

I know it is not intuitive and need docs. The developers can always opt for the custom operations though. The idea behind the generic operations is to keep the schemaless feature in Parse GraphQL API but we can discuss it further and perhaps remove them.

**Comment by davimacedo** [comment]
I was thinking little bit more here. Maybe an option could be just remove all generic operations and build new operations to manipulate the schema?

**Comment by Moumouls** [comment]
Yes not intuitive 😉 
I'm not sure it's a solution to add more doc on a `GraphQL` API, the main goal of `GraphQL` is to avoid documentation and dive directly in `Mutations` and `Queries`.

**Comment by Moumouls** [comment]
> I was thinking little bit more here. Maybe an option could be just remove all generic operations and build new operations to manipulate the schema?

It's totally what i suggest, a developer could use the full potential of `Parse GraphQL Server` without reading single line of external documentation

A example of DX:

* Developer see mutation: `createClass` ou `createSchema`
* He can use enum to choose data types: `Relation`, `Polygon`, `Pointer` during class creation
* Schema is now created
* Now he can create the new object with a full typed help (particularly useful for special data types, `ACL` (we need to type this 😉 ), `Polygon`, etc...)
* The developer can now use the full power of Parse Server without reading single line of an external doc.

**Comment by Moumouls** [comment]
## Type Proposal

```graphql
type Mutation {
	createClass(input: CreateClassInput): Boolean
	updateClass(input: UpdateClassInput): Boolean
	createSchema(input: [CreateClassInput]): Boolean
	updateSchema(input: [UpdateClassInput]): Boolean
}

input AddArrayInput {
	fieldName: String
}

input AddRelationInput {
	fieldName: String
	targetClass: String
}

input AddNumberInput {
	fieldName: String
}

input AddBooleanInput {
	fieldName: String
}

input AddFileInput {
	fieldName: String
}

input AddPointerInput {
	fieldName: String
	targetClass: String
}

input AddDateInput {
	fieldName: String
}

input AddGeoPointInput {
	fieldName: String
}

input AddObjectInput {
	fieldName: String
}

input AddStringInput {
	fieldName: String
}

input DeleteField {
	fieldName: String
}

input FieldsClassInput {
	addArrays: [AddArrayInput]
	addStrings: [AddRelationInput]
	addNumbers: [AddRelationInput]
	addDates: [AddRelationInput]
	addGeoPoints: [AddRelationInput]
	addFiles: [AddRelationInput]
	addRelations: [AddRelationInput]
	addObjects: [AddObjectsInput]
	addPointers: [AddPointersInput]
	addPolygons: [AddPolygonsInput]
	addBooleans: [AddBooleansInput]
}

input CreateClassInput {
	className: String
	fields: FieldsClassInput
}

input UpdateClassInput {
	className: ClassNameEnum
	fields: FieldsClassInput
}
```
