### ISSUE TITLE
Uncaught (in promise) Error: bad key in untransform: __v #5928

### ISSUE THREAD

**Issue by rameshkec85** [parse-community/parse-server#5929]
### Issue Description

Getting this issue while i am trying to add existing mongodb to parse-server :

 Uncaught (in promise) Error: bad key in untransform: __v #5928

### Steps to reproduce

Mongodb tables have this key : '__v' when i am using mongoose
 
### Expected Results

Should allow migrate and see the results of the particular class

### Actual Outcome

Getting below issue:
Mongodb tables have this key : '__v' when i am using mongoose

 - if any table has not have ' __v' key , tables data shown in the parse-dashboard

### Environment Setup

- **Server**
  - parse-server version : 3.7.2
  - Operating System:     Mac OS 10.13.6
  - Hardware:             
  - Localhost or remote server? Local

- **Database**
  - MongoDB version: Latest Version
  - Storage engine:  -
  - Hardware:        -
  - Localhost or remote server? Remote(Directly i have added remote mongo db url in environment variabls) 

### Logs/Trace
Uncaught (in promise) Error: bad key in untransform: __v #5928

**Comment by davimacedo** [comment]
Fields starting with `_` are reserved for Parse Server usage. You will have to get rid of these fields before connecting Parse Server to your database.

**Comment by EhsanParsania** [comment]
You can fix this with two steps:

1. Removing __v from your existing documents:
 `db.collection('CLASSNAME').updateMany({}, { $unset: { __v: 1 } });`
2. Deactivate version key from schema's option
```js 
const yourSchema = new mongoose.Schema({
    // Your other fields here
  }, {
    versionKey: false // This will disable the "__v" field
  });
  const YourModel = mongoose.model('YourModel', yourSchema);
```
