### ISSUE TITLE
Sign in with Apple - fill in Email Adress

### ISSUE THREAD

**Issue by jomaw0** [parse-community/parse-server#5947]
I have two questions regarding `Sign in with Apple`.
1. what do I have to store in the iCloud Keychain in order to get a session on another device (login). Because if i do `Sign in with Apple` again a new user is created.
2. is it possible to read the jwt-payload in order to fill in the email adress when the new user is created?

**Comment by SebC99** [comment]
@jomaw0 I'm guessing your 1. issue is due to the actual parse-server implementation: every time you try to login in, you create a new account, even with the same device. A fix has been made, but is not yet released

**Comment by dplewis** [comment]
If you want the email in JavaScript it is returned as a user 

https://developer.apple.com/documentation/signinwithapplejs/configuring_your_webpage_for_sign_in_with_apple

**Comment by jomaw0** [comment]
1. that’s great 
2. so i have to change the user record on the device by changing the email address ?

**Comment by jomaw0** [comment]
Have you heard anything new yet? Because rumours are that Apple will be having a presentation on the 10th of September and Apple often rolls out there software about a week and a half later. That would be about on 21th of September. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
