### ISSUE TITLE
Avoid error "All objects must exist on the server" on calling fetchAll()

### ISSUE THREAD

**Issue by RaschidJFR** [parse-community/parse-server#5950]
**Is your feature request related to a problem? Please describe.**
When you need to fetch a list of objects which can be managed (or deleted) by other users, you risk getting an error `"All objects must exist on the server"` if any of those objects no longer exists.

**Describe the solution you'd like**
Ideally, the call to `ParseObject.fetchAll()` could ignore nonexistent objects and go on with the rest of the results.

**Describe alternatives you've considered**
The current way of avoiding this problem is not using `fetchAll()` but instead creating a new query:

```js
let objectList = [...someObjects];
objectList = await new Parse.Query('Foo')
  .containedIn('objectId', objectList.map(o => o.id))
  .find();
```

**Comment by dplewis** [comment]
You could use fetchAllIfNeeded

**Comment by RaschidJFR** [comment]
Thanks. `fetchAllIfNeeded()` works... but:

* What about `fetchAllWithInclude()`? it still throws the error.
* Still, there's no way to tell that an object no longer exists on the server without try/catch. Maybe create something like `ParseObject.exists()`?

**Comment by dplewis** [comment]
`await object.exists()` is a good idea. I've seen multiple developers ask for such a feature.

We could do FetchAllIfNeededWithInclude also.

@acinader @davimacedo What do you think?

**Comment by davimacedo** [comment]
I like both ideas.
