### ISSUE TITLE
GraphQL: whether can support to class create mutation with a new subobject install of only a pointer 

### ISSUE THREAD

**Issue by jackeryjam** [parse-community/parse-server#5971]
Sincerely thanking for bring such a wonderful function(parse + graphQL) to us. I love it deeply.And when I use it, I also meet some question as follows.

![image](https://user-images.githubusercontent.com/32444505/63647260-fc8e3500-c750-11e9-973f-28e4ec787295.png)

If I want to do this, first step I should create the a record of the pointer class and write the object id to it, where can I write the pointer class content in it to implement create the father class record and create the son class record at the same time only with a graphQL mutation.Like the following picture.
![image](https://user-images.githubusercontent.com/32444505/63647318-d2894280-c751-11e9-9066-50b43245b8d9.png)

**Comment by davimacedo** [comment]
@jackeryjam this issue was already tackled in this PR [here](https://github.com/parse-community/parse-server/pull/5946) and it will be available in the next release.
