### ISSUE TITLE
Error: listen EACCES: permission denied 0.0.0.0:1337

### ISSUE THREAD

**Issue by hckhanh** [parse-community/parse-server#5987]
# Before opening the issue please ensure that you have:

- [x] [Read the migration guide](https://github.com/parse-community/parse-server/blob/master/3.0.0.md) to parse-server 3.0.0
- [X] [Read the migration guide](https://github.com/parse-community/Parse-SDK-JS/blob/master/2.0.0.md) to Parse SDK JS 2.0.0

### Issue Description

I follow the Getting Started then I see this error

```
C:\Users\hoang\AppData\Roaming\npm\node_modules\parse-server\lib\ParseServer.js:227
          throw err;
          ^

Error: listen EACCES: permission denied 0.0.0.0:1337
    at Server.setupListenHandle [as _listen2] (net.js:1262:19)
    at listenInCluster (net.js:1327:12)
    at doListen (net.js:1460:7)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

### Steps to reproduce

Follow Getting Started section then run parse server locally

```
$ npm install -g parse-server mongodb-runner
$ mongodb-runner start
$ parse-server --appId APPLICATION_ID --masterKey MASTER_KEY --databaseURI mongodb://localhost/test
```
 
### Expected Results

Parse server must be run

### Actual Outcome

```
C:\Users\hoang\AppData\Roaming\npm\node_modules\parse-server\lib\ParseServer.js:227
          throw err;
          ^

Error: listen EACCES: permission denied 0.0.0.0:1337
    at Server.setupListenHandle [as _listen2] (net.js:1262:19)
    at listenInCluster (net.js:1327:12)
    at doListen (net.js:1460:7)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : v3.8.0
  - Operating System:     Windows 10
  - Hardware:             Powerful Desktop
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Localhost

- **Database**
  - MongoDB version: 4.0
  - Storage engine:  [FILL THIS OUT]
  - Hardware:        [FILL THIS OUT]
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): Localhost

**Comment by chhaprahiya** [comment]
In my case, I got this error on port 9001. The root cause was: 9001 was already in use by another process. 
To find a list of ports & processes: netstat -ano -p tcp  
To convert PID to process name: tasklist

**Comment by SavvasMes** [comment]
I have the same error. nothing I tried seems to work.

**Comment by Dane411** [comment]
I got the same error. I run the following command to find the proc ID of the proc that was listening on port 1337.
`netstat -a -n -o | find "1337"`
Then in task manager I searched for the name of this process, and decided if I could finish it.

**Comment by zubairahsan** [comment]
Just Change the port in **.evn** file. you must run **npm run build** or **yarn build** or **strapi build**. because **strapi** admin templates use default port 1337 and for using on another port you must build the project again.
