### ISSUE TITLE
Parse crashes periodically - 503 error

### ISSUE THREAD

**Issue by zhgromov** [parse-community/parse-server#5996]
Hello. We connected our backend (node js) to parse server and its work earlier. But in the last week there are constantly problems with the parse server - a 503 error when working with the API is restored by itself in a few minutes or hours. I understand this is an API server error, how can I solve it? It becomes impossible to work - 503 errors more and more oftensimilarly parse-dashboard stops working at this time with similar errors

**Comment by davimacedo** [comment]
Can you please fill out the [issue template](https://github.com/parse-community/parse-server/issues/new?template=---report-an-issue.md)?
