### ISSUE TITLE
beforeSave Why can't submit successfully

### ISSUE THREAD

**Issue by xianhaosui** [parse-community/parse-server#6012]
Parse.Cloud.beforeSave('VehSubscribes', (request) => {
  const hphm = request.object.get('hphm')
  if (hphm.length > 3) {
    // test
    request.object.set('hphm', hphm.substring(0, 3) + '...')
  }
})

The above code could not save the data

**Comment by dplewis** [comment]
Can you post logs? VERVOSE=1

Your code looks right. 

Can you fill out the issue template? It would help if we know expected vs actual results.

**Comment by xianhaosui** [comment]
res.success()  

Must be written in order to submit, thank you
