### ISSUE TITLE
GraphQL invalid options errors

### ISSUE THREAD

**Issue by omairvaiyani** [parse-community/parse-server#6016]
Since `3.8.0`, I'm receiving this error message on any query:

```
{
    "errors": [
        {
            "message": "Invalid options provided to ApolloServer: Expected Upload to be a GraphQL nullable type.",
            "extensions": {
                "code": "INTERNAL_SERVER_ERROR"
            }
        }
    ]
}
```

I thought it's worth opening an issue whilst I look for the reason/solution myself. If anyone else is having the same problem, please +1 so I know it's not just me!

**Comment by omairvaiyani** [comment]
Fixed by adding the exact version of graphql as used by parse-server into the repo`package.json`, and running a fresh npm install.

**Comment by buithuyen** [comment]
I have the same one. Could you please give me more information about that.

**Comment by omairvaiyani** [comment]
The error occurs when you have multiple versions of graphql in your node modules folder. You can confirm this by going into your package lock file, and searching `"graphql"`: if you see more than one version, npm will have resolved different versions inside your child dependency's node modules. Check which version of graphql is expected by your version of parse-server, and then make sure you set that version in your own package.json file.
