### ISSUE TITLE
Transactions enabled by default on REST requests

### ISSUE THREAD

**Issue by fbeiger** [parse-community/parse-server#6019]
### Issue Description

I updated parse-server to the 3.8.0 release (which include a newest addition of transactions).

I found that transactions are enabled by default when performing a REST request (either from the JS client, parse-dashboard, or a simple POSTMAN), **without** using the `transaction: true` parameter in the payload.

Although, cloud-code seem to work as expected, as I am still able to perform operations.

Regarding this I have several questions: 
- Is it the expected behaviour? 
- If so, is it possible to disable transactions globally (when setting up the parse-server for example)? 

### Steps to reproduce

 
Perform a PUT query on whatever object (with or without MasterKey)
Example with a session token:
```
curl -X PUT \
  <PARSE_SERVER_URL>/parse/classes/<YOUR_CLASS>/<OBJECT_ID> \
  -H 'Content-Type: application/json' \
  -H 'Host: <PARSE_SERVER_URL>' \
  -H 'X-Parse-Application-Id: <YOUR_APP_ID>' \
  -H 'X-Parse-REST-API-Key: <YOUR_REST_KEY>' \
  -H 'X-Parse-Session-Token: <YOUR_TOKEN>' \
  -d '{
  "myAttribute":"myValue"
}'
```

### Expected Results

To update object's attribute with corresponding value.

### Actual Outcome

Instead, I have a status 500 response with this body:
```
{
    "code": 1,
    "message": "Internal server error."
}
```
And this error server-side:
```
error: Uncaught internal server error.Transaction numbers are only allowed on storage engines that support document-level locking
```

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 3.8.0
  - Operating System:     Heroku
  - Hardware:             Heroku
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Heroku

- **Database**
  - MongoDB version: 3.6.12
  - Storage engine:  MMAPv1
  - Hardware:        unknown
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): mLab

### Logs/Trace

```
error: Uncaught internal server error.Transaction numbers are only allowed on storage engines that support document-level locking
```

**Comment by davimacedo** [comment]
The transaction should only be opened when using the `transaction: true` option through the `batch` route. I will write a test case to ensure that. In the meantime, can you please take a look in the following issue?

https://github.com/parse-community/parse-server/issues/5983

**Comment by davimacedo** [comment]
@fbeiger see this PR: https://github.com/parse-community/parse-server/pull/6022

I added many tests and it seems to be working as expected. Feel free to add more tests to this PR in order to reproduce the problem.

Have you tried the approach of the other issue I sent you?

**Comment by fbeiger** [comment]
Hi @davimacedo , thanks for your quick response and investigation.

I tried to set `retryWrites=false`, but unfortunately it didn't work for me.

I'll need to investigate more on my side before coming back to you with a test case or specific scenario.

Thanks again for your time

**Comment by fbeiger** [comment]
Hi again @davimacedo, quick update on this issue.

After detaching my  mLab addon, then attach a fresh one (with the same config) and restoring the previous DB, this error finally came up:
```
MongoError: This MongoDB deployment does not support retryable writes. Please add retryWrites=false to your connection string.
```
Then obviously adding the query param (and #5983) solve it. 

I don't know what caused the issue in the first place though.

Anyway, now everything is working fine, thanks!
