### ISSUE TITLE
ACCOUNT_ALREADY_LINKED Error when logging in with Facebook

### ISSUE THREAD

**Issue by tealshift** [parse-community/parse-server#6035]
### Issue Description

When logging in with Facebook (or perhaps other authentication methods) I get a error message:
'this auth is already used' which is error code ACCOUNT_ALREADY_LINKED.
This happened on both Parse Server versions 3.7.2 and 3.8.0.
After downgrading to version 3.1.1 this bug does not occur.

### Steps to reproduce

I'm more of a mobile app dev than a web dev, so my STR are to run the iOS Parse SDK command: 
`[PFFacebookUtils logInInBackgroundWithReadPermissions:permissions];`
I don't think the permissions list matters, but here it is:
`@[@"public_profile", @"email", @"user_friends", @"user_link"]`

### Expected Results

User is authenticated with Facebook.

### Actual Outcome

This actually produces a crash in Parse SDK because the `PFCommandResult.result` turns out to be an `NSArray` of size two instead of the expected `NSDictionary`. It seems the actual JSON dictionary response was the second element of the array!
But even after passing JSON through the Parse SDK, I get this authentication error.
> [Error]: this auth is already used (Code: 208, Version: 1.17.2)

The SDK produces a current User, but the session is not valid.

### Environment Setup
I'm using the BaaS back4app.com 
- **Server**
  - parse-server version: 3.8.0
  - Operating System: iOS, Parse SDK 1.17.2
  - Hardware: iPhone 6s
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): back4app.com

I don't think this is DB related but...
- **Database**
  - MongoDB version: I know it's less than ver 3.0
  - Storage engine:  ??
  - Hardware: ??
  - Localhost or remote server?: ??

### Logs/Trace

I read through the Server logs but the only useful piece was from the SDK:

> [Error]: this auth is already used (Code: 208, Version: 1.17.2)

**Comment by davimacedo** [comment]
@tealshift I couldn't reproduce the issue. Is the user that you are trying to log in a new user? Or is it a user that was previously saved as anonymous or so?

**Comment by tealshift** [comment]
@davimacedo It was an existing user in my app. I believe it happened even after unlinking and relinking Facebook through the SDK. I also tried a totally separate user with a different Facebook. 
... I’m really confused.

**Comment by davimacedo** [comment]
Can you please make sure what is the scenario that it is happening? It will be easier for us to reproduce.

**Comment by tealshift** [comment]
Ok, I just made a fresh project on Xcode 11 beta 7 (login only) linked to my staging app server and Facebook app, and the crash did reproduce. Is it ok if I DM you a download @davimacedo ?

**Comment by tealshift** [comment]
Interestingly, my own (and my coworker's) Facebook account produces the crash, but a Facebook "Test User" does not. Fortunately I have a real (throwaway) Facebook account I made for testing which I can share login credentials for and does produce the crash. 
Switching Facebook users requires going into Safari and logging out, then in with the other user.

**Comment by mtrezza** [comment]
@tealshift Very trivial, but did you verify that
- unlinking in the SDK causes the auth data in the DB to be removed
- there is no other user with the auth data; maybe delete all users from the DB and test with only 1

**Comment by tealshift** [comment]
@mtrezza I did confirm the authData was cleared, but I didn't check against the other two possibilities. I could try with a fresh database/app, but I kind of doubt that will help solve my problem. I appreciate the suggestion though.
Davi says his team is on the case and I think they are more knowledgable than me here.

**Comment by douglasmuraoka** [comment]
@tealshift
I have been testing the Facebook login using the JS SDK with both 3.1 and 3.8 versions and the linking/unlinking is working just fine. I can check the ParseUser `authData` and it is always set to `undefined` when unlinked. Could you do this test using the iOS SDK?

By the way, when using parse-server 3.1, how the Facebook login response from parse-server looks like? Did you check if there are no other users with the same `authData`? I have checked some commits merged on parse-server, and one of them is a security patch that changes the response when using account linking. You can check it [here](https://github.com/parse-community/parse-server/security/advisories/GHSA-8w3j-g983-8jh5).
Also, could you try reproducing the bug on a brand new database using parse-server 3.7+? I have been analyzing the parse-server code several times and I still don't see a change that fits the bug you have described.
