### ISSUE TITLE
Mongo 4.2 Support

### ISSUE THREAD

**Issue by Vortec4800** [parse-community/parse-server#6041]
It appears the TravisCI tests run against Mongo 3.6 and 4.0, but I don't see anything testing against 4.2. Is this accurate? What versions of Mongo does Parse Server officially test against and support?

**Comment by davimacedo** [comment]
That's true. There is no tests for Mongo 4.2 in our CI and I think we should include it.

**Comment by dplewis** [comment]
As of the latest release 3.8.0 supports MongoDB 4.2.

[Mongo DB Driver 3.3.0](https://github.com/mongodb/node-mongodb-native/releases/tag/v3.3.0)
