### ISSUE TITLE
Missing docs which data can be manipulated directly in DB

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-server#6053]
### Issue Description

For certain use cases it can be more efficient to manipulate data on the DB level than via Parse Dashboard or a Parse SDK.
- For example bulk operations on large collections can be executed more efficiently in the MongoDB shell or via a MongoDB Script than routing the command through parse server.
- Or it may just be dropping a collection or removing a field from every document because the shell is already open.

At the moment it is unclear which operations *should* go through Parse Server because there are pre or post operations executed, for example updating the `_SCHEMA` collection.

Example questions:
- https://github.com/parse-community/parse-server/issues/3939
- Is it safe to simply drop a relations collection in the DB? Dropping a whole collection would be instantaneous and cause no additional load on the DB, but dropping the column in Parse Dashboard presumably will.

Particularly when it comes to collections with tens of millions of documents the approach to data manipulation changes and the current Parse Dashboard may not be suitable anymore for certain operations like dropping a column for all documents at once.

### Expected Results

It should be documented which operations are save to be executed on the DB level and which should go through Parse Server.

### Actual Outcome

Currently not documented.

**Comment by davimacedo** [comment]
A documentation explaining the data model could be a good idea but I am not sure if we should specify which/how operations could be done directly in Mongo.

**Comment by mtrezza** [comment]
@davimacedo Yes, I think the data model would do it.

With a note that before/after could code hooks are not applied. Which is not be obvious because one could think that parse server listens to MongoDB change streams and executes the hooks, which is not the case.
