### ISSUE TITLE
I can not use any third lib in CloudCode.

### ISSUE THREAD

**Issue by fuqiangZ** [parse-community/parse-server#6055]
I want to use mailgun in my CloudCode.

1. install lib in parse-server,   

> npm install mailgun-js --save
check the package.json, `"mailgun-js": "^0.22.0",` exists

2. require mailgun in cloudcode
```
var mailgun = require('mailgun-js')({apiKey: 'XXX', domain: 'XXX.com'});
Parse.Cloud.define("sendMail", (request, response) => {
});
```
3. start the parse-server. Then error occurs:
```
Error: Cannot find module 'mailgun-js'
Require stack:
- /dilu_dev/gitlab/metis-cloudcode/okr/test.js
```

**Comment by davimacedo** [comment]
Can you please fill out the issue template? https://github.com/parse-community/parse-server/issues/new/choose

**Comment by fuqiangZ** [comment]
> Can you please fill out the issue template? https://github.com/parse-community/parse-server/issues/new/choose

well, i maybe know why.
I git clone the source code and run `lib/cli/parse-server.js` directly. Besides i add dependency lib into the parse-server’s package.json。With this way, i can not require lib in the cloud code.
But, i download the parse-server-example, then add dependency to the package.json,  then reuqire the lib in the cloud code, it works...Ohh

Am i right ?  I'm new to parse-server.

**Comment by fuqiangZ** [comment]
well, solved again..... If i put the cloudcode dir out of the parse-server dir, then can not use these libs. But, put the cloudCode dir in the parse-server dir , it works.... That...
