### ISSUE TITLE
Parse-maintained node-apn

### ISSUE THREAD

**Issue by Vortec4800** [parse-community/parse-server#6057]
Is Parse maintaining their own fork of node-apn now? I'm getting a ton of errors when sending push messages about HTTP2 GOAWAY handling that seem to be related to this issue/PR: https://github.com/node-apn/node-apn/issues/640

That's from quite a while ago now and it seems like it's not going to be merged in, and even if it is I don't know if it would get merged in the new Parse fork.

**Comment by funkenstrahlen** [comment]
Parse does maintain its own fork of node-apn for some weeks now. Exactly for this reason: We want to be able to change code without relying on an inactive node-apn repository.

As far as I can see this issue could be fixed if we merge this into our fork: https://github.com/node-apn/node-apn/pull/643

Correct?

**Comment by funkenstrahlen** [comment]
If everyone agrees on this I can apply the changes to our fork tomorrow.

**Comment by funkenstrahlen** [comment]
@Vortec4800 In case you have some time to work on it you could also create the PR to our fork: https://github.com/parse-community/node-apn

**Comment by Vortec4800** [comment]
That is my (admittedly limited) understanding as well. I might be able to do it later today, if so I'll put together a PR.

**Comment by funkenstrahlen** [comment]
I found some time this morning and created a PR with the required changes: https://github.com/parse-community/node-apn/pull/7

**Comment by Vortec4800** [comment]
Cool thanks for this, will be good to get this merged and updated when it's ready.

**Comment by davimacedo** [comment]
closed via https://github.com/parse-community/node-apn/pull/7
