### ISSUE TITLE
Separating schema and user/session cache

### ISSUE THREAD

**Issue by kcolton** [parse-community/parse-server#6060]
**Is your feature request related to a problem? Please describe.**
We have a large schema which is currently being cached in redis. Our schema cache is using significant resources due to its size (~64KB) and that it gets accessed multiple times per request (we process several hundred requests per second). 

Our schema cache is putting an amount of pressure on redis (and even the raw networking) that really isn't sustainable.

**Describe the solution you'd like**
Being able to have the schema cache be managed in memory, but have the user/session cache in redis.

**Describe alternatives you've considered**
Using in-memory cache for everything:
We have tried this in the past but had issues with in-memory cache leaking memory. This was several versions ago. Maybe that has been fixed? Any drawbacks with in-memory cache other than memory usage? 
 
**Additional context**
Overall the implementation of the schema cache, particularly the number of times it is accessed per request and it's potential size, does not seem well tailored for it being stored remotely. 

Our schema does not often change w/o the backend getting redeployed anyway so we are not really concerned with schema invalidation. 

Looked into how we would be able to use a different cache for schema and it seems like it would require forking and modifying `DatabaseController`, `SchemaCache`, and `SchemaController` to be configured with a different `CacheController`. 

This seems like it would be useful for other users and well and we would be happy to commit it back into the project if there was interest. 

Appreciate thoughts/advise on the specific problem we are facing and proposed solution.

Many thanks!

----

New Relic Graph showing time in redis is taking up 1/3 of all request time. Much more than even mongo.
![image](https://user-images.githubusercontent.com/390961/65084944-c8d2b380-d97a-11e9-982d-5c075d1dd8e7.png)

Even with single schema cache enabled we still get thousands of redis operations per second. Most just reading the same ~64KB schema over and over.
![image](https://user-images.githubusercontent.com/390961/65085035-1c450180-d97b-11e9-9370-711670858959.png)

A large amount of our network IO is from the schema cache being read from redis multiple times per request. It's enough bandwidth that it overwhelmed many of the redis configurations we tried.
![image](https://user-images.githubusercontent.com/390961/65085400-fff59480-d97b-11e9-890c-a1353c4b0640.png)

**Comment by dplewis** [comment]
Which version of Parse Server are you using? Improvements have been made such as less validation of schema and reducing bottleneck on RedisCacheAdapter.

**Comment by kcolton** [comment]
@dplewis Thanks for the reply.

Version: 3.7.2

We saw a reduction in total number of redis ops after #5612 and #5616 (thanks btw! was a really nice change) as well as when we changed to `enableSingleSchemaCache: true` which did dramatically increase our cache hit ratio. We are also using `directAccess: true` although that did not seem to affect redis ops. 

However, even with all of that, there's still a very high volume of `"get" "badpanda:__SCHEMA__MAIN_SCHEMA"` ops (multiple per request); and due to our schema being pretty large, that key winds up being ~64KB. 

Here is `MONITOR` output from `redis-cli` for one of our more simple cloud functions:
https://gist.github.com/kcolton/8999d06c24f0c00d0c24d87857d2ed51

When there is a cache hit on both the schema and session, there aren't that many MAIN_SCHEMA lookups happening. Seems like 1 for the cloud function and 1 for the collection lookup (we are using directAccess: true although that didnt seem to change much w/ redis) 

However for the same cloud function on a session cache miss we wind up with 5 lookups to MAIN_SCHEMA. With hundreds of cloud function executions per second, many of which involve multiple collections, you can see how this all starts to add up to significant raw throughput through redis.

**Comment by kcolton** [comment]
Just tried running 3.9.0 locally and I'm no longer seeing the `SCHEMA<Collection>` lookups, but seems to be the same number of `"get" "badpanda:__SCHEMA__MAIN_SCHEMA"` which is the problematic key causing all the load.

**Comment by dplewis** [comment]
Do you have a specific query / use case that uses a lot of get lookups.

Can you write a test case? https://github.com/parse-community/parse-server/blob/master/spec/RedisCacheAdapter.spec.js#L187

This way we can look see how many lookups and find a way to deal with the bottleneck.
