### ISSUE TITLE
Hosting parse server

### ISSUE THREAD

**Issue by MikeJuliet** [parse-community/parse-server#6065]
Is there anyone that can assist me to get my parse server running on Linux?

I have tried "DIY" but keep on failing.

**Comment by mrmarcsmith** [comment]
Hi Mike, there are two major philosophies I have found for spinning up parse servers, each with their own advantages and disadvantages. In the near future, are you looking for Lowest Cost or the Best Scalability?

Lowest Cost Advantages:
- Less Money (duh)
Lowest Cost Disadvantages:
- no mongo replication means possible data loss up to the last mongo backup you took
- no mongo replication means the possibility of downtime for your app
- if you do grow really fast you would need to switch to the "Scalable" option with mean dev time and possible down time during high traffic times.

Best Scalability Advantages:
- Ready for high traffic
- mongo replication reduces the risk of data loss
- mongo replication reduces downtime as the system can "failover" to a backup member
Lowest Cost Disadvantages:
- You have to pay more for the "backup" servers

**Comment by MikeJuliet** [comment]
Thanks a lot Mark.

Can you contact me on WhatsApp (+27814220795) or email
marthinusjacobs@gmail.com

I would like to hear more from you about the setting up of parse servers as
I do not know anything about servers.

**Comment by diego-vieira** [comment]
@MikeJuliet in this case you are better off using a paid service/hosting that will host the server for you.

https://www.back4app.com/product/what-is-parse-server
https://github.com/relatedcode/ParseAlternatives#parse-server-hosting-providers
