### ISSUE TITLE
mongodb-runner start fails with "Response code 403 (Forbidden)"

### ISSUE THREAD

**Issue by h4xhor** [parse-community/parse-server#6072]
### Issue Description

When following the Running Parse Server Locally steps, it errors at `mongodb-runner start` step.

### Steps to reproduce

```
$ su
# npm install -g parse-server mongodb-runner
# mongodb-runner start
```
 
### Expected Results

mongodb-runner start should complete with no errors.

### Actual Outcome

Get a `{ StdError [HTTPError]: Response code 403 (Forbidden)`. Please see complete log below:

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 3.9.0
  - Operating System:     Arch Linux
  - Hardware:             IBM Lenovo W500 laptop
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Localhost

- **Database**
  - MongoDB version: Not sure
  - Storage engine:  Not sure
  - Hardware:        IBM Lenovo W500
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): localhost

### Logs/Trace

[mongodb-runner-error.txt](https://github.com/parse-community/parse-server/files/3638835/mongodb-runner-error.txt)

**Comment by davimacedo** [comment]
It seems some problem with the mongodb-runner package which is just a convenient way to run a MongoDB instance for development. You can run a MongoDB instance for your Parse Server using different ways though.
