### ISSUE TITLE
Graphql v3.9.0: enum CloudCodeFunction doesn't contain any cloud functions.

### ISSUE THREAD

**Issue by durunvo** [parse-community/parse-server#6075]
### Issue Description

I created a cloud function in cloud code. For version 3.8.0, I can call those functions in graphql as a string.
After upgraded to 3.9.0, I tried to find `enum CloudCodeFunction` but couldn't find any of my defined function name.

I am using back4app as a bootstrap parse server. There is a doc in graphql console where I can see the schemas. In the `callCloudCode` section, I only found this:

```
enum CloudCodeFunction {
  line
}
```

Not really sure what's the `line` mean.

### Expected Results

```
enum CloudCodeFunction {
 //list of all functionName
}
```

### Actual Outcome

```
enum CloudCodeFunction {
line
}
```

### Environment Setup

- **Server**
  - parse-server version 3.9.0
  - Operating System:     [FILL THIS OUT]
  - Hardware:             [FILL THIS OUT]
  - Localhost or remote server? back4app

- **Database**
  - MongoDB version: [FILL THIS OUT]
  - Storage engine:  [FILL THIS OUT]
  - Hardware:        [FILL THIS OUT]
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): [FILL THIS OUT]

**Comment by omairvaiyani** [comment]
What is your function called exactly? There is a filter that excludes certain patterns

**Comment by durunvo** [comment]
@omairvaiyani Yep. It seems to be some anti-pattern in my `functionNames`. I saw the test case and it doesn't accept hyphen.
https://github.com/parse-community/parse-server/pull/6029/files#diff-33aaa37c5b8fdaf663b4033583b25198R5357
Thanks anyway.

**Comment by omairvaiyani** [comment]
I wouldnt think that using hyphens is an anti-pattern in Parse, it's just not directly supported by ParseGraphQL as of yet. There is a task for us to auto-rename the functions using underscores before adding them to the `CloudCodeFunction` enum. In the meantime, you could dual register your cloud functions internally using underscores, assuming you have a central place in your codebase that registers all cloud functions.

**Comment by durunvo** [comment]
@omairvaiyani That would be great. I don't think hyphens is anti-pattern as well, thanks for confirming that.
