### ISSUE TITLE
Sharing auth across subdomains

### ISSUE THREAD

**Issue by Koosmann** [parse-community/parse-server#6138]
Hi guys - We posted this question on the parse community discourse a week ago with no response.  So, apologies ahead of time for this cross post, we just wanted to follow up here to see if anyone knows the answer.  Is it possible to have to user authentication work across subdomains?  For example, we'd like to have a user logged into one.example.com also be logged into two.example.com without having to log in again.  Thanks!

**Comment by dplewis** [comment]
This is possible.

The server automatically destroys duplicate session, which will cause a `invalid session token` error.

https://github.com/parse-community/parse-server/blob/master/src/RestWrite.js#L914

This is done based on installationId (unique identifier for device). If there is no installationId or unique installationId are used, then the session aren't destroyed.

```
await Parse.User.logIn('username', 'password', { installationId: 'unique' });
```

When you initialize the Javascript SDK you should get a unique installationId.
https://github.com/parse-community/Parse-SDK-JS/blob/master/src/InstallationController.js#L40

Sorry for the long post, I realized that there isn't much documentation on installationId.

**Comment by Koosmann** [comment]
@dplewis No worries, thanks for this response, we're glad to hear it's possible! We had to shelve this feature for a bit, but are coming back to it now.   

We're not quite sure about some of the implementation details from the above description.  We tried passing the installationId this way (using the response from Parse._getInstallationId()), but it didn't seem change anything i.e. if you logged in on one subdomain, you still wouldn't be logged in when you navigate to another one.  

Is there something we should be doing differently?

**Comment by dplewis** [comment]
You are correct. LocalStorage is domain specific. There are iframe tricks you can use for browser

**Comment by Koosmann** [comment]
Thanks @dplewis - So with iframe messaging, we could send the session token to the subdomain and use Parse.User.become to authenticate.  But, is there a way to set the installationId once it's received via iframe message?  I'm not seeing any way to set the current installationId in the docs.
