### ISSUE TITLE
Cannot read property 'facebook' of null

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-server#6140]
### Issue Description

Users report that they have trouble logging in and we see these entries in the NodeJS logs quite frequently since some hours:

```
error: Uncaught internal server error.Cannot read property 'facebook' of null
{
    "stack": "TypeError: Cannot read property 'facebook' of null\n    at Object.keys.forEach.provider (/var/app/current/node_modules/parse-server/lib/RestWrite.js:402:49)\n    at Array.forEach (<anonymous>)\n    at findUsersWithAuthData.then (/var/app/current/node_modules/parse-server/lib/RestWrite.js:400:29)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
}
```

We also see a few:
`(node:3200) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 connect listeners added. Use emitter.setMaxListeners() to increase limit`

Maybe related to https://github.com/parse-community/parse-server/issues/2189.

### Steps to reproduce

Haven't been able to reproduce yet.
 
### Expected Results

User should be able to log in.

### Actual Outcome

Users cannot log in.

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 3.9.0
  - Operating System:     AWS Linux
  - Hardware:             AWS
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): AWS

- **Database**
  - MongoDB version: 3.6.12
  - Storage engine:  WiredTiger
  - Hardware:        mLab
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): mLab

### Logs/Trace

-

**Comment by dplewis** [comment]
Can you look at your mongo database and post the specific user authData.

Post logs VERBOSE=1

**Comment by mtrezza** [comment]
Is there any pattern I can look for in the DB?
I want to avoid turning on verbose logging if possible.

**Comment by dplewis** [comment]
If you can set a breakpoint here 
https://github.com/parse-community/parse-server/blob/master/src/RestWrite.js#L509

I’m just guessing that two user have the authData but one of them is null.

Do you know which user is throwing that error? If we can’t replicate it at least we can narrow down the possibilities.

**Comment by mtrezza** [comment]
I don't know which user. It's a prod env so I can't set a breakpoint and rather not log verbose if avoidable.

**Comment by dplewis** [comment]
There is an issue opened for authData and the Dashboard.

https://github.com/parse-community/parse-server/issues/5365

I can open a PR for it. Hopefully that helps. If until then you can use the mongo shell.

**Comment by mtrezza** [comment]
I found some users with `authData: null` in the DB.
Normally authData for facebook is stored at `_auth_data_facebook: {...}`.

IIRC there used to be a bug in the JS SDK that would not unlink a Facebook account from a user.
So we added this as workaround:

            await Parse.Cloud.httpRequest({
                method: "PUT",
                url: ... + "/users/" + user.id,
                headers: {
                    'X-Parse-Application-Id': ...,
                    'X-Parse-Master-Key': ...,
                    'Content-Type': 'application/json'
                },
                body: {
                    "authData": null
                }
            });

**Comment by dplewis** [comment]
Here is a passing test case for Facebook unlink

https://github.com/parse-community/Parse-SDK-JS/blob/master/integration/test/ParseUserTest.js#L774

I assume it works

**Comment by mtrezza** [comment]
I think it was this: https://github.com/parse-community/parse-server/issues/4103
Fixed in 2017, how time flies :)

I'll change the code, remove the `null` values from the DB and then hopefully close this issue.

**Comment by dplewis** [comment]
It was fixed this year. https://github.com/parse-community/Parse-SDK-JS/pull/767

A lot of improvements have been made with linking users

**Comment by dplewis** [comment]
@mtrezza can I add you to the parse team? You have been active over the years and know the ins and outs of Parse.

@acinader Thoughts?

**Comment by mtrezza** [comment]
@dplewis Do I have to manually load the Facebook SDK in cloud code?

I tried to unlink like in the test case with 

```
Parse.FacebookUtils.init();
await Parse.FacebookUtils.unlink(user);
```
and the unlink seems to succeed but I get this error in the logs:

> Error: The Facebook JavaScript SDK must be loaded before calling init.

**Comment by mtrezza** [comment]
@dplewis How would I add the Facebook JS SDK to cloud code?

In the test cases the user is unlinked with 
            Parse.FacebookUtils.init();
            await Parse.FacebookUtils.unlink(user);

That requires the FB JS SDK to be loaded, but the FB docs say:

> The Facebook SDK for JavaScript doesn't have any standalone files that need to be downloaded or installed, instead you simply need to include a short piece of regular JavaScript in your HTML that will asynchronously load the SDK into your pages. The async load means that it does not block loading other elements of your page.

**Comment by dplewis** [comment]
user._unlinkFrom(“facebook”, options)

**Comment by mtrezza** [comment]
When I call `await request.user._unlinkFrom("facebook", {useMasterKey:true})` I get this error:

> TypeError: Cannot read property 'getAuthType' of undefined

> Parse error: Invalid session token
> {
>     "code": 209,
>     "stack": "Error: Invalid session token\n    at Object.getAuthForSessionToken (/var/app/current/node_modules/parse-server/lib/Auth.js:114:11)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
> }

I assume this is from [here](https://github.com/parse-community/Parse-SDK-JS/blob/38286f28b49a898214f3ce9b7468527e04ac3b7d/src/ParseUser.js#L219), so there seem to be no `authProviders` registered for the user?

The `user` is the requesting user who calls the cloud code function, so the authProvider should be registered for the user?

**Comment by mtrezza** [comment]
@dplewis 
When I call `await request.user._unlinkFrom("facebook", {useMasterKey:true})` I get this error:

> TypeError: Cannot read property 'getAuthType' of undefined

> Parse error: Invalid session token
> {
>     "code": 209,
>     "stack": "Error: Invalid session token\n    at Object.getAuthForSessionToken (/var/app/current/node_modules/parse-server/lib/Auth.js:114:11)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
> }

I assume this is from [here](https://github.com/parse-community/Parse-SDK-JS/blob/38286f28b49a898214f3ce9b7468527e04ac3b7d/src/ParseUser.js#L219), so there seem to be no `authProviders` registered for the user?

The `user` is the requesting user who calls the cloud code function. If a user is linked with a facebook account, should the auth provider for facebook be registered for the user?

**Comment by mtrezza** [comment]
I couldn't get `unlinkFrom` via the Parse JS SDK to work in cloud code and couldn't easily find the reason why.

So I just fixed the REST call, the correct body is (already in the REST docs):

    body: {
        "authData": {
            "facebook": null
        }
    }

The `authData` field is synthesized from the `_auth_data_*` fields in the DB, so direct manipulation does not work in all cases (e.g. `{"__op":"Delete"}`) and should be avoided.

**Comment by mtrezza** [comment]
Worth noting that because `authData` is a synthesized field, object manipulation with `authData` is not a good idea at all.

When an `authData` field with value `null` (or I guess any value) exists in the DB, the field cannot be synthesized and instead the actual field value of `authData` is displayed in the dashboard. So the dashboard shows value `null` even though the `_auth_data_facebook` field exists in the DB.

So this should not be allowed:

       await Parse.Cloud.httpRequest({
            method: "PUT",
            url: ... + "/users/" + user.id,
            headers: {
                'X-Parse-Application-Id': ...,
                'X-Parse-Master-Key': ...,
                'Content-Type': 'application/json'
            },
            body: {
                "authData": null
            }
        });

Instead it should throw an error that field `authData` cannot be manipulated directly.
@dplewis What do you think?

The error in the original issue occurs when a user tries to sign-in with FB and there is a field `authData` in the collection.

**Comment by dplewis** [comment]
@mtrezza Thanks for looking into this deeply. There are a few issues we have to addressed and improvements to be made for authData.

1. Fix Facebook unlink (use a basic Auth provider)
2. Fix https://github.com/parse-community/parse-server/issues/5365
3. We should avoid throwing errors if possible, can you open a PR to prevent server crashing?
4. Improve dashboard handling authData

**Comment by mtrezza** [comment]
@dplewis will open a PR. Out of curiosity, do you know what the rationale for synthesizing `authData` was?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mtrezza** [comment]
@dplewis added PR #6154 to fix your point 3.

**Comment by dplewis** [comment]
Added PR https://github.com/parse-community/Parse-SDK-JS/pull/971 for point 1.

Closing via https://github.com/parse-community/parse-server/pull/6154
