### ISSUE TITLE
Integration with Hasura for better postgres and graphql integration

### ISSUE THREAD

**Issue by MohakChugh** [parse-community/parse-server#6145]
Is there any possibility of integration Hasura Graphql Engine with it? Hasura uses postgreSQL and provides a graphql endpoint.

Maybe we can directly use Hasura Graphql engine to support the Graphql service and better Postgre support.

**Comment by davimacedo** [comment]
I am afraid that it will not be possible. The data model of the two projects are completely different. Have you tried out our GraphQL implementation?
http://docs.parseplatform.org/graphql/guide/

**Comment by Moumouls** [comment]
May be with https://github.com/parse-community/parse-server/pull/6360
And a Remote Schema strategy you can stitch an Hasura on a GraphQL Server: https://www.apollographql.com/docs/graphql-tools/remote-schemas/
