### ISSUE TITLE
Wrong image file URL

### ISSUE THREAD

**Issue by Aback231** [parse-community/parse-server#6156]
Hi, 

Parse dashboard is unable to show uploaded images when I click on download. Image link on dashboard: http://192.168.0.199/undefined/files/e190e57e626723cbe8fb2b7065dcddbcfb6896b1/a8c4554fa6f44e92eac3dce239a62215_image.png

I can view the image when I modify this link as: http://192.168.0.199/parse/files/e190e57e626723cbe8fb2b7065dcddbcfb6896b1/a8c4554fa6f44e92eac3dce239a62215_image.png

I have observed the same dashboard behavior when uploading image file using dashboard only (created new class and row using dashboard), as well as pulling objects trough code. I get "No data to display" error when I hit download using dashboard. 
I'm using parse server version 3.9.0-0 and parse dashboard 1.4.3. The same exact problem is happening on AWS EC2 Bitnami parse server instance, and on VMware image also by Bitnami. Why is this happening ? What could i try to solve this issue ? Is there any setting to modify the URL's ?

Thanks!

**Comment by dplewis** [comment]
Can you try to run the dashboard locally? Seems like a mount path is missing.

**Comment by Aback231** [comment]
Even if that worked, it's not an acceptable solution to me, but I don't think it will, because when I query those image file objects in my android app, the same wrong URL's are retrieved back. I grab URL's, swap undefined for parse, and my app works. Every Image ever uploaded is there... That would mean that parse server is serving broken URL's, nothing to do, with dashboard, or am I mistaken ?

**Comment by dplewis** [comment]
Can you check that your serverURL and publicServerURL are correct?

You can also debug your server around [here](https://github.com/parse-community/parse-server/blob/master/src/middlewares.js#L121). Where the mount is retrieved in the middleware before each request.

**Comment by Aback231** [comment]
URL's are exact match. Not sure how I would debug the server... Bitnami acknowledged the the issue a few hours ago (on their community forum), and created internal task to fix it, cause they were able to reproduce the same behavior on a fresh instance. Maybe the issue is related just to their instances.

**Comment by mtrezza** [comment]
@Aback231 when you cross post then it would be helpful if you included the link to your other post. It may save everyone some time.

**Comment by mtrezza** [comment]
https://community.bitnami.com/t/unable-to-download-or-view-images-i-o-error/71400/6

**Comment by davimacedo** [comment]
Closing since it is something specific to the bitnami deployment.
