### ISSUE TITLE
Build failed when building for MacCatalyst

### ISSUE THREAD

**Issue by Tridie2000** [parse-community/parse-server#6163]
### Issue Description

When I enable MacCatalyst and try to run it on my Mac, the app doesn't compile.

### Steps to reproduce

- Open an app with Parse Server
- Check the MacCatalyst checkbox
- Run the app
 
### Expected Results

I expect the app to run on the Mac. 

### Actual Outcome

The build failed with the following error: 
```
'initWithMemoryCapacity:diskCapacity:diskPath:' is unavailable: not available on macCatalyst
```

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.8.4
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Back4App

- **Database**
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): Back4App

**Comment by dplewis** [comment]
You can follow this issue [here](https://github.com/parse-community/Parse-SDK-iOS-OSX/issues/1461). A fix should be out soon!
