### ISSUE TITLE
ParseQuery.order is missing in beforeFind hook

### ISSUE THREAD

**Issue by virtualtoy** [parse-community/parse-server#6164]
**Is your feature request related to a problem? Please describe.**
When I access query in `beforeFind` hook I cannot access order information.

**Describe the solution you'd like**
I would like to be able to retrieve order information. 

**Describe alternatives you've considered**
So far I see no alternatives to this problem for now.

**Additional context**
Possible solution is to add order information data in file `src/triggers.js` (not sure about implications, seems pretty straightforward):
```
@@ -460,6 +460,9 @@ export function maybeRunQueryTrigger(
     if (restOptions.limit) {
       parseQuery._limit = restOptions.limit;
     }
+    if (restOptions.order) {
+      parseQuery._order = restOptions.order.split(',');
+    }
     count = !!restOptions.count;
   }
   const requestObject = getRequestQueryObject(
```

**Comment by dplewis** [comment]
Sounds like a good idea. Would you like to open a PR for this?

**Comment by dplewis** [comment]
@virtualtoy There are a few query fields missing. If you want to get started, add your test cases [here](https://github.com/parse-community/parse-server/blob/master/spec/CloudCode.spec.js#L1758) and read the [Contributor's Guide](https://github.com/parse-community/parse-server/blob/master/CONTRIBUTING.md)

**Comment by virtualtoy** [comment]
@dplewis I'd like to but looks like I cannot run tests on windows. Let me resolve issue with tests first
