### ISSUE TITLE
Parse-Server 3.9.0 d'ont start with babel-node

### ISSUE THREAD

**Issue by lordkkjmix** [parse-community/parse-server#6171]
### Issue Description

Hi, i'm faced with issue when use last version of parse-server and last version of babel-node.
I use it to use new es6 Js code structure in my cloud code.
I've aleready use it with old version of parse-server.
After install all dependencies, i got error linked with the new graphQl feature. 
### Steps to reproduce

$ mkdir my-app
$ cd my-app
$ npm install parse-server express parse-dashboard express --save
$ npm install babel-cli -S

my package.json is like this :
{
  "name": "my-app",
  "version": "0.0.1",
  "private": true,
  "description": "Myapp Server ",
  "main": "index.js",
  "dependencies": {
    "babel-cli": "^6.26.0",
    "babel-relay-plugin": "^0.11.0",
    "eslint": "^4.19.1",
    "express": "^4.16.3",
    "parse": "^1.11.1",
    "parse-dashboard": "^2.0.5",
    "parse-server": "^3.9.0"
  },
  "scripts": {
    "start": "babel-node index.js"
  },
  "devDependencies": {
    "babel-eslint": "^8.2.3",
    "babel-polyfill": "^6.26.0",
    "babel-preset-es2015": "^6.24.1"
  }
}
### Expected Results

import express from 'express';
import {ParseServer} from 'parse-server';
import ParseDashboard from 'parse-dashboard';

### Actual Outcome
var express =require('express');
var ParseServer= require('parse-server').ParseServer;
var ParseDashboard = require('parse-dashboard');

### Environment Setup

- **Server**
  - parse-server version: 3.9.0
  - Operating System:    MacOS Mojave and Ubuntu 16.4
  - Hardware:500GB,8Go
  - Localhost or remote server? : Localhost

- **Database**
  - MongoDB version: 4.2.0
  - Storage engine:  HDD
  - Hardware:      Local
  - Localhost or remote server?: Localhost

### Logs/Trace
../node_modules/graphql-tools/dist/stitching/introspectSchema.js:41
var parsedIntrospectionQuery = graphql_1.parse(utilities_1.getIntrospectionQuery());
                                                           ^

TypeError: utilities_1.getIntrospectionQuery is not a function
    at Object.<anonymous> (../node_modules/graphql-tools/src/stitching/introspectSchema.ts:8:54)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Object.require.extensions.<computed> [as .js] (../node_modules/babel-register/lib/node.js:152:7)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (../node_modules/graphql-tools/src/stitching/index.ts:2:1)

**Comment by dplewis** [comment]
Where are you hosted? If you are running node 8+ es6 functions are included (I think).

Have you tried without babel-node?

**Comment by lordkkjmix** [comment]
Hi i've tried without babel-node, it works but i need to use babel-node

Le ven. 1 nov. 2019 à 18:28, Diamond Lewis <notifications@github.com> a
écrit :

**Comment by dplewis** [comment]
@lordkkjmix This project compiles with babel [package.json](https://github.com/parse-community/parse-server/blob/master/package.json#L97) Trying to compile it again maybe your issue.

Why do you need to use babel-node? Let us know so we can find a solution.

I'm going to close this as it isn't an issue the project. We are more than welcome to help.
