### ISSUE TITLE
How to prevent unregistered users or anonymous users from obtaining class data

### ISSUE THREAD

**Issue by lybaiyy123** [parse-community/parse-server#6178]
I look up the previous iusse list, but can't prevent anonymous users from getting class data

Is there any other way besides using role?

THANKS.

**Comment by lybaiyy123** [comment]
Can I configure it in server config?

**Comment by omairvaiyani** [comment]
You can use either CLPs or ACLs (https://docs.parseplatform.org/rest/guide/#security)
