### ISSUE TITLE
Request Password Reset only works for logged in users

### ISSUE THREAD

**Issue by SteffenKeller** [parse-community/parse-server#6202]
### Issue Description

It seems that the **requestPasswordReset** function is only working for logged in users when running the following code in my Swift app:

```          
PFUser.requestPasswordResetForEmail(inBackground: email, block: {
    (success, error) in
     ...
})
```
When the user is logged in it works without problems. When the user is signed out it will not send an email and the function doesn't return an error. A also tried the ParseUI's PFLoginViewControllers included functionality but it behaves exactly the same way. 

I also implemented the following cloud function:
```
Parse.Cloud.define("requestPasswordReset", function(request, response) {
    Parse.User.requestPasswordReset(request.params.email).then(function() {
        console.log("Password reset request was sent successfully");
    }).catch(function(error) {
        console.log("The login failed with error: " + error.code + " " + error.message);
    });
});
```
However, this behaves exactly the same way. The function is executes successfully but an email is never received. 

I am using Parse Server for some years now and newer had problems with the reset password functionality. I don't know since when exactly this problem occurs but my app code should not have changed in this time.

### Steps to reproduce

Try to execute the **requestPasswordReset** function without being logged in.
 
### Expected Results

Send an email to reset the users password.

### Actual Outcome

An email is only sent if the user who request the email is logged in. 

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 3.9.0
  - Operating System:     Linux/4.10.2
  - Hardware: AWS
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): AWS

- **Database**
  - MongoDB version: 3.6.12
  - Storage engine:  MMAPv1
  - Hardware:        Shared Cluster
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): mLab

**Comment by davimacedo** [comment]
I couldn't reproduce the issue. Would you mind to create a failing test case? Can you also share details about the setup that you have in your Parse Server (e-mail adapter, etc) and also the user object whose password you are trying to reset? Do you see any error message in your logs?

**Comment by SteffenKeller** [comment]
I will try to create a failing test case. Here is the server setup and a sample user object. 
I don't see any error messages in the logs even with verbose activated. The function is executed successfully in both cases but an email is only sent if the user who requested the email is logged in.

Server setup:
```
var S3Adapter = require('@parse/s3-files-adapter');

var api = new ParseServer({
  databaseURI: databaseUri || 'mongodb://localhost:27017/dev',
  cloud: process.env.CLOUD_CODE_MAIN || __dirname + '/cloud/main.js',
  appId: process.env.APP_ID || 'myAppId',
  masterKey: process.env.MASTER_KEY || '', 
  fileKey: process.env.FILE_KEY || '', 
  serverURL: process.env.SERVER_URL || 'http://localhost:1337/parse', 
  verifyUserEmails: true,
  emailVerifyTokenValidityDuration: 72 * 60 * 60,
  preventLoginWithUnverifiedEmail: false,
  publicServerURL: 'https://url.com/data/',
  appName: 'AppName',
  maxUploadSize: '900mb',
  allowClientClassCreation: false,
  filesAdapter: new S3Adapter('...',
    '...',
    'files', {
        region: 'eu-central-1',
        directAccess: false
  }),
  customPages: {
      invalidLink: 'link',
      verifyEmailSuccess: 'link',
      choosePassword: 'link',
      passwordResetSuccess: 'link',
  },
  emailAdapter: {
    module: 'parse-server-mailgun',
    options: {
      fromAddress: 'My E-Mail <noreply@domain.com>',
      domain: 'domain.com',
      apiKey: 'key',
      templates: {
        passwordResetEmail: {
          subject: 'Reset your password',
          pathPlainText: resolve(__dirname, 'email-templates/password_reset_email.txt'),
          pathHtml: resolve(__dirname, 'email-templates/password_reset_email.html'),
        },
        verificationEmail: {
          subject: 'Confirm your account',
          pathPlainText: resolve(__dirname, 'email-templates/verification_email.txt'),
          pathHtml: resolve(__dirname, 'email-templates/verification_email.html'),
        }
      }
    }
  }
});
```

Sample user object:
```
{
    "_id": "08GQoCiFQM",
    "username": "some.email@domain.com",
    "email": "some.email@domain.com"",
    "_hashed_password": "$2a$10$XpOCRsx.nT7jCbGCBCS...",
    "emailVerified": true,
    "_wperm": [
        "08GQoCiFQM"
    ],
    "_rperm": [
        "08GQoCiFQM"
    ],
    "_acl": {
        "08GQoCiFQM": {
            "w": true,
            "r": true
        }
    },
    "_created_at": {
        "$date": "2018-05-17T20:08:32.341Z"
    },
    "_updated_at": {
        "$date": "2019-06-25T18:15:26.314Z"
    },
    "lastName": "Name",
    "firstName": "Name",
    "iap_slot1": false,
    "locale": "de-DE",
    "iap_slot2": false,
    "iap_slot0": true,
    "lastOfflineBackup": {
        "$date": "2019-04-21T06:07:15.213Z"
    },
    "appVersion": "2.4.3",
    "acceptedAlert": {
        "$date": "2019-03-06T20:03:32.025Z"
    }
}
```

**Comment by davimacedo** [comment]
Have you tried a different e-mail adapter? Does your e-mail template rely on nome user information? Do you have any trigger associated to your _User class?

**Comment by pastordee** [comment]
Hi in my case if you enter the right email the user will receive the email but if you enter the wrong email no error is giving

**Comment by SteffenKeller** [comment]
Thanks for your hint @pastordee. In my case there were some uppercase characters in some email fields. So it fails if the user enters his email lowercased. I will lowercase all email fields in my database and use a lowercase string when resetting emails.

**Comment by omarojo** [comment]
@pastordee I have the same issue. If the email is none existent in the database, it doesnt throw an error. 

```
PFUser.requestPasswordResetForEmail(inBackground: email, block: {
    (success, error) in
     ...
})
```

error is always nil and success ir always true.

**Comment by TomWFox** [comment]
Hi Omar,

This is actually very much by design. If an error was returned when the email wasn't found it would allow a malicious party to enumerate valid emails.

You can see commit 7fe4030 where this change was made.

This is now standard behaviour for most email password reset systems.

**Comment by omarojo** [comment]
@TomWFox  thanks you for the clarification. 😬
