### ISSUE TITLE
{"error":"unauthorized"}

### ISSUE THREAD

**Issue by pitxels** [parse-community/parse-server#6220]
Hello.

I am using latest node: 12.10
latest npm: 6.11.3
latest mongo 4.2.1

I just installed parse-server-example locally, following the readme instructions and without modifying any file. I also installed mongo and by default it doesn't require user/password.

When I run npm start and go to localhost:1337/test,  I get all the tests ok: "Congrats! Our local Parse server is working. :)"

Then when I go to localhost:1337/parse,  I get {"error":"unauthorized"}

I also installed the dashboard locally but when I run:
`parse-dashboard --dev --appId myAppId --masterKey myMasterKey --serverURL "http://localhost:1337/parse" `

I am running it with those keys because that is what I see in app.json by default

The Dashboard doesn't work and I get a bunch of errors, but I guess that need to be asked in the dashboard repo.

Any help is appreciated.

**Comment by ashmanmalikThinkun** [comment]
Use header X-Parse-Application-Id: yourappId while accessing parse. Moreover, update package.json with dashboard and use dashboard within parse server. Don't forget to run node when you are done with your node package.

**Comment by dplewis** [comment]
> Then when I go to localhost:1337/parse, I get {"error":"unauthorized"}

This is normal as you aren’t passing any keys in.

Which error are you encountering?

**Comment by pitxels** [comment]
> This is normal as you aren’t passing any keys in.
I am passing the strings I found in app.json, the readme doesn't explain anything about the keys so I am just guessing here.

Also In parse-server-example the keys are not asked nor suggested like in parse-server so I don't have any keys nor any file to put them in.

Once I pass the keys you mention, what am I supposed to see at http://localhost:1337/parse ?

Thanks!

**Comment by dplewis** [comment]
Sorry I mean accessing the /parse url directly. /test isn’t connect to parse is just an endpoint. It’s just to show your server is running and testing.

Checkout the guide https://docs.parseplatform.org/parse-server/guide/

Does cURL work for you?

**Comment by pitxels** [comment]
> Checkout the guide https://docs.parseplatform.org/parse-server/guide/

Yeah that is my point exactly the parser-server-example documentation is missing steps that I need to check in the full documentation. So I guess I will forget about parser-server-example for now and focus on the main repo.

**Comment by pitxels** [comment]
> Does cURL work for you?
Yep

`curl -X POST \                                                                                                                          ~
-H "X-Parse-Application-Id: myAppId" \
-H "Content-Type: application/json" \
-d '{"score":1337,"playerName":"Sean Plott","cheatMode":false}' \
http://localhost:1337/parse/classes/GameScore
{"objectId":"gDzp75bLE5","createdAt":"2019-11-20T06:35:32.944Z"}%`

**Comment by dplewis** [comment]
Looking at the original issue error: unauthorized isn’t an issue any more as you are able to access the server right?

The second issue you mention was the dashboard. 

Can you fork the parse-dashboard and see if it works?

**Comment by pitxels** [comment]
For the Dashboard I run:

`parse-dashboard --dev --appId myAppId --masterKey myMasterKey --serverURL "http://localhost:4040/"`

and I get:

`inject
dashboard.bundle.js:95 Missing push locales for 'myAppId', see this link for details on setting localizations up. https://github.com/parse-community/parse-dashboard#configuring-localized-push-notifications
e @ dashboard.bundle.js:95
(anonymous) @ dashboard.bundle.js:95
(anonymous) @ dashboard.bundle.js:95
Promise.then (async)
value @ dashboard.bundle.js:95
Cu @ dashboard.bundle.js:45
t.unstable_runWithPriority @ dashboard.bundle.js:53
qi @ dashboard.bundle.js:45
_u @ dashboard.bundle.js:45
su @ dashboard.bundle.js:45
nu @ dashboard.bundle.js:45
Ku @ dashboard.bundle.js:45
Yu @ dashboard.bundle.js:45
(anonymous) @ dashboard.bundle.js:45
fu @ dashboard.bundle.js:45
nl @ dashboard.bundle.js:45
render @ dashboard.bundle.js:45
(anonymous) @ dashboard.bundle.js:95
n @ dashboard.bundle.js:1
(anonymous) @ dashboard.bundle.js:1
(anonymous) @ dashboard.bundle.js:1
VM547:1 POST http://localhost:4040/serverInfo 404 (Not Found)
(anonymous) @ VM547:1
a @ dashboard.bundle.js:75
ajax @ dashboard.bundle.js:75
(anonymous) @ dashboard.bundle.js:75
Promise.then (async)
request @ dashboard.bundle.js:75
d._request @ dashboard.bundle.js:75
value @ dashboard.bundle.js:95
(anonymous) @ dashboard.bundle.js:95
(anonymous) @ dashboard.bundle.js:95
Promise.then (async)
value @ dashboard.bundle.js:95
Cu @ dashboard.bundle.js:45
t.unstable_runWithPriority @ dashboard.bundle.js:53
qi @ dashboard.bundle.js:45
_u @ dashboard.bundle.js:45
su @ dashboard.bundle.js:45
nu @ dashboard.bundle.js:45
Ku @ dashboard.bundle.js:45
Yu @ dashboard.bundle.js:45
(anonymous) @ dashboard.bundle.js:45
fu @ dashboard.bundle.js:45
nl @ dashboard.bundle.js:45
render @ dashboard.bundle.js:45
(anonymous) @ dashboard.bundle.js:95
n @ dashboard.bundle.js:1
(anonymous) @ dashboard.bundle.js:1
(anonymous) @ dashboard.bundle.js:1
dashboard.bundle.js:95 Missing push locales for 'myAppId', see this link for details on setting localizations up. https://github.com/parse-community/parse-dashboard#configuring-localized-push-notifications
e @ dashboard.bundle.js:95
addApp @ dashboard.bundle.js:95
(anonymous) @ dashboard.bundle.js:95
(anonymous) @ dashboard.bundle.js:95
Promise.then (async)
value @ dashboard.bundle.js:95
Cu @ dashboard.bundle.js:45
t.unstable_runWithPriority @ dashboard.bundle.js:53
qi @ dashboard.bundle.js:45
_u @ dashboard.bundle.js:45
su @ dashboard.bundle.js:45
nu @ dashboard.bundle.js:45
Ku @ dashboard.bundle.js:45
Yu @ dashboard.bundle.js:45
(anonymous) @ dashboard.bundle.js:45
fu @ dashboard.bundle.js:45
nl @ dashboard.bundle.js:45
render @ dashboard.bundle.js:45
(anonymous) @ dashboard.bundle.js:95
n @ dashboard.bundle.js:1
(anonymous) @ dashboard.bundle.js:1
(anonymous) @ dashboard.bundle.js:1
dashboard.bundle.js:45 TypeError: Cannot read property 'schemas' of undefined
    at t.value (dashboard.bundle.js:95)
    at La (dashboard.bundle.js:45)
    at Ra (dashboard.bundle.js:45)
    at eu (dashboard.bundle.js:45)
    at xu (dashboard.bundle.js:45)
    at yu (dashboard.bundle.js:45)
    at su (dashboard.bundle.js:45)
    at dashboard.bundle.js:45
    at t.unstable_runWithPriority (dashboard.bundle.js:53)
    at qi (dashboard.bundle.js:45)
es @ dashboard.bundle.js:45
n.callback @ dashboard.bundle.js:45
go @ dashboard.bundle.js:45
mo @ dashboard.bundle.js:45
Cu @ dashboard.bundle.js:45
t.unstable_runWithPriority @ dashboard.bundle.js:53
qi @ dashboard.bundle.js:45
_u @ dashboard.bundle.js:45
su @ dashboard.bundle.js:45
(anonymous) @ dashboard.bundle.js:45
t.unstable_runWithPriority @ dashboard.bundle.js:53
qi @ dashboard.bundle.js:45
Gi @ dashboard.bundle.js:45
Hi @ dashboard.bundle.js:45
nu @ dashboard.bundle.js:45
enqueueSetState @ dashboard.bundle.js:45
E.setState @ dashboard.bundle.js:37
(anonymous) @ dashboard.bundle.js:95
Promise.then (async)
value @ dashboard.bundle.js:95
Cu @ dashboard.bundle.js:45
t.unstable_runWithPriority @ dashboard.bundle.js:53
qi @ dashboard.bundle.js:45
_u @ dashboard.bundle.js:45
su @ dashboard.bundle.js:45
nu @ dashboard.bundle.js:45
Ku @ dashboard.bundle.js:45
Yu @ dashboard.bundle.js:45
(anonymous) @ dashboard.bundle.js:45
fu @ dashboard.bundle.js:45
nl @ dashboard.bundle.js:45
render @ dashboard.bundle.js:45
(anonymous) @ dashboard.bundle.js:95
n @ dashboard.bundle.js:1
(anonymous) @ dashboard.bundle.js:1
(anonymous) @ dashboard.bundle.js:1
VM547:1 POST http://localhost:4040/schemas 404 (Not Found)
(anonymous) @ VM547:1
a @ dashboard.bundle.js:75
ajax @ dashboard.bundle.js:75
(anonymous) @ dashboard.bundle.js:75
Promise.then (async)
request @ dashboard.bundle.js:75
d._request @ dashboard.bundle.js:75
value @ dashboard.bundle.js:95
(anonymous) @ dashboard.bundle.js:95
dispatch @ dashboard.bundle.js:95
dispatch @ dashboard.bundle.js:95
value @ dashboard.bundle.js:95
Co @ dashboard.bundle.js:45
Ra @ dashboard.bundle.js:45
eu @ dashboard.bundle.js:45
xu @ dashboard.bundle.js:45
yu @ dashboard.bundle.js:45
su @ dashboard.bundle.js:45
(anonymous) @ dashboard.bundle.js:45
t.unstable_runWithPriority @ dashboard.bundle.js:53
qi @ dashboard.bundle.js:45
Gi @ dashboard.bundle.js:45
Hi @ dashboard.bundle.js:45
nu @ dashboard.bundle.js:45
enqueueSetState @ dashboard.bundle.js:45
E.setState @ dashboard.bundle.js:37
(anonymous) @ dashboard.bundle.js:95
Promise.then (async)
value @ dashboard.bundle.js:95
Cu @ dashboard.bundle.js:45
t.unstable_runWithPriority @ dashboard.bundle.js:53
qi @ dashboard.bundle.js:45
_u @ dashboard.bundle.js:45
su @ dashboard.bundle.js:45
nu @ dashboard.bundle.js:45
Ku @ dashboard.bundle.js:45
Yu @ dashboard.bundle.js:45
(anonymous) @ dashboard.bundle.js:45
fu @ dashboard.bundle.js:45
nl @ dashboard.bundle.js:45
render @ dashboard.bundle.js:45
(anonymous) @ dashboard.bundle.js:95
n @ dashboard.bundle.js:1
(anonymous) @ dashboard.bundle.js:1
(anonymous) @ dashboard.bundle.js:1
dashboard.bundle.js:75 Uncaught (in promise) Error: Received an error with invalid JSON from Parse: <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot POST /schemas</pre>
</body>
</html>

    at dashboard.bundle.js:75
a @ dashboard.bundle.js:75
t @ dashboard.bundle.js:75
t @ dashboard.bundle.js:16
(anonymous) @ dashboard.bundle.js:75
Promise.then (async)
value @ dashboard.bundle.js:95
Co @ dashboard.bundle.js:45
Ra @ dashboard.bundle.js:45
eu @ dashboard.bundle.js:45
xu @ dashboard.bundle.js:45
yu @ dashboard.bundle.js:45
su @ dashboard.bundle.js:45
(anonymous) @ dashboard.bundle.js:45
t.unstable_runWithPriority @ dashboard.bundle.js:53
qi @ dashboard.bundle.js:45
Gi @ dashboard.bundle.js:45
Hi @ dashboard.bundle.js:45
nu @ dashboard.bundle.js:45
enqueueSetState @ dashboard.bundle.js:45
E.setState @ dashboard.bundle.js:37
(anonymous) @ dashboard.bundle.js:95
Promise.then (async)
value @ dashboard.bundle.js:95
Cu @ dashboard.bundle.js:45
t.unstable_runWithPriority @ dashboard.bundle.js:53
qi @ dashboard.bundle.js:45
_u @ dashboard.bundle.js:45
su @ dashboard.bundle.js:45
nu @ dashboard.bundle.js:45
Ku @ dashboard.bundle.js:45
Yu @ dashboard.bundle.js:45
(anonymous) @ dashboard.bundle.js:45
fu @ dashboard.bundle.js:45
nl @ dashboard.bundle.js:45
render @ dashboard.bundle.js:45
(anonymous) @ dashboard.bundle.js:95
n @ dashboard.bundle.js:1
(anonymous) @ dashboard.bundle.js:1
(anonymous) @ dashboard.bundle.js:1
content-automation.js:98 {quick_capture_github: "false", quick_capture_github_welcome: "false"}`

**Comment by dplewis** [comment]
Your server url is wrong. It should be your parse server url not your dashboard url. 

Looking at your screenshot it should be http://localhost:1337/serverInfo

**Comment by pitxels** [comment]
> Looking at your screenshot it should be http://localhost:1337/serverInfo

I used  http://localhost:1337/parse as the serverURL and that did the trick.

Thank you so much for the troubleshooting!
