### ISSUE TITLE
Cloud functions return undefined instead of data

### ISSUE THREAD

**Issue by Ktejaswini1608** [parse-community/parse-server#6223]
### Issue Description

previously worked on cloud function and it worked fine and now I run the cloud function it doesn't return any response and it shows undefined on all parse server versions(3.1.1,3.7.0)

### Steps to reproduce
client code:
var gettestparams = {
Name: "",
action: "get",
where: "Test"
}
Parse.Cloud.run('cloudFunctions', gettestparams).then(function (callback) {
console.log("get test call", callback);
}).catch((error) => {
console.log("fail", error);
});

cloud code:
main.js:
Parse.Cloud.define('cloudFunctions', function (req, res) {
switch (req.params.where) {
case 'Test':
switch (req.params.action) {
case 'get':
testservice.getTestData(req, res, function (recordset) {
console.log("main.js", recordset);
return recordset;
});
break;
}
}
});

testservice.js:
exports.getTestData = function (req, res, callback) {
const query = new Parse.Query("Test");
if (req.params.Name) {
query.equalTo('Name', req.params.Name);
}
query.find({ useMasterKey: true })
.then((results) => {
var testArray = new Array();
for (let i = 0; i < results.length; i++) {
testArray[i] = {
id: results[i].id,
Name: results[i].get("Name"),
Description: results[i].get("Description")
};
}

callback({status:"OK",result:testArray});
}, (error) => {
callback("Save failed! " + error);
});
};

#### Expected Results
parameters for Test table get call 
Name: "",
action: "get",
where: "Test"

Expected: Test table data 

#### Actual Outcome

undefined

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) :3.7.0
  - Operating System:     windows 10
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): localhost

- **Database**
  - MongoDB version: 3.2.7
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): localhost
### Logs/Trace

Include all relevant logs. You can turn on additional logging by configuring VERBOSE=1 in your environment.

**Comment by dplewis** [comment]
You aren't returning anything in your cloud code function.

You should easily identify your issue if you use async / await instead of callbacks.

**Comment by Ktejaswini1608** [comment]
Thanks for your reply

when I added my function code using async / await in main.js  it works fine but when I implemented async /await code in testservice.js file it returns undefined.I used to implement code in testservices.js

main.js:
Parse.Cloud.define('cloudFunctions', function (req, res) {
switch (req.params.where) {
case 'Test':
switch (req.params.action) {
case 'get':
testservice.getTestData(req, res, function (recordset) {
console.log("main.js", recordset);
return recordset;
});
break;
}
}
});


testservice.js:
exports.getTestData = async (req, res, callback)=> {
    const query = new Parse.Query("Test");
          try {
            var results = await query.find({ useMasterKey: true })
            var testArray = new Array();
            for (let i = 0; i < results.length; i++) {
              testArray[i] = {
                id: results[i].id,
                Name: results[i].get("Name"),
                Description: results[i].get("Description")
              };
            }
            callback ({ status: "OK", result: testArray });
          }
          catch (error) {
            callback ("Save failed! " + error);
          } 
};

**Comment by Ktejaswini1608** [comment]
Hi,



Thanks for your reply

when I added my function code using async / await in main.js it works fine but when I implemented async /await code in testservice.js file it returns undefined.I used to implement code in testservices.js


main.js:

Parse.Cloud.define('cloudFunctions', function (req, res) {

switch (req.params.where) {

case 'Test':

switch (req.params.action) {

case 'get':

testservice.getTestData(req, res, function (recordset) {

console.log("main.js", recordset);

return recordset;

});

break;

}

}

});



testservice.js:

exports.getTestData = async (req, res, callback)=> {

const query = new Parse.Query("Test");

try {

var results = await query.find({ useMasterKey: true })

var testArray = new Array();

for (let i = 0; i < results.length; i++) {

testArray[i] = {

id: results[i].id,

Name: results[i].get("Name"),

Description: results[i].get("Description")

};

}

callback ({ status: "OK", result: testArray });

}

catch (error) {

callback ("Save failed! " + error);

}

};




---- On Mon, 18 Nov 2019 22:48:42 +0530 Diamond Lewis <notifications@github.com> wrote ----


You aren't returning anything in your cloud code function.

You should easily identify your issue if you use async / await instead of callbacks.

**Comment by dplewis** [comment]
```
testservice.getTestData(req, res, function (recordset) {
  console.log("main.js", recordset);
  return recordset; <- this is never returned to the cloud code function.
});

// Should returns something here
```

**Comment by Ktejaswini1608** [comment]
Thanks for your reply

       But I want to return recordset data, if i return outside the service call can't find recordset value(within service only we can return recordset value)

testservice.getTestData(req, res, function (recordset) {
  console.log("main.js", recordset);
  return recordset; <- this is never returned to the cloud code function.
});

// Should returns something here       <- not able to use recordset value here

**Comment by dplewis** [comment]
> You should easily identify your issue if you use async / await instead of callbacks.

I know you are unable to which is why I recommended rewriting your code. 

Your can turn your callback into a promise with a wrapper.

**Comment by Ktejaswini1608** [comment]
I used promise instead of callback.still I am getting undefined when i return. If I prints in console data is showing.

main.js:
Parse.Cloud.define('cloudFunctions', function (req, res) {
switch (req.params.where) {
case 'Test':
switch (req.params.action) {
case 'get':
 let promise = testservice.getTestData(req, res);      
          promise.then(
            (results) => {
              console.log("main", results)
              return results;
            }
          );
break;
}
}
});



testservice.js:
exports.getTestData = function (req, res) {
    return new Promise(function (resolve, reject) {
        const query = new Parse.Query("Test");
        query.find({ useMasterKey: true })
            .then((results) => {
                var testArray = new Array();
                for (let i = 0; i < results.length; i++) {
                    testArray[i] = {
                        id: results[i].id,
                        Name: results[i].get("Name"),
                        Description: results[i].get("Description")
                    };
                }
                resolve({ status: "OK", result: testArray });
            }, (error) => {
                reject("Save failed! " + error);
            });
    });
};

**Comment by omairvaiyani** [comment]
You need to return the `promise` object within your `cloudFunctions` body.

**Comment by Ktejaswini1608** [comment]
Thanks for everyone.Now It works.
main.js:
  let promise = testservice.getTestData(req, res);
          return promise;

testservice.js:
exports.getTestData = function (req, res) {
    return new Promise(function (resolve, reject) {
        const query = new Parse.Query("Test");
        query.find({ useMasterKey: true })
            .then((results) => {
                var testArray = new Array();
                for (let i = 0; i < results.length; i++) {
                    testArray[i] = {
                        id: results[i].id,
                        Name: results[i].get("Name"),
                        Description: results[i].get("Description")
                    };
                }
                resolve({ status: "OK", result: testArray });
            }, (error) => {
                reject("Save failed! " + error);
            });
    });
};
