### ISSUE TITLE
Code 141, Error: Parse error: Cannot read property 'apply' of undefined 

### ISSUE THREAD

**Issue by ShadowCoderPro** [parse-community/parse-server#6225]
I am trying to do a Post Request to register a user.

0|parse | verbose: REQUEST for [POST] /parse/functions/userRegister: {
0|parse | "method": "POST",
0|parse | "url": "/parse/functions/userRegister",
0|parse | "headers": {
0|parse | "host": "localhost:8081",
0|parse | "connection": "keep-alive",
0|parse | "content-length": "345",
0|parse | "pragma": "no-cache",
0|parse | "cache-control": "no-cache",
0|parse | "origin": "http://localhost:8080",
0|parse | "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36",
0|parse | "dnt": "1",
0|parse | "content-type": "text/plain",
0|parse | "accept": "/",
0|parse | "sec-fetch-site": "same-site",
0|parse | "sec-fetch-mode": "cors",
0|parse | "referer": "http://localhost:8080/login",
0|parse | "accept-encoding": "gzip, deflate, br",
0|parse | "accept-language": "en-GB,en-US;q=0.9,en;q=0.8"
0|parse | },
0|parse | "body": {
0|parse | "api": {
0|parse | "version": 1,
0|parse | "endpoint": "userRegister"
0|parse | },
0|parse | "device": {
0|parse | "device": "Chrome",
0|parse | "os": "MacOS",
0|parse | "osVersion": "Macintosh; Intel Mac OS X 10_13_6",
0|parse | "appName": "WebApp",
0|parse | "version": "0.3"
0|parse | },
0|parse | "data": {
0|parse | "email": "test123@outlook.com",
0|parse | "password": "test"
0|parse | }
0|parse | }
0|parse | }
0|parse | error: Failed running cloud function userRegister for user undefined with:

The cloud code gives me this error.

error: Parse error: Cannot read property 'apply' of undefined {"code":141,"stack":"ParseError: 141 Cannot read property 'apply' of undefined\n at error /node_modules/parse-server/lib/Routers/FunctionsRouter.js:121:16)\n at process._tickCallback (internal/process/next_tick.js:68:7)"}

I am not sure why?

The code i have works perfectly on the Azure server however doesn't work on local host. Any help regarding such matter would be appreciated.

**Comment by dplewis** [comment]
If it’s failing locally, you should be able to trace the issue node_modules/parse-server/lib/Routers/FunctionsRouter.js:121:16

Do you have a way for us to replicate this issue?

**Comment by ShadowCoderPro** [comment]
Unsure about replication but the code at functionrouter.js seems to be unclear.

 key: 'createResponseObject',
    value: function createResponseObject(resolve, reject, message) {
      return {
        success: function success(result) {
          resolve({
            response: {
              result: Parse._encode(result)
            }
          });
        },
        error: function error(code, message) {
          if (!message) {
            message = code;
            code = Parse.Error.SCRIPT_FAILED;
          }
          reject(new Parse.Error(code, message));
        },
        message: message
      };

**Comment by dplewis** [comment]
Throw a few console.logs in there.

What are you returning in your cloud code function and what version of the server are you running?

**Comment by ShadowCoderPro** [comment]
I am using 3.9.0 the latest. 

This only throws this: 

error: Parse error: Cannot read property 'apply' of undefined {"code":141,"stack":"ParseError: 141 Cannot read property 'apply' of undefined\n    at error (/node_modules/parse-server/lib/Routers/FunctionsRouter.js:121:16)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"}

**Comment by dplewis** [comment]
Looking at your error, it doesn't look like its coming from parse server at all. You have an error in your cloud code. The function router is just displaying that error i think.
