### ISSUE TITLE
beforeSave: Modifying object doesn't save object as expected

### ISSUE THREAD

**Issue by allanext** [parse-community/parse-server#6227]
### Issue Description

I'm modifying the object on the Parse cloud beforeSave hook but it does't save the modified object on the database

### Steps to reproduce

```
Parse.Cloud.beforeSave("m_apps", (request) => {
m_app_data = request.object.get('data');

Created object review_average: JSON.stringify(review_average) => 

 "{"tot_score":{"values":[22.1],"result":22.1},"does_the_applicant_have_a_sufficient_educational_degree":{"values":["Yes"],"result":{"Yes":1}}}"

m_app_data['review_average'] = review_average
request.object.set('data', m_app_data);
//request.object.set('data.review_average', review_average); // tried this too
```
If in the debugger I do a request.object.save() it will save correctly the object in the mongo database (with an expected second call of the function beforeSave). Of course doing a request.object.save() on the code will create an infinite loop. 

I'm I missing something to instruct Parse.Cloud to save the object ?

request.object.dirty()
true
request.object.dirtyKeys()
Array(1) ["data"]
 
### Expected Results

Saving the object review_average on the database

### Actual Outcome

Doesnt saves the abject just assigned. 

### Environment Setup

- **Server**
  - parse-server version : 3.9.0
  - Operating System:     MacOS 10.14
  - Hardware:             MBP
  - Localhost or remote server?: LOCALHOST

- **Database**
  - MongoDB version: db version v4.0.3
  - Storage engine:  default
  - Hardware:        MBP
  - Localhost or remote server? LOCALHOST

### Logs/Trace

No error logs
SHELL: export VERBOSE=1 
INIT parse server with: 

var api = new ParseServer({
  databaseURI: databaseUri || 'mongodb://localhost:27017/parse',
  cloud: process.env.CLOUD_CODE_MAIN || __dirname + '/cloud/main.js',
  verbose: true,

**Comment by dplewis** [comment]
There is a test case for this already.

https://github.com/parse-community/parse-server/blob/master/spec/CloudCode.spec.js#L138

Can you try to write a test case to replicate your issue as closely as possible?

**Comment by acinader** [comment]
does your beforeSave function return the object?  If not, try that.  If that doesn't fix it, put your full beforeSave function in the bug so we can see what's going on.

**Comment by dplewis** [comment]
@allanext Can you produce server logs VERBOSE=1?

**Comment by allanext** [comment]
@dplewis @acinader  sorry for the late follow up. I've realized it was something that I could do on the client side and it fixed my issue. 

I've just tried to replicate the issue with the following code but looks like it's working properly, apologies.

```
Parse.Cloud.beforeSave("m_apps", (request, response) => {
  
  m_app_data = request.object.get('data');
  review_average = {"tot_score":{"values":[666.1],"result":666.1},"does_the_applicant_have_a_sufficient_educational_degree":{"values":["Yes"],"result":{"Yes":1}}};

  // Set the data again. Then the save will process the save.
  m_app_data['review_average'] = review_average;
  request.object.set('data', m_app_data);
});
```

**Comment by dplewis** [comment]
Do you remember what you changed?
