### ISSUE TITLE
live query broadcast receiver

### ISSUE THREAD

**Issue by Anechasun** [parse-community/parse-server#6232]
Send to everyone except the person who created. same as `socket.broadcast.emit`

```javascript
var query = new Parse.Query("Message");
var subscription = client.subscribe(query, TOKEN);

 subscription.on("open", () => {
        console.log("subscription opened");
});

subscription.on("create", object => {
        console.log("object created");
});

subscription.on("update", object => {
        console.log("object updated");
});

subscription.on("delete", object => {
        console.log("object deleted");
});
```

**Comment by dplewis** [comment]
InstallationId was recently added to live query 

https://github.com/parse-community/Parse-SDK-JS/pull/979/files

You can check if the installationId returned matches the installationId your client. This will work after the next server update.
