### ISSUE TITLE
WithinKilometers and FullText query not work

### ISSUE THREAD

**Issue by cuervocomando666** [parse-community/parse-server#6235]
Hi, I'm trying to use withinKilometers and fullText query, but I get  error 500

This code works perfect:
query.matches ("text", text, 'i');
query.withinKilometers ('location', point, distance);

But this code does not work:
query.fullText ("text", text);
query.withinKilometers ('location', point, distance);

I use parse 2.8.0 from Typescript

What is the problem?
thanks.

**Comment by dplewis** [comment]
Its a mongo limitation. You can't use text index with other special indexes like geo indexes. [here](https://docs.mongodb.com/manual/reference/operator/query/text/#restrictions)


> You cannot combine the $text expression, which requires a special text index, with a query operator that requires a different type of special index. For example you cannot combine $text expression with the $near operator.

**Comment by cuervocomando666** [comment]
ok thanks
