### ISSUE TITLE
Parse server does not support range

### ISSUE THREAD

**Issue by ExpDev07** [parse-community/parse-server#6244]
### Issue Description

Accessing a file on parse server on safari doesn't work due to Range header not being supported.

### Steps to reproduce

Using cURL: ``curl --range 0-100 http://localhost:3000/parse/files/path/to/file.mp4 -o test.mp4``. As you can see, this doesn't work, however, if you do ``--range 0-`` which most browsers do (but not safari, they do 0-1), it works. 
 
### Expected Results

For video to be returned.

### Actual Outcome

Get a corrupt file.

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : ^3.9.0
  - Operating System:     Windows 10
  - Hardware:             i7-4790k, 8GB RAM, GeForce GTX 980
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): localhost (both fails).

- **Database**
  - MongoDB version: unsure
  - Storage engine:  unsure
  - Hardware:        unsure
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): mLab

### Logs/Trace

None.

**Comment by dplewis** [comment]
Parse Server recently supported byte range. https://github.com/parse-community/parse-server/pull/6028

What file adapter are you using? Also does .mov files work for you in safari?

**Comment by ExpDev07** [comment]
> Parse Server recently improved byte range support. #6028
Well, try the cURL command on a .mp4, it doesn’t work.

> What file adapter are you using? Also does .mov files work for you in safari?
I don’t set a file adapter, so the default one. I believe safari only uses the “Range: 0-1“ header on MP4 files (uses “Range: 0-“ like other browsers on other file types) so it probably does work then, but I need it working for mp4. Don’t quote me on that though. 

Thanks for the quick reply!

**Comment by ExpDev07** [comment]
This was an issue with using the default file adapter (storing directly in db). Switching over to AWS bucket fixed it. Not entirely sure why.
