### ISSUE TITLE
No `installationId` for `ws_disconnect`

### ISSUE THREAD

**Issue by JeromeDeLeon** [parse-community/parse-server#6259]
### Issue Description

Following the conversation from [Parse Community](https://community.parseplatform.org/t/how-to-monitor-users-status/883). I decided to follow what @davimacedo said, but `installationId` was `undefined`.

### Steps to reproduce

```js
Parse.Cloud.onLiveQueryEvent(data => {
    console.log(data)
});
```
 
### Expected Results

Contains `installationId`

### Actual Outcome

`installationId` = `undefined`

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 3.9.0
  - Operating System:     Ubuntu 18.04
  - Hardware:             [FILL THIS OUT]
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): localhost

- **Database**
  - MongoDB version: 4.2.1
  - Storage engine: default
  - Hardware:        [FILL THIS OUT]
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): localhost

### Logs/Trace

```
// ws connect
{ event: 'ws_connect', clients: 0, subscriptions: 0 }

// connect
{
  client: Client {
    id: '545db257-c317-4cc3-8526-7ed6c6ae7aa8',
    parseWebSocket: ParseWebSocket {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      ws: [WebSocket],
      clientId: '545db257-c317-4cc3-8526-7ed6c6ae7aa8'
    },
    hasMasterKey: false,
    sessionToken: 'r:fae9e151b5a0a3693a198b7fcd368f8a',
    roles: [],
    subscriptionInfos: Map {},
    pushConnect: [Function],
    pushSubscribe: [Function],
    pushUnsubscribe: [Function],
    pushCreate: [Function],
    pushEnter: [Function],
    pushUpdate: [Function],
    pushDelete: [Function],
    pushLeave: [Function]
  },
  event: 'connect',
  clients: 1,
  subscriptions: 0,
  sessionToken: 'r:fae9e151b5a0a3693a198b7fcd368f8a',
  useMasterKey: false,
  installationId: undefined
}

// subscribe
{
  client: Client {
    id: '545db257-c317-4cc3-8526-7ed6c6ae7aa8',
    parseWebSocket: ParseWebSocket {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      ws: [WebSocket],
      clientId: '545db257-c317-4cc3-8526-7ed6c6ae7aa8'
    },
    hasMasterKey: false,
    sessionToken: 'r:fae9e151b5a0a3693a198b7fcd368f8a',
    roles: [],
    subscriptionInfos: Map { 1 => [Object] },
    pushConnect: [Function],
    pushSubscribe: [Function],
    pushUnsubscribe: [Function],
    pushCreate: [Function],
    pushEnter: [Function],
    pushUpdate: [Function],
    pushDelete: [Function],
    pushLeave: [Function]
  },
  event: 'subscribe',
  clients: 1,
  subscriptions: 1,
  sessionToken: 'r:fae9e151b5a0a3693a198b7fcd368f8a',
  useMasterKey: false,
  installationId: undefined
}

// disconnect
{ event: 'ws_disconnect', clients: 0, subscriptions: 0 }
```

**Comment by davimacedo** [comment]
Can you please try to test against master? The installationId fix was not yet released.

**Comment by JeromeDeLeon** [comment]
I haven't tried doing that nor have any idea on how to test the master branch sorry. If it was implemented then I'll just wait for it to release then.

**Comment by JeromeDeLeon** [comment]
Can you reference the merge fix?

**Comment by davimacedo** [comment]
I think this one should solve the issue: https://github.com/parse-community/parse-server/pull/6180

**Comment by JeromeDeLeon** [comment]
Do you have plans on when this will be release?

**Comment by dplewis** [comment]
@JeromeDeLeon This is the fix [here](https://github.com/parse-community/parse-server/pull/6230/files#diff-7ff5112d0c45b691746af5e56e5e3c92)

If you want to try out the master branch

https://github.com/parse-community/parse-server#want-to-ride-the-bleeding-edge

We should do a release soon, probably this weekend.

**Comment by JeromeDeLeon** [comment]
Thanks to both of you :smiley:
