### ISSUE TITLE
Parse server removing object from relation when I adding a object to relation that already exist?

### ISSUE THREAD

**Issue by codetycon** [parse-community/parse-server#6262]
### Issue Description

I am running open source parse server on heroku with mongodb (mlab). I have an table and in the table I have a relation field.

I am adding a new object to relation using add

`relation.add(offer);`

But the problem is if `offer` (object from another table) already exist in relation then this query removing offer from relation instead of add.

### Steps to reproduce

1. Let's support in the relation field I have 4 items (Item1, Item2, item3, Item4). 
2.Trying to add item using `relation.add(Item1);`, `relation.add(Item2);` ,`relation.add(Item4);`, `relation.add(Item4);` 
3. After this in relation field is showing empty.
4. And if I perform step-2 again then relation field showing items in relation field. Means if a Item already exist in relation then `relation.add`  removing that item.
 
### Expected Results
Items should be in relation field

### Environment Setup

- **Server**
  - parse-server version 2.8.4
  - Localhost or remote server?  Heroku

- **Database**
  - MongoDB version: Mlab
  - Localhost or remote server? mLab

I have also created a question on stackoverflow, here you can check: https://stackoverflow.com/questions/59188264/parse-server-removing-object-from-relation-when-i-adding-a-object-to-relation-th?noredirect=1#comment104599444_59188264

**Comment by JeromeDeLeon** [comment]
I think this [line](https://github.com/parse-community/Parse-SDK-JS/blob/master/src/ParseOp.js#L325) is the culprit to avoid adding duplicate objects. I mean why should you add duplicate objects in the first place? If that's the case, Parse should have `addUnique` and `add` to separate the use case, but that would break currently if they accidentally allow non-unique object to pass `add`.

`addUnique` and `add` is available to array field but you can use it to store relations.

**Comment by davimacedo** [comment]
@codetycon could you please upgrade to Parse Server latest version and check if the error persists?

**Comment by codetycon** [comment]
If I upgrade Parse Server then it may break other part of my application..

**Comment by davimacedo** [comment]
I don't think so. Would you be willed to write a test case to check if this problem still exists in the most recent version? If it is case, we can try to fix it and then you can use the same fix and apply to your fork.

**Comment by codetycon** [comment]
Okay, I am creating a instance of latest version of parse server..

**Comment by codetycon** [comment]
I have done setup of latest version of parse server and imported my cloud function from my previous instance(v 2.8.4) 

But all functions throwing an error `response.success() is not a function`. I have found a [question](https://stackoverflow.com/questions/52081863/parse-cloud-code-function-response-success-is-not-a-function) asked by other user on [stackoverflow](https://stackoverflow.com/questions/52081863/parse-cloud-code-function-response-success-is-not-a-function)


But the  answer of the question on stackoverflow is : 

> Since parse-server version ^3.0.0, cloud codes no longer use callbacks. You can use promise or async functions. Here is how you should change your cloud function.

Is there any better way to fix the error because  I have an more than 70 functions and I can't  rewrite them..

**Comment by JeromeDeLeon** [comment]
You do not need to call `response.success()` or `response.error()` since `response` is no longer available.

```js
Parse.Cloud.define("sample", req, => {
  return new Parse.Query("SampleClass").find();
});
```

**Comment by codetycon** [comment]
> I think this [line](https://github.com/parse-community/Parse-SDK-JS/blob/master/src/ParseOp.js#L325) is the culprit that avoids adding duplicate objects. I mean why should you add duplicate objects in the first place? If that's the case, Parse should have `addUnique` and `add` to separate the use case, but that would break currently if they accidentally allow non-unique object to pass `add`.
> 
> `addUnique` and `add` is available to array field but you can use it to store relations.

`addUnique` is not working..

**Comment by codetycon** [comment]
> I don't think so. Would you be willed to write a test case to check if this problem still exists in the most recent version? If it is case, we can try to fix it and then you can use  the same fix and apply to your fork.

I have set up latest parse sdk but I can't use it for production site because for this I have to change my cloud functions which is quite expensive way.

can you please suggest me an alternative way.

**Comment by davimacedo** [comment]
I couldn't reproduce the problem. I wrote the test case below but it is passing.
https://github.com/back4app/parse-server/commit/86322035793254de8e1f621d47469c8c290d18cc

Are you able to write a test case like this one that I sent that fails?
