### ISSUE TITLE
Project is not original parse codebase

### ISSUE THREAD

**Issue by allyraza** [parse-community/parse-server#6270]
I came across this relatively recently, I have notice going through the code it is a node project. As far as I know the original parse stuff was in ruby and rails, I know someone who worked for facebook and after the acquisition he got to work on parse scaling notification server and the api server.

it is very misleading, maybe mention in the readme that it is not the original codebase.

Thanks

**Comment by TomWFox** [comment]
I don’t believe there is any claim that Parse Server is the original codebase.

I also don’t think it’s misleading as Parse.com was an MBaaS for hundreds of thousands of developers & apps whereas Parse Server is self hosted single tenant backend.

Also worth noting that other parts of the Parse Platform are mostly original I.e. the client SDKs.
