### ISSUE TITLE
Parse server : How to store / retrieve JSON Object column

### ISSUE THREAD

**Issue by marxyes** [parse-community/parse-server#6276]
I have column named address type object and I want to Retrive using REST API How to retrieve student?where={“address”:“city”: “toronto” }

address:
{
  "street1": "abc",
"street2" : "sadas",
"area" : "Downtown",
"city" : "toronto",
"state" : "ontario",
"country" : "Canada"
}

it throw error :    "code": 107,
    "error": "You cannot use [object Object] as a query parameter."

**Comment by omairvaiyani** [comment]
Try `student?where={"address.city": "toronto"}` although you may need to run a URL encoder depending on your setup

**Comment by dplewis** [comment]
@marxyes You will want to use dot notation (nested) as @omairvaiyani has posted.
