### ISSUE TITLE
Missing encodeURIComponent in resetPassword 302 link

### ISSUE THREAD

**Issue by Klaitos** [parse-community/parse-server#6277]
### Issue Description

If I try to reset password on a user with email : "email+123@example.com", the redirect 302 link location is not encoded. Then in Express when I try to retrieve parameter from URL  in success page I have "console.log(query.username) "email 123@example.com."

### Steps to reproduce

Create new User with following email `email+123@example.com`
Call `http://localhost:1337/api/requestPasswordReset` with json body {
```
{
  "email" : "email+123@example.com"
 }
```
Click on the reset link in email
Fill the form
 
### Expected Results

After the new password filled, I should be redirected to 
http://localhost:1337/password/updated?username=email%2B23@example.com

### Actual Outcome

I am redirect to 
http://localhost:1337/password/updated?username=email+123@example.com

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 3.9.0
  - Operating System:     MacOs 10.14.6
  - Hardware:             MacBook Pro
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Localhost

- **Database**
  - MongoDB version: 3.6
  - Storage engine:  WiredTiger
  - Hardware:  MacBrook Pro
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): localhost

**Comment by davimacedo** [comment]
Thanks for reporting. Would you be willed to tackle this one?

**Comment by dplewis** [comment]
Closing via https://github.com/parse-community/parse-server/pull/6278
