### ISSUE TITLE
Add hint to Parse.Query

### ISSUE THREAD

**Issue by stevestencil** [parse-community/parse-server#6288]
**Is your feature request related to a problem? Please describe.**
My application has a collection with over 1 million objects in it. There are several indexes in this collection. The majority of the time, when querying this collection mongo picks the right index. Sometimes mongo will not pick the right index and queries can take sometimes 30 seconds. When I run the same query by accessing mongo directly, and passing in a hint to ensure the correct index is used, my query time goes to 0.021s.

**Describe the solution you'd like**
A solution to this would be to allow Parse.Query to accept a hint parameter

**Describe alternatives you've considered**
There are no other alternatives

**Additional context**
I would imagine we could add another function to Parse.Query.prototype called "hint". It would take 1 argument which is the name of the index  you want to use.

**Comment by davimacedo** [comment]
In my opinion that would be a great new feature. Is this something that you'd be willed to work on?

**Comment by stevestencil** [comment]
I will give it a shot... I guess it should be passed in as an option (string or object) when calling find, count, each, etc.?

**Comment by davimacedo** [comment]
Yes. I think it should be an option similar to readPreference. If you track readPreference down from JS SDK to Parse Server Mongo Adapter, and add the new option in a similar way, you will probably achieve what you need.

**Comment by stevestencil** [comment]
I see readPreference is set with a readPreference function on Parse.Query... should I create a "hint" function or just allow for a "hint" param to be passed into the find, count, etc. options?

**Comment by davimacedo** [comment]
I think both work but I personally prefer the function. @dplewis thoughts?

**Comment by dplewis** [comment]
Historically users should manage their own indexes. If you have mLab you can view slow queries and add indexes that way or use Mongo `db.collection.find().explain()` or similar for your database.

The current index system could use some rework (I added it when I was an inexperienced developer).

For this feature we could do `query.explain()`. To do this we can add a new endpoint in the router.

```
/explain/MyObject
```

You can copy the PR for [aggregate](https://github.com/parse-community/parse-server/pull/4207/files).

**Comment by johanarnor** [comment]
We also have a case when mongo (via mlab) picks the "wrong" index, making the query time out (we've got a limit on 10 seconds). So this would be much appreciated!

**Comment by davimacedo** [comment]
@dplewis besides the possible improvements to the index system, @stevestencil 's idea is actually to support MongoDB `hint` feature in which you can force MongoDB to use a certain index when running a query. It is very useful and I also needed it in the past myself. Take a look here: https://docs.mongodb.com/manual/reference/operator/meta/hint/

**Comment by dplewis** [comment]
Oh I see, thanks for the link

**Comment by dplewis** [comment]
Closing via https://github.com/parse-community/parse-server/pull/6322
