### ISSUE TITLE
Does parse server support rtc signaling ?

### ISSUE THREAD

**Issue by memishood** [parse-community/parse-server#6292]
I want use webrtc with parse server, can i send sdp and ice data to peer user (without save) using parse ?

**Comment by dplewis** [comment]
This currently isn’t supported. I’m not familiar with WebRTC but you could implement it with express. Parse Server is built on top of express.

**Comment by memishood** [comment]
Could you add the feature tag to this issue?

**Comment by dplewis** [comment]
@memishood I don't see how RTC would work with Parse. How do you see this feature being used?

**Comment by mtrezza** [comment]
Thank you for suggesting.
I'm closing this as it seems to be in an early stage of discussion about Parse Server architecture.

Discussions are better suited in our [Community Forum](https://community.parseplatform.org) while we expect feature requests on GitHub to be in a more advanced conceptual stage.

Feel free to comment if you have any questions and we can re-open this issue.
