### ISSUE TITLE
Mininum version of Parse-serve that supports MongoDB 4.2

### ISSUE THREAD

**Issue by grassland-curing-cfa** [parse-community/parse-server#6293]
I am currently with with Parse-server 2.8.4 hosted on Heroku and a MongoDB M2 Cluster (mongoDB 4.0 version) hosted on MongoDB Atlas.

I was recently advised that my Cluster would be automatically upgraded to 4.2.

I would like to know which version of Parse-server at minimum I will need to upgrade to from 2.8.4 to support a MongoDB 4.2 Cluster.

Thank you in advance.

Alex

**Comment by grassland-curing-cfa** [comment]
I have upgraded my mongoDB cluster to mongo 4.2.2 but left Parse-server as 2.8.4. It seems it works well with 4.2.2 at the current stage.

**Comment by davimacedo** [comment]
Our CI doe not have any automated test running against 4.2 so we can't be sure. You can pull the 2.8.4 release and run the tests against it so you can make sure that everything will work fine.

**Comment by dplewis** [comment]
@grassland-curing-cfa 4.2 support was added in MongoDB driver 3.3.0. Parse Server 2.8.4 ships with that driver. Because the driver supports 4.2, we can't assume that Server 2.8.4 does.
