### ISSUE TITLE
Permission denied for action count on class parse server

### ISSUE THREAD

**Issue by ashish-naik** [parse-community/parse-server#6295]
### Issue Description

I am using Parse Server v2.8.2 and suddenly started getting error code 119 on one of the classes. I found a post that showed a screenshot of parse dashboard CLP with count checkbox.

I was using dashboard of lower version so couldn't enable it. So upgraded dashboard and error went away after i enable count permission.

But i am wondering why i started getting this issue suddenly?

### Steps to reproduce

Execute a query on problematic class.

### Environment Setup

- **Server**
  - parse-server version - 2.8.2
  - Operating System:     Not sure
  - Hardware:             Not sure
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Heroku

- **Database**
  - MongoDB version: Not sure
  - Storage engine:  Not sure
  - Hardware:        Not sure
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): Heroku

### Logs/Trace

 error: Parse error: Permission denied for action count on class myclass. {"code":119,"stack":"Error: Permission denied for action count on class book_requests.\n    at Function.validatePermission (/app/node_modules/parse-server/lib/Controllers/SchemaController.js:1299:11)\n    at SchemaController.validatePermission (/app/node_modules/parse-server/lib/Controllers/SchemaController.js:1304:29)\n    at schemaController.getOneSchema.catch.then.schema (/app/node_modules/parse-server/lib/Controllers/DatabaseController.js:1126:65)\n    at <anonymous>\n    at process._tickDomainCallback (internal/process/next_tick.js:229:7)"}

**Comment by dplewis** [comment]
Unfortunately we don't support 2.8.2 anymore. Please update to the latest version of Parse Server.

Reopen if this issue still persists and a method to reproduce this issue.
