### ISSUE TITLE
JS query.distinct question...

### ISSUE THREAD

**Issue by LilMoke** [parse-community/parse-server#6308]
Hello,

I have written a small test func to test retrieving distinct records from parse. 

I was wondering how I can retrieve all the fields associated with the distinct records in one call?

The func below does successfully retrieve distinct records, but only for the field specified.

```
Parse.Cloud.define("getDistinct", function(req, res)
{
 var query = new Parse.Query("Chats");
 useMasterKey: true
 query.distinct("conversationId")
    .then(function(results) {
        res.success({"results" : results
		});
 })
 .catch(function(error) {
   res.error("error" + error);
 });
//	})
});

```

Thanks for the help!!

**Comment by dplewis** [comment]
This currently isn't possible. In your case distinct will group by unique `conversationId`. You will have multiple field values per conversationId, which value will be set per field?

If you want you can try to use aggregates.
