### ISSUE TITLE
Wrong Object Count in PostgreSQL

### ISSUE THREAD

**Issue by saimoomsafayet** [parse-community/parse-server#6311]
### Issue Description

I am currently using Parse Server with PostgreSQL as the database. Problem is, for some classes count is always returning 0 even if there are objects.

### Steps to reproduce

1. Create a class.
2. Add some row using parse dashboard (2.0.5)
3. See that the count is not getting updated in the Data browser - stays 0. 
4. Also if I submit a count query via rest or JS SDK, it returns 0.
Ref: [https://docs.parseplatform.org/js/guide/#counting-objects](https://docs.parseplatform.org/js/guide/#counting-objects)

Here is a sample screenshot of the mismatched User count.
[https://imgur.com/a/J3Q9N3p](https://imgur.com/a/J3Q9N3p)

### Expected Results

Provide the actual count of the objects in a Class. 

### Actual Outcome

Returns 0

### Environment Setup

- **Server**
  - parse-server version: 3.9.0
  - Operating System:  Ubuntu
  - Hardware:   Core i3 3rd Gen, 16 GB ram
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): [localhost]

- **Database**
  - MongoDB version: [Not applicable]
  - Postgres Version: 12.1
  - Storage engine:  [Not applicable]
  - Hardware:  Same as previous
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): localhost

**Comment by dplewis** [comment]
There is a known issue with Postgres called slow counting. Counting can be an expensive operation so we provide an estimate count to allow for scalability.

See the conversation [here](https://github.com/parse-community/parse-server/pull/5330).

**Comment by saimoomsafayet** [comment]
Noted. Closing this issue. Thanks!
