### ISSUE TITLE
aggregate function returns null for number fields

### ISSUE THREAD

**Issue by suathh** [parse-community/parse-server#6312]
### Issue Description

When I use aggregate function in JS SDK it is working fine with string columns but when I try to use it with a column with number type it gives reference value as null.

### Steps to reproduce

```
Parse.Cloud.define("group", async (req) => {
  var pipeline = [
    { group: { objectId: '$elapsed' } }
  ];
  var query = new Parse.Query("Fixture");
  return query.aggregate(pipeline)
    .then(function (results) {
      console.log(results);
      return results;
    })
    .catch(function (error) {
      throw error;
    });
});
```
 
elapsed is a number field. Collection has 2 different values 0 and 90 
### Expected Results

Result should be like 

`{
    "result": [
        {
            "objectId": 0
        },
        {
            "objectId": 90
        }
    ]
}`

### Actual Outcome

Current function returns as follows

`{
    "result": [
        {
            "objectId": null
        },
        {
            "objectId": null
        }
    ]
}`

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : [3.7.2]
  - Operating System:     [macOS Catalina 10.15.2]
  - Hardware:             [Macbook Pro  E2015]
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): [Localhost]

- **Database**
  - MongoDB version: [3.6.9]
  - Storage engine:  [WiredTiger]
  - Hardware:        [Sandbox DB]
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): [mLab]

**Comment by saimoomsafayet** [comment]
It is fixed in the latest version of parse server - 3.9.0

See: [https://github.com/parse-community/parse-server/pull/5994](https://github.com/parse-community/parse-server/pull/5994)

If you want to use the current version try this solution: 
[https://github.com/parse-community/parse-server/issues/5989#issuecomment-526007093](https://github.com/parse-community/parse-server/issues/5989#issuecomment-526007093)

**Comment by suathh** [comment]
Thanks
