### ISSUE TITLE
Parse Server Cloud onLiveQueryEvent

### ISSUE THREAD

**Issue by memishood** [parse-community/parse-server#6314]
Hi, i have questions about the title.

1-) does onLiveQueryEvent trigger support async / await ?

2-) could we get parse user or objectId from onLiveQueryEvent if logged in (authenticated) ?
```
Parse.Cloud.onLiveQueryEvent( ({event, client, sessionToken, useMasterKey, installationId, clients, subscriptions, error}) => {
    if (event === 'ws_disconnect') {
        //i want know who is disconnected as parse user
    }
});
```

server: 3.9.0

**Comment by dplewis** [comment]
1) I believe so, but I don't think it can resolve a promise (returns a promise). You can try it in your code and let us know if it works. Here is the code for [runLiveQueryEvents](https://github.com/parse-community/parse-server/blob/2f05d819f3e29ae26c2070e7710ab7edb9787e18/src/triggers.js#L660).

2) If you have the sessionToken or installationId you can query for that user in the _Session or _installation classes.
