### ISSUE TITLE
Cannot use latest parse-server with latest parse-dashboard and graphql

### ISSUE THREAD

**Issue by Blemming** [parse-community/parse-server#6324]
### Issue Description
Starting a fresh project with parse-server and parse-dashboard makes graphql unuseable because of version difference of graphql

Mentioned in #6214 but closed for what ever reason

### Steps to reproduce
Npm install parse-server , npm install parse-dashboard, run in express app, go in the playground either in dashboard or not, you will have a error 500
 
### Expected Results

Expected playground to work

### Actual Outcome

Get a error 500 mentionning that there is a problem with the graphql versioning

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 3.9.0
  - Operating System:    Windows
  - Hardware: i5 8gb ram
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): local

- **Database**
  - MongoDB version: 4.0.14
  - Storage engine:  Wireshark ( i think)
  - Hardware:        1gb/ram 1cpu droplet
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): Digital ocean

### Logs/Trace

Something like : 
Ensure that there is only one instance of "graphql" in the node_modules
directory. If different versions of "graphql" are the dependencies of other
relied on modules, use "resolutions" to ensure only one version is installed.

https://yarnpkg.com/en/docs/selective-version-resolutions

Duplicate "graphql" modules cannot be used at the same time since different
versions may have different capabilities and behavior. The data from one
version used in the function from another could produce confusing and
spurious results.

### Fix

~Issue would simply be fixed by merging master with the 3.9.x branch as the master's versions are all good and are updated. ( Which caused me many headaches wondering why npm wasnt installing the same versions than the package.json in the master branch 😂)~

I guess this should be fixed in 3.10, I'm just wondering what version of parse-dashboard is the current (3.9.0) version of parse-server suposed to work with ?

**Comment by Wouter125** [comment]
Second this. Having the same issue, with the following lines in my package.json;

```
"parse-dashboard": "^2.0.5",
"parse-server": "^3.10.0"
```

Do you have any solution yet?

**Comment by Wouter125** [comment]
Nevermind. I dropped the parse sample project and initialised my own, now everything works as it should.

**Comment by davimacedo** [comment]
@Blemming could you please share your package.json?

**Comment by Blemming** [comment]
This should be fixed now that 3.10.0 was released. I was using parse-server 3.0.9 with parse-dashboard 2.0.5 . I no longer have a package.json since I have chosen to not migrate my back end to parse.
