### ISSUE TITLE
LiveQuery connection fails because sessionToken is null, but sessionToken is present in localStorage

### ISSUE THREAD

**Issue by akritskiy** [parse-community/parse-server#6325]
### Issue Description

LiveQuery works fine most of the time, but sometimes opening the connection fails because the sessionToken is null.

The error message on the backend is: "error: Connect message error %s"

This message comes from: /node_modules/parse-server/lib/LiveQuery/ParseLiveQueryServer.js (line 317)

I added some console logs and the actual error message is: Invalid type: null (expected string)
and the request is
```
{ op: 'connect',
  applicationId: 'MyAppId',
  javascriptKey: 'myKey',
  sessionToken: null,
  installationId: '109b15ba-b772-4962-9dc4-ae0da8ded1c9' }
```

It looks like the request fails because the sessionToken is null. When I look in local storage, the sessionToken is there, and all other requests work fine as far as I can tell.

Another observation: In the network tab in Chrome Dev Tools, I can see Cloud functions being called. As I go down the list, it looks like the first half of the requests have the sessionToken in the request payload. The second half of the requests don't include the sessionToken. These requests work fine, but it's a bit odd to me that Parse sends the sessionToken with half of the requests, then completes the rest of the requests w/o the sessionToken. Is this intended behavior?

### Steps to reproduce

In App.js we have the Parse setup:
```
import Parse from 'parse'
Parse.initialize('MyApp', 'myKey')
Parse.serverURL = process.env.API_URL + '/parse'
Parse.CoreManager.set('REQUEST_ATTEMPT_LIMIT', 0)
```

Create a simple query for a single object with a "count" on it, subscribe, then handle updates...

```
const query = new Parse.Query('test')
query.equalTo('objectId', '7bXrkGxHFv')
query.limit(1)

const livequerySubscription = await query.subscribe()

livequerySubscription.on('open', () => {
    console.log('livequery connection opened')
})

livequerySubscription.on('update', obj => {
    console.log('livequery received update, object: ', obj.toJSON())

    let count = obj.toJSON().count
    setCount(count) // This displays the "count" in the UI
})
```

And then I have a button that changes the count and saves.

I log in with a user and navigate to my testing screen. In the console, I see "livequery connection opened." I click the button and see "livequery received update" and the UI gets updated with the new count.

I hit refresh. Same procedure works.

I repeat this several times and eventually I don't see the connection opened message. I click the button, the count gets updated but I do not get a "livequery received update" message and the UI doesn't get updated.

On the API side, I see
```
Invalid type: null (expected string)

The request: 
{ op: 'connect',
  applicationId: 'MyAppId',
  javascriptKey: 'myKey',
  sessionToken: null,
  installationId: '109b15ba-b772-4962-9dc4-ae0da8ded1c9' }
```

### Expected Results

LiveQuery connection should open consistently.

### Actual Outcome

Seems like Parse stops sending the sessionToken with some requests and it breaks LiveQuery.

### Environment Setup

- **Server**
  - parse-server version: 3.9.0
  - Operating System:
  - Hardware: 
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Local (Mac), but this also happens on remote (Azure)

- **Database**
  - MongoDB version: 4.0
  - Storage engine:  Whatever the default is
  - Hardware: 
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): remote, MongoDB Atlas

**Comment by dplewis** [comment]
A new version of Parse Server was released. Can you update and see if your issue persists?

**Comment by akritskiy** [comment]
@dplewis Sure, I'll update to 3.10.0 and report back.

**Comment by akritskiy** [comment]
@dplewis Updating didn't resolve the issue. Since it's more of a front-end issue, I should've posted it on the Parse JS SDK anyway, so I'll close this out and repost.
