### ISSUE TITLE
Parse-server release 3.10.0 wrong mongodb update version mentioned.

### ISSUE THREAD

**Issue by yog27ray** [parse-community/parse-server#6334]
In recent release of [Parse-server@3.10.0](https://github.com/parse-community/parse-server/releases/tag/3.10.0) version for mongodb mentions is 3.3.5 but in package.json it is 3.3.4.

**Comment by dplewis** [comment]
Where do you see 3.3.4? I see 3.4.1.

https://github.com/parse-community/parse-server/blob/0fc811ad8327b63866af1d905ecfb7ae747cc991/package.json#L46

**Comment by dplewis** [comment]
@yog27ray I’d recommend doing a clean install. 

Please reopen if you are still having the original replica set issue from 3.3.2.
