### ISSUE TITLE
3.10.0 onLiveQueryEvent trigger

### ISSUE THREAD

**Issue by memishood** [parse-community/parse-server#6336]
Hello i migrated to 3.10.0 for fix installationId on live query disconnect event but the problem still continues. i am getting undefined, when will you fix this? thanks a lot

**Comment by dplewis** [comment]
What are using for your client? If it’s JSSDK what version are you using?

**Comment by memishood** [comment]
Android Client

**Comment by memishood** [comment]
Could you find any soultion for this ? i am using parse server 3.10.0 , but i can't get any information on liveQueryEvent triggers when disconnect... I need this so much...
Client is Android
Parse-SDK-Android 1.22.1

**Comment by dplewis** [comment]
I believe this will require an update on the Android side to send data to the server. Please open an issue there. I can have a look although I’m not the best android dev.

**Comment by memishood** [comment]
They dont answer to any issue

**Comment by memishood** [comment]
@dplewis did you test on js sdk and are you sure working perfectly with 3.10.0 ?
