### ISSUE TITLE
Support for Redshift

### ISSUE THREAD

**Issue by srameshr** [parse-community/parse-server#6338]
**Is your feature request related to a problem? Please describe.**
Our team was looking at using the Parse ORM to query our AWS Redshift DB instead of a separate query language. Is this something that has been previously discussed?

**Describe the solution you'd like**
Server URL would be just a string to Redshift clusters.

**Describe alternatives you've considered**
Considering PostgresSQL hosted on AWS.

**Additional context**
NONE

**Comment by srameshr** [comment]
@dplewis

**Comment by davimacedo** [comment]
Currently there is no official support to Redshift as a database for Parse Server. You'd need to create a new Database Adapter.
