### ISSUE TITLE
Facebook login without PFFacebookUtils

### ISSUE THREAD

**Issue by khawarb** [parse-community/parse-server#6350]
Previously i was using PFFacebookUtils to login/signup in app using user's Facebook but somehow PFFacebookUtils stopped working in my app due to clash with other libraries. So i moved to actual Facebook login. 

Now all working fine here when user signed up/login using facebook SDK and then after searching in Parse server am logging the user in using username and password.

Now the issue is how to login the previously added user which was logged in using PFFacebookUtils through simple parse method "logInWithUsername and password". I can't find user's password in parse "User" class.

Any help would be much appreciated.
Thanks

**Comment by davimacedo** [comment]
I believe you need to set a new password for these users and unlink them from facebook. Can you share what you tried so far?

**Comment by TomWFox** [comment]
I'm closing this due to lack of response, @khawarb if you have further questions / issues we can reopen it.
