### ISSUE TITLE
Possible Documentation Issue

### ISSUE THREAD

**Issue by githubsaturn** [parse-community/parse-server#6353]
In the Dockerfile, there is a line which defines two volumes:
https://github.com/parse-community/parse-server/blob/3ed6535b233cf20c6cf853df88796f4b7f6edb99/Dockerfile#L18

Without specifying a volume in the run command, these volumes aren't easily accessible to the end user. I believe `-v` options need to be added in the sample run command:

https://github.com/parse-community/parse-server/blob/3ed6535b233cf20c6cf853df88796f4b7f6edb99/README.md#L102

**Comment by davimacedo** [comment]
Hi. Thanks for reporting. Can you please send a PR to the [docs repo](https://github.com/parse-community/docs) with your suggested improvement?
