### ISSUE TITLE
Support multiple parse instances in JS SDK

### ISSUE THREAD

**Issue by srameshr** [parse-community/parse-server#6354]
**Is your feature request related to a problem? Please describe.**
Unable to connect to multiple parse servers from UI (JS SDK)

**Describe the solution you'd like**
Allow multiple versions of Parse to exist. 

**Describe alternatives you've considered**
None. Have to invoke cloud code but not able to because of the limitation with parse JS SDK

**Comment by davimacedo** [comment]
That would be really good but I believe it would require a huge effort. Is it something that you would like to contribute? In the meantime, you can use the REST or GraphQL API in order to call the cloud code of a second app.

**Comment by TomWFox** [comment]
Seems like this should be transferred to the JS SDK repo?

**Comment by davimacedo** [comment]
I think so. It is actually [this](https://github.com/parse-community/Parse-SDK-JS/issues/203) issue that exists over there for a while.
