### ISSUE TITLE
How should I judge whether object.op is incrementOp / deleteop or setop

### ISSUE THREAD

**Issue by lybaiyy123** [parse-community/parse-server#6357]
How should I judge whether object.op is incrementOp / deleteop or setop?

thanks ,
I just want user can increment ,
so,in the  beforsave function ,i want   judge whether object.op is incrementOp / deleteop or setop?

**Comment by davimacedo** [comment]
try this:

```json
Parse.Cloud.beforeSave('MyClass', req => {
  const objJSON = req.object.toJSON();
  if (objJSON.myField.__op === 'Increment') {
    // this is an increment operation
  }
});
```
