### ISSUE TITLE
increment('test.name',1) with Parse.Cloud.beforeSave is not work 

### ISSUE THREAD

**Issue by lybaiyy123** [parse-community/parse-server#6358]
### Issue Description

var t=new Parse.Object('test')
t.set('test',{name:1,age:2})
t.save()

t.increment('test.name',1)
t.save()

when i creat a cloudFunction liks this,
 Parse.Cloud.beforeSave('test',function(req){
     // console.log(req.triggerName)
     // console.log(req.object.toJSON())
   
 })

t.increment('test.name',1)  is not work,

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : [FILL THIS OUT]  3.10
  - Operating System:     [FILL THIS OUT] windows
  - Hardware:             [FILL THIS OUT] 
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): [FILL THIS OUT]  Localhost 

- **Database**
  - MongoDB version: [FILL THIS OUT] 3.4?
  - Storage engine:  [FILL THIS OUT] 
  - Hardware:        [FILL THIS OUT]  4C8G
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): [FILL THIS OUT]  remote server

### Logs/Trace
![QQ截图20200122174829](https://user-images.githubusercontent.com/52989321/72883537-70079300-3d3f-11ea-9507-503ffa325097.png)

**Comment by davimacedo** [comment]
Thanks for reporting. Could you please write a test case?

**Comment by lybaiyy123** [comment]
> Thanks for reporting. Could you please write a test case?

step 1:
var t=new Parse.Object('testobject')
t.set('testFiled',{'name:1','age:2'})
t.save()


step 2:
creat a cloudFunction liks this,
Parse.Cloud.beforeSave('test',function(req){
// console.log(req.triggerName)
// console.log(req.object.toJSON())
})

step3:
t.increment('testFiled.name',1)
t.save()
 
expected result:
after   t.save() , the testFiled={'name:2','age:2'}

**Comment by dplewis** [comment]
Closing via https://github.com/parse-community/parse-server/pull/7003
