### ISSUE TITLE
Parse Server 3.x Parse.Cloud.httpRequest no longer able to send body for GET request

### ISSUE THREAD

**Issue by asdf01** [parse-community/parse-server#6361]
The httpRequest class no longer seems to be able to do a GET with a request body anymore.  It looks like the library used to do the http request has been completely changed in Parse Server 3.x.  

The parse server classes api allows specification of a where condition for the GET http method.  This no longer seems to work in Parse Server 3.10.0.

This curl is a simulation for what the GET request should do:
```
curl -X GET  -H "Content-Type: application/json" https://postman-echo.com/get -d "{\"where\": {\"testField01\": \"testValue01\"}}"
```
Result: 
```
{"args":{"where":{"testField01":"testValue01"}},"headers":{"x-forwarded-proto":"https","host":"postman-echo.com","content-length":"41","accept":"*/*","content-type":"application/json","user-agent":"curl/7.55.1","x-forwarded-port":"443"},"url":"https://postman-echo.com/get"}
```
But the equivalent Parse.Cloud.httpRequest call would not have anything in the "args" field.  

Thanks

**Comment by davimacedo** [comment]
Thanks for reporting. Could you please write a failing test case?

**Comment by dplewis** [comment]
Closing as Parse.Cloud.httpRequest has been deprecated.
