### ISSUE TITLE
[GraphQL] The old query way "results" is not working anymore

### ISSUE THREAD

**Issue by wahengchang** [parse-community/parse-server#6362]
### Issue Description
This is a simple graphQL string, that I used to query __**all**__ companies (i know it is not a best way, and it is not for a production project). As I see, after `parse-server` is updated to  `"parse-server": "3.10.0"`, there is not way to query `ALL` object of a `Class`.

```js
query getCompanies {
  companies  {
    count
	results {
          id
       }
    }
}
```

**Comment by wahengchang** [comment]
error message 

```
"Syntax Error GraphQL request (6:1) Unexpected }

5:   }
6: }
   ^
"
```

**Comment by Moumouls** [comment]
Since Parse 3.10 GraphQL Api spec have change from custom one to relay Spec.

**All of your graphql operations (Mutation/Query) need to be re designed**

Check the new API with the GraphQL Playground or check the docs: https://docs.parseplatform.org/graphql/guide/#queries

**Comment by wahengchang** [comment]
ya, i saw that doc is also updated. 

I am not very familiar in graphQL, feeling frustrated to redesign the existed lib on the project.

**Comment by omairvaiyani** [comment]
Appreciate that it's frustrating, but it is the reason why we placed this feature in beta and mentioned that's its a breaking change. Hopefully in the long run, this will pay off as we'll be consistent with other frameworks using graphql
