### ISSUE TITLE
Implement Azure Storage driver for file storage

### ISSUE THREAD

**Issue by rhuanbarreto** [parse-community/parse-server#6375]
I want to implement file storage in my application using Azure Storage Accounts and found a good library on https://github.com/felixrieseberg/parse-server-azure-storage that deals with it.

But it's still lacking some improvements, testing and documentation. Time has passed since last version of the library (4 years) but I'm willing to take the time to improve it and incorporate in Parse Server.

But first I need the green light to start the PR and look for some people that can help me on the development like we did on #6101.

Is it ok to implement it?

**Comment by dplewis** [comment]
We try to keeps the adapters separately from the main repo. If not we would have a lot of overhead. 

Can you try to collaborate with the owner of that repo or ask them if we can move it to this organization.
