### ISSUE TITLE
Quickly describe what parse server is and does

### ISSUE THREAD

**Issue by dfrankow** [parse-community/parse-server#6381]
I have looked at https://docs.parseplatform.org/parse-server/guide/ and https://parseplatform.org/ and https://github.com/parse-community/parse-server. I can't actually tell what Parse server does.

From github: _"Parse Server is an open source backend that can be deployed to any infrastructure that can run Node.js."_ Great. To do what?

From docs: _"Parse Server is an open source version of the Parse backend that can be deployed to any infrastructure that can run Node.js."_ Great. What does the Parse backend do? Or what does Parse do?

From parseplatform: _"The Complete Application Stack. Build applications faster with object and file storage, user authentication, push notifications, dashboard and more out of the box. no code required."_

Is that what Parse Server does? Provide object and file storage, user auth, push notifications, and more? There is a server and a client, so how does that work? I think at least the clients are intended to be integrated into other code?

If you have your own server, can people use pieces of ParseServer? In particular, I'm interested in "Data Sync". Is that a piece I could use?

This issue, however, is just to put a short description (or pointer) of what Parse Server is used for in github and the docs.

**Comment by TomWFox** [comment]
That is a fair point and is something I have considered addressing in the past. One of the issues I’ve found is that any description you give assumes some level of knowledge so it’s difficult to get the right balance between being it being simple to understand but also concise and at the same time explain the potential power and customisability of Parse Server.

I’m not sure whether you are necessarily asking for a better explanation or suggesting there should be one or both 🙂 but if you have any ideas I’m all ears...

**Comment by dfrankow** [comment]
Sorry, I have no ideas. I don't know what Parse Server does. I was just looking for a data syncing utility, and thought I'd share some feedback.

**Comment by TomWFox** [comment]
Ok, for me the simplest explanation is that Parse Server is basically [Firebase](https://firebase.google.com) but you host the backend server yourself (or use on of the Parse Server providers - Back4App & Sashido). Client SDKs for ease of querying, authentication, local storage etc, a dashboard for managing your database, REST API and GraphQL api.

**Comment by dfrankow** [comment]
Gotcha. Thanks!

**Comment by dfrankow** [comment]
You can resolve this if you wish. I'd suggest putting something of that description in the github page.

**Comment by acinader** [comment]
if you're not creating a web or app user interface, parse is probably not the right tool for what you're doing.  If you trying to sync data between two systems periodically, I'd think you'd want to use something like AWS Lambda that is triggered on a preset schedule by AWS Cloud Front.

**Comment by mtrezza** [comment]
I agree that the Github page could use a few lines of marketing working at the top. Maybe just take some inspiration from the marketing wording the original Parse site?

> Everything you need to create beautiful apps
> Focus on creating a great user experience and forget complex infrastructure. Instantly add a powerful core, push notifications, ~~and analytics~~ to your app with Parse. With native SDKs for Android, iOS, JavaScript, Unity, and more, Parse has an SDK for everyone, whether you’re creating a desktop or mobile app.

https://web.archive.org/web/20140317140146/https://parse.com/
https://web.archive.org/web/20151029234848/https://parse.com/products

**Comment by TomWFox** [comment]
Something like that could be a marked improvement! I would be happy to accept a pr to that effect.
