### ISSUE TITLE
redirection in cloud functions

### ISSUE THREAD

**Issue by MFelex** [parse-community/parse-server#6384]
### Issue Description

I have a problem via **redirection** in cloud function. 
when a client calls a specific cloud function , we need to redirect the client to a URL like [Http://google.com.](url)
Usually based on the documents we use `Parse.Cloud.httpRequest` with `followRedirects: true` , but the client receives an object instead of redirection.
What is the proper solution to redirect a client to the URL? I.e., how can we use redirection in parse platform?

### Steps to reproduce

Parse.Cloud.define("register", async (request) => {
  const httpResponse = await Parse.Cloud.httpRequest({
    url: 'https://google.com',
    followRedirects: true,
    method: 'GET'
  });
  return (httpResponse); // or even httpResponse.text
});

 
### Expected Results
redirect client to [google.com](url) page 

### Actual Outcome
just return an object like :
"result": {
        "status": 200,
        "headers": {
            "date": "Sat, 01 Feb 2020 14:11:17 GMT",
            "expires": "-1",
            "cache-control": "private, max-age=0",
            "content-type": "text/html; charset=ISO-8859-1",
            "p3p": "CP=\"This is not a P3P policy! See g.co/p3phelp for more info.\"",
            "server": "gws",
            "x-xss-protection": "0",
            "x-frame-options": "SAMEORIGIN",
            "set-cookie": [
                "1P_JAR=2020-02-01-14; expires=Mon, 02-Mar-2020 14:11:17 GMT; path=/; domain=.google.com; Secure",
                "NID=197=e7s_qamovdcDauagpT-WDjVC2Ykqy9QuNkZcifOg5YzcPEoQNvK3pJTnJDMQmHk8k2UQY9i26c06oiTP0uByD9tvJXZp6kXnLacgXoYt5e3on44ufveFTiCcTny1vsOSVuM1OL4YySGzIj40Shs-v0W4QAcftDk0a876u3uHDGA; expires=Sun, 02-Aug-2020 14:11:16 GMT; path=/; domain=.google.com; HttpOnly"
            ],
            "alt-svc": "quic=\":443\"; ma=2592000; v=\"46,43\",h3-Q050=\":443\"; ma=2592000,h3-Q049=\":443\"; ma=2592000,h3-Q048=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000",
            "accept-ranges": "none",
            "vary": "Accept-Encoding",
            "connection": "close"
        },
        "cookies": [
            "1P_JAR=2020-02-01-14; expires=Mon, 02-Mar-2020 14:11:17 GMT; path=/; domain=.google.com; Secure",
            "NID=197=e7s_qamovdcDauagpT-WDjVC2Ykqy9QuNkZcifOg5YzcPEoQNvK3pJTnJDMQmHk8k2UQY9i26c06oiTP0uByD9tvJXZp6kXnLacgXoYt5e3on44ufveFTiCcTny1vsOSVuM1OL4YySGzIj40Shs-v0W4QAcftDk0a876u3uHDGA; expires=Sun, 02-Aug-2020 14:11:16 GMT; path=/; domain=.google.com; HttpOnly"
        ],
        "buffer": {
            "type": "Buffer",
            "data": []
        },
        "text":"<!doctype html><html itemscope=\"\" itemtype=\"http://schema.org/WebPage\" lang=\"en\"><head><meta con . . .  }

### Environment Setup

- **Server**
  - parse-server version : **3.9.0**
  - Operating System:     [FILL THIS OUT]
  - Hardware:             [FILL THIS OUT]
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): **Back4App**

- **Database**
  - MongoDB version: [FILL THIS OUT]
  - Storage engine:  [FILL THIS OUT]
  - Hardware:        [FILL THIS OUT]
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): **Back4App**

**Comment by dplewis** [comment]
Why not redirect on the client side? If you want to redirect on the server side you could use a middleware. Call you cloud code function then send a response back to the client from the middleware response.
