### ISSUE TITLE
AuthenticationProviders should only create a single user with REST API

### ISSUE THREAD

**Issue by yomybaby** [parse-community/parse-server#6385]
### Issue Description
AuthenticationProviders should only create a single user with REST API.
[`AuthenticationAdapters.spec.js`](https://github.com/parse-community/parse-server/blob/master/spec/AuthenticationAdapters.spec.js#L222-L240
) has a test case for this.

```
  it('should only create a single user with REST API', done => {
    let objectId;
    createOAuthUser((error, response, body) => {
      expect(error).toBe(null);
      const b = body;
      expect(b.objectId).not.toBeNull();
      expect(b.objectId).not.toBeUndefined();
      objectId = b.objectId;

      createOAuthUser((error, response, body) => {
        expect(error).toBe(null);
        const b = body;
        expect(b.objectId).not.toBeNull();
        expect(b.objectId).not.toBeUndefined();
        expect(b.objectId).toBe(objectId);
        done();
      });
    });
  });
```

This test case try to make two `POST` request with the same `authData` in a serial way.
In a parallel way, it can make double users.

### Steps to reproduce
I wrote a test case for this. 
```
it('should only create a single user with REST API (simultaneous requests)', async () => {
    const results = await Promise.all([
      createOAuthUser(),
      createOAuthUser(),
      createOAuthUser(),
    ]);
    expect(results[0].body.objectId).toBe(results[1].body.objectId);
    expect(results[1].body.objectId).toBe(results[2].body.objectId);
  });
```

Please add this case to `AuthenticationAdapters.spec.js` and run test.

### Expected Results

Test pass.

### Actual Outcome

Test fail

example output
```
Failures:
1) AuthenticationProviders should only create a single user with REST API (simultaneous requests)
  Message:
    Expected 'qMqAZfxQsd' to be 'bl6vjyiUBG'.
  Stack:
    Error: Expected 'qMqAZfxQsd' to be 'bl6vjyiUBG'.
        at <Jasmine>
        at UserContext.it (/Users/codejong/Documents/_clone/parse-server/spec/AuthenticationAdapters.spec.js:248:38)
        at process._tickCallback (internal/process/next_tick.js:68:7)
  Message:
    Expected 'bl6vjyiUBG' to be 'vD9ZRiRmJp'.
  Stack:
    Error: Expected 'bl6vjyiUBG' to be 'vD9ZRiRmJp'.
        at <Jasmine>
        at UserContext.it (/Users/codejong/Documents/_clone/parse-server/spec/AuthenticationAdapters.spec.js:249:38)
        at process._tickCallback (internal/process/next_tick.js:68:7)
```

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 3.10.0
  - Operating System:     MacOS 10.15.2
  - Hardware: MacBook Pro (13-inch, 2016, Four Thunderbolt 3 Ports)
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): localhost

- **Database**
  - MongoDB version: 4.2.0

**Comment by dplewis** [comment]
This look like expected behavior to me. `Create0AuthUser` just creates a user.

Lets say I have to two users creating accounts at the same time. Are they two separate users or same user?

**Comment by yomybaby** [comment]
I think that this is a bug. 
With the same auth data, it have to create only one user.

> Lets say I have to two users creating accounts `using same SNS account` at the same time. Are they two separate users or same user?

This answer is "same user", right? Because they are using same SNS account.

`Create0AuthUser` use same auth data(id) every times. ([link](https://github.com/parse-community/parse-server/blob/master/spec/AuthenticationAdapters.spec.js#L106-L109))

For example,
If you try to signup/login with the same facebook account many times, 
- Only first request : creates user (sign up)
- Following request : login.
Because every call using same facebook account auth data(same facebook id).

Existing [test code](https://github.com/parse-community/parse-server/blob/master/spec/AuthenticationAdapters.spec.js#L222-L240) test it only  in a serial way not In a parallel way.

**Comment by JeffGuKang** [comment]
@dplewis I got a pain with same issue.

Sometimes multiple same accounts(having same authData) are made by multiple request from the one user when I use `linkWith()` for social login. And `username` of `_User` is randomly generated. So unique check is not work through `username`.

This situation happens by poor connection, slow DB, request by fast double click and so on. 

I suppose the options for auth options to choose `username` from authData. or integrate `username` generation to adapter.

For example, 

Apple authData's form is `apple: {id: 'xxxx', token: 'aaa'}`. 
And we want to generate unique `username` from `apple.id`

```js
new ParseServer({
...
auth: {
    kakao: kakaoAuthAdapter,
    apple: {
      client_id: process.env.APPLE_SIGNIN_CLIENT_ID,
      username: 'apple.id'
    },
  },
...
})
```
