### ISSUE TITLE
Use with fastify server instead of express

### ISSUE THREAD

**Issue by Dynan7** [parse-community/parse-server#6395]
### Issue Description

Can I use fastify backend server with ParseServer instead of express?
https://www.fastify.io/

**Comment by davimacedo** [comment]
Parse Server is essentially an Express.js middleware so I believe you will not be able to use it with Fastify (I don't know so much about Fastify though and I may be wrong).

**Comment by lamualfa** [comment]
@goshander Just use [fastify-express](https://github.com/fastify/fastify-express) to support Parse Server middleware which is essentially an Express.js middleware.
