### ISSUE TITLE
Does parse-server support protocol buffer?

### ISSUE THREAD

**Issue by itman85** [parse-community/parse-server#6407]
I see the protobufjs in nodejs, so does parse-server support protocol buffer? if yes how can i get started integrate parse-server with protocol buffer? Is there any way else to compress data transfer client&server using parse sdk android? cause i need to reduce the bandwidth.
 thanks for your help.

**Comment by MarcusAdriano** [comment]
No. The actual implementation uses HTTP 1.1 and JSON.

**Comment by dplewis** [comment]
Unfortunately we don't. Protobufs uses a static schema. Parse Server uses dynamic schema.

Feel free to open a PR to support both Protobuf and JSON.
