### ISSUE TITLE
The Community Forum is down

### ISSUE THREAD

**Issue by macarthuror** [parse-community/parse-server#6417]
Hello Guys 🖖,

I write to know if the forum will be reactivated.
If that is the case or need someone with time I would like to cooperate.

**Comment by TomWFox** [comment]
Hi,

We're very much hoping the forum will be reactivated but there has been some issues with the hosting which @acinader is trying to resolve.

I believe he has reached out for support from GCP but has not been successful thus far. It's super frustrating and we're sorry for the inconvenience to those who use the forum!

**Comment by Moumouls** [comment]
https://github.com/parse-community/parse-community.github.io/issues/35

**Comment by macarthuror** [comment]
@TomWFox 
@acinader 
any update?

**Comment by TomWFox** [comment]
Unfortunately, we’re not going to be able to recover the forum. There was a billing issue which resulted in the problem & GCP have been unwilling / unable to restore it.

As the forum had become a valuable asset to the community we are planning to put in place a replacement but unfortunately all of the existing content has been lost.

**Comment by acinader** [comment]
as an aside, my interaction with Google Cloud Platform support was just terrible.  The agent assigned to our issue was completely unwilling to help me figure out how to authenticate with them.  I tried several times in different ways but the agent seemed to take pleasure in my inability to answer his questions and he ignored my requests to escalate to a manager. 

Compared to my interactions with AWS support, this was just a frustrating, terrible experience.

And now we have lost a significant bit of institutional knowledge in our forum.  Shame on google :(.

**Comment by macarthuror** [comment]
It is a shame that the information has been lost, but I think the community is growing very fast and the data could be recovered quickly.

**Comment by L3K0V** [comment]
Is there any news or update about new community forum?

**Comment by TomWFox** [comment]
Sorry for the delay. This is something I'm actively working on now. I'll provide an update within a week.

**Comment by TomWFox** [comment]
Right... we're getting there! The basic setup is complete - feel free to pre-register now with email or GitHub 😊

**Comment by Moumouls** [comment]
Logged in !

**Comment by TomWFox** [comment]
Hi peeps, I’m almost ready to start letting people in. I just need to double check all the permissions and do some final setup.

You will see more detail about this once join the forum but I just want to reassure you that I am putting measures in place to ensure we don’t have a repeat of previous events.
1. Daily content backups on a separate s3 instance
2. Daily instance backups
3. Email and SMS notifications of downtime, billing etc
4. I will also keep recent daily backups in another location (to do)

**Comment by TomWFox** [comment]
Ok, final update and then I'll close this. Apologies it has taken so long, ironically the terrible events of COVID-19 have freed up a lot of time for me to get this sorted.

The forum is now open to new accounts without approval and anonymous browsing.

If you have any suggestions or questions about the forum I would strongly encourage you to use the [Site feedback category](https://community.parseplatform.org/c/site-feedback/2).
