### ISSUE TITLE
Parse equivalent of ObjectId.isValid 

### ISSUE THREAD

**Issue by srameshr** [parse-community/parse-server#6421]
**Is your feature request related to a problem? Please describe.**
Can we build an objectId validator for parse as mongoose does?
```
var mongoose = require('mongoose');
var isValid = mongoose.Types.ObjectId.isValid('5c0a7922c9d89830f4911426'); //true
```
**Describe the solution you'd like**
```Parse.Types.ObjectId.isValid('93kxll393'); // True```

**Describe alternatives you've considered**
N/A

**Additional context**
Are there any rules for the validating objectId in parse? Like a regex?

**Comment by davimacedo** [comment]
Can you describe your use-case? I mean, what do you need to achieve with that? You can also take a look [here](https://github.com/parse-community/parse-server/blob/master/src/cryptoUtils.js) to see how Parse generates the ids.
