### ISSUE TITLE
Delete all records on database query at once

### ISSUE THREAD

**Issue by fartem** [parse-community/parse-server#6424]
To remove objects, I need to get them at the query of the database and delete using Object.destroyAll. But this works with restrictions (by default 100 entities in 1 query result), and if the number of objects exceeds the set limit, I have to get entities and delete it in a loop. Is there a way to delete all objects at once using a query without limits?

**Comment by GoGross** [comment]
there are no limits, however its still best practice to delete in batches after .count. You can also flush the particular class via `Schema.purge();` which is more effiecient

**Comment by fartem** [comment]
I will describe the situation. I have a list of users, each of which has entries (no matter which). After deleting the user account, I also need to delete all his data. Right now, entries deleting so:

```javascript
let entries = []
do {
  entries = await entriesQuery().find()
  await Object.destroyAll(entries)
} while (entries.length >= 100)
```

Should a large amount of data be deleted this way?

**Comment by GoGross** [comment]
you can always revert to REST if the SDK isn't giving you the best options:

curl -X DELETE \
  -H "X-Parse-Application-Id: ${APPLICATION_ID}" \
  -H "X-Parse-REST-API-Key: ${REST_API_KEY}" \
--data-urlencode 'where={"userId":"object"}' \
  https://YOUR.PARSE-SERVER.HERE/parse/classes/entries

**Comment by fartem** [comment]
Hmm. This method is not entirely suitable, since I am deleting entries on server side. It’s a little strange that the server causes the removal of events on its side with REST, but not through with the JavaScript API.

**Comment by davimacedo** [comment]
Currently there is no way to delete all objects that matches a query using the JS SDK. You need either to query the objects (maybe you can use the `each` function to make sure you have all of them) or use the REST API as @GoGross suggested.

**Comment by fartem** [comment]
@GoGross, @davimacedo, thanks.
