### ISSUE TITLE
Parse Server and GraphQL Foundation

### ISSUE THREAD

**Issue by Moumouls** [parse-community/parse-server#6428]
With our last implementations on the GraphQL API, Parse Server become a true challenger, a reliable, optimized solution into GraphQL world.

I think it could be interesting to make Parse joining GraphQL foundation, like Hasura and Prisma.

I may be wrong but we could be the first fully open source project (not backed by a company) to be a member as a Baas !

What do you think about this  ?

https://foundation.graphql.org/join/

**Comment by davimacedo** [comment]
I think it is a good idea. We'd need to fill out [this](https://na3.docusign.net/Member/PowerFormSigning.aspx?PowerFormId=e27b3ed3-6854-434f-8d87-f776a3fc1aff&env=na3-eu1) form. I understand there is no fee since we are a non-profit organization. @acinader @dplewis @TomWFox , can I go for it? Or maybe it would be better one of you guys to fill out? I am afraid they can associate my name with the for profit organization that I also am part of.

**Comment by davimacedo** [comment]
@Moumouls in addition to this, I think we should add Parse in the community links both for GraphQL (https://graphql.org/code/ and https://graphql.org/community/) and Relay (https://relay.dev/docs/en/community-learning-resources) web-sites. What do you think? Could you help with this?

**Comment by Moumouls** [comment]
Yes it should be free !

 About links, it's a great idea, but i think we need to wait the https://github.com/parse-community/parse-server/pull/6379 .
From my point of view this PR is needed to provide a complete developer experience, and keep a reliable dev workflow.

**Comment by Moumouls** [comment]
Or may be we should wait a little bit here for GraphQL Foundation too for the same reasons !

**Comment by TomWFox** [comment]
Could you explain what is actually means to join the foundation? - that page doesn't seem to provide any explanation.

**Comment by mtrezza** [comment]
I'm closing this as it does not seem to be a Parse Server issue.

This seems to be a meta discussion which is better suited on our [community forum](https://community.parseplatform.org).

Feel free to comment if you have any questions and we can re-open this issue.
