### ISSUE TITLE
using allowCustomObjectId

### ISSUE THREAD

**Issue by byroncoetsee** [parse-community/parse-server#6429]
Hi everyone,

I've posted on SO and slack but no one can answer me. I've also tried to go over to `https://community.parseplatform.org` but I get an error 522. So, I'm asking here.

I'm trying to use `allowCustomObjectId`. The reason I need this is, the objects I'm trying to save are coming from an external API and therefor have IDs. I could just use my own IDs but other records from other tables, which already have proper IDs assigned for linking, would then need to be carefully handled. 

The problem I'm having is, when saving a new ParseObject, I get the error `Object not found`. This is because the save function checks to see if an `objectId` has been assigned and if so, it runs an `update` instead of `create`. Problem is, when using custom IDs, the object doesn't yet exist, despite having an ID already.

Is there any documentation on how to use this? Or a way to get around it? I can do exception handling but when saving child objects, I can't really use exception handling there and I end up at square 1 again.

Thank you

**Comment by davimacedo** [comment]
As I remember, It was only implemented in the server side and not implemented in the JS SDK yet. So you will have to call the REST API directly in order to set a custom object id.
