### ISSUE TITLE
handle http GET request from other site.

### ISSUE THREAD

**Issue by hoffergg** [parse-community/parse-server#6430]
I am integrating  parse server with instgram API, instagram console needs a callback URL to handle the Auth. 
The http request is like this:
```https://www.mysite.com/?code=AQDp3TtBQQ```
And I need the 'code' parameter to do with my ParseUser.
So what can I do? The cloud function is not working which needs auth in the Http request header.

**Comment by davimacedo** [comment]
Are you trying to authenticate via Instagram? Have you tried the [Instagram Auth Adapter](https://docs.parseplatform.org/parse-server/guide/#configuring-parse-server-for-ldap)? Otherwise I think you will have to create your own custom route in your Express.js app to handle this callback.
