### ISSUE TITLE
Add SonarQube Bagdes and PR

### ISSUE THREAD

**Issue by Moumouls** [parse-community/parse-server#6432]
Recently, I tested SonarQube, it seems that the analysis was interesting.
I think we can add bagdes from SonarQube to this repo metrics for code quality/security and many other.

With sonarcloud.io we can link Travis with SonarQube to get an additional help on PRs.

Does a PMC can set up the thing/approve integration ?

**Comment by davimacedo** [comment]
I think we can integrate and test it. It looks interesting. I've received an e-mail from them in order to approve the integration. @acinader @dplewis @TomWFox can I go for it?

**Comment by TomWFox** [comment]
I’m happy to give it a go. It does seem to overlap a bit with codecov but I’m guessing you can pick and choose which features you use?

**Comment by davimacedo** [comment]
We can also run both for a while and then decide which one best fits.

**Comment by dplewis** [comment]
I just started using SonarQube for my project. I’m all for it

**Comment by davimacedo** [comment]
Nice. So I've just approved the request. @Moumouls do you continue from here?

**Comment by Moumouls** [comment]
It seems that i have an error: "This action must be performed by an organization owner" to sync the repo...

I know it need a Governance vote, but is it possible to upgrade me as an organization owner/PMC ?

**Comment by davimacedo** [comment]
@TomWFox can you please explain the process?

@Moumouls in the meantime I can setup it for you. Just let me know what I need to do. Or maybe we could arranje a time to do it together.

**Comment by TomWFox** [comment]
A new PMC member can be added by consensus approval by the community. We haven’t defined a process for new org owners - I would say unanimous consensus of the PMC would be most appropriate.

Generally speaking I suggest we be careful about having too many org owners. Almost all normal actions can be performed within other perm levels - and we can adjust some of these where necessary/appropriate.

**Comment by mtrezza** [comment]
What is the current state of SonarCube? From the thread it seems that there was intention to add it to the repository.

**Comment by mtrezza** [comment]
I'm closing this due to prolonged inactivity. If the topic becomes relevant again we can re-open this issue.
