### ISSUE TITLE
Is there any documentation on protectedFields in the CLP?

### ISSUE THREAD

**Issue by sunshineo** [parse-community/parse-server#6435]
Tried https://docs.parseplatform.org/ and found nothing. Even tried use [google](https://www.google.com/search?source=hp&ei=JWVQXpujKMOd-gSi76yIBg&q=protectedfields+site%3Ahttps%3A%2F%2Fdocs.parseplatform.org%2F&oq=protectedfields+site%3Ahttps%3A%2F%2Fdocs.parseplatform.org%2F&gs_l=psy-ab.3...844.9167..9938...1.0..0.268.1153.5j1j3......0....1j2..gws-wiz.......0j0i131j0i10.Tv-jtE8M7rM&ved=0ahUKEwjbyYfb4-PnAhXDjp4KHaI3C2EQ4dUDCAg&uact=5)

https://community.parseplatform.org seems to be down

And I found nothing on the wiki here
Thanks

**Comment by davimacedo** [comment]
We are missing these docs and we should work on this. In the meantime, you can take a look and learn from the tests cases [here](https://github.com/parse-community/parse-server/blob/master/spec/ProtectedFields.spec.js)

**Comment by TomWFox** [comment]
I'll close this now as there is an existing issue - parse-community/docs#614. That is where we prefer to track issue relating to content missing from the docs, improvements etc.

If you manage to get a good grasp of protectedFields we are always open to contributions to the docs 😉

**Comment by sunshineo** [comment]
Thank you @TomWFox
