### ISSUE TITLE
matchesQuery and beforeFind do not work in combination

### ISSUE THREAD

**Issue by mullwaden** [parse-community/parse-server#6442]
### Issue Description
I two tables (ExpertProfile and Booking) that have a beforeFind on them that limits the number of results. When matchesQuery is a part of a query the before find is ignored.

### Steps to reproduce
First query, without a matches query:
```
 const query = ExpertProfile.query()
    .equalTo("request", request);

Results in postgres:

SELECT * FROM "ExpertProfile" WHERE "request" = 'T6HmUe7lIG' AND "enFirmOrg" = 'LINpBurUH1' AND ("_rperm" IS NULL OR "_rperm" && ARRAY['*','*',...])

```

Notice the ``"enFirmOrg" = 'LINpBurUH1'`` part has been added due to the before find on the ExpertProfile table.

Now when using matchesQuery:

```
 const query = Booking.query()
   .matchesQuery(
     "expertProfile",
      ExpertProfile.query().equalTo("request", request)
   );

Results in postgres:

SELECT * FROM "ExpertProfile" WHERE "request" = 'T6HmUe7lIG' AND ("_rperm" IS NULL OR "_rperm" && ARRAY['*','*',...])

SELECT * FROM "Booking" WHERE "expertProfile"  IN ('mIoUYOjc1b','ESNxjOqhx5','bOvIWMQLfH','0y6Yy9lRcS','kvkSFQubHB') AND ("_rperm" IS NULL OR "_rperm" && ARRAY['*','*',...])
```

Neither of the queries include the magic ``"enFirmOrg" = 'LINpBurUH1'`` from the beforeFind on either Booking or ExpertProfile.
 
### Expected Results
I would expect at least one of the queries to incorporate beforeFind.

### Actual Outcome
BeforeFind is ignored. As far as i can tell this is undocumented and might be quite an issue if you are relying on beforeFind to limit the amount of data a user has access to. 

### Environment Setup

- **Server**
  - parse-server version: 3.10.0
  - Operating System:  Windows 10 and OSX
  - Hardware:  rusty old laptop
  - Localhost

- **Database**
  - Postgres version: Tested with 10 and 12
  - Storage engine:  postgres?
  - Hardware:  rusty old laptop
  - Localhost

### Logs/Trace
See above

**Comment by davimacedo** [comment]
Can you share the code you are using in your beforeFind trigger?

**Comment by mullwaden** [comment]
Sure, it looks like this for both the ExpertProfile and Booking classes

```
beforeFind({ query, user, master }) {
    if (!master && user.isContractor()) {
      query.equalTo("enFirmOrg", user.getOrganization());
    }
  }
```

**Comment by davimacedo** [comment]
I'm not sure about using `user.isContractor()` and `user.getOrganization()` in the trigger. It may be the problem. Could you please try to use the `user.get('fieldName')` instead?

**Comment by mullwaden** [comment]
Sorry for the late reply, strange times these ...

Did some additional testing, as far as i can tell the beforeFind is never triggered. No changes to the content of the code inside beforeFind make any difference (i tried emptying it out entirely and also using .get("fieldName") instead
