### ISSUE TITLE
Release notes should contain index changes

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-server#6464]
**Is your feature request related to a problem? Please describe.**
Parse Server 4.0.0 mentions this breaking change:

> FIX: BREAKING CHANGE Prevent new usernames or emails that clash with existing users' email or username if it only differs by case. For example, don't allow a new user with the name 'Jane' if we already have a user 'jane'.

However, it is not clear that the fix creates a new index in the DB.

Creating indices in a mongoDB replica set is a delicate action, because:
- Other DB queries can depend on existing indices
- Index creation causes additional DB load (affects resources and oplog)
- For large collections it can make sense to create an index in a rolling node fashion

**Describe the solution you'd like**
Any (future) DB index modifications should be clearly mentioned in Parse Server release notes, with the same importance as a breaking change.

**Additional context**
- https://docs.mongodb.com/manual/tutorial/build-indexes-on-replica-sets/

**Comment by TomWFox** [comment]
@mtrezza we've updated the changelog and release notes accordingly, hopefully its satisfactory.

It could be a good idea to have a clear release doc with all the steps, chagelog and release notes formatting and notes like this.

**Comment by mtrezza** [comment]
Great! I agree, a release template would make sure that for example index changes are mentioned.
