### ISSUE TITLE
New Parse-Server Project: MongoDB WiredTiger, MongoRocks or Postgres?

### ISSUE THREAD

**Issue by fastrde** [parse-community/parse-server#6468]
In 2016 MongoDB with Rocks Storage Engine was the choice. Four years later the docs still recommend rocksDB. The git repository of rocksDB has not seen an update for 2 years. 
Is Postgres now also recommended for production enviroments?
Are there any reasons why not to use MongoDB out of the box nowadays (for a new Project)?

**Comment by mtrezza** [comment]
If I understand you correctly, your question comes down to "What is the difference between mongoDB and Postgres?".

Both DBMS are based on fundamentally different paradigms. While Postgres is relational, object oriented, mongoDB is non-relational, document oriented, to name just one difference.

Which one you choose depends on your use case. As an example, if you focus on geo queries, there are [performance differences](https://scholarworks.umass.edu/cgi/viewcontent.cgi?article=1088&context=foss4g) between the two DBMS.

**Comment by acinader** [comment]
@fastrde the doc should be updated (cc: @TomWFox).  Ideally, both are well supported, but I *think* that there are a lot more mongo installations, and certainly the core contributors run mongo.

If you're starting a new project, I would recommend using Mongo DB  4.2.  I currently use Mongo 3.6 but hope to upgrade in the near future.

**Comment by VladimirTambovtsev** [comment]
Which performance is better today? MongoDB or RocksDB (with latest versions)?

**Comment by TomWFox** [comment]
@fastrde could you provide a link to the section of the docs in question?

**Comment by acinader** [comment]
https://github.com/parse-community/docs/search?q=rocksdb&unscoped_q=rocksdb

**Comment by TomWFox** [comment]
That work 😅, looks like a significant update would be needed.

**Comment by acinader** [comment]
I would simplify.  I don't think that any mention of WiredTiger or RocksDB is necessary at this point and is just confusing.

If issues arise we could add more docs to address them, but at this point, I think any discussion of the MongoDB storage engine is unnecessary and potentially confusing details.  When these docs were written both storage engines were in wide use and the transition from RocksDB and WiredTiger was in progress.  

It would be like adding information about how to run parse-server on Windows 95 ;).
![image](https://user-images.githubusercontent.com/700572/76025734-65195400-5ee2-11ea-8080-25a14d074848.png)

**Comment by davimacedo** [comment]
I agree with @acinader . I believe we could just remove all the section talking about RocksDB. It has been inactive for a while now.

**Comment by fastrde** [comment]
Ok. Thank you for clarification.
Conclusion: 
- Use MongoDB as is.
- Postgres is also ok, but not so widely in use. When you need support there are more people out there using MongoDB.
- remove mentioned parts from documentation.
