### ISSUE TITLE
LiveQuery extend feature

### ISSUE THREAD

**Issue by francojohnc** [parse-community/parse-server#6480]
**Is your feature request related to a problem? Please describe.**

I have an app use live query for chat and tracking for gps. on gps function i save parse object called Location and it have geolocation, and every 5 seconds i update the Object to save the current location of the driver.

**Describe the solution you'd like**

I want to extend the feature of live query. for now when we save the object it use http protocol even were already connected to live query server and subscribe to deferent subscription event. 
Live query is use websocket protocol. I want to save or update the parse object using live query. for realtime data connection.

**Describe alternatives you've considered**

**Additional context**
If possible to remove the declaration of live query classes to parse sever. so all my class if server detect that have subscribed for that class it notify.

**Comment by dplewis** [comment]
@francojohnc 

> Is your feature request related to a problem? Please describe.

What is the issue you are trying to address? Perhaps some sample / sudo code will help.
