### ISSUE TITLE
parse server starts after NestJS (express) app has been started

### ISSUE THREAD

**Issue by AienTech** [parse-community/parse-server#6484]
### Issue Description

I've setup a NestJS app (basically expressjs) and added parse server to it's configurations. I wanted to have parse server's express middleware to be used inside of my app. But after running the app (bootstraping in terms of nestjs) the application starts, tries to connect to parse server (which shows a warning that it cannot connect to parse) and then the parse server starts up.

### Steps to reproduce

1. created a nestjs app (or a simple expressjs with `express` cli command)
2. create a new ParseServer instance and configure it
```
...
import { default as ParseServer, ParseGraphQLServer } from 'parse-server';
...

const { env, host, port, database, parse, paths, systemContextName } = global.Houston;

const parseServer = new ParseServer({
	databaseURI: database.url, // Connection string for your MongoDB database
	//cloud: null,
	appId: parse.appId,
	enableExpressErrorHandler: true,
	appName: parse.appName,
	logsFolder: paths.log,
	masterKey: parse.masterKey, // Keep this key secret!
	//fileKey: 'optionalFileKey',
	serverURL: parse.serverUrl, // Don't forget to change to https if needed
	publicServerURL: parse.publicServerUrl,
	serverStartComplete: () => {
		logger.log('parse server started', systemContextName);
	},
	emailAdapter: {
		module: 'parse-smtp-template',
		options: {
			port: parse.emailAdapter.port,
			host: parse.emailAdapter.host,
			user: parse.emailAdapter.user,
			password: parse.emailAdapter.password,
			fromAddress: parse.emailAdapter.from,
			template: false,
			templatePath: '',
			passwordOptions: {
				subject: 'Password recovery',
				body: 'Please follow this link to recover your password',
				btn: 'Recover your password',
			},
			confirmOptions: {
				subject: 'E-mail confirmation',
				body: 'Please confirm your email by clicking on the following link',
				btn: 'Confirm your email',
			},
		},
	},
});

app.use('/api', parseServer.app);

```
3. add parse server middleware to app using `app.use("/api", parseServer.app)`
4. get th following error:
```
INFO    [NestFactory]           Starting Nest application...
INFO    [InstanceLoader]        AppModule dependencies initialized
INFO    [RoutesResolver]        [/]              DefaultController
INFO    [RouterExplorer]        [/, GET]         Mapped
INFO    [NestApplication]       Nest application successfully started
INFO    [System]                application started on http://0.0.0.0:3000

WARNING, Unable to connect to 'http://0.0.0.0:3000/api'. Cloud code and push notifications may be unavailable!

INFO    [System]                parse server started
```
 
### Expected Results

Parse server should be started and after that, the app should boot up.

### Actual Outcome

following warning:
```
INFO    [NestFactory]           Starting Nest application...
INFO    [InstanceLoader]        AppModule dependencies initialized
INFO    [RoutesResolver]        [/]              DefaultController
INFO    [RouterExplorer]        [/, GET]         Mapped
INFO    [NestApplication]       Nest application successfully started
INFO    [System]                application started on http://0.0.0.0:3000

WARNING, Unable to connect to 'http://0.0.0.0:3000/api'. Cloud code and push notifications may be unavailable!

INFO    [System]                parse server started

```

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : ^4.1.0
  - Operating System:     MacOS
  - Hardware:             Intel Core i7
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): localhost

- **Database**
  - MongoDB version: latest
  - Storage engine:  MongoDB
  - Hardware:        On Mongo Atlas (shared 512)
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): Mongo Atlas

### Logs/Trace

Nothing actually

**Comment by davimacedo** [comment]
`serverStartComplete` is the callback that is called after Parse Server has initialized. Calling `app.listen(3000);` inside this callback should fix your problem.

**Comment by AienTech** [comment]
@davimacedo thanks for mentioning that. Although in my last projects I didn't need this function to set up when parse should start, but right now, the logs are changed to this:

```
INFO    [NestFactory]           Starting Nest application...
INFO    [InstanceLoader]        AppModule dependencies initialized

WARNING, Unable to connect to 'http://0.0.0.0:3000/api'. Cloud code and push notifications may be unavailable!

INFO    [System]                parse server started
INFO    [RoutesResolver]        [/]              DefaultController
INFO    [RouterExplorer]        [/, GET]         Mapped
INFO    [NestApplication]       Nest application successfully started
INFO    [System]                application started on http://0.0.0.0:3000
```

I also have `parse/node` as a dependency of this project, but it's not configured or even imported yet. What I learned so far was that this warning comes directly from the `parse-server` library. there's also only one place where this error is shown, and it's when the parse-server tries to send a request to it's `/health` endpoint.

from my point of view, this shouldn't even be possible, since, at that point, the parse is not even up!

one other thing (odd thing!) is that even though I told parse-server where to put the log files, it still uses its default path.

this means that the parse-server does not get the configurations as expected. I also checked my configurations (I use `config` package). they are also fine as far as I can tell.

can it be something else?

**Comment by mman** [comment]
Please check your ``serverURL`` and or ``publicServerURL`` properties in config. The above message indicates that the parse server will try to contact itself via 0.0.0.0 which is obviously wrong. Depending on how many instances of parse server you have running the ``serverURL`` typically can be localhost and ``publicServerURL`` your publicly reachable endpoint.

**Comment by AienTech** [comment]
@mman thanks for the response. My first tries were all with the `localhost`, here are the logs when I use `localhost` instead of `0.0.0.0`.

```
INFO    [NestFactory]           Starting Nest application...
INFO    [InstanceLoader]        AppModule dependencies initialized

WARNING, Unable to connect to 'http://localhost:3000/api'. Cloud code and push notifications may be unavailable!

INFO    [System]                parse server started
INFO    [System]                parse configuration: serverURL: http://localhost:3000/api, publicServerURL: http://localhost:3000/api
INFO    [RoutesResolver]        [/]              DefaultController
INFO    [RouterExplorer]        [/, GET]         Mapped
INFO    [NestApplication]       Nest application successfully started
INFO    [System]                application started on http://localhost:3000
```

the same happens if I use `null` for `publicServerURL`

also, there's only one instance of parse-server running on the current machine.

**Comment by AienTech** [comment]
One thing that I quietly don't understand is that why parse-server tries to connect itself before it's even started! as you can see in the logs, first
```
WARNING, Unable to connect to 'http://localhost:3000/api'. Cloud code and push notifications may be unavailable!
```
happens and then
```
INFO    [System]                parse server started
```

**Comment by dplewis** [comment]
@AienTech That is a health check. Can you try running them both on different ports?

**Comment by AienTech** [comment]
@dplewis thanks for the suggestion, it also happens when I use a different port for parse. The soul Idea is actually to use parse as a middleware inside my app. Can it have anything to do with the fact that I'm using Mongo atlas to host my database? anything like a roundtrip time delay or something?
