### ISSUE TITLE
Parse-Dashboard not updating 

### ISSUE THREAD

**Issue by pastordee** [parse-community/parse-server#6493]
### Issue Description
I use a bitnami stack, parse server 4.1.0 just updated but every time i try to update parse-dashboard i an error about enoent undefined ls-remote -h -t ssh://git@github.com/timsuchanek/codemirror-graphql.git, i belive because of this my GraphQL API Console is not working, i get this error from that one 

Server cannot be reached
{
  "error": "Response not successful: Received status code 500"
}

can any one please help Thanks.

### Expected Results

to update Parse-Dashboard

### Actual Outcome

[root@localhost htdocs]# npm install parse-server parse-dashboard
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/timsuchanek/codemirror-graphql.git
npm ERR! enoent 
npm ERR! enoent 
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) :4.1.0
  - Operating System:    CentOS 8
  - Hardware:             [FILL THIS OUT]
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Bitnami on ionos

- **Database**
  - MongoDB version: v4.2.4-rc0-5-g24b6ee2
  - Storage engine:  aws S3
  - Hardware:        [FILL THIS OUT]
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): Bitnami on ionos

**Comment by davimacedo** [comment]
Can you please share your `package.json`?

**Comment by pastordee** [comment]
> Can you please share your `package.json`?

package.json
{
  "dependencies": {
    "@parse/s3-files-adapter": "^1.4.0",
    "aws-sdk": "^2.637.0",
    "dotenv-safe": "^8.2.0",
    "firebase-admin": "^8.9.2",
    "node-schedule": "^1.3.2",
    "parse-dashboard": "^2.0.5",
    "parse-server": "^4.1.0",
    "parse-server-generic-email-adapter": "0.0.4",
    "postinstall-js": "^0.6.0"
  }
}

**Comment by Moumouls** [comment]
May be you forgot, `grapghQLServerURL`
Here a simple configuration of the Dashboard:

```js
const dashboard = new ParseDashboard(
{
    apps: [
        {
            serverURL: process.env.PUBLIC_PARSE_URL,
            appId: process.env.APP_ID,
            masterKey: process.env.MASTER_KEY,
            appName: 'PeopleVox',
            graphQLServerURL: process.env.PUBLIC_GRAPHQL_URL,
        },
    ],
    trustProxy: true,
    users:
        process.env.NODE_ENV !== 'production'
            ? undefined
            : [
                    {
                        user: process.env.DASHBOARD_ADMIN,
                        pass: process.env.DASHBOARD_PASSWORD,
                    },
                ],
},
{ dev: true, cookieSessionSecret: process.env.DASHBOARD_SESSION_SECRET || 'test' },
)
```
