### ISSUE TITLE
Apple Sign-In: Invalid Signature

### ISSUE THREAD

**Issue by doender** [parse-community/parse-server#6496]
When calling `linkWith` with the apple auth adapter as follows:

```
user.linkWith('apple', { id: 'user-id', token: 'id-token' }, { useMasterKey: true });
```
with a real user id and id token I get the following error:

```
JsonWebTokenError: invalid signature
at /node_modules/jsonwebtoken/verify.js:133:19
at getSecret (/node_modules/jsonwebtoken/verify.js:90:14)
```

Actually when I parse the token here, I also get an 'invalid signature error', although the claims in the JWT are correct. I get that this might not be a parse-server issue, but as I couldn't access https://community.parseplatform.org, I kindly ask for your help.

**Comment by doender** [comment]
I found the issue, apple is now hosting multiple public keys: https://appleid.apple.com/auth/keys.
By default the first key is used (https://github.com/parse-community/parse-server/blob/master/src/Adapters/Auth/apple.js#L24), but this should be the one matching the `kid` in the JWT.

So, the logic should something like:
```
const unverifiedPayload = jwt.decode(jwtString, { complete: true });
const kid = unverifiedPayload.header.kid;
const keysJson = await request.get(keysUrl, { json: true });
const keys = keysJson ? keysJson['keys'] : [];
const key = keys.find((k: any) => k.kid === kid);
const jwtClaims = jwt.verify(jwtString, jwkToPem(key), { algorithms: ['RS256'] });
```

I can make a PR if you want

**Comment by dplewis** [comment]
@doender Thank you for looking into it. Someone already opened a PR. https://github.com/parse-community/parse-server/pull/6416 it will be merged shortly. Can you see if that PR fixes your issue.

**Comment by doender** [comment]
Ah, I missed that :) Yeah, the PR fixed it, thanks. Hopefully this can be merged soon

**Comment by dplewis** [comment]
Closing via https://github.com/parse-community/parse-server/pull/6416

**Comment by RodrigoSMarques** [comment]
@doender 
Would you help me set up the Apple Sign in Parse Server?

I didn't find enough information on how to set up Apple Sign in on Parse Server.

I found some information in the Back4app documentation, but the screens are different and I did not find an option to download the file.

What did I do:
1) I followed the guidelines on the page https://help.apple.com/developer-account/#/devde676e696. I configured the domain and the callback address and downloaded the file with extension p8.

2) I configured Apple authentication at the start of my server according to the page https://docs.parseplatform.org/parse-server/guide/#apple-authdata

When I'm trying to create the user on Parse Server, the log displays the following error message:
``` javascript
JsonWebTokenError: jwt malformed
   at Object.module.exports [as verify] (/usr/lib/node_modules/parse-server/node_modules/jsonwebtoken/verify.js:63:17)
   at verifyIdToken (/usr/lib/node_modules/parse-server/lib/Adapters/Auth/apple.js:48:25)
   at processTicksAndRejections (internal/process/task_queues.js:97:5)
   at async Promise.all (index 0)
```

I don't know what I may have done wrong, what configuration is missing
