### ISSUE TITLE
The minimum required configuration of parse server

### ISSUE THREAD

**Issue by CollinsWalker** [parse-community/parse-server#6526]
The minimum required configuration of parse server

**Comment by dplewis** [comment]
@CollinsWalker Thanks for opening the issue. For a minimum configuration you need a Database, Node 8+, an application id and master key, optionally a `/cloud` folder.

`
parse-server --appId APPLICATION_ID --masterKey MASTER_KEY --databaseURI mongodb://localhost/test
`

We should write up a recommended setup at some point. 

Please refer to the [guide](https://docs.parseplatform.org/parse-server/guide/#getting-started) to get started. Please let us know if anything is unclear.

@acinader @davimacedo Anything I missed?

**Comment by davimacedo** [comment]
I think that's all you need for a minimum setup.

**Comment by CollinsWalker** [comment]
> @CollinsWalker Thanks for opening the issue. For a minimum configuration you need a Database, Node 8+, an application id and master key, optionally a `/cloud` folder.
> 
> `parse-server --appId APPLICATION_ID --masterKey MASTER_KEY --databaseURI mongodb://localhost/test`
> 
> We should write up a recommended setup at some point.
> 
> Please refer to the [guide](https://docs.parseplatform.org/parse-server/guide/#getting-started) to get started. Please let us know if anything is unclear.
> 
> @acinader @davimacedo Anything I missed?

Thanks for the answer.

**Comment by CollinsWalker** [comment]
> I think that's all you need for a minimum setup.

Thanks for the answer.

**Comment by CollinsWalker** [comment]
> I think that's all you need for a minimum setup.

Is 1 core 512 enough running memory?

**Comment by davimacedo** [comment]
Depending on how many requests you want to handle and what kind of requests, it should be enough for starting a new app.

**Comment by CollinsWalker** [comment]
> Depending on how many requests you want to handle and what kind of requests, it should be enough for starting a new app.

Thank you for your reply, I have understood

**Comment by dplewis** [comment]
@CollinsWalker It was recommended for example AWS T2.micro instances as a minimum to run Parse Server (1 GB ram). I have heard reports of users using T2.nano (0.5 GB) to run it as well.
