### ISSUE TITLE
Cloud Code Sign up Doesn't Convert Anonymous User to Real User

### ISSUE THREAD

**Issue by sambing** [parse-community/parse-server#6529]
### Issue Description

When trying to sign up an anonymous user via cloud code, authData does not get unset, thus client side will still report the user as anonymous.

### Steps to reproduce

1.  Enable automatic anonymous user creation client side.
2.  Set ACL and some initial setup data to that user via a cloud function.
3.  When user wants to sign up later, call a cloud function to sign up user. 

```
Parse.Cloud.define("signUp", async (request) => {
         var user = request.user;
         const password = request.params.password;
         const username = request.params.username;

        user.set("password",password);
        user.set("username",username);

        user.signUp(null, {useMasterKey: true})
        .then(function(registeredUser) {
         console.log("signed up");
        })
        .catch(function(error) {
         console.error("Error " + error.code + ":" + error.message);
        });
});
```

 
### Expected Results

User gets converted to a permanent/regular user when signUp is called via the cloud code. Just as if signUp was called from iOS or Android. 

Expect this to happen : https://github.com/parse-community/Parse-SDK-JS/pull/47

### Actual Outcome

Username and password is set, authData still remains filled out, and user reports as anonymous on the client side.

### Environment Setup

- **Server**
  - parse-server version 3.9.0
  -  AWS

Not sure if it's a bug or i missed something. Tried also updating the user and signing up, both produce the same outcome. Any help is appreciated.

**Comment by davimacedo** [comment]
Please try with `setUsername` and `setPassword` instead of `set('username')` and `set('password')` and let me know.

**Comment by sambing** [comment]
@davimacedo That was it! I apologize i missed that, thought it was an issue. Thank you and stay safe.
