### ISSUE TITLE
Resize the video before upload to parse

### ISSUE THREAD

**Issue by Eolykab** [parse-community/parse-server#6538]
Hi All, 

I am using the JS SDK. I will look to resize the video and audio before uploading it to the server.

Any suggestions?

**Comment by omairvaiyani** [comment]
Hi

This falls outside of the remit of parse-server, or even the JS SDK. You'll have to implement your own logic here for video/audio, parse only facilitates upload files to your storage system, like S3, but does not manipulate the data. Checkout https://www.filestack.com/ if you're interested.
