### ISSUE TITLE
in the beforeSave,How to know the original value of key

### ISSUE THREAD

**Issue by lybaiyy123** [parse-community/parse-server#6541]
On the client side, a user modifies/unset/set/ the key value

On the server side, how to know the original value of key?

**for example:**
**Raw data:**
className:todo;
id:'xxxxx',
name:'tom',
age:18

**Clinet:**
var todo=new Parse.Object('todo')
todo.id='xxxxx'
todo.unset('name')
todo.save()

**Server:**
Parse.Cloud.beforSave('todo',req=>{
// i want know original value of name
})

Is there a way to know this?  thanks.

**Comment by lybaiyy123** [comment]
i have a idea,but But is there a simpler way?

Parse.Cloud.beforSave('todo',req=>{
// i want know original value of name
if (req.object.dirty('name')){
   if (!req.object.get('name')){
      //get the Value before modification
      req.object.revert('name')
      let  last_name=req.object.get('name')
      //rollback the key
      req.object.unset('name')
  }
}
})

**Comment by omkar-tenkale** [comment]
You have the objectid just query the db and get the original row

**Comment by lybaiyy123** [comment]
> You have the objectid just query the db and get the original row

in the Parse.Cloud.beforSave to get db?

**Comment by omkar-tenkale** [comment]
yes

**Comment by omkar-tenkale** [comment]
Code not tested but this or something similar will work

Parse.Cloud.beforeSave("todo", (request) => {
  const id= request.object.id);
  const query = new Parse.Query("todo");
query.equalTo("objectId",id)
var originalobject  = await query.first();
var originalname = originalobject.get("name")
//rest of your code
});

**Comment by dplewis** [comment]
You should be able to get the original via `req.original` instead of `req.object`.

https://github.com/parse-community/parse-server/blob/master/src/cloud-code/Parse.Cloud.js#L393
