### ISSUE TITLE
Querying a single user in the Rest API with XMLHttpRequest

### ISSUE THREAD

**Issue by tyreepace** [parse-community/parse-server#6544]
Hi, I am trying to query the Parse Server for a user based on the username.  The docs indicate that I can pass `'where={"username":"buckybarnes@codespark.com"}'` but I'm not sure how to properly encode this and pass it in with an xhr request. I know how to fetch the user if I have the object id, but not sure how to query using a different parameter. Any help would be appreciated. Thanks!

**Comment by davimacedo** [comment]
Can you please send this question over https://stackoverflow.com/questions/tagged/parse-platform ?

Please make sure to share the code that you have tried so far.
