### ISSUE TITLE
Is there a way to save ParseObject without make a HTTP request to the REST API?

### ISSUE THREAD

**Issue by Simone-cogno** [parse-community/parse-server#6549]
Hi, I didn't find very much about this topic, so I wonder if it is an easy task to achieve or if it's actually not possible. My problem is that I have a lot of HTTP requests on my server even if a Cloud function is called only once. So I suppose that all the object updating / savings / queries are made by using the REST API. I have so many HTTP requests that several hundred are going timeout, I suppose for the huge traffic that it's generated.

Is there a way to save a ParseObject by executing the query directly to MongoDB? If it's not possible at the moment can you give me some hints if there are already some helper functions to convert a ParseQuery and a ParseObject to the relative in MongoDB so that I can use the MongoDB driver directly?

It's really important for my application to reduce HTTP requests traffic at the moment.

Any idea? Thanks!

Here an example to reproduce the concept:

Make a cloud function:
```
Parse.Cloud.define('hello', async (req, res) => {
  let testClassObject = new Parse.Object('TestClass');

  await testClassObject.save(null, {useMasterKey: true});

  let query = new Parse.Query('TestClass');

  let testClassRecords = await query.find({useMasterKey: true});

  return testClassRecords;
});

```

Make a POST request:
POST http://localhost:1337/parse/functions/hello

Capture HTTP traffic on port 1337 using Wireshark:
```
409	14.119545	     ::1	1337	HTTP	404	POST /parse/functions/hello HTTP/1.1 
418	14.122375	127.0.0.1	1337	HTTP	426	POST /parse/classes/TestClass HTTP/1.1  (text/plain)
423	14.122814	127.0.0.1	1337	HTTP	399	POST /parse/classes/TestClass HTTP/1.1  (text/plain)
```
You can see that for 1 POST request other 2 are made because of the saving / query code. What I'm trying to do is to optimize this and make the request directly on MongoDB.

Link of the Stackoverflow question: https://stackoverflow.com/questions/60951275/is-there-a-way-to-save-parseobject-without-make-a-http-request-to-the-rest-api

**Comment by davimacedo** [comment]
Can you please share your parse server configuration? Have you tried with `directAccess` option set to true?

**Comment by Simone-cogno** [comment]
Yes, it works...all my unit test passes without any change in the code and I was able to reduce by 69% the load on the server. I didn't know about this option before. Will this feature be maintained and included in the unit tests?

Thanks for the help!

**Comment by acinader** [comment]
Hi Simone,

Yes,  the goal is to support this feature and your using it in production is an important help!  Can we close this issue for now?
