### ISSUE TITLE
Accessing database from client side a good programming style?

### ISSUE THREAD

**Issue by omkar-tenkale** [parse-community/parse-server#6554]
As we all know,parse provides direct access to db with its sdks.
But many people doubt (fear) accessing db from client side.

Even if we try to obfuscate code from client side,an attacker can still debug the http requests and see the queries,or other logic in them.

Now comes ACL,CLP etc to protect the data but still from http requests attacker can see all the query logic,table info,data storage techniques etc and a competitor could replicate the same structure.
SSLs can prevent http snooping but it can also be bypassed when attacker acts as client.
One can also perform very heavy queries to slow down or crash the server.
We can restrict to only perform specific queries with cloud code but that also becomes part of writing backend logic defeating the backendless feature of parse.

We can use cloud code to avoid that and that seems the only option but then it makes all the js,android,ios sdk useless.

I personally love parse but i have no answers when someone says accessing db from client side is bad programming practice.

So does Parse recommend/discourage using cloud code only for all operations?
Is this really a bad practice accessing db from client side?

**Comment by acinader** [comment]
Hii @omkar-tenkale 

IMHO, accessing the DB from the client is an absolutely terrible idea!

You are opening your database up to untrusted clients - best practice is to prevent any network access to your database except trusted clients (like a parse-server) that can protect credentials -- this is usually down with a firewall of some sort at the network level.

I also don't understand this statement:

> We can restrict to only perform specific queries with cloud code but that also becomes part of writing backend logic defeating the backendless feature of parse.

> We can use cloud code to avoid that and that seems the only option but then it makes all the js,android,ios sdk useless.

If you put your query logic into a cloud code than you can access your data in the same way from each of the SDK's without replicating the logic in each language/platforms -- while taking advantage of parse's security features.  

> backend logic defeat[s] the backendless feature of parse

Parse is certainly not backendless, there is cloud code, triggers and cloud security is an important an id integral feature of parse.

Hope this helps!

**Comment by omkar-tenkale** [comment]
> from http requests attacker can see all the query logic,table info,data storage techniques etc and a competitor could replicate the same structure
> SSLs can prevent http snooping but it can also be bypassed when attacker acts as client.

How does parse address this issue?

**Comment by omkar-tenkale** [comment]
> If you put your query logic into a cloud code than you can access your data in the same way from each of the SDK's without replicating the logic in each language/platforms 


That's what i was saying,
If cloud code is sufficient for all the parse operations,and it also saves time being single source for any platform,also solving much of issues mentioned above,then there remains no need of sdk query functionality,
Does parse recommend cloud code only structure with no client side queries?

**Comment by mman** [comment]
@omkar-tenkale I would say this largely depends on what you want to do and how you want to do it. It's more of a question of the API design for your app.

Yes, you can design your own API and then implement it entirely in a cloud code, potentially connecting to it even without Parse SDK just using HTTPS queries. But it will be hard.

Or you can hack something together quickly by uploading ``PFObject`` instances via client SDK and querying those ``PFObject`` instances back. This is definitely a faster and easier way at the beginning. And yes, if you support multiple platforms, you need to keep those in sync.

**Comment by acinader** [comment]
> >from http requests attacker can see all the query logic,table info,data storage techniques etc and a competitor could replicate the same structure
SSLs can prevent http snooping but it can also be bypassed when attacker acts as client.

> How does parse address this issue?

You asked 'why not query db directly from client'.  If you query directly from client, then you need to expose your database server to the open internet.  

If only the parse-server is accessing your database server then you can only allow access to your data server from the parse-server and prevent any access to it from the internet.

This is standard practice.

**Comment by acinader** [comment]
> That's what i was saying,
If cloud code is sufficient for all the parse operations, and it also saves time being single source for any platform, also solving much of issues mentioned above, then there remains no need of sdk query functionality,
> Does parse recommend cloud code only structure with no client side queries?

I agree with @mman 

No Parse does not recommend 'no queries and cloud code only'.  Not by a long shot.   We expend a lot of effort on the query functionality of the SDK's and for good reason!

This is not an either/or decision.  It is a design decision.  In many cases, moving operations from the client to the cloud does not improve portability of the logic at all and the essence of the operation can be expressed simply and completely using the SDK's query and update capabilities.

In other cases, there are complex logic or security requirements that make cloud code more appropriate.

For example, you wouldn't want the client to 'change' the owner of an object just cause the client asks.  You'd want to implement whatever security considerations you'd want on the server where it cannot be observed and replicated on a client.

Also, you may have complex relationships between classes that you do not want to model on different clients, so it is worth defining a simple API in cloud code.
