### ISSUE TITLE
How to configure 'SignIn with AppleID' with Parse Server 4.2.0

### ISSUE THREAD

**Issue by RodrigoSMarques** [parse-community/parse-server#6564]
The new version of Parse Server resolved some issues related to How to configure 'SignIn with AppleID'.

How should the configuration be done on the Parse Server?

Is only the configuration indicated at [](https://docs.parseplatform.org/parse-server/guide/#apple-authdata sufficient?)

I miss this guidance in the documentation.

**Comment by TomWFox** [comment]
Cross-posted - https://community.parseplatform.org/t/how-to-configure-signin-with-appleid-with-parse-server-4-2-0/109
