### ISSUE TITLE
Configure Docker container with push notifications

### ISSUE THREAD

**Issue by dan-burt** [parse-community/parse-server#6569]
### Issue Description

I would like to create a Docker container using push notifications. I am using the Bitnami Parse-server variant currently. This must be achieved by passing in the appropriate environment variables, from docker-compose.yml configuration files.

The current config is:
`      - PARSE_SERVER_PUSH='{"ios":{"pfx":"/opt/bitnami/parse/pushcert/filename.p8","bundleId":"com.domain.appname","production":false}}'`

(Note, Apple only provides a p8 certificate download now, not p12. Though I have seen websites / forums using this configuration).

When I "up" this container, the logs crash when reading in this line. I expect the syntax is wrong, however I have followed the background of this thread with the same issue:
[https://github.com/parse-community/parse-server/issues/949](https://github.com/parse-community/parse-server/issues/949)

### Push Configuration

Above is the only "push" related configuration.

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : bitnami/parse:3
  - Operating System:     Ubuntu 16.04.6 LTS, running Docker 19.03.8
  - Hardware:             HP Microserver
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): [FILL THIS OUT]

- **Database**
  - MongoDB version: bitnami/mongodb:4.0
  - Storage engine:  Docker Container
  - Hardware:        As above
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): localhost as Docker host

### Logs/Trace

The `^` symbol in the log capture is actually pointing to the first `'` character in the string I provided to this environment variable.

> ,
> Welcome to the Bitnami parse container,
> Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-parse,
> Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-parse/issues,
> ,
> nami    INFO  Initializing parse,
> parse   INFO ,
> parse   INFO  ########################################################################,
> parse   INFO   Installation parameters for parse:,
> parse   INFO     Persisted data and properties have been restored.,
> parse   INFO     Any input specified will not take effect.,
> parse   INFO   This installation requires no credentials.,
> parse   INFO  ########################################################################,
> parse   INFO ,
> nami    INFO  parse successfully initialized,
> INFO  ==> Starting parse... ,
> undefined:1,
> '{"ios":{"pfx":"/opt/bitnami/parse/pushcert/filename.p8","bundleId":"com.domain.appname","production":false}}',
> ^,
> ,
> SyntaxError: Unexpected token ' in JSON at position 0,
>     at JSON.parse (<anonymous>),
>     at objectParser (/opt/bitnami/parse/node_modules/parse-server/lib/Options/parsers.js:38:15),
>     at Object.keys.reduce (/opt/bitnami/parse/node_modules/parse-server/lib/cli/utils/commander.js:79:43),
>     at Array.reduce (<anonymous>),
>     at parseEnvironment (/opt/bitnami/parse/node_modules/parse-server/lib/cli/utils/commander.js:69:43),
>     at Command._commander.Command.parse (/opt/bitnami/parse/node_modules/parse-server/lib/cli/utils/commander.js:138:22),
>     at _default (/opt/bitnami/parse/node_modules/parse-server/lib/cli/utils/runner.js:57:22),
>     at Object.<anonymous> (/opt/bitnami/parse/node_modules/parse-server/lib/cli/parse-server.js:38:21),
>     at Module._compile (module.js:653:30),
>     at Object.Module._extensions..js (module.js:664:10),
> 
>

**Comment by davimacedo** [comment]
Have you tried without the `'`? I mean like this? `- PARSE_SERVER_PUSH={"ios":{"pfx":"/opt/bitnami/parse/pushcert/filename.p8","bundleId":"com.domain.appname","production":false}}`

**Comment by dan-burt** [comment]
Just tried this, and produces a different error:

> ,
> Welcome to the Bitnami parse container,
> Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-parse,
> Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-parse/issues,
> ,
> nami    INFO  Initializing parse,
> parse   INFO ,
> parse   INFO  ########################################################################,
> parse   INFO   Installation parameters for parse:,
> parse   INFO     Persisted data and properties have been restored.,
> parse   INFO     Any input specified will not take effect.,
> parse   INFO   This installation requires no credentials.,
> parse   INFO  ########################################################################,
> parse   INFO ,
> nami    INFO  parse successfully initialized,
> INFO  ==> Starting parse... ,
> Configuration loaded from /opt/bitnami/parse/config.json,
> Passing AWS credentials to this adapter is now DEPRECATED and will be removed in a future version See: https://github.com/parse-server-modules/parse-server-s3-adapter#aws-credentials for details,
> WARN parse-server-push-adapter APNS bundleId is deprecated, use topic instead,
> /opt/bitnami/parse/node_modules/@parse/push-adapter/lib/ParsePushAdapter.js:83,
>           throw _iteratorError;,
>           ^,
> ,
> Error: ENOENT: no such file or directory, open '/opt/bitnami/parse/pushcert/filename.p8',
>     at Object.fs.openSync (fs.js:646:18),
>     at Object.fs.readFileSync (fs.js:551:33),
>     at resolveCredential (/opt/bitnami/parse/node_modules/@parse/node-apn/lib/credentials/resolve.js:16:15),
>     at loadCredentials (/opt/bitnami/parse/node_modules/@parse/node-apn/lib/credentials/certificate/load.js:9:15),
>     at loadAndValidate (/opt/bitnami/parse/node_modules/@parse/node-apn/lib/credentials/certificate/prepare.js:11:20),
>     at config (/opt/bitnami/parse/node_modules/@parse/node-apn/lib/config.js:49:22),
>     at new Client (/opt/bitnami/parse/node_modules/@parse/node-apn/lib/client.js:21:19),
>     at new Provider (/opt/bitnami/parse/node_modules/@parse/node-apn/lib/provider.js:12:19),
>     at Function._createProvider (/opt/bitnami/parse/node_modules/@parse/push-adapter/lib/APNS.js:253:22),
>     at new APNS (/opt/bitnami/parse/node_modules/@parse/push-adapter/lib/APNS.js:81:29),
> 
> 

If I comment out this configuration item, and access the container's bash shell, I can see the file in the expected location. I expect the container's mounted volumes to occur ahead of the parse startup sequence.

**Comment by davimacedo** [comment]
I guess it is not a Parse Server issue but something related on how you are setting up your container. I'm closing the issue for now but happy to help to figure it out. I'd need you to share the `docker-compose.yml` file.

**Comment by dan-burt** [comment]
Thanks @davimacedo 

Attaching the file so the whitespace, etc, is included. I have pushed a lot of items to variables in a `.env` file in the same directory.

[docker-compose.yml.zip](https://github.com/parse-community/parse-server/files/4442745/docker-compose.yml.zip)

**Comment by davimacedo** [comment]
Your compose file looks right to me considering that `vol_parse_push_cert` is correct and you can find the cert file from inside the container. Maybe you should try to open an issue at bitnami repository.
