### ISSUE TITLE
Can you please add 'BaaS' label to repo?

### ISSUE THREAD

**Issue by eyar** [parse-community/parse-server#6574]
**Describe the solution you'd like**
Can you please add 'BaaS' label to repo?

**Comment by TomWFox** [comment]
Can you elaborate on what you mean by a ‘BaaS’ label?

Also Parse Server isn’t really a BaaS because it isn’t a service.

**Comment by eyar** [comment]
I know but if but take a look at https://github.com/topics/baas

Don't you think parse-server should be there?

**Comment by TomWFox** [comment]
I mean it’s not a bass, but it won’t hurt to be there. I’ll add it 🙂
