### ISSUE TITLE
GraphQL: Wait before merging last major version of GraphQL

### ISSUE THREAD

**Issue by Moumouls** [parse-community/parse-server#6577]
Last version of Parse Server (4.2.0) was released with GraphQL `15.0.0`.

I think we should wait before upgrading `graphql` to a major release because it can break and currently breaks merged schemas that use packages with another version like `GraphQL Nexus` or `graphql tools`.

Parse users will be stopped by the following Apollo Error :

`Invalid options provided to ApolloServer: Cannot use GraphQLObjectType \"RoleConnection\" from another module or realm.\n\nEnsure that there is only one instance of \"graphql\" ` 

This error cannot be resolved until the other tools allow the use of the latest version...

**Comment by Moumouls** [comment]
We should probably downgrade `graphql` to `^14.5.8` and release a new parser `4.2.1` ?

**Comment by TomWFox** [comment]
I wonder whether it would be clearer and easier if we just add a clear note to the changelog and release note?

**Comment by davimacedo** [comment]
@Moumouls I believe it will break till the moment the other packages will also upgrade to GraphQL 15.0, right? Since the tests are all passing, I believe we should not consider it a breaking change and I'd go with @TomWFox suggestion of a big disclaimer in the release notes.

**Comment by Moumouls** [comment]
GraphQL Tools is on the road: https://github.com/apollographql/graphql-tools/pull/1353
I opened an issue on Nexus: https://github.com/graphql-nexus/schema/issues/410

**Comment by dotansimha** [comment]
It's currently WIP if `graphql-tools`, which shouldn't effect itself because it's using `graphql` as a peer dependency. 
Is there a reason to have a direct dependency to `graphql` in this package? why not having it as dev+peer and allow people to install their own version of GraphQL? 

Also, if you are using Yarn, you can solve that with `resolutions` field as a workaround.

**Comment by yaacovCR** [comment]
See #6611.

**Comment by Moumouls** [comment]
I may be wrong but we can't use peer dependency system since parse server should run solo without installing any other dependency.

**Comment by zanderisrael** [comment]
any updates on this matter?
