### ISSUE TITLE
Warning from Mongo logged directly to console

### ISSUE THREAD

**Issue by sunshineo** [parse-community/parse-server#6586]
This error just happened to our production. It is logged directly from Parse to console bypassing all our try catch or formatting effort
```
(node:29) DeprecationWarning: collection.findAndRemove is deprecated. Use findOneAndDelete instead.
```
This is not supposed to happen according to https://github.com/parse-community/parse-server/issues/5119

### Environment Setup

- **Server**
  - parse-server version 3.10.0
  - Operating System:     docker node:lts
  - Hardware:             aws ec2
  - Localhost or remote server? aws ec2

- **Database**
  - MongoDB version: 4.2.5
  - Storage engine:  not sure
  - Hardware:        not sure
  - Localhost or remote server?  hosted by MongoDB Atlas 

### Logs/Trace
From this screenshot you can see that it really stands out from all the other logs we formatted
![image](https://user-images.githubusercontent.com/1072766/78928156-fa18eb00-7a54-11ea-8094-517fc24ec463.png)

**Comment by davimacedo** [comment]
It looks we are still using `findAndRemove` [here](https://github.com/parse-community/parse-server/blob/fd637ff4f8ce1da2ea62ec7a8cba909f015961a1/src/Adapters/Storage/Mongo/MongoSchemaCollection.js#L178). This warning will probably show up everytime you drop a class. I will try to fix.

**Comment by sunshineo** [comment]
Thank you @davimacedo

**Comment by dplewis** [comment]
Closing via https://github.com/parse-community/parse-server/pull/6605
