### ISSUE TITLE
GraphQL query returns empty edges

### ISSUE THREAD

**Issue by thphuc** [parse-community/parse-server#6597]
### Issue Description
- GraphQL query return empty edges, but count shows correct number.

### Steps to reproduce
1. Create posts on Post class

2. Make a query:
```
query getPosts($first: Int, $last: Int, $skip: Int) {
  posts(first: $first, last: $last, skip: $skip) {
    edges {
      node {
       objectId
       content
      }
    }
    count
  }
}
``` 
With query variables:
```
{
  "first": 0,
  "last": 20,
  "skip": 0
}
```

### Expected Results

The response should return node info (objectId, content... of posts)

### Actual Outcome
Empty edges (but correct count)
```
{
  "data": {
    "posts": {
      "edges": [],
      "count": 1
    }
  }
}
```

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 4.2.0
  - Operating System:    Ubuntu 19.10 x64 
  - Hardware:             Digital Ocean droplet (2 GB Memory / 25 GB Disk )
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Digital Ocean

- **Database**
  - MongoDB version: 4.2.5
  - Storage engine:  
  - Hardware:      
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): Mongo Atlas

**Comment by davimacedo** [comment]
The problem is the var `"first": 0,`. It will make 0 rows to be returned. Try no passing this var (if you want to use only the `last` var).

**Comment by thphuc** [comment]
Thanks @davimacedo 
It works. But what is the meaning of first? I thought it is the index of first returned node.

**Comment by davimacedo** [comment]
Pagination can be achieved through GraphQL API by using the following inputs:
skip -> skips n objects
first -> returns first n objects
after -> cursor after which the objects will be returned
last -> returns last n objects
before -> cursor before which the objects will be returned

I'd use either:
- skip + first, which would be equivalent to the skip/limit of the REST API
- after + first, to do forward pagination using cursor
- before + last, to do backward pagination using cursor

Any other combination can generate weird results.

**Comment by thphuc** [comment]
Great! Thanks @davimacedo 
May I have your contact? We may have something to share in the future if you have time.

**Comment by davimacedo** [comment]
Sure. Reach me out through [Parse Community](https://community.parseplatform.org).
