### ISSUE TITLE
How to create a Parse Object from JSON for cloud code?

### ISSUE THREAD

**Issue by lorki** [parse-community/parse-server#6622]
data:
``` json
[
  { "id": "210075", "count": 3, "price": 0 },
  { "id": "210074", "count": 3, "price": 0 },
  { "id": "210073", "count": 3, "price": 0 }
]
```
I want to create three ParseObjects through the JSON.

**Comment by mstephano** [comment]
based on this post: https://github.com/parse-community/Parse-SDK-JS/issues/315:
```
const data = [
  { "id": "210075", "count": 3, "price": 0 },
  { "id": "210074", "count": 3, "price": 0 },
  { "id": "210073", "count": 3, "price": 0 }
];

let newArray = [];
data.forEach((item, index) => {
  newArray.push(Parse.Object.fromJSON(item));
});

//newArray here should contains only Parse.Object
```

Let me know if this works.

**Comment by lorki** [comment]
not working.

**Comment by lorki** [comment]
> * based on this post: [parse-community/Parse-SDK-JS#315](https://github.com/parse-community/Parse-SDK-JS/issues/315)
> * api: https://parseplatform.org/Parse-SDK-JS/api/master/Parse.Object.html#.fromJSON
> 
> ```
> let data = [
>   { "id": "210075", "count": 3, "price": 0 },
>   { "id": "210074", "count": 3, "price": 0 },
>   { "id": "210073", "count": 3, "price": 0 }
> ];
> 
> let newArray = [];
> data.forEach((item, index) => {
>   item.className = '<your parse object className here>'; //based on the Parse-SDK-JS source code, the method fromJSON check for an attribute className on the json object
>   newArray.push(Parse.Object.fromJSON(item));
> });
> 
> //newArray here should contains only Parse.Object of type className you have set in the forEach
> ```
> 
> Let me know if this works.

not working

**Comment by mstephano** [comment]
What error do you get?

**Comment by lorki** [comment]
no error, but nothing happened.

But, This problem has been solved.

usage:

``` js
let data = [
  { "id": "210075", "count": 3, "price": 0 },
  { "id": "210074", "count": 3, "price": 0 },
  { "id": "210073", "count": 3, "price": 0 }
];

data.forEach((item, index) => {
            const obj = new Parse.Object("Player");  // define a new obj (the obj)
            obj .set(item);  // set data to obj.
            obj .save(null, {  // save it!
                useMasterKey: true
            });
});

```
