### ISSUE TITLE
beforeSignUp & afterSignUp trigger on cloud

### ISSUE THREAD

**Issue by memishood** [parse-community/parse-server#6634]
Could you add to beforeSignUp & afterSignUp event trigger on cloud code? it would be really awesome.

**Comment by davimacedo** [comment]
Have you tried to use `Parse.Cloud.beforeSave(Parse.User, handler)` and `Parse.Cloud.afterSave(Parse.User, handler)`?

**Comment by memishood** [comment]
Yep, I have tried it works, but sometimes we need just onSign events

**Comment by davimacedo** [comment]
What would be the difference?

**Comment by davimacedo** [comment]
I mean. How would you expect the `onSign` events to work differently from the `beforeSave(Parse.User, handler)`?

**Comment by memishood** [comment]
for example,

We want give a random photo to each user when only signing. if we use beforeSave it will work every save operation. maybe we can fix it using check the request parameters but why do we have to ? if we would have onSign event triggers =)

**Comment by memishood** [comment]
another example,

```
Parse.Cloud.beforeSign(async request => {
     const { object: user } = request;
     if (!user.get(firstName)) {
         throw new Parse.Error(code, `missing First Name`);
     }
});
```

Yes maybe we can make this operation with beforeSave but i mean it would be more useful with onSign events

**Comment by davimacedo** [comment]
You can identify if the user is being saved for the first time like this:

```js
Parse.Cloud.beforeSave(Parse.User, async ({ original }) => {
  if (original) {
    // a new user is being created
  else {
    // an existing user is being updated
   }
});
```

I'm not sure if we'd need a separate signUp event:
- We currently only have `beforeSave` (and not `beforeCreate` and `beforeUpdate`) for all classes
- If we had a `beforeSignUp`, would it be fired when a new user is created using the master key? I think it can maybe make things more confusing.
