### ISSUE TITLE
Enable direct access by default

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-server#6637]
**Is your feature request related to a problem? Please describe.**

- Direct access of Parse Server within Cloud Code is feature flagged for some time.
- It is used in production environments by some without feedback of any major issues.
- Given the potential for significant performance improvement for Parse Server deployments without any code changes necessary, it would be beneficial to move it out of its experimental state and enable it by default.

**Describe the solution you'd like**
Identify any issues, remove the feature flag, *maybe* enable by default, see https://github.com/parse-community/parse-server/issues/6637#issuecomment-636330194.

**Additional context**
- Continuation of https://github.com/parse-community/parse-server/issues/5442
- Direct access was merged feature flagged in https://github.com/parse-community/parse-server/pull/5550

**Related PRs**
- [ ] https://github.com/parse-community/parse-server/pull/6636

**Related discussions**
- https://github.com/parse-community/parse-server/issues/4658

**Comment by mtrezza** [comment]
As quick performance test for `directAccess` here is a load test for a `_User` query by `objectId`:

| response time | status quo | direct access |
|---------------|------------|---------------|
| avg.          | 193.02ms   | 64.69ms       |
| min           | 9ms        | 9ms           |
| p95           | 459ms      | 279ms         |
| p99           | 611ms      | 427ms         |

This shows that it's well worth pursuing this feature.

**Comment by dplewis** [comment]
Check out https://github.com/parse-community/parse-server/pull/6636#issuecomment-618121110

**Comment by mtrezza** [comment]
@dplewis Do you know how I can debug the tests? I tried to use the test explorer plugin for VSCode but the tests don't execute:

![Screen Shot 2020-05-30 at 01 39 07](https://user-images.githubusercontent.com/5673677/83313486-a2a62880-a216-11ea-9d33-c9055d120c48.png)

**Comment by mtrezza** [comment]
> Would you mind to open a PR with this option set true by default so we can see them failing and work together to fix it?

@davimacedo PR opened, but I'm stuck trying to debug the tests, would you please take a look so we can get this going?

**Comment by mtrezza** [comment]
> As for the stability of the feature, it should be fine. But may not fit every workload as everything stays in memory on the same serverz

Does anyone know what was meant by @flovilmart's comment in https://github.com/parse-community/parse-server/issues/4658#issuecomment-373861886?

**Comment by mtrezza** [comment]
>  In a previous series of load testing, we realized that JSON serialization of large objects was a large source of CPU consumption, and was inducing latency in the responses as serialization is blocking the node process.
> 
> In our case, we decided not to go with the direct access but to let internal cloud code calls reach another server, as it was the most optimal solution for our workload

This means that enabling `directAccess` by default can be a breaking change as described in #4658 (comment), so maybe it should be disabled by default.

**Comment by mtrezza** [comment]
Clo

**Comment by mtrezza** [comment]
Closed by https://github.com/parse-community/parse-server/pull/6636

**Comment by gtzinos** [comment]
Anyone we found a way to deal with undefined values?
