### ISSUE TITLE
Reject LiveQuery events / modify LiveQuery query in Cloud Code

### ISSUE THREAD

**Issue by dblythy** [parse-community/parse-server#6642]
**Is your feature request related to a problem? Please describe.**
Is there a way to throw "onLiveQueryEvent"? I've restricted LiveQuerying using ACLs, however I'd like to prevent an unauthorised user from even attempting to subscribe to start. I'd also like to be able to force beforeFind logic to LiveQueries, to ensure the LiveQuery queries themselves are efficient and restrictive.

**Describe the solution you'd like**
Being able to throw from a onLiveQueryEvent, or being able to modify request.query from a LiveQuery.

**Comment by dplewis** [comment]
I like this feature and it should be easy to add a trigger for this. How do you foresee the code looking for this?

You can look [here](https://github.com/parse-community/parse-server/blob/f43afc5d4029008bd22625c4040e913700ee4a52/src/LiveQuery/ParseLiveQueryServer.js#L337) for subscription handling.

**Comment by dblythy** [comment]
Thanks mate. So it would have to be a new trigger? Something like afterLiveQueryEvent, which user can write cloud code - just like onLiveQueryEvent - but if an error is thrown, call Client.pushError? Not entirely familiar with the workings of LiveQuery code but will try create a PR.

**Comment by dblythy** [comment]
Closing as beforeConnect and beforeSubscribe has been merged.

**beforeConnect** allows validation prior to a LiveQuery opening connection. This is not class specific.

```
Parse.Cloud.beforeConnect(request => {
      if (!request.user) {
          throw "Please login before you attempt to connect."
      }
});

```

**beforeSubscribe** handles the .subscribe methods from LiveQuery. Can be used to validate users, or to mutate the request.query, enforcing fields, equalTo, or whatever required.

```
Parse.Cloud.beforeSubscribe(Parse.User, request => {
    if (!request.user) {
        throw "Please login before you attempt to connect."
    }
    let query = request.query; // the Parse.Query
    query.select("name","year")
});

```

And via the JS-SDK:
```
Parse.LiveQuery.on('error', error => {
      alert(error)
})
```
