### ISSUE TITLE
explain() does not work in Cloud Code

### ISSUE THREAD

**Issue by vmirzoyan** [parse-community/parse-server#6647]
### Issue Description

An error is throw when trying to use .explain() on a parse query in a cloud code function.

### Steps to reproduce

Create any cloud function that implements any basic query that should return a list.

According to the JS SDK documentation, explain() can be used on a query object to allow chaining.
http://parseplatform.org/Parse-SDK-JS/api/2.12.0/Parse.Query.html#explain

    return new Parse.Query(Parse.Object.extend("_User"))
        .equalTo("active", true)
        .explain()
        .find({useMasterKey:true});
 
### Expected Results

A successful response with query execution plan details as outlined here:
https://docs.mongodb.com/manual/reference/operator/meta/explain/

### Actual Outcome

The following error is thrown.

TypeError: results is not iterable
          at /parse-server/lib/RestQuery.js:613:26
          at processTicksAndRejections (internal/process/task_queues.js:97:5)

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 4.2.0

- **Database**
  - MongoDB version: 4.0.6

**Comment by mtrezza** [comment]
> TypeError: results is not iterable
> at /parse-server/lib/RestQuery.js:613:26
> at processTicksAndRejections (internal/process/task_queues.js:97:5)

When you use `explain` you don't get the resulting objects of the query, you get the `explain` output. It looks like you try to iterate through the results of the query at some point in your code, but it fails because the result is not an array of objects.

**Comment by mtrezza** [comment]
Good find, this was an issue that only affected explain on the `User` class.
