### ISSUE TITLE
callCloudCode GraphQL mutation doesn't pass variable parameters

### ISSUE THREAD

**Issue by lucatk** [parse-community/parse-server#6663]
### Issue Description

When calling cloud functions using the GraphQL mutation `callCloudCode` and supplying params using variables, the params input using variables do not exist.

### Steps to reproduce

1. Define a cloud function
```js
Parse.Cloud.define('functionWithArgs', async ({ params }) => {
  return params;
});
```
2. Call `callCloudCode` mutation (e.g. using GraphQL playground), supplying the necessary variables, e.g. `{ variableParam: 'Hi!' }`
```gql
mutation test($variableParam: String!) {
  callCloudCode(input: {
    functionName: functionWithArgs,
    params: {
      variableParam: $variableParam,
      nonVariableParam: 'Hola!'
    },
  }) {
    result
  }
}
```

### Expected Results

Function to return all params:
```js
{
  variableParam: 'Hi!',
  nonVariableParam: 'Hola!'
}
```

### Actual Outcome

Variable params are lost, function only receives and returns 'static' params:
```js
{
  nonVariableParam: 'Hola!'
}
```

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 4.2.0
  - Operating System:     Official docker image (therefore Alpine, as it seems)
  - Hardware: macOS Host, Docker container guest
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Local docker

- **Database**
  - MongoDB version: 4.2.6
  - Storage engine: 
  - Hardware: Official docker image
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): Local docker

**Comment by davimacedo** [comment]
Thanks for reporting. Would you be willed to open a PR with a test case for this bug?

**Comment by Moumouls** [comment]
It's an expected behavior.

Since `params` is a graphql scalar, graphQL can't inject some values and perform validation on value inside a scalar (it's an opaque data for graphql). To avoid unexpected error during parsing graphQL just ignore the value.

Here you should change your mutation input to `test($params: Object)` and in your mutation `params: $params`
