### ISSUE TITLE
Struggling with saving dates in the right time zone

### ISSUE THREAD

**Issue by JorisGanne** [parse-community/parse-server#6671]
I'm currently programming an app for android. One of the functionalities is to select a range of dates and then upload it to the parse server. Everything goes well unitl I save it to the parse server... The process is as following:
- First, I retrieve the selected dates from the calendar in the format Calendar
-Next I convert the dates from Calendar-type to date with the following code: calendar.getTime();
-Last, I upload the dates to the parseServer

They appear all in the parse server, but because I saved my dates in my local timezone (It just happen, it doesn't matter for me), ParseServer doesn't save the 'right' dates (example: I select 7 may, the android app gives 7 may 00:00 UTC+2 and as following, parse saves it as 6 mai 22:00 UTC)
The time is totally not important for me, but I don't know how to handle this...
How can I ensure that parse will save the rigth dates?
Thanks in advance!

**Comment by davimacedo** [comment]
Could you please share your current code and I will try to advise?
