### ISSUE TITLE
bcrypt 4.0.1 / binding failed: Symbol not found: _napi_add_finalizer 

### ISSUE THREAD

**Issue by allanext** [parse-community/parse-server#6677]
### Issue Description

Updated parse-server to 4.2.0 and the dependency bcrypt 4.0.1 is giving:
```
dyld: lazy symbol binding failed: Symbol not found: _napi_add_finalizer
Referenced from: /Users/developer/Desktop/Life/MyCode/wmNode/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node
Expected in: flat namespace
```
I've tried to remove/install all modules and also `npm rebuild bcrypt --build-from-source`

There's an open issue: https://github.com/kelektiv/node.bcrypt.js/issues/792 and as suggested bcrypt 3.0.7 works

To make it work i've removed bcrypt (package-lock.json) from requires and added to dependencies; `rm -rf node_modules; npm install`
```
"parse-server": {
      "version": "4.2.0",
      "resolved": "https://registry.npmjs.org/parse-server/-/parse-server-4.2.0.tgz",
      "integrity": "sha512-xSsK8dLwNuMOsodQ8Hpmy8QgZFR2lqjre8GG7gPQ7yG3htDuYn5V0XH2bQDL4OXLGwKNp/b/TBUO8Bho1uAE0Q==",
      "requires": {
        "@apollographql/graphql-playground-html": "1.6.24",
        ...
        "ws": "7.2.3"
      },
      "dependencies": {
        "bcrypt": {
          "version": "3.0.7",
          "resolved": "https://registry.npmjs.org/bcrypt/-/bcrypt-3.0.7.tgz",
```

Am I missing something?
Cheers

**Comment by jonas-db** [comment]
What node.js version are you using? I remember having a similar issue with bcrypt when I was still on an old node.js version. Try to upgrade to latest node.js and make sure you are actually using it (eg use nvm to check)

**Comment by allanext** [comment]
I thought i was using node 14 but sudo process was referring to an old version of node. 

Thank you!
