### ISSUE TITLE
Id token is invalid for user, while login from android with apple id

### ISSUE THREAD

**Issue by sshuvro58** [parse-community/parse-server#6683]
I was trying to login with apple from android app .By following apple documentation I was able to get access token and apple id .  Later I have done the following from android 

```
        Map<String, String> authData = new HashMap<>();
        authData.put("id", "my_apple_id");
        authData.put("access_token", "my_access_token");
        ParseUser.logInWithInBackground("apple", authData);
```

In parse server I have also added apple auth adapter 

```
 auth: {
        apple: {
            client_id: "my client id"
        }
    }
```

But I get the error `Id token is invalid for user,`

How can I resolve this ?

Parse server version : 3.9.10

**Comment by diepthuyvi** [comment]
Do you result the problem. I use Parse Server and my error like this
