### ISSUE TITLE
Invalid session error is not returned as normal Parse error, but as server error

### ISSUE THREAD

**Issue by sarsonj** [parse-community/parse-server#6684]
### Issue Description

We are using Parse API to check, if session is still valid and if not, we do logout internally and show login screen. It worked till we upgraded to newest Parse server 4.2.0 (till then we had 3.9.0). However, now the server returns generic error 500 without any info about specific error (invalid session in this case).

### Steps to reproduce

Call for example /users/me REST API with non existing sessionID. 
### Expected Results
I expected to get Parse specific response with error INVALID_SESSION_TOKEN, as it worked with previous versions of Parse server

### Actual Outcome
I get Error 500 - interval server error

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 4.2.0
  - Operating System:     linux / docker 
  - Localhost or remote server? Digital Ocean k8s

- **Database**
  - PosgreSql: PostgreSQL 11
  - Localhost or remote server? Digital Ocean

### Logs/Trace
Callstack:

Error: Invalid session token
at Object.getAuthForSessionToken (/opt/app/node_modules/parse-server/lib/Auth.js:114:11)
at runMicrotasks (<anonymous>)
 at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by sarsonj** [comment]
Update - I downgraded to Parse server 4.1.0 and everything works as expected on this version. So that problem have to happen somewhere between 4.1.0 and 4.2.0.

**Comment by mtrezza** [comment]
Maybe related to https://github.com/parse-community/parse-server/issues/6082
