### ISSUE TITLE
GraphQL: Possibility to order by Pointer's field

### ISSUE THREAD

**Issue by murshudov** [parse-community/parse-server#6686]
**Is your feature request related to a problem? Please describe.**
Currently, I couldn't find any way to order query results by the nested class field. 

**Describe the solution you'd like**
I have a `Job` and `Adress` classes. 
`Job` fields - title: string, ..., category: _Pointer_ to `Category`
`Category` fields - name: string, order: number

I would like to order jobs by category name or category order. 

**Describe alternatives you've considered**
I couldn't find any clear alternatives. I can put all fields that need to be used in order directly to Job class (eg. category_name, category_order), but it is really ugly and not the way things should work.

**Comment by Moumouls** [comment]
If I'm not mistaken, this feature is not available through the Rest API. So unfortunately we can't add it on the GraphQL part.

This type of query also poses big performance problems.

If you don't have a large amount of data in return I advise you to make a local order on the result. 
You can also review your relations or UI for a less complex query.

**Comment by Moumouls** [comment]
@murshudov  based on https://github.com/parse-community/parse-server/issues/1908, Parse Server will not support (probably for a long time) the order by pointer.

I can only suggest you to add needed fields  to order your query on the Job class and you can also create a cloud function beforeSave for the Job class that get the Address pointer and save needed informations for your Job sort query into the Job object.

Denormalized fields + beforeSave will be the best and optimized solution for your use case 👍

**Comment by aacassandra** [comment]
> @murshudov based on #1908, Parse Server will not support (probably for a long time) the order by pointer.
> 
> I can only suggest you to add needed fields to order your query on the Job class and you can also create a cloud function beforeSave for the Job class that get the Address pointer and save needed informations for your Job sort query into the Job object.
> 
> Denormalized fields + beforeSave will be the best and optimized solution for your use case 👍

how when using rest api ?
