### ISSUE TITLE
Ability to disable authentication

### ISSUE THREAD

**Issue by EricNetsch** [parse-community/parse-server#6707]
**Is your feature request related to a problem? Please describe.**
Ability to disable authentication on parse-server.

This will be very helpful for 2 main use-cases:
- People using parse-server as a simple API who don't want authentication
- People using parse-server in microservices where only some services need authentication endpoints. This would provide better security controls and reduce vulnerabilities.

**Describe the solution you'd like**
Add a config option to the parse-server initialization that will disable all authentication endpoints
`enableAuthentication: false`

**Describe alternatives you've considered**
Blocking endpoints manually on the routing and Nginx side

Open to workarounds or existing solutions

**Additional context**

**Comment by mtrezza** [comment]
Parse Server does not require authentication, see for example the Parse Arduino SDK for IoT.

> Add a config option to the parse-server initialization that will disable all authentication endpoints

Users and sessions are available if you decide to use them. If you want to forcefully prevent someone from using the related endpoints, you can do that with triggers in Cloud Code.

**Comment by EricNetsch** [comment]
@mtrezza Thanks for the reply.

What about for this use-case? Assuming many parse-server instances are using the same DB, CLP and ACL configs.

> People using parse-server in microservices where only some services need authentication endpoints. This would provide better security controls and reduce vulnerabilities.

**Comment by mtrezza** [comment]
What specifically would that use case require?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Moumouls** [comment]
If you want to block authentication you can throw an error into beforeLogin hook or beforeSave User hook
You can also set the CLP of you classes (User too) to `{}`; then only master key will be authorized to perform actions.

ex: 
```js
	classLevelPermissions: {
		find: {},
		count: {},
		get: {},
		update: {},
		create: {},
		delete: {},
		addField: {},
		protectedFields: {},
	},
```

**Comment by EricNetsch** [comment]
@Moumouls 
Yeah, I think rejection in beforeLogin could work for our use-case. 
Will that trigger only via the login endpoint? or also during session create endpoint?

Also, CLP is not honored on certain _Sessions class operations which is a bummer

**Comment by Moumouls** [comment]
beforeSave do not exists on `_Session` class (performance reason). thanks for this security part:

```js
// Handles the _Session class specialness.
// Does nothing if this isn't an _Session object.
RestWrite.prototype.handleSession = function() {
  if (this.response || this.className !== '_Session') {
    return;
  }

 // The current request should be authenticated or executed with masterKey
  if (!this.auth.user && !this.auth.isMaster) {
    throw new Parse.Error(
      Parse.Error.INVALID_SESSION_TOKEN,
      'Session token required.'
    );
  }

  // TODO: Verify proper error to throw
  if (this.data.ACL) {
    throw new Parse.Error(
      Parse.Error.INVALID_KEY_NAME,
      'Cannot set ' + 'ACL on a Session.'
    );
  }
```

An anonymous user will never be authorized to create a _Session if it was not logged in before, to resume a user can only get a session token from:
- Custom logic in Cloud Code
- Login/signup (beforeLogin can block this)
- loginWith (beforeLogin can block this)

**Comment by Moumouls** [comment]
I think you are ready to disable auth on your parse server 😃 
Feel free to close this issue

**Comment by mtrezza** [comment]
@EricNetsch As I wrote in my previous comment, you can solve this with triggers. If you set a `beforeSave` trigger for the `User` and `Session` class then it’s not possible to create a user or session regardless of the endpoint.

Also note that `beforeLogin` is the wrong trigger for your use case, as it’s not triggered on sign-up, but when logging in an existing user.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Moumouls** [comment]
@mtrezza , warning here, common triggers are not allowed on _Session class. Here to be sure to block the auth: beforeSave on User and beforeLogin should do the trick 👍

**Comment by EricNetsch** [comment]
@Moumouls Thanks for the example in RestWrite. 
What I'm seeing is that there is no way to disable Session create API regardless of _User beforeSave and CLPs. 

POST `/classes/_Session`

I understand the behavior when blocking the  _User class but I really would like to secure the session endpoints as well. We have a certain use-case that requires this. 

Where would we go about modifying the restwrite per your example?

**Comment by Moumouls** [comment]
You do not need to disable it, since it is implicitly disabled. If you block the before save on user, it will be not possible to use it without masterkey.

**Comment by mtrezza** [comment]
I'm closing this as it seems to be answered, feel free to comment if you have any questions and we can re-open this issue.
