### ISSUE TITLE
GraphQL query returning wrong file.url

### ISSUE THREAD

**Issue by mstephano** [parse-community/parse-server#6714]
### Issue Description

Following guide at http://docs.parseplatform.org/graphql/guide/#create-and-add-a-file, when properly uploading a file using GraphQL Mutation, the file.url returned contains "../graphq/..". Not sure why just "graphq" without the L in the end, but it should be "../parse/.." instead.

**NOTE** Must use MongoDB as database to save file. I spent a complete day debugging to finally found a post saying that saving files with PostgreSQL is not possible,

### Steps to reproduce

1. In parse-dashboard, create a class with a column of type "File".
1. Create a new record, and put an image file in that new column.
1. Double click on that file column, and select "Download" button.
1. Your picture should open in a new browser tab. Notice the URL in the new tab - should read something like "../parse/.."

1. Now in parse-dashboard, go to GraphQL Console page.
1. Make a GraphQL query to get records from that class you created, and include the name and url of that column of type "File".
1. Notice the result will have url with ../graphq/.. instead of ../parse/..   (you can also see "graphq" in the examples in the guide link above)

### Expected Results

GraphQL query should return proper url with ../parse/..

### Actual Outcome

GraphQL query returned url with ../graphq/..   (why only graphq without L is a mystery). This url with "graphq" is not working. Even changing to "graphql" will say error: unauthorized. But if replace with ../parse/.., image will show.

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 4.2.0
  - Operating System:     Windows 10
  - Hardware:            docker-desktop for Windows
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): parse-server, parse-dashboard and MongoDB are run in docker containers locally

- **Database**
  - MongoDB version: 4.2.0
  - Storage engine:  in a docker container
  - Hardware:        docker-desktop for Windows
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): localhost

### Logs/Trace

Docker Logs of parse-server container:
```
PS C:\Users\mstephano> docker logs 48c
allowClientClassCreation: true
appId: test
cacheMaxSize: 10000
cacheTTL: 5000
customPages: {}
databaseURI: mongodb://mongo/test
enableAnonymousUsers: true
expireInactiveSessions: true
graphQLPath: /graphql
host: 0.0.0.0
logsFolder: ./logs
masterKey: ***REDACTED***
masterKeyIps: []
maxUploadSize: 20mb
mountGraphQL: true
mountPath: /parse
mountPlayground: true
objectIdSize: 10
playgroundPath: /playground
port: 1337
protectedFields: {"_User":{"*":["email"]}}
revokeSessionOnPasswordReset: true
schemaCacheTTL: 5000
sessionLength: 31536000
allowCustomObjectId: false
collectionPrefix:
directAccess: false
enableExpressErrorHandler: false
enableSingleSchemaCache: false
preserveFileName: false
preventLoginWithUnverifiedEmail: false
scheduledPush: false
verifyUserEmails: false
jsonLogs: false
verbose: false
level: undefined
serverURL: http://localhost:1337/parse

[1] parse-server running on http://localhost:1337/parse
[1] GraphQL running on http://localhost:1337/graphql
[1] Playground running on http://localhost:1337/playground
PS C:\Users\mstephano>
```

**Comment by Moumouls** [comment]
You need to set in your parse server config the `publicServerURL` the make it working correctly. (ex for dev env: http://localhost:1337/parse)

**Comment by mtrezza** [comment]
I'm closing this as it seems to be resolved. Feel free to comment if you have any questions and we can re-open this issue.

The requirement to set the `publicServerURL` is already documented in the [GraphQL docs](http://docs.parseplatform.org/graphql/guide/#using-expressjs) and [Parse Server GitHub readme](https://github.com/parse-community/parse-server#using-expressjs), so there seems to be no required change in the documentation. If you think the documentation can be improved, please let us know where you would expect to see which information by opening an issue in the [docs repo](https://github.com/parse-community/docs/issues).
