### ISSUE TITLE
Error: accept EMFILE

### ISSUE THREAD

**Issue by ozbillwang** [parse-community/parse-server#6716]
### Issue Description

```
  | 2020-05-28T08:12:58.648+10:00 | /parse-server/lib/ParseServer.js:231
  | 2020-05-28T08:12:58.648+10:00 | throw err;
  | 2020-05-28T08:12:58.648+10:00 | ^
  | 2020-05-28T08:12:58.648+10:00 | Error: accept EMFILE
  | 2020-05-28T08:12:58.648+10:00 | at TCP.onconnection (net.js:1534:24)
  | 2020-05-28T08:12:58.648+10:00 | Emitted 'error' event on WebSocketServer instance at:
  | 2020-05-28T08:12:58.648+10:00 | at Server.emit (events.js:315:20)
  | 2020-05-28T08:12:58.648+10:00 | at Server.EventEmitter.emit (domain.js:482:12)
  | 2020-05-28T08:12:58.648+10:00 | at TCP.onconnection (net.js:1534:10) {
  | 2020-05-28T08:12:58.648+10:00 | errno: 'EMFILE',
  | 2020-05-28T08:12:58.648+10:00 | code: 'EMFILE',
  | 2020-05-28T08:12:58.648+10:00 | syscall: 'accept'
  | 2020-05-28T08:12:58.648+10:00 | }
```
### Steps to reproduce

Not sure how to reproduce. I got this error, then parse server crash, and it has to be restarted. That's the problem I currently met.
 
### Expected Results

Parse server should be not crash

### Actual Outcome

Parse server is crash everytime, I saw this log

### What I did

Looks the problem is related to file lmits setting (ulimit)

https://html.developreference.com/article/18379353/Socket+IO+infinite+loop+over+1000+connections

https://groups.google.com/forum/#!topic/nodejs/1Fy-lfH8r9Y

Anyone can explain what's the problem. I try to adjust the ulimit to `unlimited`, but seems it doesn't work.

**Comment by dplewis** [comment]
Looks like an error with the Live Query.

What version of the server are you using?

**Comment by ozbillwang** [comment]
it is a little bit old: v3.4.4

**Comment by dplewis** [comment]
Please update to the latest version. It will output the payload or this issue may have already been fixed
