### ISSUE TITLE
How to manipulate data  on BeforeFileSave

### ISSUE THREAD

**Issue by ChineOnw** [parse-community/parse-server#6722]
Hi everybody,

I have the following scenario. I am saving a class with an attribute of type file (image). When the client saves the class, the `beforeSaveFile()` function triggers. 
In other hookups I can specify the class I want to spy on e.g. `beforeSave()`.
How can I know in the `beforeSaveFIle()` hookup that it is for a certain class -> attribute.
Because in that case and only in that case I want to compress the image before saving.

Does anyone has a solution for this one ?

**Comment by uzaysan** [comment]
You can't know class in file trigger. File don't have class information. First you upload your image then you associate the file with class

**Comment by mtrezza** [comment]
I'm closing this as it seems to be resolved. Feel free to comment if you have any questions and we can re-open this issue.
