### ISSUE TITLE
Add Typescript type definitions

### ISSUE THREAD

**Issue by obermillerk** [parse-community/parse-server#6727]
I'd like to use typescript with the parse-server module, but the lack of type definitions makes this frustrating and not particularly useful. The documentation basically already has all the typing listed out in about as much detail as typescript provides. The work has/is already being done it seems, why not add type definitions so typescript users can benefit?

If these do exist somewhere I have not been able to find them after searching for most of the day, so I apologize if that's the case.

**Comment by samjarman** [comment]
I'd also be excited to see typings for the project. Would the community be open to a PR?

**Comment by davimacedo** [comment]
Yes. A PR would be welcome.

**Comment by swittk** [comment]
Anyone working on this?
