### ISSUE TITLE
Not possible to use new Instagram API

### ISSUE THREAD

**Issue by mschwarz8** [parse-community/parse-server#6728]
### Issue Description

Since the old Instagram API will stop working on June 29 (See https://www.instagram.com/developer/), the url in https://github.com/parse-community/parse-server/blob/d0a9c709fea4cbdba540420353a36a0e89601ffb/src/Adapters/Auth/instagram.js#L9 needs to be changed to match the new "instagram_graph_user_profile" API. (See https://developers.facebook.com/docs/instagram-basic-display-api/guides/getting-profiles-and-media).
The new default URL should be something like this:
https://graph.instagram.com/me?fields=id&access_token=ACCESS_TOKEN

### Steps to reproduce

1. Get the authentication_code from authorization window
`https://www.instagram.com/oauth/authorize?client_id=CLIENT_ID&redirect_uri=REDIRECT_URI&scope=user_profile,user_media&response_type=code`
2. Get a short-lived token
```
curl --location --request POST 'https://api.instagram.com/oauth/access_token' \
--form 'client_id=CLIENT_ID' \
--form 'client_secret=CLIENT_SECRET' \
--form 'grant_type=authorization_code' \
--form 'redirect_uri=REDIRECT_URI' \
--form 'code=AUTHORIZATION_CODE'
```
3. Trying to register new user via ParseServer will perform following call:
```json
curl --location --request GET 'https://api.instagram.com/v1/users/self?access_token=SHORT_LIVED_ACCESS_TOKEN'
```
 
### Expected Results

User is being verified successfully and user can be registered via Instagram.

### Actual Outcome

ParseServer receives following:
```json
{
    "meta": {
        "code": 400,
        "error_type": "OAuthAccessTokenException",
        "error_message": "The access_token provided is invalid."
    }
}
```
and returns 
```json
{
    "code": 101,
    "error": "Instagram auth is invalid for this user."
}
```
to developer.
### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 3.9.0
  - Operating System:     Back4App
  - Hardware:             Back4App
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Back4App

- **Database**
  - MongoDB version: Back4App
  - Storage engine:  Back4App
  - Hardware:        Back4App
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): Back4App

### Logs/Trace

No logs

**Comment by mtrezza** [comment]
Thanks for reporting this. Do you thin you could tackle this and open a PR?

**Comment by ruhci28** [comment]
hye is this issue still open .?

**Comment by TomWFox** [comment]
@ruhci28 yep, it hasn't been addressed yet.

**Comment by Moumouls** [comment]
@mschwarz8  i can close this one, the issue was patched by @timination  :)

**Comment by alexandre-araujo-barboza** [comment]
2021-06-20 => The access_token provided is STILL invalid!!!
