### ISSUE TITLE
Need to add "viewCode: true" in features.cloudCode json of FeaturesRouter.js 

### ISSUE THREAD

**Issue by dinoLee** [parse-community/parse-server#6752]
1. When Run Parse-Dashboard.
request http://xxx.xxx.xxx/parse/serverInfo
response 
```
{"features":{"globalConfig":{"create":true,"read":true,"update":true,"delete":true},"hooks":{"create":true,"read":true,"update":true,"delete":true},"cloudCode":{"jobs":true},"logs":{"level":true,"size":true,"order":true,"until":true,"from":true},"push":{"immediatePush":false,"scheduledPush":false,"storedPushData":false,"pushAudiences":true,"localization":true},"schemas":{"addField":true,"removeField":true,"addClass":true,"removeClass":true,"clearAllDataFromClass":true,"exportClass":false,"editClassLevelPermissions":true,"editPointerPermissions":true}},"parseServerVersion":"4.2.0"}
```

2. If change "cloudCode":{"jobs":true} to "cloudCode":{"jobs":true, "viewCode":true}, so Parse-Dashboard Side Menu show "Cloud Code". But Current Do not Show "Cloud Code" Menu.
ref) You will know cause, if see parse-dashboard/src/dashboard/DashboardView.react.js,
```
if (features.cloudCode && features.cloudCode.viewCode) {
  coreSubsections.push({
	name: 'Cloud Code',
	link: '/cloud_code'
  });
}
```

3. So need to change
```
	const features = {... 
		cloudCode: {jobs: true}
	,...} 

	to

	const features = {... 
		cloudCode: {jobs: true, viewCode: true}
	,...}
	
	in FeaturesRouter.js

**Comment by mtrezza** [comment]
This feature has not been implemented in Open Source Parse Server yet.

Historically, on hosted Parse Server it was possible to interact with Cloud Code directly in the Parse Dashboard. But this is not possible in Open Source Parse Server, even with the change you suggest. As you can see, the dashboard would try to get the cloud code file from endpoint `/releases/latest`. This endpoint does not exist on Open Source Parse Server.

https://github.com/parse-community/parse-dashboard/blob/ed5e4f3c23b002b1c259fc60b72ed7a58abac3b1/src/lib/ParseApp.js#L157

**Comment by mtrezza** [comment]
I'm closing this for now, feel free to re-open if you have any questions.

**Comment by TomWFox** [comment]
Btw @mtrezza if you close an issue the author can't reopen - only those with triage access and above can.

**Comment by mtrezza** [comment]
@TomWFox Thanks, I rephrased my previous comment 🙂
