### ISSUE TITLE
Session Token Length

### ISSUE THREAD

**Issue by gregorskii** [parse-community/parse-server#6755]
### Issue Description

OWASP recommends session tokens should be 128 bit. Parse sessions are currently 32 bit:

https://github.com/parse-community/parse-server/blob/de79b70cbce7abd3b8bae1ef66d5a15ab0a5f144/src/cryptoUtils.js#L43

https://owasp.org/www-community/vulnerabilities/Insufficient_Session-ID_Length

### Steps to reproduce

No reproduction needed, code attached.
 
### Expected Results

Session token to be a minimum of 128 bits, or be of configurable length for flexibility.

### Actual Outcome

Session tokens are 32 bit.

### Environment Setup

- **Server**
  - parse-server version : 4.2.0
  - Operating System: Linux
  - Hardware: Ubuntu / Cloud Server
  - Localhost or remote server? GCS

- **Database**
  - MongoDB version: 3.6.18
  - Storage engine:  N/A
  - Hardware:        N/A
  - Localhost or remote server? Cloud Atlas

**Comment by mtrezza** [comment]
> With a 64 bit session identifier, assume 32 bits of entropy. (...) the expected time for an attacker to successfully guess a valid session identifier is about 7 minutes.

I think this issue should receive attention. @dplewis @acinader @davimacedo

**Comment by mtrezza** [comment]
The current session token has 32 characters, that's 256 bit, so we should be good.

**Comment by gregorskii** [comment]
Derp thank you.
