### ISSUE TITLE
Fix: randomly failing tests

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-server#6758]
### Issue Description

Builds seem to be randomly failing in Travis CI. My assumption is that the cases have bugs rather than a general issue with the way tests are conducted because it seem to be always the same test cases that randomly fail at unrelated PRs. This leads to builds by bots to fail unnecessarily and kind of hinders the CI flow.

For example:
```
ParseGraphQLServer Auto API Schema Relay Spec Object Identification Id inputs should work either with global id or object id
Expected 'U2Vjb25kYXJ5T2JqZWN0OmhnSlNFTDhuS1o=' to be less than 'U2Vjb25kYXJ5T2JqZWN0Om5HUE9pa1NpZGQ='.
```
Observed in:
- https://travis-ci.org/github/parse-community/parse-server/jobs/702234299
- https://travis-ci.org/github/parse-community/parse-server/jobs/701887581

### Expected Results

Tests should pass.

### Actual Outcome

Tests randomly pass / fail at times.

**Comment by mtrezza** [comment]
@davimacedo Would you mind taking a look at it when you can? Maybe you can find the issue easily since you are familiar with the test case.

**Comment by dplewis** [comment]
I agree @davimacedo is it ok if we xit for now?

**Comment by mtrezza** [comment]
I noticed that some 5 - 10 tests are randomly failing, maybe there is an additional other issue. My first guess would be something like a race condition, maybe indeed related to the test suite setup. Keeping an eye on it...

**Comment by davimacedo** [comment]
Hi guys. Sorry for the delay. I will look at the failing tests (including the GraphQL ones) and send a PR.

**Comment by mtrezza** [comment]
This issue seems to have been solved.
