### ISSUE TITLE
Parse Cloud function returns empty object after upgraded from Parse Server 2.0 to 3.0

### ISSUE THREAD

**Issue by grassland-curing-cfa** [parse-community/parse-server#6766]
# Before opening the issue please ensure that you have:

- [ ] [Read the migration guide](https://github.com/parse-community/parse-server/blob/master/3.0.0.md) to parse-server 3.0.0
- [ ] [Read the migration guide](https://github.com/parse-community/Parse-SDK-JS/blob/master/2.0.0.md) to Parse SDK JS 2.0.0

### Issue Description

I was trying to migrate my Cloud functions from Parse Server 2.0 to 3.0.

This following Cloud function aims to return count of GCUR_OBSERVATION to the client. I intended to use native promises instead of async/await.

```
Parse.Cloud.define("countOfObservations", (request) => {
    var query = new Parse.Query("GCUR_OBSERVATION");
    var countOfObs = 0;
    query.count({ useMasterKey: true }).then( (count) => {
        countOfObs = count;
        console.log("*** count=" + countOfObs);
        return countOfObs;
    });
});
```

When I tried to call this function from the client side using cURL:

curl -X POST -H "X-Parse-Application-Id: {APP_ID}" -H "X-Parse-REST-API-Key: {REST_API_KEY}t" -H "Content-Type: application/json" https://{SERVER_URL}/parse/functions/countOfObservations

`{}` was returned. However the back-end console correctly printed `*** count=2882`.

### Expected Results

{"result":2882}

### Actual Outcome

{}

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 4.2.0
  - Operating System:     Heroku
  - Hardware:            Heroku
  - Localhost or remote server? Heroku

- **Database**
  - MongoDB version: 4.2.8
  - Storage engine: MongoDB Atlas
  - Hardware:        MongoDB Atlas
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): MongoDB Atlas

**Comment by dplewis** [comment]
I’d highly recommend using await / async, if you had you would see the error here.

You aren’t returning anything in that cloud code function. 

return query.count should do the trick. Also count operations are expensive.

**Comment by grassland-curing-cfa** [comment]
Thanks @dplewis !
Please help further clarify a few points.

According to "Upgrade Parse Server to 3.0" documentation, "For asynchronous code, you can use promises or async / await." I am in the middle of migrating several hundreds of Cloud functions from 2.0 to 3.0. Can I rewrite my code to native promises instead of async/await to minimize the work/cost?

I don't understand why my weren't returning anything. I thought, after changing "function(request, response)" to "(request) =>" most my Cloud functions would still work as promises are already in use. How can I rewrite the code as above to make it return count of gcur_observation just to give an example?
