### ISSUE TITLE
FR: successful password reset should unlock account locked via accountLockout policy

### ISSUE THREAD

**Issue by mman** [parse-community/parse-server#6773]
Running parse server 4.2.0 with ``accountLockout`` policy configured to enable locking accounts when incorrect password is entered multiple times.

What I found out is that when a user gets locked out due to many failed login attempts, and then performs a password reset successfully, the account remains locked.

I thinks a successful password reset should unlock the account.

What do you think?
Martin

**Comment by mtrezza** [comment]
I think it makes sense. I just tried out Twitter's account lock policy and it works the way you describe:

- The account is unlocked after n retries
- Even entering the correct password does not unlock the account.
- Password reset via email works, unlocks the account and allows to login immediately.

**Comment by mman** [comment]
This should remain open

**Comment by mtrezza** [comment]
The PR above introduces an option to define this behavior. The PR is currently in review.
