### ISSUE TITLE
How to put keys in JSONArray?

### ISSUE THREAD

**Issue by Berki2021** [parse-community/parse-server#6777]
I am trying to save a JSONArray in my User class, but every time I pass it to the server, the array is empty or the user is not saved. And is there a possible way to safe the array with a specific key e.g. put("country", _country)?

I tried using JSONObjects, but I couldn't save more than one and every time I tried to save a second JSONObject the first one got overriden. 

Here is my approach:

    fun createJSONArray(_country: String, _postcode: Int, _city: String, _street: String, _houseNumber: Int): JSONArray {
        val array = JSONArray()
        array.apply {
            put(1, _country)
            put(2, _postcode)
            put(3, _city)
            put(4, _street)
            put(5, _houseNumber)
        }
        return array
    }

    fun signUp(_username: String, _password: String, _eMailAdress: String, _adress: JSONArray): ParseUser = ParseUser().apply {
        username = _username
        setPassword(_password)
        email = _eMailAdress
        put("adress", _adress)
        signUpInBackground()
    }

and here my approach using JSONObject:

    fun createJSONObject(_country: String, _postcode: Int, _city: String, _street: String, _houseNumber: Int): JSONObject {
        val adress = JSONObject()
        adress.apply {
            put("country", _country)
            put("postocde", _postcode)
            put("city", _city)
            put("street", _street)
            put("houseNumber", _houseNumber)
        }

    fun signUp(_username: String, _password: String, _eMailAdress: String, _adress: JSONObject): ParseUser = ParseUser().apply {
        username = _username
        setPassword(_password)
        email = _eMailAdress
        put("adress", _adress)
        signUpInBackground()
    }

![Screenshot_1](https://user-images.githubusercontent.com/65120636/86653071-3244b100-bfe5-11ea-9a41-37c89608b009.png)

**Comment by mtrezza** [comment]
Can you describe your issue in more detail and provide
- the Parse related code you use to save the object
- the steps to reproduce
- what your expected outcome is
- what the actual outcome is (specifically what is saved in the database)

**Comment by Berki2021** [comment]
### Parse related Code: 
https://github.com/Berki2021/JsonObjectExample

### Steps to reproduce:
1. Start the app
2. Create a User by providing a username and a password. (e.g User and password1234#)
3. Click the button "sign up".
4. You will see what I provided in the first Screenshot **1.User Object with first Adress** which is the expected Outcome and the actual outcome

5.Click "Change adress"
6.You will see what I provided in the second Screenshot **2.User Adress Object after clicking Change Adress**, which is the actual outcome. The expected outcome is the third Screenshot **3.User Adress Object expected Outcome**

**Comment by Berki2021** [comment]
### Parse related Code: / When Using JSONArray to store the adress
https://github.com/Berki2021/JSONArrayExample

Note: You have to change the app_id and the key!

### Steps to reproduce:
1. Start the app
2. Create a User by providing a username and a password. (e.g User and password1234#)
3. Click the button "sign up".

### Acual Outcome (1):
4. You will see what I provided in the first Screenshot **1.User Object with first Adress** which is the actual outcome and the expected outcome
![1 User Object with first Adress](https://user-images.githubusercontent.com/65120636/86761903-95b2fb00-c046-11ea-864b-067ca36ba62f.png)

### Steps to reproduce 2 (actual error and what I want to know):
5. Click Button "Change adress"

### Expected Outcome (2):
6. See Screenshot **3.User Adress Object expected Outcome**
![3 User Adress Object expected Outcome](https://user-images.githubusercontent.com/65120636/86762698-1c67d800-c047-11ea-8cac-0f31c8a44bb7.png)


### Actual Outcome (function has overridden the first address instead of putting another one)
7. See Screenshot **2.User Adress Object actual Outcome**
![2 User Adress Object after clicking Change Adress](https://user-images.githubusercontent.com/65120636/86761915-977cbe80-c046-11ea-9d7d-09f6284df6e9.png)

**Comment by mtrezza** [comment]
Can you please remove the comment that is obsolete?

**Comment by mtrezza** [comment]
I understand from your two previous comments, that you tried the same with `JSONObject` and with `JSONArray`.

In both cases, on sign-up the address was saved with the user object. Only when tapping the "Change Address" button, you had a non-expected outcome, is that correct?

**Comment by Berki2021** [comment]
> I understand from your two previous comments, that you tried the same with JSONObject and JSONArray. In both cases, on sign-up the address was saved with the user object as expected, only when tapping the "Change Address" button, you had a non-expected outcome. The non-expected outcome was that the new address replaced the existing address, instead of being added to the existing address.

Yes yes!! You got it! That is the EXACT problem I have.

> Your expectations of the outcome are also incorrect, according to the screenshots. If you want to add an address, you would have to add it to the existing address by modifying the existing object, instead of overwriting it.

Please for the love of god provide me an example how to achieve this in android using kotilin. I've tried using `add("adress", value)` but that does absolutely nothing. If I understand you correctly, I first have to get the object / aka access the value of the user and than add another object? I have an understanding how to possibly achieve this with an array, but not with an object..

It would be amazing if you could show me how to do this with JSONArray and JSONObject...

**Comment by mtrezza** [comment]
For field of type `Array` should be able to add the new address atomically as described in the [docs](https://docs.parseplatform.org/android/guide/#arrays):

```
user.add("address", newAddress);
```

If that doesn't work, please take a look into the logs and post the relevant entries here.

**Comment by Berki2021** [comment]
> Mind that this is not an atomic operation.
What exactly does this mean? I don't exactly got the point when to use JSONObject and when to use JSONArray. What are the key differences? Is it possible to use `put("country, _country)` when using JSONArray?

> For a field of type Array you should be able to add the new address atomically as described in the docs
Do I have to call `saveInBackground()` after `add("adress", newAdress)`?

**Comment by mtrezza** [comment]
> What exactly does this mean? I don't exactly got the point when to use JSONObject and when to use JSONArray. What are the key differences? Is it possible to use `put("country, _country)` when using JSONArray?

The relevant difference for your example is that you can modify a field of type `Array` atomically, which may be the preferred way. There are many [explanations](https://www.baeldung.com/java-atomic-variables) available online, but essentially it means that between the time that you read the address field, add a new address and save the modified list of addresses back to the database, another process could have modified the address list in the database and you would overwrite that modification.

> Do I have to call `saveInBackground()` after `add("adress", newAdress)`?

Yes, you can find an example in the [docs](https://docs.parseplatform.org/android/guide/#updating-objects).

**Comment by Berki2021** [comment]
Okay thank you very much, I will try it now. But you didn't answer me whether it is possible to use keys in Arrays. I think it is not, am I right?

**Comment by mtrezza** [comment]
>. But you didn't answer me whether it is possible to use keys in arrays. I think it is not, am I right?

Key-Vale is a concept of Objects / Dictionaries, not of arrays.

**Comment by Berki2021** [comment]
Ok, I've updated the repository and  changed the function "addAnotherAdress" in the user class. The function does NOT WORK. There are no errors in my logs, but I have seen a  problem: When using `user.addAnotherAdress(adressTwo)` there is no api call made aka no data send to the server. The observing the profiler, it says 0kb send and 0kb received. Therefore, the user address is not updated aka another one added.

Note: I've changed the name from adress to address.

**Comment by mtrezza** [comment]
If there is not even a call to Parse Server made, I suggest you refactor your code into in a single method, without going back and forth between classes to eliminate any "conceptual" issues.

After you modify an object it should be flagged as `dirty` and only with that flag the object will be saved to the server when you call `saveInBackground()`. Check, whether the User object is indeed `dirty` after changing the address.

**Comment by Berki2021** [comment]
Okay, I will. I found an interesting website as well: https://guides.codepath.com/android/Troubleshooting-Common-Issues-with-Parse

This will force me to change my User class and I think the bug comes from the class itself. I am rather confused that the official parse documents don't talk about this...

**Comment by mtrezza** [comment]
> I am rather confused that the official parse documents don't talk about this...

What do you think should be mentioned in the Parse docs?

**Comment by Berki2021** [comment]
It should be mentioned that one should not extend ParseUser like I did, which maybe causes issues like not being able to add arrays correctly... And it should be mentioned how to add other variables like address etc. to the existing ParseUser.

**Comment by mtrezza** [comment]
> It should be mentioned that one should not extend ParseUser like I did, which maybe causes issues like not being able to add arrays correctly

Subclassing `ParseUser` on Android should work fine. If you find a reproducible issue when subclassing it, please open an issue in the [Parse Android SDK](https://github.com/parse-community/Parse-SDK-Android/issues).

> And it should be mentioned how to add other variables like address etc. to the existing ParseUser.

The docs show to set a field of a Parse object. Modifying objects / arrays are programming fundamentals that are unrelated to Parse Server and therefore not part of the docs.

> In many cases I feel like the Parse docs are not complete in any way and I have to search the internet or ask questions to get any further. It is also not mentioned how to write test for the ParseObjects

It is true that the docs unfortunately lag a bit behind the functionality. If you see something missing in the docs, you are invited to open a PR and we will gladly review it.

**Comment by Berki2021** [comment]
Okay, I've tried to add another JSON Array to the current user and it is definitely a bug at parse.

> After you modify an object it should be flagged as dirty and only with that flag the object will be saved to the server when you call saveInBackground(). Check, whether the User object is indeed dirty after changing the address.

It IS Dirty after I've added another Address, but `saveInBackground()` does nothing!

Here the new repository: https://github.com/Berki2021/ParseTest_ArrayBug/tree/master/app/src

### Steps to reproduce
1. Download the repository, change app_key and client_key and start the app.
2. SignUP a new User. You will see that the user with it's given credentials was saved in the database.
3. Click the Button "change" to ADD another address to the current user.

### Expected Outcome
4. Another Address should be added to the current user.

### Actual Outcome
5. Nothing happend, the user:object was set dirty, but `saveInBackground()` didn't work.

**Comment by mtrezza** [comment]
@Berki2021 Thanks for providing your example project. Can you please post a simple code block (instead of an Android project) that includes only the required code lines to reproduce the issue?

**Comment by Berki2021** [comment]
Yes, here:

```
    // Save in Background is not executed. ParseUser is set Dirty (see discusion above)
    fun addCredential(key: String, value: Any): ParseUser = parseUser.apply {
        add(key, value)
        saveInBackground()
    }
```

This problem occurs for both arrays and and object fields.

**Comment by mtrezza** [comment]
@Berki2021 Can you please provide a full minimal example including values to demonstrate the problem? It should be just the basic steps, as few as possible, to reproduce the issue.

**Comment by mtrezza** [comment]
I'm closing this as it lacks essential information. Feel free to edit your question using the issue template and we can re-open this issue.
