### ISSUE TITLE
Middleware never is call 

### ISSUE THREAD

**Issue by pc-cesar** [parse-community/parse-server#6806]
i try use middleware https://github.com/parse-community/parse-server/blob/3bd5684f67a16ec96907b50ab5fc9daa9e4fa8e0/src/Options/Definitions.js#L243 but the serve never call my function.

**Comment by mtrezza** [comment]
I am closing this as you have already posted this in the community forum and received replies. Please avoid cross-posting.

**Comment by pc-cesar** [comment]
@mtrezza not is the same question, here i ask why parse server not call my internal middleware, and this question(https://community.parseplatform.org/t/custom-middleware/548) i ask about masterkey params and how block others ips.Has the same name because i want use Middleware for solved my problem.   

Thanks for your reply.

**Comment by mtrezza** [comment]
The implementation of your custom middleware is not a Parse Server issue.
