### ISSUE TITLE
Decouple account and session management from parse-server

### ISSUE THREAD

**Issue by vmirzoyan** [parse-community/parse-server#6847]
**Is your feature request related to a problem? Please describe.**
I use parse server as a backend API service through extensive use of cloud code functions. Over the years, my cloud code has grown significantly and supports multiple different domains of my application. I've addressed scalability issues by running multiple instances of parse server against a single mongodb database. 

At this point, I'm interested in taking on more classic "micro-service" approach by breaking out domains of my application into independent parse services _with their own dedicated database_. This will allow me scale and deploy functional areas independently. The problem, of course, is user and session management is tied directly into parse server where user, installation, and session data is expected to reside in each parse server's data store.

**Describe the solution you'd like**
Having the option of deploying a separate user, session, and installation management server would allow for creating distributed services based on parser server while still supporting parse server's authentication and access controls.

I'm curious if anyone else has considered this approach or even if this is something feasible with the current parse sever architecture.

**Comment by mtrezza** [comment]
Thank you for suggesting.

> I'm curious if anyone else has considered this approach or even if this is something feasible with the current parse sever architecture.

I'm closing this as it seems to be in an early stage of discussion about Parse Server architecture.

Discussions are better suited in our [community forum](https://community.parseplatform.org) while we expect feature requests on GitHub to be more specific.

Feel free to comment if you have any questions and we can re-open this issue.
