### ISSUE TITLE
Allow for Relational Queries on _Installation when sending push notifications 

### ISSUE THREAD

**Issue by zanderisrael** [parse-community/parse-server#6853]
I'd like to know if I can create custom push audiences by adding a relational/pointer field to the Installation class, and use the _Audience query object to filter based on the relational field.

For example link _Installation and _User classes, then:

where={"_Installation":{"__type":"Pointer","className":"_User","email":"some@email"}}

I want to make sure that this is possible, then modify parse-dashboard to allow for this type of audience to be created.

Do you know if this is possible?

**Comment by davimacedo** [comment]
You don't need to modify parse-dashboard. You can create the pointer from _Installation class to _User class and then add a condition to your push audience that filters out by this pointer.

**Comment by zanderisrael** [comment]
> You don't need to modify parse-dashboard.

Well you cant modify via Dashboard from what I have seen in the UI, you cant reach _User properties via the push UI.

**Comment by zanderisrael** [comment]
**Update:** 

I was able to create a more complex Audience by using RESTApi:

"query":"{"user":{"$inQuery":{"where":{"age":22},"className":"_User"}},"deviceType":{"$in":["ios"]}}"

**So its definitely a parse-dashboard UI limitation.**
