### ISSUE TITLE
Only the first defined cloud function is available, the rest are not found

### ISSUE THREAD

**Issue by Konovalov-Nik** [parse-community/parse-server#6863]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description
When I define 2 cloud functions with Parse.Cloud.define in main.js only the first one is responding normally. Others return
Parse error: Invalid function: "<name>"

### Steps to reproduce
The minimal main.js to reproduce will look like this 

> Parse.Cloud.define('hello1', async (req) => {
>  return 'Hey 1'
> })
>
> Parse.Cloud.define('hello2', async (req) => {
>   return 'Hey 2'
> })

### Actual Outcome
hello1 returns 'Hey 1'
hello2 returns an error Parse error: Invalid function: "hello2"

### Expected Outcome
Both should return proper values

Server
- Parse Server version: `4.3.0`
- Operating system: `container built on node:11.8.0-alpine running on MacOS`
- Local

Database
- System: `MongoDB`
- Database version: `4.4.0`
- Local

Client
Simple cURL or a call from the parse-dashboard to /functions/hello1 or /functions/hello1

### Logs
parse_1      | verbose: REQUEST for [POST] /parse/functions/hello2: {} {"method":"POST","url":"/parse/functions/hello2","headers":{"host":"0.0.0.0:1337","connection":"keep-alive","content-length":"0","x-parse-master-key":"93e2bd2f-7c9e-4570-a60c-1d429d4248c7-f15287d1-f5f8-47a9-b69e-4514c7bb9991","x-parse-application-id":"test-backend","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36","content-type":"text/plain;charset=UTF-8","accept":"*/*","origin":"http://127.0.0.1:4040","referer":"http://127.0.0.1:4040/apps/Test/api_console/rest","accept-encoding":"gzip, deflate","accept-language":"en-US,en;q=0.9,ru;q=0.8"},"body":{}}
parse_1      | error: Parse error: Invalid function: "hello2" {"code":141,"stack":"Error: Invalid function: \"hello2\"\n    at handleCloudFunction (/parse/node_modules/parse-server/lib/Routers/FunctionsRouter.js:134:13)\n    at promise.then (/parse/node_modules/parse-server/lib/PromiseRouter.js:85:20)\n    at processTicksAndRejections (internal/process/next_tick.js:81:5)"}

**Comment by davimacedo** [comment]
Can you reproduce the problem running Parse Server via CLI?
```shell
parse-server --appId APPLICATION_ID --masterKey MASTER_KEY --databaseURI mongodb://localhost/test --cloud ./cloud/main.js
```

**Comment by Konovalov-Nik** [comment]
Thanks for the suggestion, the issue was in fact in the way that the cloud code was packed into the container image. Running parse with CLI directly showed no issue.

Closing this issue.
