### ISSUE TITLE
beforeSubscribe doesnt change incoming query

### ISSUE THREAD

**Issue by maxiqsoft** [parse-community/parse-server#6866]
### Issue Description
Hi, Im trying to change the incoming query subscription with Parse.Cloud.beforeSubscribe but im still getting every column at the client. Ive tried changing the subscription query with query.equalTo too but it doesnt have any effect.
I did it the same way as here: [beforeFind](https://docs.parseplatform.org/cloudcode/guide/#find-triggers)
The intention is that some parameter needed for the right subscription shouldnt be displayed in the source code.

**Thats my Cloud code:**
```
Parse.Cloud.beforeSubscribe( 'Chat', ( request ) => {
	if ( !request.user ) {
        throw "Please login before you attempt to connect.";
    }	
	var query = request.query;
        query.select( 'message', 'username' );
	return query;
});
```

**Thats my Client code:**
```
var chat = new Parse.Query( 'Chat' );
chat.subscribe().then(subscription=>{
       subscription.on( 'open', function(){
             console.log( 'Subscription to Chat opened...' );
       });
});
```

###  Environment

Server
- Parse Server version: `4.3.0`
- Operating system: `CentOS 8`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `local`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `4.0.19`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `local`

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): `JavaScript`
- SDK version: `2.15`

**Comment by mtrezza** [comment]
Thanks for reporting.

Looking at your code, I see that you `return query;` at the end. This does not seem to be necessary according to the [beforeSubscribe example](https://docs.parseplatform.org/cloudcode/guide/#beforesubscribe). Instead it seems that by changing the `request.query` object, the change is already applied. Can you try removing the `return query;` line?

**Comment by maxiqsoft** [comment]
Ive already tried both ways. Removing the `return query` doesnt change anything. Im doing it now with ACL instead of subscription queries.

**Comment by dblythy** [comment]
@mtrezza I was able to replicate, I'll provide a PR and better test cases for mutating the request query

**Comment by mtrezza** [comment]
@dblythy Can you give a bit more details about the underlying issue?

**Comment by dblythy** [comment]
Yes, [here](https://github.com/parse-community/parse-server/blob/44015c3e351fc7cf0ac3e99bc64738d35ddc3cba/src/triggers.js#L793) in my `maybeRunSubscribeTrigger` I converted the request.query (which is previously JSON) to a Parse Query for the trigger, but after the trigger runs, I never converted it back, meaning that the [LiveQuery](https://github.com/parse-community/parse-server/blob/44015c3e351fc7cf0ac3e99bc64738d35ddc3cba/src/LiveQuery/ParseLiveQueryServer.js#L690) tries to access .where, which is undefined. Mistake on my behalf, in my usage I was just throwing out of `beforeSubscribe`, and I should've created a test case for mutating the query. Sorry @maxiqsoft! Will have a PR very shortly with a few more tests as well.
