### ISSUE TITLE
Error: Cannot find module 'apollo-server-core'

### ISSUE THREAD

**Issue by zivchen** [parse-community/parse-server#6869]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description
Parse server wont run after a fresh npm install, something to do with 'apollo-server-core'
i installed apollo-server-core manually and it worked

### Steps to reproduce
remove node_modules and do  npm i
run server crash

### Actual Outcome
crash, server wont load

### Expected Outcome
server should run

###  Environment
AWS linux
node 12.16.3 (i tried also on 12.16.1)

Server
- Parse Server version: `4.3.0`
- Operating system: `aws linux + mac OS catalina`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `AWS + local`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `4.2`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `local`

### Logs

Error: Cannot find module 'apollo-server-core'
Require stack:
- /var/app/current/node_modules/parse-server/lib/GraphQL/parseGraphQLUtils.js
- /var/app/current/node_modules/parse-server/lib/GraphQL/loaders/parseClassTypes.js
- /var/app/current/node_modules/parse-server/lib/GraphQL/ParseGraphQLSchema.js
- /var/app/current/node_modules/parse-server/lib/GraphQL/ParseGraphQLServer.js
- /var/app/current/node_modules/parse-server/lib/ParseServer.js
- /var/app/current/node_modules/parse-server/lib/index.js
- /var/app/current/dist/parseServer.js
- /var/app/current/dist/app.js
- /var/app/current/dist/server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)
    at Function.Module._load (internal/modules/cjs/loader.js:840:27)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/var/app/current/node_modules/parse-server/lib/GraphQL/parseGraphQLUtils.js:12:25)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/var/app/current/node_modules/parse-server/lib/GraphQL/parseGraphQLUtils.js',
    '/var/app/current/node_modules/parse-server/lib/GraphQL/loaders/parseClassTypes.js',
    '/var/app/current/node_modules/parse-server/lib/GraphQL/ParseGraphQLSchema.js',
    '/var/app/current/node_modules/parse-server/lib/GraphQL/ParseGraphQLServer.js',
    '/var/app/current/node_modules/parse-server/lib/ParseServer.js',
    '/var/app/current/node_modules/parse-server/lib/index.js',
    '/var/app/current/dist/parseServer.js',
    '/var/app/current/dist/app.js',
    '/var/app/current/dist/server.js'
  ]
}

**Comment by dplewis** [comment]
Can you do a clean install? Remove the node_modules folder and package-lock.json file. `npm install`

**Comment by zivchen** [comment]
@dplewis 
I tried deleting and cleaning locally and rebuilding the environment on AWS, it didn't work.
I guess that applo-server-express changed something and because we dont install apollo-server-core directly something has changed.

**Comment by mtrezza** [comment]
Can you try to deploy [parse server example](https://github.com/parse-community/parse-server-example) and see whether is runs locally and on AWS for you?

**Comment by mtrezza** [comment]
I'm closing this as it seems to be resolved. Feel free to comment if you have any questions and we can re-open this issue.

**Comment by robross0606** [comment]
We're now seeing this problem.  I _really_ wish someone had documented how this was fixed.

**Comment by Wizyma** [comment]
@robross0606  same here it just popped after i updated `apollo-server@3.0.0` to `apollo-server@3.3.0`

**Comment by mtrezza** [comment]
@Wizyma How did you update it? `apollo-server` is not a dependency in package.json.

**Comment by Wizyma** [comment]
Hello @mtrezza ,
i updated it by updating apollo-server iteself (wich apollo-server-core is a dependency) but i think my comment should be in the apollo-server instead of here ! 
Sorry for the inconvenience !

**Comment by mtrezza** [comment]
Thanks, if you open an issue there maybe link to this issue here to keep everyone in the loop.
