### ISSUE TITLE
Live Query not active in Back4App

### ISSUE THREAD

**Issue by 7cold** [parse-community/parse-server#6873]
![image](https://user-images.githubusercontent.com/59493948/90804001-fabd6a00-e2ef-11ea-881b-1c8f0f0a9136.png)

"Please reach out us on chat in order to enable this feature for your app." Message error

**Comment by davimacedo** [comment]
Could you please [open a ticket](https://help.back4app.com/hc/en-us/requests/new) at Back4App?
