### ISSUE TITLE
In afterSave, when creating a new object, dirty(:key) returns always 'false'

### ISSUE THREAD

**Issue by Cloudtrackers** [parse-community/parse-server#6874]
### New Issue Checklist

- [ ] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [ ] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [ ] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [ ] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description
Server: 4.3.0
Database: Mongo 4.0,

### Steps to reproduce
* Setup a beforeSave hook for some class
* Save an object to the same class
* look on the following sample

`Parse.Cloud.afterSave("Profile", async (req) => {
  let token = { sessionToken: req.user.getSessionToken() };
 console.log("-> ", req.original, req.object.dirty("isActive"));
});`

### Actual Outcome
req.object.dirty("keyname"); always return false than actual result.

### Expected Outcome
if the particular key attribute value is changed, 'req.object.dirty("keyname");' should be true else false.

###  Environment
Server: 4.3.0
Database: Mongo 4.0,

Server
- Parse Server version: 4.3.0
- Operating system: Mac OS
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): local

Database
- System (MongoDB or Postgres): MongoDB
- Database version: 4.0
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): local

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): JavaScript
- SDK version: 2.15.0

**Comment by dplewis** [comment]
I believe this is proper functionality. Saving an object clears dirty keys. If you want to check dirty keys try `beforeSave`.

**Comment by Cloudtrackers** [comment]
> I believe this is proper functionality. Saving an object clears dirty keys. If you want to check dirty keys try `beforeSave`.

In the case of Updating the value,  dirty keys always returns empty array.

**Comment by dplewis** [comment]
Can you write a failing test [here](https://github.com/parse-community/Parse-SDK-JS/blob/master/integration/test/DirtyTest.js). This will help us replicate your issue.
