### ISSUE TITLE
Files are not found on 4.3.0

### ISSUE THREAD

**Issue by Samigos** [parse-community/parse-server#6881]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description

I updated my server from `2.8.4` to `4.3.0` and I immediately realized that none of the images loaded anymore. (the images are stored in mongo)

I dug in the `fs.files` and `fs.chunks` and I saw that all files are intact! So with the @davimacedo's suggestion, I downgraded to `4.2.0` and now everything works fine!

This is my server setup;

```
var api = new ParseServer({
    databaseURI: databaseUri || 'mongodb://',
    cloud: './cloud-code-repository/main.js',
    appId: process.env.APP_ID || '' ,
    masterKey: process.env.MASTER_KEY || '' ,
    fileKey: 'b5528d30-...',

    serverURL: process.env.SERVER_URL || 'http://ip:1337/parse' , 
    liveQuery: {
       classNames: ['Message', 'ChatRoom'] // List of classes to support for query subscriptions
    },

    publicServerURL: 'http://ip:1337/parse'
});
```

###  Environment

Server
- Parse Server version: `4.3.0`
- Operating system: `Ubuntu 18.04.1`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `Digital Ocean`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `4.0.2`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `Digital Ocean`

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): `iOS & Android`

### Logs

```
0|index  | Error: Unsupported state or unable to authenticate data
0|index  |     at Decipheriv.final (crypto.js:183:26)
0|index  |     at GridFSBucketReadStream.stream.on (/root/parse-server-example/node_modules/parse-server/lib/Adapters/Files/GridFSBucketAdapter.js:113:78)
0|index  |     at emitNone (events.js:106:13)
0|index  |     at GridFSBucketReadStream.emit (events.js:208:7)
0|index  |     at endReadableNT (_stream_readable.js:1064:12)
0|index  |     at args.(anonymous function) (/usr/local/lib/node_modules/pm2/node_modules/event-loop-inspector/index.js:138:29)
0|index  |     at _combinedTickCallback (internal/process/next_tick.js:139:11)
0|index  |     at process._tickDomainCallback (internal/process/next_tick.js:219:9)
```

**Comment by dplewis** [comment]
@cbaker6 Can you have a look at this? I think its an issue with https://github.com/parse-community/parse-server/pull/6765

**Comment by cbaker6** [comment]
My guess would be because `fileKey: 'b5528d30-...' is present so it’s attempting to decrypt the files with that key. What happens if you remove `fileKey`?

**Comment by Samigos** [comment]
> In parse-server 4.3 since `fileKey: 'b5528d30-...` is present when initializing the ParseServer, it’s attempting to decrypt the files with that key. Removing `fileKey` should fix the issue.
> 
> If you want to encrypt the files with a fileKey, see the details in the PR @dplewis referenced.

So I should remove it altogether?

**Comment by cbaker6** [comment]
@Samigos yes (or comment out and save for later), `fileKey` the way you are using it is legacy parse.com. The aforementioned PR repurposed the use of `fileKey` as it wasn't being used by parse server anymore up to 4.3. I think what I mentioned about legacy parse is in the parse documentation somewhere...

**Comment by davimacedo** [comment]
@dplewis @TomWFox @mtrezza Should we mention that somewhere in the release notes and/or docs? It is actually a breaking change.

**Comment by mtrezza** [comment]
Agree, this should be in the docs.

**Comment by TomWFox** [comment]
Seems like it should be in the release notes at least.
