### ISSUE TITLE
MatchesQuery always returns Zero results in JS-SDK  only  (works on iOS)

### ISSUE THREAD

**Issue by dipeshparashar** [parse-community/parse-server#6883]
The same code works in Swift but does not in JS. Am i doing anything wrong here, or is there a real issue in JS-SDK

**Class Structure**
   **_Order_** Class contains relation - **_products_**
   **_Product_** Class contains column named - **_stage_**

**Query I need to make**
I need orders with products in stage named '_Requested_'

**Swift Code- Works**
```
let orderQuery = PFQuery(className:"Order")

let productQuery = PFQuery.init(className: "Product")
productQuery.whereKey("stage", equalTo: 'Requested')

orderQuery.whereKey("products", matchesQuery: productQuery)
orderQuery.findObjectsInBackground()   // Gives array of Results

```

**JS  Code- DOES NOT WORK**
```
var orderQuery = new Parse.Query(OrderClass);

var productQuery = new Parse.Query(ProductClass);
productQuery.equalTo("stage", 'Requested)

orderQuery.matchesQuery("products", productQuery)
orderQuery.find()   // Returns Empty Array always

```

**Comment by mtrezza** [comment]
Thanks for reporting. To report an issue, please use the issue template provided when you create an issue.

**Comment by mtrezza** [comment]
I'm closing this as it lacks essential information. Feel free to edit your question using the issue template and we can re-open this issue.
