### ISSUE TITLE
Parse cluster not working properly

### ISSUE THREAD

**Issue by simonegiacco** [parse-community/parse-server#6894]
I'm trying to start parse server in a cluster of 3 instances (4 cores, so N - 1)

Setting the "cluster" parameter when creating `new ParseServer()` is not working
I tried with an app using parse-server@2.8.4 and with a clean installation of parse-server-example using latest parse-server without success;

```javascript
var api = new ParseServer({
  databaseURI: databaseUri || 'mongodb://localhost:27017/dev',
  cloud: process.env.CLOUD_CODE_MAIN || __dirname + '/cloud/main.js',
  appId: process.env.APP_ID || 'myAppId',
  cluster: 3, //. <==== HERE! also tried cluster:true
  masterKey: process.env.MASTER_KEY || '',
  serverURL: process.env.SERVER_URL || 'http://localhost:1337/parse'  
});
```

Using this setting, `ps -aux | grep node` shows one node instance

I've tried with parse-server CLI and the clustering is working properly:

```bash
parse-server --appId X --masterKey X --databaseURI mongodb://localhost:27017/dev --publicServerURL http://localhost:1337/parse  --cluster=3
```

Using this command, `ps -aux | grep node` shows three node instances.

Is this a bug or am I doing something wrong?

**Comment by mtrezza** [comment]
> Setting the "cluster" parameter when creating new ParseServer() is not working
> I've tried with parse-server CLI and the clustering is working properly

This is expected and it may be more obvious when you think about it this way:

- Starting Parse Server via the CLI `parse-server --cluster=true ...` does not immediately create and start a Node.js Parse Server instance. It is merely telling the Parse CLI that you want to launch a Parse Server instance. The CLI acts as an intermediary and looks at the `cluster` option to launch multiple Parse Server instances.

- Starting Parse Server via Node.js `const api = new ParseServer(...); express().use('/parse', api);` means you are directly creating and launching a Parse Server instance. There is no intermediary who looks at the `cluster` option. So it would be up to you to launch multiple clusters using the [Node.js cluster package](https://nodejs.org/api/cluster.html#cluster_cluster) which provides an example.

@dplewis Just to make sure, did I get this right?

**Comment by TomWFox** [comment]
I'm closing this as there has been no further response, let us know if you still have any questions/issues.

**Comment by rdhelms** [comment]
@mtrezza @TomWFox Just to clarify - the conclusion here was that using the `cluster` option has no effect when using `new ParseServer(...)`?

Could that be updated somewhere in the docs? The [ParseServerOptions docs](http://parseplatform.org/parse-server/api/master/ParseServerOptions.html) mention the `cluster` option in a way that certainly implies that it does something when used with `new ParseServer()`, but attempting to understand its impact is what led me here.

**Comment by mtrezza** [comment]
Such a note would be welcome. The `cluster` option is in the Parse Server Options docs because usually (probably all other) options can be set either via the Parse Server CLI or via the Parse Server object. `cluster` is an exception and can only be set via the CLI, as it needs the CLI intermediary logic to spin up multiple Parse Server instances.

Please feel free to add a comment to the options definitions in `Definitions.js`. We do not have a way in the docs to specify "CLI only" options, so a comment there should be fine.
