### ISSUE TITLE
GraphQL playground throws "Server cannot be reached" error

### ISSUE THREAD

**Issue by 185driver** [parse-community/parse-server#6897]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description

When deploying a minimal parse-server project to heroku utilizing graphql, the playground throws a "Server cannot be reached" error. The parse server itself is functional using the rest api, but not the graphql playground.

### Steps to reproduce

1. Clone my repro repo: [https://github.com/185driver/parse-graphql-issue](https://github.com/185driver/parse-graphql-issue)
2. Deploy to heroku dyno using instructions in README.md
3. Navigate to the serverURL/playground and note the error.

### Actual Outcome

1. Playground URL shows :"Server cannot be reached".
![image](https://user-images.githubusercontent.com/1835454/92533531-4b8df780-f1f8-11ea-8e24-8caf07e1bb0b.png)
2. Heroku logs --tail shows:
```cmd
error: Error: Expected RoleConnection to be a GraphQL nullable type.
app[web.1]: at assertNullableType (/app/node_modules/parse-server/node_modules/graphql/type/definition.js:425:11)
app[web.1]: at new GraphQLNonNull (/app/node_modules/parse-server/node_modules/graphql/type/definition.js:377:19)
app[web.1]: at Object.load (/app/node_modules/parse-server/lib/GraphQL/loaders/parseClassQueries.js:109:13)
app[web.1]: at /app/node_modules/parse-server/lib/GraphQL/ParseGraphQLSchema.js:109:25
app[web.1]: at Array.forEach (<anonymous>)
app[web.1]: at ParseGraphQLSchema.load (/app/node_modules/parse-server/lib/GraphQL/ParseGraphQLSchema.js:107:71)
app[web.1]: at processTicksAndRejections (internal/process/task_queues.js:97:5)
app[web.1]: at async ParseGraphQLServer._getGraphQLOptions (/app/node_modules/parse-server/lib/GraphQL/ParseGraphQLServer.js:61:17)
app[web.1]: at async /app/node_modules/parse-server/lib/GraphQL/ParseGraphQLServer.js:99:86
```
3. Dev tools console shows:
![image](https://user-images.githubusercontent.com/1835454/92533745-b0e1e880-f1f8-11ea-944f-0a272fc519aa.png)

### Expected Outcome

The playground should not throw an error.

###  Environment

```cmd
    "express": "4.17.1",
    "parse-server": "4.3.0"
```

Server
- Parse Server version: `4.3.0`
- Operating system: `Windows 10`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `Heroku`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `4.2.8`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `MongoDB Atlas`

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): `N/A`
- SDK version: `N/A`

### Additional Info
If I deploy the parse-dashboard in combination with parse-server, I get the same results.
1. Parse server works and is accessible in the browser, but if I navigate to the GraphQL API Console, I get the same errors.

If I deploy using PostGres instead of MongoDB, I get the same results.

**Comment by davimacedo** [comment]
Thanks for reporting. Do you have the same result if you run it in your local machine?

**Comment by 185driver** [comment]
I had not tested it locally, so thanks for that suggestion. As it turns out, doing so led to what appears to be the main issue for me and its resolution. I use `yarn` (1.x) rather than `npm`, so by installing locally, a `yarn.lock` file was created. After that, deploying locally works great.  

Additionally, deploying to heroku with the yarn lock file as part of the deploy resolved the issue there too. The graphql playground now works both locally and on heroku. I also tested this scenario using parse-dashboard and it resolved my issue there with the GraphQL API Console (same error earlier). 

Next, I removed the `yarn.lock` file and deployed again. Same error as before, so no joy.

Lastly, I used `npm install` so as to create a `package-lock.json` file instead of the yarn version.  The deploy failed both locally and on heroku in terms of using the GraphQL server and playground, although parse-server itself still works.

To sum up, it does not appear that parse-server itself is causing the issue, nor is heroku. The culprit appears to be that the npm installs are mishandling something (related to graphql dependencies or versions, maybe?) while yarn is handling things better. For my part, this issue can be closed since the error is no longer throwing, but if my experience is not unique, maybe a mention in the docs of this problem or solution would be helpful to others. Thanks for your help.

**Comment by davimacedo** [comment]
Thanks for the detailed reporting. I will keep an eye on that.

**Comment by cjbland** [comment]
FWIW I am having this exact issue running `parse-server` via Express with GraphQL. If it makes a difference I have the "engines" in my `package.json` set to:

```
"engines": {
  "node": "~14",
  "npm": "6.13.x"
}
```

I have a `Dockerfile` and I deploy to AWS ECS and am using `npm` when building the container. Any thoughts would be appreciated.
