### ISSUE TITLE
2FA with Google Authenticator

### ISSUE THREAD

**Issue by REPTILEHAUS** [parse-community/parse-server#6906]
It is a vital part of most mission critical applications nowadays, I think it makes sense that it is part of parse server and from reading comments/issues etc it has been requested a lot, this one seems to be the closest it has come to being integrated albeit dropped for security hazards https://github.com/parse-community/parse-server/issues/4024

**Comment by mtrezza** [comment]
I am closing this as it seems to be a continuation of https://github.com/parse-community/parse-server/issues/4024. Let's continue the discussion there, I will re-open the issue.
