### ISSUE TITLE
Unknown directive "@namespace" error

### ISSUE THREAD

**Issue by 185driver** [parse-community/parse-server#6913]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description

An error is thrown on build if I use the @namespace directive in custom schema.

### Steps to reproduce

```
const parseGraphQLServer = new ParseGraphQLServer(
  parseServer,
  {
    graphQLPath: '/graphql',
    graphQLCustomTypeDefs: gql`
    extend type Query {
      custom: Custom @namespace
    }
    type Custom {
      hello: String @resolve
    }
  `,
    playgroundPath: '/playground',
  },
);
```
1. Initialize a ParseServer using the code found in @davimacedo 's PR found at [https://github.com/parse-community/parse-server/pull/5821#issue-298733711](https://github.com/parse-community/parse-server/pull/5821#issue-298733711)
1. Open the GraphQL API console. The error will be logged in the dev console.

### Actual Outcome

An `Unknown directive "@namespace"` error in the console.

### Expected Outcome

I thought it would not error out.

###  Environment

Server
- Parse Server version: `4.30`
- Operating system: `Win 10`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `localhost`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `4.2.8`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `MongoDB Atlas`

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): `JS`
- SDK version: `Cloud Code`

### Logs

```
error: Error: Unknown directive "@namespace".
    at assertValidSDLExtension (C:\Mypath\node_modules\graphql\validation\validate.js:124:11)
    at Object.extendSchema (C:\Mypath\node_modules\graphql\utilities\extendSchema.js:77:43)
    at extensions.forEach.extension (C:\Mypath\node_modules\@graphql-tools\stitch\index.cjs.js:862:28)   
    at Array.forEach (<anonymous>)
    at stitchSchemas (C:\Mypath\node_modules\@graphql-tools\stitch\index.cjs.js:861:16)
    at ParseGraphQLSchema.load (C:\Mypath\node_modules\parse-server\lib\GraphQL\ParseGraphQLSchema.js:212:56)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by mtrezza** [comment]
@Moumouls Since you are a GraphQL expert, do you have any comment on this?

**Comment by davimacedo** [comment]
@185driver There is no `@namespace` directive implemented by default in Parse Server GraphQL. Could you please explain what's your goal with this directive? Maybe it's something that can be added to the project.

**Comment by Moumouls** [comment]
@davimacedo, you are right, @185driver , directives were designed to customize and enhance a GraphQL Schema.
Some default directives exists like: `@deprecated` , `@skip`. In case of parse server we added `@resolve` (designed to call a Parse Cloud function as a resolver) and `@mock` to allow developers to mock a response when they need the API Schema but do not have the resolver/clound function ready.

`@namespace` seems to be a custom directive, may be you see this directive into a GraphQL example ?

**Comment by Moumouls** [comment]
Ohhhh i see @185driver , `@namespace` was removed from API it's just a resolve that return an empty object `() => ({})`. After namespace i suggested to implement `@mock` that replace `@namespace` you can find some example on the PR from @davimacedo : https://github.com/parse-community/parse-server/pull/5836

**Comment by Moumouls** [comment]
@185driver If everything is ok for you, i let you close this issue

**Comment by 185driver** [comment]
Oh, copy that. That would explain the error, ha. Thank you.
