### ISSUE TITLE
LiveQuery _User and Email Verification

### ISSUE THREAD

**Issue by Danaru87** [parse-community/parse-server#6921]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description
Hello,

We have a problem on Email Validation.

In our client, we listen a liveQuery on _User to detect emailVerified value changes.

But, when we use email verification link, the value change but liveQuery doesn't receive the event.

Same problem as here: #3850

### Actual Outcome

The LiveQuery update/enter events are not triggered

### Expected Outcome
The LiveQuery update/enter event to be triggered when the user verifies their email

###  Environment
Server
- Parse Server version: `4.3.0`
- Operating system: `Linux`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `Local and Sloppy.io host`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `3.6.19-6`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `Local and Sloppy.io`

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): `Flutter`
- SDK version: `1.0.27`

**Comment by davimacedo** [comment]
It would be a good addition in my opinion. Is that something that you would be willed to work on?

**Comment by Danaru87** [comment]
It seems quite complicated to me. I have the impression that this requires a thorough knowledge of the existing code and the functioning of Parse Server.
Moreover, I am far from being an expert on Node and JS.

I will try something but I am not sure I will get a satisfactory result.

**Comment by davimacedo** [comment]
Give it a try and let me know if you need any help.

**Comment by Danaru87** [comment]
I do this modification, it works on my pc and on our server.

https://github.com/parse-community/parse-server/pull/6930
