### ISSUE TITLE
Parse Server startup crash : Cannot find module 'graphql'

### ISSUE THREAD

**Issue by Rafarel** [parse-community/parse-server#6924]
### Issue Description

Hello there, I'm working on a  parse-server project. I'll have to talk a bit about parse-dashboard but it is mainly related to parse-server. The issue is reproductible on the last version of parse-server, but I'm using 3.9 because it is a requirement of my client at the moment.

I removed the parse-dashboard form the package.json dependencies of the project because the parse-dashboard is no longer instantiated by the same node application. Then I made a clean install of `node_modules` by doing a `npm install`.

When I start the node application I have now the following error : 

```
Error: Cannot find module 'graphql'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/user/Git/project/node_modules/graphql-upload/lib/GraphQLUpload.js:6:16)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
```
I don't understand because : 
- I'm not using graphql in my scripts
- The graphql dependency is in the parse-server parckage.json

### Steps to reproduce

Just install parse-server and use it as an express middleware.

Here is my package.json 

```
{
  "name": "my-app",
  "version": "1.2.0",
  "dependencies": {
    "body-parser": "1.19.0",
    "express": "4.17.1",
    "parse": "2.16.0",
    "parse-server": "3.9.0",
    "request": "2.88.2"
  },
  "scripts": {
    "start": "node app.js"
  }
}
```
The issue can be fixed by adding `"graphql": "14.2.1"` to my package.json dependencies but it sounds a bad fix to me and I would like to understand what happened here.

###  Environment

Server
- Parse Server version: `3.9.0`
- Operating system: `Ubuntu 16.04`
- Node 9.3.0
- npm 5.5.1
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `Both Local and Remote VPS`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `3.2`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `reproductible on every database`

**Comment by Moumouls** [comment]
@Rafarel  unfortunately we do not support old versions of Parse Server since it required too much energy for a volunteer open source team. I can only advice you to update the `parse-server` package to fix this one or use your current workaround :)

**Comment by Rafarel** [comment]
@Moumouls It is reproductible on the lastest parse-server version, I just found it on 3.9 that's all.

**Comment by Rafarel** [comment]
@Moumouls I think I understood why, I needed to delete a regenerate the package-lock to fix the issue. Have you any good advice regarding how to update the package-lock.json when you remove a package ? Thanks :+1:

**Comment by Moumouls** [comment]
After removing a package from `package.json` you need to `npm i` or `yarn` to tell to the package manager that you package list has changed. And in common use cases `npm` or `yarn` just remove/install/update packages based on your `package.json`, it's a stateless system.

**Comment by Moumouls** [comment]
It's weird, your npm installation is not normal

**Comment by Rafarel** [comment]
@Moumouls 
I installed npm with nvm, I'm using the same version that is installed on my client production server so it's 5.5.1 and node is 9.3.0
I just want to have a `package-lock.json` file that match my `package.json` but no file is generated when I do a `npm i`.
npm config is set to default I didn't change anything except save=false because I don't want npm to do --save every time I do an install

**Comment by Rafarel** [comment]
@Moumouls 
Even with a newer version of npm I can't have a new package-lock.json file until I did `npm install --package-lock-only`.
I think I should upgrade node and npm on the production server but do you know any parse-server breaking change regarding this kind of update ? We are 9.3.0 for node and it would be great to upgrade to a 14.x don't you think ?

**Comment by nstrelow** [comment]
I have the same problem on the latest docker image.
Any way to fix this?
