### ISSUE TITLE
query.includeAll() does not include array of Pointers

### ISSUE THREAD

**Issue by Rafarel** [parse-community/parse-server#6926]
I have a Parse.Object `A` that have a `children` property that is an array of Pointers to reference other objects of type `B`.

When I do the following, it does not send me back the full `B` objects contained in the `children` property, I mean all B.get("something") returns `undefined`

```
const query = new Parse.Query("A");
query.includeAll();
return await query.find({ sessionToken: user.getSessionToken() }); 
```
But when I do it like that it works fine ...

```
const query = new Parse.Query("A");
query.include("children");
return await query.find({ sessionToken: user.getSessionToken() }); 
```

So maybe `query.includeAll` is broken or I missed something ?

I'm using parse-server 4.3.0

**Comment by mtrezza** [comment]
To report an issue, please use the issue template provided when you create an issue.

**Comment by dplewis** [comment]
Include all only works for type `Pointer` fields. See [here](https://github.com/parse-community/parse-server/blob/master/src/RestQuery.js#L716). You can try to add type `Array` and see if it fixes your issue.

**Comment by mtrezza** [comment]
I'm closing this as it seems to be resolved. Feel free to comment if you have any questions and we can re-open this issue.
