### ISSUE TITLE
Upload serialization unsupported when using AWS S3 when add schema.graphql in config setup

### ISSUE THREAD

**Issue by ptthien1012** [parse-community/parse-server#6935]
My project is using Graphql, parse server and parse server cloud code. Im using AWS S3 to upload Images by using filesAdapter with module @parse/s3-files-adapter and it work perfect. But My project using some custom mutation so I need to add custom file Schema.graphql like this in config file of parse server.
Code like this: “graphQLSchema”: “./schema.graphql”.
Then I test to using Mutation upload file it don’t work like usual and it show the error like this.(BTW I’m using FireCamp, it’s a tool to help me write graphql code easier).
image

This is a code of Schema.graphql
![image](https://user-images.githubusercontent.com/67034592/95658807-6af5a880-0b47-11eb-9835-519f4d30eeb5.png)

Type declare
type SendVerificationCodePayload {
clientMutationId: String
status: Int!
messages: String!
}
type ConfirmVerificationCodePayload {
clientMutationId: String
status: Int!
messages: String!
data: User!
}
type User {
objectId: String!
phoneNumber: String!
}

type checkrCandidatesPayload {
messages: String!
}

Input declare
input sendVerificationCodeInput {
"Phone Number"
phoneNumber: String!
clientMutationId: String
}
input confirmVerificationCodeInput {
"Phone Number"
phoneNumber: String!
"Verify Code"
verifyCode: String!
clientMutationId: String!
}
input checkrCandidatesInput {
phone: String!
}
extend type Mutation {
"Send Verify code to login or register"
createSendVerificationCode(
input: sendVerificationCodeInput
): SendVerificationCodePayload @resolve(to: "sendVerificationCode")
"Send Verify code to login or register"
createConfirmVerificationCode(
input: confirmVerificationCodeInput
): ConfirmVerificationCodePayload @resolve(to: "confirmVerificationCode")
createCheckrCandidates(input: checkrCandidatesInput): checkrCandidatesPayload
@resolve(to: "checkrCandidates")
}

**Comment by mtrezza** [comment]
Thanks for reporting. To report an issue, please use the issue template provided when you create an issue.

**Comment by ptthien1012** [comment]
yes I will update this is my first time I rase issues

**Comment by mtrezza** [comment]
I'm closing this as it does not use the issue template provided when creating an issue. Please edit your initial post using the issue template and we can re-open this issue.
