### ISSUE TITLE
VK authentication doesn't work

### ISSUE THREAD

**Issue by chikchik** [parse-community/parse-server#6936]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description

VK authentication doesn't work properly, because in source code used deprecated version of api (v5.8).
https://github.com/parse-community/parse-server/blob/master/src/Adapters/Auth/vkontakte.js: 14

On this page description of actual versions of api (strongly recommended v5.124)
https://vk.com/dev/constant_version_updates

It is a critical bug! Because I need to use VK auth on back4app, but I can't/.

### Steps to reproduce

No need to reproduce, just need to fix version of api in requests.

### Actual Outcome

user_id and access_token are always valid.
Respose always returned 'Vk auth is invalid for this user.' 

### Expected Outcome

Authentication without error.

###  Environment

Server
- Parse Server version: 3.10.0
- Operating system: Windows 10
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): back4app

Database
- System (MongoDB or Postgres): MongoDB
- Database version: N/A
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): MongoDB

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): Unity via rest api
- SDK version:

**Comment by mtrezza** [comment]
Thank you for reporting. Well done, you have already identified the issue. Would you want to submit a PR?

**Comment by chikchik** [comment]
> Note that the version needs to be updated as you correctly pointed out, but the authentication should not fail yet, because it is not Oct 14. You may want to verify that there is no other issue in your code.

But, unfortunately, it happening.
If you make direct request from browser with same parameters (user_id and access_token) and version 5.8 you'll get error.

if replace the version with at least 5.21 than no errors.

Thank you.

**Comment by mtrezza** [comment]
Good that you found that out, so VK retired the 5.8 API earlier than documented.

Feel free to open a parse server PR and let me know if you need any guidance on how to do that.

**Comment by chikchik** [comment]
I dont't know how to make pull requests, because i'm stupid noob ).
Maybe I need any guidance on how to do that.

**Comment by mtrezza** [comment]
The [Contributing Guide](https://github.com/parse-community/parse-server/blob/master/CONTRIBUTING.md) should help.

**Comment by gadgetreviews** [comment]
I have problems with vk login. I am not sure if I am doing something wrong or there is a bug. This case still open for 10 months. Is this bug fixed? Or my code has problems? Thanks for help

I want to login with vk with this code but I get following error message:

```
I/flutter (31767): ╭-- Parse Response
I/flutter (31767): Class: _User
I/flutter (31767): Function: ParseApiRQ.loginWith
I/flutter (31767): Status Code: 252
I/flutter (31767): Type: UnsupportedService
I/flutter (31767): Error: This authentication method is unsupported.
I/flutter (31767): ╰-- 
I/flutter (31767):  
I/flutter (31767): Logged in failed
```

```
      final ParseResponse response = await ParseUser.loginWith(
        'vkontakte', {
          "vkontakte": {
            "id": data.settings.vkUserId!,
            "access_token": data.settings.vkAccessToken!
          }
        },
      );

      if (response.success) {
        // User is logged in, test with ParseUser.currentUser()
        ParseUser currentUser = await ParseUser.currentUser();
        print("Logged in success:");
        print("Logged in success: sessionToken: " + currentUser.sessionToken!);
        print("Logged in success: username: " + currentUser.username!);
      } else
        print("Logged in failed");

```

**Comment by mtrezza** [comment]
@chikchik Would you be interested in making a PR? We have a [blog article](https://blog.parseplatform.org/learn/tutorial/community/nodejs/2021/02/14/How-to-start-contributing-to-Parse-Server.html) for first time contributors that is maybe less "technical" than the contribution guide.

**Comment by gadgetreviews** [comment]
I have similar problems with current version. Currently latest VK API version is 5.131 and 5.124 is used in parse server. 5.124 is not too old, but I replaced 5.124 with 5.131 in parse server code in locally, and restarted parse server but it did not help and I still get "Vk auth is invalid for this user." error. Several weeks ago, same code and same configuration was working fine, but now it does not.

I get following error when I try to run this flutter code: 
```
var authData = {
	"id": vkUserId,
	"access_token": vkAccessToken,
};

final ParseResponse response = await ParseUser.loginWith(
        "vkontakte", authData,
      );
```
```
I/flutter ( 9656): ╭-- Parse Response
I/flutter ( 9656): Class: _User
I/flutter ( 9656): Function: ParseApiRQ.loginWith
I/flutter ( 9656): Status Code: 101
I/flutter ( 9656): Type: ObjectNotFound
I/flutter ( 9656): Error: Vk auth is invalid for this user.
I/flutter ( 9656): ╰-- 
```

Anyone else having same problem or I just made a mistake in my configuration or code?

Thanks for help

PS: I am using flutter and flutter_login_vk plugin for this project.

**Comment by mtrezza** [comment]
@gadgetreviews We do not investigate issues with a modified version of Parse Server, so I suggest you try to reproduce the issue with the latest official version of Parse Server (and its vk auth adapter). From the issue description by @chikchik it seems that the vk auth adapter simply needs to be adapted to the latest VK API. Only changing the API endpoint version probably won't help as the auth adapter itself may require adaptation.

To fix this, you could look into the changes of the API version and adapt the Parse Server VK auth adapter and its tests in `AuthenticationAdapters.spec.js` to work with the latest API. The process would be to determine whether this issue also exists with the `alpha` branch (presumably yes since the VK auth adapter has not changed). If it does, we will consider backporting the fix to the 4.x. branch.

**Comment by gadgetreviews** [comment]
I don't know how to proceed. Let me explain my problem in more detailed and share my code.
I am developing a mobile app with Flutter as front end and parse server as back end. I am using flutter_login_vk plugin to communicate with vk api.

Several weeks ago I tried login to vk with flutter_login_vk plugin v1.0.0 and it was working fine. Yesterday I upgraded flutter_login_vk plugin to v2.0.1 and I get this error log from parse-server:
```
I/flutter ( 9656): ╭-- Parse Response
I/flutter ( 9656): Class: _User
I/flutter ( 9656): Function: ParseApiRQ.loginWith
I/flutter ( 9656): Status Code: 101
I/flutter ( 9656): Type: ObjectNotFound
I/flutter ( 9656): Error: Vk auth is invalid for this user.
I/flutter ( 9656): ╰-- 
```
This is my simplified code in flutter:
```
void vkLogin() async {
    vk = VKLogin();
    await vk.initSdk();
    final res = await vk.logIn(scope: [
      VKScope.email,
      VKScope.photos,
    ]);
    if (! res.isError) {
      print("LoginView: vkLogin not error");
      final loginResult = res.asValue!.value;
      if (! loginResult.isCanceled) {
        print("LoginView: vkLogin not cancelled");
        var accessToken = loginResult.accessToken;
        vkAccessToken = accessToken!.token;
        vkUserId = accessToken.userId;
        await vkLoginWithToken();
      } else {
        print("Login cancelled");
      }
    } else {
      print("Login failed");
    }
}

Future<void> vkLoginWithToken() async {
    print("LoginView: vkLoginWithToken");
    if (vkAccessToken == null) return;
    if (await vk.isLoggedIn) {
      email = await vk.getUserEmail();
      var profile1 = await vk.getUserProfile();
      var profile = await profile1.asFuture;
      firstName =  profile!.firstName;
      lastName =  profile.lastName;
      pictureUrl = profile.photo200!;
      // Login to parse with vk
      var authData = {
        "id": vkUserId!,
        "access_token": vkAccessToken!
      };
/////////////
// I get error here
// response.success is false
////////////
      final ParseResponse response = await ParseUser.loginWith(
        "vkontakte", authData,
      );
      if (response.success) {
        // User is logged in, test with ParseUser.currentUser()
        currentUser = await ParseUser.currentUser();
      } else {
        print("Login failed");
      }
    } else {
      print("Unexpected error");
    }
}
```
I am not sure if it is related to parse-server or flutter_login_vk plugin. So I reported this problem both on parse-server and flutter_login_vk plugin github pages.

I get error log from parse server when ```ParseUser.loginWith``` was executed. And ```response.success``` returns as ```false```.

How should I proceed? 
Thanks for help.

**Comment by mtrezza** [comment]
> So I reported this problem both on parse-server and flutter_login_vk plugin github pages.

Please post the link when cross-posting, to avoid unnecessary work on either side.

> Several weeks ago I tried login to vk with flutter_login_vk plugin v1.0.0 and it was working fine. Yesterday I upgraded flutter_login_vk plugin to v2.0.1 and I get this error log from parse-server:

If you downgrade to flutter_login_vk plugin v1.0.0 does it work? If so, you'd have to look at their changelog, because 2.0.1 is a major version jump and may contain a breaking change. That breaking change may cause an incompatibility with Parse Server.

**Comment by gadgetreviews** [comment]
> > So I reported this problem both on parse-server and flutter_login_vk plugin github pages.
> 
> Please post the link when cross-posting, to avoid unnecessary work on either side.
> 
> > Several weeks ago I tried login to vk with flutter_login_vk plugin v1.0.0 and it was working fine. Yesterday I upgraded flutter_login_vk plugin to v2.0.1 and I get this error log from parse-server:
> 
> If you downgrade to flutter_login_vk plugin v1.0.0 does it work? If so, you'd have to look at their changelog, because 2.0.1 is a major version jump and may contain a breaking change. That breaking change may cause an incompatibility with Parse Server.

If I downgraded to 1.0.0, it did not work but this time I can't even start the app. App crashes as soon as opens. 

This is the link that I opened case at flutter_login_vk plugin:

https://github.com/Innim/flutter_login_vk/issues/17

**Comment by mtrezza** [comment]
Thanks; it's interesting that you say that the project was working fine some weeks ago. Did you change anything since then, the Parse Server version? Maybe try a fresh new minimum-example project. You can also try to delete node_modules and package-lock.json.

**Comment by gadgetreviews** [comment]
I tested the same code with iOS simulator and it worked without any problems. I guess in this case the problem should not be related to parse server. I think it should be with flutter_login_vk plugin. 

What do you think? Are there any differences between iOS and Android from parse-server's point of view?

**Comment by gadgetreviews** [comment]
This problem occurs only at android devices, and does not occur at iOS devices.

**Comment by mtrezza** [comment]
> I tested the same code with iOS simulator and it worked without any problems. I guess in this case the problem should not be related to parse server.

Good investigation! So I assume we can close this issue here?

> What do you think? Are there any differences between iOS and Android from parse-server's point of view?

I can't see any difference from the server side, both are sending their requests via the REST API and Parse Server should react SDK-agnostic in this case.

**Comment by andrew-samara** [comment]
About this issue.
Since some time VK starts checking iP address for given token, and if ip address of the authorised device and server (which tries to use that token) is different you will get this error. Token will be denied. So, now when you making auth within your device you have to add .offline scope key, to generate token with no IP binding. 

Example for iOS (added Scopes.offline) :
```
func vkNeedsScopes(for sessionId: String) -> Scopes {
// Called when SwiftyVK attempts to get access to user account
// Should return a set of permission scopes
return [Scopes.email, Scopes.wall,  Scopes.photos, Scopes.offline]
}
```

Example for Android (added VKScope.OFFLINE):
```
ArrayList<VKScope> permissions = new ArrayList<>();
permissions.add(VKScope.WALL);
permissions.add(VKScope.PHOTOS);
permissions.add(VKScope.EMAIL);
permissions.add(VKScope.OFFLINE);
VK.login(activity, permissions);
```

There is no error with Parse server implementation.
Just need to implement right auth request from the device.

**Comment by gadgetreviews** [comment]
> About this issue. Since some time VK starts checking iP address for given token, and if ip address of the authorised device and server (which tries to use that token) is different you will get this error. Token will be denied. So, now when you making auth within your device you have to add .offline scope key, to generate token with no IP binding.
> 
> Example for iOS (added Scopes.offline) :
> 
> ```
> func vkNeedsScopes(for sessionId: String) -> Scopes {
> // Called when SwiftyVK attempts to get access to user account
> // Should return a set of permission scopes
> return [Scopes.email, Scopes.wall,  Scopes.photos, Scopes.offline]
> }
> ```
> 
> Example for Android (added VKScope.OFFLINE):
> 
> ```
> ArrayList<VKScope> permissions = new ArrayList<>();
> permissions.add(VKScope.WALL);
> permissions.add(VKScope.PHOTOS);
> permissions.add(VKScope.EMAIL);
> permissions.add(VKScope.OFFLINE);
> VK.login(activity, permissions);
> ```
> 
> There is no error with Parse server implementation. Just need to implement right auth request from the device.


This problem occurs only android devices but I tried this method and it looks like it is working. 

Thanks for this valuable information.

**Comment by mtrezza** [comment]
Can this issue be closed, or do we need to make a change in Parse Server or any of the Parse client SDKs?

**Comment by andrew-samara** [comment]
At current point, there is no issue with the parse server implementation. 
So, this ticket can be closed.
