### ISSUE TITLE
Removing a ParseGraphQLConfiguration does cause server to return to default settings

### ISSUE THREAD

**Issue by 185driver** [parse-community/parse-server#6941]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description

If a change is made to a `ParseGraphQLConfiguration` using `setGraphQLConfig()`, and then the change is removed, the original (default) `ParseGraphQLConfiguration` does not return automatically. It must be reset by the developer.

### Steps to reproduce

1. Create a Parse Server instance and add a custom `graphQLConfig` similar to the example below.
2. Note that the GraphQL Playground Docs tab shows that the `get` and `find` query aliases for the `Item` class are in use.
3. Remove the custom `graphQLConfig` related code from the Parse Server instance and refresh the GraphQL Playground page.
4. Note that the GraphQL Playground Docs tab continues to show that the `get` and `find` query aliases for the `Item` class are in use.
5. Instead of removing the `graphQLConfig` related code as mentioned in step `#3`, change it to this (forces a reset of the previously-changed configuration settings):
```js
const graphQLConfig = {
  classConfigs: [],
};
```
6. Note that the GraphQL Playground Docs tab now show that the `get` and `find` queries for the `Item` class has returned to the default `item` and `items` query names, respectively.

**Parse Server Instance Example**:
```js
const parseServer = new ParseServer({
  databaseURI: 'mongodb://localhost:27017/test',
  appId: 'APPLICATION_ID',
  masterKey: 'MASTER_KEY',
  serverURL: 'http://localhost:1337/parse',
});

const parseGraphQLServer = new ParseGraphQLServer(
  parseServer,
  {
    graphQLPath: '/graphql',
    playgroundPath: '/playground'
  },
);

const graphQLConfig = {
  classConfigs: [
    {
      className: 'Item',
      query: {
        getAlias: 'getItem',
        findAlias: 'findItems',
      },
    },
  ],
};

const setParseGraphQLConfig = async () => {
  await parseGraphQLServer.setGraphQLConfig(graphQLConfig);
};

setParseGraphQLConfig();

app.use('/parse', parseServer.app);
parseGraphQLServer.applyGraphQL(app);
```
### Actual Outcome

The `graphQLConfig` settings do not automatically return to their default settings after removing custom changes.

### Expected Outcome

The `graphQLConfig` settings should revert to their default settings automatically if no custom changes are applied.

###  Environment

Server
- Parse Server version: `4.3.0`
- Operating system: `Windows 10`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `localhost`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `4.2.8`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `MongoDB Atlas`

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): `GraphQL`
- SDK version: `N/A`

**Comment by davimacedo** [comment]
It happens because `setGraphQLConfig` actually persists the configuration into the database. We plan to add to Parse Dashboard the capability of managing this configuration.

**Comment by 185driver** [comment]
Copy that, thank you. It felt like unexpected behavior to me, so I wanted to raise the issue. If instead it is expected behavior and won't be changed, I could submit a minor documentation mention of the behavior to the GraphQL guide if you thought that would be helpful.  Otherwise, I can close this issue (or you can) if no action is planned or needed.

**Comment by davimacedo** [comment]
Sure. It will be a good addition to the docs.

**Comment by 185driver** [comment]
Oops, I used the wrong issue number in my [PR](https://github.com/parse-community/docs/pull/772#pullrequestreview-508909204) so I'll just close this manually.
