### ISSUE TITLE
Exception in parse Cloud Code generates internal server error

### ISSUE THREAD

**Issue by sarsonj** [parse-community/parse-server#6953]
### New Issue Checklist

- [x ] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x ] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x ] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x ] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description
I have simple cloudCode function:

```
Parse.Cloud.define("test", async => {
    throw Error("error in function!")
});
```

What I expect that I get Error (400) response with error JSON. It worked like this before I upgraded from Parse server 4.0.

What I get is Internal server error (500) with HTML output, like:

```
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Error: error in function!<br> &nbsp; &nbsp;at error (/opt/app/node_modules/parse-server/lib/Routers/FunctionsRouter.js:121:16)<br> &nbsp; &nbsp;at processTicksAndRejections (internal/process/task_queues.js:97:5)</pre>
</body>
</html>
```
### Steps to reproduce
Just define cloudCode function and throw Error

### Actual Outcome
Internal server error is generated and HTML output is returned

### Expected Outcome
JSON response and 400 error is returned

###  Environment

Server
- Parse Server version: 4.3.0
- Operating system: Ubuntu 18.04 LTS
- Local or remote host: Digital Ocean (but same on local)

**Comment by davimacedo** [comment]
Have you tried to throw Parse.Error instead?

**Comment by sarsonj** [comment]
Yes, I tried this, I also tried return reject promise, but same problem.

**Comment by dplewis** [comment]
Are you using any express middlewares? Can you post a sample project to recreate this issue?

**Comment by davimacedo** [comment]
I've just tried to reproduced and it returned 400 status code even throwing `new Error()`

**Comment by davimacedo** [comment]
I've just looked again at your code and it looks wrong. Could you please try with following code and let me know?

```js
Parse.Cloud.define("test", async req => {
    throw Error("error in function!")
});
```

**Comment by sarsonj** [comment]
@davimacedo sorry for typo in code.

I realised, that everything works in 4.1.0. So that looked into my parse server configuration.

It looks like that the problematic is option `enableExpressErrorHandler: true`. After I disabled it, the Parse server started to return correct 400 errors with JSONs. We are using Sentry for error reporting and that was the reason we also enabled express error handler. Does anything changed in Parse server after 4.2.0 regarding this?

**Comment by davimacedo** [comment]
Yes. There was this PR [here](https://github.com/parse-community/parse-server/pull/6423). `enableExpressErrorHandler` was not working properly and was fixed. When you use this option, you need to handle the thrown error in your express.js application.
