### ISSUE TITLE
Parse.Cloud.define third parameter issues (Validation Handler)

### ISSUE THREAD

**Issue by dblythy** [parse-community/parse-server#6965]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

As discussed in the [community forum](https://community.parseplatform.org/t/extending-options-to-parse-cloud-functions/958/13), `Parse.Cloud.define` has a third undocumented parameter available that is a "validation" handler. A couple of issues:

-Throwing in this block returns error code 1:

```
it('Throw from validator', async done => {
    Parse.Cloud.define('myFunction', req => {
// cloud function
    }, req => {
// validator function
      throw 'error'
    });
    try {
      await Parse.Cloud.run('myFunction');
    } catch (e) {
      expect(e.code).toBe(Parse.Error.VALIDATION_ERROR);
// is error code 1
      done()
    }
});
```

-[Validation functions must return 'true'](https://github.com/parse-community/parse-server/blob/c647c5336e96cf44521b46e080cf7135cf79486d/src/Routers/FunctionsRouter.js#L165)
```
it('complete validator', async done => {
    Parse.Cloud.define('myFunction', req => {
      return 'myFunc'
    }, req => {

    });
    try {
      const result = await Parse.Cloud.run('myFunction',{});
      expect(result).toBe('myFunc');
      done()
    } catch (e) {
      // e.code: 1, e.message: undefined
      fail('should not have thrown error');
    }
  });
```

-Validation functions don't work with async

```
it('async validator', async done => {
    Parse.Cloud.define('myFunction', req => {
      return 'myFunc'
    }, async req => {
      throw new Parse.Error(Parse.Error.SCRIPT_FAILED, 'It should fail');
    });
    try {
      await Parse.Cloud.run('myFunction');
// doesn't throw an error
      fail('should have validation error')
    } catch (e) {
      expect(e.code).toBe(Parse.Error.SCRIPT_FAILED);
      expect(e.message).toBe('It should fail');
      done();
    }
});
```

-Validator functions are [not documented](https://parseplatform.org/Parse-SDK-JS/api/2.17.0/Parse.Cloud.html#.define), and there only seems to be [one spec](https://github.com/parse-community/parse-server/blob/045d941aefd1cb452c06c18c5adb1d179ea148e6/spec/ParseAPI.spec.js#L1173). 

Considering these have seemingly been around since the beginning of [Parse Server](https://github.com/parse-community/parse-server/blob/3c4d5159b4aa5d073b1206ece40529e2bbc69eb1/src/Routers/FunctionsRouter.js#L39): 

-how likely are they to be in production? (my guess is most people aren't using them, due to being undocumented)
-should we continue to support them?
-should I work on a PR for fixing the problems with them?
-should I work on a PR to the docs / SDK?

Thanks all!

**Comment by dplewis** [comment]
I’m fine with add all the enhancements. We can document the breaking changes. I assume not a lot of users are using this feature since it’s undocumented
