### ISSUE TITLE
[error: Push Notification] Certificate and key do not match

### ISSUE THREAD

**Issue by burhanyilmaz** [parse-community/parse-server#6978]
When I run the parse server, throw this error `Certificate and key do not match `.

When the passphrase is true, throw this error `Certificate and key do not match `
When the passphrase is false, there is no error. it is so strange. 

How can solve this? Thanks.

My config here that
```
  push: {
    android: {
      apiKey: process.env.FCM_SERVER_KEY,
      senderId: ''
    },
    ios: [
      {
        production: false,
        topic: 'com.my.app',
        pfx: './assets/pushNotifications/myapp.p12',
        passphrase: 'pass'
      },
      {
        production: false,
        topic: 'com.my.app',
        pfx: './assets/pushNotifications/myapp2.p12',
        passphrase: 'pass'
      }
    ]
  }
```

**Comment by mtrezza** [comment]
Thanks for reporting. To report an issue, please use the issue template provided when you create an issue. The template asks for essential information which helps us to investigate the issue.

**Comment by mtrezza** [comment]
I'm closing this as it does not use the issue template provided when creating an issue and therefore lacks essential information required to investigate the issue. Please edit your initial post using the issue template and we can re-open this issue.
