### ISSUE TITLE
Batch Request Problem when parse is served from folder behind reverse proxy

### ISSUE THREAD

**Issue by rhuanbarreto** [parse-community/parse-server#6980]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description

**Given** I have a Parse Server Running on a local server, port 1337 (`serverUrl: "http://127.0.0.1:1337/parse"`), with publicServerURL different from the serverUrl (`publicServerURL: "http://somedomain.com/backend/parse"`)
**And** this server is behind a reverse proxy (Nginx) forwarding the address http://somedomain.com/backend/ to this host running parse:
```
location ^~ /backend/ {
    proxy_pass http://parse-server-dns-name.com:1337/;
  }
```

When, inside of a cloud function, I do a Parse.Object.saveAll() (`POST /parse/batch`) with the following parameters:
```
{
  “requests”: [
    { “method”: “PUT”, “body”: { “type”: “Test2" }, “path”: “/parse/classes/Task/lVEd1AHl08" }
  ]
}
```

**Then** I should get the object updated, but Instead an error comes in the log

`cannot route PUT /lVEd1AHl08`

### Related issue

This issue is probably happening because of https://github.com/parse-community/parse-server/pull/3042

In this line 
https://github.com/parse-community/parse-server/blob/0031c5dc9926117c21680a8dbbc15ccd7bc543c2/src/batch.js#L44

It tries to reconcile the difference between the 2 addresses, but it makes some confusion. In my case should route to the serverURL, but it's trying to use something different.

###  Environment

Server
- Parse Server version: 4.3.0
- Operating system: Linux (Docker)
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): Local (self hosted)

Database
- System (MongoDB or Postgres): MongoDB
- Database version: v4.2.9
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): Local (Self Hosted)

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): JS SDK
- SDK version: 2.15.0

### Logs
```
{“method”:“POST”,“url”:“/parse/batch”,“headers”:{“user-agent”:“node-XMLHttpRequest, Parse/js2.15.0 (NodeJS 12.19.0)“,”accept”:“*/*“,”content-type”:“text/plain”,“host”:“127.0.0.1:1337”,“content-length”:“241”,“connection”:“close”},“body”:{“requests”:[{“method”:“PUT”,“body”:{“type”:“Test2"},“path”:“/parse/classes/Task/lVEd1AHl08"}]}},
error: Parse error: cannot route PUT /lVEd1AHl08 {“code”:107,“stack”:“Error: cannot route PUT /lVEd1AHl08\n    at PromiseRouter.tryRouteRequest (/app/node_modules/parse-server/lib/PromiseRouter.js:143:13)\n    at /app/node_modules/parse-server/lib/batch.js:91:21\n    at Array.map (<anonymous>)\n    at /app/node_modules/parse-server/lib/batch.js:82:40\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)“}
```

**Comment by davimacedo** [comment]
Could you share your parse server config?

**Comment by rhuanbarreto** [comment]
```javascript
new ParseServer({
  appId: 'test',
  masterKey: process.env.MASTER_KEY,
  databaseURI: `mongodb://10.133.51.150:27017/test`,
  cloud: require.resolve("./cloud/main"),
  serverURL: `http://127.0.0.1:1337/parse`,
  publicServerURL: 'http://somedomain.com/backend/parse',
  allowClientClassCreation: false,
  auth: {
    keycloak: {
      module: require("./auth/Keycloak"),
      config: require(`./auth/keycloak_${process.env.NODE_ENV}.json`),
    },
  },
});
```

**Comment by mtrezza** [comment]
@rhuanbarreto Did you try out the suggestion above or do you have any other update on this issue?

**Comment by rhuanbarreto** [comment]
Will update it soon

**Comment by mtrezza** [comment]
I'm closing this as there were no further responses and the issue seems to be deployment specific. Please follow up on any questions asked and further steps suggested in the thread and we can re-open this issue.

**Comment by ZachGoldberg** [comment]
I'm experiencing this same isuse, and I've narrowed down the issue using the parse server unit tests.

batch.js lin 44 assumes that the requestPath is a valid `requestPath` to the `PUBLIC_SERVER_URL`.  If instead the request is coming to the `SERVER_URL` *AND* the `SERVER_URL` and `PUBLIC_SERVER_URL` have different `path` lengths, then this fails.
```
return function(requestPath) {
      // Build the new path by removing the public path
      // and joining with the local path
      const newPath = path.posix.join(
        '/',
        localPath,
        '/',
        requestPath.slice(publicPath.length)
      );
      // Use the method for local routing
      return makeRoutablePath(newPath);
    };
```

Notice how `requestPath.slice` is using the `publicPath.length` -- there is no toggle between `publicPath` and `localPath` for constructing `newPath`.

To replicate the failure change line 9 of `batch.spec.js` to anything with a longer path name, i.e.

```
publicServerURL = 'https://my.domain/somereally/longpath';
```

I'll see if I can whip up a quick test & PR for this and link to this issue.
