### ISSUE TITLE
version upgrade issue

### ISSUE THREAD

**Issue by webapis** [parse-community/parse-server#6987]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description
Hi, I get an error when running parse-server latest version 4.3.0. But when running 4.2.0 I have no problem.
 
### Steps to reproduce
1. delete node_modules folder;
2. npm clean cache;
3. inside packange.json edit version for parse-server  as  4.3.0;
4. npm install.
5. run parse server 
### Actual Outcome
  Referenced from: /Users/personalcomputer/fb/node_modules/@node-rs/bcrypt/bcrypt.darwin.node
  Expected in: /usr/lib/libSystem.B.dylib

### Expected Outcome
parse-server-example running on port 1337.

###  Environment

Server
- Parse Server version: `4.3.0`
- Operating system: `mac`

**Comment by mtrezza** [comment]
Thank you for reporting. I'm closing this as it seems to be a duplicate of #6837, let's continue the discussion there.

Feel free to comment if you think this is not a duplicate and we can re-open this issue.
