### ISSUE TITLE
Improving default File Security

### ISSUE THREAD

**Issue by dblythy** [parse-community/parse-server#6995]
**Is your feature request related to a problem? Please describe.**
This FR is in relation to the default security around files, specifically around deployments that never intend to save files.

As discussed in [this PR](https://github.com/parse-community/parse-server/pull/6973), personally I think it feels bit clunky to recommend a fileTrigger for users that never intend to have any files uploaded to their servers. Also, considering anonymous users are disabled by default, I would expect that file uploads require a logged in user.

**Describe the solution you'd like**
I was thinking of possibly baking these into the server config:

-`allowAnonymousFileUploads`: would be a breaking change as would prevent file uploads for no logged in users (unless set to true)
-`allowFileUploads`: defaults to true. Can set to false for deployments that never want file uploads.

**Describe alternatives you've considered**
As said, you can achieve this functionality with a file trigger. I just think you should be able to build a secure server without requiring cloud code. If you're building a Parse Server and only reading the Object docs, you won't ever realise that your deployment can accept files, which could be problematic.

**Additional context**
Made this an issue instead of a PR for @mtrezza :)

**Comment by mtrezza** [comment]
Thanks for suggesting (and for opening an issue to discuss this 😉).

This seems to be an elegant solution to the [anonymous file upload issue](https://github.com/parse-community/parse-server/issues/2137). The breaking change seems acceptable because it is a security improvement.

Grouping the two parameters could make for better overview in the configuration, what do you think about something like:

```
fileUpload: {
  enable: true, // Is true if files can be uploaded with Parse Server. Default is true.
  enableForAnonymousUser: false, // Is true if file upload is enabled for anonymous users. Default is false.
}
```

**Comment by dblythy** [comment]
That's a good point. I completely forgot about anonymous users, I was referring to "public" users, not "anonymous". I like your suggestion. Wording looks simple enough - I'll look into it.

I'll work on a PR, this should be a really simple addition so should have something shortly.

**Comment by mtrezza** [comment]
Now that I think about it again, isn't the `fileUpload.enabled` parameter implicitly a `fileUpload.enabledForAuthenticatedUser` parameter? And if so, should we change that logic, to allow for more granular control?

E.g. with the previous suggestion, it is not possible to allow file uploads only for anonymous users, but not for authenticated users or public. I wouldn't have a use case for that at hand, but it would give more granular control.

What is your opinion on that?

**Comment by dblythy** [comment]
It's definitely an interesting use case. I see the `fileUpload.enabled` as a master kill switch. But I agree it should be as granular as possible

I've added `enabledForAuthenticatedUser` to the latest commit.

**Comment by mtrezza** [comment]
I don't think `fileUpload.enabled` is still needed when one can disable the 3 other options and achieve the same result.

**Comment by dblythy** [comment]
Yeah, good point.

**Comment by dblythy** [comment]
Closed via #7071

**Comment by tehsunnliu** [comment]
Hi, does this prevent useMasterKey to save files too? Because in server when I try to set file and save it with masterKey i get "File upload by public is disabled" error message.

**Comment by mtrezza** [comment]
@tehsunnliu If you need help or have a question please post in the [community forum](https://community.parseplatform.org). This PR is closed.

**Comment by hamzabinamin** [comment]
> Hi, does this prevent useMasterKey to save files too? Because from CloudCode when I try to save the file with useMasterKey set to true, I get "File upload by public is disabled" error message. Even from the dashboard I get the same error. Setting enableForPublic works fine.

@tehsunnliu Can you show me your configuration file? I have added 'enableForPublic', yet I still receive the 'File upload by public is disabled' message.

**Comment by c0sm1cdus7** [comment]
@hamzabinamin did you manage to fix it?
