### ISSUE TITLE
Push Notification is silent on Android Devices

### ISSUE THREAD

**Issue by MGolob** [parse-community/parse-server#7010]
### New Issue Checklist

- [X] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [X] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [X] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [X] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description
When sending push notifications to android devices from cloud code or from the dashboard the notifications are delivered but there is no entry in the notification try.

### Steps to reproduce
Configure parse server to send push notifications, set a device token for an android device and send a notification.

### Actual Outcome
No Entry in the notification tray.

### Expected Outcome
Should be same result as sending from the firebase console. A notification should be visible in the notification tray.

###  Environment
Using Parse Server 4.4.0

Server
- Parse Server version: `4.4.0`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `Self hosted`

Database
- System (MongoDB or Postgres): `Postgres`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `Self hosted`

### Logs
```
verb parse-server-push-adapter GCM sending to 1 device
verb parse-server-push-adapter GCM GCM Response: {
verb parse-server-push-adapter GCM     "multicast_id": 899372689132584600,
verb parse-server-push-adapter GCM     "success": 1,
verb parse-server-push-adapter GCM     "failure": 0,
verb parse-server-push-adapter GCM     "canonical_ids": 0,
verb parse-server-push-adapter GCM     "results": [
verb parse-server-push-adapter GCM         {
verb parse-server-push-adapter GCM             "message_id": "0:1605486080143026%00f19590f9fd7ecd"
verb parse-server-push-adapter GCM         }
verb parse-server-push-adapter GCM     ]
verb parse-server-push-adapter GCM }
```

**Comment by mtrezza** [comment]
Thanks for reporting.

The push adapter indicates that the push message was sent successfully. It could be a misconfiguration on the device that prevents the push notification from being displayed. 

My suggestion would be to check the client side code and compare it with the Parse Android SDK push notification guide.

**Comment by mtrezza** [comment]
I'm closing this as it lacks essential information required to investigate the issue. Please follow up on any questions asked and further steps suggested in the thread and we can re-open this issue.
