### ISSUE TITLE
Allow multiple email verification codes, or resend with existing code

### ISSUE THREAD

**Issue by dblythy** [parse-community/parse-server#7012]
**Is your feature request related to a problem? Please describe.**

I often find that due to the time it takes mail to deliver in my country / with our providers, clients will reclick the "forgot password / resend email". Then, the first email comes through with an "Invalid Link" (as the second request wiped it), leading to increasing frustration with our customers.

**Describe the solution you'd like**

Cooldowns:

If the request is re-requested within a specified timeframe (e.g 1 min), either:
- The server responds with an error message such a "please wait blah blah blah"
- The server resend the email _without_ re-creating another code.

Or, allowing multiple verification codes in an array (e.g, 5), and only one has to be clicked to verify the request.

**Describe alternatives you've considered**
Using a custom cloud function to check code expiry and date, and then work backwards.

**Comment by mtrezza** [comment]
Thanks for suggesting.

This seems to be a useful enhancement for Parse Server. I suggest to pursue option 2 because it causes less friction for the user:
> The server resend the email without re-creating another code.

Do you have a conceptual suggestion how to go about it?

**Comment by dblythy** [comment]
Thanks @mtrezza. Should be too bad for Password Policy, but I'm concerned adding another option for emails on the top level (e.g `emailResetTokenReuseIfValid`).

I propose:

```
emailPolicy : {
  verifyUserEmails: true,
  emailVerifyTokenValidityDuration: 2 * 60 * 60,
  preventLoginWithUnverified: false,
  resetTokenReuseIfValid: false
}
```

Also, as far as I could tell, there are no deeper definitions for the keys in [passwordPolicy](https://github.com/parse-community/parse-server/blob/master/src/Options/index.js#L130). Could this potentially be improved?

**Comment by mtrezza** [comment]
> I'm concerned adding another option for emails on the top level 

The new parameter should go under the same key as the already existing and related  `emailVerifyTokenValidityDuration`, not at the root level.

> there are no deeper definitions for the keys in passwordPolicy. Could this potentially be improved?

Yes, however any such improvement should be done in a separate PR because it involves code sections that are not related to the functionality of this PR.

**Comment by dblythy** [comment]
Yes, but as far as I can tell, that is under ["passwordPolicy"](https://github.com/parse-community/parse-server/blob/e6ac3b6932186a6a85601c65143305f86f63e948/spec/PasswordPolicy.spec.js#L20). This feature would also affect resending verification emails, which in my view, wouldn't be expected to be password policy related.

> Yes, however any such improvement should be done in a separate PR

Ok. thanks I was just seeing your thoughts. I'll open a new issue.

**Comment by mtrezza** [comment]
What speaks against introducing two distinct config variables?

The verification email and password reset email are both "emails", but part of different features, hence they are part of distinct key groups.

```
{
  passwordPolicy: {
    resetTokenValidityDuration: ...,
    resetTokenReuseIfValid: ...
  },
  emailVerifyTokenValidityDuration: ...,
  emailVerifyTokenReuseIfValid: ...
  }
}
```

Grouping the verification email keys in its own key group should be done in a separate PR, as previously outlined.
