### ISSUE TITLE
Add defintions for accountLockout and passwordPolicy

### ISSUE THREAD

**Issue by dblythy** [parse-community/parse-server#7015]
**Is your feature request related to a problem? Please describe.**
As discussed here, there aren't deeper definitions for [accountLockout and passwordPolicy](https://github.com/parse-community/parse-server/blob/master/src/Options/index.js#L130)

**Describe the solution you'd like**
accountLockout and passwordPolicy, to deeper definitions, such as [IdempotencyOptions](https://github.com/parse-community/parse-server/blob/master/src/Options/index.js#L283).

**Comment by mtrezza** [comment]
Thanks for suggesting.

This seems to be a useful enhancement for Parse Server. I suggest to open the PR after #7017 has been merged to include the newly introduced configuration keys.
