### ISSUE TITLE
There are a lot of logs as CREATE TABLE IF NOT EXISTS "_SCHEMA"

### ISSUE THREAD

**Issue by JeffGuKang** [parse-community/parse-server#7021]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description

There are a lot of log as `CREATE TABLE IF NOT EXISTS "_SCHEMA" ( "className" varChar(120), "schema" jsonb, "isParseClass" bool, PRIMARY KEY ("className") )` 

And My DB connection pool is higher at the time.

I am not sure it makes some problem to the DB 
or 
the logs are made a lot when DB connection has a problem. 

```log
statement: CREATE TABLE IF NOT EXISTS "_SCHEMA" ( "className" varChar(120), "schema" jsonb, "isParseClass" bool, PRIMARY KEY ("className") )
```
<img width="1129" alt="image" src="https://user-images.githubusercontent.com/216363/100128918-3efa7080-2ec4-11eb-9307-be4c64dab80d.png">

I found some related query in PostgreAdopter: https://github.com/parse-community/parse-server/blob/bbae55d518f3541ce2df4b6514357cc441c57bf6/src/Adapters/Storage/Postgres/PostgresStorageAdapter.js#L875-L892

### Steps to reproduce

1. Checking postgreSQL logs on the RDS.
2. The log is shown around every 30 secs

3. But sometimes there are too many logs when backend server requests a lot.

###  Environment

This is my Parse config.
```js
const parseConfig = {
  cloud: __dirname + '/src/cloud/', // location after tsc
  appId: process.env.APP_ID,
  masterKey: process.env.MASTER_KEY,
  fileKey: process.env.FILE_KEY,
  serverURL: 'http://localhost:1337/parse', 
  auth: {
    kakao: kakaoAuthAdapter,
    apple: {
      client_id: process.env.APPLE_SIGNIN_CLIENT_ID, // optional (for extra validation), use the Service ID from Apple.
    },
  },
  maxUploadSize: '5mb',
  logLevel: process.env.NODE_ENV !== 'development' ? 'warn' : undefined,
  schemaCacheTTL: 1000 * 60 * 60 * 24 * 15, // 15 days
  cacheTTL: 1000 * 60 * 60 * 24 * 15, // 15 days
  allowClientClassCreation: false,
  enableSingleSchemaCache: true,
  enableExpressErrorHandler: false,
}

  const redisOptions = {url: 'redis://' + process.env.REDIS_CACHE_URL}
  const redisCache = new RedisCacheAdapter(redisOptions)

  parseConfig.cacheAdapter = redisCache
```

Server
- Parse Server version: `4.4.0`
- Operating system: `FILL_THIS_OUT`
- Local or remote host : `AWS` scalable server (EC2)

Database
- System (MongoDB or Postgres): `Postgres`
- Database version: `11+`
- Local or remote host: `AWS Aurora postgres`

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): `iOS, Android`
- SDK version: `FILL_THIS_OUT`

**Comment by mtrezza** [comment]
Thanks for reporting.

This may be related to https://github.com/parse-community/parse-server/issues/6193 and https://github.com/parse-community/parse-server/pull/6743.

Can you be more specific about what causes the calls to `_ensureSchemaCollectionExists`? In the source code there are some references that call this method, so depending on the operations you perform, these calls may be expected.

**Comment by JeffGuKang** [comment]
```
Postgre RDS <-------------> multiple EC2 instances
                      <--> Redis  <->
```
           
And it was caused when traffic increased. I will check the logs what is calling `_ensureSchemaCollectionExists`.

**Comment by dplewis** [comment]
_ensureSchemaCollectionExists Is called for every request to Postgres for some reason. I’m working on schema improvements right now. I can look into this

**Comment by mtrezza** [comment]
Seems related to https://github.com/parse-community/parse-server/pull/6743 and https://github.com/parse-community/parse-server/pull/6636.

**Comment by dplewis** [comment]
@JeffGuKang I'm starting to look into this. `_ensureSchemaCollectionExists()` should be called once on initialize. I have no idea why its called before every request to Postgres. Its for the tests only or does the`_SCHEMA` class gets deleted while the server is running?
