### ISSUE TITLE
mongorunner causing issue with latest Docker builds

### ISSUE THREAD

**Issue by cbaker6** [parse-community/parse-server#7039]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description

When running `docker build .` on the latest master branch, the container will not build. The first error requires the addition of installing ssh in the `Dockerfile`, but even then, the error below occurs.

Removing mongorunner from package.json fixes the issue.

### Steps to reproduce

1. clone the master branch
2. cd to the parse directory and run `docker build .`

### Actual Outcome

```
Step 1/22 : FROM node:lts-alpine as build
 ---> 7f1893c3ede0
Step 2/22 : RUN apk update;   apk add git;   apk add openssh;
 ---> Using cache
 ---> 9c0756bb891f
Step 3/22 : WORKDIR /tmp
 ---> Using cache
 ---> b6ca6099ce39
Step 4/22 : COPY package*.json ./
 ---> Using cache
 ---> 506dc8897196
Step 5/22 : RUN npm ci
 ---> Running in 2c3662de87f8
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/mongodb-js/mongodb-tools.git
npm ERR! 
npm ERR! Host key verification failed.
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-12-02T15_09_39_592Z-debug.log
```

###  Environment

Server
- Parse Server version: `4.4.0` (latest master)
- Operating system: `alpine linux via Docker`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `Local`

Database
- System (MongoDB or Postgres): `either`
- Database version: `N/A`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `Local`

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): `N/A`
- SDK version: `N/A`

### Logs

N/A

**Comment by cbaker6** [comment]
The ssh issue with mongojs may have resolved itself (or something with repo) as I'm not getting the error anymore. It was occurring yesterday and this morning

**Comment by mtrezza** [comment]
Alright, we can always re-open if it surfaces again.

**Comment by j-heinze** [comment]
I am getting the same error after adding openssh. 
Before it just states `error: cannot run ssh: No such file or directory`

```
Step 1/22 : FROM node:lts-alpine as build
 ---> 7f1893c3ede0
Step 2/22 : RUN apk update;   apk add git;      apk add openssh;
 ---> Using cache
 ---> 43600bd4564c
Step 3/22 : WORKDIR /tmp
 ---> Using cache
 ---> 8f64ca6161a6
Step 4/22 : COPY package*.json ./
 ---> Using cache
 ---> 6eab2a8e43d9
Step 5/22 : RUN npm ci
 ---> Running in 601f82c4bae4
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/mongodb-js/runner.git
npm ERR! 
npm ERR! Host key verification failed.
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-01-11T10_42_58_680Z-debug.log
```
I tried adding the RSA key to known_hosts by modifying the Dockerfile even further: 
```
RUN mkdir ~/.ssh
RUN ssh-keyscan -t rsa github.com > ~/.ssh/known_hosts
```

but that just resulted in the following:
```
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/mongodb-js/runner.git
npm ERR! 
npm ERR! Warning: Permanently added the RSA host key for IP address '140.82.121.4' to the list of known hosts.
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-01-11T10_49_35_600Z-debug.log
```

So this is now quite weird.

### Environment

#### Server
Parse Server version: 4.4.0 (latest master)
Operating system: alpine linux via Docker
Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): Local

#### Database 
System (MongoDB or Postgres): either
Database version: N/A
Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): Local

**Comment by j-heinze** [comment]
This is apparently being caused by npm changing the package-lock.json whenever a new module is installed (updating "lockfileVersion" to 2 and updating a few dependencies resulting in an ssh use. 
```
"version": "git+ssh://git@github.com/mongodb-js/runner.git#dfb9a520147de6e2537f7c1c21a5e7005d1905f8",
      "dev": true,
      "from": "mongodb-runner@mongodb-js/runner", 
...
```

Any idea for a workaround during npm install, to not modify the existing packages in package-lock.json?
