### ISSUE TITLE
FR: Add support for Huawei Cloud Messaging

### ISSUE THREAD

**Issue by rostopira** [parse-community/parse-server#7062]
Since `Installation` already has field `pushType`, it could be straightforward to set value to 'hcm' to distinguish tokens.
The API is identical, so there will be no breaking changes.

**Comment by rostopira** [comment]
Oh, nevermind, it can be done via PushAdapter

**Comment by mtrezza** [comment]
Thanks for suggesting.

To suggest a feature or enhancement please use the template provided when you create an issue. The template asks for essential information which helps others to better understand the suggestion and join the discussion.

Please also reference any related issues you found when searching through existing issues.
