### ISSUE TITLE
CORS error trying to access Parse Dashboard

### ISSUE THREAD

**Issue by amirreza8585** [parse-community/parse-server#7077]
### Issue Description

Hey there, Im trying to access parse-dashboard, But I got this error:

`Access to XMLHttpRequest at 'https://parseserver.example.com/parse/serverInfo' from origin 'https://parsedashboard.example.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
`
I also set `PARSE_SERVER_ALLOW_ORIGIN = "*"` in enviroment variables. But I got the same error.

###  Environment

Server
- Parse Server version: `4.5.0`
- Parse dashboard version : `2.1.0`
- Operating system: `Ubuntu 18`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `Fandogh.cloud`

Database
- System (MongoDB or Postgres): `Mongodb`
- Database version: `4.2`

### Logs

[parse-d84575db5-dstmq] [parse] -> allowClientClassCreation: true
2	[parse-d84575db5-dstmq] [parse] -> appId: Claassor_App
3	[parse-d84575db5-dstmq] [parse] -> cacheMaxSize: 10000
4	[parse-d84575db5-dstmq] [parse] -> cacheTTL: 5000
5	[parse-d84575db5-dstmq] [parse] -> clientKey: ''
6	[parse-d84575db5-dstmq] [parse] -> customPages: {}
7	[parse-d84575db5-dstmq] [parse] -> databaseURI: ''
8	[parse-d84575db5-dstmq] [parse] -> enableAnonymousUsers: true
9	[parse-d84575db5-dstmq] [parse] -> expireInactiveSessions: true
10	[parse-d84575db5-dstmq] [parse] -> graphQLPath: /graphql
11	[parse-d84575db5-dstmq] [parse] -> host: 0.0.0.0
12	[parse-d84575db5-dstmq] [parse] -> idempotencyOptions: {"ttl":300,"paths":[]}
13	[parse-d84575db5-dstmq] [parse] -> logsFolder: ./logs
14	[parse-d84575db5-dstmq] [parse] -> masterKey: ***REDACTED***
15	[parse-d84575db5-dstmq] [parse] -> masterKeyIps: []
16	[parse-d84575db5-dstmq] [parse] -> maxUploadSize: 1000mb
17	[parse-d84575db5-dstmq] [parse] -> mountPath: /parse
18	[parse-d84575db5-dstmq] [parse] -> objectIdSize: 10
19	[parse-d84575db5-dstmq] [parse] -> playgroundPath: /playground
20	[parse-d84575db5-dstmq] [parse] -> port: 1337
21	[parse-d84575db5-dstmq] [parse] -> protectedFields: {"_User":{"*":["email"]}}
22	[parse-d84575db5-dstmq] [parse] -> revokeSessionOnPasswordReset: true
23	[parse-d84575db5-dstmq] [parse] -> schemaCacheTTL: 5000
24	[parse-d84575db5-dstmq] [parse] -> sessionLength: 31536000
25	[parse-d84575db5-dstmq] [parse] -> allowCustomObjectId: false
26	[parse-d84575db5-dstmq] [parse] -> collectionPrefix:
27	[parse-d84575db5-dstmq] [parse] -> directAccess: false
28	[parse-d84575db5-dstmq] [parse] -> emailVerifyTokenReuseIfValid: false
29	[parse-d84575db5-dstmq] [parse] -> enableExpressErrorHandler: false
30	[parse-d84575db5-dstmq] [parse] -> enableSingleSchemaCache: false
31	[parse-d84575db5-dstmq] [parse] -> mountGraphQL: false
32	[parse-d84575db5-dstmq] [parse] -> mountPlayground: false
33	[parse-d84575db5-dstmq] [parse] -> preserveFileName: false
34	[parse-d84575db5-dstmq] [parse] -> preventLoginWithUnverifiedEmail: false
35	[parse-d84575db5-dstmq] [parse] -> scheduledPush: false
36	[parse-d84575db5-dstmq] [parse] -> verifyUserEmails: false
37	[parse-d84575db5-dstmq] [parse] -> jsonLogs: false
38	[parse-d84575db5-dstmq] [parse] -> verbose: false
39	[parse-d84575db5-dstmq] [parse] -> level: undefined
40	[parse-d84575db5-dstmq] [parse] -> serverURL: http://localhost:1337/parse
41	[parse-d84575db5-dstmq] [parse] -> [1] parse-server running on http://localhost:1337/parse

---
Edit: removed custom URL.

**Comment by mtrezza** [comment]
Thanks for reporting.

Possibly related: https://github.com/parse-community/parse-server/issues/6674, https://github.com/parse-community/parse-dashboard/issues/1296.

The error message is explicit about the issue that the `Access-Control-Allow-Origin` header is missing in the preflight response sent from Parse Server. Can you log and post the preflight response from Parse Server to verify that?

You can try to:
- explicitly set the server IP address instead of `localhost` in the `serverURL` configuration
- set `PARSE_SERVER_ALLOW_ORIGIN` to the specific domain instead of the wildcard `*`

**Comment by amirreza8585** [comment]
Hey this the response I get:

Status404
Not Found
VersionHTTP/2
Transferred265 B (0 B size)
Referrer Policyno-referrer-when-downgrade

 
content-length
 153
content-security-policy
 default-src 'none'
content-type
 text/html; charset=utf-8
date
 Wed, 16 Dec 2020 09:07:47 GMT
server
 nginx/1.15.5
x-content-type-options
 nosniff
X-Firefox-Spdy
 h2
x-powered-by
 Express
 
Accept
 */*
Accept-Encoding
 gzip, deflate, br
Accept-Language
 en-US,en;q=0.5
Access-Control-Request-Method
 POST
Connection
 keep-alive
Host
 parse-sysschoolmanagement.fandogh.cloud
Origin
 https://parsedashboard-sysschoolmanagement.fandogh.cloud
Referer
 https://parsedashboard-sysschoolmanagement.fandogh.cloud/apps/app1/browser
TE
 Trailers
User-Agent
 Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:83.0) Gecko/20100101 Firefox/83.0

**Comment by amirreza8585** [comment]
@mtrezza Can you check this please?

**Comment by mtrezza** [comment]
Did you try out the previous [suggestions](https://github.com/parse-community/parse-server/issues/7077#issuecomment-745577223)?

**Comment by amirreza8585** [comment]
Yes I did. But nothing changed @mtrezza

**Comment by amirreza8585** [comment]
Yes I did. But nothing changed @mtrezza

**Comment by mtrezza** [comment]
Your [comment](https://github.com/parse-community/parse-server/issues/7077#issuecomment-745977341) looks like the preflight request sent from the dashboard to the server. It would be also interesting to see the response sent from the server to the dashboard.

Can you post a pair of preflight request and response, so we can look into what the server is sending?

**Comment by mtrezza** [comment]
I'm closing this as it seems to be resolved. Feel free to comment if you have any questions and we can re-open this issue.
