### ISSUE TITLE
Cant set response header from a cloud function 

### ISSUE THREAD

**Issue by REPTILEHAUS** [parse-community/parse-server#7084]
I need to process some information via a cloud function and return a generated document in the response including headers like the following:

```
       'Content-Type': 'application/pdf',
        'Content-disposition': 'attachment;filename=certificate.pdf',
```

I read here that this is not possible though https://github.com/parse-community/parse-server/issues/5348 is this still the case ? and is there no recommended way to return a custom response like this which also allows me access to the parse user object etc so that i can generate this doc ?

**Comment by davimacedo** [comment]
The easiest way is creating a custom Express.js endpoint for that. Closing this issue as it does not follow the [new issue template](https://github.com/parse-community/parse-server/issues/new/choose).

**Comment by REPTILEHAUS** [comment]
@davimacedo but how to retrieve the current user via express endpoint as opposed to cloud function, I think the question is still valid regardless of new issue template if the framework is not capable of setting headers in cloud functions thats a fundamental problem

**Comment by davimacedo** [comment]
You can access the session token in the header and use the SDK to retrieve the user. I believe it is a valid feature request that can be evaluated. Could you please open a new issue using the [template](https://github.com/parse-community/parse-server/issues/new/choose)?
