### ISSUE TITLE
Set objectId for new Parse.Objects sooner so it can be accessed in beforeSave functions

### ISSUE THREAD

**Issue by dblythy** [parse-community/parse-server#7117]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation
If a new object is created, it doesn't get an object ID until [setRequiredFieldsIfNeeded](https://github.com/parse-community/parse-server/blob/c1971b2ab1a950a3bf029bd99c280dc044b2b536/src/RestWrite.js#L315).

This means that any `Parse.Cloud.beforeSave(Parse.User` triggers won't be able to any ACL work using `request.object` because it won't have an ID defined.

### Feature / Enhancement Description
Either assign the object ID prior to the beforeSave for new objects, or run setRequiredFieldsIfNeeded before the beforeSave.

This would be a breaking change for developers who use `if (!req.object.objectId)` to work out if an object is new, rather than `!req.object.existed()`.

### Example Use Case
```
Parse.Cloud.beforeSave(Parse.User, ({object}) => {
  if (!object.existed) {
    const acl = new Parse.ACL();
    acl.setReadAccess(object.id,true);
    acl.setWriteAccess(object.id,true);
    object.setACL(acl);
  }
});
```

### Alternatives / Workarounds
Run the code in an afterSave trigger.

Related: #701

**Comment by mtrezza** [comment]
Thanks for proposing this.

There have been many discussion around that topic in the past. The key obstacle is that the objectId cannot be guaranteed until an object is saved successfully in the DB. Any other objectId prior to that can only be considered provisional.

How would a case be handled if an objectId is not saved as provisioned?

**Comment by dblythy** [comment]
Hmmmm. I am not sure how you would deal with this. How does the current server handle object ID clashes? To me it seems as though runDatabaseOperation (what saves the object) is called after setRequiredFieldsIfNeeded (what sets the object ID), so if you were to create new objects via another objects' beforeSave, there's still the risk that objectID's will clash and throw, even after you've created the other objects.

My issues with this only come with the Parse.User class, where I can't set ACLs on objects that I create for users via a beforeSave trigger because no objectId is set. I am not sure if there are many use cases that come for other classes. Perhaps a solution could be a beforeSignup trigger that runs after objectId is assigned, and could "track" any other objects that are created.

```javascript
Parse.Cloud.beforeSignup(async req => {
  const acl = new Parse.ACL(req.user);
  req.user.setACL(acl);
});

If objectID clashes happen after this script, DUPLICATE VALUE will still be thrown.

**Comment by dblythy** [comment]
This isn't really required as if you want to enforce "private" users, you can write:

```js
Parse.Cloud.beforeSave(Parse.User, ({object}) => {
  if (!object.existed()) {
    const acl = new Parse.ACL();
    object.setACL(acl);
  }
});
```

And Parse Server will automatically assign read and write access of request.user to itself.

**Comment by mtrezza** [comment]
That's a nice side-effect.
