### ISSUE TITLE
"schemaCacheTTL" ParseServerOption is not working

### ISSUE THREAD

**Issue by jack092123** [parse-community/parse-server#7119]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Issue Description
It seems `schemaCacheTTL` ParseServerOption is not working. It still follows cacheAdapter's setting.

### Steps to reproduce
ParseOption
`enableSingleSchemaCache`: true,
`schemaCacheTTL`: 3600000, (1hr)
`cacheAdapter`: RedisCacheAdapter

### Actual Outcome
After a simple request, I check the keys in Redis. The schema cache's TTL is 30 seconds which is the RedisCacheAdapter's default TTL.

###  Environment
Server
- Parse Server version: `4.3.0`
- Operating system: `MacOS`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `Local`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `3.6`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `Local`
---
I'm not quite sure, but I think the problem might be [here](https://github.com/parse-community/parse-server/blob/master/src/Controllers/SchemaCache.js#L33). It doesn't pass the TTL config to the cache.

**Comment by davimacedo** [comment]
@dplewis I actually don't see the schemaCacheTTL being used here: https://github.com/parse-community/parse-server/blob/e6ac3b6932186a6a85601c65143305f86f63e948/src/Controllers/SchemaCache.js

Thoughts?

**Comment by dplewis** [comment]
Check the constructor

**Comment by jack092123** [comment]
Hi @davimacedo @dplewis , is there any update?

The schemaCacheTTL was set to ttl at the constructor, but it doesn't pass to the cacheController at Line 33. I'm not sure is it the main problem here.

**Comment by davimacedo** [comment]
> Check the constructor

The constructor uses only the default value but not a value eventually passed via parse server options, right?

**Comment by dplewis** [comment]
Should be passed here
https://github.com/parse-community/parse-server/blob/e6ac3b6932186a6a85601c65143305f86f63e948/src/Config.js#L31

**Comment by davimacedo** [comment]
@jack092123 would you mind to test a failing test case?

**Comment by jack092123** [comment]
Hi @davimacedo, this is my first time reporting issue & writing a test script. So feel free to correct me if there is a mistake.

I add a failing test case to my forked repo here. So what should I do next? Summit a pull request?
https://github.com/jack092123/parse-server/blob/issue7119/spec/SchemaCache.spec.js

**Comment by davimacedo** [comment]
Yes. You can open a PR with the test. Are you willed to also investigate and try to send a fix?

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/5.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0](https://github.com/parse-community/parse-server/releases/tag/5.0.0)
