### ISSUE TITLE
Allow Cloud Validation "options" to be async

### ISSUE THREAD

**Issue by dblythy** [parse-community/parse-server#7140]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description

As mentioned by @Cinezaster [here](https://github.com/parse-community/parse-server/pull/6968#issuecomment-765251387), it is not possible to use async with a Parse.Cloud validator.

### Actual Outcome

Cloud function completes without running async validation

### Expected Outcome

Validator should wait to run options function

### Failing Test Case / Pull Request

- [x] 🤩 I submitted a PR with a fix and a test case.
- [x] 🧐 I submitted a PR with a failing test case.

Failing test:

```
it('set params options function async', async (done) => {
    Parse.Cloud.define(
      'hello',
      () => {
        fail('cloud function should not run.');
        return 'Hello world!';
      },
      {
        fields: {
          data: {
            type: Number,
            required: true,
            options: async val => {
              await new Promise((resolve, reject) => {
                setTimeout(resolve, 500);
              })
              return false;
            },
            error: 'Validation failed. Expected data to be between 1 and 5.',
          },
        },
      }
    );
    try {
    await Parse.Cloud.run('hello', { data: 7 })
    } catch (error) {
      expect(error.code).toEqual(Parse.Error.VALIDATION_ERROR);
      expect(error.message).toEqual('Validation failed. Expected data to be between 1 and 5.');
    }
    done();
  });
```

###  Environment

Server
- Parse Server version: `4.5.0`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `FILL_THIS_OUT`

Database
- System (MongoDB or Postgres): `FILL_THIS_OUT`
- Database version: `FILL_THIS_OUT`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `FILL_THIS_OUT`

**Comment by mtrezza** [comment]
Thanks for opening this issue.

It sounds reasonable to allow async validation. I understand from your [comment](https://github.com/parse-community/parse-server/pull/6968#issuecomment-765251387) that you are already working on a PR. Just to let others know that this is in the works.

**Comment by dblythy** [comment]
Yeah, thank you Manuel. Sorry I have been a bit busy lately and haven't been able to close out my other pending PRs. I'll tryi get to that.
