### ISSUE TITLE
I'm not able to upload a file to digital ocean spaces

### ISSUE THREAD

**Issue by KAIOAVILA** [parse-community/parse-server#7141]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description
I was trying to upload a file to digital ocean spaces and every time it displays the following error, after several attempts and logs, I ended up discovering that digital ocean spaces does not accept the x-amz-tagging header, so to get around this problem I added a option to address this problem.

I already created an issue on the parse-server-s3-adapter for this and a pr to solve this problem, as soon as they are released there, I would have to update the version of parse-server-s3-adapter here.

Issue: https://github.com/parse-community/parse-server-s3-adapter/issues/137
PR: Resolve https://github.com/parse-community/parse-server-s3-adapter/pull/138

### Steps to reproduce
Use digital ocean spaces to upload files

### Expected Outcome

`error: Error creating a file: {"code":"InvalidArgument","region":null,"time":"2021-01-24T03:40:07.704Z","requestId":"tx0000000000000c423031d-00600cec17-47cdf09-nyc3b","statusCode":400,"retryable":false,"retryDelay":41.84567606709386,"stack":"InvalidArgument: null\n at Request.extractError (/home/onemenu/one-parse/node_modules/parse-server/node_modules/aws-sdk/lib/services/s3.js:837:35)\n at Request.callListeners (/home/onemenu/one-parse/node_modules/parse-server/node_modules/aws-sdk/lib/sequential_executor.js:106:20)\n at Request.emit (/home/onemenu/one-parse/node_modules/parse-server/node_modules/aws-sdk/lib/sequential_executor.js:78:10)\n at Request.emit (/home/onemenu/one-parse/node_modules/parse-server/node_modules/aws-sdk/lib/request.js:688:14)\n at Request.transition (/home/onemenu/one-parse/node_modules/parse-server/node_modules/aws-sdk/lib/request.js:22:10)\n at AcceptorStateMachine.runTo (/home/onemenu/one-parse/node_modules/parse-server/node_modules/aws-sdk/lib/state_machine.js:14:12)\n at /home/onemenu/one-parse/node_modules/parse-server/node_modules/aws-sdk/lib/state_machine.js:26:10\n at Request.<anonymous> (/home/onemenu/one-parse/node_modules/parse-server/node_modules/aws-sdk/lib/request.js:38:9)\n at Request.<anonymous> (/home/onemenu/one-parse/node_modules/parse-server/node_modules/aws-sdk/lib/request.js:690:12)\n at Request.callListeners (/home/onemenu/one-parse/node_modules/parse-server/node_modules/aws-sdk/lib/sequential_executor.js:116:18)\n at Request.emit (/home/onemenu/one-parse/node_modules/parse-server/node_modules/aws-sdk/lib/sequential_executor.js:78:10)\n at Request.emit (/home/onemenu/one-parse/node_modules/parse-server/node_modules/aws-sdk/lib/request.js:688:14)\n at Request.transition (/home/onemenu/one-parse/node_modules/parse-server/node_modules/aws-sdk/lib/request.js:22:10)\n at AcceptorStateMachine.runTo (/home/onemenu/one-parse/node_modules/parse-server/node_modules/aws-sdk/lib/state_machine.js:14:12)\n at /home/onemenu/one-parse/node_modules/parse-server/node_modules/aws-sdk/lib/state_machine.js:26:10\n at Request.<anonymous> (/home/onemenu/one-parse/node_modules/parse-server/node_modules/aws-sdk/lib/request.js:38:9)\n at Request.<anonymous> (/home/onemenu/one-parse/node_modules/parse-server/node_modules/aws-sdk/lib/request.js:690:12)\n at Request.callListeners (/home/onemenu/one-parse/node_modules/parse-server/node_modules/aws-sdk/lib/sequential_executor.js:116:18)\n at callNextListener (/home/onemenu/one-parse/node_modules/parse-server/node_modules/aws-sdk/lib/sequential_executor.js:96:12)\n at IncomingMessage.onEnd (/home/onemenu/one-parse/node_modules/parse-server/node_modules/aws-sdk/lib/event_listeners.js:313:13)\n at IncomingMessage.emit (events.js:203:15)\n at IncomingMessage.EventEmitter.emit (domain.js:466:23)"}`

### Failing Test Case / Pull Request

- [x] 🤩 I submitted a PR with a fix and a test case.
- [x] 🧐 I submitted a PR with a failing test case.

###  Environment

Server
- Parse Server version: `4.5.0`
- Operating system: `Ubuntu 18.04`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `Digital Ocean`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `3.6.3`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `Local`

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): `JavaScript`
- SDK version: `2.17.0`

**Comment by mtrezza** [comment]
Thanks for reporting.

Can you give more details how this issue is related to https://github.com/parse-community/parse-server/issues/7129?

Also, see the discussion in
https://github.com/parse-community/parse-server-s3-adapter/issues/134 regarding the approach.

**Comment by KAIOAVILA** [comment]
I understand, I hadn't seen that this issue was open already, I'll close this one and see the other one
