### ISSUE TITLE
Log on invalid cloud validator configuration

### ISSUE THREAD

**Issue by dblythy** [parse-community/parse-server#7153]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation

If you mistype a configuration in the cloud validator, it can lead to cloud functions not functioning as expected, which could lead to further problems.

And example would be typing `requiredUser: true` instead of `requireUser: true`. As far as the developer is concerned, the cloud function is restricted to users only, but the setting has no effect as it's mistyped.

### Feature / Enhancement Description

A log if an unsupported validation configuration is entered, so that developers can be aware that the validator won't function as they expected.

`E.g: "requiredUser" is not a supported cloud validator parameter. See this link for a full list of cloud validator parameters.`

**Comment by mtrezza** [comment]
Sounds good! I think this would also be an interesting feature for the Parse Server config in the future.

**Comment by dplewis** [comment]
Closing via https://github.com/parse-community/parse-server/pull/7154
