### ISSUE TITLE
Add auto-re-register Cloud Code on file changes

### ISSUE THREAD

**Issue by dblythy** [parse-community/parse-server#7158]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation

Currently, when writing and testing cloud code, you have to restart your Parse Server whenever you make changes. There is no way to "watch" your Parse Server deployment.

### Feature / Enhancement Description

Have a `watchCloudCode: true` or similar testing method (`npm run watch`) that re-registers cloud code functions on file change via `fs.watch`.

### Example Use Case

When writing cloud code locally, it would be really handy to _not_ have to restart everytime you make changes.

### Alternatives / Workarounds

Use nodemon or restart Parse Server manually.

### 3rd Party References

[Discussed in the community forum](https://community.parseplatform.org/t/deploying-cloud-code/1227)

**Comment by mtrezza** [comment]
Thanks for suggesting.

While I think this is an interesting addition, I think it needs a more clearly defined scope. In what context is this this feature intended to be used and what are example use cases? If this is a feature that is also intended to be used in a production environment, how would it handle multiple instances behind a load balancer?

**Comment by dblythy** [comment]
It would be specifically for local deployments, to assist developers in writing their cloud code. 

It would _not_ be intended for multi-instance deployments. 

Ideally, it would watch all imported and referenced files and re-register all triggers after any referenced file changed. 

What do you think?

**Comment by mtrezza** [comment]
Sounds interesting indeed. A difference to `npm run watch` may be that it merely compiles the lib files, whereas this is changing the cloud code of a running server. Wouldn't the server just crash when a file is saved in the middle of half-developed code?

**Comment by dblythy** [comment]
You’re right - I referenced npm run watch as this ideally would be how it would function. With npm run watch, you can edit internal code and run test without restarting the server. The goal of this FR would be the same, that cloud functions would re-register if the files are changed without requiring a restart. 

As far as I can tell, cloud functions are registered on server start via requiring the Parse Cloud code. Currently, changing the files has no impact as the server has already started. Even deleting the files has no impact on a running server as the triggers are registered and stored in triggers.js. 

The goal of this PR would be to clear and reload the cloud triggers if any of the required files are mutated.

**Comment by mtrezza** [comment]
> With npm run watch, you can edit internal code and run tests without restarting the server.

Is that true, or does it only recompile the libs?

**Comment by dblythy** [comment]
> Is that true, or does it only recompile the libs?

Well, yeah, again you're right. `npm run watch` recompiles the libs, so that when the mock server is started in the tests, it runs off the lates lib code.

> You could try to restart the server after each file change event, if it's not running. But I'm not sure what side effects that may have if the server restarts on ever file save event.

Maybe, again this could be a feature for the example repo using `nodemon`. But i'm cautious of bloating it out with too many dependancies that mightn't be used.

**Comment by mtrezza** [comment]
I think the easiest way would be using babel to try to compile cloud code. If it succeeds, the server us unlikely to crash and the new cloud code can load. If it fails, assume the developer was just doing a save in between without intention to use the server. Also, babel is already there, so no new dependency.

**Comment by dblythy** [comment]
Closing as this feature is now available on the [example repo](https://github.com/parse-community/parse-server-example) using `npm run watch`

**Comment by byroncoetsee** [comment]
Sorry to re-open but, this feature might be available on the example repo but it isn't available as an option to `parse-server`...  is it?
