### ISSUE TITLE
Add tests against multiple MongoDB versions

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-server#7160]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation
Parse Server CI currently only tests against MongoDB 3.6.21 and 4.0.4.

- This does not reflect the variety of MongoDB versions in use in real word deployments.
- Parse Server may not be fully compatible with the MongoDB Atlas free tier anymore, which runs MongoDB 4.4.3. This means that the docs that describe how to quickly get started using MongoDB Atlas are not practical anymore for developers who just want to try out Parse Server, because they can only choose a paid tier.

### Feature / Enhancement Description
Keep the MongoDB versions for CI tests in sync with the officially supported MongoDB versions.

That means:
- Removing the CI tests for MongoDB 3.6 (EOL date April 2021) and instead test for the following 3 versions:

  | Version     | EOL Date     | Latest Patch Release |
  |-------------|--------------| - |
  | ~~MongoDB 3.6~~ | ~~April 2021~~   |~~3.6.21~~ |
  | MongoDB 4.0 | January 2022 | 4.0.22 |
  | MongoDB 4.2 | TBD          | 4.2.12 |
  | MongoDB 4.4 | TBD          | 4.4.3 |

- When a new patch version is released, update the CI test version as well.

In addition, the Readme should contain a MongoDB compatibility table to show against which MongoDB versions which version of Parse Server is tested against.

### Example Use Case
(none)

### Alternatives / Workarounds
(none)

### 3rd Party References
(none)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/5.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0](https://github.com/parse-community/parse-server/releases/tag/5.0.0)
