### ISSUE TITLE
countObjectsInBackgroundWithBlock  throwing: Permission denied for action count on class

### ISSUE THREAD

**Issue by OpConTech** [parse-community/parse-server#7175]
- [X] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [X] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [X] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [X] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description
Find query on Class works normally.
CountObjects query on the same Class throws permission denied error

Possible bug in version 4.5.0 when counting objects?

### Steps to reproduce

        PFQuery *query= [PFQuery queryWithClassName:@"Videos"];
        [query whereKey:@"videoType" equalTo:@"Hazards"];
        [query findObjectsInBackgroundWithBlock:^(NSArray * objects, NSError *error) {
            if (!error) {
                NSLog(@"Hazard Video Count Is: %lu", (unsigned long)objects.count);
            } else {
                NSLog(@"Error: %@ %@", error, [error userInfo]);
            }
        }];
        //
        // Returns:
        // Hazard Video Count Is: 184
        //

        PFQuery *query= [PFQuery queryWithClassName:@"Videos"];
        [query whereKey:@"videoType" equalTo:@"Hazards"];
        [query countObjectsInBackgroundWithBlock:^(int count, NSError *error) {
            if (!error) {
                NSLog(@"Hazard Video Count Is: %d", count);
            } else {
                NSLog(@"Error: %@ %@", error, [error userInfo]);
            }
        }];
        //
        // Throws Error:
        // Error Domain=Parse Code=119 "Permission denied for action count on class Videos."
        //

###  Environment

Server
- Parse Server version: 4.5.0
- Operating system: Node.js Express
- Local or remote host Heroku

Database
- System (MongoDB or Postgres): Mongo 
- Database version: 4.0.22
- Local or remote host MongoDB Atlas

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): iOS SDK
- SDK version: 1.19.1

**Comment by mtrezza** [comment]
Thanks for reporting.

Before we can process this, please check the required boxes in the template where appropriate. If you have any questions regarding these boxes, please let us know.

**Comment by dplewis** [comment]
Count is an expensive operation and has security risk, I would advise against using it. Check your CLP and see if count is enabled, if you need it.

<img width="1016" alt="Screen Shot 2021-02-10 at 10 42 18 PM" src="https://user-images.githubusercontent.com/9830365/107603130-70e0c080-6bf1-11eb-8a29-e1b8ecd77fbc.png">

**Comment by OpConTech** [comment]
Hmmm... my CLPs for this class (and other classes) jus show this:

![Screen Shot 2021-02-11 at 8 12 02 AM](https://user-images.githubusercontent.com/2111943/107664364-30a92e80-6c41-11eb-9c45-2db2ae3e7ddb.png)

**Comment by dplewis** [comment]
Glad it worked

**Comment by OpConTech** [comment]
Now that I was able check the  CLP .count box everything is working good again. 

Just to be complete, the way this happened was I bumped from 3.x to 4.5 and my counts stopped working. As I show in my post above the default CLP's for 4.5 seem to be default checked for everything in a Class except .count  

The only reason my code had been using .count for so many years was because I was under the impression that from a networking viewpoint that it was less expensive than .find  Based on your feedback I will probably change .counts to .finds.

So...just trying to be helpful make CLP's more intuitive. I know you all work very hard.  
Here is some feedback I hope is helpful:
- parse-dashboard:  Maybe replace the gear icon with just the Simple-Advance switch...Or maybe just get rid of all of that and show all the CLPs when the user clicks Security (keep it simple...less to code...less to test...less to document.)
Once I got the gear icon started working it worked every time. It's like some how in my browser it was stuck in the greyed out state and would not highlight black when I read the mouse over it.  

- Documentation: Maybe its time to have a parse-dashboard Guide. Parse docs have come a long way since Facebook gave Parse to the community except for parse-dashboard. Not sure why I had so much trouble but documentation does not show what the gear icon does (i suspected but jsquery or something was mucky on my browser)  and until I saw your screenshot I had now way of knowing for sure the .count CLS was in there. 

- CLPs / Protected Fields:  These are great features but the parse-server Docs are weak. (e.g. it seems like you can override email field in protected fields...but you can't and that is not spelled out anywhere...need to clearly document why have an override if you can't override email field)  Coupled with ACL its difficult for most devs to "see" the complete fop down security strategy that yourself @flovilmart and everyone has worked so hard to build out .  Maybe its time for a Security guide showing how how these work together with examples of best practices for securing a parse-server instance. 

Anyway thanks again for all the help and thanks for all your hard work on Parse it is greatly appreciated.

**Comment by dplewis** [comment]
Thanks for the feedback. Have you tried the latest version of the dashboard? Feel free to open feedback to their respective repos
