### ISSUE TITLE
Latest docker build fails - cannot find module `graphql-tag`

### ISSUE THREAD

**Issue by sibis** [parse-community/parse-server#7181]
- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description
The latest docker image has issue. looks like 'graphql-tag' package is missing

**Comment by mtrezza** [comment]
Thanks for reporting.

To report an issue, please use the issue template provided when you create an issue. The template asks for essential information which helps us to investigate the issue.

**Comment by sibis** [comment]
There is a new docker image released 10 hours ago. But it's breaking when I run it. 

Hope this information is enough. Apologies for not following the template format. Will do it from now

**Comment by mtrezza** [comment]
@sibis No worries, we are glad you are contributing by reporting this issue. Just to mention it, you could have just edited the issue here, would have been fine too. For reference, this discussion continues in https://github.com/parse-community/parse-server/issues/7182, I will mark this as duplicate.
