### ISSUE TITLE
Add benefits of PR to Contribution guide

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-server#7190]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation
The contribution guide could need some more personal motivation as to why opening a PR.

### Feature / Enhancement Description
Add a section that outlines the benefits of a PR vs. custom code solution.

---
Suggestion:

#### Why create a Pull Request?

Buy cheap, buy twice. What? No, this is not the Economics 101 class, but the same is true for Pull Requests.

There are two ways of writing a feature or fixing a bug. Sometimes the quick solution is to just fork or write a Cloud Code function that does what you want. The fallacy only becomes obvious when you think into the future.

Writing a pull request to make the change directly in Parse Server may take you longer than writing some quick custom solution. But it actually takes much less effort over time because of the benefits you get:

- 🚀 Higher efficiency: Your code is examined for efficiency and interoperability with existing features.
- 🛡 Tighter security: Your code is scrutinized for bugs and vulnerabilities by the community and automated security checks to identify any security issues that may arise in the future.
- 🧬 Continuous improvement: If your feature is used by others it is likely to be continuously improved and extended by the community. 
- 💝 Giving back: You give something back to the community that contributed to make the Parse Platform what it is today and for future developers to come.
- 🧑‍🎓 Improve yourself: You learn something new and better understand the inner workings of Parse Server. This will help you to write more efficient code for your own application.

Most importantly, with every pull requests you improve your skills so that in the future it will take you the same or even less time to write your feature directly in Parse Server. Then you get all the benefits above for free — easy choice, right?

If this is your first pull request or you are already an experienced contributor, the Parse Community is there to support you when you write it. Start off by opening a [new issue](#) or [feature suggestion](#), then create your [pull requests](#)! 🚀

### Example Use Case
(None)

### Alternatives / Workarounds
(None)

### 3rd Party References
(None)

**Comment by mtrezza** [comment]
@TomWFox what do you think and are you aware whether we have anything similar yet anywhere?

**Comment by dblythy** [comment]
I really like the suggestion. I think the more we do to make pull requests more accessible for new developers, the better for our community. 

I've said this before but Parse is the first project I've ever submitted a PR to, and I'd imagine a lot of our devs would be the same. I found it intimidating at first and avoided tackling bugs I'd found for literally 3 years, let alone features that I'd thought Parse could use. 

It would be a shame if there are other developers out there have ideas or have identified problems but find the project too overwhelming / helpless to share their concerns or to have a crack.

I think this is already written somewhere - but maybe highlight that the contribution doesn't have to be perfect, and the team will teach and help you improve your code if need be? Could highlight that all efforts are appreciated and we're a welcoming community and there's nothing to be shy about if you're not 100% confident with coding. For me it was a HUGE step from going to writing private cloud code which just has to work for me vs _code for the package that taught me to code_. I've learnt `.some` and object literal shorthand syntax through you guys reviewing my code.

**Comment by TomWFox** [comment]
I really like it, I must say I'd never really considered any benefits to the contributor beyond 'giving back' and self-improvement.

It feels like something that would be good to highlight before people get to the contributing guide as by that point they may already be considering making a PR, although even if they are it could reduce the chance of abandonment so happy for something like this to be added.

**Comment by mtrezza** [comment]
> It feels like something that would be good to highlight before people get to the contributing guide as by that point they may already be considering making a PR

Yes, maybe we can incorporate it in the issue template, but for sure it can be used during the issue conversation by just referencing to the chapter.

> Btw we can create a contribution guide in the .github repo, it might be nice to have one so we have all generally applicable info on all repos.

How would that play with the repo-specific instructions in the existing contribution guides?

**Comment by TomWFox** [comment]
> it can be used during the issue conversation by just referencing to the chapter.

Definitely, with all these improvements to the guide we should make sure to point people to it, for example when saying 'would you be willing to submit a PR?'

> How would that technically play with the repo-specific instructions in the existing contribution guides?

It would only be visible in repos which don't have an existing guide so unfortunately we can't have centralised general info and repo specific info (unless we used links to other documents).

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/5.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0](https://github.com/parse-community/parse-server/releases/tag/5.0.0)
