### ISSUE TITLE
Docker Container not starting: Cannot find module 'graphql-tag'

### ISSUE THREAD

**Issue by fastrde** [parse-community/parse-server#7195]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest version of Docker Container from parseplatform/parse-server

### Issue Description
The Docker Container not starts and throws the following error:
```
 Error: Cannot find module 'graphql-tag'
 Require stack:
 - /parse-server/lib/GraphQL/loaders/schemaDirectives.js
 - /parse-server/lib/GraphQL/ParseGraphQLSchema.js
 - /parse-server/lib/GraphQL/ParseGraphQLServer.js
 - /parse-server/lib/ParseServer.js
 - /parse-server/lib/index.js
 - /parse-server/lib/cli/parse-server.js
 - /parse-server/bin/parse-server
     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
     at Function.Module._load (internal/modules/cjs/loader.js:725:27)
     at Module.require (internal/modules/cjs/loader.js:952:19)
     at require (internal/modules/cjs/helpers.js:88:18)
     at Object.<anonymous> (/parse-server/lib/GraphQL/loaders/schemaDirectives.js:8:42)
     at Module._compile (internal/modules/cjs/loader.js:1063:30)
     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
     at Module.load (internal/modules/cjs/loader.js:928:32)
     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
     at Module.require (internal/modules/cjs/loader.js:952:19) {
   code: 'MODULE_NOT_FOUND',
   requireStack: [
     '/parse-server/lib/GraphQL/loaders/schemaDirectives.js',
     '/parse-server/lib/GraphQL/ParseGraphQLSchema.js',
     '/parse-server/lib/GraphQL/ParseGraphQLServer.js',
     '/parse-server/lib/ParseServer.js',
     '/parse-server/lib/index.js',
     '/parse-server/lib/cli/parse-server.js',
     '/parse-server/bin/parse-server'
```

It looks like Package `graphql-tag` is not a devDependency (as referred in `package.json`) but a normal dependency.
When you install `parse-server` directly `graphql-tag` got installed as an dependency by `apollo-server-core`

### Steps to reproduce
spin up Docker Container from `parseplatform/parse-server`

### Actual Outcome
Parse Server not starting correctly in Docker Container

### Expected Outcome
Parse Server starts

### Possible Solution
move `graphql-tag` dependency from *devDependencies* to *dependencies* in `package.json`

**Comment by davimacedo** [comment]
Duplicated with https://github.com/parse-community/parse-server/issues/7182
