### ISSUE TITLE
ERR_HTTP_HEADERS_SENT when throw an Error in validateAuthData 

### ISSUE THREAD

**Issue by Etto91** [parse-community/parse-server#7200]
### New Issue Checklist

- [ ] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [ ] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description

i'm trying to implement a custom authentication module. Every time validateAuthData function throw an error, the response from the server is 

`{"code":1,"message":"Internal server error."}`

and the server log is

`ParseError: 101 Instagram auth is invalid for this user.
    at Object.validateAuthData (/Users/lib/webpack:/app.js:28:9)
    at /Users/node_modules/parse-server/src/Adapters/Auth/index.js:66:20
    at /Users/node_modules/parse-server/src/RestWrite.js:430:12
    at Array.map (<anonymous>)
    at RestWrite.handleAuthDataValidation (/Users/node_modules/parse-server/src/RestWrite.js:419:45)
    at /Users/node_modules/parse-server/src/RestWrite.js:560:17
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: 101
}
Error [ERR_HTTP_HEADERS_SENT] [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:543:11)
    at ServerResponse.header (/Users/node_modules/express/lib/response.js:767:10)
    at ServerResponse.send (/Users/node_modules/express/lib/response.js:170:12)
    at done (/Users/node_modules/express/lib/response.js:1004:10)
    at Object.exports.renderFile (/Users/node_modules/pug/lib/index.js:422:12)
    at View.exports.__express [as engine] (/Users/pug/lib/index.js:465:11)
    at View.render (/Users/node_modules/express/lib/view.js:135:8)
    at tryRender (/Users/node_modules/express/lib/application.js:640:10)
    at Function.render (/Users/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/Users/node_modules/express/lib/response.js:1008:7)`
    
with Fastify, it causes the server to crash. Express doesn't crash.

### Steps to reproduce

This is the module and i reproduce the error from the parse dashboard copying and pasting an object in the authData column in User class

```
function validateAuthData({ token, storeCode, id }) {
  throw new Parse.Error(
    Parse.Error.OBJECT_NOT_FOUND,
    "Instagram auth is invalid for this user."
  );
}

function validateAppId() {
  return Promise.resolve();
}

var api = new ParseServer({
  auth: {
    mAuth: {
      module: { validateAuthData, validateAppId },
    },
  },
  databaseURI:
    process.env.MONGODB_URI, Connection string for your MongoDB database
  cloud: process.env.CLOUD_CODE_MAIN || __dirname + "/cloud.js", 
  appId: process.env.APP_ID,
  masterKey: process.env.MASTER_KEY,
  javascriptKey: process.env.JAVASCRIPT_KEY ,
  serverURL: process.env.SERVER_URL,
});
```

### Expected Outcome

I don't know if i'm doing something wrong but it seems that there is something wrong with the error handling
### Failing Test Case / Pull Request

- [ ] 🤩 I submitted a PR with a fix and a test case.
- [ ] 🧐 I submitted a PR with a failing test case.

###  Environment

Server
- Parse Server version: `4.5.0`
- Operating system: `mac`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `Local`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `FILL_THIS_OUT`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `MongoDB Atlas`

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): `FILL_THIS_OUT`
- SDK version: `FILL_THIS_OUT`

**Comment by davimacedo** [comment]
Thanks for reporting. Would you be willed to send a PR with a failing test case and help to fix the problem?
