### ISSUE TITLE
Add custom route building

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-server#7230]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation
Currently, the experimental `PagesRouter` (like the `PublicAPIRouter`) has built-in routing and pages logic for the features:
- password reset
- email verification

It does not allow to add custom routes while using the logic that is already provided in the router in combination with the Parse Server internal `PromiseRouter`. Instead, developers usually have to write custom routes from scratch that exist beside the `PagesRouter`.

### Feature / Enhancement Description
Allow to easily add custom routes while leveraging the router's capabilities. This allows to easily create complex user flows as a combinations of HTML pages and Parse Server logic. It allows to customize the password reset and email verification routes or create new custom-purpose routes.

### Example Use Case
- Require a user to enter additional parameters for a password reset.
- Add a flow for users to change their email address by entering their old email, new email and password.
- Require a user to enter an additional password to verify their email address to prevent link-sharing.

### Alternatives / Workarounds
Developer implements custom routes without the benefits of the `PagesRouter` features such as localization and in possible conflict with built-in routes.

### 3rd Party References
(none)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/5.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0](https://github.com/parse-community/parse-server/releases/tag/5.0.0)
