### ISSUE TITLE
Password reset, email verification not working with custom pages endpoint

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-server#7235]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description
Originally reported by @mman in https://github.com/parse-community/parse-server/issues/7210#issuecomment-788041254.

> the PagesRouter must be mounted on /apps otherwise it will break the password reset logic (since UserController.js seems to be ignoring the pages router mount path.

This is true for password reset and email verification.

### Steps to reproduce
1. Use experimental pages router
2. Set custom pages endpoint that is not `apps`
3. Request a password reset link --> link is incorrect

### Actual Outcome
Link is incorrect because it contains the default endpoint `apps`.

### Expected Outcome
Link should contains the custom pages.

### Failing Test Case / Pull Request

- [x] 🤩 I submitted a PR with a fix and a test case.
- [ ] 🧐 I submitted a PR with a failing test case.

###  Environment

Server
- Parse Server version: `master #3833868`
- Operating system: `-`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `- `

Database
- System (MongoDB or Postgres): `-`
- Database version: `-`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `-`

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): `-`
- SDK version: `-`

### Logs

(none)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/5.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0](https://github.com/parse-community/parse-server/releases/tag/5.0.0)
