### ISSUE TITLE
Add Search to Aggregate pipeline

### ISSUE THREAD

**Issue by BRETT71** [parse-community/parse-server#7238]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation

Can not use the `$search` operator in aggregate pipelines

### Feature / Enhancement Description

MongoDB Atlas has a search index for collections. You can find out more [here](https://www.mongodb.com/atlas/search). The way you use your search index is through aggregate. Right now if you add search to your pipeline parse throws an error.

**You have to have mongo 4.2 and above and have MongoDB hosted on atlas.**

### Example Use Case

1. Searching people
2. Searching posts
etc. (anything that you need to search)

### Alternatives / Workarounds

Right now you have to use parse fulltext search which just uses a text index. You do not get fuzzy search and autocomplete

**Comment by BRETT71** [comment]
Pull Request #7237

**Comment by dplewis** [comment]
The pipeline keys haven't been updated since Mongo 3.2. I believe we can remove that check to support all stages now and future additions to mongo. What do you think?

**Comment by BRETT71** [comment]
I like that Idea. Do you want me to update my PR to remove that check?

**Comment by dplewis** [comment]
Go for it

**Comment by BRETT71** [comment]
@dplewis Do you think that adding a search query to parse would be something useful or is doing a search through aggregate good enough?

**Comment by dplewis** [comment]
We have fullText search builtin to the Server.

**Comment by BRETT71** [comment]
Right, I understand that. I was just thinking that it would make it easier for people to use their search indexes in Parse. For example in the JS SDK the API could look like this:

``` js
const searchText = 'cool text for search 03/03/21';

const Post = Parse.Object.extend("Post");
const postQuery = new Parse.Query(Post);

const searchQuery =
{
  text: {
    path: ['body', 'title', 'postDate'],
    query: searchText,
    fuzzy: {
      maxEdits: 1, 
      prefixLength: 2, 
      maxExpansion: 100
    }
  }
};

const res = await postQuery.search(searchQuery);

// autocomplete
const searchQuery =
{
  autocomplete: {
    path: 'title',
    query: searchText,
    tokenOrder: 'any|sequential',
    fuzzy: {
      maxEdits: 1, 
      prefixLength: 2, 
      maxExpansion: 100
    }
  }
};

// true denoting that this search is a autocomplete search
const res = await postQuery.search(searchQuery, true);
```

I do understand if you think that this would be overkill for Parse Server.

**Comment by dplewis** [comment]
closing via https://github.com/parse-community/parse-server/pull/7237
