### ISSUE TITLE
Add security checks

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-server#7246]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation
Parse Server does not give any guidance in regards to weak security settings.

- Helps developers with existing apps to secure deployment.
- Helps new apps transitioning from a "playground" environment to a production environment.

Originally discussed in the [community forum](https://community.parseplatform.org/t/parse-security-how-to-improve-default-security/924/19).

### Feature / Enhancement Description
Add security report for developer to easily identify common weak security settings. While there are endless discussions possible about how "weak" a setting has to be to be considered security relevant, this feature should at least identify obvious weaknesses (e.g. a password of 5 characters). Gradually evolving, the security check can be parametrized according to individual policies, although that is not the aim of an initial version.

The feature is expected to develop in phases:
1. Writing security report to Parse Server logs
2. Displaying security report in Parse Dashboard
3. Parametrization of security check according to individual policy

The checks can be continuously extended over time. Adding a feature-specific security check shall become a mandatory consideration whenever adding new features to Parse Server, just as writing test cases or docs.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/5.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0](https://github.com/parse-community/parse-server/releases/tag/5.0.0)
