### ISSUE TITLE
Improve changelog design

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-server#7252]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation
The changelog needs a redesign because:
- Low readability
- Duplicate wordings (fix..., fix..., fix...)

### Feature / Enhancement Description
A design similar to the [Node.js changelog](https://github.com/nodejs/node/blob/master/CHANGELOG.md).

### Example Use Case
(n/a)

### Alternatives / Workarounds
(n/a)

### 3rd Party References
- [Node.js changelog](https://github.com/nodejs/node/blob/master/CHANGELOG.md)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/5.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0](https://github.com/parse-community/parse-server/releases/tag/5.0.0)
