### ISSUE TITLE
Parse-Server cannot be installed without Node.JS (bootstrap.sh installation method)

### ISSUE THREAD

**Issue by DevDorrejo** [parse-community/parse-server#7254]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description

Trying to install parse with all dependencies installed, but it fail after accept assign the install Dir.

### Steps to reproduce

```
sh <(curl -fsSL https://github.com/parse-community/parse-server/blob/master/bootstrap.sh)
Enter an installation directory
(/): /opt/parse-server

This will setup parse-server in /opt/parse-server
Do you want to continue? (Y/n):Y

**parse-server cannot be installed without Node.js.**
```

### Expected Outcome

Successful installation

###  Environment

Server
- Parse Server version: Latest
- Operating system: OpenSUSe Tumbleweed
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): local
- NodeJS: v15.8.0
- NPM: 7.5.1

Database
- System (MongoDB or Postgres): Postgres
- Database version: 13
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): local

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): none
- SDK version: none

### Logs

parse-server cannot be installed without Node.js.

**Comment by dplewis** [comment]
Do you have node properly installed? Can you run `node -v`?

Your problem is here -> https://github.com/parse-community/parse-server/blob/master/bootstrap.sh#L28

**Comment by dplewis** [comment]
Can you fork the project and run it locally?

`which node 2>&1` is the path to node
`if [ $ret -eq 0 ] && [ -x "$node" ];` means if there is a path to node && -x (execute) node

We can change the script if need be.

**Comment by DevDorrejo** [comment]
i put set -x

```
+ INSTALL_DIR=
+ printf 'Enter an installation directory\n'
Enter an installation directory
+ printf '(%s): ' /
(/): + read -r INSTALL_DIR
/opt/parse-server
+ '[' /opt/parse-server = '' ']'
+ echo ''

+ printf 'This will setup parse-server in %s\n' /opt/parse-server
This will setup parse-server in /opt/parse-server
+ confirm Y 'Do you want to continue? (Y/n): '
+ DEFAULT=Y
+ shift
+ printf 'Do you want to continue? (Y/n): '
Do you want to continue? (Y/n): + read -r YN
Y
+ '[' Y = '' ']'
+ '[' Y '!=' '' ']'
+ '[' Y '!=' y ']'
+ '[' Y '!=' Y ']'
+ check_node
++ which node
+ node='parse.sh: line 30: which: command not found'
+ ret=127
+ '[' 127 -eq 0 ']'
+ echo 'parse-server cannot be installed without Node.js.'
parse-server cannot be installed without Node.js.
+ exit 1

```

but 
```

which node
/usr/bin/node

```

**Comment by DevDorrejo** [comment]
weird, some how which is working, but not installed and this was creating a false positive.

reinstalling `which` made the script work

**Comment by DevDorrejo** [comment]
but the version of the bootstrap is 3.9 uhhh

**Comment by dplewis** [comment]
We should automate it for sure

**Comment by DevDorrejo** [comment]
yeah, but thanks for the help, i will close the ticket.
