### ISSUE TITLE
Allow logout with invalid session

### ISSUE THREAD

**Issue by dblythy** [parse-community/parse-server#7277]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation

Currently, if your session token becomes corrupted, even logging out returns "invalid session token", or "Session token is expired", meaning for most users there's no way to resolve this issue without force quitting / reinstalling.

### Feature / Enhancement Description

Invalid Session Tokens shouldn't prevent users from logging out and `Parse.User.current()` from clearing. Even with an invalid session, `logout` should allow users to re-login.

### 3rd Party References

[Discussed here](https://community.parseplatform.org/t/logout-user-with-expired-session/1458)

**Comment by cbaker6** [comment]
Definitely can cause an issue on the client side. I did in fix in https://github.com/parse-community/Parse-Swift/pull/73

which essentially clears the user from the Keychain ignoring any server errors:

https://github.com/parse-community/Parse-Swift/blob/a99bf31f59dba033888220afaeeb84835f3abd34/Sources/ParseSwift/Objects/ParseUser.swift#L296-L305

**Comment by dblythy** [comment]
My thoughts are that if an invalid session is provided to the logout request, it should return with a "success" so current user can be cleared internally, and developer can redirect to login screen. It would just mean logout cloud triggers wouldn't fire for invalid sessions, as there would be no way to tell who the "real" user is who making the request is.

What do you think?

**Comment by cbaker6** [comment]
That sounds good to me because it seems the user is "attempting" to discard their current session token by logging out.

If the server does what you mention, then the other client SDKs wouldn't have to implement something similar to what I have above.

The only issue they would run into is if a different error from the server occurs.

**Comment by cbaker6** [comment]
> that's interesting because obviously a different error could occur here too.

Looks like we were thinking the same thing!

**Comment by dblythy** [comment]
Interestingly in the [JS guide](https://docs.parseplatform.org/js/guide/#handling-invalid-session-token-error) it recommends calling `Parse.User.logOut()` to handle invalid sessions, which won't currently work.

**Comment by cbaker6** [comment]
> Interestingly in the JS guide it recommends calling Parse.User.logOut() to handle invalid sessions, which won't currently work.

It seems if the JS SDK isn't doing something similar to ParseSwift, the user will get stuck in limbo unless there's another method JS provides to clear the Keychain. Or, delete the app as you suggested...

**Comment by mtrezza** [comment]
> My thoughts are that if an invalid session is provided to the logout request, it should return with a "success" so current user can be cleared internally

This should be handled by the client application or the client SDK. Making the server "lie" about the result of an operation prohibits the client SDK or client application to perform more complex operations. We discussed a similar issue in https://github.com/parse-community/parse-server/security/advisories/GHSA-cfgm-jqhh-xmhr#advisory-comment-64808.

The communication between the server and the client should be truthful, the communication between the SDK and the client application as well. The communication between the client application and the user can be as opaque as the developer prefers and needs for their use case.

> Interestingly in the JS guide it recommends calling Parse.User.logOut() to handle invalid sessions, which won't currently work.

This seems to be the actual bug the needs to be addressed.

**Comment by dblythy** [comment]
> This seems to be the actual bug the needs to be addressed, and maybe in other SDKs as well.

So you would suggest catching the error in the logout request in the JS SDK?

**Comment by mtrezza** [comment]
I suggest that the SDK properly cleans up the cached current user, but reports to the client application truthfully, that the logout failed.

**Comment by dblythy** [comment]
So, if I have:

```javascript
await Parse.User.logOut();
window.location.href = '/login';
```

Would I have to wrap that in:

```javascript
try {
  await Parse.User.logOut();
  window.location.href = '/login';
} catch (e) {
  if (e.code === 209) {
    window.location.href = '/login';
  }
  alert(e.message);
}
```

**Comment by mtrezza** [comment]
Yes. And this allows another developer to not redirect to `/login` but do something completely different, depending on their use case.

**Comment by dblythy** [comment]
Infact, that's how the code functions as is:

```javascript
it('can logout with expired session token', async () => {
    await Parse.User.signUp('asdf', 'zxcv');
    const sessionQuery = new Parse.Query(Parse.Session);
    const session = await sessionQuery.first({ useMasterKey: true });
    const database = Config.get(Parse.applicationId).database;
    await database.update(
      '_Session',
      { objectId: session.id },
      { expiresAt: new Date().setFullYear(2010) },
      {}
    );
    try {
      await Parse.User.logOut();
      fail('should have returned invalid session');
    } catch (e) {
      expect(e.code).toBe(209);
      expect(Parse.User.current()).toBe(null);
    }
  });
```

It's my opinion that this is still a little clunky, and perhaps a `response` of "invalid session" can be passed if the logout request contains an invalid session. The logout is still successful, the `invalid session token` does not prevent the logout action from completing.

**Comment by dblythy** [comment]
Also the docs might need to updated to:

```javascript
function handleParseError(err) {
  switch (err.code) {
    case Parse.Error.INVALID_SESSION_TOKEN: {
      try {
        Parse.User.logOut();
      } catch (e) {
        if (e.code !== 209) { 
          handleParseError(e);
        }
      }
      ... // If web browser, render a log in screen
      ... // If Express.js, redirect the user to the log in route
      break;

    ... // Other Parse API errors that you want to explicitly handle
  }
}

// For each API request, call the global error handler
query.find().then(function() {
  ...
}, function(err) {
  handleParseError(err);
});
```

**Comment by mtrezza** [comment]
> It's my opinion that this is still a little clunky

How so?

**Comment by dblythy** [comment]
If you're using an app, and all your errors are "your session has expired", and you think "ok, I need to log back out", then you go and click "logout", and unless the Parse developer is aware of the way logout works with invalid sessions, you get the error message "your session has expired" (which you already know - that's why you're logging out).

I would assume that most developers aren't catching specifically for error code 209 in their logout calls, which I could imagine would lead to frustration with end users. I know I wasn't. Maybe this just requires a doco improvement.

**Comment by mtrezza** [comment]
The actual inconsistency for me is that the local cache is cleared if `logout` throws `209`, but not if any other request throws `209`. If the local cache was cleared on any `209` regardless of the type of request, there would be no need for the developer to call `logout` on invalid session token.

I see three possible approaches:
- a) Clear the local cache on any `209` regardless of request type
- b) Never clear the local cache unless the user logs in or the developer explicitly clears it with a method like `clearLocalCache` (which may not exist yet)
- Clear the local cache only on `logout` with `209` but not on other requests with `209`, documenting this "special behavior" in the docs

I would go with a) unless we can think of any reason why a user should stay locally logged in although the authoritative entity (Parse Server) says the token is not and will never ever become valid again.

**Comment by dblythy** [comment]
> The actual inconsistency for me is that the local cache is cleared if logout throws 209

I'm not sure if that's the case. I've been trying to figure out how it works in the JS SDK.

> Now I can think of a use case where an app is offline, the user does some operations

Theoretically a developer could temporarily store the invalid user alongside the cached operations and ask the user to confirm the tasks once the session is revalidated.

Perhaps there's no need for any change on the server.

I probably still haven't explained properly but by clunky I mean it's sorta unintuitive that to handle invalid sessions, we recommend calling `Parse.User.logOut()`, which needs to be wrapped in a catch because an invalid session token error will be thrown. Effectively calling `Parse.User.logOut()` does nothing server side in this case.

**Comment by dblythy** [comment]
We could also add something to the SDK such as `Parse.User.logOut({muteInvalidSession: true})`

**Comment by mtrezza** [comment]
> So, I think the existing behaviour is fine, we just need to change Parse.User.logOut(); in the "handling invalid sessions" with Parse.User._clearCache() (as this does everything logout does locally without throwing). That way, if an invalid session error is thrown from the user clicking logout, the handleParseError will detect it, clear user cache, and redirect to login.

That sounds like approach b) and it seems to be a clean approach because it separates the `logout` functionality from the session clearing. However, if the session clearing is unrelated to pinning objects and resuming operations once the user reauths, I would still go with a) if the session cache is only managed and relevant internally for the SDK and opaque to the developer, because then the question would be, why does the developer have to care about the SDK's session clearing?

**Comment by dblythy** [comment]
Closing as I see this more as a JS SDK discussion.
