### ISSUE TITLE
WebAssembly and/or Docker Cloud Code functions

### ISSUE THREAD

**Issue by sahilpohare** [parse-community/parse-server#7297]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation

The current cloud functions are only limited to using Javascript as its language which limits the performance enhancements
that can be done to the functions. It also limits their usage to people with JS knowledge. 

#### WASM
The ability to use WebAssembly cloud functions will allow lower memory usage and higher number of functions to run on
the server (Ofc depending on the quality of code and the language chosen). Also will make it usable for heavy multithreaded backend tasks. Will allow things like [Tensorflow ](https://www.tensorflow.org/) to run natively (not exactly but its close) as functions on Parse.

I know and understand that I can call C++ in nodejs but the WASM functions I am talking about will be deliverable over http API. 
being able to register a WASM function with the Parse API exposed to it like in firebase.

#### The Second Option is Docker
Docker will bring in another set of features to parse server. The control over environment and being able to use containers as functions would be amazing. Firebase already has this with Cloud Run and AWS Lambda too. 
I would love if this comes to parse in some form

#### Consequences
This will allow Parse to become something more than just an mBAAS and turn it into a complete serverless system. 
Parse could become an aggregator for different serverless services.   

### Example Use Case

An example usecase would be if I wanna train a tensorflow model on parse. Like a mobile service that allows you to retrain facial detection models or language, I do not wanna expose any server code to the developer. Just the functions folder. 

### Alternatives / Workarounds

For Tensorflow I can always go with python-shell but that's installing dependencies inside server code and I don't like that. I like these things to be limited to the functions folder. 

### 3rd Party References

I have seen AWS Lambda and Firebase use Docker container serverless functions. IDK about WASM though but sounds cool if WASM Functions were a thing. For Functions that dont need full fledged Virtual Environment backing it.

**Comment by mtrezza** [comment]
Thanks for suggesting.

WASM is being designed to run in JavaScript VM environments and be importable like ES2015 modules. It should be possible to run WASM modules without any change in Parse Server. Parse Server is written in JS anyway, so there is no easy way to avoid JS unless coding Parse Server entirely from scratch into a WASM module.

Can you explain in a bit more detail what and why you suggest to change in Parse Server?

**Comment by mtrezza** [comment]
I'm closing this issue because it seems to be answered.

If you have any questions please feel free to comment and we can re-open the issue.
