### ISSUE TITLE
Discord server

### ISSUE THREAD

**Issue by sadortun** [parse-community/parse-server#7301]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation

- There is no way to chat/talk to other members 
- GitHub issues are very good to keep a public record of everything, but not everything need to be discussed here.
- New community members can have a hard time to get answers.

### Feature / Enhancement Description

I've created a Discord server :
###  https://discord.gg/8N7aFdrtE9  

If you are interested, feel free to join :) 

 For the moderators @dplewis @mtrezza, just let me know and ill add you as Admin(s).

If you are OK with this, i can submit a few PRs to add links to the server to the README(s) and Github Issue template

**Comment by mtrezza** [comment]
Thanks for suggesting.
I'm closing this as it does not seem to be related to Parse Server but to the community.

These topics are better suited in our [Community Forum](https://community.parseplatform.org), please feel free to open a new topic there for discussion.

**Comment by sadortun** [comment]
Done. https://community.parseplatform.org/t/official-discord-server/1506

Hope it get officially endorsed, supported and maintained by Parse Platform :)

**Comment by mtrezza** [comment]
Thanks, I'm looking forward to the discussion.
