### ISSUE TITLE
Add centralized deprecation

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-server#7302]
## New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

## Current Limitation
Currently, there is no mechanism provided to deprecate Parse Server settings. With the shift to [phased deprecation](https://github.com/parse-community/parse-server/pull/7199) as part of the larger implementation of [fixed release cycles](https://github.com/parse-community/parse-server/issues/7271), it is not clear how to communicate deprecations.

## Feature / Enhancement Description
Introduce a centralized `Deprecator` that standardizes warning logs for deprecated Parse Server options. This should also make it easy for contributors to identify deprecations to adapt contributions accordingly, and for example not build on top of a feature without knowing that it will be deprecated.

## Example Use Case
The option `directAccess` default should change from `false` to `true` in #6636.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/5.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0](https://github.com/parse-community/parse-server/releases/tag/5.0.0)
