### ISSUE TITLE
Use jwks-rsa 2.x to get their async/await methods, for simpler code

### ISSUE THREAD

**Issue by olleolleolle** [parse-community/parse-server#7304]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description

👋 Hello, I hope this "this is a hunch for avoiding some complexity" Issue sits in the right place.

The dependency jwks-rsa has a new interface: its client methods are now no longer callbacks but directly `await`able things. We no longer need to use `promisify()` around them. 

Using this new 2.x version would simplify our code.

Upgrade guide (this is the one thing in the guide which impacts us):
https://github.com/auth0/node-jwks-rsa/blob/master/CHANGELOG.md#migrated-callbacks-to-asyncawait

New Requirement: Node 10+.

I can see in package.json that 8+ is in our "engines". Can that be bumped?

Locations in our code where used: facebook, apple auth adapters.

- https://github.com/parse-community/parse-server/blob/92f50f6808e3e4067829fa65b7611bd986038c0b/src/Adapters/Auth/facebook.js#L55
- https://github.com/parse-community/parse-server/blob/033a0bd443ba846fa5a7fae969eb8f71cf492162/src/Adapters/Auth/apple.js#L12

### Steps to reproduce

Well, one can try installing parse-server with yarn and there are notes about 

### Actual Outcome

Um, existing code.

### Expected Outcome

It would be simpler code to use the new API. Also, they dropped the Axios dep.

### Failing Test Case / Pull Request

Sorry, no test case.

- [ ] 🤩 I submitted a PR with a fix and a test case.
- [ ] 🧐 I submitted a PR with a failing test case.

###  Environment

Server
- Parse Server version: `4.5.0`
- Operating system: `Linux`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `local`

Database
- System (MongoDB or Postgres): `mongo`
- Database version: `idk`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `local`

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): `javascript`
- SDK version: `idk`

### Logs

(No logs.)

**Comment by mtrezza** [comment]
Thanks for suggesting.

Parse Server is officially compatible and tested with Node 10, so bumping the engine version to >=10 should be fine.

Would you want to start a PR?

**Comment by dplewis** [comment]
Closing as jwks-rsa 3.1.0 is currently used
