### ISSUE TITLE
Add CI check for package-lock

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-server#7326]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description
Current, the repo takes the user generated package-lock as is. If package-lock is created by user in local environment with npm 7, there may be issue with older npm versions.

See:

- https://github.com/parse-community/parse-server/pull/7079#issuecomment-816485747

### Suggestion

Add CI check that validates package-lock version.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/5.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0](https://github.com/parse-community/parse-server/releases/tag/5.0.0)
