### ISSUE TITLE
Add CI check for docker image building

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-server#7327]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation
Certain package configs can cause building the docker image to fail. For example, adding a local dependency with a relative, local path, see:

https://github.com/parse-community/parse-server/pull/7324#issuecomment-816336796

### Feature / Enhancement Description
Add CI check that tries to build a docker image.

### Alternatives / Workarounds
- Test manually via policy

### 3rd Party References
n/a

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/5.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0](https://github.com/parse-community/parse-server/releases/tag/5.0.0)
