### ISSUE TITLE
Deprecation warning for listening on Db class events

### ISSUE THREAD

**Issue by Moumouls** [parse-community/parse-server#7345]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [ ] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description
Lot of warning from mongodb package after upgrade from https://github.com/parse-community/parse-server/pull/7322

### Steps to reproduce
Install parse from master
Run parse server

At each server start parse server log.
```
(node:13319) DeprecationWarning: Listening to events on the Db class has been deprecated and will be removed in the next major version.
```

### Actual Outcome
Too many logs from mongodb pkg
```
(node:13319) DeprecationWarning: Listening to events on the Db class has been deprecated and will be removed in the next major version.
```
### Expected Outcome
No logs

### Failing Test Case / Pull Request

- [ ] 🤩 I submitted a PR with a fix and a test case.
- [ ] 🧐 I submitted a PR with a failing test case.

###  Environment

Server
- Parse Server version: current master
- Operating system:  macOS
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): local

Database
- System (MongoDB or Postgres): Mongo
- Database version: `4.4.X`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): local

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc):  none
- SDK version: node

**Comment by Moumouls** [comment]
downgrade to mongo 3.6.3 fix the issue, but it's just a temporary fix. I do not know which Parse Server code use DB listening events. @dplewis @mtrezza  if you have an idea 🙂

**Comment by mtrezza** [comment]
Thanks for reporting!

Can you please fill out the versions in the template so we know in what environment you are experiencing this issue?

**Comment by Moumouls** [comment]
@mtrezza it seems to come from the native mongo driver: https://stackoverflow.com/questions/66190532/deprecationwarning-listening-to-events-on-the-db-class-has-been-deprecated-and

All version >3.6.3 seems to raise this log.

**Comment by mtrezza** [comment]
[This](https://developer.mongodb.com/community/forums/t/node-44612-deprecationwarning-listening-to-events-on-the-db-class-has-been-deprecated-and-will-be-removed-in-the-next-major-version/15849/4) seems to explain the fix needed:

> Db is no longer the place to listen to events, you should listen to your MongoClient instead like so:
>
>const client = new MongoClient(…)
client.on(‘Event name I want to listen too’, () => {…})
await client.connect()
>
>The reason for this style is because by registering your listeners before connecting you can be sure that you’re able to capture every event that is triggered

**Comment by mtrezza** [comment]
I classified this as bug with severity S4 (small/trivial):
- Using deprecated APIs should be avoided, therefore it is considered a bug
- Because it is only a warning without any current function effects, it is only considered a small / trivial bug

**Comment by rocxteady** [comment]
Wasn't this fixed with: #7626? Why is it open still?

**Comment by mtrezza** [comment]
@Moumouls can you confirm this was fixed? #7626 does not reference this issue, but it also says that there are no more deprecation warnings, so I want to make sure.

**Comment by rocxteady** [comment]
I did not pull and try with master branch but with the same changes I get no depreciation warnings in an example project.

**Comment by mtrezza** [comment]
I assume we can close this then, thanks for the heads up.

**Comment by rocxteady** [comment]
You're welcome. Thank you for the good work.

**Comment by Moumouls** [comment]
hi @mtrezza  technically we are okay now about warnings :)

**Comment by mtrezza** [comment]
Nice, thanks @Moumouls
