### ISSUE TITLE
GraphQL reassign issue

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-server#7348]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description
As reported by @Moumouls in PR https://github.com/parse-community/parse-server/pull/7344:

On our production system recently, we faced some weird random issue on types shared between custom and auto gql schema.

The issue come from the merge system that i designed, it seems that some JS ref object mess up during merge process.
Also i removed the stichSchema with merge directive because it seems use less when a code custom schema is used.

Also i do not succeed reproducing the issue on Parse server test and even in our production test suite. My team only succeed to reproduce the issue with manual e2e testing, and this fix resolve the random issue.

### Failing Test Case / Pull Request

- [ ] 🤩 I submitted a PR with a fix and a test case.
- [ ] 🧐 I submitted a PR with a failing test case.

###  Environment

Server
- Parse Server version: `FILL_THIS_OUT`
- Operating system: `FILL_THIS_OUT`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `FILL_THIS_OUT`

Database
- System (MongoDB or Postgres): `FILL_THIS_OUT`
- Database version: `FILL_THIS_OUT`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `FILL_THIS_OUT`

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): `FILL_THIS_OUT`
- SDK version: `FILL_THIS_OUT`

**Comment by Moumouls** [comment]
yes @mtrezza

**Comment by mtrezza** [comment]
Great! Can I add you to the Parse Server review team? You'd get notifications when PRs are ready for review and if you have time you could look over it.
