### ISSUE TITLE
Cloud Code validator issue with required: false

### ISSUE THREAD

**Issue by hej2010** [parse-community/parse-server#7354]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description

The `required` field in the Cloud Code validator is not working as expected. When a parameter is set as required=false, no value for that parameter is sent to the cloud function and no default value is set then the type checking and options checks should not run. They should only run when a value is sent. 

### Steps to reproduce

Define a cloud function and a validator function, e.g.:
```
Parse.Cloud.define("function", async req => {
....
}, {
fields: {
  s: { 
         required: false,
         type: String,
         options: s => {
             return s.length < 120;
         }
      } ...
```
and call the function without the parameter `s`.

### Actual Outcome

`Validation failed. Invalid type for s. Expected: string`

### Expected Outcome

Not a failed validation. If the parameter is not required, has no default value and is not sent to the function its type should not be checked. 

### Failing Test Case / Pull Request

- [x] 🤩 I submitted a PR with a fix and a test case. #7353
- [ ] 🧐 I submitted a PR with a failing test case.

###  Environment

Server
- Parse Server version: `4.5.0`
- Operating system: tested on both `Debian & Windows 10`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `local`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `4.4.5`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `local`

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): `Android`
- SDK version: `1.26.0`

### Logs

```
Parse error:  Validation failed. Invalid type for s. Expected: string {"code":142,"stack":"Error: Validation failed. Invalid type for f. Expected: string\n    at resolveError (.../node_modules/parse-server/lib/triggers.js:618:12)\n    at .../node_modules/parse-server/lib/triggers.js:647:21\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)"}
```

**Comment by mtrezza** [comment]
Thanks for reporting!

I classified this as a bug with severity S3 (normal):
- Workaround: do not use cloud function validator but manually validate

**Comment by dblythy** [comment]
I think this one can be closed

**Comment by mtrezza** [comment]
Closed via https://github.com/parse-community/parse-server/pull/7353
