### ISSUE TITLE
Tests fail on master due to Twitter API

### ISSUE THREAD

**Issue by dblythy** [parse-community/parse-server#7369]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description

As discussed [here](https://github.com/parse-community/parse-server/pull/7296#issuecomment-826007788), one test fails on master.

### Steps to reproduce

Run test `Should fail a GET request'`.

### Actual Outcome

Test should pass

### Expected Outcome

Test fails

### Failing Test Case / Pull Request

- [x] 🤩 I submitted a PR with a fix and a test case.
- [ ] 🧐 I submitted a PR with a failing test case.

###  Environment

Server
- Parse Server version: `master`

Database
- System (MongoDB or Postgres): `both`

### Logs

```
Failures:
1) OAuth Should fail a GET request
  Message:
    Uncaught exception: SyntaxError: Unexpected end of JSON input
  Stack:
        at <Jasmine>
        at IncomingMessage.<anonymous> (/home/runner/work/parse-server/parse-server/lib/Adapters/Auth/OAuth1Client.js:3:462)
        at IncomingMessage.emit (events.js:327:22)
        at endReadableNT (internal/streams/readable.js:1327:12)
        at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

**Comment by mtrezza** [comment]
This seems to be a temporary Twitter API issue, see [comment](https://github.com/parse-community/parse-server/pull/7370#issuecomment-826074292).

**Comment by dblythy** [comment]
Ok. So you would suggest wait until Twitter fix this issue on their end?

**Comment by mtrezza** [comment]
Do we already know for sure that it's a Twitter issue?

**Comment by dblythy** [comment]
No. I’m assuming it is as this issue has never been prevalent before, and the endpoint now returns an empty page regardless of IP, user agent, etc.

**Comment by mtrezza** [comment]
That means the test has always been incorrect?

**Comment by dblythy** [comment]
> That is confusing. The original endpoint returns a config object.

Yes, the original endpoint used to return that object. It returns an empty page right now.

**Comment by mtrezza** [comment]
Even if it returned an object, the test still wouldn't pass.

**Comment by dblythy** [comment]
> Even if it returned an object, the test still wouldn't pass

Sorry Manuel, I’m not quite sure I follow. The object returned by the Twitter oauth used to pass the tests, and now, does not. How would you suggest this be approached?

**Comment by mtrezza** [comment]
> The object returned by the Twitter oauth used to pass the tests

That is what I doubt. How could it have passed the test? I want to make sure we don't overlook something here.

**Comment by dblythy** [comment]
I don’t think we overlooked anything. My theory is that as Twitter move to newer API versions, they are removing older endpoints, and these no longer work. Admittedly this seems a little strange, however I can’t understand why the exisiting endpoint would stop working (rate limiting still happens on new devices).

**Comment by mtrezza** [comment]
I think we are talking about different aspects of this issue 🙂

Let's break it down:
- a) Why has the test passed in the past?
  The previous endpoint returned a [config object](https://developer.twitter.com/en/docs/twitter-api/v1/developer-utilities/configuration/api-reference/get-help-configuration). The example does not contain an error object, nor should it, because this is not an OAuth endpoint. The API did not change, it is still v1.1, and the test runs against 1.1, hardcoded in the URL. We could just say, we don't care, but I want to make sure we understand what is going on, maybe there is an additional issue we discover.
- b) What is the actual test purpose and therefore which endpoint does it require? Your PR seems to make sense, it is a failed OAuth test, so why was the configuration endpoint required previous?

**Comment by mtrezza** [comment]
@dblythy You were right, I looked into this and I understand now that these endpoints are just random endpoints to test the failing auth. It doesn't matter which endpoint is used as long as it requires OAuth. That confused me, I assumed these specific endpoints were picked for a particular reason. I will comment in your PR.

**Comment by dblythy** [comment]
Sorry, I should've explained that to start. My mistake for not being clear enough!

**Comment by mtrezza** [comment]
No worries, I found the invalid endpoint in the PR, so the research was worth it.
