### ISSUE TITLE
Incorrect response for "Object not found" on 4.2.0

### ISSUE THREAD

**Issue by saulogt** [parse-community/parse-server#7386]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description

After upgrading Parse server to version 4.2.0, a status code response that should be 404 is 500 instead. The previous version (4.1.0) works as expected.

### Steps to reproduce

Install parse server 4.2.0 or newer

```ts

const api = new ParseServer({
  databaseURI: 'mongodb://localhost:27017/dev', // Connection string for your MongoDB database
  // cloud: './cloud/main.js', // Path to your Cloud Code
  appId: 'myAppId',
  masterKey: 'myMasterKey', // Keep this key secret!
  fileKey: 'optionalFileKey',
  serverURL: 'http://localhost:1337/parse', // Don't forget to change to https if needed
  enableExpressErrorHandler: true, /// <<< This seems to be the issue
});
  
app.use('/parse', api);

/// Error handler
app.use((e, req, res, next) => {
  console.log(e);
  next(e, req, res);
})


app.listen(1337, function() {
  console.log('parse-server-example running on port 1337.');
});
  
```

Try to get a non existing user:
```bash
curl --request GET \
  --url http://localhost:1337/parse/classes/_User/CsXUw1MRCe \
  --header 'x-parse-application-id: <APPID>'
```

### Actual Outcome

```bash
< HTTP/1.1 500 Internal Server Error
< X-Powered-By: Express
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: GET,PUT,POST,DELETE,OPTIONS
< Access-Control-Allow-Headers: X-Parse-Master-Key, X-Parse-REST-API-Key, X-Parse-Javascript-Key, X-Parse-Application-Id, X-Parse-Client-Version, X-Parse-Session-Token, X-Requested-With, X-Parse-Revocable-Session, Content-Type, Pragma, Cache-Control
< Access-Control-Expose-Headers: X-Parse-Job-Status-Id, X-Parse-Push-Status-Id
< Content-Security-Policy: default-src 'none'
< X-Content-Type-Options: nosniff
< Content-Type: text/html; charset=utf-8
< Content-Length: 415
< Date: Wed, 12 May 2021 22:40:21 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
<
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>ParseError: Object not found.<br> &nbsp; &nbsp;at /Users/xyz/work/is-parse-server/node_modules/parse-server/src/Routers/ClassesRouter.js:97:17<br> &nbsp; &nbsp;at runMicrotasks (&lt;anonymous&gt;)<br> &nbsp; &nbsp;at processTicksAndRejections (internal/process/task_queues.js:93:5)</pre>
</body>
</html>
```

### Expected Outcome

```bash
< HTTP/1.1 404 Not Found
< X-Powered-By: Express
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: GET,PUT,POST,DELETE,OPTIONS
< Access-Control-Allow-Headers: X-Parse-Master-Key, X-Parse-REST-API-Key, X-Parse-Javascript-Key, X-Parse-Application-Id, X-Parse-Client-Version, X-Parse-Session-Token, X-Requested-With, X-Parse-Revocable-Session, Content-Type, Pragma, Cache-Control
< Access-Control-Expose-Headers: X-Parse-Job-Status-Id, X-Parse-Push-Status-Id
< Content-Type: application/json; charset=utf-8
< Content-Length: 40
< ETag: W/"28-+5YirrDDOrWkX+4BB7U4IKOPrA0"
< Date: Wed, 12 May 2021 22:28:40 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
<
* Connection #0 to host localhost left intact
{"code":101,"error":"Object not found."}* Closing connection 0
```

### Failing Test Case / Pull Request

- [ ] 🤩 I submitted a PR with a fix and a test case.
- [ ] 🧐 I submitted a PR with a failing test case.

###  Environment

Server
- Parse Server version: `4.2.0`
- Operating system: `macos and linux`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `Localhost and Heroku`

Database
- System (MongoDB or Postgres): `Mongodb`
- Database version: `4.0`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `MongoDb Atlas`

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): `javascript (node) and rest api`
- SDK version: `2.12`

**Comment by saulogt** [comment]
Apparently, I have to write the logic to get the right status code for the specific ParseError, and send it back to the client in my error handler, instead of calling `next(error)` and expect the parse server will do that.
This sound like a breaking change that should be in the CHANGELOG

**Comment by mtrezza** [comment]
Thanks for reporting.

> Apparently, I have to write the logic to get the right status code for the specific ParseError,

That shouldn't be necessary; if a non-existing user is queried, it should return 404.

Can you submit a PR with a failing test so we can verify this issue? I would even expect that there is already a test for this.

**Comment by saulogt** [comment]
Thank you for the quick response @mtrezza
 
This PR has changed the original behavior. https://github.com/parse-community/parse-server/pull/6423
For it to keep working properly, I have to copy the logic from here into my custom error handler https://github.com/parse-community/parse-server/pull/6423/files#diff-961f93c560811aa48d9fd06e092ee8afeab11489701254b58c6a835d3255c2f0R327

```js
app.use((err, req, res, next) => {
    // Do my stuff here

    let httpStatus;

    switch (err.code) {
      case Parse.Error.INTERNAL_SERVER_ERROR:
        httpStatus = 500;
        break;
      case Parse.Error.OBJECT_NOT_FOUND:
        httpStatus = 404;
        break;
      default:
        httpStatus = 400;
    }
    res.status(httpStatus);
    res.json({ code: err.code, error: err.message });
});
```

Previously it was simply this:
```js
app.use((err, req, res, next) => {
    // Do my stuff here
    next(err, req, res);
});
```

It looks like a breaking change that should be documented.
I managed to make it work with the changes mentioned abobe. So I guess the issue may be closed

**Comment by mtrezza** [comment]
Without having looked into this in more detail, a breaking change only occurs when a documented functionality changes.

What you are doing seems similar to what is described in https://github.com/parse-community/parse-server/issues/6422.

**Comment by saulogt** [comment]
Indeed... That feature is not documented.
thanks. I did exactly that
