### ISSUE TITLE
(graphql) Opt out from Relay Style spec

### ISSUE THREAD

**Issue by axelhildingson** [parse-community/parse-server#7412]
- [ ] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [ ] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [X] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation
We use apollo client and it is possible select your own field that will be use as cache key so we decided to use objectId instead of id. We can't see any use of the connection logic from relay, it just adds a bunch of logic in the queries that we don't use.

So is possible to opt out of the relay node interface? I can see that you discussed in this PR https://github.com/parse-community/parse-server/issues/5863 but I cant find any information about it in the docs and I can't find anything in the code that indicate that this is possible.

### Feature / Enhancement Description
Make it possible to opt out of Relay, Node, Connection and Cursor and Id.

**Comment by davimacedo** [comment]
No. It is not possible to opt out the Relay style spec. We turned out deciding to go with a single style (Relay style) which is actually a fit for both Relay and non Relay apps.

**Comment by axelhildingson** [comment]
Ok, thank you for fast answer 👍, we will probably carry on our migration as long as you can use objectId as id 😃 ( we have built a lot of logic around objectId so it will be hard for us to change it to id )

**Comment by davimacedo** [comment]
actually most of the queries and mutations accept both id and object id.
