### ISSUE TITLE
Support deeply nested pointers in queries

### ISSUE THREAD

**Issue by oallouch** [parse-community/parse-server#7413]
### New Feature / Enhancement Checklist

- [x ] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x ] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x ] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation

Say I have documents like :
```
Collections : Order

{
	items: [
		{
			item: {
				__type: 'Pointer',
				className: 'Item',
				objectId: 'yyyyyy'
			}
			count: 2
		}, {
			item: {
				__type: 'Pointer',
				className: 'Item',
				objectId: 'xxxxxx'
			}
			count: 1
		},
	]
}
```

We often use this kind of structure in our projects.

I can't find orders with a particular Item using
`query.equalTo('items.item', item)`

I have to use
`query.equalTo('items.item.objectId', item.id)`
which isn't the normal 'Parse way' of doing things.

I've had many developers struggling with this kind of queries.

Are we missing something ?

Thx,

Olivier

**Comment by mtrezza** [comment]
Would you please fill out the complete template (and maybe rather use the bug template ?). Please also state an example with the expected vs. actual outcome.
