### ISSUE TITLE
GraphQL logInWith triggers afterSave on _User without an "original" attribute

### ISSUE THREAD

**Issue by cjbland** [parse-community/parse-server#7433]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description
When using a 3rd party authentication service and GraphQL, calling the `logInWith` mutation causes the `_User` object to be updated (updating the `authData` field). When the `afterSave` trigger is executed, the request object does not have the `original` attribute.

### Steps to reproduce
Create an `afterSave` trigger on `_User` and put something like this:

```javascript
Parse.Cloud.afterSave(Parse.User, async (request) => {
  if (request.original) { 
    console.log('We are updating the object');
  } else {
    console.log('We are creating a new object');
  }

  return true;
});
```

Using GraphQL, log in with a 3rd party authentication and then call the `logInWith` mutation.

### Actual Outcome
The console is printing "We are creating a new object".

### Expected Outcome
I expected "We are updating the object" to be printed.

### Failing Test Case / Pull Request

- [ ] 🤩 I submitted a PR with a fix and a test case.
- [x] 🧐 I submitted a PR with a failing test case.

###  Environment

Server
- Parse Server version: 4.5.0
- Operating system: node:lts-alpine
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): AWS

Database
- System (MongoDB or Postgres): Postgres
- Database version: 12.4
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): AWS

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): JavaScript/GraphQL
- SDK version: 2.19.0

### Logs
This is the request object in the `afterSave` hook after the user has logged in:

```
Request:  {
  triggerName: 'afterSave',
  object: ParseUser { _objCount: 10, className: '_User', id: '4LV5P31aJe' },
  master: false,
  log: LoggerController {
    options: {
      jsonLogs: false,
      logsFolder: './logs/',
      verbose: false,
      logLevel: undefined,
      silent: undefined,
      maxLogFiles: undefined
    },
    appId: 'appid',
    debug: [Function (anonymous)],
    verbose: [Function (anonymous)],
    silly: [Function (anonymous)],
    [Symbol()]: WinstonLoggerAdapter {}
  },
  headers: {
    host: 'ec2host.compute-1.amazonaws.com',
    connection: 'keep-alive',
    'content-length': '1470',
    pragma: 'no-cache',
    'cache-control': 'no-cache',
    accept: '*/*',
    'x-parse-application-id': 'appid',
    'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36',
    'x-parse-rest-api-key': 'apikey',
    'content-type': 'application/json',
    origin: 'http://localhost:3000',
    referer: 'http://localhost:3000/',
    'accept-encoding': 'gzip, deflate',
    'accept-language': 'en-US,en;q=0.9'
  },
  ip: '::ffff:1.2.3.4',
  context: {}
}
```

**Comment by cjbland** [comment]
I'm trying to figure out how to make a PR for this but could use some help from anyone that is more familiar with the code base than I am. Here is what I believe is happening:

  1. Inside the `handleAuthData` function the existing user is found [here](https://github.com/parse-community/parse-server/blob/10695194b21a3ae2d34f88704a50a5ac0890202c/src/RestWrite.js#L475)
  2. Then, because there is no `query`, the `response` object is set directly  [here](https://github.com/parse-community/parse-server/blob/10695194b21a3ae2d34f88704a50a5ac0890202c/src/RestWrite.js#L508)
  3. Then, we get into the `runDatabaseOperation` function, and because `response` is set, no database operations are actually run [here](https://github.com/parse-community/parse-server/blob/10695194b21a3ae2d34f88704a50a5ac0890202c/src/RestWrite.js#L1303)
  4. Then we get into the `runAfterSaveFunction` and because there is no `query`, the `original` attribute is not set [here](https://github.com/parse-community/parse-server/blob/10695194b21a3ae2d34f88704a50a5ac0890202c/src/RestWrite.js#L1522)

Along the same lines with the fourth point, the `originalData` attribute is not set because this whole process kicks off as a `create` found [here](https://github.com/parse-community/parse-server/blob/10695194b21a3ae2d34f88704a50a5ac0890202c/src/GraphQL/loaders/usersMutations.js#L113). I'm trying to figure out how to get this to flow as though it's an "update" rather than having to use the `this.response` escape hatch in all of those follow-on promises. 

Would there be a problem with setting `this.query` and `this.originalData` at the point in `handleAuthData` where we determine the user to exist already? Should I just make a PR showing this?

**Comment by Moumouls** [comment]
@cjbland did you try to use `.existed()` or `isNew()` to detect new objects ?

**Comment by cjbland** [comment]
Thanks @Moumouls using `.existed()` worked. I'm going to roll with this rather than my proposed PR because I'm having a heck of a time trying to create a test case to demonstrate the flaw (it's more of an integration test than a unit test and I kept running into road blocks trying to pre-populate the database with an existing user).

**Comment by Moumouls** [comment]
No problem @cjbland , feel free to close this one if you think my answer is appropriate :)
