### ISSUE TITLE
Incorrect tags

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-server#7458]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description
There seem to be incorrect tags in this repo. Tags are used to mark release versions. The latest release was 4.5.0, but there are numerous tags beyond that:

![image](https://user-images.githubusercontent.com/5673677/124917628-553ce300-dff4-11eb-97b1-f57d0054125e.png)

If these tags have been added by mistake, they should be removed to avoid any confusion.

The tags all seem to be from @Moumouls. When opening the commit, it says:
![image](https://user-images.githubusercontent.com/5673677/124918321-3723b280-dff5-11eb-97cb-f0e8bcbad61a.png)

So I wonder why they show up, or do they only show up to me because I have any special access to that fork?

**Comment by Moumouls** [comment]
OOwwwwww  so sorry @mtrezza , i don't know how it landed here. This tags are normaly linked to my fork for my internal needs.

It seems that my git utility has pushed tags one the official repo. So strange. You can delete this safely. All tags seems to publicly visible.

**Comment by mtrezza** [comment]
Thanks, I will remove them.

**Comment by Moumouls** [comment]
Here i also wonder about one thing:
- A contributor can push a tag without any approval
- A malicious contributor could compile his own code  (with malicious code) and publish it to official repo silently

@mtrezza is it possible to disable tag push in this case ?

**Comment by Moumouls** [comment]
Oh @mtrezza after some thinking, all tags seems to be from 2020, but i still continue to push new tags on my fork. May be this use case happened:
- I made many tags (for my internal needs)
- I made a wrong merge from parse server origin and my fork for a new PR
- PR was accepted on Parse Server and some of my tags were inherited ?

**Comment by mtrezza** [comment]
You are a repo member with more permissions than public. In other words, you trusted to not commit malicious code and apply special care in your git actions. In any case, we'll review members permissions.

**Comment by Moumouls** [comment]
Totally aggreed @mtrezza 

@mtrezza  you can view tags in private navigation, there are really there.

**Comment by mtrezza** [comment]
> @mtrezza you can view tags in private navigation, there are really there.

Well, I guess it was just a mis-push then. Still strange that it shows tags from another repo in this repo.

**Comment by Moumouls** [comment]
> apply special care in your git actions.

I do it, but it look super strange to me to have some tags pushed on my fork landed here. 

Ok i can just confirm that i'm allowed to push a tag

```sh
~/Desktop/OpenSource/parse-server moumouls/webauthn-adapter*
❯ git push upstream no-suposed-to-be-here
Enumerating objects: 1, done.
Counting objects: 100% (1/1), done.
Writing objects: 100% (1/1), 174 bytes | 58.00 KiB/s, done.
Total 1 (delta 0), reused 0 (delta 0)
To https://github.com/parse-community/parse-server.git
 * [new tag]           no-suposed-to-be-here -> no-suposed-to-be-here
```

**Comment by Moumouls** [comment]
@mtrezza  can you delete `no-suposed-to-be-here`. Does github has an option to prevent silent tag push ?

**Comment by Moumouls** [comment]
@mtrezza  it seems that adding a branch protection with `refs/tags/*` could fix this issue

**Comment by mtrezza** [comment]
Can you delete the `no-suposed-to-be-here` tag?

**Comment by Moumouls** [comment]
i'll check this

**Comment by mtrezza** [comment]
I opened a ticket with Github about this. So I suggest we keep one tag as an example to investigate and I'll go ahead and delete the other ones.

**Comment by Moumouls** [comment]
Ok i tested the `refs` trick, it do not work

**Comment by mtrezza** [comment]
It doesn't work because the branch protection name field seems to be prefixed with `refs/heads/`. At least we know it's only a tag writing issue.

**Comment by mtrezza** [comment]
> So currently the only fix is to remove write permissions and any direct push to parse repo ?

We will review the repo member permissions.

**Comment by Moumouls** [comment]
> We will review the repo member permissions.

lgtm, in 2021 it's pretty strange that Github do not have this feature. But may be the write access is the real core issue.

Thanks @mtrezza for your vigilance and your reactivity 🙂

**Comment by mtrezza** [comment]
Deleted all erroneous tags.
