### ISSUE TITLE
withinKilometers withinMiles withinRadians not working with Live Query

### ISSUE THREAD

**Issue by PolSpock** [parse-community/parse-server#7480]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description

I want to retrieve object only in a specific radius of the user current Position.
I use Live Query to get when object enter, update, leave theses conditions in real time.

However when i write a query with withinKilometers / withinMiles / withinRadians the Live Query never triggered when the Object has his GeoPoint enter / update / leave the specific radius.

### Steps to reproduce

1) Setup a parse-server with Live Query
2) Create a class with a GeoPoint column (in my example, my column is "location")
3) Create a client, i tried on Parse Flutter SDK and Parse Javascript SDK
4) Connect the client, make a Parse Query with a subscription based on [withinKilometers](http://parseplatform.org/Parse-SDK-JS/api/3.2.0/Parse.Query.html#withinKilometers) / withinMiles / withinRadians conditions
My javascript example :

```<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Test</title>
    <script src="https://unpkg.com/parse/dist/parse.js"></script>
    <script>
        main();
        async function main() {
            Parse.initialize("xxxxxxxxxxxxx");
            Parse.serverURL = 'http://192.168.X.X:1337/parse'

            var query = new Parse.Query('TestObject');
            query.withinKilometers("location", new Parse.GeoPoint({latitude: 45, longitude: 2}), 1, false);
            var subscription = await query.subscribe();

            subscription.on('open', () => {
                console.log('subscription opened');
            });

            subscription.on('update', (object) => {
                console.log(object);
                console.log('object updated');
            });

            subscription.on('enter', (object) => {
                console.log(object);
                console.log('enter updated');
            });

            subscription.on('leave', (object) => {
                console.log(object);

                console.log('object left');
            });

            subscription.on('delete', (object) => {
                console.log(object);

                console.log('object deleted');
            });

            subscription.on('close', () => {
                console.log('subscription closed');
            });
        }
    </script>
</head>
<body>
    <p>Test</p>
</body>
</html>
```

### Actual Outcome

My Live Query subscription is never triggered when the GeoPoint respect the subscription conditions.

**If i replace the .subscription() by .find() the query worked fine, but this is not i want cause i need Live Query**

### Expected Outcome

I expect to get my `TestObject` when his location is update and still respect my subscription condition.

In my example : a `TestObject` with "location" `Parse.GeoPoint({latitude: 45, longitude: 2})` must be return to client because the client have the same position and the withinKilometers is respected.
(see my example line `query.withinKilometers("location", new Parse.GeoPoint({latitude: 45, longitude: 2}), 1, false);`)

### Failing Test Case / Pull Request

- [ ] 🤩 I submitted a PR with a fix and a test case.
- [x] 🧐 [I submitted a PR with a failing test case.](https://github.com/parse-community/parse-server/pull/7526)

### Environment

Server
- Parse Server version: `4.5.0`
- Operating system: `Windows 10.0.19043`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `local`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `4.4.4`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `Local`

Clients
- SDK JavaScript version: `3.3.0`
- SDK Flutter version: `3.1.0`

### Logs

No log

Regards !

**Comment by mtrezza** [comment]
Thanks for reporting! Could you add a failing test to demonstrate the issue?

**Comment by PolSpock** [comment]
Hi, after new testing i found new elements :

**With JavasScript SDK :**
If you give the last parameter of withinKilometers (sorted) : `query.withinKilometers("location", new Parse.GeoPoint({ latitude: 45.0, longitude: 2.0 }), 2, false);`
The request to register the subscription to the server will be :

```{"op":"subscribe","requestId":1,"query":{"className":"TestObject","where":{"location":{"$geoWithin":{"$centerSphere":[[2,45],0.0003139224611520954]}}}}}```

This not working

However, if you not specify the last parameter of withinKilometers : `query.withinKilometers("location", new Parse.GeoPoint({ latitude: 45.0, longitude: 2.0 }), 2);`
The request to register the subscription to the server will be :

```{"op":"subscribe","requestId":1,"query":{"className":"TestObject","where":{"location":{"$nearSphere":{"__type":"GeoPoint","latitude":45,"longitude":2},"$maxDistance":0.0003139224611520954}}}}```

And this working

**However with Flutter SDK :**
The following code :
```
ParseGeoPoint contraint = new ParseGeoPoint();
contraint.latitude = 45.0;
contraint.longitude = 2.0;

ParseObject truckObject = ParseObject("TestObject");

QueryBuilder<ParseObject> query = QueryBuilder<ParseObject>(truckObject)
  ..whereWithinKilometers("location", contraint, 2);

_subscription = await liveQuery.client.subscribe(query);
````

Generate the cURL request which not working too :
```
SubscribeMessage: {op: subscribe, requestId: 9, query: {className: TestObject, where: {location: {$nearSphere: {__type: GeoPoint, latitude: 45.0, longitude: 2.0}, $maxDistanceInKilometers: 2.0}}}, sessionToken: r:eeeeeeeeeeeeeeeeeeeeeeeeeeee}
```

So i see they are different result of request between Javascript SDK and Flutter SDK
`$maxDistance` parameter working but `$maxDistanceInKilometers` and `$geoWithin":"$centerSphere` doesn't

**Test with Jasmine in spec folder on parse-server repo :**
Not working test :
```
  it('can subscribe to query and return object with withinKilometers with last parameter on update', async done => {
    await reconfigureServer({
      liveQuery: {
        classNames: ['TestObject'],
      },
      startLiveQueryServer: true,
      verbose: false,
      silent: true,
    });
    const object = new TestObject();
    const firstPoint = new Parse.GeoPoint({ latitude: 40.0, longitude: -30.0 });
    object.set({ location: firstPoint });
    await object.save();

    const query = new Parse.Query(TestObject);
    query.withinKilometers("location", new Parse.GeoPoint({ latitude: 40.0, longitude: -30.0 }), 2, false);
    const subscription = await query.subscribe();
    subscription.on('update', obj => {
      console.log("update");
      expect(obj.id).toBe(object.id);
      done();
    });

    const secondPoint = new Parse.GeoPoint({ latitude: 40.0, longitude: -30.0 });
    object.set({ location: secondPoint });
    await object.save();
  });
 ```
 
 Working test :
  ```
   it('can subscribe to query and return object with withinKilometers without last parameter on update', async done => {
    await reconfigureServer({
      liveQuery: {
        classNames: ['TestObject'],
      },
      startLiveQueryServer: true,
      verbose: false,
      silent: true,
    });
    const object = new TestObject();
    const firstPoint = new Parse.GeoPoint({ latitude: 40.0, longitude: -30.0 });
    object.set({ location: firstPoint });
    await object.save();

    const query = new Parse.Query(TestObject);
    query.withinKilometers("location", new Parse.GeoPoint({ latitude: 40.0, longitude: -30.0 }), 2);
    const subscription = await query.subscribe();
    subscription.on('update', obj => {
      console.log("update");
      expect(obj.id).toBe(object.id);
      done();
    });

    const secondPoint = new Parse.GeoPoint({ latitude: 40.0, longitude: -30.0 });
    object.set({ location: secondPoint });
    await object.save();
  });
  ```

**Comment by cbaker6** [comment]
> **With Parse JavasScript SDK :**
> If you give the last parameter of withinKilometers (sorted) : `query.withinKilometers("location", new Parse.GeoPoint({ latitude: 45.0, longitude: 2.0 }), 2, false);`
> The request to register the subscription to the server will be :
> 
> `{"op":"subscribe","requestId":1,"query":{"className":"TestObject","where":{"location":{"$geoWithin":{"$centerSphere":[[2,45],0.0003139224611520954]}}}}}`
> 
> This not working
> 
> However, if you not specify the last parameter of withinKilometers : `query.withinKilometers("location", new Parse.GeoPoint({ latitude: 45.0, longitude: 2.0 }), 2);`
> The subscription request to the server will be :
> 
> `{"op":"subscribe","requestId":1,"query":{"className":"TestObject","where":{"location":{"$nearSphere":{"__type":"GeoPoint","latitude":45,"longitude":2},"$maxDistance":0.0003139224611520954}}}}`
> 
> And this working

I'm sure this has something to do with LiveQuery currently not supporting all query operators. More info [here](https://github.com/parse-community/parse-server/wiki/Parse-LiveQuery-Protocol-Specification#subscribe-message), specifically:

> The query.where field is mandatory. It represents the condition of the ParseQuery the client subscribes to. The format of the where field is the same with ParseQuery's REST API format. You can check the detail here. Right now we support $lt, $lte, $gt, $gte, $ne, $in, $nin, $exists, $all, $regex, $nearSphere, $within and normal equal condition. Any unsupported conditions will be ignored.

Though there has been additional support added in #7113

You can see that `$maxDistance` is supported here: https://github.com/parse-community/parse-server/blob/1e0d408ca38127813d2034eadc97e08abed21843/src/LiveQuery/QueryTools.js#L305-L311

While `$centerSphere` isn't:
https://github.com/parse-community/parse-server/blob/1e0d408ca38127813d2034eadc97e08abed21843/src/LiveQuery/QueryTools.js#L336-L340

You may want to open a PR to add support.

**Comment by cbaker6** [comment]
@mtrezza this should probably be labeled as an improvement since it's known these operators aren't supported currently
