### ISSUE TITLE
Add deprecation plan

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-server#7483]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation
With the introduction of [Phased Deprecation](https://github.com/parse-community/parse-server/issues/7198), it may become challenging to track the number of pending breaking changes and with which release these should be removed from code.

### Feature / Enhancement Description
Add a list of deprecations and planned breaking changes. The table lists deprecations, when they were introduced and when the deprecated features are planned to be removed. This should be for maintainers to know when to remove features, and for developers to better plan when changes become required to upgrade.

### Example Use Case
n/a

### Alternatives / Workarounds
n/a

### 3rd Party References
Node.js has something similar

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/5.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0](https://github.com/parse-community/parse-server/releases/tag/5.0.0)
