### ISSUE TITLE
PagesRouter in 4.5.2

### ISSUE THREAD

**Issue by Fredbellano** [parse-community/parse-server#7503]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the last release (https://github.com/parse-community/parse-server/releases). 

### Issue Description
I can't find the PagesRouter in the last release

### Steps to reproduce
Explore node_modules after run 'npm install'

### Actual Outcome
PagesRouter doesn't exists

### Expected Outcome
Find PagesRouter in src/Routers

### Failing Test Case / Pull Request

- [ ] 🤩 I submitted a PR with a fix and a test case.
- [ ] 🧐 I submitted a PR with a failing test case.

###  Environment

Server
- Parse Server version: 4.5.2
- Operating system: macOS
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): Local

Database
- System (MongoDB or Postgres): MongoDB
- Database version: 4.4.8
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): Local

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): Javascript
- SDK version: 4.5.2

**Comment by mtrezza** [comment]
The PagesRouter is not part of release 4.5.2, it will be part of the next major release. See the changelog.

**Comment by Fredbellano** [comment]
Ok, so I don't have the possibility to test this feature on my project?

**Comment by mtrezza** [comment]
Sure you do, you can simply point your parse server dependency to a specific commit, until the next version of Parse Server is released.

**Comment by Fredbellano** [comment]
Thank you so much for your answers and the work you do!
