### ISSUE TITLE
Allow a pointer to be removed using GraphQL

### ISSUE THREAD

**Issue by cjbland** [parse-community/parse-server#7517]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation
I'm trying to clear out a column that currently has a pointer value. For example, I have a class named "Issue" and a field on that class is "user" which is defined as a pointer to the "_User" class. Once that field is set, I can never unset it using GraphQL

### Feature / Enhancement Description
The current way to set a pointer on a field with GraphQL is: `user: { link: 'myuserid' }`. My suggestion (which I will submit a PR for) is to use something like: `user: { unlink: true}`. Looking through the code, this should be a pretty good and non-invasive use-case.

### Alternatives / Workarounds
My current work around is to issue a REST API call to clear out the field.

**Comment by Moumouls** [comment]
Unlink pointer is supported by parse following GQL convention

```gql
mutation aMutation($anID: ID!) {
			updateSomething(
				input: {
					id: $anID
					fields: { somePointer: { link: null } }
				}
			) {
				someThing {
					id
				}
			}
		}
```
