### ISSUE TITLE
Clear pending ops (revert) for Cloud Function validation "constant"

### ISSUE THREAD

**Issue by dblythy** [parse-community/parse-server#7534]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation

Parse Cloud Function validation field `constant` sets request.object's field to request.original. Wouldn't it be better to use Parse.Object's function `.revert`, to clear pending operations on these keys, rather than setting it?

### Feature / Enhancement Description

I propose changing [this block](https://github.com/parse-community/parse-server/blob/64fc04cc2688f3ce1ff7cf98fb9c522253831f66/src/triggers.js#L717) to:

```js
request.object.revert(key);
if (request.object.get(key) == null &&opt.default != null) {
  request.object.set(key, opt.default);
}
```

**Comment by mtrezza** [comment]
Can you please fill out the other fields to make it more clear what the current issue is and what the benefit of the suggested change would be? And I assume that "Parse Cloud Validator" refers to the Parse Cloud Function validation handler?

**Comment by dblythy** [comment]
It's only a minor nit @mtrezza, but if you use the `constant` property, the code will override req.object.key to req.original.key. This is a database op that doesn't need to happen, because effectively req.object.key isn't being changed. Hence why I think it should use the existing JS method req.object.revert(key), which removes pending OPS for req.object.key

**Comment by dblythy** [comment]
Depends on: #7839
