### ISSUE TITLE
Docker images are not updated on docker hub anymore

### ISSUE THREAD

**Issue by cbaker6** [parse-community/parse-server#7547]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description

Docker Hub made some [changes](https://www.docker.com/blog/changes-to-docker-hub-autobuilds/) around a month ago that stopped automatic builds for free accounts. So no new commits to the server or releases are being pushed.

### Steps to reproduce

- Merge a commit or make a release
- Go to https://hub.docker.com/r/parseplatform/parse-server and see that the last image was pushed over a month ago.

### Actual Outcome

Old image of dashboard

### Expected Outcome

Latest image when commits are made to the master branch and released images with respect to the tag

### Environment

Server
- Parse Server version: latest
- Operating system: Linux
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): Docker

Database
- System (MongoDB or Postgres): MongoDB
- Database version: latest
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): local

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): `ParseSwift`
- SDK version: `1.9.2`

**Comment by mtrezza** [comment]
Closed via #7548
