### ISSUE TITLE
Scalable LiveQuery server - Unable to get message from subscription

### ISSUE THREAD

**Issue by BanalitoRaulito** [parse-community/parse-server#7573]
### New Issue Checklist
- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description
Unable to get message from subscription (client/utils/initialize.js line: 22)

### Steps to reproduce
1. clone git https://github.com/BanalitoRaulito/Scalable-Parse-LiveQuery-Server
2. follow README (docker-compose up --build)
3. navigate to localhost:3000
4. type something to input and click "Add todo"

### Actual Outcome
I don't get console log after adding new item (from client/utils/initialize.js line: 22)

### Expected Outcome
I expected to get console log after adding new item (from client/utils/initialize.js line: 22)

### Environment

Server
- Parse Server version: `3.3.0`
- Operating system: `macOS Big Sur`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `Localhost`

Database
- System (MongoDB or Postgres): `Mongo AND Redis`
- Database version: `Mongo 5.0.2 AND Redis 6.2.5`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `Localhost`

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): `React`
- SDK version: `17.0.2`

### Logs
LiveQuery server: "info: Create new client: 19f08667-e7a1-456a-a138-5fe5ec9bc9e9"

**Comment by mtrezza** [comment]
Could you describe the steps based on the original repository? We don't know which customizations you my have in your fork. Probably the easiest way to demo the issue would be to create a PR with a failing test.

**Comment by uzaysan** [comment]
I've faced this issue before. When you run multiple parse-server behind the load balancer, you need to specify a redis server in order to parse servers to communicate with each other.

```
ParseServer.createLiveQueryServer(httpServer,{
  redisURL: 'redis://username:password@server-adress'
});
```
