### ISSUE TITLE
Rename master branch, rename masterKey to primaryKey

### ISSUE THREAD

**Issue by dblythy** [parse-community/parse-server#7584]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation

With the industry removing references to the word "master", "slave", "whitelist", and other potentially harmful stereotypes, Parse should adopt this change to meet industry standards.

This would likely occur in two steps:

1. Renaming the master branch
2. Removing problematic language in codebase, would be a breaking change

### Feature / Enhancement Description

Whether or not you personally agree with the change, I think at Parse we want to be ahead of the latest industry movements. Adopting this change would show our commitment to diversity and inclusivity and help promote our ideals of a welcoming developer community.

Plus, our [Code of Conduct](https://github.com/parse-community/parse-server/blob/master/CODE_OF_CONDUCT.md) enforces inclusive language and participation, so any language that has the potential to cause harm, should be removed from our platform.

It should also be noted that we don't currently use any "master / slave" structures and mostly use "parent / child".

Thoughts and discussions welcomed, please keep it civil and respectful.

### Example Use Case

.

### Alternatives / Workarounds

Keep as is, address at some point in the future.

### 3rd Party References

To name a few who have done the same:

[React](https://github.com/facebook/react/issues/21767)
[Django](https://github.com/django/django/pull/2692)
[PHP](https://github.com/sebastianbergmann/phpunit/commit/8e9c76d33dab4095c9066072076f368193e4166d)
[curl](https://github.com/curl/curl/pull/5546)
[redis](https://github.com/redis/redis/issues/5335)

**Comment by mtrezza** [comment]
Renaming the `master` branch to `main` is part of the new branch model in release automation.

**Comment by dblythy** [comment]
Yeah, I agree. I personally think renaming the `master` branch to `main` is a good middle ground for the time being. Looking forward to release automation!

**Comment by cbaker6** [comment]
I brought this topic up to the core team over a year ago. It's the reason why any parse repo I manage or submitted a lot of code to currently use `main` branch as I've made the change to them, i.e. https://github.com/parse-community/Parse-Swift, https://github.com/parse-community/parse-server-fs-adapter, https://github.com/parse-community/ParseLiveQuery-iOS-OSX. I'll point out that the core team agreed to those changes before I made them and basically agreed at the time that repos with a lower following were easier to change. I've also brought the change to `primaryKey` at the same time. My comments from last year are below:

> Hi everyone, I wanted to get peoples thoughts on moving the Parse-Swift default branch from “master” to “main”. I’m sure most of have seen the reasoning behind this and many repos on GitHub have made this change. Doing the change is pretty easy and settings, but will break somethings that can easily be fixed. Some adjustments I foresee are: 1) Travis, Circle, GitHub Actions (changing to main for tags or actions that occur on the master branch). 2) Changing the requirement to pass a build in settings from master to main

> Just putting this on the radar for the future as making the change would probably be breaking for all of the repos is the language used in some of the variable naming (this problem is in codebases outside of Parse as well), but the "swift linter" is throwing warnings of "inclusive language" due to "useMasterKey". If the other linters aren't doing this yet, I'm sure they will soon. IMO it's better to jump in front of this early and make the change before someone asks on a public forum like GitHub, stack, or somewhere else and we have to reactively respond. You can see in Parse-Swift where I commented out these warnings https://github.com/parse-community/Parse-Swift/search?q=inclusive_language

> To give insight on the type of language that's considered not inclusive, we can take a look at the "Migrating to version 4.2" section of pgpool https://www.pgpool.net/docs/latest/en/html/release-4-2-0.html For pgpool, they made a hard change on 4.2, didn't deprecate, that may or may not be the right way to do it in Parse...

**Comment by mtrezza** [comment]
The naming will be considered on the basis whether a developer expects the authoritative branch to be named `master` or `main` or whatever. This is merely a pragmatic consideration to cause the least friction with other tools and for a user / contributor to understand the branch model, not a political statement. 

We acknowledge that there may be technological tools that make political statements, such as evaluating whether code is using "inclusive language" according to their arbitrary criteria, but that does not coerce this project into following their political standpoint, nor into continuing to use these tools. We are to have our own debate about this.

**Comment by cbaker6** [comment]
> The branch naming is currently being considered on the basis whether a developer expects the authoritative branch to be named `master` or `main` or whatever. This is merely a pragmatic consideration to cause the least friction with other tools and for a user / contributor to understand the branch model, not a political statement.
> 
> We acknowledge that there may be technological tools that make political statements, such as evaluating whether code is using "inclusive language" according to their arbitrary criteria, but that does not coerce this project into assuming their political position, nor into continuing to use these tools. We are to have our own debate about this.

I think it’s important to point out that @mtrezza’s comments represent his opinions and doesn’t represent the whole Core Team, or the Contributors. You comments definitely don’t represent anything or process I believe. The fact that you can post a comment like this:

> In general, we would carefully review what we change and why we change it. Some current initiatives are based in the context of specific U.S. American political debates, strongly related to U.S. history.

Shows you are ignorant of history of the world, the history of the language you are currently writing in, along with the respective language derivative languages. Parse shouldn’t need to be, “coerced” as you put it to do the right thing. 

Note, the comments I posted above began 9/12/20, @mtrezza you chose not to participate in any of the conversation, while the other Core Contributors did. It’s been a year+ since then and the other Core Team members agreed on the process and was simply waiting for Github to release the tools to make everything easier.

**Comment by dblythy** [comment]
Again, going back to our code of conduct, which states:

> Examples of behavior that contributes to creating a positive environment include:
> 
> Using welcoming and inclusive language
> Being respectful of differing viewpoints and experiences
> ...
> Examples of unacceptable behavior by participants include:
> Trolling, insulting/derogatory comments, and personal or political attacks
> Other conduct which could reasonably be considered inappropriate in a professional setting

This is all an arbitrary criteria which is subjective to the beholder. 

Regardless of whether an issue is related to US politics or not, by choosing to continue to use language that could potentially cause harm or upset out US audience, I personally don't see why migrating and limiting our potential to isolate people base on their race _isn't_ the best course of action.

**Comment by mtrezza** [comment]
As I said before, I am encouraging a prober debate about this topic. This is not the place for political discussion, we are using the forum for this type of discussions.
