### ISSUE TITLE
LiveQuery stops working for client and class when subscribed with null condition

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-server#7609]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description

*Originally reported by @vahidalizad:*

There is bug in `/src/LiveQuery/QueryTools.js:216` in the master branch with throws an error  `can't find __type of null` because compareTo is `null`.

Only the null subscribed client does not get any events at all anymore for that class but the rest of the clients have no issues.
in my tests I realized `q.notEqualTo('***', null);` also have this problem, and clients with these conditions can't get events and the real issue apart from that is they don't get notified that the problem is `compareTo` parameter.

I think the `q.notEqualTo('***', null);` should work nicely and result in objects that are not null on that parameter but the error of `Cannot read property '__type' of null` is throwing on this condition as well.

### Steps to reproduce
```
// client side
let q = new Parse.Query('User')
q.lessThan('createdAt', null)
q.subscribe()
```

### Environment

Server
- Parse Server version: `4.10.3`

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): `JS`
- SDK version: `unknown`

### Logs
n/a

**Comment by dplewis** [comment]
@mtrezza Should be fixed via https://github.com/parse-community/parse-server/pull/8835

**Comment by mtrezza** [comment]
Yes, the description in https://github.com/parse-community/parse-server/issues/8834 seems to refer to the same issue.
