### ISSUE TITLE
CI GitHub workflows use 

### ISSUE THREAD

**Issue by oscard0m** [parse-community/parse-server#7614]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation

GitHub CI workflows using `setup-node` not getting benefit from `cache` property, which should improve execution times.

### Feature / Enhancement Description
Start getting benefit from this `cache` prop.

### Example Use Case
See PR

### Alternatives / Workarounds
-

### 3rd Party References
https://github.blog/changelog/2021-07-02-github-actions-setup-node-now-supports-dependency-caching/

**Comment by oscard0m** [comment]
> > GitHub CI workflows using setup-node not getting benefit from cache property, which should improve execution times.
> 
> * How would that improve execution times vs. `actions/cache`?
If the workflow has a by-default usage I guess is an equivalent benefit. It also depend in the number of dependencies the project have (details [here](url) <-- looking thread with the numbers ⏳ ).

Since it seems the workflow does not re-use the cache between node versions, it seems there could be room for improvement here? (not sure if you have a use case where you explicitly need to NOT re-use the cache between node versions in your CI)


> * How does the `cache` parameter interplay with matrix execution? - Currently we are are creating a cache based on matrix

My understanding is that it re-uses the cache between versions:

`The action follows actions/cache guidelines, and caches global cache on the machine instead of node_modules, so cache can be reused between different Node.js versions.`

source: https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-dependencies

**Comment by mtrezza** [comment]
From the [docs](https://docs.github.com/en/actions/advanced-guides/caching-dependencies-to-speed-up-workflows):

> GitHub will remove any cache entries that have not been accessed in over 7 days. There is no limit on the number of caches you can store, but the total size of all caches in a repository is limited to 5 GB. If you exceed this limit, GitHub will save your cache but will begin evicting caches until the total size is less than 5 GB.

It seems that it doesn't matter whether we have separate cache entries per matrix permutation. The cache is available, whether it's 1 cache file or N cache files, so I would not expect any performance improvement.

I am suspicious of having a single cache for all matrix permutations. Matrix caching is explicitly described in an [example](https://github.com/actions/cache/blob/main/examples.md#macos-and-ubuntu), using `actions/cache`. I do not think that matrix caching is done automatically "behind the scenes" using the shortcut `actions/setup-node:cache`. In fact I think the parameter serves as a shortcut for simple caching scenarios, but for complex ones, one has to explicitly use `actions/cache`. Just my guess - it would be good if you could find any hint on this.

**Comment by mtrezza** [comment]
Maybe a different node version produces a different cache? Again, no reference, but it is the suggested way for matrix caching by GitHub. This is the status quo that works, so we don't need argument to justify the status quo. To change this, we would need an argument against the status quo.

**Comment by dominikg** [comment]
Maxim's response in the issue you linked is pretty clear I think. As far as I understand it only the content of pnpm global store is cached which is not affected by node version and safe to share between different node versions.

**Comment by mtrezza** [comment]
@oscard0m thanks for investigating. 

The original issue was that the workflow was not using cache, which was incorrect, because the workflow is using cache explicitly instead of the cache parameter.

The suggested change of removing the node version won't bring any benefit as I understand. The benefit of keeping it however is that we have a clear cache separation between node versions. Even if that is not needed now, it seems a more sustainable approach because we cannot tell whether the Node.ja team will keep cache compatibility across node versions, at least I haven't found any reference.

If we find an argument in favor of removing the separation by node version, let's reevaluate.

**Comment by mtrezza** [comment]
Below is a performance comparison between the CI run times of this PR vs. status quo. As we can see, there is no noticeable performance improvement. The tests usually run +/- 1 min, so the conclusion would be that the two run at the same speed.

I'm closing this PR, as the original issue was incorrect (we were already using cache), and the suggestion to not separate the cache per node version does not yield any improvement, but potentially opens up issues if node caches become incompatible across node versions in the future.

@oscard0m Thanks for opening this issue and your investigations. If you come across a pro-argument for using a single cache, please let us know and we will gladly reconsider.

---

This PR:

![Screen Shot 2021-10-17 at 20 41 23](https://user-images.githubusercontent.com/5673677/137641258-773a3d1d-687b-4699-acc9-dae90c2f79db.png)
![Screen Shot 2021-10-17 at 21 02 37](https://user-images.githubusercontent.com/5673677/137641250-53a3c3c8-38c1-4621-a4a4-39b0bfa5a3b0.png)

Status quo:
![Screen Shot 2021-10-17 at 21 02 04](https://user-images.githubusercontent.com/5673677/137641274-8782d60f-2da5-4177-a507-70e3979a301f.png)
![Screen Shot 2021-10-17 at 21 02 23](https://user-images.githubusercontent.com/5673677/137641272-61189cff-a0fe-427d-83d4-42f86ae8f558.png)

**Comment by oscard0m** [comment]
> Below is a performance comparison between the CI run times of this PR vs. status quo. As we can see, there is no noticeable performance improvement. The tests usually run +/- 1 min, so the conclusion would be that the two run at the speed.
> 
> 
> 
> I'm closing this PR, as the original issue was incorrect (we were already using cache), and the suggestion to not separate the cache per node version does not yield any improvement, but potentially opens up issues if node caches become incompatible across node versions in the future.
> 
> 
> 
> @oscard0m Thanks for opening this issue and your investigations. If you come across a pro-argument for using a single cache, please let us know and we will gladly reconsider.
> 
> 
> 
> ---
> 
> 
> 
> This PR:
> 
> 
> 
> ![Screen Shot 2021-10-17 at 20 41 23](https://user-images.githubusercontent.com/5673677/137641258-773a3d1d-687b-4699-acc9-dae90c2f79db.png)
> 
> ![Screen Shot 2021-10-17 at 21 02 37](https://user-images.githubusercontent.com/5673677/137641250-53a3c3c8-38c1-4621-a4a4-39b0bfa5a3b0.png)
> 
> 
> 
> Status quo:
> 
> ![Screen Shot 2021-10-17 at 21 02 04](https://user-images.githubusercontent.com/5673677/137641274-8782d60f-2da5-4177-a507-70e3979a301f.png)
> 
> ![Screen Shot 2021-10-17 at 21 02 23](https://user-images.githubusercontent.com/5673677/137641272-61189cff-a0fe-427d-83d4-42f86ae8f558.png)
> 
> 
> 
> 

Thanks for the research and experimentation on this. I learned a lot with you @mtrezza !
