### ISSUE TITLE
GraphQL: Relay version >=0.8.0 introduce ID compatibility issue (objectIdSize higher than 19)

### ISSUE THREAD

**Issue by Moumouls** [parse-community/parse-server#7622]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description
With an objectId size setting equal or hight than `20` graphql request with an Mongo objectID fails (Invalid code point issue from graphql relay).

### Steps to reproduce
Start a server, set objectIdSize to 20, create an object on graphql api, and the mutation return get the objectId and the id (relay). query the graphql api with the objectId. Request will fail.

### Actual Outcome
All request fail using a non relay id

### Expected Outcome
Non relay id from any size should works
### Environment
Parse server with graphql relay >= 0.8.0
`5.0.0-alpha.1`

graphql-relay should be downgraded to 0.7.0

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-alpha.9](https://github.com/parse-community/parse-server/releases/tag/5.0.0-alpha.9)

**Comment by mtrezza** [comment]
Closing, via https://github.com/parse-community/parse-server/pull/7627 (merged into alpha), https://github.com/parse-community/parse-server/pull/7722 (merged into beta).

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-beta.10](https://github.com/parse-community/parse-server/releases/tag/5.0.0-beta.10)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.1.0](https://github.com/parse-community/parse-server/releases/tag/5.1.0)
