### ISSUE TITLE
Enable current disabled tests on Postgres

### ISSUE THREAD

**Issue by cbaker6** [parse-community/parse-server#7640]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description

A number of test cases are not enabled for the PostgresAdapter though the adapter is able to pass the tests. This can be for a number of reasons such as: 

- functionality was implemented when tests was originally created, but adapter now has functionality
- by mistake or oversight

Most of the other tests that can't pass are either `legacy` tests from the original Parse Server, from legacy versions of the servers, or tests that use specific mongo functionality (some of these specific Mongo tests don’t need to be specific, they just need to be rewritten).

In addition, some tests are incorrectly labeled to be excluded from postgres, while they specifically should say they should only run on mongo.

### Steps to reproduce

Enable tests that are currently not for Postgres and run test suite.

### Actual Outcome

Some tests actually pass that are currently disabled.

### Expected Outcome

Any test that can pass on the Postgres adapter should be run

### Environment

Server
- Parse Server version: 5.0.0-alpha.1
- Operating system:  Linux
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): Local

Database
- System (MongoDB or Postgres): Postgres
- Database version: 13
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): Local

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): N/A
- SDK version: N/A

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-alpha.2](https://github.com/parse-community/parse-server/releases/tag/5.0.0-alpha.2)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/5.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0](https://github.com/parse-community/parse-server/releases/tag/5.0.0)
