### ISSUE TITLE
CI currently isn't building for Postgres 14

### ISSUE THREAD

**Issue by cbaker6** [parse-community/parse-server#7643]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description

Postgres 14 was recently [released](https://www.postgresql.org/about/news/postgresql-14-released-2318/), but the CI currently isn't building for it.

### Steps to reproduce

Look through CI for Postgres 14 build.

### Actual Outcome

CI is testing on versions 13 and below.

### Expected Outcome

CI testing on versions 14 and below.

### Environment

Server
- Parse Server version: 5.0.0-alpha.1
- Operating system:  Linux
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): Local

Database
- System (MongoDB or Postgres): Postgres
- Database version: 13
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): Local

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): N/A
- SDK version: N/A

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-alpha.4](https://github.com/parse-community/parse-server/releases/tag/5.0.0-alpha.4)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/5.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0](https://github.com/parse-community/parse-server/releases/tag/5.0.0)
