### ISSUE TITLE
Parse Server 4.10.4 installs multiple graphql modules

### ISSUE THREAD

**Issue by FransGH** [parse-community/parse-server#7650]
### New Issue Checklist
- [ x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x ] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [ x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [ x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description
parse-dashboard/GraphQL-Console brings the error that multiple graphql versions are installed on the server.

### Steps to reproduce
in an empty folder type:

```
npm install parse-server
grep '/graphql":' -A1 package-lock.json
```

Results in:
```
    "node_modules/graphql": {
      "version": "14.7.0",
--
    "node_modules/parse-server/node_modules/graphql": {
      "version": "15.4.0",

```

graphql 15.4.0 is a dependency of parse-server
graphql 14.7.0 is a dependency of of graphql-relay 0.6.0

### Actual Outcome
Due to the above, GraphQL Console brings an error that multiple graphql versions are installed on the parse-server, causing it to fail.

### Expected Outcome
parse-dashboard/GraphQL-Console should work without errors on a fresh install of parse-server 4.x

Making following changes to parse-server/package.json resolves the issue although it is unclear if this has side effects:
```
"graphql": "15.5.0",          // from "15.4.0"
"graphql-relay": "0.7.0",  // from "0.6.0"

```

parse-server 5.x seems to fix these dependencies however since it is a major upgrade with possible breaking changes, it would be great if this could be addressed in a 4.10.x update.

### Environment
parse-server 4.10.4
parse-dashboard 3.2.1
mongodb 4.4.3
macOS Catalina 10.15.7
node 12.22.6
npm 8.1.0

### Logs
n/a

**Comment by mtrezza** [comment]
Do you want to open a PR against the 4.x branch to bump the graphql dependencies?

**Comment by FransGH** [comment]
First PR so hope this is ok? https://github.com/parse-community/parse-server/pull/7658

**Comment by mtrezza** [comment]
Amazing, I'll review.

**Comment by mtrezza** [comment]
Closing via https://github.com/parse-community/parse-server/pull/7658.
