### ISSUE TITLE
CI on LTS branch release-4.x is broken

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-server#7659]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description
CI fails with error: 

> Error: Object not found.
>     at then.then.result (/home/runner/work/parse-server/parse-server/lib/Controllers/DatabaseController.js:49:3084)
>     at process._tickCallback (internal/process/next_tick.js:68:7)

Possibly introduced by https://github.com/parse-community/parse-server/commit/4ac4b7f71002ed4fbedbb901db1f6ed1e9ac5559.

### Steps to reproduce
Run CI on current `release-4.x` branch.

### Actual Outcome
CI fails.

### Expected Outcome
CI should pass.

### Environment

Server
- Parse Server version: https://github.com/parse-community/parse-server/commit/4ac4b7f71002ed4fbedbb901db1f6ed1e9ac5559

### Logs
See https://github.com/parse-community/parse-server/runs/4028298097?check_suite_focus=true

**Comment by FransGH** [comment]
This is not an error but seems to be 'expected' trace output from [EnableExpressErrorHandler.spec.js](https://github.com/parse-community/parse-server/blob/alpha/spec/EnableExpressErrorHandler.spec.js).

I see this too when running the test locally and it's not resulting in a failed test, although the trace output is confusing.

**Comment by mtrezza** [comment]
Then it may be some other issue. Since two different PRs face the same issue of the CI failing on this branch, I assume it's some issue with the branch, not with any of the PRs. When you run `npm test` locally on Node 10 with the latest commit of the 4.x branch, do all tests pass?

**Comment by mtrezza** [comment]
Closing as the LTS branch is no longer maintained.
