### ISSUE TITLE
Class-Level Permissions not working for associated userId

### ISSUE THREAD

**Issue by Zerokk** [parse-community/parse-server#7660]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases).   <-- not exactly, look in "Steps to reproduce" section.

### Issue Description

I'm adding CLP via the latest version of Parse Dashboard, and the changes work well this far. Except for one: when I try to filter out by userId (which is a Pointer to a User), it doesn't seem to work well.

Parse Server replies to the attempt to save an object from Cloud, with the following:

> Permission denied, user needs to be authenticated

Needless to say, the user is logged in in the client app, which makes this weird. So I started looking over Internet, and I found a couple of "solutions" that make sense, should work, but they do absolutely nothing. This is my CLP for that class:

![imagen](https://user-images.githubusercontent.com/10697745/139335750-188ee878-84dc-4b0c-922a-1c9dd110cf27.png)

1. I tried using the `masterkey` in the save function, just finishing the Cloud Function like this:
`
    return businessAcc.save(null, {useMasterKey: true});`

2. Also tried getting the User Session and saving the object with it:
`    return businessAcc.save(null, {sessionToken: request.user.getSessionToken()});`

None of them did anything. I also tried passing `{}` as first parameter for `save()`, changing the CLP... but the only solution seems to be this far to just let the class open, and try to filter out access to it from Cloud. But that doesn't work if an attacker uses a logged user session to call the Parse API.

This is worrying. Any help?

### Steps to reproduce
I couldn't manage to install the latest Parse Server, as I was having a Typescript error at the dependencies of `http-assert`, which errors such as `node_modules/@types/http-assert/index.d.ts:30:100 - error TS1005: ';' expected`. I couldn't fix it even reinstalling typescript, so I guess I'm stuck with this version as for now.

It would be good to know if someone tries the following with the latest version, and tell if it works:

1. Create a class with a bunch of columns.
2. Create a Pointer<User> called "userId"
3. With the latest version of Parse Dashboard, modify it's CLP so it's the same as the one I posted above.
4. With your client app, and a logged-in user, call a Parse Cloud function that creates and/or modifies an object of that class, and try to save it. Does it throw the same error?

### Actual Outcome
The server replies with "user is not authenticated" although it really is.

### Expected Outcome
It should save the object with no problem.

### Environment

- Node v: 10.24.1

Server
- Parse Server version: `4.10.4`
- Operating system: `Debian 4.9`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `VPS`

Database
- System (MongoDB or Postgres): `MongoDB `
- Database version: `4.0.10``
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `local`

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): `Ionic - Android device`
- SDK version: `5.34`

**Comment by Zerokk** [comment]
Now the post uses the default template, don't know why the bot still takes it as wrong.

**Comment by mtrezza** [comment]
Bot just complained because the headline was missing.

> With the latest version of Parse Dashboard

Can you add the version to the description?

And could you be more specific with the steps to reproduce? For example, the client user has to be in the user pointer field?

In fact, you mention the dashboard a lot. Is the dashboard necessary to reproduce this? If not, could you open a PR with a failing test, that modifies the CLP as you described and demos this?

**Comment by Zerokk** [comment]
> 
> 
> Bot just complained because the headline was missing.
> 
> > With the latest version of Parse Dashboard
> 
> Can you add the version to the description?
> 
> And could you be more specific with the steps to reproduce? For example, the client user has to be in the user pointer field?
> 
> In fact, you mention the dashboard a lot. Is the dashboard necessary to reproduce this? If not, could you open a PR with a failing test, that modifies the CLP as you described and demos this?

You are right, sorry for not adding the dashboard version! Here it is (I add it to the first post too), I think it's indeed the latest:

`parse-dashboard@3.2.1`

About the steps to reproduce, yes, the client user is the one that should be pointed in the pointer field. So public users wouldn't be able to do anything, authenticated users can only create a new BusinessAccount, and only the owner of a given BusinessAccount can update or remove the one they own.

The problem is that the server will *always* recognize the user as not logged in — even if I just log in before the test. At client-level, when accessing to the property `.authenticated` of the Parse User, I get `true`, so it's being a weird thing of the server rather than a real authentication issue, I think.

I don't know if the dashboard is fully necessary to reproduce this, as I didn't try to do the CLP via code but rather to create a database example with the dashboard, which empty structure will be copied for production. Do you think I should do it by hand, for some reason?

Thank you!

**Comment by mtrezza** [comment]
> I don't know if the dashboard is fully necessary to reproduce this, as I didn't try to do the CLP via code

We would need a PR with a failing test to verify whether this is a dashboard issue or a server / JS SDK issue (or both). If this is indeed a server issue, then we would need a test anyway to ensure the bug isn't introduced again  due to future code changes.

Could you try to replicate this in a failing test and open a PR? You could try it out quickly before opening a PR by using the Parse Dashboard API console for example.

**Comment by 2shrestha22** [comment]
![image](https://user-images.githubusercontent.com/24835256/148682640-1b7cb163-793e-4ac2-8716-af6d27960a12.png)
I may have same issue, I have assigned admin role and while deleting file with the users assigned to admin does not work. Log gives Object not found.

**Comment by 2shrestha22** [comment]
I figured out that is was not bug but I was not knowing how CLP and ACL works together. Both mine and OP's CLP are working on my side. Make sure you have public read, write ACL if you are using CLP.

Here is very nicely said, https://docs.parseplatform.org/rest/guide/#security

**Comment by mtrezza** [comment]
@Zerokk can this issue be closed, considering https://github.com/parse-community/parse-server/issues/7660#issuecomment-1008316796?

**Comment by 2shrestha22** [comment]
I back to same issue again. Forgot what I did a year ago. I think this can be closed since OP is not active anymore.
