### ISSUE TITLE
Java implementation of LiveQuery

### ISSUE THREAD

**Issue by romanbsd** [parse-community/parse-server#7673]
I open-sourced my Java implementation of LiveQuery server if anyone's interested. Hopefully the protocol didn't change since it was written. It's pretty fast.

https://github.com/romanbsd/livequery

**Comment by mtrezza** [comment]
Interesting! We should add this to our list of supported Parse-related 3rd party packages in the docs. Or is your intention to transfer the repository to Parse Platform?

**Comment by romanbsd** [comment]
I don't mind transferring it to Parse Platform. I just hope that people will benefit from it. I wrote it to overcome a performance bottleneck that we had.

**Comment by mtrezza** [comment]
I think if you open a topic in Parse Forum it could get more community attention. I could then also post on our social channels about this to get some feedback. Maybe you could provide some more info about the repository there, like
- how stable / maintained it is
- which LiveQuery JS server version it compares to and what are the feature differences
- what to consider when migrating / trying it out
- benefits and limitations

Some of that may already be in the README, but to kickstart interest, a summary could help.

**Comment by romanbsd** [comment]
Perhaps add to documentation meanwhile. I'm really short in time lately. Hopefully I'll find some time to do that later.
In general it's pretty stable, was running in production, was in order of magnitude less hungry in memory and substantially faster. It was used for pretty simple queries, so the mileage may vary. There's a short README which includes deployment instructions in my repo.

**Comment by romanbsd** [comment]
It's a good question which Parse it's aligned to. Probably 3.x. I'm not sure. But I don't think there were any changes to the protocol since then. I may be mistaken.

**Comment by mtrezza** [comment]
Sounds good, thanks for open-sourcing this and I'm closing this for now in favor of a [forum discussion](https://community.parseplatform.org/t/java-implementation-of-livequery-server/2136).
