### ISSUE TITLE
Add Node 17 support

### ISSUE THREAD

**Issue by malcolm-dane** [parse-community/parse-server#7686]
### New Issue Checklist

- [ x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x ] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [ x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x ] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description
The dependency as it lists anything greater than I think 4. If using heroku it defaults to NodeJs v17.1.0. This crashes the app and causes it not to run. Changing it to  "node": "14.18.1" will make it run. 

### Steps to reproduce
Load Parse locally using NodeJS 17.1.0, or load this repo into heroku and attach a mongoatlas and watch it crash.

### Actual Outcome
The app crashes after build.

### Expected Outcome
For the parse server to be up and running.
### Environment
Heroku and locally if using 17.1 will result in a huge list of errors about exporting packages. 

Server
- Parse Server version: `4.5`
- Operating system: `Ubuntu 20.04 and  Heroku`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `both if using nodejs 17.1.0'

Database
Has nothing to do with it.

Client
Has nothing to do with it. Builds properly after change. Tested REST api and saved to my MongoAtlas.

### Logs
2021-11-10T01:59:39.914107+00:00 heroku[web.1]: Starting process with command `npm start`

2021-11-10T01:59:41.044285+00:00 app[web.1]: 

2021-11-10T01:59:41.044303+00:00 app[web.1]: > parse-server-example@1.4.0 start

2021-11-10T01:59:41.044303+00:00 app[web.1]: > node index.js

2021-11-10T01:59:41.044304+00:00 app[web.1]: 

2021-11-10T01:59:42.516409+00:00 app[web.1]: node:internal/modules/cjs/loader:488

2021-11-10T01:59:42.516440+00:00 app[web.1]:       throw e;

2021-11-10T01:59:42.516440+00:00 app[web.1]:       ^

2021-11-10T01:59:42.516441+00:00 app[web.1]: 

2021-11-10T01:59:42.516442+00:00 app[web.1]: Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './public/extractFiles' is not defined by "exports" in /app/node_modules/extract-files/package.json

**Comment by mtrezza** [comment]
Parse Server is not even Node 16 compatible yet, see https://github.com/parse-community/parse-server/issues/7669. Presumably, Node 16 compatibility needs to be established first, before looking at Node 17 compatibility.

**Comment by malcolm-dane** [comment]
In the Parse-Server example, which is linked through numerous places, including Heroku's guide, Parse-Server Heroku setup guide the default is greater than 4.x.x. Heroku sees that and thinkss ok node 17.x.x it is. If you look through various stack exchange, reddit threads you see alot of people having issues with it. I've tried a few different times to get it up, but didn't have the time or reason to troubleshoot it. Maybe add it to the documentation is my only suggestion. I don't know, I just wanted to bring it up! Sorry if I keep spamming this.

**Comment by mtrezza** [comment]
Good point, we should change the version range. I'll open a PR for this.

**Comment by malcolm-dane** [comment]
Sounds good, this will def help some people. This is the first time I've ever actually reported a bug, glitch,etc. :)

**Comment by mtrezza** [comment]
Well done! If you want to go to the next level, you could look for an open issue here (or in [parse-dashboard](https://github.com/parse-community/parse-dashboard/issues)) and provide a pull request to fix it. 

I reopened this because the issue of missing Node 17 compatibility is not solved.
