### ISSUE TITLE
Database connection string with postgresql protocol assumes MongoDB

### ISSUE THREAD

**Issue by pmmlo** [parse-community/parse-server#7687]
### New Issue Checklist

- [x ] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x ] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x ] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x ] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description

Developers using PostgreSQL can only use a URI with the prefix "postgres:" when "postgresql:" is also commonly used.

### Steps to reproduce

1) Set env var PARSE_SERVER_DATABASE_URI to a URI string starting with "postgresql://..."
2) There will be a "MongoParseError" as it fallsback to MongoDB.

### Actual Outcome

"MongoParseError: Invalid connection string"

### Expected Outcome

Should validate as a PostgreSQL URI.

### Environment

Node v17.0.1

Server
- Parse Server version: 5.0.0-beta.1
- Operating system: macOS 12.0.1
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): Local

Database
- System (MongoDB or Postgres): Postgres
- Database version: Postgres 14.0.0
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): Local

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): n/a
- SDK version: n/a

**Comment by cbaker6** [comment]
Seems like this could be added.

For reference: https://www.postgresql.org/docs/current/libpq-connect.html

Parse Server connects to Postgres using pg-promise->node-postgres. Reference uri: https://node-postgres.com/features/connecting

**Comment by mtrezza** [comment]
Classified this as a bug as the Parse Server docs say:

> The postgres database adapter will be automatically loaded when you pass a valid postgres URL, for example: postgres://localhost:5432. 

A "valid postgres URL" includes the `postgresql` protocol, see [docs](https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING):

> The URI scheme designator can be either postgresql:// or postgres://

So it should work with either one. Severity low, as the workaround is to use the `postgres` protocol instead.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-alpha.15](https://github.com/parse-community/parse-server/releases/tag/5.0.0-alpha.15)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-beta.10](https://github.com/parse-community/parse-server/releases/tag/5.0.0-beta.10)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.1.0](https://github.com/parse-community/parse-server/releases/tag/5.1.0)
