### ISSUE TITLE
ParseFile save timeout

### ISSUE THREAD

**Issue by jt-gb** [parse-community/parse-server#7733]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description
Certain (video) files that are uploaded to the parse server run into an infinite loop of some sorts (request was still going on after 1,5h after upload to localhost server). After my testing this can have but not neccessarily has a connection to the files size (~700MB was a video file that i could consistently not upload).

### Steps to reproduce
```
$file = Parse\ParseFile::createFromData(
	file_get_contents(PATH_TO_VIDEO),
	'video.mp4',
	'video/mp4'
);

$file->save();
```

### Actual Outcome
Timeout of request.

### Expected Outcome
Uploaded file or error message.

### Environment

Server
- Parse Server version: 4.5.0
- Operating system: Windows 10
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): local host

Configuration values used (additionally to `databaseURI`, `serverURL`, `appId`, `masterKey`):

```
{
	"maxUploadSize": "4gb",
	"verbose": true
}
```

Database
- System (MongoDB or Postgres): MongoDB
- Database version: 4.4.2
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): local host

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): PHP
- SDK version: 1.6.0

### Logs
No output to show unfortunately. When using a timeout in PHP curl (with verbose enabled):

```
BadRequestError: request aborted
    at IncomingMessage.onAborted ...
```

**Comment by mtrezza** [comment]
A file of that size should probably use a custom upload mechanism, some form of multi-part upload that allows to resume. In any case, I think your assumption is correct that an upload that progresses indefinitely seems strange.

To ensure this is a Parse Server issue and not a Parse SDK issue, can you please retry to upload using REST and see whether the upload fails at some point?

**Comment by mtrezza** [comment]
I'm closing this as it lacks essential information required to investigate the issue. Please follow up on any questions asked and further steps suggested in the thread and we can re-open this issue.
