### ISSUE TITLE
Combability with node 16

### ISSUE THREAD

**Issue by hellow554** [parse-community/parse-server#7738]
The doc states that parse should be compatible with node.js 16:

| Version    | Latest Version | End-of-Life | Compatible    |
|------------|----------------|-------------|---------------|
| Node.js 12 | 12.22.7        | April 2022  | ✅ Yes        |
| Node.js 14 | 14.18.1        | April 2023  | ✅ Yes        |
| Node.js 16 | 16.13.0        | April 2024  | ✅ Yes        |
| Node.js 17 | 17.x           | June 2022   | ❌ Not tested |

the source code however says otherwise:

https://github.com/parse-community/parse-server/blob/ac789c8537dcb775345d2953fd732d4ad864eb61/package.json#L134

which results in:

```text
# yarn global add parse-server@5.0.0-alpha.12
error parse-server@5.0.0-alpha.12: The engine "node" is incompatible with this module. Expected version ">=12.20.0 <16". Got "16.13.1"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
```

**Comment by hellow554** [comment]
This should be fixed by #7710 :)

**Comment by mtrezza** [comment]
I've opened https://github.com/parse-community/parse-server/pull/7739 so you don't have to wait for #7710 to get merged.

**Comment by hellow554** [comment]
Thank you for the fix and the tag!

**Comment by mtrezza** [comment]
Sure! Thanks for opening the issue.
