### ISSUE TITLE
Add PostGIS 3.2 to the CI

### ISSUE THREAD

**Issue by cbaker6** [parse-community/parse-server#7753]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation

PostGIS 3.2 was recently [released](https://www.postgis.net/2021/12/18/postgis-3.2.0/). The CI is currently not tested against it to se if any bugs were introduced.

### Feature / Enhancement Description

Should always test against the latest.

### Example Use Case

N/A

### Alternatives / Workarounds

Use the latest without tests.

### 3rd Party References

N/A

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-alpha.15](https://github.com/parse-community/parse-server/releases/tag/5.0.0-alpha.15)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-beta.10](https://github.com/parse-community/parse-server/releases/tag/5.0.0-beta.10)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.1.0](https://github.com/parse-community/parse-server/releases/tag/5.1.0)
