### ISSUE TITLE
Pointer queries under PostGres failing to return any results

### ISSUE THREAD

**Issue by PopeNobody** [parse-community/parse-server#7754]
### New Issue Checklist

- [x ] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [ x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [ x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x ] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description

The following query returns no results under postgres, though there are several objects that should be returned.

The class in question is "PublicCell".  Each PublicCell has an owner, who is a user.  However, the following query does not return any results, even though the user I am using owns four cells.

```
  const ownerQ = new Parse.Query("PublicCell");
  ownerQ.equalTo("owner",user);
  console.log(ownerQ);
  const owned = await ownerQ.find();

  console.log("owned");
  for(var i=0;i<owned.length;i++){
    const cell = owned[i];
    console.log("  "+cell.get("name"));
  };
  console.log("");
```
The class is created with the following code:

```
export async function createPublicCellTable() {
  console.log("createPublicCellTable");
  const schema1 = new Parse.Schema("PublicCell");
  schema1.addPointer("owner","_User",{required: true});
  schema1.addString("name",{required: true});
  // This is inexact, and unchanging.  It is their hometown,
  // not their current location.  Generally, it should be
  // some business near where they congregate
  schema1.addGeoPoint("location",{required:true});
  schema1.addRelation("members","_User");
  schema1.addString("description",{required:true});
  schema1.addString("category",{required:true});
  schema1.addBoolean("verified",{required:true,defaultValue:false});
  schema1.save();
  console.log("createPublicCellTable done");
};
```
The "members" relation works fine.  This query returns the cells of which the user in question is a member.

```  const joinedQ = new Parse.Query("PublicCell");
  joinedQ.equalTo("members", user);
  console.log(joinedQ);
  const joined = await joinedQ.find();
  
  console.log("joined");
  for(var i=0;i<joined.length;i++){
    const cell = joined[i];
    console.log("  "+cell.get("name"));
  };
  console.log("");

```

### Steps to reproduce

Create the class above, create an instance which is owned by your user, and the query for instances of PublicCell which are owned by your user.  

### Actual Outcome

I got nothing back.

### Expected Outcome

I expected to get my objects.

### Environment

Server
- Parse Server version: `Reproduced with the bleeding edge version from gitub`
- Operating system: `Ubuntu`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `AWS`

Database
- System (MongoDB or Postgres): `Postgres`
- Database version: `psql (PostgreSQL) 12.9 (Ubuntu 12.9-0ubuntu0.20.04.1)`

- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `parse-server and postgres both live on the AWS box.`

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): `Latest al`
- SDK version: `FILL_THIS_OUT`

### Logs

Ok, having answered the questions, I seem to have the fix.  It works for me for the queries I am trying to do, though it might break other stuff.

```
diff --git a/src/Adapters/Storage/Postgres/PostgresStorageAdapter.js b/src/Adapters/Storage/Postgres/PostgresStorageAdapter.js
index f787d9f1..c72f471e 100644
--- a/src/Adapters/Storage/Postgres/PostgresStorageAdapter.js
+++ b/src/Adapters/Storage/Postgres/PostgresStorageAdapter.js
@@ -729,7 +729,8 @@ const buildWhereClause = ({ schema, query, index, caseInsensitive }): WhereClaus
         values.push(fieldName, JSON.stringify([fieldValue]));
         index += 2;
       } else {
-        patterns.push(`$${index}:name = $${index + 1}`);
+        patterns.push(`($${index}:name)::json->>'objectId' = $${index + 1}::text`);
+        //patterns.push(`$${index}:name = $${index + 1}`);
         values.push(fieldName, fieldValue.objectId);
         index += 2;
       }
```

The old code was comparing (something ... I don't really grok the :name syntax  .. I assume it was the full pointer JSON object ) to fieldValue.objectId.  But the field is not an objectId, it's a Pointer.  So I changed it to use the postgres "extract field as text from json" operator, and that made my shit work.

I have not tested all of the system with the patch.  But what I am doing now works, and that is all I have time for at the moment.

As a special bonus, I have  second patch for you:

```

diff --git a/src/ParseServer.js b/src/ParseServer.js
index e6b30d19..da6b7500 100644
--- a/src/ParseServer.js
+++ b/src/ParseServer.js
@@ -205,7 +205,7 @@ class ParseServer {
       // verify the server url after a 'mount' event is received
       /* istanbul ignore next */
       api.on('mount', function () {
-        ParseServer.verifyServerUrl();
+        setTimeout(ParseServer.verifyServerUrl, 1000);
       });
     }
     if (process.env.PARSE_SERVER_ENABLE_EXPERIMENTAL_DIRECT_ACCESS === '1' || directAccess) {

```
There seems to be a race condition in the startup code which caused my server to emit the following warning on startup:

```
             `\nWARNING, Unable to connect to '${Parse.serverURL}'.` +
                ` Cloud code and push notifications may be unavailable!\n`
```

Using setTimeout to delay the test by one second resolves the issue.

I hope these patches are useful to you, and I declaim all ownership of them.  Use them any way you like, with no expectation of recompens.

**Comment by PopeNobody** [comment]
Sorry I didn't have time to go through the bug report process a second time for the second patch.

**Comment by PopeNobody** [comment]
It looks like my data was wrong.  Sorry about that!

Things seem to have gone wrong when copying data from mongodb to postgres.

**Comment by mtrezza** [comment]
> It looks like my data was wrong. Sorry about that!

Can we close this issue as false alarm?

**Comment by PopeNobody** [comment]
I'm afraid so.  I am in the process of moving a parse installation from parse to mongo, and it appears that I was not getting any results because I had not munged the data properly.  It was in the as a tripple, like you see of you do a console.log() of a fresh parse object, but it was supposed to be just the object id in the column.  When I fixed the data, the problem stopped happening.

**Comment by mtrezza** [comment]
Great, thanks for clarifying, I'll go ahead and close.
