### ISSUE TITLE
Server still uses deprecated url.parse method

### ISSUE THREAD

**Issue by cbaker6** [parse-community/parse-server#7762]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description

The currently uses a deprecated method, [url.parse()](https://nodejs.org/api/url.html#urlparseurlstring-parsequerystring-slashesdenotehost)

### Steps to reproduce

Look through the code of the server.

### Actual Outcome

`url.parse()` is used in multiple places.

### Expected Outcome

`new URL` to be used instead. 

### Environment

Server
- Parse Server version: 5.0.0-alpha.13
- Operating system: N/A
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): N/A

Database
- System (MongoDB or Postgres): Postgres
- Database version: N/A
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): N/A

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): N/A
- SDK version: N/A

**Comment by mtrezza** [comment]
Classified as feature due to lack of refactor tag; will be merged as `refactor` commit type.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-alpha.17](https://github.com/parse-community/parse-server/releases/tag/5.0.0-alpha.17)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-beta.10](https://github.com/parse-community/parse-server/releases/tag/5.0.0-beta.10)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.1.0](https://github.com/parse-community/parse-server/releases/tag/5.1.0)
