### ISSUE TITLE
Listening on 127.0.0.1 raises a warning

### ISSUE THREAD

**Issue by marvinroger** [parse-community/parse-server#7763]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description

This was already raised in #4506, but the issue was closed.
When I start my Parse server listening on `127.0.0.1`, I have the following warning:

```txt
  console.warn
    
    WARNING, Unable to connect to 'http://127.0.0.1:14744/api'. Cloud code and push notifications may be unavailable!
    

      at node_modules/parse-server/src/ParseServer.js:332:21

  console.warn
    Response: Error: connect ECONNREFUSED 127.0.0.1:14744
        at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1146:16) {
      errno: -61,
      code: 'ECONNREFUSED',
      syscall: 'connect',
      address: '127.0.0.1',
      port: 14744
    }
```

The problem comes from these lines: https://github.com/parse-community/parse-server/blob/alpha/src/ParseServer.js#L207-L209

There's a race condition here. When the app is mounted, the underlying server might not be listening yet.
When listening on `localhost`, the warning is not raised because of the DNS resolution (either on the `listen` or on the `verifyServerUrl` call), which takes some time. But when using an IP, like `127.0.0.1`, the DNS resolution is skipped, the request from `verifyServerUrl` is done straight away, and the server is not yet listening, resulting in the warning.

I am not sure what can be done here (`mount` is not the right event to listen to, `listening` would be perfect, but  this event does not exist from within a "sub" express app), except from removing this side-effect.

### Steps to reproduce

Listen a Parse server with a server URL of `127.0.0.1`

### Actual Outcome

A warning

### Expected Outcome

No warning

### Environment

Server
- Parse Server version: 4.10.4
- Operating system: macOS 12.1
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): Local

**Comment by needpower** [comment]
@marvinroger I have the similar type of issue, but with localhost

```
WARNING, Unable to connect to 'https://parse-platform:1337/parse'. Cloud code and push notifications may be unavailable!
```

The important thing is that warning happens only when parse-server runs inside a Docker container.
But i can directly access to parse-server with REST API, for example:
```
POST https://localhost:1337/parse/classes/_User
```

So question here: where is the best place to ask for help/ideas how to resolve this? I'm not sure wether this is a problem in parse-server, or docker, or in my docker-compose configuration.

**Comment by needpower** [comment]
@marvinroger Hello!
Any news or updates on that?

**Comment by marvinroger** [comment]
Hi @needpower 
I ended up creating an express app, bind it, then mounting the Parse server express app on it. Therefore, the server is already listening on Parse mount, and the warning is not raised 😉

**Comment by mtrezza** [comment]
A note for Parse Server 6; it's important to await starting Parse Server *before* adding it to the express app:

```js
const parseServer = new ParseServer({ ... });
const expressApp = express();
await parseServer.start();
expressApp.use('/parse', parseServer.app);
```

Asynchronous start of Parse Server has been introduced with Parse Server 6; this issue was reported for Parse Server 4 and any version below Parse Server 6 is unsupported at this time, hence I'm closing this issue.
