### ISSUE TITLE
CloudCode errors are sent back as html

### ISSUE THREAD

**Issue by markuswinkler** [parse-community/parse-server#7767]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description

Errors from cloud code functions get returned as HTML instead of JSON objects, which prevents from parsing the error in the iOS client.

In reference to #4991

### Steps to reproduce
All three different examples produces the actual outcome.
```
Parse.Cloud.define("ping", async (request) => {
	return Promise.reject('This is my error')
});

Parse.Cloud.define("ping2", async (request) => {
	return Promise.reject(new Parse.Error(999, "This is my error"));
});

Parse.Cloud.define("ping3", async (request) => {
	throw new Parse.Error(999, "This is my error");
});
```

### Actual Outcome
```
HTTP/1.1 500 Internal Server Error
X-Powered-By: Express
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET,PUT,POST,DELETE,OPTIONS
Access-Control-Allow-Headers: X-Parse-Master-Key, X-Parse-REST-API-Key, X-Parse-Javascript-Key, X-Parse-Application-Id, X-Parse-Client-Version, X-Parse-Session-Token, X-Requested-With, X-Parse-Revocable-Session, X-Parse-Request-Id, Content-Type, Pragma, Cache-Control
Access-Control-Expose-Headers: X-Parse-Job-Status-Id, X-Parse-Push-Status-Id
Content-Security-Policy: default-src 'none'
X-Content-Type-Options: nosniff
Content-Type: text/html; charset=utf-8
Content-Length: 475
Date: Sun, 09 Jan 2022 20:38:30 GMT
Connection: close

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Error: This is my error<br> &nbsp; &nbsp;at /<redacted>/main.js:1361:8<br> &nbsp; &nbsp;at /<redacted>/node_modules/parse-server/lib/Routers/FunctionsRouter.js:173:16<br> &nbsp; &nbsp;at processTicksAndRejections (internal/process/task_queues.js:95:5)</pre>
</body>
</html>
```

### Expected Outcome
```
{
    "code": 999,
    "error": "This is my error"
}
```

### Environment

Server
- Parse Server version: `1.19.3`
- Operating system: `macOS`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `local`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `4.4.10`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `local`

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): `iOS`
- SDK version: `1.19.3`

### Logs
```
verbose: REQUEST for [POST] /parse/functions/ping: {} {"body":{},"headers":{"connection":"close","content-length":"0","host":"localhost:1337","user-agent":"Paw/3.1.8 (Macintosh; OS X/10.16.0) GCDHTTPRequest","x-parse-application-id":"<redacted>","x-parse-client-key":"<redacted>","x-parse-os-version":"14.1 (16C50)","x-parse-session-token":"<redacted>"},"method":"POST","url":"/parse/functions/ping"}
error: Failed running cloud function ping for user <redacted> with:
  Input: {}
  Error: {"message":"This is my error","code":999} {"error":{"code":999,"message":"This is my error"},"functionName":"ping","params":{},"user":"<redacted>"}
Error: This is my error
    at /<redacted>/main.js:1361:8
    at /<redacted>/node_modules/parse-server/lib/Routers/FunctionsRouter.js:173:16
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Comment by markuswinkler** [comment]
*Bump*. Any takers? :)

**Comment by dblythy** [comment]
This was happening to me a while ago when I was using `enableExpressErrorHandler`. Could you please try to replicate on a newer version of Parse Server, and let us know your server configuration?

Could you also create a failing PR with the tests to help demonstrate the behaviour that you are seeing.

**Comment by markuswinkler** [comment]
Ohhhh, yes, that let me trace it down. Thank you!
I had to add this at the end of `index.js` to enable both, correct error messages and Sentry integration.
```
app.use(Sentry.Handlers.errorHandler());

app.use(function onError(err, req, res, next) {
	res.setHeader('content-type', 'application/json');
	res.statusCode = 400;
	res.send({"code": err.code, "error": err.message});
});
```
