### ISSUE TITLE
Password authentication fails and server fails to connect to database

### ISSUE THREAD

**Issue by pmmlo** [parse-community/parse-server#7778]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description

From pre-release 5.0.0-alpha.16 to 5.0.0-alpha.17, I get the following critical error: `error: password authentication failed for user "X"`, using PostgreSQL 14.x with enforced TLS.

### Steps to reproduce

1. Setup a base Express Server setup.
2. Run Parse, GraphQL, and LiveQuery servers.
3. Confirmation all servers are started without issue.
3. Error occurs following the start of the servers.

### Actual Outcome

`error: password authentication failed for user "X"` and server fails to connect to database.

### Expected Outcome

No error.  Successful connection to database.

### Environment

PostgreSQL 14.x with TLS enforced.

Server
- Parse Server version: 5.0.0-alpha.17
- Operating system: Dockers on unix
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): local

Database
- System (MongoDB or Postgres): Postgres
- Database version: 14.x
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): local

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): JS
- SDK version: Default in version.

### Logs

`error: password authentication failed for user "X"` and server fails to connect to database.

**Comment by ThornWu** [comment]
Did the client correctly being initialized before using it?

https://github.com/parse-community/parse-server/blob/826aa79b9fb1c7c65ae8e72726c97a9d7acb40c4/src/ParseServer.js#L78

https://github.com/parse-community/parse-server/blob/826aa79b9fb1c7c65ae8e72726c97a9d7acb40c4/src/Controllers/index.js#L43

https://github.com/parse-community/parse-server/blob/826aa79b9fb1c7c65ae8e72726c97a9d7acb40c4/src/Controllers/index.js#L155

https://github.com/parse-community/parse-server/blob/826aa79b9fb1c7c65ae8e72726c97a9d7acb40c4/src/Controllers/index.js#L230-L234

https://github.com/parse-community/parse-server/blob/826aa79b9fb1c7c65ae8e72726c97a9d7acb40c4/src/Adapters/Storage/Postgres/PostgresStorageAdapter.js#L846-L847

https://github.com/parse-community/parse-server/blob/826aa79b9fb1c7c65ae8e72726c97a9d7acb40c4/src/Adapters/Storage/Postgres/PostgresStorageAdapter.js#L1263-L1269

**Comment by mtrezza** [comment]
> From pre-release 5.0.0-alpha.16 to 5.0.0-alpha.17, I get the following critical error

Just to confirm, you do not get that error with 5.0.0-alpha.15?

**Comment by pmmlo** [comment]
> Just to confirm, you do not get that error with 5.0.0-alpha.15?

I actually checked 5.0.0-alpha.16.  Works without issue.  I also tried 5.0.0-alpha.18 with the change manually reverted and no issue.

**Comment by mtrezza** [comment]
@pmmlo would you please try to write a failing test for this issue? this is currently blocking the Parse Server 5 release, so it would be great if we could solve this within the next few days. being able to reproduce this would be an important first step. if we cannot reproduce this issue, we can't fix it and we'd assume that it's a custom code issue in your environment, so we'd make a release with this uncertainty.

If you cannot reproduce this with a test, I'd just set a breakpoint for the auth error and then go back step-by-step in the caller chain to find the issue. You could also compare the behavior this way for both, the working code without the change in https://github.com/parse-community/parse-server/pull/7678 and the failing code with the change.

Referencing [your comment ](https://github.com/parse-community/parse-server/pull/7678#issuecomment-1014220740)as it contains some more details.

**Comment by pmmlo** [comment]
> @pmmlo would you please try to write a failing test for this issue? this is currently blocking the Parse Server 5 release, so it would be great if we could solve this within the next few days. being able to reproduce this would be an important first step. if we cannot reproduce this issue, we can't fix it and we'd assume that it's a custom code issue in your environment, so we'd make a release with this uncertainty.
> 
> If you cannot reproduce this with a test, I'd just set a breakpoint for the auth error and then go back step-by-step in the caller chain to find the issue. You could also compare the behavior this way for both, the working code without the change in #7678 and the failing code with the change.
> 
> Referencing [your comment ](https://github.com/parse-community/parse-server/pull/7678#issuecomment-1014220740)as it contains some more details.

In that case, I suggest just proceeding with the community plan.  I'm just reporting bugs and issues that I think could potentially become bigger problems.  At least now, we know a similar db auth error in the future could stem from this seemingly unrelated line.

I think this most certainly could be an implementation case.

For example, in the test environment, I enforced strict TLS to authenticate postgres.  In a production environment, I think that should be done for most cases but understand not everyone can/does.  Could also be other configurations in postgres, firewall ports, private network... 

If I'm the only one running into this issue, I say just send it.  Worst case is it becomes a widespread issue and we just revert that line in the future (low chance of merge conflict).

@mtrezza Cheers for looking into the issue with me.

**Comment by pmmlo** [comment]
I never tested alpha 15 but no errors on alpha 16.

**Comment by mtrezza** [comment]
@pmmlo just before we close this issue, could you help me trying to reproduce this?

Does this issue occur also without GraphQL and LiveQuery servers and only a fresh, plain install of Parse Server connected to PostgreSQL 14.x with TLS enforced? And if you turn off TLS does the issue go away?

**Comment by pmmlo** [comment]
It’s tough to replicate my environment because you would have to setup a production distributed architecture on k8s.  It lets me see where Parse is in a realistic environment.  I wrote up a single command script to setup new clusters but can’t share it.

The basics: HA postgres with gis 14.1 deployed in a vps with firewall/port forwards, parse-server replicas.

I don’t run Parse in a real production application.  I just contribute as I can and check-in from time to time.

It sounds like the community is seeing a caching/idempotency issue that I haven’t encountered, which requires the line.  It seems like I’m the only one running into this so I say do the community consensus: push the current commits as-is.

**Comment by mtrezza** [comment]
I see, then let's assume for now that it's an env specific issue, close it and release Parse Server 5. We can try to keep this in mind in case related issues pop up in the next couple of weeks after v5 release. In case you find the time to try to reduce this issue down to a simple deployment of Parse Server that one can reproduce locally, we can pick this up again, but in any case I expect we'd get feedback if this is really a server bug.
