### ISSUE TITLE
Memory consumption doubled on the alpha branch

### ISSUE THREAD

**Issue by mman** [parse-community/parse-server#7785]
### New Issue Checklist
- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description
I am running forked alpha branch (with my tiny additions) in production for many months now. On Jan 7 I performed a deployment using the latest alpha available at that time, and since then the memory consumption of parse-server doubled. See the attached image.

<img width="1487" alt="Screenshot 2022-01-25 at 10 59 53" src="https://user-images.githubusercontent.com/249814/150955756-07702b5d-c744-4d54-bba6-df50e3a0b92a.png">

Original deployment was in production since Dec 3 (5.0.0-alpha-11): https://github.com/mman/parse-server/commit/c1e3d36a8e821411297e6906be5f207d1afecc0f

New deployment on Jan 7 (5.0.0-alpha-16): https://github.com/mman/parse-server/commit/e58216bc25f4feb7c7d16ded72914d649a811eb4

### Actual Outcome
Memory consumption doubled just by rebuilding and redeploying, same version of node, same environment, same docker, etc.

### Expected Outcome
I would expect the memory consumption to remain about the same since we are at this moment only pulling in .point updates for dependencies.

### Notes
I am currently looking at what the merge brought in on Jan 7 to better understand where is the memory consumption coming from. It may be expected behavior actually. Just wanted to give a heads up before 5.0 is officially wrapped. Looks like something between alpha 11 and alpha 16 is causing more heap to be allocated.

**Comment by mtrezza** [comment]
> forked alpha branch (with my tiny additions)

That may make it difficult to verify. I agree that the best way would be to go back in alpha releases until the issue disappears.  Note that there may be multiple commits between alpha releases, as not every commit leads to a release.

Just to mention that the method of "redeployment" may contribute to changes in the server resources. Restarting or launching a fresh server instance for each deployment may make metrics most comparable. Just deploying and restarting node may not be.

**Comment by mman** [comment]
@mtrezza I am aware of all these issues, I use this workflow for more than a year when I forked the repo and I am pretty confident in my findings. Looking through the merges, looks like only significant addition was the idempotency features?

**Comment by mtrezza** [comment]
Once you've determined the exact commit (not version) where you begin observing the issue - unless it's something obvious - we'd need to know more about your server config and maybe what your custom changes in the server code are and whether this can be reproduced with the unmodified version. Another note when determining the commit: try to also go back to the previous commit and verify that the heap size goes gown again. Heap size management is a complex topic that can sometimes seem rather opaque.

**Comment by Moumouls** [comment]
@mman after a quick check on my workloads, i've an old parsev5 on prod and the last one on staging.

Here an old version.

<img width="270" alt="Capture d’écran 2022-01-30 à 19 45 12" src="https://user-images.githubusercontent.com/27959372/151713053-8ffea5a2-b880-494b-8147-0d5123a9aec6.png">

Here the last alpha
<img width="211" alt="Capture d’écran 2022-01-30 à 19 45 24" src="https://user-images.githubusercontent.com/27959372/151713083-c6f0c63d-bc55-4213-920d-3fa20ab86cb2.png">

The 50MB diff in favor of the last alpha could be related to my code.

But the memory do not have doubled.

So @mman if you can make some investigation/inspection on your parse server it could help 👍

**Comment by mtrezza** [comment]
@Moumouls Thanks for x-checking

@mman I think the best comparison may be with a defined performance test. You can find examples in an open Parse Server issue (that I can't find right now) where we have made load tests in trying to identify a performance bottleneck in the conversion of BSON to JSON (or was it JSON to Parse Object). Something similar to that could give you a hint. 

You could also try using a tracing tool like NewRelic to drill down into where the increased heap allocation comes from. Note that heap allocation is not necessarily the same as "memory required by Parse Server". It depends on hardware resources and what else may be going on in your node process(es).

**Comment by Moumouls** [comment]
@mtrezza i also remember that parse server was able to run with 130-150MB of memory usage WITHOUT GRAPHQL.

In my case i've a huge GraphQL schema and child process with heavy webassembly module loaded. This should be a significant part of the 300MB reported on my side. (the 300MB is to total footprint of my docker container)

**Comment by mman** [comment]
@Moumouls @mtrezza I will not have a time to look into this for the next two weeks, but as my setup is super stable and not changing at all for more than a year, except bringing in latest parse alpha from time to time... Let me dig into it after two weeks.

**Comment by Moumouls** [comment]
No problem @mman keep us updated

**Comment by mman** [comment]
@Moumouls @mtrezza Guys, after yesterdays sync with alpha branch the memory consumption reverted back to where it was before... Not sure what has changed, perhaps one of the dependencies, but it's definitely visible and stable...
<img width="481" alt="Screenshot 2022-09-13 at 11 57 58" src="https://user-images.githubusercontent.com/249814/189872816-27e6f654-7662-4b59-9f9d-cae5a51f5982.png">

Great work whoever unknown individual who is responsible for this 👍

**Comment by Moumouls** [comment]
Looks interesting @mman thanks for your feedback on my side i never noticed the huge memory consumption issue.
Currently Parse receive mainly automatic dependencies updates, your issue is maybe related to a dependency.

What is your running environment? Docker, Node version ?, Bare metal install?

**Comment by mman** [comment]
@Moumouls Docker running node 14 with only basic dependencies (push adapter, mailgun, s3). For now I blame one of the nested parse server dependencies as our server schema is pretty much default with no extra classes or logic.

```
  "dependencies": {
    "@apollo/client": "^3.6.9",
    "@parse/push-adapter": "^4.1.2",
    "@parse/s3-files-adapter": "^1.6.2",
    "axios": "^0.24.0",
    "express-prometheus-middleware": "^0.8.5",
    "form-data": "^4.0.0",
    "graphql": "15.7.0",
    "mailgun.js": "^3.7.2",
    "parse-server": "git+https://github.com/mman/parse-server.git#generate-password-reset-link",
    "parse-server-api-mail-adapter": "^2.1.0",
    "pem": "^1.14.6"
  },
```
