### ISSUE TITLE
`SchemaOptions` definition not properly added

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-server#7805]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description
The Parse Server options `SchemaOptions` which were added in https://github.com/parse-community/parse-server/pull/7418 were not properly added to the definition file.

The `SchemaOptions` are defined in `/src/Options/Definitions.js`, but when re-building the options with `npm run definitions`, the options are removed.

### Steps to reproduce
1. Run `npm run definitions`

### Actual Outcome
Schema options are removed from `/src/Options/Definitions.js`.

### Expected Outcome
Schema options should be properly re-built.

### Environment

Server
- Parse Server version: `5.0.0-alpha.24`

**Comment by mtrezza** [comment]
@sadortun @Moumouls could you take a look?

**Comment by dblythy** [comment]
What do you think about having `npm run definitions` ran / checked by the CI?

**Comment by mtrezza** [comment]
What do you mean by "checked by the CI"?

**Comment by dblythy** [comment]
Well I’m assuming here that a contributor thought that they had to manually edit the Definitions.js file (even though it says “ Do not manually), instead of adding to index.js. I think it would be good to possibly have a CI check to make sure npm run definitions matches the committed Definitions.js file, so we can be sure no manual editing has been applied.

**Comment by mtrezza** [comment]
Got it, I think we could simply generate the definitions file again and compare the result with what's been committed. Or do you have a different idea?

**Comment by Moumouls** [comment]
The source of the problem is simply related to the fact that the definitions were added manually to the auto-generated file

**Comment by mtrezza** [comment]
Thanks for fixing this, the discussion was about how to prevent that in the future. Generating the definitions file and comparing it to the current definitions seems an easy check for the CI. I opened https://github.com/parse-community/parse-server/issues/7918 so we close this issue with your fix.

**Comment by mtrezza** [comment]
Closed via #7917
