### ISSUE TITLE
BeforeSave and AfterSave on Same Object continues in a recursive cycle forever if req.object.saveAll() is called.

### ISSUE THREAD

**Issue by malcolm-dane** [parse-community/parse-server#7815]
### New Issue Checklist

- [ ] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [ ] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [ ] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [X ] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description
In cloud function having a before save and Aftersave trigger assigned to the same Object  and changing the object in some way then calling save all from the before save trigger function causes a huge recursion loop and doesn't crash. While this is a stupid thing to do, I just did it by mistake and it wrote 14000 records to the DB, Only stopped when I manually disabled it. While the mistake was caused by poor documentation in my code and 2 different cloud code function paths, there should be something hard coded to prevent this from happening. 

### Steps to reproduce
   I can't remember the exact code and don't want to try again but it was something like this.

   Parse.Cloud.beforeSave('ContactUs', async( request) => {
   request.object.set('foo',encodeURIComponent(request.object.get('foo'));
   request.object.saveAll();
});

   psuedo code**
   Parse.Cloud.afterSave('ContactUs', async( request) => {
   mailSomething(request)->call back update on-success()  query that object  and write to the field 'sent:true' 

   request.object.saveAll();
});
That alone should do it but having an AfterSave trigger on the same object that also makes,creates, or destroys a record makes it even worse.

### Actual Outcome
Recursion and exponential growth and no crashing.

### Expected Outcome
Hard crash or build error for having a before and after trigger on the same function
### Environment
 "node": "14.18.1"
MongoAtlas

Server
    "express": "4.17.1",
    "parse": "3.4.0",
    "parse-server": "4.10.0",

Database
Atlas

Client
-Javascript

**Comment by mtrezza** [comment]
I'm closing this as it does not seem to be a Parse Server issue.

From the description so far it sounds like a developer mistake. If you can provide a detailed code example to reproduce the issue, we can reopen it and possibly classify it as a bug.

**Comment by malcolm-dane** [comment]
I agree but the before save and after save shouldn't be allowed either on
build it should fail, or fail when the object is put. It shouldn't
recursively continue until I shut down the web application or run out of
memory or depend on me making a commit and redeploy. It should fail safe.
