### ISSUE TITLE
Parse server cloud code mixed up the configuration

### ISSUE THREAD

**Issue by gadgetreviews** [parse-community/parse-server#7826]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description

I am using several apps with same parse server hosted on my AWS EC2 server. And two apps mixed up. Let me explain with an example:

I have app1 with db1 mongodb, user1 mongodb user, master1 master key, and app1 appId. And I have app2 with db2 mongodb, user2 mongodb user, master2 master key, and app2 appId. Both have their own cloud code.

When I try to create an object from app2 with its cloud code from mobile app via cloud code, cloud code creates this object at app1's db1.

I tried to delete db2 and user2 and re-create them with new appId, new master key and password. But nothing is changed.

I am using dash-dashboard 4.0.0 and parse-server 4.10.4 

This is a part of server.js configuration:
```
var app = express();
var mountPath = '/parse';

var api1 = new ParseServer({
  databaseURI: 'mongodb://app1:pass1@localhost:27017/app1',
  appId      : 'appId1',
  masterKey  : 'master1',
  serverURL  : 'http://127.0.0.1:1337/parse',
  publicServerURL: 'https://my.company.com/parse',
  cloud: './cloud/app1/main.js',
  allowClientClassCreation: false,
});
app.use(mountPath, api1);

var api2 = new ParseServer({
  databaseURI: 'mongodb://app2:pass2@localhost:27017/app2',
  appId      : 'appId2',
  masterKey  : 'master2',
  serverURL  : 'http://127.0.0.1:1337/parse',
  publicServerURL: 'https://my.company.com/parse',
  cloud: './cloud/app2/main.js',
  allowClientClassCreation: false,
});
app.use(mountPath, api2);
```
### Steps to reproduce

It is hard to reproduce. I have 8 different apps with same parse server and only 2 of them mixed.

### Actual Outcome

New objects created at db1.

It looks like cloud code of app2 is running on app1's db1 db with user1 user instead of app2's db2 db with user2 user.

### Expected Outcome

I expected new objects should be created at db2.

### Environment

dash-dashboard 4.0.0
parse-server 4.10.4 
Ubuntu server 20.04.3 LTS
MongoDB 4.0.28

Server
- Parse Server version: `4.10.4`
- Operating system: `Ubuntu server 20.04.4 LTS`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `AWS`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `4.0.28`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `local`

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): `Android`
- SDK version: `flutter parse_server_sdk_flutter 3.1.0`

### Logs

No relevant log I have.

**Comment by dblythy** [comment]
Does this issue still occur if you use separate `mountPaths` for the different Parse Servers?

**Comment by gadgetreviews** [comment]
I solved this problem by dedicating a parse server process and dedicated mountPath for each app. Nothing is shared and I don't have that problem anymore. In fact this method is better. I can stop and start each app's parse server individually. Previously I have to stop all of app's parse servers at the same time. This caused problems. Now this problem is gone too.

**Comment by dblythy** [comment]
Good to hear. Feel free to open a discussion in the [community forum](https://community.parseplatform.org/) if you need any additional support with your configuration.
