### ISSUE TITLE
Add SecurityChecks to check `masterKey` is rotated regularly

### ISSUE THREAD

**Issue by dblythy** [parse-community/parse-server#7872]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation

Rotating a masterKey regularly is recommended to improve security.

### Feature / Enhancement Description

Not sure how this would work, but add security check to check masterKey has been rotated.

### Example Use Case

n/a

### Alternatives / Workarounds

n/a

### 3rd Party References

n/a

**Comment by mtrezza** [comment]
I think this is beyond Parse Server. Rotation is happening on a meta level of the server, so the check also has to be on the meta level.

**Comment by dblythy** [comment]
Yeah, good point. Otherwise we would have to store previous masterKeys in memory which could open another can of worms
