### ISSUE TITLE
mongoOptions aren't passed to GridFSBucketAdapter

### ISSUE THREAD

**Issue by dblythy** [parse-community/parse-server#7910]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description

If you are using custom `databaseOptions` in your Parse Server options (such as `sslKey`), the default GridFS file storage stops working.

### Steps to reproduce

Create a Parse Server with `databaseOptions`, using a mongoDB with certificate auth. Attempt to save a file..

### Actual Outcome

Certificate validation fails

### Expected Outcome

Files to save

### Environment

Server
- Parse Server version: `alpha`
- Operating system: `macos`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `local`

Database
- System (MongoDB or Postgres): `mongo`

**Comment by mtrezza** [comment]
Closed via #7911
