### ISSUE TITLE
Upgrade GraphQL dependencies

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-server#7916]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation
GraphQL dependencies have updates available, which require code changes to get merged. Tests for MongoDB are failing.

**Comment by mtrezza** [comment]
See:
- [ ] https://github.com/parse-community/parse-server/pull/7902
- [ ] https://github.com/parse-community/parse-server/pull/7903
- [ ] https://github.com/parse-community/parse-server/pull/7900
- [ ] https://github.com/parse-community/parse-server/pull/7901

**Comment by Urigo** [comment]
What about using and moving to GraphQL Yoga 2.0?
https://twitter.com/TheGuildDev/status/1508775984748589064

**Comment by mtrezza** [comment]
@Urigo Sounds interesting, would you want to open a new issue regarding this for discussion?

**Comment by Urigo** [comment]
yes, opened here: https://github.com/parse-community/parse-server/issues/7936

**Comment by Moumouls** [comment]
I'll add this one to my todo list @mtrezza  🙂

**Comment by Moumouls** [comment]
can we close this one @mtrezza  ?

**Comment by mtrezza** [comment]
I think so, seems like this has been resolved with https://github.com/parse-community/parse-server/pull/7970
