### ISSUE TITLE
Depreciate `Parse.Cloud.beforeSaveFile(() => {})` in preference to `Parse.Cloud.beforeSave(Parse.File, () => {})`

### ISSUE THREAD

**Issue by dblythy** [parse-community/parse-server#7928]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation

Currently, the file triggers have their own unique syntax, which isn't necessary as they follow the standard trigger types (beforeSave, afterSave, etc).

### Feature / Enhancement Description

Allow `Parse.Cloud.beforeSave(Parse.File)` and depreciate existing file methods.

### Example Use Case

n/a

### Alternatives / Workarounds

n/a

### 3rd Party References

n/a

**Comment by mtrezza** [comment]
Closing via #7966
