### ISSUE TITLE
graphql peer dependencies mismatch

### ISSUE THREAD

**Issue by marvinroger** [parse-community/parse-server#7933]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description

The `graphql` dependency does not match the peer dependencies requirements.

### Steps to reproduce

Installing with `yarn` prints peer dependencies issues.

### Actual Outcome

```
➤ YN0000: parse-server@npm:5.2.0 provides graphql@npm:15.7.1 with version 15.7.1, which doesn't satisfy the following requirements:

➤ YN0000: subscriptions-transport-ws@npm:0.11.0 [b75e4] → ^15.7.2 || ^16.0.0 ✘
```

### Environment

No warning.

Server
- Parse Server version: 5.2.0

**Comment by mtrezza** [comment]
I suppose even with the PR, we will continue to run into these mismatches in the future. What can we do about that?

**Comment by marvinroger** [comment]
The only way I've found is to use Yarn Berry, which prints warnings when there's such a mismatch.
AFAIK, npm does not provide these kind of hints, but maybe a CI check like https://github.com/christopherthielen/check-peer-dependencies can do the trick?
