### ISSUE TITLE
Apple Game Center CI tests flaky

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-server#7947]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description
CI tests related to Apple Game Center are often failing:

```
1) Apple Game Center Auth adapter validateAuthData should validate
2) Apple Game Center Auth adapter validateAuthData invalid signature id
  - Expected 'error:0D0680A8:asn1 encoding routines:asn1_check_tlen:wrong tag' to be 'Apple Game Center - invalid signature'.
```

This only started recently and the tests only fail sometimes, so it may be an issue with test structure or the random order in which the tests are executed.

### Steps to reproduce
See https://github.com/parse-community/parse-server/runs/6118780493?check_suite_focus=true#step:8:3965

### Actual Outcome
Tests should pass

### Expected Outcome
Tests fail sometimes

### Environment
n/a

Server
- Parse Server version: `[5.3.0-alpha.6](https://github.com/parse-community/parse-server/releases/tag/5.3.0-alpha.6)`

**Comment by dblythy** [comment]
I believe the certificate required for gamecenter tests should be https://static.gc.apple.com/public-key/gc-prod-6.cer, as explained [here](https://developer.apple.com/forums/thread/686122)

**Comment by dblythy** [comment]
I think we also need to update the test signatures, however I can’t work out how to do this to get them to pass with the newer cert. @mtrezza any thoughts?

**Comment by mtrezza** [comment]
Closing via https://github.com/parse-community/parse-server/pull/7958#event-6528013469, thanks @dblythy
