### ISSUE TITLE
Updating schema of User class

### ISSUE THREAD

**Issue by sarsonj** [parse-community/parse-server#7949]
### New Issue Checklist

- [X] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [X] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [X] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [X] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description
We are pre-creating some fields in schema in our app using `Parse.Schema`. It works for normal classes, but we don't have success with `User` class. 

Code:

```javascript
    const userSchema = new Parse.Schema("User");
    userSchema.addString("referralId")
    userSchema.save({ useMasterKey: true });
```

just runs, but the class is not updated. Even in logs it looks like everything is fine:

```
verbose: REQUEST for [POST] /parse/schemas/_User: {
ttmonitor-server-backend-1              |   "className": "_User",
ttmonitor-server-backend-1              |   "fields": {
ttmonitor-server-backend-1              |     "referralId": {
ttmonitor-server-backend-1              |       "type": "String"
ttmonitor-server-backend-1              |     }
ttmonitor-server-backend-1              |   },
ttmonitor-server-backend-1              |   "indexes": {}
ttmonitor-server-backend-1              | } {"body":{"className":"_User","fields":{"referralId":{"type":"String"}},"indexes":{}},"headers":{"accept":"*/*","connection":"close","content-length":"206","content-type":"text/plain","host":"localhost:1337","user-agent":"node-XMLHttpRequest, Parse/js3.4.1 (NodeJS 16.14.2)"},"method":"POST","url":"/parse/schemas/_User"}
```

Server
- Parse Server version: 5.2.0
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): Docker

Database
- System (MongoDB or Postgres): Postgres
- Database version: 11
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): local

**Comment by dblythy** [comment]
Can you try:

```js

const schema = new Parse.Schema('_User')
schema.addString('referralId');
await schema.update({useMasterKey: true});

```

**Comment by Moumouls** [comment]
@sarsonj  on Parse Server, "core classes" have an `_` before the name.

ex: `_User` or `_Role`, You can also use `new Parse.Schema(Parse.User)`

Feel free to close this issue if everything works as intended

**Comment by mtrezza** [comment]
I'm closing this as it seems to be resolved. Feel free to comment if you have any questions and we can re-open this issue.
