### ISSUE TITLE
Add ability to disable authentication adapter

### ISSUE THREAD

**Issue by dblythy** [parse-community/parse-server#7952]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation

Currently, all internal auth adapters are enabled by default, with no option to disable auth adapters that aren't necessary.

### Feature / Enhancement Description

Allow 

```
auth : {
 facebook: {
   enabled: false
 }
}
```

### Example Use Case

n/a

### Alternatives / Workarounds

n/a

### 3rd Party References

n/a

**Comment by mtrezza** [comment]
Do we need a separate property for this or just disable them if they are not configured in the Parse Server options? Maybe we can make this breaking change in the future and add the option only temporarily, already with a depreciation warning?

**Comment by dblythy** [comment]
That's what I was thinking. Disabling them if they are not configured would be a breaking change. Many auth adapters however don't require any backend configuration and depend fully on client side. Perhaps we can make a change:

- For the adapters that require configuration, if they are in the auth payload (e.g `auth.facebook`) consider them enabled
- For the adapters that do not require configuration, they require `auth.google.enabled` to be enabled.

This still would be a breaking change, however I think it's one worth pushing through.

**Comment by mtrezza** [comment]
If not every adapter requires server configuration then I guess it doesn't work to only enable them if they are configured server side. I think your suggestion makes most sense to introduce an `enabled` property that is currently `true` by default (with a deprecation warning), and then we change this in a later version to `false` by default so one has to manually enable them - for security.

**Comment by dblythy** [comment]
Sounds good!

**Comment by mtrezza** [comment]
Closing via #7953
