### ISSUE TITLE
Apple Game Center test fails

### ISSUE THREAD

**Issue by Moumouls** [parse-community/parse-server#7959]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description
1) Apple Game Center Auth adapter validateAuthData should validate
  - Failed: error:0D0680A8:asn1 encoding routines:asn1_check_tlen:wrong tag

2) Apple Game Center Auth adapter validateAuthData invalid signature id
  - Expected 'error:0D0680A8:asn1 encoding routines:asn1_check_tlen:wrong tag' to be 'Apple Game Center - invalid signature'.

### Steps to reproduce
Run tests on current alpha branch

### Actual Outcome
1) Apple Game Center Auth adapter validateAuthData should validate
  - Failed: error:0D0680A8:asn1 encoding routines:asn1_check_tlen:wrong tag

2) Apple Game Center Auth adapter validateAuthData invalid signature id
  - Expected 'error:0D0680A8:asn1 encoding routines:asn1_check_tlen:wrong tag' to be 'Apple Game Center - invalid signature'.

### Expected Outcome
To pass
### Environment

Server
- Parse Server version: `5.3.0-alpha.7`
- Operating system: `Mac`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `Local`

Database
- System (MongoDB or Postgres): `Mongo`
- Database version: `5`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `Local`

### Logs

1) Apple Game Center Auth adapter validateAuthData should validate
  - Failed: error:0D0680A8:asn1 encoding routines:asn1_check_tlen:wrong tag

2) Apple Game Center Auth adapter validateAuthData invalid signature id
  - Expected 'error:0D0680A8:asn1 encoding routines:asn1_check_tlen:wrong tag' to be 'Apple Game Center - invalid signature'.

**Comment by dblythy** [comment]
Duplicate #7947

**Comment by Moumouls** [comment]
Yes my bad, thanks @dblythy
