### ISSUE TITLE
Websocket error - Parse live sync

### ISSUE THREAD

**Issue by Vidyaranigrao** [parse-community/parse-server#7969]
### New Issue Checklist

- [ ] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [ ] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [ ] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description
```
We recently moved from Cloudfare to Akamai and started seeing the error mentioned below in the logs
Websockets are enabled in Akamai. Could you please let us know what else could be causing this error? 
```

Server
- Parse Server version: `4.3.0`
- Operating system: `Ubuntu 18.04`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `Heroku `

Database
- System (MongoDB or Postgres): `MongoDB `
- Database version: `4.4.13`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `MongoDB Atlas`

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): `iOS`
- SDK version: `ParseLiveQuery 2.7.2`

### Logs
`ParseLiveQuery: WebSocket did disconnect with error: Optional(Starscream.WSError(type: Starscream.ErrorType.upgradeError, message: "Invalid HTTP upgrade", code: 403))`

Thanks,
Vidya

**Comment by Vidyaranigrao** [comment]
@mtrezza , I have updated the issue with required information. Please let me know if you need anything else.

**Comment by mtrezza** [comment]
It still seems to be an environment issue, since the only thing that changed seems to have been the environment. That's why I suggested to post your question in the community forum. Please do not post multiple issues about the same topic. Duplicate of https://github.com/parse-community/parse-server/issues/7965.
