### ISSUE TITLE
APNS config with topic not working for production

### ISSUE THREAD

**Issue by awltr** [parse-community/parse-server#8000]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description
If using APNS config with bundleId parse server says:
WARN parse-server-push-adapter APNS bundleId is deprecated, use topic instead

If you do it so, it works for development but not for production.

### Steps to reproduce
Configure APNS config with topic instead of bundleId with production=true (pfx or pem doesnt matter)

### Actual Outcome
Sending pushes causes the following error: stream ended unexpectedly with status null and empty body

### Expected Outcome
Working

### Environment

Server
- Parse Server version: 5.2.1
- Operating system: docker/k8

Using bundleId works as expected. Suggestion: make topic work for production as well or remove deprecation warning.

**Comment by mtrezza** [comment]
Could you post your configs and the payload?

**Comment by awltr** [comment]
Not quite sure if that helps. As I said, it works now with bundleId. Maybe I created the issue in the wrong project. It should be in https://github.com/parse-community/parse-server-push-adapter

But with a look at the code, that doesn't really make sense (see https://github.com/parse-community/parse-server-push-adapter/blob/e0541ecc5fd894c5bf34815f837ce41cb467c86f/src/APNS.js#L46). Maybe I did have a problem with the pfx. To fix the above error, my first attempt was to change pfx to pem. After that didn't work either, I changed topic to bundleId and it worked. Maybe something was wrong with the deployment while the first attempt. Anyway, I will test this again with pfx and if it doesn't work there again, it was more likely that.

**Comment by mtrezza** [comment]
Thanks for reporting back, I will close this for now. If you can reproduce it, we can always re-open this issue.

**Comment by awltr** [comment]
I have now investigated a bit more and it turns out that this is a sporadic problem and it coincidentally always failed with topic in the configuration. This is of course pretty much the worst, because in a k8 environment you obviously dont want to have such issues in terms of scaling and redeployment.

This issue here can definitely stay closed. But if someone has spontaneous ideas or solutions for the problem, I would of course be grateful (error message see above).

**Comment by mtrezza** [comment]
It would be interesting if you could try to replicate the issue with a new, most basic deployment of Parse Server. That may help you to find out whether it is a pase server issue or specific to your environment.

**Comment by awltr** [comment]
I'm deploying the parse server and either it works for this deployment or not. Maybe it is related to the installation and it helps if I tell a bit more about my setup.

I use ionic capacitor for client registration. On successful registration, I run a cloud function with the deviceToken and the deviceType. I then create the installation as follows:

```
//...
const Inst = Parse.Object.extend(Parse.Installation)
const inst = new Inst()

inst.set('installationId', nanoid(10))
inst.set('appIdentifier', 'my.ios.app')
inst.set('appName', 'My App')
inst.set('appVersion', '1.0')
inst.set('deviceToken', deviceToken)
inst.set('deviceType', deviceType)
await inst.save(null, { useMasterKey: true })
```

Maybe the problem occurs because the installation was not created as the parse standard would do? But that doesn't really explains for me why the problem is sporadic.

**Comment by mtrezza** [comment]
I suggest to use the [Parse Server example app](https://github.com/parse-community/parse-server-example) and deploy it in a local Node.js environment. If you can reproduce the issue in such a commonly used environment, it could increase your chances that more people will investigate.

**Comment by awltr** [comment]
I'll do so. It's most likely an issue with the environment.

Just wanted to make sure that it's supported to create the installation object manually this way. Could not find anything in the documentation. But since it already worked with this approach, I think that should be fine.

**Comment by mtrezza** [comment]
> Just wanted to make sure that it's supported to create the installation object manually this way.

That's a good question. To my knowledge, Parse Server currently has a limitation in some client SDKs (Android, ObjC at least) which require to write to the `_Installation` class directly and there is no way to override / prevent this. The other way around should definitely be possible, you can write to the installation class whatever you want. You just have to make sure to tell the SDK to use that installation ID - and I'm not sure whether every SDK supports this. But generally, if `deviceToken` and push type are correct, you should be able to send a push notification from Cloud Code. The push logic doesn't know (or care) where the installation data came from.

**Comment by mman** [comment]
> I use ionic capacitor for client registration. On successful registration, I run a cloud function with the deviceToken and the deviceType. I then create the installation as follows:

If I read your explanation correctly, you have a client that is using some SDK, that client of course needs its `Installation` class, and will create one automatically during client SDK startup.

But when you register for push notifications, you pass the push deviceToken to the cloud function and create a new `Installation` instance with the correct push details.

How do you then get back the (via cloud code) newly created `Installation` that is now present in the server database back to your client SDK? How you let the SDK know what `Installation` instance it should use?

It's a wild speculation on my side, so sorry if I am completely wrong, but I think your client SDK may still use old `Installation` without any push details.

**Comment by awltr** [comment]
> How you let the SDK know what `Installation` instance it should use?

Maybe I misunderstood something in general but why does the client/sdk need the installation? As long as the correct deviceToken is on the server, sending pushes server-side and receiving them on the client should work completely via APNS.

**Comment by mtrezza** [comment]
Generally, if you are sending a push notification from Cloud Code (not from the client) then it doesn't matter whether the client is using an incorrect installation. All that matters is whether the `deviceToken` you are sending the push to is still valid. But keep in mind that the token should be requested and updated in the installation on every app launch.

If requesting a new token invalidates the old token, and the SDK updates a different installation (as @mman suggested) then the token you are trying to send the push to may have been invalidated. This may happen sporadically as you described because it only happens when the app requests a new token for the device.

**Comment by awltr** [comment]
Okay, I was able to solve the problem by switching to authentication token. I really tried everything now. PFX worked only for sandbox and not for production (although I created the certificate for sandbox&production). PEM worked at first and then only sporadically. Why it still worked sporadically is not clear to me.

Now with authentication token it works even after the third redeployment of the server without any issues.

I got the information that you should use authentication token from here:
https://github.com/parse-community/node-apn/blob/master/doc/provider.markdown

Maybe it would be good to include this in the parse documentation here as well. Because from my point of view this is by far the easiest way.
https://docs.parseplatform.org/parse-server/guide/#2-configure-parse-server

Thanks for your replies and maybe this will help someone who has similar problems with APNS setup.

**Comment by mtrezza** [comment]
Good investigation, would you want to open a PR for the docs, so that others don't fall into the same trap?

**Comment by awltr** [comment]
I don't think it's a trap. Pretty sure I did something wrong while generating the certificates. But I'll see if I could find some time for a PR soon.
