### ISSUE TITLE
Mongo adapter seems to create too many connection

### ISSUE THREAD

**Issue by Moumouls** [parse-community/parse-server#8008]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description
I'm currently load testing Parse Server on Google Cloud Run. I set Cloud Run max container concurrency to 10. 1 Container = 1 Parse Server instance. I expect to get 10 mongodb connections per Parse Server. It seems that Parse Server creates too many connections.

![Capture d’écran 2022-05-20 à 18 33 46](https://user-images.githubusercontent.com/27959372/169573113-0632cf72-624e-49a2-9249-24744a30df01.png)

### Steps to reproduce
Start many parser servers, and load test servers behind a load balancer. Check mongo connections.

### Actual Outcome
Too many connections. Ratio Parse Server/Mongo connection does not seem balanced.

### Expected Outcome
Be close to 10 connections === 1 Parse Server

### Environment

Server
- Parse Server version: `5.2.1`
- Operating system: `Alpine`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `GCP Cloud Run`

Database
- System (MongoDB or Postgres): `Mongo`
- Database version: `5.X`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `Atlas`

**Comment by Moumouls** [comment]
it needs investigation I don't know if this behavior is related to the driver or Parse Server code.

**Comment by mtrezza** [comment]
> I expect to get 1 mongodb connection per Parse Server. It seems that Parse Server create too many connections.

Why do you expect that, where have you set that? The MongoDB driver uses connection pooling. A single connection between a server and a database is a rather unusual scenario. You can set the pool size to 1 if you really want that behavior.

**Comment by Moumouls** [comment]
After a quick check @mtrezza  it seems that this change has been introduced during the majors upgrade from mongodb 3.X -> 4.X.

I found a discussion about this on mongoose repo: https://github.com/Automattic/mongoose/issues/10809

MongoDB changed the default driver pool size from 10 to 100.

It looks like a dangerous change from my point of view since developers that use a lot of "horizontal scaling"  will run out of connections 10 times faster with Parse Server >= 5.1.0.

For example, a developer using Atlas Mongo services M10 will run out of connections with "only" 15 Parse Servers under load. With 3.6, it was 150 Parse Servers.

I also see that for the new service Mongo Serverless current max connections are 500. A developer could run out of connections with "only" 5 Parse Servers. With 3.6 -> 50 Parse Servers.

I don't know how we should handle this. Should we restore the 10 default max connections as the old behavior? Should we write a warning somewhere into the docs/readme ?

What do you think @mtrezza ?

From my point of view, 100 connections look huge, a developer that needs this level of parallel query performance I think will be familiar to tune the mongo client/URI to adjust params for high throughput needs. (high pool connections + default readPreference=secondaryPreferred).

And for common usage, a default reasonable pool size of 10-20 looks good to me.

**Comment by mtrezza** [comment]
Let's unpack this:

- Even though MongoDB released 4.x as major release, they did not mention a default pool size change in their [changelog](https://github.com/mongodb/node-mongodb-native/blob/4.0/docs/CHANGES_4.0.0.md).

- We released the 4.x driver as a feature version because we thought considering all documented breaking changes would be enough.

Who owns this?

Probably no-one and everyone.

What's the solution?

Setting the pool size is the dev's responsibility. 10 connection is as arbitrary as 100 connections. We cannot determine what the proper pool size for an unknown architecture is. We have no stake in this. I suggest to just retroactively add a warning to the Parse Server 3.1.0 release notes.

Anything to learn?

Never trust a changelog. I don't think we can avoid this in the future, because a major increment of a dependency should not automatically lead to a major increment of the dependent. We can only move on.

**Comment by Moumouls** [comment]
i'll close this issue since Parse Server allow to customize the connection pool like:

```js
			databaseURI: process.env.MONGO_URI,
			databaseOptions: {
				maxPoolSize: 30,
			},
```
