### ISSUE TITLE
websocket broken connection not handled in live query server

### ISSUE THREAD

**Issue by pash2048** [parse-community/parse-server#8010]
### New Issue Checklist

- [X] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [X] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [X] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [X] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description
Parse live query not check broken WebSocket connection and close them and 'websocketTimeout' in 'LiveQueryServerOptions' not have any effect, we need to [handle and close broken connection](https://github.com/websockets/ws#how-to-detect-and-close-broken-connections)

### Steps to reproduce
Start a live query server and then connect to those, for example, if we lose our connection(torn off WIFI or ...) we don't get any event with Parse.Cloud.onLiveQueryEvent and connection still open 

### Actual Outcome
if we unplug the ethernet cable or turn off mobile data or WIFI nothing happens and the parse server doesn't get it  

### Expected Outcome
Close connection after websocketTimeout then trigger an event onLiveQueryEvent

### Environment

Server
- Parse Server version: `5.2.1`
- Operating system: `ubuntu-desktop 18.04`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `local and Parspack cloud provider`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `4.4.14`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `local`

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): `JavaScript`
- SDK version: `3.4.2`

**Comment by pash2048** [comment]
Dear @mtrezza, I fix it and want to contribute but problem is that I don't have any idea about how can I create a test to check it.
can you help me, please?

**Comment by pash2048** [comment]
Dear @mtrezza, I fix it and want to contribute but problem is that I don't have any idea about how can create a test to check it.
can you help me, please?

**Comment by mtrezza** [comment]
@pash2048 Sure! I suggest you create a pull request and link it to this issue, so we can take a look.
