### ISSUE TITLE
Modernize API doc template

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-server#8017]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation
The API docs are generated from JSDoc. We are currently using our [forked version](https://github.com/parse-community/minami) of an JSDOc template that seems pretty outdated and not well maintained.

### Feature / Enhancement Description
Switch to a more modern template that is maintained and improves usability, for example:
- https://github.com/ankitskvmdam/clean-jsdoc-theme

### Example Use Case
n/a

### Alternatives / Workarounds
n/a

**Comment by dblythy** [comment]
Sounds good to me. We can easily drop in the amendment from https://github.com/parse-community/minami/pull/1#issuecomment-1140267604

**Comment by mtrezza** [comment]
That would be great, also see https://github.com/parse-community/minami/pull/1#issuecomment-1140267604 why I would rather not touch the current template.

**Comment by dblythy** [comment]
The same template will need to be applied to the JS repo too

**Comment by mtrezza** [comment]
Right, can we then point to the original dependency (rather than maintaining our own fork) and just add a config file to each repo?

**Comment by dblythy** [comment]
There were [some changes](https://github.com/nijikokun/minami/commit/68fd18c073e9d9008899c17d0f9d9043af834a40) to the template which may have been the reason why there is a fork.

The main changes seem to be to add `@interface` to the nav bar.

**Comment by okobsamoht** [comment]
## I'v tested the clean-jsdoc-theme.
## you can take a look here:
# https://6297b4ac43cc1f0062fbe19e--parse-server-doc.netlify.app/

### here are some screenshots
### mobile

<img width=256 src="https://user-images.githubusercontent.com/5099481/171478284-22d4bb0f-4d80-4f6c-8cb7-1ff319d046ac.png">
<img width=256 src="https://user-images.githubusercontent.com/5099481/171478297-daf41fd5-0c51-442a-8168-d1cbd4a91c5a.png">
<img width=256 src="https://user-images.githubusercontent.com/5099481/171478300-65eaee66-1505-4a64-99c9-ec6548159af0.png">


### desktop

![localhost_63342_parse-server_out_ParseServerOptions html](https://user-images.githubusercontent.com/5099481/171478306-c759c063-2524-4e11-8070-637accec25dc.png)
![localhost_63342_parse-server_out_Parse Cloud html](https://user-images.githubusercontent.com/5099481/171478313-dbd25128-27c2-465f-b623-edb5669c6037.png)
![localhost_63342_parse-server_out_ParseServer html](https://user-images.githubusercontent.com/5099481/171478318-e66e29ad-1fbb-4455-a2ca-51f8ba9974bf.png)
![localhost_63342_parse-server_out_index html__ijt=25j0lemg3jlvvckrr77g32gdo0 (1)](https://user-images.githubusercontent.com/5099481/171478324-dfd97421-b520-4e5f-85a0-155bc64f377f.png)
![localhost_63342_parse-server_out_index html__ijt=25j0lemg3jlvvckrr77g32gdo0](https://user-images.githubusercontent.com/5099481/171478332-b4e8f227-e46e-4df9-9342-72cf582c0168.png)

**Comment by mtrezza** [comment]
We'd need to make sure that all content is included in the new template; @dblythy [mentioned](https://github.com/parse-community/parse-server/issues/8017#issuecomment-1140273411) that there was some customization in the old template.

**Comment by mtrezza** [comment]
@parse-community/server Anyone wants to pick this up for Parse Server 6? While it's not required for release, it would still be nice to have a modern docs layout with the new release.

**Comment by KodeyThomas** [comment]
> @parse-community/server Anyone wants to pick this up for Parse Server 6? While it's not required for release, it would still be nice to have a modern docs layout with the new release.

Have you had a look into [TypeDoc](https://typedoc.org/guides/overview/#what-is-typedoc%3F) it's made for TypeScript but works fine in a JS project, I've used it in a few projects and it's worked pretty well. However, I do think we need a general refactor of the docs to make things a bit more clear for new users. 

Happy to pick this one up if I get a bit of free time before Jan

**Comment by mtrezza** [comment]
Haven't looked at TypeDoc, but it really depends on a feature comparison and what kind of visual themes they offer. What we see [here](https://github.com/parse-community/parse-server/issues/8017?notification_referrer_id=NT_kwDOAFaSzbIzNzA0OTQwMjcwOjU2NzM2Nzc#issuecomment-1144017081) looks pretty good to me already, if it's just a simple template change. In general, we want to switch to another docs framework, see [forum](https://community.parseplatform.org/t/new-documentation/1978).

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.1.0-alpha.8](https://github.com/parse-community/parse-server/releases/tag/6.1.0-alpha.8)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.1.0-beta.2](https://github.com/parse-community/parse-server/releases/tag/6.1.0-beta.2)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.1.0](https://github.com/parse-community/parse-server/releases/tag/6.1.0)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.1.0-alpha.9](https://github.com/parse-community/parse-server/releases/tag/6.1.0-alpha.9)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.3.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/6.3.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.3.0-alpha.1](https://github.com/parse-community/parse-server/releases/tag/6.3.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.3.0](https://github.com/parse-community/parse-server/releases/tag/6.3.0)
