### ISSUE TITLE
Possible improvements to the website and documentation

### ISSUE THREAD

**Issue by ammarahm-ed** [parse-community/parse-server#8020]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation
After a lot of research and using Parse Server in one of my projects after deciding that it is the best solution currently after playing around with other such newer projects such as appwrite, supabase etc I am here with not a feature request but a very important enhancement that could present to people how great parse actually is.

### Feature / Enhancement Description
The current website design + documentation is outdated. At a glance most people just tend to assume parse is outdated or too old to be used unless they read the documentation and go through different features to actually realize how good it is. I know parse is fully open-source and doing everything here required a lot of effort from community. But i believe that if the main contributors of parse come along to upgrade the website and docs, a lot of help from the community will pour in including myself.

### Example Use Case
In open source, better documentation = marketing. And I mean the docs are written great. But the UI could be much more better and user friendly.

### Alternatives / Workarounds
After trying out appwrite, supabase, kuzzel and others, I finally ended up with Parse. If you ask me why initially i didn't choose parse, well. The website and documentation were not clear enough at a glance and user friendly to make me feel that Parse was exactly what I was looking for. So after writing a full core with appwrite and realizing the limitations with database I went again to do some research again and go through parse documentation to look for features and things I needed to decide that parse was the way to go.

### 3rd Party References
Supabase, Appwrite and Kuzzel and other such services have made their websites and documentation more flashier even though the lack many features that parse already has.

**Comment by mtrezza** [comment]
> And I mean the docs are written great. But the UI could be much more better and user friendly.

Improving the docs is an effort on multiple fronts, involving content, structure, consolidation and UI. There have been discussions and initiatives in many places, but it never got to a point where there was enough momentum to pick it up - also because it requires quite some effort. One such discussion can be found in the forum: https://community.parseplatform.org/t/new-documentation/1978

So instead, we ended up focusing on individual initiatives, for example: #8017.

I'm closing this for now, unless you want to use this issue to establish a roadmap and maybe pick up some tasks.
