### ISSUE TITLE
GraphQL query transformer drop the condition on the object field with false value

### ISSUE THREAD

**Issue by yomybaby** [parse-community/parse-server#8031]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description
On graphql where input has a condition on the object field with false value. Graphql query transformer drop that condition.

### Steps to reproduce
- Create Class and add object filed(someObjectField). 
- Create object with object field
```
{
  foo: { bar: 'baz', qux: true },
  number: 10,
};
```
- GraphQL query with below condition 
```
const whereWithQuxFalse = {
  someObjectField: {
    notEqualTo: { key: 'foo.bar', value: 'bat' },
    greaterThan: { key: 'number', value: 9 },
    lessThan: { key: 'number', value: 11 },
    equalTo: { key: 'foo.qux', value: false },
  },
};
```
### Actual Outcome
query result has an object.

### Expected Outcome
query result shouldn't have an object. Because object has `foo.qux:true` and query condition has `equalTo: { key: 'foo.qux', value: false },`

### Environment
~5.x.x
(Maybe 4.x.x has a same bug)

Server
- Parse Server version: `5.x.x`
- Operating system: `MacOS 12.4`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `Local`

**Comment by mtrezza** [comment]
Closing via https://github.com/parse-community/parse-server/pull/8032
