### ISSUE TITLE
Masked errors on graphql API since Yoga

### ISSUE THREAD

**Issue by Moumouls** [parse-community/parse-server#8044]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description
Error are masked by Yoga GraphQL server.

### Steps to reproduce
Throw an error into a custom resolver or custom query

### Actual Outcome
Original error converted to "Unexpected Error"

### Expected Outcome
To return the original error to the client.

### Environment

Server
- Parse Server version: `5.3.0-alpha.16`
- Operating system: `Macos`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `local`

Database
- System (MongoDB or Postgres): `mongo`
- Database version: `5.X`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `local`

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): `_`
- SDK version: `_`

**Comment by mtrezza** [comment]
Closing via #8045
