### ISSUE TITLE
Logged-in user cannot upload file via GraphQL when `enableForPublic: false`

### ISSUE THREAD

**Issue by shkatulo** [parse-community/parse-server#8078]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description
I'm using GraphQL to access Parse Server on Flutter. My mutations for file upload worked fine (in v4.10.4) before `enableForPublic` parameter was introduced. After upgrading to v5.2.3 I'm getting "File upload by public is disabled" error. Session header is sent with mutation correctly, other mutations which need session work fine.

Also file is uploaded without errors when using REST API. So it looks like session is not handled by GraphQL layer when calling `createFile` mutation.

### Steps to reproduce
Try uploading file through GraphQL with `fileUpload.enableForPublic=false`.

### Actual Outcome
I'm getting error `File upload by public is disabled` with code 130.

### Expected Outcome
File should be uploaded successfully.

### Environment
Server
- Parse Server version: `5.2.3`
- Operating system: `macOS 12.0.1`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `local` and `Heroku`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `5.0.9 `
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `MongoDB Atlas`

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): `Flutter` using `graphql` package
- SDK version: `3.0.3`

**Comment by mtrezza** [comment]
Seems to have self-resolved, so reclassifying this as support question.
