### ISSUE TITLE
Remove Node 12 and Node 17 support

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-server#8081]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation
Node 12 and Node 17 are out of LTS, but its still in the CI and node engine

### Feature / Enhancement Description
Remove Node 12 and Node 17 support

Removing Parse Server compatibility would be a breaking change, so this can only be done in Parse Server 6.

### Example Use Case
n/a

### Alternatives / Workarounds
n/a

**Comment by dblythy** [comment]
Is it correct once we remove support for node 12, we can support optional chaining across all files?

**Comment by mtrezza** [comment]
Yes! Finally

**Comment by mtrezza** [comment]
Since the Parse JS SDK is a part of Parse Server, it too has to support the same (or a superset of) Node versions. So I guess we'll have to coordinate that breaking change with the Parse JS SDK, make a release and use it as dependency in Parse Server.

**Comment by mtrezza** [comment]
Closing via #8279

**Comment by mtrezza** [comment]
Node Badge in README needs to be updated
