### ISSUE TITLE
Add CI lint rule to disallow if without curly braces

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-server#8093]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation
This pattern passes lint validation:

```
if (a == 1) b = 2
```

### Feature / Enhancement Description
Add lint rule to disallow `if` statement without curly braces.

### Example Use Case
n/a

### Alternatives / Workarounds
n/a

**Comment by dblythy** [comment]
Duplicate of #7920
