### ISSUE TITLE
ParseObject.get() on relation field returns broken relation

### ISSUE THREAD

**Issue by LMBernardo** [parse-community/parse-server#8097]
- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description
As of parse-server 5.2.4, calling get() on a relation field returns a relation which works as expected. When testing with parse-server 5.3.0-beta.1, calling get() returns a broken relation which fails when attempting to call query() with the error 'Cannot construct a query for a Relation without a parent'. Replacing get() with relation() still returns a functional relation.

This seems to be specific to parse-server, as updating from 5.2.4 to 5.3.0-beta.1 is the only thing required to trigger this issue.

### Steps to reproduce
Use get() to retrieve a relation field from a ParseObject, and then attempt to call query() on the returned field.

### Actual Outcome
The returned object is broken in some way such that query() is no longer functional and instead throws an error,

### Expected Outcome
It is expected that calling query() on the return object will return a valid query, instead of throwing an error.

### Environment
Server
- Parse Server version: 5.3.0-beta.1
- Operating system: Windows 10
- Local or remote host: Local

Database
- System (MongoDB or Postgres): MongoDB
- Database version: 5.0.9
- Local or remote host: MongoDB Atlas

Client
- SDK : Javascript
- SDK version: 3.4.3

### Logs
No relevant logs, other than the error message above which shows up in the job message on parse-dashboard.

**Comment by mtrezza** [comment]
Could you please submit a PR with a failing test to reproduce the issue?

**Comment by LMBernardo** [comment]
My apologies; while I can still replicate this issue 100% of the time in my project, functionally identical code (the important parts basically copy-pasted) in a test file always passes. This leads me to believe this is an issue either with my setup (most likely) or it is specific to code running in a Cloud job. Feel free to close this issue - I will need to do some further investigation.

**Comment by mtrezza** [comment]
Thanks for updating; I'll leave this open until you conclude your investigation.

**Comment by LMBernardo** [comment]
Unfortunately, I'm totally unable to figure out what's going on here. I suspect it's something to do with how I'm creating these relations. I can work around by using .relation() instead of .get() anyway, so I'm going to go ahead and close this for now.
