### ISSUE TITLE
Upload recorded video from ionic media capture - throws Range error, stack size exceeded  or( cannot create parse file)

### ISSUE THREAD

**Issue by kfvenkatasama** [parse-community/parse-server#8111]
### Steps to reproduce

- Ionic media capture record 5 or 10 or 30 seconds video
- convert to base64 - which gives 17mb of string
- create parse.save('filename', {base64: base64data});

-- Which throws an error at RegExp.test().

Looking for help.

**Comment by mtrezza** [comment]
I'm closing this as you (or someone associated with you) has already posted this issue as https://github.com/parse-community/Parse-SDK-JS/issues/1516.
