### ISSUE TITLE
Parse Server Docs have not been generated since 5.2.0

### ISSUE THREAD

**Issue by dblythy** [parse-community/parse-server#8166]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description

The [Parse Server Docs](https://github.com/parse-community/parse-server/tree/gh-pages/api) do not support the `alpha` branch. It only has the `master` branch which has not been updated in 6 months.

### Steps to reproduce

https://github.com/parse-community/parse-server/tree/gh-pages/api

### Actual Outcome

Should have updated alpha branch

### Environment

Server
- Parse Server version: `alpha`
- Operating system: `macos`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `-`

Database
- System (MongoDB or Postgres): `mongoDb`
- Database version: `n/a`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `localhost`

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): `-`
- SDK version: `-`

**Comment by mtrezza** [comment]
I think since these are the official docs, we'd only want the `release` branch to be documented. Unless we can find a way to publish docs for each branch separately. The generated docs have a API part in their path.

**Comment by mtrezza** [comment]
The reason there haven't been any updates since 5.2.0 is because I think since then we only released security hot fixes which are merged in a way that doesn't create docs. It also doesn't create a docker release but that is done manually after merging. Maybe a workaround is to add a CI job that also allows to manually generate docs.

**Comment by dplewis** [comment]
Closing via https://github.com/parse-community/parse-server/pull/9081
