### ISSUE TITLE
docs: `databaseOptions` missing in Parse Server Options docs

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-server#8168]
The `databaseOptions` are not documented in the Parse Server docs. Instead it's just an `Any` type.

The correcting approach is to add a new Type and specify all the `databaseOptions` in that new type. See for example the `Pages` option.

This is a crucial part of the documentation for everyone who is using multiple Parse Server instances, e.g. behind a load balancer. The `databaseOptions.enableSchemaHooks` option is an essential configuration, see https://github.com/parse-community/parse-server/pull/7214.

**Comment by dblythy** [comment]
![Image](https://user-images.githubusercontent.com/4974769/190066766-c48ef951-a379-4ebe-91bc-7c6e01cdbb10.png)

![Image](https://user-images.githubusercontent.com/4974769/190066801-aa7f888f-3905-4e4d-a364-bc734e36ec53.png)

https://parseplatform.org/parse-server/api/5.0.0/DatabaseOptions.html

**Comment by mtrezza** [comment]
Ha! I must have looked at an old API version. Are there other DB options missing?

If any custom options are just passed to the adapter, we don't need to document them. But if supported options are explicitly defined, we should document them all.

**Comment by dblythy** [comment]
I'm pretty sure databaseOptions can be any valid options that can be passed to Mongo, Postgres, or any other valid database adapter

**Comment by mtrezza** [comment]
Do we have any other custom options, like `enableSchemaHooks` which is something we invented and is not passed to the DB adapter.

**Comment by dblythy** [comment]
I think `maxTimeMS`, but that is for the mongo adapter only. There might be other options but I think that's all I can find

**Comment by mtrezza** [comment]
So this issue can actually be closed then? Maybe we should add to the docs somewhere that any other parameter is passed directly to the DB client? In any case, this issue belongs to the parse-server repo, because the API docs are generated from the definition files, right?

**Comment by dblythy** [comment]
I think it can stay open but transferred, it would help to explain to users that any other database options get passed directly to the db client

**Comment by mtrezza** [comment]
OK, I'll transfer this to Parse Server and maybe you can do a PR to somehow add that note to the API docs, then we can close this.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.3.0-alpha.27](https://github.com/parse-community/parse-server/releases/tag/5.3.0-alpha.27)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.4.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/5.4.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.4.0-alpha.1](https://github.com/parse-community/parse-server/releases/tag/5.4.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.4.0](https://github.com/parse-community/parse-server/releases/tag/5.4.0)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.4.0](https://github.com/parse-community/parse-server/releases/tag/5.4.0)
