### ISSUE TITLE
Server crashed if asynchronous function get error.  (uncaughtException)

### ISSUE THREAD

**Issue by JeffGuKang** [parse-community/parse-server#8193]
Parse Server crashed when I call some asynchronous function that throws error. 
I resolved issue patch the code as below. 

uncaughtException

I think `process.on('uncaughtException', ...) throw error` should be treat in client instead of parse. 

How about changing code as below? 

https://github.com/parse-community/parse-server/blob/b64640c5705f733798783e68d216e957044ef23c/src/ParseServer.js#L193-L204

```ts
process.on('uncaughtException', err => {
  if (err.code === 'EADDRINUSE') {
    // user-friendly message for this common error
    process.stderr.write(`Unable to listen on port ${err.port}. The port is already in use.`);
    process.exit(0);
  }
});
```

**Comment by mtrezza** [comment]
I'm closing this as it does not use the issue template provided when creating an issue and therefore lacks essential information required to investigate the issue. Please edit your initial post using the issue template and we can re-open this issue.

**Comment by JeffGuKang** [comment]
Sorry for that. I missed the template cause issue was created from source code.  I will recreate with the template. 
Thank you.

**Comment by mtrezza** [comment]
You can just edit your post and we'll reopen this issue.
