### ISSUE TITLE
Add official support for MongoDB 6

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-server#8217]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation

MongoDB 6 has [been released](https://www.mongodb.com/docs/manual/release-notes/6.0/).

### Feature / Enhancement Description

Parse Server should add support for MongoDB 6.

### Example Use Case
n/a

### Alternatives / Workarounds
n/a

**Comment by cool2apps** [comment]
I've just installed a new server on ubuntu 22.04 server and I installed mongo db 6 and parse server and restored one of mongo db 5 databases. And it looks like working but not tested too much.

What are the known problems with mongo db 6 and parse server?

**Comment by mtrezza** [comment]
> What are the known problems with mongo db 6 and parse server?

We don't know. Do you want to open a PR to add support? It's pretty easy to add a job to the CI for MongoDB 6, to at least see whether all tests pass. You can take a look at previous PRs, it's just some lines of code.

**Comment by cool2apps** [comment]
What should I test? Are there any test scripts that I can run without damaging my system. Because it will be production system in a few days, if I don't find any problems.

**Comment by mtrezza** [comment]
The CI will test for you, all you need to to is add some lines to tell the CI to run our existing tests against MongoDB 6. You can take a look at these PRs for how to do that:
- https://github.com/parse-community/parse-server/pull/7894/files
- https://github.com/parse-community/parse-server/pull/7469/files

**Comment by cool2apps** [comment]
> The CI will test for you, all you need to to is add some lines to tell the CI to run our existing tests against MongoDB 6. You can take a look at these PRs for how to do that:
> 
>     * https://github.com/parse-community/parse-server/pull/7894/files
> 
>     * https://github.com/parse-community/parse-server/pull/7469/files

I hope I did it right:

https://github.com/parse-community/parse-server/pull/8239

**Comment by cool2apps** [comment]
https://github.com/parse-community/parse-server/pull/8240

**Comment by mtrezza** [comment]
@cool2apps I've opened https://github.com/parse-community/parse-server/pull/8242 for MongoDB 6 support; you can see the CI test results there to maybe get a sense for whether there are any concerns for your server upgrade, in case you need to upgrade before Parse Server officially supports it (which I wouldn't recommend of course).

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.3.0-alpha.30](https://github.com/parse-community/parse-server/releases/tag/5.3.0-alpha.30)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.4.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/5.4.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.4.0-alpha.1](https://github.com/parse-community/parse-server/releases/tag/5.4.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.4.0](https://github.com/parse-community/parse-server/releases/tag/5.4.0)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.4.0](https://github.com/parse-community/parse-server/releases/tag/5.4.0)
