### ISSUE TITLE
Add trigger before Remote Config change

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-server#8267]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation

When changing any value in Remote Config, the previous value is lost without any possibility to undo the change. That means that any user mistake can lead to information irreversibly lost.

### Feature / Enhancement Description

Add a Cloud Code trigger that is invoked when the remove config is changed. This allows a developer to catch any changes to the Remote Config parameters and log them, or store a history of changed.

### Example Use Case
n/a

### Alternatives / Workarounds
None

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.3.0-alpha.6](https://github.com/parse-community/parse-server/releases/tag/7.3.0-alpha.6)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.3.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/7.3.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.3.0](https://github.com/parse-community/parse-server/releases/tag/7.3.0)
