### ISSUE TITLE
Remove deprecation `DEPPS1`: Native MongoDB syntax in aggregation pipeline

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-server#8268]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation

Deprecation to be removed in Parse Sever 6:
- `DEPPS1`: Native MongoDB syntax in aggregation pipeline 

### Feature / Enhancement Description

Remove deprecation, see [list](https://github.com/parse-community/parse-server/blob/alpha/DEPRECATIONS.md).

### Example Use Case
n/a

### Alternatives / Workarounds
n/a

**Comment by SebC99** [comment]
Hello @mtrezza 
Do you plan to also remove all the type conversions in the pipeline? (the `_parseAggregateArgs` method basically).
It's a real mess to write aggregation with Parse, as some fields are converted and others are not, some are wrongly converted, some are removed, etc.
Dates fields are very messy too.

**Comment by mtrezza** [comment]
This issue is just removing the deprecation; see https://github.com/parse-community/parse-server/issues/7338 and https://github.com/parse-community/parse-server/pull/7339 for the full scope of the deprecation.

I think you are referring to https://github.com/parse-community/parse-server/issues/7868. That's a separate issue and currently without an ETA. There is an existing PR https://github.com/parse-community/parse-server/pull/8172, but it's still WIP.

**Comment by SebC99** [comment]
True, thanks.
Except #7868 should be broader as there are server crash issues but also wrong results ones as you the pipeline is modified under the hood. I'll try to look into #8172 .

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0-alpha.19](https://github.com/parse-community/parse-server/releases/tag/6.0.0-alpha.19)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/6.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0](https://github.com/parse-community/parse-server/releases/tag/6.0.0)
