### ISSUE TITLE
Remove deprecation `DEPPS3`: Config option `enforcePrivateUsers` defaults to `true`

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-server#8270]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation

Deprecation to be removed in Parse Sever 6:
- `DEPPS3`: Config option enforcePrivateUsers defaults to true

### Feature / Enhancement Description

Remove deprecation, see [list](https://github.com/parse-community/parse-server/blob/alpha/DEPRECATIONS.md).

### Example Use Case
n/a

### Alternatives / Workarounds
n/a

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0-alpha.9](https://github.com/parse-community/parse-server/releases/tag/6.0.0-alpha.9)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/6.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0](https://github.com/parse-community/parse-server/releases/tag/6.0.0)
