### ISSUE TITLE
Remove support for MongoDB 4.0

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-server#8272]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation

MongoDB 4.0 reached its EOL in April 2022. 

### Feature / Enhancement Description

Remove support for MongoDB 4.0:
- Remove related tests (restricted to MongoDB version)
- Remove from CI workflow

### Example Use Case
n/a

### Alternatives / Workarounds
n/a

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0-alpha.6](https://github.com/parse-community/parse-server/releases/tag/6.0.0-alpha.6)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/6.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0](https://github.com/parse-community/parse-server/releases/tag/6.0.0)
