### ISSUE TITLE
Remove CI check "NPM lock file version" and regenerate `package-lock.json` as v2

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-server#8274]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation

Removal of Node 12 support allows to safely move to package-lock.json v2.

### Feature / Enhancement Description

Remove CI check "NPM lock file version" and regenerate package-lock.json as v2

### Example Use Case
n/a

### Alternatives / Workarounds
n/a

**Comment by dblythy** [comment]
I think lockfile v2 starts with npm 7, which is shipped with node > 15

<img width="456" alt="Screen Shot 2022-11-06 at 3 38 45 pm" src="https://user-images.githubusercontent.com/4974769/200154506-3bf13d78-604c-4960-99c3-82c24a93a4ea.png">

**Comment by mtrezza** [comment]
So we stick with v1 until we remove Node 14 support in PS7? If technically possible, an argument for switching to v2 (since it's backwards compatible with v1) could be to reduce the install time on Node >=16.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0-alpha.17](https://github.com/parse-community/parse-server/releases/tag/6.0.0-alpha.17)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/6.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0](https://github.com/parse-community/parse-server/releases/tag/6.0.0)
