### ISSUE TITLE
Upgrade Redis 3 to 4

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-server#8276]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation

Node Redis dependency should be upgraded form 3 to 4, which includes a breaking change, see [migration guide](https://github.com/redis/node-redis/blob/redis%404.0.0/docs/v3-to-v4.md).

### Feature / Enhancement Description

Upgrade to Redis 4 with Parse Sever 6 release.

### Example Use Case
n/a

### Alternatives / Workarounds
n/a

**Comment by MobileVet** [comment]
@mtrezza Ironically we were just looking at this today as we look to migrate away from Heroku.  We had trouble connecting to the Redis instance without TLS (it is on a private network) but it worked fine from outside the network using TLS.

We forced Parse Server to utilize the Node Redis driver 4.4.0 and everything worked just fine on Parse Server 5.2.7.  I wonder if there is anything that is actually required to make the update for Parse 6?

**Comment by mtrezza** [comment]
Great that you already looked into that. I just fixed a conflict in the [PR](https://github.com/parse-community/parse-server/pull/7987), so we can see whether the CI passes. If it passes, it still would be good if someone could take a look at the [migration guide](https://github.com/redis/node-redis/blob/redis%404.0.0/docs/v3-to-v4.md) to see whether there is anything relevant for Parse Server. Not sure how good the Redis test coverage in Parse Server is.

For example:
> The configuration object passed to createClient has changed significantly with this release. See the [client configuration guide](https://github.com/redis/node-redis/blob/redis%404.0.0/docs/client-configuration.md) for details.

...and indeed, the CI in the PR fails with:
> TypeError: Cannot read properties of undefined (reading 'createClient')

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0-alpha.7](https://github.com/parse-community/parse-server/releases/tag/6.0.0-alpha.7)

**Comment by dblythy** [comment]
Reopening as the Redis Live Query publisher was not updated

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0-alpha.12](https://github.com/parse-community/parse-server/releases/tag/6.0.0-alpha.12)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/6.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0](https://github.com/parse-community/parse-server/releases/tag/6.0.0)
