### ISSUE TITLE
Upgrade to GraphQL Yoga 3

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-server#8314]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation

New release of GraphQL Yoga 3

### Feature / Enhancement Description

Upgrade to GraphQL Yoga 3.

Migration guide; https://www.the-guild.dev/graphql/yoga-server/v3/migration/migration-from-yoga-v2
Changelog; https://github.com/dotansimha/graphql-yoga/blob/v3/packages/graphql-yoga/CHANGELOG.md

### Example Use Case
n/a

### Alternatives / Workarounds
n/a

**Comment by mtrezza** [comment]
Removing this from Parse Server 6 planned changes list, as it won't introduce breaking changes, see https://github.com/parse-community/parse-server/pull/8250#issuecomment-1363391629.

**Comment by Moumouls** [comment]
closing this @mtrezza since we moved out of Yoga
