### ISSUE TITLE
Default `masterKeyIps` does not work on localhost

### ISSUE THREAD

**Issue by dblythy** [parse-community/parse-server#8316]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description

Introduced in #8281, the new default does not allow local IPs.

This is due to the fact that `getClientIp` returns an ipv6 IP (`::1`), whereas the `masterKeyIps` default is `127.0.0.1`

### Steps to reproduce

Run a local instance of Parse Server alpha with Dashboard

### Actual Outcome

Dashboard should load

### Expected Outcome

"MasterKey is required"

### Environment

Server
- Parse Server version: `alpha`
- Operating system: `macos`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `localhost`

Database
- System (MongoDB or Postgres): `mongo`
- Database version: `5.0`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `atlas`

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): `js`
- SDK version: `3.4.4`

**Comment by dblythy** [comment]
Solution is to change the default to `::1`, or resolve `getClientIp` to an `ipv4` address

**Comment by mtrezza** [comment]
> Solution is to change the default to ::1

How would that work on a machine where IPv6 is not enabled? Can't we just add both values as default? `['::1','127.0.0.1']`

**Comment by dblythy** [comment]
Yes, that would fix it also. Should masterKeyIps always allow localhost? Otherwise developer will have to configure `masterKeyIps: ["::1", "127.0.0.1", "ip", "ip"],`

I'm thinking internally it should be `allowedIps = ["::1", "127.0.0.1", ...config.masterKeyIps],`, masterKeyIps can default to `[]` (localhost only)

**Comment by mtrezza** [comment]
> Should masterKeyIps always allow localhost?

Why?

**Comment by dblythy** [comment]
I think it would be expected that `masterKeyIps` is external ips, and that cloud code, code run on the same instance as Parse Server, should always be allowed.

**Comment by mtrezza** [comment]
How can the use of masterKey be completely disabled?

**Comment by dblythy** [comment]
Maybe by not setting a masterKey?

**Comment by mtrezza** [comment]
Does Parse Server start without masterkey?

**Comment by dblythy** [comment]
Not at the moment

**Comment by mtrezza** [comment]
Then setting `masterKeyIps` to an empty array is the only way at the moment. So I'd say we should not set localhost as a non-removable allow-entry.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0-alpha.11](https://github.com/parse-community/parse-server/releases/tag/6.0.0-alpha.11)

**Comment by stewones** [comment]
> Then setting masterKeyIps to an empty array is the only way at the moment. So I'd say we should not set localhost as a non-removable allow-entry.

it's not working currently @mtrezza 

sent a PR to fix https://github.com/parse-community/parse-server/pull/8339

**Comment by dblythy** [comment]
> So I'd say we should not set localhost as a non-removable allow-entry.

I think we missed that still though, as the default options are always concatenated to any additional set `masterKeyIps`

https://github.com/parse-community/parse-server/blob/alpha/src/ParseServer.js#L471-L473

**Comment by mtrezza** [comment]
Oh, did #8339 aim to fix that and remove the concatenation? I reopened.

**Comment by dblythy** [comment]
I don't think so, I think #8339 was designed to make `masterKeyIps: []` === access from anywhere, which is incorrect. We can open a new PR fixing the concatenation

**Comment by stewones** [comment]
> I don't think so, I think https://github.com/parse-community/parse-server/pull/8339 was designed to make masterKeyIps: [] === access from anywhere, which is incorrect. We can open a new PR fixing the concatenation

sort of, I misunderstood the idea initially but I think it's ok now. please take a 2nd look at the PR

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/6.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0](https://github.com/parse-community/parse-server/releases/tag/6.0.0)
