### ISSUE TITLE
Add option to change the log level of the logs emitted by triggers

### ISSUE THREAD

**Issue by alljinx** [parse-community/parse-server#8329]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation
Parse Server can really get very wordy when actively using triggers (beforeSave, afterSave) : this can quickly lead to oversized log files and drowned informations.

By default, theses messages are written to the log file using the 'info' channel. The only way to shut them off is to raise the log level of Parse Server to the 'warn' level.

Customization is a key characteristic of Parse Server.  Developers should be able to modify the channel so they can enforce their log policy.

### Feature / Enhancement Description

Add three log level options into the Parse Server config (logLevelTriggerAfterHook, logLevelTriggerSuccessBeforeHook, logLevelTriggerErrorBeforeHook) in order to fine-tune the triggers log channel according Winston's one ('info', 'debug','warn').

### Example Use Case

1. Add "logLevelUses: { triggerAfterHook: 'debug' }" to Parse Server configuration
2. Save a Parse Object
3. The log is not written on the 'info' channel anymore, but use the 'debug'.

### Alternatives / Workarounds

The only way to shut them off is to raise the log level of Parse Server to the 'warn' level.

**Comment by mtrezza** [comment]
Interesting idea; is there an alternative concept to adding N parse server options? In theory someone could ask the same for any other log entry that is written and we'd end up with many new Parse Server options.

**Comment by alljinx** [comment]
Yes, I guess we could use a single option and an object as value, but I guess it would be tricky to use with environment variable.

**Comment by mtrezza** [comment]
If I'm not mistaken we do have other parse options that accept stringified JSON objects, so it should work fine as env var.

**Comment by alljinx** [comment]
Mmmm, you're right, thx. I'll make some corrections...

**Comment by alljinx** [comment]
@mtrezza I made some corrections according to your comments. What do you think ?
