### ISSUE TITLE
Upgrade to Parse JS SDK 4

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-server#8330]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation

As Parse JS SDK 4 is in preparation, and it's a breaking change, it should be released with Parse Server 5.

### Feature / Enhancement Description

Upgrade Parse Server dependency to Parse JS SDK 4; this requires a stable release of Parse JS SDK 4.

### Example Use Case
n/a

### Alternatives / Workarounds
n/a

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0-alpha.29](https://github.com/parse-community/parse-server/releases/tag/6.0.0-alpha.29)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/6.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0](https://github.com/parse-community/parse-server/releases/tag/6.0.0)
