### ISSUE TITLE
Live query subscription not working with constraint $in

### ISSUE THREAD

**Issue by theFreedomBanana** [parse-community/parse-server#8335]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description
It seems that subscribing to a live query with the constraint `$in` (`containsAll` and `containedIn` wirth the JS SDK) doesn't work, at least when the key's value is of type Array.

### Steps to reproduce
Subscribe to a query with a `containedIn` constraint, where the key to constrain as a value of type Array.

### Actual Outcome
The subscription works but when an object is deleted/created/updated it doesn't return it.

### Expected Outcome
I expect Parse to return any created/deleted/updated object falling into the boudaries of the subscribed query.

### Environment

Server
- Parse Server version: `5.4.0`
- Operating system: `Linux`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `Local`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `4.12.0`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `AWS`

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): `Javascript`
- SDK version: `3.4.2`

**Comment by dplewis** [comment]
Closing via https://github.com/parse-community/parse-server/pull/8128

Please open a new issue if this solution doesn't work
