### ISSUE TITLE
File based logging cannot be disabled

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-server#8340]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description
The [docs](https://parseplatform.org/parse-server/api/5.4.0/ParseServerOptions.html) say:

> `logsFolder`: Folder for the logs (defaults to './logs'); set to null to disable file based logging

Setting `logsFolder: null` does not seem to disable file based logging.

### Steps to reproduce

1. Set Parse Server option `logsFolder: null`
2. Log folder `./logs` still get created
3. Logs are still written to files

### Actual Outcome
Logs are still written to files.

### Expected Outcome
Logs are not written to files.

### Environment

Server
- Parse Server version: `5.4.0`

**Comment by dblythy** [comment]
Is this related to #6307

**Comment by mtrezza** [comment]
Yes, thanks, I'll close this.l as duplicate of #6307
