### ISSUE TITLE
The max query limit restriction on parse server side

### ISSUE THREAD

**Issue by ZhengAudrey** [parse-community/parse-server#8344]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation
There is some existing default query limit (like, 100 or 1000), which could be overridden by query option. If some hacker sets the value to a very large number, it seems like database can be dumped with several queries and causing heavy traffic for each query.

### Feature / Enhancement Description
Add max query limit on [ParseServerOptions](https://parseplatform.org/parse-server/api/master/ParseServerOptions.html), So that, the maximum query count can be set on server side, and not be changed through client side calling code.

**Comment by mtrezza** [comment]
> If some hacker sets the value to a very large number

That assumes that a system is already compromised. The same can be said about every other Parse Server option. This issue can stay closed.
