### ISSUE TITLE
Cannot login via REST

### ISSUE THREAD

**Issue by xissburg** [parse-community/parse-server#835]
I am trying to log in using curl, like this

`curl -X GET -H "X-Parse-Application-Id: ..." -G --data-urlencode 'username=..' --data-urlencode 'password=...' http://.../parse/login`

According to https://www.parse.com/docs/rest/guide#users-logging-in.

However I get `{"code":101,"error":"Invalid username/password."}`.

I can log in just fine with the same username/password in my iOS app.

**Comment by flovilmart** [comment]
can you try `http://.../parse/login?username=hello&password=world`

**Comment by xissburg** [comment]
That's failing too.

**Comment by xissburg** [comment]
Well, weird.. it's working with a sample parse server I deployed on Heroku but not with another I'm running on Digital Ocean.. I'll have to investigate further...

**Comment by flovilmart** [comment]
That's likely to be a problem with your hosting server. I'm gonna close that for now, please re-open if you feel that's related to parse-server.

**Comment by xissburg** [comment]
Could this be related to not using HTTPS? But how does it work on the iOS app and it doesn't via REST?

I am also having issues with user-specific ACLs where I cannot access objects that have an ACL for that specific user even though I am logged in.

**Comment by corbanb** [comment]
@flovilmart I am having this issue on heroku. 

a few other things I noticed also.


If I created a user with iOS I get this data...

```
{
    "_id": {
        "$oid": "56f1d13c0395e8bac57e3169"
    },
    "bcryptPassword": "$2a$10$QYXULzxfGJyTK9GTJOscVO8S9V1NwO9WvpRTAisQ5CG5ZHGA2Uz8G",
    "createdAt": "2015-12-03T21:00:10.410Z",
    "email": "user+2@domain.io",
    "emailVerified": false,
    "objectId": "05jE9vmilQ",
    "sessionToken": "asdfsdfgsfdghfdghhdfghsdfgs",
    "updatedAt": "2015-12-03T22:22:32.552Z",
    "username": "user+2@domain.io"
}
```

if I create a user with the REST API I get this data:

```
{
    "_id": "1qug3ehUe4",
    "username": "user+1@domain.io",
    "_updated_at": {
        "$date": "2016-03-22T23:16:39.274Z"
    },
    "_created_at": {
        "$date": "2016-03-22T23:16:39.274Z"
    },
    "_hashed_password": "$2a$10$/LL7B/XDjg8XZqX0mCqFU.E7AI65DqeNTEqvuo6rccGNtGcCBHIzi"
}
```

If I try to login with the REST API to either user I get....

```
{
  "code": 101,
  "error": "Invalid username/password."
}
```


curl:
```bash
curl -X GET -H "X-Parse-Application-Id: XXXXXXXX" -H "X-Parse-REST-API-Key: XXXXX" -H "X-Parse-Revocable-Session: 1" -H "Cache-Control: no-cache" "http://localhost:1337/parse/login?username=user+1@domain.io&password=password"
```

**Comment by xissburg** [comment]
@corbanb what is your server configuration? Are you passing the serverURL parameter?

**Comment by corbanb** [comment]
@xissburg I am... It looks like this:

```javascript
const options = {
	databaseURI: databaseUri || 'mongodb://localhost:27017/dev',
	cloud: process.env.CLOUD_CODE_MAIN || __dirname + '/cloud/main.js',
	appId: process.env.PARSE_SERVER_APPLICATION_ID || 'myAppId',
	masterKey: process.env.PARSE_SERVER_MASTER_KEY || 'myMasterKey',
	javascriptKey: process.env.PARSE_JS_KEY || 'foo',
	clientKey: process.env.PARSE_CLIENT_KEY || 'bar',
	restAPIKey: process.env.PARSE_RESTAPI_KEY || 'yay',
	serverURL: 'http://localhost:1337/parse'
	
};

const api = new ParseServer(options);
```

**Comment by xissburg** [comment]
@corbanb You should use your external server URL, the Heroku URL.

**Comment by corbanb** [comment]
@xissburg when I am testing locally?

**Comment by xissburg** [comment]
@corbanb I am not sure, I haven't ran my app locally yet. If I remember correctly, this is what fixed it for me. I am not so sure.. I tried so many things that it might have been something else.

**Comment by JHHMobile** [comment]
@corbanb I'm having the same issue. How did you solve the issue?
Thanks for sharing.

**Comment by ederelk** [comment]
@corbanb I know it is kind of late but I am having the same issue. It seems to be happening when there is a "+" character in the username

**Comment by flovilmart** [comment]
I just reopened, we'll investigate further special characters in logins

**Comment by ederelk** [comment]
@flovilmart @corbanb  I just run a couple of test on my end. What I have noticed so far is that when I send a request like this http://localhost:1337/1/login?username=%2Buser&password=pass it works fine. But if I send it like this  http://localhost:1337/1/login?username=+user&password=pass it does not work. Some encoding issue with the "+" character I believe.

**Comment by flovilmart** [comment]
Note that this + should be properly URL encoded on your side.

+ is a reserved character (like & and =) and may be interpolated as a space serverside. 

https://en.wikipedia.org/wiki/Percent-encoding and https://en.wikipedia.org/wiki/Query_string

**Comment by ProteanDev** [comment]
I am using back4apps and still getting this issue with Rest Login

**Comment by ederelk** [comment]
You should url encode the url

**Comment by zheeno** [comment]
This was what worked for me:

`Axios.post(`https://parseapi.back4app.com/login`, {
        username: 'YOUR _USERNAME',
        password: 'YOUR_PASSWORD'
    }, {
        headers: {
            "X-Parse-Application-Id": process.env["PARSE_APPLICATION_KEY"],
            "X-Parse-REST-API-Key": process.env["PARSE_API_KEY"],
            "X-Parse-Master-Key": process.env["PARSE_MASTER_KEY"],
        }
})
    .then((response) => resolve(response))
    .catch((error) => reject(error));
`
