### ISSUE TITLE
Add Node 19 support

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-server#8354]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation

Node 19 has been officially released.

### Feature / Enhancement Description

Add Node 19 support

Requires https://github.com/parse-community/Parse-SDK-JS/issues/1638

### Example Use Case
n/a

### Alternatives / Workarounds
n/a

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0-alpha.20](https://github.com/parse-community/parse-server/releases/tag/6.0.0-alpha.20)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/6.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0](https://github.com/parse-community/parse-server/releases/tag/6.0.0)
