### ISSUE TITLE
Bump jsonwebtoken to 9.0.0

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-server#8356]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation

Upgrade fixes security vulnerabilities, but since it's a major version upgrade, some tests fail.

### Feature / Enhancement Description

Adapt code for upgrade to 9.0.0.

### Example Use Case
n/a

### Alternatives / Workarounds
n/a

**Comment by mtrezza** [comment]
I assume this is related to the new auth adapter in Parse Server 6; could someone take a look? It's probably a tiny thing to fix. @Moumouls @dblythy

**Comment by Moumouls** [comment]
Hi @mtrezza it's not related to the new auth system, they just introduced some breaking changes.

here the migration guide for my self, i think it's an easy one: https://github.com/auth0/node-jsonwebtoken/wiki/Migration-Notes:-v8-to-v9

**Comment by mtrezza** [comment]
I meant that it's probably easy to fix for someone who worked on the recent auth PR, since it seems auth related. Thanks for posting the link, should make it easier for someone to pick this issue up.

**Comment by mtrezza** [comment]
@dblythy Would you mind porting https://github.com/parse-community/parse-server/pull/8420 to the 5.x.x branch, so we can fix that also in our LTS branch?

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0-alpha.32](https://github.com/parse-community/parse-server/releases/tag/6.0.0-alpha.32)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.1.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/6.1.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.1.0-alpha.1](https://github.com/parse-community/parse-server/releases/tag/6.1.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.1.0](https://github.com/parse-community/parse-server/releases/tag/6.1.0)
