### ISSUE TITLE
Docker image doesn't conform to best practices

### ISSUE THREAD

**Issue by cbaker6** [parse-community/parse-server#8360]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation

The Dockerfile currently doesn't conform to the [docker best practices](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/) or [alpine recommendations](https://github.com/gliderlabs/docker-alpine/blob/master/docs/usage.md). This results in a larger than necessary compressed/decompressed image.

### Feature / Enhancement Description

The current compressed parse-server image size(~93MB) can be as close as possible to the lts-alpine image size (~50MB) by following best practices for constructing a Dockerfile. I've built a [docker image of parse-server:6.0.0-alpha.17](https://hub.docker.com/layers/netreconlab/parse-server/docker/images/sha256-8bdd7ac3fb5c945976ecbbd617a1f6801adf0c373b5221e86924b26841e2d0fb?context=repo) with the changes in this PR and it resulted in a **68MB** compressed image compared to the [parse-community version](https://hub.docker.com/layers/parseplatform/parse-server/6.0.0-alpha.17/images/sha256-3a2898ce84439aa56b6b91467141c5d56a69925620a50777fcc6dc744cdeb431?context=explore) of **93MB; 27% smaller**.

### Example Use Case

Create an image from this image.

### Alternatives / Workarounds

Use bloated image as is.

### 3rd Party References

Noted in limitation links.

**Comment by mtrezza** [comment]
Looks like a fit for the Parse Server 6 release. Added to the [tracking list](https://github.com/parse-community/parse-server/issues/8225).

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0-alpha.24](https://github.com/parse-community/parse-server/releases/tag/6.0.0-alpha.24)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/6.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0](https://github.com/parse-community/parse-server/releases/tag/6.0.0)
