### ISSUE TITLE
Include not working on LiveQuery

### ISSUE THREAD

**Issue by vdkdamian** [parse-community/parse-server#8378]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description
When using a LiveQuery, my pointers don't get returned.

### Steps to reproduce
Use LiveQuery with pointer.

### Actual Outcome
No objects, just the reference.

### Expected Outcome
The object contained in the query.
### Environment

Server
- Parse Server version: `5.2.3`
- Operating system: `Back4App `
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `AWS`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `3.6`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `AWS`

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): `iOS`
- SDK version: `4.16.2`

**Comment by cbaker6** [comment]
@vdkdamian this is a duplicate, you can see the older discussion in #1686
