### ISSUE TITLE
`verifyServerUrl` does not work with new startup methods

### ISSUE THREAD

**Issue by dblythy** [parse-community/parse-server#8380]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description

`verifyServerUrl` does not respect the starting state, and can log an error when the server is starting up.

### Steps to reproduce

Use new startup method, and call `verifyServerUrl`.

### Actual Outcome

Logs "unable to connect to xxx, cloud code may not be available"

### Expected Outcome

`verifyServerUrl` should consider startup environment

### Environment

Server
- Parse Server version: `alpha`
- Operating system: `macos`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `local`

Database
- System (MongoDB or Postgres): `mongo`
- Database version: `5`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `atlas`

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): `n/a`
- SDK version: `n/a`

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0-alpha.22](https://github.com/parse-community/parse-server/releases/tag/6.0.0-alpha.22)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/6.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0](https://github.com/parse-community/parse-server/releases/tag/6.0.0)
