### ISSUE TITLE
Deprecate LiveQuery `fields` in preference for LiveQuery `keys`

### ISSUE THREAD

**Issue by dblythy** [parse-community/parse-server#8389]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation

Live Query uses a parameter called "fields", where it should be "keys" like the other parts of the server

### Feature / Enhancement Description

Refactor LiveQuery to use "keys"

### Example Use Case

n/a

### Alternatives / Workarounds

n/a

### 3rd Party References

n/a

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0-alpha.33](https://github.com/parse-community/parse-server/releases/tag/6.0.0-alpha.33)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.1.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/6.1.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.1.0-alpha.1](https://github.com/parse-community/parse-server/releases/tag/6.1.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.1.0](https://github.com/parse-community/parse-server/releases/tag/6.1.0)

**Comment by mtrezza** [comment]
Note that this breaks the feature in all Parse client SDKs, as they send the `fields` parameter. They need to be changed to send the `keys` parameter instead. See for example https://github.com/parse-community/Parse-SDK-JS/pull/2089.
