### ISSUE TITLE
GraphQL Playground has dependency error

### ISSUE THREAD

**Issue by REPTILEHAUS** [parse-community/parse-server#8390]
### New Issue Checklist

- [ X] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [ X] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [ X] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [ X] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description
GraphQL playground throws this error now `Uncaught SyntaxError: The requested module 'https://unpkg.com/@graphql-yoga/graphiql' does not provide an export named 'renderYogaGraphiQL' (at playground:formatted:11:20)`

### Steps to reproduce
try to access graphql playground via browser

### Actual Outcome
error above

### Expected Outcome
no error
### Environment
parse server 5.4.0
node v16.16.0
osx

Server
- Parse Server version: `5.4.0`
- Operating system: `osx`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `local`

Database
N/A, mongo

Client
N/A

### Logs
N/A

**Comment by mtrezza** [comment]
Could you please see whether this issue exists in Parse Server 6? You can use the latest alpha version to verify this. We will release a stable version in a few days, and we already don't investigate bug fixes for version 5 anymore.

**Comment by Leonich77** [comment]
Parse Server 6 also have this bug. I get it on OS Win10, localhost, node 16.13.0 (x64)

**Comment by kekami** [comment]
I believe it will be fixed with https://github.com/parse-community/parse-server/pull/8250
The fix is in `@graphql-yoga/node:2.9.0`

**Comment by Moumouls** [comment]
last version of parse-server use apollo sandbox as playground.

Closing this @mtrezza
