### ISSUE TITLE
Rate limit with RedisStore

### ISSUE THREAD

**Issue by dblythy** [parse-community/parse-server#8393]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation

Currently, the rate limiter stores values in memory, which means that it doesn't work with clusters.

### Feature / Enhancement Description

Should have an option to use a `RedisStore` to ensure multiple core use

### Example Use Case

Using on a server with multiple core use

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.1.0-alpha.6](https://github.com/parse-community/parse-server/releases/tag/6.1.0-alpha.6)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.1.0-beta.2](https://github.com/parse-community/parse-server/releases/tag/6.1.0-beta.2)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.1.0](https://github.com/parse-community/parse-server/releases/tag/6.1.0)
