### ISSUE TITLE
Long running queries 

### ISSUE THREAD

**Issue by sidan5** [parse-community/parse-server#8396]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description

I have long running queries that isn't from my code (Assume it's from the server code itself). This happened after upgrading to 5.4.0 (from 4.x version).

### Steps to reproduce

Just running server normally (I have around 400k rows in user table)

### Actual Outcome

Long running code searching for not existing field in user table.

I can see on the DB logs long running queries like this:

    {
      "type": "command",
      "ns": "somedb._User",
      "command": {
        "aggregate": "_User",
        "pipeline": [
          {
            "$match": {
              "emailCopy": {
                "$exists": false
              }
            }
          },
          {
            "$group": {
              "_id": 1,
              "n": {
                "$sum": 1
              }
            }
          }
        ],
        ....

### Environment

Server
- Parse Server version: `5.4.0`
- Operating system: `node16`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `AWS`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `5.0.14`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `Atlas`

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): `iOS`
- SDK version: `1.19.4`

**Comment by sidan5** [comment]
@mtrezza Any help with that? it is bombing mongoDB server. Thanks.

**Comment by mtrezza** [comment]
I don't think the server uses aggregate queries internally. When do these queries appear, on server start or do you send a specific request?

**Comment by sidan5** [comment]
I get it few times a minute and I don’t think it’s my cloud code (don’t find anything that could cause this).

**Comment by mtrezza** [comment]
This looks suspicious:

```
"$match": {
          "emailCopy": {
            "$exists": false
          }
        }
```

I'm not aware of a Parse Server internal field `emailCopy`. Maybe look where you are using this field and try to disable that code. It could be that you have a circular trigger where a request invokes a Cloud Code trigger that invokes a Cloud Code trigger... essentially calling itself and therefore never stops.

You could also start with a fresh deployment of Parse Server without any customization and then gradually add your custom code (cloud code, functions, triggers, etc) to pin down where the issue begins.

**Comment by sidan5** [comment]
@mtrezza 
1. I cannot find anywhere in code where this key is being checked for non-existing. also I guess it's not from a query (as it is shown as command - not sure exactly what that means). Any other way to look for that? As currently the DB is huge and it would be pretty hard to simulate and debug (I guess this won't show on a smaller DB).

2. Could something like this trigger this kind of behavior?

        var existByEmailCount = await new Parse.Query(Parse.User).equalTo("emailCopy", email).count( { useMasterKey: true });

**Comment by mtrezza** [comment]
- What is the issue, that you don't know the origin of the request, that the operation runs repeatedly or that it runs for a long time?

- Are you using aggregation queries (`Parse.Query.aggregate`) anywhere?

- Could it be that you (or someone else) is using Parse Dashboard with certain filters the issue that command?

- Maybe add a `beforeFind` trigger (not sure if that's invoked before aggregation queries as well) and add a breakpoint or log entry to investigate.

- The `"$match": { "emailCopy": { "$exists": false }` seems pretty unique so I'm quite sure this doesn't come from Parse Server.

**Comment by sidan5** [comment]
> * What is the issue, that you don't know the origin of the request, that the operation runs repeatedly or that it runs for a long time?

All, The operations runs few times a minute (it is very high load so I don't think it's part of a loop), it takes a lot of time for the response (the response takes lots of the load as it runs through almost 200k relevant rows, 200k are just the ones where this specific field don't exist) on the DB - no way to index that.
> * Are you using aggregation queries (`Parse.Query.aggregate`) anywhere?

I don't see it anywhere. Not on CloudCode and not on iOS client.

> * Could it be that you (or someone else) is using Parse Dashboard with certain filters the issue that command?

Nope.

> * Maybe add a `beforeFind` trigger (not sure if that's invoked before aggregation queries as well) and add a breakpoint or log entry to investigate.

I'm not sure how to initiate that command. Have any example on how to catch this specific command on 'beforeFind'?

> * The `"$match": { "emailCopy": { "$exists": false }` seems pretty unique so I'm quite sure this doesn't come from Parse Server.

As I do not directly target that and as it is a command, could it be some result of another process?

@mtrezza Thank you very much for your help and responsiveness....

**Comment by mtrezza** [comment]
It's a "command" because it's an aggregation query.

So the issue is the query running at all as you don't know its origins. 

The query is counting how many user objects exist without the field `emailCopy`. That looks pretty specific like something from your custom code.

Now this can have 2 origins:
- The DB itself if it's running a script or has another source that triggers its API.
- Parse Server (via a client SDK, Cloud Code, REST API request, or Parse Server internals which seems unlikely)

So:

- If you stop Parse Server, do these DB commands still occur?
- If you then just launch Parse Server without triggering any requests, do these commands occur? If no, you can then try to call various parts of your app to find out when the command occurs.
- Can you reproduce the issue in a local development? If yes, run Parse Server in your local development, set a breakpoint in the MongoDB adapter or Parse Server DB adapter to trace from where that aggregation query originates.

**Comment by sidan5** [comment]
So the issue is actually with this line in my code:

     var existByEmailCount = await new Parse.Query(Parse.User).equalTo("emailCopy", email).count( { useMasterKey: true });

This line is running under beforeSave on user table:

      Parse.Cloud.beforeSave(Parse.User, async (request) => {
         ...
         var email = request.object.get("emailCopy");
         var existByEmailCount = await new Parse.Query(Parse.User).equalTo("emailCopy", email).count( { useMasterKey: true });
         ...
      }

We are supporting anonymous users so this is running without any value in "emailCopy", so this line initiate the search using undefined. What I did to solve this is just checking if there is some value before running the query and the weird load disappeared from the DB.


    if (typeof email !== 'undefined' && email !== null){
       var existByEmailCount = await new Parse.Query(Parse.User).equalTo("emailCopy", email).count( { useMasterKey: true });
       ...
    }

So that's actually not a bug on parse server (maybe it's nice to know that queries with undef might result this kind of command). Previously I haven't noticed that maybe because of the fact that anonymous users weren't broadly adapted (so load was below the radar). 

Closing. Thanks @mtrezza
