### ISSUE TITLE
Upgrade to latest JS SDK

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-server#8412]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation

Upgrade to latest JS SDK before release.

There have been important bug fixes since version Parse JS SDK 4.0.0. If necessary, publish a new release of the JS SDK.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/6.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0](https://github.com/parse-community/parse-server/releases/tag/6.0.0)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0-alpha.31](https://github.com/parse-community/parse-server/releases/tag/6.0.0-alpha.31)
