### ISSUE TITLE
Upgrade to 6.0 caused Error: Router.use() requires a middleware function but got an object

### ISSUE THREAD

**Issue by andreisucman** [parse-community/parse-server#8419]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description
I just upgraded to 6.0. from 5.3.3 and got this error on startup.
Router.use() requires a middleware function but got an object. From my [research](https://stackoverflow.com/questions/27465850/typeerror-router-use-requires-middleware-function-but-got-a-object) it appears that router function has not been exported in some part of the code 

### Actual Outcome
Server didn't start

### Expected Outcome
Server starts

### Environment

Server
- Parse Server version: `^6.0.0`
- Operating system: `Win 10 64`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `Localhost`

Database
- System (MongoDB or Postgres): Mongo`
- Database version: `6`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `Atlas`

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): `JS`
- SDK version: `^4.0.0-alpha.7`

**Comment by dblythy** [comment]
Version 6 has a number of breaking changes, specifically that Parse Server has to be stated before it is mounted, and is mounted via .app. 

See: https://github.com/parse-community/parse-server/blob/alpha/6.0.0.md#asynchronous-initialization

**Comment by mtrezza** [comment]
I'll add a link to the migration guide at the top of the GitHub release changelog, it's quite hidden.

**Comment by aacassandra** [comment]
sorry, any example how using parse server 6 in express with Asynchronous Initialization? thankyou

**Comment by mtrezza** [comment]
See migration guide in changelog.
