### ISSUE TITLE
The option "masterKeyIps" cannot be disabled

### ISSUE THREAD

**Issue by alljinx** [parse-community/parse-server#8421]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases).
- [x] 

### Issue Description
Parse-server 6.0.0 allow to restrict IPs than can use the MasterKey using the option "masterKeyIps".
The documentation says "Setting `['0.0.0.0/0']` means disabling the filter and the master key can be used from any IP address".
In fact, even localhost is blocked.

### Steps to reproduce
Juste install and configure Parse-Server v6 with the last Parse-Dashboard on your local machine.
Try to launch without the "masterKeyIps" option. Parse dashboard should works well.
Try with masterKeyIps: ['0.0.0.0/0'], after login, Parse Dashboard should display "Server not reachable: unauthorized: master key is required" and the node console should display "error: Request using master key rejected as the request IP address '::1' is not set in Parse Server option 'masterKeyIps'."

### Actual Outcome
MasterKey is not usable anywhere with masterKeyIps: ['0.0.0.0/0']

### Expected Outcome
MasterKey should be usable everywhere with masterKeyIps: ['0.0.0.0/0']

### Environment
parse-server 6.0.0
parse-dashboard 5.0.0

Server
- Parse Server version: 6.0.0
- Operating system: Windows 10
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): Local

Database
- System (MongoDB or Postgres): Postgres
- Database version: 15
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): Local

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): JS
- SDK version: 4.0.0

### Logs
error: Request using master key rejected as the request IP address '::1' is not set in Parse Server option 'masterKeyIps'.
Error: unauthorized: master key is required
    at handler (C:\GitProjects\jdm\node_modules\parse-server\src\middlewares.js:459:19)
    at C:\GitProjects\jdm\node_modules\parse-server\src\PromiseRouter.js:72:20
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by mtrezza** [comment]
I guess you'd need to specify IPv6 ranges separately. Could you try to set `masterKeyIps: ['::/0']`? In theory you should be able to set `masterKeyIps: ['0.0.0.0/0', '::/0']`, but I'm not sure the features supports a mix of IPv4 and IPv6.

**Comment by mtrezza** [comment]
@alljinx Were you able to resolve this issue?

**Comment by alljinx** [comment]
Oh sorry, forgot this topic. I was able to make it work using `masterKeyIps: ['0.0.0.0/0', '::1']`. So there is no bug and I can indeed close this issue. Maybe we should just update the documentation to add the IPv6. Thx !

**Comment by mtrezza** [comment]
Thanks for reporting back. I reopened to find out where this is actually a bug or only a docs issue.

There should be 2 working solutions for the issue you described:

- a) `['::1']` which is the IPv6 notation for localhost
- b) `['::/0']` which allows any IPv6 address.
- c) `['::']` which allows any IPv6 address, just a different notation from (b) with range omitted.

It seems you already verified that (a) works. Could you also verify (b), (c)?

**Comment by chillaxdev** [comment]
@mtrezza My original error was  `'::ffff:192.168.0.156'` is not set in Parse Server option...

I was hosting the parse server on a LAN.

Adding `masterKeyIps: ['::/0']` did not work for me.
Adding `masterKeyIps: ['0.0.0.0/0']` fixed it.

**Comment by mtrezza** [comment]
Thanks, that's strange. It reports an IPv6 address to not be allow-listed, but then it required an IPv4 CIDR range to allow-list it.

If you don't mind trying it out:
- Does `masterKeyIps: ['::']` work?
- Does `masterKeyIps: ['::ffff:192.168.0.156']` work, or whatever is the IPv6 address that is logged in the server logs?

**Comment by chillaxdev** [comment]
`'::'` does not work.
`'::ffff:192.168.0.156'` works.

Also, this is my serverURL: `http://192.168.0.156:1337/parse`

Server is running on Windows 10 x86_64 Pro.

For testing the API, I used the postman client locally to send a request with `X-Parse-Master-Key` set in the header.

**Comment by mtrezza** [comment]
I'll leave this issue open as there seems to be a bug in the parsing of IP addresses in `masterKeyIps`.

**Comment by VKlapan** [comment]
Hi!

I try to use parse-server 6.0.0 in docker, but have the same problem:
Request using master key rejected as the request IP address '172.21.0.1' is not set in Parse Server option 'masterKeyIps'

which I can't resolve by adding maintenanceKeyIps: ['172.21.0.1'] to config.

Any other ideas?

**Comment by mtrezza** [comment]
@VKlapan `masterKey` and `maintenanceKey` are not the same.

**Comment by VKlapan** [comment]
> @VKlapan `masterKey` and `maintenanceKey` are not the same.

Sorry, it is my misprint - of course, I had used masterKeyIps: [], but without effect.
So, I need any help yet.

**Comment by mtrezza** [comment]
Could you copy/paste the log entry and the respective config you've set for Parse Server? Just to make sure.

**Comment by VKlapan** [comment]
> Could you copy/paste the log entry and the respective config you've set for Parse Server? Just to make sure.

Useful hint! I have to check more carefully if a correct config are using, because a server works in docker container

**Comment by mtrezza** [comment]
Do you mean we can close the issue?

**Comment by mtrezza** [comment]
I understand that your issue has been resolved; we'll still keep this issue open since the OP issue still seems to exist.

**Comment by VKlapan** [comment]
> Do you mean we can close the issue?

Yes! Thanks. All is ok

**Comment by dblythy** [comment]
@mtrezza what would be the fix here? Is the issue with the package [ip-range-check](https://github.com/danielcompton/ip-range-check)?

**Comment by mtrezza** [comment]
It could be that the package doesn't interpret IPv6 ranges properly.

https://github.com/parse-community/parse-server/issues/8421#issuecomment-1454808608 shows the log error mentions `::ffff:192.168.0.156`, an IPv6 address. Adding that exact address works, but the IPv6 ranges should also work.

- Adding that exact IPv6 address to the options [works](https://github.com/parse-community/parse-server/issues/8421#issuecomment-1455030097).
- Adding `'0.0.0.0/0'` fixed it for the OP, which is expected, as IPv4 and IPv6 should be usable interchangeably for this "allow all" IP address.
- Adding `::/0` should work but doesn't.
- Adding `::` should ([maybe](https://github.com/parse-community/parse-server/pull/8501#discussion_r1162487695)) work but doesn't.
- Not sure if adding `::1` should work as well, it's the IPv6 notation for "localhost", but we haven no evidence that `::ffff:192.168.0.156` is in fact localhost.

**Comment by chillaxdev** [comment]
@mtrezza `::ffff:192.168.0.156` is a localhost on my scenario as I ran the postman client on the same machine where the parse server is running.

**Comment by Artnforces** [comment]
I'm using dockers for dashboard and server, I tried to change this value with those you give here.
Set the env variable PARSE_SERVER_MASTER_KEY_IPS: 
 - in docker-compose file of dashboard app: any effect (maybe normal)
- in docker file of server app : error, indicate that the value that I put is not an IP adress. (I tried array, single IP but it doesn't work).
-  I finally change the value in the code. work following what you indicate here.

**Comment by andreisucman** [comment]
After adding masterKeyIps: ["0.0.0.0/0", "::/0"] the error is gone, but the master key stopped working.

It gives no errors, just doesn't save with `.save(null, { useMasterKey: true});`

If I remove the masterKeyIps it gives the unauthorized error.

**Comment by mtrezza** [comment]
@andreisucman which PR branch did you try out and which commit of that branch exactly?

**Comment by andreisucman** [comment]
I guess it must be the `release` because I downloaded it from npm with `npm install`. 

To clarify I haven't changed the `package.json`. I only deleted the `package-lock.json` and `node modules` and ran `npm i`. 

So, normally nothing should've gone wrong.

**Comment by mtrezza** [comment]
Could you try out the latest alpha version, and if that doesn't solve the issue, try out the branch of the PR: https://github.com/parse-community/parse-server/pull/8510; and don't delete the package-lock.json file, otherwise we cannot know what package versions you're using.

**Comment by andreisucman** [comment]
I tested both the alpha14 and the PR. The problem is present. I posted the result in the issue #8582

**Comment by mtrezza** [comment]
@andreisucman, @Artnforces, @chillaxdev, @VKlapan could you please test out the fix in https://github.com/parse-community/parse-server/pull/8501? If you need the docker image to test it, please let us know and we'll release an alpha version for docker to test; whatever we can test before merging the PR would be good to test.

**Comment by andreisucman** [comment]
@mtrezza Just tested locally `6.3.0-alpha.3` and it's working. But it's working even if I entirely remove the masterKeyIps parameter. No warnings or errors with or without masterKeyIps.

I deleted node modules and lock, and reinstalled. So this is a clean install. 

Does it mean masterKeyIps was removed and won't be included?

**Comment by mtrezza** [comment]
You are saying if you set no masterKeyIps parameter at all the master key is not restricted by IP?

**Comment by andreisucman** [comment]
Yes, here is what I tried:

1) Comment out the masterKeyIps entirely
    ```
    masterKey: process.env.MASTER_KEY,
    // masterKeyIps: process.env.MASTER_KEY_IPS.split(","),
    allowOrigin: [process.env.ALLOWED_ORIGIN],
```
Result: no error is thrown. Master key is working.

2) Set masterKeyIps to wrong IP addresses. Both V4 and V6.
Result: no errors. Master key is working.

3) Setting masterKeyIps to correct values. Obviously here also no errors, master key is working.

It seems like masterKeyIps parameter is ignored.

**Comment by mtrezza** [comment]
How is that possible, we do have tests for this:

https://github.com/parse-community/parse-server/blob/f8b5a99d54e7d74e8608be8f0fc5266929039d36/spec/Middlewares.spec.js#L154-L163

Are you sure this param is not set any other way, via config, ENV var or CLI param?
Is the request actually requiring / sending the master key?

**Comment by andreisucman** [comment]
No, I only use .env for setting params for parse. And besides, even if the env variable existed somewhere, the server is working without the masterKeyIps param. 

I mean, if I delete it and restart the server, it works.

I just deleted node modules and lock file again. And reinstalled. Yes, it works without the masterKeyIps.

**Comment by mtrezza** [comment]
The default is localhost, so if you're using the masterKey from localhost without setting the option `masterKeyIps` it would always be permitted:

https://github.com/parse-community/parse-server/blob/f8b5a99d54e7d74e8608be8f0fc5266929039d36/src/Options/Definitions.js#L336-L342

Could that be the case?

Although you also wrote:

> 2) Set masterKeyIps to wrong IP addresses. Both V4 and V6.
> Result: no errors. Master key is working.

I'm not sure if `localhost` is always allowed, even if it's not explicitly mentioned, or if setting a wrong IP address should disable the master key also for localhost. @dblythy ?

**Comment by andreisucman** [comment]
Yes, I tested setting the wrong masterKeyIps on localhost and the server was working. 

What I did is ran ipconfig, copied my v4 and v6 addresses and then changed some numbers in them. Then I set them as env variables ["ipv6", "ipv4"] for masterKeyIps. 

Upon restart the server worked and I was able to run a cloud function with .save(null, { useMasterKey: true}). Today I will test it again, including the production setting and write here.

**Comment by mtrezza** [comment]
> I was able to run a cloud function with .save(null, { useMasterKey: true}).

Could you try to make a request from an actually different IP? Not from localhost. The issue may only be related to localhost. So what you could do is try to make a request from a non-localhost IP with:
- masterKeyIps option not set
- masterKeyIps option set to a different IP that is not in use
- masterKeyIps option set to the foreign (non-localhost) IP that you are making the request from

**Comment by mtrezza** [comment]
@andreisucman and anyone else who is having this issue, could you please try out https://github.com/parse-community/parse-server/pull/8510 before we merge it, to confirm that the issue is resolved? Thanks a bunch.

**Comment by nebitrams** [comment]
How do I disable this feature?  I tried the following and several other variation but they don't work.

Server Config.
```
masterKeyIps: ["0.0.0.0/0", "::/0"]
```

Error
```
error: Request using master key rejected as the request IP address '10.1.x.y' is not set in Parse Server option 'masterKeyIps'.
```

**Comment by andreiregpin** [comment]
@nebitrams try setting it like ["0.0.0.0/0","::1"] maybe itll work.

The problem is that it has a bug and doesn't recognize all ips. In my case it doesn't work at all.

**Comment by mtrezza** [comment]
@parse-community/server Bringing some attention to this issue; there are several reports of the feature not working and PR's that have seemingly unsuccessfully attempted to fix the issue (see PRs linked to this issue). If we cannot fix the bug we may need to remove the feature.

**Comment by nebitrams** [comment]
I managed to disable masterKeyIps successfully. I am sorry to all of you. There was a bug in my earlier code. It was a bit tricky because the array representation in code and environment variable are different.  Example: [], ["0.0.0.0/0","::/0"],"0.0.0.0/0","::/0"

# How to configure ParseServer in index.js
This is the code that works for me.

```
var server = new ParseServer({
  ...
  // disable by not defining this variable
  // enable by setting this var to specific IP. Example: 101.44.104.127/32,::/0
  masterKeyIps: process.env.MASTER_KEY_IPS ? process.env.MASTER_KEY_IPS.split(",") : ["0.0.0.0/0","::/0"],
  ...
})
```

# How to disable masterKeyIps
I managed to disable masterKeyIps with the above code in Heroku, by just not defining masterKeyIps variable.

# How to enable masterKeyIps
If I want to enable this feature In Heroku, then define the MASTER_KEY_IPS in this convention.

101.44.0.0/16,::/0
![image](https://github.com/parse-community/parse-server/assets/7193366/473f461b-f82d-4cad-9c08-8924fba2033c)

Note that the trailing IPv6 `,::/0` is mandatory.

# Please ignore my earlier post
> How do I disable this feature? I tried the following and several other variation but they don't work.
> 
> Server Config.
> 
> ```
> masterKeyIps: ["0.0.0.0/0", "::/0"]
> ```
> 
> Error
> 
> ```
> error: Request using master key rejected as the request IP address '10.1.x.y' is not set in Parse Server option 'masterKeyIps'.
> ```

**Comment by nebitrams** [comment]
Is this documentation correct?  It seems that the default is **_not_** `allow all ips`

![image](https://github.com/parse-community/parse-server/assets/7193366/56050dc5-571f-4249-a3ea-c10f1cc527c9)

https://parseplatform.org/parse-server/api/3.1.0/ParseServerOptions.html

**Comment by andreisucman** [comment]
@nebitrams do you have a cloud function that saves something to the db using the master key?

Try running it, if it works then it works.

**Comment by nebitrams** [comment]
> @nebitrams do you have a cloud function that saves something to the db using the master key?
> 
> Try running it, if it works then it works.

The default is blocking all non-listed IPs.

```
var server = new ParseServer({
  ...
  // if I don't set this, the default is to block all non-listed IPs.
  // masterKeyIps: process.env.MASTER_KEY_IPS,
  ...
})
```

This is the error when I call cloud function that uses master key, regardless of whether read or write.
```
error: Request using master key rejected as the request IP address '10.1.x.y' is not set in Parse Server option 'masterKeyIps'.
```

**Comment by andreisucman** [comment]
@nebitrams yes, this is because it's actually doesn't work, even though it doesn't throw the error on start. This feature must be removed.

**Comment by andreisucman** [comment]
@nebitrams as a workaround you can set the allowed ips in the env as `0.0.0.0/0,::1`. This should be ok for read operations. But for write operations you can use MongoDB nodejs driver if you use mongodb.

**Comment by mtrezza** [comment]
The default is blocking all IPs except localhost. This makes sense since the masterkey should not be used outside of Cloud Cloud for security.

It seems to me that the feature is working, but the confusion comes from how to define the IP list as env var, see https://github.com/parse-community/parse-server/issues/8421#issuecomment-1773641945.

So is this only a docs issue?

**Comment by nebitrams** [comment]
> @nebitrams as a workaround you can set the allowed ips in the env as `0.0.0.0/0,::1`. This should be ok for read operations in cloud functions. But for write operations you can use MongoDB nodejs driver if you use mongodb. This is how I do it.

Yes, I intend to disable this feature when I deploy my code to production, by setting `masterKeyIps` to `0.0.0.0/0,::1`.

FYI, I don't use master key to perform write.  I used it for read.  For any new codes that I add, I will try to avoid using master key.  I will relook at old code to see if I can remove the use of master key.

**Comment by mtrezza** [comment]
> This should be ok for read operations in cloud functions. But for write operations you can use MongoDB nodejs driver if you use mongodb.

Do you mean `masterKeyIps` works for read operations but not for write operations? Is this a new issue?

**Comment by andreisucman** [comment]
This is not a new issue. I reported it like 2-3 months ago. Moumulis then did some work, but apparently he wasn't successful because the release is 6.3.0. already and the problem still persists. I added the video where i test it to the original pr.

**Comment by mtrezza** [comment]
> I reported it like 2-3 months ago

Could you post the link here to the issue that you reported?

> Moumouls then did some work

What do you mean with "some work" - are you referring to https://github.com/parse-community/parse-server/pull/8510 or has there been another PR?

**Comment by andreisucman** [comment]
@mtrezza By reported 2-3 months ago I mean my messages in 8510 pr from july. And the 'some work' also refers there.

**Comment by mtrezza** [comment]
@andreisucman Please see https://github.com/parse-community/parse-server/pull/8510#issuecomment-1773926552, I believe we should separate the "write" issue from the "connection" issue. We can only track issues for which a specific GitHub issue has been created; comments are unlikely to be tracked and may just fall out of focus in the flow of the conversation.

**Comment by mtrezza** [comment]
@andreisucman We will try to reproduce the write issue internally to fix it; but to track and follow up on this, could you please open a new issue with all details, as I've mentioned in https://github.com/parse-community/parse-server/pull/8510#issuecomment-1773926552?

**Comment by andreisucman** [comment]
@mtrezza My issue was related to some package I used for caching. I deleted my comments to avoid confusion. The ip detection works.

**Comment by mtrezza** [comment]
Thanks, I'll reply in https://github.com/parse-community/parse-server/pull/8510.

**Comment by mtrezza** [comment]
@alljinx @nebitrams @VKlapan @Artnforces @andreisucman @chillaxdev 

We would like to bring this issue to a closing. Could you please let us know:
- Do you still experience a connection issue? If yes, what is the version of Parse Server and does the issue still occur if you use the branch of PR #8510?
- If you solved the issue and it was based on a misunderstanding, do you have any suggestions for how we can improve the documentation of `masterKeyIps`? For example there were some comments about setting the environment variable incorrectly.

**Comment by mtrezza** [comment]
For anyone who wants to allow any IP address to use the master key:

- The current Parse Server option `masterKeyIps` cannot compare IPv4 and IPv6 against each other. Each IP version range needs to be defined separately. For example, `masterKeyIps: ['0.0.0.0/0']` allows any IPv4 address, but no IPv6 address to use the master key. Conversely, `masterKeyIps: ['::/0']` allows any IPv6 address, but no IPv4 address.

- Keep in mind that the IP version in use depends on the network stack of the environment in which Parse Server runs. A local test may use a different IP version than a remote test. It's possible that locally `masterKeyIps: ['0.0.0.0/0']` works because it's using IPv4, but when the app is deployed remotely, it doesn't allow to use the master key because it's using IPv6.  
-  To allow any IPv4 and IPv6 address to use the master key, and effectively "disable" the IP filter, use `masterKeyIps: ['0.0.0.0/0', '::/0']`.
- Note that `['0.0.0.0/0', '::/1']` is not the same as `['0.0.0.0/0', '::/0']`. I mention this because this combination has been posted here and elsewhere with the false expectation to allow any IP address.
- IPv6 addresses with a zone index (`%` suffix) may not be supported by this feature, for example `2001:db8:3333:4444:5555:6666:7777:8888%12`.
- When setting the option via environment variable the notation is a comma-separated string, for example `PARSE_SERVER_MASTER_KEY_IPS = "0.0.0.0/0,::/0"`.
- To deny the use of master key for every IP address, even from within Cloud Code for localhost, set an empty array `masterKeyIps: []`. This is currently not possible via environment variable, as there is no way to pass an empty array to Parse Server via an environment variable. For example, `PARSE_SERVER_MASTER_KEY_IPS = "[]"` will just be ignored.
- Check the correct spelling of the option, which is `masterKeyIps` and not for example `masterKeyIPs`.

I've condensed this and amended the Parse Server options docs in https://github.com/parse-community/parse-server/pull/8814.

If anyone is still facing issues after considering the above, please let us know.
Otherwise we'll consider this just a documentation issue and close this via #8814.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.5.0-alpha.2](https://github.com/parse-community/parse-server/releases/tag/6.5.0-alpha.2)

**Comment by kantorcodes** [comment]
> For anyone who wants to allow any IP address to use the master key:
> 
> * The current Parse Server option `masterKeyIps` cannot compare IPv4 and IPv6 against each other. Each IP version range needs to be defined separately. For example, `masterKeyIPs: ['0.0.0.0/0']` allows any IPv4 address, but no IPv6 address to use the master key. Conversely, `masterKeyIPs: ['::0']` allows any IPv6 address, but no IPv4 address.
> * Keep in mind that the IP version in use depends on the network stack of the environment in which Parse Server runs. A local test may use a different IP version than a remote test. It's possible that locally `masterKeyIPs: ['0.0.0.0/0']` works because it's using IPv4, but when the app is deployed remotely, it doesn't allow to use the master key because it's using IPv6.
> * To allow any IPv4 and IPv6 address to use the master key, and effectively "disable" the IP filter, use `masterKeyIPs: ['0.0.0.0/0', '::0']`.
> * Note that `['0.0.0.0/0', '::1']` is not the same as `['0.0.0.0/0', '::0']`. I mention this because this combination has been posted here and elsewhere with the false expectation to allow any IP address.
> * IPv6 addresses with a zone index (`%` suffix) may not be supported by this feature, for example `2001:db8:3333:4444:5555:6666:7777:8888%12`.
> * When setting the option via environment variable the notation is a comma-separated string, for example `PARSE_SERVER_MASTER_KEY_IPS = "0.0.0.0/0,::0"`.
> * To deny the use of master key for every IP address, even from within Cloud Code for localhost, set an empty array `masterKeyIPs: []`. This is currently not possible via environment variable, as there is no way to pass an empty array to Parse Server via an environment variable. For example, `PARSE_SERVER_MASTER_KEY_IPS = "[]"` will just be ignored.
> 
> I've condensed this and amended the Parse Server options docs in #8814.
> 
> If anyone is still facing issues after considering the above, please let us know. Otherwise we'll consider this just a documentation issue and close this via #8814.

Personally still experiencing this issue with the latest version. I honestly think an option to disable the check completely would be the way to go, passing in IPs in different formats just isn't intuitive at all.

**Comment by mtrezza** [comment]
@kantorcodes If you are experiencing any issues please open a new GitHub issue with a reference to this GitHub issue, and provide exact details so the issue can be reproduced. If it cannot be reproduced, then it cannot be fixed.

**Comment by kantorcodes** [comment]
> @kantorcodes If you are experiencing any issues please open a new GitHub issue with a reference to this GitHub issue, and provide exact details so the issue can be reproduced. If it cannot be reproduced, then it cannot be fixed.

I followed the exact steps suggested for IPv4 and IPv6 and deployed. Got the "unauthorized: master key required". That's all. 

Previous versions work fine. We should be able to turn this feature off. It is not intuitive at all.

**Comment by mtrezza** [comment]
For anyone still experiencing this issue, please try `masterKeyIps: ['0.0.0.0/0', '::/0']` to effectively allow any IPv4 and IPv6 address. The [comment](https://github.com/parse-community/parse-server/issues/8421#issuecomment-1816906502) above contained a typo and did not contain the slash in the IPv6 address (`::0`), which has been corrected now.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.5.0](https://github.com/parse-community/parse-server/releases/tag/6.5.0)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/7.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.0.0](https://github.com/parse-community/parse-server/releases/tag/7.0.0)

**Comment by tran-huy-phuc** [comment]
https://parseplatform.org/parse-server/api/master/ParseServerOptions.html

It looks like the doc is still not updated

![image](https://github.com/parse-community/parse-server/assets/4323410/a94d0645-bf25-474b-b521-24be3212c03d)

**Comment by mtrezza** [comment]
@thphuc You need to use the correct API version [7.0.0](https://parseplatform.org/parse-server/api/7.0.0/ParseServerOptions.html).
