### ISSUE TITLE
LiveQueryServer doesn't shutdown properly

### ISSUE THREAD

**Issue by dplewis** [parse-community/parse-server#8424]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description

There is a flaky test on the JS SDK and I believe it is caused by the liveQueryServer not shutting down when the server shuts down. The server is shutdown but there are still connections to the liveQueryServer. This may have unwanted effects. Also there are flaky tests on the server that could be addressed
https://github.com/parse-community/Parse-SDK-JS/actions/runs/4011772368/jobs/6889651856

### Steps to reproduce

1) Start server with `startLiveQueryServer: true` configuration
2) Call `server.handleShutdown()`
3) Call `server.close()`
4) Check if live query server is still running

### Actual Outcome

LiveQueryServer is still opened

### Expected Outcome

LiveQueryServer is closed

### Alternatives / Workarounds

In production I use a dedicated live query server instead of the internal configuration which is recommended so I never see this issue.

### Environment

Server
- Parse Server version: `6.0.0`
- Operating system: `Mac`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `local`

Database
- System (MongoDB or Postgres): `Mongo`
- Database version: `4.4`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `local`

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): `Javascript`
- SDK version: `4.0.0`

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.1.0-alpha.19](https://github.com/parse-community/parse-server/releases/tag/6.1.0-alpha.19)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.3.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/6.3.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.3.0-alpha.1](https://github.com/parse-community/parse-server/releases/tag/6.3.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.3.0](https://github.com/parse-community/parse-server/releases/tag/6.3.0)
