### ISSUE TITLE
Bump jsonwebtoken to 9.0.0 in LTS branch

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-server#8427]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation

Upgrade fixes security vulnerabilities, but since it's a major version upgrade, some tests fail.

### Feature / Enhancement Description

Port fix in https://github.com/parse-community/parse-server/pull/8420 to `release-5.x.x` LTS branch.
Related issue: https://github.com/parse-community/parse-server/issues/8356

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.4.2](https://github.com/parse-community/parse-server/releases/tag/5.4.2)

**Comment by mtrezza** [comment]
Closed via https://github.com/parse-community/parse-server/pull/8431
