### ISSUE TITLE
Allow AuthAdapters to be constructed

### ISSUE THREAD

**Issue by dblythy** [parse-community/parse-server#8439]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation

Currently, the `AuthAdapter` class is not exported by Parse Server, meaning developers cannot extend it to their own custom auth 

### Feature / Enhancement Description

Export `AuthAdapter`

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.1.0-alpha.1](https://github.com/parse-community/parse-server/releases/tag/6.1.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.1.0-beta.2](https://github.com/parse-community/parse-server/releases/tag/6.1.0-beta.2)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.1.0](https://github.com/parse-community/parse-server/releases/tag/6.1.0)
