### ISSUE TITLE
Add `afterFind` to auth adapter

### ISSUE THREAD

**Issue by dblythy** [parse-community/parse-server#8440]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation

Currently, to strip authData fields, it needs to be done in an afterFind trigger

### Feature / Enhancement Description

Give authAdapters the ability to customize find response

**Comment by mtrezza** [comment]
Could you give more details about the issue? In what scenario would one want to strip authData fields and from what should they be stripped?

**Comment by dblythy** [comment]
For the MFA Adapter, the secret which is used to generate the OTP is only meant to be seen on the server side.

**Comment by cbaker6** [comment]
Not sure if this can end up causing issues, but be mindful that most of the handling of `authData` happens on the client SDKs or on the client directly if a developer is using REST. See my comments in the following threads: https://github.com/parse-community/parse-server/issues/7737#issuecomment-1002726325

https://github.com/parse-community/Parse-SDK-JS/issues/1353#issuecomment-826192761

**Comment by dblythy** [comment]
Yeah, I don’t see it being implemented on many with adapters, but for the MFA one we need to store a secret in auth data which shouldn’t be seen on the client side. The client SDKs already need work to support the new auth adapters

**Comment by dblythy** [comment]
Related: https://community.parseplatform.org/t/remove-sensitive-data-from-authdata/2377/2

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.1.0-alpha.3](https://github.com/parse-community/parse-server/releases/tag/6.1.0-alpha.3)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.1.0-beta.2](https://github.com/parse-community/parse-server/releases/tag/6.1.0-beta.2)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.1.0](https://github.com/parse-community/parse-server/releases/tag/6.1.0)
