### ISSUE TITLE
Nested Objects can't retrieve dates

### ISSUE THREAD

**Issue by magnacartatron** [parse-community/parse-server#8445]
### New Issue Checklist
- [x ] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x ] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x ] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [ x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases).

### Issue Description
Can save nested objects, can't retrieve dates.

### Steps to reproduce
const test = new Parse.Object("Test");
test.set("objectTypeColumnName", { date: new Date(), otherValue: true });
await test.save();

const testRes = new Parse.Query("Test").first();
console.log(testRes.get("objectTypeColumnName"));

Expected 
{
    date: 2023-02-25T04:44:46.848Z,
    otherValue: true
}

Actual 
{
   date: {},
   otherValue: true
}

- Parse Server version: `6.0.0`
- Operating system: `MacOS 13.2.1`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `local`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `5.0.1`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `local`

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): `JavaScript`
- SDK version: `4.0.1`

**Comment by dblythy** [comment]
Should be fixed by #8446

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.1.0-alpha.2](https://github.com/parse-community/parse-server/releases/tag/6.1.0-alpha.2)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.1.0-beta.2](https://github.com/parse-community/parse-server/releases/tag/6.1.0-beta.2)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.1.0](https://github.com/parse-community/parse-server/releases/tag/6.1.0)
