### ISSUE TITLE
GraphQL can not use custom schema to extend type Custom Class

### ISSUE THREAD

**Issue by Vildnex** [parse-community/parse-server#8460]
### New Issue Checklist
- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description
I am trying to create some custom schema with custom resolvers (as cloud functions) but I am getting every single time the following error:

"Cannot extend non-object type \"SomeClassWhereInput\".",

Which is caused by this query from `parse-server/cloud/schema_2.graphql`: 

```
extend type SomeClassWhereInput{
    something: String @resolve
}
```

I've also tried with `StringWhereInput`  and have the same error type.

### Steps to reproduce

1.  clone my bug repo where I've made it to be reproducible https://github.com/Vildnex/BugParseServer
2.  run `docker-compose up -d`
3.  create the demo class named SomeClass by running the 2 queries from `create_db_queries.graphql`:
```
mutation CreateSomeClass{
    createClass(input: {
        name: "SomeClass"
        schemaFields: {
            addStrings: [{
                name: "description"
            }]
        }
    }){
        __typename
    }
}
```
```
mutation AddSomeClass{
    createSomeClass(input: {
         fields: {
            description: "description V2"
         }
    }){
        __typename
    }
}

```
4.  Generate `schema.graphql` file by running `.graphconfig` file
5.  Uncomment the query from `schema_2.graphql`
```
extend type StringWhereInput{
    something: String @resolve
}
```
and also uncomment the resolver from `main.js`
```
Parse.Cloud.define("something", (req) => {
    return Parse.Promise.error({"message": "User not found"});
});
```
6.  Restart server via `docker-compose restart server`
7.  Re-run the `.graphconfig` and get the error `"message": "Cannot extend non-object type \"StringWhereInput\".",`

### Actual Outcome
```
{
  "errors": [
    {
      "message": "Cannot extend non-object type \"StringWhereInput\".",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "Error: Cannot extend non-object type \"StringWhereInput\".",
            "    at assertValidSDLExtension (/parse-server/node_modules/graphql/validation/validate.js:124:11)",
            "    at Object.extendSchema (/parse-server/node_modules/graphql/utilities/extendSchema.js:77:43)",
            "    at /parse-server/node_modules/@graphql-tools/stitch/index.cjs.js:1232:28",
            "    at Array.forEach (<anonymous>)",
            "    at stitchSchemas (/parse-server/node_modules/@graphql-tools/stitch/index.cjs.js:1231:16)",
            "    at ParseGraphQLSchema.load (/parse-server/lib/GraphQL/ParseGraphQLSchema.js:236:56)",
            "    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
            "    at async ParseGraphQLServer._getGraphQLOptions (/parse-server/lib/GraphQL/ParseGraphQLServer.js:61:17)",
            "    at async /parse-server/lib/GraphQL/ParseGraphQLServer.js:99:86"
          ]
        }
      }
    }
  ]
}

```
### Expected Outcome
I would expect no error and the possibility of running this query successfully: 
```
query {
    someClasses(where: {
        something: "something"
    }){
        count
    }
}
```
Or at least this is what I've understood should happen after  reading this [documentation](https://docs.parseplatform.org/graphql/guide/) 
### Environment
I should mention that this version was chosen to be the same as used in back4app.com/ but I've tried also with the latest version such as mongo 6.0.4 and also Parse Server 5.4.0 and 6.0.0 but I have the same result.

Server
- Parse Server version: `5.2.3`
- Operating system: `Docker`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `3.6`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `Local`

**Comment by mtrezza** [comment]
Maybe @Moumouls has some quick comments here...

**Comment by Vildnex** [comment]
Soo... Any update regarind this problem? 😅

**Comment by Vildnex** [comment]
@mtrezza @Moumouls

**Comment by kekami** [comment]
Did you manage solve it somehow @Vildnex ? Since you closed the issue as completed.

**Comment by Moumouls** [comment]
@Vildnex on my side i extend inputs/outputs with Code first graphql schema, i don't know if the support of Schema First extension is complete and unfortunately it's not related to parse-server but underlaying lib.
