### ISSUE TITLE
Unable to get Parse server working with HTTPS instead of HTTP

### ISSUE THREAD

**Issue by JohnRoxMySox23** [parse-community/parse-server#8465]
### Issue Description
Hello to everyone,

I have successfully deployed a Parse Server following the [installation guide][1] on my server running Ubuntu, everything works fine with HTTP, the server (`http://www.example.com:1337/parse`) answers correctly the requests and the dashboard (`http://www.example.com:4040`) appears fine.

Then I have added a SSL certificate, and updated my domain configuration in apache:

    <VirtualHost *:443>
        ServerAdmin admin@example.com
    	DocumentRoot /var/www/html/example.com
        ServerName example.com
    
    	SSLEngine on
    	SSLCertificateFile /etc/certificate/example.com.cer
    	SSLCertificateKeyFile /etc/certificate/example.com.key

    	ErrorLog /var/log/apache2/example.com/error.log
    	CustomLog /var/log/apache2/example.com/access.log combined
    </VirtualHost>

Reaching `https://www.example.com` works now fine and is secured. But then I tried to update my parse-server config like this:

    {
      "appId": "appId",
      "masterKey": "masterKey",
      "clientKey": "clientKey",
      "appName": "MyParseApp",
      "cloud": "./cloud/main",
      "serverURL": "https://www.example.com:1337/parse",
      "databaseURI": "postgres://postgres:mypostgrespassword@localhost:5432/postgres"
    }

When starting the server while setting https instead of http for the serverURL, I get this in the logs:

    [21448] parse-server running on https://www.example.com:1337/parse
    WARNING, Unable to connect to 'https://www.example.com:1337/parse'. Cloud code and push notifications may be unavailable!

And when trying to curl the server URL, here is the result:

-> for http: *(expected result)*

    root@localhost:~/parse-server# curl http://www.example.com:1337/parse
    {"error":"unauthorized"}

-> for https: 

    root@localhost:~/parse-server# curl https://www.example.com:1337/parse
    curl: (35) error:0A00010B:SSL routines::wrong version number

Am I missing something in the configuration? Thank you for your help.

  [1]: https://docs.parseplatform.org/parse-server/guide/#deploying-on-aws-ec2-ubuntu-using-postgresql

### Steps to reproduce
Basic installation of Parse Server following the installation guide on a unsecured domain, then adding a SSL certificate and trying to replace http with https in Parse config files.

### Actual Outcome
When I try to reach my server with https, i.e. `https://www.example.com:1337/parse`, here is what I get in web browsers:
> SSL_ERROR_RX_RECORD_TOO_LONG

### Expected Outcome
I would instead expect to get the usual `{"error": "unauthorized"}`.

### Environment

Server
- Parse Server version: `3.10.0`
- Operating system: `Ubuntu 22.04`

Database
- System (MongoDB or Postgres): `Postgresql 14.7`

**Comment by mtrezza** [comment]
Closing, you have already posted this in the [forum](https://community.parseplatform.org/t/my-server-and-dashboard-are-only-available-with-http-not-https/3294).
