### ISSUE TITLE
GridFS fails with `enableSchemaHooks` is not supported

### ISSUE THREAD

**Issue by dblythy** [parse-community/parse-server#8466]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description

As mongoOptions are now set to Parse Server's default options, `enableSchemaHooks` can be passed to the GridFSAdapter

### Steps to reproduce

- Start Parse Server on alpha
- Attempt to save a file

### Actual Outcome

- Rejected

### Expected Outcome

- Should resolve

### Environment

Server
- Parse Server version: `alpha`
- Operating system: `FILL_THIS_OUT`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `FILL_THIS_OUT`

Database
- System (MongoDB or Postgres): `FILL_THIS_OUT`
- Database version: `FILL_THIS_OUT`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `FILL_THIS_OUT`

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): `FILL_THIS_OUT`
- SDK version: `FILL_THIS_OUT`

**Comment by omairvaiyani** [comment]
@dblythy We noticed this issue yesterday, I've opened a [PR](https://github.com/parse-community/parse-server/pull/8470) to address it

**Comment by mtrezza** [comment]
Does this issue only exist on the alpha branch or also on beta or release? Do we know which PR introduced this bug?

**Comment by dblythy** [comment]
I would say it was introduced by #8436, as that PR set the default for `enableSchemaHooks`. So alpha only for if `enableSchemaHooks` is unset.

However, if the feature `enableSchemaHooks` is set to `true` from Parse Server 5 to alpha, GridFS will fail. Introduced by #7214

**Comment by mtrezza** [comment]
Interesting that we don't have any test coverage that picked that up. Ok so since this is a fix that also applies to stable releases this should be a `fix` commit type. We just need to name the PR in a way that reflects that broad scope.

**Comment by mtrezza** [comment]
@omairvaiyani thanks for opening https://github.com/parse-community/parse-server/pull/8470. @dblythy is there anything from that PR that you can incorporate into this PR?

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.1.0-alpha.12](https://github.com/parse-community/parse-server/releases/tag/6.1.0-alpha.12)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.3.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/6.3.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.3.0-alpha.1](https://github.com/parse-community/parse-server/releases/tag/6.3.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.3.0](https://github.com/parse-community/parse-server/releases/tag/6.3.0)
