### ISSUE TITLE
Embedded dates are returned as empty values in Parse 6

### ISSUE THREAD

**Issue by AdrianCurtin** [parse-community/parse-server#8478]
- [ X] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [X ] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [X ] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [ X] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description
When returning an object from a query that includes an embedded object with dates, the dates are returned as {} instead of the date values shown in mongodb.

Regular dates inside documents at the root level are returned.

### Steps to reproduce

Create a mongodb document with an embedded object with an assigned property that is a date.
Query that document and read the retrieved embedded date field.

ex:

{ _id: "myObj",
  myDoc: {storedDate: {__type: "Date", iso: "2022-10-05T10:31:09.000Z"}},
}

### Actual Outcome

storedDate = {}

### Expected Outcome
storedDate = {__type: "Date", iso: "2022-10-05T10:31:09.000Z"}
### Environment
mongoDb 5.0

Server
- Parse Server version: 6.0.0, 6.1.0-beta1, 6.1.0-alpha7
- Operating system: MacOS
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): Heroku

Database
- System (MongoDB or Postgres): MongoDB
- Database version: 5.2
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): MongoDB Atlas

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): Javascript

**Comment by dblythy** [comment]
Closing as a duplicate of #8445

This issue has been fixed in [6.1.0-alpha.2](https://github.com/parse-community/parse-server/releases/tag/6.1.0-alpha.2)

**Comment by AdrianCurtin** [comment]
@dblythy I just tested this on alpha-7

**Comment by dblythy** [comment]
Can you send the code that you used to generate this issue, or open a PR with a failing test?

**Comment by AdrianCurtin** [comment]
@dblythy 
honestly it is just 

```
let query = new Parse.Query(Parse.Object.extend('projectData'));

query.equalTo("objectId",queried_id);
    
await query.first();
```

The query returns the correct data, but the embedded dates are blank {}
