### ISSUE TITLE
RestSchema interface incorrectly types defaultValue

### ISSUE THREAD

**Issue by magnacartatron** [parse-community/parse-server#8498]
### New Issue Checklist

- [x ] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [ x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [ x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [ x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description
See interface RestSchema defaultValue.
It is currently set to string
If default value is a number then typescript error occurs, same applies for arrays

### Steps to reproduce
export const TestClass: RestSchema = {
 className: 'TestClass',
 fields: {
  testField: {
   type: 'Number',
   require: false,
   defaultValue: 0 //Type 'number' is not assignable to type 'string'.
  }
 }
}

### Actual Outcome
Typescript error //Type 'type' not assignable to type 'string'.

### Expected Outcome
Expect to apply default value based on type
### Environment
NodeJS 18

Server
- Parse Server version: 6.1.0-alpha.2
- Operating system: MacOS Ventura 13.3
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): local

Database
- System (MongoDB or Postgres): MongoDB
- Database version: 5.0.2
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): local

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): `Javascript`
- SDK version: `4.0.1`

**Comment by magnacartatron** [comment]
@mtrezza  still broken as of 6.3.1 

Can't we modify it something like this

```
type RestSchemaFieldTypes = "String" | "Boolean" | "Pointer"; // Add other types as needed

type DefaultValueByFieldType<T extends RestSchemaFieldTypes> = T extends "Boolean"
  ? boolean
  : T extends "String"
  ? string
  : T extends "Pointer"
  ? string
  : never;

interface RestSchemaField<Type extends RestSchemaFieldTypes> {
  type: Type;
  targetClass?: string;
  required?: boolean;
  defaultValue?: DefaultValueByFieldType<Type>;
}

interface RestSchema {
  className: string;
  fields: {
    [key: string]: RestSchemaField<RestSchemaFieldTypes>;
  };
  classLevelPermissions: Schema.CLP;
  indexes?: {
    [key: string]: {
      [key: string]: any;
    };
  };
}
```

I can give you a complete solution.
My biggest beef is this.
I have to define my Schema in it's own area, then I have to define my interfaces for my Parse Classes, then I have to define my Parse Classes (extends Parse.Object<T>) based on the interfaces. 
I have 3 separate definitions, it would be really nice if this worked properly as then that would go down to 2 with some typescript sorcery.

**Comment by magnacartatron** [comment]
Here's a sample solution

```
type TYPE =
  | "String"
  | "Number"
  | "Boolean"
  | "Date"
  | "File"
  | "GeoPoint"
  | "Polygon"
  | "Array"
  | "Object"
  | "Pointer"
  | "Relation";

type FieldType =
  | string
  | number
  | boolean
  | Date
  | File
  | GeoPoint
  | Polygon
  | any[]
  | object
  | Pointer
  | Relation;

type ParseTypeByFieldType<T extends FieldType> = T extends string
  ? string
  : T extends number
  ? number
  : T extends boolean
  ? boolean
  : T extends Date
  ? Date
  : T extends File
  ? Parse.File
  : T extends GeoPoint
  ? Parse.GeoPoint
  : T extends Polygon
  ? Parse.Polygon
  : T extends any[]
  ? Parse.Array<ParseTypeByFieldType<T[0]>>
  : T extends object
  ? Parse.Object<ParseTypeByFieldType<T[keyof T]>>
  : T extends Pointer
  ? Parse.Pointer<ParseTypeByFieldType<T["targetClass"]>>
  : T extends Relation
  ? Parse.Relation<ParseTypeByFieldType<T["targetClass"]>>
  : never;

type RestSchemaField<Type extends TYPE> = Type extends "Pointer" | "Relation"
  ? {
      type: Type;
      targetClass: string;
      required?: boolean;
      defaultValue?: ParseTypeByFieldType<FieldType>;
    }
  : {
      type: Type;
      required?: boolean;
      defaultValue?: ParseTypeByFieldType<FieldType>;
    };

interface RestSchema {
  className: string;
  fields: {
    [key: string]: RestSchemaField<TYPE>;
  };
  classLevelPermissions: Schema.CLP;
  indexes?: {
    [key: string]: {
      [key: string]: any;
    };
  };
}
```

and sample working schema

```
const sampleSchema: RestSchema = {
  className: "SampleClass",
  fields: {
    stringField: {
      type: "String",
      required: true,
      defaultValue: "Default String",
    },
    numberField: {
      type: "Number",
      required: false,
      defaultValue: 42,
    },
    booleanField: {
      type: "Boolean",
      required: true,
      defaultValue: true,
    },
    pointerField: {
      type: "Pointer",
      targetClass: "TargetClass",
      required: false,
      defaultValue: { __type: "Pointer", className: "TargetClass", objectId: "abc123" },
    },
  },
  classLevelPermissions: {
    find: {
      "*": true,
    },
    get: {
      "*": true,
    },
    create: {
      "*": true,
    },
    update: {
      "*": true,
    },
    delete: {
      "*": true,
    },
  },
};
```

I need to do some more testing but that's the jist

**Comment by mtrezza** [comment]
If the TS error comes from a 3rd party library please open an issue with them.
