### ISSUE TITLE
Issue with Vite: Uncaught TypeError: Super expression must either be null or a function

### ISSUE THREAD

**Issue by tiavina-mika** [parse-community/parse-server#8499]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description
When running `yarn dev`, the server is running without error, but with a blank page and an error in the browser console
![image](https://user-images.githubusercontent.com/42656064/230765918-3663b359-597c-4312-9280-05aca8f42a3e.png)

### Steps to reproduce
`yarn dev`
See the browser console

### Actual Outcome
Blank page and and got an error in browser console
Clone this repository and run `yarn dev` to reproduce it: https://github.com/tiavina-mika/parse-server-vite-issue

### Expected Outcome
Should display the page

Server
- Parse Server version: `5.3.0`
- Operating system: `Windows 10`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `Local`

Database
- System (MongoDB or Postgres): `MongoDB `
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `MongoDB Atlas`

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): `JavaScript`
- SDK version: `3.4.3`

### Logs
```
inherits.js:9 Uncaught TypeError: Super expression must either be null or a function
    at _inherits (inherits.js:9:11)
    at LiveQuerySubscription.js:149:18
    at node_modules/parse/lib/browser/LiveQuerySubscription.js (LiveQuerySubscription.js:197:1)
    at __require2 (chunk-7FP5O474.js?v=ba11ca24:10:50)
    at node_modules/parse/lib/browser/LiveQueryClient.js (LiveQueryClient.js:63:53)
    at __require2 (chunk-7FP5O474.js?v=ba11ca24:10:50)
    at node_modules/parse/lib/browser/ParseLiveQuery.js (ParseLiveQuery.js:41:47)
    at __require2 (chunk-7FP5O474.js?v=ba11ca24:10:50)
    at node_modules/parse/lib/browser/Parse.js (Parse.js:339:19)
    at __require2 (chunk-7FP5O474.js?v=ba11ca24:10:50)
```

**Comment by dblythy** [comment]
Duplicate of https://github.com/parse-community/Parse-SDK-JS/issues/1362
