### ISSUE TITLE
Create rateLimit `zone` to support global rate limiting

### ISSUE THREAD

**Issue by dblythy** [parse-community/parse-server#8507]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation

Currently, rate limiting is only supported per IP

### Feature / Enhancement Description

Rate limiting might want to occur:

-globally
-per session token
-per user

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.1.0-alpha.20](https://github.com/parse-community/parse-server/releases/tag/6.1.0-alpha.20)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.3.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/6.3.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.3.0-alpha.1](https://github.com/parse-community/parse-server/releases/tag/6.3.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.3.0](https://github.com/parse-community/parse-server/releases/tag/6.3.0)
