### ISSUE TITLE
Expose ParseServer version number as a property in a ParseServer instance

### ISSUE THREAD

**Issue by jaysonng** [parse-community/parse-server#8531]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation

There is no way to get the version number of a ParseServer instance.

### Feature / Enhancement Description

Expose the running version of a ParseServer Instance

### Example Use Case

For easy debugging and information gathering, the ParseServer version number should be easily accessible via console logging. 

### Alternatives / Workarounds

as mentioned by @mtrezza here:  https://community.parseplatform.org/t/parse-server-version-property/3441/2?u=jayson the current workaround by ParseDashboard is to use the masterkey

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.3.0-alpha.5](https://github.com/parse-community/parse-server/releases/tag/6.3.0-alpha.5)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.4.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/6.4.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.4.0-alpha.1](https://github.com/parse-community/parse-server/releases/tag/6.4.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.4.0](https://github.com/parse-community/parse-server/releases/tag/6.4.0)
