### ISSUE TITLE
`extendSessionOnUse` not working when using custom session fields?

### ISSUE THREAD

**Issue by mman** [parse-community/parse-server#8575]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description

I am playing with the latest alpha build of `parse-server` and I have enabled the `extendSessionOnUse` like this:

```
€ cat index.js | grep -i session
  sessionLength: (365 * 24 * 60 * 60),  // 1 year in seconds
  extendSessionOnUse: true,             // extend on use
  expireInactiveSessions: true,         // expire when outdated
```

I have created a test user, and now I am playing with the app, seeing whether the session is properly extended by given `sessionLength` anytime the token is used. 

In my case it does not seem to work properly, here is the mongo CLI refresh (edited for brevity) of the given session object after each API interaction.

```
{ "expiresAt" : ISODate("2024-05-23T15:39:28.827Z"), "_created_at" : ISODate("2023-05-24T15:39:28.827Z"),
  "_updated_at" : ISODate("2023-05-24T15:39:29.531Z"), "lastUsedAt" : ISODate("2023-05-24T15:39:29.413Z") }

{ "expiresAt" : ISODate("2024-05-23T15:39:28.827Z"), "_created_at" : ISODate("2023-05-24T15:39:28.827Z"),
  "_updated_at" : ISODate("2023-05-24T15:40:27.251Z"), "lastUsedAt" : ISODate("2023-05-24T15:40:27.135Z") }

{"expiresAt" : ISODate("2024-05-23T15:39:28.827Z"), "_created_at" : ISODate("2023-05-24T15:39:28.827Z"),
 "_updated_at" : ISODate("2023-05-24T15:41:14.505Z"), "lastUsedAt" : ISODate("2023-05-24T15:41:14.374Z") }
```

Note that `expiresAt` stays untouched, while I am modifying and saving other unrelated field. I have already in the past implemented my own `extendSessionOnUse` by setting a `lastUsedAt` date field on the session object every time the session is used. Note that `lastUsedAt` as well as `_updated_at` fields are updating correctly.

I am using latest `Parse-iOS-OSX-SDK`, which if I understand it correctly should only send to the server modified fields, in my case I only modify session `lastUsedAt` property.

So I started investigating this in more detail, here is what I get in the verbose log after starting the app:

It first fetches the current session:

```
verbose: REQUEST for [GET] /parse/sessions/me: {} { /* headers omitted for brevity */ }
verbose: RESPONSE from [GET] /parse/sessions/me: {
  "response": {
    "objectId": "XXX",
    "sessionToken": "XXX",
    "user": {
      "__type": "Pointer",
      "className": "_User",
      "objectId": "XXX"
    },
    "createdWith": {
      "action": "signup",
      "authProvider": "password"
    },
    "expiresAt": {
      "__type": "Date",
      "iso": "2024-05-23T15:39:28.827Z"
    },
    "installationId": "60cb13c9-20c5-4890-a4ab-11edb1eabce8",
    "createdAt": "2023-05-24T15:39:28.827Z",
    "updatedAt": "2023-05-24T15:48:52.292Z",
    "lastUsedAt": {
      "__type": "Date",
      "iso": "2023-05-24T15:48:52.181Z"
    }
  }
}
```

And then modifies the `lastUsedAt` field:

```
verbose: REQUEST for [PUT] /parse/classes/_Session/XXX: {
  "lastUsedAt": {
    "__type": "Date",
    "iso": "2023-05-24T16:03:28.701Z"
  }
}

verbose: RESPONSE from [PUT] /parse/classes/_Session/XXX: {
  "response": {
    "updatedAt": "2023-05-24T16:03:28.827Z"
  }
}
```

So client side, I am always first fetching fresh session object before modifying just one unrelated field, and the client SDK sends only this one unrelated field.

If I now stop/start the app again, and check what the fresh fetch returns:

```
verbose: RESPONSE from [GET] /parse/sessions/me: {
  "response": {
    "objectId": "XXX",
    "sessionToken": "XXX",
    "user": {
      "__type": "Pointer",
      "className": "_User",
      "objectId": "XXX"
    },
    "createdWith": {
      "action": "signup",
      "authProvider": "password"
    },
    "expiresAt": {
      "__type": "Date",
      "iso": "2024-05-23T15:39:28.827Z"
    },
    "installationId": "XXX",
    "createdAt": "2023-05-24T15:39:28.827Z",
    "updatedAt": "2023-05-24T16:03:28.827Z",
    "lastUsedAt": {
      "__type": "Date",
      "iso": "2023-05-24T16:03:28.701Z"
    }
  }
} 
```

I can see that the `lastUsedAt`, and `_updated_at` fields are matching the latest update, yet expiresAt remains the same as originally created. As if it was never actually extended.

Not sure what to look for next. Perhaps I am missing something... thanks for your help,
Martin

**Comment by dblythy** [comment]
`updatedAt` has to be unmodified for over 1 day for the session to be extended - I did this so the sessions wouldn't continuously be written to. So if you are manually writing to the session object (or the session has been created in under a day), it won't trigger the extension.

**Comment by mtrezza** [comment]
Closing this as designed behavior.

**Comment by mman** [comment]
Thanks @dblythy for the explanation. I will take that into account. On my side it was in the end implemented to get similar behaviour anyway, so I can migrate away from it...

thanks,
Martin

**Comment by dblythy** [comment]
Thanks for trying out the alpha branch! 😊
