### ISSUE TITLE
CI definitions check flaky

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-server#8579]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description

Definitions check in CI seems to be flaky.

### Steps to reproduce

- Failed: https://github.com/parse-community/parse-server/actions/runs/5079395697/attempts/1
- Passed: https://github.com/parse-community/parse-server/actions/runs/5079395697/attempts/2

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.1.0-alpha.17](https://github.com/parse-community/parse-server/releases/tag/6.1.0-alpha.17)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.3.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/6.3.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.3.0-alpha.1](https://github.com/parse-community/parse-server/releases/tag/6.3.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.3.0](https://github.com/parse-community/parse-server/releases/tag/6.3.0)
