### ISSUE TITLE
Master key is not working with masterKeyIps: ["0.0.0.0/0", "::1"]

### ISSUE THREAD

**Issue by andreisucman** [parse-community/parse-server#8582]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description

I built my server initially a few months ago and today deleted the lock file and node modules. After I reinstalled it I got the masterKeyIps error, which I resolved by adding masterKeyIps: ["0.0.0.0/0", "::1"] to my server config. 

But even though the error was gone the masterKey stopped working.

I have all write permissions turned off on CLP level, so everything is done via cloud functions that use masterKey. The strange part is that there are no errors, just the save operation is not working.

I found the old lock file and rebuilt the node modules from it and now it's working normally with the old lock file.

### Steps to reproduce

Turn off the write permissions for a class on CLP level. Add the masterKeyIps: ["0.0.0.0/0", "::1"]  to server config. Try changing something in the class using cloud functions with master key. e.g.` object.save(null, { useMasterKey: true});`

### Actual Outcome

The save operation doesn't work.

### Expected Outcome

The save operation should've worked as I'm using master key and the IP range is specified as any.
### Environment

localhost as well as remote server

Server
- Parse Server version: `^6.0.0`
- Operating system: `Win x64 Pro`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `localhost and remote`

Database
- System (MongoDB or Postgres): `Mongo`
- Database version: `5.015`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `remote managed DO`

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): `JS`
- SDK version: `^4.0.1`

**Comment by mtrezza** [comment]
Please be specific with versions, don't use "latest" or semver ranges like "~x.y.z" or "^x.y.z".  Please try the replicate the issue with the latest alpha version of Parse Server.

Closing as likely duplicate of https://github.com/parse-community/parse-server/issues/8421, if the PR for that issue doesn't fix this issue, we can reopen it.

**Comment by andreisucman** [comment]
The problem is present both in alpha 14 and Moumuls PR.

Here is how I included them:

```
"dependencies" : {
     "parse-server": "6.1.0-alpha.14",
}
```

and ran `npm i`

and then,
```
"dependencies" : {
    "parse-server": "git+https://github.com/Moumouls/parse-server.git#moumouls/fix-ip-address",
}
```

In both versions the function successfully completes. But the save operation doesn't save the result.

Here is the log:

`info: Ran cloud function changeName for user cIieBCUOKh with:
  Input: {"name":"Kathy Watson"}
  Result: {"sts":true} {"functionName":"changeName","params":{"name":"Kathy Watson"},"user":"cIieBCUOKh"}
`
And here is how I defined the function:

```
Parse.Cloud.define("changeName", async (req) => {
    const { name } = req.params;

/* change name for the user */
      const rUser = await new Parse.Query(Parse.User)
        .equalTo("objectId", req.user.id)
        .select("name")
        .first({ useMasterKey: true });

      const oldName = rUser.get("name");

      if (!rUser) return;

      if (name.length < 4) return;

      rUser.set("name", name);
      await rUser.save(null, {
        useMasterKey: true,
      });
return: {sts: true}
});
```

And this is how I call it from frontend: 

```
Parse.initialize(process.env.NEXT_PUBLIC_APP_ID);
Parse.serverURL = `${process.env.NEXT_PUBLIC_SERVER_URL}/parse`;

const response = await Parse.Cloud.run("changeName", { name });
```

And here are the allowed ips:

 `masterKeyIps: ["0.0.0.0/0", "::1"],`

**Comment by mtrezza** [comment]
Then I suggest to comment on the open PR since it's not merged yet and is undergoing review. The issue seems to be similar to what the PR is trying to fix, right?
