### ISSUE TITLE
Fix flaky Postgres tests

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-server#8613]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description

The flaky Postgres tests are currently the most significant bottleneck when it comes to merging PRs:

- More reviewer effort required to restart failing tests
- Longer wait time for contributors to see PRs getting merged
- Increased resource costs (GitHub Action compute time)

While there were other CI/CD related bottlenecks in the past, they have largely been removed over time so that this issue became now the most impactful one.

### Solution

Fix the flakiness.

**Comment by mtrezza** [comment]
@dplewis not sure if that helps with fixing the flaky tests for Postgres, but since we disabled test randomization, there seems to be a recurring pattern of Postgres failing exactly like this: https://github.com/parse-community/parse-server/actions/runs/9973005229/job/27557477165?pr=9209

**Comment by dplewis** [comment]
Is this for a specific Postgres version? Can I pick up this bounty?

**Comment by mtrezza** [comment]
I believe I have seen the issue always occurring for the same Postgres version since we disabled the test randomization.

The issue has been created for all flaky tests that are specific to Postgres, but I'm unsure how vast that is, now that the randomizer is off. I guess if you could fix the flaky test from the log above we can close this issue and pay out the bounty, as w/o randomizer it seems to be the only flaky test.

**Comment by dplewis** [comment]
This test has always been flaky since the introduction of transactions. I would have fixed it years ago if I knew how it worked. Probably @davimacedo knows how to fix it. Also this isn't postgres specific either this can fail for mongo as well.

<img width="524" alt="Screenshot 2024-07-16 at 6 13 13 PM" src="https://github.com/user-attachments/assets/00097772-a866-481e-95d6-5fe2c3129873">

**Comment by mtrezza** [comment]
Interestingly, since we disabled the randomizer it seems to be only that specific Postgres version where it fails.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.3.0-alpha.3](https://github.com/parse-community/parse-server/releases/tag/7.3.0-alpha.3)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.3.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/7.3.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.3.0](https://github.com/parse-community/parse-server/releases/tag/7.3.0)
