### ISSUE TITLE
Rate Limit with `redisURL` can fail if socket is already opened

### ISSUE THREAD

**Issue by dblythy** [parse-community/parse-server#8631]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description

When using a RedisURL in rateLimit, the error "socket is already opened" seems to occur when used when clustered.

### Steps to reproduce

Create a Parse Server with clusters and a rate limit

### Environment

Server
- Parse Server version: `alpha`

Database
- System (MongoDB or Postgres): `mongo`

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.1.0-alpha.3](https://github.com/parse-community/parse-server/releases/tag/7.1.0-alpha.3)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.1.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/7.1.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.1.0](https://github.com/parse-community/parse-server/releases/tag/7.1.0)
