### ISSUE TITLE
Add option to convert `Parse.Pointer` in Cloud Function payload

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-server#8634]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description

https://github.com/parse-community/parse-server/pull/8490 was actually a breaking change because it changes the payload in Cloud Functions in a way that a Parse Pointer JSON is converted to a Parse.Pointer instance in the payload, instead of being just a POJO as it used to be previously. 

### Solution

Add a new Parse Server option that determines whether a pointer should be a POJO (by default), or converted to a `Parse.Pointer` instance.

Since #8490 is already in beta, and for simplicity, we'll need a `refactor` PR for both the `alpha` and `beta` branch.

### Environment

Server
- Parse Server version: `6.3.0-beta.1`

### References

- https://github.com/parse-community/parse-dashboard/pull/2409#issuecomment-1586177916

**Comment by mtrezza** [comment]
This PR blocks the stable release pipeline of Parse Server; it fixes a breaking change that has been introduced by mistake.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.3.0-alpha.3](https://github.com/parse-community/parse-server/releases/tag/6.3.0-alpha.3)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.4.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/6.4.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.4.0-alpha.1](https://github.com/parse-community/parse-server/releases/tag/6.4.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.4.0](https://github.com/parse-community/parse-server/releases/tag/6.4.0)
