### ISSUE TITLE
Allow extension of `FeaturesRouter`

### ISSUE THREAD

**Issue by dblythy** [parse-community/parse-server#8678]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation

Currently, the `FeaturesRouter` tells the dashboard which features are available or not. However, it does not currently check if `securityChecks` are enabled, if there's a `push` adapter, etc.

### Feature / Enhancement Description

`FeaturesRouter` should be extended

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.1.0-alpha.2](https://github.com/parse-community/parse-server/releases/tag/7.1.0-alpha.2)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.1.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/7.1.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.1.0](https://github.com/parse-community/parse-server/releases/tag/7.1.0)
