### ISSUE TITLE
Update Parse Server Configuration link in ReadMe

### ISSUE THREAD

**Issue by dplewis** [parse-community/parse-server#8712]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description

Since there isn't a master branch anymore being updated the link isn't redirected to the latest api reference. Similar to https://github.com/parse-community/parse-server/issues/8685

### Steps to reproduce

Click the link [here](https://github.com/parse-community/parse-server/blob/9ed42d7fb52c76a7f91998475de4f31b618bfcb7/README.md?plain=1#L311)

### Actual Outcome

Redirects to old docs

### Expected Outcome

Redirects to https://parseplatform.org/parse-server/api/BRANCH_NAME/ParseServerOptions.html

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.3.0-alpha.2](https://github.com/parse-community/parse-server/releases/tag/7.3.0-alpha.2)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.3.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/7.3.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.3.0](https://github.com/parse-community/parse-server/releases/tag/7.3.0)
