### ISSUE TITLE
Add MongoDB 7 compatbility

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-server#8713]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation

MongoDB 7 has been released.

### Feature / Enhancement Description

Add Parse Server compatibility for MongoDB 7.

**Comment by abhisheksharma010** [comment]
Can this issue assign to me . I want to work on this

**Comment by mtrezza** [comment]
Thanks for your interest, there is an existing PR linked above. Please feel free to look at the open questions there to complete it

**Comment by magnacartatron** [comment]
@mtrezza We've been running on of the production servers on Mongo 7 since August without any issues.
I don't see any breaking changes in the Release Notes, it's mostly enhancements and some fixes.

**Comment by mtrezza** [comment]
@magnacartatron Good to know, please let us know if you discover any compatibility issues. However this is really specific to your app. There may be Parse Server features that your app doesn't use and they may not work with MongoDB 7. You could follow https://github.com/parse-community/parse-server/pull/8761 to see the current state of compatibility check.
