### ISSUE TITLE
Switch from Yoga v2 to Apollo V4

### ISSUE THREAD

**Issue by Moumouls** [parse-community/parse-server#8728]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation

Yoga V4 is currently not suitable for prod. I encountered issues on upload feature, and types issues in a monorepo.

### Feature / Enhancement Description

Use the last version of Apollo Server. It could also help in the futur to get some extra features for developers using apollo client.

### Example Use Case

More details on the linked PR

### Alternatives / Workarounds

None

### 3rd Party References

https://www.apollographql.com/

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.0.0-alpha.20](https://github.com/parse-community/parse-server/releases/tag/7.0.0-alpha.20)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.0.0-alpha.22](https://github.com/parse-community/parse-server/releases/tag/7.0.0-alpha.22)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/7.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.0.0](https://github.com/parse-community/parse-server/releases/tag/7.0.0)
