### ISSUE TITLE
Unable to determine whether beforeFind is from a Get or a Find (5.5.5 and 6.2.2)

### ISSUE THREAD

**Issue by m12331** [parse-community/parse-server#8736]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description
In latest releases (5.5.5 and 6.2.2) we seem to be unable to determine whether beforeFind is from a Get or a Find. These recent patches ensure that beforeFind is ran for both Find and Get, but there does not seem to be any way to make this distinction? This may break some implementations that relied on such distinction.

### Steps to reproduce
Construct a query on Class A with a Parse Pointer relationship to Class B. Log req.isGet inside beforeFind of Class B and observe req.isGet is false

### Actual Outcome
[req.isGet](https://parseplatform.org/parse-server/api/master/Parse.Cloud.BeforeFindRequest.html) inside beforeFind seems to return false regardless of whether beforeFind is from a Get or a Find 

### Expected Outcome
req.isGet to be true in the log described above or an alternative way to make this distinction?

Server
- Parse Server version: `5.5.5 and 6.2.2`

**Comment by mtrezza** [comment]
cc @Moumouls

**Comment by mtrezza** [comment]
Was it possible to distinguish that before the patch? If yes, how?

**Comment by m12331** [comment]
I believe this was possible with `isGet` before https://parseplatform.org/parse-server/api/master/Parse.Cloud.BeforeFindRequest.html

**Comment by mtrezza** [comment]
There are existing tests for this, but I've added 2 more concrete tests in #8738, let's see whether they fail. Please let me know in case the tests do not represent the scenario you are describing in this issue.

**Comment by mtrezza** [comment]
> unable to determine whether beforeFind is from a Get or a Find

To clarify, `Parse.Query.get` and `Parse.Query.find`  both execute with a HTTP GET request, so I'm assuming you are talking about `Parse.Query` methods. As you can see in https://github.com/parse-community/parse-server/pull/8738#issue-1880685262, such a distinction was also not possible in 6.2.1. The only distinction is between a `Parse.Query.get/find` and a `Parse.Object.fetch`. That is what `isGet` seems to indicate. I think that could certainly be improved in the docs.

If you have a different experience where you were able to distinguish between `Parse.Query.get` and `Parse.Query.find` via the `isGet` parameter, please provide more context and code examples.

**Comment by m12331** [comment]
Looks like you're right and I was off here. Thanks for the clarification

**Comment by mtrezza** [comment]
Do you want to open a PR to clarify this in the API docs? It's quite a simple PR.

**Comment by m12331** [comment]
I would need some time on that, but should be able to get to it eventually

**Comment by mtrezza** [comment]
That would be great, we've put some time into researching this issue, so it would surely be helpful to document it.
