### ISSUE TITLE
Add Node 20 compatibility

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-server#8743]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation

Node 20 is the current Node.js version.

### Feature / Enhancement Description

Add support for Node 20.

**Comment by funkenstrahlen** [comment]
Are there already any specific known tasks to do to add node 20 support?

**Comment by mtrezza** [comment]
You could take a look at https://github.com/parse-community/parse-server/pull/7707 and open a PR where you only add Node 20 to the the ci.yml file and the README.md. We'll then run the CI to see whether it passes. If it requires more code changes then we could add a bounty to it.

**Comment by mtrezza** [comment]
Closed via https://github.com/parse-community/parse-server/pull/8907
