### ISSUE TITLE
File Upload uses first period to determine extension

### ISSUE THREAD

**Issue by marcderhammer** [parse-community/parse-server#8753]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description

Uploading file names that contain periods before the extension causes the file extension validation to fail.  For example, I can upload some file like `file.png.html` which should be blocked, but the extension is detected as `.png`.

### Steps to reproduce

1. Upload a file called `file.png.html`
2. File uploads successfully but should have been stopped

### Actual Outcome

File upload success

### Expected Outcome

Request should have been rejected for `File upload of extension html is disabled`

### Environment

Server
- Parse Server version: `6.2.2`
- Operating system: `MacOS`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `Local`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `4.4`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `Local`

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): `Android`
- SDK version: `4.2.0`

### Logs

Instead of first index of `.`, should it check for last index of `.` in the [FilesRouter.js](https://github.com/parse-community/parse-server/blob/05939858af2ff830bffad1e58a6e09673267f3de/src/Routers/FilesRouter.js#L158) ?

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.4.0-alpha.3](https://github.com/parse-community/parse-server/releases/tag/6.4.0-alpha.3)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.5.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/6.5.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.5.0-alpha.1](https://github.com/parse-community/parse-server/releases/tag/6.5.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.5.0](https://github.com/parse-community/parse-server/releases/tag/6.5.0)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.0.0](https://github.com/parse-community/parse-server/releases/tag/7.0.0)
