### ISSUE TITLE
Officially support for MySQL Database in parse-server

### ISSUE THREAD

**Issue by mohammeddarwish0** [parse-community/parse-server#8775]
I think it's very important to add "MySQL" Adapter in parse-server
previously @dplewis added an adapter for MySQL Database, but, it's not working probably.
Most hostings providers support MySQL Database only...

**Comment by mtrezza** [comment]
The larger issue with supporting more DB adapters in Parse Server is that every new adapter currently effectively needs to be built into the Parse Server core codebase for maintainability. This adds unnecessary baggage for developers who don't use the adapter and makes it difficult to develop adapters in separate repositories. The first step to make this easier is https://github.com/parse-community/parse-server/issues/8714, which is nearing completion.

**Comment by dplewis** [comment]
@mohammeddarwish0 Ideas were brought up in https://github.com/parse-community/parse-server/issues/8714 that will make running MySQL against the test suite easier. I'll clean the project up and offer it to the community.

**Comment by mohammeddarwish0** [comment]
Ok 👍👍
