### ISSUE TITLE
Add `$setOnInsert` operator to `Parse.Server.database.update`

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-server#8792]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation

When using the Parse Server DB adapter directly (as exposed in Cloud Code via `Parse.Server.database`) the operator [$setOnInsert](https://www.mongodb.com/docs/v4.4/reference/operator/update/setOnInsert/) is not supported for upsert operations via Parse Server's `upsertOneObject`.

### Feature / Enhancement Description

Add support for `$setOnInsert`.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.4.0-alpha.7](https://github.com/parse-community/parse-server/releases/tag/6.4.0-alpha.7)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.6.0](https://github.com/parse-community/parse-server/releases/tag/5.6.0)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.5.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/6.5.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.5.0-alpha.1](https://github.com/parse-community/parse-server/releases/tag/6.5.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.5.0](https://github.com/parse-community/parse-server/releases/tag/6.5.0)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.0.0](https://github.com/parse-community/parse-server/releases/tag/7.0.0)
