### ISSUE TITLE
[Live Query] `matchesKeyConstraints` throwing error when `constraints` is `{$ne : null}`

### ISSUE THREAD

**Issue by RahulLanjewar93** [parse-community/parse-server#8834]
### New Issue Checklist

- [ x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [ x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [ x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [ x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description
matchesKeyConstraints function is not handling not equal to null constraint properly. 
Due to which error is thrown `Cannot read properties of null (reading '__type')

<img width="592" alt="image" src="https://github.com/parse-community/parse-server/assets/63550998/cffefdac-7373-4372-96bc-ee60a5808ac6">

### Steps to reproduce
Create a subscription on a class with constraint `notEqualTo(key,null)`

### Actual Outcome
Throws error.

### Expected Outcome
Shouldn't throw an error.

### Environment
18.19.0

Server
- Parse Server version: `5.5.5`
- Operating system: `Mac`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `self hosted`

Database
- System (MongoDB or Postgres): `Mongo`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `Local`

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): `Javascript`
- SDK version: `4.0.1`

**Comment by RahulLanjewar93** [comment]
@mtrezza i think we need some changes in the code block

QueryTools.js > matchesKeyConstraints 

<img width="469" alt="image" src="https://github.com/parse-community/parse-server/assets/63550998/c07d1b5b-bb36-4e57-a72d-7d57dbf0b74e">


here we need to check if compareTo is not null/undefined

**Comment by RahulLanjewar93** [comment]
@mtrezza  please have a look

**Comment by mtrezza** [comment]
Will this issue be fixed by https://github.com/parse-community/Parse-SDK-JS/pull/2102 once the Parse SDK is upgraded in Parse Server? @dplewis

**Comment by dplewis** [comment]
@mtrezza Thats a fix for the Local Datastore this issue is for LiveQuery. The query engines for both are almost the same. You can basically copy the fix over to Parse Server and it should work for Live Query.

**Comment by mtrezza** [comment]
@RahulLanjewar93 do you want to give it a try?

**Comment by RahulLanjewar93** [comment]
> @RahulLanjewar93 do you want to give it a try?

sure!

**Comment by RahulLanjewar93** [comment]
> @RahulLanjewar93 do you want to give it a try?

added required change in #8835

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.1.0-alpha.10](https://github.com/parse-community/parse-server/releases/tag/7.1.0-alpha.10)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.1.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/7.1.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.1.0](https://github.com/parse-community/parse-server/releases/tag/7.1.0)
