### ISSUE TITLE
Remove deprecation DEPPS6: Auth providers disabled by default

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-server#8842]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Feature / Enhancement Description

Remove deprecation DEPPS6: Auth providers disabled by default

### References 

https://github.com/parse-community/parse-server/pull/7953

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.0.0-alpha.18](https://github.com/parse-community/parse-server/releases/tag/7.0.0-alpha.18)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/7.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.0.0](https://github.com/parse-community/parse-server/releases/tag/7.0.0)
