### ISSUE TITLE
Remove deprecation DEPPS8: Login with expired 3rd party authentication token defaults to `false`

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-server#8844]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Feature / Enhancement Description

Remove deprecation DEPPS8: Login with expired 3rd party authentication token defaults to `false`

### References 

https://github.com/parse-community/parse-server/pull/7079

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.0.0-alpha.17](https://github.com/parse-community/parse-server/releases/tag/7.0.0-alpha.17)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/7.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.0.0](https://github.com/parse-community/parse-server/releases/tag/7.0.0)
