### ISSUE TITLE
Config upgrade faiing for account lockout functionality

### ISSUE THREAD

**Issue by praharsha123** [parse-community/parse-server#8856]
### New Issue Checklist

- [ ] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [ ] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [ ] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [ ] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description

 I am trying to enable account lockout functionality for parse dashboard 

### Steps to reproduce

we create a file name as parse-server as below and started the docker container 

The container started successfully but when we tried to test functionality (attempted three login failure attempts but don't see any response logs)
docker run --name my-parse-server -v /home/ubuntu/datapond/parse-server/parse-server-config.json:/parse-server/parse-server-config.json -p 1337:1337 --link my-mongo:mongo -d parse-server --appId MyParseApp --databaseURI mongodb://mongo/test   

--------
ubuntu@ip-xxxxxxxx:~/datapond/parse-server$ cat parse-server-config.json
const server = ParseServer({

  // The account lock policy
  accountLockout: {
    // Lock the account for 5 minutes.
    duration: 5,
    // Lock an account after 3 failed log-in attempts
    threshold: 3,
    // Unlock the account after a successful password reset
    unlockOnPasswordReset: true,
  },

  // The password policy
  passwordPolicy: {
    // Enforce a password of at least 8 characters which contain at least 1 lower case, 1 upper case and 1 digit
    validatorPattern: /^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.{8,})/,
    // Do not allow the username as part of the password
    doNotAllowUsername: true,
    // Do not allow to re-use the last 5 passwords when setting a new password
    maxPasswordHistory: 5,
  },
});
---------------
### Environment

Server
- Parse Server version: `FILL_THIS_OUT`
- Operating system: `FILL_THIS_OUT`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `FILL_THIS_OUT`

Database
- System (MongoDB or Postgres): `FILL_THIS_OUT`
- Database version: `FILL_THIS_OUT`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `FILL_THIS_OUT`

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): `FILL_THIS_OUT`
- SDK version: `FILL_THIS_OUT`

**Comment by praharsha123** [comment]
lets us know if the config we enabled  in a right way and suggest me if there is any work around

**Comment by mtrezza** [comment]
You wrote "I am trying to enable account lockout functionality for parse dashboard" but this is the Parse Server repo. What exactly are you trying to achieve? If this is related to Parse Server, and not Parse Dashboard, then please provide a code example that demonstrates the issue.

**Comment by mtrezza** [comment]
Closing as there hasn't been any clarification on this issue.

**Comment by praharsha123** [comment]
<img width="739" alt="image" src="https://github.com/parse-community/parse-server/assets/22877017/cdf21c6b-ff2a-40fe-8c01-e753c025ad78">

**Comment by praharsha123** [comment]
I am following this --> https://github.com/parse-community/parse-dashboard


please let me know at which location of the code where I need to make changes to enable the account lockout funcationality
