### ISSUE TITLE
Cannot pass Parse pointers inside arrays to cloud functions

### ISSUE THREAD

**Issue by mstniy** [parse-community/parse-server#8861]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description
Parse server rejects cloud function calls which include Parse pointers inside arrays

### Steps to reproduce
```
Parse.Cloud.define("test", function () {});
// Later
await Parse.Cloud.run("test", {
  a:[{__type: "Pointer", className:"foo", objectId: "foo" }]
});
```

### Actual Outcome
Parse server returns an internal server error

### Expected Outcome
The cloud function should run
### Environment

Server
- Parse Server version: `6.4.0`
- Operating system: `Ubuntu`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `local`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `6.0.12`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `local`

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): `javascript`
- SDK version: `4.3.1`

**Comment by mtrezza** [comment]
Not sure whether this is supposed to be supported and documented anywhere; if it is then we can reclassify this as a bug.

**Comment by mstniy** [comment]
Duplicate of #8783
