### ISSUE TITLE
Add official MongoDB 7 compatibility

### ISSUE THREAD

**Issue by MobileVet** [parse-community/parse-server#8882]
### New Feature / Enhancement Checklist
- [X ] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [X ] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [X ] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation
Current Parse Server support identifies MongoDB 6 as the latest supported version.  MongoDB 7 has been out for a while and all new lower tier instances hosted by MongoDB will be updated in February.  As such, we should ensure Parse supports this upcoming release.

### 3rd Party References
[MongoDB 7 Migration](https://www.mongodb.com/docs/manual/release-notes/7.0-compatibility/)

**Comment by mtrezza** [comment]
Parse Server 7 will be compatible, see https://github.com/parse-community/parse-server/issues/8713
