### ISSUE TITLE
Parse Server option `emailVerifyTokenReuseIfValid: true` generates new token on every email verification request

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-server#8886]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description

The Parse Server option `emailVerifyTokenReuseIfValid: true` generates a new token on every email verification request. This bug was likely introduced with https://github.com/parse-community/parse-server/pull/8212 where using the `masterKey` does not provide read access to fields of internal scope, in this case `_email_verify_token`, `_email_verify_token_expires_at`.

The bug has not been noticed due to a weak test case which compares the previous to the new token, but does not check whether a token and expiry date is defined at all; since these fields are not returned anymore by the `masterKey`, the test is comparing `undefined` values and passes, even if these values have changed in the DB.

https://github.com/parse-community/parse-server/blob/4aba66c620cb60fc379090be3ebf180782579ba0/spec/EmailVerificationToken.spec.js#L928-L933

### Steps to reproduce

See failing test in https://github.com/parse-community/parse-server/pull/8885.

### Actual Outcome

Token and expiry date are modified.

### Expected Outcome

Token and expiry date are not modified.

### Environment

Server
- Parse Server version: `7.0.0-alpha.5`

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.0.0-alpha.6](https://github.com/parse-community/parse-server/releases/tag/7.0.0-alpha.6)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/7.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.0.0](https://github.com/parse-community/parse-server/releases/tag/7.0.0)
