### ISSUE TITLE
Username is `undefined` in email verification link on email change

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-server#8888]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description

The email verification link is broken due to the value `username=undefined` within the link. This occurs when changing the email address of a user.

### Steps to reproduce

See test in #8887.

### Actual Outcome

Username is undefined in link. 

### Expected Outcome

Username should be defined.

### Environment

Server
- Parse Server version: `7.0.0-alpha.6`

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.0.0-alpha.7](https://github.com/parse-community/parse-server/releases/tag/7.0.0-alpha.7)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/7.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.0.0](https://github.com/parse-community/parse-server/releases/tag/7.0.0)
