### ISSUE TITLE
Incomplete user object in `verifyEmail` function if both username and email are changed

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-server#8890]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description

Incomplete user object in `verifyEmail` function if both username and email are changed. The user object appears as if it was unsaved, without `objectId`, `createdAt` and other fields being set. This issue does not occur if only the email address or only the username are changed. This was not an issue before the introduction of conditional email verification, but that feature requires the full user object to be made available to the developer.

### Steps to reproduce

See failing test in #8889.

### Actual Outcome

User object appears as if it was unsaved and is missing fields.

### Expected Outcome

Complete user object should be passed to `verifyEmail` function.

### Environment

Server
- Parse Server version: `7.0.0-alpha.7`

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.0.0-alpha.8](https://github.com/parse-community/parse-server/releases/tag/7.0.0-alpha.8)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/7.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.0.0](https://github.com/parse-community/parse-server/releases/tag/7.0.0)
