### ISSUE TITLE
ERR_UNSUPPORTED_ESM_URL_SCHEME

### ISSUE THREAD

**Issue by anda88** [parse-community/parse-server#8897]
node -v
18.18.2
npm start 启动程序时发生 ERR_UNSUPPORTED_ESM_URL_SCHEME错误
原因：
这个错误表明你在使用 ESM（ECMAScript 模块）时，尝试导入一个不支持的 URL 方案。
错误发生在 const config = {
     cloud: './cloud/main.js'
}
解决办法：
方法一：改成函数形式
const config = {
    // cloud: './cloud/main.js',
    cloud: () => import('./cloud/main.js')
}
方法二：在\node_modules\parse-server\lib\ParseServer.js:143
 if (process.env.npm_package_type === 'module' || ((_json = json) === null || _json === void 0 ? void 0 : _json.type) === 'module') {
            await import(path.resolve(process.cwd(), cloud));
          } 
  改成：await import('file://'+path.resolve(process.cwd(), cloud));

另外还有一个问题，process.env.npm_package_type 为undefined，所以用解决方法二时，还要增加process.env.npm_package_type = 'module';（虽然，我的package.json加入了type，但是env中还是获取不到  ）

**Comment by anda88** [comment]
![1705823481479](https://github.com/parse-community/parse-server/assets/39217448/f48df258-d52d-4a5a-aab0-5fbf0d22b722)

**Comment by mtrezza** [comment]
I'm closing this as it lacks essential information. Please edit your question using the issue template and we can re-open this issue.
