### ISSUE TITLE
Formally support node 20 and 21

### ISSUE THREAD

**Issue by cbaker6** [parse-community/parse-server#8908]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation

Node 20 and 21 are not tested in the CI. In addition, node versions 14, 15, and 19 are no longer supported by node

### Feature / Enhancement Description

Add support for node 20 and 21

### Example Use Case

Use parse on latest node.

### Alternatives / Workarounds

Devs run and test on their own.

### 3rd Party References

https://nodejs.org/en/about/previous-releases

**Comment by mtrezza** [comment]
See https://github.com/parse-community/parse-server/pull/8907#issuecomment-1944376020 for why Node 21 is not supported.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.0.0-alpha.12](https://github.com/parse-community/parse-server/releases/tag/7.0.0-alpha.12)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/7.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.0.0](https://github.com/parse-community/parse-server/releases/tag/7.0.0)
