### ISSUE TITLE
required field on Parse Schema is not handled correctly on special types on the GQL API

### ISSUE THREAD

**Issue by Moumouls** [parse-community/parse-server#8914]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description

When a special field like File is required on the Parse Schema, mutations fails because the GQL type is wrapped by a GraphQL Non Null type.

### Steps to reproduce

Add a "required: true" to a special field like a field with a type "File", and attempt a mutation

### Actual Outcome

Mutation fails, Parse fail to recognize correctly the special field.

### Environment

Server
- Parse Server version: `7.0.0`
- Operating system: `MacOS`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `Local`

Database
- System (MongoDB or Postgres): `Mongo`
- Database version: `6.0.2`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `FILL_THIS_OUT`

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): `FILL_THIS_OUT`
- SDK version: `FILL_THIS_OUT`

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.0.0-alpha.30](https://github.com/parse-community/parse-server/releases/tag/7.0.0-alpha.30)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.1.0-alpha.1](https://github.com/parse-community/parse-server/releases/tag/7.1.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.1.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/7.1.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.1.0](https://github.com/parse-community/parse-server/releases/tag/7.1.0)
