### ISSUE TITLE
Log a warning in case of a unknown options

### ISSUE THREAD

**Issue by EhsanParsania** [parse-community/parse-server#8938]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation
When we pass a wrong option in Parse config it doesn't make a warning, 

### Feature / Enhancement Description
There should be a validation or list of giving options to prevent such mistakes with a warning.

### Example Use Case
for instance in the Parse config I had a typo like:
`masterKeyIPs` which was the correct form was `masterKeyIps` and it took time to find out why I got error.

**Comment by vivekjoshi556** [comment]
@mtrezza Can I try this issue?

**Comment by mtrezza** [comment]
Sure, please go ahead

**Comment by mtrezza** [comment]
Related: https://github.com/parse-community/parse-server/issues/7069

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.1.0-alpha.5](https://github.com/parse-community/parse-server/releases/tag/7.1.0-alpha.5)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.1.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/7.1.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.1.0](https://github.com/parse-community/parse-server/releases/tag/7.1.0)
