### ISSUE TITLE
How about add beforeUpdate, afterUpdate

### ISSUE THREAD

**Issue by badboy-tian** [parse-community/parse-server#8954]
### New Feature / Enhancement Checklist

- [ ] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [ ] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [ √] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation

spreate beforeSave and beforeUpdate
### Feature / Enhancement Description

spreate beforeSave and beforeUpdate
### Example Use Case

```
Parse.Cloud.beforeSave('CommentTie)

if(request.object.createdAt){
     beforeUpdate(updatedKeys)
}else{
   beforeSave()
}

we can handle object updatedKeys
```

**Comment by badboy-tian** [comment]
```
Parse.Cloud.afterSave('CommentTie)

if(request.object.createdAt !== request.object.updatedAt){
     afterUpdate(updatedKeys)
}else{
   afterSave()
}
```

**Comment by mtrezza** [comment]
You can already determine in the beforeSave trigger whether it's an update or creation operation.

Closing as there is a feature that already addresses this request.
