### ISSUE TITLE
Migrate to the latest Firebase Cloud Messaging API (HTTP v1) 

### ISSUE THREAD

**Issue by pcg92** [parse-community/parse-server#8956]
I'm in the process of setting up the server for Firebase push notifications, but I noticed that the API doesn't seem to have been migrated to the new version. Can you confirm if the migration has been completed, or am I mistaken?

<img width="958" alt="Screenshot 2024-02-27 at 09 18 35" src="https://github.com/parse-community/parse-server/assets/10808022/a9b9edcd-1b0b-410b-b0d0-349007e543c1">

https://firebase.google.com/docs/cloud-messaging/migrate-v1

**Comment by mtrezza** [comment]
In the works, see https://github.com/parse-community/parse-server-push-adapter/issues/219. 

Closing as this is a Push Adapter issue, not a Parse Server issue.
