### ISSUE TITLE
Latest releases are prereleases on GitHub page

### ISSUE THREAD

**Issue by cbaker6** [parse-community/parse-server#8988]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description

Versions 6.5.1 and 6.5.2 are listed as “prereleases” instead of actual releases. 

### Steps to reproduce

See https://github.com/parse-community/parse-server/releases

### Environment

Server
- Parse Server version: `FILL_THIS_OUT`
- Operating system: `FILL_THIS_OUT`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `FILL_THIS_OUT`

Database
- System (MongoDB or Postgres): `FILL_THIS_OUT`
- Database version: `FILL_THIS_OUT`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `FILL_THIS_OUT`

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): `FILL_THIS_OUT`
- SDK version: `FILL_THIS_OUT`

**Comment by mtrezza** [comment]
Closing via https://github.com/parse-community/parse-server/pull/8989; manually removed pre-release tags from GitHub releases

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.5.3](https://github.com/parse-community/parse-server/releases/tag/6.5.3)

**Comment by mtrezza** [comment]
This is an issue with semantic release; we expect this issue to be resolved after releasing Parse Server 7 on the `release` branch. 

- [ ] Update release config on `release-6.x.x` branch after PS7 release on `release` branch

**Comment by mtrezza** [comment]
Closing via https://github.com/parse-community/parse-server/pull/9035
