### ISSUE TITLE
Parse server crash - Cannot read property 'encodeParseObjectInCloudFunction' of undefined in PS6.x.x

### ISSUE THREAD

**Issue by jaysonng** [parse-community/parse-server#9010]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description

Parse server crash - Cannot read property 'encodeParseObjectInCloudFunction' of undefined

This issue is the same as https://github.com/parse-community/parse-server/issues/8783#issuecomment-1994944683 but the PR fix for that issue was only pushed to v7.

Opening this new issue for PR for v6

### Steps to reproduce

Same as https://github.com/parse-community/parse-server/issues/8783#issuecomment-1994944683

### Actual Outcome

Parse server crash - Cannot read property 'encodeParseObjectInCloudFunction' of undefined

### Expected Outcome

Not to crash

### Environment

Server
- Parse Server version: `6.5.2`
- Operating system: `Mac`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `local`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `6.0.0`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `Local`

**Comment by mtrezza** [comment]
Closing via https://github.com/parse-community/parse-server/pull/9012
