### ISSUE TITLE
Parse.Cloud.beforeLogin doesn't trigger the first time when linked with AuthData.

### ISSUE THREAD

**Issue by kyawswarthwin** [parse-community/parse-server#9050]
Parse.Cloud.beforeLogin doesn't trigger the first time when linked with AuthData.

**Comment by mtrezza** [comment]
Should it trigger at all? Linking may not be considered a login, but a user update event, which you could probably catch in the `beforeSave` trigger. The [docs](https://docs.parseplatform.org/cloudcode/guide/#considerations-1) say that it should run on an auth data login, which I understand must have the auth data already stored, so after the linking.

**Comment by mtrezza** [comment]
Closing as issue seems to be resolved.
