### ISSUE TITLE
Add support for Facebook auth JWT token

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-server#9117]
### New Feature / Enhancement Checklist

- Report security issues [confidentially](https://github.com/parse-community/parse-server/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/parse-server/blob/alpha/LICENSE).
- Before posting search [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation

Due to Apple's ATT requirements, the "normal" Facebook Login requires a user to allow app tracking.  For users who do not allow app tracking, Facebook Limited Login must be used instead, which uses JWT for authentication. Parse Server currently only supports the token provided by "normal" Facebook Login. It does not support the token generated by Limited Login.

This is an urgent issue, because:
- The majority of users does not allow app tracking, so developers must often fall back to Limited Login.
- The Facebook SDKs <= 16 are rejected by AppStore review because they lack the privacy manifest file. The Facebook SDK 17 automatically prohibits "normal" Login and requires Limited Login if the user has not allowed app tracking.

**That means that Parse Server (and possibly the Parse Apple SDK) currently do not support Facebook auth when submitting a new app or an app update to the AppStore with Facebook SDK 17.**

See https://github.com/parse-community/Parse-SDK-iOS-OSX/issues/1787

### Feature / Enhancement Description

Extend the Facebook auth adapter, so that it supports JWT auth from Facebook Limited Login. Ideally, no change will be required on the Parse Apple SDK side.

### Alternatives / Workarounds
Unknown.

### 3rd Party References

- https://github.com/facebook/facebook-ios-sdk/issues/2384#issuecomment-2080038284
- https://developers.facebook.com/docs/facebook-login/limited-login/

**Comment by mtrezza** [comment]
Note: The bounty scope includes https://github.com/parse-community/Parse-SDK-iOS-OSX/issues/1787.

**Comment by mtrezza** [comment]
For reference, here the PR that implemented FB limited login server side: https://github.com/parse-community/parse-server/pull/7219. It defined:

> Classic Graph API login (no change)
> ```Javascript
> {
>   id: "your_facebook_id",
>   access_token: "facebook_graph_api_access_token"
> }
> ```
> 
> Limited Login
> ```Javascript
> {
>   id: "your_facebook_id",
>   token: "openid_token"
> }
> ```

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.5.6](https://github.com/parse-community/parse-server/releases/tag/6.5.6)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.1.0-alpha.7](https://github.com/parse-community/parse-server/releases/tag/7.1.0-alpha.7)

**Comment by mtrezza** [comment]
For reference, FB published this related to "Limited Login" endpoints:

> Update the Facebook Login SDK to the most recent version and update any Limited Login endpoint domains within your application to the new Limited Login endpoint (as shown [here](https://developers.facebook.com/docs/facebook-login/limited-login/token)).

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.1.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/7.1.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.1.0](https://github.com/parse-community/parse-server/releases/tag/7.1.0)

**Comment by tran-huy-phuc** [comment]
For some reason, I can only use below structure for both Limited and Classic:
**(Parse server 7.2.0)**

```
{
  id: "your_facebook_id",
  token: "openid_token"
}
```

If I replace `token` by `access_token` in classic mode, it says:
```
Status Code: 101
Type: ObjectNotFound
Error: Facebook auth is invalid for this user.
```

**Comment by mtrezza** [comment]
@pdkcoder Could you please open a new issue for that and provide more details?

**Comment by mtrezza** [comment]
@pdkcoder Does it work for both classic and limited login?

**Comment by tran-huy-phuc** [comment]
Hi @mtrezza Yes it works for both

**Comment by mtrezza** [comment]
@pdkcoder Could you open a new issue and describe the issue in more detail with sample code?
