### ISSUE TITLE
Codecov not working

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-server#9129]
### New Issue Checklist

- Report security issues [confidentially](https://github.com/parse-community/parse-server/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/parse-server/blob/alpha/LICENSE).
- Before posting search [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Issue Description

Codecov doesn't work; nothing we can do ATM, see https://github.com/codecov/codecov-action/issues/1262. We'll consider this when reviewing failing workflows in PRs.

**Comment by cbaker6** [comment]
@mtrezza I recently fixed this in my repos. You should be able to do the same thing:

1. Goto Codecov and create a new global upload token https://docs.codecov.com/docs/the-codecov-cli#how-to-get-an-upload-token
2. Set the global token as a secret for the whole organization using `CODECOV_TOKEN` https://docs.github.com/en/codespaces/managing-codespaces-for-your-organization/managing-development-environment-secrets-for-your-repository-or-organization#adding-secrets-for-a-repository
3. Note, I had to also set the same `CODECOV_TOKEN`  in the organizations Dependabot secrets to allow bots to use the token or else the bots will fail when they create PRs, `Settings->Secrets and variables->Dependabot`
4. Delete any old `CODECOV_TOKEN`'s that's designated for individual repo settings , just let the global token be used

**Comment by mtrezza** [comment]
I believe I already did this. If you look at the CI file, you can see the org global token being set.

**Comment by mtrezza** [comment]
Seems to be working
