### ISSUE TITLE
Docker build is failing

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-server#9130]
### New Issue Checklist

- Report security issues [confidentially](https://github.com/parse-community/parse-server/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/parse-server/blob/alpha/LICENSE).
- Before posting search [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Issue Description

Docker build is failing.

### Steps to reproduce

See https://github.com/parse-community/parse-server/actions/runs/9116779407/job/25066654383?pr=9128

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.1.0-alpha.10](https://github.com/parse-community/parse-server/releases/tag/7.1.0-alpha.10)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.1.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/7.1.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.1.0](https://github.com/parse-community/parse-server/releases/tag/7.1.0)
