### ISSUE TITLE
Upgrade to Parse 5.1.0 fails

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-server#9131]
### New Issue Checklist

- Report security issues [confidentially](https://github.com/parse-community/parse-server/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/parse-server/blob/alpha/LICENSE).
- Before posting search [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Issue Description

CI fails for https://github.com/parse-community/parse-server/pull/9128. We cannot upgrade Parse Server to the latest Parse version.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.1.0-alpha.11](https://github.com/parse-community/parse-server/releases/tag/7.1.0-alpha.11)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.1.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/7.1.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.1.0](https://github.com/parse-community/parse-server/releases/tag/7.1.0)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.3.0-alpha.1](https://github.com/parse-community/parse-server/releases/tag/7.3.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.3.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/7.3.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.3.0](https://github.com/parse-community/parse-server/releases/tag/7.3.0)
