### ISSUE TITLE
How about add DefineOptions(internal?: boolean) in define Cloud function ?

### ISSUE THREAD

**Issue by badboy-tian** [parse-community/parse-server#9138]
### New Feature / Enhancement Checklist

- Report security issues [confidentially](https://github.com/parse-community/parse-server/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/parse-server/blob/alpha/LICENSE).
- Before posting search [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation

1. I want to define a cloud function, but it is only for internal use and cannot be called by clients.

### Feature / Enhancement Description

current define function
```
function define(
                name: string,
                func: (request: FunctionRequest) => any,
                validator?: Validator | ((request: FunctionRequest) => any),
            ): void;
```
and then add a DefineOptions
```
interface DefineOptions {
    internal?: boolean,
    //some else
  }

function define(
                name: string,
                func: (request: FunctionRequest) => any,
                 defineOptions: DefineOptions,
                validator?: Validator | ((request: FunctionRequest) => any),
            ): void;
```

### Example Use Case

```
Parse.Cloud.define("internalFunc", { internal: true }, (request)=>{} )
```
### Alternatives / Workarounds

no
### 3rd Party References

https://docs.leancloud.cn/en/sdk/engine/functions/guides/
![image](https://github.com/parse-community/parse-server/assets/2835129/72553fe6-a9dc-49ed-9d8a-c050c23a1745)

**Comment by mtrezza** [comment]
Could you please clarify the feature you are suggesting?

**Comment by badboy-tian** [comment]
for example:
I define a cloud function
```
Parse.Cloud.define("internalFunc", { internal: true, fetchUser:false }, (request)=>{} )
```
I call the function use parse clicent sdk, for example flutter sdk.  return "function not found".

when i call the function from express and parse-server, return normal result

**Comment by mtrezza** [comment]
Still don't understand it. What does this have to do with `fetchUser`?

**Comment by badboy-tian** [comment]
1. ```fetchUser?: boolean```: Whether to automatically fetch the user logged in on the client side. Defaults to true. When set to false, Request will not contain the currentUser property.

2. ```internal?: boolean```: Whether to only allow the function to be invoked within Cloud Function (with Parse.Cloud.run without enabling remote) or with the Master Key (by providing useMasterKey when calling Parse.Cloud.run). When set to true, the function cannot be invoked directly by the client. Defaults to false.

I'm just giving an example, it doesn't matter if ```fetchUser``` is used or not.  I just feel that ```internal: true``` is very useful. It allows the ```cloud function``` to be called ```only internally``` on the server, not on the client.

**Comment by mtrezza** [comment]
(1) requieres a different discussion than (2), so I'd keep this issue focused on one of the two. If you find (2) important then I suggest to focus on only that for now and adapt the issue title and description to make it easier for readers to follow this.
