### ISSUE TITLE
Can skip triggers

### ISSUE THREAD

**Issue by tiavina-mika** [parse-community/parse-server#9145]
### New Feature / Enhancement Checklist

- Report security issues [confidentially](https://github.com/parse-community/parse-server/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/parse-server/blob/alpha/LICENSE).
- Before posting search [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation

Actually, when saving (with `.save()`) something, that will trigger `afterSave `and `beforeSave`

### Feature / Enhancement Description

For example, I just want upate one field without firing `afterSave `and `beforeSave`

### Example Use Case

1. I have a collection named `Order`
2. the triggers have some dozen of conditions and calculation
3. It's resource intensive to run these calculation on every change
4. I want just to change the zipCode field for example

### Alternatives / Workarounds

Put conditions in the triggers if a function should be called

**Comment by mtrezza** [comment]
That's what `context` is for.
