### ISSUE TITLE
Object data type change from beforeSave to afterSave hook trigger

### ISSUE THREAD

**Issue by mkmandar123** [parse-community/parse-server#9176]
### New Issue Checklist

- Report security issues [confidentially](https://github.com/parse-community/parse-server/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/parse-server/blob/alpha/LICENSE).
- Before posting search [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Issue Description
Object field data type changes from json to array during beforeSave and afterSave hook triggers.

### Steps to reproduce
https://github.com/parse-community/parse-server/pull/9177

### Actual Outcome
data type of the field value is not same in beforeSave and afterSave hook. It changes from json object to array.

### Expected Outcome
data type of the field value should remain same in beforeSave and afterSave hook.

### Environment
ParseServer: 7.1.0 (7.0.0 no issue observed)

Server
- Parse Server version: `7.1.0`
- Operating system: `Ubuntu 20.04`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `Docker`

**Comment by mtrezza** [comment]
I believe this is a duplicate of https://github.com/parse-community/Parse-SDK-JS/issues/2198?

**Comment by mtrezza** [comment]
Test added in https://github.com/parse-community/parse-server/pull/9177
Fixed via https://github.com/parse-community/parse-server/pull/9180
Related tests in https://github.com/parse-community/parse-server/pull/9179

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.2.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/7.2.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.2.0](https://github.com/parse-community/parse-server/releases/tag/7.2.0)
