### ISSUE TITLE
CacheAdapter cannot be used in the configuration file with parse-server 6.x; fixed in 7.x; should be back ported to 6.x

### ISSUE THREAD

**Issue by evtimDev** [parse-community/parse-server#9204]
This is a follow-up for https://github.com/parse-community/parse-server/issues/8610, basically when started via config.json file, the RedisCacheAdapter will not connect on start.

The issue was fixed for parse-server 7.x here https://github.com/parse-community/parse-server/pull/8633

However, I think it should be back ported to 6.x. Encountered when upgrading client from 5.x to 6.x

Server
- Parse Server version: 6.x

**Comment by mtrezza** [comment]
Closing; according to our [LTS policy](https://github.com/parse-community/parse-server?tab=readme-ov-file#long-term-support), only critical security issues are backported. If you however feel like opening a PR for Parse Server 6, we'll be happy to review it. In that case the backport should be kept as close as possible to the original PR.
