### ISSUE TITLE
Postinstall script incorrectly parses required min. Node version

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-server#9214]
### New Issue Checklist

- Report security issues [confidentially](https://github.com/parse-community/parse-server/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/parse-server/blob/alpha/LICENSE).
- Before posting search [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Issue Description

The post install script makes the installation fail if the min. Node version in package.json is higher than the environment Node version. However, it regex-parses the `engine.node` value instead of properly semver-parsing it to properly handle any possible semver notation. 

https://github.com/parse-community/parse-server/blob/9282e348b0f6f696b41f637950abd7c393c2c1be/postinstall.js#L4

The current string is parsed incorrect so that the required min. Node version is 18.19:

https://github.com/parse-community/parse-server/blob/9282e348b0f6f696b41f637950abd7c393c2c1be/package.json#L141-L143

This also points to a larger issue with the Parse Server `engine.node` value, because only specifying the major version means that Parse Server is compatible with Node 18.0.0, which may not even be the case as it has never been tested with that exact version.

### Environment

Server
- Parse Server version: `7.2.0`

**Comment by dplewis** [comment]
I'd recommend removing the check altogether. npm will let developer's know which versions are supported.

**Comment by mtrezza** [comment]
I've changed this to use semver, but I think you are right, better to remove it

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.3.0-alpha.3](https://github.com/parse-community/parse-server/releases/tag/7.3.0-alpha.3)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.3.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/7.3.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.3.0](https://github.com/parse-community/parse-server/releases/tag/7.3.0)
