### ISSUE TITLE
Upgrade to mime 4

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-server#9250]
### New Feature / Enhancement Checklist

- Report security issues [confidentially](https://github.com/parse-community/parse-server/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/parse-server/blob/alpha/LICENSE).
- Before posting search [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Issue

Merge https://github.com/parse-community/parse-server/pull/9248

**Comment by Moumouls** [comment]
patched @mtrezza  !
