### ISSUE TITLE
Add support for async `FilesAdapter.getFileLocation`

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-server#9268]
### New Feature / Enhancement Checklist

- Report security issues [confidentially](https://github.com/parse-community/parse-server/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/parse-server/blob/alpha/LICENSE).
- Before posting search [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation

The `FilesAdapter` protocol expects `getFileLocation` to be a synchronous method.

### Feature / Enhancement Description

Add support for `getFileLocation` to be either an asynchronous or synchronous method:
- Support for asynchronous is required for file adapters that generate the file URI asynchronously, for example the S3 file adapter using a pre-signed URL, see https://github.com/parse-community/parse-server-s3-adapter/issues/197.
- Support for synchronous is required for backward compatibility. 

### Example Use Case

See https://github.com/parse-community/parse-server-s3-adapter/issues/197.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.3.0-alpha.7](https://github.com/parse-community/parse-server/releases/tag/7.3.0-alpha.7)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.3.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/7.3.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.3.0](https://github.com/parse-community/parse-server/releases/tag/7.3.0)
