### ISSUE TITLE
Cannot find method onLiveQueryEvent in Parse.Cloud typescript

### ISSUE THREAD

**Issue by WidiNetkrom** [parse-community/parse-server#9282]
### New Issue Checklist

- Cannot find method onLiveQueryEvent in Parse.Cloud typescript

### Issue Description
Maybe it should be there because it's also in the official documentation.
https://docs.parseplatform.org/cloudcode/guide/#onlivequeryevent

<img width="587" alt="Screenshot 2024-08-15 at 14 33 44" src="https://github.com/user-attachments/assets/86f91b00-a9d8-464e-993c-a6aa8480be32">

### Environment
"dependencies": {
    "@parse/push-adapter": "^6.5.0",
    "@types/cors": "^2.8.17",
    "@types/ejs": "^3.1.5",
    "@types/express": "^4.17.21",
    "@types/parse": "^3.0.9",
    "axios": "^1.7.2",
    "cors": "^2.8.5",
    "dotenv": "^16.4.5",
    "ejs": "^3.1.10",
    "express": "^4.19.2",
    "express-ws": "^5.0.2",
    "parse-dashboard": "^5.4.0",
    "parse-server": "^7.2.0",
    "typescript": "^5.5.4"
  },
  "devDependencies": {
    "@types/dotenv": "^8.2.0",
    "@types/node": "^20.14.14",
    "nodemon": "^3.1.4",
    "ts-node": "^10.9.2"
  }

Server
- Parse Server version:  "parse-server": "^7.2.0", "@types/parse": "^3.0.9"

**Comment by mtrezza** [comment]
@types/parse is a 3rd party library; please open an issue there.
