### ISSUE TITLE
Move to ECMAScript ES Module Import statements from require

### ISSUE THREAD

**Issue by R3D347HR4Y** [parse-community/parse-server#9316]
### New Feature / Enhancement Checklist

- Report security issues [confidentially](https://github.com/parse-community/parse-server/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/parse-server/blob/alpha/LICENSE).
- Before posting search [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation

Using require is the old way of coding, most of my code needs to be converted to this crappy syntax when moving to cloud code

### Feature / Enhancement Description

Use import instead of require in the whole project

### Example Use Case

Not having to rewrite code to an old way of doing

### Alternatives / Workarounds

Thanks to @mtrezza here is a workaround:
Creating a main.cjs file in the cloud folder and pointing to it in the Parse Server Config
```js
(async () => {
  await import('./main.js');
})();
```

### 3rd Party References

Litteraly every single big node based project
Would also recommend using hono and deno to get a massive performance boost

**Comment by mtrezza** [comment]
>  I need to require Parse server as a CommonJS file and put anything regarding it in a .cjs

You could "import" (not "require") Parse Server like so:

```
import { ParseServer } from 'parse-server';
```

If you are referring to the Cloud Code file, then this may be a duplicate of https://github.com/parse-community/parse-server/issues/7559?

If you mean something else, then please provide more details and example code to explain the issue.

**Comment by R3D347HR4Y** [comment]
I'm talking of using import and export statements inside cloud code

27 sept. 2024 03:43:14 Manuel ***@***.***>:

**Comment by mtrezza** [comment]
Is this then a duplicate of https://github.com/parse-community/parse-server/issues/7559?

A workaround would be to create a file `main.cjs` and set it in the Parse Server option for `cloud`:

```
(async () => {
  await import('./main.js');
})();
```

The file imports a ESM to make it available via CommonJS. This doesn't require any code rewriting.

**Comment by R3D347HR4Y** [comment]
> Is this then a duplicate of #7559?
> 
> A workaround would be to create a file `main.cjs` and set it in the Parse Server option for `cloud`:
> 
> ```
> (async () => {
>   await import('./main.js');
> })();
> ```
> 
> The file imports a ESM to make it available via CommonJS. This doesn't require any code rewriting.

This works perfectly!
Should absolutely be noted in the doc for cloud code I think, I've been using Parse Server & Cloud Code for 4 years now and I never had such a simple trick to use ES6 Imports in CommonJS environnements

**Comment by mtrezza** [comment]
Closing as duplicate of https://github.com/parse-community/parse-server/issues/7559
