### ISSUE TITLE
Pg-promise is out-of-date

### ISSUE THREAD

**Issue by cbaker6** [parse-community/parse-server#9346]
### New Feature / Enhancement Checklist

- Report security issues [confidentially](https://github.com/parse-community/parse-server/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/parse-server/blob/alpha/LICENSE).
- Before posting search [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation

The dependencies `pg-promise` and `node-postgres` and their respective dependencies are out-of-date.

### Feature / Enhancement Description

Update to the latest versions.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.4.0-alpha.3](https://github.com/parse-community/parse-server/releases/tag/7.4.0-alpha.3)
