### ISSUE TITLE
Upgrade CI to test against Postgis 3.5

### ISSUE THREAD

**Issue by cbaker6** [parse-community/parse-server#9355]
### New Feature / Enhancement Checklist

- Report security issues [confidentially](https://github.com/parse-community/parse-server/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/parse-server/blob/alpha/LICENSE).
- Before posting search [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation

A new [version of Postgis](https://postgis.net/2024/09/PostGIS-3.5.0/) was recently released

### Feature / Enhancement Description

Support latest version

### Example Use Case

N/A

### Alternatives / Workarounds

Test against older versions

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.4.0-alpha.3](https://github.com/parse-community/parse-server/releases/tag/7.4.0-alpha.3)
