### ISSUE TITLE
$hint ended in MongoDB 5.0

### ISSUE THREAD

**Issue by rgunindi** [parse-community/parse-server#9491]
### New Issue Checklist

- Report security issues [confidentially](https://github.com/parse-community/parse-server/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/parse-server/blob/alpha/LICENSE).
- Before posting search [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Issue Description

Using the $hint aggregate stage in MongoDB 5.0 results in the following error:

> ParseError: Invalid aggregate stage 'hint'.
>     at AggregateRouter.transformStage (C:\Users\mypre\parse_projects\own-parse-server\node_modules\parse-server\lib\Routers\AggregateRouter.js:102:13)
>     at C:\Users\mypre\parse_projects\own-parse-server\node_modules\parse-server\lib\Routers\AggregateRouter.js:93:30
>     at Array.map (<anonymous>)
>     at AggregateRouter.getPipeline (C:\Users\mypre\parse_projects\own-parse-server\node_modules\parse-server\lib\Routers\AggregateRouter.js:88:21)
>     at AggregateRouter.handleFind (C:\Users\mypre\parse_projects\own-parse-server\node_modules\parse-server\lib\Routers\AggregateRouter.js:38:40)
>     at C:\Users\mypre\parse_projects\own-parse-server\node_modules\parse-server\lib\Routers\AggregateRouter.js:118:19
>     at C:\Users\mypre\parse_projects\own-parse-server\node_modules\parse-server\lib\PromiseRouter.js:74:20
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
>   code: 102
> }

### Steps to reproduce

Use later than MongoDB 5.0 as the database.
use the parse `distinct `function ex(distinct) [guide](https://docs.parseplatform.org/js/guide/#distinct)

Execute the query through Parse Server.

### Actual Outcome

Proper distinct result!

### Expected Outcome

`{
    "code": 102,
    "error": "Invalid aggregate stage 'hint'."
}`

### Environment

"parse-server": "^7.3.0"

Server
- Parse Server version: "^7.3.0"
- Operating system: Windows OS
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): Local

Database
- System (MongoDB or Postgres): MongoDB
- Database version: MongoDb 7.0 
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): Local or MongoDB Atlas

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): None
- SDK version: None

**Comment by rgunindi** [comment]
parse-server\\lib\\Routers\\AggregateRouter.js

![image](https://github.com/user-attachments/assets/c3339022-4e70-45a6-9e72-f54b6eef3890)

**Comment by mtrezza** [comment]
Don't we have an existing test for $hint? Please post a minimal example of the query that causes that error.

**Comment by rgunindi** [comment]
I made some tests in parse-server but it doesn't give any errors so I don't get it, why am I getting this error in my local project, therefor I'm closing the issue. Thank you.
