### ISSUE TITLE
The “latest” docker tag wasn’t updated with 7.4.0 release 

### ISSUE THREAD

**Issue by cbaker6** [parse-community/parse-server#9506]
### New Issue Checklist

- Report security issues [confidentially](https://github.com/parse-community/parse-server/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/parse-server/blob/alpha/LICENSE).
- Before posting search [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Issue Description

The latest tag in Docker Hub wasn’t updated with the recent `7.4.0` release.

### Steps to reproduce

Release a new version, check docker hub: https://hub.docker.com/r/parseplatform/parse-server/tags

### Actual Outcome

The `latest` tag isn’t updated.

### Expected Outcome

`latest` to update whenever there’s an actual release.

### Environment

Server
- Parse Server version: `7.4.0`
- Operating system: `Linux`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `Docker Hub`

Database
- System (MongoDB or Postgres): `Both`
- Database version: `17.2`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `remote`

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): `N/A`
- SDK version: `N/A`

**Comment by mtrezza** [comment]
The reason for this is a recent issue with the release automation. We currently have no process for re-tagging on docker. The issue will be solved with a future release.
